### ISSUE TITLE
Opensource build scripts

### ISSUE THREAD

**Issue by zyfdegh** [MysteriumNetwork/node#10]
How to build mysterium-node to `*.deb` packages and binaries like `linux_arm`?

Any idea on making those build scripts public?

**Comment by Waldz** [comment]
Yes, we will merge them to this repo later.
Currently not testing of .deb is in progess.

**Comment by Waldz** [comment]
>> packages and binaries like linux_arm?

@zyfdegh ARM binaries and .deb packages are already complied please check https://github.com/MysteriumNetwork/node/releases

**Comment by zyfdegh** [comment]
Oh, that's great!
