### ISSUE TITLE
Bounty Node Tester: NAT Failed - Can't connect (Win10)

### ISSUE THREAD

**Issue by AndriusMyst** [mysteriumnetwork/node#1045]
When user tries to share his bandwidth, it shows that the NAT failed but it is still visible in discovery and from another app. But it's not possible to connect.

Firewall disabled, port forwarding 1194 deleted.

![image](https://user-images.githubusercontent.com/36914062/57457276-e038bc00-7277-11e9-858a-a9a3f154a63b.png)

![image](https://user-images.githubusercontent.com/36914062/57457806-e713fe80-7278-11e9-8411-9299ae90e1b3.png)

**Details:**
MYST ID: 0x9a9faf720dd796e87c1c5e9bb91915bf33542a59
OS: Windows 10
Build: 0.8.0 (2252)-0.7.0
Router: TP-LINK  model TL-WR841N(RU)
Country: RU

NODE logs:
[logs1.zip](https://github.com/mysteriumnetwork/node/files/3162364/logs1.zip)

CONSUMER logs:
[consumer logs.zip](https://github.com/mysteriumnetwork/node/files/3162371/consumer.logs.zip)

**Comment by mjankauskas** [comment]
Need to retest with new build
