### ISSUE TITLE
Bounty Node Tester: NAT Successful - Can't establish the connection

### ISSUE THREAD

**Issue by AndriusMyst** [mysteriumnetwork/node#1046]
Setup:
- User launched node on macOS
- UPnP enabled on router
- FW disabled
- NAT traversal is successful

Problem:
- Node doesn't establish connection

![image](https://user-images.githubusercontent.com/36914062/57475071-45060d80-729c-11e9-9e88-5c5520e5ae4f.png)

About node:
- Telegram name: @yocmen
- ID: 0x8cb5346a50d34bbdecf117305decf200ece01fe4
- Country: Ireland
- OSx mojave 10.14.4 (18E226)
- 0.8.0(2252)-0.7.0
- Router: Virgin Media Hub 3.0

NODE Logs:
[logs (2).zip](https://github.com/mysteriumnetwork/node/files/3163365/logs.2.zip)

CONSUMER logs:
[stdout.log](https://github.com/mysteriumnetwork/node/files/3163367/stdout.log)

**Comment by mjankauskas** [comment]
Need to retest now with new build @AndriusMyst
