### ISSUE TITLE
Fails to update location on mobile

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1053]
05-10 11:09:20.573 16680 16769 I GoLog   : 2019-05-10T08:09:20.572283731 [Error] [location-cache] location update failedfailed to execute request: Get https://testnet-location.mysterium.network/api/v1/location: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

![Screenshot_20190510-111020](https://user-images.githubusercontent.com/13434315/57525454-72ea6100-7333-11e9-861d-115a39347c2c.jpg)

**Comment by zolia** [comment]
So far managed to figure out, that at some point between 0.6.1 release and 0.7-rc0 things got broken. Maybe changes to location structure influenced how mobile app works with it. Need further debugging.

**Comment by ignasbernotas** [comment]
Fixed it with the latest mobile release.
