### ISSUE TITLE
Bounty Node Tester: macOS app Fails to Load on startup

### ISSUE THREAD

**Issue by AndriusMyst** [mysteriumnetwork/node#1055]
DDVS1, [May 10, 2019 at **12:29:17 AM**]:
my node returns allways Fail to Load Client
macOS High sierra
no firewall port 1194 forward

[logs (3).zip](https://github.com/mysteriumnetwork/node/files/3166686/logs.3.zip)

![image](https://user-images.githubusercontent.com/36914062/57531458-31ad7d80-7342-11e9-911f-e74528f42b35.png)

![image](https://user-images.githubusercontent.com/36914062/57531465-35410480-7342-11e9-8294-a30ac67f2381.png)

**Comment by ignasbernotas** [comment]
This may be fixed in the latest release. Need to test it on that users machine.

**Comment by mjankauskas** [comment]
Need to retest with new build, during tests no similar issues were noticed
