### ISSUE TITLE
wireguardctrl has been moved and renamed to wgctrl

### ISSUE THREAD

**Issue by mdlayher** [mysteriumnetwork/node#1060]
Hey folks, I spotted your project on the list of imports for my wireguardctrl project and wanted to reach out to let you know that the project has been moved to the WireGuard org and the main package has been renamed:

https://godoc.org/golang.zx2c4.com/wireguard/wgctrl

It should be fairly easy to update, but feel free to reach out if you run into any issues. Thanks!

**Comment by soffokl** [comment]
@mdlayher thank you for letting us know, we will update it in a short time.
