### ISSUE TITLE
Migrate from debber to nfpm

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#1070]
nfpm is go based, so no need to install ruby on our builder image

**Comment by soffokl** [comment]
We probably will not need to build DEB packaged after https://github.com/mysteriumnetwork/node/issues/1057 resolved. 
Launchpad will build it for us.

**Comment by eugenegoncharuk** [comment]
@soffokl @tadaskay [1057](https://github.com/mysteriumnetwork/node/issues/1057) has been closed. Should it be prioritized?

**Comment by soffokl** [comment]
This is just for local builds, CI builds packages on the launchpad. I don't think this is a priority.

**Comment by chompomonim** [comment]
Can we simply close this tasks? Is it needed at all?
