### ISSUE TITLE
Node system diagnostics

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#1071]
At least for windows, it would be useful to print the following to make debugging easier:
- OS version
- Installed OS updates
- powershell version
- .net framework version
- network adapters

Perhaps implement it as a separate `--diagnostics` flag instead of printing to stdout during startup. We could also move upnp diagnostics (now we debug log upnp devices discovered on the network) to the same place.

**Comment by tadaskay** [comment]
ARM binary for [tty-share](https://github.com/elisescu/tty-share)

[tty-share.zip](https://github.com/mysteriumnetwork/node/files/3421661/tty-share.zip)

Usage: 
```
scp tty-share myst@raspberrypi.local:~
ssh myst@raspberrypi.local
./tty-share
```

**Comment by eugenegoncharuk** [comment]
@tadaskay Is it still relevant? Cause we are using Docker image for installation on Windows.
