### ISSUE TITLE
Report Node version and OS

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/node#1092]
We need to be able to identify which node is running which version so probably it's best to add a new field in proposals. @zolia @Waldz

**Comment by mjankauskas** [comment]
Version + platform maybe?

**Comment by soffokl** [comment]
Why do we need this? 
Disclosed exact version and platform eventually could be used to attack a node provider. 

Maybe it's enough to add proposal protocol version to handle compatibility issues?

**Comment by ignasbernotas** [comment]
Maybe we can store the versions for our own use and have a "secret" endpoint which would return it, or just hide the fields in the public API. I think this is needed for our own needs like debugging connectivity issues. @mjankauskas

**Comment by mjankauskas** [comment]
Report in Metrics somewhere, check with @vkuznecovas what is the best way to do?

**Comment by tadaskay** [comment]
Node version is reported, OS is not. 

Another thing, would it be possible to add these to certain metrics, so we could track some statistics (errors) by node_version/os?

**Comment by soffokl** [comment]
This will be done in the scope of https://github.com/mysteriumnetwork/node/issues/1150.

**Comment by tadaskay** [comment]
@soffokl But from description of it, it only covers it partially. What we lack is ability to slice other metrics by these.

> Another thing, would it be possible to add these to certain metrics, so we could track some statistics (errors) by node_version/os?

**Comment by soffokl** [comment]
@tadaskay yeah, I think it will be possible. Added it to the #1150 as a comment to remember it.
