### ISSUE TITLE
Terms & conditions

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/node#1095]
We need to be able to version and maintain our terms and conditions texts on multiple platforms. Markdown may be the best option in terms of integrations in different languages and easy formatting via GUI tools.

**Comment by tadaskay** [comment]
Saving https://github.com/mysteriumnetwork/terms via [Stackedit.io](https://stackedit.io/) (In browser markdown editor for Github) automatically builds and publishes:
- [Github release](https://github.com/mysteriumnetwork/terms/releases) (for go - `terms-go`)
- [NPM package](https://www.npmjs.com/package/@mysteriumnetwork/terms)

**Comment by tadaskay** [comment]
Need to update node/web ui to use updated terms. Ieva said it's fine for her to use stackedit to update terms directly.
