### ISSUE TITLE
ARM64 build for node

### ISSUE THREAD

**Issue by romainreuillon** [mysteriumnetwork/node#11]
Dear devs,

would it be possible to make and a deb package for arm64 available ? 

The armhf achitecture raises and error when installed on an arm64 ubuntu:

```
root@sleepy:~# sudo dpkg --install mysterium-node_linux_armhf.deb 
dpkg: error processing archive mysterium-node_linux_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
Errors were encountered while processing:
 mysterium-node_linux_armhf.deb
```

cheers,
Romain

**Comment by kytcoin** [comment]
i have the  same message! on my raspberry pi2 last ver. Debian Jessie

**Comment by Waldz** [comment]
Are You guys having external IP for those Raspberries?

**Comment by zolia** [comment]
arm64 support added in #1447
