### ISSUE TITLE
Report node version to QualityOracle 

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#1150]
- [x] Send `app_start` metric to QualityOracle
- [x] `app_start` metric should contain - provider id
- [x] `app_start` metric should contain - service type
- [x] `app_start` metric should contain - node version
- [x] `app_start` metric should contain - OS where it runs

Should use new MORWA to report events to  - https://github.com/mysteriumnetwork/quality-oracle)

**Comment by soffokl** [comment]
We also need to be able to file events like errors by fields like version/os as @tadaskay suggested:
> Another thing, would it be possible to add these to certain metrics, so we could track some statistics (errors) by node_version/os?
