### ISSUE TITLE
Report NAT traversal metrics to QualityOracle

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#1181]
- [ ] DI for NAT mapper
- [ ] DI for NAT proxy
- [ ] Service type to traversal metric field
- [ ] Create new metric DTO for NAT success
- [ ] Create new metric DTO for NAT failure
- [ ] Sign NAT traversal metrics with provider identity

**Comment by chompomonim** [comment]
I believe we already reporting NAT traversal metrics
