### ISSUE TITLE
Easy installation script

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#1198]
It should be easy to install mysterium node at least on linux systems. A single script should be able to set up required dependencies and myst service so that no manual work is needed. This will also save us time to update myst when testing raspberries build.

```bash
curl https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh | bash
```

- [x] Debian https://github.com/mysteriumnetwork/node/pull/1199
- [x] Ubuntu (wireguard installation slightly differs on Ubuntu)
- [x] Other distros (todo list)

Related: #1189 #1190 #1192

**Comment by zolia** [comment]
covered since 0.15.1
