### ISSUE TITLE
Service should not start automatically at startup

### ISSUE THREAD

**Issue by interro** [mysteriumnetwork/node#1223]
Unless Terms & Conditions are accepted.

Latest mystberry release 0.10.0 has "Plug & Play" feature. That means as soon as user starts newly installed mystberry, it automatically runs the service without user consent. This approach assumes that user has read and accepted T&C which he found in the packaging of Raspberry box.
This causes issue, because currently there is no designed way to make sure user accepted printed T&C which found in the packaging of box.
For now it would be simpler to disable "Plug & Play" and ask user to accept T&C before launching service.

**Comment by interro** [comment]
Any thoughts on this @tadaskay @ignasbernotas @Waldz @zolia @AndriusMyst  ?

**Comment by tadaskay** [comment]
@soffokl @vkuznecovas

**Comment by vkuznecovas** [comment]
I think this is pretty much resolved as you can't install the node without accepting terms.
