### ISSUE TITLE
Old (closed) sessions are returned from state endpoint

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#1230]
After running node for a day, there are hundreds of rows in web UI, because closed sessions are also returned from the state endpoint (eventstream):
`http://raspberrypi.local:4449/tequilapi/events/state`

**Comment by Waldz** [comment]
What if You just filter them out by session state?

**Comment by tadaskay** [comment]
Possible, but they are irrelevant to current node state so they should be filtered out in the node itself.

**Comment by eugenegoncharuk** [comment]
@tadaskay Still needed or can be closed?
