### ISSUE TITLE
Wrong total data transferred is reported in testnet dashboard

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#1231]
https://testnet.mysterium.network/node/0x1ad25703e87839cd9b94617e4357c8eed51d5100/openvpn

It shows not total, but total of the last 10 sessions.
Actual total should be several GBs.

**Comment by interro** [comment]
PR [https://github.com/mysteriumnetwork/api/pull/143](url)

**Comment by zolia** [comment]
Fixed.
