### ISSUE TITLE
Endless synchronization

### ISSUE THREAD

**Issue by gandalf12345** [mysteriumnetwork/node#1247]
I install myst node by commands:
sudo dpkg -i myst_linux_amd64.deb
sudo apt-get -f install

When I try to connect from a smartphone, endless connecting occurs and nothing more

My node is 0xbb1439e071f77d96905b934b48da4a14b6e820aa

OS - Ubuntu 16.04 LTS

File log.txt after sudo journalctl -u mysterium-node.service>log.txt

[log.txt](https://github.com/mysteriumnetwork/node/files/3457764/log.txt)

**Comment by tadaskay** [comment]
Are you using the latest mobile version `0.10.0`, released on Jul 23, 2019?

**Comment by gandalf12345** [comment]
I installed the latest version, the same

**Comment by zolia** [comment]
Hello, 

it looks like your application you are testing with is outdated. 
I can tell it from this: 

> received: {"payload":{"proposal_id":1,"config":{"Port":0,"IP":"82.196.7.213"}

Your port should be dynamic (not 0) if you are connecting to node behind router (NAT). 

Please update desktop / mobile application to more recent node version. On google playstore you should get recent enough one for android.

**Comment by zolia** [comment]
installation script for ubuntu 16.04 updated since: 
https://github.com/mysteriumnetwork/node/releases/tag/0.15.1

use this command to install: 

> sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"
