### ISSUE TITLE
Report issue API

### ISSUE THREAD

**Issue by RenatBuga** [mysteriumnetwork/node#1251]
In Menu add an item Send logs. After clicking it, the logs are submitted and the user gets an overlay window with 'Thank you! The logs were received.'

**Comment by tadaskay** [comment]
1. Collect node logs in node
2. Implement `reporter` service to report issues to github
3. Call `reporter` from node to report issues

**Comment by tadaskay** [comment]
https://github.com/mysteriumnetwork/feedback
