### ISSUE TITLE
RPi hangs/crashes after a dozen hours every day. Logs attached.

### ISSUE THREAD

**Issue by RenatBuga** [mysteriumnetwork/node#1267]
[messages.dms.zip](https://github.com/mysteriumnetwork/node/files/3492299/messages.dms.zip)

First day I could not ssh into the pi, but all the lights were up and
blinking. Upon restart I could not believe I had to agree to T&Cs
again and the confirmation on this device was not stored locally
somewhere.  Sometimes the NAT is green, but mostly yellow and red. My
router (Vodafone router) does have UPnP enabled.

Second day I could ssh into the pi after it was reported offline by
mysterium network. Didn't have too much time to go through it, but low
memory and almost no swap was a contributing factor (OOM). I've
increased swap to 2GB on the pi now and we'll see how it goes. Was a
bit baffled how it can have 4 cpu and 1gb of ram only.

**Comment by soffokl** [comment]
Regarding OOM, looks like some memory leak happened in the `myst` process in your case:
![image](https://user-images.githubusercontent.com/8612618/63766125-52e3ab00-c8ec-11e9-8dad-01cca1ce7047.png)
It does not happen to our nodes for running a long time, but we will try to catch the problem to resolve it. 

Regarding the first part, we are working on the persistent configuration saving in the separate task, and it will be resolved there.

**Comment by chompomonim** [comment]
There was already many fixes done after this bug report. Closing as not relevant anymore.
