### ISSUE TITLE
Raspberry Install Fails on ARM64

### ISSUE THREAD

**Issue by joesixpack** [mysteriumnetwork/node#1268]
![image](https://user-images.githubusercontent.com/23145642/62912096-87c3ff80-bd3b-11e9-9272-b11d7a31442e.png)

**Comment by ignasbernotas** [comment]
Hey @joesixpack could you provide the full log for this?

**Comment by joesixpack** [comment]
There is no log AFAIK.

![image](https://user-images.githubusercontent.com/23145642/64508927-7c5ce900-d293-11e9-8502-018dfa33d360.png)

The problem is there's no match for arm64 in the install.sh file.

![image](https://user-images.githubusercontent.com/23145642/64508985-a4e4e300-d293-11e9-86d4-f624f3f06735.png)

**Comment by pvdl** [comment]
See in `install.sh` the function `get_architecture()`
There are basically two command's to determine the architecture. One is primary (`dpkg --print-architecture`), the second one is the fallback (`uname -m`). However these commands have a different output:

In my case (Raspberry Pi 3):
```
pi@raspberrypi:~$ dpkg --print-architecture
armhf
pi@raspberrypi:~$ uname -m
armv7l
```
If the fallback command is chosen in the `download_latest_package()` fucntion, the output 'armv7l' is no hit, so you get the error: "Error: could not determine package to download, aborting"

**Comment by zolia** [comment]
Hello, 

currently we only support raspbian OS for myst node. That means on raspberry our node has 32bit target. Ubuntu you installed is already 64bit arm.  Either install raspbian or try to compile node yourself from sources adding arm64 target. This should not be too hard.

Please refer to this post for more info on platforms: https://stackoverflow.com/questions/37790029/what-is-difference-between-arm64-and-armhf

**Comment by zolia** [comment]
arm64 support added in #1447
