### ISSUE TITLE
RPi Bug - not reentrant:

### ISSUE THREAD

**Issue by Germuxas** [mysteriumnetwork/node#1276]
"Hey Germantas, tried it a couple of days ago on a rpi3+ and i must mention that the script is not reentrant: if it is aborted halfway through for some reason (ie a ctr+c or some other condition) then the apt system is left in an inconsistent state and you’ll need to manually deal with it. ie you’ll have apt complaining that eg package openvpn is not completely installed/uninstalled. Otherwise it works. Suggestions: make the script more bulletproof and add more options, such as install only wireguard, openvpn or both, and also would be nice to have an option to set the default vpn type in the config."

**Comment by RenatBuga** [comment]
NE-17

**Comment by eugenegoncharuk** [comment]
@tadaskay Do You know, if this is still relevant?
