### ISSUE TITLE
Analyse logs unreachable node x0078

### ISSUE THREAD

**Issue by RenatBuga** [mysteriumnetwork/node#1287]
Node ID
0x00782112dc28d0d1dfde4a7b377aa164da66e324

*Report by user:*
Since resetting my router I can confirm UPnP is enabled on my router.
In my port forwarding log, I can see the following entry

Destination     Proto. Port range  Redirect to     Local port
ALL             UDP    44553       192.168.1.189   44553      

192.168.1.189 is the IP for the Mysterium device.
I can also confirm I have a green tick for the NAT status

[log.txt](https://github.com/mysteriumnetwork/node/files/3574848/log.txt)

**Comment by zolia** [comment]
I see sessions are being setup and data being transferred successfully for this node. Closing ticket.
