### ISSUE TITLE
Port forwarding on a router w/o UPnP?

### ISSUE THREAD

**Issue by RenatBuga** [mysteriumnetwork/node#1288]
**Report by the user:**
I have AT&T gigabit fiber internet. They are a giant internet provider located all over the United States.

I have a machine more or less dedicated to running a Mysterium node. I have teamview installed on there if you guys want to check anything out. I have also run the node without teamviewer running, and still have the same problems.

AT&T makes sure their routers do not have UPnP capabilities, as they see it as a security vulnerability.

It seems the node can sometimes, once in a while be running fine, and then I can get 1 connection. This doesn't last that long most of the time.

Usually, though, it seems I am just getting attempted connections.

Please see - https://testnet.mysterium.network/node/0x035740809db0d41aefef1ee5678d1c2df6db03cc/openvpn

What I would like to know is how I can set up port forwarding for this. I had to do this with anything I set up. For example, Storj has ports forwarded for it.

Thanks for your time, and this seems like a pretty simple fix, I just need the necessary information.

sh4rmini  has shipped me the RPIs, and the first couple people I have in mind also have gigabit fiber through the same provider. This could be an ongoing problem that needs to be looked at.

I am here to help, and if you want to log into my computer let me know.

The documentation that is linked directly on the node interface "How to configure NAT manually?" has a tiny part about port forwarding. That did not work, and I was told that usage of that port was deprecated.

![](https://cdn.discordapp.com/attachments/618207162816135169/618294460798730250/unknown.png)

**Comment by cam0sum** [comment]
@RenatBuga I'm also an AT&T customer in the US. I've configured the AT&T Arris router to do an IP Passthrough (Allows the device's public IP address to be assigned to a single LAN client.) to a router (Netgear R8000) that does support UPnP (and is configured to allow it).

Here is what I'm seeing:

2019-10-04T01:04:47.431173045 [Info] [nat/upnp] UPnP gateways detected: 1
2019-10-04T01:04:47.431242461 [Info] [nat/upnp] UPnP gateway detected map[server:Linux/2.6.12, UPnP/1.0, NETGEAR-UPNP/1.0 deviceType:urn:schemas-upnp-org:device:InternetGatewayDevice:1 manufacturer:NETGEAR, Inc. friendlyName:R8000 (Gateway) modelName:R8000 modelNo:R8000]
2019-10-04T01:04:55.265652927 [Warn] [port mapping]  Couldn't add port mapping for port 1194: no UPnP or NAT-PMP router discovered, retrying with permanent lease
2019-10-04T01:04:56.19279456 [Warn] [core/quality] failed to send metric "nat_mapping". event not implemented
2019-10-04T01:04:56.19302614 [Info] [traversal-events-tracker] got NAT event: {port_mapping false no UPnP or NAT-PMP router discovered}
2019-10-04T01:04:56.193143679 [Warn] [port mapping]  Couldn't add port mapping for port 1194: no UPnP or NAT-PMP router discovered

**Comment by zolia** [comment]
Hello, 

@cam0sum, did you manage to resolve this issue?
Can you tell us which version of the node you are using? 
Also, do you see actual port forwarding rule being set up in netgear interface? 
This may be just notification claiming that non-permanent rule addition failed. After such failure node attempts to setup permanent upnp rule (which is supported by most routers). 

Make sure you are using recent release and in case problem is not solved, give us more complete logs.

Antanas

**Comment by cam0sum** [comment]
1. Still haven't resolved the issue.
2. I cloned the repo on 2 October and built from source (because I'm on arm64, no pre-built binary). I don't think that maps to a "version", but I'm not sure how you're handling your release cycles.
3. I have port forwarding being set up by other UpnP clients on my network, but not the node. And the only permanent forwards are the ones I've set up manually.

I can go pull the latest source and try again. The most recent logs attached...
[mysterium_logs.txt](https://github.com/mysteriumnetwork/node/files/3725676/mysterium_logs.txt)

**Comment by zolia** [comment]
Hello, 

thank you for info. 
Would you be able to run service with trace log on, as this: 
> bin/run --log-level=trace --testnet service --agreed-terms-and-conditions 

From current logs I do not see the cause, why upnp is not being setup. Maybe some sort of port clash causes it. Maybe 1194 is used on that router somewhere and we are not getting proper error message? Lets try with dynamic port generation as in above command.

Also, maybe there is issues setting up TCP port forwarding. Have you tried without TCP flag? Usually performance with UDP is much much better.

**Comment by cam0sum** [comment]
Log attached. Command used:

/mnt/git/src/github.com/mysteriumnetwork/node/bin/run --log-level=trace --testnet service --agreed-terms-and-conditions  --openvpn.proto=UDP >> myst_log



[myst_log.txt](https://github.com/mysteriumnetwork/node/files/3790502/myst_log.txt)

**Comment by zolia** [comment]
Hello, 

What I don't see is properly working message-broker. Not sure where it loses its connectivity. 
This statement basically fails:
[NATS.DialogWaiter] Connecting to: {nats/v1 {0x153cc3868e7ec58e56feeb904a6ceff3eb32b1e5.noop [nats://testnet-broker.mysterium.network:4222]}}

Can you try to connect to broker from node host like:

# telnet testnet-broker.mysterium.network 4222

response you should get: 

INFO {"server_id":"5viCxsLAisRm8D24guZfMT","version":"1.0.4","go":"go1.8.3","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576}

**Comment by zolia** [comment]
Closing since there is no response.

**Comment by zolia** [comment]
@cam0sum you can try our build with arm64 support.
arm64 support added in #1447
