### ISSUE TITLE
Expose node control methods through message broker

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1331]
As a 3rd party application developer I want to be able to control my node from my own application: 
 - [ ] get service list 
 - [ ] start service 
 - [ ] stop service
 - [ ] fetch service info

All these commands currently are implemented through TequilAPI as REST endpoints.

List of requirements for such control: 
 - access should be secure, since I will need to access my node from outside networks
    - only authorized owner should be able to issue commands
 - my commands should NOT be visible to other network entities
 - I want to be able to send commands instantly
 - I want to see my command execution status

Proposed solution is to use message broker as a transport for such control commands. 
Message broker can be considered as another binding (apart from REST) to execute TequilAPI methods.

PROS:
   - Implementation can be lightweight (protobuf for messages)
   - Implementation can be decentralized
   - Does not involve 3rd parties for security assurance

CONS:
   -  Application has to register with message broker. In case of  decentralized message broker, application should employ discovery mechanism to find such broker. (can be ignored for current implementation)
   - Control mechanism should not be too verbose as it would produce large amount of messages which might grow uncontrollably. 
   - Messages should be signed and accepted only from authorized owner. That means node should generate an access token for 3rd party application and user would need to copy it manually. Node should use this token to decrypt control messages.

**Comment by chompomonim** [comment]
We discussed this solution heavily and it adds quite a bit of complexion as well as opens security issues.
