### ISSUE TITLE
Create generic way for subscriptions to eventbus

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1339]
Currently there is too much logic in DI. DI should only be dealing with construction and aggregation of components. 

Since many components are starting to have subscriptions to eventbus, we need to find a way to initialize these subscriptions outside of di bootstrapping.

Each component could implement EventSubscriber { SubscribeEvent() } interface. This SubscribeEvent() can be called for each component separately after DI has been constructed.

**Comment by vkuznecovas** [comment]
We've solved this by moving towards having the `.Subscribe(...)` on the components in question.
