### ISSUE TITLE
RFC: collecting node deployments data from 3rd parties

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1345]
# Partner tokens

In order to collect statistics how many nodes different 3rd parties managed to deploy we need some way to identify them. 

Currently we have referral model which lets you generate your own referral code and pass it to registering node owner in hope that he will enter this referral code. This is not a robust solution for partners that a willing to account 100% of their nodes and let us know their contribution to a network. 

We assume that Partner is able to pre-configure nodes with required parameters. 

Suggestion is that we generate unique token for each partner willing to report their nodes to us and request them to submit { node_identity, partner_token } info through their nodes.

We cannot allow them to submit such info directly since they might abuse such system and report nodes that are not theirs. 

Implementation details: 
  - add node parameter / cli command and optionally tequilapi endpoint accepting partner_token 
  - if parameter was set - trigger Partner data submit to mmn portal
  - save  such submit state - we should not allow to re-submit such data. Its one time binding.
  - service receiving Parner data (mmn) should not accept re-submits and should always store the same and only 1 { node_identity, partner_token } binding.

In the future partner token can be used as a way to identify which nodes belongs to Parner and enable him centralized management place through mmn.

# Setting up payout wallet

Currently users or partners willing to receive payments according to bounty rules have to register payout (wallet) address. This can be done either through web-ui of a node, either through CLI interface (using payout command) or using tequilapi REST call through a node: 

https://tequilapi.mysterium.network/#operation/updatePayoutInfo

**Comment by tadaskay** [comment]
> save such submit state - we should not allow to re-submit such data. Its one time binding.
> only 1 { node_identity, partner_token } binding

This will forbid users from switching devices. Identity is not unique to a device. It may be exported by copying data files to another device (some users even requested an easier way to do it).

> tequilapi endpoint accepting partner_token
Is this really necessary? We could simply add a configuration flag (CLI/config) which is easy to configure either at runtime (by call configuration API) or preconfiguration (providing configuration file or node options). We could then append this flag to the metrics/events we already report to grafana or MMN.

**Comment by zolia** [comment]
>>save such submit state - we should not allow to re-submit such data. Its one time binding.
>>only 1 { node_identity, partner_token } binding

>This will forbid users from switching devices. Identity is not unique to a device. It may be >exported by copying data files to another device (some users even requested an easier way to >do it).

In partner case, that's a bonus. Client uses partner configured device and he should NOT move such identity to other device. In case if such identity is move to other means to run a node, that means its no longer parner's identity and we should not assign it to partner. In such case user should create another identity and transfer his tokens.

**Comment by zolia** [comment]
>>tequilapi endpoint accepting partner_token

>Is this really necessary? We could simply add a configuration flag (CLI/config) which is easy to >configure either at runtime (by call configuration API) or preconfiguration (providing ?>configuration file or node options). We could then append this flag to the metrics/events we >already report to grafana or MMN.

Problem here is that we don't know what partners will need. If they were controlling nodes through API they probably will need that too. But I agree, we can start from command line parameters only if it will not be enough we will add another option.

**Comment by zolia** [comment]
>Additionally, any service that needs such information could get it from metrics. I'm not very convinced that we need to submit this directly to certain services, such as MMN in this scenario.

Not sure about publicity of such information. 3rd parties might not be willing to expose such info. 

@tadaskay

**Comment by tadaskay** [comment]
OK, let's add this as a configuration property which we will report to MMN together with the rest of the node information (registration).
