### ISSUE TITLE
Opt in-opt out from unattended upgrades for debs

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1354]
In order for a user to be able to decide if he would want myst debian package to update itself without user intervention we need to introduce additional step during deb installation suggesting to opt out from unattended package upgrades. By default unattended  upgrades should be allowed.

**Comment by eugenegoncharuk** [comment]
@tadaskay Is this still actual?

**Comment by soffokl** [comment]
@eugenegoncharuk yes, this seems to be reasonable. This can be a part of the overall update.
