### ISSUE TITLE
Accepting terms and conditions doesn't work well during deb installation

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/node#1363]
User presses arrow keys to select "OK" but they're printed as control keys in the terminal.
![slika](https://user-images.githubusercontent.com/402965/67402408-38ab0e00-f5b9-11e9-99ae-62af802a42bb.png)
<img width="539" alt="Screenshot 2019-10-23 at 17 16 45" src="https://user-images.githubusercontent.com/402965/67402418-3c3e9500-f5b9-11e9-86f1-626e8fdd0738.png">

**Comment by zolia** [comment]
Which OS it is? I just recently tested for Debian9 and Debian10 and it works as expected.
