### ISSUE TITLE
Wrong Go package names

### ISSUE THREAD

**Issue by 4xx** [mysteriumnetwork/node#14]
-  import "github.com/mysterium/node/***"

+  import "github.com/MysteriumNetwork/node/***"

**Comment by Waldz** [comment]
+1

**Comment by zyfdegh** [comment]
I think the names of Go packages should be lowercase, although the username of this repo is `MysteriumNetwork`.

To solve this, create a directory named `mysterium` manaully under GOPATH, and clone this repo to it.
```sh
mkdir -p $GOPATH/src/github.com/mysterium
git clone github.com/MysteriumNetwork/node $GOPATH/src/github.com/mysterium
```

Or rename an existing directory.
```sh
# rename
$GOPATH/src/github.com/MysteriumNetwork/node
# to
$GOPATH/src/github.com/mysterium/node
```

**Comment by zyfdegh** [comment]
We does need to rename imports from `github.com/mysterium` to `github.com/MysteriumNetwork`

**Comment by Waldz** [comment]
All imports are not `github.com/mysteriumnetwork/node`
