### ISSUE TITLE
Running bare metal on a generic Linux distro

### ISSUE THREAD

**Issue by tarnh** [mysteriumnetwork/node#1405]
I would like to run mysterium under ArchLinux. Bare metal, because I don't believe in Dockerizing.

I've compiled `myst` and now need some help how configure it. Especially what to do with `setDefaultRoute`.

`./node/tequilapi/client/http_client.go:109 >  error="Get http://127.0.0.1:4050/proposals: dial tcp 127.0.0.1:4050: connect: connection refused"`

**Comment by tadaskay** [comment]
```
bin/build && sudo build/myst/myst daemon
```
Should build myst from source and launch a daemon running Tequilapi. You can then interact with it using `myst cli` or builtin web UI (`:4449` by default).

**Comment by tarnh** [comment]
Thanks for the info, I've forgotten to append `daemon`.

But now there is another problem: My login from `https://my.mysterium.network/` does not work at `http://localhost:4449/#/login`

**Comment by tadaskay** [comment]
Local daemon runs independently from MMN and its credentials are only stored locally. You can login using initial credentials `myst:mystberry` and then change it via builtin web UI.

**Comment by eugenegoncharuk** [comment]
Marking this issue as closed, as no answer following from the user @tarnh.
