### ISSUE TITLE
RFC: detect and push system DNS IPs to consumers

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1408]
Currently consumers willing to use providers DNS have to dns-proxy traffic through provider. 
This poses some issues since provider has to run with lifted permissions to run DNS service on port 53. 

Also this rises questions with transparency since consumer is not able to see which actual DNS server is being used.

Proposed model would be to implement parameters for DNS configuration with following defaults:

<pre>
--dns="provider" (default)
--dns="8.8.8.8,1.1.1.1"
--dns="system"
</pre>

For unix type systems we could try getting system DNS'es using: 

github.com/miekg/dns

In case node fails to get DNS'es using this method. We should fall back to some default (i.e.  openDNSes)

Consumer node should check if received DNS IPs are not overlapping with local IPs. In case they do we should fall back to system DNS servers.

## dns setup for traffic slicing 

In order to facilitate traffic slicing DNS requests need to go through node itself. In case node will want to enable traffic slicing it will have to start DNS as a proxy or redirect DNS requests through itself.

To make it more portable it makes sense to start node with DNS server inside on port 53. This can also be done with iptables rules, but limited to Linux only.  

Be default, node should not start DNS server on 53 port, but push its own DNS servers to consumer side. If slicing will be turned on it should start pushing itself or start using iptables redirect rules.

**Comment by tadaskay** [comment]
If `dns=provider` fails, should we try to fallback to `system` and then to `public` or just `public`?
If `dns=system` fails, should we fallback to `public` or error?

* `public` = cf/google/opendns

**Comment by soffokl** [comment]
I don't think we need to have a fallback policy here. 
If the consumer wants to use `provider` DNS, he doesn't want to leak any requests to other servers. We cannot do it transparently for the consumer. It should be explicitly defined that we are passing DNS requests to other servers.

**Comment by zolia** [comment]
@soffokl is right, we should not fall back since that would unexpected for consumer and would result in DNS leaks. 

As for the case we discussed when DNS server for provider is a router or some other LAN device (such as 192.168.0.1). We should not proxy request through node itself as I suggested at first. It would be better to set up an exception to firewall rule to access just that IP in LAN to 53 udp / tcp ports from VPN subnet. That would involve NATting just to that LAN address on macOS and DROP exception on Linux.

**Comment by zolia** [comment]
Regarding DNS leaks @soffokl we would still have them in case provider fails to provide DNS servers. Question is what would be better - provide some public DNS servers, provide some fake non-working ones or fallback to system DNS servers. Either case we cannot be sure that requests will not leak since there might be redundand DNS'es set up on a system.

**Comment by zolia** [comment]
We probably should set-up additional firewall rules to block all traffic from system to 53 port except through tun device.

**Comment by tadaskay** [comment]
After an offline discussion with @soffokl we decided to add `auto` option to the list that would try to use `provider`, but then fallback to `system` or `public`. `provider` option then would be strict: if provider can't provide DNS, connect would fail.
One question about it though: should we add this capability to the proposal? It would allow us to filter proposals client side (if client want's strictly provider's DNS).

**Comment by zolia** [comment]
Lets not modify proposal atm, we can have it as a separate feature later.
