### ISSUE TITLE
Fix accountant_promise_settler error signaling

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#1422]
#1421 introduced the accountant promise settler.

The accountant promise settler needs to be more resilient in allowing the service runner to know when his balance is reaching the "safe" limit. At the moment our smart contracts are not penalizing the provider if he exceeds his allowed balance, but in the future this will not be the case. Current error handling in the accountant promise settler does not allow for proper informing. As this is not crucial for an alpha release, it's being postponed. See `accountant_promise_settler.go` and fix the relevant TODOS.

**Comment by chompomonim** [comment]
Is this still relevant?

**Comment by vkuznecovas** [comment]
Yes it's still relevant

**Comment by zolia** [comment]
I think this has to be done for mainnet.
