### ISSUE TITLE
Better handling of HTTP requests after connected to VPN

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1436]
**Problem**
Currently in our [HTTP clients](https://github.com/mysteriumnetwork/node/blob/master/requests/client.go#L50) with have 20 seconds timeouts and disabled keep alive. The problem is that if consumer connects to slow VPN server it can still get timeouts or connection close errors. Another problem is that we disable keep alive for all cases.

**Proposal**
I propose to implement custom HTTP transport which can close idle connections when connection state changed. We can get this state change by subscribing to our EvenBus.

**Example**
Here is pseudo  implementation which works on my local machine. In my local tests I got much quicker responses and no timeouts or closed connections issues.

```go
// NodeHTTPTransport is a wrapper around http.Transport which can close
// idle connections and do http retries in case of a VPN connection change.
type NodeHTTPTransport struct {
	rt http.RoundTripper
	eventBus EventBus
}

// Subscribe subscribes to connection state event
// and closes idle connections if connection changed.
func (t *NodeHTTPTransport) Subscribe() {
	type closeIdler interface {
		CloseIdleConnections()
	}

	t.Subscribe(StateEventTopic, func(e StateEvent) {
		if connChanged {
			if tr, ok := t.rt.(closeIdler); ok {
				tr.CloseIdleConnections()
			}
		}	
	})
}

// RoundTrip does HTTP request with 1 extra when got timeout or close error.
func (t *NodeHTTPTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	// Handle err here and retry in case it was canceled.
	return t.rt.RoundTrip(req)
}

func main() {
	client := http.Client{
		Timeout:   20 * time.Second,
		Transport: NewNodeHTTPTransport(eventBus),
	}
}
```

**Comment by vkuznecovas** [comment]
I'm all up for this, however one thing you'll need to take into account in the implementation is the state change timing. It might not occur as rapidly as you'd like in some cases(for instance, on connection establishing) as some time is passed before a "connected" event is emitted. Need to check if the events would be sufficient. In case they are not, the timings might need adjustment introduction of completely new ones.

**Comment by soffokl** [comment]
There is a comment in the code, which is almost TODO regarding this:
https://github.com/mysteriumnetwork/node/blob/master/requests/client.go#L48-L49

We just need to make sure it works, and I fully support these changes.

**Comment by zolia** [comment]
This is nice workaround. My concerns are also with this dependency on event. But otherwise - good thinking!
