### ISSUE TITLE
Add guide how to get raspberry node logs via SSH

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1452]
There are cases when node runner can not setup his raspberry and even can not send feedback with attached logs. In such case we can't help user if he can't sent us logs. I propose that we write a guide how to connect via SSH to get logs. This should be straightforward for macOS and Linux to use scp command, but for windows user may need to install Putty which contains pscp.exe tool.

**Comment by chompomonim** [comment]
@etherunit could you create such a guide and post into our new docs project?

**Comment by etherunit** [comment]
@chompomonim will do it.
