### ISSUE TITLE
Push notification to inform that user have to topup 

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1457]
If consumer balance less than 0.01 MYSTT we should throw push notification so he would aware of need of pushing TOPUP button.

**Comment by chompomonim** [comment]
@anjmao what is status of this task?

**Comment by chompomonim** [comment]
This is part of #1505

**Comment by eugenegoncharuk** [comment]
@tadaskay Can we close it or there is a still work to do?

**Comment by chompomonim** [comment]
This is already done in our next version of mobile app.
