### ISSUE TITLE
Empower mobile app to show amount of tokens spend during current session

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1461]
Now we see on mobile app, when session in active we only data (send/received) and time. Would be very valuable to see there also token spent during that session.

I'm aware that there are no possibility on node side to get such data, so it is needed to add such possibility.

**Comment by vkuznecovas** [comment]
This is not really true. Currently, we already have balance calculations, so the app needs to take balance before the session start and compare it to the ongoing balance to get the current session spend.

**Comment by chompomonim** [comment]
A technique you mentioned is exactly one that we could use. Closing this task.

There is still a need to expose some things for WebUI so there would be possible to see how much tokens provider earned during past sessions. I will create a separate task for that, however.
