### ISSUE TITLE
Wireguard static route is left after disconnect

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1470]
After wg disconnect on macos wg static route is not being removed: 

```
 $ netstat -rn | grep 94.237.52.85
94.237.52.85       10.0.88.1          UGHS            1     2295     en0
```

looks like cleanup procedure is prematurely terminated: 

INFO: [userspace-wg]2019/12/20 09:58:31 Device closing
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: TUN reader - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: event worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: receive incoming IPv4 - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: receive incoming IPv6 - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 peer(QKzp…xd0Q) - Stopping...
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 peer(QKzp…xd0Q) - Routine: nonce worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: encryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 peer(QKzp…xd0Q) - Routine: sequential receiver - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: decryption worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 peer(QKzp…xd0Q) - Routine: sequential sender - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
DEBUG: [userspace-wg]2019/12/20 09:58:31 Routine: handshake worker - stopped
INFO: [userspace-wg]2019/12/20 09:58:31 Interface closed
2019-12-20T09:58:31.783 ERR services/wireguard/connection/connection.go:152 > Failed to close wireguard connection error="allocated subnet not found"
2019-12-20T09:58:31.784 INF firewall/noop_vendor.go:46               > Rule for IP: 94.237.52.85 removed
2019-12-20T09:58:31.784 DBG session/pingpong/exchange_message_tracker.go:264 > Stopping...
2019-12-20T09:58:31.784 INF core/connection/manager.go:448           > Connection exited
2019-12-20T09:58:31.784 DBG core/connection/manager.go:497           > onStateChanged called
2019-12-20T09:58:31.784 DBG consumer/statistics/reporter.go:132      > Session statistics reporter stopping
2019-12-20T09:58:31.810 DBG consumer/session/session_storage.go:88   > Session 83f9632f-dc8d-4505-9fb1-8060bb7b24e0 updated
2019-12-20T09:58:31.817 DBG core/location/oracle_resolver.go:41      > Detecting with oracle resolver
2019-12-20T09:58:31.817 INF cmd/di.go:885                            > Reconnecting HTTP clients due to VPN connection state change

**Comment by tadaskay** [comment]
![7338738F-3B39-4A6E-B2E7-B1B81EC8DC3B](https://user-images.githubusercontent.com/4745368/71249536-0ce0a600-2326-11ea-92d4-bcd0b4c0e7b8.jpeg)

**Comment by soffokl** [comment]
Resolved by https://github.com/mysteriumnetwork/node/pull/2309
