### ISSUE TITLE
Running client in docker container

### ISSUE THREAD

**Issue by alimbada** [mysteriumnetwork/node#1487]
I'm looking for a way to run a mysterium client inside a docker container and have other containers route network traffic through that container. It seems possible to run OpenVPN client inside a container (e.g. https://github.com/dperson/openvpn-client) so I'm just looking for the missing pieces to interface with it. I'm thinking of something like this:

mysterium-vpn UI  (local) or CLI/other UI using TequilAPI <---> [inside docker container myst_client <---> OpenVPN client ]

Can someone point me in the right direction as to what this would involve and some tips to go about it?

Thanks in advance.

**Comment by soffokl** [comment]
It's possible to run the mysterium consumer inside a docker container. You can use a standard docker image for that https://hub.docker.com/r/mysteriumnetwork/myst.

`docker run --cap-add NET_ADMIN --name myst mysteriumnetwork/myst --daemon`

Make sure that you are using `--cap-add NET_ADMIN` which is required to provide needed permissions for the docker container.
`--daemon` starts a process ready to serve requests. 

You can use TequilAPI directly to establish a connection or use `myst cli` to run commands from CLI. 

When you will be able to establish a connection from the docker consumer, you will just need to configure the container to work with other containers. 
If you are going to pass traffic through it, you will need to configure NAT forwarding with iptables or install some kind of proxy server inside the docker consumer container.
