### ISSUE TITLE
Use updated docker images on the CI to make sure we are doing correct tests

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#1496]
Now CI runners caching Docker images and never updates. 
Docker images with a `latest` tag could be outdated. 
We need to pull the required image on every run to make sure we are doing correctly tests

**Comment by eugenegoncharuk** [comment]
@soffokl Is this still actual? Can we make a short call about this?

**Comment by soffokl** [comment]
This probably never was fixed. Let's keep it open to make at least check it again.

**Comment by chompomonim** [comment]
@soffokl have you checked this again?

**Comment by soffokl** [comment]
nope
