### ISSUE TITLE
Introduce backoff timer for proposal ping

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1516]
During severe load periods frequent ping updates should be prevented not to downgrade system performance further. Failed ping should kick in a backoff timer. 

Since missing ping will mean that node is unavailable we cannot use exponential backoff.

Currently default PingTimer is 180 sec. 

Suggested backoff calculation: 
  - 1 failed ping ( backoff = PingTimer sec + random(60) sec )
  - 2 subsequently failed pings ( backoff = PingTimer*2 sec + random(120) sec )
  - more than 2 subsequently failed pings ( backoff = PingTimer*3 sec + random(300) sec )

**Comment by Waldz** [comment]
Sounds complicated. 
What is term used here *Failed ping*? Do we have cases of such fails?

**Comment by zolia** [comment]
Most frequently encountered atm is 503 (service unavailable), but i would treat failure condition for all errors > 400

**Comment by anjmao** [comment]
70% of nodes are running 0.18.0 version which means they should already fire events. Is such case there is no need to ping old proposal that often. Let's ping it once per hour and instead listen to proposal-ping events in old discovery and update proposals accordingly.
