### ISSUE TITLE
Add nodeType into mobile proposals

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1521]
- Expose node_type field for proposals inside mobile entrypoint. Some 3th party developers asked simce they filter quality by thos field too.
- Extend consumer CLI to also display node_type residential, datacenter etc.

**Comment by Waldz** [comment]
Service type distinguishes between Wireguard and Openvpn providers. I am successfully using advanced filtering from here:
https://github.com/mysteriumnetwork/node/blob/master/core/discovery/docs.go#L66

And what is defferedNode?

**Comment by anjmao** [comment]
@Waldz It's not service type. node_type has values (residential, data_center) It is needed for some developers who a building their own android app.

**Comment by tadaskay** [comment]
`service_type` and `node_type` are 2 different things, @Waldz is right on this one

**Comment by anjmao** [comment]
Sorry, I update description to be more clear.

**Comment by Waldz** [comment]
I am not sure if we want to implement more filters for API discovery, but rather advance with support of these the way i described

**Comment by anjmao** [comment]
@Waldz Yes we could use this as you suggested. Thanks.

**Comment by chompomonim** [comment]
@anjmao could you comment on status of his issue?

**Comment by anjmao** [comment]
Node type is now addes into mobile node proposals. Could be closed.
