### ISSUE TITLE
Proposals discovery API for consumers

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1524]
## Problem
 Mysterium and other 3th. party developers who are developing client (consumer) side desktop, mobile, cli apps needs to get initial proposals list. Soon after we kill our Python discovery and move to broker there will be no user friendly way to get proposals. Consumer side will need to listen to all proposal events, do filtering only on client side, still will want to access quality data which is centralised. Some apps may decide to support only WireGuard service proposals etc. This will complicate consumer side implementation and good user usability will be hardly possible.

## Proposed solution
Implement our hosted HTTP API service which would allow to fetch proposals based on common use cases. Behind the scene service would have broker subscriber which could listen to proposal events from all providers and do aggregation as needed.

### Requirements
- Allow to filter proposals by various filters like service_type, node_type, provider_id, quality, country. This could be implemented with technologies like GraphQL + MongoDB.
- Paging to limit number of returned proposals. Consumer should not be forced to fetch all proposals at once as it is done in current API.
- Allow to subscribe to proposal change events using server push based model.
- API must be protected by access keys. Only verified developers should get keys in order to call API.
- High availability with at least two API instances running on separate machines.
- API calls could be billed with freemium tier available ?
- Open source?

### Pros
- Developer and user friendly proposals discovery.
- Easily implementable logic for filtering, proposals distribution across different regions, consumers, load.
- Consumers don't need to get all proposals events in which they are not interested. This should also reduces broker load.
- Consumer don't need to fetch extra data like quality metrics separately in order to calculate quality level number.

### Cons
- Centralised service which in theory can be blocked for some consumers in some countries by some ISP providers. But such service can be hosted by other parties too which means that consumer could choose which proposals discovery service to use (the same as with accountant). I will not to be concerned about this issue since it applies to accountant too without which system will not work.

**Comment by tadaskay** [comment]
I suggest not to limit to proposals only. Simply have a BFF for all mobile needs (quality, trust and other services that are not provided p2p, too)

**Comment by chompomonim** [comment]
We have decided to go forward with a similar but slightly different proposal in #1798
