### ISSUE TITLE
Payout endpoint times out

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/node#1533]
![unknown](https://user-images.githubusercontent.com/402965/72629085-4540c780-3958-11ea-9c9c-88ec86e06803.png)

Many people are reporting that this endpoint times out quite often and they're not seeing their wallets in the UI.

Since discovery API is constantly bombarded with requests, maybe we can have a separate tiny service just for settings/KYC storage? I'd love to move this into MMN, but understand why you wouldn't want to do that.

**Comment by etherunit** [comment]
any updates here?

**Comment by chompomonim** [comment]
Please ask for node versions when this happens.

**Comment by chompomonim** [comment]
Will be done with new webUI
