### ISSUE TITLE
After upgrading node into newest version my identity have changes

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1539]
I have upgraded my Linux node (installed from .deb) into newest 0.19.1 (from 0.17.0) version and it's identity have changed.

I do believe that updating node should not touch my private keys and should use same identity. Otherwise all my collected tokens will be lost by simply upgrading software.

**Comment by soffokl** [comment]
Some people also reporting switch from "Verified traffic" to "All traffic". This could be related to the same bug.

**Comment by chompomonim** [comment]
Closing this task as there is no easy way to reproduce. Will open a new one with actual reproduction steps if it will repeat.
