### ISSUE TITLE
Since 0.19 --openvpn.port= is no longer working

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#1542]
A user reported that it's not possible to set static OpenVPN port after recent changes.

**Comment by tadaskay** [comment]
More information would be nice but my guess it’s wrong flag ordering. Flag should be set right after service command.

**Comment by Peter-SovietSquirrel** [comment]
Yes was problem with ordering. This should be reflected on help.mysterium.network as it's advising the incorrect order.

**Comment by tadaskay** [comment]
@ignasbernotas ☝️

**Comment by soffokl** [comment]
`help.mysterium.network` updated.
