### ISSUE TITLE
Make 1 MYSTT = 1 USD --> Make all needed changes in transactor and node

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#1547]
* [x] Node should filter proposals only with wanted price range. #1520 #1570 
* [x] Provider should provide traffic for 0.0005 MYSTT per minute. #1546 
* [x] Transactor should topup 7 MYSTT instead of current default. https://github.com/mysteriumnetwork/transactor/pull/44
* [x] Transactor should give 62 MYSTT during registration of provider. https://github.com/mysteriumnetwork/transactor/pull/44
* [x] Transactor should charge 0.1 MYSTT for registration and 0.03 MYSTT for settlement. https://github.com/mysteriumnetwork/transactor/pull/44
* [x] Recheck that accountant not have some limits on channel stake size (during opening provider's channel)

**Comment by chompomonim** [comment]
To ensure backward compatibility this have to be done after #1520

**Comment by vkuznecovas** [comment]
I've checked the SC - we're only checking for a maximum amount of stake, not a minimum, so we should be good.
