### ISSUE TITLE
Update mingw version for xgo image

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1553]
In order win target to be compilable again, try updating mingw compiler to ver 6 in our xgo image.

**Comment by anjmao** [comment]
@vkuznecovas xgo library is now waiting for you. I did my changes.

**Comment by vkuznecovas** [comment]
Bumped mingw locally, did not help.

**Comment by vkuznecovas** [comment]
New image is up for xgo with fixes for windows:
https://hub.docker.com/layers/mysteriumnetwork/xgo/windows-0.0.1-go-1.13.6/images/sha256-dd84644d68e04de413bd4dadafcbdb40cf67fcdc2cf55a0f1a3d8979794b039c?context=explore

Relevant node changes are made in:
https://github.com/mysteriumnetwork/node/tree/make-windows-great-again

What's missing: wireguard service fails to build on windows.

**Comment by cvl** [comment]
Is it possible to get windows node 0.20.3 this week?

**Comment by tadaskay** [comment]
@vkuznecovas @anjmao Created a separate issue to fix wg windows compilation errors: https://github.com/mysteriumnetwork/node/issues/1818

**Comment by anjmao** [comment]
There is separate branch which works with windows now https://github.com/mysteriumnetwork/xgo/tree/windows-hacks
