### ISSUE TITLE
OpenVPN service failed to start

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1566]
While locally testing a Mysterium Node on a Docker container, encountered that openvpn server is failing to start: 
_core/service/manager.go:154_              > **Service serve failed error="failed to start Openvpn server: failed to create device node: exit status 1"**
Instead of 3 services, 2 are present in MMN dashboard only.

1. Run a command: sudo docker run  --cap-add NET_ADMIN --net default  -p 4449:4449  --name myst  -v "$YOUR_MYSTERIUM_DIR/data:/var/lib/mysterium-node"  -v "$YOUR_MYSTERIUM_DIR/config:/etc/mysterium-node"  mysteriumnetwork/myst service --agreed-terms-and-conditions
2. See in-log data

**Screenshots**
<img width="1248" alt="openvpn fail" src="https://user-images.githubusercontent.com/60128746/72987942-0dbc9a00-3df4-11ea-8ce9-ebe63da5bd7f.png">

**Comment by zolia** [comment]
should be addressed by #1567 
get rid of: 
`-v "$YOUR_MYSTERIUM_DIR/config:/etc/mysterium-node"`
