### ISSUE TITLE
make config.toml backupable

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1567]
Currently, after user changes config through web IU, RPI creates config.toml file and saves it to /etc/mysterium-node

User running myst node in docker is not able to save its last config. Mounting through volume is not an option since in this dir there are necessary pre-distributed files.

Suggestion: move config.toml saving to data dir.

**Comment by soffokl** [comment]
It is possible to mount a single file to the docker container.

**Comment by zolia** [comment]
Yes, but config.toml is created by node itself, thus we cannot mount it apriori.

**Comment by soffokl** [comment]
It is possible to create an empty file and container will be able to modify it: 

`docker run --cap-add NET_ADMIN --mount type=bind,source="$(pwd)"/config.toml,target=/etc/mysterium-node/config.toml mysteriumnetwork/myst daemon`

or just:

`docker run --cap-add NET_ADMIN -v "$(pwd)"/config.toml:/etc/mysterium-node/config.toml mysteriumnetwork/myst daemon`

**Comment by soffokl** [comment]
I'm just worried that it's still user config which is obviously located in the `/etc/mysterium-node` and easy to find for a user. 
Moving it to the `/var/lib/mysterium-node` will mean that the user will never find it at the expected path.
