### ISSUE TITLE
Built .apk to run consumer node on Fire stick

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1568]
Unfortunately `mysteriums.apk` does not work on fire stick because it need play store.
Fire stick is android base but its a skinned diffrrent version of android for tvs not the mobile android. If a app does not need Google play store it will work on a fire-stick.

**Comment by mrhayman12** [comment]
This issue is easily mitigated considering there are custom versions of Android made for the Fire Stick. Check https://forum.xda-developers.com/fire-tv/development for more info.

**Comment by tadaskay** [comment]
@mrhayman12 Could you try APK from one of the latest [releases](https://github.com/mysteriumnetwork/mysterium-vpn-mobile/releases)?
