### ISSUE TITLE
Sometimes session timestamp is not being updated

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1588]
**Describe the bug**
Many providers are seeing 1s sessions (usually from Netherlands) with big about of traffic:
```
Session ID                              Country              Duration        Traffic
31739a19-fdef-4087-8bc2-8ac84fa84afb	Netherlands		1s	     368.94 MB
```

**Expected behavior**
See proper duration in MMN dashboard and WebUI.

**Screenshots**
![1s](https://user-images.githubusercontent.com/153896/73367246-f2500400-42b7-11ea-96bf-4c97bda80ee0.png)

**Environment (please complete the following information):**
 - Node version: 0.19.x
 - OS: raspbian, ubuntu

**Comment by ignasbernotas** [comment]
<img width="312" alt="Screenshot 2020-01-29 at 16 57 49" src="https://user-images.githubusercontent.com/402965/73367669-8326df80-42b8-11ea-8137-e2cb87a0487d.png">

Session created_at and client_updated_at timestamps are identical. Looks like the consumer side isn't updating the session.

**Comment by zolia** [comment]
Analyzed this issue, looks like its a legit traffic with not so well description of duration. Traffic comes from monitoring agent and takes less than 1 min, to be generated. We send statistics once per 1 min first generated statistics entry has these number of MB of data already.

We will update mmn duration description to: "< 1 min" 

@ignasbernotas , can you update this one?

**Comment by chompomonim** [comment]
I have seen many sessions with duration of 3s or 10s. Is this problem related to monitoring agent only? Maybe he is closing connection is some other way than mobile app users?

**Comment by soffokl** [comment]
On the session disconnect, we should send the final stats to make sure we have ended it gracefully. 
https://github.com/mysteriumnetwork/node/blob/master/consumer/statistics/reporter.go#L102

On the other hand, there could be the case when the session stats could not be sent because of the non-gracefull end of the consumer process. But it should be a very rare case.
