### ISSUE TITLE
Proposals structure changes

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1594]
Currently we store quite a lot of duplicate information for each proposal and if we want to add more info like node version it will be duplicated on all proposals. Example.

Node running two services (OpenVPN and WireGuard) publishes two different proposals two broker.

OpenVPN proposal.
```json
{
  "format": "service-proposal/v1",
  "id": 1,
  "payment_method": {
    "duration": 60000000000,
    "price": {
      "amount": 50000,
      "currency": "MYST"
    }
  },
  "payment_method_type": "PER_TIME",
  "provider_contacts": [
    {
      "definition": {
        "broker_addresses": [
          "nats://testnet-broker.mysterium.network:4222"
        ],
        "topic": "0xa46b7659075d46b88b337b7df02b372e0e10d86c.openvpn"
      },
      "type": "nats/v1"
    }
  ],
  "provider_id": "0xa46b7659075d46b88b337b7df02b372e0e10d86c",
  "service_definition": {
    "location": {
      "asn": 45102,
      "city": "Unknown",
      "continent": "AS",
      "country": "CN",
      "isp": "Alibaba",
      "node_type": "hosting"
    },
    "location_originate": {
      "asn": 45102,
      "city": "Unknown",
      "continent": "AS",
      "country": "CN",
      "isp": "Alibaba",
      "node_type": "hosting"
    },
    "protocol": "udp",
    "session_bandwidth": 83886080
  },
  "service_type": "openvpn"
}
```

WireGuard proposal.

```json
{
  "format": "service-proposal/v1",
  "id": 1,
  "payment_method": {
    "price": {
      "amount": 50000,
      "currency": "MYST"
    }
  },
  "payment_method_type": "WG",
  "provider_contacts": [
    {
      "definition": {
        "broker_addresses": [
          "nats://testnet-broker.mysterium.network:4222"
        ],
        "topic": "0xa46b7659075d46b88b337b7df02b372e0e10d86c.wireguard"
      },
      "type": "nats/v1"
    }
  ],
  "provider_id": "0xa46b7659075d46b88b337b7df02b372e0e10d86c",
  "service_definition": {
    "location": {
      "asn": 45102,
      "city": "Unknown",
      "continent": "AS",
      "country": "CN",
      "isp": "Alibaba",
      "node_type": "hosting"
    },
    "location_originate": {
      "asn": 45102,
      "city": "Unknown",
      "continent": "AS",
      "country": "CN",
      "isp": "Alibaba",
      "node_type": "hosting"
    }
  },
  "service_type": "wireguard"
}
```

You can see that there is a lot of common information and some duplicates like location and location_originate.

I propose to merge all provider proposals to single object called `node` and defined it in Protobuf.

```json
  {
    "identity": "0xa46b7659075d46b88b337b7df02b372e0e10d86c",
    "version": "0.20.0",
    "location": {
      "asn": 45102,
      "city": "Unknown",
      "continent": "AS",
      "country": "CN",
      "isp": "Alibaba",
      "node_type": "hosting"
    },
    "discovery": {
      "type": "nats/v1",
      "addresses": ["nats://testnet-broker.mysterium.network:4222"]
    },
    "services": [
      {
        "service_type": "wireguard",
        "payment": {
          "type": "WG",
          "price": {
            "amount": 50000,
            "currency": "MYST"
          }
        }
      },
      {
        "service_type": "openvpn",
        "payment": {
          "duration": 60000000000,
          "type": "PER_TIME",
          "price": {
            "amount": 50000,
            "currency": "MYST"
          }
        }
      }
    ]
  }
```

**Benefits**
1. Smaller structure.
2. Less calls to broker.
3. No need to duplicate common fields.

**Comment by vkuznecovas** [comment]
Also protobuf?

**Comment by chompomonim** [comment]
I like this proposal. I also wold think how to have payments price per type. One can charge X tokens per time + Y tokens per traffic. Currently proposed structure supports only one type of payments.

**Comment by chompomonim** [comment]
Also could we avoid location in proposal? Consumer should anyway recheck it by IP address.

**Comment by anjmao** [comment]
@chompomonim We need location to show country in proposals list. At that point user doesn't have IP yet.

**Comment by chompomonim** [comment]
I understand that. I'm just thinking how we could make such country announcement in proposal more "trustless". Would it be big problem if provider would expose his IP in proposal? That IP anyway is public it we're not doing privacy for stuff for providers. Also it is relatively easy to go over all proposals and get list of their IP. 1s connection would be enough.

**Comment by soffokl** [comment]
We have whitelists for providers, not anyone can walk through all providers.

**Comment by chompomonim** [comment]
Another idea would be signatures whre provider "proofs" his country. And if after connection node is getting different one, that information with "cheating" proofs could be sent to Quality Oracle and rating of such provider should go down.

**Comment by chompomonim** [comment]
> We have whitelists for providers, not anyone can walk through all providers.

This is subject to be changed sooner or later. Nodes with whitelisted traffic may be accessible to all the network.

**Comment by tadaskay** [comment]
```
    {
        "contacts": [
            {
                "definition": {
                    "broker_addresses": [
                        "nats://testnet2-broker.mysterium.network:4222",
                        "nats://testnet2-broker.mysterium.network:4222",
                        "nats://95.216.204.232:4222"
                    ]
                },
                "type": "nats/p2p/v1"
            }
        ],
        "format": "service-proposal/v2",
        "location": {
            "asn": 33363,
            "city": "Florida",
            "continent": "NA",
            "country": "US",
            "ip_type": "residential",
            "isp": "Spectrum"
        },
        "price": {
            "currency": "MYSTT",
            "per_gib": 1250002123419077244,
            "per_hour": 6000000000000000
        },
        "provider_id": "0x023e83a8a52fca2ab252a10a8849e22191630564",
        "service_type": "wireguard"
    }
```

**Comment by cvl** [comment]
Proposals result-set should include metrics as well if fetchMetrics == true.

The result set should be controlled via params, e.g.
- fetch wireguard AND openvpn: /proposals/service_type=wireguard,openvpn. Just wireguard - /proposals/service_type=wireguard
- fetch with metrics /proposals/service_type=wireguard&fetch_metrics=true
- fetch not whitelisting proposals with metrics /proposals/service_type=wireguard&fetch_metrics=true&include_whitelisted=false

**Comment by chompomonim** [comment]
@tadaskay will you have here quality parameters as well? Would be cool to have them in same response.

**Comment by chompomonim** [comment]
@cvl what do you mean by metrics? Quality param?

**Comment by cvl** [comment]
Hmm, not sure the difference. It was called metrics previously, probably it's the same as quality.
It's the result set which were retrieved with fetchMetrics: true previously (e.g. tequilapi.findProposals({ fetchMetrics: true, serviceType: "wireguard" }) )

Metrics result-set returned "connectCount.success", connectCount.fail and connectCount.timetout.

**Comment by chompomonim** [comment]
@tadaskay could you also elaborate a little idea around `definition.broker_addresses`. What is reason to having it there?

**Comment by tadaskay** [comment]
@chompomonim Broker addresses provide means for p2p communication between proposal provider and the potential consumer.

Most recent format:

```
{
        "compatibility": 0,
        "contacts": [
            {
                "definition": {
                    "broker_addresses": [
                        "nats://testnet2-broker.mysterium.network:4222",
                        "nats://testnet2-broker.mysterium.network:4222",
                        "nats://95.216.204.232:4222"
                    ]
                },
                "type": "nats/p2p/v1"
            }
        ],
        "format": "service-proposal/v2",
        "location": {
            "asn": 63473,
            "city": "Lombardy",
            "continent": "EU",
            "country": "IT",
            "ip_type": "hosting",
            "isp": "HostHatch"
        },
        "price": {
            "currency": "MYSTT",
            "per_gib": 220000029504303120,
            "per_hour": 300000000000000
        },
        "provider_id": "0x359cdae6f5ddafc75b4db395b4a9ba0c3f927f29",
        "quality": {
            "bandwidth": 1.7692416000000002,
            "latency": 281.791651,
            "quality": 1.3
        },
        "service_type": "wireguard"
    }
```
