### ISSUE TITLE
Docker host requires additional iptables NAT rule

### ISSUE THREAD

**Issue by ewrogers** [mysteriumnetwork/node#16]
Running `mysterium-node` as a Docker container will cause connected clients to be without WAN access if an additional iptables NAT rule is not specified.

Docker **host** should add the following NAT rule to iptables:
`sudo iptables --table nat -A POSTROUTING -o eth0 -s 10.8.0.0/16 -j MASQUERADE`

(Replace `eth0` with your WAN interface if it differs)

The `mysterium-node` container should then be restarted and connected clients will now have WAN access.

**Comment by KFDCompiled** [comment]
Confirmed that this solution works for nodes behind a firewall. Make sure that there are no lingering docker rules with `sudo iptables -t nat -nvL`

**Comment by Nipol** [comment]
There is something else to report.
Lightsail in AWS will pass static IP incoming connections to private ip, so eth0 will only appear as private IP.
Therefore, the method described here does not apply.
In conclusion, mysterium should be able to work through techniques such as "hole punch".

If you can see it, check the my node connection.
[my node on mvp](https://mvp.mysterium.network/node/dwfq4fiwh7)
