### ISSUE TITLE
Port Forward static Port

### ISSUE THREAD

**Issue by salvo0097** [mysteriumnetwork/node#1608]
Hi, I would run Mysterium Node not using the UPNP router function.

I opened the port 1194 UDP on my router/firewall and online test shows:
Port Open when Mysterium service is running
Port Closed when I stop Mysterium service

I also enabled the UPNP changing the SERVICE_OPTS to standard "openvpn" and it works.

The SERVICE_OPTS string I'm using on /etc/default/mysterium-node is "--openvpn.port=1194 openvpn"

Myst version is 0.20

I did all tests using mysterium mobile app using my mobile connection (so different IP address).

**Comment by anjmao** [comment]
Hi @salvo0097, it's a bit not clear what issue do you experience? Could you please describe how you expect it to work and how it actually works? Thank you.

**Comment by salvo0097** [comment]
The issue Is that I cannot connect to my node Also if I opened the router Port.

**Comment by tadaskay** [comment]
Could you try using a higher port number, e.g. 20300? 
It would also be useful to look at the logs. Can you submit feedback using web UI?

**Comment by salvo0097** [comment]
Yes i tried. 
I sent the summit feedback from web UI some days ago

**Comment by etherunit** [comment]
@salvo0097 I could not locate your report nor identify you in intercom? do you still experiencing the connectivity issues?

**Comment by chompomonim** [comment]
I think this is already solved in recent releases.
