### ISSUE TITLE
Terms and conditions bug

### ISSUE THREAD

**Issue by httpbob** [mysteriumnetwork/node#1609]
Hello,

I have installed a mysterium node on a raspberry pi 4 following this guide:
[https://my.mysterium.network/node-running-guide/raspberry-guide](https://my.mysterium.network/node-running-guide/raspberry-guide)

Then I logged in at the corresponding ip address: 192.168.0.10:4449.
It redirected me to this url: http://192.168.0.10:4449/#/terms, I scrolled down and I cliked on the "Agree and Continue" button.
The  it is stuck there, nothing happens...

![Capture du 2020-02-01 18-55-37](https://user-images.githubusercontent.com/13799713/73596720-051b4080-4525-11ea-86e4-a2e9efd3c725.png)

Please help !!

Thanks

**Comment by anjmao** [comment]
@httpbob Hi, thanks for report. Could you please describe which browser you are using and which OS? If you open Developer Console you should see possible JavaScript errors which may cause this issue.

**Comment by httpbob** [comment]
Hi!
I am using `Google Chrome Version 79.0.3945.130 (Build officiel) (64 bits)`

My OS is the following:
```
❯❯❯❯ lsb_release -a           ~
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

I tool a new screenshot with developper console opened
![Capture du 2020-02-03 18-19-26](https://user-images.githubusercontent.com/13799713/73675027-0037c780-46b2-11ea-9ded-a1c46e168144.png)

**Comment by Peter-SovietSquirrel** [comment]
If you haven't already figured it out already you need to check the box just to the left of the text "By clicking Agree and Continue".

**Comment by httpbob** [comment]
Haaaa, I have not seen the checkbox !

Let's close this :)
