### ISSUE TITLE
Add latest ubuntu distribution support

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1610]
At the moment we're building only for ubuntu `16.04` and `18.04`. Update build script and Launchpad magic so Ubuntu 19.10 would be also supported.

Currently on Ubuntu 19.10 we're getting such error while running install script:
```
wireguard.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.3.0-18-generic/updates/dkms/

depmod...

DKMS: install completed.
Hit:1 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu eoan InRelease
Ign:3 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu eoan InRelease
Hit:4 http://mirrors.digitalocean.com/ubuntu eoan-updates InRelease
Hit:5 http://ppa.launchpad.net/wireguard/wireguard/ubuntu eoan InRelease
Hit:6 http://mirrors.digitalocean.com/ubuntu eoan-backports InRelease
Err:7 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu eoan Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Hit:8 http://security.ubuntu.com/ubuntu eoan-security InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu eoan Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by tadaskay** [comment]
Should we just wait for Ubuntu 20.04 LTS?
Or should we support all of the releases, not only LTS? @chompomonim @soffokl

**Comment by chompomonim** [comment]
People are expecting us to support all of the releases. If that is not complicated, I would go for all Ubuntu releases. This makes life of support people much easier.

**Comment by chompomonim** [comment]
Reopening task because it is still not possible to install myst via our default script on Ubuntu 19.10

`sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"`

**Comment by soffokl** [comment]
Required changes were added to the code. 
To get a new release we need to publish a new release.

**Comment by soffokl** [comment]
> Or should we support all of the releases, not only LTS? @chompomonim @soffokl
@tadaskay I think it will be good to support current LTS versions and the latest one, non-LTS.

**Comment by chompomonim** [comment]
> @tadaskay I think it will be good to support current LTS versions and the latest one, non-LTS.

I agree with that.

**Comment by soffokl** [comment]
After the release, it works with no issue.
