### ISSUE TITLE
Can't report issue from WebUI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1611]
I have tried to report issue via webUI, but got such message:

![Screenshot 2020-02-02 at 13 01 15](https://user-images.githubusercontent.com/153896/73607229-3bf06580-45bc-11ea-9774-6a0928dc207a.png)

**Comment by zolia** [comment]
Usually an error like this means that logging was disabled for a node. To enable logging logging flag has to be set, like this: `--log-dir="/var/log/"`

On docker logging usually it is disabled inside container.  

Opened feature request to make message more informative: #1647
