### ISSUE TITLE
Values not matching between my Dashboard and Network Bounty Leaderboard

### ISSUE THREAD

**Issue by bijomaru78** [mysteriumnetwork/node#1624]
1. Session showing on my local node interface is still going on since 1h 22m with total of 231MB transfer. In the online dashboard it shows as duration under 1 minute and completed, with 205MB transfer.

2. my node shows 651h availability and 15GB transfers this month. Online bounty leaderboard shows me at 450h and 25GB. While the hours may be out of date, it doesn't explain why other nodes have been updated, and some nodes showing as being available for more than the max amount of hours per month, even though we're not even on 31st Jan yet. Just shows that the 150 top list will be played by those appearing online above what is even possible.
![myst_issue1](https://user-images.githubusercontent.com/60647317/73731636-bcd06e00-4730-11ea-9366-7670d631c5a9.png)

Similarly when checking today when my node has been on all the time since 1st Feb, I am showing 84h on my Dashboard, but Bounty Leaderboard only shows 27 hours for me, despite some people shown there at 84 hours.

**Comment by chompomonim** [comment]
NodeUI was recreated from scratch so such issue don't exit there anymore.
