### ISSUE TITLE
Docker node 0.20.3 crashed

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1638]
2020-02-05T05:14:57.328 ERR dns/proxy.go:95 > Error proxying DNS query to 127.0.0.1:53 error="read udp 127.0.0.1:35525->127.0.0.1:53: i/o timeout"
2020-02-05T05:14:59.226 ERR dns/proxy.go:95 > Error proxying DNS query to 127.0.0.1:53 error="read udp 127.0.0.1:35530->127.0.0.1:53: i/o timeout"
2020-02-05T05:15:01.228 ERR dns/proxy.go:95 > Error proxying DNS query to 213.186.33.99:53 error="read udp 5.196.71.224:33785->213.186.33.99:53: i/o timeout"
**panic: runtime error: invalid memory address or nil pointer dereference**
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9c2836]
goroutine 24561 [running]:
github.com/miekg/dns.(*Msg).PackBuffer(0x0, 0x0, 0x0, 0x0, 0xc000ee70e0, 0xc0000c9df0, 0x44f667, 0x0, 0xc0000c9e08)
/go/pkg/mod/github.com/miekg/dns@v1.1.22/msg.go:761 +0x26
github.com/miekg/dns.(*Msg).Pack(...)
/go/pkg/mod/github.com/miekg/dns@v1.1.22/msg.go:754
github.com/miekg/dns.(*response).WriteMsg(0xc000ec2120, 0x0, 0x2c, 0xc00024a760)
/go/pkg/mod/github.com/miekg/dns@v1.1.22/server.go:671 +0x5d
github.com/mysteriumnetwork/node/dns.(*Proxy).proxyHandler.func1(0x1a08620, 0xc000ec2120, 0xc000740f30)
/go/src/github.com/mysteriumnetwork/node/dns/proxy.go:97 +0x215
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc01222e100, 0x1a08620, 0xc000ec2120, 0xc000740f30)
/go/pkg/mod/github.com/miekg/dns@v1.1.22/server.go:37 +0x44
github.com/miekg/dns.(*Server).serveDNS(0xc012130ea0, 0xc0000d1800, 0x2f, 0x200, 0xc000ec2120)
/go/pkg/mod/github.com/miekg/dns@v1.1.22/server.go:609 +0x2e0
github.com/miekg/dns.(*Server).serveUDPPacket(0xc012130ea0, 0xc00024ac34, 0xc0000d1800, 0x2f, 0x200, 0xc000188508, 0xc000e9f260)
/go/pkg/mod/github.com/miekg/dns@v1.1.22/server.go:549 +0xb2
created by github.com/miekg/dns.(*Server).serveUDP
/go/pkg/mod/github.com/miekg/dns@v1.1.22/server.go:479 +0x2ac

His myst node 0.20.3 is running in docker whereas host OS is debian 9 64bit and docker version: 19.03.4
+ unable to send logs 
Couple identities for testing: 
0xc5a82d847ff2c35204fea8e14eb9762b05fb662a
0xb7afcdfa265686b231856f44067197605a14dde0

**Comment by 2mf** [comment]
@etherunit 
Yes, these are actually my nodes. 
You can as well contact my on github, but please remove my email from the posting, since I'm already getting enough spam :-D

**Comment by etherunit** [comment]
@2mf your email has been removed. thanks for your collaboration!

**Comment by 2mf** [comment]
So one node crashed and I'll send the whole log from that node to support.

**Comment by 2mf** [comment]
Yesterday I had 3 crashes with the same error
