### ISSUE TITLE
Node won't stop when running in command line

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#1646]
**Describe the bug**

**To Reproduce**
Open two terminals.

On the first one, run a daemon.
On the second one, run a cli.

On cli start a noop service.
Using another identity connect to the given service.

Return to the daemon, ctrl + c. The node should stop but it doesnt.

**Expected behavior**
Node would stop.

**Environment (please complete the following information):**
 - Node version: bleeding edge
 - OS: mac

**Comment by 2mf** [comment]
Yes I have a similar issue with a node running in docker, where I had to issue 'docker kill myst' to stop the node, so I could update it.

Myst Node version 0.20.2 on Docker 19.03.5 and 19.03.4 on debian 9 64 bit

**Comment by vkuznecovas** [comment]
Update: tried, but could not reproduce this today

**Comment by 2mf** [comment]
I'll keep the log if it happens again.

**Comment by vkuznecovas** [comment]
Please reopen if it happens.
