### ISSUE TITLE
More informative error on WEB-UI when logging is disabled

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1647]
Currently when logging is disabled, all user get after feedback submit is "Opps". Get more informative error like: "logging is disabled, make sure that --log-dir parameter is set to logging directory"

**Comment by chompomonim** [comment]
If myst is installed via `apt` how to set `--log-dir="/var/log/"` params for it? 

I would say the message should also point into documentation or explain how to set that logging directory. O ideally WebUI should allow that.

**Comment by chompomonim** [comment]
Will be done with new webUI
