### ISSUE TITLE
Traffic is being proxied through local proxy even with static port

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1652]
Looks like we broke static port parameter behaviour since last nat-hole punching refactoring. Currently nat-hole punching starts even when static port is specified. This effectively prevents nodes from operating with routers in manula forwarding mode. 

We need to check if static port was specified manually and to not start nat pinger for service which was configured with static port.

this should address an issue described by @2mf in #1576

**Comment by 2mf** [comment]
@soffokl It seems in 0.21 beta it is still not really fixed
```
2020-02-12T14:58:58.413 WRN nat/mapping/port_mapping.go:112          > Couldn't add port mapping for port 1194: retrying with permanent lease error="no UPnP or NAT-PMP router discovered"
2020-02-12T14:58:58.414 WRN nat/mapping/port_mapping.go:115          > Couldn't add port mapping for port 1194 error="no UPnP or NAT-PMP router discovered"
2020-02-12T14:58:58.900 DBG core/ip/resolver.go:103                  > IP detected: 87.128.xx.yy
2020-02-12T14:58:58.900 WRN core/quality/sender.go:203               > Failed to send metric: nat_mapping error="event not implemented"
```

my starting parameter
```
 --openvpn.proto=UDP
 --openvpn.port=1194
 --wireguard.listen.ports=6600:6620
```

Can you add an option to disable the entire NAT-PNP or UPNP discovery mechanism.

**Comment by zolia** [comment]
@2mf can you submit feedback with logs again (with 2mf comment)? Excerpt you posted does not show that manual port forwarding does not work. 

What is your topology? Is node behind a single router (firewall)? 
Does your ISP provide you with public IP? You should see on router interface that ip 87.128.xx.yy is configured.

**Comment by 2mf** [comment]
I have a static public IP which is 87.128.x.y on my dsl router where as the node is running in docker with it's own local lan IP (bridge mode), I'll forward the details in my mail

**Comment by 2mf** [comment]
I've been looking into the code.
`addMapping` routine from `nat/mapping/port_mapping.go` is been called for openvpn even thou there were 0 returns from `discoverGateways` routine in `nat/upnp/discover.go` and I had specified a static port.

To fix this, there should be an additional option to disable port mapping and upnp discovery at once.

```
2020-02-12T16:54:04.723 INF nat/upnp/discover.go:58                  > UPnP gateways detected: 0
```
The result is what I mentioned above.

I would make a pull-request if I would be more into go-lang.

**Comment by soffokl** [comment]
@2mf the current issue are describing bug that was generating you random port when you were trying to specify static one. This is fixed. 

Now if you are setting the static port, this port will be used. 
Port mapping is trying to map exactly this port. 

If you really want to disable this port mapping attempts you can set `--experiment-natpunching=false` option to disable it.
