### ISSUE TITLE
Availability has stopped reporting (in 0.20.3) but node status is online

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1658]
provider: 0x503c70da293b45178d4d2b30934ee622d7ede045
node version: 0.20.3
os: Raspbian GNU/Linux

this provider has upgraded his node software to 0.20.3 and the availability metric stopped working after 72hrs mark (Grafana is showing offline from 2/4).
https://grafana.mysterium.network/d/7r6vlKvZz/super-proxy-provider?orgId=1&var-provider=0x503c70da293b45178d4d2b30934ee622d7ede045&from=now-7d&to=now

but, the node status is showing "Online" in MMN.

provider has shared some pics from his router/upnp settings. he has not changed anything (just updated his node).

<img width="640" alt="Marco_router_settings_with_UPnP_on" src="https://user-images.githubusercontent.com/60128746/73937031-ca325780-48ec-11ea-951e-977233d47646.png">

<img width="882" alt="Screenshot 2020-02-06 at 14 25 46" src="https://user-images.githubusercontent.com/60128746/73936988-aa9b2f00-48ec-11ea-919e-f6280490e523.png">
<img width="640" alt="Marco_myst_config" src="https://user-images.githubusercontent.com/60128746/73937017-c0a8ef80-48ec-11ea-984f-42dbd2710aaf.png">

**Comment by soffokl** [comment]
`openvpn.port=443` should be `--openvpn.port=443`

**Comment by etherunit** [comment]
Response from Marco:
"sadly that doesn’t seem to help. I have the option of setting the port as http, https (each with tcp) or emule with udp. I chose https server. Maybe that’s wrong. I’m not an IT expert, so I really like your approach to make the process easy.
When I started, my logs stated that no UPnP was found, so I enabled UPnP again and explicitly allowed my pi to enable ports.dditionally I tested again to open the pi completely to the internet and disabling the firewall. Even then it cannot get the port connected. The essence seems to be 500 Internal Server Error. It also warns that the ip is not matching the external ip, but is only the network ip. But I don’t know if that’s a problem at all."
[logs_portset_UPnP_on (1).txt](https://github.com/mysteriumnetwork/node/files/4170513/logs_portset_UPnP_on.1.txt)
[logs_portset_UPnP_on.txt](https://github.com/mysteriumnetwork/node/files/4170514/logs_portset_UPnP_on.txt)
[marco_logs_disable_firewall_completely.txt](https://github.com/mysteriumnetwork/node/files/4170516/marco_logs_disable_firewall_completely.txt)

**Comment by soffokl** [comment]
The node is shown as "Test failed" now. The node was never working correctly

This should be resolved with a 0.22 version and new TTL based NAT hole punching.
Please reopen this issue if the new version will not help to make the node "Online".
