### ISSUE TITLE
Node doesn't work on desktop after upgrade to 0.20.3 (mac)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1666]
After upgrading to "mysterium-client-bin": "0.20.3" errors below.
http://127.0.0.1:4050/healthcheck is unreachable.

Error at stderr.log:

�[90m2020-02-07T16:36:43.102�[0m �[1m�[31mERR�[0m�[0m �[1msource/cmd/mysterium_node/mysterium_node.go:58�[0m�[36m >�[0m failed to execute command: �[31merror=�[0m�[31m"accept tcp 127.0.0.1:4050: use of closed network connection"�[0m
�[90m2020-02-07T16:40:12.820�[0m �[1m�[31mERR�[0m�[0m �[1msource/cmd/mysterium_node/mysterium_node.go:52�[0m�[36m >�[0m Failed to create command: �[31merror=�[0m�[31m"$HOME is not defined"�[0m

**Comment by cvl** [comment]
This might help:
Error at stderr.log:

[90m2020-02-07T16:36:43.102[0m [1m[31mERR[0m[0m [1msource/cmd/mysterium_node/mysterium_node.go:58[0m[36m >[0m failed to execute command:  [31merror=[0m[31m"accept tcp 127.0.0.1:4050: use of closed network connection"[0m
[90m2020-02-07T16:40:12.820[0m [1m[31mERR[0m[0m [1msource/cmd/mysterium_node/mysterium_node.go:52[0m[36m >[0m Failed to create command:  [31merror=[0m[31m"$HOME is not defined"[0m

**Comment by chompomonim** [comment]
We do have plans to update our client app to be updated to use the newest node version. We should start working on it in a week or two.

**Comment by cvl** [comment]
- Would it be possible to fix this sooner, as you plan to block the traffic from old node versions since March 1.
- Would it be possible for Mysterium to test node on all environments like mobile, desktop (i.e. not just superproxy) before future releases?

**Comment by chompomonim** [comment]
We're planning to start working on desktop client updates from the next sprint (starting from next Tuesday).

**Comment by cvl** [comment]
Great news, thanks!

**Comment by cvl** [comment]
Is it possible to get mac node 0.20.3 this week?

**Comment by chompomonim** [comment]
Mac node is available all the time, look at [releases](https://github.com/mysteriumnetwork/node/releases). But if you talk about desktop app, then we need at least one more week for that.

**Comment by cvl** [comment]
Okay, thanks

**Comment by chompomonim** [comment]
We're reworking desktop app (track milestone/29). Closing this ticket as node is working on MacOSX and old desktop app is deprecated.
