### ISSUE TITLE
Don't allow consumers who are not supporting payments

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1668]
At the moment our provider node is accepting both paying and free (with version until 0.17.0) consumer apps. After 3 months of testing of the payment system, we should disable support for old (not paying consumer) apps.

**Comment by zolia** [comment]
@chompomonim 3 months counting since when?
Should we disable it since March 1? Since we will base our payouts based on traffic transferred and this would lead to confusion on node runners side.

**Comment by cvl** [comment]
Can you elaborate?
Will Mysterium Network stop working on March 1?

**Comment by zolia** [comment]
@cvl network should NOT stop working, it just gets updated :)
We will try to update all our major products / libraries with recent micro payments support soon.  

As  consumer you will be automatically topped up with tokens on initial identity creation. Later, as a consumer you will be able to top-up tokens in certain intervals.

Those providers that are not updated will not be visible for new consumers. That means that old consumers will be seeing only proposals from old providers until they update themselves.

**Comment by cvl** [comment]
Correct me if I'm wrong, on March 1:
- the network will stop working for desktop apps (until it gets updated to 0.20.3 https://github.com/mysteriumnetwork/node/issues/1666
- it will work for only new users (i.e. new identities) created with the updated node version. So desktop users, who create identities before March 1 will stop working even if they update the app?
- after initially topped up test tokens run out for each identity, those identities will stop working, if payment pool is still not implemented?

I think the timing for this huge change is not the best one, as a) Mysterium will run the blogpost campaign right before this change b) we'll probably have support for this new version on desktop days before the March 1, and we'll very likely not be able to upgrade our apps to support this.

I'd suggest to reconsider the timing and aim for a proper quality roll-out.

**Comment by cvl** [comment]
p.s. I'm lucky I found this issue by accident :)

**Comment by chompomonim** [comment]
> the network will stop working for desktop apps (until it gets updated to 0.20.3 #1666)

No, not correct. After some release in March, clients without payments support will see the only proposals from nodes <= 0.21.x. By our current observation, it takes up to a couple of months for whole network to upgrade into the newest version of the software. This means less choice for older clients, but they still be able to use the network, and they will have time to be upgraded.

> it will work for only new users (i.e. new identities) created with the updated node version. So desktop users, who create identities before March 1 will stop working even if they update the app?

No, not correct. While you're upgrading node software into a new version your old identity is still being used. So there is no need to register a new identity after software upgrade.

> after initially topped up test tokens run out for each identity, those identities will stop working, if payment pool is still not implemented?

Partly correct. After running out of tokens, the client will not get service. But there still will be some API endpoint allowing to topup given identity with more tokens (until pool manager will be not implemented). So when identity will be running out of tokens, it could simply call that endpoint and get a little more test tokens.
