### ISSUE TITLE
Dump firewall and routing table state to logs

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#1670]
In order to debug severe cases of application crashes we need more detailed state of desktop environment.

Such info should be dumped only when log level TRACE or even some dedicated level as "DUMP" has been enabled. 

Information should be written to logs; output of these commands before EACH connect:

[ Linux ]
 
`iptables -L -n`
`iptables -L -n -t nat`
`ip route list`
`ip address list`

[ MacOS ]

`pfctl -s all`
`netstat -rn`
`ifconfig`

[ Windows ]

`ipconfig`
`netstat -d`

**Comment by zolia** [comment]
iptables-save is not universally available package throughout different OS'es. Not sure if we should be relying on it.  Simple `iptables -L -n` + `iptables -L -n -t nat` output should be enough.

**Comment by soffokl** [comment]
Just any output that shows full configuration is ok. For sure for MacOS iptables-save will not work too and we need native tools.

**Comment by tadaskay** [comment]
May I suggest simply dumping it to the logs so that it is picked up for the reporting?
