### ISSUE TITLE
0.20.3 mobile doesn't work

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1676]
on app boot:

E/DeferredNode: Failed to start node
    go.Universe$proxyerror: could not bootstrap dependencies: iptables cmd error: exec: "sudo": executable file not found in $PATH
        at mysterium.Mysterium.newNode(Native Method)

cc: @chompomonim

**Comment by cvl** [comment]
@chompomonim checking, if this fix is under consideration?

**Comment by chompomonim** [comment]
We're actively working on the mobile release. And we will definitely use the newest node version in our public release.

**Comment by cvl** [comment]
Very nice!

Will this be included in 0.20.4?

**Comment by anjmao** [comment]
@cvl It will be included in 0.21.x and in 0.21.0-rc2 (once pipeline finishes https://gitlab.com/mysteriumnetwork/node/pipelines/117590427)
