### ISSUE TITLE
[Android app] VPN stops working abruptly after turning off wifi

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1684]
When connected to VPN & WIFI -> switch off wifi (so cellular connection gets turned on).
The connection stops (perhaps because DNS server cannot be reached or other causes).
VPN app misleadingly stays connected. After 1-2 minutes, the app notification icon turns to "VPN disconnected", yet the built-in "Android System" notification still says VPN is activated. The VPN is actually on (just the notification icon misleads).

cc: @chompomonim

**Comment by chompomonim** [comment]
This is duplicate from #1607
