### ISSUE TITLE
Add byte count on the provider side

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#1686]
Make sure that byte counts are emitted for ongoing sessions.

**Comment by zolia** [comment]
We will need to update consumer side too since we will need configurable reporting frequency. Initially we might assume that reporting every 3 sec. should be enough. Given that payment invoicing frequency is 60 sec. atm. this should yield around 5% discrepancy.

**Comment by zolia** [comment]
Most likely we will need to address this bug too: #1674

**Comment by tadaskay** [comment]
> We will need to update consumer side too since we will need configurable reporting frequency
I suggest opening a separate issue for that
