### ISSUE TITLE
Start / stop different services from WEB-UI

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1690]
Since introduction of NAT hole punching for WG we should be able to manage WG service through web-ui too. 

Currently WG is already started on RPIs by default, but service start / stop manages only openvpn service. 

We might need some layouts for this. @ignasbernotas would you be able to help with this?

**Comment by anjmao** [comment]
Can we make it simple to stop all services on Stop service press? What is the case to stop only once service?

**Comment by zolia** [comment]
It was simply not implemented. Since we don't have stop all services call it was missing from the beginning.

**Comment by anjmao** [comment]
Yes, my idea is just to rename it to Stop Services and stop all services instead of creating new layouts for each service etc., but if it's needed right now when ok.

**Comment by ignasbernotas** [comment]
I agree with @anjmao, we should have Start Services and Stop Services and handle starting/stopping of all services in code even though we don't have that in TequilAPI and will have to do separate calls for each service. Does that sound right to you?

**Comment by ignasbernotas** [comment]
I'll take this one @zolia

**Comment by Waldz** [comment]
How are you planning to get services to start?

According to @etherunit, problem is that users expects this button to work same way as it works after device reboots.
And after reboot services are taken from this config `/etc/default/mysterium/network` and then not respected afterwards.

We need to migrate user's services to `config.toml` as it's highest priority configuration.

**Comment by ignasbernotas** [comment]
Closed with https://github.com/mysteriumnetwork/dvpn-web/pull/89

Second part of the issue as stated in Waldz comment is here #2116
