### ISSUE TITLE
Update documentation for docker

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1694]
In docker related documentation we should describe how to specify a range of ports which we can map and use for NAT pinging. This should fix most of the cases of #1599. 

Also mention in the documentation that docker support in a local network is experimental and may not work in all cases.

**Comment by Waldz** [comment]
```
docker run --cap-add NET_ADMIN -p 24000:24000/udp -p 4449:4449 -v /Users/waldz/.mysterium/keystore:/var/lib/mysterium-node --name myst --rm myst:alpine --experiment-natpunching=false --nat-port-mapping=false service --agreed-terms-and-conditions --openvpn.port=24000
```

**Comment by etherunit** [comment]
https://help.mysterium.network/en/articles/3777670-running-your-node-on-a-docker

**Comment by chompomonim** [comment]
Cool!

Can we also mention wireguard setup? Or wireguard is not supported in our docker images ATM?

**Comment by zolia** [comment]
>  Don't forget to start you container with TCP protocol `--openvpn.proto=tcp`

this should be needed only if you want to test whether your port mapping configuration works. Service itself and port mapping should be run on UDP protocol thus for production 
`--openvpn.proto=tcp` should not be needed.

**Comment by zolia** [comment]
Also, with recent NAT changes there should be no need to run such port mapping configuration at all. Documentation should clearly state that such configuration should only be used if client has strict firewall configuration rules and wants to control all access through firewall.

**Comment by ignasbernotas** [comment]
Instructions added for static port. Will update once another solution is possible.
