### ISSUE TITLE
Scriptable CLI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1702]
At the moment to use CLI user should first run CLI interface (via `myst cli`) and only then run CLI commands. 

This approach has own benefits of having autocomplete and other usability features.

Unfortunately, there are downlisted too. Such CLI is not scriptable (hard to use in automation scripts). Also, people are used to copy-pastable cli documentation when to do something you just follow instructions and copy/pasting commands.

In addition to the current `myst cli` interface, we could expose most commands directly into `myst` as params. e.g. there could be `myst service start ...` or `myst identities list` commands runnable directly from command line.

**Comment by vkuznecovas** [comment]
Is this really necessary? You can already script stuff through tequila.

**Comment by vkuznecovas** [comment]
Just adds complexity.

**Comment by chompomonim** [comment]
> Is this really necessary? You can already script stuff through tequila.

There are couple of downsides to using tequila. 

1. There is a possibility that we will kill tequila API.  
2. Linux admins are not used to writing scripts that are using restful APIs. Admins are using bash scripts.
