### ISSUE TITLE
[Test failed#1] Unable to connect to node

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1720]
**Node id: 0xa3790c694803e46523003dfd69d0d33d7917d4d7**
OS: Ubuntu 19.10
Node version: 0.20.3
IP type: Cellular
_MMN Status: Test failed_
Grafana status: connect_fail (1s, 270B sessions).

Connection with my identity via cli is failing. Trying with NAT hole punching, but returns connectivity timeout.
2020-02-17T11:17:56.205 DBG source/logconfig/openvpnlog.go:63        > [openvpn-proc] Stdout: Mon Feb 17 11:17:56 2020 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2020-02-17T11:17:56.205 DBG source/logconfig/openvpnlog.go:63        > [openvpn-proc] Stdout: Mon Feb 17 11:17:56 2020 TLS Error: TLS handshake failed

<img width="1180" alt="Screenshot 2020-02-17 at 12 17 27" src="https://user-images.githubusercontent.com/60128746/74644802-8b6b8f80-517f-11ea-8251-18bd7ee5c379.png">

<img width="779" alt="Screenshot 2020-02-17 at 12 05 14" src="https://user-images.githubusercontent.com/60128746/74643671-c967b400-517d-11ea-91d5-b142370cf785.png">

Download node logs [here](https://my.mysterium.network/nodes/3126/dashboard).

Other providers with lport=0 and status: Test failed
**Node id: 0x50aaceb4e348e5b5c8078b4e46ea6abd09358ff7** 

update: there are ±40 cellular nodes affected
https://grafana.mysterium.network/d/EyrCp5wWk/cellular-nodes

**Comment by samdave123** [comment]
This was working fine a few weeks ago, the only thing I can think of that's changed is that I upgraded to the latest software version.

**Comment by zolia** [comment]
Issue is here: 

```
Feb 13 14:31:28 samuel-pc myst[682]: 2020-02-13T14:31:28.588 INF nat/mapping/port_mapping.go:120          > Mapped network port: 46174
Feb 13 14:31:29 samuel-pc myst[682]: 2020-02-13T14:31:29.070 DBG core/ip/resolver.go:103                  > IP detected: 94.197.121.XX
Feb 13 14:31:29 samuel-pc myst[682]: 2020-02-13T14:31:29.071 INF nat/event/tracker.go:52                  > Got NAT event event={"stage":"port_mapping","successful":true}
```

a few moments later, we send response to session-create: 

```
Feb 13 14:41:57 samuel-pc myst[682]: 2020-02-13T14:41:57.695 DBG communication/nats/receiver.go:142       > Request "f2e6e6cf-dace-4c56-bc28-90becab0ae9d.session-create" response: {"payload":{"success":true,"message":"","session":{"id":"176d2d56-5d5a-4917-a662-569c9377ecd7","config":{"OriginalRemoteIP":"","OriginalRemotePort":0,"dns_ips":"10.8.0.1","remote":"94.197.120.YYY","port":46174,"lport":0,"protocol":"udp","TLSPresharedKey":"-----BEGIN OpenVPN Static key V1-----
```

We should ALWAYS operate with and send most recently detected public IP.

In this particular case IP have changed multiple times from node startup.

**Comment by samdave123** [comment]
>  In this particular case IP have changed multiple times from node startup.

I guess this is not typical behaviour? Is it because of cellular?

**Comment by etherunit** [comment]
Most likely it is related to that (IP address changes constantly) during reboot and we send request to session creation to the previous IP (the one we detected before change). we hope to fix it within next release

**Comment by anjmao** [comment]
Should be fixed with https://github.com/mysteriumnetwork/node/commit/7e017106f7a6fd3b739360a988da6ae73453651d
