### ISSUE TITLE
 Rework balance calculations after topup

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1724]
Node (consumer) should not just get the balance from an accountant but should watch blockchain for popup events and update his own local state after seeing a popup event.

The only time node should get the balance from an accountant is in case of lost own state.

**Comment by vkuznecovas** [comment]
https://github.com/mysteriumnetwork/accountant/pull/81 < basicly forces this on the consumers

**Comment by vkuznecovas** [comment]
Currently, we're taking the accountants word for the balance. This, however, will soon become inaccurate(see comment above). What needs to be done, is balance needs to be calculated on unlock by querying blockchain for on chain balance and on chain settled and querying local total promised amount. The balance is then = bc.Balance - (totalPromised - bc.Settled)

**Comment by chompomonim** [comment]
Relates to #1869
