### ISSUE TITLE
MYSTT calculation in nodeUI

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1732]
The amount of MYSTT displayed on provider's local server is much higher than on https://my.mysterium.network
Node id: 0x8e2108a73ec3ebce12dd002504b8786796f16db0

<img width="1481" alt="Screenshot 2020-02-18 at 10 10 36" src="https://user-images.githubusercontent.com/60128746/74736905-6e58be80-525c-11ea-9785-b81e011192db.png">
<img width="1359" alt="Screenshot 2020-02-18 at 14 38 51" src="https://user-images.githubusercontent.com/60128746/74736918-76b0f980-525c-11ea-811f-9d79cbfcd503.png">

**Comment by vkuznecovas** [comment]
#1729 fixed this
