### ISSUE TITLE
[Android] Node doesn't work (sometimes) until app relaunch since 0.21.0-rc2

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1742]
Started occurring since 0.21.0-rc2 (also buggy with 0.21.0)
Sometimes node doesn't work until app relaunch (sometimes) although it looks like it's working normally:
- when connecting to good provider nodes, the app doesn't connect to them, but rather immediately disconnects (or doesn't connect without timeout). In my case, I connect to all country's providers (if one fails - connect to another), so I can see that like 20 or I can see that the attempt to connect to those 20 nodes took like 1-2 seconds (whereas the timeout for one node attempt should be like 3s+)
- after relaunching the app (i.e. killing it and starting again) it starts working again.

This happens usually after fresh app install, but not necessary.

My take: something wrong with timeout functionality?

**Comment by anjmao** [comment]
I think I found the issue. I started getting Cancelling connection initiation:  error="invalid protocol: UDP" We are doing validation here https://github.com/mysteriumnetwork/node/blob/master/services/openvpn/config_validator.go#L65
the problem is that we expect protocol to be lowercase.

**Comment by cvl** [comment]
Doesn't reoccur anymore.
