### ISSUE TITLE
Fix time.Sub after device resumes from sleep

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1749]
Time calculations could be wrong when device resumes from sleep. This is important since we are doing payment checks based on time.

References for this issue.
1. https://go.googlesource.com/proposal/+/master/design/12914-monotonic.md
2. https://github.com/golang/go/issues/12914
3. https://github.com/golang/go/issues/23178
4. https://github.com/golang/go/issues/24595
5. https://github.com/golang/go/issues/35012
6. https://github.com/golang/go/issues/36141

WireGuard fixed it by pathing Go. See [here](https://github.com/WireGuard/wireguard-apple/blob/master/wireguard-go-bridge/goruntime-boottime-over-monotonic.diff).

**Comment by zolia** [comment]
is it solved already, can we close it? @anjmao ?
