### ISSUE TITLE
Lowercase OpenVPN port after unmarshal VPNConfig

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1750]
If user sets openvpn port to upper case eg. 'UDP' validation will fail [here](https://github.com/mysteriumnetwork/node/blob/master/services/openvpn/config_validator.go#L64).

After consumer gets config RemotePort could be lowercased since we check it's value in some places eg. [here](https://github.com/mysteriumnetwork/node/blob/master/services/openvpn/client_config.go#L52) .

Also update example [here](https://github.com/mysteriumnetwork/node/blob/master/cmd/commands/cli/command.go#L58).

**Comment by tadaskay** [comment]
I suggest introducing a proper type instead of passing strings around
