### ISSUE TITLE
Terms and conditions does make node operators vulnerable and liable

### ISSUE THREAD

**Issue by 2mf** [mysteriumnetwork/node#1759]
I've been reading the law and cases, especially in germany.

The current terms of mystermium.network would make node operators not only vulnerable but also liable.

The german supreme curt (case I ZR 64/17) made a clear decision on case of a tor exit node operator, that he is not liable in general BUT the person has to prof the traffic was not his/hers and therefor he/she was not responsible for it and 2nd the operator can and possibly will be ordered to prevent certain traffic.

So a node operator has to keep a log of all traffic that originated from the exit node so it can proofed it wasn't the operators traffic and the operator can be ordered to prevent it.

This breaks a couple things in the terms.
e.g.
- not monitor, log and(or) store any information or data which passes through your Node, including connection time stamps, used bandwidth, traffic logs, Users' IP addresses, destinations IP addresses and other communication data, and not disclose such information to a third party;

- respect a net neutrality principle, i.e. not filter, limit, restrict, inhibit or obstruct any communication or types of communication which passes through your Node and treat all data as the same regardless of its kind, source, or destination.

**Comment by chompomonim** [comment]
Thank you for pointing this. We'll analyze what was Tor's decisions according to collecting logs. 

Also, we're working on updates for Terms of Use. Maybe some of your mentioned questions will be already addressed there.

For now, I'm closing this task. Aim for GitHub Issues is to store technical tasks, bugs, and future development ideas.
