### ISSUE TITLE
[Android] if reconnect happens, the AppNotification doesn't catch this, as it's triggered only in SharedViewModel.connect

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1762]
if reconnect happens, the AppNotification doesn't catch this, as it's triggered only in SharedViewModel.connect

So App Notification says the connection is lost, when in fact it's on.

Related to: https://github.com/mysteriumnetwork/node/issues/1607

**Comment by anjmao** [comment]
Hi @cvl  I fixed it in https://github.com/mysteriumnetwork/mysterium-vpn-mobile/pull/184
The problem was that after reconnect new state value is CONNECTING.

**Comment by cvl** [comment]
Perfect, thanks!
