### ISSUE TITLE
Mysterium Node Vps Issue

### ISSUE THREAD

**Issue by z3r0d0n3** [mysteriumnetwork/node#1770]
i tried to run locally the node, it's working fine on debian buster, i rent a vps with exactly same configuration, but there is an issue related to iptables,
a host is not responding, i am attaching bellow two screenshots with the error

![Screenshot from 2020-02-24 19-06-44](https://user-images.githubusercontent.com/56674847/75328466-bdb77400-5886-11ea-9e83-8ecd6ffebdb2.png)

when i try to ping this domain from the error, from my pc, it shows me 100 % but at least it returns an ip

![Screenshot from 2020-02-24 18-59-43](https://user-images.githubusercontent.com/56674847/75328507-d1fb7100-5886-11ea-81ed-eeb644fbc6a1.png)

when i try to ping it from the vps, it says that host is not available

![Screenshot from 2020-02-24 18-59-56](https://user-images.githubusercontent.com/56674847/75328539-de7fc980-5886-11ea-9d1f-e3370aa025b1.png)

**Comment by zolia** [comment]
>when i try to ping it from the vps, it says that host is not available 

looks like DNS server issue on vps. Have you tried replacing dns in /etc/resolv.conf with 8.8.8.8 or 4.4.4.4 ?

**Comment by z3r0d0n3** [comment]
thx, it worked

**Comment by z3r0d0n3** [comment]
the node is working, but i can't see it on the website
also in journal ctl there is an error 
![Screenshot from 2020-02-26 16-52-01](https://user-images.githubusercontent.com/56674847/75356286-6b8f4680-58b8-11ea-8e31-4c21011c023e.png)

> Cannot find device "ifb0"

**Comment by z3r0d0n3** [comment]
and also i have a question, how can i reset the password of a node ?
