### ISSUE TITLE
Show new payout data in identity dashbard

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1776]
* [x] Add graph for token earnings/day and maybe additionally traffic and session time/amount. 
* [x] Show current Leaderbord position for residentials in proper county || Postion in own country for all the rest nodes.
* [ ] Show "last checked time" with small font on the bottom of the status for the last time the agent made a check.
* [x] In MMN show users total MYSTT collected as more important.

**Comment by ignasbernotas** [comment]
Released token earnings chart. Other improvements will come in separate tickets in later sprints.
