### ISSUE TITLE
Send session earnings data into monitoring 

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1779]
Send earning data together with the session's traffic data into discovery service or into monitoring.

**Comment by zolia** [comment]
We need more clarification here. At the end of the session we need to report to metrics service how much that session did cost? How and where this data will be used. It is good to know such things before starting implementation.

And it says "in progress" who is doing this one? @chompomonim ?

**Comment by chompomonim** [comment]
This tada will be shown in MMN in the list of latest sessions. 

<img width="1409" alt="Screenshot 2020-03-13 at 12 50 18" src="https://user-images.githubusercontent.com/153896/76614686-4261ed80-6529-11ea-9aca-7a07d665165f.png">

I would say that sending jus after session end would be not enough. MMN is showing also on-going session, so there users would like to see earnings together with data about sessions time and provided traffic.
