### ISSUE TITLE
using OpenVPN client?

### ISSUE THREAD

**Issue by fnzv** [mysteriumnetwork/node#18]
Hi,
Is it possible to connect to a node using the standard OpenVPN client?

Sami

**Comment by zyfdegh** [comment]
Good question. I think it would be great if it's compatible with OpenVPN.

**Comment by Waldz** [comment]
Yes, it's possible currently, but:
- it's not documented feature.
- we will depreciate it in future

**Comment by krisoul** [comment]
@Waldz So it is avaible now? 

I tried, but failed.

nc test:
```
nc -v <node-ip> 1194
Ncat: Version 6.40 ( http://nmap.org/ncat )
Ncat: Connection refused.
```
I runned a Mysterium node by docker

**Comment by Waldz** [comment]
Using our software is not possible with standard OpenVPN client anymore
