### ISSUE TITLE
Need some kind of check if node is actually from the country it says it is

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1802]
E.g. node 0x5626c78981154c31a100dcdabf183dc0f8f18ff5 says it's from Swiss, but it's actually China (my guess it's a human error when selecting country).

It would be good to have some kind of cron check against IP and their reported countries.

This might be critical in some situations, e.g. if user in China thinks he's using VPN in Swiss, but actually uses VPN in China, and gets busted.

**Comment by chompomonim** [comment]
An exact node provider identity or even better the whole proposal, where Chinese node announced himself as Swiss node, would be very helpful to debug such cases.

**Comment by cvl** [comment]
Could you elaborate on what is the "exact node provider identity"? Isn't myst_id enough?

**Comment by chompomonim** [comment]
myst_id = identitty

**Comment by cvl** [comment]
Is the one provided in the description sufficient?

**Comment by cvl** [comment]
This one sometime says he's from Sweden, sometimes from Germany. 0x3994370e0fe4439a28a008c1d090f869297c0b2a

Maybe he's traveling?

**Comment by chompomonim** [comment]
It is hard to say. Currently, it shows German IP. He can also use proxy on his router...

**Comment by chompomonim** [comment]
It's not really possible to know real exit IP (country) until you connect via node. We may have in the future some kind of checks in quality oracle, to mark nodes which not correctly reporting their country.

**Comment by cvl** [comment]
The first solution could be very simple:
- Have some kind of cron, which connects to all nodes one by one daily and checks a) if it works b) if the IP location is correct

**Comment by cvl** [comment]
don't

**Comment by chompomonim** [comment]
It can be already fixed with new discovery.

@mdomasevicius is our new discovery somehow recheck nodes country? Is country part of proposal send by node or location is actually added by discovery?

**Comment by cvl** [comment]
x

**Comment by portalsnetwork** [comment]
Hi @soffokl 

Has this been resolved?

**Comment by cvl** [comment]
Hi @soffokl

Has this been resolved?

**Comment by chompomonim** [comment]
@soffokl was recently working on this issue and it should be resoled in newest release.
