### ISSUE TITLE
[Mac] After upgrading node to 0.15.0, the app won't quit

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1803]
1. Set node to 0.15.0
2. Connect to node, disconnect
3. Try to quit app -> it won't quit (probably because myst is still running and cannot get killed).

This didn't happen once in 0.14.1

**Comment by anjmao** [comment]
Not sure if we need to support that old node versions as we already have 0.21.0 version.

**Comment by cvl** [comment]
0.21.0 doesn't work, but I can see that you'll have support in one week (https://github.com/mysteriumnetwork/node/issues/1666), so I agree, let's wait.
