### ISSUE TITLE
Connect into my own home node

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1813]
There may be situations when connecting into your own home node is very beneficial (e.g. for security reasons while working from a cafe). 

In such a case, the node should not charge the consumer for using a VPN tunnel and traffic. Also there should be easy way to set "own" consumer identity (e.g. via node's WebUI) and remember home node in desktop and mobile apps.

**Comment by Jayto1** [comment]
This would be awesome

**Comment by AdineVikash** [comment]
Yep, it's awesome!
