### ISSUE TITLE
Test CLI ver 0.22 nodes

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1814]
We should get at least 3 people done this test successfully: 

* [ ] @zolia
* [x] @etherunit
* [ ] @chompomonim

**Comment by etherunit** [comment]
done test with 0x0c21792107eb8581343e2d0b63251fe372f32309, Residential, RPi, 0.22-rc2
connected successfully via OpenVPN & WireGuard
<img width="1484" alt="Screenshot 2020-03-03 at 15 17 53" src="https://user-images.githubusercontent.com/60128746/75779418-3e341400-5d62-11ea-9768-71d5d590e816.png">
