### ISSUE TITLE
Test Mobile app over 0.22

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1815]
We should get at least 5 people done this test successfully:

* [x] @zolia
* [x] @anjmao
* [ ] @chompomonim
* [x] @etherunit
* [x] some one from community

**Comment by etherunit** [comment]
done test with Android phone, Mysterium app version 0.22.0-rc1.1.107045
multiple connection tries failed to: 0x0c21792107eb8581343e2d0b63251fe372f32309 via WireGuard
OpenVPN - connected but internet is not working

**Comment by Peter-SovietSquirrel** [comment]
Tested all available nodes at the time using 0.22.0-rc.107047. The ones stared all function correctly.
nodes 2dbe &2aa6 probably have an issue with iptables.

[https://user-images.githubusercontent.com/60095913/76078801-4dea6d00-5f9b-11ea-8a90-dcab48fa6f33.jpg](url)

**Comment by chompomonim** [comment]
The mobile app is released. Thanks for all your testing.
