### ISSUE TITLE
Data in nottification differers from that in app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1824]
**Describe the bug**
You sometimes have to restart the app for the data counter in the notification bar to catch up with the data counter on the app.

**Screenshots**
![mobile bug](https://user-images.githubusercontent.com/153896/75762492-74ae6680-5d43-11ea-840d-928d63869dd7.png)

**Environment (please complete the following information):**
 - Version: [e.g. 0.22.0-rc1.1]
 - OS: Android

**Comment by anjmao** [comment]
@chompomonim I need more info about this issue as I can't reproduce it and don't see any possible fixes in the code.

1. Does notification bar updates after some time later or it just doesn't change at all?
2. Does this happen after 1 minute of usage as in this example?
3. Is it OpenVPN only?

**Comment by chompomonim** [comment]
Can't reproduce either. Closing for now.
