### ISSUE TITLE
Relicense to LGPL-3.0-or-later

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#1843]
### Rationale

To encourage third-party development based on Mysterium network, we should loosen the license restrictions. As discussed offline with @zolia, this could be LGPL-3.0-or-later - so that developers are free to use it as a library without being forced to license their own product under GPL.

Also, if we want devs using our reference implementation of the desktop client as a quick starter, we should consider licensing it under a permissive license such as MIT, while the SDK could be LGPL.

### Steps

- [x] Confirmation @zolia @chompomonim 
- [ ] Review/replace incompatible dependencies
  - [ ] node
  - [x] mysterium-vpn-js
  - [x] mysterium-vpn2
  - [x] go-ci
  - [ ] go-openvpn
  - [x] node-supervisor
  - [x] go-wondershaper
  - [x] payments
  - [x] metrics
  - [x] payments-smart-contracts
  - [x] feedback
- [ ] Apply license changes (follow https://www.gnu.org/licenses/gpl-howto.en.html - we're not fully compliant with this yet, even in GPL)
  - [ ] node
  - [x] mysterium-vpn-js https://github.com/mysteriumnetwork/mysterium-vpn-js/pull/32
  - [x] mysterium-vpn2 https://github.com/mysteriumnetwork/mysterium-vpn2/commit/56f8b7a4d9dd35e22c95993d9e394b860edb5db8
  - [x] go-ci
  - [x] go-openvpn https://github.com/mysteriumnetwork/go-openvpn/pull/60
  - [x] node-supervisor
  - [x] go-wondershaper
  - [x] payments
  - [x] metrics
  - [x] feedback

- [ ] Add licence for our OpenVPN package

**Comment by chompomonim** [comment]
`payments-smart-contracts` is not used in our software in any way and are just deployed into blockchain. So having there GPL is totally fine.

**Comment by chompomonim** [comment]
I suggest having such licencing in the following repos:
- `node`: LGPLv3
- `mysterium-vpn-js`: MIT
- `go-ci`: MIT
- `go-openvpn`: LGPL
- `node-supervisor`: MIT
- `go-wondershaper`: MIT
- `payments `: MIT
- `metrics`: MIT
- `payments-smart-contracts`: GPL
- `feedback`: MIT

**Comment by tadaskay** [comment]
Just to make sure - are you proposing `LGPL-3.0-or-later` both for node and go-openvpn?

**Comment by chompomonim** [comment]
Why "or-later" part is important for you?

**Comment by tadaskay** [comment]
More importantly, why are licenses different for node and go-openvpn? `or-later` is a recommendation from GNU for specificity and future compatibility.
