### ISSUE TITLE
Event-stream API for consumer state

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#1844]
### Rationale

1. Lots of polling needed to get the current state
2. Lots of redundant endpoints (connection/ip, connection/location, etc)

### Suggestion

Implement event-stream based API, similar to the one we have for the provider mode (`/events/state`). We might re-use existing https://github.com/mysteriumnetwork/node/blob/master/core/state/state.go#L56 by adding consumer state to it.

**Comment by tadaskay** [comment]
We could also consider graphql: it supports queries and subscriptions using the same model. I think it would fit our use case perfectly.

**Comment by chompomonim** [comment]
Let's do it in a similar way as event-streaming for providers. GraphQL is good idea, but it is expensive to rewrite all tequila and related packages that are using it. And supporting two different APIs doesn't sound as proper solution.
