### ISSUE TITLE
MysteriumVPN app keep showing connected after openvpn process stopped

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1859]
1. Launched docker node 0.22.1 > docker run --cap-add NET_ADMIN -p 4449:4449 -p 25007:25007/udp --rm --name myst -v ~/.mysterium/keystore:/var/lib/mysterium-node mysteriumnetwork/myst --experiment-natpunching=false service --agreed-terms-and-conditions --openvpn.port=25007
2. Successfully connected via mobile MysteriumVPN app to this node.
3. Stopped node and all services
4. Mobile app is still showing that I am connected (this not changed even if I have disabled wifi connection).

As a consumer, I expect to see Disconnected status in mobile app screen once node goes offline or I am disconnected from wifi network.

**Comment by anjmao** [comment]
This issue impacts all consumers, not only mobile. It could be fixed with https://github.com/mysteriumnetwork/node/issues/1713 probably.

**Comment by chompomonim** [comment]
There are no known consumer applications who're using OpenVPN at this moment. It is deprecated service.
