### ISSUE TITLE
[Android] Sometimes node jumps into forever cycle of connecting to bad node

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1861]
In most cases it just times out or is rejected.
In some cases, it "freezes" in a forever cycle of attempts without returning error.

E.g. provider node: 0x50c88b26d0be1996253b956d883e1e771f1ad095

Logs (note, I've obfuscated the IP for privacy reasons):
E/GoLog: [90m2020-03-09T17:04:05.000[0m [32mINF[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/mobile/mysterium/openvpn_connection_setup.go:218[0m[36m >[0m Openvpn log: Server poll timeout, trying next remote entry...
E/GoLog: [90m2020-03-09T17:04:05.000[0m [32mINF[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/mobile/mysterium/openvpn_connection_setup.go:213[0m[36m >[0m Unhandled event: {Fatal:false Error:false Name:RECONNECTING Info:}
E/GoLog: [90m2020-03-09T17:04:05.000[0m [32mINF[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/mobile/mysterium/openvpn_connection_setup.go:218[0m[36m >[0m Openvpn log: Contacting 123.123.123.123:1194 via UDP
    [90m2020-03-09T17:04:05.000[0m [32mINF[0m [1mext-go/1/src/github.com/mysteriumnetwork/node/mobile/mysterium/openvpn_connection_setup.go:213[0m[36m >[0m Unhandled event: {Fatal:false Error:false Name:WAIT Info:}

**Comment by cvl** [comment]
Note, that connection attempt cycles forever and it never throws an error.

**Comment by cvl** [comment]
cc: @anjmao @chompomonim

**Comment by cvl** [comment]
Another provider with the same issue: 0x01ebced2ea25fa383e0d31f2797267fc93b83683

This didn't happen before.

**Comment by anjmao** [comment]
0x50c88b26d0be1996253b956d883e1e771f1ad095 is offline.
0x01ebced2ea25fa383e0d31f2797267fc93b83683 works for me.

**Comment by chompomonim** [comment]
What is node version you see this habit on?

**Comment by cvl** [comment]
0.21.0

**Comment by cvl** [comment]
I'll try to reproduce on 0.22.2 if I won't be able to, we can close this.

**Comment by cvl** [comment]
0.22.2 is much better than 0.21.0 so far

**Comment by cvl** [comment]
Looks like this is fixed in 0.22.2 although some providers still take a long time to fail when trying to NAT hole punch, e.g.: 0x464ad2d2347b89126fb5523e43945eac79406c5b
