### ISSUE TITLE
Better UX in node runner dashboard (better payments calculations)

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1864]
Du to specifics of our payment protocol, nodes are not charging during first minute of connection. So our monitoring agent is not paying nodes, because he is connecting for not longer that 1 minute.

People are looking for an aggregated Gb number on their dashboard. Trying to do math and it doesn't work for them. We have to fix that somehow (I mean UX in the dashboard).

One thing which may help is showing earned token amount for each session. And then showing sum on top of that sessions list. 

Let's discuss more ideas here.

**Comment by diabloblack** [comment]
Totalling the MYSTT earned per session makes perfect sense and would seperate the monitoring agent from regular connections. Monitoring agent and other <1min connection could be made more identifyable by using a different colour or adding an asterix. Another option would be to not display a session at all until it has reached the 1min mark.
