### ISSUE TITLE
Proposal search / filter

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1871]
We do have a lot of nodes already so it may be hard to choose in some cases. Proposals filter should help to filter wanted exit node.

Filter by:
- [x] country
- [x] IP type (residential/DC)
- [x] connectivity (connectable/all nodes - according to monitoring agent)
- [x] quality (bars)
- [x] price

**Comment by tadaskay** [comment]
@chompomonim Let's remove bandwidth and connectivity because there's no way to reliably test all network nodes. Per discussion with @soffokl :

> bandwidth is measured by monitoring agent, this is temporary solution, we will not be able to monitor whole network when it will be big enough
> and bandwidth is highly depend not only on provider, but on consumer too. I suggest not to show any numbers in the app, because it will not be correct, and people will complain about it.

and regarding connectivity:

> this is almost the same, if monitoring agent was able to connect to the node it doesn’t mean that user will be able.

> we have stats about successful/failed connections to the providers https://quality.mysterium.network/api/v1/providers/sessions
this is probably the best option to visualize provider reliability.

**Comment by chompomonim** [comment]
Deleted bandwidth from requirements.

**Comment by tadaskay** [comment]
@chompomonim why only bandwidth?

**Comment by chompomonim** [comment]
I still do think that we should have switcher which would help to filter out not connectable by monitoring agent nodes. If someone would like to see who list, he would just switch off such filter.

**Comment by tadaskay** [comment]
Connectivity filter added in df33a1a6602f49afce919c80df1566b786c71b1b
