### ISSUE TITLE
Desktop app for Linux

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1876]
Our initial version of desktop app (#1734) will support only MacOSX. Because we're using cross-platform [nodegui](https://github.com/nodegui/nodegui) library, adding Linux desktop support should be relatively easy task to do. But some tweaks will be still needed.

Also on Linux we could additionally introduce provider mode.

**Comment by mdomasevicius** [comment]
- [ ] Implement node_supervisor for linux arch
