### ISSUE TITLE
Any version greater than 0.21.1 fails to load using Docker

### ISSUE THREAD

**Issue by christoefar** [mysteriumnetwork/node#1877]
When I update Mysterium past version 0.21.1 it fails to start correctly, I have attached a full log from the console but it looks to me to be related to iptables and/or the ipset command. 

[myst.txt](https://github.com/mysteriumnetwork/node/files/4319213/myst.txt)

`[90m2020-03-11T15:41:15.255[0m [31mWRN[0m [1mfirewall/incoming_firewall_iptables.go:62[0m[36m >[0m Error deleting ipset table. [31merror=[0m[31m"ipset cmd error: \"sudo ipset destroy myst-provider-dst-whitelist\": exit status 1 output: ipset v6.32: Kernel error received: Invalid argument\n"
`

`
[90m2020-03-11T15:41:15.265[0m [1m[31mERR[0m[0m [1mcmd/mysterium_node/mysterium_node.go:58 [0m[36m >[0m Failed to execute command: [31merror=[0m[31m"ipset cmd error: \"sudo ipset create myst-provider-dst-whitelist hash:ip --timeout 86400\": exit status 1 output: ipset v6.32: Kernel error received: Invalid argument\n"
`

 - OS: unRAID 6.8.0
 - Docker: If I use the :latest tag it doesn't work, so I have to force :0.21.1-alpine to get the node up and running.

**Comment by pwnorbpwnd** [comment]
Can also confirm the same error and "workaround" on Unraid 6.8.3(Docker v19.03.5).

**Comment by zolia** [comment]
Hello, 

I am not familiar with this OS, but from the error it looks like linux kernel does not have proper ipset support. Most likely ipset kernel module is missing. Try loading ipset module for the kernel or build a custom one compiling it in.

**Comment by christoefar** [comment]
Thanks both for you suggestions.

@pwnorbpwnd I can confirm that with the latest version of unRAID (6.8.3) I get the same problem.

@zolia This would seem to make sense, unRAID has quite a conservative kernel. I will try and get the kernel module loaded and see how I get on.

Thanks again.

**Comment by robweighill** [comment]
Has anyone found a solution to this issue yet? I am still having to run 0.21.1 on my UnRaid docker.

**Comment by christoefar** [comment]
@robweighill since my knowledge on the Linux Kernel is very limited I contacted UnRaid.

They have said the ipset kernel modules can be included in the 6.9 release.

This is going to be a while though, since they only have beta1 available, which is essentially the same as 6.8.3 but with the latest kernel.

**Comment by robweighill** [comment]
@christoefar Thanks for letting me know. I went into a very short lived rabbit hole of trying to add the module myself but decided it wasn't worth breaking my server for. I will look forward to 6.9.

**Comment by soffokl** [comment]
Maybe we should change this issue to make `ipset` optional? It's not required to have it now. We can add a flag or option to use service without it.

**Comment by christoefar** [comment]
@soffokl yeah if that is possible it would be great. I did a very similar thing to @robweighill where I spent hours try to figure it out, it's just a little of of reach for me.

**Comment by soffokl** [comment]
Required changes are added it will be included in the next release version.
