### ISSUE TITLE
Container restart over and over

### ISSUE THREAD

**Issue by NeverVane** [mysteriumnetwork/node#1885]
**Describe the bug**
The container is restarting over and over resulting online for a few seconds.
Looking at "docker stats" I can see the container loading in the memory and then freeing the memory, over and over.

**To Reproduce**
Unfortunately I can't precisely tell how to reproduce it, since I have some containers running and some no, without an evident reason.

**Expected behavior**
Start & Run

**Screenshots**

![container_restartting](https://user-images.githubusercontent.com/40278940/76681562-98e82e00-65f4-11ea-8d89-78a9cb16c338.gif)

**Environment :**
 - OS: Ubuntu 18.04
 - Docker: 0.22.2 & 0.22.3

**Comment by soffokl** [comment]
@NeverVane could you provide logs from the container? It's required to find a reason for the restarts. 

You can get it with a `docker logs v222-72-84`

`v222-72-84` is a container name if I can read it correctly.

**Comment by NeverVane** [comment]
The log exceed 50MB and I can't upload here on GitHub, how do you prefer me to send it?

**Comment by soffokl** [comment]
Compress it or post only last lines with errors and problems.

**Comment by NeverVane** [comment]
Here we go
[containerRestarting.log.zip](https://github.com/mysteriumnetwork/node/files/4332864/containerRestarting.log.zip)

**Comment by NeverVane** [comment]
Also, before switching to 0.22.2 and 0.22.3, I had no problem with containers

**Comment by soffokl** [comment]
Error is the following:
```
[90m2020-03-14T13:26:14.440[0m [1m[31mERR[0m[0m [1mcmd/mysterium_node/mysterium_node.go:58 [0m[36m >[0m Failed to execute command:  [31merror=[0m[31m"unknown service type: \"openvpn.port=1194\""[0m
```
Looks like you are passing some arguments incorrectly: `openvpn.port=1194`

@NeverVane could you share how do you running this container?

**Comment by NeverVane** [comment]
Oh man, on some containers I have lost "--" in front of openvpn.port
Embarrassing :/
