### ISSUE TITLE
Noop transport report data transferred stats

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#1892]
Noop connection does report some transferred traffic: 
```
Data Sent / Received 
1.83 MB / 25.72 MB
```
 
https://testnet.mysterium.network/session/971e085a-c490-4fe7-8999-a3c0472e7b6f

`session_id="971e085a-c490-4fe7-8999-a3c0472e7b6f"`
`provider_id="0x6d312f8d0ff90a3863b455d87fcc0776077dc43a"`

But stats metrics show the session correct with zero traffic.

![image](https://user-images.githubusercontent.com/8612618/76849734-2d11f980-6870-11ea-9c1d-1b1490e8f167.png)

Noop transport should not report any traffic. We are counting it incorrectly somewhere.

**Comment by creotiv** [comment]
is this still relevant?
