### ISSUE TITLE
Which ports are used by nodes?

### ISSUE THREAD

**Issue by eshavkun** [MysteriumNetwork/node#19]
Hi,

I need to setup port forwarding so my node (which is behind router) can be discovered and used. Unfortunatelly I couldn't find any information regarding which port(s) are used. So far I set up forwarding for 1194 (which I saw in docker setup). Is it enough or I need to have more (e.g. I saw that node is listening on 123)? Thank you!

**Comment by Waldz** [comment]
Node is using only port 1194/udp (whitelist 1194/tcp also).
But I guess where is more - need to configure proper NATing for internet packets.
In future we will fix usability of nodes behind router, but now we just dont concentrate here.

**Comment by eshavkun** [comment]
Hmmm, so there is no known workaround? It really complicates MVP participation for me :(
Anyway, here are some details I found recently after finishing of node and client setups (on different machines) with only 1194 port forwarding enabled:

- Client is able to connect to node (both node and client logs confirm this)
- I cannot reach the Internet from client once it is connected
- Once in while there is error in client logs saying that packet failed (I can paste exact message later today)

My guess is that some messages from server to client are not getting through. But I'm not sure how to confirm this
Is there anything I can do to investigate further and narrow down to root cause?

**Comment by eshavkun** [comment]
Ok, I solved it. Indeed forwarding 1194 port seems enough. My issue was that ip4 forwarding needed to be set up on the node machine. I guess issue can be closed...
