### ISSUE TITLE
Node runners stopped receiving email notifications

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1911]
Below node runners are complaining that they have stopped receiving email notifications (once their node goes offline) during last weeks.
Reports from:

- Email: sneakybrit@msn.com
- Node identity: 0xded999ecee526da0965d6e28608dbc894e5fce20

- Email: jason@ncg.me.uk
- Node identity: 0xe7747dcc06db552de3f4e3d62637cb5018db3b8c

We need to check what is wrong there to ensure that they will get all notifies further.
<img width="745" alt="Screenshot 2020-03-24 at 16 07 26" src="https://user-images.githubusercontent.com/60128746/77434478-99997500-6de9-11ea-81e3-c05111eeddb7.png">

**Comment by chompomonim** [comment]
@etherunit is this still there? Could you confirm that issue is fixed?

**Comment by etherunit** [comment]
the issue has been fixed (also made a test to ensure it works on my nodes going offline/test failed).
