### ISSUE TITLE
Desktop app should not run in provider mode

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1939]
Our desktop apps are in consumer only mode. To ensure that, have to pass `--mymysterium.enabled=false` and `--ui.enable=false` flags. Otherwise, WebUI will be still accessible and MMN will show a possibility to add node into its dashboard.

**Comment by cvl** [comment]
`[Portals Priority 20/100]`

**Comment by tadaskay** [comment]
Fixed in https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/c2e4848e0eee55d9df70a90a41e6ff3b6e5b73d3
