### ISSUE TITLE
Bandwidth limit seems to work only for OpenVPN, but does not work for Wireguard

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#1956]
Example node ID: 0xc40f4caf7a8b7b7d367ba7122d12e5b49e4d3c26

![image](https://user-images.githubusercontent.com/8612618/77991530-f21ac600-7345-11ea-9a48-b1b872fe7a0d.png)

**Comment by etherunit** [comment]
If node runner has capped the transfer rate to 5mpbs, then the most that can be transferred in 1 minute would be ~37.5 mb (5mpbs = 0.625MB/s times that by 60 should give me 37.5 roughly). As mentioned by soffokl, this does not applied for WG based sessions.
other identities: 0xc20b410f1cac80ee1bced94476b1f7bc5ada78c1
below are some example session ID's,

9c9ca03e-c798-4c87-9d07-84fbc010ba90 Netherlands 3 days ago Completed < 1min 101.03 MB
6149fbce-945e-478d-83d4-d36bf2e408ad Netherlands 4 days ago Completed < 1min 139.12 MB

d095c2fc-9577-466c-a8e4-8ffa8adaf05b Netherlands 4 days ago Completed < 1min 123.33 MB

e449df08-7309-4127-be5c-ae87661dc5ff Netherlands 4 days ago Completed 8s 33.73 MB

acefce89-5eca-42e9-93e5-312149f79f0d Netherlands 5 days ago Completed < 1min 51.95 MB
