### ISSUE TITLE
Payments: consumer -> provider promotion flow

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#1971]
Currently there's no way for a registered consumer to become a registered provider. Need to make appropriate changes for this to happen.

**Comment by chompomonim** [comment]
After current smart contracts refactoring consumer can simply start service and start exchanging promises. Payment channel with hermes will be opened during the first settlement.

**Comment by soffokl** [comment]
This is resolved by the https://github.com/mysteriumnetwork/payments/pull/68, https://github.com/mysteriumnetwork/hermes/pull/103, and https://github.com/mysteriumnetwork/transactor/pull/68

Also, https://github.com/mysteriumnetwork/node/tree/payment-v3 which is decided to not merge now.
