### ISSUE TITLE
[MMN] 0 values in earnings

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1976]
Node runners have had successful sessions but total earnings is 0.
Node id_1: 0xc16e96c1b0e29fa03cbb0dd7f84f5181d3aea48a
Node id_2: 0x8eefdbc704c5802ad2f221459bf2e586af627c3a
Node logs will be added shortly

**Comment by scorcher70** [comment]
And mine too, since approx 26th March 2020

0xcc96829ffdb960da7654a4bf3c8f99b24b068914

**Comment by etherunit** [comment]
0xd2234371d8d595c110ab2b5e3e54c4dc246eb70a
