### ISSUE TITLE
cannot trust tequilapi.connectionCreate throwing error

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1996]
Provider to reproduce: 0x409b5c902d26d4c5250dce8cbd574bd0cbe2b8cb, type: wireguard (Lithuania)

at connection/store.ts#connect 
tequilapi.connectionCreate throws timeout error (Could not connect timeout of 5000ms exceeded (path="connection"))

Yet, after a while it actually connects.

In my case this is critical as I attempt to connect to another provider in case tequilapi.connectionCreate throws error.
Note: this works smoothly in mobile, isn't it the same node code?
p.s. should I move this issue to https://github.com/mysteriumnetwork/node ?

**Comment by cvl** [comment]
Noticed, that even in Mysterium app, even though timeout is set to 5000, it attempts to connect for more than 1 minute in some cases (e.g. New Zealand provider 0xbfe879812b8cdb4aa22794f3f2f689a9cb9fdebf).

**Comment by cvl** [comment]
0x9137cbfb964275623121385ecb951e484de5f964 Singapore fails:
- when connecting, it connects forever from node perspective. I assume tequilapi timeouts after 30000, yet node is stuck in "connecting" state forever.

**Comment by chompomonim** [comment]
It is related to #2400. Closing this, because after connection speed improvement this issue should be fixed.
