### ISSUE TITLE
[MMN] Negative values in earnings

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1997]
MMN is showing negatives figures in both month's earnings and MYSTT balance.

1. 0xb09781df89214cba5a61e442624722f8fa55aa59
2. 0x86ac210d5548eb0aa2e7d351b52460d382e75da4
3. 0x2bc8193504a60c1d9746006a9eb3ade5d6b7f51b

Most of nodes are affected

<img width="499" alt="Screenshot 2020-04-03 at 13 45 09" src="https://user-images.githubusercontent.com/60128746/78355913-4082cb80-75b7-11ea-8157-d86b431556e5.png">

**Comment by soffokl** [comment]
Another node that affected too 0xeab3ff556a9bb8a8f9cb09e93800a623e87b76e3

**Comment by ignasbernotas** [comment]
Fixed, accountant changed it's endpoint response therefore latest total token amount was 0.

**Comment by moorer2k** [comment]
Mines doing this also.

0x2749228be904d1f75a8920dec5e16f2eaaabc379

Please help so I can keep up on the leaderboards! Thanks!

**Comment by etherunit** [comment]
@moorer2k Can you please provide a few examples of the negative values? Thanks!

**Comment by moorer2k** [comment]
> @moorer2k Can you please provide a few examples of the negative values? Thanks!

It seemed to have fixed itself a couple days after I had posted, anyways, this is what it was doing prior for future reference.

![76C22B15-56D4-432D-B920-303500A5F9D3](https://user-images.githubusercontent.com/2856413/87946516-fb47b400-ca56-11ea-950b-100c1d03c0b5.jpeg)
