### ISSUE TITLE
Fix a loop error

### ISSUE THREAD

**Issue by zyfdegh** [MysteriumNetwork/node#20]
I think there is a loop error in file `openvpn/utils.go`,
```sh
for i := 0; i < 10000; i++ {
	filePath = directory + "/" + filePrefix + randomString(10, finenameCharset) + fileExtension
	if _, err := os.Stat(filePath); os.IsExist(err) {
		continue
	}
}
```
This will run `10000` times whenever the temp file exists or not.

I guess your original idea is `generating a non-duplicated  temp file path `, is it?

If so, an `else` clause is needed and a `break` should be in the else case. 

Or simply
```sh
for i := 0; i < 10000; i++ {
	filePath = directory + "/" + filePrefix + randomString(10, finenameCharset) + fileExtension
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		break
	}
}
```

**Comment by donce** [comment]
PR merged, thanks :)
