### ISSUE TITLE
Connection cancel doesn't work while connecting

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2004]
1. Call http.put('connection', request, timeout)
2. While still not connected (Connection in progress) -> call http.delete('connection')
3. Instead of canceling the connection in progress, it doesn't do anything, and after a while unwanted connection is established.

You can try provider 0x8d4707b19fa02ba1de6ce09b9796e4e68e260f07 to test this, as it takes long time to establish conn with this one.

**Comment by cvl** [comment]
Note, that in Android node throws CancellationException, which is correct behavior.

**Comment by cvl** [comment]
Another identity (India) which doesn't let to disconnect ever, until app relaunch: 0x24a6571fc0017b2b0c05ab955ded62f2a8e01b3b

**Comment by chompomonim** [comment]
Could you try with the latest macOS app build (freshly installed)? Is this still happening?

**Comment by cvl** [comment]
When I disconnect now, it throws
PUT http://127.0.0.1:4050/connection 500 (Internal Server Error)
Could not connect Request failed with status code 500 (path="connection")


But it behaves correctly (i.e. disconnects).

**Comment by cvl** [comment]
don't

**Comment by chompomonim** [comment]
I believe this is not a problem of desktop app but node's problem itself. We'll recheck scenario described in task description and if it a case, will fix it or create feature request with more details what should be done to achieve wanted experience.

**Comment by chompomonim** [comment]
@cvl could you ellaborate on steps to reproduce?

> 1. Call http.put('connection', request, timeout). 
> 2. While still not connected (Connection in progress) -> call http.delete('connection')

These are tequilapi calls from JavaScript app, right?

**Comment by cvl** [comment]
Yes, but they're being called by tequila api, specifically:
tequilapi.connectionCancel()

Here's how it looks when attempting to disconnect. In this attempt it just hung up in "Connecting" state, have to relaunch the app.

<img width="695" alt="Screenshot 2021-06-24 at 15 33 25" src="https://user-images.githubusercontent.com/100252/123263536-bdbe9700-d501-11eb-8997-0a2711116a24.png">

**Comment by chompomonim** [comment]
Have you checked it only on Mac or this issue is reproducible only on Mac and Windows is ok?

**Comment by cvl** [comment]
Same on Windows

**Comment by tomasmik** [comment]
Tested on linux, disconnect seems to work, but together with the disconnect it also brings down DNS configuration (and maybe something else?) and I'm forced to restart the machine. Will investigate further.

**Comment by cvl** [comment]
I've tested this on Mac & Windows, didn't test it on Linux.

General note: almost in all cases the buggy behavior follows the crapiness pattern: Linux > Mac > Windows.
I.e. if there's any possible bug, test it on Windows first, as it's most likely to fail. Linux is the most likely to succeed, so not worth trying first.
Also, 80% VPN users are on Windows, and 5% are on Linux, so fixing Linux problem first is not productive :)

**Comment by tomasmik** [comment]
I understand your point. Honestly I'd say that from what I tested, linux is the worst. I disconnect but am left with no internet connection 🤷🏻 As mentioned before I will continue to investigate this, but this probably will not be a quick solution.

**Comment by cvl** [comment]
Happens on other OS as well (some folks report that after disconnecting/connection drop they're left without Internet connection).

**Comment by chompomonim** [comment]
@Snawoot should this be fixed after your last PR or that was just partial solution to this problem?

**Comment by Snawoot** [comment]
We've implemented some fixes to cause less damage when connection was cancelled before it was established. However, proper cancellation will require all code on the way to connection accept cancellation contexts and do a proper rollback on error. This work will be carried out as a separate task #3774.
