### ISSUE TITLE
Auto upgrade desktop app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2019]
During upgrade into mainnet old client apps will be still using testnet and will need to upgrade node for joining main net. Unfortunately, users often don't do app upgrades and we would need to force it. 

Supervisor should watch if there is a node upgrade required and should do auto-upgrade so the user would not need to install a new client version manually. Also if there is a mandatory upgrade found, app should stop working until node is not upgraded.

**Comment by anjmao** [comment]
It would be better to show notification that app update is ready. Forcing autoupdate is not a good practice. Apple can even forbid such app to be placed in app store.

**Comment by zolia** [comment]
The only thing is that we might need to disable service for such app. This is due to preventing network splits.

**Comment by chompomonim** [comment]
By "force" I mean that the user would need to choose either take an action to upgrade or not to use the app because it will stop working for him.

**Comment by anjmao** [comment]
Check https://www.electron.build/auto-update

**Comment by Waldz** [comment]
https://github.com/iffy/electron-updater-example

**Comment by tadaskay** [comment]
Fixed with https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/9953ff1b8ee2f938082558cf85406b2cb3c19ba6
