### ISSUE TITLE
Pingpong: first invoice should be critical

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#2034]
We need to make sure that the first session invoice gets sent and paid for by the consumer as soon as the session starts. This is the only way to make sure that the consumer is able to pay for the service.

There are 2 issues:

1) on sending failure of the invoice, the provider will just increase a failure counter, and ignore the error
2) on successful send, the invoice gets handled just like any other invoice, meaning that if consumer does not respond to it, we will just increase a counter and ignore the error.

Suggested changes:

1) Make sure that the invoice is sent AFTER the p2p channel is ready on both ends.
2) Make sure that the first invoice is treated as a special case and we fail early.

**Comment by zolia** [comment]
Moving this to TODO, as its important and its a bug.

**Comment by anjmao** [comment]
Can we start VPN session only after first invoice is sent and received back?

**Comment by anjmao** [comment]
For now easy fix for first invoice would be to check for ErrHandlerNotRegistered and retry each second.
