### ISSUE TITLE
After crash machine have stale DNS config

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#2035]
Made connection to wireguard server and machine crashed.
Problem is that after such crash can't use internet at all. Machine reboot does not help, so as end user I would not be able to fix such issue.

```
ifconfig utun0

utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
inet6 fe80::da83:6e1d:b22d:cfd5%utun0 prefixlen 64 scopeid 0x10
nd6 options=201<PERFORMNUD,DAD>

cat /etc/resolv.conf
nameserver 10.182.0.1
```

**Comment by zolia** [comment]
I don't know how to fix that for cli client crash, but for desktop client we install myst_supervisor. I suggest to make checks/cleanup there.

**Comment by creotiv** [comment]
Maybe add some lock file and if it exists then make cleanup on start of application + add some small tool which will do this(in case of app crash on startup)
