### ISSUE TITLE
[MacOS] Cannot connect to providers on the first app run

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2051]
1. Install app (freshly), 2. run and try to connect to nodes.
The problem occurs on the first run.
Subsequent runs don't produce the same behavior.

- It fails to connect to the same nodes which actually work on subsequent runs.
- Fails to connect to most nodes (works on subsequent runs).
- Even if it connects, it disconnects after 10 seconds or so
- Some nodes work okay though even on the first run

2020/04/14 17:15:33 Running myst supervisor daemon
2020/04/14 17:15:33 Waiting for connections...
2020/04/14 17:15:33 Waiting for connections...
2020/04/14 17:15:33 Client connected: unix
2020/04/14 17:15:33 myst [err=exec: already started] output:
2020/04/14 17:15:33 Error running myst: exec: already started
2020/04/14 17:22:35 Client disconnected: unix
2020/04/14 17:22:40 Waiting for connections...
2020/04/14 17:22:40 Client connected: unix
2020/04/14 17:22:40 myst [err=exec: already started] output:
2020/04/14 17:22:40 Error running myst: exec: already started

Tested with Portals as well as with Mysterium v1.0 release https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/download/SNAPSHOT/MysteriumVPN.1.0.dmg

E.g. try this proposal:

0xa790b42ed41898122fb485c79267cdcf53482412 | GB | openvpn

**Comment by cvl** [comment]
CC: @chompomonim

**Comment by cvl** [comment]
Good news this is reproducible in dev mode as well.

**Comment by chompomonim** [comment]
> CC: @chompomonim

You don't need to cc me, I'm reading most of the issues anyway ;)

**Comment by chompomonim** [comment]
Have you tried if similar habits are reproducible with CLI?

**Comment by cvl** [comment]
I can check, how do I do that?

**Comment by cvl** [comment]
`[Portals Priority 90/100]`

**Comment by etherunit** [comment]
@cvl Hi, I have launched a fresh copy of latest pre-release (Mysterium CLI) on Mac. Everything worked well (managed to connect) and I did not have a chance to reproduce this issue.
You can try to do same on your end, pls follow these steps:

Mysterium CLI:
1. Download binary or .deb package from Github https://github.com/mysteriumnetwork/node/releases
2. Locate path and jump into correct folder with downloaded files
3. Launch Myst CLI:  ./myst cli or myst cli 
4. Create new identity: identities new
5. Unlock your newly created identity (need to unlock each time your tequilapi service (daemon) reloads: identities unlock {IDENTITY_ID}
6. Register your newly created identity (need to register just once): identities register {IDENTITY_ID}
7. Connect to remote node: connect <consumer-identity> <provider-identity> <service-type>

Daemon (tequilapi service)
1. Download binary or .deb package from Github https://github.com/mysteriumnetwork/node/releases
2. Open a new tab in terminal or use iTerm for multi-tabs. Locate path and jump into correct folder with downloaded files
3. Launch daemon: ./myst daemon or myst daemon

Let me know the output. thanks!

**Comment by cvl** [comment]
Thanks! Then it's an app (or supervisor) problem, not a node client.

**Comment by cvl** [comment]
I made a video of how it works differently on the first (clean) run, and then after relaunch: https://recordit.co/zjUle7sc98

On the first run:
- All nodes I'm trying to connect fail
- The attempt to connect is much shorter than after relaunch

On the second run:
- First few nodes fail connection (as in the first run), yet the attempts take much longer.
- The same node it failed in the first run, works in the second run


Additional clue here is, that (here not visible, but I can see this in Portals app) it actually connects to the node (the one that works in the second run), i.e. the function tequilapi.connectionCreate doesn't throw error, but after a moment the node disconnects.

I believe this must be some concurrency issues, but somehow it's more evident in the first clean run.

CC: @chompomonim @tadaskay @zolia

**Comment by chompomonim** [comment]
@cvl could you provide you consumer logs and exact provider identities have tried to use?

**Comment by cvl** [comment]
The only logs I have are from myst_supervisor.log
2020/04/17 14:42:57 Running myst supervisor daemon
2020/04/17 14:42:57 Waiting for connections...
2020/04/17 14:42:57 Waiting for connections...
2020/04/17 14:42:57 Client connected: unix
2020/04/17 14:52:58 Client disconnected: unix
2020/04/17 14:54:21 Running myst supervisor daemon
2020/04/17 14:54:21 Waiting for connections...
2020/04/17 14:54:21 Waiting for connections...
2020/04/17 14:54:21 Client connected: unix
2020/04/17 15:15:32 Client disconnected: unix
2020/04/17 15:19:28 Running myst supervisor daemon
2020/04/17 15:19:28 Waiting for connections...
2020/04/17 15:19:28 Waiting for connections...
2020/04/17 15:19:28 Client connected: unix
2020/04/17 15:57:52 Client disconnected: unix
2020/04/17 15:58:38 Running myst supervisor daemon
2020/04/17 15:58:38 Waiting for connections...
2020/04/17 15:58:38 Waiting for connections...
2020/04/17 15:58:38 Client connected: unix
2020/04/17 16:02:24 Client disconnected: unix
2020/04/17 16:02:27 Waiting for connections...
2020/04/17 16:02:27 Client connected: unix
2020/04/17 16:04:00 Client disconnected: unix
2020/04/17 16:05:11 Running myst supervisor daemon
2020/04/17 16:05:11 Waiting for connections...
2020/04/17 16:05:11 Waiting for connections...
2020/04/17 16:05:11 Client connected: unix
2020/04/17 16:08:27 Client disconnected: unix
2020/04/17 16:08:31 Waiting for connections...
2020/04/17 16:08:31 Client connected: unix
2020/04/17 17:01:52 Client disconnected: unix
2020/04/17 17:03:40 Running myst supervisor daemon
2020/04/17 17:03:40 Waiting for connections...
2020/04/17 17:03:40 Waiting for connections...
2020/04/17 17:03:40 Client connected: unix
2020/04/17 17:05:07 Client disconnected: unix
2020/04/17 17:05:13 Waiting for connections...
2020/04/17 17:05:13 Client connected: unix
2020/04/17 17:18:07 Client disconnected: unix


Tried today again:
1) clean install (see below for instructions)
2) open US, select first node on top of the list (I chose opvn service type always for repeatability)
3) same behavior (connects & disconnects automatically), until relaunch. No errors, or error logs.
2020/04/20 14:38:47 Running myst supervisor daemon
2020/04/20 14:38:47 Waiting for connections...
2020/04/20 14:55:42 Running myst supervisor daemon
2020/04/20 14:55:42 Waiting for connections...
2020/04/20 14:55:42 Waiting for connections...
2020/04/20 14:55:42 Client connected: unix

So in logs it says only that it has connected, but no errors or notification about disconnect.

How to clean:
sudo rm -rf /Applications/MysteriumVPN.app
sudo launchctl unload /Library/LaunchDaemons/network.mysterium.myst_supervisor.$
sudo rm /Library/LaunchDaemons/network.mysterium.myst_supervisor.plist
sudo rm -rf /var/root/.mysterium ~/.mysterium

Identities as per video (or just try the ovpn nodes from US country):

<img width="357" alt="Screenshot 2020-04-17 at 16 14 13" src="https://user-images.githubusercontent.com/100252/79749523-071cc080-8318-11ea-88a3-92643945f312.png">
<img width="480" alt="Screenshot 2020-04-17 at 16 14 50" src="https://user-images.githubusercontent.com/100252/79749532-0b48de00-8318-11ea-9036-7013ee5c06a8.png">
<img width="427" alt="Screenshot 2020-04-17 at 16 15 01" src="https://user-images.githubusercontent.com/100252/79749538-0e43ce80-8318-11ea-8c51-4d55a3152b8d.png">
<img width="434" alt="Screenshot 2020-04-17 at 16 15 17" src="https://user-images.githubusercontent.com/100252/79749554-13a11900-8318-11ea-9a7c-13bd123ef8ed.png">
<img width="467" alt="Screenshot 2020-04-17 at 16 15 31" src="https://user-images.githubusercontent.com/100252/79749566-1865cd00-8318-11ea-91c8-9247da2afe41.png">

**Comment by cvl** [comment]
Also, it could (and probably is) be related to https://github.com/mysteriumnetwork/node/issues/1743
This didn't happen in 0.22.5

**Comment by zolia** [comment]
@cvl can you retest this? Do you still experience this with 0.31.0?

**Comment by cvl** [comment]
Tried the following myst binary (not sure which version one is that, but I guess from node master) https://github.com/mysteriumnetwork/mysterium-vpn-desktop/tree/master/static

Works really well so far on Mac (not just that it works on first connect, but also connects smoothly and quickly).

Will try today on Android as well.

**Comment by cvl** [comment]
Works well on Android with 0.31.1! good job :)
