### ISSUE TITLE
Beta release of MacOSX desktop dVPN app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2057]
We're going closer into the public release of dektop app. This is an intermediary release for beta testers to try app and give us feedback/feature requests. 

Until release such tasks should be done:

- [x] Desktop app should not run in provider mode #1939
- [ ] Packed .dmg with 0.31.x node version

**Comment by tadaskay** [comment]
https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/2.0.0-beta1
