### ISSUE TITLE
Refactoring for desktop app to use Electron

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2058]
Unfortunately `nodegui` is still on very early stage. It is very good for apps with limited UI features, but while working on additional user interface features we reached a point when making any changes becomes quite slow and complicated. So we decided to try going with `electron`. Most of work done for this app will still be very useful (e.g. supervisor or changes in node itself), also part of JS code will be also used in new app.

**Comment by cvl** [comment]
Could you talk to framework author instead? He's very open and motivated to fix things.
I'd suggest to think about this very well, as Electron app has terrible architecture and we've spent few months working on nodegui app already.

**Comment by chompomonim** [comment]
Nodeql is very promising technology, however, for more complex UI it is still hard to work with. We do plan to have a lot of features in mysterium desktop app and we need to create more advanced UI. In the same time for simple UI (e.g. Portals VPN) nodegui may be very good solution.

Most of work done for current desktop app implementation will remain same, only rendering framework will be changed. Also thanks to supervisor (which can be used in any app) people using nodeql can do that in the future and still be able to get newest backend related fixes. 

Also, migration into electron was done in 2 days and we already do have a working branch made with it.

**Comment by tadaskay** [comment]
Fixed in https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/21
