### ISSUE TITLE
miscalculation in monthly earnings / 58min sessions

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2078]
Node identity: 0xcc96829ffdb960da7654a4bf3c8f99b24b068914
v0.22.5, RPi
This month's earnings = $0.53 (node has processed 135GB of data). According to our official rates, it should be 135x0.07=9.45MYSTT

This node has same 58m sessions as described in #2076 and for some reason are not being counted.

user reports: https://github.com/mysteriumnetwork/node-user-reports/issues/468.& https://github.com/mysteriumnetwork/node-user-reports/issues/468

Download node logs: https://my.mysterium.network/admin/issues/download/467

**Comment by zolia** [comment]
Could you reset this with 0.32.0-rc1 or some will be 0.32 branch releaeses.

**Comment by chompomonim** [comment]
Please open new bug if it will repeat with 0.32.
