### ISSUE TITLE
Node starts with issues after flashing RPi image from mystberry.zip 

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2081]
**Describe the bug**
I have flashed my node's sd card as pointed in [documentation](https://my.mysterium.network/node-running-guide/raspberry-guide) by using [this mystberry.zip image](https://github.com/mysteriumnetwork/node/releases/download/0.22.5/mystberry.zip).

OS started and myst was running there but webui was not accessible. 

After running [a standard install script](https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh), everything is fixed and node is up and running.

**To Reproduce**
1. Downlod mystberry.zip image.
2. Flash your sd card it using etcher.
3. Put sd card into RPi 3B and wait until start
4. Type http://[local_node_ip]:4449 and see that no webpage available.
5. ssh into node and run cli.
6. Read the logs.

**Additional context**
```
2020-04-16T21:53:15.198 ERR source/tequilapi/client/http_client.go:107 >  error="Get http://127.0.0.1:4050/proposals?lowerGBPriceBound=0&lowerTimePriceBound=0&upperGBPriceBound=7000000&upperTimePriceBound=50000: dial tcp 0.0.0.0:0->127.0.0.1:4050: connect: connection refused"
[WARNING] Get http://127.0.0.1:4050/proposals?lowerGBPriceBound=0&lowerTimePriceBound=0&upperGBPriceBound=7000000&upperTimePriceBound=50000: dial tcp 0.0.0.0:0->127.0.0.1:4050: connect: connection refused
Mysterium Node
  Version: 0.22.5
  Build info: Branch: 0.22.5. Build id: 126951870. Commit: 23c656f7
```

**Comment by chompomonim** [comment]
@etherunit could you recheck if you can reproduce this issue?

**Comment by etherunit** [comment]
@chompomonim will check

**Comment by chompomonim** [comment]
@etherunit  Any news?

**Comment by etherunit** [comment]
Hey, I have tried to install it few times already, did not notice any issues during installation or startup.
