### ISSUE TITLE
Testing v0.31.0-rc

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2083]
We have released new pre-release version of node software. Here we're going to collect issues reported by node runners who are testing it.

What to test in 0.31.0:

- [x] Check if P2P traffic works (0.31 consumer to 0.31 providers. Should be faster connects and logs should indicate that payment promises are sent in P2P way, not via broker.) 
- [x] Check if old (0.22.5) cli consumers works with new providers
- [x] Check if new cli consumers works old providers
- [x] Check if old mobile consumers  (0.22.5) works with new providers
- [x] Check if new mobile consumers works with old providers
- [x] Check if tokens are calculated properly (log, accountant apis, dashboards, mmn, webUI)
- [x] Check both protocols OpenVPN and WireGuard
- [x] Check desktop and mobile clients
- [x] Check if whitelisting is note randomly changed anymore #1917
- [ ] Check if connecting to node you can reach his WebUI (shouldn’t possible)

**Comment by chompomonim** [comment]
```
Done the latest update to 0.31, still have same issues as in 0.30pre with node now doesn't start on reboot or from the webUI.

Ok , progress. The reason why it wasn't able to start up was due to 
SERVICE_OPTS="--openvpn.port=XXXX --wireguard.listen.ports=XXXXX:XXXXX openvpn,wireguard"
somewhere in that there was an error. If I remove all the wireguard part it will start up and the service will run.
Now the service starts a log is written but the service stops with an error as can be seen from the log
```

**Comment by chompomonim** [comment]
People are reporting that "the earned mystt reported on webUI is different from whats reported on mmn."

This is known. WebUI shows the amount of not settled tokens on blockchain. MMN tracks its own payout logic. However, we most probably should have two balances there:

- total not settled MYSTT
- your monthly earnings

**Comment by anjmao** [comment]
Looks like from mobile OpenVPN doesn't work, only WireGuard.

**Comment by anjmao** [comment]
Issue with OpenVPN is fixed, new app version is released.

**Comment by Peter-SovietSquirrel** [comment]
0.31.0-rc2 
Service is running MMN reports that it's online except it does not show as an available node on android app.

**Comment by anjmao** [comment]
@Peter-SovietSquirrel I just noticed similar issues. Recently we did a change in proposals to filter out nodes to which monitoring agent wasn't able to connect. The issue is that after monitoring agent marks such node as not accessible it's not possible to see it anymore. I though that after some time monitoring agent will try again but I didn't received any more checks in 15 mins. Need to check with @soffokl 
Anyway we will probably need a change in mobile app to allow see all nodes by more filters.

**Comment by Peter-SovietSquirrel** [comment]
Eventually without any change being made it is now visible.  But when attempting to connect from 0.31.0-rc2 app it looks like it resets the mysterium service each time, and the connection fails.
There has been completed connections but not from0.31.0-rc2.

**Comment by anjmao** [comment]
@Peter-SovietSquirrel , I'm looking into it now.

**Comment by etherunit** [comment]
Updated my RPi node 0x409b5c902d26d4c5250dce8cbd574bd0cbe2b8cb to 0.31.0-rc2 pre-release. 

0.31.0-rc2 consumer > 0.31.0-rc2 node / 

1. Communication exchange is being handled via P2P channel but not via broker. Most of connections worked well for me, however,  just a few times was getting some connection retries which basically delayed the connection speed. 
<img width="1675" alt="Screenshot 2020-04-20 at 10 37 39" src="https://user-images.githubusercontent.com/60128746/79726545-a1b6d880-82f3-11ea-841b-c384817df7e8.png">

2. Tokens calculation. Consumer total spent in MYSTT and providers earnings in MYSTT matched during my test. WebUI supports maximum X.XXX decimal format while consumer shows more explicit numbers, e.g. Spent: 0.002664MYST (in WebUI it would be rounded off to 0.003MYST). WebUI shows MYSTT, consumer shows MYST.
The earned MYSTT reported on WebUI is different from whats reported on MMN but as per Jaro's comment, it's a know issue.

3. Service restart via WebUI in 0.31.0-rc2. Manual stop and start of the service removes OpenVPN from service list. 
<img width="1445" alt="Screenshot 2020-04-20 at 11 04 21" src="https://user-images.githubusercontent.com/60128746/79728519-b8aafa00-82f6-11ea-98cb-b1c612417454.png">
Needed to reboot my RPi to get them back.
After reboot:
<img width="1410" alt="Screenshot 2020-04-20 at 11 07 15" src="https://user-images.githubusercontent.com/60128746/79728786-21927200-82f7-11ea-99ad-004daa3cedd1.png">
`sudo service mysterium-node restart`does works normally and keeps two services alive.

**Comment by etherunit** [comment]
0.31.0-rc2 cli consumer worked well with 0.22.5 provider 1.0x12153f185242cdf1dec4fe338bd4655e517685d5 0.22.5
2. 0x4a71111e8669b4e161454c70c2becc4e0c2c5a3d 0.22.5

0.22.5 cli consumer worked well with 0.31.0-rc2 provider 
1. 0xeab3ff556a9bb8a8f9cb09e93800a623e87b76e3 0.31.0-rc2 
2. 0x2bc8193504a60c1d9746006a9eb3ade5d6b7f51b 0.31.0-rc2

**Comment by zolia** [comment]
> Check if old (0.22.5) cli consumers works with new providers

[ Provider behind NAT ] 
cli openvpn, plain connect - works
cli openvpn, speed test - works
cli wireguard, plain connect - works
cli wireguard, speed test - works

[ Provider on public IP ] 
cli openvpn, plain connect - works
cli wireguard, plain connect - works

**Comment by zolia** [comment]
>Check if old mobile consumers (0.22.5) works with new providers
[ Provider behind NAT ]
cli openvpn, plain connect - works
cli openvpn, speed test - works
cli wireguard, plain connect - works
cli wireguard, speed test - works

connect on WG takes up to 18 sec.
connect on OVPN takes up to 4 sec.

**Comment by etherunit** [comment]
https://my.mysterium.network/nodes/6777/dashboard 
made a fresh 0.31.0-rc2 install and manually switched from "Mysterium verified partner traffic" to "All traffic", however, MMN is not adjusted (restarted and rebooted node).
Is there any delay in sync with MMN? Or priority is set to cat /etc/default/mysterium-node access policy config?

**Comment by etherunit** [comment]
@anjmao made several successful sessions to my LT node 0x409b5c902d26d4c5250dce8cbd574bd0cbe2b8cb with MysteriumVPN app for Android. In short, it was a pretty stable and seemingly worked better (no random disconnects etc.). The word "stable" was a rare case in previous mobile app versions.:)

**Comment by Peter-SovietSquirrel** [comment]
0.31.0-rc2, no change made and it has gone to test failed. Port is forwarded and is reachable.

**Comment by etherunit** [comment]
As far as I know, only OpenVPN service is checked now by monitoring agent and Test failed in MMN means that monitoring agent has failed to connect this node. This identity is also not available in mobile app and there is no proposal for it. `proposals 0x57daba353514f004c86edf2e3892740ec4d98c4d` returns nothing.
but, this node is reachable via CLI
<img width="1535" alt="Screenshot 2020-04-23 at 15 32 45" src="https://user-images.githubusercontent.com/60128746/80099957-f5d1ef00-8577-11ea-9794-2dcc184b988f.png">

**Comment by soffokl** [comment]
`0x57daba353514f004c86edf2e3892740ec4d98c4d` has invalid `payment_method_type` for some reasons:
```
{
	"format": "service-proposal/v1",
	"id": 1,
	"payment_method": {
		"bytes": 0,
		"duration": 0,
		"price": {},
		"type": ""
	},
	"payment_method_type": "",
	"provider_contacts": [{
		"definition": {
			"broker_addresses": ["nats://testnet-broker.mysterium.network:4222"],
			"topic": "0x57daba353514f004c86edf2e3892740ec4d98c4d.openvpn"
		},
		"type": "nats/v1"
	}, {
		"definition": {
			"broker_addresses": ["nats://testnet-broker.mysterium.network:4222"]
		},
		"type": "nats/p2p/v1"
	}],
	"provider_id": "0x57daba353514f004c86edf2e3892740ec4d98c4d",
	"service_definition": {
		"location": {
			"asn": 5378,
			"city": "England",
			"continent": "EU",
			"country": "GB",
			"isp": "Vodafone UK",
			"node_type": "residential"
		},
		"location_originate": {
			"asn": 5378,
			"city": "England",
			"continent": "EU",
			"country": "GB",
			"isp": "Vodafone UK",
			"node_type": "residential"
		},
		"protocol": "udp",
		"session_bandwidth": 83886080
	},
	"service_type": "openvpn"
}
```

**Comment by Peter-SovietSquirrel** [comment]
Version 0.31.0, p2p port forwarding set up and seems to be working correctly except node still isn't showing up as available in app.

**Comment by anjmao** [comment]
@Peter-SovietSquirrel Thanks for report. I can confirm that I have the same issue. On my node proposals registration fails.
