### ISSUE TITLE
New default pricing

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2086]
From v0.31.0 node runners will be able to set own price. But we should still set some reasonable price as default. From feedback from nodes, they mostly care about traffic provided, because that is what they're paying for ISPs and this also can make his own internet worse.

I suggest to have such default pricing:
- [ ] 1Gb of traffic: 0.10 MYSTT
- [ ] 1min session: 0.0001 MYSTT
- [ ] accountant fee: 12%

In such case, in the default configuration, providers would be getting around 0.09 USD for 1 Gb of traffic.

**Comment by zolia** [comment]
I just suggest increase max limits and let users decede. Default price should not be high as it would better reflect possible market conditions.

**Comment by zolia** [comment]
we agreed to move this one to v0.32.0 and implement payment visibility on apps before allowing drastics price changes.

**Comment by chompomonim** [comment]
> I just suggest increase max limits and let users decide. Default price should not be high as it would better reflect possible market conditions.

There are couple of reasons for default price change:
- users usually not change default settings, only advance users will do that
- current default minute price is quite high and traffic price is quite low, I'd like to have default prices closer to market conditions and also easier to calculate
