### ISSUE TITLE
Price flags have the same description

### ISSUE THREAD

**Issue by idunno101** [mysteriumnetwork/node#2089]
The usage section of the price flags both have the same wording.
I assume the first one is supposed to end with "per minute" and the second one should say "per GiB"

https://github.com/mysteriumnetwork/node/blob/27ce917deab7f7c1ee7e6adef52b52a7cbc6dc6b/config/flags_service_openvpn.go#L49-L59

**Comment by soffokl** [comment]
@idunno101 Thank you for noticing this. It will be fixed in the https://github.com/mysteriumnetwork/node/pull/2090
