### ISSUE TITLE
Incorrect session duration

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2091]
1. Connect and immediately check for status and session duration. 
2. I would expected that session duration should be few seconds, but it already shows that session was established for 17 seconds(sometimes more) which is not correct from end user perspective.
```
[SUCCESS] Connected.
» status
[INFO] Status: Connected
[INFO] SID: 2db5d143-18bb-4f3b-be85-990295d372a9
[INFO] IP: xx.xxx.xxx.xx
[INFO] Location: Vilnius, LT
[INFO] Proposal: Id: 1 , Provider: 0x2bc8193504a60c1d9746006a9eb3ade5d6b7f51b, Country: LT
[INFO] Connection duration: 17s
[INFO] Data: 50.8KiB/23.7KiB
[INFO] Throughput: 1.5KiBs/1.6KiBs
[INFO] Spent: 0.000011MYST
```

The problem here is that we start session and only when setup payments which leads to such duration time. It could be fixed with https://github.com/mysteriumnetwork/node/issues/2034

**Comment by anjmao** [comment]
@chompomonim What priority should we give for this issue? From end user perspective who is paying for time this can look not only confusing but also like we are cheating.

**Comment by tomasmik** [comment]
No longer happens. Closing the issue.
