### ISSUE TITLE
Connection fails on newly registered identity until restart

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#2094]
**Describe the bug**
Currently, we are doing grand total recovery on identity unlock. This does not work correctly for the newly created identity.

**To Reproduce**
1. `identity new`
2. `identity unlock 0x0000...`
3. `identity register 0x0000...`
4. `connect 0x0000... 0x1111... openvpn`

**Expected behavior**
After registration, it should be possible to establish first connection successfully without a restart.

**Comment by zolia** [comment]
Is this reproducible on mobile too? Did not notice this behaviour.

**Comment by soffokl** [comment]
@zolia I didn't test it on mobile.

**Comment by soffokl** [comment]
This could be related to the https://github.com/mysteriumnetwork/node/issues/2052 and https://github.com/mysteriumnetwork/node/issues/2051.
