### ISSUE TITLE
Whitelisting settings does not work in NodeUI

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2098]
Provider 0xcb0eaf373bff3812279e78ebcf81839bfd34188e changed whitelisting option from "Mysterium verified partner traffic" to "All traffic", restarted & rebooted his RPi node via terminal. 
 Checked in MMN several times and whitelisted status was not adjusted accordingly (was showing Yes). 

**Steps to reproduce the behavior:**
1. Go to NodeUI > Settings.
2. Select "All traffic" instead of "Mysterium verified partner traffic".
3. Save settings.
4. Restart node.

**Expected behavior**
Once provider changes whitelisting option from "Mysterium verified partner traffic" to "All traffic" or opposite and then restart his node, this should force MMN whitelisted mode change (from Yes to No or from No to Yes).

p.s. have tried to reproduce with my node 0x409b5c902d26d4c5250dce8cbd574bd0cbe2b8cb and it also did not work.
 manually editing `SERVICE_OPTS="--access-policy.list= openvpn,wireguard" `or `SERVICE_OPTS="--access-policy.list=mysterium openvpn,wireguard"` helped.

Logs: https://my.mysterium.network/admin/issues/download/503

**Comment by Waldz** [comment]
I investigated this together. Problems is that `config.toml` should be highest priority configuration. But for some reason it loses some values.
My guess - with value `access-policy.list=""` which mean All traffic

Related: https://github.com/mysteriumnetwork/node/issues/1917#issuecomment-612192910

**Comment by soffokl** [comment]
This was fixed in 0.31 release version. 
@etherunit Do you still have this issue on the latest version?

**Comment by etherunit** [comment]
@soffokl so with 0.31 version manual change of whitelisting option via NodeUI will affect whitelisting change in MMN correct? Should I reboot node via terminal or NodeUI to make this happen?

**Comment by soffokl** [comment]
Yes, now it will require process restart from a terminal, but after https://github.com/mysteriumnetwork/node/issues/2116 fixed, it will be possible to do a restart from webUI too.

**Comment by soffokl** [comment]
@etherunit 
I did a number of tests again on the latest 0.31.1 version. 
Both my Ubuntu Server and Rapsberry PI does change the access policy correctly.
It requires manual restart from terminal, but it will be fixed in another issue as I mentioned.

One note: It takes a few minutes for MMN to get this update after changes.

I'll close this issue. Feel free to reopen it if you will find a case where it does not work as expected.
