### ISSUE TITLE
RFC: logging aggregation

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#2099]
Just had a small grooming with @anjmao regarding the need to simplify and make problem analysis faster. Also we need a priori indication for possible severe infra issues.

Suggestion is to have all basic services: quality, location oracles, hermes and transactor json logging to some log aggregators. Options we considered: 
 - https://grafana.com/oss/loki/
 - elk

Basic structuring could be arranged as follows: 
 - index log source, time and logging level

Additionally node logs could be imported from submitted feedbacks. This means we will need to migrate node logging to json based too. At least for WRN and ERR levels. 

This way tester or programmer working on an issue would be able to search for errors in specific time frame making analysis a lot faster.

Suggestions and comments are welcome.

**Comment by soffokl** [comment]
➕ for loki.

**Comment by anjmao** [comment]
Good news that we don't need json format for logs. Loki parses fields automatically.

![image](https://user-images.githubusercontent.com/3028012/80284155-623e2100-8725-11ea-8aaa-f238fc2e3fbe.png)

**Comment by chompomonim** [comment]
I think we already are using loki. @soffokl are we?

**Comment by soffokl** [comment]
testnet2 loki, testnet3 elk again %)
