### ISSUE TITLE
Move IP detection to caching layer

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#2113]
Currently we waste up to 2sec for each connect just trying to resolve provider public IP.
Move this to caching layer. Each request to caching interface should check lastUpdated time. If it is less than 5 min we should reuse that value.

There were the case with providers on cellular network which changes IPs frequently. In this case we could force cache refresh on failed connect attempt. Statistically if should be a rare case.

**Comment by zolia** [comment]
Wrote short analysis script to better understand where connect lag is coming from:

```bash
#!/bin/bash

findgaps()
{

oldline="not set"
myVar=$(</dev/stdin)

while read line
do
    if [[ $line == "" ]] ; then
	    continue
    fi

    if [[ $line =~ (ping|event) ]] ; then
        oldline="${line}"
   	continue
    fi
    new=$(date -d "$(echo "$line" | sed -e 's/^\(.\{23\}\).*/\1/' | sed -E 's/([0-9][0-9])T([0-9][0-9])/\1 \2/' | sed -E 's/-([0-9][0-9])\.([0-9][0-9])\./ \1:\2:/')" '+%s%N')
    new=$new/1000000
    if [ "$old" ] && (( $new - $old > 100))
    then
	printf "line that took so long: ${oldline}\n"
        printf "%4i msec gap before %s\n" "$((new - old))" "$line"
    fi
    old=$new
    oldline="${line}"
done <<< $myVar
}

findgaps
```
how to use on RPI: 
`# sudo tail -f /var/lib/mysterium-node/.mysterium/logs/mysterium-node.log > out`
`cat out | gap.sh `

**Comment by anjmao** [comment]
Nice, good idea for script :)
