### ISSUE TITLE
RFC: Node capacity

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#2124]
Nodes should not serve more consumers than they are capable of (mostly restricted by the bandwidth available). At the moment there is no limit on how many consumers can connect to a node that provides 5Mbps bandwidth, hence making it unusable for streaming once more than 2 consumers connect. Nodes should report available capacity as a metric and not accept more consumers than they can handle.

**Comment by anjmao** [comment]
Yes, this is something which seems quite important to do. How do we want to show proposals for such nodes? I would display some load percentage (0-100%) field in proposal.

**Comment by tadaskay** [comment]
Still relevant
