### ISSUE TITLE
Can't disconnect from non-working provider

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#2126]
**Describe the bug**
Can't disconnect from a non-working provider.

**To Reproduce**
1) Connect to `0x3eb30a6b70423926b0142aee41f6b6b6299695a3` 
2) Try to disconnect.

Disconnect does not work (node is stuck in disconnecting state)

**Expected behavior**
Node disconnects

**Environment (please complete the following information):**
 - Node version: master
 - OS: macOS
 - Docker: if running on docker, specify docker version and image tag

**Additional context**
If using openvpn, it's possible to kill myst with `-9`. If using wireguard, kill leaves stale DNS configuration - need to reset manually, e.g. `sudo networksetup -setdnsservers wi-fi 1.1.1.1`

**Comment by zolia** [comment]
Looks like packet forwarding on such node is disabled. We get into connected state, but are not able to forward messages. This leaves a node in inconsistent state not able to ack connected state.

**Comment by zolia** [comment]
node in question (0x3eb30a6b70423926b0142aee41f6b6b6299695a3)  is 0.22.5 thus no p2p messaging is supported. P2P disconnect should solve this issue. 

To make consumers resilient and independent from provider version we should still make disconnect on consumer to be robust.
