### ISSUE TITLE
[NodeUI] Statistics page flickerings

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2139]
Statistics screen page is flickering. It's happening during active sessions only. 
https://gyazo.com/ae216278e4a766310f4c9d8d25ebe3b0

**Comment by cvl** [comment]
Any reason to support multiple versions of desktop client?

Let's focus on getting single app right :)

React native build fixes numerous nodegui problems (not just flickering) - e.g. the app doesn't break if close icon X is clicked.

**Comment by zolia** [comment]
Its an interface for node running providers, a.k.a web-ui.

**Comment by pvdl** [comment]
Also at the `/#/dashboard` the red button 'Stop services / Start services' is flickering.
