### ISSUE TITLE
Proposals registration fails

### ISSUE THREAD

**Issue by Peter-SovietSquirrel** [mysteriumnetwork/node#2156]
This is still an issue. https://github.com/mysteriumnetwork/node/issues/2083#issuecomment-619732102

**Comment by vkuznecovas** [comment]
Your node identity?

Looking at the prior issue, I'm assuming it's 0x57daba353514f004c86edf2e3892740ec4d98c4d.

In this case, you've got an astronomical price set in your proposal(~117MYSTT per GB transfered).

```json
"payment_method": {
"bytes": 4569,
"duration": 0,
"price": {
"amount": 50000,
"currency": "MYST"
},
"type": "BYTES_TRANSFERRED_WITH_TIME"
},
"payment_method_type": "BYTES_TRANSFERRED_WITH_TIME",
```

The clients are coded with logic to exclude such proposals from their lists. 

If i'm incorrect, your identity is wrong or something else, please open an issue and provide more details.
