### ISSUE TITLE
Need some effective way to communicate API changes

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2166]
E.g. in newest node version the connection status api changed
http://127.0.0.1:4050/events/state
instead of
"consumer":{"connection":{"status":"NotConnected"}}
we get
"consumer":{"connection":{"**state**":"NotConnected"}}

This breaks the desktop app in runtime.

Suggest to have dev newsletter to announce such key/breaking changes in release notes.

**Comment by anjmao** [comment]
@cvl You are right. We need to include such breaking changes inside release notes. I will communicate with at team.
