### ISSUE TITLE
[android, question] is it possible to get node version?

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2168]
E.g. I need to check if node is upgraded after app update, also used when reporting errors and such.

In desktop app I can get the version from healthcheck call.

**Comment by anjmao** [comment]
Hi, there is no such call, but it will really be useful to show node version in the app. I will add new go binding call `GetNodeInfo` which will return Version.

**Comment by cvl** [comment]
Perfect, thanks!

**Comment by cvl** [comment]
@anjmao can't find this GetNodeInfo in 0.32.1
Was it included?
