### ISSUE TITLE
Add price range filters to mobile

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2184]
Allow user to configure min max price ranges in mobile so we don't need to play with hardcoded values any more. 
This should be done wiht 0.34.0 release and app released before releasing node providers.

**Comment by anjmao** [comment]
This filter can be in new separate Settings screen. When we can also add more settings like DNS etc.

**Comment by zolia** [comment]
If it should be in 0.32 then it should have been done already. We already have 0.32-rc1.

**Comment by chompomonim** [comment]
Here is mockup for new filters.

The main idea is that is should be possible to changes filter by clicking on filter (e.g. it would show sliders while changing price range) and the remember filter settings for the future.

Price and quality sorting should always set as cheaper/best nodes to top by default.

![Filter](https://user-images.githubusercontent.com/153896/84367046-5bd40d80-abdc-11ea-93a1-b31a2e648521.png)
