### ISSUE TITLE
Consumer does not show providers with free price

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2185]
**Describe the bug**
Service restart in WebUI breaks set price settings to 0 and node becomes unavailable in app and discovery.

**To Reproduce**
1. Go to NodeUI > Settings
2. Set price: 0.07/0.0005 or any
3. Save settings
4. Stop/Start services in WebUI

**Expected behavior**
Node is available in app/cli with price adjusted after manual restart in WebUI.

**Screenshots**
<img width="686" alt="Screenshot 2020-05-07 at 14 30 36" src="https://user-images.githubusercontent.com/60128746/81289592-59c3df80-906f-11ea-9652-f7d6e009bd12.png">
<img width="1448" alt="Screenshot 2020-05-07 at 14 31 23" src="https://user-images.githubusercontent.com/60128746/81289657-74965400-906f-11ea-9b14-1ecda00c1308.png">
<img width="511" alt="Screenshot 2020-05-07 at 14 31 45" src="https://user-images.githubusercontent.com/60128746/81289692-824bd980-906f-11ea-88d7-deb98d448599.png">

 - Node version: RPi 0.31.x

**Comment by etherunit** [comment]
fixed in #2116 (will be released in 0.32.0)

**Comment by Waldz** [comment]
It's known issue that service restarts in UI leads to 0 price, fixed in #2116 (will be released in 0.32.0).

But strange that consumer filters out free services (0 price). It's kind of good because it indicates that their service wont generate earnings for them.

**Comment by vkuznecovas** [comment]
This is a non-issue. Proposals with 0 price are visible to the consumer already. The only issue was having an invalid payment type, which is solved by #2116
