### ISSUE TITLE
Proposal is not visible if max price is set in web UI

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2190]
1. Set max price in WEB UI for GB and Time.
2. Start provider.
3. From consumer list proposals with default settings for price ranges.
```
payments.consumer.price-pergib-max:11000000
payments.consumer.price-perminute-max:50000
```

This is the proposal from provider.

```
        "payment_method_type": "BYTES_TRANSFERRED_WITH_TIME",
        "payment_method": {
            "price": {
                "amount": 50000,
                "currency": "MYST"
            },
            "duration": 30000000000,
            "bytes": 1073741,
            "type": "BYTES_TRANSFERRED_WITH_TIME"
        },
```

**Comment by soffokl** [comment]
Do you think that the default price limit should be equal to the max allowed price?

**Comment by tadaskay** [comment]
I don’t think it’s a bug.
We have defaults set in desktop for a reason, but you can adjust the slider to the maximum price you are willing to pay.

**Comment by anjmao** [comment]
Yes, so the problem is when only on mobile which should be fixed with https://github.com/mysteriumnetwork/node/issues/2184 but it's quite important when.

**Comment by Waldz** [comment]
pricePerTime() filter:
60*1000*1000*1000) / 30000000000 * 50000 = 100000 = 0,001 MYSTT

pricePerDataTransfer() filter:
(1*1024*1024*1024)  / 1073741 * 50000 = 50000038,370519520070483 = 
0,500000383705195 MYSTT
