### ISSUE TITLE
Web UI default services prices are not set

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2191]
By default web ui shows prices with zeros, but actual default values are:

```
build/myst/myst service --help
   --payment.price-gb value           Sets the price per GiB applied to provider service. (default: 0.1)
   --payment.price-minute value       Sets the price per minute applied to provider service. (default: 0.0001)
```

![image](https://user-images.githubusercontent.com/3028012/81387935-36a53880-9120-11ea-9ebb-4d01a35f402c.png)

This is confusing as provider will think that service is free and will try to insert values. But what values, how should provider know what to insert here? 

These prices should not be global, but set per service.

**Comment by anjmao** [comment]
I suggest for now to hide these UI settings at all as they doesn't make sense.

**Comment by etherunit** [comment]
yes, now is confusing as they think they provide service for free
more sense would be to change 0 to defaults 0.1/0.0001
