### ISSUE TITLE
Drop OpenVPN support on mobile

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2192]
Looks like it's a good time to drop OpenVPN support for mobile. We already have the same amount of proposals for both types. By dropping OpenVPN on mobile will allow to remove a lot of code and simplify our mobile builds significantly.

![vpn](https://user-images.githubusercontent.com/3028012/81408324-b72a6000-9145-11ea-961a-c2271bc5420c.png)

**Comment by soffokl** [comment]
It's good to have more than 1 alternatives. One protocol could be blocked much easily.

**Comment by anjmao** [comment]
OpenVPN is one of the most popular VPN protocols and can be blocked easily. We don't even have stable core foundation yet and spend a lot of time maintaining both WG and OpenVPN.

**Comment by cvl** [comment]
100%.
Yet, let's not isolate mobile, we should have the same single focus on all platforms (MacOS, Windows, Android).
And if WG comes with some bad surprises (unlikely, but to be seen, as it's new tech), we can always revert back to OpenVPN in relatively short timeframe.

As per "blocked" easily: I assume if WG is getting blocked, then OpenVPN will be blocked for sure.
