### ISSUE TITLE
Secure inner communication between myst and supervisor 

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2204]
As supervisor will run with higher permissions we need to make sure there is no easy way to call supervisor via unix sockets for unauthorised processes.

One idea is to validate peer socket PID when accepting connections in supervisor.

Example for **darwin**:

```go
const (
	syscall_SOL_LOCAL     = 0
	syscall_LOCAL_PEERPID = 2
)

pid, _ := unix.GetsockoptInt(int(f.Fd()), syscall_SOL_LOCAL, syscall_LOCAL_PEERPID)

fmt.Println("peer process pid", pid)

// Validate if this pid is actually created by myst node process.
```

**Linux**
```go
Can use syscall.GetsockoptUcred which returns Ucred object containing PID
```

**Windows**
Need to check what do we have for named pipes.

**Comment by tadaskay** [comment]
Related #2359
