### ISSUE TITLE
First settlement should be used as stake 

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2223]
- [x] Hermes should accept promise exchange messages even when there is 0 stake in channel (until min stake amount is reached).
- [x] Node should adapt settlement flow if using 0 stake.
- [x] Transactor should be adapted for updated settlement logic.

This task requires #2222 to be done first

**Comment by soffokl** [comment]
This is resolved by the https://github.com/mysteriumnetwork/payments/pull/68, https://github.com/mysteriumnetwork/hermes/pull/103, and https://github.com/mysteriumnetwork/transactor/pull/68

Also, https://github.com/mysteriumnetwork/node/tree/payment-v3 which is decided to not merge now.
