### ISSUE TITLE
[android, bug] deferredNode ignores showOpenvpnProposals param

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2225]
Perhaps not relevant if it will return wireguard providers only, but still:

        val req = GetProposalsRequest()
        req.showOpenvpnProposals = false //this is ignored
        req.showWireguardProposals = true
        req.refresh = refresh

...
deferredNode.await().getProposals(req)

it still returns proposals with openvpn service type

**Comment by anjmao** [comment]
Yes, both showOpenvpnProposals and showWireguardProposals are removed in master already.
