### ISSUE TITLE
Flaky test: TestPinger_PingPeer_N_Connections

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#2226]
--- FAIL: TestPinger_PingPeer_N_Connections (5.01s)
    pinger_test.go:134:
        	Error Trace:	pinger_test.go:134
        	            				asm_amd64.s:1357
        	Error:      	Received unexpected error:
        	            	ping failed: context deadline exceeded
        	Test:       	TestPinger_PingPeer_N_Connections
    pinger_test.go:140:
        	Error Trace:	pinger_test.go:140
        	Error:      	Received unexpected error:
        	            	ping failed: context deadline exceeded
        	Test:       	TestPinger_PingPeer_N_Connections
    pinger_test.go:142:
        	Error Trace:	pinger_test.go:142
        	Error:      	"[]" should have 2 item(s), but has 0
        	Test:       	TestPinger_PingPeer_N_Connections
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 57 [running]:
testing.tRunner.func1(0xc000104100)
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:874 +0x69f
panic(0x16b4900, 0xc00012a8e0)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/mysteriumnetwork/node/nat/traversal.TestPinger_PingPeer_N_Connections(0xc000104100)
	/Users/viktoras/GIT/GO/src/github.com/mysteriumnetwork/node/nat/traversal/pinger_test.go:143 +0x11ac
testing.tRunner(0xc000104100, 0x1709750)
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.3/libexec/src/testing/testing.go:960 +0x652

**Comment by zolia** [comment]
Anything about frequency of this? Never saw that one.

**Comment by vkuznecovas** [comment]
Consistently reproducible with `go test -count=100 -timeout 30s github.com/mysteriumnetwork/node/nat/traversal -run TestPinger_PingPeer_N_Connections`
