### ISSUE TITLE
[Mac] Hot reloading fails after making myst run under user permissions

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2240]
Just try to save any file in dev mode, lots of weird errors popup. App restart is needed.

**Comment by cvl** [comment]
After https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/24

**Comment by cvl** [comment]
In some cases, even after app relaunch it acts weirdly, needs a second relaunch.

It seems that myst is not killed in some cases. After app is quit - myst keeps running. Then I assume app tries to relaunch it I guess which results in conflict?

@anjmao

**Comment by anjmao** [comment]
I will check this tomorrow :)

**Comment by cvl** [comment]
Thanks.

I believe the problem lies, that myst.ts#startMyst is run from app's front-end (i.e. from daemon store), while when quitting, killMyst is called from main/index.tsx which is back-end code (which has completely different environment). Therefore variable let mystProcess is undefined, and mystProcess.kill("SIGTERM") is never called.

Strange, that after 1 relaunch, myst is actually killed somehow.
