### ISSUE TITLE
Inaccuracy in token earnings calculation

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2255]
Completed a few remote OpenVPN test sessions with custom pricing set by `--openvpn.price-gb value` flag.
price per min is in default setting (0,0001MYSTT/min) so it's not a factor.

Node identity: 0x409b5c902d26d4c5250dce8cbd574bd0cbe2b8cb, RPi, 0.32
1st session id:  2b538a30-6c28-4fa5-9a31-e6e798efc3c6, duration: 6m, data: 87.1 MB
2nd session id: bc49bd61-208f-4631-81a2-a1ae77f9e323, duration: 3m, data: 91.85 MB

As a provider, I expect my 2nd session to generate more income according to `pricePerDataTransfer() filter`: (1*1024*1024*1024)  / {bytes} * 50000 / 100M
but it has generated less MYSTT.

**Comment by vkuznecovas** [comment]
First of all, the assumption that the default pricing is in place here is wrong.

The provider has custom pricing for openvpn:

```json
"payment_method": {
  "bytes": 5368,
  "duration": 300000000000,
  "price": {
    "amount": 50000,
    "currency": "MYST"
  },
  "type": "BYTES_TRANSFERRED_WITH_TIME"
}
```

Which equates to 10,000 MYSTT/min and 10,001,321,013 MYSTT/GB(or a ridiculous 100$/GB). 

Therefore, the time component plays a pretty minuscule part in the session price and can be safely ignored for the purpose of this ticket.

The session statistics that are seen on MMN are reported by the **consumer**. The earnings are reported by the **provider**. 

Session invoices are sent every minute, therefore the following scenario is possible:

1) Consumer connects, uses the service for 2 minutes with little to no transfer, pays the invoices for the 2 minutes.
2) Consumer ramps up download speed, starts pumping data for a whole minute before disconnecting.
3) The third invoice is never sent, but the stats are already reported by the consumer. 
4) Discrepancy in stats/amount paid occurs.

To solve this problem, I see a few of possibilities:

1) Increase the frequency of payment messages. This has the downside of increasing bandwidth usage just for keeping session alive.
2) Send an exchange message from consumer to provider before killing the session taking the data transferred and time into account. This has the downside of making the protocol vulnerable to the abuse mentioned above.
3) Ignore this problem completely under the assumption that it will be solved by a "reputation system".

**Comment by etherunit** [comment]
> First of all, the assumption that the default pricing is in place here is wrong.

Yes, there is no default pricing for openvpn price per GiB, and I did not mentioned that. there is a default price for openvpn price per min.

**Comment by zolia** [comment]
>Ignore this problem completely under the assumption that it will be solved by a "reputation system".

Would go for this one since such ridiculous price should not be seen by consumers altogether. Anything in a decent range should not make too much difference for the consumer.

**Comment by soffokl** [comment]
> To solve this problem, I see a few of possibilities:

Maybe we should send invoices, not by time interval, but do some calculation based on minimal value to set the invoice? 

Let's say `--minimal-amount-to-invoice=0.1 MYST`. We can send invoices every 10 seconds or once in 10 minutes if we are ready to risk 0.1 MYST. 

We do track transferred traffic every 2 seconds, it should be easy to decide if the user transferred too much and it's time to request payment.

**Comment by vkuznecovas** [comment]
> Let's say `--minimal-amount-to-invoice=0.1 MYST`. We can send invoices every 10 seconds or once in 10 minutes if we are ready to risk 0.1 MYST.

I like it.

**Comment by zolia** [comment]
I assume such `--minimal-amount-to-invoice=` should be fairly small. But how to treat invoice timeout in this case? If timeout is large then time it took to generate this "minimal-amount-to-invoice" ? Should timeout still be honoured and invoice ignored?
