### ISSUE TITLE
Refactor: BrokerPort should be configurable

### ISSUE THREAD

**Issue by zyfdegh** [mysteriumnetwork/node#226]
In `communication/nats/discovery/config.go`, broker port is currently hard-coding as

```
BrokerPort             = 4222
```

It impossible to change if broker (NATS) use a different port.

**Comment by Waldz** [comment]
Good idea, we could implement argument `--broker-port` save way as argument `mysterium_server --broker-address=127.0.0.1` is implemented.

Feel free to contribute to our repo

**Comment by tadovas** [comment]
Let's start with grouping related configuration options like broker.address and broker.port

**Comment by zyfdegh** [comment]
@Waldz Since `-broker-address` is address of broker, it's supposed to contain *host* and *port*. We can simply append the port in existing address. So I will put a PR later to parse the address and update the documents on how to use the flag and `.env`.
