### ISSUE TITLE
Discrepancy in token calculation

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2297]
0x117de425fd81515fe8b44b8df54b910288c36f93, 0.32.1

Made a manual calculation of total tokens earned during the specific period. For example, take a look at period starting from 5/24 00:00 until now. Simply making an approximate sum of all MMN sessions per day (counting GiB and minutes of sessions), I am calculating in total ±7MYSTT for data transferred and 0.1MYSTT for ±1900min.

Grafana shows 15MYSTT earned during that period.

Looking at earnings chart in MMN, there is another number: 115.483 (current earnings) - 97.63 (total earnings at 5/24) = 17.87MYSTT

**Comment by ignasbernotas** [comment]
I have double checked grafana/MMN, the display of data is correct, however the token amounts calculated for the transferred data/time are mismatching (@etherunit already did the math). If you sum session list columns for a node in MMN (`session_data` prometheus metric) it doesn't reach what's in `accountant_total_promised_amount`. Is this a bug? 

My guess is that there's a problem with `session_data` prometheus metric, but not sure how to validate this assumption.

@chompomonim @Waldz @vkuznecovas

**Comment by vkuznecovas** [comment]
I've investigated this a bit as well. I do think it's an issue with metrics/reporting of metrics. I have not, however, found the culprit.

**Comment by soffokl** [comment]
This provider is actively used by supernode. It's connected 24/7, so the time component is big here. 

I suspect that MMN does not correctly show session information. 
Take a look at the following session: 
![image](https://user-images.githubusercontent.com/8612618/83211307-966e8c80-a17e-11ea-92cf-94b041b52918.png)
![image](https://user-images.githubusercontent.com/8612618/83211349-b4d48800-a17e-11ea-8d1a-22798f626f5b.png)

https://grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-session=7acd5bc2-10fa-4f5d-b4be-bb4832182478&from=now-7d&to=now

**Comment by soffokl** [comment]
Another good example: 
![image](https://user-images.githubusercontent.com/8612618/83213173-51992480-a183-11ea-9f05-36891f72907f.png)
![image](https://user-images.githubusercontent.com/8612618/83213191-5cec5000-a183-11ea-94d4-a78b192cb816.png)
https://grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-session=a6f0779b-3a77-42dd-96c4-6067afdc13a5&from=now-7d&to=now

**Comment by vkuznecovas** [comment]
@soffokl makes a good point.

There seems to be a bug in how mmn generates the session list.

I suspect 
that the time values passed(to, from) are rather random, therefore the session info is not correct. https://github.com/mysteriumnetwork/my.mysterium.network/blob/master/app/Libraries/Prometheus/SessionRepository.php#L328

I'd suggest using the same queries that @soffokl has used in the dashboard:

To get the sessions:
`session_event{provider="0x117de425fd81515fe8b44b8df54b910288c36f93", event="Created"} == 1`
To get the session duration: 
`delta(timestamp(session_data{session_id="$session",direction="rx"})[$__range])-300`
To get the session data transfer:
`sum(increase(session_data{session_id="$session"}[$__range])<1000000000000)`
To get the myst earned:
`running_sum(sum(increase(session_tokens{session_id="$session"})))/100000000`

**Comment by ignasbernotas** [comment]
I have updated the token query to `sum by (session_id)(increase((session_tokens{provider="%s"} default 0)[%ss]))`. It's now returning more data, but still not all test sessions have tokens.
