### ISSUE TITLE
Add a Makefile for convenience

### ISSUE THREAD

**Issue by zyfdegh** [MysteriumNetwork/node#23]
Makefile will make it easier to build, run and test Mysterium, faster.

It may support subcommands with the following functions:

* Build Mysterium client (golang binary)
* Build Mysterium server (golang binary)
* Run Mysterium client (golang binary)
* Run Mysterium server (golang binary)
* Build Mysterium client (Docker image)
* Build Mysterium server (Docker image)
* ...

What do you think?

**Comment by zyfdegh** [comment]
done, closing

**Comment by Waldz** [comment]
Thanks @zyfdegh and welcome to contributors ;)
