### ISSUE TITLE
Consumer sees wrong balance after topup

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2303]
After topping balance, a consumer sees much more tokens than actually available.

Consumer: 0x76db93bf29861aef7f9bdf3c7c3a290d1afde0e5
Node version: v0.33.1 and master

On blockchain there are 8.47481362 MYSTT
https://goerli.etherscan.io/token/0x7753cfad258efbc52a9a1452e42ffbce9be486cb?a=0x19dF1ffA39a518c3682C6229f342CAb8a71Cb22f

Accountant reports about 7MYSTT balance
https://testnet-accountant.mysterium.network/api/v1/data/consumer/0x76db93bf29861aef7f9bdf3c7c3a290d1afde0e5

App shows 8.512 MYSTT

<img width="641" alt="Screenshot 2020-05-29 at 10 55 26" src="https://user-images.githubusercontent.com/153896/83236720-a1381a00-a19c-11ea-860e-003bfa720e4c.png">

**Comment by vkuznecovas** [comment]
Closing this as it's not reproducible and no logs are provided.
