### ISSUE TITLE
New way thinking about quality

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2304]
Our current quality metrics are less than not useful. They have a lot of problems and I think that we should start thinking about a new framework.

High:

Medium:
 - Speed: avarage+
 - 

Low:
 - connectable
 - have x % success of last 20 sessions 
- speed: any 

Not connectable: 0 quality. 

**Get feedback from user about his last connection:** 
 - Vote at the end of the session (rate your connection 1-5 stars).
 - Ask why stopped connection after 1/2 min. (possibility to choose a couple of "tags/icons" like in the uber app.
 - 

"Sticky provider"

**Comment by cvl** [comment]
I'd suggest to think about provider motivation to focus on quality.
I assume some folks try to run multiple nodes on their machine or lan.

Rather, it would be much better to have less, but quality nodes.

So I'd suggest to think about having some kind of coefficient/multiplier based on node reputation (time + quality + conn counts + data sent etc). So the more "mature" node provider has, the more cash he generates.

**Comment by chompomonim** [comment]
There is another quality related epic (#2597), closing this as duplicate.
