### ISSUE TITLE
Change icon for macOS app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2320]
<img width="467" alt="myst-icon" src="https://user-images.githubusercontent.com/153896/83487471-c2a64800-a4b3-11ea-8ab6-e6fcb3c94b43.png">

**Comment by tadaskay** [comment]
Fixed in https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/ff4ff9007a6789321ca8734370e59280d7cc2f9e
