### ISSUE TITLE
Connect fails to slow providers

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#2329]
looks like #2312 introduced another problem when connecting to slow providers fails prematurely. Sometimes connect to node takes ~30sec. I know this is unreasonably long, but probably we should allow such duration to take place. To solve issue for connect hanging forever we could set 2min or so dial timeout.

Also some progress feedback for a users on applications would be great. We could have some progress bar reflecting stages that were reached for given session in progress.

**Comment by soffokl** [comment]
@zolia Could you list such providers? I'd like to check why this is so slow.

**Comment by zolia** [comment]
Most likely not this one timeout hits, but 20 sec timeout on dial while sending / awaiting statues in `sendSessionStatus()` Can reproduce it only with mobile client so far.
You can use this RPI to test: 0x2bc8193504a60c1d9746006a9eb3ade5d6b7f51b

**Comment by anjmao** [comment]
For now I added connection traces which can be used to determine individual slow parts.
