### ISSUE TITLE
Build custom .msi installer with our named driver

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#2338]
In https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/36Currently we distribute Wintun driver from http://staging.openvpn.net/openvpn2/ 

Need to buil custom .msi installer with our named driver instance, reasons:
- According to Wireguard team instructions at https://github.com/WireGuard/wintun
- Probably it's a way to avoid conflict with other VPN applications installed/unnstalled on same machine

Links:
- [ ] https://github.com/WireGuard/wintun/tree/master/msi-example
- [ ] https://git.zx2c4.com/wireguard-windows/tree/installer

**Comment by chompomonim** [comment]
@tadaskay we still may have conflicts with other VPN applications.
