### ISSUE TITLE
Registration with topup

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2350]
At the moment while running app for the first time users don't have to topup. This will changes after mainnet release. Let's introduce this step now and show step where user will see topup wallet address (with QR code) with message that he needs to topup tokens. And on bottom of screen there could be button "Get testnet tokens" and message that while in testnet you can request free token topup. After clicking this, we're doing same request into transactor as we already automatically doing on network start.

**Comment by vkuznecovas** [comment]
@chompomonim no-one has to top up now, the top up is performed automatically via transactor. This means all flows have to change, including the transactor.
