### ISSUE TITLE
Force upgrade for android app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2351]
There should be a way to force users to upgrade into never version of our app.

There could be a service that would return a minimal acceptable version. On the app start, application would call this service and if it's version is less, then app should show a message for the user "you have to upgrade" and redirect it into Google Play. App should not allow to use it until migration into the new version.

**Comment by chompomonim** [comment]
@anjmao is this already done?

**Comment by chompomonim** [comment]
Could you write in comment short Readme what's to do to test it and how to use it in the future?

**Comment by anjmao** [comment]
Yes it's done. To test it you will need to bump version in https://github.com/mysteriumnetwork/api/blob/master/api/mobile.py#L4

It compares this version string with mobile app release tag https://github.com/mysteriumnetwork/mysterium-vpn-mobile/tags

I was testing it by running local app version in release mode.
