### ISSUE TITLE
Topup/wallet screen upgrades

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2353]
Wallet screen should be similar to desktop app. 

<img width="639" alt="Screenshot 2020-06-08 at 15 00 07" src="https://user-images.githubusercontent.com/153896/84028435-605cb400-a999-11ea-9ca8-2a5b2cde1ace.png">

**Comment by anjmao** [comment]
`Get free test tokens` button show only if there is 1 <= MYSTT.
