### ISSUE TITLE
Windows VPN DNS leak

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#2354]
Even if we configure static DNS address for VPN interface Windows will still try to resolve DNS by sending DNS requests to all active interfaces and using first arrived response. There are few ways how to solve this.

1. Configure other interfaces to use static non valid DNS something like
```
netsh interface IPv4 set dnsserver "Ethernet" static 0.0.0.0 both
```
Downside is that this approach requires to keep track of original DNS to be able to reset it back after disconnect.

2. Use **Windows Filtering Platform** which allows to block outside DNS so only tunnels DNS is used. This looks more correct, but API is available only in C/syscall and is quite complicated. Available example could be found [here](https://github.com/WireGuard/wireguard-windows/tree/master/tunnel/firewall)

**Comment by zolia** [comment]
IMHO we should go with 2nd option. Not sure about the general policy tho in win for such things. Found general overview of windows firewall functioning: 
https://docs.microsoft.com/en-us/windows/win32/fwp/basic-operation
https://docs.microsoft.com/en-us/windows/win32/fwp/windows-filtering-platform-architecture-overview
