### ISSUE TITLE
Intercom feedback with logs in desktop apps

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2360]
- [x] Hamburger menu
- [x] Intercom integration https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/43
- [x] Extensible side panel for intercom https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/44
- [X] Investigate log collection https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/45

**Comment by tadaskay** [comment]
Fixed in https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/45
