### ISSUE TITLE
 Expose info about terms of use accepting via API

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2364]
E.g. getting this info via config. Could be simply documentation how to access info from UI.

**Comment by Waldz** [comment]
- Show versioned terms from NPM package https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/d2dada4267a1898a56dc7e95c5a8714e6e6fc140
- Example how to accept terms: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/b22924922ee48645ffe47d5c23a6f8e3ee57a5e3

Terms should

**Comment by tadaskay** [comment]
This is app developer responsibility, nothing specific to node here. Tequilapi docs regarding app config should be enough.
