### ISSUE TITLE
Session duration calculation failed

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2375]
0x570a84ee052caad1911c6c7b4f1d5bf2d7cc0dae, 0.34.1, RPi
There are a number of transactions that are showing zero MYSTT.

Sample session:
91839032-d6f1-448e-84f8-4df2b8f31e9d, https://snapshot.raintank.io/dashboard/snapshot/8IdUVYl01XQal2n66c2DFu7T5gF13SmS

**Comment by etherunit** [comment]
one more provider 0xb3accee773f88eab42d6d4cc285e469b3b41a58c
session id ex: a7d9dac2-4524-4d28-b282-0931593b2f81

**Comment by etherunit** [comment]
Update:
node id: 0xbe1ee9ddea4cb2077f01ec64e3c15b7a9b4b558a
session id: 9aa74f2b-5f4a-403b-86cf-50dc861d0556

**Comment by vkuznecovas** [comment]
Seems like dup of #2388 ?

**Comment by soffokl** [comment]
Session `91839032-d6f1-448e-84f8-4df2b8f31e9d` [has](https://grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-session=91839032-d6f1-448e-84f8-4df2b8f31e9d&from=1591641817141&to=1591650785613) earnings 0.019573 for 201 MB.


Session `a7d9dac2-4524-4d28-b282-0931593b2f81` [has](https://grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-session=a7d9dac2-4524-4d28-b282-0931593b2f81&from=1591694729742&to=1591695891139
) earnings 0.012407 for 108 MB.

Session `9aa74f2b-5f4a-403b-86cf-50dc861d0556` [has](https://grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-session=9aa74f2b-5f4a-403b-86cf-50dc861d0556&from=1591973811300&to=1591974669667) earnings 0.000022 for 30 MB.
This node is running Node version: 0.32.1. I suggest to update it. 

All the sessions have earnings in the Grafana, but not shown in the MMN. This is the same problem that was discussed in the 
https://github.com/mysteriumnetwork/node/issues/2297. I suggest using more accurate queries in the MMN to resolve it.
