### ISSUE TITLE
Send desktop app analytics into prometheus

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2376]
- [x] Deploy analytics service
- [X] Send to the new service instead of Google Analytics (desktop) https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/97
- [ ] ~Send to the new service instead of Google Analytics (mobile)~ https://github.com/mysteriumnetwork/node/issues/3130
- [ ] ~Add an option to opt-out from sending events in configs~ https://github.com/mysteriumnetwork/node/issues/3131

**Comment by tadaskay** [comment]
As discussed with many, we shall give matomo analytics a try - for one, prometheus is not for events, and also it provides applications analytics out of the box. If it doesn't stick, we can consider parsing events from loki.
