### ISSUE TITLE
Cannot connect to nodes from Linux CLI

### ISSUE THREAD

**Issue by NeverVane** [mysteriumnetwork/node#2377]
I cannot succeed in connecting to any node from the Linux CLI.

I have installed the linux package, created an identity, unlocked & registered and everything went just fine.
But when I try to connect :
connect <my_identity> <provider_identity> <protocol> <dns>
I always get this error (I have tried from multiple machines):

<img width="1030" alt="Schermata 2020-06-10 alle 12 19 31" src="https://user-images.githubusercontent.com/40278940/84256877-d0dc1000-ab14-11ea-9b35-31eed4365065.png">

<img width="1030" alt="Schermata 2020-06-10 alle 12 19 46" src="https://user-images.githubusercontent.com/40278940/84256930-e3564980-ab14-11ea-8e04-5bb596d2446d.png">

and if trying to connect using noop will actually say [SUCCESS]

<img width="1030" alt="Schermata 2020-06-10 alle 12 22 58" src="https://user-images.githubusercontent.com/40278940/84257193-3defa580-ab15-11ea-9659-7ff36672f309.png">

I'm trying to connect on a fresh Ubuntu 18.04 installation with 3.4.0 CLI

**Comment by soffokl** [comment]
Some more context required to figure out what is wrong. 
How did you install the package? How the daemon is running?
It looks like you are running myst with incorrect configuration.

**Comment by NeverVane** [comment]
I installed the package using 

sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"

**Comment by soffokl** [comment]
This starts a myst in the service mode for providers, not consumers. 
It's not possible to be a provider and a consumer at the same time for now.

You still can reconfigure it to use in the consumer mode:

Edit the `/lib/systemd/system/mysterium-node.service` file. 

Replace the following line: 
`ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS service --agreed-terms-and-conditions $SERVICE_OPTS`
with:
`ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS daemon`

After that, you can just reboot the host or do the following:
`sudo systemctl daemon-reload`
`sudo systemctl restart mysterium-node`

And you should be able to use it in the consumer mode and successfully establish a connection.

**Comment by NeverVane** [comment]
I'll try it thanks

**Comment by NeverVane** [comment]
Same error here 

<img width="1009" alt="error myst" src="https://user-images.githubusercontent.com/40278940/84261403-ff111e00-ab1b-11ea-88b2-bedb9eae82f9.png">

**Comment by soffokl** [comment]
yep, correct you can use `myst cli`. 

Could you please attach logs to the issue? It will show more details about the problem. 
You can get it with a `sudo journalctl -u mysterium-node` command.

**Comment by NeverVane** [comment]
yes, here they are

[logs-linux-cli-issue.log](https://github.com/mysteriumnetwork/node/files/4758098/logs-linux-cli-issue.log)

**Comment by soffokl** [comment]
Try to add the following line to the `/etc/sudoers.d/mysterium-node` file:
`mysterium-node    ALL=NOPASSWD: /sbin/resolvconf`

And try to connect one more time.

It's not used in the provider mode, but for consumers it's required.

**Comment by NeverVane** [comment]
this made the trick
