### ISSUE TITLE
Run OpenVPN service over TCP by default

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2378]
In some networks UDP may be firewalled and we should have TCP alternative for our users.

As WireGuard is usually faster and more stable it should be our main option. And the main reason for using OpenVPN is when you need to open TCP based tunnel.

**Comment by tadaskay** [comment]
Prerequisite is to implement openvpn support consumer side in `--usermode`

**Comment by z3r0d0n3** [comment]
> In some networks UDP may be firewalled and we should have TCP alternative for our users.
> 
> As WireGuard is usually faster and more stable it should be our main option. And the main reason for using OpenVPN is when you need to open TCP based tunnel.

google about TCP Meltdown please

**Comment by chompomonim** [comment]
@z3r0d0n3 we're aware of that. We simply need fallback option for those who can't use UDP. We are also considering various other options. E.g. transparent proxies and SOCKS5.

**Comment by zolia** [comment]
Main issue here that we don't have TCP nat hole punching mechanics.. this would prevent node runners without port forwarding or public IP running such service, that is about 90% of all node runners.
