### ISSUE TITLE
Add consumer service for Linux

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#2380]
Some users want to run Mysterium node in the consumer mode: https://github.com/mysteriumnetwork/node/issues/2377

We can add additional service(disabled by default), configured for consumer, to allow it without big changes in the system. 

User should be able to switch to the consumer mode only by following commands:
`systemctl stop mysterium-node`
`systemctl start mysterium-consumer`

**Comment by tadaskay** [comment]
Doesn't desktop app cover this use case?

**Comment by soffokl** [comment]
@tadaskay no, there could be just a server without a desktop environment.
