### ISSUE TITLE
Registration error thrown prematurely

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2382]
1) Install fresh app
2) Click connect while InProgress state
3) Click disconnect
4) Identity status changes to RegistrationError
5) After 10-20 seconds it changes back to RegisteredConsumer

I assume it fails initially because the app is in connecting/disconnecting state.

**Comment by cvl** [comment]
CC: @chompomonim

**Comment by chompomonim** [comment]
Which version of android app do you use?

**Comment by cvl** [comment]
Latest

**Comment by cvl** [comment]
Try this:
- Uninstall app (if installed)
- Download app from Play store
- Install app
- Click connect right after install (i.e. not after few minutes)
- Click disconnect
- Click connect to the same provider -> you'll get an error

This is happening with 0.37.0 node as well.

**Comment by vkuznecovas** [comment]
This seems to be android specific. I could not reproduce on node with wg/openvpn.

**Comment by tomasmik** [comment]
> This seems to be android specific. I could not reproduce on node with wg/openvpn.

Yes it seems like it's android specific bug. I could reproduce this following instructions above. @tadaskay could you look at this please.
It doesn't seem too critical because after registration is actually over, you can continue using your app no problem.

**Comment by cvl** [comment]
Was this resolved?

**Comment by chompomonim** [comment]
Thi is very old issue. We reworked our registration process couple of times already. If you'll get such issue again, please open new ticket.
