### ISSUE TITLE
Provider DNS randomly fails and returns no answers

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#2387]
**Describe the bug**
Some providers fail to resolve DNS when using the default connection setting (auto, which effectively tries provider DNS proxy first). DNS works/stops working seemingly at random.

**To Reproduce**
1. Open desktop app
2. Select Residential / US
3. Try all of the providers
4. Some of the providers fail to resolve DNS
5. Retry those providers: some of them will start resolving DNS

**Expected behavior**
DNS is consistently resolved

**Environment (please complete the following information):**
 - Node version: master
 - Desktop app version: master
 - OS: macOS and windows - consumer

**Comment by tadaskay** [comment]
Waiting for provider logs, that may give us some clue (errors should be logged as warning on the provider side).

**Comment by tadaskay** [comment]
Should re-test this with the nodes upgraded to 0.35.3

**Comment by etherunit** [comment]
connected 2.3.3 Mac app > 0.35.3 node (0x64c54964dca1745b761d0c17a7299b87edde3d31) got same results- still (Updating..)
<img width="644" alt="Screenshot 2020-07-07 at 17 28 04" src="https://user-images.githubusercontent.com/60128746/86796428-3f11e500-c077-11ea-930c-206f11fa4453.png">

Node logs https://my.mysterium.network/admin/issues/download/768
https://github.com/mysteriumnetwork/node-user-reports/issues/768

let me know if any additional information is required.

**Comment by etherunit** [comment]
Connecting from 2.3.4 Mac app to 0.36.2 node.. Still Updating.. but internet is working.
<img width="638" alt="Screenshot 2020-07-15 at 10 43 29" src="https://user-images.githubusercontent.com/60128746/87517795-1184f700-c688-11ea-9023-c5585b332738.png">
<img width="705" alt="Screenshot 2020-07-15 at 10 42 43" src="https://user-images.githubusercontent.com/60128746/87517725-f1edce80-c687-11ea-8b51-e285614cec82.png">

**Comment by tadaskay** [comment]
As already explained, "Updating" had nothing to do with connectivity. It should be fixed in 2.5 by the way.

**Comment by soffokl** [comment]
I did a number of tests on Windows and MacOS, and everything seems to work fine without any issue. 
I'll close this issue. 
Let's enable provider DNS by default for everyone to make sure we don't have this issue anymore.
