### ISSUE TITLE
Node fails to start upon reboot

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2397]
0xdd661645e8754a0e833bcec3b86966290bf963cf, 0.34.1, RPi
The Mysterium node service sometimes does not start correctly after host reboot. Manual service 
start fix the issue. 

[after_manual_service_restart.log](https://github.com/mysteriumnetwork/node/files/4802553/after_manual_service_restart.log)
[after_reboot.log](https://github.com/mysteriumnetwork/node/files/4802555/after_reboot.log)

**Comment by zolia** [comment]
```
Jun 18 08:05:49 pinkberry systemd[1]: mysterium-node.service: Main process exited, code=exited, status=1/FAILURE
Jun 18 08:05:49 pinkberry systemd[1]: mysterium-node.service: Failed with result 'exit-code'.
Jun 18 08:05:50 pinkberry systemd[1]: mysterium-node.service: Service RestartSec=100ms expired, scheduling restart.
Jun 18 08:05:50 pinkberry systemd[1]: mysterium-node.service: Scheduled restart job, restart counter is at 2.
```

Looks like we lack some logs. Could we get /var/log/daemon output for this time period?

**Comment by etherunit** [comment]
will request from provider.
