### ISSUE TITLE
How to use client in Maxos?

### ISSUE THREAD

**Issue by jiffies** [mysteriumnetwork/node#24]
I have download https://github.com/MysteriumNetwork/node/releases/download/0.0.6/mysterium_client_osx_amd64,
but I don't know how to use it.

**Comment by davidgibbons** [comment]
It looks like it's a pre-compiled binary
`$ chmod +x mysterium_client_osx_amd64
12:39:50 ~/Downloads $ ./mysterium_client_osx_amd64
Missing VPN node key!
12:39:51 ~/Downloads $ ./mysterium_client_osx_amd64 --help
Usage of ./mysterium_client_osx_amd64:
  -node string
    	Mysterium VPN node to make connection with
  -runtime-dir string
    	Runtime directory for temp files (should be writable) (default ".")
flag: help requested`

**Comment by zyfdegh** [comment]
I ran mysterium client and it's started correctly. Then I typed `mysterium_client --cli` and entered the interactive cli.

```
./mysterium_client -cli                                                                                                                                            (gke_linker-aurora_asia-east1-a_aurora-dev/default)
» help
[INFO] Mysterium CLI tequilapi commands:
  connect
  identities
  ├── new
  ├── list
  status
  proposals
  ip
  disconnect
  help
  quit
  stop
  unlock

»
```

**Q1:** It's confusing, do the VPN users need to be familiar with these commands?

Then I tried `identities new` and a <consumer-identity> was created, afterward I typed `unlock <consumer-identity>`, `connect <consumer-identity> <provider-identity>` to connect to the server, but it failed:

```
2018-04-12T09:12:09.489494809 [Error] [Tequilapi.Client]server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/connection)
[WARNING] open /Users/me/.mysterium/run/client.ovpn: no such file or directory
```

**Q2:** I realized the `client.ovpn` file is missing, so how will I retrieve/generate this file? 

I searched Google and find this page https://openvpn.net/index.php/access-server/docs/admin-guides/183-how-to-connect-to-access-server-from-a-mac.html

**Q3:** Do I need to install *Tunnelblick* and continue?

Hope for your help, thanks.

**Comment by tadovas** [comment]
**A1**: No they don't. It's just cli for command line enthusiasts, and more like demonstration of tequilapi
**A2**: Just make sure that /Users/me/.mysterium/run directory exists and is readable/writable by you - or you can create PR to automatically create runtime dir :)
**A3**: No you don't need to install tunnelblick. BUT your system must have openvpn available `brew install openvpn`

I hope it helps :)
