### ISSUE TITLE
Improve connect speed

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2400]

**Comment by soffokl** [comment]
Overall connection speed looks ok:
![image](https://user-images.githubusercontent.com/8612618/86428707-3cc62880-bd0f-11ea-95ee-736bd6c560c2.png)

But for Windows, it looks much slower:
![image](https://user-images.githubusercontent.com/8612618/86428828-87e03b80-bd0f-11ea-9193-e99dce70919d.png)

And some more details about session stages:
![image](https://user-images.githubusercontent.com/8612618/86428882-ab0aeb00-bd0f-11ea-93f9-b0113de84889.png)

**Comment by soffokl** [comment]
Overall connection speed looks ok. I'm closing this issue.
Let's open a new one for every specific case of the slow connection.
