### ISSUE TITLE
[android, question] how to get access of identity private key file on mobile

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2413]

**Comment by cvl** [comment]
CC: @anjmao @chompomonim

**Comment by anjmao** [comment]
Base path is set [here](https://github.com/mysteriumnetwork/mysterium-vpn-mobile/blob/master/android/app/src/main/java/network/mysterium/service/core/MysteriumAndroidCoreService.kt#L181) using `filesDir.canonicalPath`

**Comment by cvl** [comment]
Thanks!
