### ISSUE TITLE
Installation Link & Download

### ISSUE THREAD

**Issue by ngx3** [mysteriumnetwork/node#243]
I can't find the download link for Ubuntu and all the installation guides have broken links.

Can this work with a standard vps or is true cloud needed?

**Comment by zolia** [comment]
Hello ngx3, 

try reading our [FAQ](https://github.com/MysteriumNetwork/node/wiki/Node-operation) section.

Basically if You want to run via docker, Your OS, should support it. It means you want Linux kernel >= 3.10
