### ISSUE TITLE
[android, question] increasing minSdkVersion increases app size by 3x

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2431]
After minSdkVersion was increased from 19 to 24, the app size increased from 70 MB to 170MB.

Is there any need for minSdkVersion=24 ?

CC: @anjmao

**Comment by tadaskay** [comment]
Android 6.0 (API level 23)
Revision 1 (August 2015)

I don't see any sensible reason for supporting APIs even older than that.

https://play.google.com/store/apps/details?id=network.mysterium.vpn

Updated
June 30, 2020
Size
**67M**
Installs
10,000+
Current Version
0.35.1
Requires Android
**7.0 and up**

The app size is 67M
