### ISSUE TITLE
RPI as consumer

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#2434]
It would be very convenient to have MN VPN client which would cover all private LAN.
One way to approach it is to have plain RPI. Plug ethernet end to home router and expose Wifi for local appliances. 

![image](https://user-images.githubusercontent.com/13434315/86326981-28205c80-bc4b-11ea-9a1b-14096853668c.png)

When streaming or other unblocking is required - simply switch WiFi.

In the future, MN node could act as a dual provider / consumer node, thus covering expenses for consumed traffic while providing VPN services for others.

**Comment by manfromdownunder** [comment]
You could also maintain a streaming services host/ip list and split tunnel
