### ISSUE TITLE
Export/Import private keys via CLI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2448]
It should be possible to import/export private key via CLI. We should not use tequilla for that. Also please ask user to type password for PrivKey backup (at least 12 symbols) as it should be never backoups with empty passwords. User should be able to set backup file destination, by default it could be the path from which the command was run. 

- [x] CLI to export encrypted private key.
- [x] CLI to import private keys (should be endrypted and decrypted).
- [x] Add/update documentation page how to make a privkey backup and how to download it to your machine (if its in docker, rpi or remote server)

**Comment by tadaskay** [comment]
What are the measures to prevent anything running on local machine from dumping the private keys? With it being exposed via tequila, it becomes even easier, does it not?

**Comment by chompomonim** [comment]
I agree with @tadaskay comment. CLI could simply encrypt private keys and copy then into give location. We don't need tequila for that.

**Comment by Zensey** [comment]
In the interactive CLI there are already exist commands: 
  export <identity> <new_passphrase> [file]
  import <passphrase> <key-string/key-file>

**Comment by Zensey** [comment]
So the point is -- this commands need to run w/o tequilla api ?

**Comment by chompomonim** [comment]
I command is already there, maybe then we're simply missing documentation ;)
BTW is adding password is already there?

**Comment by Zensey** [comment]
> I command is already there, maybe then we're simply missing documentation ;)
> BTW is adding password is already there?

Yes, password is required for both import and export, but length is not validated. 
So, we need a password length check and documentation update.
