### ISSUE TITLE
Run second monitoring agent from behind the NAT

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2456]
There are quite a few cases when the monitoring agent is able to connect, but users can't. It can happen due to monitoring agent being run on datacenter and users devices are behind many kinds of different NATs.

Let's have RPi which would use a mobile router to run such tests as a second monitoring agent.

**Comment by MysteriumTeam** [comment]
Monitoring agent running myst in docker container, which is behind NAT. No port forwarding done there.

**Comment by soffokl** [comment]
Monitoring agent running myst in docker container, which is behind NAT. No port forwarding done there.

**Comment by chompomonim** [comment]
Any ideas what else we can do to see more real situation and why many people (even myself) can't connect to "connectable" nodes?

**Comment by soffokl** [comment]
It requires investigation in every specific case. Let's create an issue with exact details about node ID and error description. 
It's hard to say was went wrong in these cases without knowing details.
