### ISSUE TITLE
Add log dump to error reporting

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2466]
Sometimes it would be very useful to get log dumps from user computer (app logs, node logs) to investigate the cause of problem.

**Comment by cvl** [comment]
@chompomonim I can see that you have log dump in the node code.

So it would be as easy as expose this via node api, so any client can use this feature.

**Comment by cvl** [comment]
atm customers just tell me "I can't connect", and that's how it ends.

**Comment by chompomonim** [comment]
We have error logs reporting service (called `feedback` and opensourced in our GitHub). In our UI you have possibility to report logs. So we're exposing it via API. I think you simply would need to run own such service and update your app configs to use your own feedback service.

**Comment by cvl** [comment]
Are you referring to this api https://tequilapi.mysterium.network/#tag/Feedback ?

This would send the dump to Mysterium team.

**Comment by chompomonim** [comment]
You can reconfigure your app so it would send dump to yourself.

**Comment by cvl** [comment]
Clarified this a bit more in a feature request: https://github.com/mysteriumnetwork/node/issues/2871

**Comment by chompomonim** [comment]
@vkuznecovas is there easy way how to configure our node so it would send logs to arbitrary `feedback` service?

**Comment by cvl** [comment]
> You can reconfigure your app so it would send dump to yourself.

Any hints on how to do that? Haven't find the way looking at the source code.
