### ISSUE TITLE
Test 0.37-rc

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2471]
We're going to release 0.37 release early next week. Here is list of things to test before release:

- [x] Node’s webUI should be not accessible when consumer is connected into node.
- [x] 0.35 consumer -> 0.37 provider
- [x] 0.37 consumer -> 0.36 provider
- [x] 0.37 consumer -> 0.37 provider
- [x] Latest android app -> 0.37 provider
- [x] Latet macOS desktop app ([2.4](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/2.4.0)) -> 0.37 provider
- [x] Latet windows desktop app ([2.4](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/2.4.0)) -> 0.37 provider

**NOTES**
- In all tests consumer should connect and pay for traffic
- Ideally if you'll test sessions for at least 20 minutes.
- Also would be good to test (0.37 -> 0.37) OpenVPN connection via CLI.
- For old consumer you can use android and desktop apps

Current latest release candidate version is https://github.com/mysteriumnetwork/node/releases/tag/0.37.0-rc3

**Comment by etherunit** [comment]
[Android 0.36.2]
My node (0x409b5c902d26d4c5250dce8cbd574bd0cbe2b8cb) was visible in Android app.
Once I've changed node (0.37.0-rc3) service price to custom 0.5/0.001 and did `sudo systemctl restart mysterium-node`, my node dissapeared from the list (price filters are set and applied to the max.)
Once I set back to defaults in WebUI, node appears on the list again.

p.s. no such issues with desktop applications.

**Comment by etherunit** [comment]
Latet macOS desktop app (2.4) -> 0.37 provider, works fine, consumer pays for traffic
<img width="647" alt="Screenshot 2020-07-17 at 15 59 31" src="https://user-images.githubusercontent.com/60128746/87788837-b816f680-c846-11ea-8e9c-a820a12a5ff1.png">

Logs: https://my.mysterium.network/admin/issues/download/806

**Comment by etherunit** [comment]
Lates
![Myst (1)](https://user-images.githubusercontent.com/60128746/87789127-307db780-c847-11ea-923a-0a381a8a1cda.png)
t windows desktop app (2.4) -> 0.37 provider







Logs: https://my.mysterium.network/admin/issues/download/806

**Comment by etherunit** [comment]
0.37 consumer -> 0.36 provider (0xa49dc8f21aa4ff42caaf0e69009b7d88935b86e4) works fine
 0.37 consumer -> 0.37 provider (0x64c54964dca1745b761d0c17a7299b87edde3d31) > works fine
