### ISSUE TITLE
Prepare Prometeus for new token

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2472]
New token will use e18 instead of e8, so uint64 is not enough. We should make sure that Prometeus will work properly with new MYSTT token.

**Comment by vkuznecovas** [comment]
This is matter of gathering the metrics. The metrics should be sent as a float64, meaning that all the values that are submitted to the prom would display whole myst, i've already added a util for that: https://github.com/mysteriumnetwork/payments/blob/0fdb6c914650d315d6d74548d8d145ec8577520f/crypto/helpers.go#L31
