### ISSUE TITLE
[feature request, desktop] make it possible to use another folder than .mysterium

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2480]
Currently if user is using MysteriumVPN and Portals at the same time, those two apps would clash, as they would use same .mysterium folder.

**Comment by tadaskay** [comment]
So use a different folder for portals. Everything is configurable via flags. config-dir, data-dir, log-dir, runtime-dir, etc. 
I don't see anything to be done here from our side.

**Comment by cvl** [comment]
Could you elaborate on how to set those flags.

Should this be passed to supervisor (e.g. "--config-dir=xx")?

**Comment by tomasmik** [comment]
Yes Tadas is correct, you can find them here: https://github.com/mysteriumnetwork/node/blob/master/config/flags_directory.go#L29

It should be passed to node on start up or set in node config. To get full list of flags available try running `myst --help`

**Comment by cvl** [comment]
Perfect, thanks.

**Comment by tomasmik** [comment]
To give you even more information.  Starting node daemon like this:
```
myst --data-dir /tmp/node-data --config-dir /tmp/node-data daemon
```
Configures it like this:
```
myst@ubuntu:~/go/src/github.com/mysteriumnetwork/node$ build/myst/myst config show | grep dir
config-dir: /tmp/node-data
data-dir: /tmp/node-data
....
```

**Comment by cvl** [comment]
Great.
Perhaps myst/supervisor process is also configurable, so both apps wouldn't conflict?
I assume changing process names wouldn't be enough, as it creates launch daemon for supervisor with mysterium classpath.

**Comment by cvl** [comment]
I believe the flags handling implementation could be improved:

If I set data-dir to e.g. .portals, but omit overriding other flags (e.g. logs location), it will still write to .mysterium/logs.
The correct behavior would be to use data-dir as the base (as is correctly implemented now, but only when defaulting to .mysterium e.g. https://github.com/mysteriumnetwork/node/blob/3029005d30c70a9dbb39abafb19465e8fbdaec02/config/flags_directory.go#L69

I can override all the flags now, but if you happen to add more flags in the future, then this will fail for me, as I wouldn't know that you've added them. Of course I can try to track this file each on each node version change to see if you've changed something, but this is still an "invitation for error".

This is low priority of course, could be given to some intern developer to fix. (atm I don't know go language, so can't provide a quick fix proposal).
