### ISSUE TITLE
Session earnings miscalculated

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2492]
**Describe the bug**
Provider (0x7a513f20dc9400a80bbbb23e5562dafd81c778b7) is claiming that session earnings is not calculated correctly in 0.37rc
Session id: 884c319a-b397-4e0b-b08d-cb90fb345d08
Current service price: 0.5MYSTT/GiB & 0.001MYSTT/min.

_Current earnings: 10h, data: 1.12GB, Earnings: 0.1783MYSTT._ 
**Should be: 1.12x0.5+600x0.001=1.16MYSTT**

**Expected behavior**
A provider is being paid according to the set service price.

**Screenshots**
<img width="1304" alt="Screenshot 2020-07-21 at 14 08 39" src="https://user-images.githubusercontent.com/60128746/88048286-b9ecfc80-cb5b-11ea-9674-5c0ff38a75f1.png">

**Environment (please complete the following information):**
 - Node version: 0.37
 - OS: RPi

**Comment by vkuznecovas** [comment]
The question here is was the price the same at the time when the session happened?

I've looked at recent sessions, and they seem to be priced what they are supposed to be priced at. It seems to me that the the provider had set a different price at the time. 

There are a couple of types of proposals online at the moment, ones charge 0.5myst/GB while others charge 0.1myst/GB. 

The session you're talking about probably happened when the provider had the price set to 0.1myst/GB. The current sessions are charged according to the price.
