### ISSUE TITLE
Monitoring agent checks have no traffic

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2504]
**Describe the bug**
Monitoring agent checks have no traffic & payments but node is showing online. 
0xdd9908a9bf2adbea4907ab34ca3773f06b132e55

**Screenshots**
<img width="1393" alt="Screenshot 2020-07-24 at 09 13 22" src="https://user-images.githubusercontent.com/60128746/88366953-39184580-cd93-11ea-9b04-15d3ba7f972b.png">

**Environment (please complete the following information):**
 - Node version: [0.32.1]
 - OS: Alpine Linux v3.11

**Comment by vkuznecovas** [comment]
Running a very old version of node, therefore session establishing will fail. Not a bug, needs to update.

Node version:
0.32.1
