### ISSUE TITLE
[android, bug] can't disconnect after migrate-to-network-call

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2537]
After https://github.com/mysteriumnetwork/mysterium-vpn-mobile/commit/ab722feee485d00ee212503f5bdb6d3483d66ca3

Reproducible on phone (not emulator):

1. Install fresh app (or after app relaunch)
2. connect
3. disconnect:
After clicking disconnect - state text flickers (connecting… / disconnecting) (probably attempting to reconnect), the app is left in “Connecting…” state, error message “No internet connection” is displayed. After 1 minute, it becomes “Connected”, error message “No internet connection” is still present.

CC: @tadaskay

**Comment by tadaskay** [comment]
Can't reproduce with your scenario.

**Comment by etherunit** [comment]
Tried several times with several nodes but could not reproduce step 3.

App: 0.37.6
Device: Huawei Y7
Android: 8

**Comment by cvl** [comment]
This was fixed with https://github.com/mysteriumnetwork/mysterium-vpn-mobile/commit/7b35d4dcd3ed897ca315e2d8a15c9f52693f9a46
