### ISSUE TITLE
Session disconnects after 2 mins

### ISSUE THREAD

**Issue by arpitjindal97** [mysteriumnetwork/node#2547]
**Describe the bug**
Any connection made to the node gets disconnected automatically after 2 minutes

**To Reproduce**
Simple installation on RPI running ubuntu 18

**Expected behaviour**
Session should last as long as client doesn't click disconnect

**Screenshots**
![image](https://user-images.githubusercontent.com/15676216/89100546-5ee9be00-d415-11ea-810e-274358da306f.png)

![image](https://user-images.githubusercontent.com/15676216/89117218-cfe2b180-d4b9-11ea-9d6a-899c5ce529c1.png)

**Environment :**
 - Node version: 0.37.0
 - OS: Ubuntu 18.04
- Node: 0xadb458ce5296caf0a64531a7d15c643d94f50ce5

**Comment by etherunit** [comment]
Thank you @arpitjindal97 for creating this issue. I am adding your node logs for reference. 

https://my.mysterium.network/admin/issues/download/834

**Comment by zolia** [comment]
Hello, 

@arpitjindal97 can you elaborate a bit more about your setup? What kind of router is between you and your ISP? Does you ISP provide you with an external IP or it is a private one? 

From what I see and understand from logs is that our signalling channel stops working and keep-alives fails. This is most likely due to strict NAT rules requiring frequent symmetric packet exchange to be able to maintain datagram tunnel. 

please refer to fix: https://github.com/mysteriumnetwork/node/pull/2549

We will release patch version of a node for you to try it out.

**Comment by arpitjindal97** [comment]
I have 2 routers. My ISP provides public IP. Setup is like this 

Router 1 (with Public IP) --> Router 2 (NAT) --> RPI

2 NATS are there. I have done Port forwarding of port `1194` also to Public IP. Still it's working on UDP only.

**Comment by arpitjindal97** [comment]
I have TP-link router, which doesn't allow changing UDP timeout. 

https://community.tp-link.com/en/business/forum/topic/167412

Although, it is written default timeout is 180s but expiring early.

**Comment by etherunit** [comment]
Update:

Provider 0x0fcb730b802d943b23caa1d7252199e5d4c26051 also facing similar issues with p2p.

`Aug 02 18:20:10 nzbdrone myst[18686]: 2020-08-02T18:20:10.946 ERR source/session/manager.go:190 > Payment engine error error="sending of invoice failed: did not sent a new exchange message"
Aug 02 18:20:10 nzbdrone myst[18686]: 2020-08-02T18:20:10.947 DBG source/session/pingpong/invoice_tracker.go:621 > Stopping...
Aug 02 18:20:10 nzbdrone myst[18686]: 2020-08-02T18:20:10.959 DBG source/consumer/session/session_storage.go:236 > Session bb3f4de2-cf4d-41d8-a0a3-ab363e3335c6 updated with final data
Aug 02 18:20:15 nzbdrone myst[18686]: 2020-08-02T18:20:15.348 ERR source/session/manager.go:289 > Failed to send p2p keepalive ping. SessionID=bb3f4de2-cf4d-41d8-a0a3-ab363e3335c6 error="timeout waiting for reply to \"p2p-keepa
Aug 02 18:20:52 nzbdrone myst[18686]: 2020-08-02T18:20:52.285 INF source/nat/mapping/port_mapping.go:149 > Mapped network port: 46874`

**Comment by zolia** [comment]
@arpitjindal97 please try upgrading to this one: https://github.com/mysteriumnetwork/node/releases/tag/0.38.0

and give us feedback.

Antanas

**Comment by arpitjindal97** [comment]
Resolved
