### ISSUE TITLE
Failed to sent batch metrics

### ISSUE THREAD

**Issue by xospecialk** [mysteriumnetwork/node#2554]
**Describe the bug**
Not getting any connections on 0.38.0, clients disconnect after 1m.  Not sure if the errors below are related

> Aug 04 09:49:05 nzbdrone myst[1701]: 2020-08-04T09:49:05.027 INF source/services/openvpn/service/manager.go:163 > OpenVPN server waiting
> Aug 04 09:49:06 nzbdrone myst[1701]: 2020-08-04T09:49:06.269 DBG source/session/pingpong/accountant_promise_handler.go:120 > accountant promise handler started
> Aug 04 09:49:06 nzbdrone myst[1701]: 2020-08-04T09:49:06.367 INF source/market/mysterium/mysterium_api.go:166 > Proposal registered for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: wireguard
> Aug 04 09:49:06 nzbdrone myst[1701]: 2020-08-04T09:49:06.377 INF source/market/mysterium/mysterium_api.go:166 > Proposal registered for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: openvpn
> Aug 04 09:49:13 nzbdrone myst[1701]: 2020-08-04T09:49:13.431 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:16 nzbdrone myst[1701]: 2020-08-04T09:49:16.751 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:17 nzbdrone myst[1701]: 2020-08-04T09:49:17.917 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:21 nzbdrone myst[1701]: 2020-08-04T09:49:21.947 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:23 nzbdrone myst[1701]: 2020-08-04T09:49:23.120 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:24 nzbdrone myst[1701]: 2020-08-04T09:49:24.438 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:24 nzbdrone myst[1701]: 2020-08-04T09:49:24.441 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:24 nzbdrone myst[1701]: 2020-08-04T09:49:24.447 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:49:24 nzbdrone myst[1701]: 2020-08-04T09:49:24.449 ??? github.com/rs/zerolog@v1.17.2/log.go:403 > http: proxy error: context canceled
> Aug 04 09:52:06 nzbdrone myst[1701]: 2020-08-04T09:52:06.792 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: openvpn
> Aug 04 09:52:06 nzbdrone myst[1701]: 2020-08-04T09:52:06.806 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: wireguard
> Aug 04 09:55:22 nzbdrone myst[1701]: 2020-08-04T09:55:22.209 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: openvpn
> Aug 04 09:55:22 nzbdrone myst[1701]: 2020-08-04T09:55:22.229 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: wireguard
> Aug 04 09:58:22 nzbdrone myst[1701]: 2020-08-04T09:58:22.620 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: openvpn
> Aug 04 09:58:27 nzbdrone myst[1701]: 2020-08-04T09:58:27.654 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: wireguard
> Aug 04 09:58:36 nzbdrone myst[1701]: 2020-08-04T09:58:36.068 ERR source/core/quality/mysterium_morqa.go:112 > Failed to sent batch metrics request error="Post https://quality.mysterium.network/api/v1/batch: dial tcp: lookup quality.mysterium.network on 208.67.222.222:53: no such host"
> Aug 04 10:01:23 nzbdrone myst[1701]: 2020-08-04T10:01:23.006 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: openvpn
> Aug 04 10:01:28 nzbdrone myst[1701]: 2020-08-04T10:01:28.046 INF source/market/mysterium/mysterium_api.go:203 > Proposal pinged for node: 0x0fcb730b802d943b23caa1d7252199e5d4c26051 service type: wireguard

**Environment (please complete the following information):**
 - Node version: 0.38.0
 - OS: raspbian buster
 - Desktop app version (if applicable): NA
 - Docker (if applicable): NA

**Additional context**

**Comment by vkuznecovas** [comment]
Please upgrade to the latest node version(0.41.8). You're running a node in the legacy network, which is no longer supported and will be discontinued in the near future.
