### ISSUE TITLE
Cut designs of Wallet views of WebUI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2588]
Create non actionable .jsx and .css for Wallet and Settings views

<img width="1680" alt="Settings" src="https://user-images.githubusercontent.com/153896/91201506-30f05480-e709-11ea-8f48-a362cd04bb64.png">

![Wallet](https://user-images.githubusercontent.com/153896/91201556-406f9d80-e709-11ea-9115-ce7f57a6cbac.png)

**Comment by elstringer** [comment]
is it possible to be able to manage the api (tequila api) from the panel? 
 as well as provide for the possibility of translations in several languages
 ​​(I am available for translation into French)

**Comment by chompomonim** [comment]
@elstringer we'll think about multilang support in webui. It will be not done in initial release, but we may add it a little later.

And according "able to manage the api" I not exactly get what do you mean? Could you elaborate on your use-case?

**Comment by chompomonim** [comment]
@VarnasV is this already done? What is your status on this task?

**Comment by VarnasV** [comment]
> @VarnasV is this already done? What is your status on this task?
a couple of places left to finish in the wallet screen. Sessions and settings are done.
