### ISSUE TITLE
WebUI password reset

### ISSUE THREAD

**Issue by dpellegr** [mysteriumnetwork/node#2623]
Is there a way to, having full access to the server running node?

**Comment by chompomonim** [comment]
Could you elaborate? Do you already run mysterium node? You do that on RPi? Or you simply want to hack server which is running mysterium node? :)

**Comment by dpellegr** [comment]
Sorry, maybe I was too cryptic.

The node is already up and running (on a linux server in a docker container).
To this server, I have admin access.

I have simply lost the WebUI credentials of the node.
I would like to know where they are stored and/or how reset them to the default.

Thank you

**Comment by chompomonim** [comment]
You should delete `myst.db` file and restart myst service. Database file is usually located in `~/.mysterium/db`.

Such questions is better to ask in discord or via chat on our website.
