### ISSUE TITLE
[Windows] App get stuck on loading screen

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2661]
**Describe the bug**
MysteriumVPN app for Windows stuck on loading screen and cannot start normally.

**Expected behavior**
Launch and use.

**Screenshots**
<img width="333" alt="Screenshot 2020-09-22 at 21 39 37" src="https://user-images.githubusercontent.com/60128746/93923498-229f5380-fd1c-11ea-83ce-ebc296cb72ac.png">

**Environmentt:**
 - OS: Windows10
 - Desktop app version 2.9.0

**Additional context**
[main (5).log](https://github.com/mysteriumnetwork/node/files/5263378/main.5.log)
[renderer (2).log](https://github.com/mysteriumnetwork/node/files/5263380/renderer.2.log)

**Comment by etherunit** [comment]
@tadaskay Pls let us know if you need any additional information to investigate this further.

**Comment by vkuznecovas** [comment]
Fixed

**Comment by etherunit** [comment]
Another user has the same issue with loading screen stuck on a startup on Windows.
Adding logs that I've received from him.
<img width="571" alt="Screenshot 2020-11-20 at 08 35 47" src="https://user-images.githubusercontent.com/60128746/99767685-211bbd00-2b0c-11eb-8e69-8507145bc158.png">


[main (6).log](https://github.com/mysteriumnetwork/node/files/5571693/main.6.log)
[myst_supervisor (8).log](https://github.com/mysteriumnetwork/node/files/5571694/myst_supervisor.8.log)
[renderer (2).log](https://github.com/mysteriumnetwork/node/files/5571695/renderer.2.log)

**Comment by tomasmik** [comment]
After quickly looking at the logs this seems to be related to this: https://github.com/mysteriumnetwork/node/issues/2982

Do you still have the machine and it's still not working @etherunit ? Could you confirm that port 4050 is already taken?

**Comment by etherunit** [comment]
Yep, it's related. Closing another application with 4050 taken port solved it. It works now.

**Comment by tomasmik** [comment]
I guess we can close this then and investigate further on the before mentioned issue.
