### ISSUE TITLE
Failed to request proposals metrics

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2662]
https://my.mysterium.network/network is showing 0 providers. 

<img width="333" alt="Screenshot 2020-09-22 at 21 49 48" src="https://user-images.githubusercontent.com/60128746/93924547-8ece8700-fd1d-11ea-84f5-4b0d6310a621.png">
<img width="1534" alt="Screenshot 2020-09-22 at 21 50 13" src="https://user-images.githubusercontent.com/60128746/93924585-9d1ca300-fd1d-11ea-87b1-566015ef6721.png">

**Comment by vkuznecovas** [comment]
Fixed
