### ISSUE TITLE
Build 0.39 deb package for Ubuntu eoan

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2677]
We do have new node release, but on Launchpad new versions are only build for `bionic` and `focal`. `Eoan` still have `0.38.1`.

https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node-pre

**Comment by soffokl** [comment]
>Rejected:
>eoan is obsolete and will not accept new uploads.
>
>myst (0.39.0+build191012625+eoan) eoan; urgency=medium
>
>* CI build number 191012625
