### ISSUE TITLE
Feedback on new WebUI

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2683]
~~1. Current default MysteriumVPN service price on the testnet is 0.1MYST/GiB & 0.001 MYST/min. New WebUI onboarding page shows 0.005 as price per min and GiB (there is also no asset symbol attached to it).~~

~~2. Guess still not shipped. Unable to register identity with following response `message: "failed identity registration request: server response invalid: 400 Bad Request (https://betanet-transactor.mysterium.network/api/v1/identity/register){"error":"transactor requires at least 100000000000000000 fee"}`~~
~~3. Implement password manager in the 3rd step (copy or view)~~
~~4. Unable to paste copied API Key in the API token field.~~
~~5. No flow to reset password (needed to delete myst.db file in /var/lib/mysterium-node/betanet/db/ in case I forgot my credentials)~~
~~6. Unable to access http://127.0.0.1:4050/events/state during DC & Residential node onboarding. Pages are not loading. Blocked from manual testing it further.
<img width="1677" alt="Screenshot 2020-09-28 at 18 48 59" src="https://user-images.githubusercontent.com/60128746/94455300-91b4f600-01bb-11eb-8b7f-7ac244db94cb.png">~~
~~

**Comment by chompomonim** [comment]
@etherunit could you test WebUI on BetaNet one more time and see if all your mentioned issues are already fixed?

**Comment by etherunit** [comment]
1. When enabling/disabling traffic shaper and/or Whitelist feature under Service Settings, getting errors as below:
<img width="1676" alt="Screenshot 2020-10-14 at 17 22 50" src="https://user-images.githubusercontent.com/60128746/96003542-fe2e2700-0e42-11eb-9a16-50935e00e9a4.png">
2. Issues with pagination on sessions page? https://streamable.com/27uh0a
3. Users often asking the purpose of "NAT status" functionality. It shows "NAT status is not finished" but monitoring agent is connecting successfully. 
![Uploading Screenshot 2020-10-14 at 17.47.52.png…]()
