### ISSUE TITLE
Ensure proper registration metrics

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2700]
Node should report proper registration metrics with additional metadata such as country and operating system.

- [x] ~~More metadata next to identity metric `Event_VersionPayload(os, arch, version, country)`~~ (moved to another issue #2776 )
- [x]  How many successful/failed registrations are done in node: `Event_RegistrationEventPayload(os, arch, version, hermesId, country, event)`
event = "Started/Registered/Failed" (similar to `Event_SessionEventPayload(event)`)

**Comment by Waldz** [comment]
@soffokl did i describe correctly?

**Comment by soffokl** [comment]
The task is about registration metrics. I don't think we should make it complicated. 

We are not sending the registration metric from the node right now. All we have is transaction metrics only, but it's lacking some information. 
The idea here is to send events about identity registration from the node:
```
node_identity_registration{identity="0x00000123", os="androd", version="0.40.0", status="Registration request sent", country="LT"}
node_identity_registration{identity="0x00000321", os="windows", version="0.40.0", status="Registration done", contry="KG"}
```
