### ISSUE TITLE
Groom China unban

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2713]

**Comment by Waldz** [comment]
Please read https://github.com/mysteriumnetwork/internal-docs/wiki/Using-public-CDN-for-discovery-censorship-bypass

**Comment by Waldz** [comment]
Next sprint:
- [ ] Check if our DNS is black-holed (https://testnet-api.mysterium.network)
- [ ] Investigate exact reason why CH stopped
- [ ] Alerts if CH get gets blocked again
- [ ] Get datacenter server in china
- [ ] Proactive search for machine in CH (Sharmini, Tadas friend)
- [ ] SIKE DHT discovery (servers on nodes, publish content, discover content)

Later:
- [ ] DNS replacement service in China with DHT (epic)
- [ ] Start monitoring from Mysterium nodes
----------
- [ ] Integrate Kademlia client and bootstrap proposals in it's routing
- [ ] Remove broker from P2P session 
- [ ] Host entry proxies (secure, multihop) 
- [ ] Clusterisation of blocker

**Comment by Waldz** [comment]
All further tasks will be linked to epic #2747
