### ISSUE TITLE
Test node and apps for BetaNet

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2716]
We should be testing such scenarios:

- Node (provider) install from deb package and on-boarding using WebUI
- Node (provider) install in docker and setuping it via CLI
- MacOS and Windows desktop app 
   - registration with tokens (ping @chompomonim to get some test MYST).
   - registration with referral code (ping @chompomonim) to get referral code.
   - connection into various nodes and their stability
- Android app installation via .apk.

**Comment by etherunit** [comment]
Could not get session data
2`.4044f559.chunk.js:2 GET http://134.122.104.184:4449/tequilapi/sessions?date_from=2020-09-01T00:00:00.000Z&date_to=2020-10-01T00:00:00.000Z 422 (Unprocessable Entity)`

**Comment by chompomonim** [comment]
Issues found:

- [ ] Throwing 404 if going into `/dashboard` or `/sessions`. Works only with `:4449/`
- [ ] See `TypeError: SessionStats: stats is not provided` when navigating into `/sessions` page via menu
- [ ] It didn't asked me to topup MYST after setting stake amount. --> Missing screen with address where to send stake tokens.
- [ ] Min/Max stake slider should get values from Hermes smart contract (`getStakeTresholds()`).
- [ ] Default price slider (on-boarding screens) looks strange. It shows same values for per data and per time (0.005 MYST).
- [ ] WebUI dashboard should be aware that Identity is not registered and should not start services... Should show people some information about registration status. Had check registration status via CLI to see that it is not registered and to get topup channel address.

**Comment by mdomasevicius** [comment]
> Min/Max stake slider should get values from Hermes smart contract (getStakeTresholds()).
Caching issues
![image](https://user-images.githubusercontent.com/20511486/95550425-8eb6d280-0a11-11eb-8737-3fa34cf9d82c.png)

**Comment by chompomonim** [comment]
Results after second test:

- [ ] localhost:4449 still not accessible
- [ ] Forgot password URL should open help with instructions
- [ ] After `apt remove myst` process were not stopped, had to do `systemctl stop mysterium-node`
- [ ] Only QR code is not enough, you always should show wallet address (for copy/paste)
- [ ] In onboading it shows wrong 'get api key' url, also could't add it during on-boarding, only later from settings
- [ ] Can't enable OpenVPN from WebUI
- [ ] Can't see my node even with "include unreachable". Monitoring agent still can connect to it
- [ ] There is not information about node version in WebUI. Maybe we should show it at least in setting or report an issue screens?


![Screenshot from 2020-10-19 04-29-47](https://user-images.githubusercontent.com/153896/96394070-c8ce6400-11c9-11eb-9810-91f48f3c6c81.png)

**Comment by soffokl** [comment]
I cannot claim a node via webui, when via CLI it works fine: 
![image](https://user-images.githubusercontent.com/8612618/99622455-62509600-2a54-11eb-99f2-13ac9445c1cb.png)

**Comment by chompomonim** [comment]
Closing this issue and opening new one for testing TestNet v2 (#2844)
