### ISSUE TITLE
422 Unprocessable Entity - failed to fetch session data

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2722]
Provider identity: 0x3b13793403515ac7d3e5ea343646e468a8416ace
IP type: hosting
Could not fetch session & update asset data over API for DC node on betanet in new WebUI.

<img width="638" alt="Screenshot 2020-10-08 at 11 12 19" src="https://user-images.githubusercontent.com/60128746/95432781-c7927100-0957-11eb-87d6-dadfdb0579e0.png">

**Comment by Waldz** [comment]
I forwarded email with failure details

**Comment by Waldz** [comment]
Use newest betanet `master`.
Should be fixed by by https://github.com/mysteriumnetwork/node/pull/2720
