### ISSUE TITLE
Feedback on betanet MMN

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2723]
Identity address: 0x3b13793403515ac7d3e5ea343646e468a8416ace, IPtype: hosting,  node version: "0.39.0-1snapshot-20201006T1335-5ed0d3ef, commit: "5ed0d3ef".
1. Node is using default pricing condition (0.2MYST/GB, 0.00001MYST/min). I am seeing unconverted values under service pricing: 
<img width="466" alt="Screenshot 2020-10-08 at 20 57 35" src="https://user-images.githubusercontent.com/60128746/95496147-13b9d180-09a9-11eb-8b0e-47140c31a6ca.png">
2. Unsettle earning in UI=11.558 MYST, Current balance and current promise in MMN are negative -80,161,416,728.67 MYST & 
-68,897,578,866.25 MYST

3. No earnings shown under session data.
<img width="1417" alt="Screenshot 2020-10-08 at 21 03 49" src="https://user-images.githubusercontent.com/60128746/95496660-d43fb500-09a9-11eb-9b24-07ffdaa4d1f6.png">
4. 1 test session generates 5GB of data ±1MYST. Should we use traffic shaper?

Node logs: https://betanet.mysterium.network/admin/issues/download/1012

**Comment by chompomonim** [comment]
Betanet should not forget that our new token is `1e18`. I see "Current balance 1,107,617.42 MYST" which is total nonsense.

**Comment by etherunit** [comment]
There is also noop service on MMN while running a node with docker image.
<img width="466" alt="Screenshot 2020-10-09 at 13 06 06" src="https://user-images.githubusercontent.com/60128746/95570919-4f4bae80-0a30-11eb-8be4-8ad903ba5fc1.png">

**Comment by chompomonim** [comment]
Betanet mmn points into wrong grafana 

![Screenshot from 2020-10-19 05-16-38](https://user-images.githubusercontent.com/153896/96394315-51e59b00-11ca-11eb-85fa-c0e19e19a00d.png)

**Comment by etherunit** [comment]
- [ ] Betanet MMN does not reflect pricing set on UI;
- [ ] No earnings for a test sessions with several GB transfers;
- [ ] Traffic limiter does not apply for a session

**Comment by ignasbernotas** [comment]
Issue with outdated monitoring agent.
