### ISSUE TITLE
Update payment client to support multiple chains at once

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2729]
The payment client currently accepts an RPC endpoint.

This should change in the following way:

It should accept a  `map[int]string` where we'd pass in a map of chain_id -> RPC endpoint. All the corresponding methods should then accept the chain ID and work with the corresponding chains. The nonce tracker needs to take this into account, i.e. keep track of nonces on different chains.

**Comment by vkuznecovas** [comment]
The payment client currently accepts an RPC endpoint. 

This should change in the following way:

It should accept a map[int]string where we'd pass in a map of chain_id -> RPC endpoint. All the corresponding methods should then accept the chain ID and work with the corresponding chains. The nonce tracker needs to take this into account, i.e. keep track of nonces on different chains.
