### ISSUE TITLE
Deploy Matic full node

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2731]
- [x] Make ansible which can be reused for deployment of the full matic node
- [x] Deploy matic node to the required servers. (testnet mumbai only)

**Comment by vkuznecovas** [comment]
https://docs.matic.network/docs/integrate/full-node-deployment/

**Comment by vkuznecovas** [comment]
Matic provides an RPC endpoint for interactions with BC. The RPC/WSS endpoints are part of the static JSON configurations provided by Matic. You can find them attached below.

For goerli, see: https://static.matic.network/network/testnet/mumbai/index.json
For mainnet, see https://static.matic.network/network/mainnet/v1/index.json
