### ISSUE TITLE
Node should track multiple balances

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2732]
- [ ] There should be notion of default chain, where provider channels will be created.
- [ ] Consumer balances should be tracked on multiple chains.
- [ ] `balance` tequilapi should have endpoint which shows all consumer balances.
- [ ] On session start consumer should send chain_id with largest balance (together with hermes id).
- [ ] On session start provider should validate if given chain id is supported.
- [ ] Possibility to switch default chain (tequilapi endpoint + cli command).
- [ ] All blockchain and transactor calls should have chain_id.
- [ ] Adapt `payments` package with chain_id.

**Comment by vkuznecovas** [comment]
https://github.com/mysteriumnetwork/node/issues/2785 has more details
