### ISSUE TITLE
Adapt MMN for multichain support

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2735]
MMN should be aware, that channels on L2 chains is like having them on separate hermes.

**Comment by chompomonim** [comment]
Single Hermes can have response with two items (channel objects) in a list (by chain id).

**Comment by chompomonim** [comment]
@ignasbernotas have you looked at this task? Was it done last week?

**Comment by ignasbernotas** [comment]
@chompomonim @eugenegoncharuk I thought I had done it, sorry. Fixed and deployed with: https://github.com/mysteriumnetwork/my.mysterium.network/commit/cc97887f8d83a60c42fd4cb887760895052ca846

Supports multiple Hermes endpoints and multiple chains.
