### ISSUE TITLE
Grafana [testnet] - monitor version change for Dev KR1

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/node#2759]
We should monitor latest version drop to 0 and new version coming up. Metric values should be within 2 weeks after the migration.

**Comment by soffokl** [comment]
Time to update to the exact version can be tracked at https://grafana.mysterium.network/d/HaqMZOpMz/happiness
![image](https://user-images.githubusercontent.com/8612618/97144602-f3eb2180-178e-11eb-9c5f-23319753514c.png)
