### ISSUE TITLE
Grafana [testnet] - Calculate nodes leaving the network Dev KR2

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/node#2760]

**Comment by soffokl** [comment]
The number of nodes leaving the network can now be tracked here:
https://grafana.mysterium.network/d/HaqMZOpMz/happiness
![image](https://user-images.githubusercontent.com/8612618/97144621-fb122f80-178e-11eb-9ee4-d15cd7750b6e.png)
