### ISSUE TITLE
Give free registration for testnet users

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2790]
- [x] Transactor on testnet should giving free registration (use config, so betanet and testnet code would be same)

Testnet apps (cli, android, desktop, webui) should not show registration step and should user transactor to register for free:
- [x] Android https://github.com/mysteriumnetwork/mysterium-vpn-mobile/commit/154db4371a0f362b72d6fd0eb3901543e10e5aab
- [x] Desktop https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/74
- [x] CLI ( https://github.com/mysteriumnetwork/node/issues/2790#issuecomment-746239700 )
- [ ] WebUI

**Comment by tomasmik** [comment]
CLI still has the `account register` command but it doesn't only register, it also creates, unlocks identities etc. I dont think this should be changed. As for `myst cli`, I also would say that asking to use the `register` command is OK, as it's an advanced/debug tool. These command do output that `registration is completed` straight away if running in testnet, without asking for any top ups, which I think it enough.

So I assume we can tick the `CLI` box being happy with the current implementation.

**Comment by chompomonim** [comment]
@mdomasevicius as far as I have tested we have "free registration" in WebUI already. Right?
