### ISSUE TITLE
Myst Desktop Not Resolving IP 

### ISSUE THREAD

**Issue by NCGValkyrie** [mysteriumnetwork/node#2799]
![myst broken](https://user-images.githubusercontent.com/20866706/98362278-ddfa1e00-2024-11eb-9451-5a4e3760b09a.jpg)

This is an issue that has been present since day 1 of the myst application being released, the issue has been disused many times with Jaro and Etherunit on the discord.

When ever I connect to any node while on my business connection in my shop, I get this same error on all computers I have tried.

The app will connect to nodes but will not show the IP of the node I am connected too, it just shows updating which means it is have issues resolving the IP for that node.

This results in the internet connection being extremely slow to the point of not loading anything at all until disconnected.

This is an old issue but yet no one to date seems to be able to answer what causes it.

**Comment by chompomonim** [comment]
There is chance, that this node simply don't give you internet connection and problem itself is with node or its networking, node the app.

If you could attach logs, that would help to debug more. You can do that via "send logs" menu or by attaching here such files:

- App logs:  `%USERPROFILE%\AppData\Roaming\MysteriumVPN\logs\*.log`
- Supervisor logs: `%PROGRAMDATA%\MystSupervisor\myst_supervisor.log`

**Comment by NCGValkyrie** [comment]
I was thinking the same, but unfortunately its an issue that happens with all nodes I try to connect too including nodes I know 100% work using the android app and the same windows app at home.

It is only the windows app being used on my business network that is having the issues, even tried on different windows desktops on the same network with the same results.


[main.log](https://github.com/mysteriumnetwork/node/files/5511037/main.log)
[myst_supervisor.log](https://github.com/mysteriumnetwork/node/files/5511038/myst_supervisor.log)
[renderer.log](https://github.com/mysteriumnetwork/node/files/5511039/renderer.log)

**Comment by etherunit** [comment]
Another user has the same issue with loading screen stuck on a startup.
Adding logs that I've received from him.
<img width="571" alt="Screenshot 2020-11-20 at 08 35 47" src="https://user-images.githubusercontent.com/60128746/99767245-67bce780-2b0b-11eb-91f4-76d5e5cd59ba.png">

[main (6).log](https://github.com/mysteriumnetwork/node/files/5571678/main.6.log)
[myst_supervisor (8).log](https://github.com/mysteriumnetwork/node/files/5571680/myst_supervisor.8.log)
[renderer (2).log](https://github.com/mysteriumnetwork/node/files/5571681/renderer.2.log)
