### ISSUE TITLE
NAT doesn't work over IPsec/IKEv2

### ISSUE THREAD

**Issue by arpitjindal97** [mysteriumnetwork/node#2802]
**Describe the bug**
My network traffic is routed through a server via IPsec/IKEv2. I'm able to surf web properly without any issue. When I want to run Mysterium node in my network, than UDP Hole Punching doesn't work in node. Users are able to connect to my node via official myst app but there is no internet for them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a VPN network routed through a VPN server (strongSwan)
2. Run a myst node inside the network
3. Node will appear on dashboard with VPN server's IP and online status
4. Try connecting to the Node from Internet.
5. You will get connected but there will be no internet
6. In node's log, You will be able to see NAT failing

**Expected behaviour**
UDP hole punching should work even if network traffic is routed via IPsec

**Environment (please complete the following information):**
 - Node version: 0.39.0
 - OS: Alpine
 - Docker: mysteriumnetwork/myst:latest

**Comment by zolia** [comment]
Hi Arpit, 

problem in question might be not IPsec/IKEv2 itself, but what kind internal VPN you are getting behind that IPsec tunnel.
There are a couple of angles to check: 

 - MTU size of a packet. You might want to reduce wireguard packet MTU in order to fit it in into IPsec MTU. This depends on your current MTU size of IPsec packet.
 - What kind of NAT is behind IPSec tunnel? Some type of NATs cannot be properly punched. 
 - Is UDP protocol properly enabled on IPSec router? Does it allow all UDP ports?

**Comment by arpitjindal97** [comment]
Hi @zolia ,

I tried setting up a personal `wireguard` server and connect my laptop to it. Then I ran myst node on my laptop. I observed same behaviour as seen with `IPsec`

Node is online, but UDP packets are failing.

![image](https://user-images.githubusercontent.com/15676216/101141069-c8830e80-3639-11eb-8594-1410fd98d4cd.png)

I have also created a small tool to host a personal IPsec and Wireguard server, to try things quickly
https://github.com/arpitjindal97/aegis

The configuration files of server are in config folder. You can have a look at them.

For IPsec/IKEv2, I can say that there might be configuration issue, but for wireguard the config is simple and straightforward. You can host a vpn server and try running a node at your end. 

**Questionable thoughts:**
 - Does it have to do anything with the iptables of server where personal wireguard vpn is hosted (docker) ?
 - Is it myst node, which is not able to punch though VPN tunnel ?

**Comment by arpitjindal97** [comment]
One more update, I tried to run myst node normally on my MacBook without any tunnel, and it's failing. Is it the problem from docker on Mac

**Comment by arpitjindal97** [comment]
Hi @zolia ,

I removed my previous comment because I'm guessing the problem was in my MacOS which wasn't allowing UDP hole punching to passthrough. 

Nevertheless, I tried it on Ubuntu VM then Alpine Docker image.

 - IPSec is connected to my Personal hosted VPN server (https://github.com/arpitjindal97/aegis)
 - Running myst inside it stucks

![image](https://user-images.githubusercontent.com/15676216/101211574-66f48b80-369d-11eb-9a71-791473ef98f7.png)

If you see `curl` command works perfectly fine. I do not know what's the issue here. Not able to debug more.

**Comment by zolia** [comment]
Hi @arpitjindal97 , 

are you attempting to run MN node inside docker container on MacOS? 
If so, this approach is very little tested. Most of our nodes run in RPIs / linux VMs + docker. Basic use-case macos + docker MN used to work, but almost no one except devs use it. 

Better way to test MN + IPsec compatibility imho would be to setup router (RPI / any other linux) with MN node + IPSec directly (no docker).
IPSec client implementations as OS routing / firewall rules vary too much to account for every aspect. If you really want to run with IPsec, let's do it step by step starting from best know to work environment. 

Antanas

**Comment by arpitjindal97** [comment]
Yea, I was running it in MacOS, but now I'm trying it in Ubuntu. 

The above screenshot is from Ubuntu, You can see that MN node is stuck when IPsec is running.

**Comment by chompomonim** [comment]
@Snawoot is this still relevant? Should we fix it or close it?
