### ISSUE TITLE
Vpn fluctuating a lot on wifi

### ISSUE THREAD

**Issue by AmritSingh297** [mysteriumnetwork/node#2813]
Hi, team 
I faced this particular issue on wifi connection. After every few mins the vpn get disconnected automatically, while on cellular network data it works fine and stable .. tested on same node using mysterium dvpn app android ..with wifi (Jiofiber broadband connection India) and Jio 4G cellular data... but vpn always drops on wifi.. please resolve this asap.

My device - Android smartphone.
My Location- India
My mail id - moneyji29700@gmail.com

**Comment by chompomonim** [comment]
To be able to debug you issue we would need to get a little more information.

- Exact version of dVPN app you're using (e.g. android 0.39.1)
- Logs of your app (ideally reported right after connection dropped. you can do that from user interface)
- Node Identity  you're connecting to.

**Comment by chompomonim** [comment]
We addressed a lot of connectivity issues during last half a year, this should be fixed already.
