### ISSUE TITLE
Cannot add a wallet to my Node

### ISSUE THREAD

**Issue by lertsoft** [mysteriumnetwork/node#2815]
**Describe the bug**
Cannot add a wallet to my node.

**To Reproduce**
1. Go to 'https://betanet.mysterium.network/user/payments'
2. Click on 'Built-in UI'
3. it will take you to the Node
4. See error (there is nowhere to put the wallet address)

**Expected behavior**
A straightforward way of implementing the wallet to the node so that payments could be fulfilled.

**Screenshots**
![Screen Shot 2020-11-10 at 9 47 00 PM](https://user-images.githubusercontent.com/28693094/98759440-155b2880-239f-11eb-8cb3-f7223e21abef.jpg)

![Screen Shot 2020-11-10 at 9 52 16 PM](https://user-images.githubusercontent.com/28693094/98759453-1d1acd00-239f-11eb-828a-9ea358816ae0.jpg)

**Environment (please complete the following information):**
 - Node version: [e.g. 0.40]
 - OS: [e.g. raspbian buster, debian 10]

**Comment by chompomonim** [comment]
This will be fixed after #2881 is done.
