### ISSUE TITLE
Tequilla api should be adapted to newest smart contracts

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2834]
New smart contracts have such changes:
- Beneficiary address is stored in `Registry`, not in Hermes.
- You can still change beneficiary via `settleWithBeneficiary` call, and it will update beneficiary for all hermesses.
- To settle promises we should use `settlePromise` call. There are not 'settleAndRebalance` call anymore.
- Providers are not required to have stake and can settle up to `maxStake` value (can be fetched by `getStakeThresholds` call).
- Settlement tequilla call should ensure that user have enough funds collected. CollectedFunds > TransactorFee.
- There are no stake goal anymore, we should delete all related logic (if there is one). 

We should ensure, that Tequilla endpoints and transactor are working correctly and are ready to support such features.

**Comment by vkuznecovas** [comment]
This is already implemented.
