### ISSUE TITLE
Add config management into CLI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2878]
To make datacenter node runners life easier, we could add a little more "sugar" for `myst cli`.

- [ ] `myst config show` --> prints currently used params (all of them, default, passed as running daemon params and loaded from configs).  ( https://github.com/mysteriumnetwork/node/pull/2905 )
- [ ] `myst config set --ui-enable=false`
- [ ] `myst config set --ui.address=192.168.1.10,192.168.1.20`
- [ ] `myst config set --ui.port=4449`
- [ ] `myst config set --testnet=true`
- [ ] `myst config set --nat-port-mapping=true`
- [ ] `myst config set --experiment-natpunching=false`
- [ ] `myst config set --chain-id=1`
- [ ] `myst config set --transactor.address=https://testnet2-transactor.mysterium.network/api/v1`
- [ ] `myst config set --transactor.registry-address=0x15B1281F4e58215b2c3243d864BdF8b9ddDc0DA2`
- [ ] `myst config set --transactor.identity-address=0x45b224f0cd64ed5179502da42ed4e32228485b3b`
- [ ] `myst config set --transactor.channel-implementation=[address]`
- [ ] `myst config set --transactor.provider.registration-retry-delay=3m0s`
- [ ] ...

After setting any config, node daemon should be restarted.

It also could be simply part of interactive CLI if separate command doesn't look right.

**Comment by chompomonim** [comment]
Plus update all the docs after adding these improvements.

**Comment by tomasmik** [comment]
I've added the `show` command as I deem it useful enough.

For the `set` commands after some discussion we agreed upon a general idea: it's not worth it.
It's not only clunky to implement or use, but it also requires user to do advanced things after executing this command and if the
user is able and willing to do that, he can just alter the config himself at that point.

If you have any argument against this - feel free to leave this open. If not we can close it after the `show` is merged.

**Comment by chompomonim** [comment]
I agree that at this stage having `show` is enough. I will create separate task for `config set`, so in future we could reevaluate its importance.
