### ISSUE TITLE
Finalize settlement/wallet screen

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2883]
On betanet users will need to settle their collected rewards manually via blockchain settlement transactions. We need to show list of blockchain settlement transactions and button to settle collected funds.

- [x] Show list of settlement transactions where are such parameters: date/time, beneficiary address, transaction id (with url to etherscan), fee, received amount. There is event on Hermes smart contract `event PromiseSettled(bytes32 indexed channelId, address indexed beneficiary, uint256 amountSentToBeneficiary, uint256 fees);`
- [x] Show payout beneficiary address box (beneficiary address is stored in `Registry` smart contract and can be called via `getBeneficiary(address _identity)`. Can be read only for now.
- [x] Show auto-settlement threshold settings box. Can be read only for now.

![Wallet-settlements](https://user-images.githubusercontent.com/153896/100815284-34078900-344c-11eb-98a0-40adcf78dde1.png)

- [x] Settle button. It should be active only when there are enough funds to cover transactor fee. When user clicks on "Settle now" button, there should appear additional popup with settlement information: amount to settle, transaction fee, "you get" amount, possibility to set into which beneficiary address to settle. If user is not changing beneficiary (beneficiary field is same as currently known beneficiary) we should call `settlePromise` instead of `settleWithBeneficiary`. 

![Settle promise](https://user-images.githubusercontent.com/153896/100815185-0a4e6200-344c-11eb-8560-6aee0d9ef299.png)

**Comment by mdomasevicius** [comment]
@chompomonim I am starting to remember that we decided to show all time cumulative amounts of myst and data and session in dashboard charts. Do we really need those cards at the bottom right of wallet screen?

**Comment by chompomonim** [comment]
You mean in wallet screen?
How user can see that accumulative data while in wallet screen?

**Comment by mdomasevicius** [comment]
@chompomonim he can't see it in wallet screen
