### ISSUE TITLE
node 0.40.3 (and snapshot) is not working (on desktop app)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2909]
Mac Catalina

Myst or supervisor crashes when app is started.
No logs produced.

"@mysteriumnetwork/node": "0.0.0-dev.2",

tried with 0.40.3 - same result

**Comment by tadaskay** [comment]
Use bug report template to report issues. It helps.

I have reproduced the issue. There are logs produced in app's console that indicate the myst process exiting prematurely.
Changed the already non-existing flag `--betanet` to `--testnet2` and it started working as it should. Try with the latest master version that uses node 0.40.6-pre: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/2ec8668e50fa3f3394b3ec11902dd6dfa43f8001

**Comment by cvl** [comment]
Thanks!

**Comment by chompomonim** [comment]
@cvl can we close this issue?

**Comment by cvl** [comment]
Yes, Tadas already closed it.
