### ISSUE TITLE
Testing of v0.41-rc

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2941]
Please add here any bugs you will find while testing our release candidate of 0.41 node version (which will already use Testnet 2.0).

**Comment by soffokl** [comment]
`Forgot password?` button does nothing:
![image](https://user-images.githubusercontent.com/8612618/102320327-56e68100-3fa6-11eb-9a70-b9acda1ff20c.png)

**Comment by soffokl** [comment]
MMN shows only Unsettled amount at earnings, not total:
![image](https://user-images.githubusercontent.com/8612618/102320509-944b0e80-3fa6-11eb-883a-e472e0e321bd.png)
![image](https://user-images.githubusercontent.com/8612618/102320541-a331c100-3fa6-11eb-92db-5305bfe9a131.png)

**Comment by chompomonim** [comment]
> MMN shows only Unsettled amount at earnings, not total:

Agree, on testnet we should who total earnings...

**Comment by chompomonim** [comment]
There are couple of bugs I have found during my last testing session.

Node WebUI:
- [ ] It requires to type default password during first run of fresh install --> UI could try to login using default password during launch of user interface (so users would 
- [ ] Show node version instead of WebUI version in settings view. By knowing node version you always also know WebUI version, not vice versa.
- [ ] Unsettled earnings —> Total earnings (WebUI on testnet) 
- [ ] Bigger spacing between service and global settings boxes. (in .services-footer `margin-top: 15px`)
- [ ] Move back screen with beneficiary settings (during on-boarding)
- [ ] WebUI don’t show proper price when “default” setting is set

General:
- [ ] Agree on terms doesn’t work when I’m changing `.mysterium/config.toml`.
- [ ] I had to agree twice (first when installing via apt and second on cli).
- [ ] RPi install have some pre settings? I didn’t choose price, beneficiary address and whitelisted… 

Apps:
- [ ] Android app is connecting only from second/third time (checked on two phones with multipole providers, Andzej have same issue)
- [ ] There are no still any beta version to test for desktop app.

**Comment by matthprost** [comment]
Hi!

I found small issues: 

- The link of "Get it here" leads on `https://testnet2.mysterium.network//user/profile` double slash shouldn't be before user
![Screenshot 2020-12-29 at 15 43 00](https://user-images.githubusercontent.com/15812968/103291797-d768a100-49ec-11eb-9153-459d3ff99a19.png)

- Copy button doesn't add value to clipboard 
![Screenshot 2020-12-29 at 15 43 12](https://user-images.githubusercontent.com/15812968/103291933-1139a780-49ed-11eb-8301-50613faf2937.png)

- When global bounty position is not yet set we don't have ineligibility reason
![Screenshot 2020-12-29 at 15 50 14](https://user-images.githubusercontent.com/15812968/103292271-c704f600-49ed-11eb-91ff-6ff23759b94e.png)
![Screenshot 2020-12-29 at 15 50 19](https://user-images.githubusercontent.com/15812968/103292272-c79d8c80-49ed-11eb-9d8b-b11bb6ba41a5.png)

**Comment by mdomasevicius** [comment]
@matthprost  which browser are you using (exact version would be great) ?

**Comment by matthprost** [comment]
@mdomasevicius Sorry for those missing information.

**Browser version:** Google Chrome 87.0.4280.88 (Official Build) (x86_64)
**Operating System:** OS X 11.1.0

**Comment by chompomonim** [comment]
After releasing v0.41.0-rc1, please add your testing comments into #2965
