### ISSUE TITLE
Upgrade Raspbian for our RPi image

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2963]
Our RPi image is using very old Raspbian version. We should upgrade it into newest stable version.

**Comment by soffokl** [comment]
Updated to the Raspberry Pi OS Lite (Release date: December 2nd 2020, Kernel version: 5.4)

**Comment by chompomonim** [comment]
Is it already part of 0.41.0-rc1 build?

**Comment by soffokl** [comment]
Yes
