### ISSUE TITLE
Android app is connecting only from second/third time 

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2964]
Android app is connecting only from second/third time (checked on multiple phones with multipole providers from multiple ISPs)

Reproduction steps:
- instal newest mobile app (0.41.0).
- Try to connect to any selected node.
- If connection fails, try connecting again. It should connect after second or third. time.

**Comment by cvl** [comment]
Same here.

And even after that, connecting is terrible. Something changed dramatically. Only one in 10-20 attempts is successful. Can connect to one node, then after 30 seconds, I cannot connect to the same node anymore.

In essence, it's not working.

0.39.0 was working very well, something happened.

Here are my last attempts of trying to connect (-1 means it failed)


0x0259f45e190f7a28eda8d0c945b5d66950d1e44d | -1 | 2021-01-04 16:29:36
-- | -- | --
0x5e9eaba49428f143c0831d5dbdfe781cd9480d5b | -1 | 2021-01-04 16:29:45
0x35d2c7599d29428fcf90fc3eb9fa55a29208e87e | -1 | 2021-01-04 16:29:47
0x726f652dc79e6421877f679271c464d60bb15b14 | 1 | 2021-01-04 16:29:54
0x0259f45e190f7a28eda8d0c945b5d66950d1e44d | -1 | 2021-01-04 16:30:37
0x726f652dc79e6421877f679271c464d60bb15b14 | -1 | 2021-01-04 16:30:44
0xcbebf86a2cdf004c2c913fbd9e6ac4bfd6c14d9e | -1 | 2021-01-04 16:30:45
0xeac9378ac40c1b10dc6ca9aa5f8dc3bec0221165 | -1 | 2021-01-04 16:30:47
0x02ade20f52c427c9d9730ae9de1e09138d46e8b0 | 1 | 2021-01-04 16:30:50
0x726f652dc79e6421877f679271c464d60bb15b14 | -1 | 2021-01-04 16:31:49
0xcbebf86a2cdf004c2c913fbd9e6ac4bfd6c14d9e | 1 | 2021-01-04 16:31:50
0x726f652dc79e6421877f679271c464d60bb15b14 | -1 | 2021-01-04 16:32:38
0xeac9378ac40c1b10dc6ca9aa5f8dc3bec0221165 | -1 | 2021-01-04 16:32:40
0x02ade20f52c427c9d9730ae9de1e09138d46e8b0 | -1 | 2021-01-04 16:32:41
0xcbebf86a2cdf004c2c913fbd9e6ac4bfd6c14d9e | -1 | 2021-01-04 16:32:43
0x5e9eaba49428f143c0831d5dbdfe781cd9480d5b | -1 | 2021-01-04 16:32:51
0x35d2c7599d29428fcf90fc3eb9fa55a29208e87e | 1 | 2021-01-04 16:32:52
0x726f652dc79e6421877f679271c464d60bb15b14 | -1 | 2021-01-04 16:33:50
0xcbebf86a2cdf004c2c913fbd9e6ac4bfd6c14d9e | -1 | 2021-01-04 16:33:51
0x02ade20f52c427c9d9730ae9de1e09138d46e8b0 | -1 | 2021-01-04 16:33:52
0xeac9378ac40c1b10dc6ca9aa5f8dc3bec0221165 | -1 | 2021-01-04 16:33:53
0x5e9eaba49428f143c0831d5dbdfe781cd9480d5b | -1 | 2021-01-04 16:34:43
0x35d2c7599d29428fcf90fc3eb9fa55a29208e87e | -1 | 2021-01-04 16:34:44

**Comment by cvl** [comment]
Important note: 0.41.0-pre works a bit better (than 0.41.0-rc1)
