### ISSUE TITLE
Testing of v0.41-rc1

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#2965]
Please add here any bugs you will find while testing our release candidate of 0.41 node version (which will already use Testnet 2.0).

**Comment by soffokl** [comment]
Fresh install on raspberry, it asks me to enter an MMN API token, but I already did it during onboarding a few minutes ago:
![image](https://user-images.githubusercontent.com/8612618/103602793-222b7100-4f37-11eb-9ae3-62f783222d03.png)

**Comment by soffokl** [comment]
MMN shows incorrect pricing https://testnet2.mysterium.network/nodes/75/dashboard:
![image](https://user-images.githubusercontent.com/8612618/103602949-89e1bc00-4f37-11eb-81d6-7927dce5ba1c.png)
![image](https://user-images.githubusercontent.com/8612618/103602961-9108ca00-4f37-11eb-8a3e-fe116f50d1cc.png)

**Comment by soffokl** [comment]
Changed pricing in WebUI to 0, but it was not changed:
![image](https://user-images.githubusercontent.com/8612618/103603327-91559500-4f38-11eb-8bad-5fc16c6fdde7.png)
![image](https://user-images.githubusercontent.com/8612618/103603311-86026980-4f38-11eb-9120-db1967d36ad7.png)

**Comment by soffokl** [comment]
Missing `/` at the view in MMN link:
https://testnet2.mysterium.networknodes/75/dashboard
![image](https://user-images.githubusercontent.com/8612618/103603598-2c4e6f00-4f39-11eb-9848-5ce525eb1c81.png)
![image](https://user-images.githubusercontent.com/8612618/103603568-1c368f80-4f39-11eb-9b53-5eae3ac07ea2.png)
