### ISSUE TITLE
Flexible port for tequilapi: 4050 can be already taken on windows

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#2982]
Seems that port 4050 is taken on some windows machines not allowing to start a node instance.

Seems that svchost.exe is using it for something. Investigate further and figure this out.

~~Edit: This might be caused by somehow having a node installed and not removed properly leaving something still running in the background.~~

Edit2: Seems that processes like `sihost (Shell Infrastructure Host)` are ran using svchost on this port on my machine for some reason. Maybe we should raise the port to something a lot higher so that we wouldn't have a chance to collide with system processes?

**Comment by chompomonim** [comment]
As a solution after detecting that this port is already taken we should use another port (e.g 4051, 4052...) and make desktop app aware of that.

**Comment by tomasmik** [comment]
> As a solution after detecting that this port is already taken we should use another port (e.g 4051, 4052...) and make desktop app aware of that.

As for a quick solution I guess we could also just bump these ports to some much higher values where collisions are much less probable.

**Comment by tadaskay** [comment]
I suggest we just take a port in a higher range

**Comment by chompomonim** [comment]
I think we should do both things. Taking higher port range and still detect when it is taken and take second port.
Otherwise some users may still face similar issues.

**Comment by tomasmik** [comment]
Agreed with @chompomonim here. Seeing as we already have the port discovery done, we should make any improvements to it if any are needed, bump the initial port on which tequila starts and ship this.

**Comment by tomasmik** [comment]
Tested again on my machine by building the latest master branch. The desktop app now actually starts without any problems.

**Comment by cvl** [comment]
Is this implemented (as it's been closed)?
If so, then this will break desktop app, as it has hardcoded port at tequilapi/index.ts -  TEQUILAPI_PORT = 44050

I believe myst process should return it's port number on spawn (at supervisor.ts).

**Comment by cvl** [comment]
I'm referring to @chompomonim suggestion "Taking higher port range and still detect when it is taken and take second port."

**Comment by tomasmik** [comment]
Before it was 4050, now it's 44050. So yes we took a higher port. Here: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/89/files

We also allow to set ports dynamically here: https://github.com/mysteriumnetwork/node/pull/3051

This has been released for 2+ weeks now, as far as I am aware, nothing broke.

**Comment by cvl** [comment]
I'm referring to @chompomonim suggestion "Taking higher port range and still detect when it is taken and take second port."

I.e. if node sees, that 44050 is taken, then it would try 44051, if this is taken it will try 44052 and so on.

If that would have been implemented per Jaro suggestion, this would break the app in case 44050 is taken (as node would be on higher port, but app would connect to hardcoded 44050 (and failing to do so obviously).
