### ISSUE TITLE
Ensure payment exchange on session end

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#2985]
This is a low priority as it's more of a nice-to-have than a real prerequisite. 

Due to the async nature of the payment system, a situation might occur where a consumers reported spending is larger than the actual amount that reaches hermes.

This happens in the following flow:
1) Session is established.
2) Payments occur normally for some time.
3) Consumer received yet another invoice.
4) Consumer starts calculating the amount to promise.
5) Session is killed as operation 4) is happening.
6) The promise is incremented but never issued as the session is aborted. This can happen due to promise not being sent, or provider not listening for further promises on the given topic.
7) Hermes is not aware of the last promise, therefore the consumer and hermes reportings are different.

Under normal circumstances, such occurences should be VERY, VERY rare and the amount of myst involved is rather small. They should have no impact on the payment system as a whole.

We can, however, improve this by making sure that "last promise" is issued and reaches the provider before session end. 

This was originally discovered while investigating #2984

**Comment by tomasmik** [comment]
No one will ever do this.
