### ISSUE TITLE
Login page has wrong 'Forgot password?' URL

### ISSUE THREAD

**Issue by pvdl** [mysteriumnetwork/node#2994]
**Describe the bug**
Login page has wrong 'Forgot password?' URL

**To Reproduce**
1. Go to `http://<yourNodeIP>:4449/#/login`
2. Click on 'Forgot password?'
4. Redirect to non existing page: https://docs-v2.mysterium.network/node-runners/troubleshooting/#forgot-tequilapi-password

**Expected behavior**
Probably this is the correct URL: https://docs.mysterium.network/node-runners/troubleshooting/#forgot-password

**Environment (please complete the following information):**
 - Node version: 0.41.0
 - OS: raspbian buster, debian 10

**Additional context**
-

**Comment by pvdl** [comment]
https://github.com/mysteriumnetwork/node/blob/3b44749bd9263ed6f61fbf8012ee961d5a6ae417/config/flags_node.go#L247

**Comment by pvdl** [comment]
Fixed in this commit:
3050510c9cd33c2758e7f20ad5ba87a6e316f225

**Comment by panayotovip** [comment]
but now do not open nothing to help with "Forgot password" :(
search in https://docs.mysterium.network do not find anything.
