### ISSUE TITLE
Wrong country on initial setup

### ISSUE THREAD

**Issue by scysys** [mysteriumnetwork/node#3004]
**Describe the bug**
IP Country is wrong on initial setup. The Docs are not including this error. Any files to manually change the country to the right one.

**Environment (please complete the following information):**
Node version 0.41.0
WebUI version 0.1.21
Ubuntu 20.04

**Comment by vkuznecovas** [comment]
Hello,

You'll need to fill out a form on [the MaxMind page](https://support.maxmind.com/geoip-data-correction-request/correct-a-geoip-location/) to get this sorted. 

I've also added the information to the [documentation](https://docs.mysterium.network/resources/faq/#my-node-is-reporting-its-country-incorrectly).

**Comment by scysys** [comment]
> Hello,
> 
> You'll need to fill out a form on [the MaxMind page](https://support.maxmind.com/geoip-data-correction-request/correct-a-geoip-location/) to get this sorted.
> 
> I've also added the information to the [documentation](https://docs.mysterium.network/resources/faq/#my-node-is-reporting-its-country-incorrectly).

Thats one way. But you have internal options for this. This options are not working.
When you prefer to use the maxmind page, why are these options are available?

```
   --location.type value                                  Location autodetect adapter. Options: { oracle, builtin, mmdb, manual } (default: "oracle")
   --location.address value                               Address of specific location adapter given in '--location.type' (default: "https://testnet-location.mysterium.network/api/v1/location")
   --location.country value                               Service location country
   --location.city value                                  Service location city
   --location.node-type value                             Service location node type
```

Adding --location.type=manual --location.country=DE to the start process it was not working. (V0.41)
