### ISSUE TITLE
[Testnet 2.0] Incorrect bounty reportings

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3005]
**Describe the bug**
We have received several reports that bounty earnings (on MMN) do not equate to data transferred nor to earnings chart on Testnet 2.0. It also differ from numbers found on Grafana. Affected providers:
- 0xd63a53dae5aea08d2bd733717f747ba034993d32
- 0x53de5d5b7ae2e9a81fe904622d3d8332116ae9dc
- 0xe8c067dca2d9ac0fd2dfb5fd14717d7618d7bc6d
- 

<img width="1407" alt="Screenshot 2021-01-18 at 18 35 19" src="https://user-images.githubusercontent.com/60128746/104941639-fe970a80-59bb-11eb-8df5-990030324d54.png">

**Comment by ignasbernotas** [comment]
Fixed. MMN was subtractiing settled amount from the latest promise, which is only valid for betanet.

**Comment by MoralisRubric** [comment]
0x0b9ac1c32f59bc6177f3c1520934115608e400ed
