### ISSUE TITLE
Matic -> Mainnet withdrawal flow tooling

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3008]
While node runners may be using Matic sidechain for payment channels they would need withdrawal flow to send earned tokens into L1 (Ethereum mainnet).

We should create all needed payments package extensions to cover crypto and api calls needed to do that.

**Comment by chompomonim** [comment]
Tasks to do:

 - Extend smart contracts to have `pay and settle` --> this should be only in L1 `HermesImplementation`
 - Hermes should have endpoint which will issues payment promise to yourself
     1. Hermes should check that exchange message is having same identity in "consumer" and in "provider" channels
     1. Hermes should issue special kind of payment promise (acceptable by `pay and settle`) and return in response
     1. Hermes can immediately take funds out of consumer channel (on Matic).
 - Node should immediately call transactor with this special promise to do `payAndSettle` on L1 --> `payAndSettle` support for node
 - Add `payAndSettle` support into Transactor

**Comment by chompomonim** [comment]
Schematics how all of it may work.

![Withdraw via Hermes](https://user-images.githubusercontent.com/153896/109467446-dd721100-7a73-11eb-97bb-02b08a309e9c.png)

**Comment by NGUYENAN9999** [comment]
Dear Support Team, 

This is An from Vietnam. 

 I  need your help to support me for the MATIC deposit issues. 

I have withdraw 1398.66 MATIC from MXC Exchange to my wallet address on Binance Exchange as below:

My receipt wallet Addres(ERC20)

0xcfefea2224871ab5e79caf354172e77e1e32ccde

Txid：

0x7d352c0f10c45ebb61a2f1abc0d82b1a2fbb3a487df9b6d8ee49e61ab65961bf

Transaction details: 
https://explorer-mainnet.maticvigil.com/tx/0x7d352c0f10c45ebb61a2f1abc0d82b1a2fbb3a487df9b6d8ee49e61ab65961bf/internal-transactions

 I saw that the withdrawal is successful in the history withdrawals but I don’t see the MATIC come in my Matic wallet on Binance Exchange!

When I wait for a long time then I re-check back then I saw my wallet MATIC on MXC Exchange is MATIC NETWORK not ERC20 NETWORK. 

So could you please help me on this issue. How can I get back the money? 

Thank you very much!
Best Regards 
An

**Comment by vkuznecovas** [comment]
Testnet3 branches should now cover this flow.
