### ISSUE TITLE
Start collecting ping and/or roundtrip time statistics

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3010]
Start collecting metrics about P2P pings (during session) and send it into monitoring / quality oracle.

Store this information by subnets.

**Comment by soffokl** [comment]
Now we are collecting information about the ping between countries:
This is information for LT consumers:
https://testnet2-grafana.mysterium.network/d/pJcf4DYMk/ping?orgId=1&var-consumer_country=LT&from=now-7d&to=now
![image](https://user-images.githubusercontent.com/8612618/107309915-8ea90b00-6ab5-11eb-818f-3313a9496e3c.png)

**Comment by chompomonim** [comment]
Should we create separate ticket to start collecting pings by subnet? Or at least by country+IP type/isp? Ping to different ISPs and DCs may be quite different.
