### ISSUE TITLE
Make a mini RFC of how to measure node's bandwith

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3014]

**Comment by soffokl** [comment]
We are currently sending session traffic stats with a 30 seconds interval. 
Using this information it's possible to calculate the traffic rate for every single session, detailed by the countries. 

That gives us an estimation for the provider bandwidth based on the existing session, that can be splited by the countries or any other attributes.
![image](https://user-images.githubusercontent.com/8612618/108798791-dd2bce80-75b8-11eb-82c3-5e17a17ed6a3.png)

As pointed in the https://github.com/mysteriumnetwork/node/issues/2997 epic, it's possible to aggregate this information to calculate median values and 95% percentile:
![image](https://user-images.githubusercontent.com/8612618/108800142-8922e900-75bc-11eb-8cfd-ac4d1a794d09.png)

https://testnet2-grafana.mysterium.network/explore?orgId=1&left=%5B%22now-24h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22quantile(0.5,%20provider_session_max_rate:avg30s%7Bprovider%3D%5C%220x1bc36ff8da5ac4a1e4e886da03e482c82a6ab2c7%5C%22%7D)%20by%20(direction)%22,%22requestId%22:%22Q-131501c4-664e-4c35-97e5-27b6bb40e600-0Q-a4ccf7c8-509f-412f-9c61-85f81a3e4652-1A%22%7D,%7B%22expr%22:%22quantile(0.95,%20provider_session_max_rate:avg30s%7Bprovider%3D%5C%220x1bc36ff8da5ac4a1e4e886da03e482c82a6ab2c7%5C%22%7D)%20by%20(direction)%22,%22requestId%22:%22Q-131501c4-664e-4c35-97e5-27b6bb40e600-0Q-a4ccf7c8-509f-412f-9c61-85f81a3e4652-1B%22%7D%5D

**Comment by chompomonim** [comment]
So, what should be our next steps? Are we ready to expose some kind of "bandwith" endpoint for quality oracle?
