### ISSUE TITLE
Adapt CLI flow so it would send it's chain when requesting for payment invoice

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3018]

**Comment by tomasmik** [comment]
As far as I know we can probably just read it from config in pilvytis API ( https://github.com/mysteriumnetwork/node/pull/3028 ) and doing that would close this and https://github.com/mysteriumnetwork/node/issues/3017 as we would just send the same chain id that node is currently using.

**Comment by chompomonim** [comment]
Good point. I think we can try this approach.
