### ISSUE TITLE
Consumer side  traffic slicing

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3034]
Problem statement
-------------------

In some regions node runners may be afraid of running full access into internet via their exit node. Around 40% of our exit nodes are using while listed only traffic selected to protect themself from potentially malicious traffic. 

Another observation is that consumers often don't need VPN for all their networking activities, they need simply overcome censorship and get access into some services. All other traffic may go via standard connection.

Solution
--------

Let's introduce consumer side traffic slicing, so Mysterium dVPN app would detect package destination and would send only send only selected traffic type (e.g. into media streaming services) via VPN tunnel. 

In such situation we could give people access into whitelisted nodes without degradation of user experience. Node runners would get more traffic, users would have more exit nodes to choose from.

- User should be able to select which services should go via VPN tunnel and which directly via ISP. 
- Node runners should choose whitelisting categories so consumers could choose not separate service, but category for such sliced tunnel. 
- Discovery should allow to search nodes who are serving traffic into selected whitelisted categories.

**Comment by cvl** [comment]
Do I understand correctly, that VPN consumer will need to pick different providers based on what he wants to do on the web? Using a VPN would become a full time job.

If there's a problem for providers to serve sensitive traffic, start with creating a public black-list.

I don't really understand how censorship at node level will help Mysterium network fulfil it's goal?
Sounds like "You're free to do as I tell you".

Correct me if I misunderstood (hopefully).

**Comment by chompomonim** [comment]
No, you miss interpret what is written. 

This is additional feature, for those users who don't need VPN for all their traffic, just for part of it. There is quite big amount of such users (look at Hola, they allow you enabling VPN only for selected apps, and they're very popular). 

At the moment whitelisted nodes are not accessible to general public at all, only to our partners via SuperProxy. We want to extend that accessibility for wider public. People can set once in settings which apps (or websites) should be browsed via VPN, all other traffic will go via ISP. Looking to examples of some other providers, this doesn't look complicated. 

Also this will not touch people who wants to set VPN for all their traffic (including Portals users).

**Comment by Technetium1** [comment]
Imagine working in the UK and wanting to watch Netflix in the US, or likewise being in the US and wanting to watch BBC. This is the perfect solution.

**Comment by cvl** [comment]
- Enabling VPN for certain apps only is a good feature (although nice to have considering other much more critical issues/features).
- I'm referring to incentivising nodes to become whitelisted nodes, which is misaligned with VPN service (and will canibalize it eventually): why would anyone run general node, when you can run whitelisted node, which a) gets only safe traffic b) gets much more traffic, because most of the content is video streaming.

The problem here, is that your SuperProxy business model (i.e. reselling residential IPs to centralized VPN so their users can watch Netflix) will be misaligned with Mysterium network vision and VPN service model, UNLESS you wouldn't incentivise node whitelisting.
If you would still go with whitelisting model, you would eventually get bunch of residential IPs, which serve Netflix streaming service to centralized VPN, under the flag of fighting global censorship / privacy problems. Corpos will eat Mysterium.

So my suggestion: stop incentivising whitelisted nodes and save Mysterium network.

**Comment by chompomonim** [comment]
Node runners are afraid that users will do some malicious activity via their home IPs. That is why around 35% of them are already using whitelisting option even is they're getting significantly less traffic (less income).

This proposal is  simply opening access to that nodes for wider public and should stimulate growth of our node runners network. Otherwise after couple of really dangerous situations for node runners, we will loose them instead of giving solution.

**Comment by Technetium1** [comment]
Where would the larger list of whitelisted sites come from in the future? What would be the process for adding and removing from the list?

**Comment by chompomonim** [comment]
This is to be decided. At this stage any suggestions and ideas are welcome.

**Comment by Technetium1** [comment]
Free: https://majestic.com/reports/majestic-million
Paid: https://www.alexa.com/topsites

**Comment by Technetium1** [comment]
Stale bot allows for issues to quietly disappear instead of being fixed.

**Comment by Hc747** [comment]
Bumping for interest

**Comment by Flight1530** [comment]
So is there and update?

**Comment by Technetium1** [comment]
> Free: [majestic.com/reports/majestic-million](https://majestic.com/reports/majestic-million)
> Paid: [alexa.com/topsites](https://www.alexa.com/topsites)

Alexa will be discontinued on May 1, 2022, if you want to get information from there, do it sooner than later... https://support.alexa.com/hc/en-us/articles/4410503838999
