### ISSUE TITLE
Better ways to limit  bandwidth

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3035]
At the moment there is option to limit bandwidth to 5Mbps, but this is very limited option.

Node runners would like to set how many concurrent sessions they support and what is maximum bandwidth they’re ready to give.

**Comment by scysys** [comment]
For some regions it would be also optimal to have options for traffic limitations per month / day.

**Comment by cvl** [comment]
Such limitations must be included in proposal description, so user can filter out such limited nodes.
Would be a huge downgrade to Mysterium network, hopefully this won't be included.

**Comment by chompomonim** [comment]
We already have limits, many nodes set 5Mbps. But actually many of them would like to increase that limit to 20Mbps or have it disabled during night.

Suggestion to have it in proposal in good, but only for short term. Technically we can't trust what is in proposal (in terms of quality parameters), nodes can lie there. To allow consumers to filter only "fast" nodes we're working on quality params improvements #2997.

**Comment by scysys** [comment]
> Such limitations must be included in proposal description, so user can filter out such limited nodes.
> Would be a huge downgrade to Mysterium network, hopefully this won't be included.

I dont mean this for users. Limitations for users make no sense. I mean this on node basis.

**Comment by cvl** [comment]
- It's very surprising and hard to understand, why such information is not transparent to consumers and partners. This must be transparent and visible, so user can use less limiting nodes. This must be a free and transparent market: the node price and proposal value (e.g. quality, speed, location etc) must be transparent, otherwise user pays for service he doesn't get.
- How can a node realistically like (versus theoretically): node provider would need to mingle with code, and build and support his node codebase to workaround this limit reporting? Don't see why anyone would take an effort in doing that considering there's almost nothing he would win. And if there'll be one node in hundreds - who cares.

**Comment by chompomonim** [comment]
@cvl you clearly don't get something.

1. Node runners never have to mingle with code. Why you think that after this proposal they would need to do that? They will simply set some limits via NodeUI.
2. At the moment we already have option to limit bandwidth, and many node runners use it. They're afraid that VPN consumers will eat all their internal while they also need to use it.
3. We're extending quality oracle, so proposals would have also real node's speed. So if someone will limit it to 20Mbps, there will be according info in proposal. Consumers will be able to filter out "slow" nodes.

**Comment by cvl** [comment]
Trust me, I get it. Too much perhaps.

1. You're saying, that providers can lie about their limits. There's no way to do that, unless they mingle with the code, or limit with some other 3rd party tools - i.e. they must be arbitrarily malicious. Which I argue will almost never be the case as there's close to 0 reason to do that. Obviously, the real speed will vary irrelevant to the limits they put (based on their internet speed and usage at the moment).
2. I'm trying to tell that a) such limits should be transparent to the consumer, so he can filter / prioritise the nodes based on node quality b) I'm quite disappointed/surprised that this information is being disclosed just now after few years of operation.
3. Very good, thanks.

Not sure what's here "not to get".

**Comment by chompomonim** [comment]
> a) such limits should be transparent to the consumer, so he can filter / prioritise the nodes based on node quality

What you mean by "transparent"? Isn't quality oracle updates about that? 

b) I'm quite disappointed/surprised that this information is being disclosed just now after few years of operation.

What information you're talking about? All have been said above is public for ages (visible in NodeUI, in code, in issuer closed, in release notes ...).

**Comment by cvl** [comment]
"Transparent": I suggest this information should be present when retrieving proposals.

E.g.:
{
"id":1,
"provider_id":"0x75f64bcc28ed1bd84a6ea6766870a903399fb6a6",
"service_type":"openvpn",
**"max_bandwidth": 5,**
"service_definition":{
"location_originate":{
"continent":"EU",
"country":"DE",
"city":"Lower Saxony",
"asn":56382,
"isp":"vServer.site LTD",
"node_type":"hosting"
}
},
"payment_method":{
"type":"BYTES_TRANSFERRED_WITH_TIME",
"price":{
"amount":500000000000000,
"currency":"MYSTT"
},
"rate":{
"per_seconds":300,
"per_bytes":3579139
}
}
},

b) Unfortunately, I have no chance of going through all the code, and all the changes, especially when I wouldn't suspect such things might happen.

**Comment by chompomonim** [comment]
This is exactly why we're working on #2997 and #1798

**Comment by Zensey** [comment]
@chompomonim 
AFAIS there's no concurrent sessions limit flag in node yet.
