### ISSUE TITLE
Can't upgrade from 0.41.0 to 0.41.2 - "already registered" error

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3042]
- Install android app with node 0.41.0
- Install app with 0.41.2
- I'm getting
Loaded identity 0xe9f0f2327ef3c49f25336cd8365a8e4e45393bf4, channel addr: 0xA72615820Cf010Fa12303837b608DCA23706aFe7, status: RegistrationError

    go.Universe$proxyerror: could not register identity: server response invalid: 400 Bad Request (https://testnet2-transactor.mysterium.network/api/v1/identity/register){"error":"already registered"}

So when refreshing identity (i.e. loading from NodeRepository), the status is RegistrationError, yet when trying to register, it says it's already registered.

**Comment by chompomonim** [comment]
This should be fixed already.
