### ISSUE TITLE
Node Whitelisting

### ISSUE THREAD

**Issue by Data-Gremlin** [mysteriumnetwork/node#3043]
Node register as "Public" but not showing up on Mysterium app.

Only receiving connections from "Whitelisted" Connections.

**Comment by vkuznecovas** [comment]
Could you please provide more information? What platform are you using? What's your identity?

**Comment by Data-Gremlin** [comment]
@vkuznecovas apologies. 

I'm running it on a RP4 running

Linux raspberrypi 5.4.83-v7l+ #1379 SMP 

My node ID is 

0x4295d0893b65cb5f5a35baaeae179d0a7f5de104

**Comment by Data-Gremlin** [comment]
@vkuznecovas does this help ?

**Comment by vkuznecovas** [comment]
It does. You have your pricing set quite high, therefore your node gets filtered out by the applications. If you lower your pricing, the node will become available.
