### ISSUE TITLE
Transfer of Earnings

### ISSUE THREAD

**Issue by Data-Gremlin** [mysteriumnetwork/node#3044]
Transferring of earnings from previous node ver to new 41.2 all previous connections and earning are not showing up on UI.

**Comment by vkuznecovas** [comment]
The old earnings are not compatible with the new versions of node. The new versions are a clean slate if you will. There's no way to transfer them.

**Comment by Data-Gremlin** [comment]
@vkuznecovas so do I loose all them funds if they are just below the threshold for transfer to my wallet ?

**Comment by etherunit** [comment]
@Data-Gremlin If your node qualify as one of the top three (Global IP bounty) or one of the top 250 (Residential IP bounty), then your accumulated earnings on deprecated Testnet V1 network will be paid out to your wallet address.
