### ISSUE TITLE
41.2 upgrade: server response invalid: 500 Internal Server Error

### ISSUE THREAD

**Issue by matthprost** [mysteriumnetwork/node#3049]
**Describe the bug**
Cannot start node since I upgrade it to 41.2, even downgrade to 41.1 doesn't work.

**To Reproduce**
1. Upgrade node from 41.1 to 41.2

**Expected behavior**
To run the node without any failure.

**Environment (please complete the following information):**
 - Node version: 41.2
 - OS: Debian 4.19.160-2 (2020-11-28)
 - Kernel release: 4.19.0-13-amd64

**Additional context**
Logs: [Link](https://really-nice-bucket.s3.nl-ams.scw.cloud/node.logs?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=SCW8CGPMWJ7BKNSRCMEC%2F20210125%2Fnl-ams%2Fs3%2Faws4_request&X-Amz-Date=20210125T100437Z&X-Amz-Expires=561343&X-Amz-Signature=ec66a973c50dcc165e593365b2462195b6b0873434db2e515c954d655a43c721&X-Amz-SignedHeaders=host) (expire in 1 week)

**Comment by bathrobehero** [comment]
Same, in case you mean 41.3.

**Comment by matthprost** [comment]
Hello, I did meant 0.41.2 release but it seems like every services turned back online.
I upgraded to 0.41.3, services are still online without any error.
