### ISSUE TITLE
Fix DialerSwarm fallback

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#3055]
Currently, the dial is performed in parallel with both dns and IP addresses directly, which means that we are kind of unable to point our DNS and/or move our servers. This needs addressing.

**Comment by chompomonim** [comment]
Lets start DNS lookup a little earlier (e.g. 2-3 sec.)

**Comment by chompomonim** [comment]
As a first step we could delay requests via ip by 1 second, so requests via DNS would get priority.
