### ISSUE TITLE
Can't install on Ubuntu (wireguard missing)

### ISSUE THREAD

**Issue by bathrobehero** [mysteriumnetwork/node#3065]
**Describe the bug**
Install fails with:

The following packages have unmet dependencies:
 myst : Depends: wireguard but it is not installable
E: Unable to correct problems, you have held broken packages.

**To Reproduce**
sudo apt install myst, as per the linux guide at https://docs.mysterium.network/node-runners/setup/linux/

**Expected behavior**
Completed install

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
I've tried several workarounds, like "sudo add-apt-repository -y ppa:wireguard/wireguard" or installing linux headers but none of them worked.

**Comment by soffokl** [comment]
I have just checked on the brand new installed Ubuntu 18.04 and wireguard available there in the standard repositories:
![image](https://user-images.githubusercontent.com/8612618/106227581-a1008a80-6213-11eb-85d9-c1f22165e57d.png)

Make sure that you have default repositories enabled. 
And execute `apt update` before trying to install wireguard.
