### ISSUE TITLE
Always focus app window on Windows if already running

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3066]
After solving https://github.com/mysteriumnetwork/node/issues/3041 there seems to be another issue on Windows OS.

When window is closed via close button (not quit), then opening app doesn't do anything (looks like it's broken). The only way to open the app window is via tray icon.

**Comment by cvl** [comment]
@tomasmik commented on this, fixes this for me https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/88/files#r566724484
