### ISSUE TITLE
[Android, bug] Connected, but no internet connection -> can't disconnect

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3078]
Node: 0xc37f4aaeb92adad7245c737b1189a928b621147f

Connected, but no internet connection -> can't disconnect (stuck in disconnecting state).

Need to kill connection manually via android taskbar.

This is an old bug, happens rarely, might be a chance to catch it.

**Comment by vkuznecovas** [comment]
Please reopen the issue following our bug template as it is impossible to investigate/solve with the information you are providing.

**Comment by cvl** [comment]
Reopened here: https://github.com/mysteriumnetwork/node/issues/3080
