### ISSUE TITLE
still only 50/50 chance of getting connected

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3079]
Here's the attempts to connect today (2021-02-03).
1 - connected successfully, -1 or empty - failed

0x723e53e81220e891da240d64a1a0eb1a566a3dc9	-1
0x9723c34bb53b3b292d6c9599e3980bf1fb67eeed	-1
0x9d58193a1bc61a4c6fbb5f21fd4808939ef516f9	1
0x025d84306f589bb54f6bf09be29fafe72eea1b39	-1
0x2335d2bb7c3eae65bc4a51b52b455364fc718f96	-1
0x17c4b47873b642949e155c795f13c6ce7d15ac35	1
0x723e53e81220e891da240d64a1a0eb1a566a3dc9	-1
0x0a654ea3071e2e20c0fb71e501a14007394fa7ff	1
0xce9acf0972e2e1a9851dfc28f7b596cc2cbef8fb	1
0x9723c34bb53b3b292d6c9599e3980bf1fb67eeed	-1
0x4a71111e8669b4e161454c70c2becc4e0c2c5a3d	1
0x9d58193a1bc61a4c6fbb5f21fd4808939ef516f9	1
0xd136a2025fd3d3a5a77dc8c22a4f4eca1cca00d3	1
0x7ec2538e845dbc43deb03cb73a30637d05777b64	1
0x196a087e2d9e4c4860d74ffa59a1c255a11213b9	1
0x4fafa8b72aa51bf97fdba4b3bef89ca114910f06	1
0x24cdfbb5f4209d5b8ab639fe10cb7a3550867c1e	1
0x025d84306f589bb54f6bf09be29fafe72eea1b39	-1
0x787f60298ef419e1d26f5a6fa85f74f9a67a8e99	1
0x2335d2bb7c3eae65bc4a51b52b455364fc718f96	-1
0x17c4b47873b642949e155c795f13c6ce7d15ac35	1
0x219fd0275db0f7b0fdc8ca6f4219c920fd5d7706	-1
0xad6cd07428624ba15d0313fb4b4b0fafbc63ae5e	-1
0x3b08ad02f2e7346f7a965dfd34101cf665884411	1
0x4a71111e8669b4e161454c70c2becc4e0c2c5a3d	1
0x0f10e0277b41221915c8b332729d54befff23e91	1
0x6ba8f21cc3535d89a44a34269d5f6050e0885242	1
0x1cb1e30c4dec60dc06da78ac4026c87babb6d75d	1
0x219fd0275db0f7b0fdc8ca6f4219c920fd5d7706	-1
0xa95897d5fd929d25d7a2cf7e5a2ee36c173f029b	1
0xad6cd07428624ba15d0313fb4b4b0fafbc63ae5e	
0x219fd0275db0f7b0fdc8ca6f4219c920fd5d7706	-1
0x922d3072c3ced31347449e661c2c129faa750f1e	1
0xc44e625115e1b17148db2e6c40c724b9ddc6c6a0	-1
0x3d2a73bb408d0a5ace3e8fd71ded43cf6e344cfc	1
0x992ed5f2503ec546b633954be4037bf489bb5fc9	1
0x9998e1a77cd1a900164f2d65f80da4b2e7accde1	1
0x9d0468f41391f139addf3c5ed3d9ebe0cf62e94b	-1
0x93dabb21b613ce308bd38db3f59774d1a2a43ae4	1
0xfab5be6397ae6b214b31fa21496732b88060855d	-1
0x16b6c03d966874d5e4033b13cda9740766ae51b3	1
0xf2278b0e483a61cc1e68fe19eb18d0fe4adb2154	-1
0xb363d488e188d2cf961989d218e267c44edd63c9	-1
0x2a76c4fd54c12b6a89ea434a45ce03370fb3dde1	-1
0x775bbaf125831fb0f59677a8f87a391248ab2c4c	1
0x3d9ee8338c1597b2640eca2e67b0e99a607d34ea	-1
0xeb195d3e5ccd7e0927d4de9eac0a1f9a62fafcd3	-1
0x76da712a9456cfcdadbd90e7dfa2b528a73aebcb	1
0xc8e8bade6cc6247d5fc80fc92cafc5342c5642a3	-1
0x4abac44551e653111fb3e7a83d802c4847e45140	1
0x8a40873db789c5d3e595538980046f01ed298303	1
0x6b8e031f7f418f037909f8aaecb51f9475df03dc	1
0xaad2c5a42e47a1e5b4bcae607fb048f48817f035	1
0x080dd608fdd5dcb20e9c13782d8f60307d9c3763	1
0xcd6160ee1d575fb8a094b8446b619ac36ed7a24b	-1
0x2c5aba36988031d0e32fe5422aa5823f62e5549e	-1
0xe6fbea72c70b9029cef2688ce8670fde052f9edf	1
0x57dec5fadb4b9e92ba68837ca5ce89e25c2f3460	1
0x778e12cfdd1470d4af211923f7faba1ea391a37b	1
0xca4dcf4a3bad1da81c4a15841de79a2147656f5f	-1
0xb638e218360a20cde821742e8fcc7d85267d364a	1
0x515a652f669a0730b90ced1d44ef91234a953dae	1
0x29c0b7b9e6dde262ddd64b502ee734c2daeb8100	-1
0x779b3db278e30387ce78e9be5de9f53652b5ff04	1
0x13fa6095cd33ec8c359ecf02c7a1b83abf0abda5	1
0x3ed141f90e0b471a94108241689293ad2c4ec17d	-1
0xc37f4aaeb92adad7245c737b1189a928b621147f	
0x867794425e42626265354198d7035fb1e57ca3a8	1
0x0da444370166e0c2decb744122fcc2d07b8be4ce	1
0x0da444370166e0c2decb744122fcc2d07b8be4ce	-1
0x867794425e42626265354198d7035fb1e57ca3a8	-1
0xae8b2d1d17acad99fa67897973c89865bfaa1942	-1
0x2e6f337fc55a0611fd2db719b595adc1b8bc5fdd	-1

**Comment by tomasmik** [comment]
Im sorry but this information is not very useful. You will have trouble connecting to some providers and thats just how it is at the moment. We're working on improvements.
If you're having trouble connecting to specific providers and believe that node itself is at fault, please provider specific logs for that connection so that we can take a look.

**Comment by vkuznecovas** [comment]
Please start adding context to the issues you are opening. I'd gladly help, but your issues are literally unsolvable.

Our metrics show that the network as a whole has a connectivity rate of 95%. This is in direct contradiction to your findings. 

As this is a decentralized network we're fully aware that a subset of the whole provider population will probably be inaccessible due to various network configurations.

Here are a few questions for you: 

1) How were the tests conducted?
1) Are you behind a NAT? 

1) What do entries such as these even mean? You connected but didn't?
```
0x0da444370166e0c2decb744122fcc2d07b8be4ce 1
0x0da444370166e0c2decb744122fcc2d07b8be4ce -1
```

1) At what time have you conducted the tests?
1) Are these identities hardcoded or are you taking a random sample each time?
1) Are you taking quality metrics into account when choosing nodes?
1) Is this a test you perform regularly? What are the previous results in that case?
1) Have you tried connecting from a different network setup(i.e. while being connected via mobile, or using another router)?

**Comment by cvl** [comment]
This is a general report from my testing (I'm doing these random sample tests once or twice per week atm), also metrics from usage of my users.

Although this is usual behavior (i.e. sometimes the stats are close to 90%, yet last couple days those were much worse). Nothing specific I can report, just timeouting I guess.

Please find logs attached of me trying to connect to 3 nodes (3rd attempt successful):
0x723e53e81220e891da240d64a1a0eb1a566a3dc9	-1
0x9723c34bb53b3b292d6c9599e3980bf1fb67eeed	-1
0x9d58193a1bc61a4c6fbb5f21fd4808939ef516f9	1

[logs.txt](https://github.com/mysteriumnetwork/node/files/5918085/logs.txt)


Answers to the questions:
- How were the tests conducted?
Simply using Windows and Android apps from my home (Mezon).
The similar success stats can be seen in metrics from my users though.
- Are you behind a NAT?
Not sure. How can I check that?
- What do entries such as these even mean? You connected but didn't?
In this case, Windows app connected, Android app didn't. Should've clarified that.
- At what time have you conducted the tests?
12:30 LT time
- Are these identities hardcoded or are you taking a random sample each time?
Random, going through all the countries.
- Are you taking quality metrics into account when choosing nodes?
Yes, sorting by quality.
Also, filtering black-listed nodes (i.e. nodes that my users failed to connect to at success rate less than 20%, or are stuck at connecting state, or connected, but no internet conn etc). At the moment we have 100 black listed nodes.
So the sample is from "good" nodes, or new nodes (i.e. not tested enough yet).
- Is this a test you perform regularly? What are the previous results in that case?
Yes, twice a week, also can see the metrics from my users.
See the sample attempts from 01-16 (node 0.39.0) attached.
[01-16 attempts.txt](https://github.com/mysteriumnetwork/node/files/5918134/01-16.attempts.txt)
- Have you tried connecting from a different network setup(i.e. while being connected via mobile, or using another router)
Rarely, but I'll give it a try.
As mentioned, the stats are similar for other users globally.
I've changed my router ~month ago, the stats didn't change so I could notice.

**Comment by vkuznecovas** [comment]
> * Not sure. How can I check that?

In short - if you're using any sort of router, you're behind NAT. Most of the users will be behind nat, as public IPs are pretty much an ad-on on any ISP subscription or only accessible in data centers. 

Yesterday, at around 12:00 an upgrade to our infrastructure was performed, which meant that some of the nodes you tried might have had additional issues that should not be present today. 

I've also tried a few nodes from the list, with varying successes. This is completely normal, as the current nat hole punching mechanic might struggle with some network configurations. What works for me, might not work for you and vice-versa. 

There are also a bunch of nodes in the list that in general do not seem to be able to accept connections. You seem to have drawn a rather bad subset. 

We're fully aware that our NAT traversal is not as good as it should be and we have issues that will further improve the quality of the network. Here are a few:

https://github.com/mysteriumnetwork/node/issues/1576 -> improves traversal capability
https://github.com/mysteriumnetwork/node/issues/3011 -> improves connectibility via allowing further classification of nodes.
https://github.com/mysteriumnetwork/node/issues/2597 -> improves connectibility
https://github.com/mysteriumnetwork/node/issues/2997 -> epic for quality reporting improvements.

I don't think this issue adds anything to the discussion, as we're already aware of the problems that we have and are constantly working to improve these. Therefore, I'm closing this.

**Comment by cvl** [comment]
thanks for the elaboration!
