### ISSUE TITLE
Lots of spelling issues with online scanning

### ISSUE THREAD

**Issue by tonyxia2016** [mysteriumnetwork/node#308]
By using Go Report Card site scanning, there are lots of spelling issues in the source codes.

https://goreportcard.com/report/github.com/MysteriumNetwork/node

misspell96%
Misspell Finds commonly misspelled English words
node/cmd/commands/cli/command_cli.go
Line 327: warning: "occured" is a misspelling of "occurred" (misspell)
node/cmd/commands/server/factory.go
Line 122: warning: "overriden" is a misspelling of "overridden" (misspell)
Line 126: warning: "publicaly" is a misspelling of "publicly" (misspell)
Line 127: warning: "probaly" is a misspelling of "probably" (misspell)
node/client/connection/manager.go
Line 181: warning: "depencency" is a misspelling of "dependency" (misspell)
node/client/connection/manager_test.go
Line 206: warning: "instanse" is a misspelling of "instances" (misspell)
node/openvpn/management/connection_mock.go
Line 39: warning: "expectes" is a misspelling of "expects" (misspell)
node/openvpn/state.go
Line 41: warning: "successfuly" is a misspelling of "successfully" (misspell)
node/openvpn/discovery/dto/payment_method_per_bytes.go
Line 25: warning: "transfered" is a misspelling of "transferred" (misspell)
Line 28: warning: "transfered" is a misspelling of "transferred" (misspell)
node/metadata/build_info.go
Line 19: warning: "overriden" is a misspelling of "overridden" (misspell)
node/tequilapi/http_api_server.go
Line 44: warning: "addres" is a misspelling of "address" (misspell)
node/utils/cancelable.go
Line 37: warning: "succeded" is a misspelling of "succeeded" (misspell)
Line 64: warning: "immediatelly" is a misspelling of "immediately" (misspell)

**Comment by soffokl** [comment]
@tonyxia2016 it's fixed now, thank you for the issue.
