### ISSUE TITLE
Connected, but no internet connection -> can't disconnect

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3080]
Reopening https://github.com/mysteriumnetwork/node/issues/3078

**Describe the bug**
Attempting to connect to node 0xc37f4aaeb92adad7245c737b1189a928b621147f.
- It says it's connected, but there's no internet connection. Then I can't disconnect (stuck in disconnecting state). Need to kill connection manually via android taskbar.

This is an old bug, happens rarely, might be a chance to catch it

**To Reproduce**
Connect to the same node 0xc37f4aaeb92adad7245c737b1189a928b621147f on Android.

**Expected behavior**
If it fails to connect (e.g. timeouts), it shouldn't hang the app in disconnecting state. It should throw error, and get back to disconnected state, so I can try other nodes.
Relaunching app / rebooting phone on bad node shouldn't be considered satisfactory behavior.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Node version: 0.41.3
 - OS: Galaxy 8, Android 9

**Additional context**
Can't provide logs, as there's no way to gather them on Android yet to my knowledge.

**Comment by cvl** [comment]
Just experienced similar behavior with another node on MacOS (i.e. not Android): 0x778e12cfdd1470d4af211923f7faba1ea391a37b

Also connected -> no internet connection.
Then tried disconnecting - no response. After some time it disconnected finally.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/5919069/mysterium-node.log)

**Comment by cvl** [comment]
Again, on Android this time.
Node: 0.42.1
Provider node: 0xa95897d5fd929d25d7a2cf7e5a2ee36c173f029b

Note: This node is actually a good node: I've 14 successful connections (and 0 fails) to this node in the past, including 2 conns at the same day, same node version. The caveat is, all those connections in the past were from desktop app (either macos, or windows), but never android. So this was the first attempt to connect from Android.

Logs:
[mysterium-node 13.log](https://github.com/mysteriumnetwork/node/files/5978160/mysterium-node.13.log)

**Comment by chompomonim** [comment]
This is quite old issue. I believe in 0.47.1 it should be fixed for mobile.
