### ISSUE TITLE
[android, feature request] make it possible to send diagnostics report

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3081]
Same as in desktop app - it should be possible to send diagnostics report with app logs (including node logs).

**Comment by tomasmik** [comment]
I believe you already can do that. Here is one that I made as a test: https://github.com/mysteriumnetwork/node-user-reports/issues/1751

Or did you mean something else?

**Comment by cvl** [comment]
As far as I can see this sends email & message. Does this send logs as in desktop app?

If so, how could I change the url it sends logs to. In desktop app I can set the url via node config: { url: "<url here>" }

**Comment by tomasmik** [comment]
As far as I know it does send logs. @tadaskay could you comment a big more on this? Is this configurable?

**Comment by tadaskay** [comment]
https://github.com/mysteriumnetwork/node/blob/a818674e18a912869e2eeb8e97f51bccc342edcc/config/flags_node.go#L86

```
	FlagFeedbackURL = cli.StringFlag{
		Name:  "feedback.url",
		Usage: "URL of Feedback API",
		Value: "https://feedback.mysterium.network",
	}
```

Here's a reference implementation of that service: https://github.com/mysteriumnetwork/feedback

**Comment by cvl** [comment]
please don't close unresolved issues

**Comment by cvl** [comment]
reopened https://github.com/mysteriumnetwork/node/issues/3086

**Comment by chompomonim** [comment]
@cvl this issue was closed because there is already possible to configure own feedback service. I can see it more as need of more documentation rather that lack of functionality. There will be separate ticket to create tutorial how to create own dVPN app on top of Mysterium Network.
