### ISSUE TITLE
[android, feature request] make it possible to send diagnostics report

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3086]
Same as in desktop app - it should be possible to send diagnostics report with app logs (including node logs).

This should be configurable (same as in desktop app) so the logs wouldn't be sent to Mysterium, but to app owner.

**Comment by tadaskay** [comment]
This has been answered in https://github.com/mysteriumnetwork/node/issues/3081#issuecomment-773410286

**Comment by cvl** [comment]
Are you suggesting to fork node code for mobile to configure this? Could you elaborate?

**Comment by tadaskay** [comment]
No, this is passable as an argument when creating a MobileNode instance.

**Comment by tadaskay** [comment]
```kt
        val options = Mysterium.defaultNodeOptions().apply { 
            feedbackURL = "https://portals.com/feedback"
        }

        mobileNode = Mysterium.newNode(filesPath, options)
```

**Comment by cvl** [comment]
Perfect, thanks!
