### ISSUE TITLE
[windows, bug] can't register node - registration failed

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3090]
User can't register node: he's stuck on registration in progress error. App restart doesn't help either.

Node 0.41.3
Logs:
[mysterium-node 7.log](https://github.com/mysteriumnetwork/node/files/5936650/mysterium-node.7.log)

**Comment by vkuznecovas** [comment]
0.42.1 fixes this, will need to bump clients.

**Comment by cvl** [comment]
Perfect, thanks!

**Comment by cvl** [comment]
Reopened, looks similar: https://github.com/mysteriumnetwork/node/issues/3137
