### ISSUE TITLE
[android, bug] java.lang.UnsatisfiedLinkError at defaultNodeOptions

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3095]
Got this exception reported from 21 users yesterday (8th Feb). Devices OnePlus or Samsung, 62% are Android 11 devices. users.
Can't reproduce by myself though.

Looks like some issue when calling Mysterium.defaultNodeOptions()

Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: library "libgojni.so" not found
java.lang.Runtime.loadLibrary0 (Runtime.java:1087)
java.lang.System.loadLibrary (System.java:1664)
go.Seq.<clinit> (Seq.java:37)
go.Seq.touch
mysterium.Mysterium.<clinit> (Mysterium.java:12)
mysterium.Mysterium.defaultNodeOptions (Mysterium.java)
network.portals.service.core.MysteriumAndroidCoreService.startMobileNode (MysteriumAndroidCoreService.kt:38)
network.portals.service.core.MysteriumAndroidCoreService.access$startMobileNode (MysteriumAndroidCoreService.kt:14)
network.portals.service.core.MysteriumAndroidCoreService$MysteriumCoreServiceBridge.startNode (MysteriumAndroidCoreService.kt:74)
network.portals.service.core.DeferredNode$start$startJob$1.invokeSuspend (DeferredNode.kt:32)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (Dispatched.kt:241)
android.os.Handler.handleCallback (Handler.java:938)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:978)

**Comment by tomasmik** [comment]
Did you make the changes suggested here: https://github.com/mysteriumnetwork/node/issues/3086 because if so, I would assume this is related.

**Comment by cvl** [comment]
Those changes are unreleased yet, so no.

Here's some short thread about this https://stackoverflow.com/questions/60073428/couldnt-find-libgojni-so
Perhaps it's related to some less common arch used?

What's strange, that it seems that this occurred for a brief period (at around 8:36PM).
Have you noticed anything similar to your app (esp. yesterday)?

**Comment by cvl** [comment]
It seems the error occurred for two device types:
OnePlus 8 (IN2020). Android 11.
samsung Galaxy A20. Android 10.

**Comment by cvl** [comment]
If you don't experience this, I'd suggest to close this until this reoccurs. Somehow I feel this was a one time thing.
