### ISSUE TITLE
Desktop app stuck on loading screen

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3109]
**Describe the bug**
I have just installed the v3.5.0 and got a loading screen (app does not open).

**Screenshots**
<img width="497" alt="Screenshot 2021-02-11 at 07 58 43" src="https://user-images.githubusercontent.com/60128746/107607906-2f790100-6c43-11eb-8f66-d80c1cdc7661.png">

<img width="642" alt="Screenshot 2021-02-11 at 08 24 56" src="https://user-images.githubusercontent.com/60128746/107607924-34d64b80-6c43-11eb-8ea2-27cd8ea651f6.png">

**Environment (please complete the following information):**
 - Node version:  0.42.1
 - Desktop app version : 3.5.0

**Comment by tomasmik** [comment]
I think this: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/96 fixes it.
