### ISSUE TITLE
Empty service price values in config.toml

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3110]
Node: 0xd58ebba40530033f8779e92a8a572d527c19dddd, v0.42.2
```
myst@raspberrypi:~ $ cat /etc/mysterium-node/config.toml 
[mmn]
  api-key = ""
[openvpn]
[payment]
[shaper]
  enabled = false
[terms]
  consumer-agreed = true
  provider-agreed = true
  version = "0.0.27"
[wireguard]
myst@raspberrypi:~ $
```

Service price on MMN:
<img width="434" alt="Screenshot 2021-02-11 at 11 14 09" src="https://user-images.githubusercontent.com/60128746/107618485-4ecf5880-6c5a-11eb-9cba-7e1d2c0b818d.png">

**Comment by tomasmik** [comment]
I tried choosing default price, changing the price, keeping the same without moving the slider in on-boarding but I can't repeat this bug.

**Comment by tomasmik** [comment]
I tried more things, found no way to reproduce this. Closing for now.
