### ISSUE TITLE
Can't save beneficiary wallet address in NodeUI

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3114]
**Describe the bug**
It allow to change/adjust the input field but "Save" button is disabled (not clickable). 
E.g. provider: 0xe1c4079ce3ead5ce6aea225fa5fd01dc45557046

**Environment (please complete the following information):**
 - Node version: 0.42.3
 - OS: Raspbian GNU/Linux 10 (buster)

**Comment by tomasmik** [comment]
I assume this was fixed in: https://github.com/mysteriumnetwork/node/releases/tag/0.42.5
If not please re-open the issue.
