### ISSUE TITLE
Incorrect session storage information for local session

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#3115]
**Describe the bug**
Starting a local service and connecting to it results in incorrect stat reporting via the sessions endpoint.

**To Reproduce**
1. Start local noop service.
1. Connect to the local noop service via cli with another identity.

**Expected behavior**
These two endpoints should show a sum_tokens that's at least pretty close to each other:
http://localhost:4050/sessions/stats-aggregated?direction=Provided&provider_id={your_id}
http://localhost:4050/sessions/stats-aggregated?direction=Consumed&provider_id={your_id}

**Screenshots**
Direction provided:
<img width="346" alt="Screen Shot 2021-02-15 at 10 54 07 AM" src="https://user-images.githubusercontent.com/18392269/107924889-57869e00-6f7c-11eb-80f1-caea9fcc837b.png">
Direction consumed:
<img width="411" alt="Screen Shot 2021-02-15 at 10 54 00 AM" src="https://user-images.githubusercontent.com/18392269/107924916-61a89c80-6f7c-11eb-8368-44d1455bcf65.png">

**Environment (please complete the following information):**
Any, latest master.

**Additional context**
This causes incorrect info being shown in web UI.

While this is non-critical
, it would be nice to figure out a way to fix this as it helps local development.

**Comment by chompomonim** [comment]
@vkuznecovas is this still relevant? Should we close it?
