### ISSUE TITLE
[android, bug] can't start node "could not get hermes url: daily request count exceeded, request rate limited"

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3120]
Node: 0.42.1

mysterium.Mysterium.newNode (Mysterium.java)
network.portals.service.core.MysteriumAndroidCoreService.startMobileNode (MysteriumAndroidCoreService.kt:42)

Error:
could not bootstrap dependencies: could not get hermes url: daily request count exceeded, request rate limited

Looks like something on the server-side?

**Comment by vkuznecovas** [comment]
This is duplicate of #3117. We're working on multiple fronts to solve this :)

**Comment by cvl** [comment]
Good luck :)
