### ISSUE TITLE
Node configure the agent

### ISSUE THREAD

**Issue by frank-pian** [mysteriumnetwork/node#3125]
**Describe the bug**
I build a node in china. But the API interface is not responding because of the GFW(Great Firewall).
Can I set up proxy bypass?

![aaa](https://user-images.githubusercontent.com/8214804/108355301-9a1ed380-7225-11eb-9f65-5475e87d1a4c.JPG)
![b](https://user-images.githubusercontent.com/8214804/108355791-41036f80-7226-11eb-84e8-205129ebaaa9.JPG)

**Comment by vkuznecovas** [comment]
This is a fault on our side, expect a patch soon.

**Comment by tomasmik** [comment]
I've added Pilvytis to the DNS map, this issue should be resolved when we merge and release the change. Thanks for the report.
