### ISSUE TITLE
Build dVPN app for macOS with M1 chip

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3134]
Node is ready for M1 support, so dVPN app should be built for it.

**Comment by vkuznecovas** [comment]
We have account setup for m1 runner for gitlab. Need to:

1) write ansible script to install errything that's needed on the machine and register the runner. This will involve workarounds as stuff doesn't really work on apple silicone yet.
1) add m1 build job. Will need to write a mage script for it.

**Comment by tadaskay** [comment]
Fixed by https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/368 https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/369
