### ISSUE TITLE
DNS leak test failed

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3135]
DNS started leaking.
Node: 0.42.1, Windows.

Example node: 0xd503c59ae90180150e6f7259d89d3b9d35e79606
<img width="714" alt="Screenshot 2021-02-23 at 13 20 55" src="https://user-images.githubusercontent.com/100252/108837523-08bfb080-75db-11eb-89af-64e7883bf8b5.png">
<img width="787" alt="Screenshot 2021-02-23 at 13 19 24" src="https://user-images.githubusercontent.com/100252/108837539-0c533780-75db-11eb-9bbf-90afd52b5124.png">

**Comment by cvl** [comment]
@chompomonim tried once more just now.
Identity: 0x8c5bd3f9c15eb4a045550e2f66b1ac1c3c221c0d
Windows
Node: 0.44.0

Another ISP than before (was Mezon, now Telia).

Test 1: https://dnsleak.com
<img width="605" alt="Screenshot 2021-03-05 at 20 05 20" src="https://user-images.githubusercontent.com/100252/110155346-274d5500-7dee-11eb-9e67-2b32261a32b3.png">

Test 2: https://www.dnsleaktest.com/
<img width="801" alt="Screenshot 2021-03-05 at 20 05 15" src="https://user-images.githubusercontent.com/100252/110155421-45b35080-7dee-11eb-85a8-7dcd2978210b.png">

**Comment by soffokl** [comment]
@cvl Could you please retest it with a node version 0.45? 
I'm failed to reproduce it on my installations.

**Comment by cvl** [comment]
Still leaking (latest node). Also reported by few of our users.

First attempt (UK node): 0x58ea21952024b699c429ab549f6df590d14e91fc
**https://www.dnsleaktest.com**
<img width="826" alt="Screenshot 2021-03-23 at 11 30 10" src="https://user-images.githubusercontent.com/100252/112124794-6be93680-8bcb-11eb-87cf-dd77b5bd9084.png">
**https://ipleak.net/**
<img width="1140" alt="Screenshot 2021-03-23 at 11 32 33" src="https://user-images.githubusercontent.com/100252/112124870-7f949d00-8bcb-11eb-9592-30bf015c836c.png">

Second attempt (US node): 0x723e53e81220e891da240d64a1a0eb1a566a3dc9
**https://www.dnsleaktest.com/**
<img width="907" alt="Screenshot 2021-03-23 at 11 34 57" src="https://user-images.githubusercontent.com/100252/112125216-dc905300-8bcb-11eb-8f69-3058fe8dd0ce.png">
**https://ipleak.net/**
Didn't detect leak.

**Comment by cvl** [comment]
To reproduce try using the same setup:
- Use Windows desktop app (i.e. not cli, not mac app, not mobile app etc)
- DNS settings: provider
- Connect to 3rd party nodes (could try the ones in the example)

**Comment by soffokl** [comment]
It does not happen to me, I tried many services to test and same providers as you:
![image](https://user-images.githubusercontent.com/8612618/113660356-ae2f6f00-96c5-11eb-9e6f-9738872680e9.png)
![image](https://user-images.githubusercontent.com/8612618/113660360-b38cb980-96c5-11eb-93f3-a195bb32e75e.png)

Probably you have some configuration different.

**Comment by cvl** [comment]
Are you using DNS settings: provider ?

**Comment by soffokl** [comment]
Yep, it was a provider setting. This is probably related to the system setup.
We have found what could create this problem. Working on a solution to fix it.
