### ISSUE TITLE
[windows, bug] can't register node - registration failed - already registered

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3137]
User stuck on "registration in progress" screen, again.
Perhaps related to https://github.com/mysteriumnetwork/node/issues/3090

Node: 0.42.1, Windows.
Perhaps relevant that user is in Iran.

Logs attached:
[mysterium-node 14.log](https://github.com/mysteriumnetwork/node/files/6028689/mysterium-node.14.log)

**Comment by vkuznecovas** [comment]
The status is reported correctly as RegistrationError.

```
2021-02-23T13:45:20.431 DBG source/eventbus/event_bus.go:81          > Published topic="registration_event_topic" event={ID:{Address:0x5e8994a6ac990de01360812983efab38b4e7c8f0} Status:InProgress ChainID:5}
...
2021-02-23T13:45:49.962 ERR source/identity/registry/registry_contract.go:256 > Subscription error error="read tcp 10.7.2.2:50581->54.90.76.2:443: wsarecv: An established connection was aborted by the software in your host machine."
2021-02-23T13:45:49.963 DBG source/eventbus/event_bus.go:81          > Published topic="registration_event_topic" event={ID:{Address:0x5e8994a6ac990de01360812983efab38b4e7c8f0} Status:RegistrationError ChainID:5}
```

At this point in time node is unable to assert the registration status, therefore the connection attempt fails.

It seems that your app is not handling the the registration error status or handling it incorrectly. It's up to the user to handle the `registration_event_topic` events.

**Comment by cvl** [comment]
Can you elaborate?

Node fails to register identity, what can I do in this case? How should I handle it correctly - try again or ... ?
Why does it fail to register?

This is a new bug, please investigate.

**Comment by chompomonim** [comment]
Yes, when registration is failing, you should send registration request one more time.

**Comment by cvl** [comment]
This doesn't help, as mentioned previously.

Node itself needs to be fixed to work in such countries as Iran. As suggested, it can be done using designated residential nodes in friendly countries which would work as gateways for dns/location/discovery and similar services.

Desktop app cannot resolve this, it must be done on node level.

I understand this will take time, and I remember you've told me few weeks ago it's a priority for Mysterium now (to make Mysterium work in Iran/China and similar countries), so can't wait :)

**Comment by cvl** [comment]
Also note, that this discussion has been explained as "can't do" in another issue: https://github.com/mysteriumnetwork/node/issues/3140
