### ISSUE TITLE
Limit MA to check for active service only

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3139]
Currently, our monitoring agent is doing checks for both (wg and openvpn) by default. There are cases when provider disable openvpn (in NodeUI or via flags) and run wg service only. As a result, node status switch to "test failed" even if wg service is working properly and adding new sessions.

I think our MA should check only active service protocols.

<img width="696" alt="Screenshot 2021-02-24 at 07 39 10" src="https://user-images.githubusercontent.com/60128746/108953207-7fa88800-7673-11eb-833b-3e3b8c26dab5.png">
<img width="1100" alt="Screenshot 2021-02-24 at 07 39 27" src="https://user-images.githubusercontent.com/60128746/108953213-820ae200-7673-11eb-8f59-3ce1b610cb69.png">
<img width="1291" alt="Screenshot 2021-02-24 at 07 40 54" src="https://user-images.githubusercontent.com/60128746/108953308-a8c91880-7673-11eb-93de-66014982e0d5.png">

**Comment by ignasbernotas** [comment]
Easiest way to fix this from MMN's side would be to check whether the proposal in the discovery db exists and isn't old enough to assume the service is running. We need to check the time interval when the proposal gets unpublished from discovery because the database records exist indefinitely.

**Comment by ignasbernotas** [comment]
Fixed and released. MMN now checks which services are active by viewing the proposals in discovery.
