### ISSUE TITLE
Handle Public IP change

### ISSUE THREAD

**Issue by arpitjindal97** [mysteriumnetwork/node#3145]
**Description**
Here in India, there are many ISP who assign Private IP address to resident. Multiple home share single Public IP address. They change Public IP address on the fly at any unknown interval. 
As far as I know, when mysterium node starts it checks for IP in the beginning and then keeps broadcasting the same. 
Solution to overcome this problem could be introducing a cron job mechanism inside node to check for Public IP in every 10 mins.

**Expected behavior**
Node should be able to detect if the public IP is changed.

**Comment by vkuznecovas** [comment]
We're already detecting public IP changes. Are you experiencing issues with this?

The current flow goes like this:

On the consumer side, public IP info is flushed after every connection. Prior to establishing a new connection, the public IP info is refreshed.

On the provider side, public IP info is cached for 5 minutes and re-checked with the cache every time a new session begins. On a cache miss, the public IP info is updated.

**Comment by arpitjindal97** [comment]
Cool, closing the bug
