### ISSUE TITLE
[NodeUI] Beneficiary wallet address switched to 0x000..

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3146]
**Describe the bug**
After restarting/rebooting the Mysterium node - beneficiary (wallet) address changed to 0x000..
e.g.
0xacf3ac00ccf0a4f14670501b8acfa4f8ea49378a
0x0286756508c3ee5c516a3f6c27f95341d52f8a65

**Expected behavior**
I expect my wallet address to be visible in NodeUI.

**Screenshots**
<img width="519" alt="Screenshot 2021-02-25 at 13 38 53" src="https://user-images.githubusercontent.com/60128746/109409431-518cb600-799b-11eb-9ccc-e664c7e6164a.png">

**Environment (please complete the following information):**
 - Node version: 0.42.6
 - OS: Ubuntu 20.10

**Additional context**
It seems to be a visual bug only. The actual ERC-20 address I've set during on-boarding is still there.

**Comment by mixmafritz** [comment]
Get this problem, here is my node ID : 0x0baa8b4be102923afdd84cc821871a849ba8e36a

**Comment by tomasmik** [comment]
These two are probably related and should be addressed shortly: https://github.com/mysteriumnetwork/node/issues/3136

**Comment by tomasmik** [comment]
This should also be addressed with: https://github.com/mysteriumnetwork/dvpn-web/pull/176

@mdomasevicius close this issue if I am right.

**Comment by tomasmik** [comment]
This was fixed in release: https://github.com/mysteriumnetwork/node/releases/tag/0.43.0
