### ISSUE TITLE
[windows, bug] can't connect, multiple errors

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3152]
Node: 0.42.6
User can't connect on Windows, gets multiple errors in the logs:

Could not recover Grand Total Promised error="could not request consumer data from hermes: resource not found"
retry 2 of 3 error="could not get consumers channel: no contract code at given address"

INF source/core/connection/manager.go:278    > Cancelling connection initiation:  error="could not start new connection: failed to start connection endpoint: could not configure device: failed to create wg interface: failed to create TUN device myst: could not create Wintun tunnel: Error creating interface: SetupDiCallClassInstaller(DIF_INSTALLDEVICE) failed: This operation requires an interactive window station."

Logs:
[mysterium-node 24.log](https://github.com/mysteriumnetwork/node/files/6067409/mysterium-node.24.log)

**Comment by tomasmik** [comment]
First error is normal, it just means that the user has not yet been registered.
Second error is worth looking into.

**Comment by cvl** [comment]
@tomasmik previously it was implemented, that when registration status is in progress, user can still connect.
What I can see now, this changed. When it's in progress - balance is zero, and all the hell breaks loose.

Has this been changed? I.e. can user connect while registration is in progress?

**Comment by cvl** [comment]
Kinda answered my question with trial: it works, in most cases.
I believe "could not request consumer data from hermes: resource not foun" is also a bug (separate one), as it behaves differently on each separate run. Sometimes it works well, sometimes it produces errors, resulting in inconsistent behavior (e.g. failing to connect to nodes).

Created an issue for this: https://github.com/mysteriumnetwork/node/issues/3154

**Comment by cvl** [comment]
User gave some feedback, might be the cause:

Firstly, during installation, the Norton360 antivirus cursed, messages about an untrusted certificate were issued, then he did not like the traffic going through an unfamiliar proxy server. There was also a report that the reputation of the application is very low.
I had to disable the antivirus to use the Portal.

**Comment by tomasmik** [comment]
> @tomasmik previously it was implemented, that when registration status is in progress, user can still connect.
> What I can see now, this changed. When it's in progress - balance is zero, and all the hell breaks loose.
> 
> Has this been changed? I.e. can user connect while registration is in progress?

No, that has not changed. What I meant to say, was that the error is harmless and shouldn't impact anything.

About the second part, antivirus software could definitely be the problem here. Usually such issues can be resolved by emailing the antivirus company. Actual screenshots of antivirus alerts/errors would help.
