### ISSUE TITLE
Trying to connect while registering sometimes fails

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3154]
Node: 0.42.6
System: MacOS + Windows

Tried two clean runs, same MacOS.

One resulted in errors, and failed to connect to good nodes (because it failed to retrieve balance I guess).
Both attempts are while registration is in progress, one worked perfectly well, the other not. Must be a bug.
Also, both attempts produced wrong balance (instead of 5 MYST it says I have 7.837906341092476000 MYSTS) in some quick glitch (then it reverts back to 5). Might be a clue.

There's clearly some inconsistency, most likely concurrency problems.

Bad run logs:
[bad.log](https://github.com/mysteriumnetwork/node/files/6068125/bad.log)

Good run logs:
[good.log](https://github.com/mysteriumnetwork/node/files/6068127/good.log)

**Comment by vkuznecovas** [comment]
> Also, both attempts produced wrong balance (instead of 5 MYST it says I have 7.837906341092476000 MYSTS) in some quick glitch (then it reverts back to 5).

^ this is not a bug. This is normal behaviour as fee gets deducted. This is then handled in node appropriately.

Other points still stand though, need investigating.
