### ISSUE TITLE
Unexpected use of my web service in this application

### ISSUE THREAD

**Issue by benjojo** [mysteriumnetwork/node#3155]
**Describe the bug**
It appears this application hard codes my web service unexpectedly to me 

**To Reproduce**
1. Be me and run  `badupnp.benjojo.co.uk` 
2. Unexpected traffic with no explanation 
3. Blocked it by user agent since there was no description on it and it looked DoS-ey
4. Find this repo via github code search

**Expected behavior**
Ideally for people to ask before hard coding my web tool endpoints :) I can provide a dedicated URL if that is helpful to you, but please at least change the User-Agent to something descriptive.

**Screenshots**

https://github.com/mysteriumnetwork/node/pull/2846

**Comment by soffokl** [comment]
Hey @benjojo. Sorry to hear this. 
It didn't suppose to be a significant load for your service. A few hundred nodes do this check once on startup only.
We will be running our own service if this causes problems for you. 

I'll make sure we replaced it with our own solution. 
Thanks for letting us know about the problem.

**Comment by benjojo** [comment]
@soffokl no direct harm yet! The load is mostly fine _for now_ but the lack of user agent and ramp-ish growth worried me, Can you put a descriptive user-agent on (maybe also search for possible other cases of similar things) the request and I can at least keep a better eye on it, rather than `goclient-v0.1` :)

I'll shout if the load gets too much

**Comment by benjojo** [comment]
But also in general shooting an email over is best to just let the operator know rather than then finding out via logs / weird things happening

**Comment by vkuznecovas** [comment]
Once again sorry for any inconvenience caused.

I've added a user agent string to our HTTP requests. Once nodes update, it will be sent out with all HTTP requests.

**Comment by benjojo** [comment]
Thanks!
