### ISSUE TITLE
Truncate old node logs

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3164]
As node outputs logs pretty heavily, it quickly grows to big heavy files.
It produces ~53MB in 10 days, so in a year it will be 2GB.

Logs should be handled in a similar fashion as e.g. apache logs are handled:
- Zip old logs each 2-3 days
- Delete 1 or 2 months old logs

**Comment by soffokl** [comment]
Could you please fill the template when you are creating an issue? 
It's not clear what platform you are referring here.

**Comment by cvl** [comment]
All of them.

The template is mundane and irrelevant in most cases, I'm favoring (well - trying to) clarity over bureaucracy.

Here's an example in this case (no added information, just a lot of boilerplate):

**Describe the bug**
As node outputs logs pretty heavily, it quickly grows to big heavy files.
It produces ~53MB in 10 days, so in a year it will be 2GB.

**To Reproduce**
Steps to reproduce the behavior:
N/A

**Expected behavior**
Logs should be handled in a similar fashion as e.g. apache logs are handled:

Zip old logs each 2-3 days
Delete 1 or 2 months old logs

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Node version: Any
 - OS: Any
 - Desktop app version (if applicable): Any
 - Docker (if applicable): Any

**Additional context**
N/A

**Comment by tomasmik** [comment]
We've actually received some complaints about this already over on our discord server. I'll add this to the board.

Logs should probably be truncated no matter if node is running in consumer or provider modes.

**Comment by tomasmik** [comment]
@cvl if you were actually able to produce this issue, could you provide some specific steps? I've tested this and it seems like it works.
```
$ ls -la logs/
```
```
-rw-r--r-- 1 myst myst 4312753  mysterium-node.log
-rw-r--r-- 1 myst myst  375936  mysterium-node.log.gz.20210330T143514
-rw-r--r-- 1 myst myst  378570  mysterium-node.log.gz.20210330T143519
-rw-r--r-- 1 myst myst  375813  mysterium-node.log.gz.20210330T143524
-rw-r--r-- 1 myst myst  377601  mysterium-node.log.gz.20210330T143529
-rw-r--r-- 1 myst myst  358258  mysterium-node.log.gz.20210330T143534

```

**Comment by cvl** [comment]
Thanks.

- which node version fixes this?
- are the logs destroyed after a while? i.e. if user uses VPN for 1+ years, will he get clogged with log.gz files, or would they be removed as per suggestion (Delete 1 or 2 months old logs)?
- is this fixed for mobile as well?

**Comment by tomasmik** [comment]
This is actually in the current node version and has been for a very long time. This is why I said that if you know how to reproduce this, please let me know. Currently the max allowed file size for the log file is [50MB](https://github.com/mysteriumnetwork/node/blob/master/logconfig/rollingwriter/rollingwriter.go#L46) (it can go a bit over that, but not much) after that it gets compressed. [5 compressed files](https://github.com/mysteriumnetwork/node/blob/master/logconfig/rollingwriter/rollingwriter.go#L49) can be stored at max.

https://github.com/mysteriumnetwork/node/blob/master/logconfig/rollingwriter/rollingwriter.go#L63

**Comment by cvl** [comment]
Well 23 days ago you've said that you're receiving same complaints. So not so long time ago :)

Thanks, I'll check. The logic sounds reasonable.

**Comment by cvl** [comment]
p.s. perhaps you know, if user sends log files (using node api), will it send all compressed + uncompressed log files, or just the uncompressed one?

**Comment by cvl** [comment]
Btw, does this work for mobile as well?

**Comment by tomasmik** [comment]
> Well 23 days ago you've said that you're receiving same complaints. So not so long time ago :)
> 
> Thanks, I'll check. The logic sounds reasonable.

Yes I did and I investigated this, but could not find a way to reproduce it.

**Comment by cvl** [comment]
Got it. Will keep an eye on it.
