### ISSUE TITLE
Prevent DNS leaks via IPv6

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3185]
At the moment Mysterium is using on IPv4 for tunneling traffic. Adding IPv6 is quite big tasks and requires significant effort to make it right and secure. 

However at the moment we could at least block IPv6 at all when Mysterium session active to allow only IPv4. This will prevent DNS leaks via IPv6 and will give more privacy for users.

**Comment by Amin-Idris** [comment]
Some suggestions for implementing IPv6 support in Mysterium:

**1. Address allocation:** Mysterium nodes should be able to dynamically allocate IPv6 addresses to clients, ensuring that each client has a unique and private address for its session. This can be achieved using stateless address autoconfiguration (SLAAC) or DHCPv6.

**2. Tunneling:** IPv6 packets should be encapsulated within IPv4 packets for transmission over the existing Mysterium network. This can be done using protocols such as IP-in-IP (IPIP) or GRE (Generic Routing Encapsulation).

**3. Routing:** Mysterium nodes should be able to route IPv6 traffic between clients and servers. This may require modifications to the existing routing mechanisms in Mysterium, such as the Pathfinding Network.

**4. Security:** IPv6 traffic should be encrypted to protect user privacy and prevent eavesdropping. This can be achieved using strong encryption algorithms such as AES or ChaCha20.

**5. Compatibility:** Mysterium should be compatible with existing IPv6 infrastructure, including routers, firewalls, and applications. This may require additional configuration or software updates.

Adopting IPv6 will require a significant effort from the Mysterium team, but it will bring significant benefits in terms of scalability, security, and privacy. Here are some specific implementation steps that can be taken:

**1. Design and implement a new IPv6 routing protocol for Mysterium.**

**2. Develop a mechanism for dynamically allocating IPv6 addresses to clients.**

**3. Modify the Pathfinding Network to support IPv6 routing.**

**4. Integrate IPv6 support into the Mysterium client software.**

**5. Test and debug the IPv6 implementation to ensure that it is secure and reliable.**

**6. Migrate the Mysterium network to IPv6 over time.**

The transition to IPv6 will be gradual, and not all nodes and clients will need to support IPv6 immediately. However, the long-term goal should be to make Mysterium fully compatible with IPv6 as soon as possible.

By adopting IPv6, Mysterium can become a more scalable, secure, and private VPN network for users worldwide.
