### ISSUE TITLE
[bug, android] fix identity registration flow (once and for all)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3200]
**Describe the bug**
Install app -> Click connect -> disconnect -> Click connect again -> App shows error:

![Screenshot_20210310-192235_MysteriumVPN](https://user-images.githubusercontent.com/100252/110670520-247ba700-81d6-11eb-81ce-af110f822ba4.jpg)

**Expected behavior**
There's no objective reason for such err behavior, as it clearly can connect while being unregistered (i.e. identity registration is in progress), as it does connect successfully the first time.
So it should connect no matter if its registration status is registered or in progress.

**Environment (please complete the following information):**
 - Node version: Any
 - OS: Android

**Comment by tomasmik** [comment]
I believe this is duplicate: https://github.com/mysteriumnetwork/node/issues/2382

It's included in the board already just not fixed yet.
