### ISSUE TITLE
Resetting the password by running myst reset does not reset the password

### ISSUE THREAD

**Issue by xospecialk** [mysteriumnetwork/node#3201]
**Describe the bug**
After forgetting my password to the NodeUI, I tried running myst reset and myst reset --tequliapi and while the output says the reset was successful, the default password of ```mystberry``` did not work.

**To Reproduce**
1. ssh to your node
2. run ```myst reset``` 
3. goto <your host>:4449
4. Enter password of ```mystberry```
5. run ```myst reset --tequilapi```
6. goto <your host>:4449
7. Enter password of ```mystberry```

**Expected behavior**
Expect to be able to login to the NodeUI with default password ```mystberry```

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 0.44.0
 - OS: raspbian buster

![image](https://user-images.githubusercontent.com/16543115/110796415-ed44de80-8245-11eb-8c26-bdc5327df038.png)
![image](https://user-images.githubusercontent.com/16543115/110796451-f635b000-8245-11eb-8ddf-518b5d217778.png)

**Comment by tomasmik** [comment]
Hi, thanks for reporting the issue. I've just tested this on my two nodes, it seems like I was able to reset my password without any issues by running `myst reset --tequilapi`

Note though after running this command you should clear cookies/browser cache just in case and make sure you're actually going to `192.168.0.2:4449` and not ` `192.168.0.2:4449/#/login` . It should redirect you to onboarding page with only a single step which will be the password [reset](https://user-images.githubusercontent.com/40318863/110827120-6c660100-829e-11eb-9739-af32370f101f.png)

If you're still not able to change your password, please let me know, I'll investigate further.

**Comment by xospecialk** [comment]
Correct, after running ```myst reset --tequilapi``` I goto ```192.168.0.2:4449``` which redirects me to ```192.168.0.2:4449/#/login```.  I've cleared my cookies and browser cache.

**Comment by tomasmik** [comment]
Thats very strange, I will investigate this further.

**Comment by Federbein0815** [comment]
Hi I have the same issue with the prebuilt deb file for linux. cant login through the gui. the password for mystberry didnt worked.

**Comment by tomasmik** [comment]
Are you running this command as a `sudo` or as your regular user? Could you provide me with the output from `myst config show | grep dir`?

**Comment by tomasmik** [comment]
I am sorry but neither me nor the team is able to reproduce this issue.

One crude way of fixing this would be to just remove the `nodeui-pass` file from node data dir (_make sure you backup that file before removing it, just in case)_. You can find the data-dir by executing `myst config show | grep data-dir`. That will force a password change once you go nodeUI.

**Comment by xospecialk** [comment]
```myst config show | grep dir
config-dir: /etc/mysterium-node
data-dir: /var/lib/mysterium-node
log-dir: /var/lib/mysterium-node/.mysterium/logs
runtime-dir: /var/run/mysterium-node
script-dir: /etc/mysterium-node
```

I am running as sudo.

Removing the nodeui-pass file did work though, so thats a relief
