### ISSUE TITLE
Registration status migration when launching new hermes/registry

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#3204]
Add migration to set all registration statuses in `registry/storage.go` to unregistered. This forces re-checks on blockchain on app launch and will trigger the registration flow.

Should only be released when we're ready for matic.

**Comment by tomasmik** [comment]
This works: https://github.com/mysteriumnetwork/node/compare/migration-registration-new

For now lets leave it as a branch 🤷🏻
