### ISSUE TITLE
[question] is Mysterium protected against DNS hijacking?

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3223]
If node acts as DNS provider, can it provide wrong resolved IP for domain?

Something like https://mobile.twitter.com/CreamdotFinance/status/1371448627663491088

**Comment by soffokl** [comment]
The node providing DNS can give you any IP-address, the same as ISP or other VPNs. 
Make sure that you are using HTTPS connection with a valid certificate to prevent leaking any sensitive information.

**Comment by cvl** [comment]
Okay, then this is a major security issue, and we need to resolve this.
