### ISSUE TITLE
Lost tokens

### ISSUE THREAD

**Issue by misss-m** [mysteriumnetwork/node#3229]
Hello!
Had many problems with the app. So the last time was fatal for me, because all my tokens gone.

Windows 10, god bless all its' users

First problem:
I use Mysterium VPN App. I Use Ethernet connection. If the connection with internet lost, or i will reboot my laptop without disconnecting Mysterium VPN, i will not have internet after rebooting. VPN seem to be hung. And it not disconnected after that. So after this i need to disconnect ethernet adaptor, connect to wifi, disconnect, reboot laptop, and only after these magical moves i have internen by cable and VPN works again.

But sometimes, if the internet lost while i use VPN the app hungs and don't want to load. It is on the step "Loading Daemon". Uninstall the app with regular uninstaller, clearing all caches using cmd doesn't help! If I install the app again it hungs on Loading Daemon. 
I solved that problem by:
Uninstall Mysterium VPN
Delete all files and folders from program files, user folder, App Data in Local and Roaming. 
After that, i installed Mysterium VPN, and it works.

**BUT**
There are no tokens on my account after that! 
I had about 100 tokens, but it gone! :(

Actualy the identity changed after deleting and reinstalling. So i've got 5 tokens. And i can use this bug every day (uninstall, delete all files and folders, get 5 tokens). But it is not comfortable.
I think u connect account tokens with the files in Users folder. But it is not safe.

Please: give me my tokens back :) I need to work. Also please solve the problem with the app, when it works and internet connection losts, and it hungs.

Thank you!

**Comment by tomasmik** [comment]
Hi there, when you deleted all the node files, you've also deleted the private key, so your identity is sort of lost forever now.. We're working on a way to backup your private key so that such problems dont happen in future: https://github.com/mysteriumnetwork/node/issues/3228

About the app hanging, connection dropping etc. we can for sure investigate this. Node logs at the time this happens would  help us figure out the issue quicker. You can find the logs in:
* `%USERPROFILE%\.mysterium\logs`
* `%USERPROFILE%\AppData\Roaming\MysteriumVPN\logs`
* `%PROGRAMDATA%\MystSupervisor`

**Comment by tomasmik** [comment]
Regarding the missing tokens please email: help@mysterium.network and provide your identity information.

**Comment by misss-m** [comment]
Hello!
Trying to hang the app on purpose, but it but fails :D will try more times and will send logs soon 
>Пятница, 19 марта 2021, 9:44 +03:00 от Tomas ***@***.***>:
> 
> 
>Hi there, when you deleted all the node files, you've also deleted the private key, so your identity is sort of lost forever now.. We're working on a way to backup your private key so that such problems dont happen in future:  #3228
>About the app hanging, connection dropping etc. we can for sure investigate this. Node logs at the time this happens would help us figure out the issue quicker. You can find the logs in:
>*  %USERPROFILE%\.mysterium\logs
>*  %USERPROFILE%\AppData\Roaming\MysteriumVPN\logs
>*  %PROGRAMDATA%\MystSupervisor
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Miss M

**Comment by chompomonim** [comment]
@etherunit could you help @misss-m to handle this issue?

**Comment by etherunit** [comment]
We have a conversation via emails. Will update shortly.
