### ISSUE TITLE
Could not connect with MysteriumVPN for Android

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3230]
We have apprx. 5-12% of the failed sessions (NG) according to https://testnet2-grafana.mysterium.network/d/yWVZNqCZk/country-stats?orgId=1&var-consumer_country=NG&var-provider_country=All&var-service_type=All&from=now-2d&to=now.

Majority of users on mobile apps (when sessions are failed) are getting `"Oops.. could not connect. Please try again later"` message (I've done multiple checks and it seems not related to provider). These are mostly users from Nigeria, Benin city, UAE and other "long distance" Africa, Asia regions. I think we need a better way to address the mobile app errors with more detailed info.

<img width="1349" alt="Screenshot 2021-03-19 at 10 19 14" src="https://user-images.githubusercontent.com/60128746/111750984-97eb7b80-889c-11eb-8937-924f96943dcb.png">

[User report A: 0x41bcac033e18bced33244942ad694d839c2bc42e #2130
](https://github.com/mysteriumnetwork/node-user-reports/issues/2130)[User report B: 0x9e779ce83fcd16da532e1a8466dd8355046f9a22 #2132
](https://github.com/mysteriumnetwork/node-user-reports/issues/2132)

Logs A: https://my.mysterium.network/admin/issues/download/2130
Logs B:  https://my.mysterium.network/admin/issues/download/2132

**Comment by tomasmik** [comment]
The ones related to registering could probably be solved by solving: https://github.com/mysteriumnetwork/node/issues/2382

**Comment by chompomonim** [comment]
I'm closing this issue because `1.0.0` release of mobile app has completely different UI and error messages. If there will be need, please open new issues with new bug reports about connection issues.
