### ISSUE TITLE
Multi user support for macOS desktop app

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3233]
**Describe the bug**
- Install app as Administrator (or Standard + enter admin credentials on install)
- Login as Standard user
- On app open, it asks for password - entering any password (standard or admin user's) doesn't work. Can't access Mysterium app as standard user.

**Environment (please complete the following information):**
 - Node version: Any
 - OS: Mac
 - Desktop app version (if applicable): Any
 - Docker (if applicable): specify docker version and image tag

**Comment by chompomonim** [comment]
> Node version: Any
> Desktop app version (if applicable): Any

Does it mean that you have tried with `v0.45.0-rc3` of node and `3.8.2` desktop?

**Comment by cvl** [comment]
Yes

**Comment by chompomonim** [comment]
I have one more question. Is this happening only on macOS or on Windows you're able to reproduce similar issues?

**Comment by cvl** [comment]
Haven't tried on Windows with standard user. I'll give it a shot and report.

**Comment by cvl** [comment]
Works well on Windows.

**Comment by chompomonim** [comment]
Ok, so this is macOS only related feature request. Thanks for rechecking.

**Comment by chompomonim** [comment]
At the moment we're not supporting multiple user setup of macOS. There are some rare cases when users have couple of users in their system and would like to make available installed dVPN app for all the system users.

We should make sure, that system administrator could be able to give app access for non admin users.

**Comment by cvl** [comment]
I find a growing tendency for Mysterium to change bugs to "feature requests".

This is important bug, not a feature request.

This matters, because feature requests are usually at the end of priority list.

Thousands of Mysterium users can't use Mysterium app because of this bug.

**Comment by cvl** [comment]
Also this is not only for multiple users setup.

It's not safe to use computer under Administrator account. If you want to improve your digital security, use computer on standard user. Mysterium breaks on standard user, yet it is digital security / privacy oriented app.

**Comment by chompomonim** [comment]
@cvl this is a feature request. We don't support many things, one of them is multi user support.

**Comment by chompomonim** [comment]
Also, please use our convertion and don't add [macos, bug] in the beginning of task. We use github tags for meta information.

**Comment by chompomonim** [comment]
> Thousands of Mysterium users can't use Mysterium app because of this bug.

We don't have "Thousands" of macOS users. 98% of our users are using Windows and Android.

**Comment by cvl** [comment]
I'm using [macos, bug] to make it easier to classify information for anyone at Mysterium, also provides better information on the intention of the issue. I can't change tags when reporting issues unfortunately.

**Comment by chompomonim** [comment]
> I'm using [macos, bug] to make it easier to classify information for anyone at Mysterium, also provides better information on the intention of the issue. I can't change tags when reporting issues unfortunately.

We're using github labels to make it easier to classify information. It is also easier for filter issues later.

![Screenshot from 2021-03-24 12-29-01](https://user-images.githubusercontent.com/153896/112295409-8d662300-8c9c-11eb-9d13-19c9e9e5ed51.png)

**Comment by cvl** [comment]
I know Jaro :)

I'm using the same on my projects.

I cannot use them on this project (no permissions), so I'm doing the best I can.

**Comment by cvl** [comment]
Yes

**Comment by cvl** [comment]
Thank you for your contributions.
