### ISSUE TITLE
Improve unstable connection handling

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3235]
**Describe the bug**
- connect to some node
- turn off Internet connection (e.g. turn off wifi or so) (don't disconnect)
- wait a minute or so
- turn on Internet connection

VPN connection stays active after turning back on the Internet (which is nice), yet after 10-20 of activity, VPN connection is dropped.

**Expected behavior**
If we manage to keep working VPN connection after re-establishing Internet connection, then it shouldn't disconnect after 10-20 seconds afterwards.

**Environment (please complete the following information):**
 - Node version: 0.44.0
 - OS: Tested on MacOS, probably OS independent.

**Comment by soffokl** [comment]
This will be resolved within the scope of the https://github.com/mysteriumnetwork/node/issues/3188
