### ISSUE TITLE
[question] what is the reason to omit fetchMetrics: true from findProposals

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3238]
I can see that instead of single call, we have to make 2 calls (findProposals, then proposalsQuality). Then apps need to merge the two result sets into one.

This further makes proposals fetching slower and complicated. What is the logic behind such decisions?

**Comment by soffokl** [comment]
We are currently reworking it heavily to make it more simple for everyone. It will be changed shortly.
