### ISSUE TITLE
[communication request] Mysterium should communicate to open source community about key changes more openly and explicitly & improve code change handling

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3239]
I've noticed accidentally, that tequilapi.findProposals({ fetchMetrics: true, serviceType: "wireguard" }), no longer returns metrics. Node: 0.44.0

Apparently, this feature was removed in some node release...

Unfortunately, such key changes are not communicated properly (if at all), breaking or downgrading apps relying on it. In this case apps suffered from undefined metrics. This is not the first case with lack of communication regarding key changes / critical bugs.

Suggestion:
- communicate on key changes or known bugs openly and eagerly to open-source community and devs. This could be some newsletter, or at least some change log with very clear description of what will change / break in new version.
- try to have some grace period for back-compatibility if possible
- if not possible, the feature should fail fast and explicitly. In this case, if server receives fetchMetrics: true, then it should not return proposals with partial information, but should not return any proposals + throw clear error with specific error description (e.g. "fetchMetrics param is no longer supported, please use this and that instead")

**Comment by tomasmik** [comment]
We release versions in a manner of minor and major releases. If we bumped a major version, (0.43.X -> 0.44.0) assume that there might be some breaking changes, inspect [releases](https://github.com/mysteriumnetwork/node/releases) and do some form of testing after you bump the node version.

As far as I know we try to keep things backwards compatible, but if you're bumping node versions which are far apart from each other, then there is no guaranty regarding unexpected breaking changes. However I do agree that keeping everyone informed about breaking changes in each version, could be done better and thats something to improve on in moving forward.

This issue specifically seems like it was handled poorly from our side. Sorry for that.

**Comment by cvl** [comment]
Thanks, let's continue communicating.
