### ISSUE TITLE
Ui hangs with the message "your identity is being registered, please be patient"

### ISSUE THREAD

**Issue by damko** [mysteriumnetwork/node#3242]
**Describe the bug**
My rasperry goes offline almost immediately and the Ui hangs with the message "your identity is being registered, please be patient"
![mysterium_ui_hanging](https://user-images.githubusercontent.com/1107588/112245419-21aa9880-8c51-11eb-9730-7b3deb1a7b1f.png)

**To Reproduce**
1. take brand new rasperry 3 B+
2. flash it with node 0.45
3. create brand new eth wallet (I used mycrypto)
4. follow the installation steps
5. at the end of UI configuration, it hangs with "your identity is being registered"
6. device appears online in my.mysterium.network 
7. `systemctl status` shows active
8. reboot -> same
9. unplug/plug eth cable -> same

**Expected behavior**
Node should be online. I can't add much more 'cause this is my 1st ever installation

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 0.45
 - OS: debian 10.8 (mystberry)
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag

**Additional context**

**Comment by damko** [comment]
I've spent a few more minutes on this and I have to add something.

I forgot to mention that I can always access the raspberry via ssh.

I've also noticed that the node goes offline online after I try to access the management console at port 4449. It seems that if I reboot and I don't try to access the UI the node stays online. Currently it's online and I'm going to leave it like that to see what happens.

Also

`myst@raspberrypi:~ $ sudo systemctl status mysterium-node.service
● mysterium-node.service - Server for Mysterium - decentralised VPN Network
   Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-03-24 02:50:51 GMT; 2min 7s ago
     Docs: https://mysterium.network/
 Main PID: 483 (myst)
    Tasks: 20 (limit: 2062)
   CGroup: /system.slice/mysterium-node.service
           ├─483 /usr/bin/myst --config-dir=/etc/mysterium-node --script-dir=/etc/mysterium-node --data-dir=/var/lib/mysterium-node --runtime-dir=/
           └─559 openvpn --port 41054 --server 10.8.0.0 255.255.255.0 --topology subnet --tls-server --dh none --explicit-exit-notify --ca /var/run

Mar 24 02:51:15 raspberrypi myst[483]: 2021-03-24T02:51:15.152 DBG source/config/config.go:196              > Returning default value shaper.enable
Mar 24 02:51:15 raspberrypi myst[483]: 2021-03-24T02:51:15.152 ERR source/session/pingpong/consumer_balance_tracker.go:287 > Could not get consumer
Mar 24 02:51:15 raspberrypi myst[483]: 2021-03-24T02:51:15.153 INF source/services/openvpn/service/manager.go:163 > OpenVPN server waiting
Mar 24 02:51:15 raspberrypi myst[483]: 2021-03-24T02:51:15.299 DBG source/eventbus/event_bus.go:81          > Published topic="balance_change" even
Mar 24 02:51:17 raspberrypi myst[483]: 2021-03-24T02:51:17.513 WRN source/nat/upnp/discover.go:86           > Error parsing discovery response erro
Mar 24 02:51:20 raspberrypi myst[483]: 2021-03-24T02:51:20.515 WRN source/nat/upnp/discover.go:86           > Error parsing discovery response erro
Mar 24 02:51:23 raspberrypi myst[483]: 2021-03-24T02:51:23.517 WRN source/nat/upnp/discover.go:86           > Error parsing discovery response erro
Mar 24 02:51:26 raspberrypi myst[483]: 2021-03-24T02:51:26.519 WRN source/nat/upnp/discover.go:86           > Error parsing discovery response erro
Mar 24 02:51:26 raspberrypi myst[483]: 2021-03-24T02:51:26.520 INF source/nat/upnp/discover.go:58           > UPnP gateways detected: 0
Mar 24 02:51:42 raspberrypi myst[483]: 2021-03-24T02:51:42.915 INF source/pilvytis/order_status_tracker.go:126 > Pausing order status tracking
`

Beside the fact that I obviously don't have upnp enabled on my router (is this required?) this also looks significant _source/session/pingpong/consumer_balance_tracker.go:287 > Could not get consumer_

**Comment by damko** [comment]
I'm not exactly happy to have upnp enabled however for the sake of testing, I turned it on.
This fixes the errors displayed by systemctl status

myst@raspberrypi:~ $ sudo systemctl status mysterium-node.service
● mysterium-node.service - Server for Mysterium - decentralised VPN Network
   Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-03-24 04:36:01 GMT; 11s ago
     Docs: https://mysterium.network/
 Main PID: 489 (myst)
    Tasks: 12 (limit: 2062)
   CGroup: /system.slice/mysterium-node.service
           └─489 /usr/bin/myst --config-dir=/etc/mysterium-node --script-dir=/etc/mysterium-node --data-dir=/var/lib/mysterium-node --runtime-dir=/var/run/mysterium-nod

Mar 24 04:36:14 raspberrypi sudo[598]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/sbin/sysctl -w net.ipv4.ip_forward=1
Mar 24 04:36:14 raspberrypi sudo[598]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 24 04:36:14 raspberrypi sudo[598]: pam_unix(sudo:session): session closed for user root
Mar 24 04:36:14 raspberrypi myst[489]: 2021-03-24T04:36:14.369 INF source/nat/service_ipforward.go:55       > IP forwarding enabled
Mar 24 04:36:14 raspberrypi myst[489]: 2021-03-24T04:36:14.370 DBG source/config/config.go:196              > Returning default value access-policy.address:https://test
Mar 24 04:36:14 raspberrypi myst[489]: 2021-03-24T04:36:14.370 DBG source/config/config.go:196              > Returning default value access-policy.fetch:10m0s
Mar 24 04:36:14 raspberrypi myst[489]: 2021-03-24T04:36:14.371 INF source/firewall/outgoing_firewall_noop.go:57 > Allow URL https://testnet2-quality.mysterium.network/a
Mar 24 04:36:14 raspberrypi myst[489]: 2021-03-24T04:36:14.372 INF source/firewall/incoming_firewall_noop.go:53 > Allow URL https://testnet2-quality.mysterium.network/a
Mar 24 04:36:14 raspberrypi myst[489]: 2021-03-24T04:36:14.373 INF source/firewall/outgoing_firewall_noop.go:48 > Allow IP 239.255.255.250 access
Mar 24 04:36:14 raspberrypi myst[489]: 2021-03-24T04:36:14.384 INF source/feedback/reporter.go:40           > Using feedback API at: https://feedback.mysterium.network

The ports seem to be forwarded correctly however the situation does not change a bit

**Comment by damko** [comment]
Update: I've downloaded v.044 and installed. No problem at all, everything seems to work however during the configuration process my router had upnp on. I don't know if 0.45 would actually work in the same situation. 

I kept the 0.45 version on another SD, in case you need some logs etc. I can't retry with 0.45 without erasing the original SD (I'm short on SD atm) so please let me know.

One weird thing I'm seeing now in the UI is:

Node version 0.45.0
WebUI version 0.1.28

But I'm sure that I've flashed 0.44 on a brand new SD

**Comment by tomasmik** [comment]
>Node version 0.45.0
>WebUI version 0.1.28
>But I'm sure that I've flashed 0.44 on a brand new SD

You can get the node version in terminal using `myst version`

The problem with your node registration hanging was most probably caused by one of the interval services having a slight hiccup. It was resolved yesterday, so thats probably why your second attempt to register and setup was successful.

**Comment by vkuznecovas** [comment]
Can confirm that this was indeed caused by the internal service hiccup. Issue has been resolved, code has been adjusted for a better user experience if it were to happen again. Thanks for the report.

**Comment by vkuznecovas** [comment]
> Beside the fact that I obviously don't have upnp enabled on my router (is this required?) this also looks significant source/session/pingpong/consumer_balance_tracker.go:287 > Could not get consumer

upnp is not strictly required, you can set it up manually as well.

**Comment by soffokl** [comment]
UPnP service is optional, most of the nodes can work fine with a default NAT hole punching. 
This is just one of the technics we are using to connect to nodes. If one of the work for you, you don't need to worry about others.
