### ISSUE TITLE
Could not copy topup address on Android app

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3243]
**Describe the bug**
"When trying to top up account in wallet on Android, I try to pay using Bitcoin or Ethereum and it will not copy the address to send to for a payment. It says copied, but it does not paste into my send wallet."
 
**To Reproduce**
1. Go to 'Wallet'
2. Click on 'Top up'
3. Select the amount of MYSTT;
4. Select currency: BTC or ETH or any;
5. Try to Copy `TOPUP ADDRESS`;
6. Try to paste it in receivers field;

**Environment:**
 - Node version: 0.41.6
 - OS: Android 8.1.0
 - App version: 0.41.3

**Comment by tomasmik** [comment]
I assume this is fixed in: https://github.com/mysteriumnetwork/mysterium-vpn-mobile/pull/225/files
And released in: https://github.com/mysteriumnetwork/mysterium-vpn-mobile/releases/tag/0.42.0
