### ISSUE TITLE
Hermes doesn't allow settling offchain

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3252]
If we add an offchain identity, we can get it, connect using it, but if hermes tries to settle it panics.

```
main.main()
/go/src/github.com/mysteriumnetwork/hermes/cmd/main.go:50 +0x2f5
2021/03/28 13:41:18 nothing to migrate
panic: could not handle settlement for identity 0xBF4789475c8a8fDf50427cC901d1551402316F65 on chain 5: consumer unregistered
```

**Comment by vkuznecovas** [comment]
the problem is the isOffchain flag:

https://testnet2-hermes.mysterium.network/api/v1/data/consumer/0xBF4789475c8a8fDf50427cC901d1551402316F65

Need to take a look at to why it's not set to true.

**Comment by tomasmik** [comment]
I believe this bug was caused by me being reckless.
