### ISSUE TITLE
Doesn't work on raspberry pi 4 raspbian 64bit

### ISSUE THREAD

**Issue by gomme600** [mysteriumnetwork/node#3255]
**Describe the bug**
Error installing.
Message: 

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-5.10.17-v8
E: Couldn't find any package by glob 'linux-headers-5.10.17-v8'
E: Couldn't find any package by regex 'linux-headers-5.10.17-v8'

**To Reproduce**
Run the instal script : sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"

**Expected behavior**
It should install

**Screenshots**

**Environment (please complete the following information):**
 - Node version: latest
 - OS: raspbian buster 64bit

**Additional context**

**Comment by tomasmik** [comment]
You might just need to install/update your kernel headers: `sudo apt-get install raspberrypi-kernel-headers`
[Here is more information about this](https://rohitsw.wordpress.com/2019/04/28/installing-kernel-headers-for-raspbian-and-understanding-the-internals-of-apt-install/)
