### ISSUE TITLE
[question] can provider change the price on the fly once connected?

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3257]
Question originating from discussion at https://github.com/mysteriumnetwork/node/issues/3256

Before I was told that once I connect to proposal with certain prices, provider can't change the price.

- Can provider change proposal prices on the fly?
- If he can, how can I detect the price change and disconnect / ban such provider?

CC: @chompomonim

**Comment by vkuznecovas** [comment]
Out of the box - he can't. However, no one prevents the provider from forking the node and adding the logic to do it on the fly. 

Such changes will get detected(this is what happened on #3256) on the consumer side and the session will get destroyed.

**Comment by cvl** [comment]
Thanks!
