### ISSUE TITLE
Status NotConnected

### ISSUE THREAD

**Issue by Data-Gremlin** [mysteriumnetwork/node#3266]
Running on RP4
Version 0.45.0
As of 2130hrs on 03.04.2021 status is showing as not connected. 

Connection to WAN checked 
Plus Network and all active
Ping to 8.8.8.8 perfect 

Rebooted device plus update and upgrade but service still not connecting automaticly.

Any help or advice would be great.

**Comment by tomasmik** [comment]
I'm sorry, but I'm failing to understand the problem. What do you mean by `...still not connecting automatically`?

Did you have a look in to our guides on running [provider](https://docs.mysterium.network/node-runners/setup/raspberry-pi/)  or [consumer](https://docs.mysterium.network/user-guide/) services?

**Comment by Data-Gremlin** [comment]
My Node will automatically connect to the network but when trying it says under status Not Connected. Ever since I've done the update. On the main webpage it also shows as test fail.

**Comment by tomasmik** [comment]
Would I be correct to understand that you're running node in consumer mode and trying to create a connection? Could you make sure you have any balance left? Any logs provided would also help.

**Comment by Data-Gremlin** [comment]
What ssh command do I need to type to get the logs you need? Still learning.

**Comment by Data-Gremlin** [comment]
I've received and it is now working with an active connection however it still shows on my GUI page as 

Active services

No services found.
