### ISSUE TITLE
Not able to start Mysterium-Node Service

### ISSUE THREAD

**Issue by felix900006** [mysteriumnetwork/node#3267]
**Describe the bug**
The Mysterium-Node Service is not able to start because it cant connect.

**To Reproduce**
1. systemctl start mysterium-node.service

**Expected behavior**
The Mysterium-Node should start.

**Environment (please complete the following information):**
 - Node version: [v8.10.0]
 - OS: [lubuntu 4.4.179 on armhf]

**Error log of the Service**
Error Log : [https://drive.google.com/file/d/1s7uotmgEMHyKndaNGnGd-DAw9Ji2xRXn/view?usp=sharing](url)

**The Error** 
Apr 04 12:32:50 NanoPC-T4 myst[7276]: 2021-04-04T12:32:50.978 ERR cmd/mysterium_node/mysterium_node.go:68  > Failed to execute command:  error="ethereum client failed to connect: dial tcp: lookup goerli.infura.io on 127.0.0.1:53: read udp 127.0.0.1:41908->127.0.0.1:53: i/o timeout"

**Comment by tomasmik** [comment]
Could you check that your internet connection and dns resolution is actually working on the machine? For example try to `ping google.com`

**Comment by felix900006** [comment]
> Could you check that your internet connection and dns resolution is actually working on the machine? For example try to `ping google.com`

That works without a problem. When I did the installation the Mysterium-Node Service was running and working but after I restarted the server it is not working anymore.
