### ISSUE TITLE
No earnings data under sessions in NodeUI

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3268]
**Describe the bug**
 There is over 2GB of transactions; however, no MYST has been generated.
**Provider id: 0x5024be4c722f049da5baf45701ae7cc97a025764**

**Screenshots**
<img width="578" alt="Screenshot 2021-04-05 at 09 40 28" src="https://user-images.githubusercontent.com/60128746/113545564-13fef680-95f3-11eb-97f9-3b5eb5217f5a.png">
<img width="574" alt="Screenshot 2021-04-05 at 09 40 35" src="https://user-images.githubusercontent.com/60128746/113545570-16615080-95f3-11eb-980b-70e38f999fca.png">

**Environment:**
 - Node version: 0.45.0
 - OS: Raspbian GNU/Linux 10 (buster)

**Logs for review: https://my.mysterium.network/admin/issues/download/2357**

**Comment by Data-Gremlin** [comment]
I have the same issue.

**Comment by bysismo** [comment]
I am having the same problem. client, I turned it off.

**Comment by edyshok** [comment]
Having the same issue here 
Node: 0xeeb7f1ade35da77b096c47430452a18d53c9f14d
Node Version: Node version 0.46.2-rc0
WebUI version 0.1.28
OS: Ubunty Mate 20.04.2 LTS
Issue started when earnings reach 20 MYSTT
Then all sessions display 0 MYSTT being earn , amount of MYSTT stack at 20 tokens 

![image](https://user-images.githubusercontent.com/85687242/121533395-3d127d80-c9ce-11eb-95dd-4c4784e9e175.png)
![image](https://user-images.githubusercontent.com/85687242/121534364-26b8f180-c9cf-11eb-9cc9-3c84c7ef7c87.png)
![image](https://user-images.githubusercontent.com/85687242/121534445-3d5f4880-c9cf-11eb-9087-59a832b35b69.png)

**Comment by etherunit** [comment]
@edyshok Can you please try to update your node to 0.47+?
https://docs.mysterium.network/node-runners/setup/updating/#how-to-update-your-linux-node

**Comment by edyshok** [comment]
Done so, updated to 0.47.1 , now appears to be that clients on androids with older VPN  software versions unable to see nodes updated to 0.47.1 version. I don't see my own node from older android device client, I see only 18 nodes, used to be 40

**Comment by nefiwashere** [comment]
getting the same issue on Node version: 0.65.0
![image](https://user-images.githubusercontent.com/10413814/134906352-0cff11f6-b045-4c55-8bb5-a97a4bf36943.png)

**Comment by chompomonim** [comment]
@nefiwashere zero bytes issue is different one. This was about having 0 MYSTT when traffic was provided. Could you create a new issue with more context? Ideally with not only screenshots, but your node ID and logs attached into it.
