### ISSUE TITLE
Changes in the Universe UI to manage the pricing

### ISSUE THREAD

**Issue by eugenegoncharuk** [mysteriumnetwork/node#3286]
Universe UI pushes the data into Oracle.

Pricing example per node type:
Residential US: $0.5 /Gb
DC US: $0.3 / Gb
Residential with whitelisting US $0.5 / Gb
Residential in Ukraine: $0.2 / Gb
DC in Ukraine: $0.1 / Gb
Residential with whitelisting Ukraine: $0.01 / Gb

**Comment by vkuznecovas** [comment]
Done.
