### ISSUE TITLE
sudo permissions problem in the container

### ISSUE THREAD

**Issue by cynnfx** [mysteriumnetwork/node#3295]
Hello, it seem it has problem there with permision: 
(wonderful project by the way)

mysteriumnetwork-node    | 2021-04-13T11:06:58.837 WRN logconfig/openvpnlog.go:45               > Failed to add tun device: [sudo ip tuntap add dev tun0 mode tun] Returned exit error: exit status 1 Cmd output: ioctl(TUNSETIFF): Operation not permitted
mysteriumnetwork-node    | 2021-04-13T11:06:58.837 ERR core/service/manager.go:165              > Service serve failed error="failed to start Openvpn server: failed to create a tunnel: /sys/class/net/tun0: exit status 1"
mysteriumnetwork-node    | 2021-04-13T11:06:58.837 INF logconfig/openvpnlog.go:54               > [openvpn-mgmt] Shutdown
mysteriumnetwork-node    | 2021-04-13T11:06:58.837 INF logconfig/openvpnlog.go:54               > [openvpn-mgmt] Shutdown finished
mysteriumnetwork-node    | 2021-04-13T11:06:58.838 INF core/discovery/discovery.go:145          > Stopping discovery loop...
mysteriumnetwork-node    | 2021-04-13T11:06:58.846 WRN logconfig/openvpnlog.go:45               > Failed to flush tun device: [sudo ip addr flush dev ] Returned exit error: exit status 1 Cmd output: Device "" does not exist.
mysteriumnetwork-node    | 
mysteriumnetwork-node    | 2021-04-13T11:06:58.853 WRN logconfig/openvpnlog.go:45               > Failed to remove tun device: [sudo ip tuntap delete dev  mode tun] Returned exit error: exit status 255 Cmd output: Error: argument "" is wrong: "dev" not a valid ifname

**Comment by soffokl** [comment]
@cynnfx hey, could you share the command that was used to start the container?
