### ISSUE TITLE
[bug, windows] new user can't connect to any node (insufficient balance)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3297]
**Describe the bug**
New user from China, new identity.
Can't connect to any nodes, gets errors:
- could not get consumers channel: no contract code at given address
- Failed to connect error="insufficient balance"

Logs:
[mysterium-node 32.log](https://github.com/mysteriumnetwork/node/files/6309923/mysterium-node.32.log)

**Environment (please complete the following information):**
 - Node version: 0.44.0
 - OS: Windows

**Comment by vkuznecovas** [comment]
The user registered today successfully, previous failure was caused by our infra having a bit of downtime. Everything should be in order now, need to restart node.

**Comment by cvl** [comment]
Thanks!
