### ISSUE TITLE
Provider already has settlement in progress

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3300]
**Describe the bug**
 Provider want to change beneficiary (by entering his wallet address and clicking on the Save button), however, the saving is not done (still running as you can see on the screenshot). Tried to modify the wallet from the CLI, which resulted in a timeout error.
Provider id= 0x3af2fafe49a470425629ffab72d90bb83734f994

**Screenshots**
<img width="379" alt="Screenshot 2021-04-15 at 13 36 31" src="https://user-images.githubusercontent.com/60128746/114856375-b25b3b00-9def-11eb-9c2a-224c72a0741e.png">
<img width="360" alt="Screenshot 2021-04-15 at 13 37 25" src="https://user-images.githubusercontent.com/60128746/114856514-dfa7e900-9def-11eb-8e69-2d905e9cd9c0.png">

**Environment (please complete the following information):**
 - Node version: 0.45.0
 - OS: Ubuntu 20.04.2 LTS

**Comment by Papabibo** [comment]
I am the provider in question,
I am trying to modify the payout wallet without success, I am trying first via Node UI, then with the cli:
myst cli, both failed as you can see:
» identities beneficiary 0x3af2fafe49a470425629ffab72d90bb83734f994 <my wallet>
[INFO] Waiting for new beneficiary to be set
.....................................................[WARNING] Setting new beneficiary timed out
»
`

**Comment by tomasmik** [comment]
This should be improved. Refer to: https://github.com/mysteriumnetwork/node/issues/3344#issuecomment-832509098
