### ISSUE TITLE
[Andzej catch up meeting] Support issues

### ISSUE THREAD

**Issue by eugenegoncharuk** [mysteriumnetwork/node#3303]
---
Problem with stolen tokens

Provider used testnet 1

Migration happened testnet 1 -> testnet 2 on 30-01-21 - 01-02-21

Raspberries can do auto upgrade manually

Others should do the upgrade by themself
!!! How to see old testnet1 provider sessions to be 100 % sure we have this information logged?

--- 
Problem with sessions. Why in Ukraine it is so bad (20-80%). Algiria (1-15%).
Need to separate the errors to see where the problems appear much often?

---
[Planned] Starting daemon is stuck on the screen. Fix: delete app or data log

---
[Planned] Installation is to complex (Mac OS and Windows users)

--- 
Why openvpn is still in use (SERVICE_OPTS : openvpn,wireguard)

[Planned] p2p ports needed? Can there be one port range for all services on Node UI without tech terminology (my-mysterium-network)

---
Germany problem
Jurisdiction to switch to whitelisted notes (only Mysterium verified partner traffic)

---
[contacted Ignas] MMN issues 
Who can solve the problems with MMN (Ignas left the company)
We need someone to look into that

NAT status problem
Confuses people if the server is not under the NAT. Why we need this?
!!! Grooming needs to happen.

Look into Github issues

--- 
25% of all the conversation
The monitoring agent checks it 6 times a day
If 1 failed when in MMN is shown "Test Failed".
Need 24 hours to turn it online again.

The problem that it confuses and causes providers to react to find answers.
How fast it becomes available when once failed? Available in discovery list.

!!! Grooming needs to happen.

---
Registration failed problem

Spinning all day (glitches in transactor or ?) - Viktoras or Tomas can help with that?

---

**Comment by chompomonim** [comment]
Closing this issue. Most of mentioned things should be fixed by now. If something left, please create separate tasks per each issue
