### ISSUE TITLE
Detecting Debian dystro on install.sh

### ISSUE THREAD

**Issue by Paktas** [mysteriumnetwork/node#3304]
Install.sh script is NOT detecting Debian 10 dystro - thinking it's dealing with Rasberry.

https://github.com/mysteriumnetwork/node/blob/c2f2760d8c09569301649efada939587b9f11c50/install.sh#L51

The dystro is:
```
uname -a
Linux mysterium-node 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
```

While the script returns raspbian:
```
sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"
### Detecting platform
System info:
OS: linux
Distribution: raspbian
Version codename: buster
### Detecting platform - done
```

**Comment by soffokl** [comment]
@Paktas hey, the issue was resolved. You can try to install it now.
