### ISSUE TITLE
Debug if DNS is properly set on mobile

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3326]
In our new app users are able to set DNS (provider, system, cloudflare). Mobile developer implemented calls into backend, but there is question how to properly test that and if that works at all.

**Comment by soffokl** [comment]
I did a test for a new app. It seems it always uses a Cloudflare DNS no matter what option is set. 
However, our old android application is using provider DNS with no issue. 

This can be tested again by using https://dnsleaktest.com/ service. 
1) Open https://dnsleaktest.com/ and do a test without a VPN connection. You will see a list of your system DNS.
2) Connect to the VPN and do the same test again to see what DNS is used now.

**Comment by chompomonim** [comment]
@soffokl could it be problem in mobile package which is exposing bindings for mobile?

**Comment by soffokl** [comment]
@chompomonim yes, it could, I'm checking it.
