### ISSUE TITLE
"Oops could not connect..try again later"

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3329]
**Describe the bug**
Здравствуйте, вот что происходит.
https://www.youtube.com/watch?v=h2GD87pPOY8

**Environment:**
 - App version: 3.8.2
 - OS: Windows 7 ''Ultimate'' + Service Pack 1 (64-bit)

**Additional context**
[main.txt](https://github.com/mysteriumnetwork/node/files/6348103/main.txt)
[myst_supervisor.txt](https://github.com/mysteriumnetwork/node/files/6348104/myst_supervisor.txt)
[renderer.txt](https://github.com/mysteriumnetwork/node/files/6348105/renderer.txt)

**Comment by soffokl** [comment]
Unfortunately, we are supporting Windows 10 only. So this issue could be related to the incompatible version. 
The problems happened on the video could be also related to the network configuration. I can recommend to try version 0.47.0-rc2 or higher, we added improvements that can help with some network setups.
