### ISSUE TITLE
Mint MYST through Wallet

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#333]
As a developer
In order to make MYST minting on Devnet and Testnet easier and faster
I want to have MYST minting in mysterium's Wallet website

Acceptance criteria:
- show minting functionality in wallet.mysterium.network when it detects the main contract account(eth address) in Metamask was unlocked

**Comment by soffokl** [comment]
Should it go to the https://github.com/mysteriumnetwork/wallet?

**Comment by Waldz** [comment]
> Should it go to the https://github.com/mysteriumnetwork/wallet?

Yes it's in this `wallet` repo.

**Comment by Waldz** [comment]
We are looking for way to simplify way how User gets free tokens for Wallet operations: Allowance Register, Topup Wiwdraw, ClearPromise.

Currently user has to leave online Wallet and go to 2 different Fauceting chats.
We are longoking for ways to stay on Wallet and do buttons clicks there.

Now geting free tokens is complex:
- users goes to online Wallet

- if Localnet: ETH is Minted in Wallet
- if Testnet:   ETH is Fauceted by bot chats (Twiter, Metamask)

- if Localnet: MYST is Minted in Wallet
- if Testnet:   MYST is Minted in Wallet

**Comment by Waldz** [comment]
@zolia @interro @shroomist please correct if I am wrong somethere.

**Comment by shroomist** [comment]
it's definitely possible to mint tokens on testnet via our walletx interface, without using the telegram bot, thus simplifying the flow.

**Comment by Waldz** [comment]
I wrote what its not possible to mint ETH, just Faucet them

**Comment by shroomist** [comment]
yea, you should mine the testnet eth

**Comment by Waldz** [comment]
Actually it's possible to Mint ETH also:
1. we create our personal address
2. we put a lot of ETH there
3. we can Mint from that wallet automatically because we are owners there

**Comment by shroomist** [comment]
Let’s get the terms straight — that’s not minting, that’s an airdrop.
Term minting implies that no work is done

**Comment by interro** [comment]
This task is about to create function for contract owner to mint tokens on testnet/locanet. 
@Waldz @shroomist you are discussing about different task, about minting tokens for user.

**Comment by Waldz** [comment]
Yes minting for owner is good. But just a small improovement. 

Lets:
- [ ] Create other tickets then closing this task
- [ ] describe airdroping ticket because it would work in all environments
