### ISSUE TITLE
Implement kill switch

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3341]
Implement kill-switch as following:
The VPN Kill Switch continuously monitors your connection to the VPN server. If the connection accidentally drops, the Kill Switch blocks your device (or the apps you have specified) from accessing the web.

More:
- https://www.hotspotshield.com/what-is-a-vpn/kill-switch/
- https://nordvpn.com/features/kill-switch-technique/
- https://whatismyipaddress.com/internet-kill-switch

**Comment by soffokl** [comment]
I thought we already have this working the same way, no?

**Comment by cvl** [comment]
Hi @soffokl 
I don't know. How can we try?

**Comment by tomasmik** [comment]
I think this was already being talked about in here: https://github.com/mysteriumnetwork/node/issues/3168

**Comment by cvl** [comment]
Not sure if it's the same. It sounds more like a reconnect as far as I understand.

I'd suggest to implement kill-switch in the following fashion:
- Main requirement: If the connection accidentally drops, the Kill Switch blocks your device from accessing the web. So there's no way user traffic would leak, or his identity would be exposed. This should work as a standard VPN kill-switch feature, without inventing any new interpretations.
- Done criteria: Make sure it's possible to use in real-life apps (desktop and mobile), and has a description on how to use it. I.e. it must work in apps, otherwise it's kinda useless. Best way imho: simply have a flag "killSwitch" (on/off) when requesting node to connect.

In desktop app it would be:

await tequilapi.connectionCreate(
                    {
...
                        connectOptions: {
                            **enableKillSwitch: true/false,**
....
                        },
                    }
                )

In mobile app it would be:

val req = ConnectRequest()
..
**req.enableKillSwitch = true/false**
deferredNode.await().connect(req)



Also note, that there's already such or similar flag called disableKillSwitch. So someone has already already beem working on this in the past I guess.

**Comment by cvl** [comment]
This is a very important and long awaited feature which can determine life/death in certain jurisdictions.
Imagine user in Iran, China, Russia or whatever using VPN, and suddenly getting exposed when connection drops. This could have serious consequences to him and his family.

**Comment by soffokl** [comment]
@cvl this is enabled by default in the 0.47.0-rc2 node for mobile. Could you try and provide some feedback?

**Comment by cvl** [comment]
Will do today.

Is there a way to disable/enable it? Not all users want that (I guess).

**Comment by cvl** [comment]
Doesn't run now:

com.beust.klaxon.KlaxonException: Unable to instantiate ProposalItem:No argument provided for a required parameter: parameter #0 providerID of fun <init>(kotlin.String, kotlin.String, kotlin.String, kotlin.Int, kotlin.String, kotlin.Boolean, network.portals.service.core.ProposalPaymentMethod): network.portals.service.core.ProposalItem
    No argument provided for a required parameter: parameter #0 providerID of fun <init>(kotlin.String, kotlin.String, kotlin.String, kotlin.Int, kotlin.String, kotlin.Boolean, network.portals.service.core.ProposalPaymentMethod): network.portals.service.core.ProposalItem
    No argument provided for a required parameter: parameter #0 providerID of fun <init>(kotlin.String, kotlin.String, kotlin.String, kotlin.Int, kotlin.String, kotlin.Boolean, network.portals.service.core.ProposalPaymentMethod): network.portals.service.core.ProposalItem
    No argument provided for a required parameter: parameter #0 providerID of fun <init>(kotlin.String, kotlin.String, kotlin.String, kotlin.Int, kotlin.String, kotlin.Boolean, network.portals.service.core.ProposalPaymentMethod): network.portals.service.core.ProposalItem
    No argument provided for a required parameter: parameter #0 providerID of fun <init>(kotlin.String, kotlin.String, kotlin.String, kotlin.Int, kotlin.String, kotlin.Boolean, network.portals.service.core.ProposalPaymentMethod): network.portals.service.core.ProposalItem
    No argument provided for a required parameter: parameter #0 providerID of fun <init>(kotlin.String, kotlin.String, kotlin.String, kotlin.Int, kotlin.String, kotlin.Boolean, network.portals.service.core.ProposalPaymentMethod): network.portals.service.core.ProposalItem
    No argument provided for a required parameter: parameter #0 providerID of fun <init>(kotlin.String, kotlin.String, kotlin.String, kotlin.Int, kotlin.String, kotlin.Boolean, network.portals.service.core.ProposalPaymentMethod): network.portals.service.core.ProposalItem
    
        at com.beust.klaxon.JsonObjectConverter.initIntoUserClass(JsonObjectConverter.kt:115)


How does the new ProposalItem object look like?

Any other changes to be aware of?

**Comment by cvl** [comment]
@soffokl need your hints on this.

**Comment by soffokl** [comment]
@cvl there is a number of changes in the 0.47.0 version including killswitch. The discovery part was changed too. 
Unfortunately, I cannot say what needs to be changed on the mobile part to make it work for you.

**Comment by cvl** [comment]
Upgraded to 0.47.1, yet there's no kill-switch.

Any plans for kill-switch in near future?

**Comment by cvl** [comment]
@chompomonim closed https://github.com/mysteriumnetwork/node/issues/3169 stating that kill-switch is implemented...

Copying few months old questions, none of which were even attempted to be answered. Why would anyone spend hours implementing a critical feature then not giving 5 minutes of communication time to tell how it can be used is behind my comprehension.

Thread: https://github.com/mysteriumnetwork/node/issues/3168

- There's no such config as "stated" config.Current.SetDefault(config.FlagKeepConnectedOnFail.Name, true).
-  can see that Android lib and mysterium-vpn-js has setDisableKillSwitch amongst connect options.
Is this something I should use?
- How should I implement this in desktop app?
- Is this a real kill-switch (i.e. can I market is a kill-switch) - as it sounds like it's a reconnect feature. In other words: if connection is dropped for any reason (node, wifi signal lost/reconnected whatever), would the traffic leak, or will the internet be disabled until user manually clicks Disconnect, or node reconnects to provider successfully?
- is it possible to get a notification (e.g. status change or smth like that) once the connection is dropped, so I can notify user that something bad happened and he should Disconnect and Connect again.

**Comment by cvl** [comment]
Here's some info gathered so far:

- For mobile kill-switch is enabled by default. There's no (easy) way to disable it for now.
- setDisableKillSwitch flag is old and obsolete, shouldn't be used.
- In desktop, use flag "--keep-connected-on-fail=true", when starting myst process. Yet when using this flag, node doesn't start. I'll create another issue for this.
- Is it real kill-switch: not clear yet, most likely.
- Get notification on connection drop: unknown

**Comment by cvl** [comment]
After testing on desktop, it's still not working. Here are the two issues that need to be resolved:
https://github.com/mysteriumnetwork/node/issues/3475
https://github.com/mysteriumnetwork/node/issues/3483

**Comment by chompomonim** [comment]
Kill switch is implemented but is not clear how to use it and may have some issues on desktop.

I'm closing this issue in favor for #3506
