### ISSUE TITLE
Cannot change beneficiary

### ISSUE THREAD

**Issue by arnoheekhout** [mysteriumnetwork/node#3344]
**Describe the bug**
Settings beneficiary times out but still takes Mystt.

**To Reproduce**
I installed the node but accidentally used an ethereum adress instead of mystt.

**Expected behavior**
I expect my beneficiary adress to change.

**Screenshots**
![image](https://user-images.githubusercontent.com/83210630/116054273-cae31500-a67b-11eb-9ebe-6d9fe2ad0661.png)

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: Raspian

**Additional context**

**Comment by GregSia** [comment]
yes i also have the same issue.

My Node ID: 0x81331cabe6196bbc5e63cef1fd833bc83ebced7b

would be glad if the engineer can look into the matter....thks

**Comment by tomasmik** [comment]
Hi, if MYST was actually taken from you account the address should get changed even though you've received this error. We'll still take a look in to this though.

**Comment by 4KJuegos** [comment]
I am on the same situation, I can't change my address succesfully...

**Comment by 4KJuegos** [comment]
There is a bug on myst node, it says I haven't enough earnings but I have x5 earnings up to fees. And the price of fees goes up with every try.

**Comment by tomasmik** [comment]
I've made some changes to how the beneficiary gets changed using the CLI #3350 

- It should no longer display the timeout error 
- You can now check your last change request and current beneficiary using `beneficiary-status <identity>`
- The whole process should now be a it more stable

This change will be included in the next RC release `0.46.2-rc2` or stable release `0.46.2`
If there are any more issues, feel free to open a new ticket.

**Comment by vegtelenmt2** [comment]
Hello! My problem: 
https://prnt.sc/12r4avz

I would like to change the payment address. Because unfortunately my address is not in it in the node, so you get paid for something else from my node. ... Please help!

My: node version:  0.46.2-rc0
OS:  Ubuntu 20.04.2 LTS

**Comment by tomasmik** [comment]
0.46.2-rc2 was just released, please wait for it to be built and released on the platform you need, then upgrade and refer to my comment above.

See release and notes here: https://github.com/mysteriumnetwork/node/releases/tag/0.46.2-rc2
