### ISSUE TITLE
[desktop] Allow passing default options when starting node

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3353]
Similarly to mobile bindings newNode(defaultOptions()), allow to pass default when starting node in desktop apps.
This is needed e.g. to set correct feedback url.

**Comment by cvl** [comment]
This issue is around unresolved since December.

**Comment by vkuznecovas** [comment]
The way node is currently implemented means that **most** of the config flags can not be re-set on the fly. Node restart will be required in all cases. 

Refactoring this mechanism is a big task and will be of low priority, so I wouldn't hold my breath.

**Comment by vkuznecovas** [comment]
You can change them prior to launching node by changing it in the `newNode(defaultOptions())` construct(however you're using that via mobile bindings). That way there's no need to update it at runtime.

**Comment by cvl** [comment]
Would it be possible to pass default options in desktop apps as well?
I assume this is relatively easy to implement (compared to runtime config update, which would be unnecessary at least in this case).

**Comment by vkuznecovas** [comment]
Yes, it most likely is but @mdomasevicius or @tadaskay are more qualified to answer that.

**Comment by cvl** [comment]
Updated title and description to reflect this.

**Comment by mdomasevicius** [comment]
You can actually pass flags. Take a look [here](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/blob/502f744ffa170542b0442855bdfa4265691ff9a8/src/supervisor/supervisor.ts#L196)

The one you would need to pass in feedback URL is:
```
   --feedback.url value                                   URL of Feedback API (default: "https://feedback.mysterium.network")
```

On another note, the issue submission should be fixed as of yesterday.

**Comment by cvl** [comment]
Perfect, thank you!
