### ISSUE TITLE
[bug, linux app] app cannot be installed again after uninstall

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3360]
**Describe the bug**
- Install Mysterium app on Ubuntu

1st scenario:
- Don't quit app, and try to remove it via installer.
- Installer will show that app is removed, but in fact it's not, and tray icon is there, you can still open Mysterium app window via "Show Window".

2nd scenario:
- Quit app, and try to remove it via installer.
- Installer will show that app is removed, but myst_supervisor keeps running.
- Try to install app again -> the app cannot get installed again: installer shows, that it installed, but there's no app to be found amongst apps.

**Environment (please complete the following information):**
 - OS: Ubuntu LTS
 - Desktop app version (if applicable): 3.9.0

**Comment by Zensey** [comment]
@cvl 
How do you uninstall in the 2nd scenario ?
Via apt remove ?

**Comment by cvl** [comment]
This issue was for client app, i.e. not node runner app.

**Comment by cvl** [comment]
I was using built-in Ubuntu package manager (GUI) - called Ubuntu Software I guess. Just double click the .deb package.

**Comment by Zensey** [comment]
> * installer shows, that it installed, but there's no app

Is it shown in Ubuntu Software as well ?

**Comment by Zensey** [comment]
@cvl 
Which Ubuntu version it was ? Was it 20.4 ?

**Comment by cvl** [comment]
yes, 20.04.2.0 LTS

**Comment by Zensey** [comment]
Seems to be an electron-build related problem.

**Comment by cvl** [comment]
x

**Comment by cvl** [comment]
x
