### ISSUE TITLE
Node version doesn't update on MMN

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3373]
**Describe the bug**
ID: 0xa20504db0b6790715509a04aa70a2e0459c0e6e6
Pulled latest docker image (updated). 
```
docker exec -it myst /bin/bash
bash-5.0# myst version
```
```
Mysterium Node
  Version: 0.46.1
  Build info: Branch: 0.46.1. Build id: 290620211. Commit: 39954d3a
```
my.mysterium.network shows 0.42.6. Getting this message:

<img width="787" alt="Screenshot 2021-05-10 at 15 26 52" src="https://user-images.githubusercontent.com/60128746/117659080-2ba63d80-b1a4-11eb-8280-ac6ebb6c3c07.png">

**Expected behavior**
Version is updated on MMN.

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: Alpine Linux v3.12

**Comment by benv666** [comment]
Seeing the same thing here while running the latest docker image (mysteriumnetwork/myst:latest):
![image](https://user-images.githubusercontent.com/165034/118471057-9eb13600-b707-11eb-9c2a-0f72b1d096a7.png)

```
$ docker exec -it myst myst version
Mysterium Node
  Version: 0.46.1
  Build info: Branch: 0.46.1. Build id: 290620211. Commit: 39954d3a

```
Container has been deleted and recreated, no effect.

**Comment by adpandhare** [comment]
Upgraded to version 0.46.1 still showing version 0.44.0

Node number 0x5510c92dc0fb9d5bf88149a55c568e1be24d7309

![MMN](https://user-images.githubusercontent.com/84430621/118753055-2abf7c80-b832-11eb-90cf-d96a8784d979.PNG)

**Comment by NebNitram** [comment]
I have upgraded also.. with exactly the same issue
Node: 0x8ebeb4e76767d7dbfdd39a8115ec32d3dfb06fb6
![Screen Shot 2021-05-20 at 21 53 42](https://user-images.githubusercontent.com/84519158/119001433-2a4fee80-b9b6-11eb-8bf9-5df227da6542.png)

**Comment by soffokl** [comment]
@benv666 @adpandhare @NebNitram @etherunit 
Could you please try to go to the `nodeUI settings` and set `MMN integration API Key` once again? 
Looks like it solved the problem for me.
![image](https://user-images.githubusercontent.com/8612618/119074467-e9d18e80-ba10-11eb-86f3-6c3401dcd4c1.png)

**Comment by adpandhare** [comment]
Thanks @soffokl, It worked for me too!

**Comment by chompomonim** [comment]
Closing issue as it is most probably fixed. Please open new one if it will repeat.
