### ISSUE TITLE
Topup my Myst

### ISSUE THREAD

**Issue by MDgit897** [mysteriumnetwork/node#3386]
Hello, i think Myst topup should not have a time limit, as Myst is Myst 1 on 1, no price difference, it make sit easier to send from exchanges to topup, because when the fund is send is up to the exchange, and the time might have run out.

Why have a time limit for topping up with Myst ?

Also, would be best if the wallet has a fixed address to be able to send Myst to, or does it already have ?

And 3rd, it would be more user friendly to be able to send also using the build in wallet of the andriod app wallet.

4th. A wallet backup, because if one adds Myst to wallet, how to restore it if phone breaks, or is lost ? Also to make it be able to use across platforms, mac/windows etc... same wallet from 1 wallet the funds across platforms.

thnx.

**Comment by tomasmik** [comment]
> Why have a time limit for topping up with Myst ?

This is how the external payment provider is configured. Maybe we can adjust something, but thats a bit out of our control. All topup requests have an expiration time. In theory if you hold MYST on the same chain that consumer is running on, you could just send it from your wallet to the channel address.

> Also, would be best if the wallet has a fixed address to be able to send Myst to, or does it already have ?

It already does. You send MYST to your channel address. Though as mentioned before, you have to make sure you're sending from the correct chain. For example right now Consumers are running on ethereum goerli.

> And 3rd, it would be more user friendly to be able to send also using the build in wallet of the andriod app wallet.

Could you elaborate on this?

>4th. A wallet backup, because if one adds Myst to wallet, how to restore it if phone breaks, or is lost ? Also to make it be able to use across platforms, mac/windows etc... same wallet from 1 wallet the funds across platforms.

We're working on this 🚀 You will be able to backup and import your wallet in the new android app which we'll release soon. Node already supports it and you can already do it using the CLI ( https://github.com/mysteriumnetwork/node/pull/3215 ) . Desktop apps will also have this feature in the future ( https://github.com/mysteriumnetwork/node/issues/3228 ).

**Comment by MDgit897** [comment]
Hello, thnx for answers, I appreciate, I will check the chain, I did not know Myst is run on different chains,

about the 3rd, what i meant was, to be able to use the wallet in the android app not just to hold, but also to be able to send to other wallets ? (like other android myst vpn apps with wallets)

**Comment by tomasmik** [comment]
> about the 3rd, what i meant was, to be able to use the wallet in the android app not just to hold, but also to be able to send to other wallets ? (like other android myst vpn apps with wallets)

You can already send and receive MYST to wallets like Metamask. As far as I know the MYST in your dVPN app account balance is only meant to be used as a way to pay for service. To store, trade and transact MYST, you can a crypto wallet of your choice.

**Comment by tomasmik** [comment]
Im closing the issue, if you have any more questions, feel free to open another issue or get in touch with and community on discord: https://discord.gg/VcCFHXCRB7
