### ISSUE TITLE
Wallet address is missing + node UI does not work after migration Ubuntu to Raspberry

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#3391]
Hi all,
I have migrated my node from Ubuntu to Raspberry.
What I basically did was to copy the directory /var/lib/mysterium-node (with all subdirectories and files) from Ubuntu to Raspberry.

By checking the status on my.mysterium.network I see the node is online, but there's an orange exclamation mark just by the Residential/Global bounty section. When I click on there, I read: "Ineligibility reason - Your node does not have a wallet address.".

When I try and open the node UI, I see only the rotating circle, but nothing more happens.
Can somebody help?

![immagine](https://user-images.githubusercontent.com/34000198/118332331-35b09f00-b50a-11eb-8780-92f494be619a.png)
![immagine](https://user-images.githubusercontent.com/34000198/118332360-4103ca80-b50a-11eb-80f5-7848dba20338.png)
![immagine](https://user-images.githubusercontent.com/34000198/118332384-49f49c00-b50a-11eb-9c87-c668834afe32.png)

**Comment by tomasmik** [comment]
Hi, such issues can be resolved with the help of the community and our support faster over in our discord server: https://discord.gg/UM9RuCmMTd

Some troubleshooting steps you can try are:
* [Check if your node is healthy](https://docs.mysterium.network/node-runners/setup/linux/#service-health)
* Try to access the node ui using incognito or delete your cookies and cache.
* Check if your node identity matches the old one
* Check if node can access the data dir, files should belong to `mysterium-node`
Example:
```
-rw-r--r--  1 mysterium-node mysterium-node  220 Feb 25  2020 .bash_logout
-rw-r--r--  1 mysterium-node mysterium-node 3771 Feb 25  2020 .bashrc
drwx------  2 mysterium-node mysterium-node 4096 May 14 08:15 keystore
drwx------  3 mysterium-node mysterium-node 4096 May 14 08:15 .mysterium
-rw-------  1 mysterium-node mysterium-node   60 May 14 08:17 nodeui-pass
-rw-r--r--  1 mysterium-node mysterium-node  807 Feb 25  2020 .profile
drwx------  3 mysterium-node mysterium-node 4096 May 14 08:15 testnet2
```
If that is not the case execute:  `sudo chown -R mysterium-node:mysterium-node YOUR_DATA_DIR_FOLDER_HERE `
