### ISSUE TITLE
Can't connect to nodes under firewall

### ISSUE THREAD

**Issue by ElDavoo** [mysteriumnetwork/node#3392]
Hi,
I'm not sure where I should open this issue, but here we go. Under a particular firewall I can't connect to any node. Only discovery works.
I suspect that this happens because the firewall blocks outgoing connection to many ports, for example 51820. I believe this is called "port whitelist".
A VPN should be able to get around as many firewalls as it can right? :)
(FYI, many commercial VPNs do not work either)
A proposed solution would be to use "common whitelisted ports" for P2P channels, like 443.

**To Reproduce**
1. Configure a firewall with port whitelist
2. Try to connect.

Log when I try connecting to my node.
```
Received consumer public key
Found cached public IP
Supplying port 51990
Supplying port 52021
Couldn't detect router IP address error="no UPnP or NAT-PMP router discovered"
Port mapping is useless, skipping it. error="failed to find router public IP"
Published topic="Traversal" event={ID:0x390dc9be878eac3adf7588ef63d49022f3e93010 Stage:port_mapping Successful:false Error:failed to find router public IP}
Got NAT event event={"error":{},"id":"0x390dc9be878eac3adf7588ef63d49022f3e93010","stage":"port_mapping","successful":false}
Found cached public IP
Sending reply with public key and encrypted config to consumer
Decrypted consumer config: publicIP:""  ports:46696  ports:43928
Skipping consumer ping
Delaying pings from consumer for 5 ms
Creating p2p channel with local addr: 192.168.1.4:51990, UDP session addr: 127.0.0.1:60575, proxy addr: 127.0.0.1:59112, remote peer addr: x.x.x.x:46696
Will use service conn with local port: 52021, remote port: 43928
Sending handlers ready message
No initial traffic for 10 sec. Terminating channel.
```

**Comment by soffokl** [comment]
Unfortunately, the current implementation works using UDP ports, we cannot use TCP ports like 443. 
We are planning to add some more transport protocols including TCP-based, but it will take some time. 

We cannot fully pass all firewalls if it blocks UDP traffic. But we are constantly trying to add more and more ways to bypass it. 
With the latest 0.47.0-rc2 version we added another approach for it. You can try to use this version to see if it will work for you.

**Comment by ElDavoo** [comment]
what about using udp 443, it will get more used in the future because of http3?

**Comment by soffokl** [comment]
Unfortunately, it's not enough to use only one port. We are using multiple ports to establish sessions in various restricted environments. And using a single port makes it easy to block by any organization.

**Comment by ElDavoo** [comment]
>  not enough 

Will it work if I set a single port in my daemon's config? Will other people be able to connect to me?

**Comment by ElDavoo** [comment]
0.47 doesn't work btw

**Comment by ElDavoo** [comment]
My dashboard now says:
Your NAT Type: Port Restricted Cone.
Most of network users can connect to your node. Only users with Symmetric NAT cannot.
However, the docs do not explain how to make users with Symmetric NAT connect to me.

**Comment by creotiv** [comment]
@ElDavoo For now there is no possibility to change this. Maybe in the future we will find a way to fix this problem
