### ISSUE TITLE
Users are getting disconnected constantly

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3398]
**Describe the bug**
Multiple users report they get disconnected / or stops working constantly. Started happening few days ago.

Perhaps a hint of possible error: "Failed to send exchange message error="peer error: could not unmarshal exchange message proto: proto: cannot parse invalid wire-format data""

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6493542/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: Windows 10

**Comment by vkuznecovas** [comment]
Have these reports occured on Friday evening-night?

**Comment by cvl** [comment]
The first report was on 05-09.

**Comment by cvl** [comment]
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6493746/mysterium-node.log)

Logs from another user.

**Comment by cvl** [comment]
One more report with logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6510358/mysterium-node.log)

**Comment by LorenzKa** [comment]
I also constantly have this problem, cant stay connected for more than 5 Minutes.

**Comment by cvl** [comment]
Constantly happening

**Comment by airyariv** [comment]
still happening
