### ISSUE TITLE
Test 0.47 rc release candidate

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3403]

**Comment by Peter-SovietSquirrel** [comment]
Upgraded working node to 0.47.0-RC3, upon reboot MMN reports Offline with no active services.

- OS: Raspbian Buster
- Node version 0.47.0-RC3

[newlog.txt](https://github.com/mysteriumnetwork/node/files/6522124/newlog.txt)

**Comment by ElDavoo** [comment]
same

**Comment by hyvamiesh** [comment]
also updated node to 0.47.0-RC3.
MMn offline and no active services.
Prices were also reset to 0

**Comment by ElDavoo** [comment]
now it gives me test failed

**Comment by chompomonim** [comment]
Just installed 0.47.0-rc5, here are two bugs founds:

- [ ] service price is set to 0
![Screenshot from 2021-05-28 06-34-59](https://user-images.githubusercontent.com/153896/119926110-691a1180-bf7f-11eb-913c-e935e712e017.png)

- [ ] the node is not visible in mobile app anymore :/

**Comment by mdomasevicius** [comment]
@chompomonim I am not able to reproduce this, I would need your `.mysterium` config toml files with this issue, it might be super old prices in the settings, anyway the workaround is to edit prices via "settings" so not sure if this is critical.

**Comment by Twizzer** [comment]
> @chompomonim I am not able to reproduce this, I would need your `.mysterium` config toml files with this issue, it might be super old prices in the settings, anyway the workaround is to edit prices via "settings" so not sure if this is critical.

You can't change it in settings, even on new fresh installs

**Comment by ElDavoo** [comment]
now the node is online, but nobody connects to it. 0.47.0-rc5 . I can't see it in the desktop app.

**Comment by Twizzer** [comment]
> now the node is online, but nobody connects to it. 0.47.0-rc5 . I can't see it in the desktop app.

This is a known issue with 0.47.0-RC5 I had this issue and I wiped and started over.

back on 0.42.6-RC2 and everything is working perfectly.

**Comment by chompomonim** [comment]
@ElDavoo today we have released [4.1.1](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/4.1.1) version of desktop app, could you check if this version can see your 0.47.0-rc5 node?

**Comment by ElDavoo** [comment]
yay!

**Comment by chompomonim** [comment]
0.47 is released. Thank you everyone for testing.
