### ISSUE TITLE
Tokens earned stuck at 141

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3405]
https://testnet2-grafana.mysterium.network/d/n3xeQlgMz/provider?orgId=1&var-provider=0xc80f98a08fc5d20c78dcb197f0eab1cf3fdd825b&from=now-30d&to=now

**Comment by tomasmik** [comment]
Should be fixed as https://github.com/mysteriumnetwork/transactor/issues/206 was released.
