### ISSUE TITLE
Decouple "openvpn" package from Mysterium logic

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#341]

**Comment by Waldz** [comment]
Package moving started here https://github.com/Waldz/node/compare/feature/MYST-726-openvpn-tunnel-setup...Waldz:feature/MYST-723-exctract-openvpn?expand=1

**Comment by vkuznecovas** [comment]
Moved, see #379 
and https://github.com/mysteriumnetwork/go-openvpn/pull/1
