### ISSUE TITLE
[android, bug] Can't register identity

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3413]
**Describe the bug**
Two new users (already refunded) couldn't register identity.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6515014/mysterium-node.log)
[mysterium-node (1).log](https://github.com/mysteriumnetwork/node/files/6515016/mysterium-node.1.log)

**Environment (please complete the following information):**
 - Node version: 0.42.1
 - OS: Android

**Comment by vkuznecovas** [comment]
We had an outage on transactor. It's working now.

For future use, you might consider migrating to offchain balances, the registration will then be redundant.

**Comment by cvl** [comment]
:(
Bad timing, lost 2 customers :(

**Comment by cvl** [comment]
How can I migrate to offchain balances? What is this?

**Comment by tomasmik** [comment]
The new pilvytis offchain balances. If you're offchain, you dont nee to register and you dont need to have real balance.

It's the new v2 endpoints.
