### ISSUE TITLE
Testing v1.0.0-rc of mobile app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3416]
We're going to release our Android app soon. While it is in release candidate mode, we'd like to collect all possible bug reports. Please add comment in this issue with your findings.

**Comment by eugenegoncharuk** [comment]
After installation, I see 0.000 Myst tokens in my account.
Checked 2 hours later - same.

**Comment by tomasmik** [comment]
> After installation, I see 0.000 Myst tokens in my account.
Checked 2 hours later - same.

This was probably due to the issue we've had with transactor. I assume you've failed to register, not sure if app sends a registration request more than once now. Would be useful to see logs.

**Comment by eugenegoncharuk** [comment]
Tested now. 8.022 MYSTs are there.

**Comment by eugenegoncharuk** [comment]
Detected Bug.
Steps to reproduce:
- connect to one of the providers
- go surfing over the internet
- go back to Mysterium App
- tap on "Select another node"
- waiting until it connects
- crash happens

Expected:
App rejoins to another provider successfully.

**Comment by eugenegoncharuk** [comment]
Detected Bug with languages.
Steps to reproduce:
- open App
- go and change language to RU
- interface still in English

Expected:
Interface language changes successfully.

**Comment by chompomonim** [comment]
It would be good instead of `incorrect password` to show `please use at least 12 symbols for your password`.

**Comment by eugenegoncharuk** [comment]
[RC3]
Detected Bug.
Steps to reproduce:

- connect to one of the providers
- go surfing over the internet
- disable Wi-fi
- go back to Mysterium App
- it still show "Connected"

Expected:
The same message should appear indicating that the session has been dropped because of the bad network.

**Comment by eugenegoncharuk** [comment]
[RC3]
Detected Bug.
Steps to reproduce:

- connect to one of the Node provider
- go surfing over the internet
- disable Wi-fi
- enable wi-fi
- no internet available for surfing through the same Node provider

Expected:
- after Wi-fi enabled internet should be available through the same Node provider

**Comment by eugenegoncharuk** [comment]
[RC3]
Detected Bug.
Steps to reproduce:
- go to Mysterium App
- tap on "Account"
- try to top-up in MYST
- error is shown "Payment server doesn't work"

Expected:

- top-up in MYST is working

**Comment by chompomonim** [comment]
**Issues found in v1.0.0-rc3:**

- [ ] `Incorrect password` message should be changed to: `Password is too short`.

<img src="https://user-images.githubusercontent.com/153896/119822602-83f77200-befc-11eb-97ef-29ac249db9a5.png" width="250">

- [ ] We have view with filters, lets use it for "All nodes" screen.

<img src="https://user-images.githubusercontent.com/153896/119822998-f9fbd900-befc-11eb-8cc2-f560aaadb940.png" width="250"> <img src="https://user-images.githubusercontent.com/153896/119823482-8efed200-befd-11eb-8b28-50ed21df4cc7.png" width="250">

- [ ] "Download" filter should show only non-residential nodes, "Media Streaming" should show only residential nodes.

<img src="https://user-images.githubusercontent.com/153896/119823968-14828200-befe-11eb-908c-02dc782116db.png" width="250">

- [ ] App is loading significantly longer than our previous version. Is is due loader image or app itself is much more heavy?

- [ ] Can't click on "add to bookmark icon" :( 

<img src="https://user-images.githubusercontent.com/153896/119824167-4693e400-befe-11eb-8bfb-6a5bf14a2e9c.png" width="250">

- [ ] Connection screen shows wrong IP address

<img src="https://user-images.githubusercontent.com/153896/119824270-65927600-befe-11eb-8d45-1646b08f1a6b.png" width="250"><img src="https://user-images.githubusercontent.com/153896/119824289-6a572a00-befe-11eb-910f-f63f5c2ca6d5.png" width="250">

**Comment by Peter-SovietSquirrel** [comment]
Version 1.0-rc5 107101
The text Hight should be changed to something more suitable for example Best.

![IMG_20210606_103035](https://user-images.githubusercontent.com/60095913/120919784-442a4a80-c6b3-11eb-9c14-ef180a11a45f.jpg)
