### ISSUE TITLE
Connection state not updated correctly. Spam like emails being sent out and other visual bugs.

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3440]
**Describe the bug**

Multiple users report they get notified their nodes are disconnected even when they are not/ or nodes periodically stop working for a short period of time. Started happening few weeks ago. Possibly, an issue related to the changes in mmn and introducing of new discovery.

Perhaps a hint of possible error: "Failed to send exchange message error="peer error: could not unmarshal exchange message proto: proto: cannot parse invalid wire-format data""

Logs:
mysterium-node.log

**Environment (please complete the following information):**

Node version: 0.46.1 and earlier 
OS: all

**Additional context**
Possibly the same issue as last time. However, this time some of the providers were experiencing their node disappearing from the leaderboard. 
One provider (ID 0x641cb8019932) mentioned his earnings dropped to zero for awhile and got automatically readjusted afterwards.

**Comment by creotiv** [comment]
@isaackielma Do we have this problem now?
