### ISSUE TITLE
Bounty reset to 0 if node is marked as outdated

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3450]
```
{
    "5": {
        "Identity": "0xb57E7cbEBd97250Ed1Ab9890F7F1c6572Ea49716",
```

**Describe the bug**
Bounty reset to 0 (after payouts) if node is marked as outdated. 

**Expected behavior**
It should keep the accumulated balance and wait for provider to update his node version so it can be paid out.

**Screenshots**
<img width="1335" alt="Screenshot 2021-06-07 at 09 28 40" src="https://user-images.githubusercontent.com/60128746/120969379-c463b500-c772-11eb-8c40-3df984682cf0.png">

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: Alpine Linux v3.12 (Avado)

**Comment by MattLong6** [comment]
I have an AVADO. It was unplugged for a week. I think it is unfair that I did not receive my rewards from earlier in May before I unplugged it.
