### ISSUE TITLE
Make exit node installation process easier

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3456]
* User friendly Windows installer.
* NodeUI onboarding process could be simplified.
* Create Video instructions how to run exit node on various platforms
* Create installer for MacOS.
* Add possibility to become exit node in desktop app interface.
* Make NAT hole punching more stable + detect when it doesn’t work and show user friendly guides (video, pictures …) how to configure port forwarding.
* Allow to swich from NAT hole punching to port forwarding from user interface (maybe even provide external service to test if porst are properly forwarded)

**Comment by Donatas-MN** [comment]
Not relevant anymore as suggestions already implemented or have separate tasks created.
