### ISSUE TITLE
NAT hole punching and ports issue

### ISSUE THREAD

**Issue by venezuelan-folk** [mysteriumnetwork/node#3459]
I have some serious issues concerning NAT protocol and connection.
**********************************************
> irect_gateway=0
abr 22 20:24:30 jutsu-desktop myst[5462]: 2021-04-22T20:24:30.683 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,END
abr 22 20:24:30 jutsu-desktop myst[5462]: 2021-04-22T20:24:30.683 INF logconfig/openvpnlog.go:54               > Client with ID: 0 disconnected
abr 22 20:24:31 jutsu-desktop myst[5462]: 2021-04-22T20:24:31.451 DBG session/pingpong/price_calculator.go:72  > Calculated price 8825202701821. Time component: 2.0164700837499997983e+12, data component: 6.80873261807253289e+12
abr 22 20:24:31 jutsu-desktop myst[5462]: 2021-04-22T20:24:31.493 DBG core/service/subscription.go:77          > Received P2P message for "p2p-session-destroy": consumerID:"0x079827c41b7148bfe049dbc2a9167017d570af79" sessionID:"756bbace-030d-4253-9df2-5d1ceca9989b"
abr 22 20:24:31 jutsu-desktop myst[5462]: 2021-04-22T20:24:31.494 INF services/openvpn/service/manager.go:210  > Cleaning up session 756bbace-030d-4253-9df2-5d1ceca9989b
abr 22 20:24:31 jutsu-desktop myst[5462]: 2021-04-22T20:24:31.494 DBG session/pingpong/invoice_tracker.go:636  > Stopping...
abr 22 20:24:31 jutsu-desktop myst[5462]: 2021-04-22T20:24:31.545 DBG consumer/session/session_storage.go:294  > Session 756bbace-030d-4253-9df2-5d1ceca9989b updated with final data
abr 22 20:24:35 jutsu-desktop myst[5462]: 2021-04-22T20:24:35.553 INF market/mysterium/mysterium_api.go:203    > Proposal pinged for node: 0x7176c24cb3145cf45f54b84eebcf2da613b0a163 service type: openvpn
abr 22 20:24:36 jutsu-desktop myst[5462]: 2021-04-22T20:24:36.461 INF market/mysterium/mysterium_api.go:203    > Proposal pinged for node: 0x7176c24cb3145cf45f54b84eebcf2da613b0a163 service type: wireguard
a**br 22 20:24:41 jutsu-desktop myst[5462]: 2021-04-22T20:24:41.496 _****ERR services/openvpn/service/proxy.go:54     > Failed to write/read a stream to/from service natProxy error="read udp4******_ 192.168.0.100:42286->116.202.100.246:44272: use of closed network connection"
abr 22 20:24:41 jutsu-desktop myst[5462]: 2021-04-22T20:24:41.496 DBG services/openvpn/service/proxy.go:57     > Total bytes transferred from 116.202.100.246:44272 to 127.0.0.1:47074: 15204
abr 22 20:24:41 jutsu-desktop myst[5462]: 2021-04-22T20:24:41.496 ERR services/openvpn/service/proxy.go:54     > Failed to write/read a stream to/from service natProxy error="read udp 127.0.0.1:38079->127.0.0.1:47074: use of closed network connection"
abr 22 20:24:41 jutsu-desktop myst[5462]: 2021-04-22T20:24:41.497 DBG services/openvpn/service/proxy.go:57     > Total bytes transferred from 127.0.0.1:47074 to 116.202.100.246:44272: 19543
***********************************************************
First time I configured it on Free, one user managed to get connected and the command: 
*********
sudo journalctl -fu mysterium-node.service
*********
showed no errors or weird stuff whatsoever.

when I configured some prices then:
************************************

> envpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,END
abr 22 20:37:21 jutsu-desktop myst[5462]: 2021-04-22T20:37:21.083 INF logconfig/openvpnlog.go:54               > Client with ID: 0 connection established successfully
abr 22 20:37:21 jutsu-desktop myst[5462]: 2021-04-22T20:37:21.717 DBG session/pingpong/price_calculator.go:72  > Calculated price 555679991500. Time component: 5.5567999150000005335e+11, data component: 0
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.155 DBG eventbus/event_bus.go:81                 > Published topic="SessionTokensEarned" event={ProviderID:{Address:0x7176c24cb3145cf45f54b84eebcf2da613b0a163} SessionID:a013c80a-cc7c-4890-b3e8-79c7c4bd31f7 Total:+1}
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.155 INF session/pingpong/hermes_channel_repository.go:274 > Loaded state for provider {"0x7176c24cb3145cf45f54b84eebcf2da613b0a163"}, hermesID "0xD5d2f5729D4581dfacEBedF46C7014DeFda43585": balance 0, available balance 0, unsettled balance 84651927426693417
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.156 DBG eventbus/event_bus.go:81                 > Published topic="earnings_change" event={Identity:{Address:0x7176c24cb3145cf45f54b84eebcf2da613b0a163} Previous:{LifetimeBalance:+84651927426693416 UnsettledBalance:+84651927426693416} Current:{LifetimeBalance:+84651927426693417 UnsettledBalance:+84651927426693417}}
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.157 INF session/pingpong/hermes_promise_settler.go:250 > Received hermes promise for {"0x7176c24cb3145cf45f54b84eebcf2da613b0a163"}
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.157 INF session/pingpong/hermes_promise_settler.go:277 > Hermes "0xD5d2f5729D4581dfacEBedF46C7014DeFda43585" promise state updated for provider {"0x7176c24cb3145cf45f54b84eebcf2da613b0a163"}
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.240 DBG logconfig/openvpnlog.go:63               > [openvpn-proc] Stdout: Thu Apr 22 20:37:22 2021 127.0.0.1:57453 PUSH: Received control message: 'PUSH_REQUEST'
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.240 DBG logconfig/openvpnlog.go:63               > [openvpn-proc] Stdout: Thu Apr 22 20:37:22 2021 127.0.0.1:57453 SENT CONTROL [UNDEF]: 'PUSH_REPLY,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 60,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.240 DBG logconfig/openvpnlog.go:63               > [openvpn-proc] Stdout: Thu Apr 22 20:37:22 2021 127.0.0.1:57453 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.240 DBG logconfig/openvpnlog.go:63               > [openvpn-proc] Stdout: Thu Apr 22 20:37:22 2021 127.0.0.1:57453 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
abr 22 20:37:22 jutsu-desktop myst[5462]: 2021-04-22T20:37:22.490 DBG core/service/subscription.go:99          > Received P2P message for "p2p-session-acknowledge": consumerID:"0x948bad65f22608ff42dc61924bb96ec8a5a2183f" sessionID:"a013c80a-cc7c-4890-b3e8-79c7c4bd31f7"
abr 22 20:37:23 jutsu-desktop myst[5462]: 2021-04-22T20:37:23.718 DBG session/pingpong/price_calculator.go:72  > Calculated price 3762267927186. Time component: 1.05584396075000005835e+12, data component: 2.7064239664366177008e+12
abr 22 20:37:24 jutsu-desktop myst[5462]: 2021-04-22T20:37:24.801 DBG core/service/subscription.go:56          > Received P2P session status message for "p2p-session-connectivity-status": ConsumerID:"0x948bad65f22608ff42dc61924bb96ec8a5a2183f" SessionID:"a013c80a-cc7c-4890-b3e8-79c7c4bd31f7" Code:1000
abr 22 20:37:25 jutsu-desktop myst[5462]: 2021-04-22T20:37:25.719 DBG session/pingpong/price_calculator.go:72  > Calculated price 7164796639700. Time component: 1.5559983962500001029e+12, data component: 5.608798243450751654e+12
abr 22 20:37:27 jutsu-desktop myst[5462]: 2021-04-22T20:37:27.719 DBG session/pingpong/price_calculator.go:72  > Calculated price 8091125476001. Time component: 2.0561539335000001901e+12, data component: 6.034971542501473517e+12
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.025 DBG nat/traversal/pinger.go:334              **_> Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:41951: i/o timeout"_**
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.025 W**_RN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"_**
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.027 DBG nat/traversal/pinger.go:334              > Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:48444: i/o timeout"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.027 WRN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.029 DBG nat/traversal/pinger.go:334              > Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:44294: i/o timeout"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.030 WRN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.032 DBG nat/traversal/pinger.go:334              > Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:48563: i/o timeout"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.033 WRN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.047 DBG nat/traversal/pinger.go:334              > Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:46826: i/o timeout"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.048 WRN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.053 DBG nat/traversal/pinger.go:334              > Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:48593: i/o timeout"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.054 WRN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.056 DBG nat/traversal/pinger.go:334              > Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:41384: i/o timeout"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.057 WRN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.064 DBG nat/traversal/pinger.go:334              > Failed to read remote peer: <nil> - attempting to continue error="read udp4 0.0.0.0:47529: i/o timeout"
abr 22 20:37:28 jutsu-desktop myst[5462]: 2021-04-22T20:37:28.064 WRN nat/traversal/pinger.go:131              > One of the pings has error error="ping receiver error: NAT punch attempt stopped"
abr 22 20:37:29 jutsu-desktop myst[5462]: 2021-04-22T20:37:29.720 DBG session/pingpong/price_calculator.go:72  > Calculated price 8631121810760. Time component: 2.5562896537500000987e+12, data component: 6.0748321570105881863e+12
abr 22 20:37:31 jutsu-desktop myst[5462]: 2021-04-22T20:37:31.720 DBG session/pingpong/price_calculator.go:72  > Calculated price 9395385022521. Time component: 3.0564297282500000641e+12, data component: 6.3389552942719178815e+12
abr 22 20:37:33 jutsu-desktop myst[5462]: 2021-04-22T20:37:33.677 DBG eventbus/event_bus.go:81                 > Published topic="provider_ping_p2p" event={SessionID:a013c80a-cc7c-4890-b3e8-79c7c4bd31f7 Duration:182.705929ms}
abr 22 20:37:33 jutsu-desktop myst[5462]: 2021-04-22T20:37:33.721 DBG session/pingpong/price_calculator.go:72  > Calculated price 9926102114590. Time component: 3.5565994334999999175e+12, data component: 6.3695026810919874725e+12
abr 22 20:37:35 jutsu-desktop myst[5462]: 2021-04-22T20:37:35.721 DBG session/pingpong/price_calculator.go:72  > Calculated price 10441137494893. Time component: 4.056733649499999657e+12, data component: 6.384403845394459598e+12
abr 22 20:37:37 jutsu-desktop myst[5462]: 2021-04-22T20:37:37.722 DBG session/pingpong/price_calculator.go:72  > Calculated price 11053779872627. Time component: 4.556872236749999819e+12, data component: 6.4969076358781293473e+12
...
> abr 22 20:35:11 jutsu-desktop myst[5462]: 2021-04-22T20:35:11.736 DBG config/config.go:196                     > Returning default value chain-id:5
abr 22 20:35:11 jutsu-desktop myst[5462]: 2021-04-22T20:35:11.737 INF services/wireguard/service/service_unix.go:287 > Wireguard: started
abr 22 20:35:11 jutsu-desktop myst[5462]: 2021-04-22T20:35:11.736 DBG config/config.go:192                     > Returning user config value mmn.api-key:Ppm2XO1IuAOWNV8GOBJk9YTugb51qJh1XT0Gjm8L
abr 22 20:35:11 jutsu-desktop myst[5462]: 2021-04-22T20:35:11.737 INF session/pingpong/hermes_promise_settler.go:148 > State for {0x7176c24cb3145cf45f54b84eebcf2da613b0a163} already loaded, skipping
abr 22 20:35:11 jutsu-desktop myst[5462]: 2021-04-22T20:35:11.737 DBG config/config.go:192                     > Returning user config value mmn.api-key:Ppm2XO1IuAOWNV8GOBJk9YTugb51qJh1XT0Gjm8L
abr 22 20:35:11 jutsu-desktop myst[5462]: 2021-04-22T20:35:11.738 DBG config/config.go:196                     > Returning default value vendor.id:
abr 22 20:35:11 jutsu-desktop myst[5462]: 2021-04-22T20:35:11.827 DBG mmn/client.go:58                         > Registering node to MMN: {LocalIP:192.168.0.100 Identity:0x7176c24cb3145cf45f54b84eebcf2da613b0a163 APIKey:Ppm2XO1IuAOWNV8GOBJk9YTugb51qJh1XT0Gjm8L VendorID: OS:Linux Mint 20 Arch:linux/amd64 NodeVersion:0.45.0}
abr 22 20:35:13 jutsu-desktop myst[5462]: 2021-04-22T20:35:13.462 INF market/mysterium/mysterium_api.go:166    > Proposal registered for node: 0x7176c24cb3145cf45f54b84eebcf2da613b0a163 service type: wireguard
abr 22 20:35:13 jutsu-desktop myst[5462]: 2021-04-22T20:35:13.462 INF market/mysterium/mysterium_api.go:185    > Proposal unregistered for node: 0x7176c24cb3145cf45f54b84eebcf2da613b0a163
abr 22 20:35:13 jutsu-desktop myst[5462]: 2021-04-22T20:35:13.462 INF core/discovery/discovery.go:218          > Proposal unregistered

and running check connection with that:
***********************************

> openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_COMP_STUB=1
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.273 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_LZO=1
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.274 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_LZ4v2=1
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.274 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_LZ4=1
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.274 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_CIPHERS=AES-256-GCM:AES-128-GCM
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.275 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_NCP=2
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.275 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_PROTO=2
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.276 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_PLAT=linux
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.276 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,IV_VER=2.4.10
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.277 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,remote_port_1=40586
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.277 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,local_port_1=40586
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.278 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,local_1=0.0.0.0
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.278 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,proto_1=udp
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.279 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,daemon_pid=19588
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.279 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,daemon_start_time=1619138107
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.279 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,daemon_log_redirect=0
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.280 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,daemon=0
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.280 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,verb=3
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.280 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,ifconfig_local=10.8.0.1
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.280 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,ifconfig_netmask=255.255.255.0
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.280 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,ifconfig_broadcast=10.8.0.255
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.280 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,script_context=init
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.280 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,tun_mtu=1500
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.281 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,link_mtu=1621
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.281 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,dev=tun0
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.281 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,dev_type=tun
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.281 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,redirect_gateway=0
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.281 DBG logconfig/openvpnlog.go:63               > [openvpn-mgmt] Line delivering: >CLIENT:ENV,END
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.281 INF logconfig/openvpnlog.go:54               > Client with ID: 0 disconnected
abr 22 20:37:43 jutsu-desktop myst[5462]: 2021-04-22T20:37:43.725 DBG session/pingpong/price_calculator.go:72  > Calculated price 13606561014132. Time component: 6.0576311785000003242e+12, data component: 7.5489298356327073565e+12
abr 22 20:37:45 jutsu-desktop myst[5462]: 2021-04-22T20:37:45.220 DBG core/service/subscription.go:77          > Received P2P message for "p2p-session-destroy": consumerID:"0x948bad65f22608ff42dc61924bb96ec8a5a2183f" sessionID:"a013c80a-cc7c-4890-b3e8-79c7c4bd31f7"
abr 22 20:37:45 jutsu-desktop myst[5462]: 2021-04-22T20:37:45.221 INF services/openvpn/service/manager.go:210  > Cleaning up session a013c80a-cc7c-4890-b3e8-79c7c4bd31f7
abr 22 20:37:45 jutsu-desktop myst[5462]: 2021-04-22T20:37:45.221 DBG session/pingpong/invoice_tracker.go:636  > Stopping...
abr 22 20:37:45 jutsu-desktop myst[5462]: 2021-04-22T20:37:45.262 DBG consumer/session/session_storage.go:294  > Session a013c80a-cc7c-4890-b3e8-79c7c4bd31f7 updated with final data
abr 22 20:37:55 jutsu-desktop myst[5462]: 2021-04-22T20:37:55.222 ERR services/openvpn/service/proxy.go:54     > Failed to write/read a stream to/from service natProxy error="read udp4 192.168.0.100:40091->116.202.100.246:47621: use of closed network connection"
abr 22 20:37:55 jutsu-desktop myst[5462]: 2021-04-22T20:37:55.223 DBG services/openvpn/service/proxy.go:57     > Total bytes transferred from 116.202.100.246:47621 to 127.0.0.1:40586: 12665
abr 22 20:37:55 jutsu-desktop myst[5462]: 2021-04-22T20:37:55.223 ERR services/openvpn/service/proxy.go:54     > Failed to write/read a stream to/from service natProxy error="read udp 127.0.0.1:57453->127.0.0.1:40586: use of closed network connection"
abr 22 20:37:55 jutsu-desktop myst[5462]: 2021-04-22T20:37:55.223 DBG services/openvpn/service/proxy.go:57     > Total bytes transferred from 127.0.0.1:40586 to 116.202.100.246:47621: 7780
terium/mysterium_api.go:203    > Proposal pinged for node: 0x7176c24cb3145cf45f54b84eebcf2da613b0a163 service type: wireguard
abr 22 20:50:23 jutsu-desktop myst[5462]: 2021-04-22T20:50:23.179 ERR core/quality/mysterium_morqa.go:106      > Failed to sent batch metrics request error="Post https://testnet2-quality.mysterium.network/api/v2/batch: EOF"

********************************************

Help one Venezuelan folk to get around the grip of a brutal dictatorship :(

This is my configuration to disable the Experimet Hole Punch

[mysterium-node-service.txt](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/6361978/mysterium-node-service.txt)

**Comment by chompomonim** [comment]
@venezuelan-folk we just release new version of node and desktop apps. Could you test it? Your problem may be fixed already.

**Comment by eugenegoncharuk** [comment]
@venezuelan-folk We have a newer version of the Node released 0.48.0. Are you still facing with this problem?

**Comment by chompomonim** [comment]
It should be fixed. If the problem will repeat, please open new issue.
