### ISSUE TITLE
DNS leaks again

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3462]
**Describe the bug**
DNS leaks again.
Reported by customer, also I can see the leaks on https://www.dnsleaktest.com/results.html and https://ipleak.net/ by myself.
(see screenshots).
<img width="818" alt="Screenshot 2021-06-09 at 15 14 52" src="https://user-images.githubusercontent.com/100252/121352607-b4e09980-c935-11eb-8699-05e08b082cc5.png">
<img width="963" alt="Screenshot 2021-06-09 at 15 12 12" src="https://user-images.githubusercontent.com/100252/121352621-b8742080-c935-11eb-8924-2cbf4691a9c8.png">

Tried by myself with provider 0xd6d92aeacc071ee7411862286bd0996d1a60bc9c

Affected OS: Windows, Linux. Mac not affected.

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: Windows, Linux, Mac, Windows

**Comment by cvl** [comment]
also on 0.47.1

**Comment by cvl** [comment]
Any progress with this?

**Comment by vkuznecovas** [comment]
The status is as following:

The DNS leaks were introduced in https://github.com/mysteriumnetwork/node/pull/3461/files

This was due to the fact that after release it was figured out that we're having issues on windows due to this. Temporarily, this functionality got disabled. 

It will be back once it's fixed(expect sometime this week).

**Comment by cvl** [comment]
Thank you!

**Comment by cvl** [comment]
@vkuznecovas any news on this?

**Comment by cvl** [comment]
Any updates on this?

**Comment by cvl** [comment]
Guys, are we still communicating?

**Comment by cvl** [comment]
Nice!

Will this be included in 0.54.0 ?

**Comment by Snawoot** [comment]
@cvl Sure, it will, changes already merged. Expecting it in next release.

**Comment by cvl** [comment]
Hi @Snawoot when do you expect this to be released?

**Comment by Snawoot** [comment]
@cvl Hi! Was released two releases ago, in 0.53.1.

**Comment by cvl** [comment]
thanks!

**Comment by cvl** [comment]
I'd suggest to add notes to release, especially for such critical change as a fix for DNS leak.
