### ISSUE TITLE
Tokens earned stuck at 1.77K

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3464]
**Describe the bug**

```
{
    "5": {
        "Identity": "0x0baA8B4bE102923AfDD84cc821871A849BA8e36A",
```

Tokens earned stuck for node with many successful sessions.

**Screenshots**
<img width="788" alt="Screenshot 2021-06-09 at 19 00 17" src="https://user-images.githubusercontent.com/60128746/121389448-18c68a80-c955-11eb-9865-edec4b450a24.png">
<img width="883" alt="Screenshot 2021-06-09 at 19 00 45" src="https://user-images.githubusercontent.com/60128746/121389451-19f7b780-c955-11eb-8364-d054bfc6c9d2.png">

**Environment (please complete the following information):**
 OS:
Debian GNU/Linux 10 (buster)
Architecture:
linux/amd64
Node version:
0.46.2-rc0

**Comment by mixmafritz** [comment]
I got this problem, i have lot of sessions with gigabyte of download into my node, but Myst earning still static 66.30 Myst. Amount not moving for few days. I did nothing special, it is a VM on a server. I upgraded to version 0.47.0 still same problem.

**Comment by tomasmik** [comment]
This is due the whole gas price issue. Settlements are either very slow or not happening at all, in turn the earnings graph isn't getting updated. This should not affect much though, after a settlement eventually goes through it should take in to account the tokens earned.
