### ISSUE TITLE
0.47.1 Test failed

### ISSUE THREAD

**Issue by vegtelenmt2** [mysteriumnetwork/node#3467]
**Describe the bug**
Test failed.

**Environment (please complete the following information):**
 - Node version: 0.47.1
 - OS: Ubuntu 20.04.2 LTS
- Not use docker.

**Comment by soffokl** [comment]
@vegtelenmt2 could you please provide your identity?

**Comment by vegtelenmt2** [comment]
0x5b9ace3658ca5e04688a8264e86c90c9e11c588a

**Comment by Sciph3r** [comment]
I, too, am getting Test Failed

Node Version: 0.47.1
OS: Linux Mint 20.1
No docker/native

Identity: 0x7ab67aabdaac9734e6d77edcfb23b250d3210589

**Comment by soffokl** [comment]
@vegtelenmt2 your node is online now. 
@Sciph3r your node is online as well.
