### ISSUE TITLE
After upgrade to 0.47.1 registration is not succeeded

### ISSUE THREAD

**Issue by eugenegoncharuk** [mysteriumnetwork/node#3474]
Node ID: 0x5060e5f0894da23de93b594d02868c7f2d148d81
error message: “Failed to contact hermes to get new registration status error”- ‘could not request consumer data from Hermes’: internal error.

**Comment by eugenegoncharuk** [comment]
![Image from iOS](https://user-images.githubusercontent.com/87538/122008548-de7c4380-cdc1-11eb-9fce-7471dfee96fa.jpg)
![identity registering](https://user-images.githubusercontent.com/87538/122008580-e6d47e80-cdc1-11eb-9683-f52860cfba1b.jpg)

**Comment by isaackielma** [comment]
Environment:

Node version: 0.47.1
OS: Ubuntu 20.04 LTS under Proxmox server

**Comment by vkuznecovas** [comment]
We had an issue with registrations, to fix you'll need to re-register manually. Sorry about that. Here's the instructions:


To fix this, access the cli via `myst cli` and run the following:

```
identities unlock 0x5060e5f0894da23de93b594d02868c7f2d148d81
```

Then 

```
identities register 0x5060e5f0894da23de93b594d02868c7f2d148d81 10000000000000000000 {your_beneficiary_address}
```

This should solve the issue.


Alternatively, you can delete & reinstall, but this would destroy your identity.
