### ISSUE TITLE
Payments. Consumer replies to balance sent by Provider

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#348]
*IN ORDER TO* responde to Service Provider’s balance message sent
*AS A* Consumer
*I WANT TO* reply with proper response 

h2. Acceptance Criteria
* Consumer replies with “balance recieved”
* Constumer replies with “balance_error”

h2. Later
 Myst-19 will do “Constumer replies with “updated promise”

**Comment by zolia** [comment]
Outdated by new payment model.
