### ISSUE TITLE
Kill switch not working on desktop

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3483]
**Describe the bug**
- Use "--keep-connected-on-fail=true", flag when starting myst. You'll need to enter password in dev mode for node to start.
- Connect to some provider
- Use Network Link Conditioner (from xcode) to kill your connection (100% packets dropped)
- The connection status goes to OnHold (which is okay)
- After reenabling the connection, it works for few seconds (i.e. I can see the IP of the provider I was connected to before the connection kill).
- Yet after few seconds, it disconnects from provider, and original IP is revealed.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6654602/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.47.1
 - OS: Mac

**Comment by cvl** [comment]
Works well on Android though.

**Comment by cvl** [comment]
Hi @Snawoot 

Sounds awesome.

Is there any particular flag/config that needs to be set on desktop app to enable kill-switch?

**Comment by Snawoot** [comment]
Hi @cvl 

It's `--keep-connected-on-fail`
