### ISSUE TITLE
Payments. Consumer sends(replies) with "updated old promise" to extend the service

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#349]

**Comment by Waldz** [comment]
\-\->>> Update description

‌h2 User story
*IN ORDER TO* perform payment for service
*AS A* Consumer
*I WANT TO* Provider to get my Promise (check) to pay later

h2. Acceptance Criteria
* Serialise promise to JSON
* Send promise to Node via CommunicationChannel

h2. Later
* Promise will be sent to Node via communication channel (another ticket)
* Create Promise structure after successful VPN connection (still discussible)

**Comment by zolia** [comment]
We need a continuous stream of promise messages to be able to keep data session up.

**Comment by mjankauskas** [comment]
@Waldz @zolia is it relevant for this milestone?

**Comment by zolia** [comment]
This is an old issue and was implemented already. Currently we are working on adapting an old promise mechanism to Accountant pattern.
