### ISSUE TITLE
Residential node incorrectly identified as Business IP

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3490]
**Describe the bug**
Node ID: 0x37cacf3baf5060639cbf47a3640d14d0c178b21a

Provider is experiencing an issue where he is running a node in his own residence but dashboard Identifies node as business IP.

**Expected behavior**
 Node should be categorized as a residential IP as it previously did before the update.

 

**Screenshots**
<img width="376" alt="Screenshot 2021-06-15 at 14 46 47" src="https://user-images.githubusercontent.com/84313603/122063848-89075d00-cde8-11eb-9828-972c81171d3b.png">

**Environment (please complete the following information):**
 - Node version: [0.47.0]
 - OS: (Avado)

**Additional context**
Also same provider is no longer able to adjust his pricing. Upon trying to adjust pricing it goes to zero and does not slide up. However, node has been set with the default price of .1/gb and .0001 per hour.

**Comment by etherunit** [comment]
@isaackielma We are taking this type of data from Maxmind service. It's using the GeoIP2 connection type database to determine the connection type based on the IP address.

Provider should submit a correction request through the forms, linked https://support.maxmind.com/geoip-data-correction-request/

**Comment by vkuznecovas** [comment]
If this is something that's occuring frequently, it needs to be opened as a separate issue. 
```
Additional context
Also same provider is no longer able to adjust his pricing. Upon trying to adjust pricing it goes to zero and does not slide up. However, node has been set with the default price of .1/gb and .0001 per hour.
```

As far as incorrect categorization @etherunit is correct, there's nothing for us to do, the user needs to contact maxmind.
