### ISSUE TITLE
Reduced Traffic after update to new release.

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3493]
**Describe the bug**
Reduced Traffic after update to new release (compared to the last node versions). Providers are reporting to have a lot less clients connecting to their nodes after the update. Barely none. After attempting connecting to these nodes I could only connect a few times. Most times I would get the error

**Expected behavior**
Ideally, update should either maintain or positively affect the performance of node and quality of the sessions.

**Environment (please complete the following information):**
 - Node version: 0.47.1 update

**Additional context**
**Ed**:

I still have no client traffic since updating my node 0xeeb7f1ade35da77b096c47430452a18d53c9f14d to node ver 0.47, any suggestions?

3d day with almost no traffic after update to 0.47.1.

My node resets price to 0.0000 myst on its own,  since  update to 0.47.1 and there almost no client traffic since update

Obs: Tried connecting to the node, ‘oops could not connect error’

**Nicolas :**

"Hello admins, I did the 0.47.1 update, and unfortunately I have a lot less clients connecting to my node. What's happening? I think that this version is completely bug, it's impossible that I find myself suddenly with so few connections!"

Node ID: 0xfcd07eb90bf3a6fce52d8a9dfee6322a3611c410

**:**

"I have two nodes: 0x0ee934c5340b6fa336e83d5039f9d5e05d653a95 and 0xcec6d9724357714b1e174dd3346871ea67734b6b
I managed to update 0x0ee934c5340b6fa336e83d5039f9d5e05d653a95 to version 0.47.1 but when i upgrade to this version i am not receiving ongoing VPN sessions any longer, how come? (i reverted to the old version because i will keep earning)."

**Comment by etherunit** [comment]
it will stabilise itself once the major part of consumers will start using 0.47+ node compatible apps.
