### ISSUE TITLE
Documentation on how to use kill switch pragmatically

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3504]
In v0.47 we have released experimental kill switch support. It is enabled by default in mobile apps however it is not clear how to use it by app developers. 

We need documentation:
- [x] How to enable/disable kill switch from kotlin code without touching node and go lang.
- [x] How to enable/disable kill switch for desktop app (via tequilapi) without touching node and golang code.
- [x] How to enable/disable kill switch for cli consumer (e.g. which exactly flags to use, what exactly to set in config file...)

NOTE: if there is not possible to create documentation because such functionality don't exist, please create supportive tasks to implement it and then continue with documentation.

**Comment by soffokl** [comment]
Starting from the node version 0.64.0 kill-switch for the consumer can be enabled using the following approach: 

1) **Command like argument** - set `--keep-connected-on-fail=true` flag when starting a node.
2) **CLI** - `myst config set keep-connected-on-fail false` allow to set configuration for the flag.
3) **TequilAPI golang client**  has method `SetConfig` that allows you to set any configuration flag, including `keep-connected-on-fail`.
4) **TequilAPI** - `http://127.0.0.1:4050/config/user` endpoing allows you to set any configuration flag, including `keep-connected-on-fail`
5) **Mobile node** has method `SetUserConfig(key, value string) error` that allows you set any configuration flag, including keep-connected-on-fail

All of these methods are applied on the fly and do not require node restarts.
