### ISSUE TITLE
Add kill switch support to Mysterium dVPN app

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3505]
Mysterium android dVPN app is going into "On Hold" state when there are issues with connection which prevents from leaking network requests outside of VPN tunnel. It also is trying to reconnect to same node after lost connection.

We need to enable such functionality for desktop apps as well. Ideally this should be configurable in app's settings (enable/disable).

**Comment by cvl** [comment]
Any news on this?

**Comment by cvl** [comment]
Any updates on this?

This is a critical feature of any VPN.

**Comment by chompomonim** [comment]
This task is client side implementation, we're working on #3506

**Comment by cvl** [comment]
Hmm, please don't spend time on "documentation", which is not needed.
Please focus just on making it work.

**Comment by cvl** [comment]
Any progress on implementing kill switch?
Waiting 2+ years now :\

**Comment by soffokl** [comment]
Starting from the node version 0.64.0 kill-switch for the consumer can be enabled using the following approach: 

1) **Command like argument** - set `--keep-connected-on-fail=true` flag when starting a node.
2) **CLI** - `myst config set keep-connected-on-fail false` allow to set configuration for the flag.
3) **TequilAPI golang client**  has method `SetConfig` that allows you to set any configuration flag, including `keep-connected-on-fail`.
4) **TequilAPI** - `http://127.0.0.1:4050/config/user` endpoing allows you to set any configuration flag, including `keep-connected-on-fail`
5) **Mobile node** has method `SetUserConfig(key, value string) error` that allows you set any configuration flag, including keep-connected-on-fail

All of these methods are applied on the fly and do not require node restarts.

**Comment by cvl** [comment]
hi @soffokl 
is kill-switch enabled by default on Android app as before, or do I need to enable it by calling SetUserConfig when starting app?

**Comment by soffokl** [comment]
@cvl if the configuration was not set, it will be enabled by default. Once the configuration is saved it will keep using the value from the configuration.

**Comment by cvl** [comment]
Thank you

**Comment by whaler237** [comment]
Would you be able to make a video tutorial on how to set up the kill switch for the average user? I'm on Windows 10, not running a node.
