### ISSUE TITLE
Ensure that kill switch is easy to use by 3rd party developers

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3506]
While kill switch is not enabled in desktop apps and there is no proof that it is working correctly we need to:

- [x] Retest if this functionality is still working and how to use is
- [x] Create documentation for app developers on how to use it (#3504)
- [ ] Add kill switch support to Mysterium dVPN app (#3505)

@cvl is reporting that:
- For mobile kill-switch is enabled by default. There's no (easy) way to disable it for now.
- setDisableKillSwitch flag is old and obsolete, shouldn't be used.
- In desktop, use flag "--keep-connected-on-fail=true", when starting myst process. Yet when using this flag, node doesn't start. (#3483)
- Get notification on connection drop: unknown

**Comment by soffokl** [comment]
I'll close this since only subtask task are left, which will be covered in a separate issue.
