### ISSUE TITLE
Lag on updating MMN eligible status for updated node

### ISSUE THREAD

**Issue by eugenegoncharuk** [mysteriumnetwork/node#3515]
There is lag for a 30+ minutes happening on eligible status update for node in the MMN.

Steps to reproduce:
- have an outdated node [0.46.1]
- update node with latest version [0.47.2]
- log in to NodeUI > MMN Integration > re-enter API key and save it
- log in to MMN > select your updated node
- click on exclamation mark inside Bounties box

Observed:
- "Your node's version is too old. Please, upgrade"

Expected:
- Green box should appear "You're all set!"

**Comment by eugenegoncharuk** [comment]
Screenshots attached
![exclamation_mark](https://user-images.githubusercontent.com/87538/122559777-712e1400-d048-11eb-8244-af478ccf8fe4.jpg)
![message](https://user-images.githubusercontent.com/87538/122559784-72f7d780-d048-11eb-9486-7f6daa0f4f5a.jpg)

**Comment by eugenegoncharuk** [comment]
Should be
![image](https://user-images.githubusercontent.com/87538/122559858-8acf5b80-d048-11eb-91c8-aefd63abfe47.png)

**Comment by untitledlt** [comment]
Can not reproduce it.

Possibly related fix in https://github.com/mysteriumnetwork/my.mysterium.network/pull/92

**Comment by eugenegoncharuk** [comment]
This can be fixed by implementing this task https://github.com/mysteriumnetwork/my.mysterium.network/issues/86

**Comment by eugenegoncharuk** [comment]
It's related to UpdateMonthlyReports scheduler job
$schedule->command(UpdateNodeMonthlyReports::class)
    ->hourly();
    run once in 1 hour
