### ISSUE TITLE
pilvytis api docs url not working anymore

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3518]
https://testnet2-pilvytis.mysterium.network/swagger/index.html site can't be reached

**Comment by tomasmik** [comment]
Pilvytis is up and running: https://testnet2-pilvytis.mysterium.network/api/v1/ping

Just checked the swagger link - it can be reached.

**Comment by cvl** [comment]
doesn't work for me

**Comment by cvl** [comment]
also some apps cannot be started anymore, e.g. android I get 
2021-06-18 16:34:33.458 30530-30530/network.portals.vpn E/DeferredNode: Failed to start node
    go.Universe$proxyerror: could not bootstrap dependencies: failed to connect to NATS servers [nats://testnet2-broker.mysterium.network:4222 nats://testnet2-broker.mysterium.network:4222 nats://95.216.204.232:4222]: nats: no servers available for connection
        at mysterium.Mysterium.newNode(Native Method)

mac I get 
2021-06-18T16:33:47.666 ERR source/cmd/mysterium_node/mysterium_node.go:68 > Failed to execute command:  error="failed to connect to NATS servers [nats://testnet2-broker.mysterium.network:4222 nats://testnet2-broker.mysterium.network:4222 nats://95.216.204.232:4222]: nats: no servers available for connection"

**Comment by tomasmik** [comment]
Are you sure it's not just some network/dns issues that you're having? All apps are working for me, pilvytis also loads and is running.

**Comment by cvl** [comment]
I don't know. I'm not alone though, someone on Discord complains as well.

Might be dns issues, if the of webservices IP changed?

**Comment by cvl** [comment]
Cleaned cache with sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder still not working :\

**Comment by vkuznecovas** [comment]
DNS records have not been touched, so everything should be in order. 

Tested via multiple remote locations, all seems to be in order. Have you tried rebooting? :)

**Comment by cvl** [comment]
Just did. It helped.
Never experienced anything like that.

Thank you.

**Comment by cvl** [comment]
There's one fellow on Discord with similar problem, I assume he has experienced the same issue.
