### ISSUE TITLE
Communication Channel. Provider sends Session metering to Consumer

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#352]
h2 User story
*IN ORDER TO* know how Provider is charging for Service
*AS A* Service Consumer
*I WANT TO* get all session metering & payment notifications from Provider
 
h2. Acceptance Criteria
- ???

h2. Later
- Provider checks if he is knows same price for Service???

**Comment by zolia** [comment]
scope of another task with payments.
