### ISSUE TITLE
stuck on "Your identity is being registered, please be patient..."

### ISSUE THREAD

**Issue by andrewasd** [mysteriumnetwork/node#3520]
**Describe the bug**
In node UI I'm stuck on: "Your identity is being registered, please be patient..."
i tried deleting and acclaiming the nodes from the account but I'm still stuck on that screen, how can i reset the node ui?
i also tried restarting the node service but it's the same
is there a way to reset the node settings reconfigure everything?

**Environment (please complete the following information):**
 - Node version: latest
 - Ubuntu 21.04

Edit , I managed to reinsall the app, but now im getting this error
![image](https://user-images.githubusercontent.com/44606697/122646970-3b5d5e00-d122-11eb-8471-7db3a52fea12.png)

**Comment by etherunit** [comment]
@tomasmik Can you please look into it? Thx

**Comment by tomasmik** [comment]
This issue should be resolved now. A re-registration attempt will be required either using the CLI or removing the current identity all together and restarting node.
