### ISSUE TITLE
Unclear as to which ports to open

### ISSUE THREAD

**Issue by tacerus** [mysteriumnetwork/node#3521]
The Docker routed TCP/4449 allows access to the admin UI, however the Firewall logs show a bunch of rejected UDP requests, and your system reports my node to be offline. This does not seem right. It's also weird how the Docker instructions for Linux show different port mappings then the Docker instructions for Windows/macOS.

**Comment by etherunit** [comment]
@tacerus Can you please refer to the latest docker guides: https://docs.mysterium.network/node-runners/setup/docker/

**Comment by tacerus** [comment]
Thanks, I did. It only mentions `-p 4449:4449` for Linux, which, from my understanding, ONLY routes the port for the Web GUI to outside of the container. In the Windows part, further ports are listed. I do not understand how you intend Docker on Linux to magically route the other ports?
