### ISSUE TITLE
SPIKE kill switch

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#354]
In order to for a customer to be sure that his traffic will not leak via unsecured (no vpn) link
As I customer, I want to be able to turn on kill switch effectively stopping all traffic if VPN connection becomes unavailable.

**Comment by zolia** [comment]
We will probably fail with our openvpn approach. Problem is that client clears out routes if it reaches ping-restart timeout. That is we loose tun device even if openvpn client stays alive:

routes:

0/1 10.8.0.1 UGSc 95 0 utun1
10.8/24 10.8.0.65 UGSc 45 0 utun1
10.8.0.65 10.8.0.65 UH 1 0 utun1
128.0/1 10.8.0.1 UGSc 14 5 utun1

gets removed.

Client receives ping-restart timeout from the server. We could ignore it, but that would solve problem only for UDP connections. We could also manage routes ourselves , but this will not work for Darwin. Also it will keep alive sessions on server.

Route management might be an options, but in certain cases (computer restarted) routes might be reapplied and you could loose your kill switch. Also, this will not work for Darwin as our own route management will be clashing with openvpn routes. We cannot have persist tun on darwin.

To track inactivity timeout you should get such clear out report: 
2018-09-11T13:22:16.088507827 [Trace] [openvpn-process] Stdout: Tue Sep 11 16:22:16 2018 [0x0f3dc88e2fa9d716c67b0169531a94780709678d] Inactivity timeout (--ping-restart), restarting
2018-09-11T13:22:16.088899695 [Trace] [openvpn-process] Stdout: Tue Sep 11 16:22:16 2018 /sbin/route delete -net 54.38.213.93 192.168.0.1 255.255.255.255

Some fw based approach:

https://technofaq.org/posts/2017/08/how-to-setup-a-manual-kill-switch-to-prevent-openvpn-leaks-in-gnulinux-os-x-and-windows/

**Comment by zolia** [comment]
Currently we will leave ConnectOptions and kill switch as a mock. We will be introducing kill-switch for each platform one-by-one.
