### ISSUE TITLE
Installing mysterium with the bash script messes up dns

### ISSUE THREAD

**Issue by gitxmax** [mysteriumnetwork/node#3540]
**Describe the bug**

**To Reproduce**
1. Fresh Ubuntu  install
2. Install mysterium using the bash script

 - Node version: 0.47.2
 - OS:Ubuntu 18.04 or 20.04

After the installation complete, the node comes up and runs fine, till I restart the server.
After reboot, no internet connection is available, keep on getting " Temporary failure in name resolution", I presume some dns issues ..

systemctl status mysterium-node.service:

`justwhynot:~# sudo systemctl status mysterium-node.service
● mysterium-node.service - Server for Mysterium - decentralised VPN Network
   Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2021-06-23 04:45:25 PDT; 3s ago
     Docs: https://mysterium.network/
  Process: 1894 ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS service --agreed-terms-and-conditions $SERVICE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 1894 (code=exited, status=1/FAILURE)

Jun 23 04:45:25 justwhynot systemd[1]: mysterium-node.service: Main process exited, code=exited, status=1/FAILURE
Jun 23 04:45:25 justwhynot systemd[1]: mysterium-node.service: Failed with result 'exit-code'.

systemd-resolve --status:
`Failed to get global data: Unit dbus-org.freedesktop.resolve1.service not found.`

`

**Comment by gitxmax** [comment]
from my observation, by default the machine has cat /etc/resolv.conf returning google dns servers.  After installing the mysterium script, those are gone and no internet connection, after reboot.

**Comment by soffokl** [comment]
hm, this is very weird, mysterium node service or install script does not touch any DNS configuration of the system. 
I was installing it many times on different Ubuntu versions and everything was working fine there. 

Are you sure that no other components could do this with system DNS? 
If it reproducible case could you please provide the output of the bash install script?
