### ISSUE TITLE
Unable to update beneficiary wallet address

### ISSUE THREAD

**Issue by AsgardexTester** [mysteriumnetwork/node#3543]
The beneficiary address is set to 0x0000000000000000000000000000000000000000 despite having input the wallet address duringg initial setup. Attempts to update it shows the following error messages.

![image](https://user-images.githubusercontent.com/79346230/123187175-330f7500-d4cc-11eb-8e21-b4c5222ec5d2.png)

![image](https://user-images.githubusercontent.com/79346230/123186804-833a0780-d4cb-11eb-841d-224efb48e28a.png)

**To Reproduce**
Attempt 1: updated beneficiary address via web UI
Attempt 2: updated beneficiary address via MYST CLI

Status attempting to check: identities beneficiary-status 0xe258795356f2bd4315a903d70e8ead8a3c635bc1
﻿
identities beneficiary-status 0xe258795356f2bd4315a903d70e8ead8a3c635bc1
[INFO] Current beneficiary: 0x0000000000000000000000000000000000000000
[INFO] Last change request information:
[INFO] Change to: _ETH address appears here_
[INFO] State: completed
[WARNING] Error: server response invalid: 429 Too Many Requests (https://testnet2-transactor.mysterium.network/api/v1/identity/settle_with_beneficiary)Limit exceeded
\u00bb

**Environment (please complete the following information):**
 - Node version: 0.4.7.2
 - OS: Raspbian GNU/Linux 10 (buster)
 - Desktop app version (if applicable): 0.1.32
 - Docker (if applicable): NA

**Comment by frissia** [comment]
Same issue here !
