### ISSUE TITLE
"NAT status Not Finished" not fixable

### ISSUE THREAD

**Issue by rush0815** [mysteriumnetwork/node#3548]
I burned the image for my pi, configured the node and all was fine with the NAT. First 3 sessions came in a few minutes later. Then I restarted my node and now I only see "NAT status Not Finished". Don't understand why because it worked before the reboot. I have nothing changed on my raspberry nor the router till here.

Also UPnP is activated on my router, but no ports have been opened by my node via UPnP.
I have tried every option mentioned in   https://docs.mysterium.network/node-runners/troubleshooting/#nat-traversal
No one worked, still getting "NAT status Not Finished".

I then burned the image again on the same card, used the same raspberry. It connected to the same router with unchanged configuration and NAT  was green again.

I have found that NAT remains green only at the first boot. As soon as I reboot the PI, NAT becomes orange and says "NAT status Not Finished"  forever. Even after the reboot it becomes never green again.

After the first reboot dmesg shows this (maybe it helps):
![dmesg](https://user-images.githubusercontent.com/61414616/123345191-d5c00600-d555-11eb-86bb-9fac4ac277e5.png)

**Environment (please complete the following information):**
 - Node version: 0.48.0
 - WebUI version: 0.3.0
 - OS: your official provided raspberry pi image

**Comment by StefanStieger** [comment]
Also tried this yesterday on my raspberry pi and the same issue. 

BTW: The link in the description to mystberry.zip is a dead end.
https://docs.mysterium.network/node-runners/setup/raspberry-pi/

Node version: 0.48.0
WebUI version: 0.3.0
OS: your provided raspberry pi image
