### ISSUE TITLE
Unable to connect to docker node with android app, but good connection with windows app. 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3561]
**Describe the bug**
"I almost always can't connect to my docker node by android app, but i have a good connection with my docker node by windows app. Sometimes i can connect by android app, but it happens so rarely. My node is 0x813d855bd73cdd5661ea0c375951c4e9feecc1c8"

**To Reproduce**
1. Open mobile app
2. Connect to node
3.  'Oops could not connect'

**Expected behavior**
Both mobile and desktop apps should be connecting at all times 

**Environment (please complete the following information):**

OS:Alpine Linux v3.12(docker)

Architecture:linux(docker)/amd64

Node version:0.48.0

**Comment by soffokl** [comment]
Does the android app use WiFi or mobile network when trying to connect to the provider?

**Comment by Serque** [comment]
i try to connect to my node via wifi and mobile network, but phone does not connect

**Comment by soffokl** [comment]
@Serque thanks for the information. Could you please send a report from the app? It will send logs so we could analyze the problem.

**Comment by Serque** [comment]
> @Serque thanks for the information. Could you please send a report from the app? It will send logs so we could analyze the problem.

How can i do that?

**Comment by Serque** [comment]
> > @Serque thanks for the information. Could you please send a report from the app? It will send logs so we could analyze the problem.
> 
> How can i do that?

i sent bug report from android app

**Comment by soffokl** [comment]
@Serque thanks for the report, I have received it. It's still unclear what is happening, but we are trying to analyze the problem to resolve it.

**Comment by Serque** [comment]
same problem when i trying to connect from PC

**Comment by Serque** [comment]
same problem when i try to connect from pc

**Comment by soffokl** [comment]
@Serque we did another fix that could help you, but it's not released yet. I hope we will be able to release it today.

**Comment by soffokl** [comment]
@Serque could you try to update your node to 0.51.0 version?

**Comment by Serque** [comment]
> @Serque could you try to update your node to 0.51.0 version?

it is done

**Comment by soffokl** [comment]
I see. Waiting for the android release to test It on the updated android version.

**Comment by soffokl** [comment]
Android app version 1.0.4 released, should be available for download soon.

**Comment by Serque** [comment]
the issue fixed
