### ISSUE TITLE
[Windows, bug] can't start node: could not get consumers channel: no contract code at given address

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3567]
**Describe the bug**
User is having trouble starting node. I can see errors like 2021-06-30T15:09:53.101 ERR source/session/pingpong/consumer_balance_tracker.go:356 > Could not get consumer channel error="could not get consumers channel: no contract code at given address"

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6742140/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.47.2
 - OS: Windows

**Comment by cvl** [comment]
x

**Comment by theluke** [comment]
Same issue here!
Raspi4
Node version: 1.2.2
Port 1194 is forwarded in the router, as well as ports 14000-32000

**Comment by ganzocrypt** [comment]
same issue on RPI 4
"Could not get consumer channel error="no contract code at given address"
Node version 1.3.3

on the console I have the spinning and this message:
"Your identity is being registered, please be patient..."

The node is into my account but as offline.
any suggestions?

**Comment by Killerbeans** [comment]
Most likely your identity hasn't been registered.

Type the following in your console: 

`myst cli`

Followed by this:

`identities list`

Copy, paste the identity and run in this:

`identities register <identity>`

Exit Myst CLI with Ctrl + C

restart myst node with:

`sudo systemctl restart mysterium-node.service
`
Wait for about 15 to 30 minutes.  If it node doesn't go online, repeat the process.
