### ISSUE TITLE
[Windows, bug] Connection keeps dropping, after drop, no Internet connection until computer restart

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3572]
**Describe the bug**
User reported, that with node 0.47.2 connection keeps dropping, after connection drop, he doesn't have Internet (even if he disconnects and quits the app), until he restart the computer.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6747760/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.47.2
 - OS: Windows

**Comment by tomasmik** [comment]
Not stale really. People are still reporting this.

**Comment by cvl** [comment]
x
