### ISSUE TITLE
[android] user can't connect, multiple errors (node 0.50.1)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3575]
**Describe the bug**
Received the report that user can't connect to nodes. I can see multiple errors in the logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6753264/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.50.1
 - OS: Android

**Comment by soffokl** [comment]
Try to use 0.51.0, we did some fixes for that.

**Comment by cvl** [comment]
Thanks
