### ISSUE TITLE
nats: no servers available for connection"

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3576]
**Describe the bug**
User sent logs, I can see the error nats: no servers available for connection" in the logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6753349/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.50.1
 - OS: Linux

**Comment by tomasmik** [comment]
This is a known issue that sometimes occurs. From my testing this could be related to a non stable/slow internet connection.
@soffokl  please take a look in to this one.
