### ISSUE TITLE
[windows] could not request consumer data from hermes: resource not found

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3577]
**Describe the bug**
Got logs from user, I can see multiple errors:
could not request consumer data from hermes: resource not found
then Could not get consumer channel error="could not get consumers channel: no contract code at given address"
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6753397/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.47.2
 - OS: Windows

**Comment by tomasmik** [comment]
That error actually means nothing in this case. That consumer is known to hermes, here: https://testnet2-hermes.mysterium.network/api/v1/data/consumer/0xd785d3fe64b7f793a3bbf3790a0b0dc1c8b8bcec

That error is something you can get on initial launch, but it should in no way interfere with the node function. As soon as you become offchain or register your identity, these errors will disappear.
Logs have no other useful information. There were a lot of changes done between that node version you reported and current one which improved the connection stability, the only logical advice here is to update your node version.
