### ISSUE TITLE
Add possibility to run exit node on non Debian based Linux distributions

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3581]
At the moment only debian like (e.g. Ubuntu) Linux users are able to run mysterium exit nodes. We provide .deb packages via launchpad, but there are many Linux users who're using different type of distributions.

We may build either snap or rpm packages to cover bigger range of potential users.

**Comment by Snawoot** [comment]
I expect [this PR](https://github.com/mysteriumnetwork/node/pull/3663) will make it possible to run node on any Linux.
