### ISSUE TITLE
Allow changing traversal priorities

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3588]
At the moment traversal mechanism priorities are hard-coded.

1. Check if node is running on **public address**.
2. Try using **UPnP** 
3. **NAT hole punching**
4. Manual port forwarding. 

We could make that priorities configurable via config. The same config could disable some of them (e.g. if `nat_traversal: ["upnp", "port_forwarding"] then nat hole punching and public address checks could be not done at all)

If possible, we could show how many of last 100 sessions were used by which configuration method + their success rate

> NOTE: This would allow make NAT punching as seconds step instead of third because NAT hole punching could be successful in bigger percentage of sessions than UPnP.

**Comment by Snawoot** [comment]
I'm asking to clarify how this task relates to #3585

If we enforce additional check against external services on each forwarded port with UPnP, we may not care about priorities.

**Comment by soffokl** [comment]
This is about giving an option to the user to set the order for the checks. If a user knows that UPnP works for him, he can set this as a first option and not waste time on other options. 
Doing all the checks takes time and these options will give a possibility to make connections faster. 

Most of the users will live with an automatic option though.
