### ISSUE TITLE
Huge logs files - /var/log partition gets 100% full in very short time

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#3599]
If there's a small number of connections to the node, the daemon.log and syslog files are just behaving normally.
They grow up slowly, and rotate when it's scheduled.

If there are many connection to the node, the logs are growing incredibly fast, and the /var/log partition gets full in just a few hours (my /var/log partition is 80 GB in size), and logrotation will not work, as there's no free space to compress the files.

**Environment (please complete the following information):**
 - Node version: 0.52.0
 - OS: Raspbian Buster

**Comment by soffokl** [comment]
We had a bug in the old versions when it was generating too many logs. 
These logs could be produced by the old version even if you are running the latest one now. 
This should not appear in the latest versions after cleaning old logs. Please let me know if you will face it again.
You can change the logs level to less verbose to make the log size smaller too.

**Comment by lollapalooza1973** [comment]
How do I change the log verbosity?

**Comment by soffokl** [comment]
There is a flag, you can set it to the `--log-level=info`

**Comment by lollapalooza1973** [comment]
Shall I set this in ` /etc/default/mysterium-node`?
Something like
`LOG_LEVEL="--log-level=info"`

**Comment by soffokl** [comment]
yep, it goes to the `/etc/default/mysterium-node`

should be like `DAEMON_OPTS="--keystore.lightweight --log-level=info"`

**Comment by lollapalooza1973** [comment]
Great, thank you.
