### ISSUE TITLE
Introduce new endpoint in MMN for changing beneficiary address

### ISSUE THREAD

**Issue by eugenegoncharuk** [mysteriumnetwork/node#3604]
Need to have new endpoint in MMN that would receive close to this json
{
"beneficiary": "0x00000012312312312312312312313213",
"signature": "0x12312521AFAFAFAFAFAFAFAFAFAFAFAFAFAFFAFAFAFAFFAFAFAAFAFAFAFAFAFAFAFAFAFAFAFAFAF"
}

Then do ecrecover on signature with the beneficiary and get the signer. If this signer matches one in our MMN DB then update the DB with new data.

ecrecover - function can be gathered from https://github.com/wmh/php-ecrecover/

**Comment by untitledlt** [comment]
https://github.com/mysteriumnetwork/my.mysterium.network/pull/97
https://github.com/mysteriumnetwork/my.mysterium.network/pull/99
