### ISSUE TITLE
[mac] 0.51.0 node doesn't start, multiple errors: Could not recover Grand Total Promised, could not get consumers channel, protocol wrong type for socket

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3606]
**Describe the bug**
User can't get node up and running. I can see multiple errors: Could not recover Grand Total Promised, could not get consumers channel, protocol wrong type for socket...

Logs:
[mysterium-node 48.log](https://github.com/mysteriumnetwork/node/files/6797399/mysterium-node.48.log)

**Environment (please complete the following information):**
 - Node version: 0.51.0
 - OS: Mac

**Comment by tomasmik** [comment]
I would assume I just fixed this. Registrations were getting stuck the whole day today.
There are improvements coming on monday to reduce such instances.
