### ISSUE TITLE
Rewrite /bin helpers to Golang in /ci package

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#361]
Pros:
- We can modern engineering (conditions, variables, CLI args, reuse functions)
- Bash is not cross-platform and Go is

Good example https://github.com/ethereum/go-ethereum/tree/master/build

Now:
```
BINARY=build/myst/myst_linux_amd64 bin/package_standalone linux
```

Vision:
```
go build/package.go standalone --os=linux --output=build/myst/myst_linux_amd64
```
or `bin/package` -> links to go `build/package.go`

**Comment by vkuznecovas** [comment]
One implementation that might work is magefile - makefile combo. See example at https://github.com/mysteriumnetwork/go-openvpn/pull/23. Need a decision on it though - do we port the magefiles as a separate lib or do we actually just copy paste the files here?

**Comment by tcharding** [comment]
`go` command in 'Vision' is missing `run` @Waldz :)

**Comment by tcharding** [comment]
Has this been discussed further @vkuznecovas @Waldz?  Are we wanting to go with the mage option like go-ovenvpn or with the ethereum option?
