### ISSUE TITLE
Test windows installer (for exit nodes)

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3618]
Now we do have exit node installer for Windows 10. It will install and run Mysterium node in docker container and configure it without a need to touch command line. It will also have one click upgrade feature.

Now we need to test it. You can download release preview from here:
[https://github.com/mysteriumnetwork/myst-launcher/releases](https://github.com/mysteriumnetwork/myst-launcher/releases)

Please add your issue reports and suggestion in comments above.

**Comment by Zensey** [comment]
https://github.com/mysteriumnetwork/myst-launcher/releases/tag/0.0.1-preview18

**Comment by AdineVikash** [comment]
![image](https://user-images.githubusercontent.com/68943180/126776659-fa422a2c-39b7-45bd-89fd-24ac8ca29c0a.png)
The download url does not working, could you please fix it?

**Comment by shlavik** [comment]
seems like private repo

**Comment by AdineVikash** [comment]
> seems like private repo

Yeah.

**Comment by chompomonim** [comment]
Thanks for reporting, made public so now you can download it.

**Comment by Zensey** [comment]
For last releases turn to this page:
https://github.com/mysteriumnetwork/myst-launcher/releases

**Comment by evanmcfarland** [comment]
I set up with Testnet 3 Windows installer and things went smooth as butter. The hardest part was enabling virtualization in BIOS settings. Well done.
