### ISSUE TITLE
Auto upgrade for docker nodes (installed with windows installer)

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3622]

**Comment by Zensey** [comment]
Probably we can just do `docker pull mysteriumnetwork/myst:latest` once per week, when launcher starts.
However it needs to be checked if contaner's data stays survives this.

**Comment by Zensey** [comment]
As of 0.0.1-preview11 it is ready.
https://github.com/mysteriumnetwork/myst-launcher/releases/tag/0.0.1-preview11

**Comment by chompomonim** [comment]
Are you still working on this? Can we close this task? I think manual mode is good enough solution.
