### ISSUE TITLE
 My Node Not Updating Earnings

### ISSUE THREAD

**Issue by kabirzohaib22** [mysteriumnetwork/node#3624]
My node is not updating any earnings since past week. it's stuck on that same value. 
Neither in the dashboard nor in the MMN network website.
![2121](https://user-images.githubusercontent.com/87380999/125478263-977e4262-94a6-4d9f-9a31-7172ea8ff9be.JPG)
![1212](https://user-images.githubusercontent.com/87380999/125478275-f8ee8e70-6e48-41f7-9a5f-b9c97459309a.JPG)

Node is Running On RPI 4B (Raspbian 10 Buster)
Node version  - 0.52.0
Node ID - 0xc35e91a92d88cfe6692d250268b478e81c3d9f8c

**Comment by isaackielma** [comment]
0xfd4b5b24903463589002935891f13650f0b69f8e 

Provider also experiencing the same issue. earnings not updating on dashboard

**Comment by etherunit** [comment]
Earnings are adjusted now (looking at graph).

**Comment by kabirzohaib22** [comment]
> 
> 
> Earnings are adjusted now (looking at graph). @isaackielma

indeed the new earnings are getting updated, but the earlier ones are still not added. i did the calculation/day. it's showing much much lower than then it should be.
