### ISSUE TITLE
Release 0.3 version with Paid ID

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#363]
Acceptance Criteria:
- make feature toggle `myst service --experiment-identity-check` and DI registers `IdentityRegisterNoop`
- Create branch `release/0.3` and tag release `0.3.0`
- Deploy WITH `--experiment-identity-check` to Devnet servers
- Deploy WITHOUT `--experiment-identity-check` to 1 Testnet server
- Test http://github.com/mysteriumnetwork/mysterium-vpn 0.2.* version with 1 new Testnet server
- Deploy WITHOUT `--experiment-identity-check` to all Testnet servers

**Comment by soffokl** [comment]
Looks like everything done in the scope of the issue.
