### ISSUE TITLE
Tagging service

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#3637]
Create a tag service

Tag service should allow to add tags to proposals. These tags could be things like "netflix", "hulu", ... 

The tag service should:

- [x] 1. Allow to create a tag.
- [x] 2.  Allow to update a tag.
- [x] 3. Allow to delete a tag.
- [x] 4. Allow to assign a tag to a given identity.
- [x] 5. Allow to remove an assigned tag from a given identity.
- [x] 6. Allow to list all identities with their corresponding tags(paging, probably). Mostly used for universe management.
  - [x]  Add pagination
- [x] 7. Allow to list the tags(tags created in step 1).
- [x] 8. Allow to list the tags that are assigned to a specific node(accept a providerID).

All endpoints except for the last two should be protected by universe auth. The last 2 are public.

**Comment by Waldz** [comment]
> Allow to update a tag.
IMHO not needed

> Allow to assign a tag to a given identity.
Not `identity`, but `unique proposal` everythere e.g. "Allow to assign a tag to a given proposal."

**Comment by tomasmik** [comment]
Service created, will be releasing to testnet3: https://github.com/mysteriumnetwork/badger
