### ISSUE TITLE
Tag management via universe

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#3638]
Add tag management dashboard to universe:

The universe should allow to edit the tags in the tag service.

1) Allow to create a tag.
1) Allow to update a tag.
1) Allow to delete a tag.
1) Allow to see all identities that have tags assigned to them(paging, probably).
1) Allow to assign a tag to a given identity.
1) Allow to remove an assigned tag from a given identity.

Ideally, identities should be autocompleted from the available proposals or chosen via dropdown.

**Comment by tomasmik** [comment]
Badger is alive and ready to be implemented. Swagger is here: https://testnet3-badger.mysterium.network/swagger/index.html
