### ISSUE TITLE
Your node does not have a wallet address.

### ISSUE THREAD

**Issue by Vineet7805** [mysteriumnetwork/node#3640]
Hi Team,

I have been facing the issues with mysterium network. It is exactly the same issue raised earlier.
https://github.com/mysteriumnetwork/node/issues/3391

Issue 3391 was closed without giving solution. I am seeing on telegram, this issue is happening to others.
Also on my https://my.mysterium.network/leaderboard, I am seeing only one node. Earlier it was showing all the to 600 records.

Thanks,
Vineet Sharma.

**Comment by xpecex** [comment]
My node is having the same problem, tested with versions 0.48.0 and 0.52.0 both have the same error. 

Error message on log:
2021-07-18T04:27:10.311 ERR source/session/pingpong/consumer_balance_tracker.go:379 > align with hermes failed with a critical error, offchain balance out of sync error="could not request consumer data from hermes: could not unmarshal error body: invalid character 'B' after top-level value"

**Comment by chompomonim** [comment]
Have you added you beneficiary/payout address in NodeUI ([your_ip]:4449) settings section?

**Comment by xpecex** [comment]
Yes, it was already configured and working, but it suddenly stopped working, including the Residential Leaderboard (https://my.mysterium.network/leaderboard) only appears one node, now (without any intervention from me) it works again, both my node as the Leaderboard listing.

**Comment by tomasmik** [comment]
This was probably due to an issue we have with one of our services. It is now solved?
