### ISSUE TITLE
Many users down, offchain balance out of sync error, failed to connect to NATS servers etc

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3641]
**Describe the bug**
Many users reported that nothing works. Seems like Mysterium backend is down again?
I can see errors like failed to connect to NATS servers, align with hermes failed with a critical error, offchain balance out of sync error="could not request consumer data from hermes: could not unmarshal error body: invalid character 'B' after top-level value"

Logs:
[mysterium-node 50.log](https://github.com/mysteriumnetwork/node/files/6835906/mysterium-node.50.log)

**Environment (please complete the following information):**
 - Node version: 0.51.0
 - OS: Windows, Mac

**Comment by chompomonim** [comment]
This should be fixed by now.
