### ISSUE TITLE
Node is online, latest version and still not discoverable in app

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3642]
**Describe the bug**
Node seems to be online and working correctly. However, address cannot be identified in the app.

0xf770f0f5eca91de957db8f93800bb236d3618823

**To Reproduce**
1. Go to Mysterium VPN app
2. Paste address on search bar
3. Address does not appear

**Expected behavior**
Node should be listed in both apps mobile and desktop.

**Environment (please complete the following information):**
OS: Raspbian GNU/Linux 10 (buster)
Architecture: linux/arm
Node version: 0.52.0

**Comment by etherunit** [comment]
Address is present in the dVPN app. Please check it once again :)
App version: 1.0.5
Node version: 0.52.0
<img width="292" alt="Screenshot 2021-07-21 at 12 38 48" src="https://user-images.githubusercontent.com/60128746/126467802-86434d45-f932-4944-ada5-c31c9b4b6c89.png">

**Comment by etherunit** [comment]
@isaackielma Can this be closed?
