### ISSUE TITLE
Our monitoring agent tried to connect to your node, but something went wrong

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3643]
**Describe the bug**
0xe2fd9dbe32cfde3c9205eb82b45f7e509069db46 node reading as test failed no sessions at all. Provider has said to have forwarded ports 

**Environment (please complete the following information):**
OS:
Ubuntu 18.04 LTS
Architecture:
linux/amd64
Node version:
0.52.0

**Additional context**

**Comment by etherunit** [comment]
We're using 4 connection establishment mechanisms. Node is trying to test each of them (in ordered way) to become connectable for consumers.

1. Check if node is running on public address. If there is public IP attached to the network interface, then node is asking external services (e.g. location oracle and couple other fallback services at once) to ping him and ensure that ports are visible/opened externally.

2. If step 1 fails, then node is trying to use UPnP (communicates with router and check if UPnP enabled). There still may be some situations when there are a couple of routers (in a layered NATs) before final gateway and second router is not supporting UPnP so we may additionally need to ask external services to check if node is accessible.

3. If step 2 fails (or UPnP is disabled on your router), then node is trying to use `NAT hole punching. This technique is énabled by default (in node) and requires support from both sides (consumer and provider). Also in some cases (depending on ISP router configs) internally punched ports are not matched with one visible externally. To solve such async port mapping we're using STUN servers (again requesting a few external services at once and moving forward on first positive response).

4. If all previous cases fails (or false), node assumes that user should configure manual port forwarding. In this particular scenario, node operator should manually configure ports in his router and adjust node configuration file to run services on a predefined ports.

If you have ensured that port forwarding is done correctly (both in the config file and in the router) and there no specific fw rules that might be blocking connection than try steps 1,2,3 (if applicable);

**Comment by etherunit** [comment]
This node ip_type=hosting. Additionally check if forward or input chains are not set to drop packets.

Generate iptables output: `sudo iptables-save`
Set fw INPUT and FORWARD chain policies to Accept (if needed):

```
sudo iptables -P FORWARD ACCEPT
sudo iptables -P INPUT ACCEPT
```

**Comment by trupsalms** [comment]
This is a public server with port forwarding enable as well as open ports, I'm not sure why it's not connecting.

**Comment by trupsalms** [comment]
root@racknerd:~# sudo iptables -L INPUT
Chain INPUT (policy DROP)
target     prot opt source               destination
ufw-before-logging-input  all  --  anywhere             anywhere        
ufw-before-input  all  --  anywhere             anywhere
ufw-after-input  all  --  anywhere             anywhere
ufw-after-logging-input  all  --  anywhere             anywhere         
ufw-reject-input  all  --  anywhere             anywhere
ufw-track-input  all  --  anywhere             anywhere
root@racknerd:~# sudo iptables -L OUTPUT
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ufw-before-logging-output  all  --  anywhere             anywhere       
ufw-before-output  all  --  anywhere             anywhere
ufw-after-output  all  --  anywhere             anywhere
ufw-after-logging-output  all  --  anywhere             anywhere        
ufw-reject-output  all  --  anywhere             anywhere
ufw-track-output  all  --  anywhere             anywhere
root@racknerd:~# sudo iptables -L FORWARD
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
ufw-before-logging-forward  all  --  anywhere             anywhere      
ufw-before-forward  all  --  anywhere             anywhere
ufw-after-forward  all  --  anywhere             anywhere
ufw-after-logging-forward  all  --  anywhere             anywhere       
ufw-reject-forward  all  --  anywhere             anywhere
ufw-track-forward  all  --  anywhere             anywhere

**Comment by Snawoot** [comment]
Trying to connect, getting message in my node logs:

```
2021-08-08T20:31:07.904 DBG p2p/channel.go:212    > Creating p2p channel with local addr: 192.168.1.62:25544, UDP session addr: 127.0.0.1:34072, proxy addr: 127.0.0.1:49696, remote peer addr: 45.158.199.199:49044
```

Quickly tracerouting it:

```
[20:30:14] dt1:~/src/node> sudo traceroute -U 45.158.199.199 49044
traceroute to 45.158.199.199 (45.158.199.199), 30 hops max, 49044 byte packets
 1  rpi-gw (192.168.1.1)  5.241 ms  9.004 ms  13.646 ms
 2  213.231.0.200 (213.231.0.200)  25.204 ms  73.649 ms  87.590 ms
 3  91.203.136.9 (91.203.136.9)  101.005 ms  102.775 ms  107.210 ms
 4  194.44.212.37 (194.44.212.37)  121.475 ms  124.981 ms  125.103 ms
 5  ipv4.de-cix.fra.de.as1828.unitasglobal.com (80.81.196.38)  145.440 ms * *
 6  * ae1-3.cr2.fra1.de.unitasglobal.net (50.115.90.107)  63.198 ms  116.093 ms
 7  * * ae30.cr1.iad1.us.unitasglobal.net (50.115.90.146)  145.734 ms
 8  * * *
 9  e0-16.cr1.lax2.us.unitasglobal.net (50.115.91.42)  191.829 ms  265.714 ms  336.269 ms
10  inap.cust.lax2.us.unitasglobal.net (198.232.115.138)  236.349 ms  240.709 ms  245.299 ms
11  border1.ae2-bbnet2.lax014.pnap.net (216.52.255.115)  236.824 ms  239.203 ms  189.586 ms
12  dedipath-lacp.border1.lax014.pnap.net (69.88.129.106)  198.479 ms  202.376 ms  189.143 ms
13  23.147.224.15 (23.147.224.15)  214.669 ms  652.133 ms  1349.002 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

UDP packets are **NOT** passing to destination host. Check middlebox firewals and/or local firewall configuration.

**Comment by trupsalms** [comment]
Is it wiregaurd or openvpn, and if so what specific ports need to be
opened?

**Comment by Snawoot** [comment]
@trupsalms  I've tried wireguard, but stuck at building service p2p-channel for payment promises, so doesn't really matter what protocol.

Those which are configured with `--p2p.listen.ports` and `--wireguard.listen.ports`. Note that each incoming session requires at least one port from each group.

**Comment by Snawoot** [comment]
Also note: you have to open UDP ports, not TCP.

**Comment by trupsalms** [comment]
I read somewhere openvpn does not work or is not used, and I usually open
both tcp/udp at same time for used ports.

**Comment by trupsalms** [comment]
However, I'm not sure how to set the port in this config for either openvpn
or wiregaurd. I run a separate openvpn instance also, i know how to set the
port there, just not in the one that mysterium installs

**Comment by Snawoot** [comment]
@trupsalms Please refer to node runner documentation: https://docs.mysterium.network/node-runners/troubleshooting/#port-forwarding

**Comment by trupsalms** [comment]
I'll try this process again but it didn't work out last time

**Comment by Snawoot** [comment]
@trupsalms You can check if ports within given range are open for UDP traffic manually with netcat/socat/etc.

E.g. on your node server run:

```
nc -l -u 1234
```

On any other linux machine run:

```
nc -u 45.158.199.199 1234
```

and start typing lines. If you'll see them on the other end port's open. Otherwise it's not.
