### ISSUE TITLE
Potential MITM on P2P service channel

### ISSUE THREAD

**Issue by Snawoot** [mysteriumnetwork/node#3645]
### Background

Mysterium node uses some flow to establish P2P connection (`p2p.Channel`) to provider node which can be roughly described like this:

1. Provider node listens for request messages on public message broker (`nats://testnet2-broker.mysterium.network:4222`) topics related to it's Provider ID and service pair.
2. Consumer node initiates connection, sending public ECDHE part signed with consumer node identity key.
3. Provider node responds with ephemeral public ECDHE part signed with provider node identity key.
4. Provider and consumer node exchanging P2P connection configuration, authenticated and encrypted with agreed shared key.
5. Provider and Consumer build KCP connection encrypted with agreed shared key.

### Problem

Both peers do not verify if signature made with public key of expected peer identity. [Current identity `Verifier`](https://github.com/mysteriumnetwork/node/blob/dd44549ba5415a9405f00e70861ffa8d2ae45a9d/cmd/di.go#L311-L319) in use [doesn't ensure that signature was made by any known identity key](https://github.com/mysteriumnetwork/node/blob/dd44549ba5415a9405f00e70861ffa8d2ae45a9d/identity/verifier.go#L40-L47), identity just gets discarded. However, there is [another verifier](https://github.com/mysteriumnetwork/node/blob/dd44549ba5415a9405f00e70861ffa8d2ae45a9d/identity/verifier.go#L49-L61) which does identity matching, but it seems it is not used anywhere except integration tests.

Combined with communication via public NATS server, it makes possible to tap into such channels even without actual access to both peers internet connection (i.e. middlebox is not required). This channel is used to pass parameters of actual service connection and altering exchanged parameters may ruin actual VPN service security.

### Mitigation

Obviously, at least Consumer must verify Provider node identity.

It's unclear for me if further interactions has to be cryptographically bound to consumer identity (i.e. disallow service requests and other requests which specify Consumer ID other than ID requested channel). Maybe it's also has to be enforced.

**Comment by vkuznecovas** [comment]
Good catch, I'll add it to todo, we'll fix it :)
