### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Serque** [mysteriumnetwork/node#3651]
**Describe the bug**
Unable to connect to my node by android app. Node: 0x813d855bd73cdd5661ea0c375951c4e9feecc1c8

**To Reproduce**
1. Open android app
2. Click on the node
4. See error 'Filed to connect  '

**Expected behavior**
Successful connection to node. Assignment the node's ip-address.

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 0.52.0
 - OS: Ubuntu 20.04
 - Desktop app version (if applicable): -
 - Docker (if applicable): Docker version 20.10.7, build f0df350, myst tag: latest

**Additional context**

**Comment by tomasmik** [comment]
Could you please provide additional information such as android app logs, node logs for the time frame when the connection is being established? Also would be useful it you'd specify if you're using mobile data or wifi? Are others able to connect to the node with no issues?

**Comment by Serque** [comment]
what exactly logs do you need. could you show me where  the node logs should be placed and how to save logs on android? Thanks.

**Comment by Serque** [comment]
Here is the node log file.
[Node_log_813.pdf](https://github.com/mysteriumnetwork/node/files/6895424/Node_log_813.pdf)

**Comment by Serque** [comment]
> Here is the node log file.
> [Node_log_813.pdf](https://github.com/mysteriumnetwork/node/files/6895424/Node_log_813.pdf)

The File contains records when i try to connect to node by android app. i  using phone internet connection.
