### ISSUE TITLE
Test failed not connectable updated version

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3655]
**Describe the bug**
0xe2fd9dbe32cfde3c9205eb82b45f7e509069db46 discoverable in the app but not connectable.

**Expected behavior**

**Screenshots**
<img width="877" alt="Screenshot 2021-07-21 at 20 22 58" src="https://user-images.githubusercontent.com/84313603/126547809-3c4d691f-cf91-4456-9227-f612dd1dcacf.png">

**Environment (please complete the following information):**
OS:Ubuntu 18.04 LTS
Architecture:linux/amd64
Node version:0.52.0

**Comment by etherunit** [comment]
Based on Grafana, he was never connectable, but his proposal is listed in app.

<img width="659" alt="Screenshot 2021-07-22 at 08 06 42" src="https://user-images.githubusercontent.com/60128746/126592599-246fb335-aa1c-45bb-a1e4-d9d701fa96df.png">

**Comment by trupsalms** [comment]
This is a public server with port forwarding enable as well as open ports, I'm not sure why it's not connecting.
