### ISSUE TITLE
Pre-mainnet (a.k.a. testnet3) testing

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3656]
We're starting `pre-mainnet` testing. The main flows to test are:

- Install fresh node for Linux via apt (https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/testnet3)
- Install node into Windows using our new installer
- Install docker node
- Install fresh raspberry pi node using this image: https://github.com/mysteriumnetwork/nightly/releases/latest/mystberry.zip
- Upgrade current testnet2 node into testnet3 node (by changing apt config and doing `apt update; apt upgrade`
- Register into MMN3 (https://mmn3.mysterium.network) and claim node there
- Try changing beneficiary address (it should change immediately, even with zero token balance)
- Install desktop, cli or mobile app (you can get them here: https://github.com/mysteriumnetwork/nightly/releases/latest) and try connecting to your own and other nodes. Check connection stability. 

NOTE:
Node registration should take not longer than 10 seconds, if you're waiting longer, report us!

------
**How to update/install your Docker node:**

**Update:** 
Pull the testnet3 node image: `docker pull mysteriumnetwork/myst:testnet3`
Delete the container that is already being used for running node: `docker rm -f myst`
Follow the running a docker node guide (https://docs.mysterium.network/node-runners/setup/docker/) to start a new container using `:testnet3` tag.

**Install a new one:** 
Check our installation guides here: https://docs.mysterium.network/node-runners/setup/docker/ 
Use `:testnet3` tag

------
**How to update your Linux node:**

Add the repo:
1. `sudo add-apt-repository ppa:mysteriumnetwork/testnet3`

Update after repo change:
2. `sudo apt-get update`

Update the cache policy:
3. `sudo apt-cache policy myst`

4. Pick your command for your OS:
Ubuntu 18.04.5 LTS (Bionic Beaver) › `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+bionic`
Ubuntu 16.04.7 LTS (Xenial Xerus) › `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+groovy`
Ubuntu 20.04.2 LTS (Focal Fossa) › `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+focal`
Ubuntu 21.04 (Hirsute Hippo) › `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute`

------
How to update your RPi node:

In `/etc/apt/sources.list` add source `deb http://ppa.launchpad.net/mysteriumnetwork/testnet3/ubuntu focal` 

`cat /etc/apt/sources.list`
Uncomment line below then ‘apt-get update’ to enable ‘apt-get source’
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
#deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
#deb http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu focal main
deb http://ppa.launchpad.net/mysteriumnetwork/testnet3/ubuntu focal main

Remove unattended-upgrades: 
`sudo apt-get -y remove unattended-upgrades`
`sudo apt-get update`
`sudo apt-cache policy myst`
`sudo apt install myst=<Myst candidate version>`

**Comment by aaugustin4omnis** [comment]
'aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster' when add-apt-repository ppa:mysteriumnetwork/testnet3 - does this mean we can only install a fresh node as far as the raspberry pi is concerned?

**Comment by AdineVikash** [comment]
> 'aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster' when add-apt-repository ppa:mysteriumnetwork/testnet3 - does this mean we can only install a fresh node as far as the raspberry pi is concerned?

if your added the testnet3 repository then run `sudo apt-cache policy myst`
`apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute`

Else do `sudo add-apt-repository ppa:mysteriumnetwork/testnet3` `sudo apt-get update` and then run `sudo apt-cache policy myst`
`apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute` and your good to go!

**Comment by aaugustin4omnis** [comment]
> > 'aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster' when add-apt-repository ppa:mysteriumnetwork/testnet3 - does this mean we can only install a fresh node as far as the raspberry pi is concerned?
> 
> if your added the testnet3 repository then run `sudo apt-cache policy myst`
> `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute`
> 
> Else do `sudo add-apt-repository ppa:mysteriumnetwork/testnet3` `sudo apt-get update` and then run `sudo apt-cache policy myst`
> `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute` and your good to go!

Thanks - the problem is that add-apt-repository fails because it could not find a distribution template for Raspbian/Buster. E.g. https://stackoverflow.com/questions/62248269/aptsources-distro-nodistrotemplateexception-error-could-not-find-a-distributio

So I think it's something that needs fixing on the repository end or alternatively have a public list of supported Raspbian systems if it's a case of unsupported distro?

**Comment by AdineVikash** [comment]
![image](https://user-images.githubusercontent.com/68943180/126636543-f1bf904b-1b35-4c48-a34f-ce25216a8a48.png)
![image](https://user-images.githubusercontent.com/68943180/126636326-517cff4e-f806-48d3-bbd1-9bf8a86eb541.png)

My IP address is residential and it was showing as **Your node's IP addresses is not residential,** and i was rebooted the raspberry pi.

**Comment by AdineVikash** [comment]
> > > 'aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster' when add-apt-repository ppa:mysteriumnetwork/testnet3 - does this mean we can only install a fresh node as far as the raspberry pi is concerned?
> > 
> > 
> > if your added the testnet3 repository then run `sudo apt-cache policy myst`
> > `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute`
> > Else do `sudo add-apt-repository ppa:mysteriumnetwork/testnet3` `sudo apt-get update` and then run `sudo apt-cache policy myst`
> > `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute` and your good to go!
> 
> Thanks - the problem is that add-apt-repository fails because it could not find a distribution template for Raspbian/Buster. E.g. https://stackoverflow.com/questions/62248269/aptsources-distro-nodistrotemplateexception-error-could-not-find-a-distributio
> 
> So I think it's something that needs fixing on the repository end or alternatively have a public list of supported Raspbian systems if it's a case of unsupported distro?

![image](https://user-images.githubusercontent.com/68943180/126636979-37eef97b-8b22-46c6-be1f-8c5c192938bb.png)
Seems like yes but i'm not sure, they might not added update feature support for **Raspbian/buster**, but **mystberry.zip** is available in https://github.com/mysteriumnetwork/nightly/releases/tag/nightly-22072021.

**Comment by AdineVikash** [comment]
**BUG**:
![image](https://user-images.githubusercontent.com/68943180/126637849-ecaecd98-37f7-4fab-a255-6e54c6d3ada6.png)
This was showing in the https://mmn3.mysterium.network/
![image](https://user-images.githubusercontent.com/68943180/126637981-342c4114-234f-4e07-bb50-6c37d704b3f7.png)
This was in node UI.

I was heared about node runners can't change the price anymore in **Testnet 3.0**, but for me the price showing in dashboard and node ui is completely different.

**Comment by azlok21** [comment]
> > > 'aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster' when add-apt-repository ppa:mysteriumnetwork/testnet3 - does this mean we can only install a fresh node as far as the raspberry pi is concerned?
> > 
> > 
> > if your added the testnet3 repository then run `sudo apt-cache policy myst`
> > `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute`
> > Else do `sudo add-apt-repository ppa:mysteriumnetwork/testnet3` `sudo apt-get update` and then run `sudo apt-cache policy myst`
> > `apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+hirsute` and your good to go!
> 
> Thanks - the problem is that add-apt-repository fails because it could not find a distribution template for Raspbian/Buster. E.g. https://stackoverflow.com/questions/62248269/aptsources-distro-nodistrotemplateexception-error-could-not-find-a-distributio
> 
> So I think it's something that needs fixing on the repository end or alternatively have a public list of supported Raspbian systems if it's a case of unsupported distro?

I also have raspbian and have similar problem. Try to add to the file _sources.list_ which is locate in _/etc/apt_ this two rows
```
deb http://ppa.launchpad.net/mysteriumnetwork/testnet3/ubuntu focal main 
deb-src http://ppa.launchpad.net/mysteriumnetwork/testnet3/ubuntu focal main 
```
After that try to do that AdineVikash said.

**Comment by dpellegr** [comment]
Hi,

I had no issues migrating my Docker node 0xf281d61f1d056b42323ad72b3cd75339eb1ebf7e however:
* [mmn3](https://mmn3.mysterium.network) does not categorize properly my Italian residential IP.
* Wireguard is enabled in the webui, but in my case it is not even recognized as an active service.

![Screenshot from 2021-07-22 15-17-46](https://user-images.githubusercontent.com/7815854/126647441-8f63a1d5-8560-4fa8-a1e7-0a5b3b090264.png)

PS. I refreshed mmn3 and now the node is reported offline.

**Comment by AdineVikash** [comment]
> Hi,
> 
> I had no issues migrating my Docker node 0xf281d61f1d056b42323ad72b3cd75339eb1ebf7e however:
> 
> * [mmn3](https://mmn3.mysterium.network) does not categorize properly my Italian residential IP.
> * Wireguard is enabled in the webui, but in my case it is not even recognized as an active service.
> 
> ![Screenshot from 2021-07-22 15-17-46](https://user-images.githubusercontent.com/7815854/126647441-8f63a1d5-8560-4fa8-a1e7-0a5b3b090264.png)
> 
> PS. I refreshed mmn3 and now the node is reported offline.

I got the same problem and it fixed after sometime.

**Comment by jueij** [comment]
Hello,
my node now is twice in the leaderboard, I have no Idea, why.  https://mmn3.mysterium.network/leaderboard   Its the german node , actually on position 2 and 3

**Comment by AdineVikash** [comment]
Because there is no competition rightnow among us, so you will be at lead!

**Comment by jueij** [comment]
I dont think so, it shows different session ammount.

**Comment by AdineVikash** [comment]
> I dont think so, it shows different session ammount.

Do you mean by the different price per GB ? 
If yes, node runners can't set the price anymore in testnet v3 prices and it will be determined by the team.

**Comment by jueij** [comment]
![Unbenannt](https://user-images.githubusercontent.com/87820674/126664217-eef1ee35-09ef-4961-ae39-19a0ef618114.JPG)

**Comment by AdineVikash** [comment]
As I'm already said, it's completely new network and currently open for few people's at this time, so only few nodes upgraded from **testnet 2.0** to **testnet 3.0**

**Comment by jueij** [comment]
I understand, what you mean, but my node is the only one, that do appear twice, thats a bit strange. There are 6 positions now, so 5 nodes, but only mine is showing double.

**Comment by AdineVikash** [comment]
> I understand, what you mean, but my node is the only one, that do appear twice, thats a bit strange. There are 6 positions now, so 5 nodes, but only mine is showing double.

Oh, just now I saw property, does your dashboard shows 2 nodes?

**Comment by jueij** [comment]
no, only one, i even did unclaim my 2.0 node, because I thought, that may be the reason

**Comment by AdineVikash** [comment]
It's not an problem, even I did not unclaim the node from testnet 2.0 and
my node is offline in testnet 2 and online in testnet 3.0

**Comment by jueij** [comment]
Therefore I did mention a bug here. Also, in global leaderboard, i am on position 2, but in the dashboard it shows a "-" only. It should show position 2 there, not a "-"

**Comment by dpellegr** [comment]
> > ...
> > PS. I refreshed mmn3 and now the node is reported offline.
> 
> I got the same problem and it fixed after sometime.

Nope, I waited several hours and nothing happen. Then I rebooted the node and it went fine.

**Comment by AdineVikash** [comment]
> > > ...
> > > PS. I refreshed mmn3 and now the node is reported offline.
> > 
> > 
> > I got the same problem and it fixed after sometime.
> 
> Nope, I waited several hours and nothing happen. Then I rebooted the node and it went fine.

Great 👍

**Comment by movefasta** [comment]
I got an issue after upgrade node to testnet3:
```
Ineligibility reason
Your node is sharing its IP address with another node.
```
Node unclaimed in my.mysterium.network

**Comment by Liten90** [comment]
It is impossible to change the address, writes that it has been changed, but in fact not.
For some reason, all the nodes created new wallets. Although the WEBUI is correct. I can’t change.
![unknown](https://user-images.githubusercontent.com/32055609/126763730-8764b50e-6156-4200-aa14-d96f9266eff2.png)
![unknown2](https://user-images.githubusercontent.com/32055609/126763732-7900dfc0-52b6-49dd-89de-83997ea99b70.png)

**Comment by etherunit** [comment]
@movefasta Could you provide your node identity address?

**Comment by sj64** [comment]
![Screenshot from 2021-07-25 09-35-55@2x](https://user-images.githubusercontent.com/64731653/126891545-8b62e825-03b9-4e16-8a7c-b0857d78b81e.png)

Install of node on VPS went fine, took a while to complete registration but sorted itself out without any intervention from me. testnet3 MMN also updated itself correctly.
Now trying the linux desktop VPN, still stalled with 0 MYSTT, and identity registration error after 15 mins, as shown.

**Comment by AdineVikash** [comment]
Using the testnet3 linux desktop VPN? if yes, you will not have the free MYSTT.

**Comment by sj64** [comment]
ok, so is it recommended to topup, paying with real ETH, despite the warnings?

**Comment by AdineVikash** [comment]
> ok, so is it recommended to topup, paying with real ETH, despite the warnings?

Mostly yes, it's safe but i'm not 100% sure because i'm not topuped yet because of lack of funds in my wallet/pockets.

**Comment by sj64** [comment]
Thanks, but I'll want to wait for a more certain confirmation before paying the transaction fees etc!

**Comment by chompomonim** [comment]
> Now trying the linux desktop VPN, still stalled with 0 MYSTT, and identity registration error after 15 mins, as shown.

Could you try installing newest build?
https://github.com/mysteriumnetwork/nightly/releases/tag/nightly-25072021

**Comment by chompomonim** [comment]
> Using the testnet3 linux desktop VPN? if yes, you will not have the free MYSTT.

You still should have free MYSTT. If not, then this is bug. Your node logs would help.

**Comment by chompomonim** [comment]
> there are NO nodes showing at all with any/no filter. however searching specifically for my own node address lists it, and then I can connect fine (nice animation for the connect btw!).

There is glitch in desktop app. Please set quality to any in settings.

**Comment by chompomonim** [comment]
> Possibly more serious, I have connection set to automatic dns, and dnsleaktest.com shows all dns queries are routed and logged through my VPS host DNS servers, whilst connected to testnet3 through my own VPS node.

Are you using Windows desktop app?

**Comment by AdineVikash** [comment]
> > Using the testnet3 linux desktop VPN? if yes, you will not have the free MYSTT.
> 
> You still should have free MYSTT. If not, then this is bug. Your node logs would help.

Understood rightnow, let me check!

**Comment by AdineVikash** [comment]
> > Now trying the linux desktop VPN, still stalled with 0 MYSTT, and identity registration error after 15 mins, as shown.
> 
> Could you try installing newest build?
> https://github.com/mysteriumnetwork/nightly/releases/tag/nightly-25072021

![Uploading Screenshot_2021-07-26-13-29-49-68_108628a93f2024d8604e0ea3544ef3cb.jpg…]()
How to by pass this?

**Comment by sj64** [comment]
@chompomonim 
Already using nightly: 25072021 desktop VPN
Linux (Elementary 5.1.7 Hera)

Had yesterday already tried setting quality to any without success. HOWEVER today it is running perfectly, with no action on my part (using quality Any). It just seems at several stages there have been delays in full functionality that sorted themselves out without intervention. That is:

Initial node registration
MMN integration
Desktop VPN MYSTT balance
Desktop VPN Node listing

All now working perfectly after delays of an hour or more. Just a complete guess but could it be anything to do with ledger updating on the blockchain, with presumably a very small testnet3 userbase at this point? 

As to DNS leaks: Testing all 4 options through the same UK node (I am in Spain) the results from dnsleaktest.com are:

Automatic:   Node ISP (UK)
Provider:      Node ISP (UK)
System:       My ISP (Spain)
Cloudflare:   Cloudflare (UK)

If you need logs etc. just let me know.

**Comment by AdineVikash** [comment]
> > Using the testnet3 linux desktop VPN? if yes, you will not have the free MYSTT.
> 
> You still should have free MYSTT. If not, then this is bug. Your node logs would help.

installed the testnet3 desktop client. How much min does it take to get my identity registered?

**Comment by AdineVikash** [comment]
> > Using the testnet3 linux desktop VPN? if yes, you will not have the free MYSTT.
> 
> You still should have free MYSTT. If not, then this is bug. Your node logs would help.

installed the testnet3 desktop client. How much min does it take to get my identity registered?

![image](https://user-images.githubusercontent.com/68943180/126978989-8aeb4e77-8e3f-46ba-84f4-ce07c1ff8a80.png)

Waiting for more then 10min.

**Comment by Peter-SovietSquirrel** [comment]
> > Using the testnet3 linux desktop VPN? if yes, you will not have the free MYSTT.
> 
> You still should have free MYSTT. If not, then this is bug. Your node logs would help.

This is an upgrade from 5.0.0-5on Windows to the latest nightly release this shows 0 MYSTT. Previous MYSTT not carried forward.
[main.log](https://github.com/mysteriumnetwork/node/files/6877886/main.log)

**Comment by AdineVikash** [comment]
> > > Using the testnet3 linux desktop VPN? if yes, you will not have the free MYSTT.
> > 
> > 
> > You still should have free MYSTT. If not, then this is bug. Your node logs would help.
> 
> This is an upgrade from 5.0.0-5on Windows to the latest nightly release this shows 0 MYSTT. Previous MYSTT not carried forward.
> [main.log](https://github.com/mysteriumnetwork/node/files/6877886/main.log)

Previous MYSTT will not carry forward once the migration completes?

**Comment by MoralisRubric** [comment]
I am having trouble with updating the Bounty Payout Address.

When I updated the node to MMN3 the Bounty Payout Address was empty, I have tried updating the details but I get an error.


![MMN3_WalletScreenshot-20210726](https://user-images.githubusercontent.com/13920475/126991782-a1a25293-29f3-4c30-a944-8b55db6a30a0.png)

**Comment by jueij** [comment]
With the new update my node dissapeared from the dashboard. If I try to claim it, it tells me, it is already claimed. _"Error
This node has already been claimed. Please visit https://mmn3.mysterium.network/ and unclaim it first."_ But I cant unclaim, because it dont show up in my dashboard. Running on debian.

**Comment by etherunit** [comment]
@jueij You are using an API key from my.mysterium.network or mmn3.mysterium.network to claim your node?

**Comment by AdineVikash** [comment]
> @jueij You are using an API key from my.mysterium.network or mmn3.mysterium.network to claim your node?

I'm sure, for now my.mysterium.network and mmn3.mysterium.network is same rightnow.

**Comment by etherunit** [comment]
@jueij What's your node identity address?

**Comment by jueij** [comment]
> ode identit

0x8a964baba8f5cd7cc5327d6554e1142d7af0541b  and the api key now seems the same in any network, testnet3 and testnet2

**Comment by chompomonim** [comment]
Yes, now mmn2 and mmn3 have same api-key and they will show nodes in both networks. Technically there is only one mmn now, just with two separate addresses ;)

**Comment by sj64** [comment]
Nightly: 25072021 desktop VPN
Node version 0.52.0-1branch-testnet3-b-1
WebUI version 0.4.0
Linux (Elementary 5.1.7 Hera)
Hosted Node: 0x199e0bb4faf2611c4b26ba06dbad850df982e406

Just noticing new issues, not sure if they relate to each other.

https://mmn3.mysterium.network/ has been unreachable for several days now - only displays "default backend - 404". NOT the usual 404 error page, seems to load a default text.

My API keys and MYSTT balances for the same node are different in
Node UI: 4WFPnCm27UfPd0***      2.05MYST
my.mysterium.network: ZJrZw0CJgzBhZ***     15.26MYST

Also in Node UI the bounty payout section displays:
Your bounty report is being generated. Refresh this page in a moment to update.
Refresh sometimes displays the correct layout, but with blank amounts.

Do I need to unify my API key, and if so which one should I use?
As I cannot access testnet3 mmn control panel, I can't verify which key is displayed there either.

**Comment by marvz702** [comment]
Hi Guys,

I updated my node and I was on Step 4 and this is what came up:

sudo apt install myst=0.52.0+1branch+testnet3+b+1+build341085458+focal
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '0.52.0+1branch+testnet3+b+1+build341085458+focal' for 'myst' was not found

So I thought to restart the node and my node is still showing as 0.52 but I got an active connection. My MMN Dashboard though says No Active Services Found and Connection Check is failing.

**Comment by marvz702** [comment]
Hey guys.

Since updating to Node version 0.53.1-1branch-testnet3-b-1 I am no longer getting incoming connections.
Is there an issue or change in the port used by the new version? Previous to the upgrade I have had multiple connections on a daily basis.

Thanks.

**Comment by chompomonim** [comment]
The first beta testing stage is done. Thanks to you guys we have found and fixed quite a few issues. **Thank you** very much! 

Now we're going into second testing phase. There is [Pre-Mainnet beta testing milestone](https://github.com/mysteriumnetwork/node/milestone/61) with couple of scenarios to test. We're putting yet another 5 MYST for those who will test (and report testing results) of at least one of listed scenarios there.
