### ISSUE TITLE
Node UI not responding and Showing Offline

### ISSUE THREAD

**Issue by kabirzohaib22** [mysteriumnetwork/node#3661]
My node suddenly went Offline.
Now i can't access the UI.

Node is Running On RPI 4B (Raspbian 10 Buster)
Node version - 0.52.0
Node ID - 0xc35e91a92d88cfe6692d250268b478e81c3d9f8c

![33](https://user-images.githubusercontent.com/87380999/126693436-16255edd-fed4-405b-b4c6-b4594d452271.JPG)
![44](https://user-images.githubusercontent.com/87380999/126693451-02abfc23-829c-44a5-82fe-777cad024f65.JPG)

**Comment by etherunit** [comment]
@kabirzohaib22 There was a session from Ghana 8 h ago which is 3 h after you have reported an issue on Github. Do you still have any issues with your node? Is it possible to submit your node logs so we can investigate it further?

**Comment by kabirzohaib22** [comment]
> 
> 
> @kabirzohaib22 There was a session from Ghana 8 h ago which is 3 h after you have reported an issue on Github. Do you still have any issues with your node? Is it possible to submit your node logs so we can investigate it further?

yeah, i just checked, i had multiple sessions but it's still showing offline and the UI is just loading, can't access anything. the login page appeared but i couldn't get through.
here i'm attaching the log file.
[node_logs.txt](https://github.com/mysteriumnetwork/node/files/6866929/node_logs.txt)

**Comment by kabirzohaib22** [comment]
it's working now.
thanks
