### ISSUE TITLE
[Mac, bug] User can't connect to any node, multiple errors, One of the pings has error

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3665]
**Describe the bug**
According to user he's always stuck in connecting state.
I can see multiple errors like "One of the pings has error".
Logs:
[mysterium-node 51.log](https://github.com/mysteriumnetwork/node/files/6870494/mysterium-node.51.log)

**Environment (please complete the following information):**
 - Node version: 0.51.0
 - OS: Mac

**Comment by cvl** [comment]
Some more logs:
[mysterium-node 52.log](https://github.com/mysteriumnetwork/node/files/6872910/mysterium-node.52.log)

Apparently, user can connect to nodes if he uses system DNS (versus provider DNS).

**Comment by chompomonim** [comment]
This should be solved with #3681, especially after #3709 will be done. 

We're working on them already. So closing this issue as duplicate.
