### ISSUE TITLE
Testnet3 - residential IP not detected on mmn3

### ISSUE THREAD

**Issue by endosym1** [mysteriumnetwork/node#3668]
**But the status in myst cli is accurate and the docker logs says it is Residential IP:** 
![Screenshot 2021-07-25 at 9 45 47 AM](https://user-images.githubusercontent.com/87921704/126887510-2c00dbc3-e2dc-4112-9c7e-00e480e5f72e.png)

![Screenshot 2021-07-25 at 9 43 19 AM](https://user-images.githubusercontent.com/87921704/126887490-ba2ae5bd-f5cf-4f17-92a4-8099b10bbb4b.png)

**Comment by eugenegoncharuk** [comment]
Not reproducable.
