### ISSUE TITLE
testnet3 - missing options to set service rates and openvpn is gone

### ISSUE THREAD

**Issue by endosym1** [mysteriumnetwork/node#3669]
missing option to set service rates - Price per GB and price per hour

![Screenshot 2021-07-25 at 9 47 30 AM](https://user-images.githubusercontent.com/87921704/126887561-d099827f-0c2b-4add-bc3d-3cbd3a67bf77.png)

**Comment by etherunit** [comment]
@endosym1 OpenVPN is deprecated from UI on Testnet V3. It's a part of the product roadmap (not a bug).
Price is auto-setting ( a * b  where a is basic rate and b is modifier (modifier is not a constant and it changes based on the country), there is no way to set it manually in UI on Testnet V3.
