### ISSUE TITLE
Same node is listed twice on V3 leaderboard

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3671]
Identity: 0x8a964baba8f5cd7cc5327d6554e1142d7af0541b
<img width="1402" alt="Screenshot 2021-07-25 at 10 25 54" src="https://user-images.githubusercontent.com/60128746/126891285-9a794f3a-7d26-48ce-a193-646a37aea0a4.png">

**Comment by untitledlt** [comment]
Not an issue any more. Let's wait for it to come back.
