### ISSUE TITLE
Too much notifications are sent to node runners from MMN if node is in Test Failed state

### ISSUE THREAD

**Issue by eugenegoncharuk** [mysteriumnetwork/node#3673]
There are too much notifications are sent to node runners if MMN in test failed state. Why it is so? Expected that notifications are sent not so often.

<img width="1128" alt="Screenshot 2021-07-26 at 10 36 50" src="https://user-images.githubusercontent.com/60128746/126959934-1c31fee8-50c5-4d24-ab20-b686e95ac5da.png">

**Comment by untitledlt** [comment]
Probably we had some issues with discovery service.
Let's see if this issue comes back.
