### ISSUE TITLE
Node status online and running fine. Dashboard stating "no services found"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3679]
**Describe the bug**
Multiple nodes experiencing an issue where their nodes are working just fine. However, upon checking connection on their nodes they get message that there are no service to be found..

**To Reproduce**
1. Go to MMN2 Dashboard
2. Click on 'Check connection'
3. See error 'No services found'

**Expected behavior**
Check connection should be queued upon clicking the button

**Screenshots**

**Environment (please complete the following information):**
<img width="809" alt="Screenshot 2021-07-27 at 07 34 09" src="https://user-images.githubusercontent.com/84313603/127107054-27135f8e-f37d-4750-ac7f-160882322fa9.png">
<img width="809" alt="Screenshot 2021-07-27 at 07 34 09" src="https://user-images.githubusercontent.com/84313603/127107088-5c139ca4-6770-483f-b073-b4087d0bd217.png">

**Additional context**

**Comment by marvz702** [comment]
Hi Team,

After the update. The main dashboard is no longer being updated and Client Check fails.

I have rebooted my node and there are ongoing sessions any NAT is a Success. I haven't checked if my earnings and data usage is being updated and will compare data with my internal node dashboard.

My info for your reference:
Node ID: 0x2b2a001aeb59e27d28912ad49bf73d0ecb7124a6

OS: Ubuntu Deskop

**Comment by coder-amogh** [comment]
Similar issue...
Node ID: 0xd68f8ce2ff01b22a14a756bb573844557b8fe71c
I have the status as Online but if I click "Check connection" button from the mysterium dashboard I get "No active services found". 
Can anyone tell me how to resolve the issue?

**Comment by JSubelj** [comment]
Similar issue, docker:latest
Node ID: 0xb6d657397b571838bf45d11a91461e781cdaebd9

Have not gotten a successful connection check in a while, also no traffic.

![image](https://user-images.githubusercontent.com/32905940/127115046-b734272f-a4ee-4b18-83d9-53eb428916f3.png)

**Comment by lollapalooza1973** [comment]
Same issue here.
Node is "online", and I also have incoming connections.
Anyway, MMS shows "No services found".

Node ID: 0x641cb8019932b0fc112eeb1c265a4e93811c9086

**Comment by bitcoinbov** [comment]
NODE ID 0x1c45db9acef969d9165a7c4c10bc65342cf483bb

OS Raspbian GNU

**Comment by fatkulnurk** [comment]
Same issue here.
Node is "online", and I also have incoming connections.
Anyway, MMS shows "No services found".

-----

**Node ID:**
0xca8c0aaef075823f20ed947b7c0aeb6bbd2d1e80
**OS:** 
Ubuntu 20.04 LTS	
**Location:**
Indonesia

-----

**Node ID:**
0x0180aaa57950acb474ec7313325e8469a7938567
**OS:** 
Ubuntu 20.04.2 LTS 
**Location:**
France

**Comment by 300Gram** [comment]
Node ID: 0x6d7a8c13e06133135df1412c7a99a82cd7e62d59
Ubuntu 20.04 LTS
Location:  Singapore

**Comment by untitledlt** [comment]
fixed in https://github.com/mysteriumnetwork/my.mysterium.network/pull/109

**Comment by RED163** [comment]
Had to delete my OLD Node cause it went offline after windows installer that was created...was 5.2 now this new not is 5.3 and now says I am not residential...Got no problem as long as I am earning but still

0xf7f1bd2413b135fd83d84795a77856045056f897

India

Windows 10

**Comment by drvvvrd** [comment]
Hi team.

Clean install 0.53.2 - Ubuntu 20
Global bounty not green. Country is - Unknown. On maxmind service showing correct information - Switzerland. Country in NodeUI - unknown. PLZ make something.
Node id - 0x4ed3ec808ca5b6e2c39650ff0d5ad817c5781aa8

**Comment by drvvvrd** [comment]
Hi team.
The same
Clean install 0.52.0 - Ubuntu 20
Global bounty not green. Country is - Unknown. On maxmind service showing correct information - Switzerland. Country in NodeUI - unknown. PLZ make something.
Node ID - 0xd98b6d5ae59da22993ba458a1f3ed718528312ec
