### ISSUE TITLE
Allow users to choose between manual and auto port configuration in Windows installer

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3689]
At the moment we're using port restricted cone nat for docker nodes. This limits some consumers (who's ISP is using symmetric NATs) to connect to such nodes. This is simpler way to configure node but will potentially limit amount of consumers.

Windows installer should allow person to choose which option to choose between:
 - Use port restricted cone NAT (recommended)
 - Use manual port forwarding (for advanced users)

**Comment by Zensey** [comment]
What ports must be mapped ?

**Comment by chompomonim** [comment]
@soffokl could you comment on details so @Zensey could implement such switcher and properly configure myst docker container in installer?

**Comment by soffokl** [comment]
Users should be able to choose a port range for forwarding. We can just recommend using a sane range size like 100 ports. 
It will be good to different ranges for users, so it will be harder to block providers by the single range. 

The docker run command should look like following; 
```
docker run --cap-add NET_ADMIN -p 41100-41200:41100-41200/udp -d --name myst mysteriumnetwork/myst:latest --udp.ports=41100:41200 service --agreed-terms-and-conditions 
```

**Comment by chompomonim** [comment]
@Zensey what is status of this task?

**Comment by Zensey** [comment]
@chompomonim 
mostly done, however there's a problem with setting the port mapping programmatically (through docker API).
