### ISSUE TITLE
Failed to connect to vmsingle.metrics-metric.svc 8429

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3695]
<img width="1073" alt="Screenshot 2021-07-28 at 10 03 57" src="https://user-images.githubusercontent.com/60128746/127278850-9d80f421-5092-4528-b7b6-0948e46e8586.png">
<img width="720" alt="Screenshot 2021-07-28 at 10 04 02" src="https://user-images.githubusercontent.com/60128746/127278874-4e187087-79a9-448e-b6c1-7753499b0639.png">

Sometimes MMN outputs with 503 or loading slowly.

**Comment by eugenegoncharuk** [comment]
Now limit of 4 CPU and 20 Gi of Ram is used for VM single. Should be ok now.
![image](https://user-images.githubusercontent.com/87538/127280707-78fc7e9b-8828-43c8-a454-41584e122f63.png)
