### ISSUE TITLE
MMN node status online vs Grafana test failed

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3699]
**Describe the bug**
There is a clear inconsistency between MMN status and actual status being reported from a single point of truth.
Node: 0x10fcdb03aaa6b0186162c8ae5e9d4e258c5bcf2e, Reported status: Online;

Grafana is reporting: Test failed

https://testnet2-ndiscovery.mysterium.network/api/v3/proposals-metadata?provider_id=0x10fcdb03aaa6b0186162c8ae5e9d4e258c5bcf2e "updated_at":"2021-07-28T08:27:10.680839Z"}]

But on MMN 
Proposals in Discovery
null

**Screenshots**
<img width="682" alt="Screenshot 2021-07-28 at 11 07 38" src="https://user-images.githubusercontent.com/60128746/127287605-caf345ca-fd1d-4898-89bb-ee05be47c9b4.png">
<img width="942" alt="Screenshot 2021-07-28 at 11 09 46" src="https://user-images.githubusercontent.com/60128746/127287689-805c5fd9-c4e9-46ed-9666-f89ee0ba1586.png">

**Environment (please complete the following information):**
 - Node version: 0.52.0
 - OS: Alpine Linux v3.12(docker)/  linux(docker)/amd64

**Comment by eugenegoncharuk** [comment]
Update status nodes scheduled job has been fixed.
@untitledlt also fixed a problem on MMN side - Monitoring was returning 500 if not found and stopped us from trying another Monitoring agent from testnet3 or vice-versa.
