### ISSUE TITLE
Notifications sent for deleted node

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3708]
`NotificationManager` still dispatches alert emails for node which has been manually deleted from my.mysterium.network. 

<img width="1010" alt="Screenshot 2021-07-29 at 10 41 28" src="https://user-images.githubusercontent.com/60128746/127452093-b84fa570-e76a-4365-ad4c-cc3b504dad0b.png">

**Comment by untitledlt** [comment]
should be fixed now
