### ISSUE TITLE
Consumer should not fetch unaccessible nodes

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3709]
We need add detection in node if consumer ISP is using symmetric NAT, in such case consumer app should filter out unaccessible nodes. Also user should be able to enable/disable in config such auto detection.

This is related to #3681 and allow not to show docker nodes with certain configuration.

**Comment by Snawoot** [comment]
Consumer side done, only part on discovery server is remaining. Reassigning to @soffokl
