### ISSUE TITLE
Mysterium node is having issue

### ISSUE THREAD

**Issue by sohailshaikh333** [mysteriumnetwork/node#3714]
**Describe the bug**
Hi team,
My node status is showing online but when I click on check connection it returns me a pop-up "Failed to queue connection". I have tried various things based on the steps listed on this page "https://docs.mysterium.network/node-runners/troubleshooting/#introduction-to-network-troubleshooting"

1. I tried enabling NAT: The NAT status also was appeared success on the node setting page but the node was giving the same message when we click Check connection.
2. Than as suggested by Isaac, I tried port forwarding as well by following steps.
Step a.  Firstly I disabled the nat by updating the service configuration file /etc/default/mysterium-node, In that file I have commented all the lines and just kept the below lines:

DAEMON_OPTS="--nat-port-mapping=false --keystore.lightweight"
SERVICE_OPTS="openvpn,wireguard"

Step b. Manully changed the virtual server setting of router and put the below configurations:
ServerName: PPTP
Protocol: UDP
WAN Port:51820:52075
LAN Port:1723
Static IP: 192.168.2.3

Step c. I checked the ip_forward status as well using the command cat /proc/sys/net/ipv4/ip_forward  and it returned 1

Step d. I ran the command "iptables -P FORWARD ACCEPT" as well incase their is a default firewall.

**To Reproduce**
1. Go to node id - 0x08844b21ce937c464ab9a96d26ffc4ce940f1afe
2. Click on "check connection"
3. See error

**Expected behavior**
Failed to queue connection message will appear

**Screenshots**
![image](https://user-images.githubusercontent.com/20125778/127704680-0e5370ee-818a-46db-8b43-82ddc7ca6296.png)

**Environment (please complete the following information):**
 - Node version: 0.52.0
 - OS: raspbian buster

**Additional context**

**Comment by sohailshaikh333** [comment]
Hi Team,
Any updates.

**Comment by tomasmik** [comment]
Sorry for the delay, we're looking in to it.

**Comment by sohailshaikh333** [comment]
Hi Tomas, no problem I'll wait for your inputs....

**Comment by untitledlt** [comment]
Could someone confirm that this is still happening? I can not reproduce it.

**Comment by sohailshaikh333** [comment]
Yes it is still happening...

**Comment by sohailshaikh333** [comment]
Hello team any updates on it?

**Comment by untitledlt** [comment]
@sohailshaikh333 should be fixed now. Please check let me know if everything is fine.

**Comment by sohailshaikh333** [comment]
Hi Team,
Now on check connection I am not getting the message but when I am trying to connect to the node through mobile app it is not connecting to it and in quality column their is no signal as well. Why is it so? Please check this issue and let me know if I need to perform any steps to resolve it.

Thanks,
Sohail
