### ISSUE TITLE
Problems in setting payout beneficiary in testnet3 NodeUI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3717]
Getting error while setting new beneficiary in NodeUI.

Message: 
![Screenshot from 2021-08-01 08-55-41](https://user-images.githubusercontent.com/153896/127760960-0be921f0-f72e-4d2b-9368-3e7c972afe16.png)

Node version 0.53.0-1branch-testnet3-b-1
WebUI version 0.4.0

**Comment by tomasmik** [comment]
This appears to be an issue with the build for testnet3 PPA. It's still pointing to the old MMN (mmn3.mysterium.network), which is long gone. Will update the PPA releases.

**Comment by untitledlt** [comment]
related: https://github.com/mysteriumnetwork/node/issues/3670
