### ISSUE TITLE
Wrong MMN URL in NodeUI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3718]
mmn3.mysterium.network is not accessible anymore but WebUI version 0.4.0 is still pointing into it.

**Comment by eugenegoncharuk** [comment]
Not relevant anymore. changed back to my.mysterium.network.

**Comment by tomasmik** [comment]
Testnet3 PPAs have been rebuilt to no longer include mmn3.mysterium.network
