### ISSUE TITLE
Help Wanted! Which port should i open?

### ISSUE THREAD

**Issue by jimgreen2013** [mysteriumnetwork/node#3726]
I run the node on my vps in a data center, i'm so confused about how to config my firewall, please help and thanks in advance

**Comment by tomasmik** [comment]
The issue you're describing is not really clear enough to give you a clear answer.

Have a look at our docs:
- [Port forwarding]( https://docs.mysterium.network/node-runners/troubleshooting/#port-forwarding)
- [WireGuard service port configuration](https://docs.mysterium.network/resources/faq/#wireguard-service-port-configuration)

You can also search the docs for any additional information needed. You can also join our [community discord ](https://discord.com/invite/n3vtSwc)to get help.
