### ISSUE TITLE
Nodes not displaying specific countries on MMN. Location Unknown

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3735]
**Describe the bug**
Nodes not displaying specific countries on MMN dashboard. Location Unknown is being displayed.

Paramba- 0xe974018de1605a366f9de33c74d32599009d7701  ——> USA
ABCMine- 0x65ee793880ca381ae3c7d00f09abfcaf2e954a5b ——> Russia
Sonu Adhikari- 0x3baabcea9723f7db82a9be1f1ce53021568d8ac4 ——> India

**To Reproduce**
1. Go to 'MMN'
2. See on dashboard
3. See error

**Expected behavior**
Dashboard should be displaying respective countries. 

**Screenshots**
Visual Example:

![2021-08-04 17 05 43](https://user-images.githubusercontent.com/84313603/128215198-acc3a716-c57a-4e8f-b366-179e3b44daf0.jpg)

**Environment (please complete the following information):**
OS: Ubuntu 20.04.2 LTS
Architecture: linux/amd64
Node version: 0.52.0

OS:
Alpine Linux v3.12(docker)
Architecture:
linux(docker)/amd64
Node version:
0.53.1

Possibly other environments as well (will request other users with same issue to include their respective environments).

**Comment by isaackielma** [comment]
@untitledlt Could you please take a look at this issue? Maybe you could help us 😊

Thank you, we appreciate your great work and skills! 🙏

**Comment by s89b96** [comment]
Hello I have the same issue

Node : 0x0cc0f33da8568888f1f350857c2396f466989592

Recently set up my PI node 
Location is showing as Unknown ( My location is Hong Kong )
Last seen time is incorrect
IP address is being shown with N/A on top of it - doesn't recognise as Residential
Connections amount are also low
![Screen Shot 2021-08-05 at 3 55 15 pm](https://user-images.githubusercontent.com/84949471/128313707-9cf7cd37-9c95-4ea2-91e0-1c661f8b5a0b.png)

**Comment by gantaaman007** [comment]
hello i have the same issue 
here is the screenshot of it 
my location is india and my node id: 0x8f58ba869ed672daaa06357a425c2dfcae9544a4
<img width="941" alt="Screenshot 2021-08-05 134709" src="https://user-images.githubusercontent.com/88482287/128317152-19a34a9d-e4ae-424f-af1e-121ab7bf6503.png">

**Comment by dkmatthew** [comment]
Just started second node 0xfc739fea45be18917ed1a566d852dbf95fff59af on residental IP from RU country and have same problem
In https://www.maxmind.com/en/geoip-demo
I Have right country RU
and in https://www.ip2location.com/demo
i have right ISP IP
In MMN i have "Unknown" country and "N/A" type of address
Thats why I dont display in dVPN app tu users and have no any sessions now

**Comment by isaackielma** [comment]
0x1b4d91b47fc5512cadc08ac79b1f8a842bbd61b6 UK

**Comment by isaackielma** [comment]
0xd0649d6fbea6a5b87d9ab5db0194aa1bf2d86376 USA

**Comment by untitledlt** [comment]
> 0xd0649d6fbea6a5b87d9ab5db0194aa1bf2d86376 USA

are you sure it's USA? i'm getting United Kingdom

**Comment by dkmatthew** [comment]
0x78b6de33916e0b1ae3c2bc7982b42ae997f4d2b7

**Comment by isaackielma** [comment]
0x17df52660c8e05517f1435f87a3ae7ad1bd19b64 - Portugal

**Comment by AvidZero** [comment]
0x33683b06cf122fe263024efce7ed65ae82d847a7 - USA
Location is showing as Unknown 
Last seen time is incorrect
IP address is being shown with N/A on top of it.. I am not recognized as a residential location
Position is also not shown

**Comment by isaackielma** [comment]
0xbf0853688742f4881a26f887289b4e168d0d3a0d - Canada

**Comment by pandariafx** [comment]
Germany, 0x8402d5c69ea602c484c4f7d211fcb4b2ba7ae1ed
![Screenshot 2021-08-11 201620](https://user-images.githubusercontent.com/33103561/129081920-d9a1997f-f634-48de-8e10-ed5bd2aded98.png)

**Comment by isaackielma** [comment]
1 - 0x4ed3ec808ca5b6e2c39650ff0d5ad817c5781aa8
2 - 0x2ee2e5274860ff0d545a5d06d9a4200da36f209a
3 - 0x3bd842b2912937731964a18c60ac1c6a05b8f85e

Global bounty not green. Country is - Unknown. On maxmind service all 3 nodes from Switzerland. Country in odeUI - unknown. PLZ make something.

**Comment by gnatx1** [comment]
OS: Raspbian-buster
Architecture: linux/aarch64
Node version: 0.53.2

![Screenshot_20210812-165925_VNC Viewer](https://user-images.githubusercontent.com/86992232/129281383-29690293-86fe-4aa1-a13a-b830fbb88149.jpg)

**Comment by barneyvaughan** [comment]
I'm getting similar - just Unknown and my IP isn't getting tagged as residential (which is was).

0x4b749cb905f6db38d706edf94c15e263e456842b - GB (United Kingdom)

**Comment by ayoinc** [comment]
I'm facing the same issue; my residential tag is not on and Country which is UK is not showing.

**Comment by epzilla325** [comment]
Had been jumping from a device to a device. First had it working. Now the country unknown, last seen 12 hours ago, the latest version.

0xfc03f899be0f14552182f58e713edb2792d969f3 - NL

**Comment by mcsebrad** [comment]
I'm getting - Your node's IP addresses is not residential.  - 

Country isn't correct. 

0x29406e28e7e9ddaba2fa935f7202f5845d4d9ea5 - USA - residential

**Comment by ayoinc** [comment]
0xc51e2fe2eeda78e65601ed89a181813b66b9c5d4
United Kingdom

Please fix as it's showing as unknown at the moment.

**Comment by ayoinc** [comment]
0xc34b4dea6b62b5b065da7959958b69eb339a19a5
United Kingdom (Residential)
Alpine Core
Country is showing as unknown.

**Comment by breezytm** [comment]
0xa971e8ac67360916367aa2ee6ce552c9de3e2b59 - United States (Residential)
Thanks.

**Comment by Schifer** [comment]
Ineligibility reason shown as "Your node's IP addresses is not residential".

![129525056-18479400-52c5-445f-bdb5-214cf2e00060](https://user-images.githubusercontent.com/86069056/129525546-5639eab8-601c-478e-b3b5-759c9caa91c7.png)

My Node Identity : 0xac4f83b9f37fcc8716c9a861723fcd8fa12d486a - INDIA - residential

**Comment by drvvvrd** [comment]
![2021-08-16 103908](https://user-images.githubusercontent.com/88892903/129535887-2bd90084-113a-4c74-b211-f4a3a8178727.jpg)


Node ID:
0x3c0cd01d70db72771e78fd670c52359742b9e4cf
0xd98b6d5ae59da22993ba458a1f3ed718528312ec

**Comment by barneyvaughan** [comment]
Just wondering if there's any info on how this effects the nodes visibility/usability for the network? Will it be impacting the ability to earn?

**Comment by drvvvrd** [comment]
> Just wondering if there's any info on how this effects the nodes visibility/usability for the network? Will it be impacting the ability to earn?

Doesn't affect performance in any way. There is a node in the list for connecting.

**Comment by drvvvrd** [comment]
> Just wondering if there's any info on how this effects the nodes visibility/usability for the network? Will it be impacting the ability to earn?

Old nodes are being checked and this is reflected for example: 3 minutes ago. And new ones, for a strange reason, do not get tested online.

**Comment by breezytm** [comment]
if there isn't a fix for this bug yet, why not allow an override. As a node runner I can select my location and whether or not my IP is residential or not.

**Comment by isaackielma** [comment]
0xaaaab806b9d5de8c411ddff1e4fe714a0e6ebc02 - Portugal

**Comment by isaackielma** [comment]
0x1c3a912c994700ed358caf706daa501b4c128075 - India

**Comment by stavinlawrence** [comment]
Yes i have the same issue : Node id is 0x7c48148d262d88f410e29cf754d35cab733ff15d and location is NJ, USA

**Comment by mema777** [comment]
0x3b2b4a693f1375e648c7a35982e2788bb84b859b - Czechia

**Comment by breezytm** [comment]
0x989e30961c57f8e1b8e760b8c7c9685519480886 -USA - Residential

My second node.

**Comment by isaackielma** [comment]
0x7c48148d262d88f410e29cf754d35cab733ff15d and location is NJ, USA

**Comment by cenasri** [comment]
Ineligibility reason shown as "Your node's IP addresses is not residential".

![129525546-5639eab8-601c-478e-b3b5-759c9caa91c7](https://user-images.githubusercontent.com/84898843/129837134-c6b726f2-a972-4800-8e75-96f4b81d9a33.png)


My Node Identity : 0x8c9a71e1a30df4ca8e8e3b51a16f534af37f04bf   - INDIA - residential

My Node Identity : 0x1c3a912c994700ed358caf706daa501b4c128075 - INDIA - residential

**Comment by drvvvrd** [comment]
Good afternoon. I found the reason for the error. This error only applies to new registrations. Namely, there is no automatic registration.
Here's what's in the logs of the node itself: 

2021-08-18T09:29:57.909 INF core/discovery/discovery.go:239          > Identity 0x3236e58d95b88947a5c71293313c0594809d2849 not registered, delaying proposal registration until identity is registered
2021-08-18T09:29:57.910 INF core/discovery/discovery.go:180          > Waiting for registration success event
2021-08-18T09:29:57.920 INF session/pingpong/hermes_promise_settler.go:158 > Provider {0x3236e58d95b88947a5c71293313c0594809d2849} not registered, skipping
2021-08-18T09:29:57.935 INF identity/registry/provider_registrar.go:185 > Provider "0x3236e58d95b88947a5c71293313c0594809d2849" not registered on BC, will check if elgible for auto-registration
2021-08-18T09:29:57.936 DBG config/config.go:196                     > Returning default value chain-id:5
### **2021-08-18T09:29:57.936 INF identity/registry/provider_registrar.go:216 > provider "0x3236e58d95b88947a5c71293313c0594809d2849" not eligible for auto registration, will require manual registration**

But despite this, the node is visible to clients and you can connect to it. In the client, the node is located in the correct country, and so on. 
In addition to this, the system periodically does not check when the node was last online (parameter in MMN "Last seen")

**Comment by untitledlt** [comment]
@eugenegoncharuk this is k8 queued jobs related

**Comment by drvvvrd** [comment]
Now in log:

ERR mmn/mmn.go:95 > Failed to register identity to MMN : server response invalid: 403 Forbidden (https://my.mysterium.network/api/v1/node)

**Comment by isaackielma** [comment]
0x7de3cab9b70a3308de07cddd22c383538bb4d09b - USA

**Comment by drvvvrd** [comment]
0x4ed3ec808ca5b6e2c39650ff0d5ad817c5781aa8 - Switzerland

0x2ee2e5274860ff0d545a5d06d9a4200da36f209a - Switzerland

0xd98b6d5ae59da22993ba458a1f3ed718528312ec - Switzerland

0x3236e58d95b88947a5c71293313c0594809d2849 - Italy

0x34a510fca5378b2e17e9b4bc5043a37aeaa298c6 - Germany

0x33745ddbc5a724e2e21b83a87ee58f2e550a2550 - Netherland

**Comment by drvvvrd** [comment]
After executing the command  systemctl restart mysterium-node.service on the MMN Dashbord IP updated to the unoriginal 172.69.109.19
After 2nd restart - 172.69.109.21
Country - Unknown
IP type N/A
Node ID - 0xd98b6d5ae59da22993ba458a1f3ed718528312ec

**Comment by Fajo83** [comment]
Hello there. I had some residential bounty issues on a fresh node.

Node ID: 0xbae927713b89317760ee703787403b33898067b1
Country: Netherlands / Unknown
Version: 0.53.2

System: Proxmox / Windows 10 Pro 21H1 - Docker Desktop - WSL 2 Ubuntu 20.04.

**Comment by drvvvrd** [comment]
Same

0x1a8bdb365141137c7c8cfe10defee5e79cb635f7

**Comment by isaackielma** [comment]
0x7de3cab9b70a3308de07cddd22c383538bb4d09b - USA

**Comment by ayoinc** [comment]
0xb05f707864bfbf96e6e02535919eaba7f9e84a43 - United States

Not generating Country

**Comment by eugenegoncharuk** [comment]
According to the latest fixes "Country" and "IP type" should appear in your dashboard.
Checked for a bunch of them and now data exist.
