### ISSUE TITLE
kill switch for Linux

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#374]
using `iptables` implement kill switch for Linux, as part of firewall module.

**Comment by tcharding** [comment]
Is this really within scope?  For Linux users at least it may be better to let them handle this themselves.  Perhaps we could document the benefits of having a kill switch but if we are trying to 'do one thing and do it well' then perhaps we should leave this to the user.

**Comment by zolia** [comment]
it should be dependant on how you run this. @tcharding, my thoughts were the same, but it looks there are users who would not be able to do it themselves. There at least should be an option to set this switch arbitrary. For example, users running mysterium from desktop application might want to see such flag.

**Comment by zolia** [comment]
This is implemented already thorough firewall rules support on node.
