### ISSUE TITLE
[windows, bug] user getting disconnected after 20-30 seconds after connecting

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3772]
**Describe the bug**
User connects to India provider, and gets disconnected after 20-30 seconds after connecting.
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6974219/mysterium-node.log)

Other countries he cannot connect at all. Logs:
[mysterium-node-2.log](https://github.com/mysteriumnetwork/node/files/6974220/mysterium-node-2.log)

**Environment (please complete the following information):**
 - Node version: 0.51.0
 - OS: [e.g. raspbian buster, debian 10]

**Comment by chompomonim** [comment]
We did significant changes in NAT traversal logic which are going to be included in testnet3 node (currently available to test in [nightly builds](https://github.com/mysteriumnetwork/nightly)). We apologise for inconvenience, but for this temporary network migration period we're able to debug and investigate only conductibility issues for testnet3 clients.

The good news is that there is big chance, that issue for this user is already solved.

**Comment by cvl** [comment]
Huh?...
