### ISSUE TITLE
Payment was not fully transferred.

### ISSUE THREAD

**Issue by Vineet7805** [mysteriumnetwork/node#3776]
Hi,

I have received my first payment this month. Around 3500MYST was deducted but only 130MYST was transferred to my ETH account. My node ID is 0xb990db35369b28182b18c71f0b7252f11597e368.

![image](https://user-images.githubusercontent.com/12422357/128758673-733a6c3c-dc65-488b-8199-ab7d54767dde.png)

Please let me know what's going on?

Thanks

**Comment by chompomonim** [comment]
Please contact our support via help_at_mysterium_dot_network and we'll debug your issue. Such issues should be solved case by case.
