### ISSUE TITLE
Test macOS dVPN app upgrade for user who have `> 1 MYSTT`

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3777]
This scenario is for users who have topuped his dVPN app balance using our CoinGate (on testnet2). 

1. Topup your dVPN app balance using BTC, LTC, ETH, MYST or other supported cryptos (could be done a while ago, your current balance should be more than 1 MYSTT).

1. Download newest testnet3 app (.dmg file) from [https://github.com/mysteriumnetwork/nightly/releases/latest](https://github.com/mysteriumnetwork/nightly/releases/latest) and install it.

1. Launch the app, go via onboarding steps and check your app balance, it should remain the same as before upgrade.

---------- 
**NOTE**: After finishing this scenario please post a comment above (if all was ok, please also give us know about that).

**Comment by vkuznecovas** [comment]
Works fine, see https://testnet3-hermes.mysterium.network/api/v1/data/consumer/0x37d8b3bcfda828b159a878074ee27c126b9225e9
