### ISSUE TITLE
Test exit node migration into pre-mainnet (a.k.a. testnet3)

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3778]
# Scenario to test

1. Migrate your node into `pre-mainnet` (look at instructions provided below)
1. Open NodeUI in your browser (http://[your_ip]:4449 and finish onboarding (your node identity will be registered in on Matic Mumbai chain).
1. Ensure that you node identity didn't change. It should remain the same as in testnet2.
1. Recheck service price (e.g. for WireGuard). It should be set automatically (you should be not able to change it).
1. Recheck beneficiary (a.k.a. payout address) address in NodeUI and in [MMN](https://my.mysterium.network/user/payments). It should remain the same as you had before upgrade (in testnet2).
1. In NodeUI try changing payout address into new one. This should be done instantly (even when your node balance is zero).
1. Recheck [MMN](https://my.mysterium.network/user/payments) to ensure that new address is changed there as well.

# Migration instructions

##  How to update your Docker node:

1. Pull the testnet3 node image: 
  `docker pull mysteriumnetwork/myst:testnet3`

1. Delete the container that is already being used for running node: 
  `docker rm -f myst`

1. Follow the running a docker node guide (https://docs.mysterium.network/node-runners/setup/docker/) to start a new container using `:testnet3` tag.

##  How to update your Linux node:

1. Add the repo:
  `sudo add-apt-repository ppa:mysteriumnetwork/node-pre`

2. Update after repo change:
  `sudo apt-get update`

3. Update the cache policy:
  `sudo apt-cache policy myst`

4. Upgrade Mysterium node:
  `sudo apt upgrade myst`

##  How to update your RPi node:

In `/etc/apt/sources.list` add source `deb http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu focal` 

`cat /etc/apt/sources.list`

Uncomment line below then `apt-get update` to enable `apt-get source`

```
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
#deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu focal main
```

Remove unattended-upgrades: 
`sudo apt-get -y remove unattended-upgrades`
`sudo apt-get update`
`sudo apt-cache policy myst`
`sudo apt install myst=<Myst candidate version>`

---------- 

**NOTE**: After finishing this scenario please post a comment above (if all was ok, please also give us know about that).

**Comment by vkuznecovas** [comment]
The migration works OK.

However, I was not able to set my beneficiary address on a fresh testnet2 install in mmn. It would get set in web ui, the on chain settlement would pass, but MMN was not aware of the change.

**Comment by MoralisRubric** [comment]
What is the current <Myst candidate version>?

**Comment by MoralisRubric** [comment]
The migration went well, once the launchpad was updated to get the current build number - would be great If you could publish this info in real-time on updating nightly on GitHub.

I still cannot see the Bounty Payout Address, which still was an issue in the previous nightly builds and no comments were made when I reported it the first time.    I have not attempted to try and change or add Bounty Payout Address, and don't intend to as I do not know what the issue is or why it occurred or that Mysterium, on the face of it, doesn't seem that bothered about it either for the time being.

**Comment by creotiv** [comment]
Migration passed ok.

**Comment by MoralisRubric** [comment]
Migration seemed to have been successful with no big issues.   Did have an issue with Bounty Payout Address not displaying, so I changed the setting to update the address with no issues and with low MYST.

**Comment by GoZippy** [comment]
PASS ->1) Migration after update ppa was painless - did not need to update cache policy (but did after update). 
Using Ubuntu 21.04   5.11.0-31-generic
Note: I used systemwide update and upgrade and was updated to new kernel in the process as well...

PASS -> 2) appears updated

PASS ->3) node name remained same

PASS ->4) confirmed

PASS ->5) confirmed no changes to MMN or NodeUI ID or Beneficiary address - looking good

*** FAIL ***->6/7) from nodeUI - edited Bounty Payout Address with new ETH wallet address - Red alert box, bottom right corner, no text just a narrow red alert slide in animation on bottom right corner screen with white x - remained for 20 sec or so and disappeared. ... Went to MMN to verify - no update was made on MMN still showing old bounty address.
Reading docs more to check if I missed something. Update address on NodeUI failed to update NodeUI nor send to MMN from what I see but no log or error display so hard to know what happened without digging withd devtools and such for now.

**Comment by chompomonim** [comment]
> *** FAIL ***->6/7) from nodeUI - edited Bounty Payout Address with new ETH wallet address - Red alert box, bottom right corner, no text just a narrow red alert slide in animation on bottom right corner screen with white x - remained for 20 sec or so and disappeared. ... Went to MMN to verify - no update was made on MMN still showing old bounty address.
> Reading docs more to check if I missed something. Update address on NodeUI failed to update NodeUI nor send to MMN from what I see but no log or error display so hard to know what happened without digging withd devtools and such for now.

What is you current node version?
If it is not `0.60.2` could you update it (via `apt update; apt upgrade`) and try changing payout address one more time?
