### ISSUE TITLE
Test fresh testnet3 node installation on Ubuntu Linux

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3780]
## Scenario to test

1. Add the repo:
`sudo add-apt-repository ppa:mysteriumnetwork/node-pre`

1. Update after repo change:
`sudo apt-get update`

1. Update the cache policy:
`sudo apt-cache policy myst`

1. Install Mysterium node:
`sudo apt install myst`

1. Open NodeUI in your browser (http://[node_ip]:4449) and finish onboarding process. You should see **WireGuard** service be up and running. 

   For those who are running mysterium node in data centers you can use our CLI  to setup the node:
    - `$ myst cli`
    - `» identities list`      # this will show your identity
    - `» identities unlock [your identity]` # you need to unlock identity before using it
    - `» identities register [your identity]` # you need register your identity, must be done only once
    - `» service start [your identity] wireguard` # this will start wireguard service
    - `» service list`           # if you see ID of your running service then congrats, you're mysterium node runner
 
1. Download dVPN desktop or mobile app from our nightly builds (look for .apk, .exe or .dmg): https://github.com/mysteriumnetwork/nightly/releases/latest and try establishing connection to your own node. 

DON'T FORGET: you have to be in separate networks (e.g. node on local WIFI and mobile phone using 4G) for successful connection.

---------- 

**NOTE**: After finishing this scenario please post a comment above (if all was ok, please also give us know about that).

**Comment by Peter-SovietSquirrel** [comment]
OS: Ubuntu 21.04
Install and running fine and was able to connect and browse.

$ node cli should read $ myst cli
on install an identity was already crated so maybe >>identities new is not necessary.

**Comment by Jayto1** [comment]
OS: Ubuntu 20.04 
Host Enviroment: VirtualBox 6.1.26 on a Windows 10 Computer

**Comment by vkuznecovas** [comment]
Tested via datacenter, works fine :)

**Comment by creotiv** [comment]
Tested. Works fine.

OS: Ubuntu 20.04
Mobile App: 0.1.120

**Comment by etherunit** [comment]
Ubuntu 20.10 x64

Traffic shaper is jump to 0.005 MB/s after page refresh.
<img width="386" alt="Screenshot 2021-08-17 at 15 10 54" src="https://user-images.githubusercontent.com/60128746/129724139-d06c4807-bcb2-40fa-bd61-c2f63cb65d59.png">

Connection works fine.

**Comment by Jayto1** [comment]
> Ubuntu 20.10 x64
> 
> Traffic shaper is jump to 0.005 MB/s after page refresh.
> <img alt="Screenshot 2021-08-17 at 15 10 54" width="386" src="https://user-images.githubusercontent.com/60128746/129724139-d06c4807-bcb2-40fa-bd61-c2f63cb65d59.png">
> 
> IP type: N/A
> County: Unknown
> Node is registered.
> <img alt="Screenshot 2021-08-17 at 16 09 05" width="1426" src="https://user-images.githubusercontent.com/60128746/129731289-8e3546cc-6548-43d2-8e66-ee24a3e7d035.png">
> 
> Connection works fine.

Check out [](https://github.com/mysteriumnetwork/node/issues/3814)! I opened an issue for this already :)
