### ISSUE TITLE
Test client sorting in a real environment 

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3782]
We've added BC client sorting to:
* Node
* Transactor
* Hermes

**Node**:
* [x] Test that if two clients are added and ones goes down that, we resort the list of clients and use the one that is still up.

**Transactor/Hermes**:
* [x] Test that if two clients are added and ones goes that, we resort the list of clients and use the one that is still up.
* [x] Test that if one node falls behind in blocks, we start using another node and continue to use it over the one that is behind
  * [x] Check that after changing the clients transactions start to work again
  * [x] Nonces should be issued without actually going forwards or backwards

**Comment by GoZippy** [comment]
Please provide verbose instruction on desired steps for test

**Comment by tomasmik** [comment]
> Please provide verbose instruction on desired steps for test
Sadly this is impossible for the community to test.

**Comment by tomasmik** [comment]
Tested with a broken matic node which doesn't sync - works.
