### ISSUE TITLE
Test that affiliates still work

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3786]
Affiliates were moved to the sidecar of transactor.
* [x] Afiiliates can be created and campaigns can be added
* [x] Can register with affiliate code
* [x] Affiliate rewards are submitted to the BC
* [x] Affiliates can claim their rewards

**Comment by chompomonim** [comment]
I have tried to test in both mobile and desktop apps. On mobile app there is no way to enter referral code. On mobile app entering code doesn't work.

**Comment by tomasmik** [comment]
There is a slight problem. I dont think we can use the same smart contract in both networks. We should probably deploy new contracts for testnet3.

**Comment by chompomonim** [comment]
Now mobile app is allowing to enter referral code and free MYSTT are visualized properly in the app.

As affiliate partner I can't login using affiliate.mysterium.network, getting 'wallet data not known' error. Is it accepting only testnet2 affiliates?

**Comment by tomasmik** [comment]
>  Is it accepting only testnet2 affiliates?

Yes. It will start accepting testnet3 once we move to the new network, so probably next week. Unless you think there is a reason to create two websites. Dont think we want to spend more time here.

**Comment by chompomonim** [comment]
One website it should be.

**Comment by tomasmik** [comment]
Tree was updated from testnet3: https://polygonscan.com/tx/0x43d9c10b6821e6fbd4d569a7136663966bd44f08dd73d46f13302929455d5bdc

**Comment by chompomonim** [comment]
I went via full flow (create affiliate -> create code -> apply code in mobile app -> see earnings in affiliate dashboard -> claim earned tokens) and it is working.
