### ISSUE TITLE
Provider should auto settle on testnet3 when he reaches 1 myst of earnings

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#3789]
Provider should auto settle on testnet3 when he reaches 1 myst of earnings.

# Scenario to test

1) Start a service on testnet3.
1) Reach 1 myst in earnings.
1) Check if settlement occured.

Settlement info can be found in the following way:

1) Open hermes for the provider: 
https://testnet3-hermes.mysterium.network/api/v1/data/provider/0x37dc82ec9f05dbb349c32348e745fe6dcdfbe1f5.
1) Copy the beneficiary on chain 80001:
<img width="550" alt="Screenshot 2021-08-13 at 10 15 39" src="https://user-images.githubusercontent.com/18392269/129319246-e0afe0c5-e1c8-4aae-981a-4d3c9e79cc90.png">
1) Transaction should be visible on https://mumbai.polygonscan.com/address/0x8d50743368aCA2Fe4Ff1F8642CC8C58DC1e62B3F

**Comment by chompomonim** [comment]
The interesting fact is that settlement amounts are quite random. Here is beneficiary address of one of testing nodes: https://mumbai.polygonscan.com/address/0x2faeCe2f70a4c8f40DA47D38F4b6b30E9F59f228#tokentxns

**Comment by vkuznecovas** [comment]
> The interesting fact is that settlement amounts are quite random. Here is beneficiary address of one of testing nodes (identity: 0xd7afef28c470129f9792f29761d39cee5ec49995): https://mumbai.polygonscan.com/address/0x2faeCe2f70a4c8f40DA47D38F4b6b30E9F59f228#tokentxns

https://github.com/mysteriumnetwork/node/pull/3773
Old nodes are affected.

**Comment by vkuznecovas** [comment]
Tested with provider 0x0533b886ef7ddd4d2c3da9c212e81bf01e71085a

Here are the channel's transactions:
https://mumbai.polygonscan.com/address/0xCc5A61770343F38A6d2B9a7990B36CB2E107A002#tokentxns

Settled when myst earnings reached 1, transferred ~0.8(after fees) to the channel

**Comment by chompomonim** [comment]
I can confirm that after latest upgrade my node is also doing settlements in proper regularity.
