### ISSUE TITLE
[windows, bug] user getting disconnected after 20-30 seconds after connecting

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3791]
Reopening: https://github.com/mysteriumnetwork/node/issues/3772
Please do not close unresolved issues.

**Comment by chompomonim** [comment]
Without logs from testnet3 app this is not actionable issue. Why to have such issues opened if we can do nothing with them?

**Comment by cvl** [comment]
I'd suggest to keep all issues, as it's quite hard to catch them.
Then close this if this is fixed in testnet3.

Otherwise we should close all issues prior to testnet3 and expect them not to come up anymore.

Btw, is there are huge node refactor in testnet3? Afaik it's only payments (matic) integration?

**Comment by chompomonim** [comment]
I disagree with keeping issues for very long time, especially those which are very rare. It is almost impossible later to reproduce them so they become not actionable.

In terms of testnet3 there are couple of main fixes:
- polygon (matic) integration
- automagic pricing  --> no more manually set prices with insane numbers
- NAT traversal refactoring --> should solve many connectivity issues
- couple of small, less significant changes

**Comment by cvl** [comment]
Do you plan to close just this issue, or all the other issues prior to testnet3?

If just this one, I can keep the record internally for this one.

**Comment by chompomonim** [comment]
Only issues we can't reproduce and which most probably are fixed. For now only this issue.
