### ISSUE TITLE
 Data transferred 0 B Sessions 0

### ISSUE THREAD

**Issue by mass34** [mysteriumnetwork/node#3802]
0x2e11cdd2eb306a5de2aaa2c36581c724ec5c08bb

Availability
347h / 744h

Active services
Wireguard

Per hour: 0.0004341

Per GB: 0.0723503

Residential bounty
0.0000 MYST / $0
Position
950 

Online
Germany
Last seen
2 minutes ago
Version
0.52.0 
"You're all set!

Thank you for participating in Mysterium bounty program. Payments are in MYST and sent out at before the 7th day of each month. "

**Comment by chompomonim** [comment]
I believe there maybe network configuration complications. Neither our monitoring agent nor network users can't connect to your node. 

What is your node setup? Windows? Linux? Docker? 

Could you upgrade to latest version of node and check if this will help?

**Comment by mass34** [comment]
Ubuntu 20.04

For what reason migrating a new address?
Saved copy of 31.07.2021
was 0x2e11cdd2eb306a5de2aaa2c36581c724ec5c08bb
became 0xd384dc172ccd935f99ef1b7279ec0159ee14b90b
How is that?

**Comment by chompomonim** [comment]
I can see both your nodes are up and have different IP addresses. It looks that that are two separate instances, why you think that address of your node was migrated? 

Our monitoring agent is failing to connect to your node. I also tried to connect from android app and also failed.

Could you upgrade to v0.60? We significantly updated NAT traversal mechanism there, it may help your node to become connectable.

**Comment by etherunit** [comment]
@mass34 Please try to update your node as we have done some significant changes there.
I'm closing this issue for now.
Feel free to reopen it in case you still have a problem.
