### ISSUE TITLE
[android, bug] Can't access /proc/net/route

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3804]
**Describe the bug**
User sent diagnostics report, I can see many errors like 
write udp [::]:40992->239.255.255.250:1900: sendto: operation not permitted
https://testnet2-location.mysterium.network/api/v1/location -> 64:ff9b::5fd8:cce8 error="failed to get default gateway: Can't access /proc/net/route

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6990360/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.51.0
 - OS: Android

**Comment by soffokl** [comment]
This was fixed already, please use the latest version.

**Comment by cvl** [comment]
Thank you!

**Comment by cvl** [comment]
@soffokl what version was this included in? I get same error in node 0.53.2

**Comment by soffokl** [comment]
Is there something broken and not working or this is just a complaint about logs?

**Comment by cvl** [comment]
It looks like it's just a complaint in the logs as far as I can see.

Still waiting for the feedback from user who sent report, assumingly for a reason.

**Comment by cvl** [comment]
x

**Comment by cvl** [comment]
x
