### ISSUE TITLE
Ineligibility reason shown as "Your node's IP addresses is not residential".

### ISSUE THREAD

**Issue by Schifer** [mysteriumnetwork/node#3805]
![image](https://user-images.githubusercontent.com/86069056/129525056-18479400-52c5-445f-bdb5-214cf2e00060.png)

My Node Identity : 0xac4f83b9f37fcc8716c9a861723fcd8fa12d486a - INDIA - residential

**Comment by untitledlt** [comment]
@eugenegoncharuk this is k8 queued jobs related

**Comment by untitledlt** [comment]
should be fixed now
