### ISSUE TITLE
[android, bug] Can't access /proc/net/route

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3812]
Reopening https://github.com/mysteriumnetwork/node/issues/3804

Fix was merged into master on 24 Jun, when 0.51.0 was released in 2 Jul.
Also I can see the same error on 0.53.2

**Comment by soffokl** [comment]
can't you reopen your previous issue or ask about it?

**Comment by cvl** [comment]
Can't reopen once closed.
