### ISSUE TITLE
Limit Bandwidth Rates Bug in NodeUI

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#3814]
**Describe the bug**
Limiting Bandwidth in WebUI displays incorrect rates. (Very unreliable results)

**To Reproduce**
1. Install a fresh node version **_0.60.0_**
2. Launch WebUI
3. Click on "Limit bandwidth"
4. Refresh Page
5. See error
6. Unlimit Bandwidth
7. Refresh Page 
8. See error

**Expected behavior**
Limit Bandwidth rates will display incorrect numbers, examples are below.

**Screenshots**
Outcomes:
![image](https://user-images.githubusercontent.com/79473923/129661481-f7b2c8f2-a591-443f-b61c-ffe5de475e28.png)
![image](https://user-images.githubusercontent.com/79473923/129661529-232be4db-da53-4faa-929f-9810b57c4e1a.png)
![image](https://user-images.githubusercontent.com/79473923/129661539-164acaa7-5579-4860-a952-af34af7491dc.png)
![image](https://user-images.githubusercontent.com/79473923/129661557-e5ab19db-49ee-4871-89f9-474f3aa149d3.png)

**Environment (please complete the following information):**
 - Node version: 0.60.0
 - OS: Ubuntu 20.04
 - WebUI Version: 0.4.1

**Additional context**
After you have repeated the process a few times the bug seems to just add an additional 3 MB/S each time the process is repeated.

**Comment by mass34** [comment]
Hi. How do I upgrade to 0.60.0?
