### ISSUE TITLE
Issue sync fails

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3818]
MMN synchronizes Github issues from our node-user-reports repo > https://github.com/mysteriumnetwork/node-user-reports/issues, parses the content and downloads logs from our S3 service.
The latest report was fetched 3 weeks ago into MMN.
<img width="540" alt="Screenshot 2021-08-18 at 08 09 52" src="https://user-images.githubusercontent.com/60128746/129840742-d5d26297-d4de-42c0-9aa7-e52b67404323.png">

**Comment by untitledlt** [comment]
@eugenegoncharuk we need to add new `GITHUB_TOKEN` to `.env`
Contact me for new token.

**Comment by eugenegoncharuk** [comment]
Token changed and deployed

**Comment by etherunit** [comment]
It works now.
