### ISSUE TITLE
MMN: Tokens in hermes column

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3825]
Bounty payouts history column `Tokens in Hermes` is downright confusing for people.
![image](https://user-images.githubusercontent.com/40318863/129911324-777d2cdb-a8af-4b6a-bbc9-16d8299d8a8b.png)

It's ok while the numbers are small, but some providers provide a lot of service and the number goes in to hundreds or thousands and then the confusion starts, because they don't read the bounty rules (or forget them) they start to assume that all the MYST that is displayed there will actually be paid out. The thing is bounty payouts are capped while in testnet.

There are multiple ways to address this, pick one ore two:
* Add explanation that this has little to nothing to do with bounty and bounty is capped at X.
* Remove the column
* Replace the column with actual calculations for the bounty amount which reset to 0 every month and are capped at max bounty.

**Comment by untitledlt** [comment]
i'll go with option #2 for now and we will implement option #3 in MMN 2.0

**Comment by ignasbernotas** [comment]
This column is only visible to MMN Admins and was added to display the tokens in Hermes for that month (useful when investigating node runner bounty troubles).

**Comment by tomasmik** [comment]
Then I dont understand the user confusion with this section of MMN. Will close for now. Thanks for letting me know.
