### ISSUE TITLE
[bug] App broken in testnet3

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3828]
**Describe the bug**
After running app with 0.60.2 in dev mode (clean install):
- app took 3 minutes to get from splash screen
- countries list is never loaded (spins forever).

Has the flow been changed substantially, as "nothing works anymore"?

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7008843/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.60.2
 - OS: Mac

**Comment by creotiv** [comment]
Thanks for your report, we are looking into it. Can you also please send us app logs (~/Library/Logs/MysteriumVPN). Thanks

**Comment by cvl** [comment]
Sure
[main.log](https://github.com/mysteriumnetwork/node/files/7012669/main.log)
[renderer.log](https://github.com/mysteriumnetwork/node/files/7012670/renderer.log)

**Comment by cvl** [comment]
Managed to get it working.
