### ISSUE TITLE
Bounty Pilot Report in WebUI Not Resolving

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#3829]
**Describe the bug**
Bounty pilot report in WebUI is not showing resolving to show MMN earnings.

**To Reproduce**
1. Go to WebUI
3. Scroll down to "Bounty Pilot" Box

**Expected behavior**
"Your bounty report is being generated. Refresh this page in a moment to update."

**Screenshots**
![image](https://user-images.githubusercontent.com/79473923/129975399-a9161b0c-bcfe-426f-80c8-b22f6742c2ec.png)

**Environment (please complete the following information):**
 - Node version: 0.53.2
 - OS: Raspbian GNU/Linux 10 (buster)
 - WebUI: 0.3.2

**Comment by untitledlt** [comment]
![image](https://user-images.githubusercontent.com/7152884/130613836-a5ec982c-50c3-445c-90c8-6bb52a91357a.png)

Probably this was just a temporary issue. LMK if this issues comes back. Closing now.
