### ISSUE TITLE
On status.myserium.network "Site" Should Be Renamed to "Mysterium Network"

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#3831]
**Describe the bug**
"Site" which refferes to Mysterium Network should be renamed to "Mysterium Network"

**To Reproduce**
1. Go to https://status.mysterium.network/
3. Scroll down to "Site"

**Screenshots**
![image](https://user-images.githubusercontent.com/79473923/129976396-4866a049-d8df-420a-abce-9a9509a66eba.png)

**Comment by soffokl** [comment]
It's `Mysterium Network website` now

**Comment by Jayto1** [comment]
@soffokl Thanks! Is there anyway we could capitalize the **W** in "Website" :) Just for me :D

**Comment by Snawoot** [comment]
@Jayto1 that gonna cost you, but I delivered!

**Comment by Jayto1** [comment]
@Snawoot thanks! I owe you one ;)
