### ISSUE TITLE
wg service turns off if whitelisting is turned on

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3839]
**Describe the bug**
Provider id: 0x00f735d4ad380b56b92cd6c9f078763bbfeab3e8
If provider switches from Äll traffic to Mysterium verified partners traffic or vice versa, it immediately evokes wg service to switch off. 

**To Reproduce**
1. Go to NodeUI;
2. Switch to Mysterium verified partners traffic or vice versa;
3. Monitor the behaviour of wg service (it will turn off).

**Expected behavior**
wg service is not affected. 

**Screenshots**
<img width="923" alt="Screenshot 2021-08-20 at 16 17 13" src="https://user-images.githubusercontent.com/60128746/130239078-78cbf6e3-fa2e-42fd-b27f-4983bb69f995.png">

**Environment (please complete the following information):**
 - Node version: 0.60.2
WebUI version: 0.4.3
 - OS: Ubuntu 20.10

**Comment by creotiv** [comment]
Can't reproduce on Node version: 0.60.0, WebUI version: 0.4.1

**Comment by etherunit** [comment]
For the sake of clarity, adding a screencast.

https://user-images.githubusercontent.com/60128746/130245397-e52a5fb6-b88e-4dbf-aac4-4f6450b2c0a2.mov
