### ISSUE TITLE
whitelisting is not adjusted on mmn

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3840]
Enabled whitelisting feature, service restarted, config.toml file is seeing new settings
Whitelisting status on my.mysterium.network remains unchanged (no).

<img width="858" alt="Screenshot 2021-08-20 at 16 22 01" src="https://user-images.githubusercontent.com/60128746/130239704-e8f1b810-9f10-453f-b5eb-cb5f496a751a.png">
<img width="271" alt="Screenshot 2021-08-20 at 16 22 07" src="https://user-images.githubusercontent.com/60128746/130239708-8f32139f-17cd-4a97-b349-6ff905e44522.png">
<img width="1440" alt="Screenshot 2021-08-20 at 16 23 15" src="https://user-images.githubusercontent.com/60128746/130239909-4ac8e51e-ee25-4132-9a81-62e93e3cd824.png">

**Comment by untitledlt** [comment]
this issues also depends on `node:updata-status` cronjob

**Comment by untitledlt** [comment]
all good
