### ISSUE TITLE
MMN shows wrong IP address of my node

### ISSUE THREAD

**Issue by AdineVikash** [mysteriumnetwork/node#3841]
**Describe the bug**
MMN shows wrong ip address of my node.

**Expected behavior**
Your node is sharing its IP address with another node.

**Screenshots**
![Screenshot_2021-08-20-22-50-08-24](https://user-images.githubusercontent.com/68943180/130270578-073ca04c-c548-4a62-be08-6340d55bb6a0.jpg)

**Environment**
 - Node version: [0.60.2]
 - OS: [raspbian buster, debian 10]

**Additional context**
Actual IP - 117.201.7.97 (changes once in day because of dynamic ip)
IP shown in mmn - 162.158.235.248
Checked https://ipinfo.io/162.158.235.248 and I found it's an ip of Cloudflare.

**Comment by Snawoot** [comment]
Restart your node or re-add it to MMN and it'll be fixed.
