### ISSUE TITLE
Map Missing Country

### ISSUE THREAD

**Issue by jos1264** [mysteriumnetwork/node#3842]
Can you add Andorra (AD) country to https://my.mysterium.network/network ?

**Comment by untitledlt** [comment]
I have updated /network page to use hi-res map so now _technically_ Andorra is here but no one will be able to hover it 🤣  
![image](https://user-images.githubusercontent.com/7152884/132710882-d07ad339-e597-4028-99e1-2b1fdf97dfc5.png)

**Comment by jos1264** [comment]
@untitledlt 

I have the node there. No matter how small, it is a country ... Anyway, thank you.
