### ISSUE TITLE
Quitting app without disconnecting first doesn't cleanup the connection

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#3866]
Message from discord:

> when ever I quit the app (window) without hitting the disconnect button, my system will not release the IP/VPN session, causing my system losing connection with Internet. I have to manually release/renew IP/DNS. Please make a mechanism to eliminate this issue.

**Comment by Snawoot** [comment]
Should be fixed by https://github.com/mysteriumnetwork/node/pull/3702
