### ISSUE TITLE
Unable to connect to a node

### ISSUE THREAD

**Issue by mullafabz** [mysteriumnetwork/node#3876]
![Annotation 2021-08-27 210314](https://user-images.githubusercontent.com/26839042/131176611-85e28690-0c69-4132-9cd0-8ed66de82183.jpg)
I am trying to connect to a node but every time i get message saying:
"Oops! Could not connect :(
Error: could not start new connection: failed to
start connection endpoint: could not configure
► device: failed to create wg interface: failed to
create TUN device myst: could not create Wintun
tunnel: Error creating interface: No driver for
device "Wintun" installed (path="connection")"

Attached the screenshots
 - Desktop app version : 6.0.0

**Comment by etherunit** [comment]
@mullafabz Could you Try installing TUN driver (Wintun) for the Windows kernel manually? https://www.wintun.net/builds/wintun-0.13.zip
Restart your pc and app afterwards.
