### ISSUE TITLE
Nodes should not be visible until they have had 24h of total uptime

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#3882]
**Feature Request**
This is a feature request to implement the process of hiding nodes from the network that have less than 24h total uptime. This is to reduce people connecting to brand new nodes that have issues or people testing out a node on a VM that they will soon destroy.

The reason I think it should be total and not consecutive is that some people do not have access to the internet at night and only run their nodes during the day, thus will not be not be able to meet this requirement.

**Comment by timscodebase** [comment]
Thanks, I was wondering why I could not see my new node. :)

**Comment by Jayto1** [comment]
> Thanks, I was wondering why I could not see my new node. :)

Oh this is a feature request, it’s not actually implemented yet :)

**Comment by Jayto1** [comment]
Closing this issue because I think stacking will likely solve this concern.
