### ISSUE TITLE
Login to node-ui failed, even after a 'myst reset' command

### ISSUE THREAD

**Issue by pvdl** [mysteriumnetwork/node#3886]
**Describe the bug**
After upgrade from 0.61.1 to 0.62.0 login to node-ui failed, even after a 'myst reset' command.

**To Reproduce**
1. Go to http://192.168.x.y:4449 (redirected to http://192.168.x.y:4449/#/login)
2. Enter your 'Web UI password'
4. See error: Error Bad credentials

**Expected behavior**
Login should be possible with the known password.
Even after a 'myst reset' command, login with the standard password 'mystberry' doesn't work
(Node seems to work, but I can't access the node-ui to make changes or see the status)

**Screenshots**

**Environment (please complete the following information):**
 - Node version:  0.62.0 (upgraded from 0.61.1)
 - OS: Raspbian GNU/Linux 10 (buster)

**Comment by pvdl** [comment]
I did a check with my bcrypted string in `/var/lib/mysterium-node/nodeui-pass` with this tool: https://bcrypt-generator.com/
I entered the bcrypt hash and the default password `mystberry` and I got a mach. So settings seems to be ok, but the node-ui doesn't process the decryption correctly.

**Comment by iamwoz** [comment]
Having exactly this issue after upgrade to 0.62.0 from 0.61.1

**Comment by Serque** [comment]
> Having exactly this issue after upgrade to 0.62.0 from 0.61.1.
> 
> Also checked with bcrypt and found hash matches.
> 
> Checked https://my.mysterium.network/ and node is up and working properly, just auth issue to local interface
> 
> Node: Node version: 0.62.0 (upgraded from 0.61.1)
> OS: Linux mysterium 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> ![image](https://user-images.githubusercontent.com/85816876/131570865-a856d5cf-d913-4ab0-aef1-690292f1741a.png)
> 
> ![image](https://user-images.githubusercontent.com/85816876/131570952-9d864eed-7996-4969-a8d2-d96319d7f5ae.png)

Same problem

**Comment by pvdl** [comment]
Solved in 0.62.1. 
You'll get a new on-boarding process and you can set your password.

**Comment by madmax1970** [comment]
Try renaming the nodeui-pass under /var/lib/mysterium-node/ to something else. Then reload NodeUI, it will then ask you to supply a new password.
