### ISSUE TITLE
Can't login to Node UI after update to 0.62.0 from 0.53ish

### ISSUE THREAD

**Issue by EndymionSpr** [mysteriumnetwork/node#3893]
Can't login to Node UI after update to 0.62.0 from 0.53ish.

I have a Node installed on my raspberry pi. Yesterday i updated packages via "sudo apt update" "sudo apt upgrade".
Myst node updated along with 8 other packages. I restarted Rpi, my node went online and seemed to work but i couldn't log in via Node UI tho. I had access to my rpi via ssh, was able to change ui password here:

![image](https://user-images.githubusercontent.com/26204624/131815536-14c9dd69-3e1a-4618-bdd8-95e6507a185f.png)

![image](https://user-images.githubusercontent.com/26204624/131815947-58959bf9-3732-4576-bd1b-81b042018307.png)

It didn't help. Still unable to log in (yes i restarted).

Today my node traffic increased both in number of connections and data pushed through I just cannot login.
Last month my node had 40GB of traffic through it and i had no problem logging in to it once.

 - Node version: [0.62.0]
 - OS: [raspbian]

UPDATE1: I only got TEST traffic today.

**Comment by duilionet** [comment]
Same problem with new node just created with the installation script:
sudo apt-get install curl
sudo -E bash -c "$ (curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"

Node: [0.62.0]
OS: [Ubuntu Server 21.04]

**Comment by mauricecyril** [comment]
Same issue. Running myst reset --tequilapi changes the webui password but there's no indication of what that new password is.

**Comment by pvdl** [comment]
I got the same issue and logged https://github.com/mysteriumnetwork/node/issues/3886
It is solved in 0.62.1

**Comment by Serque** [comment]
> I got the same issue and logged #3886
> It is solved in 0.62.1

but repository has 0.62.0 version. After "sudo apt update" is all up to date, but myst is 0.62.0

**Comment by pvdl** [comment]
You need an extra ppa repo:
This is my mysterium.list file:

```pi@raspberrypi:/etc/apt/sources.list.d $ cat mysterium.list
deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu bionic main
deb http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu bionic main```

**Comment by EndymionSpr** [comment]
> 
> 
> You need an extra ppa repo:
> This is my `/etc/apt/sources.list.d/mysterium.list` file:
> 
> ```d
> deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu bionic main
> deb http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu bionic main
> ```

It worked, thank you. BUT now my NAT isn't as it was for some reason.

![image](https://user-images.githubusercontent.com/26204624/131885355-ab9a1872-539b-4e5a-9221-9b85c18a8ca7.png)

I also had no way of adding OPENVPN service via nodeUI, had to do it through "myst cli".

Should i change something in my /etc/default/mysterium-node  ?


# Define additional args for `myst` service (see `myst --help` for full list)
CONF_DIR="--config-dir=/etc/mysterium-node"
SCRIPT_DIR="--script-dir=/etc/mysterium-node"
RUN_DIR="--runtime-dir=/var/run/mysterium-node"
DATA_DIR="--data-dir=/var/lib/mysterium-node"
DAEMON_OPTS="--p2p.listen.ports=51820:52075 --experiment-natpunching=false --keystore.lightweight"
SERVICE_OPTS="--wireguard.listen.ports=52820:53075 wireguard"

**Comment by Serque** [comment]
> You need an extra ppa repo:
> This is my `/etc/apt/sources.list.d/mysterium.list` file:
> 
> ```d
> deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu bionic main
> deb http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu bionic main
> ```

Thanks

**Comment by etherunit** [comment]
Guys, this issue is fixed by https://github.com/mysteriumnetwork/node/pull/3888
Please upgrade your nodes to 0.62.1
