### ISSUE TITLE
I cant re-login into the myst ui to my local pi

### ISSUE THREAD

**Issue by evgenyvh** [mysteriumnetwork/node#3894]
I just cant re-login into the myst ui to my local p :(
This was my second setup ( i reinstalled/ flashed the sd card again) so I put in a password, API to claim host, but then let's say 10 min later I want to log in it gives me every time "Error
Bad credentials" and have tried t reset the password it says something about permission... Please help :)

* I got a response to open here a issue

**Comment by evgenyvh** [comment]
![image](https://user-images.githubusercontent.com/45003203/131862332-e07fdbd7-e6d1-4a1a-9c28-e038626b0d8d.png)

**Comment by mauricecyril** [comment]
Experiencing the same issue. Looks like a bug with the latest version 0.62.0

**Comment by pvdl** [comment]
I got the same issue and logged #3886
It is solved in 0.62.1

**Comment by etherunit** [comment]
Guys, this issue is fixed by #3888
Please upgrade your nodes to 0.62.1
