### ISSUE TITLE
Connection should be renewed after it was dropped when using kill-switch

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3895]
**Describe the bug**
- Use "--keep-connected-on-fail=true", flag when starting myst.
- Connect
- Use Network Link Conditioner (from xcode) to kill your connection (set to drop 100% packets)
- The connection status goes to OnHold (which is okay)
- After reenabling the connection with Link Conditioner, the Internet connection is not renewed (i.e. it's still down, until I manually disconnect).

It should renew the VPN connection after connection is back.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7100053/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.62.1
 - OS: Mac

**Comment by cvl** [comment]
On another attempt, the connection was renewed (I assume it depends on how long the connection was dropped), but node status didn't update back to Connected (was left at OnHold).

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7100270/mysterium-node.log)

**Comment by creotiv** [comment]
@cvl We are working on reconnect feature right now.

**Comment by cvl** [comment]
Got it, thanks!
