### ISSUE TITLE
Unable to reset password for Node UI

### ISSUE THREAD

**Issue by subhasisbanik** [mysteriumnetwork/node#3896]
**Describe the bug**

**To Reproduce**
1. Go to 'Node UI'
2. Click on 'Forgot password'
3. ssh into the raspberry pi with myst user
4. Run 'sudo myst reset --tequilapi'

**Expected behavior**
The new password to be set as mystberry and enables the user to login to Node UI

**Screenshots**
![image](https://user-images.githubusercontent.com/25420904/131898698-7745657b-5d72-4904-9ac2-d64342456d5f.png)

**Environment (please complete the following information):**
 - Node version: 0.62.0
 - OS: raspbian
 - Desktop app version : Don't know

**Additional context**
The reset password does not throw any error in the console.

**Comment by etherunit** [comment]
Could you please try upgrading your node to 0.62.1?

**Comment by etherunit** [comment]
0.62.1 should fix this problem. If you still experience this problem after upgrade, feel free to re-open it.
