### ISSUE TITLE
Node list disappearing from the my.mysterium.network dashboard

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3898]
It switches through the period of time - getting either 200 OK or cancelled. I have no such issue when calling https://my.mysterium.network/api/frontend/nodes directly.
https://user-images.githubusercontent.com/60128746/131964665-54b4f8bc-fa2e-4334-860e-986e34780f04.mov
<img width="886" alt="Screenshot 2021-09-03 at 10 08 00" src="https://user-images.githubusercontent.com/60128746/131964868-05f6f403-c65d-456b-9c3d-721666582935.png">

**Comment by icmono** [comment]
![Screenshot from 2021-09-07 14-57-24](https://user-images.githubusercontent.com/12896725/132341704-af2694e4-ccd5-42a0-b66e-59ccd40c8f80.png)

https://my.mysterium.network/api/frontend/nodes returns error 500 and displays "worker error: EOF" after exactly 1.5m

**Comment by chompomonim** [comment]
Not reproducible anymore, closing. If it will repeat, please create new issue.
