### ISSUE TITLE
Stuck on node version 0.46.2-rc0 in my.mysterium.network despite updating both nodes

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3899]
**Describe the bug**
0x8db0575a165f780ebee4eb23976ad23f49f6e69f
0x28e13d5d3c47e93da4bdeb0f2ac94f256bd6ab03

Nodes are being unsuccessfully updated. tried and still showing on my.myst.network as being on the old node on both raspberry pis.

**To Reproduce**

Heres the results of that command:
myst@raspberrypi:~ $ sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"
### Detecting platform
System info:
OS: linux
Distribution: raspbian
Version codename: buster
### Installing myst & dependencies
Executing: /tmp/apt-key-gpghome.WESaXZFBwF/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
gpg: key E0B11894F66AEC98: "Debian Archive Automatic Signing Key (9/stretch) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg: unchanged: 1
Executing: /tmp/apt-key-gpghome.hl0sMAyoXp/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
gpg: key DC30D7C23CBBABEE: "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg: unchanged: 1
Get:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:2 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Get:3 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]
Get:4 http://deb.debian.org/debian unstable InRelease [165 kB]
Hit:5 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease
Get:6 http://deb.debian.org/debian buster-backports/main armhf Packages [476 kB]
Get:7 http://archive.raspberrypi.org/debian buster/main armhf Packages [378 kB]
Get:8 http://deb.debian.org/debian unstable/main armhf Packages [8,428 kB]
Get:9 http://deb.debian.org/debian unstable/main Translation-en [6,519 kB]
Fetched 16.1 MB in 25s (632 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
raspberrypi-kernel-headers
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.7 MB of archives.
After this operation, 180 MB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian buster/main armhf raspberrypi-kernel-headers armhf 1:1.20210805-1 [27.7 MB]
Fetched 27.7 MB in 3s (8,515 kB/s)
Selecting previously unselected package raspberrypi-kernel-headers.
(Reading database ... 40800 files and directories currently installed.)
Preparing to unpack .../raspberrypi-kernel-headers_1%3a1.20210805-1_armhf.deb ...
Unpacking raspberrypi-kernel-headers (1:1.20210805-1) ...
Setting up raspberrypi-kernel-headers (1:1.20210805-1) ...
Executing: /tmp/apt-key-gpghome.fwEdYcRqBb/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys ECCB6A56B22C536D
gpg: key ECCB6A56B22C536D: "Launchpad PPA for Mysterium Network" not changed
gpg: Total number processed: 1
gpg: unchanged: 1
Hit:1 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://deb.debian.org/debian buster-backports InRelease
Hit:4 http://deb.debian.org/debian unstable InRelease
Hit:5 http://archive.raspberrypi.org/debian buster InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
myst is already the newest version (0.53.2+build348501509+focal).
wireguard is already the newest version (1.0.20200827-1~bpo10+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
### Installation complete!

**Expected behavior**
Node would update normally after running commands

**Screenshots**

<img width="783" alt="Screenshot 2021-09-03 at 11 34 51" src="https://user-images.githubusercontent.com/84313603/131992178-33a0fc2e-20c3-493e-8026-ffd7a9d847f9.png">

**Environment (please complete the following information):**
System info:
Device: Pi 3b
OS: linux
Distribution: raspbian
Version codename: buster

**Additional context**
Provider's comment
"ive got over 100 myst tokens I cannot collect though no fault of my own"

**Comment by etherunit** [comment]
Check if MMN API key is present under MMN integration in NodeUI.
