### ISSUE TITLE
move user space WG support from mobile package

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#390]
In order to have WG support for all major platforms use wireguard-go userspace WG implementation we need to move current user space WG support from mobile package to generic WG package in node.

**Comment by zolia** [comment]
We should use our fork for this matter. Where we tried to make device usage more library like: 

https://github.com/mysteriumnetwork/wireguard-go

@tadovas did refactored that part and we should use it.

**Comment by zolia** [comment]
Looks like we are using original name "git.zx2c4.com/wireguard-go/", but substituting it with our fork. IMHO this is bogus, since we depend on package manager. Those who will fetch our sources and try to use other packaging might go into trouble. 

I think we should use our package naming (forked) since it is very confusing and in general our source does not comply contract implemented by "git.zx2c4.com/wireguard-go/".

**Comment by soffokl** [comment]
Changed it in following PR, but I don't have permissions to assign reviewers: 
https://github.com/mysteriumnetwork/wireguard-go/pull/1
