### ISSUE TITLE
Node UI not reflecting earnings and sessions

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3900]
**Describe the bug**
Node UI not reflecting earnings and sessions
MMN dashboard is updated and reflecting earnings and sessions correctly. However, node ui is not at all 

0xeeb7f1ade35da77b096c47430452a18d53c9f14d after node updated to latest version

**To Reproduce**
1. Go to 'NodeUI Dashboard'
2. See error

**Expected behavior**
NodeUI should be reflecting same information as MMN is. 

**Screenshots**

<img width="1302" alt="Screenshot 2021-09-03 at 14 58 03" src="https://user-images.githubusercontent.com/84313603/132017379-5dd2a7ee-6a55-4f71-885f-42327bce66e1.png">

<img width="683" alt="Screenshot 2021-09-03 at 15 14 27" src="https://user-images.githubusercontent.com/84313603/132020001-29ab5fcb-818c-4d33-b001-3ab97590f771.png">
<img width="676" alt="Screenshot 2021-09-03 at 15 14 40" src="https://user-images.githubusercontent.com/84313603/132020012-2fd54399-783d-407e-9fd6-ca8818c8ee5e.png">
<img width="669" alt="Screenshot 2021-09-03 at 15 14 53" src="https://user-images.githubusercontent.com/84313603/132020021-5075252a-cfbf-4bc2-90a2-11d47e1439f6.png">
<img width="675" alt="Screenshot 2021-09-03 at 15 15 04" src="https://user-images.githubusercontent.com/84313603/132020024-8679a170-3b2d-49ea-b728-3ec46d66a789.png">
<img width="669" alt="Screenshot 2021-09-03 at 15 15 16" src="https://user-images.githubusercontent.com/84313603/132020035-9ae79baa-1554-4f6d-a71a-4b1ff3041f75.png">

**Environment (please complete the following information):**
 OS:
Ubuntu 20.04.3 LTS
Architecture:
linux/amd64
Node version:
0.62.1

**Additional context**

**Comment by edyshok** [comment]
![image](https://user-images.githubusercontent.com/85687242/132024429-5836b839-6c50-41ad-b152-4e4b130617a8.png)

**Comment by edyshok** [comment]
After update

**Comment by etherunit** [comment]
NodeUI was reset after migration while MMN keeps all data incl. earnings.
