### ISSUE TITLE
[404 Page Not Found] error message all over winter-is-coming repository

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#3905]
**Describe the bug**
Lots of 404 Page Not Found Errors on winter-is-coming page

**To Reproduce**
1. Go to https://github.com/MysteriumNetwork/winter-is-coming
2. Click on **Mysterium Team, Backend Engineering, Application Engineers, Peer-to-Peer (P2P) Developers, Network Protocol Developers** 
3. See error

**Expected behavior** 
404 Page Not Found

**Screenshots**
![image](https://user-images.githubusercontent.com/79473923/132117832-43e1847f-8ab4-42fd-88ce-9638d6f529b7.png)

**Comment by tomasmik** [comment]
Fixed.
