### ISSUE TITLE
Dial udp 127.0.0.53:53: socket: too many open files

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3915]
**Describe the bug**

Node stuck after some decent amount of traffic passed through a tunnel. It was a long session pulling down 15 GB of data. Find a piece of log output below:

Affected providers:

- 0xd63c065d12517e48a77ac33247c2ea2aa8551231
- 0x3712b4009a8c3372f370c79f766a306683e42d53

```
Sep 05 19:32:47 nas myst[2789709]: 2021-09-05T19:32:47.343 ERR dns/handler_system.go:65                 > Error proxying DNS query to 127.0.0.53:53 error="dial udp 127.0.0.53:53: socket: too many open files"
Sep 05 19:50:57 nas myst[2789709]: 2021-09-05T19:50:57.845 DBG config/config.go:224                     > Returning default value chain-id:80001
```

It seems that all available file handles for the myst process have been used (this includes sockets as well).
Probably, this is the result of file handles (file descriptor) is being leaked by some part of the application. 

`sudo lsof -n -a -p <PID OF MYST PROCESS>` output:
[lsof.txt](https://github.com/mysteriumnetwork/node/files/7121003/lsof.txt)

**Screenshots**
<img width="1063" alt="Screenshot 2021-09-07 at 12 15 00" src="https://user-images.githubusercontent.com/60128746/132330806-f337ea38-7593-4ed7-92de-9aa02ba9c7ba.png">

**Environment (please complete the following information):**
 - Node version: 0.62.1
 - OS: Ubuntu 20.04.2 LTS

Node logs: https://my.mysterium.network/admin/issues/download/3572

**Comment by soffokl** [comment]
There were other logs that might be related:
```
Sep 05 19:32:47 nas myst[2789709]: 2021-09-05T19:32:47.343 ERR dns/handler_system.go:65 > Error proxying DNS query to 127.0.0.53:53 error="dial udp 127.0.0.53:53: socket: too many open files"
```

**Comment by Snawoot** [comment]
@etherunit please ask when lsof output was collected: after node restart or in the exact moment when it got stuck. In former case please ask to collect lsof output again when node gets stuck and emitting such errors. So far we don't see in output excess number of open file descriptors.

**Comment by etherunit** [comment]
Update: 0xd63c065d12517e48a77ac33247c2ea2aa8551231 affirms that he faced this problem again. This time` lsof` output and logs were collected before the restart of the node service.
[lsof2.txt](https://github.com/mysteriumnetwork/node/files/7128540/lsof2.txt)

**Comment by Snawoot** [comment]
@etherunit Thank you very much! New data is very useful. Now we know how ports are used and what limit number we hit.

**Comment by creotiv** [comment]
@etherunit can they send result of `sysctl -a` command?

**Comment by creotiv** [comment]
And also this one `netstat | grep "TIME_WAIT" | wc -l && netstat | grep "CLOSE_WAIT" | wc -l`

**Comment by Snawoot** [comment]
Hello there!

Let me help a little here.

`sysctl -a &> out.txt` won't give you anything useful regarding open fds or particular process state.

`netstat | grep "TIME_WAIT" | wc -l && netstat | grep "CLOSE_WAIT" | wc -l` won't give you anything because such connections are not accounted as an open FD.

`ulimit -a` will give you ulimit of the shell, not of the particular process. However, lsof indicates that ulimit was `1024`, which is one of possible defaults.

**Comment by etherunit** [comment]
```
netstat | grep "time_wait" | wc -l && netstat | grep "close_wait" | wc -l
0
0
```

[sysctl.txt](https://github.com/mysteriumnetwork/node/files/7141357/sysctl.txt)

**Comment by creotiv** [comment]
@etherunit We made couple updates that may fix such behavior. Ask them to update node on the next release >=0.64.1 (or from master)
If it appears again, please reopen this issue.

**Comment by etherunit** [comment]
Problem repeated for 0x021b817caf509c195cc9375b0d9856abb9c8c8c9
Will submit logs shortly

**Comment by Snawoot** [comment]
Please update to 0.66.0, it contains a lot of fixes relevant to this.

**Comment by Arnav-247** [comment]
Hi I'm on 0.66.4
I think I have the same issue as mentioned in this thread.
When this happens my WebUI doesn't load and I see this in the logs

[log.txt](https://github.com/mysteriumnetwork/node/files/7316006/log.txt)

To remedy this I have to restart it using sudo systemctl restart mysterium-node.service

My node is on a raspberry pi.

**Comment by Arnav-247** [comment]
Using lsof didn't give me any output.
I used `ps -aux  | grep myst` to find the pid
![image](https://user-images.githubusercontent.com/9696861/136949731-a88efee4-253c-4096-9ff9-b4263b8768ce.png)

I don't have any files in /var/log/mysterium-node its empty

In the mysterium discord server, it says we can collect logs like this
Using `sudo journalctl -u mysterium-node.service > crash_log1.txt`
I got a text file which is 600MB in size and I can't upload it here, so I'm adding a google drive link
https://drive.google.com/file/d/12dxUyBO7JtNQlaj-7f6Rgtg1rNsPwu_T/view?usp=sharing
