### ISSUE TITLE
Your node does not have a wallet address

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3921]
**Describe the bug**
MMN bounty module displays "Your node does not have a wallet address." but beneficiary wallet is configured properly. Admin page shows `Hermes [] No location information found.`

**Expected behavior**
Bounty box should display "You are all set!".

**Screenshots**
<img width="802" alt="Screenshot 2021-09-07 at 16 39 00" src="https://user-images.githubusercontent.com/60128746/132354534-f3c11a1f-bbc1-45a8-9548-7ac39c19d93f.png">

**Environment (please complete the following information):**
 - Node version: 0.62.1
 - OS: Ubuntu 20.10

**Comment by kevinderek** [comment]
Reserved the same masseges

**Comment by sridharanreigns** [comment]
![image](https://user-images.githubusercontent.com/68216966/132382549-6281a9fb-7f33-466a-ad9f-f6152b0a3409.png)

My node Id - 0x151bd29cf0f803414dcc68e87ed51e55df9f9162 - INDIA

Im not recived my payments!!! 

Ineligiblity reason Shown As "Your node does not have a wallet address."

**Comment by etherunit** [comment]
Fixed. Closing this one.
