### ISSUE TITLE
MMN and NodeUI not reflecting earnings nor data transferred 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3926]
**Describe the bug**
MMN and NodeUI not reflecting earnings nor data transferred as it previously was before. No update or changes were done to the node

Node ID: 0xeeb7f1ade35da77b096c47430452a18d53c9f14d

**To Reproduce**
1. Go to 'MMN or Node UI'
2. See error

**Expected behavior**
Normally dashboards should either keep their previous information or accumulate MYST and data transferred.

**Screenshots**
<img width="1290" alt="Screenshot 2021-09-09 at 07 55 32" src="https://user-images.githubusercontent.com/84313603/132637573-cb4d79ed-d2dc-4d8a-b6fc-823cf78c8636.png">
<img width="1286" alt="Screenshot 2021-09-09 at 07 55 21" src="https://user-images.githubusercontent.com/84313603/132637612-83dc44fe-f8c7-4a00-acf7-14c6d40110d7.png">

**Environment (please complete the following information):**
OS: Ubuntu 20.04.3 LTS
Architecture: linux/amd64
Node version: 0.62.1

**Comment by fatkulnurk** [comment]
I have 7 nodes, and 5 nodes I have this problem:

Describe the bug
all the income I earned from the beginning of the month (1st September) to 8th September disappeared.

![image](https://user-images.githubusercontent.com/12779618/132661579-4a16dfbf-87b3-46cf-89eb-b3c404c06f35.png)
Node ID: 0xca8c0aaef075823f20ed947b7c0aeb6bbd2d1e80
OS: Ubuntu 20.04 LTS
Node Version: 0.61.0


![image](https://user-images.githubusercontent.com/12779618/132662146-08d4f070-8873-409d-85c7-13dcc79a2b23.png)
Node ID: 0x13b7aebad706a340f8353c1f6f76c83de7e8f39e
OS: Ubuntu 20.04.2 LTS
Node Version: 0.62.1

![image](https://user-images.githubusercontent.com/12779618/132662241-83772280-66e7-4f99-9705-4da5809ae69f.png)

Node ID: 0x5b6c40c936a8d6f7afce585a9e574818cb5190a7
OS: Ubuntu 20.04.2 LTS
Node Version: 0.62.1

![image](https://user-images.githubusercontent.com/12779618/132662399-723a9855-02e0-40c6-94d7-5dec6365fe57.png)
Node ID: 0x3704a59d5c5fb5fbc1fc48105855b743b0494a3e
OS: Ubuntu 20.04.2 LTS
Node Version: 0.62.1


![image](https://user-images.githubusercontent.com/12779618/132662494-fd207cc1-ab3d-4672-ba4d-5bef322b0059.png)
Node ID: 0x967ed85a529a1ab78d72d20706cbbf5b38a3de4e
OS: Ubuntu Ubuntu 20.04.2 LTS
Node Version: 0.53.2
