### ISSUE TITLE
[windows, bug] node can't be started

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3934]
**Describe the bug**
Node can't be started when starting app. Multiple errors:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7142570/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.61.1
 - OS: Windows

**Comment by tomasmik** [comment]
It seems that supervisor was not running or was killed. Could you provide steps to reproduce this? Could you check that you get the same errors if supervisor is killed?

**Comment by cvl** [comment]
Still waiting for the response from the user.
