### ISSUE TITLE
Nodes are getting earnings differently on Residential Bounty balance and Global Bounty balance

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3935]
**Describe the bug**

Nodes are getting earnings differently on Residential Bounty balance and Global Bounty balance

"I’ve been selling much more residential bandwidth than global, but my country isn’t listed so I’m losing money. Please add Greece or tell me when are you planing to do it."
0x9265e89a23591cff7f22be6c531761c26e21d4b9

**To Reproduce**
1. Go to 'MMN'
2. Scroll down to 'Bounty balances'
4. See error (error shown in screenshot below)

**Expected behavior**
Normally nodes tend to reflect the same balance on both Global and residential bounties. However, for a few of the nodes the balances are completely different between the two bounties. Is there a criteria or a reason behind this?

The issue arrises when these providers are not eligible for residential bounty and are eligible for the Global Bounty. However, all of their earnings go to residential bounty balance and since they are not eligible all of their earnings stay there and are never payed. 

**Screenshots**
<img width="1283" alt="Screenshot 2021-09-10 at 11 28 11" src="https://user-images.githubusercontent.com/84313603/132840273-e19acd15-e26e-4f75-bf02-b606c22e9d63.png">

**Environment (please complete the following information):**
OS:Raspbian GNU/Linux 10 (buster)
Architecture: linux/arm
Node version: 0.62.1

**Additional context**

Similar balance discrepancies can be seen on the comment section of the issue right below. Screenshot displays about 7 nodes with different balances from Residential and global bounty.

https://github.com/mysteriumnetwork/node/issues/3926

**Comment by eugenegoncharuk** [comment]
Yes, per code it's possible that these values differ.
Not a bug.

**Comment by isaackielma** [comment]
@eugenegoncharuk Is there a way to ensure that provide is only earning global bounty instead. Since Greece isn't in the residential bounty anyways, provider would not get paid for shared bandwidth?

**Comment by eugenegoncharuk** [comment]
The provider will earn only for global bounty.
