### ISSUE TITLE
Avado node provider is stuck on older version. Node cannot update it in order to receive bounty payments

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3936]
**Describe the bug**
One of our node providers is running a node on Avado box and for some odd reason his node isn't auto updating like the rest of the other Avado nodes in the Network. As seen in the screenshot below provider is still on version 0.41.4, but has no way to update manually unless Avado updates for him.

**To Reproduce**
1. Go to 'MMN'
2. See node version
3. Click on 'Bounty Payout History'
4. See error message 'Leaderboard positions were ineligible for payments'

**Expected behavior**
Normally Avado nodes are expected to auto update whenever our updates become available for the Avado team to update them all. 

**Screenshots**
<img width="893" alt="Screenshot 2021-09-10 at 11 36 02" src="https://user-images.githubusercontent.com/84313603/132841314-ff37ed26-2244-4dd7-b09f-ed8f4affa24d.png">

**Environment (please complete the following information):**
OS: Alpine Linux v3.12
Architecture: linux/amd64
Node version: 0.41.4

**Additional context**
This issue was reported last month and was not fully resolved. What happened last month is that we manually payed node provider the amount he deserved, because we agreed that it was not his fault since he could not update the node.

**Comment by sponnet** [comment]
I will reach out to him - to verify if he has auto-updates enabled for the package. It should auto update in that case.

**Comment by MattLong6** [comment]
Yes I have been having issues with this for awhile now. Like 3 month. Here is my current info from my AVADO:

![Uploading Screenshot_20210910-175130_Chrome.png…]()

**Comment by MattLong6** [comment]
![Screenshot_20210910-175213_Chrome](https://user-images.githubusercontent.com/71360466/132921660-317c0e1f-d0aa-42f1-9d9c-a373b3474ea0.png)

**Comment by MattLong6** [comment]
![Screenshot_20210910-175142_Chrome](https://user-images.githubusercontent.com/71360466/132921830-eda579dd-fd37-4ddb-b4b2-d18e237b45bf.png)

**Comment by MattLong6** [comment]
![Screenshot_20210910-175130_Chrome](https://user-images.githubusercontent.com/71360466/132921842-9dea83d6-a1e3-4111-8d59-778f771df122.png)

**Comment by eugenegoncharuk** [comment]
From the grafana I see that user has updated version
![image](https://user-images.githubusercontent.com/87538/133800850-f10a7319-4817-44b9-90eb-a64a1fd7e209.png)

**Comment by eugenegoncharuk** [comment]
![image](https://user-images.githubusercontent.com/87538/133802830-76c4627b-ec9f-4f3a-b054-fb8fc219cb2c.png)
Correct version is now seen.

**Comment by eugenegoncharuk** [comment]
Eligibility for both programs
![image](https://user-images.githubusercontent.com/87538/133802962-10cabb71-27e9-402e-bdbf-de8fdd674043.png)

**Comment by eugenegoncharuk** [comment]
@MattLong6 Can you please, try to check if Avado node is able reach "my.mysterium.network" ? Cause it seems, that it's not and that's why the version is not updated in MMN.
Also, could you, please, confirm that you are not running any kind of firewall, blocking Avado requests to and from?

**Comment by MattLong6** [comment]
Sorry, I am busy this weekend. I will get back to you.

What ports need forwarded? I do not have a firewall, I use windows defender.

I am able to connect and sign in when I go to my AVADO and click Mysterium node.

Does that answer the questions? If not please let me know what to check :)

**Comment by MattLong6** [comment]
Can we wait to close this until after we see if I automatically received payment rewards for providing the VPN endpoint?

**Comment by eugenegoncharuk** [comment]
@MattLong6 We need to test that my.mysterium.network got pinged from Avado node. Can you check to ping it from Avado node?

**Comment by MattLong6** [comment]
How do I do that?

**Comment by MattLong6** [comment]
I am not available this weekend, I am trying to figure out what you need me to do.
I am on Version: 0.0.55 QmTs1KW4W8i3ioVpjhbQ83y2SCJoxTBHkaqjQ8qpvx8sC8

**Comment by MattLong6** [comment]
I believe that I can ping it just fine - 
![image](https://user-images.githubusercontent.com/71360466/135478937-0892e848-8c3e-4631-a710-77e3a84a2068.png)
&
![image](https://user-images.githubusercontent.com/71360466/135479397-d5a2305a-dbad-44e9-8ec2-667a0cd37dc8.png)
&
![image](https://user-images.githubusercontent.com/71360466/135479345-9d6ee34a-16ab-4cfd-9cf2-ecbac1cd2cc4.png)

**Comment by MattLong6** [comment]
I want to make sure that I get automatic payments before we close this issue.
I also want to know about the other MYST that I earned.

**Comment by eugenegoncharuk** [comment]
@MattLong6 We will process two payouts. One for September in the amount of around 25 MYST and one additional of not paid for the previous months in the amount of 40.7224 MYST.

**Comment by MattLong6** [comment]
Thank you!

**Comment by MattLong6** [comment]
I just wanted to add this as a reference. 
Old bug report - https://github.com/mysteriumnetwork/node/issues/3450

**Comment by eugenegoncharuk** [comment]
Made both payments. Can be closed.
