### ISSUE TITLE
[Android, docker,  bug] Docker node has disappeared from app node-list

### ISSUE THREAD

**Issue by Serque** [mysteriumnetwork/node#3938]
**Describe the bug**
My docker node 0x813d855bd73cdd5661ea0c375951c4e9feecc1c8 is absent in nodes list on android app

**To Reproduce**
1. Go to 'Netherlands'

**Expected behavior**
Node is in list of nodes.

**Screenshots**
![Screenshot_2021-09-10-20-46-35-024_network mysterium vpn](https://user-images.githubusercontent.com/48916648/132895913-429b7f7a-43c0-4b74-b780-d4e26b7c9d9f.png)

**Environment (please complete the following information):*
 - Node version: 0.63.0
 - OS: android 10 (MIUI 12.0.5 stable)
 - Desktop app version (if applicable): 1.1.1.107112
 - Docker (if applicable): 20.10.8, build 3967b7d

**Additional context**
The node is present in Windows app. My other not docker node is present in android app.

**Comment by etherunit** [comment]
![Screenshot_2021-09-14-10-00-41-439_network mysterium vpn](https://user-images.githubusercontent.com/60128746/133210952-ef596ee3-4d98-4780-8a74-a26978e19b98.jpg)

**Comment by Serque** [comment]
![Screenshot_2021-09-14-14-22-04-752_network mysterium vpn](https://user-images.githubusercontent.com/48916648/133248856-2f597e52-883e-411b-81e8-7b02ef3bc17d.jpg)
Still absent

**Comment by etherunit** [comment]
What's your app version?

**Comment by Serque** [comment]
> What's your app version?

my android app version: 1.1.1.107112

**Comment by etherunit** [comment]
Make sure that "All nodes", "Media browsing" or "Download" filter is selected on the main screen.
![Screenshot_2021-09-14-22-57-27-262_network mysterium vpn](https://user-images.githubusercontent.com/60128746/133325316-9dd3a333-842b-4fa0-91b9-c7385bed74cf.jpg)
If you select Media browsing, node become unavailable.

**Comment by Serque** [comment]
Yes, i always selected 'all nodes'.
![Uploading Screenshot_2021-09-14-23-25-30-152_network.mysterium.vpn.png…]()

**Comment by Serque** [comment]
Yes, i always selected 'all nodes'.
![Screenshot_2021-09-14-23-25-30-152_network mysterium vpn](https://user-images.githubusercontent.com/48916648/133329423-e3264542-be23-4e8e-bb0b-a548b2dda7e7.png)

**Comment by etherunit** [comment]
Apparently, your node is visible for everyone who checked it.
You can still try to reset filters to All nodes, All types and Any. If that still doesn't help, try to kill the app and check it again. Alternatively, reinstall the app and see if that helps.

**Comment by Serque** [comment]
> Apparently, your node is visible for everyone who checked it.
> You can still try to reset filters to All nodes, All types and Any. If that still doesn't help, try to kill the app and check it again. Alternatively, reinstall the app and see if that helps.

i'll try and let you know.

**Comment by etherunit** [comment]
I was able to find your node service proposal but it's not visible for you in mobile UI. It might be that its source NAT type is incompatible with your destination transport address. By default we are filtering out unsupported nodes automatically. It should be improved by: https://github.com/mysteriumnetwork/mysterium-vpn-mobile/issues/447 It would help to disable such filtering if users wants to

**Comment by Serque** [comment]
etherunit — Yesterday at 1:53 PM
Alternatively (because your container is running on dc), adding --net=host into docker run should solve nat compatibility issue you have.  - This advice has solved that issue. Thanks a lot.

**Comment by Serque** [comment]
![Screenshot_2021-09-22-19-24-35-672_network mysterium vpn](https://user-images.githubusercontent.com/48916648/134384207-dd995eaa-008e-44eb-880a-1fd0fa07c4ec.jpg)
