### ISSUE TITLE
Test Failed, Symmetric Connection

### ISSUE THREAD

**Issue by visualalchemy** [mysteriumnetwork/node#3941]
**Describe the bug**
Node Status: **Test Failed**
Your NAT Type: **Symmetric.**
Consumers are having hard time connecting to your node. Please check documentation on how to improve it.

**To Reproduce**
My current setup reproduces this message in the Nat Connection status icon.

<img width="682" alt="Screen Shot 2021-09-09 at 11 46 53 AM" src="https://user-images.githubusercontent.com/90494621/132937959-bf847200-5737-4e34-b9a6-7c1900aaaa84.png">

**Environment (please complete the following information):**
 - Node version: Node version: 0.62.1
 - OS: raspi

Node had been working properly prior to this error showing up. No changes were made.

**Comment by etherunit** [comment]
Your internet connection is behind a Symmetric NAT Modem/Router. Consumers may have difficulty connecting to your node.

The 1st solution to this problem will involve you configuring your router through a web page built into them. Many recent routers support a feature called Universal Plug and Play (UPnP) which will allow Myst to do most of the configuration required.
Enable UPnP, change NAT traversal ordering under Advanced Settings in UI to `upnp,manual,holepunching`, restart your node and perform [manual connection check. ](https://docs.mysterium.network/node-runners/service-monitoring/#how-to-trigger-a-connection-check)
If your node become accessible, it will trigger node status changes.

The 2nd solution is to manually configure your router to do port-forwarding for UDP ports (default 10000:60000), though you can use a shorter range of ports (e.g. 56500:60000). Once completed, navigate to your UI and 
change NAT traversal ordering under Advanced Settings in UI to `manual,upnp,holepunching`, restart your node and perform [manual connection check. ](https://docs.mysterium.network/node-runners/service-monitoring/#how-to-trigger-a-connection-check)
If your node become accessible, it will trigger node status changes.
