### ISSUE TITLE
Node Running On Docker Daily Offline Issue 

### ISSUE THREAD

**Issue by breezytm** [mysteriumnetwork/node#3943]
At least once a day my node seems to go offline. However, the container is still running. Please take a look. 

<img width="1468" alt="Screen Shot 2021-09-11 at 5 41 10 PM" src="https://user-images.githubusercontent.com/3412923/132962314-937aa631-ef01-4bd6-a18b-aebdf3c2b887.png">

Node ID: 0x989e30961c57f8e1b8e760b8c7c9685519480886
Time of notification from MMN: 12:46 EST

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Docker version 18.06.1-ce, build e68fc7a 

Log file attached. 
[myst-node_logs.txt](https://github.com/mysteriumnetwork/node/files/7148560/myst-node_logs.txt)

**Comment by breezytm** [comment]
Issued occurred again. 

Time of notification from MMN: 9:16 EST

[myst-node_logs.txt](https://github.com/mysteriumnetwork/node/files/7148823/myst-node_logs.txt)

**Comment by etherunit** [comment]
I suspect it could be a matter of session start/cleanup and causing node to panic.

```
2021-09-12T01:11:06.145 ERR trace/trace.go:63                        > Stage Provider session create (start) was already started
2021-09-12T01:11:06.145 INF core/service/session_manager.go:276      > Cleaning stale session 4b0f401a-8c3c-451e-96c0-afe672ede76b for 0x00eb00ee5a0b03fb9d1ee04379a5db54d251c8dc consumer
2021-09-12T01:11:06.145 DBG session/pingpong/invoice_tracker.go:641  > Stopping...
2021-09-12T01:11:06.147 DBG consumer/session/session_storage.go:330  > Session 08e1e969-5e7b-4a5a-b0e8-87f5b63409fb saved
2021-09-12T01:11:06.148 ERR trace/trace.go:85                        > Stage  was not started
2021-09-12T01:11:06.148 ERR trace/trace.go:85                        > Stage  was not started
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xd7258a]

goroutine 145412 [running]:
github.com/mysteriumnetwork/node/trace.(*Tracer).EndStage(0xc000809240, 0x0, 0x0)
	/go/src/github.com/mysteriumnetwork/node/trace/trace.go:88 +0x13a
github.com/mysteriumnetwork/node/core/service.(*SessionManager).Start.func2(0xc00000cd20, 0x0, 0x0, 0xc00044e2a0)
	/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:185 +0x50
panic(0x15c3da0, 0x2ad3d40)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/mysteriumnetwork/node/trace.(*Tracer).EndStage(0xc000809240, 0x0, 0x0)
	/go/src/github.com/mysteriumnetwork/node/trace/trace.go:88 +0x13a
github.com/mysteriumnetwork/node/core/service.(*SessionManager).startSession(0xc00044e2a0, 0xc00000cd20, 0x0, 0x0)
	/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:255 +0x1e0
github.com/mysteriumnetwork/node/core/service.(*SessionManager).Start(0xc00044e2a0, 0xc00015f4a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:190 +0x285
github.com/mysteriumnetwork/node/core/service.subscribeSessionCreate.func1(0x1f84ba0, 0xc001227c00, 0xc001030260, 0x12)
	/go/src/github.com/mysteriumnetwork/node/core/service/subscription.go:41 +0x232
github.com/mysteriumnetwork/node/p2p.(*channel).handleRequest(0xc000d48fc0, 0xc00015e910)
	/go/src/github.com/mysteriumnetwork/node/p2p/channel.go:412 +0x195
created by github.com/mysteriumnetwork/node/p2p.(*channel).localReadLoop
	/go/src/github.com/mysteriumnetwork/node/p2p/channel.go:349 +0x1fe
```

**Comment by etherunit** [comment]
Opened a separate thread to address this.

**Comment by breezytm** [comment]
Sometimes the node gets into this weird state. The status reads "Test failed" and the node stops receiving connections even though the service is still available. See screenshot

<img width="1399" alt="Screen Shot 2021-09-14 at 9 19 24 AM" src="https://user-images.githubusercontent.com/3412923/133268113-8a8940f2-88e8-4b25-873d-4983d01e4f00.png">

If I click on "Check connection" as you can see from the screenshot below, the node is reachable. Nonetheless, the server stopped accepting connections since the error was triggered two days ago. 

<img width="1654" alt="Screen Shot 2021-09-14 at 9 41 31 AM" src="https://user-images.githubusercontent.com/3412923/133268586-61581dbb-7ee4-45cb-8370-1502e0f342f2.png">

**Comment by etherunit** [comment]
Please note that our monitoring bot is checking your node every 24 hours. We send ±1GB of data to check your speed and connection health. Every 6 hours we attempt to connect to make sure your node is accessible.
If one of the checks fails, then it marks your node as "Test failed". It will clear status back to "Online" within next successful connection. You can do a manual connection check which will attempt to connect to your Wireguard service. 
If that still doesn't work, try to restart your node.

`sudo systemctl daemon-reload`

`sudo systemctl restart mysterium-node`

**Comment by breezytm** [comment]
I have been doing all of that. The server never recovers once it goes to the "Test failed" status; regardless of whether or not I tried to manually try to check the connection. That is exactly what my comment right above yours is explaining. The only solution thus far has been a restart. This issue occurs multiple times a day. I can't be available all the time to restart it. Clearly, there is a bug somewhere that needs fixing. Perhaps the concept/implementation is buggy. The node should run 24/7 without any issues. I know it is not an issue specific to me because others in the telegram group have complained about the same problem. This results in a lot of losses in potential earnings.

**Comment by etherunit** [comment]
It looks like your node is online now. If you'll still experience "test failed" or "offline" issue, please submit your node logs. It will help us to investigate it further.

**Comment by breezytm** [comment]
I have more than one node experiencing the same issue. 0x989e30961c57f8e1b8e760b8c7c9685519480886

Right now it's stuck on Test failed and even rebooting doesn't seem to be able to get it out of there

**Comment by breezytm** [comment]
This is running on AVADO. Not sure how to grab the logs
