### ISSUE TITLE
Residential bounty not calculating earning from all days this month(september)

### ISSUE THREAD

**Issue by lvlegab1te** [mysteriumnetwork/node#3945]
**Describe the bug**
Residential bounty not calculating earning from all days this month

**To Reproduce**
see screen shots 

**Expected behavior**
Residential bounty should count all session earnings

**Screenshots**
![myst-issue-1](https://user-images.githubusercontent.com/15414696/133170676-8f52f364-c666-4430-b663-00c6e17c1060.png)
![myst-issue-2](https://user-images.githubusercontent.com/15414696/133170683-1ebb2df1-0f1f-4fd0-8a4d-6024ff109896.png)

**Environment (please complete the following information):**
 - Node version: 0.62.1 (since upgraded to 0.63.0)
 - OS: Ubuntu 20.04.3 LTS (Focal Fossa)

**Comment by etherunit** [comment]
@lvlegab1te Can you please provide your node identity address?

**Comment by lvlegab1te** [comment]
Thanks for looking into this Node address is
0xf6539ec593d111e62f2876cefc96e05f13f287c4

**Comment by etherunit** [comment]
It has been adjusted on my.mysterium.network
<img width="1419" alt="Screenshot 2021-09-14 at 08 47 07" src="https://user-images.githubusercontent.com/60128746/133201903-ffd776ed-9299-4fa1-9d4d-fbc147f682ad.png">

**Comment by RowdyMuncher** [comment]
Im having the same issue. Node ID - 0x182c5bc7b8aacada3e59a988ab9a6f8fcf7fa234

**Comment by Arnav-247** [comment]
I'm having the same issue as well, Node ID - 0xeaf6a7ece8746a8c5e11dc0aaba8aa741a223f0d

**Comment by lvlegab1te** [comment]
![Screenshot from 2021-09-20 09-10-16](https://user-images.githubusercontent.com/15414696/133945930-18521d88-8ceb-49f7-952a-a34e223a392d.png)

this has happened again on my node ID 0xf6539ec593d111e62f2876cefc96e05f13f287c4

**Comment by eugenegoncharuk** [comment]
Node ID : 0xf6539ec593d111e62f2876cefc96e05f13f287c4
@lvlegab1te As I see per payout history it's correct. You should see really earned this month MYSTs if you have been paid last month.

**Comment by eugenegoncharuk** [comment]
Node ID : 0xeaf6a7ece8746a8c5e11dc0aaba8aa741a223f0d
@Arnav-247 As I see per payout history it's correct. You should see really earned **this** month MYSTs if you have been paid last month.

**Comment by eugenegoncharuk** [comment]
Node ID : 0x182c5bc7b8aacada3e59a988ab9a6f8fcf7fa234
@RowdyMuncher As I see per payout history it's correct. You should see really earned this month MYSTs if you have been paid last month.

**Comment by eugenegoncharuk** [comment]
Global and Residential earned values for the current month are shown correctly.
