### ISSUE TITLE
Large GiB session missing from MMN. Earnings not reflected in residential bounty.

### ISSUE THREAD

**Issue by Arnav-247** [mysteriumnetwork/node#3947]
**Describe the bug**
I had a large user session (36.98 GiB) over a day from 12/9/2021 to 13/9/2021. The session shows up in the Web UI logs for the node and the correct amount which is 14 MYST is included in the earnings graph and the total earnings in the Web UI but the same session is not visible in the MMN logs and the 14MYST isn't added to the earnings on MMN.

**To Reproduce**
Has only happened once to my knowledge.

**Expected behavior**
I expected the said session to be visible in the MMN logs and the correct amount of MYST added to the earnings on MMN.

**Screenshots**
The session entry on the web UI.
![image](https://user-images.githubusercontent.com/9696861/133202097-6325fcd7-bd1c-4a29-9e5b-34b2c68e526c.png)

Corresponding Change in earnings on the Web UI
![image](https://user-images.githubusercontent.com/9696861/133202254-11883f87-f2e2-44c8-b16b-5406ac13a5f7.png)
![image](https://user-images.githubusercontent.com/9696861/133202269-6c07679e-a2e0-4e67-a573-f5f74af12352.png)

Change not visible on MMN
![image](https://user-images.githubusercontent.com/9696861/133202840-48802450-e235-4355-945e-ada68b2092e6.png)
![image](https://user-images.githubusercontent.com/9696861/133202865-fe712caa-0a06-4e55-be9f-ab4dbb78289d.png)

**Environment (please complete the following information):**
 - Node version: 0.62.1 (Since upgraded to 0.63.0)
 - OS: Raspbian Buster
 - Node ID: 0xeaf6a7ece8746a8c5e11dc0aaba8aa741a223f0d

**Additional context**
One thing to note, I am also facing https://github.com/mysteriumnetwork/node/issues/3945 which is why the earnings in MMN and Web UI don't match up in the screenshots.

**Comment by etherunit** [comment]
Session data indicates no data from consumer (superproxy) has been received: https://testnet3-grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-session=781cf0c3-ff[…]7c4639562c9&var-service_type=All&from=now-7d&to=now
WebUI shows stats collected by a provider but it's not visible on MMN.
