### ISSUE TITLE
MystNodes 1.0 - Don't send email about issue with the residential node when user go to sleep

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/node#3949]
I'm having plenty of notification about issue with my node each day when i basically turn of my laptop and go to sleep. This increase load on the mailer service, make us pay more for it and what more important very annoying.

To handle this, i think, we should add additional settings to node-ui to turn of this sort of notifications, or maybe set time in which turned of node shouldn't make them.

**Comment by Donatas-MN** [comment]
Covered with https://github.com/mysteriumnetwork/mmn/issues/137
