### ISSUE TITLE
Unable to login into NodeUI

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3951]
**Describe the bug**

when using sudo myst reset
does not reset it to the default password
neither does it redirect the node setting to a onboarding page
the problem stays

0x1f6f6e197e645c5ad144819678ec658b03aa9fc2

**To Reproduce**
1. Go to 'NodeUI login page'
2. See error

**Expected behavior**
NodeUI should either accept password or allow for password reset

**Screenshots**

**Environment (please complete the following information):**
OS:Raspbian GNU/Linux 10 (buster)
Architecture:linux/arm
Node version:0.63.0

**Comment by etherunit** [comment]
@isaackielma How do you determine that it's not being reset to defaults?

**Comment by isaackielma** [comment]
@etherunit 

"Thank you for your assistance.



I have tried using the default password ‘mystberry’ after sudo reset, it still gives bad credential error. Also, I have went into my raspi and checked the password file. The encrypted password in the file matches ‘mystberry’ but somehow it gives me bad credential.



Best regards,

Daniel"

**Comment by etherunit** [comment]
Can you please copy>paste the output of `nodeui-pass` file?
You can find it in `/var/lib/mysterium-node/ folder`

**Comment by tomasmik** [comment]
Are you sure that you're resetting the correct credentials? Did you try to run the command with `sudo` privileges? From where did you get the `nodeui-pass` t compare?

**Comment by etherunit** [comment]
Stop the node `sudo systemctl stop mysterium-node.service`

Delete nodeui-pass from dir `/var/lib/mysterium-node/keystore`

Start it again `sudo systemctl start mysterium-node.service`

This should help and force to create a new password for NodeUI.
