### ISSUE TITLE
Remove 'node claim' after myst password reset

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3954]
<img width="624" alt="Screenshot 2021-09-15 at 10 32 28" src="https://user-images.githubusercontent.com/60128746/133391010-fa750017-d5b3-4c0b-88ad-df5235847a77.png">

`Claim this node in my.mysterium.network` feature is optional rather causing confusion. Myst password reset should not unclaim node, therefore provider should not claim it again. I suggest to remove it.

**Comment by Donatas-MN** [comment]
Covered in https://github.com/mysteriumnetwork/node/issues/4046.
