### ISSUE TITLE
Discrepancies in bounty

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3957]
**Describe the bug**
Provider: 0x498a5ad56204b339cf5a38e938c62dcc75a0482b
Earnings graph: 27.21. MYSTT
Bounties: 2.5764 MYSTT 

There was no payment for the month of August so I'm excluding the possibility of reset: 

`2021, August | 18.0663 MYST | outdated / outdated | - | - | Leaderboard positions were ineligible for payment.`
-- | -- | -- | -- | -- | --

<img width="996" alt="Screenshot 2021-09-16 at 08 39 39" src="https://user-images.githubusercontent.com/60128746/133556414-dba706c0-a629-4e49-92c8-6b2a5ee737c3.png">

**Comment by etherunit** [comment]
Similar issue for 0xeaf6a7ece8746a8c5e11dc0aaba8aa741a223f0d

**Comment by tomasmik** [comment]
> 0xeaf6a7ece8746a8c5e11dc0aaba8aa741a223f0d

This one did receive a bounty payout of 100.

**Comment by pianoman10** [comment]
Something similar for me, the statistics and bounty does not make sense for me. I only have Global bounty, not residential, but lots of MYSTT disappeared at some point in the last few days. Last month (August) I received a payout of 30 MYST on this one
Identity: 0x883782c2a9dced2db849ef8ce9bc16eccdbab2b4

![Screenshot 2021-09-16 at 11 58 35](https://user-images.githubusercontent.com/80623961/133593813-388a838d-95b0-42f3-978f-e096ca00cdb9.jpg)
![Screenshot 2021-09-16 at 11 58 05](https://user-images.githubusercontent.com/80623961/133593817-6ab837b8-d140-4567-8570-ba7bde5b9a78.jpg)

**Comment by tytusandronicus** [comment]
Same situation in my node: 0x4a152bad05b12f3028f141a1ddafb7c72d6b555f
![22](https://user-images.githubusercontent.com/22968117/133610456-49c0a480-aa09-4b7a-9444-d75d195a1d5a.png)

**Comment by invme247** [comment]
> 
> 
> Seems like the earnings graph might be at fault in the first case.
> 
> > 0xeaf6a7ece8746a8c5e11dc0aaba8aa741a223f0d
> 
> This one did receive a bounty payout of 100.

Hi, The first one is my node. How the graph is in fault when I have been running this node over one month and earned about 22 MYST? Suddenly all my MYST is gone. The graph is showing it right  and not the residential/global bounty. 
Thanks,

**Comment by RowdyMuncher** [comment]
I have the same issue that I lost a lot of Residential MYST earnings as well. Can this be fixed please.

Node ID: 0x182c5bc7b8aacada3e59a988ab9a6f8fcf7fa234

**Comment by eugenegoncharuk** [comment]
As I see per payout history it's correct. You should see really earned this month MYSTs if you have been paid last month.

**Comment by invme247** [comment]
@eugenegoncharuk  not sure who you are referring to here as multiple people complaining about it after this issue was logged because of missing MYST for my node (Provider: 0x498a5ad56204b339cf5a38e938c62dcc75a0482b) . If you see my payout history I was never paid. My guess was my accumulation of MYST was low. However even with 27MYST suddenly all my MYST was wiped out after the update. I was hoping to get those back. 

![image](https://user-images.githubusercontent.com/90883072/134708513-07877d2c-65b0-46a4-95b9-0ffc297913eb.png)

**Comment by invme247** [comment]
![wd](https://user-images.githubusercontent.com/90883072/134709329-aacc033c-a10e-41c6-8fcd-3fd86e808152.JPG)
