### ISSUE TITLE
NodeUI - Settlement improvements for better UX

### ISSUE THREAD

**Issue by mdomasevicius** [mysteriumnetwork/node#3962]
After performing a withdraw there is currently very limited settlement tracking capabilities. From Node runner perspective - broken UX.

Cases:
- withdrawal initiated, node shuts down, settlement history has a record of pending settlement.

- node crashes during withdrawal, transaction is sent to block-chain but not recorded in DB (big stretch but maybe doing whole sync would be an option?)

**Comment by vkuznecovas** [comment]
I've currently monkey patched the settlement info to include a withdrawal flag. However, a proper flow should be implemented where it goes something like that:

When a settlement or withdrawal occurs, an entry should be created in the boltdb settlement collection with the queue id that is returned from the transactor. The status should be then continuously updated and transaction info added when transactor returns the appropriate info. The current limitation for this is that the settlement info is stored with the transaction hash as the ID for the entry, however, the transaction hash is only known AFTER it has been submitted by transactor. The ID should be changed to accommodate for such flow.

On the startup of node, the settlement collection should be checked for incompleted settlements and re-synced with transactor. This can be done by handling the node startup events.
