### ISSUE TITLE
Payment in progress. It should reach you before 2021-09-07. Not reached yet

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#3963]
**Describe the bug**
Node ID: 0x9cccbc4cd4d02e4d060259945e82cc88b0cc243c

Provider should have been paid on the 7th of the month but still has not been processed 

**To Reproduce**
1. Go to 'MMN dashboard'
2. Click on 'Bounty payout history'
3. Scroll down to 'September'
4. See error 'Payment in progress. It should reach you before 2021-09-07'

**Expected behavior**
Ideally payment should have been processed before the 7th of the month.

**Screenshots**
<img width="1386" alt="Screenshot 2021-09-16 at 17 17 28" src="https://user-images.githubusercontent.com/84313603/133648953-bcbb5818-7b92-4c19-9915-322d3ff2a105.png">

**Environment (please complete the following information):**
OS: Ubuntu 20.04.2 LTS
Architecture: linux/amd64
Node version: 0.62.1

**Additional context**

**Comment by eugenegoncharuk** [comment]
@tomasmik We need to make a payment to this user in the amount of 12.3135 MYST. When done, please, ping me.

**Comment by tomasmik** [comment]
We can include this in the next payment cycle if thats ok. It will paid next week.

**Comment by eugenegoncharuk** [comment]
For September auto paid and in Etherscan we see the correct amount.
