### ISSUE TITLE
Cannot listen on UDP port :: error="listen udp :: bind: address already in use"

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3967]
**Describe the bug**

Provider id: 0x3712b4009a8c3372f370c79f766a306683e42d53

Service is still responsive - serving **multiple connections** at once, but provider is seeing these warnings in the logs.

```
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.179 INF core/port/availability.go:37             > Cannot listen on UDP port 32936 error="listen udp :32936: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.179 INF core/port/availability.go:37             > Cannot listen on UDP port 10000 error="listen udp :10000: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.179 INF core/port/availability.go:37             > Cannot listen on UDP port 10001 error="listen udp :10001: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.179 INF core/port/availability.go:37             > Cannot listen on UDP port 10002 error="listen udp :10002: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.180 INF core/port/availability.go:37             > Cannot listen on UDP port 10003 error="listen udp :10003: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.180 INF core/port/availability.go:37             > Cannot listen on UDP port 10004 error="listen udp :10004: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.180 INF core/port/availability.go:37             > Cannot listen on UDP port 10005 error="listen udp :10005: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.180 INF core/port/availability.go:37             > Cannot listen on UDP port 10006 error="listen udp :10006: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.180 INF core/port/availability.go:37             > Cannot listen on UDP port 10007 error="listen udp :10007: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.180 INF core/port/availability.go:37             > Cannot listen on UDP port 10008 error="listen udp :10008: bind: address already in use"
Sep 16 16:28:39 nas myst[1024972]: 2021-09-16T16:28:39.181 INF core/port/availability.go:37             > Cannot listen on UDP port 10009 error="listen udp :10009: bind: address already in use"
```

**Environment:**
 - Node version: 0.63.0
 - OS: Ubuntu 20.04.3 LTS

**Additional context**
[myst_logs.txt](https://github.com/mysteriumnetwork/node/files/7194017/myst_logs.txt)
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7194018/mysterium-node.log)

**Comment by creotiv** [comment]
@etherunit can you ask them to update node to 0.65.0 (we had couple of fixes for connections there). And if problem will arise again write here. And also send output from `lsof -n`

**Comment by breezytm** [comment]
After upgrading to 0.65.0 I can't get my node to stay online.
Error: Test Failed
[myst_logs.txt](https://github.com/mysteriumnetwork/node/files/7229279/myst_logs.txt)
ed

**Comment by Peter-SovietSquirrel** [comment]
> @etherunit can you ask them to update node to 0.65.0 (we had couple of fixes for connections there). And if problem will arise again write here. And also send output from `lsof -n`

[INFO] Uptime: 132h36m55.673627243s
[INFO] Process: 588
[INFO] Version: 0.65.0
[INFO] Branch: 0.65.0. Build id: 374344242. Commit: f69741d2

Sep 26 22:53:05 raspberrypi myst[588]: 2021-09-26T22:53:05.075 INF source/core/port/availability.go:37      > Cannot listen on UDP port 52010 error="listen udp :52010: bind: address already in use"

Node has gone from Online to Test Failed/Offline without user input.
[lsof.txt](https://github.com/mysteriumnetwork/node/files/7232808/lsof.txt)
[newlog.txt](https://github.com/mysteriumnetwork/node/files/7232809/newlog.txt)
