### ISSUE TITLE
Local Gui Non Responsive 

### ISSUE THREAD

**Issue by nefiwashere** [mysteriumnetwork/node#3988]
**Describe the bug**
after several hours or min local Gui is non responsive.  In MMN is see that its online but there is no traffic through it. I check my router and dont see any data transfers.   i can restart the node and get user connections than same issue happens

**To Reproduce**
just plug it in and power up.   Login to local gui and its fine will start seeing connections.  Give it time and the Local Gui is non responsive.

**Expected behavior**
no access to Local Gui.   Node is online in MMN.  Disconnects any current connections.  No data transfers by checking Router.

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 0.65.0
 - OS: raspbian buster 
 
**Additional context**
tried New os pi install. Tested on another pi. same results.

**Comment by etherunit** [comment]
@nefiwashere Could you submit your node logs? It would help us a lot.
https://docs.mysterium.network/node-runners/troubleshooting/#reporting-an-issue

**Comment by nefiwashere** [comment]
> @nefiwashere Could you submit your node logs? It would help us a lot.
> https://docs.mysterium.network/node-runners/troubleshooting/#reporting-an-issue

[](https://drive.google.com/file/d/1thF6OLwH5daeXJLzHyP5hTzmbtTWBw28/view?usp=sharing)
https://drive.google.com/file/d/1o_v9O8Ra4X7_rpjKJbrm31m75cU6JtLr/view?usp=sharing[](url)

**Comment by nefiwashere** [comment]
![image](https://user-images.githubusercontent.com/10413814/135458347-39a346e4-c1c5-4c21-81f0-c09931bee9ce.png)
