### ISSUE TITLE
Your identity is being registered, please be patient...

### ISSUE THREAD

**Issue by shirubei** [mysteriumnetwork/node#3994]
Planned to create 10 nodes using DigitalOcean VPS, 8 successed and two failed.
Both stucked at the message "Your identity is being registered, please be patient..." when I try to open the dashboard.
Please help me get out of this status.
I am completed new to this project, a step by step operation note/ command line will be appreciated.
Thanks.

NodeID1:0x545888592d1a3fe162cc7aacc8e0fbe7fad40937
NodeID2:0xc50c1b94be9a8d1fc3b7dfdbcc03db5144bb095f

Environment :
 - Node version: 0.65.0
 - OS: Ubuntu 20.04(LTS) x64 under DigitalOcean VPS

**Comment by Alshukaily** [comment]
Same here this is my first time same problem "Your identity is being registered, please be patient"
Node is in linux and it's status seems like it's working

**Comment by isaackielma** [comment]
Node ID:
0xbc7e66c8b0597981a99ef1d880d4eaa919d0568e

Also experiencing this same issue for over 12 hours "Your identity is being registered, please be patient"

**Comment by pmatheus** [comment]
Node ID:
0x82409a28fde1d1f29d6578f4b648fe49386b4347

Also experiencing this same issue for over 6h "Your identity is being registered, please be patient..."

**Comment by airyariv** [comment]
same here:
0xf57206528c054934cffcb9bfdfc8d4e7d2f8c95f

**Comment by airyariv** [comment]
Same here:

0x9e9f16f003c152004cabdec805fe5eff01cae046

Also, i have issues with this one, always disconnecting:

0xf57206528c054934cffcb9bfdfc8d4e7d2f8c95f

Do you have a command to uninstall the node on terminal (mac)?
i have 2 out of 10 causing problems

thank u!

**Comment by tomasmik** [comment]
This should now be solved. Thanks for reporting.

**Comment by shirubei** [comment]
> This should now be solved. Thanks for reporting.

so what's the solution of so many people? Please help.
I do not think it can be closed without any solution.

**Comment by tomasmik** [comment]
The cause of this was solved, any pending or previous registrations requests will have to be resent. That should happen automatically, but if thats not the case please resend the requests yourself using the CLI:
```
myst cli identities list
...
myst cli identities unlock X
...
myst cli identities register X
```

Or remove the node together with all it's user data and install it again.

**Comment by shirubei** [comment]
Thank you for the solution. Get it.

**Comment by airyariv** [comment]
Hi Tomas,
fantastic
it worked fine manually.
Thanks a lot.

so, now i have 9 working perfectly out of 10.
The problem with 1 of my nodes is that it disconnects after  few mn. ( 0xf57206528c054934cffcb9bfdfc8d4e7d2f8c95f )

I have tried to reboot the VPS several times: it reconnects for a couple of mn and disconnects again.
I would like to uninstall the node from the vps and reinstall, but I dont know the command line.

FYI i'm using TERMINAL on MAC to access to my VPS.
Installation was done with the following command lines:

sudo apt-get install curl

sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"


I'm just looking for an uninstall command line.
thank u
