### ISSUE TITLE
User should never be disconnected (and his IP exposed) when kill-switch is enabled

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3997]
It seems there are scenarios, when this still happens, as per https://github.com/mysteriumnetwork/node/issues/3986

In this case, if user's balance depletes, his connection should be suspended, but he shouldn't be disconnected (and thus IP exposed).

Would be good to think about more scenarios when kill-switch might not work as expected.

**Comment by tomasmik** [comment]
If you actually read through the logs it seems that connection went to `OnHold` which is the expected behavior and the user just described it in such a way where it looks like he actually disconnected. Unless I'm not seeing something that you are - in that case please point it out.

**Comment by cvl** [comment]
That's great. I was relying on user description.
