### ISSUE TITLE
L2 RPC URLs remove after default settings restored in Web UI

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#4000]
**Describe the bug**
L2 RPC URLs got removed after default settings were restored in Web UI

**To Reproduce**
1. Go to Web UI
2. Click on Advanced Settings
3. Click on Restore Defaults 

**Expected behavior**
L2 RPC URLs will be missing

**Screenshots**
![image](https://user-images.githubusercontent.com/79473923/134929172-91487aae-ea70-4533-9803-c1c4dede6d99.png)

**Environment (please complete the following information):**
 - Node version: 0.65.0
 - Web UI version: 0.4.4
 - OS: Raspbian GNU/Linux 10 (buster)

**Comment by Jayto1** [comment]
**Update:** Restarting my node did not restore the URLs even though it says **(Requires NODE restart)**

**Comment by tomasmik** [comment]
I think you just misunderstood. Default for this box is actually - empty.
This does not override the URLs, it just extends the list with your own URLs to use. So after restoring the defaults this is supposed to be empty as you cannot change the default ones and they are not displayed.

If you execute config show and grep for l2 you will see that everything is still there:
```
$ myst config show | grep l2
client.rpcl2: [https://mumbai1.mysterium.network/ https://mumbai2.mysterium.network/]
```

**Comment by Jayto1** [comment]
Ah ok thank you for clearing this up Tomas, I got confused because for some reason my box had some entries in it. Thanks for clearing things up.
