### ISSUE TITLE
Test pingpong.TestConsumerBalanceTracker_FallsBackToTransactorIfInProgress is unstable

### ISSUE THREAD

**Issue by Snawoot** [mysteriumnetwork/node#4002]
It seems eventually consumer balance tracker resorts to payment channel, rather than transactor and stays that way. Test only works successfully if assertion check falls into small time window when balance was set from transactor. After single balance update (no matter from which source), balance update from transactor is not possible anymore because transactor aligning method skips any update if balance already defined.

We need to either make it stable, or remove if it's not that important.

Steps to reproduce:

```sh
go test -race -v -count 100 -run TestConsumerBalanceTracker_FallsBackToTransactorIfInProgress ./session/pingpong |& less
```

**Comment by tomasmik** [comment]
Should be solved by: https://github.com/mysteriumnetwork/node/pull/4004
