### ISSUE TITLE
Node issue

### ISSUE THREAD

**Issue by mulder2222** [mysteriumnetwork/node#4003]
I am getting emails which says there is an issue with my node. "Our monitoring agent tried to connect to your node, but something went wrong."

**Screenshots**
Log file:
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.601 ??? vendor/github.com/rs/zerolog/log.go:403  > Cannot find device "ifb0"
Sep 27 19:44:20 raspberrypi sudo[1090]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1090]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev ifb0 ingress
Sep 27 19:44:20 raspberrypi sudo[1086]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.559 ??? vendor/github.com/rs/zerolog/log.go:403  > Cannot find device "ifb0"
Sep 27 19:44:20 raspberrypi sudo[1086]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1086]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev ifb0 root
Sep 27 19:44:20 raspberrypi sudo[1084]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.525 ??? vendor/github.com/rs/zerolog/log.go:403  > Error: Cannot find specified qdisc on specified device.
Sep 27 19:44:20 raspberrypi sudo[1084]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1084]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev tun0 ingress
Sep 27 19:44:20 raspberrypi sudo[1078]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.497 ??? vendor/github.com/rs/zerolog/log.go:403  > Error: Cannot delete qdisc with handle of zero.
Sep 27 19:44:20 raspberrypi sudo[1078]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1078]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev tun0 root
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.308 INF nat/service_iptables.go:71               > Setting up NAT/Firewall rules... done
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.307 DBG nat/service_iptables.go:201              > "/usr/sbin/iptables -A FORWARD --destination 10.8.0.0/24 --jump ACCEPT" output:
Sep 27 19:44:20 raspberrypi sudo[1070]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi sudo[1070]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1070]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/iptables -A FORWARD --destination 10.8.0.0/24 --jump ACCEPT
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.263 DBG nat/service_iptables.go:201              > "/usr/sbin/iptables -A FORWARD --source 10.8.0.0/24 --jump ACCEPT" output:
Sep 27 19:44:20 raspberrypi sudo[1060]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi sudo[1060]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1060]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/iptables -A FORWARD --source 10.8.0.0/24 --jump ACCEPT
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.228 DBG nat/service_iptables.go:201              > "/usr/sbin/iptables -A POSTROUTING --source 10.8.0.0/24 ! --destination 10.8.0.0
Sep 27 19:44:20 raspberrypi sudo[1054]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi sudo[1054]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1054]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/iptables -A POSTROUTING --source 10.8.0.0/24 ! --destination 10.8.0.0/24 --jump S
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.176 DBG nat/service_iptables.go:201              > "/usr/sbin/iptables -A INPUT --source 10.8.0.0/24 --destination 127.0.0.0/8 --ju
Sep 27 19:44:20 raspberrypi sudo[1049]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi sudo[1049]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1049]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/iptables -A INPUT --source 10.8.0.0/24 --destination 127.0.0.0/8 --jump DROP
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.139 DBG nat/service_iptables.go:201              > "/usr/sbin/iptables -A FORWARD --source 10.8.0.0/24 --destination 127.0.0.0/8 --
Sep 27 19:44:20 raspberrypi sudo[1046]: pam_unix(sudo:session): session closed for user root
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.131 INF nat/upnp/discover.go:60                  > UPnP gateway detected map[deviceType:urn:schemas-upnp-org:device:InternetGateway
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.130 INF nat/upnp/discover.go:58                  > UPnP gateways detected: 1
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.128 DBG nat/upnp/discover.go:90                  > not a gateway device: map[deviceType:urn:dial-multiscreen-org:device:dial:1 frie
Sep 27 19:44:20 raspberrypi sudo[1046]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 27 19:44:20 raspberrypi sudo[1046]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/iptables -A FORWARD --source 10.8.0.0/24 --destination 127.0.0.0/8 --jump DROP
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.093 DBG nat/upnp/discover.go:90                  > not a gateway device: map[deviceType:urn:schemas-upnp-org:device:Basic:1 friendl
Sep 27 19:44:20 raspberrypi myst[631]: 2021-09-27T19:44:20.090 DBG nat/service_iptables.go:201              > "/usr/sbin/iptables -A INPUT --source 10.8.0.0/24 --destination 192.168.0.0/16 -

**Environment (please complete the following information):**
 - Node version: 0.53.2
 - OS: Raspbian GNU/Linux 10 (buster)

**Comment by etherunit** [comment]
Could you try to update your node to v0.66 (https://github.com/mysteriumnetwork/node/releases/tag/0.66.0) and see if this issue still present?
