### ISSUE TITLE
Wallet address for node was not set in MMN but still saved in local cache

### ISSUE THREAD

**Issue by iovestor** [mysteriumnetwork/node#4005]
**Describe the bug**
Node wallet address in my.mysterium.network is empty

**To Reproduce**
1. Go to 'https://my.mysterium.network/'
2. Click on 'Profile > Payment information'
3. Scroll down to 'Node wallet'
4. See error 'Wallet address is empty'

**Expected behavior**
In the Node UI the wallet address is populated in 'Settings > Bounty Payout Address'. I would expect the same address to be visible in my.mysterium.network.

**Screenshots**
I add screenshots from my.mysterium.network and Node UI.

**Environment (please complete the following information):**
 - Node version: 0.65.0
 - WebUI version: 0.4.4
 - OS: Linux Lite 5.2, Kernel 5.4.0-80

**Additional context**
Node Id: 0x5f9640129e7cbf5e0c1bc73226bfda66dbf4654
![MMN_Wallet](https://user-images.githubusercontent.com/91537616/135078851-cd1cf186-8f38-4ff1-9f16-e8094efd5aa5.jpg)
b
![NodeUI_Settings](https://user-images.githubusercontent.com/91537616/135078874-3c7c710f-8a42-4a8f-ace7-571ee345ceaf.jpg)

**Comment by tomasmik** [comment]
Did you set the address or was it just migrated from testnet2 to testnet3?
This should resolve itself if you click save again or set it to a different and back to this address.

The cause for this is unknown and I'm investigating it. Any additional details would help. Thanks.

**Comment by iovestor** [comment]
The address/node was migrated from testnet2 to testnet3 and then back to testnet2. After opening the issue I updated the node to version 0.66.0.
Just clicking the SAVE button seems to have no effect. Entering another valid ERC-20 address and clicking SAVE sets the address in MMN.

**Comment by tomasmik** [comment]
> Just clicking the SAVE button seems to have no effect. Entering another valid ERC-20 address and clicking SAVE sets the address in MMN.

Right, so as a temporary fix, this should work. For the cause of it, we'll check and make some fixes.

**Comment by tomasmik** [comment]
Should now be fixed.
