### ISSUE TITLE
Unable to create a new node

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4010]
**Describe the bug**
After getting several complains that on-boarding a new node is not possible with 0.66.1, made a test and faced the same problem completing it both in UI & CLI.

CLI: 
```
mmn 0HeOP7t8WmjK5zLewRKY69nSqjtvozKr6N4pe...
[ERROR] Failed to set MMN API key: EOF 

```
NodeUI: 
```
Error
Request failed with status code 500 (path="mmn/api-key")
```

**Screenshots**
<img width="530" alt="Screenshot 2021-09-29 at 07 51 53" src="https://user-images.githubusercontent.com/60128746/135205675-55085396-25b6-4187-acac-8f20b05dda2e.png">

**Environment (please complete the following information):**
 - Node version: 0.66.1
 - OS: Ubuntu

**Comment by tomasmik** [comment]
Tested, seems to work with the latest build now.
