### ISSUE TITLE
Update from 0.65.1 to 0.66.1 - Node UI does not work

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#4012]
**Describe the bug**
Last night the node automatically updated to 0.66.1.
Now I see that the Node UI does not work (I see a blank screen).
I tried to reboot the node, but nothing has changed.

**Environment (please complete the following information):**
 - Node version: 0.66.1
 - OS: Raspbian

**Comment by tomasmik** [comment]
We're aware of this, there has been a new version released - [0.66.2](https://github.com/mysteriumnetwork/node/releases/tag/0.66.2)

It should be available to upgrade to soon.

**Comment by lollapalooza1973** [comment]
Thank you.

**Comment by lollapalooza1973** [comment]
I have updated the node to 0.66.2, nothing has changed.

**Comment by tomasmik** [comment]
Have you tried clearing cache or using incognito to access it? Might be something cached on your side.

**Comment by lollapalooza1973** [comment]
> Have you tried clearing cache or using incognito to access it? Might be something cached on your side.

You're right... it worked!
Thanks
