### ISSUE TITLE
Index out of range in 0.66-1 alpine release

### ISSUE THREAD

**Issue by chriolant** [mysteriumnetwork/node#4013]
After I updated to the latest build, it seems that there is a panic and the container restarts itself repeatedly. Anyone else facing this issue?

> panic: runtime error: index out of range [1] with length 1
> goroutine 427 [running]:
>
> github.com/mysteriumnetwork/node/mmn.(*MMN).register(0xc0004d1c00, 0x180efe2, 0xb)
>
> /go/src/github.com/mysteriumnetwork/node/mmn/mmn.go:104 +0x643
>
> github.com/mysteriumnetwork/node/mmn.(*MMN).handleServiceStart(0xc0004d1c00, 0xc000bcd290, 0x24, 0xc000a1e8d0, 0x2a, 0xc0004a88e0, 0x9, 0x18083da, 0x7)
>
> /go/src/github.com/mysteriumnetwork/node/mmn/mmn.go:94 +0x96
>
> reflect.Value.call(0x1526ce0, 0xc000af3ad0, 0x13, 0x1804338, 0x4, 0xc0007072e0, 0x1, 0x1, 0x0, 0x16d8180, ...)
>
> /usr/local/go/src/reflect/value.go:460 +0x5f6
>
> reflect.Value.Call(0x1526ce0, 0xc000af3ad0, 0x13, 0xc0007072e0, 0x1, 0x1, 0xc0007072e0, 0x1, 0x1)
>
> /usr/local/go/src/reflect/value.go:321 +0xb4
>
> github.com/asaskevich/EventBus.(*EventBus).doPublish(0xc000830fe0, 0xc000aa5a40, 0x1812e02, 0xe, 0xc0008210f0, 0x1, 0x1)
>
> /go/pkg/mod/github.com/asaskevich/!event!bus@v0.0.0-20180315140547-d46933a94f05/event_bus.go:158 +0xa8
>
> github.com/asaskevich/EventBus.(*EventBus).doPublishAsync(0xc000830fe0, 0xc000aa5a40, 0x1812e02, 0xe, 0xc0008210f0, 0x1, 0x1)
>
> /go/pkg/mod/github.com/asaskevich/!event!bus@v0.0.0-20180315140547-d46933a94f05/event_bus.go:166 +0xd7
>
> created by github.com/asaskevich/EventBus.(*EventBus).Publish
>
> /go/pkg/mod/github.com/asaskevich/!event!bus@v0.0.0-20180315140547-d46933a94f05/event_bus.go:150 +0x25b`

**Comment by soffokl** [comment]
This is already resolved in 0.66.2. Please try to use the newest version.
