### ISSUE TITLE
Web UI - Global Bounty - Your node is sharing an IP subnet.

### ISSUE THREAD

**Issue by foxtrotdev** [mysteriumnetwork/node#4019]
**Describe the bug**
I run several VPS machines. Today I noticed that three of them have exclamation mark for global bounty.
It says: Your node is sharing an IP subnet.

**To Reproduce**
1. Create a new VPS
2. Install myst
3. Wait 1 day

**Expected behavior**
To do not see this error message.

**Screenshots**

Pic. 1 - Web UI

<img width="799" alt="Zrzut ekranu 2021-10-1 o 14 02 33" src="https://user-images.githubusercontent.com/35732606/135617128-cc458265-7eb0-4c65-b564-18fff50e09b1.png">

Pic. 2 - VPS machines

<img width="61" alt="Zrzut ekranu 2021-10-1 o 14 02 49" src="https://user-images.githubusercontent.com/35732606/135617187-69475e91-b3e7-4a11-8806-b2e7be7b1d4f.png">

**Environment (please complete the following information):**
 - Node version: 0.66.3
 - OS: Ubuntu 20 LTS

**Additional context**
My VPS provider generates different VPS machines. It is strange that I get such message right now.

**Comment by etherunit** [comment]
Could you provide your node id?

**Comment by Donatas-MN** [comment]
We have a rule that using IP from the same subnet is not allowed in Testnet (as described in Bounty rules). This restriction will be lifted with MainNet release.
