### ISSUE TITLE
MMN dashboard not displaying nodes

### ISSUE THREAD

**Issue by icmono** [mysteriumnetwork/node#4045]
https://my.mysterium.network/dashboard nod loading nodes.
Accessing https://my.mysterium.network/api/frontend/nodes directly loads a json with all nodes.

There are 100 nodes on this account.

![Screenshot from 2021-10-05 15-31-39](https://user-images.githubusercontent.com/12896725/136023248-e5fc793f-a670-482c-8b41-7e6f66218acc.png)
![Screenshot from 2021-10-05 15-32-05](https://user-images.githubusercontent.com/12896725/136023264-30125567-c624-41b5-bf9a-cf6e17778d5f.png)

This is the same issue from #3898

**Comment by Donatas-MN** [comment]
List is rendered by React component which is fetching nodes list periodically, so it's probably issue in this component.
