### ISSUE TITLE
Node partially offline, but keep sending proposals to broker

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#4049]
**Describe the bug**
Node v0.66.3 
0xa56879b4c1eeb6d4f5a06e421ad7b72858aa28cf running Raspbian GNU/Linux 10 (buster) seems to be partially offline.

It keeps sending proposals to the broker, so it's visible in discovery. 
But nothing else seems working on the provider side. It does not send metrics, it does not accept connections, even does not respond to messages via the broker. 

There might be more nodes affected by this. This could cause multiple problems with connections if this happening a lot. 

The monitoring agent will mark such node as test failed eventually, but it will take 24h before we do this.

**Comment by Donatas-MN** [comment]
Node seems to be fine now: https://mainnet-grafana.mysterium.network/d/n3xeQlgMz/provider?orgId=1&var-provider=0xa56879b4c1eeb6d4f5a06e421ad7b72858aa28cf&var-service_type=All&from=now-30d&to=now
