### ISSUE TITLE
[mac] can't connect to node after lid is closed & reopened

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4051]
**Describe the bug**
- Run the app
- Close Mac lid, then reopen it after a while
- The app can't connect to node anymore

I assume that somehow node is getting suspended when lid is closed, and app can't connect to it after revoked, yet the port is still taken by the (inactive) node.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7292037/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.62.1
 - OS: Mac

**Comment by soffokl** [comment]
This looks like duplicate of https://github.com/mysteriumnetwork/node/issues/4051

**Comment by cvl** [comment]
Hehe nice trick :)

**Comment by cvl** [comment]
On a serious note: could you reopen this? I don't have the permission rights.
