### ISSUE TITLE
Ethereum top up fail issue

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4059]
**Describe the bug**

Sent around 15$ in eth to purchase 20myst and It never arrived. i sent the eth to the eth address provided to me, I sent this around 2 days ago and still do not have my top up?"
**To Reproduce**

https://etherscan.io/tx/0x103267b57e9e7b43b4957d712e282b8665c3beb5d039ec838865965de114acba'

**Expected behavior**
Top up should land in user's balance after a few minutes.

**Screenshots**

![Uploading Screenshot 2021-10-07 at 15.43.11.png…]()**Environment (please complete the following information):**
<img width="1083" alt="Screenshot 2021-10-07 at 15 43 11" src="https://user-images.githubusercontent.com/84313603/136407913-253ed5bc-db2b-4235-acbb-f2c112e4ed4c.png">"

**Additional context**
https://etherscan.io/tx/0x103267b57e9e7b43b4957d712e282b8665c3beb5d039ec838865965de114acba

**Comment by Numberedd** [comment]
This is also my Mysterium ID (if you need it)

0xd56e933d17e95dfde98790047e04a2d62fe3cf68

**Comment by tomasmik** [comment]
Right.. I only saw the [0x103267b57e9e7b43b4957d712e282b8665c3beb5d039ec838865965de114acba ](https://etherscan.io/tx/0x103267b57e9e7b43b4957d712e282b8665c3beb5d039ec838865965de114acba) transaction. Seems like the one you just mentioned isn't accounted for. Let me check again and get back to you. Sorry this is taking so long.

**Comment by Numberedd** [comment]
The 15 dollay payment I sent wasn't to you guys... My friend sent me the 15 dollars to pay for the vpn. I clicked on "send all" to the address of the vpn if that makes sense.

**Comment by tomasmik** [comment]
Ok, so as I said, when topping up you had to cover the network fees. In result you've only actually transferred `
0.000437448432048148 Ether` which is not enough to cover for the payment.

Look in to your [original transaction](https://etherscan.io/tx/0x103267b57e9e7b43b4957d712e282b8665c3beb5d039ec838865965de114acba) you did pay the 15 dollars, just that most of it went in to fees. :)

So as I said before, we can send you the MYST for the actual value transferred. We are adding cheaper top up options that dont require such huge amounts of money to cover for fees.
