### ISSUE TITLE
Node ranked at #11 in the Global Bounty, despite earnings are greater then node 1st position

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#4066]
**Describe the bug**
My node is listed in position # 11, despite it has earned more Myst than the node at position # 1.

**To Reproduce**
Check the Global Bounty page in Mysterium website, country Italy.

**Expected behavior**
I would expect to be listed at position # 1.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/34000198/136655076-bc4fba1f-1855-4354-a968-65e4a8baff7d.png)
![immagine](https://user-images.githubusercontent.com/34000198/136655085-4b2c1fef-4797-4b50-939e-fb72e8d598ef.png)

**Environment (please complete the following information):**
 - Node 0.66.4
 - OS: Raspbian

**Comment by Donatas-MN** [comment]
@lollapalooza1973 could you provide your node ID?

**Comment by lollapalooza1973** [comment]
Node ID is 0x641cb8019932b0fc112eeb1c265a4e93811c9086.
Same situation is happening now... my node has earned 33 Myst, but it's listed at position #11
The Top 5 in my country have earned less than 1 Myst.

![image](https://user-images.githubusercontent.com/34000198/140281500-0309b66d-82d4-4a49-8223-8000d2300736.png)

![image](https://user-images.githubusercontent.com/34000198/140281563-20f6a4a8-3ca9-4831-8a0f-496ca5fa85c3.png)

**Comment by Donatas-MN** [comment]
Positions are actually correct, it's just a visual glitch. Users who did not get Global bounty paid last month carry their amounts to next month. Dashboard positions are ranked on total amount, so those with remaining balance are on top in the beginning of the month.

**Comment by lollapalooza1973** [comment]
In this case I believe that the total amount should be shown on the dashboard.
It's a matter of transparency.

**Comment by Donatas-MN** [comment]
Yes, I agree, we will try to address this.
