### ISSUE TITLE
What's the status of the project?

### ISSUE THREAD

**Issue by arminnaderi** [mysteriumnetwork/node#407]
What's the status of the project? What's the simple architecture of this project? What things are you guys having difficulty with?

**Comment by vkuznecovas** [comment]
Hello @arminnaderi, sorry for the long time with no response.

The project is being actively developed by the core team with current focus on finding a VPN solution that will work on desktops and mobile devices. We're looking into openvpn3 and wireguard as possibilities. 

In parallel, we're working on enabling crypto payment functionality to incentivise service providers and improving our open source processes.

At the moment we do not have a great way of showing the architecture but we do have plans to improve the projects wiki with all the relevant info. The short version though - this project, node, is the core of the Mysterium VPN. It's a cross platform tool that can act both as a provider and as a consumer. It enables providers to act as VPN providers and enables consumers to connect to the running providers.

Currently, the biggest struggle is getting openvpn3 and Go to shake hands on all the platforms.

**Comment by Waldz** [comment]
We have a lot tickets with label [help wanted](https://github.com/mysteriumnetwork/node/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
Feel free to look at them ;)

**Comment by arminnaderi** [comment]
A bit more of a specific question: How does the node guarantee privacy? How does it guarantee a provider doesn't snoop on the VPN consumers? How many providers is the connection routed through? One? Multiple? All?
