### ISSUE TITLE
Unrewarded data transfers

### ISSUE THREAD

**Issue by Csmflow** [mysteriumnetwork/node#4071]
**Describe the bug**
Was asked by Isaac to file this report.
Some data transfer sessions received no Myst rewards) on node 0x8826bceb9697ebc7c958075c33b02ab15b7e00be.
The affected sessions ID's are:
1. 463e2f03-f84f-40c9-ad2f-20794d5afca9 
2. aeaa6ccf-3242-4e64-9cf6-614a94e21099
3. 679adf0a-4867-4fa1-9b42-cff7786f2866 
4. 65b99bf4-0dd4-4cee-95bb-814d2a1de66d
5. 3268ecf7-cb26-477c-8182-c542c8dd684a
6. 40f8be1d-5b7b-4b02-bda6-f772a6f6d5b6
7. c82be0e4-2897-4306-94ec-604cd4038838
8. 1d8cf306-c503-4d8a-9318-4e9b8bc7b6f3
9. 6cbcd2ea-afef-4d32-ae67-89a6e570f0a6
10. 2979c941-e609-40de-941b-31d1828f1745
11. 7e7c0eb1-67de-4fd8-99dc-0daee8688b62
12. 898f55ef-bb00-47f7-a7d5-d5ef356c36b3
13. a939695f-d53e-44a6-9d05-f4e636917998
14. ea4a600a-39a0-4f6c-b5d5-e62ba9078bdb
15. 12fb6223-346f-401e-8f3b-e5726496bff6
16. 8851ceb9-552f-4273-b561-77410fa47ec0
17. 6986b5c8-1ab2-4959-9ab3-ae3d4b2a626d
18. a6e78ae6-1e29-4a6f-b118-c8b50d8fefb2
19. 48f69bb1-8b9d-4251-9bdb-cf81df673566
20. d9bdf3b7-8d5d-40e1-b4a1-2763e164d230
21. f0b29c65-ce35-4a31-a4ed-361e38c0ce87
22. bcd8a5ad-d3d0-4fec-9722-b2b535d435b5
23. 7b9b78c5-da33-4375-b97b-a747ad5cfbd3
24. e603ca55-a772-423c-9d9a-f8852146c899
25. 1516d09a-0ca1-4f4a-bfa1-8c1f67f4618e
26. 131dc529-ab4f-4ae5-ab48-4acbea1a9945
27. 40971111-51f7-4951-9ad6-77ba3bf12010
28. fc2a3b0c-c141-4f87-bb92-a6370a690ce5
29. 7efa645d-9b5e-4c89-b50b-e13c869e8d4f
30. 793623e7-105d-4377-8fff-b4e14fed729f
31. 974773ff-36b9-4a67-b3cb-8d53b86304e1
32. e2557778-7e91-49e6-bd88-fa65516820bc
33. 5113c9ca-aab8-4007-a25a-2ca61adb382c
34. 55e7f476-64c8-4142-bb36-a2d71ca5daa5
35. 405ccb7b-ba80-4b7c-acdb-fea236902d7a
36. ebd9b1b1-3b7b-4ac6-85af-124078512410
37. e7c4f0e0-df65-40a3-ab3f-25611a81585b
38. cab4d052-f88c-4b0d-885f-566a54280f2a
39. adc5123e-383d-4a99-aa34-e85f06bd814c
40. 59cbbed5-734b-4fae-84a0-20c8fffe7dcc
41. 16fae6fb-4201-480c-8f20-81b5c1b79e15
42. 7f106351-026e-4f10-a0f7-a41d93d1aee5
43. 2b0bdb91-a81f-4837-b576-5494d0fdba76
44. 32e5f12b-681a-4c71-96bc-0dc0f2d5b588
45. bf565f06-4a7e-4f74-91e6-cb7317dad571
46. a2675732-524e-4605-a164-e2caef74d350
47. b3f6b3d9-b51e-49f9-b371-51b3e256526c
48. a876acdf-d40e-4bfb-85df-c6d557738471 
49. f0b681db-c049-4679-875c-1e0b4e6f726c
50. 77b763a2-3fda-4f1c-a7d1-e1a24eaf0807
51. 68af5f56-c6bb-4dcf-b1b2-112712e91c30
52. f914db53-0870-4f0c-9874-742772d1a0a3
53. 3743987d-601e-4642-82f1-1db5d673fcc6
54. 811cf6df-3eaf-4b49-af52-2112170ed991
55. 70830dbe-e160-486b-97aa-06a4fbd155ee
56. b1e6de54-a1f0-4d7b-a1f6-92eea495b943
57. 37d15fbb-87e0-4a7a-9af9-c7b2aa3f774b 
58. 158ca096-498b-4f83-9fda-2afc6158080f 
59. 276a45f8-fd6f-4c87-9d27-6874a90373d3
60. 182a12a5-d283-4521-a55e-e16ee3027572
61. 66afd49a-5657-48f8-8a7a-26ae35e0502d
62. ca198c55-8bb9-4b8b-acaf-ed7abd86bab6 
63. 5d1557fc-4234-4ea4-bb5b-9ad82263c281
64. 018b32f8-02cd-4e75-8039-c317dedbbb2a
65. 21223fe8-66fd-46f6-a419-50ac07b44e86
66. 7289e439-15ff-406c-af61-b286946fff72
67. d3d99e2f-3415-432b-92a8-38ccfb7d2a3d 
68. f81c2b24-83fc-4121-80cc-62842d760478
69. 49262eed-1b4b-4990-9cb7-5327eda7f10b
70. 159c1272-2bd9-49ad-b0fa-c893c73653d8
71. 6ae6bd40-e418-42b1-9b41-1a063defaefe
72. 1166e801-b6a0-459f-af80-839f31ef84b6
73. 5f2db9d2-b8bd-4a3f-b4df-a122fd5945ee 
74. 450fa57a-1fdf-4fa9-9de2-26e23f985e90 
75. bcc65f05-6ee3-4188-9b03-89b531356eb5
76. a242372f-c970-4339-84af-cccfe57c704e
77. 14114b23-5af0-4be9-9caa-b0a853f80bc9
78. ec84d312-3e66-4c59-861c-d4f05e0589ba
79. 9d4b5d81-9b49-4f53-924e-35c3341254f1
80. aca70031-02ab-4cba-b3c6-4437a765b589
81. 9908b3f1-6384-43fc-a7eb-4f3e398c6980 
82. 10c96ff7-94f8-4a08-ba70-23786b683102
83. 35c2318c-ae6d-4911-843b-cd2503a8307e
84. 3218705e-d94f-4699-85a4-3f6b0989d1fb
85. cb083362-f6c5-40ec-a182-41b9d11df566
86. 05741d71-d725-45e2-9cdd-cdd032e72f15 
87. 8e68ff00-6587-4fe7-aa52-5065cfb27937
88. e8f3dabf-6d4d-4882-82ba-58ab37ba3c4d 
89. 3f8f84b7-8d3c-4b50-b195-d4e9708f7350
90. 496ecca3-145d-4e0c-94fd-15a22635392d
91. 25fa66dd-e31f-403b-bb7e-5d1c8baa327a
92. 8dfd6d56-4564-4957-809c-e8e68cbb4470
93. e4112783-4269-4504-826e-2f9375f4c58a
94. 121964a5-0615-4d07-a801-c9cb2a8aaa72 
95. 47417fee-eb18-4546-ba99-e51c9cabbb03

The above sessions have all transferred data but got no MYST rewards

**Environment (please complete the following information):**
 - Node version: 0.66.4
 - OS: Raspbian GNU/Linux 10 (buster)
 - Pi 4 8gb

**Comment by Donatas-MN** [comment]
@Csmflow are these session unrewarded also in NodeUI?

**Comment by Csmflow** [comment]
Yes

**Comment by Donatas-MN** [comment]
Can you send a screenshot from NodeUI?
