### ISSUE TITLE
Long session not reflected into earnings

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4076]
**Describe the bug**

ID: 0x7525249fd4ad940829eb538fa3855a9c2f890376

Few days ago i had someone connected to my network for a long time (3 days as you can see). I've seen Live earning as higher than 0 MYSTT. but once connection ended, in Sessions history i see it gave my nothing. Live data was also bigger than 0, bigger than 500mb for sure. Both session time and data transferred are worth something. What happened there? Here are details:

LU 
3d 21:31:42 
10/7/2021, 6:15:44 PM 
0.0000000 MYSTT 
0 Bytes 
d8381320

*Logs can be found on Additional context section

**Expected behavior**
Earnings should be updating.

**Environment (please complete the following information):**
OS:
Debian GNU/Linux 10 (buster)
Architecture:
linux/arm64
Node version:
0.63.0

**Additional context**
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7329037/mysterium-node.log)

**Comment by etherunit** [comment]
@isaackielma You can find this session on my.mysterium.network with details. I suspect it's related to another bug where NodeUI fails to visually display earnings. Advice him to update his node version and check if issue remains after restart.

d8381320-069a-435f-9781-7ea33b1e6aba | Luxembourg | 5 days ago | Completed | 12h | 155.37 MB | 0.04698525 | Normal
-- | -- | -- | -- | -- | -- | -- | --
https://testnet3-grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-service_type=All&var-session=d8381320-069a-435f-9781-7ea33b1e6aba
