### ISSUE TITLE
Node test failed even after restarting. "Permissive NAT"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4078]
**Describe the bug**

Hello, My node respond with "Test Failed" for two days. I have no idea what to do. The node runs on Oracle arm64 VPS, Ubuntu 20.04. The identity is: 0xcdeb451f572a6f77491086bda2ec15f63667b6e0 The DH2i NAT Test responds with "Permissive NAT". Thanks in advance!

**Expected behavior**
If node is receiving both test and normal sessions, transfer of data and earnings should be increasing.

**Environment (please complete the following information):**
OS:
Ubuntu 20.04.3 LTS
Architecture:
linux/arm64
Node version:
0.66.4

**Additional context**
[mysterium-node-13.log](https://github.com/mysteriumnetwork/node/files/7329080/mysterium-node-13.log)

**Comment by etherunit** [comment]
@isaackielma Could you request the output of `sudo iptables-save`?
