### ISSUE TITLE
Running Mysterium Node through third party VPN Service

### ISSUE THREAD

**Issue by Englischdude** [mysteriumnetwork/node#4083]
Online safety is of prime importance to me. Although I love the idea of Mysterium, I am concerned about my network being used for malicious or illegal purposes. 

I already have a 3 year PIA Vpn subscription and so I would like to be able to run my raspberry pi node through this VPN service. I have set this up already and confirm the results of my first tests as follows:

- Raspberry pi will only accept TCP connections and fails when trying to connect to a UDP server.
- The test data transfer rate is very slow. A normal testrun without the third party vpn passes approximately 160Mb of data, with the third party VPN the testrun transfers for example 51kb.
- Mysterium Dashboard correctly recognises my new third party VPN ip address and allocates the correct country flag.
- Even though I am running through a "Netherlands" PIA VPN server which is on the Mysterium residential rewards list of countries, and the country is highlighted in green indicating I have a connection, there is a message saying I am not eligible for residential rewards as I am not in one of the residential rewards countries. (my actual location is Austria)

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/92470726/137192389-ee488dbd-a31a-4a95-b419-07c3295a7c97.png)
![image](https://user-images.githubusercontent.com/92470726/137192522-c354e4ea-9e13-400f-b37b-c98c08484154.png)

You have already indicated to me via chat that this is a feature you would be very interested to assess. I am happy to support you as a tester for any trials and/or developments.

**Comment by Englischdude** [comment]
update after 4 days. Node running fine, data being tranfered, however rewards I am sure are much too low!
4 days, 8Gb transfered, 34 sessions.... only 0.25 Myst rewards!

**Comment by krohnoz** [comment]
Hello there. 
I thought about doing the same.
Are you still running it like that?
