### ISSUE TITLE
Myst is lost when node is not up to date

### ISSUE THREAD

**Issue by sparkd82** [mysteriumnetwork/node#4085]
**Describe the bug**
Noticed that when there is a newer node version available, the current running node accepts connections but Myst is not earned.

**Expected behavior**
I am fairly new to Mysterium but I could not find any indication that my running node was not up to date. Also I cannot seem to find a way to sync and get back the lost Myst for the bandwidth provided.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
To resolve I updated using sudo apt-get update and Myst started being earned normally

**Comment by Donatas-MN** [comment]
You can find min required version to be eligible for bounty in the leaderboard: https://my.mysterium.network/leaderboard

Unfortunately if node was running an updated software during that month it's not eligible for bounty.
