### ISSUE TITLE
Bounty (Myst) count reset

### ISSUE THREAD

**Issue by CDuarte144** [mysteriumnetwork/node#4092]
**Describe the bug**
For the second time, the MYST count was reset to 0 in my node (0xeb55a64976390bbfd43d1107fb76243d0d1d9a7d). The first time I submitted a Bug report and after a few chats with Isaac, the MYSTs were back to this node. Original MYST count attached.
After a few days, the MYST count was reset to 0 again and start over accumulating again, which is the current count. 
The MYSTs that were reset the second time were never applied back. 

**To Reproduce**
I don't know how to reproduce this error as this just happened twice and without any change on the node from my part.

**Expected behavior**
The MYST count accumulated until the second reset (attached) should be added to the current MYST count.

**Screenshots**
 
![Captura de pantalla 2021-09-15 072951](https://user-images.githubusercontent.com/88176451/137416664-cbcb0fcc-490b-4006-b2fe-6c9a2b0c525e.png)

![Captura de pantalla 2021-09-15 073107](https://user-images.githubusercontent.com/88176451/137416755-aec274a0-0a8d-4ea7-9f76-f925889e7f52.png)

**Environment (please complete the following information):**
 - Node version: now 0.67.0
 - OS: Linux Ubuntu 20.4
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag

**Additional context**

**Comment by Donatas-MN** [comment]
Similar to #4098.

**Comment by Donatas-MN** [comment]
It looks like everything is correct here as token amount in UI is reset after bounty payment is done (in other words you start collecting bounty tokens from scratch for a new month if payment was done). I can see you have received bounty payments for September and October.

**Comment by CDuarte144** [comment]
The reset didn't correspond bounty payment as you can see in the date of those screenshot were taken didn't correspond to payment date. Also you probably should be able to chech, that those more than 20 MYST were never payed to my account.

After this reset I continuing seeing some bugs from time to time like negative MYST count (attached) in my account but soon later the count backs to normal. 

In fact there were several successful bounty payout after the reset (no payout) of the more than 20 MYST that I reported "lost", but those 20MYST were never returned back to my account.
![3E966EBD-DABF-4064-A679-6EA0897282A3](https://user-images.githubusercontent.com/88176451/140342891-94c16eff-efea-441e-bb8d-0298fdadbc5e.png)
![6FDCFFF1-8A40-4225-9EF8-7111CC757137](https://user-images.githubusercontent.com/88176451/140343480-6e8ad2ab-83f1-4430-bdfa-30d1210682a1.png)

**Comment by Donatas-MN** [comment]
Negative balances was a separate issue (already fixed), not related to this. 

The recent reset to 0 was due to payment made to you. I can see you were successfully paid for September (including August) and October.

I believe you have in mind residential bounty, but as I can see Columbia was not eligible in August for it, so that's why it was reset to 0.

**Comment by CDuarte144** [comment]
Thank you Donatas, it is clear now.
