### ISSUE TITLE
Credit reset from 50 myst to 0

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4098]
**Describe the bug**

My credit was reset from 50 myst to 0. But I haven't received a payout in my wallet yet.

The payout has not yet been received on my Metamask wallet.

0xefb4c0a998bc098d9d0a0c137b8d28144b854c92

**To Reproduce**
1. Go to 'MMN Dashboard'
2. Click on 'bounty payout history'
3. Scroll down

**Expected behavior**
Balance was reset from 50 to 0.

**Environment (please complete the following information):**
OS:
Raspbian GNU/Linux 10 (buster)
Architecture:
linux/arm
Node version:
0.66.4

**Comment by Donatas-MN** [comment]
The issue is that Node version was outdated in August (0.52.0), so Node was not eligible for bounty collected during that month. 

Node was updated in September and bounty for September/October was successfully paid today.
