### ISSUE TITLE
"Test Connection" gets the message "Unauthenticated"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4100]
**Describe the bug**
Node's status is marked as test failed. Even after node reboot and update.

0xb0858ca5931a1a1310399dd1ab58f849b00260c1

root@vmi683860:~# myst --versionMysterium Node Version: 0.67.0 Build info: Branch: 0.67.0. Build id: 386192775. Commit: 8aeb9998

**Expected behavior**
Node should complete a test connection with the node.

**Environment (please complete the following information):**
OS:
Ubuntu 20.04.3 LTS
Architecture:
linux/amd64
Node version:
0.66.3

**Additional context**

$ sudo systemctl daemon-reload
$ sudo systemctl restart mysterium-node
$ systemctl status mysterium-node
● mysterium-node.service - Server for Mysterium - decentralised VPN Network
Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
Active: active (running) since Sat 2021-10-09 01:03:24 CEST; 564ms ago
Docs: https://mysterium.network/
Main PID: 1805054 (myst)
Tasks: 10 (limit: 9485)
Memory: 10.2M
CGroup: /system.slice/mysterium-node.service
└─1805054 /usr/bin/myst --config-dir=/etc/mysterium-node --script-dir=/etc/mysterium-node --data-dir=/var/lib/mysterium-node --runtime-dir=/var/run/mysterium-no>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.081 INF cmd/di.go:645 > Using local DNS: testnet3-location.mysteriu>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.082 INF cmd/di.go:645 > Using local DNS: api.ipify.org -> [54.204.1>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.082 INF cmd/di.go:645 > Using local DNS: badupnp.benjojo.co.uk -> [>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.082 INF cmd/di.go:645 > Using local DNS: testnet3-trust.mysterium.n>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.082 INF cmd/di.go:645 > Using local DNS: testnet3-quality.mysterium>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.082 INF cmd/di.go:645 > Using local DNS: feedback.mysterium.network>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.082 DBG communication/nats/connector.go:78 > Connecting to NATS servers: [nats://testnet>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.082 INF firewall/outgoing_firewall_noop.go:57 > Allow URL nats://testnet3-broker.mysterium.>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.083 INF firewall/outgoing_firewall_noop.go:57 > Allow URL nats://testnet3-broker.mysterium.>
Oct 09 01:03:25 vmi683860.contaboserver.net myst[1805054]: 2021-10-09T01:03:25.083 INF firewall/outgoing_firewall_noop.go:57 > Allow URL nats://167.233.11.60:4222 access
$ systemctl status mysterium-node
● mysterium-node.service - Server for Mysterium - decentralised VPN Network
Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
Active: activating (auto-restart) (Result: exit-code) since Sat 2021-10-09 01:03:32 CEST; 288ms ago
Docs: https://mysterium.network/
Process: 1805054 ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS service --agreed-terms-and-conditions $SERVICE_OPTS (code=exited, status=1>
Main PID: 1805054 (code=exited, status=1/FAILURE)
Oct 09 01:03:32 vmi683860.contaboserver.net systemd[1]: mysterium-node.service: Main process exited, code=exited, status=1/FAILURE
Oct 09 01:03:32 vmi683860.contaboserver.net systemd[1]: mysterium-node.service: Failed with result 'exit-code'.

**Comment by etherunit** [comment]
@isaackielma Please advice him to update.
