### ISSUE TITLE
Test exit node migration into mainnet

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/node#4101]
# Scenario to test

1. Migrate your node into `mainnet` (look at instructions provided below)
1. Open NodeUI in your browser (http://[your_ip]:4449 and finish onboarding (your node identity will be registered in on [Polygon](https://polygonscan.com/address/0x87F0F4b7e0FAb14A565C87BAbbA6c40c92281b51)).
1. Ensure that you node identity didn't change. It should remain the same as in testnet3, however your earnings should start from 0.
1. There should be no bounty box on NodeUI, you should see withdrawal button instead.
1. In NodeUI try changing payout address into new one. This should be done instantly (even when your node balance is zero).

# Migration instructions

##  How to update your Docker node:

1. Pull the mainnet node image: 
  `docker pull mysteriumnetwork/myst:mainnet`

1. Delete the container that is already being used for running node: 
  `docker rm -f myst`

1. Follow the running a docker node guide (https://docs.mysterium.network/node-runners/setup/docker/) to start a new container using `:mainnet` tag.

##  How to update your Linux node:

1. Add the repo:
  `sudo add-apt-repository ppa:mysteriumnetwork/node-mainnet`

2. Update after repo change:
  `sudo apt-get update`

3. Update the cache policy:
  `sudo apt-cache policy myst`

4. Upgrade Mysterium node:
  `sudo apt upgrade myst`
  
if this will not help, they try:
  
  `apt install myst=0.68.1+1branch+mainnet+bu+1+build398678629+focal`

<br class="Apple-interchange-newline">

##  How to update your RPi node:

In `/etc/apt/sources.list` add source `deb http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu focal main` 

`cat /etc/apt/sources.list`

Uncomment line below then `apt-get update` to enable `apt-get source`

```
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
#deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu focal main
```

Remove unattended-upgrades: 
`sudo apt-get -y remove unattended-upgrades`
`sudo apt-get update`
`sudo apt-cache policy myst`
`sudo apt install myst=<Myst candidate version>`

---------- 

**NOTE**: After finishing this scenario please post a comment above (if all was ok, please also give us know about that).

**Comment by Cmac0519** [comment]
Rpi node migration was successful. I had to add main to the end of the new source line without it I was getting a malformed entry. Should be updated in the instructions. 
deb http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu focal main

**Comment by CharlyEmpereurmot** [comment]
Docker node migration worked correctly. My node identity did not change and my earnings started at 0. Withdrawal for MYST is displayed. I could input a payout address (format TrustWallet) and this was set instantly. However, after migration the payout address field was blank initially, while the migrated node already had an address set.

**Comment by MarkWieczorek** [comment]
Migration worked on raspberry pi for me. However, the Instructions above are somewhat mangled. I propose the following instead:

1. Type `sudo nano /etc/apt/sources.list` in the terminal.
2. Replace the contents of the file with
```
#deb-src http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
#deb http://raspbian.raspberrypi.org/raspbian/ buster main contrib non-free rpi
deb http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu focal main
```
3. Save the file, then type the following in the terminal:
```
sudo apt-get -y remove unattended-upgrades
sudo apt-get update
sudo apt-cache policy myst
sudo apt install myst
```

**Comment by invest4wealth2endeavor** [comment]
Migration was successful on Linux/Ubuntu. Really took my time to make sure my node id and everything was logged/saved in case anything went wrong. 

Upon migration, I was on version 0.67.4. After Etherunit's experience trying to upgrade from version 0.67.3, I was a little worried, but everything upgraded smoothly from my version. 

Node ID remained the same, withdrawal button ws present instead of a bounty box, and I was able to input my payout address immediately (same as the testnet version). 

Thanks for the links, assistance, and support in the Discord!

**Comment by AVeryTastyRaspberry** [comment]
Migration to 0.68.1+1branch+mainnet+bu+1+build399229897+focal worked without a hitch on RPI.

I have to agree with @MarkWieczorek instruction need to be changed, however, I focused on 

Step 1: `sudo nano /etc/apt/sources.list.d/mysterium.list`
Step 2: copy and paste to replace contents with:

```
deb http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu focal main
#deb-src http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu focal main
```

Step 3: 

```
sudo apt-get -y remove unattended-upgrades
sudo apt-get update
sudo apt-cache policy myst
sudo apt install myst=0.68.1+1branch+mainnet+bu+1+build399229897+focal 
```

*And to get the current version of mainnet go to `https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node-mainnet` and check two things the focal which appears second don't he list and has `+focal` and that the build was successful which you can find the top right-hand corner.

But whatever works I suppose.

**Comment by abhrajo** [comment]
Migration to mainnet on Linux (Ubuntu 20.04 LTS VPS) worked without any issues for me. Current version: mainnet (0.68.1-1branch-mainnet-bu-1-b77df227

**Comment by Durfduivel** [comment]
I am using this hardware and OS:
CPU: Dual Core Intel Core i5-7200U (-MT MCP-) speed/min/max: 1548/400/3100 MHz
Kernel: 5.11.0-38-generic x86_64 Up: 6d 1h 49m Mem: 2854.4/15886.8 MiB (18.0%)
Storage: 238.47 GiB (12.1% used) Procs: 340 Shell: bash 5.0.17 inxi: 3.0.38
Kernel: 5.11.0-38-generic x86_64 bits: 64 compiler
Distro: Ubuntu 20.04.3 LTS (Focal Fossa)

All commands worked, I didn't have to use : apt install myst=0.68.1+1branch+mainnet+bu+1+build398678629+focal (what I even tested but gave an error msg).
What I find strange is that in the Mysterium Dashboard I don't see any change, it said this before and after install:
Laptop | Online | 26 minutes ago | 0.67.4 | Ubuntu 20.04.3 LTS | #1428  - 0.9445 MYST / $0.95 | #157  - 0.9445 MYST / $0.95
Also clicking on it brings me to the nodes/number/dashboard and also there all is the same.
Than I clicked on Node settings and I had to enter my password (that I entered during install of the testnet version) and it brought me to the old dashboard but my payout address and API key where missing. I entered those by hand but I got an error. Than after that I entered those things via the terminal with the corresponding 'myst cli' commands eg.
myst cli service list (to check if I still had the same identity)
myst cli identities unlock MY_NODE_IDENTITY
myst cli identities register MY_NODE_IDENTITY
myst cli mmn MY_API_KEY
myst cli identities set-payout-address MY_NODE_IDENTITY MY_PAYOUT_ADDRESS
myst cli identities get-payout-address MY_NODE_IDENTITY (to verify payout address)

After doing that still the dashboard showed the old dashboard.
Than I cleared Brave browser cache and now I saw the new Dashboard with the new Withdraw button.

Node version: mainnet (0.68.1-1branch-mainnet-bu-1-b77df227)
NodeUI version: 0.5.0-mainnet8

Going back to https://my.mysterium.network/dashboard still shows exactly the same.

I changed payout address  (Default Withdrawal Address) to my Coinbase Wallet MYST address, this worked.
And I leave it at that address :-)

**Comment by pianoman10** [comment]
As there is not yet the scenario of creating a fresh node in RPi from scratch, I put here the results.
Have a RPI 4 model B, SD 64, running latest nightly version: https://github.com/mysteriumnetwork/nightly/releases/tag/nightly-20211113

Identity: 0x01b4e92b8769d2495eeee68a94c7cde3f84f96d2

Will check if I manage to get to work a client app in Mac to test it. I would appreciate if someone can test it and let me know

**Comment by CharlyEmpereurmot** [comment]
I have just finished migrating 37 nodes and it went _mostly_ fine (all running with Docker on Ubuntu 20.04). My node identities did not change and my earnings started at 0. Withdrawal for MYST is displayed in the dashboard. I could input a payout address (ERC20 format from TrustWallet, not sure if this is OK) and this was set instantly.

However, for just 4 of these 37 nodes I am receiving 0 traffic while it seems you send ~500 Mb at first connection for testing purposes, which I received + some other connections for the 33 nodes for which it seems everything is working fine.

Here are the adresses of the nodes for which I'm not seeing any traffic:

0x02879f81de704b6ca79274b467a19abcb9774ff1
0x3727cf9869860aac4db20c4eea0902e898beba32
0xd99f70dcefb2a4aabed5af955ec207f8cea69d83
0x2d460b13e5929d3a5cd5805840836f6a7b483168

All required ports are open + UDP 10k-60k in UFW and there is no network firewall on these machines.
