### ISSUE TITLE
Test dVPN desktop app upgrade for user who have `> 1 MYSTT`

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/node#4103]
This scenario is for users who have topuped his dVPN app balance using our CoinGate (on testnet3). 

1. Topup your dVPN app balance using BTC, LTC, ETH, MYST or other supported cryptos (could be done a while ago, your current balance should be more than 1 MYSTT).

1. Download newest mainnet app (.dmg, .deb or .exe file) from [https://github.com/mysteriumnetwork/nightly/releases/latest](https://github.com/mysteriumnetwork/nightly/releases/latest) and install it.

1. Launch the app, go via onboarding steps and check your app balance, it should remain the same as before upgrade.

---------- 
**NOTE**: After finishing this scenario please post a comment above (if all was ok, please also give us know about that).

**Comment by MarkWieczorek** [comment]
It is important to point out that the migration of funds from testnet3 to mainnet occurs only once, at the time when you register your mainnet identity. Thus, if you add funds to testnet3 after you create your mainnet identity, these funds will remain stuck on testnet3.
