### ISSUE TITLE
Test fresh mainnet node installation on Ubuntu Linux

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/node#4104]
This test should be done on a fresh machine or on machine where myst was already uninstalled and it's `.mysterium` folder was deleted.

## Scenario to test

1. Add the repo:
`sudo add-apt-repository ppa:mysteriumnetwork/node-mainnet`

1. Update after repo change:
`sudo apt-get update`

1. Update the cache policy:
`sudo apt-cache policy myst`

1. Install Mysterium node:
`sudo apt install myst`

1. Open NodeUI in your browser (http://[node_ip]:4449) and finish onboarding process. You should see **WireGuard** service be up and running. 

   For those who are running mysterium node in data centers you can use our CLI  to setup the node:
    - `$ myst cli`
    - `» identities list`      # this will show your identity
    - `» identities unlock [your identity]` # you need to unlock identity before using it
    - `» identities register [your identity]` # you need register your identity, must be done only once
    - `» service start [your identity] wireguard` # this will start wireguard service
    - `» service list`           # if you see ID of your running service then congrats, you're mysterium node runner
 
1. Download dVPN desktop or mobile app from our nightly builds (look for .apk, .exe or .dmg): https://github.com/mysteriumnetwork/nightly/releases/latest and try establishing connection to your own node. 

DON'T FORGET: you have to be in separate networks (e.g. node on local WIFI and mobile phone using 4G) for successful connection.

---------- 

**NOTE**: After finishing this scenario please post a comment above (if all was ok, please also give us know about that).

**Comment by Jayto1** [comment]
- [ ] 1. Add the repo:
sudo add-apt-repository ppa:mysteriumnetwork/node-mainnet

- [ ] 2. Update after repo change:
sudo apt-get update

- [ ] 3. Update the cache policy:
sudo apt-cache policy myst

- [ ] 4. Install Mysterium node:
sudo apt install myst

- [ ] 5. Open NodeUI in your browser (http://[node_ip]:4449) and finish onboarding process. You should see WireGuard service be up and running.

OS: Ubuntu 20.04
Enviroment: Virtual Box
Network Type: Bridged Adapter

**Comment by abhrajo** [comment]
Steps 1-5 Worked without issues on 20.04 LTS running in VPS

Step 6 Had no issue connecting. Even tried Downloading file and faced no issues.  But for some unknown reason the Node lost internet connection after like 10-15mins during download. Interestingly, during this time the download kept going but I couldn't access any website. Didn't check logs yet.

**Comment by invest4wealth2endeavor** [comment]
Steps 1-5 were good while testing on 21.04 Ubuntu/Linux. For step 6 I could not get the mobile VPN application nor the desktop application to identify and connect to my node (mobile gave me an option to manually type my Node ID...but just couldn't find my node; desktop application did not even provide a search bar to input my node ID. Will double back to this step to see if if works later or is a resolvable issue.

**Comment by ZeroBug-ZB** [comment]
All done without errors.

Ubuntu server 21.04
