### ISSUE TITLE
Test topup money transfers 

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/node#4106]
While running your dVPN desktop app you can topup your balance via crypto or fiat. 

<img width="450" alt="Screenshot 2021-10-30 at 14 26 59" src="https://user-images.githubusercontent.com/153896/139531105-af4b7d57-cd56-421c-b0ef-6877966af7d8.png">

1. Go to wallet screen and choose how much you'd like to topup.
2. Choose your payment method. 
3. Follow given instructions to finish funds transfer.
4. After 1 minute check your balance (if needed click refresh button), your balance should be increased.

<img width="150" alt="Screenshot 2021-10-30 at 14 33 05" src="https://user-images.githubusercontent.com/153896/139531297-6985e264-6c17-485b-b3d9-40e625e2671c.png">

**NOTE.** If you're using MYST, at the moment you should send them on Ethereum chain, Polygon support will be added soon.

**Comment by MarkWieczorek** [comment]
UNSUCCESSFUL (macOS client (6.8.1):

1. I chose to transfer ETH and sent the amount via metamask.
2. metamask confirmed the transaction. When clicking on the link "Pay in browser instead", I was directed to a coingate page that said "Paid and Confirmed".
3. Refreshing the balance in the Myst client did not update the amount of Myst that was available in my account.
4. I am posting this 1.5 hours after the initial ETH transaction was confirmed.

Comments
1. There should be buttons to copy the amount of crypto and the address to send it to (as opposed to just copying it by hand).
2. The client should tell you the status of your transaction. I suspect that there are several steps: initial transaction on blockchain to coingate, conversion to Myst, and transfer from coingate to my account.

**Comment by MarkWieczorek** [comment]
Also, why is the balance in MYSTT? I thought that this was a mainnet test that uses MYST?

**Comment by abhrajo** [comment]
![myst1](https://user-images.githubusercontent.com/25876788/139709796-7d128135-8090-40af-9b8a-7cff8e125d66.png)
I was unable to Topup. Kept throwing me this error.

**Comment by tomasmik** [comment]
@MarkWieczorek Can you please provide me with your identity and if possible order ID that you got from coingate? As I do not even see your topup request being created. Something seems to not be right when it comes to the desktop app.

**Comment by etherunit** [comment]
Just to reiterate:

1. User tried to top up his testnet3 mysterium account (this is one of the mainnet beta-testers tasks: https://github.com/mysteriumnetwork/node/issues/4106#issuecomment-955697648)
2. He confirmed that his ETH transfer was confirmed on the blockchain, and at the **Coingate** website.
3. The balance of his mysterium account (using the testnet3 client downloaded from the website) never changed.
4. As he waited, he figured out that he could try using the new mainnet-beta client (dVPN app for Mac from nightly repo), so he downloaded it, and set it up.
5. His 1 MYST that was on the testnet3 client was successfully transferred to his new mainnet account. The 60 MYST that he bought wasn't there either.
6. He contacted Tomas, and Tomas found a problem on our end concerning topping up (order creation). Once fixed, his 60 MYST appeared in testnet3 mysterium account.
7. However, the 60 MYST was not transferred to the mainnet account: It seems that this is only done once when you first run the new mainnet client.
https://testnet3-hermes.mysterium.network/api/v1/data/consumer/0x3fe3fce5e6ef2165b1ddb45c24512ed0a0187996

Update: user is still missing 60MYST in his mainnet-beta account.

**Comment by chompomonim** [comment]
After latest tests topup works fine. Please create separate issue if you'll get any troubles with topups in mainnet app.
