### ISSUE TITLE
Test that affiliates still work 

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/node#4109]
Affiliates were moved to the sidecar of transactor.
* [x] Afiiliates can be created and campaigns can be added
* [x] Can register with affiliate code
* [x] Affiliate rewards are submitted to the BC
* [x] Affiliates can claim their rewards

**Comment by Jayto1** [comment]
Release: 6.8.1
OS: Ubuntu 20.04
![image](https://user-images.githubusercontent.com/79473923/139550985-c3f53d34-4061-4559-9fbc-1db96a31c509.png)

**Comment by Jayto1** [comment]
[Feature Request] Ability to use referral code even when registered

**Comment by invest4wealth2endeavor** [comment]
If the referral code is referred to as an affiliate code for this test category, it was an option to submit immediately upon registering. Code was accepted and went flawlessly. Forgot to screenshot the code input box, but the 1.5 MYST from code is reflected in account.
<img width="633" alt="Screen Shot 2021-11-03 at 1 42 43 AM" src="https://user-images.githubusercontent.com/93509600/140031243-a81faf3d-3866-496e-a777-4078b5bab33e.png">

**Comment by invest4wealth2endeavor** [comment]
If the referral code is referred to as an affiliate code for this test category, it was an option to submit immediately upon registering. Code was accepted and went flawlessly. Forgot to screenshot the code input box, but the 1.5 MYST from code is reflected in account.

**Comment by MarkWieczorek** [comment]
Similar to the screenshot above, the "BETA_TESTER" referral code does not work on Android (I am using the most recent nightly build).

**Comment by chompomonim** [comment]
All the issues with affiliate codes are solved. Now it is successfully used more than 40 times, both on mobile and desktop app.
