### ISSUE TITLE
Test token withdrawal flow in NodeUI

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/node#4110]
In MainNet node runners will be able to settle collected funds into blockchain wallet (on Polygon or Ethereum).

- [x] Check withdrawal widget in NodeUI dashboard present and working

<img width="1680" alt="Dashboard - withdrawal" src="https://user-images.githubusercontent.com/153896/133096956-c4ac0438-8d6e-42f3-80aa-7bdfe478aead.png">

- [x] Check token withdrawal

![Withdrawal popup](https://user-images.githubusercontent.com/153896/133535119-8c33527c-1a1d-4e2c-b947-8908b98825d4.png)
![Group 2862348](https://user-images.githubusercontent.com/153896/133535322-e4c6dbec-6f70-4cc0-8ff9-aeb502c9afeb.png)

- [x] Check withdrawal for both networks: Polygon and Ethereum (Default should be "L2: Polygon-Matic (smaller fees, faster transactions)", secondary option is "L1: Ethereum (bigger fees, slower transactions))

**Comment by etherunit** [comment]
No chains except Goerli and fee way to high.
<img width="1011" alt="Screenshot 2021-10-21 at 11 15 42" src="https://user-images.githubusercontent.com/60128746/138238587-74850bc6-7737-4c75-ad25-48b566768085.png">

**Comment by MarkWieczorek** [comment]
The withdrawal dialog should explicitly provide the units for "Amount", "Fee", and "you will get". Most people who are familiar with Ethereum will naturally assume that the "fee" will be in ETH (when withdrawing to the Ethereum blockchain). Similarly, one would naturally assume that the fee would be in Matic when withdrawing to Polygon. Furthermore, when withdrawing to Ethereum, one would assume that the user could set their own gas fee (using something like Metamask, for example), so it is not obvious if this is a suggested fee or not.

If the fee is in fact in MYST, then somewhere there would need to be a MYST to ETH conversion, it is is not immediately obvious how this would occur, and what dex would be used to do this. (I am sure that this will be explained in the forthcoming whitepaper).

**Comment by abhrajo** [comment]
Withdrawal worked fine on Polygon network. Shows up on Polygonscan and reflects the same on Metamask.

**Comment by Durfduivel** [comment]
It would be better to not promote Ethereum Mainnet so much by putting it as default in the "Select chain" choice but to put MATIC (Polygon) Mainnet as first choice. It is idiotic to have to pay over 20 MYST to transfer tokens to a wallet (or anywhere). But to Polygon Mainnet worked very good and very fast, it is almost instantly.

**Comment by pianoman10** [comment]
All the process worked fine (still pending receive it in my metamask wallet)
(see attached pictures)
Picture 1: Shows balance 15 MYST
Picture 2: Shows amount to be withdrawn 14.8 MYST and network Matic(Polygon) Mainnet
Picture 3: Shows confirmation dialog 
Nothing happens, nor a confirmation message, it went straight to main page (did not get the TX hash)
Picture 4: Shows outstanding balance correct 

If I go to withdraw again, it show now at the bottom the TX hash, that I checked in Polygonscan and it is there, 
but after 34 minutes 870 confirmations still **DO NOT SHOW UP** in my Metamask Polygon PoS (Matic) Mainnet



![4-Screenshot 2021-11-18 at 21 56 50](https://user-images.githubusercontent.com/80623961/142499532-841fec1f-44c5-48a9-a633-f3c3da071bd7.jpg)
![3-Screenshot 2021-11-18 at 21 55 50](https://user-images.githubusercontent.com/80623961/142499539-a4331396-d36c-43aa-86d2-d8b992cbce0f.jpg)
![2-Screenshot 2021-11-18 at 21 55 26](https://user-images.githubusercontent.com/80623961/142499541-27e0645e-7a90-4557-b091-791012665f21.jpg)
![1-Screenshot 2021-11-18 at 21 53 23](https://user-images.githubusercontent.com/80623961/142499543-ecaeda3a-5db2-4a0c-9dde-90582c98ed88.jpg)

**Comment by CharlyEmpereurmot** [comment]
I have done 9 different withdrawals from 9 different nodes via Polygon and it worked mostly fine. The delay was slightly higher for 3 of the withdrawals, that were not showing in the 10-15 min after I pushed the WITHDRAW button. But after a sound night of sleep I recheck and everything was delivered.

**Comment by chompomonim** [comment]
@pianoman10 could you try with latest nightly build? We were fixing couple of edge cases in withdrawal flow recently.

**Comment by pianoman10** [comment]
> @pianoman10 could you try with latest nightly build? We were fixing couple of edge cases in withdrawal flow recently.

Sure, will do it
. Will search for the correct line to put in the file /etc/apt/sources.list, but if you read this please let me know just in case I do not fund the right one

**Comment by chompomonim** [comment]
@pianoman10 I think you don't need to change anything in `/etc/apt/sources.list` if you're already running mainnet node. Simply `apt update && apt upgrade`.

**Comment by pianoman10** [comment]
> @pianoman10 I think you don't need to change anything in `/etc/apt/sources.list` if you're already running mainnet node. Simply `apt update && apt upgrade`.

I have done another withdrawal now and everything went ok. Although it would be nice to have an intermediate pop up like the one in the example of above 
THIS ONE

![image](https://user-images.githubusercontent.com/80623961/142742006-70cff00c-87da-4313-8667-99000fe991bb.jpeg)
