### ISSUE TITLE
Bounty payout history show payment made but no payment received

### ISSUE THREAD

**Issue by invme247** [mysteriumnetwork/node#4112]
**Describe the bug**
as per record , i suppose to receive payout before 10th Oct but i dont see any deposit to my account.
my node id 0x498a5ad56204b339cf5a38e938c62dcc75a0482b

see screenshot for the dates and trx but the amount was not deposited. 

**Expected behavior**
The reward should get deposited.

**Environment (please complete the following information):**
version : 0.62.1

**Comment by etherunit** [comment]
Please refer to https://github.com/mysteriumnetwork/node/issues/4113 @invme247
