### ISSUE TITLE
September payouts still in progress not completed

### ISSUE THREAD

**Issue by OneCDNGuy** [mysteriumnetwork/node#4113]
**Describe the bug*

Hi there, I have not received my bounty payout from September either of my nodes. The bounty payout history for both state that a payment would be made by 10-07. My nodes are:
0x5b4be5003112378a14718ebf03d8f54db34332d2
And
0x37f06d93955a6497311ff1c675739e9d9b70aafe

**Expected behavior**
Bounty payout history for both nodes states "Payment in progress. It should reach you before 2021" it is well past this date and payment has not been made.

**Environment (please complete the following information):**
 - Node version: 0.67.2
 - OS: raspberry pi
 -

**Comment by Donatas-MN** [comment]
There was an issue with bounty caps, so as cap was 10 MYST in August/September you did not get paid. It showed up as "in progress" in MMN due to a bug. October bounty cap is 5 MYST, so you will receive your bounty in the beginning of November.

**Comment by invme247** [comment]
Ok, understand due to bug payment was stuck and not paid but where your node operators can see the accumulated balance? There is no way for us to see the overall contribution. Don't see transparency here.
