### ISSUE TITLE
Internal test mainnet beta

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#4117]
Team should test Mainnet beta before moving it into public testing.

- [x] It should be possible to establish successful connection on mainnet.
- [x] We should be able to run dVPN macOS and Windows apps on mainnet and establish successful connection.
- [x] Should be possible to establish successful connection from desktop app
- [x] It should be possible to withdraw funds on L1
- [x] It should be possible to withdraw funds on Polygon
- [x] Should be possible to install fresh node and register it
- [x] Should be possible to establish successful connection from android app

**Comment by tomasmik** [comment]
Connection seems to work fine. Marking first as done:
```
» connect 0x565cf9136d6c7d8c73815efe829e0ea60087aaf0 0xb861f881b489858b698dc43577b8d3b52994513d wireguard
[CONNECTING] from: 0x565cf9136d6c7d8c73815efe829e0ea60087aaf0 to: 0xb861f881b489858b698dc43577b8d3b52994513d
[SUCCESS] Connected.
```

**Comment by chompomonim** [comment]
Each team member should go though all scenarios:
https://github.com/mysteriumnetwork/node/milestone/65
