### ISSUE TITLE
Make a mainnet beta ready android build

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#4118]
- [x] Use mainnet ready node build from https://github.com/mysteriumnetwork/nightly/releases
- [x] A default currency there should be MYST (not a MYSTT which was used on testnet)
- [ ]  In initial on boarding step check that user is able to register for free here using #4205, if so then proceed with automatic old workflow. If not then there should be no skip (topup later) option in topup step.
- [ ] Migrating to the new payments api [use V2 methods](https://github.com/mysteriumnetwork/node/blob/master/mobile/mysterium/payment_orders.go)

**Comment by furkanarius** [comment]
Hi! We had an internal release but might be crushed during the updates. We'll get one up on the internal releases as soon as possible.

**Comment by tomasmik** [comment]
There are a few things to address:
* In initial on boarding step check that user is able to register for free here using this https://github.com/mysteriumnetwork/node/pull/4205 if so then proceed with automatic old workflow. If not then push the user to purchase some myst as without it user cannot register or use the app anymore.
* Migrating to the new payments api. [Using V2. So basically we should drop all old methods and use these instead](https://github.com/mysteriumnetwork/node/blob/master/mobile/mysterium/payment_orders.go)
