### ISSUE TITLE
Missing bounty payment

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4134]
**Describe the bug**
MMN still reports as pending the payments of August and September for 0xf281d61f1d056b42323ad72b3cd75339eb1ebf7e

```
2021, September | 584.9226 MYST | - / - | #76 | #4 | Payment in progress. It should reach you before 2021-10-07.
-- | -- | -- | -- | -- | --
2021, August | 502.9860 MYST | - / - | #211 | #8 | Payment in progress. It should reach you before 2021-09-07.

```
It seems that min 10 MYST threshold was hit.

**Screenshots**
<img width="1407" alt="Screenshot 2021-10-22 at 12 24 16" src="https://user-images.githubusercontent.com/60128746/138429821-440bc78b-bbd3-4432-837f-ba3dcdca146e.png">

**Environment (please complete the following information):**
 - Node version: 0.64
 - OS: Alpine Linux v3.12(docker)

**Comment by dpellegr** [comment]
@Guillembonet Are you sure? The address was set in the WebUI several months ago and was never touched. As of today the WebUI is reporting the proper address. Is there something I should do from my side?

**Comment by Guillembonet** [comment]
It seems that there might have been some error when saving it or something... Maybe you can try setting it again and see if it is saved then, if you remind me I can check if it is saved correctly on tuesday!

**Comment by dpellegr** [comment]
Ok, I randomly modified the address, hit save, then restored the proper address and hit save again.

Thank you in advance for checking the db, the address should be the same of my other node: 0x0bcc847afa69866eb53d444076bd3be9ff51084c which has never stopped receiving payments.

I hope something could be done for the overdue payments, as the node has accumulated quite a lot of traffic in the past months and with the current bounty limits I may never be able to get it back even.

**Comment by Guillembonet** [comment]
The address is now saved in DB! We'll see what we can do about past payments with the team!

**Comment by Donatas-MN** [comment]
@dpellegr You should have received payment for October, can you please confirm that?

Also, you should receive missing payment for August/September shortly.
