### ISSUE TITLE
Problem with rewards calculation?

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [mysteriumnetwork/node#4143]
**Description of the bug**

I can see some sessions for which the calculated rewards make little sense to me. I made a small compilation so that you can investigate.

**Node: 0xd99f70dcefb2a4aabed5af955ec207f8cea69d83**
![image](https://user-images.githubusercontent.com/44687951/138658254-0e9fbdf4-d329-4946-bb69-46f8a90e4daf.png)
Problem: Reward absent for 1+ Gb and there is no chance this node could have sent 1+ Gb in just 1 sec (*Normal* connection)

**Node: 0x2ba5fc887e4431d5b9feb3602df3df43f126d23d**
![image](https://user-images.githubusercontent.com/44687951/138693188-8b9dc61f-9925-487f-b6d2-13136f46f037.png)
Problem: Reward absent for 2x 1+ Gb (*Normal* and *Test* connections)

**Node: 0xc6e7557ee0f5911398b6b4ef8896db1944a8018c**
![image](https://user-images.githubusercontent.com/44687951/138601139-47965c26-258f-421d-b115-c79fa23ad921.png)
Problem: Reward absent while I would expect to collect some dust here (*Normal* connection)

**Node: 0xfcb81cb962ba50623951189bf3be87f00264ac90**
![image](https://user-images.githubusercontent.com/44687951/138601493-648511de-685d-4e54-8a82-d33361962ccb.png)
Problem: Reward absent while I would expect to collect some dust here (*Normal* connection)

**Node: 0x5534e231855bacf70392858d12ab854f7e609598**
![image](https://user-images.githubusercontent.com/44687951/138601188-d48fee20-5d8f-4cfd-89d2-7f363c239226.png)
Problem: Reward absent while I would expect to collect some dust here (*Test* connection)

**Node: 0xb59411742cfc3bb0e67d1d36f8af7435fc9010ad**
![image](https://user-images.githubusercontent.com/44687951/138601258-e243d838-0e6a-42a3-93b9-81d0db11e675.png)
Problem: Reward is as much as for 1 Gb transferred (as seen from other sessions on this node) while in this rewarded session data is 0 bytes and time is 1 sec

**Node: 0x6f5e4d15e3b8b7710743a0ae477e0e9bcdceb8fb**
![image](https://user-images.githubusercontent.com/44687951/138601655-03fb50b1-d5d0-46f6-bf7e-e8e2bb3078f9.png)
Problem: (Bottom 4th line) There is no chance this node could have sent 1 Gb in just 1 sec (With respect to 1st line) Why the test connection is twice as expensive as the normal one? It is 1 min vs 1 sec OK but does this make sense?

**Environment**
 - Node version: 0.67.4 for each node in this report
 - OS: Ubuntu 18/20
 - Docker: Yes

**Additional remarks**
I think most of these nodes (if not all) I have migrated from one VPS to another one. These migrations happened like 1-2 weeks before the observations in this report.

**Comment by CharlyEmpereurmot** [comment]
Unrewarded sessions have also been seen in #4071

**Comment by Donatas-MN** [comment]
@CharlyEmpereurmot are these session unrewarded also in NodeUI?

**Comment by CharlyEmpereurmot** [comment]
I checked for some nodes on which I would see this in recent sessions.
On node 0xc0c63c70b69b536fdf31065d060bb3454cfc6530 there is session cb46df99-a00f-46ae-81e7-ac296205ee5e that does NOT show as rewarded, but it DOES show as rewarded in the node UI, in fact.

**Comment by Donatas-MN** [comment]
Good, it means you got rewarded for them, so it looks like data sync issue then. In MainNet all sessions will be viewable only in NodeUI, so there shouldn't be such issues anymore.

**Comment by CharlyEmpereurmot** [comment]
Alright then :) I have moved most of my nodes to mainnet already, looking forward  to full deloyment!
