### ISSUE TITLE
0.3.0 standalone has wrong 'config' directory structure

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#415]
See at https://github.com/mysteriumnetwork/node/releases/tag/0.3.0

![Screen Shot 2018-09-28 at 15.25.14.png](https://images.zenhubusercontent.com/5af1aeda4b5806bc2bd24871/31b195a9-e89a-4abe-b8c1-00d7ec48f691)

**Comment by soffokl** [comment]
Fixed at [0.3.1](https://github.com/mysteriumnetwork/node/releases/tag/0.3.1)

![image](https://user-images.githubusercontent.com/8612618/46328411-dafff880-c628-11e8-816a-baa9ca2c4c21.png)
