### ISSUE TITLE
Provide instruction for beta testers how to run testnet and mainnet node on same machine

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#4151]
A documentation on how to run different node version in docker. 

Also mention that people could run two RPi nodes with same IP, one for mainnet another for testnet.

**Comment by pianoman10** [comment]
Regarding **"Also mention that people could run two RPi nodes with same IP, one for mainnet another for testnet"**
How we should we proceed with the fresh installed RPi node in mainnet, as regards the port-forwarding, if we already have set up the port-forwarding for our testnet3 node ??

**Comment by pianoman10** [comment]
in the beta-test channel of discord, ZB has provided a simple but great idea, Kudos to him. I copy it here:

decrease port range in both nodes config, for example from 10k to 25k and from 25001 to 50k, also on router forward these ports range for each lan ip
https://discord.com/channels/614079733663006750/867668964770447370/904373659970469948

**Comment by chompomonim** [comment]
@etherunit what is status of this task? People are waiting, soon it will be not really needed.

**Comment by etherunit** [comment]
https://docs.mysterium.network/node-runners/setup/updating/#dual-mode-provider-testnet3--mainnet

**Comment by pianoman10** [comment]
Should I then just forward 4448 port on new node on mainnet ?

**Comment by etherunit** [comment]
Yep, just forward one for Mainnet based UI and another for Testnet3. Exactly as shown in the guide.
