### ISSUE TITLE
[windows] can't connect to any provider

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4153]
**Describe the bug**
Can't connect to any provider on Windows.
Lots of errors, probably related to NAT punching?

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7409556/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.66.4
 - OS: Windows

**Comment by Donatas-MN** [comment]
@cvl is this issue still relevant?

**Comment by cvl** [comment]
yes, keeps repeating over and over.

**Comment by cvl** [comment]
disable

**Comment by cvl** [comment]
Hi, here are some https://github.com/mysteriumnetwork/node/issues/created_by/portalsdevs
also https://github.com/mysteriumnetwork/node/issues/created_by/cvl

**Comment by Donatas-MN** [comment]
> Hi, here are some https://github.com/mysteriumnetwork/node/issues/created_by/portalsdevs also https://github.com/mysteriumnetwork/node/issues/created_by/cvl

This is just a list of issues, we need specific recent logs for this one.

**Comment by cvl** [comment]
Hi @Donatas-MN 
Yes, the issues are getting very old as they are not looked into in a timely fashion (if at all).

It's hard for me to understand which issues are related (i.e. recurring with similar bugs), as I'm not familiar with how Node is implemented.

I'd suggest that someone in Mysterium team would at least look into the issues when they are reported and possibly group into related issues (to have better understanding of the severity of the issue).

In this case we often receive NAT related errors for years e.g. https://github.com/mysteriumnetwork/node/issues?q=is%3Aissue+is%3Aopen+nat

**Comment by Donatas-MN** [comment]
> Hi @Donatas-MN Yes, the issues are getting very old as they are not looked into in a timely fashion (if at all).
> 
> It's hard for me to understand which issues are related (i.e. recurring with similar bugs), as I'm not familiar with how Node is implemented.
> 
> I'd suggest that someone in Mysterium team would at least look into the issues when they are reported and possibly group into related issues (to have better understanding of the severity of the issue).
> 
> In this case we often receive NAT related errors for years e.g. https://github.com/mysteriumnetwork/node/issues?q=is%3Aissue+is%3Aopen+nat

All of those issues reported have one thing in common - very old version of node. The first thing to be done should be updating to the newest one. If still notice issue after upgrading, we will check them.

**Comment by cvl** [comment]
We'll see.
