### ISSUE TITLE
Payment in progress. It should reach you before...

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4154]
**Describe the bug**
 Only one payment was made in September, there are a number of payments in progress messages, but nothing, other than September has been payed.
 
 node ID- 0x9e296ecdef8b2685414ffd39473b8adafadfeb36 

**Expected behavior**
Payments should not be in progress for longer than payout history dates.

**Screenshots**
<img width="410" alt="Screenshot 2021-10-25 at 22 58 12" src="https://user-images.githubusercontent.com/84313603/138776995-9bfe8ba6-8efd-4e52-8b42-cd202df2f3ab.png">

**Environment (please complete the following information):**
OS:
Raspbian GNU/Linux 10 (buster)
Architecture:
linux/arm
Node version:
0.67.4

**Comment by endosym1** [comment]
Same for my raspberry pi node - 0x761291e58271b325de94bf41c4fc939baf7abda7

payout address : 0x46264C8b03dd3AD3269b08f3C0834ABa80a39F3e

![Screenshot 2021-11-02 at 11 15 35 AM](https://user-images.githubusercontent.com/87921704/139793049-5511b78d-bea8-4c7c-9467-122703f2a951.png)

**Comment by eugenegoncharuk** [comment]
Correct message should appear in the Payout history

**Comment by eugenegoncharuk** [comment]
Please, check https://my.mysterium.network/nodes/8061/bounty-payouts
