### ISSUE TITLE
Node not paying out MYST to MetaMask

### ISSUE THREAD

**Issue by CyrilsGiantEyebrow** [mysteriumnetwork/node#4159]
**Describe the bug**

My Mysterium node is not paying out MYST to my MetaMask each month. There are more than 5MYST in my node account and I have received a bounty payment, separate to the MYST accrued through providing bandwidth. Can you help please?

**To Reproduce**

If you look at the first screenshot you can see that the payout has not happened. 

**Expected behavior**

MYST to be paid out to my account.

**Screenshots**

![41C1FB48-F7D3-4667-9742-BFED2222BC11](https://user-images.githubusercontent.com/93228382/138968142-9e05ccd3-455e-48de-9165-7f2ef097269e.png)
![95E4776E-B499-4CCA-AEFD-5FE80C1F8830](https://user-images.githubusercontent.com/93228382/138968192-5832381a-c8e0-4a7c-9328-43912b1edc2a.png)

**Environment (please complete the following information):**
 - Node version: 0.67.4
 - OS: Raspberry Pi
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A

**Additional context**

I’m not very tech savvy so am hopeful that whatever the fix is, that it is either really easy to do, or can be done at your end. 

Thanks and look forward to hearing from you.

Sean

**Comment by eugenegoncharuk** [comment]
The message is corrected for previous months.
Before 1 Oct 2021, there was a need to get 10 MYSTs to be paid.
https://my.mysterium.network/nodes/1037/bounty-payouts
