### ISSUE TITLE
Test Failed Issue

### ISSUE THREAD

**Issue by HRichiez6** [mysteriumnetwork/node#4168]
**Describe the bug**
I keep getting test failed. I recently updated the node and for some reason the service can't establish correctly.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag

**Additional context**

**Comment by isaackielma** [comment]
Hello there!

Could you please try doing some troubleshooting with this guide:https://docs.mysterium.network/node-runners/troubleshooting/#introduction-to-network-troubleshooting

It seems like your still have to do some router config and open some ports. Please let us know if that helps!
