### ISSUE TITLE
Add CI tests that will check services in the DEB package. 

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#417]
In the current CI process, there is no check for full operation with a DEB package. 
Only build and installation are done in the docker container. 
But we are not checking if services work correctly after installation since in the docker container it is replaced with a `docker-entrypoint.sh` script.

**Comment by zolia** [comment]
It is a bit better now since we started to use deb on our RPI builds, but in general we still need proper testing with different OSes: ubuntu16, ubuntu18, debian9, debian10, raspbian9, raspbian10.

**Comment by chompomonim** [comment]
I think our build and testing environment changed a lot since creation of this task. If we'll decide to make any changes there, let's create new task.
