### ISSUE TITLE
Entering the Bounty Payout Address with command "myst cli identities set-payout-address" doesn't show up in NNM

### ISSUE THREAD

**Issue by Durfduivel** [mysteriumnetwork/node#4178]
When I enter this commands;

myst cli identities unlock 0x654b5722464cebe70e61b8d5b74831946a7dea80
myst cli identities register 0x654b5722464cebe70e61b8d5b74831946a7dea80
myst cli mmn myst API-KEY
myst cli identities set-payout-address 0x654b5722464cebe70e61b8d5b74831946a7dea80 0xB6BF464940220C4202CD22674D3D1DA225C9923F

The Node is registered to my account and the Bounty Payout Address has been set.
I check this with this command;
myst cli identities get-payout-address 0x654b5722464cebe70e61b8d5b74831946a7dea80

And it confirms the address I have entered.

I also set a password with: myst reset thepassword (this should set a new password)

When I after that go to http://my_node:4449/#/settings
First I have to enter a new password.
After that it doesn't ask me for my API token and not for my payout address, it goes directly to the Dashboard.

I then see that all is filled in but not the payout address, this field is empty and this results in an error here;
https://my.mysterium.network/nodes/my_node/dashboard (exclamation mark (!) no bounty payout address set).

**Expected behavior**
I expected that after entering the cli commands all would be filled in in the NNM too.

**Environment (please complete the following information):**
Node version: 0.67.4
WebUI version: 0.4.6
Ubuntu 20.04
Native install; sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"

**Comment by eugenegoncharuk** [comment]
Node is not presented anymore in the nodes table in MMN.

**Comment by eugenegoncharuk** [comment]
Tried to reproduce with version 0.67.4. Wallet address appeared in MMN.

**Comment by Durfduivel** [comment]
Thank you Eugene, I will close this, I have moved the node to mainnet, I am participating in the mainnet test. I don't know what I did wrong with that, maybe it was my browser (cache) I don't know.
