### ISSUE TITLE
Bounties reset to 0 on several nodes this month, without payout happening

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [mysteriumnetwork/node#4185]
**Description of the bug**
My accumulated bounties have reset to 0 on November 1st for 12 of my 47 nodes. No bounty payout happened there. Then for all my other nodes, there was no such thing happening.

**List of nodes for which bounties reset to 0**
0x70c60965e679f9aecc4e81924706a1af65c84c3b
0x7d7922b368d64329df0d3883c4b5238416cbf4e7
0xe37e7fce408269cc7c283c5081e99c1d65a810b5
0x2d460b13e5929d3a5cd5805840836f6a7b483168
0x6f5e4d15e3b8b7710743a0ae477e0e9bcdceb8fb
0xb2b534be93ad14fb61ed29521700b6ff4daafe66
0x9b3aa83462392daef68d84ca9324bdf9447929f5
0xf85f57a802e1392494dcab9a931a7eb1da2ded09
0x0fae7efa93fb611c95d8a831398c19cd632a26dd
0x4e5dde13e06336904826a5e1c6b4ff0b4eca2caa
0x877b60fa4a247b332783131d26988c09961611d2
0x0dc8989046702f4879679760ec83fe1808f36a93

**Expected behavior**
I would expect the bounties to continue accumulating as usual, since there was no payout for these nodes, as they were ineligible.

**Screenshots**
![image](https://user-images.githubusercontent.com/44687951/139658807-59d5c094-646a-423c-8fa6-4b3af0af73bf.png)
![image](https://user-images.githubusercontent.com/44687951/139658863-e85b9a67-5c00-4137-ad3d-a3a57d189319.png)

**Environment**
 - Node version: 0.68.1
 - OS: Ubuntu 18/20
 - Docker: All nodes running on an up-to-date version of Docker

**Additional info**
There was just slightly below 5 MYSTT on each of these nodes.

**Comment by veldspar** [comment]
I can confirm this for my nodes 0x8ee1206b2bbd0cea4e554f3338d6a2463e8efa31 and 0x26bf7857b5f332637294b5013d28bb8a7b84d0f8 . payout window in MMN shows 

`Leaderboard positions were ineligible for payment. `

One of the nodes had > 10 MYST accumulated but is not on the leaderboard because of one of my other nodes which is on a different line but shares the same /24 network facing the internet. (One node has IP x-x-x-207, the ones that got nulled have x-x-x-199 / 200 (with x-x-x being hte same for all machines)Since I'm running my nodes primarily to help establish this project rather than to just make coin, its not a real problem but should it should really be fixed.

**Comment by eugenegoncharuk** [comment]
There is no node in the list you provided, that is eligible for payout. Please, check below.

0x70c60965e679f9aecc4e81924706a1af65c84c3b - is not eligible (not_residential / duplicate_subnet)
![image](https://user-images.githubusercontent.com/87538/139877847-2aca7558-905d-4c33-8bd6-bd4481963dfd.png)
================
0x7d7922b368d64329df0d3883c4b5238416cbf4e7 - is not eligible (not_residential / duplicate_subnet)
![image](https://user-images.githubusercontent.com/87538/139878067-b47f19f0-c193-449e-844f-8d87c2913991.png)
================
0xe37e7fce408269cc7c283c5081e99c1d65a810b5 - is not eligible (not_residential / duplicate_subnet)
![image](https://user-images.githubusercontent.com/87538/139878166-12c5ca5a-418c-4aeb-9957-225ec9f0d5b7.png)
================
0x2d460b13e5929d3a5cd5805840836f6a7b483168 - is not eligible (not_residential / duplicate_subnet)
================
0x6f5e4d15e3b8b7710743a0ae477e0e9bcdceb8fb - is not eligible (not_residential / duplicate_subnet)
================
0xb2b534be93ad14fb61ed29521700b6ff4daafe66 - is not eligible (not_residential / duplicate_subnet)
================
0x9b3aa83462392daef68d84ca9324bdf9447929f5 - is not eligible (not_residential / duplicate_subnet)
================
0xf85f57a802e1392494dcab9a931a7eb1da2ded09 - is not eligible (not_residential / duplicate_subnet)
================
0x0fae7efa93fb611c95d8a831398c19cd632a26dd - is not eligible (not_residential / duplicate_subnet)
================
0x4e5dde13e06336904826a5e1c6b4ff0b4eca2caa - is not eligible (not_residential / duplicate_subnet)
================
0x877b60fa4a247b332783131d26988c09961611d2 - is not eligible (not_residential / duplicate_subnet)
================
0x0dc8989046702f4879679760ec83fe1808f36a93 - is not eligible (not_residential / duplicate_subnet)
================
