### ISSUE TITLE
Bounty Payments Not Going Through

### ISSUE THREAD

**Issue by maessedai** [mysteriumnetwork/node#4186]
My bounty payments for June, August, and September still say in progress and I have only received myst from July. I thought it might resolve with time but hasn't.  My node address is 0x37cacf3baf5060639cbf47a3640d14d0c178b21a.  I have included a screenshot for reference.

I expected to receive the bounty payments on the date described but all are still in progress.  It also seems my balances have not always rolled over so I am not even sure how much I am owed in bounty payments.  

<img width="960" alt="2021-11-01" src="https://user-images.githubusercontent.com/86741374/139672351-41ba497d-aabb-40f7-8179-590f8ec5c16c.png">

**Environment (please complete the following information):**
 - Node version: 0.67.2
 - OS: AVADO

**Comment by Donatas-MN** [comment]
I can see the last transaction to you went through (25.0991 MYST were sent today). This amount includes bounties for August, September and October.
