### ISSUE TITLE
Migration node docker

### ISSUE THREAD

**Issue by wwjimenez** [mysteriumnetwork/node#4187]
good afternoon, I am trying to migrate a node from one server to another. 

According to the documentation I just have to copy the docker volume from the old server, and add it to the volume of the new server. the documents I copy are: nodeui-pass, keystore, testnet2. 

The log tells me this: ERR cmd / mysterium_node / mysterium_node.go: 68> The command could not be executed: error = "The wireguard service could not be executed: the server response is invalid: 500 Internal server error (http : //127.0.0.1: 4050 / services). Possible error: Request could not be executed: Get https://testnet2-location.mysterium.network/api/v1/location: net / http: request canceled while waiting connection (Client.Timeout exceeded while waiting headers) "stack = [{" func ":" (* serviceCommand) .runService "," line ":" 195 "," source ":" command.go "}, { "func": "goexit", "line": "1357", "source": "asm_amd64.s"}]

**Comment by vkuznecovas** [comment]
Hello, you seem to be still using the testnet2 version(` https://**testnet2**-location.mysterium.network/api/v1/location`). This version is rather old and deprecated, please update to a newer version.

See https://docs.mysterium.network/node-runners/setup/updating/#how-to-update-your-docker-node

**Comment by isaackielma** [comment]
wwjimenez

"I was able to solve the error by updating the myst image, but now despite using the same docker volume where it was in position 20 in the new docker, it is coming out as if it were a totally new node.

It comes out that I am in position 1196"
