### ISSUE TITLE
No Payout on Bittrex Wallet

### ISSUE THREAD

**Issue by amenwilli** [mysteriumnetwork/node#4189]
Hello, 
I've checked my payouts that should have been on my Bittrex wallet long ago. Here is an excerpt: 

2021, September # 468 # 76 Payment in progress. It should reach you before 2021-10-07.
2021, August # 405 # 88 Payment in progress. It should reach you before 2021-09-07.

But unfortunately I could not find any receipt of payment. I have checked my wallet address from Bittrex for MYST several times, but there is no error there. I don't know anymore what I could have done wrong.
I got this Problem with both of my Nodes.

If you need additional information, I will of course provide it later.

![Unbenannt1](https://user-images.githubusercontent.com/87032076/139731730-fe62fe73-59ae-4129-8133-305fde59d81b.JPG)

![Unbenannt](https://user-images.githubusercontent.com/87032076/139731764-ce1cd3ac-9f91-4ea4-96c6-7680f0003426.JPG)

**Screenshots**

 - Node version: 0.67.4
 - OS: Ubuntu newest

**Comment by etherunit** [comment]
Could you provide your node id?

**Comment by amenwilli** [comment]
Shure,
0x52619395587750463676511847d75d3c8fee359d
0x2aa10a6f0d7bdf3dcd2e3d1c0e4615af46c10378

**Comment by Donatas-MN** [comment]
Threshold for bounty payment was 10MYST in August/September and this amount was not reached. There was a bug in UI, so it was incorrectly shown that payment was made. You will receive the full amount with the payment for October as unpaid balances are carried to next month. Payment will be made in the next couple of days.

**Comment by amenwilli** [comment]
Thanks for Info.
