### ISSUE TITLE
[android] no fees known for chain 0: redis: nil

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4191]
**Describe the bug**
Can't connect to any provider. Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7459403/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.66.2
 - OS: Android

**Comment by tomasmik** [comment]
These values are literally pulled from the config. Is this your own node/app? Did you make any changes? As this should not be possible.

**Comment by cvl** [comment]
No, no changes for months/years in the app.

**Comment by tomasmik** [comment]
https://github.com/mysteriumnetwork/node/issues/4257
