### ISSUE TITLE
Fix Görli Testnet blockchain text during activation on Mainnet-beta

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4194]
<img width="595" alt="Screenshot 2021-11-02 at 18 50 04" src="https://user-images.githubusercontent.com/60128746/139910279-14103fb6-fd66-4047-82e6-def2ace1e68c.png">

Görli Testnet blockchain > Mainnet

**Comment by vkuznecovas** [comment]
where's the 20 myst coming from as well?

**Comment by Donatas-MN** [comment]
Solved with https://github.com/mysteriumnetwork/node/issues/4206.
