### ISSUE TITLE
Coingate payment didn't result in top up

### ISSUE THREAD

**Issue by Guillembonet** [mysteriumnetwork/node#4195]
A user tried to do a top-up using LTC but didn't receive MYST in his balance. Coingate payment is marked as payed.

Identity: 0xb92953f8f38014c3caae3d33685b1150c5c05bbd
Coingate order #9995734

**Comment by tomasmik** [comment]
This seems to be an issue on the payment provider side. I've contacted their support, we're investigating this futher.
