### ISSUE TITLE
Delay registration for users without stake

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#4199]
If node decides not to put stake, during first few days it should provide traffic for free and earn "karma". After proof that node is real and is providing traffic, registration could be initiated by monitoring agent or quality oracle and tx fee covered by transactor.

- [ ] Refactor "agree on price" part in node, so not registered  node would be free. --> 
- [ ] "Registrator" should register node after delay period passed successfully.
- [ ] Monitoring should get unregistered proposals for queue and start checking them. After check is ok, it could mark node as "good" and register it.
- [ ] Node should somehow know that he is registered and start sending proposals to discovery, only on this step discovery will start allowing his promises.

**PROBLEMS:**
- Discovery is not allowing unregistered nodes, so there may be needed additional queue with unregistered nodes from where monitoring will be picking it for check.
- Free nodes should be available only for chosen actors. Otherwise some other nodes can start resending traffic to then and being parasites.

**Comment by vkuznecovas** [comment]
Details would be nice :)

**Comment by chompomonim** [comment]
Details will be added here after grooming.

**Comment by chompomonim** [comment]
We decided not to move forward with this proposal as it has own downsides and may cause more problems than give benefits.
