### ISSUE TITLE
GoLint?

### ISSUE THREAD

**Issue by jiminoc** [MysteriumNetwork/node#42]
Whats the project's stance on golint and comments? 

So far from a casual glance I'm not seeing any comments or golint compliant source files. These things are much easier to add up front than backfilling and opens up the source to more devs who can follow along in the codebase. 

thx

**Comment by goktugyil** [comment]
Any updates?

**Comment by Waldz** [comment]
Kudos to @jiminoc for pointing out ;)

**Comment by Waldz** [comment]
@goktugyil we setuped helper command `bin/lint`.
Project still has lots of linter errors, and we are actively clearing them package by package.
