### ISSUE TITLE
NodeUI - Network registration step update

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4206]
This screen replaces screen mentioned in https://github.com/mysteriumnetwork/node/issues/4194.

Mysterium Network will be covering fees for limited amount of registrations, so the rest of the users will have to pay for their registration. 

Dedicated API endpoint will handle Provider registration and will tell if free registration is available for the user (ping @vkuznecovas in case additional details on API endpoint needed).

Solution flow:
1. User comes to this screen during onboarding with NodeUI. If free registration is not available then user is shown following instructions to deposit MYST. 
![image](https://user-images.githubusercontent.com/91055712/140085226-334c4782-665c-4bd6-a73f-5f8fa1c2e6d4.png)

Notes:
 - Once amount is received, user can click NEXT button (button is disabled until then).
 - Wallet address is user channel address.
 - After amount is received (available in blockchain), message changes to such:
![image](https://user-images.githubusercontent.com/91055712/140087103-6446e2d3-1bf3-4fa5-a5cc-775dc7e0ca74.png)

2. If free registration is available, user just needs to click NEXT:
![image](https://user-images.githubusercontent.com/91055712/140085593-19e6ee0e-02f1-4b0b-9ae4-68eecb3c724b.png)

3. If user clicks on "Don’t have any MYST? Read here how to get it!" then he is displayed a modal with following text:
```
To avoid transaction fees on Ethereum network, we recommend to use Polygon network for MYST transfers. Follow these steps to buy MYST tokens needed for registration:

1. Buy MATIC token for amount of $ you'd like to spend for MYST on Binance or any other exchange supporting Polygon network withdrawal.
2. Install Metamask wallet. Configure it work with Polygon (e.g. by using this guide https://medium.com/stakingbits/setting-up-metamask-for-polygon-matic-network-838058f6d844)
3. Withdraw your MATIC into wallet address generated by MetaMask. Don't forget to choose Polygon (not Ethereum) in Binance withdrawal interface.
4. Go to QuickSwap (https://quickswap.exchange/#/swap?outputCurrency=0x1379e8886a944d2d9d440b3d88df536aea08d9f3) and swap your MATIC to MYST.
5. Send required MYST amount for your node registration.
```

![image](https://user-images.githubusercontent.com/91055712/140087675-9f0d5c63-a5a0-4135-ab13-e4c6655b8cb6.png)

**Comment by chompomonim** [comment]
Is this already added into any release? How could I test it?

**Comment by Donatas-MN** [comment]
Yes, it's released. If `service` command is used and there are free registration available, user will be registered and he won't see that modal. If free registrations are used already then user will get the modal:
![image](https://user-images.githubusercontent.com/91055712/141088045-a5a1dffc-a602-4290-9e84-dade035524c6.png)
