### ISSUE TITLE
NodeUI - Improvements/Bug fixes for MainNet

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4207]
Improvements for MainNet NodeUI.

Tasks:
- [x] Change message on top of withdrawal screen to such: 

You can withdraw your collected earnings into own Ethereum or Polygon wallet address at any time. Please allow some time (usually a few minutes) for withdrawal transaction to be processed. Your balance will update once transaction was executed.

![image](https://user-images.githubusercontent.com/91055712/142378065-2ee4bac2-0656-47b1-a30f-59e01b67e896.png)

- [x] Make Polygon chain as default choice for Withdrawal

- [x] Add following warning message to Withdrawal screen when Polygon chain is chosen:

`Make sure withdrawal address is from ERC-20 compatible wallet (e.g. MetaMask or MyEtherWallet) supporting Polygon! Addresses from Ethereum network exchanges (e.g. Bittrex, HitBTC) are not supported for Polygon network withdrawals and your tokens might be lost.`

![image](https://user-images.githubusercontent.com/91055712/141316022-fc9e129b-db22-43f1-b482-bee1141135b3.png)

- [x] In Withdrawal screen change button name from "Withdrawal" to "Withdraw". 
![Pasted_Image_2021-11-11_15_36](https://user-images.githubusercontent.com/91055712/141307351-34b8f3cd-a1fc-4d2b-b9db-7ba2996e868e.png)

- [x] Change message here to: "Please click OK to proceed with your withdrawal request."
![image](https://user-images.githubusercontent.com/91055712/142374271-0c83a075-28cf-4d6e-9f06-6ce4026d993a.png)

- [x] Remove link from Tx Hash for now as link is not yet available in BE.

- [x] If user click OK to proceed with withdrawal and there is an error from backend, it's not handled in UI. Display such message in toast in case there is an error: "There was an error processing your withdrawal. Please try again later."

- [x] Remove possibility to adjust number by scrolling with mouse. It's really easy to change entered number by just scrolling mouse:
![image](https://user-images.githubusercontent.com/91055712/142401737-c3d72b2f-0e59-4c48-991d-27c3a12395bf.png)

- [x] In Settings pages change "MMN integration" section name to "Mystnodes.com integration".
![image](https://user-images.githubusercontent.com/91055712/142378424-3e27a24f-9835-401e-9a80-ac2b8e07f197.png)

- [x] Change my.mysterium.network to mystnodes.com in the 1st screen of onboarding pop-over (password setup screen):
![image](https://user-images.githubusercontent.com/91055712/141427989-97c239f1-3c8f-4b5b-a133-c2939de674f3.png)

- [x] In Step2 of Onboard Install Metamask wallet - change link to our official documentation (https://docs.mysterium.network/node-runners/payout-guide/#link-metamask-to-the-polygon-network) instead of an external resource.

- [x] MainNet NodeUI version number should look nice (instead of current 0.5.0-mainnet17):
![image](https://user-images.githubusercontent.com/91055712/142166533-0d56375e-a11d-4e33-94c7-30200ef9ea59.png)

- [x] Update link from https://mystnodes.com/user/profile (blank page) to https://mystnodes.com/me
<img width="653" alt="Screenshot 2021-11-16 at 21 27 17" src="https://user-images.githubusercontent.com/60128746/142052339-75027f75-a94b-46d9-9490-526c3411d6a2.png">

**Comment by etherunit** [comment]
Just noticed 
<img width="463" alt="Screenshot 2021-11-16 at 20 39 41" src="https://user-images.githubusercontent.com/60128746/142045822-24e4fabf-9906-4522-90de-9cfefa4b6ab3.png">

**Comment by Donatas-MN** [comment]
> Just noticed <img alt="Screenshot 2021-11-16 at 20 39 41" width="463" src="https://user-images.githubusercontent.com/60128746/142045822-24e4fabf-9906-4522-90de-9cfefa4b6ab3.png">

Already in the list :)

**Comment by lusine-h** [comment]
**Precondition**
Node UI is opened with not enough balance for withdrawal

**Steps to reproduce**

- I click on the Withdraw button

**Expected result**
The screen is scrollable and I can see a close button on the screen

**Actual result**
The screen isn't scrollable, Close and Withdraw buttons aren't displayed

![Withdrawal-screen](https://user-images.githubusercontent.com/60058956/144059060-c9838f41-6da0-4bbd-9f8f-9e880fcdd056.png)
ed

**Comment by lusine-h** [comment]
**Precondition**
Node UI is opened

**Steps to reproduce**

- I click on the Withdraw button
- I decrease the Amount number using the arrow down

**Expected result**
For negative numbers, a validation message is displayed

**Actual result**
I can increase numbers without limit (included negative numbers)

![image](https://user-images.githubusercontent.com/60058956/144214740-1c5ad523-85eb-4c94-b31b-d263c085d314.png)
