### ISSUE TITLE
DAI Top up fail 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4208]
**Describe the bug**

Approximately 18 DAI transferred to get 20 MYST to use the service. Mysterium DAI top up address was scanned with the QR code, generated by Mysterium. So there is no possibility for a typo on address inputting.  Please advise. 

Mysterium ID is

0xd38ddb4881648e661939982d85626a3b59b4e361

Below is the transaction information:

https://etherscan.io/tx/0x76eea8e7d1acd53ccc91cc1c8e2589fa7e50c22b8a4f34083f019aea29c3e174

**Additional context**

**Comment by tomasmik** [comment]
Money sent. Coingate issue solved.
