### ISSUE TITLE
Add instructions on how to set up auto update for RPI and Ubuntu

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4209]
**Is your feature request related to a problem? Please describe.**
At the moment, many of our node runners are unaware of auto update feature. As a result, node runners end up having to manually update their nodes.

**Describe the solution you'd like**
If the instructions were available within our documentation pages, I believe that more providers would be aware of this possibility and benefit from it. 

**Additional context**

sudo apt-get -y install  unattended-upgrades
after that create file
/etc/apt/apt.conf.d/50unattended-upgrades with a content from here https://github.com/mysteriumnetwork/node/blob/master/bin/package/raspberry/files/unattended-upgrades
and file
/etc/apt/apt.conf.d/20auto-upgrades with a content from here https://github.com/mysteriumnetwork/node/blob/master/bin/package/raspberry/files/auto-upgrades
unattended-upgrades
<https://github.com/mysteriumnetwork/node|mysteriumnetwork/node>mysteriumnetwork/node | Added by GitHub
auto-upgrades
<https://github.com/mysteriumnetwork/node|mysteriumnetwork/node>mysteriumnetwork/node | Added by GitHub

**Comment by veldspar** [comment]
Simpler solution: ues crib

`crontab -e`
Add a line saying 
`0 0 * * * apt update && apt -y upgrade`

Be done with it
