### ISSUE TITLE
NodeUI - Bandwidth limiter enhancements

### ISSUE THREAD

**Issue by nmargaritis** [mysteriumnetwork/node#4210]
**Is your feature request related to a problem? Please describe.**
Bandwidth limiter is a good feature, however a single setting for it, is not that practical.
I believe that most end-users will want to have higher flexibility when controlling bandwidth throughout the day and week. For example, one might like to set it to 10Mb/s during working hours and set it to 95Mb/s during night time, when the network is idle.

**Describe the solution you'd like**
I suggest that, you allow someone to control the bandwidth on a daily or even better weekly basis.
Users should be able to set different time-slots and have different bandwidth configurations applied dynamically.
Including days on the week for this feature, either initially or in a second iteration would also prove helpful. Usage usually varies between days in households or work environments.

**Describe alternatives you've considered**

1. Set myst node UI limit to maximum
2. SSH to rasp pie
3. installing `wondershaper` or similar utility to limit the bandwidth of the interface
4. identifying network interface (in our case eth0)
5. write an executable `.sh` file including `wondershaper {interface} {down} {up}` with daily or weekly routines
6. setup a cron job and crontab (`@reboot`) to change the bandwidth of the interface dynamically based on previously set routines

However, this is not something any person looking to run a node will be able to do, or even attempt to do. Supporting this through the UI will make it easier/simpler for the majority of your target audience.

**Additional context**
-

**Comment by CharlyEmpereurmot** [comment]
Also a maximum bandwidth usage per time unit (day/month/whatever) would be appreciable!

**Comment by Ayse-AK** [comment]
bandwidth can be set
