### ISSUE TITLE
Misinformation about bandwidth (limiter)

### ISSUE THREAD

**Issue by nmargaritis** [mysteriumnetwork/node#4217]
**Describe the bug**
Node UI is showing misleading info about the measurements of the bandwidth's limiter. Inside is says Mbs (normally megabit). When you set this, in the outer menu you see MBs (megabytes) due to capitalization.

Megabytes and Megabits are not the same thing, 100 Mbp/s are 12.5 MB/s
This can lead to misconfigurations and overall is wrong. Please state the exact measurement as is.

**To Reproduce**
Visit NodeUI

**Expected behavior**
Clearly define if it is Mbp/s or MB/s you refer about.

**Screenshots**
![Screenshot from 2021-11-05 01-32-52](https://user-images.githubusercontent.com/7851375/140435897-14318635-6994-40c1-895b-760fd188881b.png)
![Screenshot from 2021-11-05 01-32-43](https://user-images.githubusercontent.com/7851375/140435899-db29f211-5b82-4d98-b6d4-f83f86559681.png)
**Environment (please complete the following information):**
NodeUI

**Additional context**

**Comment by Donatas-MN** [comment]
This is a known issue and the fix will come with MainNet release.

**Comment by Guillembonet** [comment]
> This is a known issue and the fix will come with MainNet release.

Yes, but I will modify Mb/s to MB/s in the popup menu as a quick fix before MainNet as I also fixed another thing in node-ui.

**Comment by nmargaritis** [comment]
> > This is a known issue and the fix will come with MainNet release.
> 
> Yes, but I will modify Mb/s to MB/s in the popup menu as a quick fix before MainNet as I also fixed another thing in node-ui.

To my understanding your underlying measurement  is actually megabits and not megabytes, **which is Mbp/s**. Cause the limiter goes from 5 to 200!! A lowest possible value for a limiter that is 5Mbp/s, is actually translated to 625 kB/s. (maybe this measurement is what you are actually used to). 

Now If the limiter is referring to MB/s then there is another problem, that is a lowest value of 5 is actually **too big** for a starting point. Because this means that the possible lowest limit you can set are ~40Mbp/s. Now given that most home internet connections plans are at 50Mbp/s, this will render the bandwidth limit functionality almost useless.
[Speedtest Mbp/s global index](https://www.speedtest.net/global-index)

You need to set the representation to what actually is underlying. So verify if it is MB/s or Mbp/s. Chances are that it refers to Mbp/s. Setting it incorrect, will not resolve this issue but instead cause greater confusion.

**Comment by Donatas-MN** [comment]
Currently it's in MB/s (Megabytes per second).
