### ISSUE TITLE
Showing as online nodeUI, but no data is transferred

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4230]
**Describe the bug**
🆔 0x509de225b5fca67e7dc87960a88a8ee62ba24b25

Just installed this node using macOS launcher.

Ports were successfully set to 10000 to 60000 manually. I have even called my ISP to be sure and they confirmed me that ports are open as of now.
Accepting most connections on node UI

showing as online nodeUI but test failed on MMN and receiving test connections successfully. However, no data is transferred. 

**Expected behavior**
Node should be receiving sessions and transferring data

**Screenshots**
<img width="801" alt="Screenshot 2021-11-06 at 21 59 39" src="https://user-images.githubusercontent.com/84313603/140625019-6e7587d3-f83f-47c8-aaa7-9d45aa414851.png">
<img width="801" alt="Screenshot 2021-11-06 at 21 59 39" src="https://user-images.githubusercontent.com/84313603/140625020-e8ba0168-4290-4232-8828-aee09596235d.png">
<img width="1176" alt="Screenshot 2021-11-06 at 21 59 54" src="https://user-images.githubusercontent.com/84313603/140625033-9f1b416f-edc0-4d08-9241-6ffe9b916876.png">

**Environment (please complete the following information):**
 OS: Alpine Linux v3.12(docker)
Architecture: linux(docker)/amd64
Node version: 0.68.2

**Additional context**

Logs:

[mysterium-node-20.log](https://github.com/mysteriumnetwork/node/files/7491304/mysterium-node-20.log)

**Comment by iamwoz** [comment]
Same issue here, just manually specified 0.68.1-alpine tag to rollback and once again is working fine. 

Rolled forward to 0.68.2 and immediately the same problem. Rollback to 0.68.1 and fine.

**Comment by Snawoot** [comment]
Original issue looks caused by

```
2021-11-04T16:49:10.779 ERR p2p/channel.go:417                       > Handler "p2p-session-create" internal error error="cannot start session: : cannot get provider config for session 4460731e-e0ab-445a-8fb1-ad6432372f6e: could not start new connection: could not run conn endpoint factory: socket: protocol family not supported"
```

**Comment by Snawoot** [comment]
wireguard doesn't work for some reason when running x86_64 image on apple M1 machine

**Comment by coolman28129** [comment]
Same here mine shown it works and all but it doesn't just earn. It does only shows and it's test for the earnings

**Comment by dave9123** [comment]
Raspberry Pi 3 works with this tho
