### ISSUE TITLE
[improvements] NodeUI mainnet on-boarding process 

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4236]
1. Currently, during the onboardings free registration on the Mysterium Network user is prompted to "Change the default password" instead of Creating a new one. From UX point of view, it's misleading and might cause some confusion.  It's an indication that account might had some previously generated record that user is not aware of (at least he potentially could not be as not all users are reading docs carefully). 

**Describe the solution you'd like**
User is asked to create a new password. 

<img width="1511" alt="Screenshot 2021-11-09 at 08 51 53" src="https://user-images.githubusercontent.com/60128746/140879154-90a065e6-be5c-42f5-83a4-36d2bd144809.png">

2. Step2 _Install Metamask wallet_ - point to our official documentation (https://docs.mysterium.network/node-runners/payout-guide/#link-metamask-to-the-polygon-network) instead of an external resource.

**Comment by Donatas-MN** [comment]
Covered in https://github.com/mysteriumnetwork/node/issues/4207.
