### ISSUE TITLE
Query language to to filter storage data

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#424]
**In order** to have to filter proposals by properties 
**As a** Tequilapi caller
**I want to** have some standard to query proposals+relational data about proposals

- Filter by proposal `serviceType = "openvpn"`
- Filter by proposal `providerId = "0x1"`
- Filter by proposal `serviceDefinition.location = "US"`
- Filter by quality metric `connection.failedConnection <= 3`
- Filter by quality metric `sessions.activeCount > 1`
- Filter by named filter `filter = "US-active"` save named filter `active-US` with all filters

**Comment by Waldz** [comment]
- What tools for query language we have?
- How query language will be integrated to our storage solution?

**Comment by soffokl** [comment]
Do we really need to have something complicated as a query language? 
Maybe we can just use REST with some arguments?

**Comment by Waldz** [comment]
Can you investigate and create a demo for our chosen storage solution
