### ISSUE TITLE
Modem constantly freeze when running mysterium node

### ISSUE THREAD

**Issue by breezytm** [mysteriumnetwork/node#4240]
**Describe the bug**
I have an AVADO which I am using to stake ETH. Whenever I run the Mysterium package it causes my modem to freeze. I ran the ETH validator for 3 months prior to introducing Mysterium and it ran without any issue. I had a perfect score for everything. After I started running the node I began having many missed attestations. After much testing, it became abundantly clear the Mysterium node was the culprit. I shut it down and the Internet issue went away. I turned it back on for a day and the issue came back. Now I would like to remove the package on my AVADO since I have it on Pause but it keeps turning itself back online. I can not delete the package since I have some MYST on there. Can you please withdraw all the MYST and send it to my wallet? 

0xa971e8ac67360916367aa2ee6ce552c9de3e2b59

**To Reproduce**
I simply have to start the Mysterium node. A few times a day I would have to reboot my modem for the internet to start working again. I have not needed to reboot my modem since I stopped the node 6 days ago. 

**Environment (please complete the following information):**
 - Node version: 0.67.2
 - OS: AVADO

**Comment by isaackielma** [comment]
Provider has already talked with the Avado team on this subject matter. Nothing they can do about it. 

Currently I am constantly login into the AVADO checking to see if the package is turned back on to turn it off. The logical thing to do would be to remove it completely, but I have about 30 bucks on there worth of Myst. Anyway on recovering this myst with Avado node turned off?

**Comment by isaackielma** [comment]
As explained on intercom, we don’t have withdrawal on testnet as it’s still MYSTT there. 

"Please note that there is no way to withdraw or transfer your tokens on Testnet. You will have to wait for a payment for running a node service which will be executed at the start of the upcoming month. If your node qualify - the amount earned will be transferred to the specified wallet address.

 

More information: https://docs.mysterium.network/token/bounty/"

**Comment by breezytm** [comment]
Well here's the caviat. I can not run my node to earn enough MYSTT to be qualified for the bounty because when I run it my internet stops working. Perhaps all available MYSTT from testnet should be withdrawal and send to bounty wallet right before mainnet. At least no one would call foul.
