### ISSUE TITLE
[android] node doesn't work, multiple errors (could not fetch fees, no contract code at given address)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4256]
**Describe the bug**
Node doesn't work properly on Android, I can see multiple errors. Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7526928/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.68.1
 - OS: Android

**Comment by tomasmik** [comment]
https://github.com/mysteriumnetwork/node/issues/4257
