### ISSUE TITLE
NodeUI - Possibility to restart node

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4258]
Tasks:
- [ ] Add possibility to restart node. 
[Icon](https://fontawesome.com/v6.0/icons/arrow-rotate-right?s=solid) could be added here:
Pasted_Image_2021-11-25_13_02

After button is clicked, show "Do you really want to restart your node?" with Cancel and Restart buttons.

**Comment by Donatas-MN** [comment]
Icon could be added here:
![Pasted_Image_2021-11-25_13_02](https://user-images.githubusercontent.com/91055712/143429899-6e79ac08-878e-44a1-a494-ae207aeff1e6.jpg)

**Comment by Donatas-MN** [comment]
Research is needed to understand what would be possible and on what devices.

**Comment by Donatas-MN** [comment]
Grooming needed with Protocol to agree on max settlement limit.

**Comment by mdomasevicius** [comment]
- The most desirable way to restart node would be to initiate soft shutdown in the code, then allow everything to be garbage collected and then re-initiate all the node command start sequence. Unfortunately the way node was coded it is not possible out of the box. Shortly - this solution would require revising entire code base, and might end up as a Herculean task.

- Another less appealing option is somehow triggering OS to make a restart for you. But that inherently bring problems of it's own. Different OS, different environments ant methods on how node was started. It might break easily and most likely will require constant maintenance.

**Comment by Donatas-MN** [comment]
We should try discussed option with Vlad. Also add feature flag, so it could be turned ON/OFF.

**Comment by soffokl** [comment]
Why do we need to restart a node? Don't we have everything to apply changes on the fly?
Sounds like another workaround instead of fixing things properly.

**Comment by Donatas-MN** [comment]
There a couple of things in general:
1. Node runners have been asking a lot for this feature as "simple restart" fixes some of the issues we have from time to time (e.g. not updating balances, issues with withdrawals). In general, those issues are being fixed, but having possibility to simply restart node would also help with such things in the future.
2. Also there were a couple things like changing auto-settlement value which with current node logic would require restart.

**Comment by Donatas-MN** [comment]
Works fine on docker.

Text/design fixes:
1. Change icon to "restart" one (currently looks like "shutdown" icon).
2. Update text here:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/91055712/158400563-aae471df-4d16-4891-9949-c063f2484227.png">
Are you sure you want to restart your node?
Button name: OK --> Restart
3. Update text here:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/91055712/158400901-cebd52d8-6851-4528-9ae5-e6ffd0795ac7.png">
Node is being restarted. Page will automatically refresh in ...s.
