### ISSUE TITLE
Topup in consumer mode fails

### ISSUE THREAD

**Issue by jkimmel** [mysteriumnetwork/node#4260]
I have setup a Raspi 3B in consumer mode under Buster.
Everything looks ok but when I try to get a top-up I get following rerror:
```
pi@raspberrypi:~ $ myst account topup --amount 100 --currency BTC
[ERROR] Can't continue, no such gateway:

```

**Comment by tomasmik** [comment]
The command is supposed to be like this:
```
myst account topup --amount 100 --currency BTC --gateway coingate
```

Docs are updated to reflect these changes.
