### ISSUE TITLE
Germany only sessions for the most part

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4266]
**Describe the bug**
0x3fa7d8326e01e67594ef5123d9efff029f9adb9f node

Sessions from Germany, every time it finishes at 10 minutes and 5 or 6 seconds, it is never longer. What is the reason.

**To Reproduce**
1. Go to 'mmn'
2. Click on 'view all sessions'
3. Scroll down

**Expected behavior**
Provider should be getting normal sessions from all over the world and not just Germany. Since he is not whitelisted.

**Environment (please complete the following information):**
OS:
Alpine Linux v3.12(docker)
Architecture:
linux(docker)/amd64
Node version:
0.68.3

**Additional context**
Waiting on logs input

**Comment by Donatas-MN** [comment]
Those are Test sessions from our Monitoring agent. I can see the node is in Bulgaria, so most probably demand is too low for this region.
