### ISSUE TITLE
When will they be paid? :) (Joke)

### ISSUE THREAD

**Issue by Shade1981** [mysteriumnetwork/node#4268]
Am I glad I managed to collect so many MYSTs when I can withdraw them in one lump sum?
![hohack3](https://user-images.githubusercontent.com/40514262/141778408-a320b90e-9bc7-4889-8d7a-49ff2e91f52b.png)

My ACC was intentionally blurred.
The knowledgeable professionals can still identify me.

**Comment by tomasmik** [comment]
Get the latest mainnet build of node and invite for a ride in the new lambo

**Comment by Shade1981** [comment]
The trouble is, it's not a joke ... This is really what my account writes

**Comment by Shade1981** [comment]
Please reopen the post and someone find a reasonable solution ...

**Comment by tomasmik** [comment]
> The trouble is, it's not a joke ... This is really what my account writes

Thanks for creating an issue, but next time please provide a proper title and description.
@Donatas-MN re-open if needed

**Comment by Donatas-MN** [comment]
Fix is already on a way, so no lambo :)

**Comment by Shade1981** [comment]
Thank you very much, although I would have been happier if I could have bought you a lambo from this amount.

> Fix is already on a way, so no lambo :)
