### ISSUE TITLE
nodeUI mainnet rc1.0.0 - tries to login with wrong password

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4271]
**Describe the bug**
After setting up mysterium node, try to login to node ui interface. you will be greeted with no error just a blank page with the loading circle of node ui.
quick debug with live http headers reveals that the webif for some reason tries to autologin with user myst and password mystberry. all subsequent requests are answered by nodeui with 401 unauthorized(which, since the password has been changed makes sense, still a user friendly error would be great). Grabbing the JSON Request with live headers in firefox and changing the password to the user specified nodeui password and then resending the request resolves the problem

**To Reproduce**
1. Go to 'http://127.0.0.1:4449/'
2. greeted by empty white page. 

**Expected behavior**
Expected would be nodeui asking for the password

**Screenshots**

**Environment (please complete the following information):**
 - Node version: mainnet 1.0.0-rc
 - OS: client and node machine run debian bullseye

**Additional context**

**Comment by Guillembonet** [comment]
should be fixed by mysteriumnetwork/dvpn-web#228
