### ISSUE TITLE
Global bounty payout not happening

### ISSUE THREAD

**Issue by sammers230** [mysteriumnetwork/node#4272]
I have been running my node for a few months and have accumulated on both the residential and global bounty leader boards. 
The residential bounty system has been giving. A payout pretty much every months but the global bounty system currently has not given any payout even with any roll over from the previous months accumulation.
Currently at the time of writing the top 5 in the UK where I am based is showing from 16.8242 MYST - 92.1271 MYST.
My global bounty payout is showing on my node at 261.9777 MYST and have been instructed to submit a bug report here.

The node ID for this is 0xf83d0c3ce39a80507cccaf618941ff8b769a0fc1
Currently running version 0.67.4

If any other details are needed I’m happy to assist and add them here.

**Comment by tomasmik** [comment]
Wallet set for the node is this: https://etherscan.io/address/0x537D00dE964C5997DDbfD8c1F970cC063a112F98#tokentxns

It's been paid multiple times. Including the previous months. 
![image](https://user-images.githubusercontent.com/40318863/141813599-04effb80-9a96-4fbe-84f5-fd3e588b3237.png)

**Comment by Donatas-MN** [comment]
Global bounties are paid to Top 5 nodes in each country. I can see that your node did not reach Top 5, e.g. in September it was #60, then in October it was #31. That's why your balance is transferred to next month and if you will be Top 5 in November you will get paid the whole amount.

**Comment by sammers230** [comment]
So the roll over of the bounty into the next month and the subsequent populated MYST have no relevance to the position. Meaning I could have amassed what’s likely going to be around 500 MYST by the time I’m shown within the top 5 on the global bounty leaderboard before getting a capped payout of 20 MYST for one month?
If so what are the metrics used to determine who makes the top 5 as the example description given in the docs reads as if the accumulated MYST is what denotes your leader board position.
