### ISSUE TITLE
When trying to report a bug thru bug button, it failed

### ISSUE THREAD

**Issue by pianoman10** [mysteriumnetwork/node#4273]
**Describe the bug**
When trying to report a bug thru bug button, it failedç
I got the following message (see screenshot)

**To Reproduce**
1. Go to 4449/#/dashboard
2. Click on Bug button on the left bottom side
3. Write in the box
4. click SEND
5. Got the error (see attachment)

**Environment (please complete the following information):**
Node version: 0.67.4
WebUI version: 0.4.6
on raspberry pi 4

**Comment by etherunit** [comment]
@pianoman10 Could you submit node logs? Fortunately, it includes some data related to this incident.
