### ISSUE TITLE
Erroneous balance reflecting an outrageous amount of tokens

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4274]
**Describe the bug**
Main net Node ID- 0x92e7d46dbb818cfbabbcfee37c0co3c4cf2a64acbd

Erroneous balance reflecting an outrageous amount of tokens:

**Expected behavior**
Node balance should not be that high.

**Screenshots**
<img width="869" alt="Screenshot 2021-11-16 at 11 13 50" src="https://user-images.githubusercontent.com/84313603/141975516-14cb740c-f79a-485c-a644-aa497e409443.png">

**Environment (please complete the following information):**
 Alpine linux v3.12 (docker)
 1.0.0-rc

**Comment by tomasmik** [comment]
Already fixed I believe https://github.com/mysteriumnetwork/node/issues/4268
