### ISSUE TITLE
Node status issue

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4276]
Unexpected disconnection. Client has reconnected to the server but node remains offline on MMN 2.0 dashboard. Container is up and running.

```
2021-11-16T19:00:00.700 DBG eventbus/event_bus.go:81                 > Published topic="NAT-type-detected" event=prcone
2021-11-16T19:02:03.117 WRN communication/nats/connection_wrap.go:102 > NATS: disconnected error=EOF
2021-11-16T19:02:10.786 WRN communication/nats/connection_wrap.go:103 > NATS: reconnected
```
<img width="1352" alt="Screenshot 2021-11-16 at 21 08 42" src="https://user-images.githubusercontent.com/60128746/142049729-0f6653cc-041e-440d-8c66-a77682968c3c.png">

All active containers are reported as offline on MMN 2.0

```
CONTAINER ID   IMAGE                           COMMAND                  CREATED             STATUS          PORTS                                       NAMES
1845d9df080a   mysteriumnetwork/myst:mainnet   "/usr/local/bin/dock…"   28 minutes ago      Up 28 minutes   0.0.0.0:4477->4449/tcp, :::4477->4449/tcp   myst77
e134306b5d1f   mysteriumnetwork/myst:mainnet   "/usr/local/bin/dock…"   58 minutes ago      Up 16 minutes   0.0.0.0:4478->4449/tcp, :::4478->4449/tcp   myst78
fe2c6c4fb153   mysteriumnetwork/myst:mainnet   "/usr/local/bin/dock…"   About an hour ago   Up 16 minutes   0.0.0.0:4479->4449/tcp, :::4479->4449/tcp   myst79
```

<img width="1072" alt="Screenshot 2021-11-16 at 22 02 39" src="https://user-images.githubusercontent.com/60128746/142057330-1aadd6dc-f208-4706-aefc-9208542784a2.png">

<img width="1342" alt="Screenshot 2021-11-16 at 22 00 23" src="https://user-images.githubusercontent.com/60128746/142057082-8001ed63-afc0-4ba3-a43a-ab6590473643.png">

**Comment by Donatas-MN** [comment]
Issue was recently resolved with MystNodes.com bug fixes.
