### ISSUE TITLE
Fix on-boarding text

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4277]
my.mysterium.network - > mystnodes.com

<img width="463" alt="Screenshot 2021-11-16 at 20 39 41" src="https://user-images.githubusercontent.com/60128746/142050179-7821a555-8f68-4999-8fc6-2787a3184166.png">

**Comment by Donatas-MN** [comment]
Covered in https://github.com/mysteriumnetwork/node/issues/4207.
