### ISSUE TITLE
Update API keys "Get it here" link

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4278]
<img width="653" alt="Screenshot 2021-11-16 at 21 27 17" src="https://user-images.githubusercontent.com/60128746/142052339-75027f75-a94b-46d9-9490-526c3411d6a2.png">

Update from https://mystnodes.com/user/profile (blank page) to https://mystnodes.com/me

**Comment by Donatas-MN** [comment]
Covered in https://github.com/mysteriumnetwork/node/issues/4207.
