### ISSUE TITLE
NodeUI - User is prompted to create a default WebUI password twice

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4279]
1st run
<img width="1678" alt="Screenshot 2021-11-16 at 21 33 50" src="https://user-images.githubusercontent.com/60128746/142053455-1bc4eeda-3653-4159-98d5-d538dfd46df7.png">

Click Save and Continue.

`2.0be93341.chunk.js:2 POST http://127.0.0.1:4477/tequilapi/auth/login 401 (Unauthorized)`

2nd run 

<img width="1680" alt="Screenshot 2021-11-16 at 21 36 23" src="https://user-images.githubusercontent.com/60128746/142053622-3a79e350-8dc0-4fbb-95eb-38b32c2ee067.png">

Relates to #4271

**Comment by Donatas-MN** [comment]
Happened also to me when onboarding TV Box (Armbian) node.

**Comment by Guillembonet** [comment]
This seems to be an issue with the onboarding flow design, should be fixed by mysteriumnetwork/dvpn-web#238 once merged
