### ISSUE TITLE
[feature request] Make MMN 2.0 cross-platform responsive

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4282]
![Screenshot_2021-11-16-23-07-53-192_com android chrome](https://user-images.githubusercontent.com/60128746/142066123-842c0c8a-868a-48fa-91e2-b8c3f37588e8.jpg)

**Comment by Donatas-MN** [comment]
Initial responsiveness is coming with https://github.com/mysteriumnetwork/mmn/issues/73.

**Comment by lusine-h** [comment]
We don't have Logout boutton both on Android and IOS versions.

**Comment by Donatas-MN** [comment]
@lusine-h add this bug to https://github.com/mysteriumnetwork/mmn/issues/73. Thanks!
