### ISSUE TITLE
Earnings=2e 

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4283]
<img width="1336" alt="Screenshot 2021-11-17 at 08 34 47" src="https://user-images.githubusercontent.com/60128746/142147113-bae17326-4500-4834-989e-9d9fec81f405.png">

**Comment by Donatas-MN** [comment]
Covered in https://github.com/mysteriumnetwork/mmn/issues/55.

**Comment by Donatas-MN** [comment]
Solved.
