### ISSUE TITLE
The programs are running but there is no connection.

### ISSUE THREAD

**Issue by Shade1981** [mysteriumnetwork/node#4284]
**Describe the bug**
I asked my service provider to take it out from behind NAT. Removed, but the ports are still not public. My port forwarding is set to 10000-60000 in the router.
Router TP-link Archer C2, modem from my service provider in bridge mode ZTE ZXHN 618.

**Environment (please complete the following information):**
 - Node version: 1.0.0-rc
 - OS: Alpine Linux v3.12(docker)
 - Desktop app version (if applicable): 1.0.19
 - Docker (if applicable): 4.2.0

I am looking for a solution if anyone could help me I would be very grateful.

[bugreport.txt](https://github.com/mysteriumnetwork/node/files/7552550/bugreport.txt)

bugreport.txt is an approximately 24-hour log file created by the docker

Thank you for a help!

**Comment by etherunit** [comment]
Could you provide us with your node id?

**Comment by Shade1981** [comment]
Yes, I will. Here, though, I thought it was in the log file.
0x92e7d46dbb818cfbabbcfee37c03c4cf2a64acbd

**Comment by Shade1981** [comment]
> Could you provide us with your node id?

Yes, I will. Here, though, I thought it was in the log file.
0x92e7d46dbb818cfbabbcfee37c03c4cf2a64acbd

**Comment by Shade1981** [comment]
_WRN requests/dialer_swarm.go:293             > Failed to lookup host: "pilvytis.mysterium.network" error="lookup pilvytis.mysterium.network on 192.168.65.5:53: dial udp 192.168.65.5:53: operation was canceled"_

What does this mean? This red text is repeated. How can I prevent this from happening because I think here is the source of the error.
