### ISSUE TITLE
My payments are not made

### ISSUE THREAD

**Issue by Rtoprakci** [mysteriumnetwork/node#4287]
Hello there.  they use vpn service but they are not paid.

**Screenshots**
![E7C546B4-B0C0-403B-B683-962D18E2F82F](https://user-images.githubusercontent.com/93008706/142268620-aa59c6fd-521d-4144-8dfb-90d46ec2c5a5.png)

**Environment (please complete the following information):**
 - Node version: 0.68.3
 - OS: rasbian 
 - My node : 0x457c24f8ca52573347a83ab8c0cefc4029b0e461

**Comment by Donatas-MN** [comment]
@Rtoprakci can you check these sessions in NodeUI? Are they paid there? It's probably just a data sync issue, so in other words you're still getting paid.

**Comment by Rtoprakci** [comment]
@Donatas-MN Hello there. I did not receive any payment.

![Opera Anlık Görüntü_2021-11-19_143042_my mysterium network](https://user-images.githubusercontent.com/93008706/142615945-96b6dbe1-926a-4162-8a98-22ff7ba076da.png)

**Comment by Donatas-MN** [comment]
This screenshot you just sent is from my.mysterium.network. It's taking data from Node, so it would good if you could check these sessions in NodeUI - [local-ip-of-your-node]:4449, for example something like: https://192.168.1.8:4449.

I think it's just data sync issue and you actually got reward in NodeUI.

**Comment by Rtoprakci** [comment]
@Donatas-MN If you look at the other location from the link below, I can't see nodeiu, can you help with this?

[4142](https://github.com/mysteriumnetwork/node/issues/4142)
