### ISSUE TITLE
Failed transaction waiting for resolution

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4288]
**Describe the bug**

Telegram User: Iam Jas
"Below is my TX from the 2nd of February in which I by mistake sent my mysterium tokens to Mysterium wallet. 😔
I then communicated with Mysterium team about that back then and they told me that they can send it back to me. They told me to wait a bit and that they will inform me when everything is done. But since then I received no messages or somewhat of information about my incident."

Thanks in advance.

https://etherscan.io/tx/0x722e4d3c1784f7d101159b4c092a9008afae77fb130a750229d2be83fb9e38df

Ethereum Transaction Hash (Txhash) Details | Etherscan
Ethereum (ETH) detailed transaction info for txhash 0x722e4d3c1784f7d101159b4c092a9008afae77fb130a750229d2be83fb9e38df. The transaction status, block confirmation, gas fee, Ether (ETH), and token transfer are shown.

**Comment by tomasmik** [comment]
@chompomonim Can you do anything about this?

**Comment by chompomonim** [comment]
There is technical possibility to withdraw such funds, however we're expecting user to cover needed tx fees and headache of engineers who would take time to do withdrawal. I thought we already communicated that such recovery operation should cost $500 (can be paid in MYST, I mean we would take some of MYST tokens locked in our smart contract). I believe that back in January such operation was not worth it, however now, with MYST token price growth, we could withdraw user's tokens if he agrees to pay $500 in MYST fee. Withdrawn funds would send back into address from with transaction was originally sent.

**Comment by sulfursoul** [comment]
> There is technical possibility to withdraw such funds, however we're expecting user to cover needed tx fees and headache of engineers who would take time to do withdrawal. I thought we already communicated that such recovery operation should cost $500 (can be paid in MYST, I mean we would take some of MYST tokens locked in our smart contract). I believe that back in January such operation was not worth it, however now, with MYST token price growth, we could withdraw user's tokens if he agrees to pay $500 in MYST fee. Withdrawn funds would send back into address from with transaction was originally sent.

Hi, chompomonim! TG @iamjas here. I'm aware and agree that engineers can charge 500$ for this withdrawal. How long should I expect this TX to be done? Thanks.

**Comment by chompomonim** [comment]
It is quite busy week for us, but I hope we'll manage to do something till end of week.

**Comment by sulfursoul** [comment]
> It is quite busy week for us, but I hope we'll manage to do something till end of week.

Thanks a lot, looking forward to hear from you. Have a good one!

**Comment by sulfursoul** [comment]
Hi guys. Any updates?

**Comment by Orintaj** [comment]
Tokens are recovered after the fee @sulfursoul

**Comment by sulfursoul** [comment]
Thanks. The fee is disgusting tho.
