### ISSUE TITLE
NodeUI - Improvements

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4290]
- [x] Implement last transaction hash on withdrawal card.

Link should be formed like this: `https://polygonscan.com/tx/[hash]`
Example: https://polygonscan.com/tx/0xe00dfc7d611b945fb5c6ab58491adcfb949e89494bc04dbfb3c1deff0ac28be1

OR

`https://etherscan.io/tx/[hash]`
Example: https://etherscan.io/tx/0xe00dfc7d611b945fb5c6ab58491adcfb949e89494bc04dbfb3c1deff0ac28be1

Requires and is blocked by: https://github.com/mysteriumnetwork/node/pull/4289

- [x] Make Y axis dynamic in increments of 2.
![image](https://user-images.githubusercontent.com/91055712/140512283-eb9a8301-1b97-4f59-b3f6-6d0a05dfe08b.png)

- [x] Add "Channel" below Identity:
![Pasted_Image_2021-11-18_12_06](https://user-images.githubusercontent.com/91055712/142394722-bd158bda-30ba-4ac0-8d99-48e656f3bd6c.jpg)
Also add following explanation below:

```Channel address is an internal wallet of your node. This address can be used to top up MYST.```

- [x] Lower the lowest value of Bandwidth limit to 15Mbps.

- [x] Add Start time in latest sessions list on homepage:
![Pasted_Image_2021-11-29_17_43](https://user-images.githubusercontent.com/91055712/143898425-d162d6a8-dc0f-4d09-adc3-73ee738c47ec.jpg)

- [x] Add ? symbol to Unsettled card in NodeUI and following text on mouse over.

```These are confirmed earnings which are not settled to your Balance yet. Settlement to Balance is done automatically when 0.3 MYST is reached. Please note that settlement fee is 20% plus blockchain fees, so Balance will be lower than Total earnings.```

Visual like here:
![image](https://user-images.githubusercontent.com/91055712/143892283-e2e0b8ab-39a5-4920-bfc7-ade3606b345a.png)

- [x] Remove word Matic from this description, so users are not confused to send MATIC. Only Polygon should be mentioned.
![Pasted_Image_2021-12-03_09_43](https://user-images.githubusercontent.com/91055712/144564453-bcb55aaa-35b1-4440-b979-2938731e34a9.jpg)

**Comment by lusine-h** [comment]
Make Y axis dynamic in increments of 2
![image](https://user-images.githubusercontent.com/60058956/145195415-be16e989-9223-4546-a16d-3e491bfe25ce.png)

**Comment by Donatas-MN** [comment]
Hmm looks good to me:
![image](https://user-images.githubusercontent.com/91055712/145599594-95c68c70-0ba9-46a1-a57a-13ff83ffa679.png)

@lusine-h do you still see it?

**Comment by lusine-h** [comment]
@Donatas-MN  yes, I still see this issue

**Comment by Donatas-MN** [comment]
Strange.. Does it reproduce on multiple nodes? On which Node version you tried?

**Comment by lusine-h** [comment]
it is the 1.0.13 version, I will check on other nodes and will let you know

**Comment by lusine-h** [comment]
for the Node that was installed on Linux it looks as expected, the issue appears only on Windows

**Comment by Donatas-MN** [comment]
Can you try to run another node from scratch?

**Comment by lusine-h** [comment]
I checked on another device and it looks as expected.

**Comment by lusine-h** [comment]
the issue is solved on version 1.1.15
