### ISSUE TITLE
openvpn error when starting services

### ISSUE THREAD

**Issue by emuhack** [mysteriumnetwork/node#4297]
Try to enable openvpn on server and threw the following error, I have restarted the service and still same.

```
» service start 0xMAGICNUMBER openvpn
[ERROR] Failed to start service: server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/services). Possible error: unexpected openvpn exit code: 0
```

**Environment (please complete the following information):**
 - Node version: 0.68.3 
 - OS: ubuntu

**Comment by etherunit** [comment]
@emuhack Please note that OpenVPN is not used anymore. Please disable it and keep using WireGuard service only.

**Comment by emuhack** [comment]
Thanks!
