### ISSUE TITLE
[android] sendto: operation not permitted, could not fetch fees

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4305]
**Describe the bug**
Can't get node running properly on Android.
I can see multiple errors. Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7574507/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.68.1
 - OS: Android

**Comment by tomasmik** [comment]
Duplicate of https://github.com/mysteriumnetwork/node/issues/4257
