### ISSUE TITLE
Sessions dropping every 10 min, payments not processed

### ISSUE THREAD

**Issue by lvlegab1te** [mysteriumnetwork/node#4307]
**Describe the bug**
No payments are being made and sessions are dropping after 10 mins

**To Reproduce**
run node as normal

**Expected behavior**
sessions to not drop after 10 mins and payments to be processed

**Screenshots**
![image](https://user-images.githubusercontent.com/15414696/142742528-9b88032d-dd00-4b1d-a4be-1594daf7f596.png)

**Environment (please complete the following information):**
 - Node version: 0.68.3
 - Node ID 0xf6539ec593d111e62f2876cefc96e05f13f287c4
 - OS: Ubuntu 20.04.3

**Additional context**
not sure if this is related but i can see the following in journalctl 
2021-11-21T09:18:49.153 WRN session/pingpong/invoice_tracker.go:534  > hermes error, will retry error="hermes request promise error: could not reveal R: could not reveal R for hermes: internal error"

**Comment by tomasmik** [comment]
This is probably due to the connection issues we've been having with the blockchain RPCs we use. We're working on it.

**Comment by adinetech** [comment]
hmm
