### ISSUE TITLE
[android] 1.0.0-rc1 could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4309]
**Describe the bug**
Trying to connect getting multiple errors including "could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built"

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7576291/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.0.0-rc1
 - OS: Android

**Comment by tomasmik** [comment]
This again has an error related to this issue: https://github.com/mysteriumnetwork/node/issues/4257
I can't seem to find a way to replicate it. Are you sure you didn't edit out thats needed in the app for your own version?

**Comment by cvl** [comment]
Hmm, nothing's changed for years in the app.

It works fine for most providers though.

**Comment by cvl** [comment]
Still recurring with other users.
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7609368/mysterium-node.log)

**Comment by cvl** [comment]
x
