### ISSUE TITLE
Get account back

### ISSUE THREAD

**Issue by dmys** [mysteriumnetwork/node#4311]
Hi guys,

Hope you're doing great. Its not a bug issue but Isaac sent me here after email conversation. I had an account, i paid for 20 myst, and i lost my backup key because i downgraded to macos big sur. I dont have anything to get my account back with my 20 myst now. I can provide all the proof of payment.

Thx

**Comment by isaackielma** [comment]
Transaction details:

https://etherscan.io/tx/0xa3f42db37b621fc1d6d443573c2f3357ee7242df9c713996222d5c7d90c51f2d

**Comment by tomasmik** [comment]
How does the transaction prove that it was this person for sure who did this. @chompomonim Whats your take on this?

**Comment by dmys** [comment]
My point is very clear : i am the one who made the transaction and there for i can provide anything you ask. I am new to all this bitcoins blockchain stuff. Thats why im telling you to ask for anything you need to prove its me.

**Comment by chompomonim** [comment]
This sounds like proper CoinGate transaction. Lets do this way. You'll give us here your new app identity (also don't forget to backup private keys in secure place) and we'll send you 20 MYST. However this will be done only once, so please don't loose your keys anymore.

**Comment by dmys** [comment]
Thank you for your help guys ! Sure im gonna back it up right away in my external hard drive. Here's my new id : 0x22062fbb0102bbf9189742c2836cd3d2e8caffdf

**Comment by chompomonim** [comment]
Sorry for delay. Should be done tomorrow.

**Comment by dmys** [comment]
done ! thank you guys
