### ISSUE TITLE
Identity update in Node UI

### ISSUE THREAD

**Issue by arjunkool** [mysteriumnetwork/node#4314]
**Is your feature request related to a problem? Yes**
If there has been a system crash or when the node runners are updating there system. If backup is not already taken the Node UI generates a new Identity which we are not able to change. Also, some times the restore option also doesn't work either.

**Describe the solution you'd like**
As user are linking there identities to MMN (API key) after registering through the https://mystnodes.com/. User are able to keep there specific Identity# intact. Instead of Node UI generating a new identity if there is no system files or back up found. Instead of restore which failed often for me.

A prompt to enter identity or request for one. If a identity information is entered it can send a security code to the linked API in the my nodes tab (https://mystnodes.com/nodes). If security code is validated the identity can be retrieved. In order to prevent multiple system using same identity we can set the usage of identity limit to 1. It can only used in one system if the other system is online it cannot be updated but if the system is offline it can be retrieved. If someone tried logging more than 1 system using same identity it can show a error warning and cut traffic for both systems preventing node runners from using same identity on multiple system.

**Describe alternatives you've considered**
No.

**Additional context**
Node runners by losing the identity they wont be able to retrieve the money they have earned. But by integrating a option in node UI to enter identity and verifying using the special code shown in https://mystnodes.com/nodes. Thereby node runners can be sure that even if the device gets corrupted an no back up is present it would be easier to retrieve the money they have earned by setting up a new device with same identity.

**Comment by tomasmik** [comment]
You can update the identity node uses by default using a myst command: `myst account set-identity [IdentityAddress]` and restarting your node afterwards.
That should help with the issue for now, while we're looking in to it.

**Comment by arjunkool** [comment]
Tried the same but got error message as Failed to set identity as default. Stopped the container and node and tried changing the identity but got the error and tried restarting as well. The issue is not resolved.
