### ISSUE TITLE
[critical] testnet3 not working anymore

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4323]
**Describe the bug**
Can't connect to any provider both on Android and Mac.
Can't register on Mac

Logs:
[mysterium-node-2.log](https://github.com/mysteriumnetwork/node/files/7582811/mysterium-node-2.log)
[mysterium-node-3.log](https://github.com/mysteriumnetwork/node/files/7582812/mysterium-node-3.log)
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7582813/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: Various
 - OS: Mac, Android, WindowS

**Comment by tomasmik** [comment]
resolved.
