### ISSUE TITLE
NodeUI unsettled earnings+balance < total earnings.

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4325]
**Describe the bug**
total earnings should be equal to unsettled earnings + balance for nodes that have not withdrawn balance since being added to the network(aka new identity). There should be a withdrawal history that is more than "last withdrawal tx link" on the withdraw page. There maybe should be a "earnings report" page or something in nodeui showing either a transaction list or transaction breakdown to keep track of earnings

**To Reproduce**
1. create new node identity (systemctl stop mysterium-node && rm /var/lib/mysterium-node/keystore/UTC* && systemctl start mysterium-node)
2. let node run for a couple days after completing onboarding process
3. open nodeui - total earnings != unsettled earnings+balance

**Comment by Donatas-MN** [comment]
That's because some of your earnings go for settlement to balance. It looks like default settlement threshold (0.3 MYST) is not suitable (too frequent) for all users, so we allow to customize this in NodeUI. Update should come in the coming weeks.
