### ISSUE TITLE
[android] can't connect to any node on mainnet (weird errors)

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4326]
**Describe the bug**
Lots of errors with weird characters. App reinstalls don't help.

Logs
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7584080/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.0.0
 - OS: Android

**Comment by tomasmik** [comment]
Seems to again have errors related to this: https://github.com/mysteriumnetwork/node/issues/4257

**Comment by cvl** [comment]
Still getting reports with the weird errors like Unexpected message: !�B��|���k����& t����> - attempting to continue
or
Remote peer data received: !�Bf�����yv��A r����>, len: 32, from: 172.253.121.127:19302

**Comment by cvl** [comment]
x
