### ISSUE TITLE
Node country should be changing in discovery when node is moving/jumping between location (e.g. person is travelling)

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4332]
**Describe the bug**
When Node country is changed by connecting to internet in different country then country will change in Discovery and then in MystNodes.com also. But when country is back to original one, country stays the same in Discovery (does not change back).

Reproduced by using VPN to change country.

**To Reproduce**
1. Run a node on localhost (e.g. on docker)
2. Check country in Discovery (e.g. it will be Lithuania)
3. Connect to VPN to e.g. USA, country will change to USA in discovery too.
4. Disconnect from VPN.
5. Country will stay USA in Discovery.

**Environment (please complete the following information):**
 - Node version: 1.0.3
 - OS: macOS
 - Docker

**Comment by chompomonim** [comment]
Related to #1802
