### ISSUE TITLE
Not seeing node in Mainnet

### ISSUE THREAD

**Issue by asuib515** [mysteriumnetwork/node#4335]
Hi went through a the steps of moving to the mainnet. When I went to the node UI my API was already there. I deleted it and repasted it. My node is still not showing up on the mainnet

**Comment by etherunit** [comment]
Do you mean Mainnet dVPN?

**Comment by asuib515** [comment]
I believe so. I'm running the node through a vps @etherunit. I am the one
who messaged you on discord. Adine told me to.

**Comment by asuib515** [comment]
I followed these instructions. Please see attachment. Then I was told node
not found. Thin I tried to get into the UI and I not longer can. It just
keeps loading. Please see attachment

I am using a data center. Ubuntu 18.04 with Docker pre-installed. I asked
if this was Linux and they said yes.

My test net node says active. But when I trigger connection it's as if
nothing is there

I Ran the status command and I will also attach that here

Idk what else to do. I've been at it since yesterday. I tried to run all
the commands for test net to start over and that doesn't work withet
Show quoted text

**Comment by asuib515** [comment]
What????  Nobody responded back to me....
