### ISSUE TITLE
Payment not implemented since Oct

### ISSUE THREAD

**Issue by thanhtantran** [mysteriumnetwork/node#4336]
**Describe the bug**
I have a node which eligble to reward in Sep. 
Bounty payout stated that paymetn in progress and it should reach before 2021-10-07 but i see nothing
Already put my ETH address 0xF8cb057582F3b13444C69CC45edA0C9e102A4688 in the node and account.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5319910/143174321-ac4fe4c6-7b61-46a6-b33e-318530eda613.png)

**Environment (please complete the following information):**
Node in hosting server. Already stopped it

**Additional context**

**Comment by tomasmik** [comment]
Without your identity, we can't find you. Provide that please.

**Comment by thanhtantran** [comment]
sorry my node id is 0x27a740a21b8db6519f3bc974e9643140196aeeb1

**Comment by Donatas-MN** [comment]
@thanhtantran Do you have wallet setup on your node? Looks like there is none added.

**Comment by thanhtantran** [comment]
> @thanhtantran Do you have wallet setup on your node? Looks like there is none added.

i have put my wallet while setup, no idea why it has been gone :(

My ERC20 wallet 0xF8cb057582F3b13444C69CC45edA0C9e102A4688
