### ISSUE TITLE
sessions amount is decreased massively

### ISSUE THREAD

**Issue by AdnanSayyed** [mysteriumnetwork/node#4337]
**Describe the bug**
After upgrading to mainnet it is observed that hardly one or two sessions is happening the whole day which is the waste of our resources if sessions are not ongoing in significant amount
Also, the price per GB is decreased and reached 0.03 per GB which is very low

**Expected behavior**
sessions should happen so that resources consumption is okay
Price per GB should be okay

**Environment (please complete the following information):**
 - Node version: mainnet (1.0.4-293fe8b3)
 - OS: Windows 10

**Comment by tomasmik** [comment]
> After upgrading to mainnet it is observed that hardly one or two sessions is happening the whole day which is the waste of our resources if sessions are not ongoing in significant amount

This is expected for the first few days or a week in mainnet. Consumers have to update their apps etc.

> Also, the price per GB is decreased and reached 0.03 per GB which is very low

MYST price increases, MYST/GB decreases. So the price hasn't changed, you just get less currency, which is worth the same amount as before.

**Comment by AdnanSayyed** [comment]
sessions frequency is still very low after a week
