### ISSUE TITLE
Semantic version for dev releases

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#434]
- NPM packages cant have our `latest` release because they are compatible with https://docs.npmjs.com/getting-started/semantic-versioning
- Start latest release `0.4-dev` or `0.4-rc` as per proposal 
 here https://github.com/mysteriumnetwork/node/pull/430#discussion_r223591034

**Comment by Waldz** [comment]
In another projects I've seen unofficial **semantic version** like this:
```
const Version = "0.0.20181001-dirty"
```

**Comment by soffokl** [comment]
We can get a version of the latest dev release from pre-releases:
