### ISSUE TITLE
 personal account

### ISSUE THREAD

**Issue by StiLgaR23** [mysteriumnetwork/node#4340]
**Describe the bug**
I can't enter my personal account mystnodes.com  On https://mystnodes.com/ the account is working fine.

 - Node version: [e.g. 0.1.3]
 - OS: [windows 10]
 - Docker Desktop 4.2.0 (70708)

**Comment by etherunit** [comment]
Can you please specify your question? You are unable to enter my.mysterium.network but mystnodes.com is working fine?

**Comment by StiLgaR23** [comment]
Good afternoon . I cannot log in to the site https://mystnodes.com/login. On the site https://my.mysterium.network/dashboard I can log in

**Comment by etherunit** [comment]
can you please try to reset your password on mystnodes.com?

**Comment by StiLgaR23** [comment]
When I enter mail and confirm. Request failed with status code 400

**Comment by Donatas-MN** [comment]
@StiLgaR23 could you send a screenshot?

**Comment by StiLgaR23** [comment]
![1](https://user-images.githubusercontent.com/94962066/144810357-349f3250-5634-40c7-9bdc-05c1ef6db257.jpg)
![2](https://user-images.githubusercontent.com/94962066/144810380-6675b0e7-7734-470d-95fb-ed8ddcd50fee.jpg)

**Comment by Donatas-MN** [comment]
Try entering your email as STILGAR.UA@gmail.com to password reset field. Form is case sensitive, but we will fix it shortly.
