### ISSUE TITLE
Node isn't registering w new mainnet. Have been looking for help

### ISSUE THREAD

**Issue by asuib515** [mysteriumnetwork/node#4342]
Hey thanks for responding. I'll try and lay this out as best as I can. I set up the test net node with a vps. With docker pre installed. So I saw that we need to move to mainnet. I went through all the steps. I had trouble getting into the node UI because I had never come to a step in the process to make a password. I found the PW reset script. Ran it in putty so I was finally able to get into UI. So I needed to paste my API in there to claim my note on the mainnet. My API was already there. So I deleted it and repasted it there just in case. I saved. Went to claim my node and it wasn't found. I did that about 20 times. Adine tried to help me a lot but we couldn't figure it out. Honestly a lot of it was confusing to me. She had a way better grasp on it all than me. It looks like there were no "packages or "image". That's when she told me to message you. So than I did this. (in the screenshot). Went through those steps with the command. Now every time I try to paste the API for mainnet I get "validation" error. It won't let me save API now. When I go to test net and try and trigger connection it says "no active services found"

I set up the test net node two weeks ago and also realized today I wasn't earning anything. For what it's worth.

Can someone please help me

**Comment by veldspar** [comment]
you did enter the mainnet api token? Tokens for my.mysterium.network and mystnodes.com are different(Sounds like you did use the old API token:

`My API was already there. So I deleted it and repasted it there just in case.`

log on to mystnodes.com and go to claim node, when it wont find the node(which it wont) click claim manually and then copy the api token from that page. if that doesnt work, do the following: stop your mysterium node. Backup the /var/lib/mysterium-node/keystore/UTC* file(it will start with UTC- and have a series of numbers and characters in the name after). THIS IS YOUR IDENTITY FILE AND IT IS NEEDED TO GET ANY BALANCES YOU HAD ON TESTNET/MAINNET, SO BACK IT UP!!!
Once it is backed up, delete the entire contents of the directory /var/lib/mysterium-node/
then start your mysterium-node again. it should now be reset to factory defaults. Go through the boarding process again. it should now show up in mystnodes.com.

**Comment by asuib515** [comment]
Ok I will get back to you and let you know how this works

**Comment by asuib515** [comment]
Also when I logged into mainnet I believe it gave me an API to use but it
was the same as the old. Any idea why I know longer have access to ui?

**Comment by asuib515** [comment]
It's telling me to enter this API.  Please see attachment. This is from
mystnodes.com And it happens to be the same as the old API as the old I
believe.

Now I can't access UI. Haven't been able to get in all day. It just keeps
loading. I don't even arrive at the landing page. Just a white loading
screen.

**Comment by etherunit** [comment]
Please note that API keys were migrated to the new platform so it's normal to see the same value. Could you please share the output of the dev console at the time this happening?

**Comment by asuib515** [comment]
Hi. I ended up getting it all figured out. I how to run some particular
commands to fix the API problem. Someone suggested I do it in the discord
