### ISSUE TITLE
[windows] can't connect to provider: NATS: disconnected error="nats: stale connection"

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4343]
**Describe the bug**
Can't connect to provider.

Looks like the only error:
NATS: disconnected error="nats: stale connection"

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7596776/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.0.4
 - OS: Windows

**Comment by wallyqs** [comment]
Hi NATS maintainer here 👋 This is a Go client right? This would only occur after the client missing 3 PINGs from the servers within a span of 6 minutes (those are the defaults) so it should be quite rare to get these errors but it could happen when there is a network partition or in connections with very high latency.
