### ISSUE TITLE
New node only receiving sessions with 0 duration and data

### ISSUE THREAD

**Issue by erler493** [mysteriumnetwork/node#4347]
**Describe the bug**
I'm trying to setup a new node, but do not seem to get any valid sessions as all sessions are of 0 seconds duration with 0 bytes of data transferred. I've tried setting up port forwarding using your documentation, but when checking the ports from outside they are not reachable. The issue with the ports seems they are only binding to tcp ip6 and not udp ip6 or ip4. If I cannot reach the ports internally, I will for sure not be able to reach them externally. This is the result from nmap:

nmap -p 60000 192.168.1.5
PORT      STATE  SERVICE
60000/tcp closed unknown

nmap -sU -p 60000 192.168.1.5
PORT      STATE  SERVICE
60000/udp closed unknown

nmap -6 -p 60000 fe80::ff7d:cf5c:f788:a0d7%13
PORT      STATE SERVICE
60000/tcp open  unknown

nmap -sU -6 -p 60000 fe80::ff7d:cf5c:f788:a0d7%13
PORT      STATE  SERVICE
60000/udp closed unknown

**Environment (please complete the following information):**
 - Node version: 1.0.4
 - OS: ubuntu 18.04.2
 - Docker 19.03.2 mysteriumnetwork/myst:latest

**Expected behavior**
Although manual port configuration doesn't work, I still expect hole punching to work and to receive valid sessions.

**Additional context**
Find the log in the attachments, containing some errors and warnings
[node.log](https://github.com/mysteriumnetwork/node/files/7610711/node.log)

**Comment by lokidaibel** [comment]
Push ! See the same on my node installed on 29.11.2021.

**Comment by erler493** [comment]
@lokidaibel I managed to get my node running in docker without port forwarding (but using hole punching) by adding the following to my dokcer run command: --device=/dev/net/tun
This resolved the error 'Failed to create TUN device: open /dev/tun: no such file or directory' which I was seeing in my logs. I'm not sure why I have this issue or if this is the proper fix. But for me at least it got my node running.
I still don't know why port forwarding is not working and I like to see that sorted out.

**Comment by lokidaibel** [comment]
My problem isn`t that i can bring the node online. My problem is that i only get 0 bytes / 0 sec Sessions on that node.
This seams to be a issue because this special hoster is using openvz as virtualiziation which dont allow me to use wireguard with kernel modules. I need to use wireguard-go instead. But i dont know how to configure myst to use this.

**Comment by ufukcaneski** [comment]
> @lokidaibel I managed to get my node running in docker without port forwarding (but using hole punching) by adding the following to my dokcer run command: --device=/dev/net/tun This resolved the error 'Failed to create TUN device: open /dev/tun: no such file or directory' which I was seeing in my logs. I'm not sure why I have this issue or if this is the proper fix. But for me at least it got my node running. I still don't know why port forwarding is not working and I like to see that sorted out.

`ERR cmd/mysterium_node/mysterium_node.go:68  > Failed to execute command:  error="flag provided but not defined: -device"`
I am getting an error like this.
