### ISSUE TITLE
Cannot login on Mystnode

### ISSUE THREAD

**Issue by thingsmart** [mysteriumnetwork/node#4350]
I'm registered on the platform my.mysterium.network but it's not possible for me to login on mystnode.com.
With the same credential (email and password, copied & pasted) I had "Invalid Login".

**Comment by veldspar** [comment]
you need to reregister on mystnodes.com

**Comment by thingsmart** [comment]
I already tried but I got the error: "Already registered"

Il 25/11/2021 15:53, veldspar ha scritto:

**Comment by veldspar** [comment]
try resetting the password?

**Comment by etherunit** [comment]
Yep, please try to reset password.
