### ISSUE TITLE
MYST on windows app not visible

### ISSUE THREAD

**Issue by mullafabz** [mysteriumnetwork/node#4352]
MYST that i bought via BTC are all gone after the latest windows v10 update.
One my android phone, the MYST are still there but not on windows.
![image](https://user-images.githubusercontent.com/26839042/143542999-7aee0ef5-7ff4-4ff2-b104-4f6987e3bff2.png)

**Comment by tomasmik** [comment]
Are you sure that you're using the same identity on both devices? If so can you provide it for me to check

**Comment by mullafabz** [comment]
Yes i am using the identity.
Here is my identity:
0x051bb53a6fb198a40890ca509b0e17b4e93c4f07

**Comment by mullafabz** [comment]
Any updates on my issue?

**Comment by mullafabz** [comment]
Any updates on my issue?

**Comment by tomasmik** [comment]
That identity has 20+ MYST app was just not updating the balance as it should.

Check your balance here yourself: https://hermes.mysterium.network/api/v1/data/consumer/0x051bb53a6fb198a40890ca509b0e17b4e93c4f07

**Comment by mullafabz** [comment]
On the testnet i have 30 MYST+ and i was expecting them to be added to the balance i have on the mainnet. I just checked on my android app(still using the old version that was on testnet) and the 30+MYST i had have disappeared. Where are they?
