### ISSUE TITLE
[android] connection goes to OnHold after few minutes, then app crashes

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4354]
**Describe the bug**
Connection goes to OnHold after few minutes, then app crashes.
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7607391/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.0.0
 - OS: Android

**Comment by soffokl** [comment]
We did a fix for android onhold in 1.0.1 version. Try to use the latest version.

**Comment by cvl** [comment]
Thanks!
