### ISSUE TITLE
Node 0x30d71268b5732c099978304a8a8a9f2125e1cfee doesn't come online in the MainNet

### ISSUE THREAD

**Issue by Edy2009** [mysteriumnetwork/node#4361]
**Describe the bug**
Node 0x30d71268b5732c099978304a8a8a9f2125e1cfee doesn't come online in the MainNet

**To Reproduce**
Node was live on TestNet. I made the update to cross it in the MainNet, but is offline from that day

**Expected behavior**
Should appear online

**Screenshots**
![image](https://user-images.githubusercontent.com/95053625/143612727-597c7cfa-7778-4e2d-b0cd-58907d2cd2b9.png)

**Environment (please complete the following information):**
- raspberry pi
- version 	1.0.3

**Additional context**
Isaac asked me to upload a bug report

**Comment by Edy2009** [comment]
API key vlU0DEYjDGw9q724geePtdxzcn7mpA4Y7QMS4N91

**Comment by etherunit** [comment]
Please do not expose your API keys publicly. I suggest to delete it.
I can see that your node is not visible on our discovery list: https://discovery.mysterium.network/api/v3/proposals
Could you open Mysterium CLI locally and run `identities get 0x30d71268b5732c099978304a8a8a9f2125e1cfee`?

**Comment by Edy2009** [comment]
hi

i tried to run identities get 0x30d71268b5732c099978304a8a8a9f2125e1cfee, but it says 

_-bash: identities: command not found_

**Comment by Edy2009** [comment]
Done,
i checked service list and i see 2 running id, but is still offline in my mystnodes

**Comment by etherunit** [comment]
Still, could you copy > paste the output of `identities get 0x30d71268b5732c099978304a8a8a9f2125e1cfee`?
It could help to understand the current state of your identity registration.

**Comment by Edy2009** [comment]
here  it is
» identities get 0x30d71268b5732c099978304a8a8a9f2125e1cfee[INFO] Registration Status: Unregistered[INFO] Channel address: 0x77EE411938F7DD0D650F6e65b8b2F5c4e31874Ab[INFO] Balance: 0.000000[INFO] Earnings: 0.000000[INFO] Earnings total: 0.000000
is this info okay?
    On Tuesday, November 30, 2021, 11:40:48 AM GMT+2, etherunit ***@***.***> wrote:  
 
 


Still, could you copy > paste the output of identities get 0x30d71268b5732c099978304a8a8a9f2125e1cfee?
It could help to understand the current state of your identity registration.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Edy2009** [comment]
» identities register 0x30d71268b5732c099978304a8a8a9f2125e1c[ERROR] Could not register identity: server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x30d71268b5732c099978304a8a8a9f2125e1c/register). Possible error: failed identity registration request: failed to fill in identity request: failed to calculate channel address: given identity, registry and channelImplementation params have to be hex addresses


    On Tuesday, November 30, 2021, 11:40:48 AM GMT+2, etherunit ***@***.***> wrote:  
 
 


Still, could you copy > paste the output of identities get 0x30d71268b5732c099978304a8a8a9f2125e1cfee?
It could help to understand the current state of your identity registration.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Edy2009** [comment]
any news here?

**Comment by etherunit** [comment]
We had some component related issues that have been successfully fixed. Please try to re-register your identity again.

**Comment by Edy2009** [comment]
mnope, again the same error from 1 month ago


really?!?


    On Tuesday, December 28, 2021, 10:06:02 AM GMT+2, etherunit ***@***.***> wrote:  
 
 


We had some component related issues that have been successfully fixed. Please try to re-register your identity again.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
