### ISSUE TITLE
Tried to move node from TestNet to MainNet but asks for MYST

### ISSUE THREAD

**Issue by Edy2009** [mysteriumnetwork/node#4362]
**Describe the bug**
Tried to move node 0xcccd938a4d39b58cab0b009419b06a5d105e424e from TestNet to MainNet but asks for MYST

**To Reproduce**
I made node 0xcccd938a4d39b58cab0b009419b06a5d105e424e in TestNet at the begining of the week
I tried to move it to MainNet and asked me for myst
I asked Isaac and he said that being a node from TestNet shouldn't ask for MYST

**Expected behavior**
to be moved to MainNet

**Screenshots**
![image](https://user-images.githubusercontent.com/95053625/143613242-6b0b34c0-325e-4a75-94a9-22cf5542fa68.png)

**Environment (please complete the following information):**
- raspberry pi
- version 0.68.3
- 

**Additional context**
API key vlU0DEYjDGw9q724geePtdxzcn7mpA4Y7QMS4N91

**Comment by tomasmik** [comment]
You are not registered on testnet. You can only migrate to for free mainnet if you are registered on testnet.

Testnet free registrations have been disabled and are no longer available. You will have to pay or try to register for free as we allow a small amount of new providers to register for free.

**Comment by Edy2009** [comment]
hi,

it appears in my testnet

![image](https://user-images.githubusercontent.com/95053625/143849427-344fc95a-314d-4861-b2e4-6ab4228e1721.png)

**Comment by tomasmik** [comment]
You never registered in testnet, this is just MMN.

https://testnet3-hermes.mysterium.network/api/v1/data/consumer/0xcccd938a4d39b58cab0b009419b06a5d105e424e
