### ISSUE TITLE
Raspberry Pi install script need to include the ECCB6A56B22C536D key

### ISSUE THREAD

**Issue by lunarnautics** [mysteriumnetwork/node#4368]
**Describe the bug**
I could not install myst with the script because "GPG error: http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ECCB6A56B22C536D"

I was able to add the key using sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ECCB6A56B22C536D and it installed correctly

**Comment by etherunit** [comment]
Thanks for sharing your insight. Team will take this into account.
