### ISSUE TITLE
1.0.7-alpine container not working properly on Windows 10

### ISSUE THREAD

**Issue by chriolant** [mysteriumnetwork/node#4370]
**Describe the bug**
The Mysterium Node Launcher automatically updated node container versions a few hours ago to 1.0.7-alpine, however, it fails some kind of pre-check and does not finish loading, causing the Mysterium Node Launcher to kill the instance and start a new instance. If I terminate the Mysterium Node Launcher, the container starts properly, but the UI says "Node status: Test Failed".

**To Reproduce**
1. Start the Mysterium Node Launcher.
2. Mysterium Node Launcher goes into a loop where it does not complete updating Mysterium to the latest version.

**Comment by Zensey** [comment]
The same bug: https://github.com/mysteriumnetwork/node/issues/4375

This version should fix the problem
https://github.com/mysteriumnetwork/myst-launcher/releases/tag/1.0.23-rc1
