### ISSUE TITLE
Node launcher in docker container restarting every 5 sec

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4375]
**Describe the bug**
container in docker installed but it is restarting every 5 sec. not running correctly.

**Expected behavior**
should install container and stay online

**Screenshots**
<img width="473" alt="Screenshot 2021-11-28 at 23 14 35" src="https://user-images.githubusercontent.com/84313603/143790325-eb4825b2-fd91-4390-b8a1-e6f8b8ec719d.png">

**Comment by Zensey** [comment]
The version  v1.0.22 fixes major part of a problem (including periodic node restart), but still don't turn on 'Upgrade automatically'

https://github.com/mysteriumnetwork/myst-launcher/releases/download/1.0.22/myst-launcher-amd64.exe

**Comment by isaackielma** [comment]
Noted! Thanks for quick response

**Comment by Zensey** [comment]
This version should finally fix 'auto-upgrade' issue
https://github.com/mysteriumnetwork/myst-launcher/releases/tag/1.0.23-rc1
