### ISSUE TITLE
Toping up

### ISSUE THREAD

**Issue by mehradj1** [mysteriumnetwork/node#4377]
Hi 
I toped up my acc through coingate but my balance is still 0 
What should i do?
[be0bc538-ba43-4448-a7cb-18fee208b8ad.pdf](https://github.com/mysteriumnetwork/node/files/7615769/be0bc538-ba43-4448-a7cb-18fee208b8ad.pdf)
I attached my receipt

**Comment by tomasmik** [comment]
Money has been transferred and should appear in app. Note though that it can take some time for it to show up in the UI as it only updates every minute or two and it takes time for our services to transfer you the funds after a topup.

**Comment by tomasmik** [comment]
Here is the transfer we've made to your account
https://polygonscan.com/tx/0x0839d61104dc22e068a3c90a417300440f67d0a765b9535cb4a18c65603fa720

**Comment by mehradj1** [comment]
Why when i open my app my balance is still 0 and i cant use it?
I attached my balance and app
![Uploading Screenshot_20211129-125352_MysteriumVPN.jpg…]()

**Comment by mehradj1** [comment]
![Uploading Screenshot_20211129-125352_MysteriumVPN.jpg…]()

**Comment by mehradj1** [comment]
When open the i see my balance is 0I attached my balanceCould you tell me what should i do?
-------- Original message --------From: Tomas ***@***.***> Date: 29/11/2021  12:40  (GMT+03:30) To: mysteriumnetwork/node ***@***.***> Cc: mehradj1 ***@***.***>, Author ***@***.***> Subject: Re: [mysteriumnetwork/node] Toping up (Issue #4377) 
Here is the transfer we've made to your account
https://polygonscan.com/tx/0x0839d61104dc22e068a3c90a417300440f67d0a765b9535cb4a18c65603fa720

**Comment by mehradj1** [comment]
![Uploading IMG_20211129_132107_591.jpg…]()

**Comment by mehradj1** [comment]
![Uploading IMG_20211129_132107_591.jpg…]()
