### ISSUE TITLE
Payment Problem

### ISSUE THREAD

**Issue by patrizok** [mysteriumnetwork/node#4378]
I paid for vpn,

This is my transacition id : https://polygonscan.com/token/0x1379e8886a944d2d9d440b3d88df536aea08d9f3?a=0x1f660870fda873f51064561d88c42b2e0832b48f

But vpn don't see payment. And when I reinstall import not work, is show "Ppossible Error Failed to import identity ,account already exists". 
I know it exists, I already want to import existing one :(

What can I do?

**Comment by tomasmik** [comment]
Is this dekstop app or android? What is the app version?

If account already exists, then you dont need to import it. It's already there.
How did you transfer these funds? Did you sent them to your payment channel?

**Comment by patrizok** [comment]
It is Windows desktop app. (I am VPN user now, not node owner email support redirect me this repo)
If account already exists why do I see "Create Account"  and "Import Existing" buttons, I except to see my account information?

I sent 12 MYST to wallet shown in windows app, you use coingate as payment partner, you can check transaction that I write before.

**Comment by patrizok** [comment]
Any news?
Can you please enable service or refund it ?

**Comment by tomasmik** [comment]
After various fixing to the apps and the services. if a payment as made your app should be working.
