### ISSUE TITLE
Improve UI handle for failed registrations

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4379]
When registration to the networks fails, NodeUI window hangs on "Your identity is being registered, please be patient..." and log output completes at `2021-11-29T10:29:00.760 ERR identity/registry/registry_contract.go:261 > registration reported as failed by transactor` & `29T10:29:00.764 DBG session/pingpong/hermes_promise_settler.go:263 > Ignoring event RegistrationError for provider {"0xe0b4ccacfd0ebd988a5f624adb55f2df99d19848"}` . Node service restart doesn't help.
I think UI need to handle it better by displaying a pop-up window with something like "Registration has failed, please try again" and redirect to the initial on-boarding step.

**Comment by Donatas-MN** [comment]
@mdomasevicius will check what could be possible (e.g. add error message and possibility to retry registration).

**Comment by Donatas-MN** [comment]
Fixed with https://github.com/mysteriumnetwork/node/issues/4435.
