### ISSUE TITLE
Toping up

### ISSUE THREAD

**Issue by mehradj1** [mysteriumnetwork/node#4387]
Hi
I toped up my account twice but still cant use the app and my balance is 0
I cant see my my profile either
What should i do?
Can give reffral code or sth for charging my acc i lost 10$ and still cant use the app
I attached my receipt and the app problem
Tnx
[389339a7-a83d-4ca3-9c81-e7031897ae4a.pdf](https://github.com/mysteriumnetwork/node/files/7619238/389339a7-a83d-4ca3-9c81-e7031897ae4a.pdf)
[be0bc538-ba43-4448-a7cb-18fee208b8ad.pdf](https://github.com/mysteriumnetwork/node/files/7619241/be0bc538-ba43-4448-a7cb-18fee208b8ad.pdf)
![Screenshot_20211129-125352_MysteriumVPN](https://user-images.githubusercontent.com/84955449/143897206-da181a59-6084-4548-b03b-3c22e14e7a6c.jpg)

**Comment by tomasmik** [comment]
Transfers have been made, register has failed.

**Comment by mehradj1** [comment]
What should i do?
Could you help me?

**Comment by tomasmik** [comment]
This should be fixed with the next release of mysterium app for android.

**Comment by mehradj1** [comment]
Did i lose my money?

**Comment by tomasmik** [comment]
No. As I said in my comment above. the money has been transferred to your account, no money has been lost.

**Comment by mehradj1** [comment]
What my account is?
I have no information about it
