### ISSUE TITLE
Example docker run command in README fails

### ISSUE THREAD

**Issue by tcharding** [mysteriumnetwork/node#439]
Current command given in `README.md` to start the mysterium node service using docker image `mysteriumnetwork/myst` appears to be incorrect.
```
sudo docker run --cap-add NET_ADMIN --net host --name myst -d mysteriumnetwork/myst service --agreed-terms-and-conditions
```
Current docker image `mysteriumnetwork/myst` does not accept flag `--agreed-terms-and-conditions`

Running the same command *without* this flag brings up the service.

**Comment by soffokl** [comment]
@tcharding Thanks for noticing it, we will fix it soon.
