### ISSUE TITLE
Meysteruim vpn payments

### ISSUE THREAD

**Issue by Akremkr** [mysteriumnetwork/node#4393]
Hello team meysteruim please I buy 5 USD dogecoin meysteruim vpn and not get MYST please sloved my problem

https://pay.coingate.com/invoice/875784f0-f397-4d6f-a725-5fa678a93e3c

My payment completed

**Comment by tomasmik** [comment]
Transfer has been made: https://polygonscan.com/tx/0x02d891393fa4afa926cadafab02a82004ca7ca88e5c4197e6120473d5bf201f3

Apps seem to not be handling the on boarding flow correctly sometimes. There are fixes ready to fix this issue.
