### ISSUE TITLE
Missing PGP key while updating repo

### ISSUE THREAD

**Issue by jkimmel** [mysteriumnetwork/node#4399]
After adding repo as described `sudo apt-get update` ended with NO_PUBKEY ECCB6A56B22C536D
![Mysterium GPG key](https://user-images.githubusercontent.com/2156125/144269585-830bb765-eebc-4a91-853e-384e6207211e.jpg)
``

**Comment by etherunit** [comment]
Add public key to your Ubuntu system using the apt-key command: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ECCB6A56B22C536D`

**Comment by jkimmel** [comment]
Thanks, worked!

Am Do., 2. Dez. 2021 um 07:59 Uhr schrieb etherunit <
***@***.***>:
