### ISSUE TITLE
WARNING: Published ports are discarded when using host network mode

### ISSUE THREAD

**Issue by tcharding** [mysteriumnetwork/node#440]
There are currently multiple images on docker hub
```
mysteriumnetwork/myst
mysteriumnetwork/mysterium-node
```

It is not immediately obvious what is the difference between these two images.  Also the docker command invocation has changed slightly and there seems to be some confusion between the docs on docker hub for these two images, master branch `README.md`, and online docs about the exact command.  (Specifically the flag `--agreed-terms-and-conditions` and `--publish "1194:1194/udp`.)

**Comment by soffokl** [comment]
Yeah, looks like it's again a problem of the incorrect documentation. 
We are going to review and extend our documentation soon. 

Let's keep this issue open specifically to fix the mentioned problem in the documentation.

**Comment by Waldz** [comment]
Lets add depreciated notices to `mysteriumnetwork/mysterium-node` image and links to `myst` image
