### ISSUE TITLE
Balances does not match

### ISSUE THREAD

**Issue by eduardorothschild** [mysteriumnetwork/node#4400]
![image](https://user-images.githubusercontent.com/21217703/144298364-914239b1-4af7-4d2d-8f38-50e305dbf704.png)
If I've never withdrawn MYSTs, why my Unsettled added to my balance would not be equal to the Total Earnings?

**Comment by tomasmik** [comment]
It costs money to settle in to balance, we expect that you will cover that fee with your earnings. Though it seems like the settlements happen too often resulting in a lot of money going in to fees. We'll check and make some adjustments regarding this.

**Comment by dsm012** [comment]
![Screenshot_20211202-103507~2](https://user-images.githubusercontent.com/4349493/144484323-71a81503-8ff5-4ee4-980a-cabb20485cc0.png)
I'm having a similar issue.

**Comment by tomasmik** [comment]
After a talk with the team I got some news on this. We'll add some way to configure the settlement frequency using the UI which should help you with the fees if you want to settle less often and save a few cents. But there is still a fixed rate accountant takes for taking care of payments made. With current config + accountant fees this adds up to something like 30%. With less settlements it could go down to something around 25% or less.

**Comment by dsm012** [comment]
Thanks for the prompt response!

Yeah, a lower fee would be great, but I don't think that's the main issue. The fee needs to be reported somewhere--this is probably a new feature request. Ideally, there would be a transaction report either on a user's node or on their mystnodes.com page. It should show the running balance, as well as the details of all the settled transactions and their associated fees. Perhaps you could provide links to those transactions on the Mysterium blockchain. From an accounting perspective, those fees are needed for tax reporting purposes. Each fee is part of the cost of doing business, so, in many jurisdictions, it's a tax deduction.
