### ISSUE TITLE
Port Restricted Cone.

### ISSUE THREAD

**Issue by ufukcaneski** [mysteriumnetwork/node#4401]
**Your NAT Type: Port Restricted Cone.**

Your NAT Type: Port Restricted Cone. I am facing such a problem. I tried many things but without success. Thinking that I have the problem, I requested a static ip from the internet service provider, but my problem was still not resolved.

**Expected behavior**
I would be very grateful if you could let me know how to fix the port constrained cone problem.

**Screenshots**
![Ekran görüntüsü 2021-12-01 190146](https://user-images.githubusercontent.com/24737685/144300592-c1aabeab-167c-405d-9038-4fe6ebf373be.jpg)

![Ekran görüntüsü 2021-12-01 190109](https://user-images.githubusercontent.com/24737685/144300619-f7c1195e-4988-44f7-83d2-77d6512040b7.jpg)

![Ekran görüntüsü 2021-12-01 223418](https://user-images.githubusercontent.com/24737685/144301517-ab711ad9-cd78-4e63-95ed-498458d38921.jpg)

**Environment (please complete the following information):**
 - Node version: 1.0.9
 - OS: Alpine Linux v3.14(docker)
 - Docker (if applicable): mysteriumnetwork/myst:latest

**Comment by AdnanSayyed** [comment]
![image](https://user-images.githubusercontent.com/30722682/144361275-6893842c-142d-417a-be56-5f73dc1d8787.png)
![image](https://user-images.githubusercontent.com/30722682/144361324-156c6128-d7f3-433c-bfd4-ef0dfca90132.png)

Same for me

**Comment by jos1264** [comment]
> **Your NAT Type: Port Restricted Cone.**
> 
> Your NAT Type: Port Restricted Cone. I am facing such a problem. I tried many things but without success. Thinking that I have the problem, I requested a static ip from the internet service provider, but my problem was still not resolved.
> 
> **Expected behavior** I would be very grateful if you could let me know how to fix the port constrained cone problem.
> 
> **Screenshots** ![Ekran görüntüsü 2021-12-01 190146](https://user-images.githubusercontent.com/24737685/144300592-c1aabeab-167c-405d-9038-4fe6ebf373be.jpg)
> 
> ![Ekran görüntüsü 2021-12-01 190109](https://user-images.githubusercontent.com/24737685/144300619-f7c1195e-4988-44f7-83d2-77d6512040b7.jpg)
> 
> ![Ekran görüntüsü 2021-12-01 223418](https://user-images.githubusercontent.com/24737685/144301517-ab711ad9-cd78-4e63-95ed-498458d38921.jpg)
> 
> **Environment (please complete the following information):**
> 
>     * Node version: 1.0.9
> 
>     * OS: Alpine Linux v3.14(docker)
> 
>     * Docker (if applicable): mysteriumnetwork/myst:latest

Port Forward 10000 - 60000 and it will be solved.

**Comment by ufukcaneski** [comment]
> > **Your NAT Type: Port Restricted Cone.**
> > Your NAT Type: Port Restricted Cone. I am facing such a problem. I tried many things but without success. Thinking that I have the problem, I requested a static ip from the internet service provider, but my problem was still not resolved.
> > **Expected behavior** I would be very grateful if you could let me know how to fix the port constrained cone problem.
> > **Screenshots** ![Ekran görüntüsü 2021-12-01 190146](https://user-images.githubusercontent.com/24737685/144300592-c1aabeab-167c-405d-9038-4fe6ebf373be.jpg)
> > ![Ekran görüntüsü 2021-12-01 190109](https://user-images.githubusercontent.com/24737685/144300619-f7c1195e-4988-44f7-83d2-77d6512040b7.jpg)
> > ![Ekran görüntüsü 2021-12-01 223418](https://user-images.githubusercontent.com/24737685/144301517-ab711ad9-cd78-4e63-95ed-498458d38921.jpg)
> > **Environment (please complete the following information):**
> > ```
> > * Node version: 1.0.9
> > 
> > * OS: Alpine Linux v3.14(docker)
> > 
> > * Docker (if applicable): mysteriumnetwork/myst:latest
> > ```
> 
> Port Forward 10000 - 60000/udp and it will be solved. You will have full Cone

Unfortunately that didn't work. It comes this way by default anyway.
