### ISSUE TITLE
NodeUI - Change registration fee from static to dynamic

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4404]
Currently 0.1 MYST is hardcoded, but as fees are growing on Polygon we need to make a dynamic one. 

Use such formula: (approx. fee) x 2 

Round up to 3 decimals, e.g. 0.125 MYST

**Comment by Guillembonet** [comment]
Done as discussed but I still think we should improve the current solution as if fees increase too much in less than 1 hour it could still fail
