### ISSUE TITLE
The app is not working after top up

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4412]
The payment was processed by CoinGate.
Status: **Paid and Confirmed** 
tx: 6359f90c539c006ac58962c65e951eb47b77ca7bea7f244f5973d2bf5dbaf903
CoinGate Order ID: #10285785

**Comment by tomasmik** [comment]
What does it mean not working?

**Comment by etherunit** [comment]
a.k.a not usable. asking to top up/use ref code again.

**Comment by tomasmik** [comment]
There are no registration requests by the user. Android app is still broken it seems.
