### ISSUE TITLE
stuck on starting Daemon 

### ISSUE THREAD

**Issue by anujno123** [mysteriumnetwork/node#4415]
It's been 1 day VPN is Not Starting it's showing Starting Daemon All time My version is Already Updated Using Windowns 10

**Comment by tomasmik** [comment]
Please provide logs as without them, we don't even know where to look. They should be located in:
* %USERPROFILE%\.mysterium\logs
* %USERPROFILE%\AppData\Roaming\MysteriumVPN\logs
* %PROGRAMDATA%\MystSupervisor

You can open these dirs using windows Run tool.
