### ISSUE TITLE
[android] Connect failed, disconnecting error="could not create p2p channel during connect: p2p dialer failed: could not subscribe to ready subject: nats: invalid connection"

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4422]
**Describe the bug**
Can't connect, I can see a lot of Connect failed, disconnecting error="could not create p2p channel during connect: p2p dialer failed: could not subscribe to ready subject: nats: invalid connection"

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7656271/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.0.5
 - OS: Android

**Comment by etherunit** [comment]
We had some issues with message broker reverse proxy which went into crash loop. It was successfully fixed. Do you still experience this issue @cvl ?

**Comment by cvl** [comment]
Will keep an eye on it.
