### ISSUE TITLE
Where did the rest of my balance go after Auto settlement?

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#4423]
![image](https://user-images.githubusercontent.com/6954079/144754116-d6c631c1-f0a0-48b5-a45a-e0effbf8ff84.png)
The balance and unsettled balance do not add up to the total earnings after the first auto settlement.
Or is it just my bad math??

 - Node version: 1.0.10-cba97919
 - OS: raspbian buster

**Comment by etherunit** [comment]
Please note that Hermes and Blockchain are taking some fees for auto-settlement.

**Comment by tomasmik** [comment]
This seems normal. There should be an explanation added in the next release of UI + we'll be working on ways you can control the auto settlement to maybe settle less and save some money.
