### ISSUE TITLE
Hello please fix my problem mysterium app

### ISSUE THREAD

**Issue by TinyDestinyQueen007** [mysteriumnetwork/node#4424]
Hello mysterium company..am so sorry to brother you

There problem with loading mysterium app I was trying to connect using all VPN it seems like it doesn't work at all please fix this problem right away

**Comment by TinyDestinyQueen007** [comment]
BTW mysterium app server have been down would you please fix this problem right away...

**Comment by etherunit** [comment]
@TinyDestinyQueen007 We had some infrastructure-wide issues that were successfully resolved. I hope it works fine for you now,
