### ISSUE TITLE
Node active, online, MMN ok, but can't register/topup

### ISSUE THREAD

**Issue by phmmining** [mysteriumnetwork/node#4426]
**Describe the bug**
Node hosted on VPS not able to complete setup, not "online".  Vultr/Ubuntu

**To Reproduce**
1. Go to https://mystnodes.com/onboarding/datacenter/0
2. Follow Instructions "Installation on Linux machine in a Data center
3. Once finished, go to NodeUI (ip-of-your-node:4449) and complete claiming by entering API key when asked: 
4. ** Cannot connect (ip-of-your-node:4449) cannot connect.
5. SSH into root@ipaddress
6. » identities list
[+] 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab
»  healthcheck
[INFO] Uptime: 102h25m55.905981815s
[INFO] Process: 8822
[INFO] Version: 1.0.9
[INFO] Branch: 1.0.9. Build id: 420048373. Commit: cde8ab61
 identities get 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab
[INFO] Registration Status: Unregistered
[INFO] Channel address: 0xc6783D14b4a578355856D66EdBDd7Fad2b4f2caD
[INFO] Balance: 0.000000
[INFO] Earnings: 0.000000
[INFO] Earnings total: 0.000000
» identities unlock 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab
[INFO] Unlocking 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab
[SUCCESS] Identity 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab unlocked.
» identities register 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab
[INFO] Registration started. Topup the identities channel to finish it.
[INFO] To explore additional information about the identity use: get <identity>
» identities get 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab
[INFO] Registration Status: Unregistered
[INFO] Channel address: 0xc6783D14b4a578355856D66EdBDd7Fad2b4f2caD
[INFO] Balance: 0.000000
[INFO] Earnings: 0.000000
[INFO] Earnings total: 0.000000
7. Node is active, but not online at mystnodes.com.  Cannot conect to ipaddress@4449

**Expected behavior**
Connect to Node UI to topup or transfer MYST and have node online.  

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag

**Additional context**
This is the second hosted node that will not complete the process. it seems to be something on the API mising

**Comment by tomasmik** [comment]
Free provider registration is only possible using the UI right now. If you're using the CLI you have to send at least 0.15MYST on polygon network to the `Channel address` of your node after or before submitting a registration request.

**Comment by phmmining** [comment]
OK, I sent .15 MYST to  0xc6783D14b4a578355856D66EdBDd7Fad2b4f2caD.
identities get 0xdad3220b4eb8b2b5861d4edb67067efeebbe0bab
[INFO] Registration Status: Registered
[INFO] Channel address: 0xc6783D14b4a578355856D66EdBDd7Fad2b4f2caD
[INFO] Balance: 0.000000
[INFO] Earnings: 0.000000
[INFO] Earnings total: 0.000000

It is showing registered, but NOT in the API and not online at mystnodes.com

**Comment by tomasmik** [comment]
It takes time for it to appear online on mystnodes.com
Seems like everything is working as expected.

**Comment by phmmining** [comment]
OK, it is already 10 hours so how long for the node to be recognized by mystnodes.com and begin to provide service?
