### ISSUE TITLE
LTC Top up fail 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4429]
**Describe the bug**

Litecoin transaction 0.0238 LTC was sent and never reflected on top up

https://pay.coingate.com/invoice/bec9c250-5f22-4c22-b0d4-2e43e8fa35f6

https://chainz.cryptoid.info/ltc/tx.dws?bcd2b1386f72d1960fa653ad736684415f8b476d4d24f7a7e740b5f268c4982b

**Screenshots**
<img width="354" alt="Screenshot 2021-12-06 at 09 07 05" src="https://user-images.githubusercontent.com/84313603/144818194-8fe4c3fb-fc17-4db6-b1a3-fd5f58bd0f12.png">

**Comment by etherunit** [comment]
Hi @isaackielma, please inform user that payment has been processed and myst allocated to the balance of the app.
