### ISSUE TITLE
Back up not working/ Top up not reflected in balance

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4430]
**Describe the bug**

Dear,

I used the topup the vpn app with 12 myst, address used was the the app.

Transaction success but nothing show up in the app!

Here is the tx:

https://polygonscan.com/tx/0x473c5db23f72936107894a2e9dda7186006e360366a4ba7073c1a09609d0361f

One more point, each time I start the VPN app it ask for create new Mysterium ID, restore id from a backup does not work!.

Regards,

Chi

**Comment by etherunit** [comment]
Payment has been processed and MYST allocated into the app. Please let our user to know that.

**Comment by isaackielma** [comment]
Done!
