### ISSUE TITLE
Total earnings and unsettled balance showing incorrect after upgrade to 1.0.12

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#4432]
![Screenshot from 2021-12-06 15-12-58](https://user-images.githubusercontent.com/6954079/144871084-263ba83f-ff93-4bbc-8ed9-6c5813b0aab3.png)
Upgraded to 1.0.11 today and everything wrong on node ui.
In the pic the total earnings do not match the graph or the total earnings on mystnodes.com.
And my unsettled balance went from 0.06 myst to 0.00

**Comment by rmtucker** [comment]
My mistake it put itself right after a few hours.Will close this

**Comment by rmtucker** [comment]
After upgrading about 3hrs ago i have the same problem again.
Total earnings showing as 0.18myst and no unsettled balance.
But the graphs are showing correctly.
Why does it take so long for the ui to show the correct figures after an upgrade?

**Comment by Donatas-MN** [comment]
@rmtucker What is your identity?

**Comment by rmtucker** [comment]
0x3529b0ebdbdd536074de9c25f17151de62cff8cd
I watched the node carefully and the figures are not updated until the next session.which in my case was not until a good few hours later.

**Comment by Donatas-MN** [comment]
What are the current numbers you're seeing?

**Comment by rmtucker** [comment]
![Screenshot from 2021-12-09 14-53-37](https://user-images.githubusercontent.com/6954079/145419248-894c5c11-0429-4362-aeac-e3e1983843f1.png)
The figures are all correct i believe at the moment but as soon as i do an upgrade they do not show correctly until a session is started.

**Comment by Donatas-MN** [comment]
Yes, figures look correct now. @lusine-h can you try to reproduce bug when after upgrade wrong earning figures are shown for some time?

**Comment by rmtucker** [comment]
Same problem again after updating to 1.0.14
![Screenshot from 2021-12-13 10-58-34](https://user-images.githubusercontent.com/6954079/145800632-a8c9983b-d206-405f-a922-2bda4fb1db8a.png)

**Comment by Donatas-MN** [comment]
Yes, it looks like it sometimes shows incorrect numbers until new session is started after update to new version. Adding this to ToDo list.

**Comment by mdomasevicius** [comment]
As a partial fix - live session stats are now added to the all time historical stats (shown in the cards)
