### ISSUE TITLE
Bitcoin top up credit

### ISSUE THREAD

**Issue by Mrpiebald** [mysteriumnetwork/node#4433]
I clicked top up and sent in Bitcoin twice but it's not showing in my mysterium account

**Comment by isaackielma** [comment]
Could you please try restarting your device to see if the balance updates?

Looking forward to your response!

**Comment by Mrpiebald** [comment]
I just did that and it didn't help. I still only see the second,
approximately $4 top up but not the initial $20 top up that was done.

**Comment by isaackielma** [comment]
Mysterium ID : 0x1450ca3433a3cc2b30f46e92d0eaaecbc6cdb25d

**Comment by tomasmik** [comment]
There is only a single order created for 4.95 MYST which is paid.

**Comment by Mrpiebald** [comment]
That's disappointing to hear because the day before I did in fact do a $20
top up and those Bitcoin have been sent from my coinbase account

**Comment by isaackielma** [comment]
<img width="318" alt="Screenshot 2022-05-10 at 05 27 56" src="https://user-images.githubusercontent.com/84313603/167584461-ef731ef2-83e1-4abf-ab17-152ca7393c89.png">

https://www.blockchain.com/btc/tx/d9cc4e4b1da0353f27b8d8ddd0f95712c27e7d5ba619b855bf08c3ff0f10fb0d

**Comment by isaackielma** [comment]
Mysterium ID: 0x1450ca3433a3cc2b30f46e92d0eaaecbc6cdb25d 

User has also added: "The initial $20 transaction done on November 24th via the coingate invoice was done before I had a login to coingate and so I don't have a email record of that however I do see the completed transaction on my coinbase account."

**Comment by Mrpiebald** [comment]
I had a message thread going in the app, but that doesn't seem to be there any longer. The last thing I that was asked of me was to look in my android download folder for a file. Would you remind me what file I'm looking for and what the file name or extension is?
