### ISSUE TITLE
Tokenomics 1.5 - Debug and test IQ borrower on Testnet environment

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#4440]
Tasks:
- [x] 1. Debug why currently rent amount is 0.
- [x] 2. Configure IQ borrower to look into Mainnet Hermes earnings, so testing could be done with actual borrowing amounts.
- [x] Investigate why Pagerduty receives alert for cron running over 12 hours.

**Comment by Donatas-MN** [comment]
UI: https://testnet.iq.space/
