### ISSUE TITLE
Your identity is being registered, please be patient...

### ISSUE THREAD

**Issue by muffs123** [mysteriumnetwork/node#4448]
Node id : 0x99158ad777404bb832b3c0a47ffb557fdbd271a9

Node is in Linux and its ststus seems like it is working.
Tried the manual method :
myst cli identities list
...
myst cli identities unlock X
...
myst cli identities register X

Still stuck with same error on the dashboard

**Comment by tomasmik** [comment]
Registration from CLI will not work if you dont transfer any MYST to your payment channel. The only way to register for free is using the UI to submit the free registration request when those are possible.

All your registration requests have failed. Please try again using the UI.

**Comment by muffs123** [comment]
But how to register thru the GUI?
It is stuck on the Registration screen with the method "Your identity is being registered, please be patient..."
Please advice..........

**Comment by tomasmik** [comment]
Node will appear online after some time.
