### ISSUE TITLE
[android] align with hermes failed with a critical error, offchain balance out of sync error="could not request consumer data from hermes

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4454]
**Describe the bug**
Complains about a lot of "OnHold". I can see multiple errors like "align with hermes failed with a critical error, offchain balance out of sync error="could not request consumer data from hermes"

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7684050/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.0.5
 - OS: Android

**Comment by Donatas-MN** [comment]
OnHold is caused by interrupted internet connection, so it's on client side. However, improvements were made to prevent errors like "align with hermes failed with a critical error, offchain balance out of sync error="could not request consumer data from hermes" happening instantly on OnHold, so now such situations should be much more rare.

**Comment by cvl** [comment]
Hi Donatas.

"OnHold is caused by interrupted internet connection, so it's on client side."

Do you see this from logs (if so, could you tell me what indicates this), or is this just a guess?

**Comment by cvl** [comment]
By the way, lots of users have this problem.

**Comment by Donatas-MN** [comment]
> Hi Donatas.
> 
> "OnHold is caused by interrupted internet connection, so it's on client side."
> 
> Do you see this from logs (if so, could you tell me what indicates this), or is this just a guess?

It becomes "OnHold" when internet connection is interrupted, I mean it's coded like that. Could you get more data from users regarding their internet connection? I guess it's pretty unstable?

**Comment by cvl** [comment]
- OnHold _should happen_ when connection is interrupted
- Connection interruption can occur for various reasons, namely (at least):
-- If connection is unstable on client end (as you suggest)
-- If connection is interrupted in between client and provider
-- If provider interrupts connection
-- Due to some software bug not handling some networking state properly

Considering this happens quite frequently to multiple, esp after mainnet release, I'd suggest to investigate the possible cause.
Alternatively, perhaps we could add some reporting to logs, so client node would log if OnHold happened due to unstable client connection (not sure if it's possible to detect that though).
