### ISSUE TITLE
MYST Balance disappeared after rebuilding node

### ISSUE THREAD

**Issue by djcrawleravp** [mysteriumnetwork/node#4457]
**Describe the bug**

**To Reproduce**
1. Deposit 0.2 MYST into the wallet to activate your node after creating a docker container
2. Delete Docker container
3. Rebuild your node and put your withdrawal wallet
4. 0 Myst on the new balance

**Comment by etherunit** [comment]
@djcrawleravp Have you used volumes to keep the previous data state?
By default, Mysterium uses `-v myst-data:/var/lib/mysterium-node` but you can replace myst-data with the path where you'd like to store the node's configuration and keystore files, e.g.

**Comment by djcrawleravp** [comment]
Sure, my node eas updated with watchtower using the exact same address

**Comment by etherunit** [comment]
Thanks. It's still not clear for me how did the rebuild process worked. Could you shred some light here?

**Comment by djcrawleravp** [comment]
All I have is my Watchtower logs prior to the issue now, I have deleted my mysterium node

last Saturday at 05:01:32 time="2021-12-11T05:01:32-04:00" level=info msg="Stopping /portainer (71ffeb7566ee) with SIGTERM"
last Saturday at 05:01:33 time="2021-12-11T05:01:33-04:00" level=info msg="Stopping /presearch-node (b1462a3d8e5b) with SIGTERM"
last Saturday at 05:01:34 time="2021-12-11T05:01:34-04:00" level=info msg="Stopping /Mysterium-Network (60f332de3315) with SIGTERM"
last Saturday at 05:01:35 time="2021-12-11T05:01:35-04:00" level=info msg="Creating /Mysterium-Network"
last Saturday at 05:01:36 time="2021-12-11T05:01:36-04:00" level=info msg="Creating /presearch-node"
last Saturday at 05:01:37 time="2021-12-11T05:01:37-04:00" level=info msg="Creating /portainer"
last Saturday at 05:01:38 time="2021-12-11T05:01:38-04:00" level=info msg="Removing image cbab0690b2f2"
last Saturday at 05:01:38 time="2021-12-11T05:01:38-04:00" level=info msg="Removing image 29b23fe3c9c3"
last Saturday at 05:01:38 time="2021-12-11T05:01:38-04:00" level=info msg="Removing image 725d6dd70b20"

**Comment by etherunit** [comment]
Can you please specify which command exactly was used to start a node? We have tried to reproduce it without any success (data-dir content was saved using volumes as stated in our official docs).

**Comment by etherunit** [comment]
Closed due to inactivity.
