### ISSUE TITLE
Add a " Dark Mode "to the NodeUI? Thanks

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4458]
**Is your feature request related to a problem? Please describe.**
Few providers have previously asked for a dark mode on node UI. That would be cool, though not a priority at all. Just expressing our providers preferences and suggestions 😉

**Comment by Ayse-AK** [comment]
In process, This feature is covered under [here](https://github.com/mysteriumnetwork/mmn/issues/327)
