### ISSUE TITLE
Status of Withdrawals, transaction details

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4459]
**Is your feature request related to a problem? Please describe.**

If for some reason it shows on CLI withdraw succeeded, but it does not reflect on balance. Would be nice if there was an easy way to track. Or any info to be able to check on blockchain explorer.

<img width="1290" alt="Screenshot 2021-12-09 at 18 21 55" src="https://user-images.githubusercontent.com/84313603/145453725-f478d736-b420-4eac-80f5-6eef8972bfc3.png">

When we see "withdrawal succeeded" for a mainnet CLI withdraw, there should be some public way to see the status of this, similar to a blockchain explorer, so we can see any issues or if the transaction fails or stuck some where

**Comment by Donatas-MN** [comment]
Balance issue is now fixed. Regarding transaction hash, it's already available in the UI, but we will also add it to CLI.

**Comment by tomasmik** [comment]
TequilaAPI already exposes an endpoint `/identities/settle/history` which is also used by the NodeUI.

- [ ] Add a new command `identities last-withdrawal <IDENTITY>` which would browse that endpoint and return you some information on your last withdrawal.

**Comment by n10ty** [comment]
Added command ```identities last-withdrawal <identity>```
Example of response:
```
[INFO] Tx hash:  0x01c3fae5848950f178b04061ed899fdccda77693d2099139769425ad1a2bf178
[INFO] DateTime:  2022-03-10T13:08:21Z
[INFO] Beneficiary:  0x40a307f2e7C62Ad833349C8707BE907e523ec431
[INFO] Amount:  0.077056
[INFO] Fees:  0.022944
[INFO] Blockchain explorer Url:  https://polygonscan.com/tx/0x01c3fae5848950f178b04061ed899fdccda77693d2099139769425ad1a2bf178
[INFO] Error: none
```
