### ISSUE TITLE
Dashboard not accessible after update

### ISSUE THREAD

**Issue by Stephen988** [mysteriumnetwork/node#4460]
**Describe the bug**
on my raspberry pi 4 running raspbian os (Debian 10) after run sudo apt update and upgrade, updating myst node from 1.0.9 to .12, Dashboard is not more accessibile, I get blank page "ERR_CONNECTION_REFUSED", restarted service and reboot device.
Node is actually work if I connect to it with android mysterium vpn client.

**To Reproduce**
update repo and upgrade version from 1.0.9 to 1.0.12

**Expected behavior**
open dashboard like always on local device ip:4449

**Screenshots**
![IMG_20211209_223219](https://user-images.githubusercontent.com/64849759/145483335-849c4b89-d6be-4b26-a9b5-f6e68719437b.jpg)
![IMG_20211210_004639](https://user-images.githubusercontent.com/64849759/145493322-c9fd44e3-0dc2-451b-af5b-53f61fc1b076.jpg)

**Environment (please complete the following information):**
 - Node version: 1.0.12
 - OS: raspbian buster

**Comment by etherunit** [comment]
@Stephen988 Is this possible to see the output of the **dev console** while pushing a refresh of the page?

**Comment by Stephen988** [comment]
> @Stephen988 Is this possible to see the output of the **dev console** while pushing a refresh of the page?

Hello @etherunit we have talk also on Discord, this the link of your last reply https://discord.com/channels/614079733663006750/628640906844831754/918796420159537153
You tell me after post screenshot console in F12 there is a incompatibility with tailscale.

**Comment by Stephen988** [comment]
Thanks for closing issue @Donatas-MN without find a solution, actually  if I try to open my localip:4449 not work.
