### ISSUE TITLE
All sessions earn 0.00 MYST, no matter the time or MB

### ISSUE THREAD

**Issue by phmmining** [mysteriumnetwork/node#4461]
**Describe the bug**
My node on a residential IP is perforimg 10+ sessions per day and earn 0.00

**To Reproduce**
1. Go to Node UI (ip:4449/#/sessions)
2. View sessions
3. Notice Sessions of 100MB+, 0.00 earning.
4. Notice 100+ sessions for 3 days, 0.00 earnings

**Expected behavior**
Earning commensurate with activity

**Screenshots**
![image](https://user-images.githubusercontent.com/86210791/145495616-14e3727f-2c91-4510-8232-8532a084d527.png)

**Environment (please complete the following information):**
 - Node version: 1.0.9
 - OS: Ubuntu 20.4.3 LTS
 - Residential IP
-  Node: 0x59b989918ecef80d71632a5bcee806ae2771e256

**Additional context**

**Comment by phmmining** [comment]
Day 5 with multiple sessions per hour and up to 100 MB sessions that earn Zero.  Also can't withdraw myst already settled.  Updated to 1.0.12 today, no fix

**Comment by etherunit** [comment]
@phmmining Could you add myst.db file here (`/var/lib/mysterium-node/mainnet/db/myst.db`)? It's important to verify that session relevant data is being stored in myst.db file and fails to "visualise" in UI.

**Comment by phmmining** [comment]
How do I "add myst.db file here"?  I found the file, but don't know how to
add to email.  It's not a file to open or move in Ubuntu

**Comment by phmmining** [comment]
Can I get the DB info in terminal?  Just give me the command codes.  I am
not able to open or send the DB file from Ubuntu

**Comment by etherunit** [comment]
Could you zip it and add here please? thanks

**Comment by etherunit** [comment]
Also, is it possible to submit a screenshot of the main dashboard window of UI? The one which shows Total earnings 

<img width="1198" alt="Screenshot 2021-12-28 at 12 23 17" src="https://user-images.githubusercontent.com/60128746/147556571-7f97cce5-702b-4c89-a255-afb07d8e5fdb.png">

**Comment by phmmining** [comment]
I deleted the node and reinstalled. New node working fine

**Comment by Donatas-MN** [comment]
@phmmining It was probably something corrupted in database, so it could not be displayed in UI. If you encounter this issue again, send us DB extract so we could locate actual issue. Thanks!
