### ISSUE TITLE
Node - Increase auto-settlement threshold to 0.9 MYST

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4465]
Currently it's 0.25: https://github.com/mysteriumnetwork/node/blob/master/config/flags_payments.go#L83

This will ease MATIC shortage on Transactors.

Also, NodeUI explanation should be adjusted to 0.9:
![Pasted_Image_2021-12-10_12_02](https://user-images.githubusercontent.com/91055712/145555836-02190153-6c9f-4cd2-84e9-0461f4277942.jpg)

**Comment by rmtucker** [comment]
I am not sure if this is a good idea?
Looking at my stats below (Dismal) after 11 days of connection,I could maybe draw my £0.13 once a month?
![Screenshot from 2021-12-11 19-14-30](https://user-images.githubusercontent.com/6954079/145688784-6c6c865c-32d0-4130-9171-d270705ca162.png)

**Comment by Donatas-MN** [comment]
@rmtucker You will be able to adjust this yourself in the near future. Anyway, having lower auto settlement threshold means that you're paying more blockchain fees as well, so higher is more optimal.

**Comment by tomasmik** [comment]
You're also able to settle yourself anytime you wish, even at 0.1MYST. This only concerns automatic settlements.
