### ISSUE TITLE
Atomic Wallet is NOT compatible

### ISSUE THREAD

**Issue by stutteringp0et** [mysteriumnetwork/node#4467]
**Describe the bug**
I wanted to test withdrawals with the smallest possible amount, and I'm glad that I did.  I attempted a transfer to my Atomic Wallet (0x5a0e68bF95ed0575f8480195fFf91161CF0C9F2b) and that deposit seems to have vanished.  It never arrived.

I chose Atomic specifically because it was recommended by your documentation as a compatible wallet.

**To Reproduce**
1. Host for days and days
2. Attempt withdrawal
3. experience disappointment

**Expected behavior**
A transfer to my wallet, obviously...

**Screenshots**
<img width="627" alt="image" src="https://user-images.githubusercontent.com/310899/145691297-60ef8db8-e230-4d88-81c9-c91c0cb93a8c.png">

**Environment (please complete the following information):**
Node version: mainnet (1.0.12-7215c255)
NodeUI version: 1.1.1
Ubuntu 20.04.3

**Additional context**
I opened a ticket with Atomic as well.  I'm not sure where the error occurred.

**Comment by stutteringp0et** [comment]
According to Atomic support:

> You have deposited a Polygon network token (removed link)
> 
> We don't support Polygon Network. This is the reason you don't see your balance.
> 
> Your funds are not lost, but you will need extra actions to retrieve them. You will need to import your keys to Metamask.

So, your documentation should be updated to reflect that Atomic Wallet is NOT compatible.

**Comment by adinetech** [comment]
Transaction Hash: https://polygonscan.com/tx/0x516343a036eeb856315e0eb0da17da295088ffe98d72c9818420c25d61afec7a

You got paid, but I'm not sure whether atomic wallet supports adding custom tokens.
I recommend you to use that same recovery phrase on Metamask/Trust Wallet/Coinbase Wallet!

**Comment by stutteringp0et** [comment]
I was able to recover the funds - My reason to leave this issue open is that the documentation suggests Atomic Wallet when it cannot receive the transactions.

**Comment by etherunit** [comment]
@stutteringp0et Have you tried adding MYST as a custom token? https://support.atomicwallet.io/article/42-how-to-add-a-custom-erc20-eth-token
It could be that it's just a visual display issue.

**Comment by stutteringp0et** [comment]
@etherunit Yes, I tried that - and that's how I found that it doesn't work, confirmed by Atomic support (email quoted above).  They don't support transfers through polygon, which is the Myst default (because eth gas fees are so high I suppose).

**Comment by etherunit** [comment]
Thanks for checking. We have adjusted our documentation page.

**Comment by WayneChattillon** [comment]
Atomic Needs to Support Polygon since it  has 2 versions of polygon (eth) and Polygon (Matic) Polygon (ETH) = Ethereum Polygon (Matic) = Matic https://crypto-wikipedia.com/what-is-polygon-matic/  Offical site https://polygon.technology/  https://polygon.technology/matic-token/ $matic Witch is Used for eth gas or any side token that is part of eth network
