### ISSUE TITLE
Withdrawal has dissapeared into thin air

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#4471]
Pressed the withdrawal button this morning and my 0.18myst has just Vanished?
It has not appeared in my metamask wallet like every other time.
And the last withdrawal shown at the bottom of the window is a few days ago.
Here is an exert of the logs around that time:-
3 13:14:00 raspberrypi myst[22795]: 2021-12-13T13:14:00.162 INF session/pingpong/hermes_promise_settler.go:469 > Marked provider {0x3529b0ebdbdd536074de9c25f17151de62cff8cd} as requesting settlement
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.305 INF session/pingpong/hermes_promise_settler.go:277 > Received hermes promise for {"0x3529b0ebdbdd536074de9c25f17151de62cff8cd"}
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.305 DBG eventbus/event_bus.go:81                 > Published topic="SessionTokensEarned" event={ProviderID:{Address:0x3529b0ebdbdd536074de9c25f17151de62cff8cd} SessionID: Total:+178139000000000000}
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.306 INF session/pingpong/hermes_channel_repository.go:274 > Loaded state for provider {"0x3529b0ebdbdd536074de9c25f17151de62cff8cd"}, hermesID "0xa62a2A75949d25e17C6F08a7818e7bE97c18a8d2": balance 0, available balance 751069316119128480, unsettled balance 154188348610405320
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.306 INF session/pingpong/hermes_promise_settler.go:304 > Hermes "0xa62a2A75949d25e17C6F08a7818e7bE97c18a8d2" promise state updated for provider {"0x3529b0ebdbdd536074de9c25f17151de62cff8cd"}
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.307 WRN consumer/session/session_storage.go:226  > Received a unknown session update, sessionID:
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.307 DBG eventbus/event_bus.go:81                 > Published topic="earnings_change" event={Identity:{Address:0x3529b0ebdbdd536074de9c25f17151de62cff8cd} Previous:{LifetimeBalance:+905257664729533800 UnsettledBalance:+154188348610405320} Current:{LifetimeBalance:+905257664729533800 UnsettledBalance:+154188348610405320}}
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.508 WRN core/state/state.go:368                  > Couldn't find a matching session for earnings change:
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.697 DBG eventbus/event_bus.go:81                 > Published topic="provider_withdrawal_requested" event={ProviderID:{Address:0x3529b0ebdbdd536074de9c25f17151de62cff8cd} HermesID:0xa62a2A75949d25e17C6F08a7818e7bE97c18a8d2 FromChain:137 ToChain:137}
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.699 INF session/pingpong/hermes_promise_settler.go:577 > caling mister transactor
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.700 DBG session/pingpong/hermes_promise_settler.go:436 > Updating promise with latest fee. HermesID 0xa62a2A75949d25e17C6F08a7818e7bE97c18a8d2
Dec 13 13:14:01 raspberrypi myst[22795]: 2021-12-13T13:14:01.979 DBG session/pingpong/hermes_promise_settler.go:452 > promise updated with latest fee

**Comment by rmtucker** [comment]
There is a line a little further down :-

Dec 13 13:17:02 raspberrypi myst[22795]: 2021-12-13T13:17:02.243 INF session/pingpong/hermes_promise_settler.go:593 > withdrawal complete

**Comment by rmtucker** [comment]
Here are the node logs for all of yesterday.
This is after upgrade to 1.0.14 yesterday.
I am not sure if it is worthwhile continuing with a mysterium node as it is unsafe now to withdraw any settled balance,which makes it all a little pointless.
There seems to be no way of verifying this transaction.

[node.logs.zip](https://github.com/mysteriumnetwork/node/files/7710855/node.logs.zip)

**Comment by rmtucker** [comment]
Screenshot of recent Transactions on polygonscan.
But nothing for yesterday.
![Screenshot from 2021-12-14 14-05-26](https://user-images.githubusercontent.com/6954079/146013569-e0eaedb0-bde1-4136-8f01-f4d44ffa0752.png)

**Comment by tomasmik** [comment]
Your withdrawal is not gone, as you can see you have withdrawal promise with the amount you tried to withdraw here: https://hermes.mysterium.network/api/v2/data/provider/0x3529b0ebdbdd536074de9c25f17151de62cff8cd/withdrawal

The problem here is that it failed to settle that promise. It will try to do it again when another settlement is requested. Hermes will remember that you are owned money.
There are some possible improvements for this workflow which will be implemented some time in the near future.

**Comment by rmtucker** [comment]
Yes it put itself right today with the next withdrawal,Thank you.
