### ISSUE TITLE
bug: Top-up is completed but MYST is not credited on the Mysterium dVPN.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#4472]
**Describe the bug**
Top-up is made and completed but MYST is not credited on the Mysterium dVPN

**Expected behavior**
Coingate tells as Paid and Confirmed but so far, able to get into the Mysterium dVPN but with the balance 0MYST instead of 5MYST

**Screenshots**
![Mysterium](https://user-images.githubusercontent.com/68943180/145839576-92e52662-2516-4e8b-ac04-0ccb0a998257.png)

**Environment:**
 - OS: Android 9.0 (Android Pie)
 - Mobile app version: 2.0.3

**Additional context**
Coingate invoice: https://pay.coingate.com/invoice/4c741606-99e5-470e-9db4-60162cbcb0cc
Mysterium ID: 0x97963797ce5d24a2898904b473acf61b9f5c48fe

The reported user @Talisman33 (Telegram) confirmed that he paid 2.71USD for 5MYST.

**Comment by etherunit** [comment]
@adinetech While team is looking into this issue, is it possible to check whether user could extract node logs? thanks

**Comment by tomasmik** [comment]
MYST sent. Bug will be fixed in a bit.
