### ISSUE TITLE
Open NodeUI is not working for 2nd container

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4473]
`openNodeUI` in mystnodes always points to the default socket {http://localhost:4449) which is fine for default WebUI port, however, it doesn't work in case provider run more than 1 container (with different port mappings, e.g. 4447:4449, 4445:4449..).

**Comment by Donatas-MN** [comment]
Only one node should be run on the same IP machine, so one container is enough in this case.
