### ISSUE TITLE
Its Showing  "Failed to lookup proposal:no providers avaiable for the filter (path='Connection')"

### ISSUE THREAD

**Issue by ashutoshno120** [mysteriumnetwork/node#4478]
**Describe the bug**
in my all Application when I connect any USA node (residential) is showing this error "Failed to lookup proposal: no providers available for the filter (path='Connection')"
I tried to uninstall and install again and delete the .mysterium folder but still, the issue is the same can you please look at this.

**Environment (please complete the following information):**

 - OS: Windows 10
 - Desktop app version (if applicable): 10.1.0

![image](https://user-images.githubusercontent.com/96180338/146179059-8bf00c61-6601-4f4e-ade3-9551c5df5e81.jpg)
Here is log
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7718972/mysterium-node.log)

**Comment by etherunit** [comment]
There was some improvements done on the discovery part. Could you try to restart the app and see if this issue remains?
