### ISSUE TITLE
[linux] linux consumer app doesn't work at all on Ubuntu after last update

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4480]
**Describe the bug**
- Install Mysterium app
- Select provider and try to connect
- Error is displayed "failed to lookup proposal: no providers available for the filter"

Apparently this commit broke the app: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/1e5f35d498b57623604d7125bca67a8defbab667 was added 

**Environment (please complete the following information):**
 - Node version: 1.0.14
 - OS: Ubuntu

**Comment by tomasmik** [comment]
We know https://github.com/mysteriumnetwork/node/issues/4478

**Comment by tomasmik** [comment]
This was also caused by an update to discovery, not the app. Should be resolved either now or very soon.

**Comment by etherunit** [comment]
Did you try with Quality:Any or Medium+ or higher? @cvl 
There was a fixed deployed by Dmitry, should be working now.

**Comment by cvl** [comment]
It was three bars I believe.

Also it's working fine when built without https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/1e5f35d498b57623604d7125bca67a8defbab667

**Comment by cvl** [comment]
With 1.0.15 node fails to boot up.

I get the following error:
![20211216_134722](https://user-images.githubusercontent.com/100252/146366593-8ac6fa5f-f4d7-40e4-96e6-5d330ac9cc02.jpg)

**Comment by cvl** [comment]
Also fails on Windows with the same error
Failed to execute command:  error="could not get hermes URL: Post \"https://polygon1.mysterium.network/\": dial tcp: lookup polygon1.mysterium.network: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."

**Comment by cvl** [comment]
A lot of users can't boot up app now with node 1.0.14.

As 1.0.15 is broken, do you plan to release fix in 1.0.16 anytime soon?

**Comment by cvl** [comment]
Didn't see that this was closed :)
