### ISSUE TITLE
mystnodes.com shows nodes as offline despite updating node data

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4481]
In mystnodes.com panel it shows some of my nodes as offline, having last seen be between 1hour and 2 days. Nodes are online and responsive, restarting a node does not make it appear as online either. However one of my nodes was still on 1.0.9, I updated it to 1.0.14, it is still shown as offline for a day but the node version has been updated to 1.0.14 in mystnodes.com. Probably a database error or a backend upgrade that broke things.

**Comment by rmtucker** [comment]
My node is also showing as offline for the last hour,also running ver 1.0.14.
But according to the logs everything is running fine.

**Comment by no-good-usernames-left** [comment]
I also have this issue, these nodes need way too much babysitting and don't auto update when new code is released

If I have to manually apt-get update && reboot now every few days, this is not a good design

**Comment by etherunit** [comment]
Fix will be deployed tomorrow morning.

**Comment by etherunit** [comment]
Can you please check it now? Node status fix has been deployed.

**Comment by rmtucker** [comment]
Seems to be working fine here now,Thank you
