### ISSUE TITLE
Account Recovery 

### ISSUE THREAD

**Issue by DANS55** [mysteriumnetwork/node#4483]
Hello MySteriumVpn customers,

I recharged my account today and my account became paid. The important thing is, I was trying to connect to the servers, but the connection was not accepted. I tried many ways, but it did not connect to any server.

I tried to clear the app's storage data, but I forgot to download the keystore

I am calling you now to retrieve it, please reply and help.

my identity address: 0x5f3504dd88bc649fad58f9a0bcc0fa7c990a51ca

**Comment by DANS55** [comment]
please help me

**Comment by DANS55** [comment]
please help me

**Comment by veldspar** [comment]
there is no way to recover your balance - you and only you are in control of your account. That is why the app asks you to back up the private key behind your identity when you install it. if you did not back it up, consider it unrecoverable
