### ISSUE TITLE
Withdraw not received in wallet

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4485]
**Describe the bug**

I added the token MYST to the Freewallet.
But the withdraw does not arrive and I just want understand what happened.
Transaction details: https://polygonscan.com/tx/0x56db458fc5278cbe1ce95960ddff2d33ed781644b8d886e6cce8bb6999cfa915
Thanks for help.
Best Regards,
Sérgio Rodrigues

**Comment by etherunit** [comment]
He added it on Polygon Matic Mainnet or ETH?

**Comment by isaackielma** [comment]
ETH

**Comment by etherunit** [comment]
He made a withdrawal using Polygon chain to Ethereum wallet? Unfortunately, it's not possible.

**Comment by etherunit** [comment]
@isaackielma I am closing this one for now. Feel free to reopen it if needed.
