### ISSUE TITLE
Lost back up on recent top up 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4487]
**Describe the bug**
Hi. I lost the recovery backup. But I have all the information of the purchase transactions. Can you help me fix it?

https://pay.coingate.com/invoice/db855644-6fd9-4bdc-98a7-d406f8680baa

https://dogechain.info/tx/2bda0fcee29bb333fc2f164a9fa754f16cd7869c6e3d189e5b44e2170e93f9d4

<img width="532" alt="Screenshot 2021-12-16 at 02 19 48" src="https://user-images.githubusercontent.com/84313603/146274266-af6dc523-c8f3-4781-9e62-265f0225af04.png">

**Comment by tomasmik** [comment]
If you loose your identity, thats it. Nothing we can do about it sadly.

**Comment by isaackielma** [comment]
Thanks you!
