### ISSUE TITLE
Node-UI 1.1.5 not showing details after login

### ISSUE THREAD

**Issue by JustMe0815** [mysteriumnetwork/node#4491]
**Describe the bug**
After login to the Node-UI, the dashboard loads with all 0 values. Once refreshed, it loads up fine.

**To Reproduce**
1. Log-out of Node-UI
2. Log-in to Node-UI

**Expected behavior**
Show correct details even on first login.

**Screenshots**

**Environment (please complete the following information):**
 - Node-UI version:1.1.5 

**Additional context**
-No errors in logs

**Comment by etherunit** [comment]
@lusine-h Have you noticed such behaviour when doing QA tests?

**Comment by lusine-h** [comment]
I didn't notice such behavior, it looks good to me

**Comment by lusine-h** [comment]
I installed the Node from scratch (for double-checking) and a bug exists for me (version 1.1.5)

**Comment by Donatas-MN** [comment]
This was fixed with later version.
