### ISSUE TITLE
[windows, linux] node doesn't start at all with 1.0.15

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4492]
**Describe the bug**
After updating the 1.0.15 the app can't start at all.

Error on Windows:
Failed to execute command: error="could not get hermes URL: Post "https://polygon1.mysterium.network/\": dial tcp: lookup polygon1.mysterium.network: getaddrinfow: This is usually a temporary error during hostname resolution and means that the local server did not receive a response from an authoritative server."

On Linux:
![20211216_134722](https://user-images.githubusercontent.com/100252/146403291-81adaf54-f531-4fe1-b8b0-47cb58ef7bdc.jpg)

**Environment (please complete the following information):**
 - Node version: 1.0.15
 - OS: Windows, Linux
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag

**Additional context**

**Comment by cvl** [comment]
might be related: https://github.com/mysteriumnetwork/node/issues/4480

**Comment by tomasmik** [comment]
Should now be resolved

**Comment by cvl** [comment]
Yes, started working now. Thanks!
