### ISSUE TITLE
WG service unable to receive any traffic, despite node status being Online and WG service running

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4494]
**Describe the bug**

Since upgrading to version 1.0.10, I've been unable to run the OpenVPN service, and hence haven'y been earning anything. For some reason, since the day I final created my nodes (on the test net), the WG service on my nodes haven't been able to receive any traffic, despite the node status being Online and the WG service running.

none of my nodes are attracting any traffic or generating any MYST.
This has has been the case since the very first day for me, even when the nodes were on test net. The way I previously got around this issue was to start the OpenVPN service via the CLI, and then this issue got resolved and I was getting traffic. Now I understand that OpenVPN is no longer being supposed, so I cannot run the service, but the problem is that I then have no other was to generate MYST, as WireGuard is not getting any traffic despite it seemingly running properly.
What do you think the issue would be that OpenVPN worked fine for me, but WireGuard isn't? I'm running the nodes on dockers within Ubuntu OpenVZ VPSs. Thanks

nodes:

0x20d4d776151f79a5187a69efd6ece07a4a832d4e
0x087a70d7b4aa9bdc3e4c74e737fe856926cf47be
0xdeedfd1f6e2bed40e9574c90f1d24c4b85c510da
0xf585bcb02c273afbf7f17fb4c439c3edfc8f2de3
0xfcb45a4f34c8745f4e73ad487bc83a5c6e3bc88e
0xb70cb9ba98be5df9eb17bb544f45f696b1f620f8
0xb6a0f0f16e58ba2fc5a8c6469b181a8280f3ee6a
0xbfad7c7db8626579c5a0d7d69f787a647089f462
0x57e34d5e099f4999f8c669e394c444b3673fc4d8

**Comment by etherunit** [comment]
I checked a few of identities and it seems that all attempts to establish a vpn connection using wireguard have failed (see below) with the following errror:

`could not create p2p channel during connect: p2p dialer failed: could not subscribe to ready subject: nats: invalid connectioncould not send p2p session create request: peer error: cannot start session: : cannot get provider config for session a24cc269-8ecc-4a5e-8bee-0a3d6db74f0a: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: no such file or directory`

<img width="764" alt="Screenshot 2021-12-17 at 09 11 53" src="https://user-images.githubusercontent.com/60128746/146504511-ce4fe986-b8c7-482f-8296-d811c853d039.png">

**Comment by etherunit** [comment]
Now I see that your are running docker containers with ubuntu openvz vps. Please note that OpenVZ containers (like your VPS) do not have access to TUN virtual device by default. It could require you to ask your hosting support to enable TUN for you.

**Comment by isaackielma** [comment]
Checked within the VPS Control Panel, TUN / TAP seem to have been enabled (please see attached screenshot), and also went through the information you shared in the link, the result of that also seems to indicate TUN is supported and enabled


Within the logs however, I noticed one more error message relating to the WG interface, please see attached screenshot. Perhaps this is the main culprit? I spent the entire night trying to fix this by looking at guidance online, but haven't been able to sort this out. Do you have any suggestions?

Also, coming back to my original point, if there was something wrong with the VPS configuration, OpenVPN should not have worked before, but I was previously able to successfully receive connections and earn by enabling the OpenVPN service. Since that has now been discontinued, I can't do so anymore, and WireGuard is for some reason not working properly


<img width="1348" alt="Screenshot 2021-12-20 at 01 03 22" src="https://user-images.githubusercontent.com/84313603/146690682-e17ce205-0aa3-436e-a039-20ee9c132343.png">
<img width="1351" alt="Screenshot 2021-12-20 at 01 03 10" src="https://user-images.githubusercontent.com/84313603/146690696-9b449d1d-dd03-45de-bb9c-8033fe83d563.png">

**Comment by etherunit** [comment]
Has he tried to reboot his host machine?

1. Check if any TUN/TAP device is issue?
2. Try to load the TUN module manually `modprobe tun`
3. Tried to find whether any TUN related module is present in the kernel
`lsmod | grep tun
`
