### ISSUE TITLE
Linux install error (Unable to locate package myst)

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4495]
**Describe the bug**
install Myst on linux (i tried Debian 9 &10, Ubuntu 20.10) but i have an error when i type "sudo apt install myst":
E: Unable to locate package myst
and when I type "sudo add-apt-repository ppa:mysteriumnetwork/node", I have an error:
404 Not Found [IP: 2001:67c:1560:8008::19 80]

**To Reproduce**
1. Go to 'terminal'
2. Run 'sudo add-apt-repository ppa:mysteriumnetwork/node'
3. See error

**Comment by StrangerGithuber** [comment]
Do you have IPv6 IP address?

**Comment by networkscs** [comment]
Hi,
yes both. IPv4 and IPv6
Thanks

**Comment by isaackielma** [comment]
Myst nodes only support IPv4

**Comment by networkscs** [comment]
ok, so i need to disable IPv6 ?
Many thanks for your help

**Comment by networkscs** [comment]
I disabled IPv6 and when I type: "sudo apt-get update"

Hit:1 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu groovy InRelease
Hit:2 http://security.ubuntu.com/ubuntu groovy-security InRelease              
Ign:3 http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu groovy InRelease
Err:4 http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu groovy Release
  404  Not Found [IP: 91.189.95.85 80]
Hit:5 http://nova.clouds.archive.ubuntu.com/ubuntu groovy InRelease
Hit:6 http://nova.clouds.archive.ubuntu.com/ubuntu groovy-updates InRelease
Hit:7 http://nova.clouds.archive.ubuntu.com/ubuntu groovy-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mysteriumnetwork/node-mainnet/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by networkscs** [comment]
Hi,
Finally I managed to install Myst via Docker solution.
Many thanks
