### ISSUE TITLE
Withdrawn coins do not appear in my wallet (MyEtherWallet).

### ISSUE THREAD

**Issue by m11kessler** [mysteriumnetwork/node#4496]
Withdrawn coins do not appear in my wallet (MyEtherWallet). I selected the Polygon Mainnet option and MyEtherWallet address.

**Comment by etherunit** [comment]
Have you added MYST as a custom token to MEW list? https://medium.com/@williamazibaluaikiabo/step-by-step-guide-to-adding-bela-as-a-custom-token-in-myetherwallet-mew-5d8e7576cc86

**Comment by m11kessler** [comment]
Yes, I have added MYSY as a custom token.

**Comment by etherunit** [comment]
Have you added it on Polygon Matic chain or ETH?

**Comment by etherunit** [comment]
@m11kessler

**Comment by m11kessler** [comment]
Please clarify. I selected the Polygon Mainnet option during the withdraw process.

**Comment by etherunit** [comment]
Thanks.
Could you send us with your node identity and link to polygon tx (you can find it under wallet > transaction history.

**Comment by etherunit** [comment]
Closed due to inactivity.
