### ISSUE TITLE
Issue with Singapore

### ISSUE THREAD

**Issue by AdnanSayyed** [mysteriumnetwork/node#4497]
**Describe the bug**
With Singapore it's connecting for a long time with very slow data consumption, but after completing it ads 0 bytes

**Screenshots**
![image](https://user-images.githubusercontent.com/30722682/146495246-a965c330-94d0-4dca-bc20-ce686b758174.png)

**Environment (please complete the following information):**
 - Node version: mainnet (1.0.15-df8fc733)
 - OS: windows

**Comment by Donatas-MN** [comment]
Most probably it's consumer with very weak connection thus unable to start proper session. Shouldn't repeat too often though.
