### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by Mustgbolahan** [mysteriumnetwork/node#4498]
I transferred Ethereum and the Ethereum was successful but my wallet application deducted some amount from it and it was incomplete so I decided to transfer the amount of 0.000555 that was remained but unfortunately my crypto currency application can not send such a lower amount but I decided to increase it to 0.001 but unfortunately the payment was not successful and it shows 'dropped and replaced' on etherscan website. Please help I don't know what to do. Secondly I don't want to subscribe again and I want my payment for the first transaction that was successful and the second transaction that shows dropped and replace on etherscan website back please. This is the transaction hash for the first payment that wrote successful on etherscan website 0x0997e0dbef7031770016e26f6b5af02dacfc2a332c697df25bdfc8e8b8eed5f1
And this is the transaction hash that shows dropped and replace on etherscan website
0x487c9c9929ce5c0e9f98e5517e591545ab6ead95cc1205ed97c9c15a6acae100 
And this is the transaction ID of the first payment that was successful 10472510
And this is the transaction ID of second transaction that showed dropped and replace 10472715 or 10472783 because I tried again and I don't know which out of the two transaction
![Uploading Screenshot_2021-12-15-17-01-27-110_com.android.chrome.jpg…]()

**Comment by tomasmik** [comment]
Order 10472510 was underpaid by 0.000555ETH and no money has been transferred because of that. No other orders were paid.

Please raise an issue with support regarding your payment on possible compensation or refund.
