### ISSUE TITLE
Token migration

### ISSUE THREAD

**Issue by buybuybabe** [mysteriumnetwork/node#4501]
**Describe the bug**

Migration using etherscan (connected to metamask) or myetherwallet is not possible.

**To Reproduce**

Myetherewalllet:
1.start new stransation
2. Indicate 0 ETH
3. Update advanced with gas limit and generated payload data (from Myst site) 
4. Transaction not possible, red marked transfer amount 0, comment: invalid jump destination

Metamask
1. Open Etherscan
2. Write contract
3. Connect to metamask
4. under point 7. indicate MYST to be migrated
5. matamesk shows that transactio can be perforomed by paying some crazy gas fees (deviate from 7000 to 30000 $ depending on day) 

**Expected behavior**

I would like to be able to migrate my MYS tokens as it is described in MYST token migration guide

**Screenshots**

myetherwalleet issue:
![image](https://user-images.githubusercontent.com/96303351/146567883-ea66c880-e388-41c7-b9b1-969fad1e5606.png)

Metamask issue:
![image](https://user-images.githubusercontent.com/96303351/146567997-d49b3137-fb59-4bb1-b9fd-8f5a9bbdd7f9.png)

**Environment (please complete the following information):**
 OS xubuntu
explorer Chromium

**Additional context**
none

**Comment by tomasmik** [comment]
@chompomonim maybe you could comment in this?

**Comment by chompomonim** [comment]
Many people are successfully migrating tokens, but in some strange cases wallets are showing errors. It is hard to say what is reason without deep investigation (I newer had chance to reproduce it) but downgrading MetaMask to pre EIP1559 may help.

**Comment by buybuybabe** [comment]
Thanks for the answer, which version of pre EPI could work? 10.8.2, 10.7.1 etc?

My concern is that myether wallet also does not work.
