### ISSUE TITLE
Migration to Raspberry Pi

### ISSUE THREAD

**Issue by Frederic-Aguilar** [mysteriumnetwork/node#4503]
**Describe the bug**
Hi,
I was using Mysterium on an x86 small PC under Ubuntu 18.04 without any issue. I am behind a pfSense router with Suricata at home if it helps. NAT was configured and everything was green, traffic was coming thru.
Recently, I have migrated that PC to a Raspberry Pi 4B 4GB RAM under Raspbian Bullseye, all up to date.
The installation went without a hitch and once reconfigured the pfSense router, everything was back to green (Accepting Connections:
Most).

The problem is that I got 119 sessions from 37 unique clients without a few seconds of connection each time and 0 bytes transferred what so ever...

Here is a screenshot of the Web UI:

![Myst screenshot](https://user-images.githubusercontent.com/96323699/146626161-dd479e62-161d-4b5d-83b7-a20d290ee48e.png)

Node version: mainnet (1.0.14-b16259ef)
NodeUI version: 1.1.5

Do you have any idea of the origin of the issue?

Thank you in advance for your help.

Best regards,

Frederic Aguilar.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag

**Additional context**

**Comment by etherunit** [comment]
Hi @Frederic-Aguilar, we apologies for a delayed reply as it seems that this ticket was lost between our boards.
Do you still experience this issue?

**Comment by Frederic-Aguilar** [comment]
Hi,
I have just checked and it is still the exact same problem, many sessions, 0 bytes transferred, accepting most connections (green).

Thank you in advance for your help.

Best regards,

Frederic Aguilar.



Jan 12, 2022, 14:06 by ***@***.***:

**Comment by isaackielma** [comment]
Could you please attempt to update your node to the latest version 1.2.3 and let us know if that helps.

Looking forward to your response!
