### ISSUE TITLE
Linux failed to lookup host

### ISSUE THREAD

**Issue by StrangerGithuber** [mysteriumnetwork/node#4507]
Hello
I am using Ubuntu 21.04 and I tried with 20.04 too but I get the same errors.

I get these errors in the terminal:
![image](https://user-images.githubusercontent.com/1939827/146639244-44ae0888-5b75-4657-87fd-3d860a368beb.png)

I followed this instruction: https://mystnodes.com/onboarding/desktop/linux/0

The web ui works. I can reach everything but in the console I get the above messages.
Especially for pilvytis.mysterium.network 

Did I do wrong something or something bad with the node or I need to do something else too?

**Comment by StrangerGithuber** [comment]
I checked in the service status too and same
![image](https://user-images.githubusercontent.com/1939827/146654813-51899ab9-64d4-44a7-a07c-a7ec29f5c8f8.png)

I tried ping those domains and I can ping them however the node gives me error.

I added also in additional new nameservers too:
```
1.1.1.1
1.0.0.1
8.8.8.8
8.8.4.4
```

**Comment by etherunit** [comment]
Could you specify your node identity?

**Comment by etherunit** [comment]
@StrangerGithuber
