### ISSUE TITLE
Accidentally sent MATIC coins to the default withdrawal address. Was successful but now I dont have access to my coins.

### ISSUE THREAD

**Issue by thomaszwei** [mysteriumnetwork/node#4510]
Hi, I sent MATIC coins from my metamask app to the default withdrawal address on my mystnode. The withdrawal was successful but now I dont have access to my coins. I wanted to swap it first into myst coins and then send it. What are my options to get access to the coins again?
Thanks in Advance

**Comment by etherunit** [comment]
Unfortunately, there is no way to retrieve your tokens. It's irreversible action. Please note that Polygon MYST should be sent to your identity channel address, sending any other token will result in loss.

**Comment by thomaszwei** [comment]
Ty for that quick response. I understand, my mistake to send wrong tokens.
