### ISSUE TITLE
Refactor consumer affiliates

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#4517]
Current consumer affiliates are held inside our transactor services. However transactor is meant to proxy users transaction for some MYST fee, not deal with affiliates.

Before doing task: https://github.com/mysteriumnetwork/mmn/issues/110 we should refactor the consumer affiliates out to a new service so that we could combine consumer and provider affiliates together.

* [x] Refactor the DB layer
> Move the current database logic to another service. Move it in such a way where we could easily add provider affiliates later, without having to again change the schema.
* [x] Implement the API to control both provider and consumer affiliates.
> Again most of the API is in transactor itself. API is used in universe to interact with affiliates codes and affiliates themselves.
* [x] Transactor should call the new affiliate service when a consumer is registering with an affiliate token
> Transaction should no longer check it's database but rather check the reward amount needed for the token and if its valid with the service, if the user registers, transactor should notify that service, saying that hey this user registered with this code, you can now start calculating data for him.
* [x] Node should now also call the new affiliate service for consumer workflow
> Node pretty much only cares to validate that the token is valid
* [x] Refactor out the affiliate tree submission to the new service and submit both the consumer and provider rewards
> Before launching this, old affiliate service should be killed.
* [x] Affiliates UI should point to the new service too
* [x] Data should be migrated from old service to the new one

**Comment by Guillembonet** [comment]
- [ ] copy this https://github.com/mysteriumnetwork/pilvytis/blob/master/server/middleware/resp.go#L57 and make proper, typed errors which can be understood by the front end

**Comment by Guillembonet** [comment]
closing this, deployment rollout will have its own issue mysteriumnetwork/affiliator#6 as it will happen over time (probably a week or so as I keep checking that everything works fine and give it time to let it sync properly)
