### ISSUE TITLE
Node balance does not refresh after successful withdrawal

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4520]
Steps to reproduce:
1. Do a withdrawal to Polygon chain.
2. Check if withdrawn amount arrived to destination.
3. Balance stays the same like before withdrawal.

Looks related: https://github.com/mysteriumnetwork/node/issues/4459

**Comment by tomasmik** [comment]
```
{"level":"error","error":"error during promise settlement: handler failed to send transaction: nonce too low","chain_id":137, ---SNIP --- "message":"could not settle promise"} 
```

hermes locked up with a nonce too low error and was literally dead for a 2.5days. A restart has fixed the problem. I plan to fix it for good with the new payments API I've implemented here: https://github.com/mysteriumnetwork/payments/pull/159

Closing this issue as we'll get to this eventually when completing the rework of payments.
