### ISSUE TITLE
View all sessions only showing first page ver 1.0.17 and 1.0.18

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#4527]
Never noticed if it was doing this before but now when using the page selectors at the bottom,it only shows the first page of session history and the buttons are doing nothing?

**Comment by etherunit** [comment]
If you have more sessions than allowed by pager, you should be able to navigate through history by clicking buttons.
Could you share me with your screenshot?

**Comment by rmtucker** [comment]
![Screenshot from 2021-12-24 18-24-00](https://user-images.githubusercontent.com/6954079/147368673-68fe5df6-c55f-4510-aeb4-687f89db5fff.png)
Pressing the buttons at the bottom does nothing and it says there are 40 pages?
But i can only see the first page.

**Comment by etherunit** [comment]
This is a known issue (more reports around it). Passing back to NH team for further troubleshooting and fixes.

**Comment by Donatas-MN** [comment]
The same as https://github.com/mysteriumnetwork/node/issues/4539.

**Comment by Loggsie** [comment]
Can confirm this affects my Debian v.1.0.18 too, came here to report just that 😀

**Comment by etherunit** [comment]
Pagination should be working with latest NodeUI version 1.4.2. Please update your node.

**Comment by Loggsie** [comment]
Can confirm working with 1.1.3
