### ISSUE TITLE
Getting a 10 second session every 1 minute from Brazil

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#4528]
Suddenly getting a 10 second session repeatedly every minute from brazil.
Just started tonight on ver 1.0.18
See pic and end of todays logs.
![Screenshot from 2021-12-22 19-39-30](https://user-images.githubusercontent.com/6954079/147148010-fbd9dfbd-f573-4fdd-b996-4d9c7b8739b5.png)
[node.logs.zip](https://github.com/mysteriumnetwork/node/files/7764907/node.logs.zip)

**Comment by etherunit** [comment]
Thanks for adding logs. For all Brazil sessions I'm seeing the same error:

Dec 22 19:34:31 raspberrypi myst[719]: 2021-12-22T19:34:31.339 DBG session/pingpong/invoice_tracker.go:275  > Starting...
Dec 22 19:34:31 raspberrypi myst[719]: 2021-12-22T19:34:31.341 DBG session/pingpong/price_calculator.go:52  > Calculated price 23297723. Time component: 2.329772395079578327e+07, data component: 0. Transferred: 0, duration: 0.000165208. Price 507674000186824/h, 91381320033628320/GiB
Dec 22 19:34:31 raspberrypi myst[719]: 2021-12-22T19:34:31.342 DBG session/pingpong/invoice_tracker.go:466  > Being lenient for the first payment, asking for 1
Dec 22 19:34:31 raspberrypi myst[719]: 2021-12-22T19:34:31.343 DBG session/pingpong/invoice_messaging.go:57 > Sending P2P message to "p2p-payment-invoice": AgreementID:"17805958155051774477006936690134011734640467624508066765487297497168746975060"  AgreementTotal:"1"  TransactorFee:"0"  Hashlock:"e9d3dad4cf453767337f41a27ea738f5045e6bc2cc0d3e3a82dc90ff35e2fa92"  Provider:"0x3529b0ebdbdd536074de9c25f17151de62cff8cd"  ChainID:137
`Dec 22 19:34:41 raspberrypi myst[719]: 2021-12-22T19:34:41.345 ERR core/service/session_manager.go:327      > Payment engine error error="could not send first invoice: timeout waiting for reply to \"p2p-payment-invoice\": p2p send timeout"`

It seems that consumer tried but failed to pay invoice, thats why he got disconnected many times.

**Comment by etherunit** [comment]
Closed due to inactivity.
