### ISSUE TITLE
Support chat a bot?

### ISSUE THREAD

**Issue by jkimmel** [mysteriumnetwork/node#4532]
*I don't whether this is a bug  or a feature.

Because there had been no response from the support chat (usual reply time = 1 day) I asked:

Already startet into holydays?

I expected: Yes or no or some declaration

But I was asked:

Hello ﻿﻿Thanks for reaching out!﻿﻿I am sorry to hear about this inconvenience. Are you still experiencing this same issue?

**Comment by tomasmik** [comment]
Bot is not that smart I guess. Not a bug though and it's not made by us either. It works good enough even if sometimes a bit confusing.
