### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by jkimmel** [mysteriumnetwork/node#4535]
I got stuck while registering a new node with error:

`» [ERROR] Could not register identity: server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/identities/0x46307a7b05ccaefcdc0f95814c60a9b3de60bf43/register). Possible error: failed identity registration request: server response invalid: 400 Bad Request (https://transactor.mysterium.network/api/v1/identity/register){"error":"registration in progress"}
`

**Comment by jkimmel** [comment]
@etherunit 
You considered it as low level but I can't install a node
For me it's not above money but to join the movement

**Comment by tomasmik** [comment]
Try it now. Some minor issues were resolved.

**Comment by jkimmel** [comment]
In the meantime a installed a node without problems on a different Raspi.
