### ISSUE TITLE
Allow export of transactions from Web UI

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#4536]

**Comment by tomasmik** [comment]
What transactions? Withdrawals? You can already do that on polygonscan or etherscan

**Comment by Jayto1** [comment]
> What transactions? Withdrawals? You can already do that on polygonscan or etherscan

All transactions node related for people paying taxes on their earnings or just trying to track them would be great. Polygonscan and Etherscan show **all** transactions for MYST, this could contain transactions unrelated to your node and thus would make it very hard to export just your node-related earnings.

**Comment by Donatas-MN** [comment]
@Jayto1 coming soon with this one: https://github.com/mysteriumnetwork/node/issues/4521

**Comment by Jayto1** [comment]
> @Jayto1 coming soon with this one: #4521

Perfect.
