### ISSUE TITLE
[Feature Request] Allow export of private key from default payment channel

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4538]
It would be great to export the payment channels private key so it can be used on other wallets as well instead having to manually transfer proceeds out.

**Comment by tomasmik** [comment]
Will not be implemented. [Thats just not how the protocol works](https://github.com/mysteriumnetwork/payments-smart-contracts/blob/master/docs/paper/accountant-pattern.pdf).

There are changes coming for withdrawals, were you will be able to make automatic withdrawals to your own wallet every 0.1 or so MYST.
