### ISSUE TITLE
VPN app backup with CLI does't work correctly

### ISSUE THREAD

**Issue by lusine-h** [mysteriumnetwork/node#4544]
**Describe the bug**
During the VPN app identity Backup process (via CLI), after exporting identity it saves a file without json format, but in the case of importing lets to select only json files. It doesn't do import via CLI even if I change the file format to json manually.

**Preconditions**
Registered identity in the VPN app

**Steps to reproduce the behavior**
1.  Export identity via CLI
2.  Remove user data for VPN app
3.  Change exported file format to json
4.  Import identity via CLI

**Expected behavior**
Identity is imported correctly via CLI.

**Actual behavior**
The import identity command returns an error.

**Environment**
 - OS: Ubuntu 20.04
 - Desktop app version:  10.1.0
 
**Additional context**
Export identity command should save json file and should import identity correctly.

**Comment by Donatas-MN** [comment]
@tomasmik will check this.

**Comment by tomasmik** [comment]
```
» identities export 0xca967e4276d02f2e4037396206a03ba92f51122e  123 /home/tomas/export.json
[SUCCESS] Identity exported to file: /home/tomas/export.json
» ^C
tomas@pop-os:~/go/src/github.com/mysteriumnetwork/node$ cat /home/tomas/export.json
{"address":"ca967e4276d02f2e4037396206a03ba92f51122e","crypto":{"cipher":"aes-128-ctr",.....
---- SNIP -----
```

![image](https://user-images.githubusercontent.com/40318863/148925487-0ed150bc-1c92-46f6-8449-29ff6358af58.png)
