### ISSUE TITLE
My Nodes won't show online in Dashboard, but saying registered

### ISSUE THREAD

**Issue by darkman1983** [mysteriumnetwork/node#4547]
**Describe the bug**
I have registered two Nodes, one at home on a RasPi in a docker Container.
The ohter on a VPS in a docker container.

**To Reproduce**
Simply gone through the Docker install Guide, but set network-mode to host, as it's better.

**Expected behavior**
My two Nodes showing as online and also "Last seen" is not never.

**Screenshots**
<img width="1057" alt="MystNodeExplorer" src="https://user-images.githubusercontent.com/553212/147675222-974979a9-199c-4487-8d72-4587d2b11994.PNG">
<img width="1837" alt="MystVPSNode" src="https://user-images.githubusercontent.com/553212/147675223-36a4afd5-5b78-41c0-9b24-5f3a892844b8.PNG">
<img width="1854" alt="MystHomeNode" src="https://user-images.githubusercontent.com/553212/147675225-3e7e6fd5-830f-4fc2-9a19-690a685bcba9.PNG">

**Environment:**
 - Node version: 1.0.18
 - OS: Raspbian (home) / Ubuntu 20.04.3 LTS (VPS)
 - Docker: 20.10.11, build dea9396 / 20.10.12, build e91ed57

**Additional context**
My VPS Node is showing "Monitoring failed" -> https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&provider_id=0x8f7d47da301708d6258794dc4335444423c783bc
For my home Node all seems to be ok -> https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&provider_id=0x4722ae75bdfbba9859731193738fc4bf5ae02daa

I reregistered multiple times to no success, they're not showing up in the dashboard.
I also let a friend of mine test this out on his side, but for him all is working as expected.
We're both from Germany.

Any ideas?

**Comment by darkman1983** [comment]
Thanks for seeting this to low prio lol
Is this a display bug only?
Are my Nodes working correctly, so i don't loose any potential income?

**Comment by darkman1983** [comment]
One of my Nodes turned online after 1 Day, but last seen is 10 hours now?!
I read somewhere that the healthcheck runs every 6 hours?
Can't see any logic in this :-D

**Comment by darkman1983** [comment]
Btw. running 2 Days now and only got one Session with 290MB on my Home-Node.
The VPS Node got 6 Session of 5 seconds each with only a few KB...
So for me it seems, that there's a actual problem, because i'm not getting any real Connection with 1 MB+ transfered.

**Comment by adinetech** [comment]
Do `sudo iptables-save output`

**Comment by adinetech** [comment]
Check whether your's shows the same

`*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]`

**Comment by darkman1983** [comment]
I think the documentation is misleading here: https://docs.mysterium.network/node-runners/setup/docker/

It said:
`docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node mysteriumnetwork/myst:latest service --agreed-terms-and-conditions
`
But that brouhgt me some problems:
1. In the logs for the node it's complaining about the tun device not found
2. Why do i need bridge network, when there could only be one node per IP? Host or macvlan would be better
2.2 UPNP Portforwarding is workin with this
3. You have to dig even further to find the sugestion of lowering the UDP Portrange (in Node UI) from standard 10000:60000 to eg. 60000:62000 or so.
3.3 When the suggestion is lowering, why is the standard for the Node 10000:60000, when we prefer residential Nodes, who would need that much portrange for a home node?

So i adjusted accordingly:
`docker run --cap-add NET_ADMIN --net host --device /dev/net/tun -d  --name myst -v myst-data:/var/lib/mysterium-node mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`

After another half day the nodes showed online for me.
