### ISSUE TITLE
Transactor should swap MYST for MATIC

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#4549]
Myst is now available on Uniswap V3 in the polygon network: https://info.uniswap.org/#/polygon/pools/0x54b7707579df82b3ca2079b415c4c2ff77463154

We should be able to just swap the MATIC tokens we need using this, instead of relying on topperupper.

**Comment by Donatas-MN** [comment]
Quickswap could be also considered as an alternative if needed.

**Comment by tomasmik** [comment]
It now does
