### ISSUE TITLE
is there any chance to sort nodes list by ping/location around you?

### ISSUE THREAD

**Issue by AndriusMyst** [mysteriumnetwork/node#455]

**Comment by tcharding** [comment]
Hi @AndriusMyst would this be any good to you #476.  It doesn't sort the output but it allows you to filter it so you can do
```
» proposals SG
2018-10-23T05:59:50.896303068 [Info] [Mysterium.api] Proposals fetched: 41
[INFO] Found 41 proposals (filter: 'SG')
[INFO] - provider id: 0x44ceda7262fcc48d591ee468c8a7319585d51aee, proposal id: 1, country: SG
[INFO] - provider id: 0xeed4ee266b2175a7f4063ecd59eef414b60f9d1d, proposal id: 1, country: SG
[INFO] - provider id: 0xf03f364719d09b37260872735c113baaee4f4f1a, proposal id: 1, country: SG
```
Hope this helps

**Comment by zolia** [comment]
This probably will not help much for application team, since they need this functionality through tequilapi (REST endpoints). We have Endpoint `/proposals?fetchQuality=true` within #429 for this case already.
