### ISSUE TITLE
MYST Totals not calculated for all pages

### ISSUE THREAD

**Issue by Durfduivel** [mysteriumnetwork/node#4550]
I noticed just now that the total earnings are not total for all nodes but this is a total for each page of 100 nodes.
Can you fix this so it will calculate total MYST for all nodes (not for each page)?

Also it would be very good if the Nodes are numbered (and stay on the same spot, they now move around). If that is not easy than please make the pages be 20 Nodes each (not 100 like now).

If you want to have more information, please contact me on Discord Amin Idris#5655

**Comment by ikolubr** [comment]
I would add the option to set a name for each node. So we could name them in a way that would make sense to us.

**Comment by Donatas-MN** [comment]
Renaming is coming very soon!

Regarding calculating total MYST for all nodes, we have it in backlog. I hope we can do the improvement soon.

**Comment by Durfduivel** [comment]
@Donatas-MN you closed this but you didn't write if you have done the feature request about renaming (I know that it has been made but you should write that in here). And my issue about wrong calculation of MYST for all nodes I don't see that this is fixed but still you closed this issue.
