### ISSUE TITLE
[android] connection gets into OnHold state after 10 minutes

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4553]
**Describe the bug**
10 minutes after connecting, connection goes into OnHold state.
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7795880/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.0.14
 - OS: Android

**Comment by tomasmik** [comment]
From logs the initial impression is that the internet connection just isnt that stable.

**Comment by cvl** [comment]
Another one (Windows):
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7801048/mysterium-node.log)

**Comment by cvl** [comment]
x
