### ISSUE TITLE
Withdrawing MYST but didn't recive any

### ISSUE THREAD

**Issue by Droghyz** [mysteriumnetwork/node#4557]
The 27/12/2021 at 12:00 i withdrawed 0.6~ MYST from my node, but nothing arrived yet.
Before clicking on Withdraw i checked on the Settings if "Default Withdrawal Address" was correct (and it was) and i also checked before pressing the withdrawal.
I then checked my other node (residential) and i saw on the new added nodeUI feature "wallet" different transaction with the same beneficiary 0x000...00.

1) First withdrawal from the node
Node ID: 0xfe142d129cc1e4f033f41f694cff1de3bfa84f7e
Trx ID: https://polygonscan.com/tx/0xf97378a0c9af18110c7094afcf5ffedf62af5cb7136be58808fa286d4fab78f6
My Wallet: 0x90e607BD380F33DcCB09Ed2e96D5E6853AE3FE9d
![1withdrawal1](https://user-images.githubusercontent.com/11157670/147820518-6f9625ca-9c02-465e-a2c5-f951456a6ee2.png)

2)Residential node with strange transactions
Node ID: 0x4611360443b4cb233b2f8221d8f93b06146226b4
Trx IDs: 
18/12: https://polygonscan.com/tx/0xcab3c598a5a033098af8c9f7df3eab4296c5ee1913466842ae9b1d350c92b1e2
21/12: https://polygonscan.com/tx/0xa5582d600715b2ed3f2403142af55e33d9d1789a15f4f44f4836a22ed6259f50
27/12: https://polygonscan.com/tx/0xd2d00cc69ec9c63a478bb288718b83e4a09e07ddb387378c1009bbfdf5e0e7c1
30/12: https://polygonscan.com/tx/0x919d5fa23bb496c1db07a47851ac6b7fcda9c99855796131c0fbc03057dd79da
31/12: https://polygonscan.com/tx/0x1d09afc6fcb88eb002942c474ba8763d50273d1e7c35e19daee24ca466c338dc
31/12-2: https://polygonscan.com/tx/0xfc31197840f089bbecb563b9aff679a7de6ea8cbf5e593465b2677d472674f1f
My Wallet: 0x90e607BD380F33DcCB09Ed2e96D5E6853AE3FE9d
![2residential](https://user-images.githubusercontent.com/11157670/147820637-efb523f5-b05f-42fb-a3be-d3d7696a762e.png)

**Comment by tomasmik** [comment]
For the first case your money that you tried to withdraw never left your channel, you can see it here: https://polygonscan.com/address/0xe11049ca60FA24FC10D6bA6C92321907D77EAbA3

There are cases when this fails and we're working on eliminating them. There should be new changes deployed in the upcoming week. Meanwhile that MYST is not gone and it will either we eventually settled and sent to you or you will receive that + extra the next time you withdraw, sorry for the trouble.

**Comment by Droghyz** [comment]
What about the second case? for the residential node?
I never withdraw anything from that, but still the beneficiary is 0x000..00 and not my wallet address

**Comment by Donatas-MN** [comment]
> 

These are internal settlement transactions when your Unsettled earnings are settled to withdrawable Balance. We're going to add transaction type and some tooltips with explanations soon, so it's more clear.
