### ISSUE TITLE
Can not import backed up identity

### ISSUE THREAD

**Issue by MarkWieczorek** [mysteriumnetwork/node#4560]
I am trying to import an identity that I previously backed up with a password, but it doesn't work when using `sudo myst cli` on a Raspberry Pi. To demonstrate this, I reinstalled everything. Then I exported the identity that was created, and then tried to import it. As you can see, I get an error. (I get the same error when imported my backed up identity as well.)

```
» identities list
[+] 0x........
» identities export 0x......... test-pass
[SUCCESS] Private key exported:
{"address":"......,"version":3}
» identities import test-pass {"address":"......,"version":3}
[ERROR] Failed to import identity: server response invalid: 400 Bad Request (http://127.0.0.1:4050/identities-import). Possible error: failed to import identity: invalid character 'a' looking for beginning of object key string
»
```

This is obviously a major problem.

**Comment by Loggsie** [comment]
Looks like an issue with the port number the CLI request is using. 

When you installed the node package onto the RPi did you specifically request for port 4450 to be used instead of 4449?

**Comment by MarkWieczorek** [comment]
No. I didn't change anything. I just installed everything on a new card, so there aren't any old config files lying around.

I did find a hack as a temporary fix: I created a file with "{"address":"......,"version":3}" and then tried to import using a filename (as opposed to text string from the cli). This worked, so it appears to me that the cli interface parser doesn't work as it should.

**Comment by etherunit** [comment]
@lusine-h Have you received the same testing result as mentioned by @MarkWieczorek ?

**Comment by etherunit** [comment]
@lusine-h any updates?
