### ISSUE TITLE
Force use of and/or enable https access for node GUI

### ISSUE THREAD

**Issue by Loggsie** [mysteriumnetwork/node#4561]
Currently if you're running a node on a VPS your password is submitted in plain text when accessing the node GUI. 

This is a security risk if your connection were to be eavesdropped. Without your knowledge, your withdrawal address could be altered.

The only current suitable workaround is to VPN into the host. 

I would like to see a forced redirect to https protocol with a self signed certificate. 

As a bare minimum the option to use http and https interchangeably.

**Comment by tomasmik** [comment]
Working on it https://github.com/mysteriumnetwork/node/issues/2041
