### ISSUE TITLE
Mysterium Identity registering process will not complete

### ISSUE THREAD

**Issue by prestinem** [mysteriumnetwork/node#4562]
The identity registering process is countinuing for weeks. I keyed in my node's ip address in the web browser so that I could complete the registering process, :4449, login credentials and the process has not finished he regtistering process since and countinues to mention that that registering process is still happening. The page reads "Your identity is being registered, please be patient..."
It will not allow me to start the process over again so that I can attempt options.

Assistance would be greatly appreciated.

Thank you!

<img width="1431" alt="166 screen Shot 2021-12-26 at 8 52 28 AM" src="https://user-images.githubusercontent.com/96850828/147863212-cb225adb-725e-46a1-aafb-cb18380e8920.png">
<img width="1434" alt="29 59 Screen Shot 2021-12-26 at 8 49 56 AM" src="https://user-images.githubusercontent.com/96850828/147863214-fbb00820-09f9-4b56-85c2-fa2c2db8e398.png">
<img width="1424" alt="183 screen Shot 2021-12-26 at 8 53 23 AM" src="https://user-images.githubusercontent.com/96850828/147863215-5bd2929e-2540-492a-bf94-06af5dbb9caa.png">

**Comment by etherunit** [comment]
Could you please copy paste your identity here? 
Alternatively, you can register your identity via terminal. 

Run the commands listed below (restart your host/node in advance):

```
identities unlock [your-node-id-here]
identities register [your-node-id-here]
```

**Comment by prestinem** [comment]
Hello and thank you for your expertise. 

I truly appreciate it.

Do you mean paste my node id here?

I just want to make sure. Thank you very much.

**Comment by etherunit** [comment]
Yep, if possible.
Have you tried to re-register your node?

**Comment by prestinem** [comment]
Thank you for your response. I did not want to make a mistake because I
want to make sure.
Would my node id be the ip address and :4449 ?


PRESTINE MANDERVILLE JR.
CEO, Color Star Media
Director, Director Of Photography, Videographer, Video Editor, Live Stream
Operator
colorstarmedia.com
***@***.***
704-351-8483

This message (including any attachments) may contain confidential,
proprietary, privileged and/or private information. The information is
intended to be for the use of the individual or entity designated above. If
you are not the intended recipient of this message, please notify the
sender immediately, and delete the message and any attachments. Any
disclosure, reproduction, distribution or other use of this message or any
attachments by an individual or entity other than the intended recipient is
prohibited.

**Comment by prestinem** [comment]
Also, would I use putty to input the node id?

**Comment by etherunit** [comment]
That is correct. Please check it here: https://docs.mysterium.network/node-runners/node-ui/#how-to-login

**Comment by etherunit** [comment]
Yep, you can use Putty or any other command-line based tool. Alternatively, the registration could be re-tried within NodeUI window.

**Comment by prestinem** [comment]
Hello, I was unable to fix this issue. I have provided my identity below.
Could you please assist me?

144.202.29.59:4449
104.156.247.166:4449
108.61.245.183:4449

Thank you

**Comment by gozno8** [comment]
I have had luck fixing the stuck register WebUI screen by using the "myst cli" command within an ssh session, while in the "myst cli" command do a "identities list" to get the channel id, "identities unlock (channel id here)", "identities get (channel id here)".  Upon completing the "identities get (channel id here)" I watched the stuck web page for registration change over to the normal WebUI.  I've done this on 20+ node runners like this.  This was prior to version 1.2.2.
