### ISSUE TITLE
Node Status Reading Test Failed

### ISSUE THREAD

**Issue by mtcoats** [mysteriumnetwork/node#4565]
**Describe the bug**
A clear and concise description of what the bug is:

My Mysterium node launcher displays that the node and docker are both online, but when I enter the Node UI it states that the Node Status as "test failed"

In the "My Nodes" interface it is listed as "Offline"

I believe the issue occurred after updated to version 1.0.24

**To Reproduce**
1. Lauch Mysterium Node Launcher.  Mysterium and Docker read as online
2. Log into Node UI status reads Test Failed
3. Log into My Nodes Status Reads Offline

**Expected behavior**
The node to read online and be online

**Screenshots**

![Screenshot 2022-01-02 204348](https://user-images.githubusercontent.com/97010129/147900223-c28b7558-22f7-418f-a9a0-8bd2c2f034a9.png)

![Screenshot 2022-01-02 204450](https://user-images.githubusercontent.com/97010129/147900264-835479f1-a038-4a23-b182-b1a0bbec2db3.png)

![Screenshot 2022-01-02 204644](https://user-images.githubusercontent.com/97010129/147900344-4e34d47c-00da-4eb5-a48e-a84bc5ddf9a8.png)

**Environment (please complete the following information):**
 - Node version:1.1.1
 - OS: Windows 10/Docker/Alpine Linux
 - Desktop app version 1.0.24
 - Docker image ID: 79d4a1f6451f

**Comment by etherunit** [comment]
Please provide us with your node identity and docker log output (from within console or by running `docker logs myst`). Thank you!

**Comment by mtcoats** [comment]
Hello

My Node ID is

0x0731346225fb7285d4d09a9687cbeb99308f19eb

Here is a screen shot of my docker log, it appears to be blank? Am I not in the correct place for the log?



The node launcher still shows docker being online

**Comment by etherunit** [comment]
Can you please re-attach the screenshot? Unfortunately, I'm not seeing it.

**Comment by etherunit** [comment]
1. Login to your Node UI and click the "Bug" button on the left side panel.
or
2. Report issue directly to Mysterium support using API service: `curl -X POST --data '{"email":"your_email@gmail.com"}' localhost:4050/feedback/issue`
