### ISSUE TITLE
Unsettle balance is always 0 , not getting any reward

### ISSUE THREAD

**Issue by AdnanSayyed** [mysteriumnetwork/node#4567]
**Describe the bug**
Balance is not increasing even sessions are done and earned some MYST coins
unsettle balance should increase but it is always 0

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/30722682/147916891-f15287ef-151f-47f1-83a6-719754068a39.png)
![image](https://user-images.githubusercontent.com/30722682/147916965-3308a5da-c682-4813-9a9f-387d9b6bb003.png)
![image](https://user-images.githubusercontent.com/30722682/147917103-6ed39d6d-8fa4-4d5c-b922-8e0765728c71.png)

**Environment (please complete the following information):**

![image](https://user-images.githubusercontent.com/30722682/147917247-aeec37f9-65cc-4a94-b4e4-3b133b1d5b6e.png)

**Additional context**

**Comment by tomasmik** [comment]
Please provide your identity

**Comment by adinetech** [comment]
@AdnanSayyed

**Comment by AdnanSayyed** [comment]
> Please provide your identity

0xc6bbb96ec18b390bf48924635001a00a4f57d113

**Comment by adinetech** [comment]
@tomasmik

**Comment by Donatas-MN** [comment]
@AdnanSayyed can you try to update your node to newest version and then reboot it?

**Comment by AdnanSayyed** [comment]
![image](https://user-images.githubusercontent.com/30722682/148914906-42e7f757-e77e-4b99-ad54-736f1e0f812e.png)
my versions
now sometimes balance is updated but most of the times its 0

**Comment by Donatas-MN** [comment]
When did you start running node? I mean on which date approx?
