### ISSUE TITLE
Registered identities reported as failed by transactor

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4568]
It seems that successfully registered node identities are being reported as failed by transactor. 

e.g. https://transactor.mysterium.network/api/v1/identity/0xd385cf7eba140e82117f25d89d430112953c8430/status
https://transactor.mysterium.network/api/v1/identity/0x33fa2cb2d61c858a11b5d6848e4373793c4de385/status

I've requested agent to check on of them and test did passed.
<img width="788" alt="Screenshot 2022-01-03 at 11 18 32" src="https://user-images.githubusercontent.com/60128746/147922360-733b9816-dc06-4ea7-a905-709521107632.png">

However, no proposals are displayed on discovery (null) https://discovery.mysterium.network/api/v3/proposals?provider_id=0xd385cf7eba140e82117f25d89d430112953c8430/status

**Comment by etherunit** [comment]
Any updates @tomasmik ?

**Comment by tomasmik** [comment]
should be solved with the latest changes done to registration and transaction flow.
