### ISSUE TITLE
Page 1 is the only sessions list page that works

### ISSUE THREAD

**Issue by Jayto1** [mysteriumnetwork/node#4570]
**Describe the bug**
Sessions list not showing anything other than page 1

**Expected behavior**
Clicking on any page that's not page 1 doesn't show any new info

**Environment (please complete the following information):**
 - NodeUI version: 1.2.1

**Comment by etherunit** [comment]
It's a known issue. Fix is already present in 1.4.2 NodeUI

**Comment by Jayto1** [comment]
> 

Thanks, etherunit, closing this issue now.
