### ISSUE TITLE
MYST Tokens are not showing up in the client

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4571]
**Describe the bug**
Paid tokens are not showing in the app after x hrs of waiting time.

```
CoinGate Order ID #10699235
088dd2c5fd32818ef8617250ce32e31a0814026923243498799644f6a147b374
```
**To Reproduce**
1. Go to Top Up screen;
2. Select the amount of MYSTs to top up and click Next;
3. Select Payment method and click Next;
4. Select the cryptocurrency or payment currency to pay with and click next;
5. Continue to pay; Confirm the payment;

**Expected behavior**
Paid tokens are allocated into the dVPN app balance;

**Screenshots**
<img width="357" alt="Screenshot 2022-01-04 at 09 56 20" src="https://user-images.githubusercontent.com/60128746/148029488-f20db618-ebc1-4706-b472-11d462ca5498.png">
<img width="345" alt="Screenshot 2022-01-04 at 10 19 29" src="https://user-images.githubusercontent.com/60128746/148029658-745ad31d-a3c1-4fd5-a127-7650dfdf29ad.png">

**Environment:**
 - OS: Windows10
 - Desktop app version: 10.3.0

[main (2).log](https://github.com/mysteriumnetwork/node/files/7806275/main.2.log)
[renderer (2).log](https://github.com/mysteriumnetwork/node/files/7806276/renderer.2.log)
[myst_supervisor (3).log](https://github.com/mysteriumnetwork/node/files/7806285/myst_supervisor.3.log)
[mysterium-node (9).log](https://github.com/mysteriumnetwork/node/files/7806365/mysterium-node.9.log)

**Comment by Strike9999** [comment]
https://pay.coingate.com/invoice/ce1b532a-5957-4583-8497-1d46913723da pelase fix

**Comment by adinetech** [comment]
![telegram-cloud-photo-size-4-5954311105058813441-y](https://user-images.githubusercontent.com/68943180/148046341-1985a11e-04ae-42aa-a050-422fcd831f62.jpg)

`CoinGate Order ID #10698078`

The user reported to me that the top-up failed and unable to get the Mysterium ID.

**Comment by Ilyas039** [comment]
![Screenshot_20220104-032655_One UI Home](https://user-images.githubusercontent.com/97092685/148049779-34d4ee93-a7c4-4387-80a4-aa9303ffc5eb.jpg)
![Screenshot_20220103-204824_Chrome](https://user-images.githubusercontent.com/97092685/148049811-5b0c1e59-afb6-48b5-ad6e-1fbea9461d52.jpg)
![Screenshot_20220103-200238_Drive](https://user-images.githubusercontent.com/97092685/148049830-80034d52-64f6-484f-bfdd-b7fbefaaa4d1.jpg)
 
My account not open

**Comment by Strike9999** [comment]
![image](https://user-images.githubusercontent.com/94880282/148057667-f7420bc9-828c-4112-9989-5a64b24042c3.png)
![image](https://user-images.githubusercontent.com/94880282/148057691-12fe7cac-1a22-483d-9818-13d96263a771.png)
https://pay.coingate.com/invoice/ce1b532a-5957-4583-8497-1d46913723da

**Comment by Ilyas039** [comment]
Not work
give me file .json

**Comment by Ilyas039** [comment]
My problem I paid Bitcoin and the account did not work for me, is there a
solution?

**Comment by Strike9999** [comment]
pls fix my account

**Comment by darkman1983** [comment]
After restaring the dVPN app today my tokens arrived and all works now. Thanks!

**Comment by Ilyas039** [comment]
> ![telegram-cloud-photo-size-4-5954311105058813441-y](https://user-images.githubusercontent.com/68943180/148046341-1985a11e-04ae-42aa-a050-422fcd831f62.jpg)
> 
> `CoinGate Order ID #10698078`
> 
> The user reported to me that the top-up failed and unable to get the Mysterium ID.

 Any solution ?

**Comment by etherunit** [comment]
A few users confirmed that tokens were successfully received. Please try to reboot PC/app as it might help you.

**Comment by Ilyas039** [comment]
tested no work any solution?
![Screenshot_20220103-200238_Drive](https://user-images.githubusercontent.com/97092685/148213353-6f706ded-d984-47e2-8c97-07489cab02d0.jpg)

**Comment by Ilyas039** [comment]
![Screenshot_20220105-065334_One UI Home](https://user-images.githubusercontent.com/97092685/148213568-a60635c6-c7a6-45a3-97fc-3ba869b8ae18.jpg)

**Comment by Ilyas039** [comment]
Any solution? Or refund my money

**Comment by tomasmik** [comment]
There were issues with payments being late due the Polygon network congestion. We've managed to solve that issue and everything should be working as expected now. Please close the app complete and open it back up if you didnt finish your registration and you should be fine.

**Comment by Ilyas039** [comment]
No work 
![Screenshot_20220105-130559_One UI Home](https://user-images.githubusercontent.com/97092685/148266921-75d8347e-4789-4eed-bb76-e3bc92bc7db6.jpg)

**Comment by Donatas-MN** [comment]
@Ilyas039 still didn't arrive? If not, go to Profile and send us your Mysterium Identity Address.

**Comment by Ilyas039** [comment]
It's working.  Thanks

**Comment by Donatas-MN** [comment]
Thanks for confirming!
