### ISSUE TITLE
MYST reward went back to senders address instead of my withdrawal address

### ISSUE THREAD

**Issue by mrgupe** [mysteriumnetwork/node#4573]
Hello, I have withdraw my MYST but they gone missing one withdraw was ok but rest of them disappeared same as all MYST from balance
I have found transactions I withdraw to my address but somehow it went to senders address where they came from https://polygonscan.com/tx/0x26c2e2e7059b325f4fad4b8447f60803653a10fe4b7a0e4f35d319b1cf87cca8
https://polygonscan.com/tx/0x474f40c2ce6e89bbcf81b519f975de28a8ba1ab6812dff5513959285d286380d
https://polygonscan.com/tx/0x06b372b7537cd42ba2a07f9c079589e190961a7bdebd1ce0a849b6b2cfed5295

67.19821709999999 50 and 20 MYST
![myst](https://user-images.githubusercontent.com/53581740/148048442-1f968ad7-4d8a-42ca-b25c-878b94177824.PNG)

**Comment by Donatas-MN** [comment]
@mrgupe Can you send a screenshot how it looks like in your Wallet screen in NodeUI?
![Pasted_Image_2022-01-10_22_14](https://user-images.githubusercontent.com/91055712/148832885-5a2b3b18-827e-4430-8de5-feaac92503da.jpg)

**Comment by mrgupe** [comment]
G. Petersons

**Comment by tomasmik** [comment]
Should be resolved.

**Comment by Donatas-MN** [comment]
Try to withdraw one more time and see if the lost balance also arrived.
