### ISSUE TITLE
Let users pick their own automatic settlement value

### ISSUE THREAD

**Issue by stutteringp0et** [mysteriumnetwork/node#4583]
First it was 0.25, then 0.9, now it's 3 - it would be nice if I could choose.  I'm stuck on 1.1.2 until you decide to update the PPA - and in the mean time gas prices are so high that the 0.9 settlement value minus 20% and the gas fee (52% today) means I get a payout of 0.26.....fees and gas took 72%.  Rather than lose more myth to fees and gas, I shut off 20 hosted nodes in 11 countries because they're all set to auto-settle at 0.9....because I'm stuck at version 1.1.2 for (what I'm told) will be 4 or 5 days.

**Describe the solution you'd like**
Set the default to whatever you like - but allow users to pick their automatic settlement amount.

If I had this option, I could have just set the value high and left the nodes running until the update becomes available.

**Describe alternatives you've considered**
shutting off 20 nodes

**Comment by CharlyEmpereurmot** [comment]
+1 for having both:

- A user-defined MYST amount earned for triggering automatic settlement
- A user-defined limit on the accepted gas fee, that would inactivate automatic settlement until gas fee are below this user-defined threshold again

**Comment by tomasmik** [comment]
Thanks for the the input. We already have that planned. There are also issues opened for that:
* https://github.com/mysteriumnetwork/node/issues/4577
* https://github.com/mysteriumnetwork/node/issues/4575

For now we'll be releasing an update to allow you to settle whenever you want by clicking a button in the UI, but there is still no way to change the auto settlement threshold easily. However while a bit more tricky it is possible to manually set in the node config.

[Here is a short doc on how to edit the start up options/config](https://docs.mysterium.network/node-runners/setup/linux/#altering-start-up-options). The flag you're interested in is [payments.zero-stake-unsettled-amount](https://github.com/mysteriumnetwork/node/blob/master/config/flags_payments.go#L84)

**Comment by stutteringp0et** [comment]
Fantastic news!  Thanks @tomasmik & @CharlyEmpereurmot

**Comment by tomasmik** [comment]
Take note though, the longer you're not settling on the blockchain, the more trust you put in us and hermes to keep track of all your earnings, so you want to settle as often as possible. This is also subject to change if and when stacking is introduced back in to the workflow of node.

**Comment by stutteringp0et** [comment]
I only wanted access to the setting in response to the polygon gas fees.  I lost 72% on a 0.9 myst settlement yesterday.  Rather than lose more, I shut down 20 nodes.  If this option was available, I could have set the autosettlement high and left the nodes running, and turned the number back to something reasonable when the gas fees settle back down.

**Comment by Donatas-MN** [comment]
With the newest 1.1.6 release auto-settlement amount is not set to 5 MYST. We've also added SETTLE button to manually settle if you want to do it before 5 MYST are accumulated.
![Pasted_Image_2022-01-05_21_19](https://user-images.githubusercontent.com/91055712/148347780-7994dd4a-4c85-4024-a7e6-f6d673258b53.jpg)
