### ISSUE TITLE
Offline but connectable

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4592]
Identities:
- 0xe914e5ad375bad3cce19f8c2e427a691767789de
- 0x71af75149eee56d9d5bb1468148c9cab12e816b3
- 0x6d39d968073f0f9474a24de60a2230d3c38265a0

Provider IDs are being included in Discovery APIs list, connectable and processed some traffic over 24hrs but it displayed as offline and last seen: never on mystnodes.com dashboard. 

e.g.
https://discovery.mysterium.network/api/v3/proposals?provider_id=0xe914e5ad375bad3cce19f8c2e427a691767789de
>
<img width="1224" alt="Screenshot 2022-01-06 at 10 32 57" src="https://user-images.githubusercontent.com/60128746/148353743-d34738cf-8dae-420f-83f5-0dbff7074638.png">
>
<img width="1553" alt="Screenshot 2022-01-06 at 10 35 36" src="https://user-images.githubusercontent.com/60128746/148353811-b4805dd1-9ab9-4f24-b663-34aa8002de3d.png">

**Comment by hugomcconnell** [comment]
this is an issue I have - happy to help debug if i can

**Comment by Donatas-MN** [comment]
Should be fixed now.
