### ISSUE TITLE
Fees are 

### ISSUE THREAD

**Issue by KiwiMorpheus** [mysteriumnetwork/node#4601]
**Describe the bug**
Something significant has changed in the display of fee in "Node version: mainnet (1.1.6-bbd3079c)"

**To Reproduce**
Steps to reproduce the behaviour:
Go to wallet page and compare fees from before and after v1.1.6 upgrade

**Expected behaviour**
Fees should not be greater than payout.

**Screenshots**
![image](https://user-images.githubusercontent.com/6799110/148759247-79d80aa2-c62f-49d9-85ba-037fe7d772cf.png)

**Environment (please complete the following information):**
 - Node version: [e.g. 1.1.6]
 - OS: [e.g. Raspbian GNU/Linux 11 (bullseye)]
 - Your identity (if applicable): [e.g. 0x70bc9c62336140240ff4c5cb52d724bb311a]
 - Transaction ID (if applicable): [e.g. 0x8cf29edb136d44582b67de68be02ae1703c08b1605717802f456077eb33990a1]

**Comment by tomasmik** [comment]
This seems like settlemnts were done when transaction fees were through the roof on polygon so this is correct. The fees have gone down and your settlement amounts should go back to normal now.
