### ISSUE TITLE
Bulletproof apps registration/topup flow 

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#4602]
There seems to still be cases of people being forced in to the `topup` screen even though they have topped upped. Sometimes it is our backends fault, but sometimes it also seems that the app fails to handle certain scenarios. Go through these multiple workflows and test the apps, bulletproofing the missing or incomplete parts if any issues are found.

### 1. Registering a fresh account with no balance should only ping for topup once.
* [ ] Android
* [ ] Desktop

My registration should be automatically retried if:
   - I have failed registration and my status is `RegistrationError` or `Unregistered`. You can receive these events during runtime, you should be able to handle them and restart the registration automatically.
   -  I have money in my payment channel
   - I have an order which is paid

Apps should try to recover registration status if:
   - [My registration status is unknown](https://github.com/mysteriumnetwork/node/blob/master/identity/registry/status.go#L40). There are multiple ways to fetch the registration status and refresh it.

If my registration is being retried, I should also not see any `import identity` screens or anything like that. I should either see some new screen that says `Registering please wait` or be redirect to the nodes list as I always am.

---
### 2. If a registration request is sent out and I close the app - I should not be prompted to topup again.

This case seems rare, but not 0%. Somehow it's still possible to be prompted to topup or import your account even though you just closed it in the middle of registration.

* [ ] Android
* [ ] Desktop

---
### 3. If my registration is reported as failed the apps should retry the registration without showing me any of the topup screens again
* [ ] Android
* [ ] Desktop

As it stands right now, people are forced to force quit apps and jump through multiple hoops and rely on our support to actually finish their registration in case of an error. Consider showing somewhere/somehow that registration is in progress and dont leave the user in complete dark on this.

---
### 4. Consider giving additional context to the user
* [ ] Android
* [ ] Desktop ( these might be already possible on desktop )

1. Allowing for the user to see and copy his identity easily, would make it much easier to track problems and for them to provide additional information more easily.
2. Displaying topup orders and showing that they are paid even if user is not registered yet would also provide some assurance for the user that something is happening and we know his order is paid.

**Comment by tadaskay** [comment]
> I have failed registration and my status is RegistrationError or Unregistered. You can receive these events during runtime, you should be able to handle them and restart the registration automatically.
> I have money in my payment channel
> I have an order which is paid

The last point seems to be redundant (covered by 2nd). And if the money is not in the payment channel, it's backend's responsibility to move the money.

**Comment by tomasmik** [comment]
> The last point seems to be redundant (covered by 2nd). And if the money is not in the payment channel, it's backend's responsibility to move the money.

It's not redundant. Point is, why would the app show the topup screen on start up if a person has a paid order. Backend will move the money eventually.
