### ISSUE TITLE
wont show up on Mystnodes but shows into the node UI and its active

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4606]
**Describe the bug**

Node ID: 0x01f0acc7919d4c780727abf9aa0a969074d34d11

my node wont show up when i log in but i can log into the node UI and its active it says

i just tried to login to the website and it says i dont have a active node. i can still log in to the node ui and its active

i formatted my node and did a fresh install, updated to the latest version as requested by support. Still facing same issue.

Waiting on more details such as logs..

**Comment by etherunit** [comment]
I can see that his node is available in discovery: [0x01f0acc7919d4c780727abf9aa0a969074d34d11](https://discovery.mysterium.network/api/v3/proposals?provider_id=0x01f0acc7919d4c780727abf9aa0a969074d34d11)
Received quite a lot connections over the last 24hrs
<img width="777" alt="Screenshot 2022-01-11 at 18 32 46" src="https://user-images.githubusercontent.com/60128746/148982976-a5b69759-3b0b-4bfd-9dd3-b64006316363.png">

Can you please specify in which website it doesn't show up? mystnodes.com? Have he claimed his node?
