### ISSUE TITLE
Registered node shows as online but 'Accepting Connections' is Checking

### ISSUE THREAD

**Issue by Bugs789** [mysteriumnetwork/node#4608]
I have had my node online for a few days and haven't really seen an 'Live' activity apart from the Mysterium probes popping up. I wasnt overly concerned as I had heard when it was moved to Mainnet the users dropped.

My node is shown as 'Online' in the node UI but Accepting Connections just says checking, also when I go to the main dashboard I got a pop up error in red in the bottom right saying 'Nat probing is impossible at this connection state (path=nat/type)

I had the accepting connecting checking a few days ago but no error but this morning I noted it had dropped my proposal connection I reconnected which is when the nat/type error started.

The error only appear when I go to the main dashboard page

**Environment 
 - Node version: 1.1.6
 - OS: Ubuntu 20.04
  
I am also running the node from a cloud provider all the correct ports are open.

**Comment by etherunit** [comment]
Could you attach your node logs please?

https://docs.mysterium.network/node-runners/troubleshooting/#reporting-an-issue

**Comment by Bugs789** [comment]
Hi really not sure how to get the logs I could just do a 'journalctl -u' is that what you mean?

**Comment by etherunit** [comment]
If your node is unable to report an issue through the built-in Node UI or TequilAPI, you may need to save the logs to a file 

`sudo journalctl -u mysterium-node.service > node.logs
`
