### ISSUE TITLE
Node not earning and unsettled earnings incorrect

### ISSUE THREAD

**Issue by JmzTaylor** [mysteriumnetwork/node#4612]
**Describe the bug**
Node is showing 0 MYST earned from every single connection for at least a week no matter how much data is transferred.  Unsettled earnings balance is showing 7.3 MYST ever since the bug started.  

**To Reproduce**
Nothing to reproduce.  

**Expected behavior**
Balance be correct and earning from connections

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1] 1.1.4
 - OS: [e.g. raspbian buster, debian 10] Windows
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag docker - 4.2.0 latest tag for image
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A] 0x6135f146c25ba38f7b5e39e4841dd2e253531aef
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709] 

**Additional context**

**Comment by etherunit** [comment]
Can you please check it now?

**Comment by JmzTaylor** [comment]
I upgraded to 1.6.0 and still don't see a change.  unsettled balance is still the same no matter if I try to settle or not.  0 MYST earned from every single connection no matter how much data was transferred.  Recreated the container and restarted it, with no effect.

**Comment by JmzTaylor** [comment]
If it helps any.  The last connection that had any payment was 12/28.  600 connections since all showing 0 MYST earned.
