### ISSUE TITLE
myst not recieved by me

### ISSUE THREAD

**Issue by oh2020** [mysteriumnetwork/node#4613]
i settled my balance and clicked withdraw. wallet address confirmed....got a error saying try again later....i tried again and transaction completed. IT TOOK MY MYST AND NEVER SENT THEM

**Expected behavior**
myst in my meta wallet

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.1.6
 - OS: raspbian buster
 - Your identity (if applicable): 0xc055db438d97fd3ad592422827c9426b14547094

**Additional context**
when i click on the withdraw button at the bottom
Your last transaction: 0x683ef7c3627895e598396902fbe555f7c1d88335b10afb74d268ac9993ca8a04

in my wallets tab is shows 2 transactions since that one...both of which i never recieved.
![myst issues1](https://user-images.githubusercontent.com/31231466/149194217-b1d0e403-d15d-45d4-9ada-39bf35a935b0.png)

the tx on 1/3: polygonscan has NO record of....
https://polygonscan.com/tx/0x8ead868c95724f292d6d3bf4dffd9a0d4b268a9829495e42b04bad2a5dda39ce

the tx from last night:
https://polygonscan.com/tx/0xbba3fcfb34659b3c5d038595481f266eb0e0a3eb71ce1da06ed4467b8e0c3509

the wallet on polygonscan
https://polygonscan.com/token/0x1379e8886a944d2d9d440b3d88df536aea08d9f3?a=0xA0147978d73D7367b856c581c20A5c47d8eAE0D8

**Comment by etherunit** [comment]
Your tokens won't be lost. Any withdrawal that's not settled or fails to settle will just do it again next time you withdraw money. However, I though that we made some fixes in this workflow, or its a different one @tomasmik ?

**Comment by tomasmik** [comment]
This appears to be another case of hermes not settling the withdrawal promise for whatever reason. You can [see here in the withdrawal data](https://hermes.mysterium.network/api/v2/data/provider/0xc055db438d97fd3ad592422827c9426b14547094/withdrawal) that you're owed more money than you were given.

Next time you withdrawal you should receive both of the amounts in a single transaction with no problem. Hermes will remember that he owns you money.

I've created another issue to track the progress of investigating and fixing it as it's clearly not 100% perfect yet: https://github.com/mysteriumnetwork/node/issues/4631
