### ISSUE TITLE
Node UI withdrawal discrepancy

### ISSUE THREAD

**Issue by Loggsie** [mysteriumnetwork/node#4618]
If you withdraw more than 100 MYST in one go, whilst successful the node UI will only show part of the transaction hash and report an incorrect withdrawal value. 

Transaction hash - 235 MYST withdrawal requested 

https://polygonscan.com/tx/0xfe21a596ceea7a06282885105521ffde446c284d733f3a0b4cd13d456b833fd2 

Split over hashes 

https://polygonscan.com/tx/0xedf2b4852c719fa45abb65d390c2c082045b9c4562a41fec60b9ef2fd3374d00 

& 
 https://polygonscan.com/tx/0x699f9f6a3ac8d010cc6231c1b97f93a64983e70cea1f5634fa83acd429637a5c 

Node UI only displays the following withdrawal hash, equivalent to 77 of the 235 MYST requested and also incorrectly report this as 100 MYST

https://polygonscan.com/tx/0x699f9f6a3ac8d010cc6231c1b97f93a64983e70cea1f5634fa83acd429637a5c

**Comment by tomasmik** [comment]
We're solving this in the next few releases of node. We're aware of the issue. Currently the proposed fix will be to limit withdrawal amount to less than 100 MYST per single request.

This is a limitation in our smart contracts, which is not explained anywhere. Closing this as duplicate for now.
