### ISSUE TITLE
Quiting the cli hangs instead of quitting

### ISSUE THREAD

**Issue by tcharding** [mysteriumnetwork/node#462]
Running `bin/run cli` then entering command `quit` (or `exit`) outputs a goodbye message then prints the cli prompt again, the cli hangs at this stage (Ctl-C does not work).

**Comment by soffokl** [comment]
I have [commented](https://github.com/mysteriumnetwork/node/pull/463#issuecomment-431737877) in the PR:

>Looks like this is a bug in the package that we are using https://github.com/chzyer/readline/pull/136
It fixed in master, but we are using the latest version and we don't have the fix released. 
>We can workaround it somehow, or just use the master branch in `dep`

There is an [issue](https://github.com/chzyer/readline/issues/135), that request a new release:
