### ISSUE TITLE
NoreUI - 99 MYST withdrawal limit improvements

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#4621]
Tasks:
- [x] If total Balance is > 99 MYST, cut max Amount to 99 MYST.
- [x] With error shown this withdrawal modal does not fit Macbook 13 screen:
![image](https://user-images.githubusercontent.com/91055712/149625705-8c932bd1-8821-433b-ab2b-94d10b2d0968.png)
- [x] Withdrawal button is shown as active even if Amount is over >99 MYST (however nothing happens after a click).
![Pasted_Image_2022-01-15_16_39](https://user-images.githubusercontent.com/91055712/149625772-0cde5dac-09ff-4005-a7ba-530fb62bcbd4.jpg)
- [ ] Remove arrows for input field. Allow to enter both with . and , if possible (1.25 or 1,25)
![Pasted_Image_2022-01-16_16_15](https://user-images.githubusercontent.com/91055712/149663727-23b807ca-5c57-43fc-9e4f-18838f813647.jpg)

**Comment by mdomasevicius** [comment]
> Remove arrows for input field. Allow to enter both with . and , if possible (1.25 or 1,25)
this will be done with restyling
