### ISSUE TITLE
Update from 1.0.14 to 1.1.9 deletes unsettled balance

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4622]
**Describe the bug**
manual update of a node from version 1.0.14 -> 1.1.9 using apt update//apt upgrade. Upgrade happened with no errors, however after relogging into the webif on localhost:4449 I noticed that the unsettled balance went from 0.25 to 0. settled balance stayed at 0.33 as before

**Expected behavior**
unsettled balance should be carried over during update

**Environment (please complete the following information):**
 - 1.0.14 -> 1.1.9
 - debian bullseye
 - identity: 0x8868b41251de1683366c4adfa0d1567bd07d8d4b

**Comment by tomasmik** [comment]
> unsettled balance should be carried over during update

It does.

This seems either a nodeUI issue or node itself not getting the right balance after the restart.

**Comment by veldspar** [comment]
I can exclude nodeUI for now, as trying to settle the balance manually  via myst cli settles 0.00 myst

**Comment by tomasmik** [comment]
What do you mean by settling 0 MYST?
