### ISSUE TITLE
Node Online but all connections with 0 seconds/bytes

### ISSUE THREAD

**Issue by Pascal51882** [mysteriumnetwork/node#4623]
**Describe the bug**
The node is online with the standard ports 1194 UDP and 4449 TCP (accepting most connections).
All connections I get have 0 seconds and 0 traffic.

**Expected behavior**
That the connections get traffic.

**Screenshots**
![image](https://user-images.githubusercontent.com/41856419/149725000-042b3638-bfa8-44a5-ab1b-168c53cda0b7.png)
![image](https://user-images.githubusercontent.com/41856419/149725043-6e6f2edc-9bfa-4a41-9ce8-2b3467585236.png)

**Environment (please complete the following information):**
 - Node version: [e.g. 1.6.2]
 - OS: [e.g. debian stretch, debian 9]
 - Docker (if applicable): newest docker version on OMV4. 
 - System: rock64 with armhf image
 - Your identity (if applicable): [e.g. 0x60c2693e463866668b9640c9add5f89b7ee12869]

**Comment by etherunit** [comment]
I can see that your node is failing to accept any incoming connection. 
<img width="801" alt="Screenshot 2022-01-18 at 22 36 39" src="https://user-images.githubusercontent.com/60128746/150014609-8159cc66-90d6-4836-85a0-5e7c4f0893d8.png">

There may be a time when you encounter an issue with your node and we may ask you to submit your logs for further investigation. For us to understand what is happening we'd like you to submit your node logs. Login to your Node UI and click the "Bug" button on the left side panel.
Thanks

**Comment by Pascal51882** [comment]
I have submitted the log and entered the link to this post as a comment

**Comment by supercjlee** [comment]
Same problem happen by my system.

![image](https://user-images.githubusercontent.com/60121744/151470289-5a6349b5-6cfc-446a-ac35-abd9b762b968.png)
![image](https://user-images.githubusercontent.com/60121744/151470685-5e238277-35c2-4c90-8353-d568956b11e7.png)

Node version: 1.7.0
OS: Alpine Linux v3.14(docker)
Docker (if applicable): newest docker version on OMV4.
System: intel CPU
Your identity (if applicable): 0x5b7c02ee92a492ea5096e7fbef8d45aed14363bb

**Comment by isaackielma** [comment]
https://s3-testnet.mysterium.network/node-user-reports/2022-01-20-e25ef159-2b92-49d7-bc3f-a9ea9677b21f-mysterium-node.zip2138369657

**Comment by isaackielma** [comment]
@supercjlee Can you please submit your app logs so we could investigate this further with our engineering team? 

 

Access the "Help" tab section on the title bar (top of app window). Then, 'Report Bug'.

 

Please note  that description and application logs will be attached to the issue. Logs may include sensitive information, such as IP address and location. It will be only accessible and used by the engineering team to address the issue you are reporting.

 

After doing so, please let us know here so we can forward logs
