### ISSUE TITLE
Node UI — Statistics Widgets at the Top of the Dashboard Are Reset and Stopped Counting New Data after Any Node Update between Versions 1.1.6–1.1.9

### ISSUE THREAD

**Issue by alexstreltsov** [mysteriumnetwork/node#4627]
**Description**
Statistics widgets at the top of the Node UI dashboard are reset and stopped counting new data after any node update between versions 1.1.6–1.1.9.

**Expected Behaviour**
A node runner should be able to see statistics for the entire lifetime of the node on the widgets at the top of the Node UI dashboard, and for the last 30 days — in the 30-day report below.

**Screenshots**
<img width="1198" alt="Node UI Dashboard Screenshot" src="https://user-images.githubusercontent.com/75667852/149761756-113fa547-0051-4926-b6b7-920860390b37.png">

**Environment:**
 - Node version (before update): 1.1.6
 - Node version (after update): 1.1.9
 - Node UI version: 1.6.2
 - OS: Ubuntu Server Focal Fossa 20.04.3 LTS
 - Node type: hosting

**Additional Information**
Related issue: #4620.

**Comment by alexstreltsov** [comment]
When I noticed that some node runners were facing various issues with Node UI after the update 1.1.7 was released, I decided to cancel automatic updates and wait for later versions come out. It turned out that with the update 1.1.9 the problem remained. It turned out that with the update 1.1.9 this bug still remains

**Comment by Donatas-MN** [comment]
It's was fixed in the later node version. Sorry for the inconvenience.
