### ISSUE TITLE
Nodes are not visible on the Mysterium Mysterium Desktop app

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#4632]
**Describe the bug**
Nodes are not visible on the Mysterium Desktop app

**Expected behavior**
Once I open the Mysterium Desktop app, it should show all the nodes on manual connect..

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/149945570-9373b6cd-0b33-4901-b186-dc8611faf0bd.png)
![image](https://user-images.githubusercontent.com/68943180/149945588-23ab7c25-967e-4092-87c2-61ac9a0f8501.png)

**Environment:**
 - Desktop app version: 10.4.1
  - OS: MacOS
 - Your identity: 0x21a40c7d29a85dd7ecf590dde6653e8a2bb7c371

**Additional context**
This issue is being reported by 2 of our community members from discord and re-opening, rebooting the device didn't fix this issue.

**Comment by etherunit** [comment]
@adinetech Thanks for opening it! We need node logs to verify the origin of this issue.
Is this possible to arrange?

**Comment by adinetech** [comment]
It is resolved automatically.
