### ISSUE TITLE
considerable amount of myst lost upon withdraw

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4634]
**Describe the bug**
nodeid 0x397818e19ab5a2ea26daa00f66bef6881e195065

had a balance of ~1200, withdraw attempted all at once and got an error message. successfully withdrew 90, then 100

tried one for 800 and it does not appear in provider's withdraw logs, but has been deducted from balance.

**Expected behavior**
Withdrawal amount should either remain on balance or go to wallet included in the transaction. Transaction details should appear in withdraw logs if amount is deducted from balance

**Comment by Loggsie** [comment]
Known issue.

Withdrawal limited due to smart contract to no more than 99 MYST a time.

Your next withdrawal will force the hung withdrawal to complete.

**Comment by overland-liquor** [comment]
that explains why several later withdrawls doubled up.

still, i dont have 600 more myst to withdraw from earnings.  what can be done?

further, why doesnt the interface indicate this at all?  if the limit is 99...it shouldnt even let you submit more than 99...

**Comment by Loggsie** [comment]
A limit has been requested to be incorporated in a later release. 

In your instance any withdrawal under 99 MYST should be sufficient to force completion of your initial withdrawal request. 

It will not be dependent on you making several withdrawals totaling 600 MYST.

**Comment by etherunit** [comment]
@isaackielma 
Please refer to:
https://github.com/mysteriumnetwork/node/issues/4621
https://github.com/mysteriumnetwork/node/issues/4617

**Comment by etherunit** [comment]
No MYST will be affected by this, next withdrawal should initiate the "Stuck" amount to be processed again (up to 99MYST limit).

**Comment by overland-liquor** [comment]
i have made subsequent withdraws but the stuck amount was not fully released, only an amount identical to the subsequent withdraw (i can send those transactions in discord if you want to review)

**Comment by Loggsie** [comment]
There are four potential ways forward

1. Use an existing MYST holding of the same value to recomplete the withdrawal up to 99 MYST each time - stuck MYST will double up what is received in your wallet. It is possible to return MYST held in your wallet back to your node wallet to facilitate this. Rinse and repeat.

2. Buy additional MYST to allow the above to happen and dump immediately afterwards.

3. Rent MYST temporarily from IQ liquidity https://app.iq.space

4. Loan the required MYST from a friend.

**Comment by overland-liquor** [comment]
all of these solutions involve burning my own myst to resolve an acknowledged UI/UX issue.  

theres another solution: the myst project lends me the necessary myst to solve the problem created by their software.  ill return it when the stuck myst is drained.

**Comment by Loggsie** [comment]
You wouldn't be burning here, you would be moving MYST between wallets and back again to force the initial withdrawal through the network. Burning would imply a one way action which is irreversible.

Given you're governed by the limitations of the Smart contract here, you've limited options. 

Other than sitting it out until you've accumulated the same amount of MYST on your node wallet, I don't see any alternative solution available to you than what I have already mentioned.

**Comment by tomasmik** [comment]
> all of these solutions involve burning my own myst to resolve an acknowledged UI/UX issue.

This is actually fixed in the UI from version 1.1.9 and in node API since version 1.1.10. There were also fixes made for this in Hermes which will be released soon. The current limit which is set might be changed in the upcoming weeks, to allow for larger withdrawals at a time.

**Comment by overland-liquor** [comment]
whatever excess transaction fees occur, i guess actually MATIC?, to release the MYST would be getting burned, and/or whatever cost associated with the loan.

it seems to me that the myst project, as a partner in this effort and the source of the UI bug, should accept responsibility for the situation and be the 'friend' that loans the necessary MYST, to be returned when the process is complete.

thats great, glad it got fixed.

**Comment by overland-liquor** [comment]
checking in here - is the myst project going to be the friend that loans me the necessary tokens to release my funds and help fix the issue their UX implementation created?

**Comment by overland-liquor** [comment]
i finally got enough out of the network to try again, performed a 99 myst transfer, and did not receive an additional deposit in the destination wallet that i was expecting, from the remaining balance that is hung up from the initial larger transfer.

**Comment by Donatas-MN** [comment]
@overland-liquor can you try to do a small withdrawal like 0.5 MYST? In this way you should get the missing MYST.

**Comment by overland-liquor** [comment]
@Donatas-MN per previous theres about 300 myst still held up in the contract.  i performed a 99myst withdrawl a couple days ago and did not receive the additional amount from the smart contract.

something is loose.

**Comment by Donatas-MN** [comment]
You can only receive maximum of 99 MYST with one withdrawal, so you have to make a few small withdrawals (e.g. 0.5 MYST) to receive missing MYST.

**Comment by Donatas-MN** [comment]
And make sure you have latest node version installed.

**Comment by overland-liquor** [comment]
@Donatas-MN yes, that information has already been communicated previously by team members.  note that per their communication transactions will only match the withdrawn amount, which is why i withdrew the maximum amount - i have more than that stuck in the contract.  this matches my previous experience, but not the most recent withdrawal when no matching at all happened.

**Comment by overland-liquor** [comment]
this is not resolved

**Comment by Donatas-MN** [comment]
@overland-liquor what happens if you withdraw 0.5 MYST now?
