### ISSUE TITLE
NodeUI displays wrong earnings data

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4637]
UI displayed an improper earnings data comparing to what is being displayed on Hermes. 

e,g. Hermes:
 https://hermes.mysterium.network/api/v2/data/provider/0x0b684acd0c9d7758811cc1a8758a9eaf49024edd

UI:
<img width="1011" alt="Screenshot 2022-01-19 at 13 00 15" src="https://user-images.githubusercontent.com/60128746/150119322-4e204723-c3bf-4bc7-8030-bffc0a191892.png">

Using incognito fixes it.

**Comment by tomasmik** [comment]
This very well could be related to this: https://github.com/mysteriumnetwork/node/issues/4646

**Comment by Donatas-MN** [comment]
Happens to me as well when node is updated to new version or reset is performed by using: 
`sudo systemctl restart mysterium-node.service`
