### ISSUE TITLE
I can't connect Mysterium Node UI

### ISSUE THREAD

**Issue by aqa54** [mysteriumnetwork/node#4641]
Hi, I get this error when I want to connect Mysterium Node UI. I will attach a screenshot of "Pageable: totalItems is not provided". I tried connecting from several different devices and browsers, and I got the same error on all of them.

There is no problem using Node. I can connect others and earn myst coins. but I couldn't add a payment address because I couldn't enter the interface.
![Adsız](https://user-images.githubusercontent.com/98105691/150362654-6c80f170-3fc2-48ad-b2e9-fa2309de6bce.png)

 - Node version: 1.1.9
 - OS: raspbian
 - Identity : 0x6361e17dde43333406493ea26adc717cbcc697ef

**Comment by forkposix** [comment]
I have same issue

**Comment by etherunit** [comment]
Guys, could you try to update your node to `Node version: mainnet (1.1.10-90175c6e)`
https://docs.mysterium.network/node-runners/setup/updating/

**Comment by forkposix** [comment]
Mysterium Node
  Version: 1.1.10
  Build info: Branch: 1.1.10. Build id: 450561391. Commit: 90175c6e
  
![image](https://user-images.githubusercontent.com/22747808/150391071-bc1f5146-c9b2-4bcb-9d1d-a93b6baca8ab.png)

This error occurred after update, i am already in new version.

**Comment by forkposix** [comment]
curl 'http://192.168.1.100:4449/tequilapi/auth/login' \
H 'Connectio>   -H 'Connection: keep-alive' \
ndows NT 10.0; Win64; x64) Apple>   -H 'Accept: application/json, text/plain, */*' \
>   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
>   -H 'Content-Type: application/json' \
AiOjE2NDI4NzEzMDl9.IXroXIdxTgd61qY5FoT7pQi9rHReK>   -H 'Origin: http://192.168.1.100:4449' \
Y-MTqOnkqmsz>   -H 'Referer: http://192.168.1.100:4449/?' \
>   -H 'Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh-CN;q=0.5,zh;q=0.4' \
>   -H 'Cookie: token=*******************' \
>   --data-raw '{"username":"myst","password":"mystberry"}' \
>   --compressed \
>   --insecure
{"message":"bad credentials: crypto/bcrypt: hashedPassword is not the hash of the given password"}

**Comment by Rtoprakci** [comment]
Hi
I also have the same Problem. version 1.1.6, where I could enter the latest panel, after this version, I could not enter the panel page.

**Comment by Loggsie** [comment]
> ```
> curl 'http://192.168.1.100:4449/tequilapi/auth/login' \
> H 'Connectio>   -H 'Connection: keep-alive' \
> ndows NT 10.0; Win64; x64) Apple>   -H 'Accept: application/json, text/plain, */*' \
> >   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
> >   -H 'Content-Type: application/json' \
> AiOjE2NDI4NzEzMDl9.IXroXIdxTgd61qY5FoT7pQi9rHReK>   -H 'Origin: http://192.168.1.100:4449' \
> Y-MTqOnkqmsz>   -H 'Referer: http://192.168.1.100:4449/?' \
> >   -H 'Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh-CN;q=0.5,zh;q=0.4' \
> >   -H 'Cookie: token=*******************' \
> >   --data-raw '{"username":"myst","password":"mystberry"}' \
> >   --compressed \
> >   --insecure
> {"message":"bad credentials: crypto/bcrypt: hashedPassword is not the hash of the given password"}
> ```
> 
> My password is not mystberry. When i try to enter my password. Login payload is not contain password i entered. It contains default password.
> 
> I can post successfully login request with curl. Otherwise i am getting bad credentials error.

Do you notice any difference when you remove the following file

/var/lib/mysterium-node/nodeui-pass ?

**Comment by etherunit** [comment]
Adding node happiness team to help on that.

**Comment by mdomasevicius** [comment]
> ```
> curl 'http://192.168.1.100:4449/tequilapi/auth/login' \
> H 'Connectio>   -H 'Connection: keep-alive' \
> ndows NT 10.0; Win64; x64) Apple>   -H 'Accept: application/json, text/plain, */*' \
> >   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36' \
> >   -H 'Content-Type: application/json' \
> AiOjE2NDI4NzEzMDl9.IXroXIdxTgd61qY5FoT7pQi9rHReK>   -H 'Origin: http://192.168.1.100:4449' \
> Y-MTqOnkqmsz>   -H 'Referer: http://192.168.1.100:4449/?' \
> >   -H 'Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6,zh-CN;q=0.5,zh;q=0.4' \
> >   -H 'Cookie: token=*******************' \
> >   --data-raw '{"username":"myst","password":"mystberry"}' \
> >   --compressed \
> >   --insecure
> {"message":"bad credentials: crypto/bcrypt: hashedPassword is not the hash of the given password"}
> ```
> 
> My password is not mystberry. When i try to enter my password. Login payload is not contain password i entered. It contains default password.
> 
> I can post successfully login request with curl. Otherwise i am getting bad credentials error.

This is a checking call to decide if user needs on-boarding (setting new password). 

It would be great if someone that can reproduce this issue would provide a network tab read-out on which endpoint was called that failed with `totalItems` not provided error.

**Comment by forkposix** [comment]
@mdomasevicius i dont know how to check it.

**Comment by Rtoprakci** [comment]
> /var/lib/mysterium-node/nodeui-pass

I deleted this file. I re-created the password, but the same problem still persists.

**Comment by forkposix** [comment]
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7916076/mysterium-node.log)
here is the mysterium node logs.

**Comment by mdomasevicius** [comment]
@forkposix 

if you are using "Chrome" or any chrome based browsers: https://developer.chrome.com/docs/devtools/network/
firefox: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

the requests that fail should be in red

**Comment by etherunit** [comment]
@forkposix @aqa54 any updates on this one?

**Comment by forkposix** [comment]
> @forkposix @aqa54 any updates on this one?
[logs.zip](https://github.com/mysteriumnetwork/node/files/7940682/logs.zip)

**Comment by forkposix** [comment]
> @forkposix @aqa54 any updates on this one?

issue fixed with last update.
