### ISSUE TITLE
Top up fail USDT

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4642]
**Describe the bug**
I deposit 21.63 usdt but I didn't get anything please help
Txid : 0x0b8a86912b771d10ac16586634d20174f50ce9b3ce439d9b4284395a756b11e6

**Screenshots**
<img width="375" alt="Screenshot 2022-01-20 at 19 16 46" src="https://user-images.githubusercontent.com/84313603/150407132-c44cb49c-5767-4420-bebd-9d797e071f92.png">
<img width="381" alt="Screenshot 2022-01-20 at 19 17 00" src="https://user-images.githubusercontent.com/84313603/150407163-b31a9785-6b51-47a4-919a-ff113bb7627f.png">
<img width="407" alt="Screenshot 2022-01-20 at 19 16 34" src="https://user-images.githubusercontent.com/84313603/150407115-34c68290-c9b0-4bce-b786-0f2588c9865a.png">

**Comment by adinetech** [comment]
Seems like the user withdrawn USDT over the Polygon network, Coingate only supports USDT on the Ethereum mainnet.

**Comment by tomasmik** [comment]
Order was never paid for and is expired. Maybe it was the reason @adinetech described, maybe something else, but not a single cent has been received to pay for this order.

**Comment by isaackielma** [comment]
<img width="634" alt="Screenshot 2022-01-24 at 17 03 44" src="https://user-images.githubusercontent.com/84313603/150829676-9c539729-670f-43e4-a5c5-40123f366b18.png">

App is not clearly specifying that USDT transaction should be under ERC20 network or that BSC transactions are not supported. Maybe we could add a warning note to the users so something like this does not happen again?

**Comment by adinetech** [comment]
That would be nice!

**Comment by isaackielma** [comment]
@Artem Hryhorov

**Comment by adinetech** [comment]
> <img alt="Screenshot 2022-01-24 at 17 03 44" width="634" src="https://user-images.githubusercontent.com/84313603/150829676-9c539729-670f-43e4-a5c5-40123f366b18.png">
> 
> App is not clearly specifying that USDT transaction should be under ERC20 network or that BSC transactions are not supported. Even though it shows total amount in ETH, some people may not understand unless clearly specified. Maybe we could add a warning note to the users so something like this does not happen again?

This will be an feature request for our UI Enginner.
