### ISSUE TITLE
[question] IP_NOT_CHANGED connection state

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4643]
What is IP_NOT_CHANGED connection state?

Apps constantly get to this state after connecting.

**Comment by soffokl** [comment]
`IP Not Changed` means that consumer IP not changed after the connection is created. 
This might indicate some problems with connection, might be a provider or consumer configuration incorrect.

**Comment by cvl** [comment]
Interesting, because IP is actually changed. It behaves as if Connected.

**Comment by cvl** [comment]
I assume if connection goes into IP_NOT_CHANGED state, then kill-switch should activate automatically (i.e. it should enter the ON_HOLD state).
That doesn't happen as well.

Also, official Mysterium Android app treats IP_NOT_CHANGED as protected connection state https://github.com/mysteriumnetwork/mysterium-vpn-mobile/blob/50eaccb23a726f0caf3eb14bf09b116b23bdc08d/android/app/src/main/java/updated/mysterium/vpn/ui/base/BaseActivity.kt#L216

**Comment by portalsdevs** [comment]
x

**Comment by cvl** [comment]
x

**Comment by portalsdevs** [comment]
x
