### ISSUE TITLE
too much gpu usage

### ISSUE THREAD

**Issue by anweshan2** [mysteriumnetwork/node#4647]
I get that it uses some CPU power which is completely fine but why is the dvpn app using around 20 and sometimes 40% of my gpu?
![image](https://user-images.githubusercontent.com/88652570/150656878-78449ff9-ffd3-4bc0-9403-1a90f5e2883c.png)

**Comment by adinetech** [comment]
You can minimize the app, so the GPU usage will change to 0

**Comment by adinetech** [comment]
hmm

**Comment by adinetech** [comment]
stop my bot
