### ISSUE TITLE
DHT node to update MORQA state

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#465]
As Myst node provider operator 
In order to collect statistics information on my node's usage
I want to store such statistics in DHT which later can be used by MORQA service

**Comment by zolia** [comment]
SPIKE documentation:  

https://mysteriumnetwork.atlassian.net/wiki/spaces/MN/pages/653262849/SPIKE+store+MORQA+shared+state+using+DHT+465

**Comment by soffokl** [comment]
Shouldn't it go to the https://github.com/mysteriumnetwork/morqa/?

**Comment by zolia** [comment]
True, probably we should have similar ticket in both places. Node should be able to start DHT node as a service. Will create a separate ticket for MORQA repo.

**Comment by zolia** [comment]
Currently we use metrics.mysterium.network service to store metrics. Shared data storage version needs more detailed investigation and should be covered in detail through series of tasks.
