### ISSUE TITLE
Node crashes cause ongoing connections to not  be settled

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4651]
**Describe the bug**
If a node or its internet connection crash during an ongoing session, the session is not going to be settled

**To Reproduce**
If a node host crashes during an ongoing session, the transaction will show up in logs like this after node restart:
`Croatia
04:19:36
23/01/2022, 18:19:39
0 MYST
0 Bytes
cd6fa658`
**Expected behavior**
After restarting the node, session is settled.

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.1.19
 - OS: raspbian buster
 - Your identity (if applicable): 0xc2c70edbafba5a11b5c411afc553f4c80560c7fc

**Additional context**
unfortunately this is the only unstable node, it sometimes starts getting laggy and sluggish, so it has to be restarted every now and then. since this raspberry also provides my home wifi network, I have to restart it when the wife starts complaining too loud about bad internet connection. interestingly enough, sometimes the node activity seems to impair the functionality of wifi(clients on wifi get unreasonably slow and laggy while doing a speedtest from the box itself still yields the desired speed/responsiveness)

**Comment by etherunit** [comment]
Thank you for your insights! We will do a round of testing in regards to this issue and will try to improve it.

**Comment by etherunit** [comment]
Is there anything we can do about it @Snawoot?
