### ISSUE TITLE
Withdrawal didn't come in the wallet as well as unable to see it in the dashboard

### ISSUE THREAD

**Issue by AdnanSayyed** [mysteriumnetwork/node#4654]
**Describe the bug**
The withdrawal didn't come in the polygon wallet, also didn't updated in the withdrawal history in the dashboard
https://polygonscan.com/tx/0x45b84069a6a8f23dd6c2c04563ef4f983610fb00b7953afd6caa3de978f438c6

**To Reproduce**

**Expected behavior**
Withdrawal should come in the wallet as well as should reflect in the withdrawal history in the dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/30722682/150798805-0d87048c-2d60-4cee-abd0-a810c39b1d9c.png)

**Environment (please complete the following information):**

**Additional context**

**Comment by etherunit** [comment]
Can you provide us with your node identity?

**Comment by speedf1** [comment]
I had the same problem.  When I used a different node to withdraw it seem to get the other transaction to show.

**Comment by 4KJuegos** [comment]
I have also the same problem... never comes to the wallet but i can see the transaction hash as "success". No withdrawals on the dashboard. And now, withdrawals doesn't work.

**Comment by etherunit** [comment]
@speedf1 @4KJuegos Can you provide your node identities? I'll check the withdrawal endpoint status on Hermes and if the debit for the withdrawal was made (if not, it will be done next time).

**Comment by 4KJuegos** [comment]
> @speedf1 @4KJuegos Can you provide your node identities? I'll check the withdrawal endpoint status on Hermes and if the debit for the withdrawal was made (if not, it will be done next time).

My node identity:   0x5c2d1fe134cf0dff70e3adc873437996e54c7ccc

**Comment by etherunit** [comment]
@4KJuegos For us to understand why transactor is not creating the pay and settle transaction we'd like you to submit your node logs. Login to your Node UI and click the "Bug" button on the left side panel. Thanks!

**Comment by 4KJuegos** [comment]
> @4KJuegos Thanks! Team will investigate it further. Also, to understand why transactor is not creating the pay and settle transaction we'd like you to submit your node logs. Login to your Node UI and click the "Bug" button on the left side panel.

Done. I sended the report on bug button. Thanks!

**Comment by speedf1** [comment]
@etherunit this transaction went through (after I did another transaction on a different node), however I've also submitted the logs via the bug report button

**Comment by speedf1** [comment]
@etherunit it's happened again this morning on two nodes.  I've withdrawn from both, the balance has gone done.  No MYST arrives in my metamask wallet and no transactions shown in either of the two node GUI transaction (wallet) page.  I'll submit buglogs for both nodes.

**Comment by speedf1** [comment]
@etherunit the two node IDs are:

0x2163fd60996553c867f6434d6aab37383aff6c54
0x9d42893e4ee86950d83b2f48dc76fbabd0b1f949

**Comment by AdnanSayyed** [comment]
0xc6bbb96ec18b390bf48924635001a00a4f57d113
Node version: mainnet (1.2.3-2e737829)
NodeUI version: 1.7.0

> Can you provide us with your node identity?

**Comment by AdnanSayyed** [comment]
This is not a minor bug, Please make it major as our perspective

**Comment by AdnanSayyed** [comment]
any update?? @etherunit

**Comment by AdnanSayyed** [comment]
ISSUE IS STILL NOT FIXED BY YOUR TEAM
I AM QUITTING THIS SHIT PLATFORM

**Comment by etherunit** [comment]
Apologies for the delay. We have done numerous improvements on the withdrawals side. They should work as expected. If you will see that it's failing again, feel free to reopen it.
