### ISSUE TITLE
Node remains in status test failed

### ISSUE THREAD

**Issue by Pascal51882** [mysteriumnetwork/node#4655]
**Describe the bug**
My Node remains in status test failed. At the beginning my node worked fine for a week.
After that it was in status test failed and I rebuilt it afterwards and deleted all data/dockers. The status is again test failed and for 2 days it was once online, although I had not changed anything. Meanwhile the status is permanently test failed.
Test connections seem to work? The https://mystnodes.com/nodes shows online.

Disclaimer: I am running a Windows node in the same network because this linux node is not workung atm. I use different ports.

**Screenshots**
![image](https://user-images.githubusercontent.com/41856419/150800424-12c92983-cd53-4aaa-ba99-89cdc359dfcb.png)

**Environment (please complete the following information):**
 - Node version: [1.6.3]
 - OS: [Unraid 6.9.2]
 - Docker (if applicable): newest on Unraid
 - Your identity (if applicable): [e.g. 0xda71b4585c32c5549496abc25085e8b72427446b]
 - Payment (top-op) reference (if applicable): [e.g. 0xC17837552b0d60262E0A5Ee8635AD34A0f64d319]

**Additional context**
Ports:
TCP 4449
UDP 1194
UDP range: 10000-10200

I will Upload my Logs throug the Guide with this topic as link.

**Comment by etherunit** [comment]
There may be a time when you encounter an issue with your node and we may ask you to submit your logs for further investigation. For us to understand what is happening we'd like you to submit your node logs.

Node logs do not include your node's traffic.

Login to your Node UI and click the "Bug" button on the left side panel.
or
Report issue directly to Mysterium support using API service:
`curl -X POST --data '{"email":"yourmail@mail.com","description":"Write description here min 30 characters"}' localhost:4050/feedback/issue`

**Comment by etherunit** [comment]
Your node is connectable but it fails to access internet once connection is established.
<img width="811" alt="Screenshot 2022-01-25 at 09 22 26" src="https://user-images.githubusercontent.com/60128746/150929921-71c0eccb-ce36-43f3-9f52-76ce5d297aa4.png">

```
2022-01-25T09:21:20.650 ERR ../../../../source/core/location/cache.go:102        > Location update failed error="failed to execute request: Get \"https://location.mysterium.network/api/v1/location\": read tcp : read: connection reset by peer"
2022-01-25T09:21:20.658 ERR ../../../../source/core/ip/resolver.go:101           > could not reach location service, will use fallbacks error="Get \"https://location.mysterium.network/api/v1/location\": read tcp : read: connection reset by peer"
2022-01-25T09:21:21.476 ERR ../../../../source/core/ip/resolver.go:129           > public ip fallback error error="Get \"https://www.trackip.net/ip\": read tcp : read: connection reset by peer" url=https://www.trackip.net/ip
2022-01-25T09:21:21.500 ERR ../../../../source/core/ip/resolver.go:129           > public ip fallback error error="Get \"https://ipinfo.io/ip\": read tcp: read: connection reset by peer" url=https://ipinfo.io/ip
```

**Comment by etherunit** [comment]
0xda71b4585c32c5549496abc25085e8b72427446b node was never online (according to grafana), hence I suspect there is an issue with firewall settings not allowing myst node service to function properly (blocking packets).

**Comment by Pascal51882** [comment]
My Firewall AVM FritzBox does not block any packets. In fact Windows docker works. Unraid/Docker Firewall does also not block.

**Comment by etherunit** [comment]
Looking at historical data, all past test sessions failed due to the same problem. 

```
» status
[INFO] Status: Connected
[INFO] SID: afd3c9fc-6aab-4a12-ad03-03e204df33e6
[WARNING] server response invalid: 503 Service Unavailable (http://127.0.0.1:4050/connection/ip). Possible error: out of fallbacks
[WARNING] server response invalid: 503 Service Unavailable (http://127.0.0.1:4050/connection/location). Possible error: failed to execute request: Get "https://location.mysterium.network/api/v1/location": read tcp 10.182.0.2:58131->51.15.116.186:443: read: connection reset by peer
[INFO] Proposal: Provider: 0xda71b4585c32c5549496abc25085e8b72427446b, ServiceType: wireguard, Country: DE
[INFO] Connection duration: 47s
[INFO] Data: 40.5KiB/351.1KiB
[INFO] Throughput: 1.6KiBs/12.0KiBs
[INFO] Spent: 0.000000
```

**Comment by Pascal51882** [comment]
How can I troubleshoot this in detail. 

Docker Port config:
![image](https://user-images.githubusercontent.com/41856419/150959226-5063c584-978c-4a98-8b9f-47ee78ff132e.png)
Router:
![image](https://user-images.githubusercontent.com/41856419/150959329-b008fe95-f83f-4801-876b-b94ff37e35bb.png)

**Comment by Pascal51882** [comment]
Could it be that Docker has some problems with bridged networks? After choosing the default Unraid template + host as network adapter it works now. Unfortunately this is not optimal because I can't enable UPNP on the host for security reasons. According to the port scanner only port 4449 is open and 1194 is closed, although both are enabled. My UDP range  10.000-10.100 is also closed.

**Comment by Pascal51882** [comment]
I changed it back to bridge network after 15 working days as network type host. Bridge ist just better because of the extra ip address. Can you check if its 100% up? Cant tell at the moment, because I dont see any traffic at the moment.

**Comment by etherunit** [comment]
It seems to be up. Your node is getting test connections and the are going through.
![Screenshot 2022-03-09 at 08 53 06](https://user-images.githubusercontent.com/60128746/157388295-eccc8a31-39c8-4b7c-ad77-5e3ca9f3b8e8.png)
