### ISSUE TITLE
Dashboard counters all zero'd out.

### ISSUE THREAD

**Issue by johnhighway** [mysteriumnetwork/node#4657]
**Describe the bug**
All the cumulative counters "Session Time", "Bytes Transferred", "Sessions", "Unique Clients" have all zero'd out.

**To Reproduce**
On one of the main dashboards, it shows zero despite having 504 sessions and data transfer of 27Gb. When there's a client actually connected and transferring data, the counters update with active connections. When that client disconnects, all counter information related to that client disappears from the dashboard. If there was one client and he/she disconnects, it reverts back to zero counters.

**Expected behavior**
Loading the page should show cumulative totals for each category.

**Screenshots**
<img width="1356" alt="mysterium-node-01" src="https://user-images.githubusercontent.com/33267537/150829303-e28fd9ce-8398-4f19-89f5-06af17e1a898.png">
<img width="1346" alt="mysterium-us-01" src="https://user-images.githubusercontent.com/33267537/150829306-bde64d1d-07f0-4a1f-98be-5c4657f34c9b.png">
<img width="1346" alt="mysterium-us-02" src="https://user-images.githubusercontent.com/33267537/150829307-665bc04e-63dc-4dce-94d8-b64ffd279b26.png">
<img width="1336" alt="mysterium-jp-01" src="https://user-images.githubusercontent.com/33267537/150829308-c67bf984-b5e4-4ecc-8a89-6f3ecfb96520.png">
<img width="736" alt="Screen Shot 2022-01-21 at 8 24 14 AM" src="https://user-images.githubusercontent.com/33267537/150829309-dc4f6495-590b-46fb-966f-baf5e271b521.png">

**Environment (please complete the following information):**
 - Node version: [1.1.9]
 - OS: Ubuntu 20.04.3 LTS (3x) & Raspbian GNU/Linux 10 (buster)
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A
 - Your identity (if applicable): 
     0x1817717e3538205bff2b0168014c380aa531aefa
     0xf4d33812214ad4ce1b51b4985ce81a607b699683
     0x74c8e8cd833caddc79c7a7f3310ef3dbf8a260e8
     0x06e695d811bd08e37a216c43826ab8e512053845

**Additional context**

**Comment by etherunit** [comment]
We have experienced stats issue in 1.1.8-1.1.9 node versions. Could you please update your node and check if problem remains?

**Comment by johnhighway** [comment]
1.2.2	Ubuntu 20.04.3 LTS	hosting (23.239.5.120)

Appears to have resolved the issue with zeroed
<img width="1122" alt="Screen Shot 2022-01-25 at 2 52 41 AM" src="https://user-images.githubusercontent.com/33267537/150934539-d060fddd-c34c-49b2-acdf-e3d34bf10c37.png">
 out counters.
