### ISSUE TITLE
withdraw issue + error 

### ISSUE THREAD

**Issue by Exepion** [mysteriumnetwork/node#4659]
Hi, 

I've tryed to make a withdraw yesterday of 120 myst. but they didn't come to my wallet and totaly disapear from node at first.
![2](https://user-images.githubusercontent.com/18357427/150987723-4983d62a-9b68-44bf-85db-6d9e1936073b.png)
![1](https://user-images.githubusercontent.com/18357427/150987726-f7020ef7-07ba-4a3f-99a5-f31d7b7ef749.png)

then i've try to do what a telegram admin ask. Do another withdraw. but : 
![2022-01-25 14_18_19-](https://user-images.githubusercontent.com/18357427/150987828-fd67e05f-30cf-41ca-9482-90bc5299b494.png)

My node is  0xc51aef2b95d33183d4e806ee81b5c1d4b5e9fb42	

can you help ?

**Comment by Guillembonet** [comment]
if you try again does it work now?

**Comment by Exepion** [comment]
> if you try again does it work now?

nope

**Comment by Guillembonet** [comment]
can you send your node's logs so I can see what is going on? You can do it with the bug report button on node ui. Write something like for Guillem in the description and I'll try to see what's going on tomorrow!

**Comment by Exepion** [comment]
Done. But >< 

the withdraw finaly came when i try to withdraw 29 other myst tonight. But not the 29 myst withdraw, the older ><
![2022-01-25 22_36_04-Window](https://user-images.githubusercontent.com/18357427/151064035-77ec2fdb-d120-4684-9e1b-ca2f06a91f6f.png)

**Comment by Guillembonet** [comment]
The maximum withdrawal amount is 99 MYST (limited in the smart contract), the next time you withdraw you should get the rest. Let me know if it is solved!
