### ISSUE TITLE
Allow node operator to withdraw by calling contract function directly

### ISSUE THREAD

**Issue by msvanvertloo** [mysteriumnetwork/node#4660]
Right now, withdrawals have to be done through the transactor service, and the contract function that actually handles the payout (HermesImplementation.payAndSettle) requires a signature from the operator of the HermesImplementation contract (i.e. not something the node operator can do).  If node operators have MATIC and are willing to pay actual transaction fees in that currency, don't force them to pay MYST (at a terrible exchange rate calculated opaquely by transactor service).

**Comment by tomasmik** [comment]
There you go: https://github.com/mysteriumnetwork/payments-smart-contracts/blob/master/contracts/ChannelImplementation.sol#L125
