### ISSUE TITLE
Cannot report an issue using report bug button in Node UI

### ISSUE THREAD

**Issue by iovestor** [mysteriumnetwork/node#4663]
**Describe the bug**
Cannot report an issue using report bug button in Node UI

**To Reproduce**
1. Go to Node UI
2. Click on the bug button
3. Enter a message under 'Your message' and click 'SEND'
4. See error 'could not create github issue: invalid character '<' looking for beginning of value (path="feedback/issue")'

**Expected behavior**
A new github issue with relevant logs attached is created.

**Screenshots**
![Myst_ReportIssue](https://user-images.githubusercontent.com/91537616/151186577-fb2f8440-4f9a-4f03-a055-b7c07634fbc4.jpg)
![Myst_ReportIssue2](https://user-images.githubusercontent.com/91537616/151186615-9033cf01-890d-46a3-9232-1328ff0dcfcf.jpg)

**Environment (please complete the following information):**
 - Node version: mainnet (1.1.9-b323bbed)
 - NodeUI version: 1.6.2
 - OS: Ubuntu 20.04.3 LTS
 - Your identity: 0x5f9640129e7cbf5e0c1bc73226bfda66dbf4654b
 - Your Payment Channel: 0xAbe54dd9e6DCC5137d645eb0baEff5951057aDBD

**Comment by Guillembonet** [comment]
Are you able to open the intercom widget in the bottom left?

**Comment by Guillembonet** [comment]
Thanks, I will check it tomorrow!

**Comment by Guillembonet** [comment]
Also, it would be great if you could you manually upload the logs somewhere and provide a link!

**Comment by iovestor** [comment]
The intercom widget is working in Node UI and not working in mystnodes.com. How do I get the logs?

**Comment by Guillembonet** [comment]
https://docs.mysterium.network/node-runners/setup/linux/#save-logs-to-a-file
Contact me on discord and I'll be able to guide you better, my username is bunetz#7324

**Comment by iovestor** [comment]
I've uploaded zipped logs (password protected) on https://c.mail.com/@766510613663850349/vpwlautXSLeDCb_-nGvN4A

**Comment by Guillembonet** [comment]
okay so, try updating to the latest version and let me know if it is still happening for you. Sadly I can't replicate the issue and I see no obvious error, might be because we were doing some changes to feedback and the service was down for some time yesterday. About your other issue, transactor issues should be much better now so the next time you withdraw you will receive the "lost" myst.
