### ISSUE TITLE
Node does not receive any traffic other than test sessions when whitelisted.  

### ISSUE THREAD

**Issue by overland-liquor** [mysteriumnetwork/node#4664]
**Describe the bug**
After a very productive december (and pre-mainnet), my whitelisted node is getting no traffic other than test sessions when whitelisted.  If whitelist is disabled, normal sessions work - so i know the node is functional.  mystnodes also lists it as online.

it looks like this started on 12/29.

**To Reproduce**

enable whitelisting

**Expected behavior**
Id expect _some_ traffic.  I know whitelist isnt as productive as unrestricted, and theres nothing at all going through.

**Screenshots**
![image](https://user-images.githubusercontent.com/97700468/151208954-7d7a3908-1064-4606-a457-1ef195d37993.png)

**Environment (please complete the following information):**
 - Node version: 1.2.2, and several previous versions
 - OS: debian 10
 - Docker (if applicable): Docker version 20.10.12, build e91ed57, mysteriumnetwork/myst   latest          4393e96a92e0
 - Your identity (if applicable): 0x397818e19ab5a2ea26daa00f66bef6881e195065

**Comment by etherunit** [comment]
Whitelisted mode will delist your service proposal from discovery (&app). It's normal not to get normal sessions with whitelisting switched on.

**Comment by overland-liquor** [comment]
right - the strange bit is i was getting lots of traffic until 12/29 while whitelisted.  then it all disappeared and its been _only_ test sessions since unless i turn whitelisting off.

**Comment by overland-liquor** [comment]
er, im not sure i understand why this was closed - the original question is still open.  im observing distinctly different behavior without making changes.  i know my node is configured correct.

why the sudden and dramatic difference in operation on the 29th?  i understand volume wont be the same, and this is a huge difference.  being delisted, i have no way to check if its correctly participating in whitelisting without getting traffic.  can you at least confirm that?

**Comment by etherunit** [comment]
Can you please elaborate more on your last question? thanks!

**Comment by overland-liquor** [comment]
when a node is whitelisted, its not visible in the API.  because of that i cannot verify myself it is correctly participating in serving whitelisted traffic. because of the dramatic difference in traffic pre/post 12/29, i contacted support and they indicated my node may be in some nonfunctional state network side and suggested i open a ticket to check.

**Comment by adinetech** [comment]
Your whitelisted node will be still visible here with `"whitelist":true`- https://discovery.mysterium.network/api/v3/proposals-metadata

**Comment by overland-liquor** [comment]
ok thats helpful.  i can now see that my node is present.

any further information as to what happened on 12/29 to cause the drastic change in traffic levels?
