### ISSUE TITLE
Several Node registration fails credit card payment

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4670]
**Describe the bug**
"I have a problem with the payment when setting up my server for running a vpn node i put my wallet address which was : 0x8D7D7B3D493F164d5D73B0A266eBD2cAC2b3f2bf and used credit card for payment but weirdly it was stuck on 0.000 and then didnt pass i tried to retry didnt asked for payment again and when i checked my credit card the payment was taken from it"

"my registration failed, and i have bought the myst token using credit card, and i dont receive it yet"

"Hello, i keep having Unfortunately, node identity registration failed. Please click RETRY button to try again. Although i deposit the myst fee. is there any issue ? thank you"

"Hello there, been trying to register a new identity but its being stuck on "Your identity is being registered, please be patient...
0x58a8b8f0fca6a3b642052e92b5cae6591a58f4d6" despite being listed as created there
https://transactor.mysterium.network/api/v1/identity/0x58a8b8f0fca6a3b642052e92b5cae6591a58f4d6/status "

**To Reproduce**
1. Go to 'set up a node'
2. Click on 'Buy MYST with credit card or debit card'
3. Scroll down to 'Make payment'

**Expected behavior**
Node should register after payment is successful and completed.

**Screenshots**
<img width="871" alt="Screenshot 2022-01-27 at 11 32 49" src="https://user-images.githubusercontent.com/84313603/151351052-919d3aab-3ec6-499e-9fc2-62af544f58af.png">
<img width="443" alt="Screenshot 2022-01-27 at 11 32 59" src="https://user-images.githubusercontent.com/84313603/151351063-d757e921-9633-4b52-8f86-4ba3e1a92eb5.png">
<img width="990" alt="Screenshot 2022-01-27 at 11 33 14" src="https://user-images.githubusercontent.com/84313603/151351064-83629ba1-c650-4201-8ad4-45718ae4ab88.png">
<img width="439" alt="Screenshot 2022-01-27 at 11 33 36" src="https://user-images.githubusercontent.com/84313603/151351068-adff4d02-a80e-486b-bd83-c5d07aa70fc0.png">
<img width="442" alt="Screenshot 2022-01-27 at 11 34 48" src="https://user-images.githubusercontent.com/84313603/151351217-3e7c243d-5c8f-44f2-b3d8-66162aaae6db.png">

**Comment by avmorales25** [comment]
Hi there, i have the same issue. I've waited over 10 minutes to get my MYST credited to my account for the network registration and still have not receive anything. I tried again, paid through cardinity and waited hours, and still didnt get the MYST. Could you help me out?
<img width="1176" alt="Screen Shot 2022-01-27 at 00 14 41" src="https://user-images.githubusercontent.com/98541121/151392830-b9b9b636-7e4f-4648-8129-b283f7586caa.png">
<img width="760" alt="Screen Shot 2022-01-27 at 00 14 47" src="https://user-images.githubusercontent.com/98541121/151392889-4d2debe5-d816-4330-81f0-afc9397c3f67.png">

**Comment by dmb4ur** [comment]
I also go through with the payment, confirm it with the VISA app on my phone and see the "Secure Checkout - Payment approved" page. I wait a second and then get a "Forbidden" warning, while on the network registration page the payment is still pending. Tried twice now.
![Forbidden](https://user-images.githubusercontent.com/96404846/151396375-e76c65b9-9dc0-4f7e-b82f-7dcf1273016c.png)
![payment](https://user-images.githubusercontent.com/96404846/151396384-d1e5f8e6-f3f9-47c3-9892-d45d981dae1b.png)
.

**Comment by avmorales25** [comment]
Hi there, finally it did work and got my MYST. However i had to delete the docker container and create a new one, so i have to go through the whole process of claiming and buying MYST again. Payment confirmation successful however it's been a while and i still don't get my credits. Hopefully i will get it later on. So my question is that everytime that a docker container is created it needs to run the same verification process??

**Comment by xamidovic** [comment]
![Screenshot from 2022-01-28 07-32-40](https://user-images.githubusercontent.com/32868313/151499504-a9c07f32-9ba4-4870-8e95-cd83acbbbdb0.png)
Installed it on linux, payment confirmation successful, everything went well but at some point it decided to let me know that node registration failed.

**Comment by etherunit** [comment]
@xamidovic Can you please try to restart your node?

**Comment by xamidovic** [comment]
> @xamidovic Can you please try to restart your node?

Did... seams like it works now. But still can't find it on etherscan

**Comment by SpettV** [comment]
> @xamidovic Can you please try to restart your node?

Lol thanks cant believe I didnt try that - worked
