### ISSUE TITLE
Mystnodes.com : Allow naming hosts / indicate active connection

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4672]
**Is your feature request related to a problem? Please describe.**
When running multiple nodes, it is difficult to distinguish by ip which node has issues(like showing offline in mystnodes)

**Describe the solution you'd like**
Allow Noderunners to either designate a nickname for nodes in nodeUI or in mystnodes.com. I for example assigned dns names for my nodes so I can easily cycle through them and check that everythings right.
It would also be neat to have a little more stats on mystnodes com, like active connection indicator, active connection count, daily connections(with a graph maybe?), Traffic consumption etc

**Describe alternatives you've considered**
right now I am running a script on each node checking for the above data and using email to notify a mailbox of node going down, connection events etc. not really something for everyone and it generates a lot of messages for my 15 nodes

**Comment by CharlyEmpereurmot** [comment]
It is now possible to enter names manually for the nodes displaying in mystnodes.com
