### ISSUE TITLE
Settling Unsettle Earnings Yields Error

### ISSUE THREAD

**Issue by johnhighway** [mysteriumnetwork/node#4673]
**Describe the bug**
I have 'settled' my unsettled earnings from my many nodes and some are resulting in Hermes error.
* Fail with error 'Hermes: amount to settle should cover transactor fee'
Some nodes are resulting with errors like above and other nodes are successful in transferring.

Before I tried settling, I made sure that the transfer fee would be low enough to cover my transfer.

**To Reproduce**
Sporadic error results.

**Expected behavior**
A successful transaction.

**Screenshots**
![Screenshot 2022-01-27 100600](https://user-images.githubusercontent.com/33267537/151385907-25d320a1-3580-4cff-a818-be7ff4ead587.png)
![Screenshot 2022-01-27 100709](https://user-images.githubusercontent.com/33267537/151385909-5b96d4fd-b060-4385-b672-7d859ce5f914.png)

**Environment (please complete the following information):**
 - Node version: 1.2.2
 - OS: Ubuntu 20.04.3 LTS (x3), Raspbian GNU/Linux 10 (buster)
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A
 - Your identity (if applicable): 
0x1817717e3538205bff2b0168014c380aa531aefa
0xf4d33812214ad4ce1b51b4985ce81a607b699683
0x74c8e8cd833caddc79c7a7f3310ef3dbf8a260e8
0x06e695d811bd08e37a216c43826ab8e512053845

 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
This also happened when I tried to perform a withdrawal

**Comment by Guillembonet** [comment]
can you provide the channel address of the nodes that failed?

**Comment by tomasmik** [comment]
Please refer to this and make sure it's not a duplicate: https://github.com/mysteriumnetwork/node/issues/4679

**Comment by johnhighway** [comment]
Thanks.
