### ISSUE TITLE
not enough sessions 

### ISSUE THREAD

**Issue by Sahilahmed84** [mysteriumnetwork/node#4674]
I dont get enough sessions at all, by now i have 21 unique clients in which i only transfered 656mb of data, i just get test sessions/clients and few clients, please look into this issue. i keep my node on for 5-6 hrs [everyday
<img width="652" alt="Screenshot 2022-01-27 at 8 38 25 PM" src="https://user-images.githubusercontent.com/62053196/151388350-ca0840e9-dedb-4eb0-b518-ff1125798f39.png">
<img width="637" alt="Screenshot 2022-01-27 at 8 39 46 PM" src="https://user-images.githubusercontent.com/62053196/151388356-3d4c880f-8359-4e2c-b194-a7eb2c7acfd9.png">
.

**Comment by veldspar** [comment]
if you only run your service for 5-6hrs a day, dont expect worlds income. this isnt a get rich quick scheme. Income mainly depends on the quality of your node, aka how reliably(conttinouus) is it online, how good is the connection quality, is the node behind a nat that restricts some clients from connecting, your bandwidth and your IPs worth. let the node run continous, and give it time. Or maybe advertise for mysterium so more people use it(and thus pay for it), but dont expect to start the node software and be filthy rich by the end of the day

**Comment by Sahilahmed84** [comment]
> if you only run your service for 5-6hrs a day, dont expect worlds income. this isnt a get rich quick scheme. Income mainly depends on the quality of your node, aka how reliably(conttinouus) is it online, how good is the connection quality, is the node behind a nat that restricts some clients from connecting, your bandwidth and your IPs worth. let the node run continous, and give it time. Or maybe advertise for mysterium so more people use it(and thus pay for it), but dont expect to start the node software and be filthy rich by the end of the day

if you understand properly, i never mentioned about earning, my issue is all about NOT ENOUGH SESSIONS, if you have knowledge about it, help it out, don't preach about getting rich in a day

**Comment by veldspar** [comment]
well, there can only be as many sessions as there are people needing vpn services. theres not much you can do to increase your sessions/clients/etc except promote mysterium.

**Comment by Sahilahmed84** [comment]
> well, there can only be as many sessions as there are people needing vpn services. theres not much you can do to increase your sessions/clients/etc except promote mysterium.

Alright, thank you !
