### ISSUE TITLE
$SERVICE_OPTS (code=killed, signal=SEGV) - killed service mysterium-node - won't start

### ISSUE THREAD

**Issue by vedranius** [mysteriumnetwork/node#4676]
When I installed a mysterium on my RPi 0 I get this error:
```
       Docs: https://mysterium.network/
    Process: 602 ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS service --agreed-terms-and-conditions $SERVICE_OPTS (code=killed, signal=SEGV)
   Main PID: 602 (code=killed, signal=SEGV)
```

Running latest Raspbian Lite OS.

Any idea what's wrong?

Thanks!

**Comment by veldspar** [comment]
Give us the output of `journalctl -fu mysterium-node`

Also, doing a plain install on Raspbian sometimes messes with DNS resolver of the os, leading to failure of resolving host names and that in turn causes Mysterium to fail starting(and everything else internetwise depending on DNS)
Therefore try `ping google.com` and see if that works

**Comment by etherunit** [comment]
Even better give us the node logs. Login to your Node UI and click the "Bug" button on the left side panel or
Report issue directly to Mysterium support using API service: `curl -X POST --data '{"email":"yourmail@mail.com","description":"write description here"}' localhost:4050/feedback/issue`

**Comment by vedranius** [comment]
Just to add.
I've done an new fresh install on RPi 400, and that worked fine with the same process I've done on RPi 0.
After I've added the RPi 400 to the myst nodes and everything worked, I've removed the SD card from it and put it in RPi 0.
Myst service didn't won't to start, same as the above error.
I'll copy logs here later.
Thanks!

**Comment by GrzegorzWalewski** [comment]
Hi, I have similar problem. I'm on Raspberry Pi 3B, latest Raspbian Lite OS. From `journalctl -fu mysterium-node` I get:
```
Jan 30 09:38:07 raspberrypi systemd[1]: Started Server for Mysterium - decentralised VPN Network.
Jan 30 09:38:07 raspberrypi systemd[1]: mysterium-node.service: Main process exited, code=killed, status=11/SEGV
Jan 30 09:38:07 raspberrypi systemd[1]: mysterium-node.service: Failed with result 'signal'.
Jan 30 09:38:12 raspberrypi systemd[1]: mysterium-node.service: Scheduled restart job, restart counter is at 4217.
Jan 30 09:38:12 raspberrypi systemd[1]: Stopped Server for Mysterium - decentralised VPN Network.
Jan 30 09:38:12 raspberrypi systemd[1]: Started Server for Mysterium - decentralised VPN Network.
Jan 30 09:38:12 raspberrypi systemd[1]: mysterium-node.service: Main process exited, code=killed, status=11/SEGV
Jan 30 09:38:12 raspberrypi systemd[1]: mysterium-node.service: Failed with result 'signal'.
```
I can ping google.com. And I can't access Node UI as node is not running.
It's fresh install and I tried installing it few times now, without success.
