### ISSUE TITLE
BUG → Withdrawal problems on the Mysterium Network node (seems to be an ISSUE for several days, please fix it ASAP)

### ISSUE THREAD

**Issue by 2dRYoMz7XKx3Bii** [mysteriumnetwork/node#4688]
---

Describe the bug ↓

I can not withdraw ... every time I want to go to do the procedure I always get the error below

![image](https://user-images.githubusercontent.com/77741077/151824838-db83bc99-956a-48a9-bc75-1a68c085459b.png)

---

Steps to reproduce the behavior ↓
1. Go to your Mysterium Node
2. Click on 'Withdraw'
3. Wait for the error to pop up (down below on the right)
4. Evaluate the error

---

Expected behavior ↓
Usually the procedure takes a few seconds to be processed and completed, but this time it doesn't and it doesn't start at all.

---

Environment (please complete the following information) ↓
 - Node version: mainnet (1.2.2-7ebc1c52)
 - Node coordinates: 0x9ba274ab7cb96acd3993a0771cb2af0dea774690
 - OS: Raspbian GNU/Linux 10 (buster)
 - Your identity (if applicable): 0x9ba274ab7cb96acd3993a0771cb2af0dea774690
 - Payment (top-op) reference (if applicable): 0x9ccA2016D7363a028a55a72B777b6C4B67B74754
 
 ---
 
 That's also another github member that is having the same problem, here it is his report... take a look → #4687

**Comment by veldspar** [comment]
I already reported on it and gave a workaround here: https://github.com/mysteriumnetwork/node/issues/4671

It's a rounding error

**Comment by tomasmik** [comment]
After investigating this and talking with a few members of the community it seems that there is something wrong with the UI (https://github.com/mysteriumnetwork/node/issues/4690) and it could also be a rounding issue.

**Comment by 2dRYoMz7XKx3Bii** [comment]
---

> I already reported on it and gave a workaround here: #4671
 
> It's a rounding error. Try reducing the withdrawal amount by at least 0.0000001 MYST and it should go through
 
 ---
 
↑ I confirm that this way above works, so for anyone who has problems, here is your resolution ↑

**Comment by Donatas-MN** [comment]
Rounding issue was fixed with latest 1.2.4 Node release. Sorry for the inconvenience.
