### ISSUE TITLE
Sometimes withdrawal is not possible using NodeUI but works in CLI

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#4690]
Reported by multiple people. UI throws an error, CLI works like a charm.

**Comment by tomasmik** [comment]
This could be related: https://github.com/mysteriumnetwork/node/issues/4671

**Comment by Jhobean** [comment]
I confirm CLI worked.
error on the UI is this one: 
![image](https://user-images.githubusercontent.com/51728381/151868211-465f4bd1-7c88-4433-993f-67f272d7be13.png)

**Comment by Donatas-MN** [comment]
Rounding issue was fixed with latest 1.2.4 Node release. Sorry for the inconvenience.
