### ISSUE TITLE
No Error Message Regarding > 99 MYST Withdrawal

### ISSUE THREAD

**Issue by rpmurph** [mysteriumnetwork/node#4691]
**Describe the bug**
Yesterday evening I tried to withdraw ~311 MYST and only ended up getting ~99. I see the GitHub ticket instituting a limit on each withdrawal now. I had not seen it before. I also did not receive an error message when I put in 311 MYST as the amount. I am running on am AVADO. Are the rest of those funds lost now?

**To Reproduce**
1. Go to Wallet
2. Click on Withdraw
3. Enter Amount > 99 MYST on the Polygon Network
4. Confirm withdraw

**Expected behavior**
Expect an error message to appear that stops the transaction from processing > 99 MYST.

**Environment (please complete the following information):**
 - Node version: 1.1.16
 - OS: AVADO
 - Desktop app version: 0.0.62
 - Your identity: 0x8c27c39bede6c32f8e182641fbec86c10f3655a7
 - Polygon TxID: 0x63907ee5ab78c7f31b5a220660e40f4d6bc2d6b225806d30869dc91b5c0315b1

**Comment by tomasmik** [comment]
Could you please confirm your node version? That should not be possible since version 1.1.10 and version 1.1.16 doesn't really exist.

**Comment by rpmurph** [comment]
Yes, correction from the AVADO Dapp it says the version is Based on: 1.1.6

From the https://mystnodes.com/nodes dashboard it says the version is 1.0.5

**Comment by tomasmik** [comment]
Will close this now then.
