### ISSUE TITLE
Cashing Out Issue

### ISSUE THREAD

**Issue by B08** [mysteriumnetwork/node#4692]
**Describe the bug**
Made my first cash out absolutely fine, no problems (to my Android MEW Wallet)

**To Reproduce**
Knowing everything was in order I waited and a couple of weeks and cashed out again.
- Clicked 'Withdraw' from my web dashboard.
- Checked chain was still selected as 'Polygon Mainnet'
- Clicked 'Withdraw'
- Waited.. Noticed after a few minutes my withdraw balance had decreased.
- Waited.. After two days, I started making enquiries. Initially to Chindalath@MyEtherWallet (very helpful) and also to Isaac@Mysterium (also helpful, he instructed me to create this 'bug report')
- Noticed my 'Withdraw' page it still only listed the details of my first withdrawal.

**Expected behaviour**
I expected my MEW wallet balance to be updated with the balance from this second withdrawal.

**Screenshots**
Don't think screenshots of this are really relevant?

**Environment (please complete the following information):**
- Node version: mainnet (1.0.14-b16259ef)
- NodeUI version: 1.1.5
- OS: Windows 10 (withdrawal request) or Ubuntu Server VM (application)
- Desktop app version (if applicable): N/A
- Docker (if applicable): N/A
- Your identity (if applicable): 0xac03b51f12ec99f92ea32360abe471535c378a2f
- Payment (top-op) reference (if applicable): N/A

**Additional context**
Obviously my balance has gone somewhere, I'm interest to find out where and how it got to this other place. We're only talking about 0.7 MYST / €0.20c but it's the principle of the matter.

**Comment by veldspar** [comment]
go to nodui settings, copy the payment channel id(where it says 'this can be used to topup') and go to polygonscan.com to see transactions made to/from your node

**Comment by B08** [comment]
OK, thanks for the quick reply Veldspar. We have something interesting here.. When doing as you ask, I can see two transactions in Polygonscan.com.. both my deposits. Which total 1.7924264 MYST. However on my 'Withdraw' page on my Node UI, it's only showing my first withdrawal in the box which states "Your last transaction:" Additionally in my wallet I've only got the 1st transaction too.. Image attached.. [Image attached..](https://i.postimg.cc/50cFLdFz/Screenshot-20220131-203216.png)

**Comment by B08** [comment]
A couple more screen shots which may be helpful? - [NodeUI](https://i.postimg.cc/j2bg8FBw/node.jpg) & [PolygonScan](https://i.postimg.cc/RC7b3vnc/Polygon.jpg)

**Comment by veldspar** [comment]
have you tried restarting the service? I noticed recently that withdrawals will be stuck. node restart sometimes helps, sometimes it helps to do another withdrawal.

**Comment by B08** [comment]
Unable to do another withdrawal yet, but I'll try restarting the VM. Thanks in advance, I'll let you know what happens.
