### ISSUE TITLE
Withdraw issue

### ISSUE THREAD

**Issue by Anar9686** [mysteriumnetwork/node#4695]
**Describe the bug**
My withdrawal seemed to have failed on the blockchain and there it said that my money was returned but i dont see it anywhere

**To Reproduce**

**Expected behavior**
transfer said money into my wallet or mysterium site wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/67626474/151939604-684739db-1a5d-42b0-bbf9-1505ca8dc9e7.png)

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by tomasmik** [comment]
You have not provided an identity, nothing I can answer really.

Refer to this for explanation on the error: https://github.com/mysteriumnetwork/node/issues/4679
