### ISSUE TITLE
Pilvytis disabled some users automatically

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4696]
**Describe the bug**
Pilvytis disabled some users automatically tonight.

At 00:15 UTC we've run a usage limit reset for all users. A guess would be that this might be related.

**Comment by Guillembonet** [comment]
Can we get some more info on this? What do you mean by users getting disabled, you mean that the disabled field in the user was set to true just by changing the user limit?

**Comment by Guillembonet** [comment]
I investigated this and didn't find anything that could cause this behaviour, so I will need some more info if you have it :)

**Comment by portalsdevs** [comment]
@Guillembonet what is your Discord id?

**Comment by tomasmik** [comment]
Answered personally.

**Comment by Guillembonet** [comment]
Hey, we investigated with @tomasmik and made sure this can't happen again. Sadly, we did a release just before you reported it so we didn't have the logs and we can't be 100% sure of what happened there. If it happens again report it so we can investigate more. I'm closing this for now, if you need anything else you can reopen it!

**Comment by portalsdevs** [comment]
thank you
