### ISSUE TITLE
Node is online, Node UI shows offline

### ISSUE THREAD

**Issue by theluke** [mysteriumnetwork/node#4698]
**Describe the bug**
- My node UI stopped working, it does not show any data about my node, nor the previous connections. IT is reporting the node as `offline`.
- The node is online, I used the `myst cli` commands to run various tests and I can see the node is alive when I run `sudo journalctl -fu mysterium-node.service` 
- I have had various connections and it all worked fine for a few days

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `192.168.1.xxx:4449` : **all services offline**
2. Go to `https://mystnodes.com/nodes` : node appears online

**Expected behaviour**
The node UI should reflect the correct status of the node

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.2.2
 - OS: raspbian bullseye
 - Your identity : `0x986e44106b8e23992cf26b8e82898402454a928a`

**Additional context**
I keep seeing these messages:

```
Could not update orders error="Get \"https://pilvytis.mysterium.network/api/v2/payment/orders\": read tcp 192.168.1.50:54205->51.15.116.186:443: read: connection reset by peer" identity=0x986e44106b8e23992cf26b8e82898402454a928a
```

```
Failed to get current location for proposal, using last known location error="failed to execute request: Get \"https://location.mysterium.network/api/v1/location/\": read tcp 192.168.1.50:48463->51.15.116.186:443: read: connection reset by peer"
```

```
Feb 01 14:54:21 raspberrypi myst[679]: 2022-02-01T14:54:21.803 WRN communication/nats/connection_wrap.go:105 > NATS: disconnected error="read tcp 192.168.1.50:35243->51.15.72.87:4222: read: connection reset by peer"
```

I have the logs available, but I do not think it is safe to post them here, right?

**Comment by etherunit** [comment]
@theluke It's ok to attach your zip'ed logs there. Without logs, it's hard to say what's wrong there.

**Comment by theluke** [comment]
thank you @etherunit attached the log.
[theluke.log](https://github.com/mysteriumnetwork/node/files/7985200/theluke.log)

**Comment by theluke** [comment]
Update on the issue: this morning I could see some information in the node UI, but as soon as I refreshed the page, all values reset back to zero.
What is also weird is that I have really few connections, even if I have UpnP, ports open and mapped and 1Gbit/200Mb fiber, always on.

**Comment by Captmicka** [comment]
Hello,
I'm joining this thread because I have the same behavior on a new node install on a Raspberry (Myst image taken).
Node version 1.2.4 on a Raspbian 10.

@theluke I don't know about you, but I can briefly see the dashboard refresh and show the information when I restart my raspberry.

**Comment by etherunit** [comment]
Do you still experience this problem on your end?

**Comment by Captmicka** [comment]
HI @etherunit for me this problem is still there, I tried to log in this morning and I still have the information not initialized at first login.
I have to wait 20 minutes and refresh the browser to get all the information.

**Comment by isaackielma** [comment]
@Captmicka Can you please submit your app logs so we could investigate this further with our engineering team? 

 

Access the "Help" tab section on the title bar (top of app window). Then, 'Report Bug'.

 

Please note  that description and application logs will be attached to the issue. Logs may include sensitive information, such as IP address and location. It will be only accessible and used by the engineering team to address the issue you are reporting.

 

After doing so, please let us know here

**Comment by theluke** [comment]
@etherunit my node still has the same issues. It is online, but the UI shows offline.
My identity is 0x986e44106b8e23992cf26b8e82898402454a928a

> » healthcheck
[INFO] Uptime: 810h40m7.384563296s
[INFO] Process: 19974
[INFO] Version: 1.6.0
[INFO] Branch: 1.6.0. Build id: 502802993. Commit: 50375323
