### ISSUE TITLE
Can't withdraw MYST balance. 

### ISSUE THREAD

**Issue by edwin34** [mysteriumnetwork/node#4700]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.2.2
 - OS: Ubuntu 20.04.3 LTS
 - Your identity (if applicable): 0x37b989a766baf61f38ea9a9391a447cea8de79d7
 - 
**Additional context**
when I try to withdraw my balance, it says "There was an error processing your request"
![cant withdraw](https://user-images.githubusercontent.com/36815243/151969551-0cee7bbf-547c-48f1-8877-512f29808279.png)

Apart from that, when I use the report issue button, that too also doesn't work. It generates an error could not create Github issue.
![GITHUB Issue](https://user-images.githubusercontent.com/36815243/151969943-f7cf71d3-409c-4943-9b2b-3050b08e9885.png)

**Comment by Donatas-MN** [comment]
This issue has been fixed with Node version 1.2.4. Sorry for the inconvenience.

**Comment by edwin34** [comment]
Thanks it works now.
