### ISSUE TITLE
MYST wird nicht auf das Wallet übertragen.

### ISSUE THREAD

**Issue by TreeBoy27** [mysteriumnetwork/node#4701]
MYST wird nicht auf das Wallet übertragen.

Wenn ich auf "Withdraw" drücke überweißt er auf mein Wallet 0 MYST

**Comment by adinetech** [comment]
Translated -> 
MYST is not transferred to the wallet.

When I press "Withdraw" it transfers 0 MYST to my wallet

**Comment by TreeBoy27** [comment]
I didnt get any errors or something. Polygon Mainet is already on Metamask.
[image: grafik.png]

The transaction:
https://polygonscan.com/tx/0x7b3aea4e79541558ac43d305d7e1f0c713db8226126f25e5880c0239e76ec837




Am Do., 3. Feb. 2022 um 16:58 Uhr schrieb Donatas ***@***.***

**Comment by Donatas-MN** [comment]
Have you added MYST token to Metamask? Just adding Polygon network is not enough. See here for instructions? https://docs.mysterium.network/node-runners/payout-guide/#using-metamask-with-polygon-myst
