### ISSUE TITLE
Node registration

### ISSUE THREAD

**Issue by cybrisbob** [mysteriumnetwork/node#4703]
**Describe the bug**
I registered the node and paid the 1$, node registration came to mynodes but then the node requested registration again, not going to pay another 1$.

**To Reproduce**
No reproduction of the error as I can not register my node without paying again.

**Expected behavior**
The node should have registered as it is in my node list but did not.

**Screenshots**
Unfortunately, node identity registration failed. Please click RETRY button to try again.  is the error I get

**Environment (please complete the following information):**
 - Node version: 1.2.2
 - OS: Ubuntu
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x2100ae285e5d3756c1287ecc1c1ed986c57e486f
 - Payment (top-op) reference (if applicable): Not sure what this means.

**Additional context**

**Comment by Donatas-MN** [comment]
@cybrisbob I can see that this identity is registered. Do you still get the error?

**Comment by cybrisbob** [comment]
Hi

Yes still get error, see image below.

[image: image.png]

When I say retry it wants to pay again as the free option is greyed out.

Thanks
Jaysen

**Comment by Donatas-MN** [comment]
Looks like image was not attached. Can you try again to attach it?

**Comment by cybrisbob** [comment]
Hi

I was inline but I have attached now.

Thanks
jaysen

**Comment by Donatas-MN** [comment]
It looks like it's not appearing here on Github if you add it via email.

Can you attach it directly to this issue? https://github.com/mysteriumnetwork/node/issues/4703

**Comment by cybrisbob** [comment]
![image](https://user-images.githubusercontent.com/98826413/152692332-fe568b27-1f68-4901-af19-18677ef120f1.png)

**Comment by cybrisbob** [comment]
that is what I get

**Comment by Donatas-MN** [comment]
Can you restart your node completely? I mean turn it off and then back on.

**Comment by cybrisbob** [comment]
Hi

Restarted dont get registration warning anymore, just waiting to see if it
can display on my nodes page.
Will update later.

Thansk
Jaysen

**Comment by Donatas-MN** [comment]
Great, let us know if encounter any other issues.

**Comment by cybrisbob** [comment]
Hi

Many thanks, the node is online now and reporting in.

Kind regards,
Jaysen
