### ISSUE TITLE
Problem withdrawal from my node.

### ISSUE THREAD

**Issue by koalangebut** [mysteriumnetwork/node#4704]
I have problem withdrawing my myst. Its been over two weeks and still not receive it in my wallet

Here it the link
https://polygonscan.com/tx/0x5b743eb443a8a01193bdc0981093a5f6fe439125dc8e8742d2e87616ae4613c1
and node id is 0x1b1d5349ccf2e5989043a461915937794b6c8a60

**Comment by tchereau** [comment]
same issue here, I losed my money

![image](https://user-images.githubusercontent.com/78658872/152038677-e7bab3eb-fa09-418f-9992-1bb77882a9c4.png)

I readed when there is this error, token should be returned to the wallet, less the fee of gas
In 5 day, I didn't see the any mist in any wallet

but as Isaac answered, the funds are "safe", I will wait for a will...

![image](https://user-images.githubusercontent.com/78658872/152038784-d2531a22-2197-4043-aaad-25e8bd9533a4.png)

**Comment by Donatas-MN** [comment]
@koalangebut @tchereau what are your wallet addresses? Can you also send a screenshot from your Node wallet screen?
