### ISSUE TITLE
Withdraw fail 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4705]
**Describe the bug**
"I withdrew a small amount to my wallet to test the new polygon network. I'm a noob with crypto, anyway here it says that the payment was successful but on metamask I set up polygon mainnet and myst coin into polygon and my balance is still zero. I mean I'm not paying, just receiving. 

**Environment (please complete the following information):**
 - Node version: 1.2.3-alpine
- OS: windows 11
- Desktop app version (if applicable): latest
- Docker (if applicable): docker version 4.3.1 and image tag: latest
- Your identity (if applicable): 0x87faac111a9bbb28fef16d8e8bc46200957d55f7
- Transaction reference https://polygonscan.com/tx/0x0d00026ac3d15bfd34bf708628474c5270f48cc4e449dd257b3a908d7d46130b

**Comment by veldspar** [comment]
just guessing that this is your metamask address: `0xb03a76bcc7be030f0d86b4ab80ee273a342eefd3`it looks to me like it holds 0.0232956059216 MYST in balance. Sometimes MetaMask doesnt show MYST on its own. In this case click Import token in metamask, enter the mysterium contract `0x1379E8886A944d2D9d440b3d88DF536Aea08d9F3` as Token ID, Symbol is MYST and decimals 18.
add the token and refresh metamask(by either swiping down or closing and reopening it)
your myst should now show up in your wallet.
