### ISSUE TITLE
No settlement since Jannuary 25 !!

### ISSUE THREAD

**Issue by gus92mysterium** [mysteriumnetwork/node#4706]
I see a lot of sessions since 25/01/2022 in my node but there is no more settlement in the node UI
The last settlement was on 25/01/2022 20:17:03

Node version 1.2.2 
 - OS: ubuntu 21.10

 - My identity : 0x5bace942f0365b480c406544ab5f6d5fe5444009
 
 attached is the settlements export
 [settlement_history_1643735177028.csv](https://github.com/mysteriumnetwork/node/files/7980514/settlement_history_1643735177028.csv)

**Comment by Donatas-MN** [comment]
Auto-settlement is done when 5 MYST is reached. You can also settle manually before that by clicking this button:
![Pasted_Image_2022-02-03_17_15](https://user-images.githubusercontent.com/91055712/152371107-b28faf5f-6e2a-41ff-8783-b9b0b097397b.jpg)
