### ISSUE TITLE
Withdraw fail no data of transaction available

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4707]
**Describe the bug**
I tried to make a withdrawal from one of my device - 0xa3eabca527ab32714a92c3f575f738439c764aae - and send about 3.x MYST to my wallet - 0x17ceB24A462b3E15468Bd0a953260780dDe28115

I can see, that MYST are gone, can't see nothing in "My Wallet" on that node, and also nothing in my wallet with that address.  What should I do?

**Screenshots**
<img width="928" alt="Screenshot 2022-02-01 at 17 23 39" src="https://user-images.githubusercontent.com/84313603/152018488-59287d58-b0e7-46da-abb9-df19b8246ac9.png">
<img width="1285" alt="Screenshot 2022-02-01 at 17 24 21" src="https://user-images.githubusercontent.com/84313603/152018893-2e52a9c2-9715-4a0e-a5e4-8a529c5762ce.png">

Node version: mainnet (1.2.3-2e737829), NodeUI version: 1.7.0
debian 9
no transaction id, not even in node's wallet and not provider's wallet

**Comment by Donatas-MN** [comment]
There is no record that this node (0xa3eabca527ab32714a92c3f575f738439c764aae) would ever had balance ~3.x MYST. Is this correct identity?

**Comment by isaackielma** [comment]
I will double check with provider.

**Comment by Donatas-MN** [comment]
@isaackielma any update from provider?

**Comment by isaackielma** [comment]
After stale bot reminder, I have sent user another message in hopes of an answer:

<img width="609" alt="Screenshot 2022-05-18 at 10 28 08" src="https://user-images.githubusercontent.com/84313603/169050508-2a046896-8f70-4017-b140-fe244f802c3b.png">
<img width="607" alt="Screenshot 2022-05-18 at 10 29 07" src="https://user-images.githubusercontent.com/84313603/169050524-73e35032-98a5-451f-9b62-6b78b89a798e.png">
