### ISSUE TITLE
Cant withdraw

### ISSUE THREAD

**Issue by perlpy** [mysteriumnetwork/node#4709]
Cant withdraw funds
![myst](https://user-images.githubusercontent.com/84513397/152060509-e539e14f-bd6b-49c8-ab8e-5ab79dedf9c5.png)
s

**Comment by etherunit** [comment]
@perlpy Can you please try to restart your node before requesting to withdraw?

**Comment by etherunit** [comment]
Please refer to https://github.com/mysteriumnetwork/node/issues/4690

**Comment by perlpy** [comment]
I restarted my node and im getting the same error.

**Comment by etherunit** [comment]
Please refer to #4690. Team is investigating it.

**Comment by perlpy** [comment]
I just used the terminal commands to withdraw and it worked. Thanks
