### ISSUE TITLE
node not working properly

### ISSUE THREAD

**Issue by davidj2003** [mysteriumnetwork/node#4715]
i get this error code in the UI: Network Error (path="sessions")
also the docker container keeps turning on and off continuosly

**Comment by etherunit** [comment]
There may be a time when you encounter an issue with your node and we may ask you to submit your logs for further investigation. For us to understand what is happening we'd like you to submit your node logs.

[Login to your Node UI](https://docs.mysterium.network/node-runners/node-ui/) and click the "Bug" button on the left side panel.
