### ISSUE TITLE
Missing withdrawal

### ISSUE THREAD

**Issue by markjhealey** [mysteriumnetwork/node#4717]
**Describe the bug**
I attempted 4 withdraws 31st January, three of 100 MYST and one of c. 60 MYST.
The first three have all correctly withdrawn from my node wallet and arrived on the blockchain, but the final one has only been removed from my node wallet.

**To Reproduce**
Unable to reproduce, as the funds have been removed from my node wallet.

**Expected behavior**
I expected the withdrawal to complete, and the funds to not be removed from my node wallet until the transaction had been submitted to the blockchain.

**Screenshots**
![dashboard](https://user-images.githubusercontent.com/5901920/152163414-7e44f9ae-bb38-4da7-b388-80323a61c13e.png)
![withdrawls](https://user-images.githubusercontent.com/5901920/152163417-fbb0d174-d75a-46bf-89a8-65abb0ad88bc.png)

**Environment (please complete the following information):**
 - Node version: mainnet (1.2.2-7ebc1c52)
 - NodeUI version: 1.6.4
 - OS: Raspbian GNU/Linux 10 (buster)
 - Your identity (if applicable): 0x264194b820552adcbcb92eccde397634c8f95c2a
 - Payment Channel: 0x3E292219FA1eD5b9572BcAE3C203C15361Caf7C0
 - Withdrawal Address: 0x5c9E52488a152980cBb5852Be862a96CbeC16130

**Additional context**
Advised to raise by support on Intercom

**Comment by markjhealey** [comment]
https://polygonscan.com/address/0x5c9E52488a152980cBb5852Be862a96CbeC16130#tokentxns
No failed transactions listed.

**Comment by tomasmik** [comment]
Refer to this issue here on what happened, why and how to fix it: https://github.com/mysteriumnetwork/node/issues/4557

When it comes to the cause, we are aware of this already:
* https://github.com/mysteriumnetwork/node/issues/4631
* https://github.com/mysteriumnetwork/node/issues/4669
