### ISSUE TITLE
IP is a residential IP, but app doesn't show as a residential IP

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4721]
**Describe the bug**
ip is a residential ip. But on the app it doesn't show was a residential ip

Node ID: 0xb3c6e0a1505c...
&
0xd11626b69c03...

**To Reproduce**
1. Go to 'Apps'
2. Click on 'Ghana'
3. Scroll down to 'nodes listed'

**Expected behavior**
Nodes should show up as residential if they are residential

**Screenshots**
<img width="352" alt="Screenshot 2022-02-02 at 22 40 12" src="https://user-images.githubusercontent.com/84313603/152249725-e556b2b4-fadb-4b41-9441-3a066e2236fd.png">
<img width="634" alt="Screenshot 2022-02-02 at 22 40 48" src="https://user-images.githubusercontent.com/84313603/152249733-716565f2-fbdb-43ef-a6e0-bd0089038a67.png">
<img width="356" alt="Screenshot 2022-02-02 at 22 43 36" src="https://user-images.githubusercontent.com/84313603/152250201-cd2f79df-b66e-496a-b48d-8af08be78902.png">

**Additional context**
Waiting on full node ID and more detailed information (logs)

**Comment by Donatas-MN** [comment]
If IP address is classified incorrectly, user should submit request to Maxmind to update it: https://www.maxmind.com/en/geoip-location-correction
