### ISSUE TITLE
withdraw failed

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4722]
**Describe the bug**
 "I made transactions to my wallet and I didn't receive the tokens, what happened? I made all the correct configurations to add Polygon network to my metamask wallet and I added also the Myst token"
 
 - Node version: 1.2.4-alpine
- OS: macOS Monterey, version 12.1
- Desktop app version: 1.2.4-alpine
- Docker: 4.4.2 (73305)
- My identity: 0x169F89a8f96932D4BC2E61427D8EbcfbC02265dF

4 transaction IDs:

1 - 0xacadfc8793ec42240de8720cac1cdeeb3757420862d3ab6a4291fc2e0a7366f0
2 - 0x8891409e77724d83ba32a4b3c76283fc85843ea0f4af895dae39c85e6a7c752a
3 - 0xb8a45708e82c8e8b27cd7436c451f2379bf926365f39ce8c4860220eee296f84
4 - 0x169ff8a436ea30377e6bc8ce7474aaa30269135304597218e4fd22d3bbeb0905

**Comment by tomasmik** [comment]
> My identity: 0x169F89a8f96932D4BC2E61427D8EbcfbC02265dF

Thats not identity, thats a wallet he withdrew the funds to.

Please before creating issues, check polygonscan first: https://polygonscan.com/address/0x169f89a8f96932d4bc2e61427d8ebcfbc02265df#tokentxns
![image](https://user-images.githubusercontent.com/40318863/152359436-e2b88db8-fd8f-4172-acb9-89230b2037fb.png)

**Comment by isaackielma** [comment]
04T19:54:45.53397456Z"},{"provider_id":"0x587c8a0d3c418069798ac928cfe2ea01b0e21401","service_type":"wireguard","country":"PT"
