### ISSUE TITLE
NodeUI - Node price not refreshed in UI

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/node#4724]
**Describe the bug**
The fees reported by NodeUI and the actual proposal sometimes differ.

**To Reproduce**
1. Open NodeUI. See proposed Price/GiB. In my case, nodeUI reports 0.1228532 MYST/GiB (Price/h seems to get reported correctly, so left out here
2. Open a connection to that node by searching for its identity in the android(or desktop app). Connect to node. Price gets reported as: 0.1317/GiB
3. Refresh nodeUI to make sure we did not just miss an update: NodeUI still reports 0.1228532 Myst/GiB
4. trying to get the proposal from the very node shows that the node announced the right MYST/GiB
myst connection proposals | grep 0x64952ed1742b65ea56ef9d1445a92d9f59af0475
| Identity: 0x64952ed1742b65ea56ef9d1445a92d9f59af0475 | Type: residential | Country: DE  | Price: 0.000733/hour 0.131913/GiB |
5. This happens on multiple nodes, I just grabbed this one for testing. To make sure I get unbiased results, I connected to the node using cellular network.

**Expected behavior**
NodeUI and the network propose the same prices

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.2.2
 - OS: Raspbian, Debian bullseye, Debian Bookworm
 - Desktop app version (if applicable): latest
 - Docker (if applicable): no docker used
 - Your identity (if applicable): 0x64952ed1742b65ea56ef9d1445a92d9f59af0475

**Comment by tomasmik** [comment]
Hi, sorry for the late reply. When such an issue occurs, could you do a curl on that node to get the latest price and report if there is a missmatch: `curl localhost:4050/prices/current`?

Also about step 4. in your description, did you pull this proposal using the node that is showing the bad price or some other? This could be some cache issue, did you try to see if the prices change in UI if use incognito mode?

**Comment by Ayse-AK** [comment]
Hi @veldspar Is the issue resolved?
