### ISSUE TITLE
If gas stations are out, we should rely on nodes to suggest us prices

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#4726]

**Comment by Guillembonet** [comment]
From what I have checked it seems that there are different ways of doing this:

1. The simplest would be to rely on the already existing for go-ethereum:
```
        cl, _ := ethclient.Dial("rpc-address")
	gas, _ := cl.SuggestGasPrice(context.Background())
	tip, _ := cl.SuggestGasTipCap(context.Background())
	fmt.Println("gas:", new(big.Int).Div(gas, big.NewInt(1000000000)))
	fmt.Println("tip:", new(big.Int).Div(tip, big.NewInt(1000000000)))
	config := params.MainnetChainConfig
	bn, _ := cl.BlockNumber(context.Background())
	bignumBn := new(big.Int).SetUint64(bn)
	blk, _ := cl.BlockByNumber(context.Background(), bignumBn)
	baseFee := misc.CalcBaseFee(config, blk.Header())
	fmt.Println("base:", new(big.Int).Div(baseFee, big.NewInt(1000000000)))
	basePlusTip := new(big.Int).Add(baseFee, tip)
	fmt.Println("base+tip:", new(big.Int).Div(basePlusTip, big.NewInt(1000000000)))
	fmt.Println("diff:", new(big.Int).Div(new(big.Int).Sub(basePlusTip, gas), big.NewInt(1000000000)))
```
Also in the full node launch params we can set the calculation params to be as aggressive as we want to. And if we need different tiers (like standard, fast, rapid as in polygon's gas tracker) we could just use some multipliers. Current config is pretty similar to the standard tier.

2. Check the mempool and do some statistical calculation based on the transactions found there, this seems more complex and probably not worth it if we want to create a fallback of a fallback.

3. Something else I'm not aware of ?

**Comment by n10ty** [comment]
Fallback added to: hermes, caretaket, topperupper, transactor
