### ISSUE TITLE
Node identity import error

### ISSUE THREAD

**Issue by danieleperera** [mysteriumnetwork/node#4727]
**Describe the bug**
When I try to import an identity there is an issue which causes an error.

**To Reproduce**
1. docker run --cap-add NET_ADMIN --net host --publish "1194:1194/udp" --name mysterium-node mysteriumnetwork/mysterium-node --agreed-terms-and-conditions
2. docker exec mysterium-node myst cli identities list
3. copy the IDENTITY 
4. docker exec mysterium-node myst cli identities IDENTITY PASSWORD, copy exported key to file
5. stop container and remove old volumes
6. start again the node, new identity created
7. docker exec mysterium-node myst cli identities import PASSWORD EXPORTED_KEY_FILENAME
8. [ERROR] Failed to import identity: server response invalid: 400 Bad Request (http://127.0.0.1:4050/identities-import). Possible error: failed to import identity: invalid character 'e' in literal true (expecting 'r')

**Expected behavior**
The expected behavior is to import/backup the identity in order to recover it later.

**Environment (please complete the following information):**
 - Node version: 1.2.4
 - OS: Linux raspberrypi 5.10.92-v7+ [Raspbian GNU/Linux 11 (bullseye)]
 - Docker: mysteriumnetwork/myst:latest-alpine

Thanks

**Comment by lusine-h** [comment]
I reproduced it for me, got the same error which is described above.
![photo_2022-02-08_16-06-43](https://user-images.githubusercontent.com/60058956/152983990-75fa9ba5-7a0f-4c9f-a243-83960cc3515e.jpg)

**Comment by tomasmik** [comment]
We could not reproduce this

**Comment by lusine-h** [comment]
here are the steps:

1. `docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`
3. `docker exec -it myst myst cli`
4. `identities export <IDENTITY> <PASSWORD>`
5. `copy exported key to the .json file`
6. `docker kill <CONTAINER_ID>`
7. `docker rm <CONTAINER_ID>`
8. `docker volume rm <VOLUME_NAME>`
9. `docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`
10. `docker exec -it myst myst cli`
11. `identities import <PASSWORD> <FILE_PATH_WITH_KEY>`
