### ISSUE TITLE
Where are my Myst ? ;)

### ISSUE THREAD

**Issue by kervadort** [mysteriumnetwork/node#4729]
**Describe the bug**
I tried to send some of my myst from my node to my metamask wallet but 5 hours later, nothing arrived in my wallet. As I'm a n00b in crypto I hope I've done everything correctly. My wallet address is : 0xB1F2be99f3fC8571f10B6E9E95a0D1A59308E9A0

**To Reproduce**
I have just use the withdraw button on the page "ip address of my node:4449/?#/dashboard"

**Expected behavior**
I'm not sure where my myst are ... Somewhere but where ? ;)

**Screenshots**
Transaction ID is : 0x819f7c3f256ada130e9bde413d5079f927162e874eb745362db39eda4d5d6490](https://polygonscan.com/tx/0x819f7c3f256ada130e9bde413d5079f927162e874eb745362db39eda4d5d6490

**Environment (please complete the following information):**
 - Node UI version: 1.7.0
 - OS: raspbian 
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x51517e94e99816a8d998e77706d05052103248eb
 - Payment (top-op) reference (if applicable): 0x5734faD8b054D9C2A555201cAFb4dDB71129a1E3

**Additional context**

**Comment by veldspar** [comment]
looks like the transaction went through - polygonscan shows 3.97 MYST on that wallet. test the steps I outlined in https://github.com/mysteriumnetwork/node/issues/4705 (first response). Also make sure your wallet is on the Polygon network, not on the ethereum network

**Comment by kervadort** [comment]
Already done what you told in this answer (adding myst token)

_Also make sure your wallet is on the Polygon network, not on the ethereum network_
I'll check how to do this in metamask : I did not changed any settings after I created my wallet.

**Comment by kervadort** [comment]
Sorry for the n00b question : 
Where do you see this : _polygonscan shows 3.97 MYST on that wallet_ ?

**Comment by veldspar** [comment]
Then there you go. Metamask defaults to the Ethereum Blockchain, but Mysterium works on polygon. Don't worry, your Myst are not lost. Follow this article https://medium.com/stakingbits/setting-up-metamask-for-polygon-matic-network-838058f6d844 to add polygon to your metamask. You will see your coins after. Beware: when u send your Myst to another wallet(exchange for example) pay attention to what address you send them to. Currently i don't know any exchange that accepts Myst token on polygon, however some accept Myst on Ethereum (which you DONT have). Sending polygon tokens to an eth erc20 address will usually result in all funds lost. You can however bridge your polygon Myst to the binance smart chain(using mysts router) or Ethereum network(polygon bridge) and then deposit them to an exchange. Or you use metamask swap(or uniswap) to change them to Matic, usdc or user, which can be deposited to some exchanges(like hot it). This is usually the cheapest option to get them out of the polygon chain. Or ofc you could always hold or spend your myst

**Comment by kervadort** [comment]
Thank for your help. (I appreciate :) )

Just done what it's told (adding polygon network to metamask)
But MATIC and MYST are still at 0 

Do I need to buy some matic to get my myst on polygon ?

**Comment by kervadort** [comment]
> 

So what's your advice for the next time I want to withdraw my myst ? (as it looks complex to use myst on polygon)

**Comment by johnhighway** [comment]
@kervadort I had the same issue and I realized I used the wrong token settings in my MetaMask.

1. Make sure you're on the Polygon Network
2. Make sure that you're importing the tokens associated with Polygon Network.

Go to "Import Token"
Under Token Address, use "0x1379E8886A944d2D9d440b3d88DF536Aea08d9F3"
https://polygonscan.com/token/0x1379E8886A944d2D9d440b3d88DF536Aea08d9F3

Once you enter the token address, the rest of the form should auto-fill and click on IMPORT.

![metamask-import-mysterium-token](https://user-images.githubusercontent.com/33267537/152421738-bfa868f9-1078-4ef7-85ba-c1d6d0dd8792.png)

After that, you should see your MYST coins.

**Comment by kervadort** [comment]
> 

Great ... It works ... But I don't understand why it did not work the first time.
I was seeing Mysterium logo on the one I imported first.
But not the same logo on the one you told me to import. ... But I see my tokens ...
That's strange for me.
but it's working ... So ... 

Thank you every one for your kind help.
