### ISSUE TITLE
Start having Carthage frozen releases

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#473]
AC:
- have Carthage package with frozen releases

https://github.com/Carthage/Carthage/issues/2036
https://github.com/Carthage/Carthage#adding-frameworks-to-an-application
Initial release is done here https://releases.mysterium.network/Carthage.json

**Comment by soffokl** [comment]
Looks like we are done with it. Carthage releases available as described in [docs](http://docs.mysterium.network/en/latest/user-guide/mobile-sdk/).
