### ISSUE TITLE
Missing crypto from wallet-never received.

### ISSUE THREAD

**Issue by chatanova2003** [mysteriumnetwork/node#4730]
**Describe the bug**
A clear and concise description of what the bug is that I have withdrawn 4.15368324123842 MYST out of my account to my metamask wallet.

8/01/2022, 20:39:44
Withdrawal
0xb7e46cEFC95dfc50e280C4bA392CECF78377a8Ed
[0x3b5637ff78e1a02029f122e57d862b4feb91168a69622fd4d7f0ea31cef8cacb](https://polygonscan.com/tx/0x3b5637ff78e1a02029f122e57d862b4feb91168a69622fd4d7f0ea31cef8cacb)
0.0255462 MYST
4.1536830 MYST

**To Reproduce**
1. Go to 'Miner Dashboard'
2. Click on 'Withdraw button'
3. Wallet has 0.

**Expected behavior**
Get my crypto to my wallet.

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by veldspar** [comment]
transaction went through. the wallet holds 4.15 MYST. make sure you set metamask to polygon and followed solutions in comment 1 of https://github.com/mysteriumnetwork/node/issues/4705

**Comment by chatanova2003** [comment]
Thank you, it worked.
