### ISSUE TITLE
installing myst node

### ISSUE THREAD

**Issue by ImLegion117** [mysteriumnetwork/node#4731]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: Tinker OS (Debian 10) [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
myst : Depends: wireguard but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by etherunit** [comment]
Could you please try to upgrade your system before installing myst package?

**Comment by ImLegion117** [comment]
I still get the same error

**Comment by etherunit** [comment]
Is it possible to see the whole installation output?

**Comment by veldspar** [comment]
tinker os is based on debian 9 which does not ship with wireguard in its repo(and the kernel isnt prepped for it). There are two options: (1) build the wireguard debian package, either crosscompile or easer but takes longer build it on the tinkerboard:
`sudo apt-get install libelf-dev linux-headers-$(uname -r) build-essential pkg-config` to install prereqs on the tinkerboard
then 
follow here: https://www.wireguard.com/compilation/
exceptr make will be make deb-pkg
2) build wireguard, manually unpack the myst debian package and manually install it(or unpack it, remove the wireguard dependency and repack it, then install it).

Both arent going to be easy unless you are at least an intermediary user

**Comment by ImLegion117** [comment]
why it say this tho

linaro@linaro-alip:~$ hostnamectl
   Static hostname: linaro-alip
         Icon name: computer
        Machine ID: f4567144e8bd41e6a11e6b7577dc423a
           Boot ID: 9dfb7780a2b84684a3251d649a3d9a12
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.4.194
      Architecture: arm

**Comment by ImLegion117** [comment]
> tinker os is based on debian 9 which does not ship with wireguard in its repo(and the kernel isnt prepped for it). There are two options: (1) build the wireguard debian package, either crosscompile or easer but takes longer build it on the tinkerboard: `sudo apt-get install libelf-dev linux-headers-$(uname -r) build-essential pkg-config` to install prereqs on the tinkerboard then follow here: https://www.wireguard.com/compilation/ exceptr make will be make deb-pkg 2) build wireguard, manually unpack the myst debian package and manually install it(or unpack it, remove the wireguard dependency and repack it, then install it).
> 
> Both arent going to be easy unless you are at least an intermediary user

**Comment by veldspar** [comment]
If I have time this weekend I'll build the package and upload it somewhere. I'm afraid this is a corner case with the tinker boards. But hang in tight, I'm a bit sick at the moment so i might take one or two days

**Comment by etherunit** [comment]
Any updates on this one?

**Comment by ImLegion117** [comment]
i have no updates, still waitin :grin:
