### ISSUE TITLE
upgrade doesn't work

### ISSUE THREAD

**Issue by xapobilo** [mysteriumnetwork/node#4732]
[INFO] Uptime: 113h29m42.875353784s
[INFO] Process: 778
[INFO] Version: 1.0.3
[INFO] Branch: 1.0.3. Build id: 414046477. Commit: 83e2dab4

0x223568e14a2818ac8b60f970d13f8f993abb9058

i've tried to upgrade the node but it seems not to work.

according to your website the upgrade process is as follows.
sudo apt update; sudo apt install myst
but after that i get this message.

Hit:1 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu bionic InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Hit:3 http://archive.raspberrypi.org/debian buster InRelease
Err:4 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
403 Forbidden [IP: 91.189.95.85 80]
Reading package lists... Done
E: Failed to fetch http://ppa.launchpad.net/wireguard/wireguard/ubuntu/dists/bionic/InRelease 403 Forbidden [IP: 91.189.95.85 80]
E: The repository 'http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.

**Comment by etherunit** [comment]
It seems that wireguard repository is no longer available. Please try to remove it and re-try installation process.

**Comment by xapobilo** [comment]
thanks. it worked.
