### ISSUE TITLE
Can't enable the node

### ISSUE THREAD

**Issue by lucasaf1981** [mysteriumnetwork/node#4739]
Hello there, i am trying to activate my node.
I did every step correctly, i am not able to Free register, so at this screen:
![image](https://user-images.githubusercontent.com/99054107/152615253-7cb78281-0f23-4aac-ba35-b26be6b62304.png)
It ask for a MYST deposit, so i did. Twice.
On January 29 i did a deposit
https://bscscan.com/tx/0x6c865df07e6e77eec37f5208e9ba7fbca6bc9d0a1df2022438d89063108d14bb

But after couple days my node has not been activated. So I did the deposit again
On February 2 
https://bscscan.com/tx/0xbb3edd89eb45307be85874d349c8aac649d0517e7b7ead3ba4a09a166e89bb25

Today is February 4 and my node is not activating.

**Comment by adinetech** [comment]
Hey there,
You have to use Polygon Mainnet for registration, not BSC.

**Comment by lucasaf1981** [comment]
So what about those transactions? Where they went to?

**Comment by adinetech** [comment]
> So what about those transactions? Where they went to?

It's in your node's identity channel, @tomasmik knows whether it's possible to get the funds back.

**Comment by lucasaf1981** [comment]
> > So what about those transactions? Where they went to?
> 
> 
> 
> It's in your node's identity channel, @tomasmik knows whether it's possible to get the funds back.

@tomasmik can you help me with that?

**Comment by tomasmik** [comment]
Hi @lucasaf1981, sorry I didn't get to you sooner, there is nothing one can do if the contract wasn't even created. Please send Polygon MYST on mainnet, try to get a spot to register for free at around 10AM GMT or buy MYST for 1USD. Consider that 0.4 MYST lost, sorry about that.
