### ISSUE TITLE
Incorrect bounty paid in MYSTT

### ISSUE THREAD

**Issue by gothichi** [mysteriumnetwork/node#4740]
Incorrect bounty paid in MYSTT

**To Reproduce**
i go to MY Sessions and see my history. i checked the earning with the MB trasferred and sometimes they are not correct.

**Expected behavior**

Sometimes the earning are not correct,.

Hi, please can you check these session ID's and let me know why they are not paid at the correct rate?:

Price per GB(today, 05/02/2022): 0.1152110 MYST
My node id: 0x1761db33b16c6848f862f4f0bdbffca19b66ce7c

Session ID          Trasferred      Earnings                          what i should earn

03605a36  --->   121.48 MB    i got: 0.0087462 MYST    i should get about 0.0136678
b525dc79  --->   121.43 MB    i got: 0.0045458 MYST    i should get about 0.0136621
1fa5743c  --->   121.2  MB      i got: 0.0047662 MYST    i should get about 0.0136363
2568ac45  --->   121.12 MB    i got: 0.0089775 MYST    i should get about 0.0136273

**Environment (please complete the following information):**
 - NodeUi version: 1.6.4
 - Node version: mainnet (1.2.2-7ebc1c52)
 - OS: Linux raspberry 5.10.63-v7+
 - Your identity (if applicable): 0x1761db33b16c6848f862f4f0bdbffca19b66ce7c

**Comment by adinetech** [comment]
Price per GB will fluctuate from time to time, you can't tell 0.1152110 MYST is your Price per GB.

**Comment by gothichi** [comment]
> Price per GB will fluctuate from time to time, you can't tell 0.1152110 MYST is your Price per GB.

As i said,it is today's price. About last week it was about 0.12 and 0.11 MYST. Those session ID i report were from last 7 days. The rewards weren't calculated correctly.

**Comment by veldspar** [comment]
The price/hr and price/gib adjusts dynamically and multiple times daily. Depending on demand it can actually change from one minute to the other
