### ISSUE TITLE
I can't register my node identity!!

### ISSUE THREAD

**Issue by anon-user-com** [mysteriumnetwork/node#4741]
- I want to register my node and I use a metamask ethereum wallet I have try so many things and it show me "Unfortunately, node identity registration failed. Please click Retry button to try again", also it's my first time and it show me disable free registration button ![image](https://user-images.githubusercontent.com/64283589/152647496-3f3eb9ab-b2f0-4597-a989-9ddb7c52dc26.jpeg)

**Comment by adinetech** [comment]
Hey, did you paid MYST over the polygon network for registration? incase if you did via Ethereum mainnet it won't work.

**Comment by anon-user-com** [comment]
> Hey, did you paid MYST over the polygon network for registration? incase if you did via Ethereum mainnet it won't work.

I didn't pay because it's my first time that I'm doing it and I don't know why registration free button is grey and disabled

**Comment by etherunit** [comment]
Free registration limit is capped and it's usually being quickly exhausted. It opens at apprx. 10 AM UTC.

**Comment by anon-user-com** [comment]
> Free registration limit is capped and it's usually being quickly exhausted. It opens at apprx. 10 AM UTC. 
> 
> 

Yes I understand this but I don't know why it's disabled because it's my first time I'm registering my node

**Comment by maade69** [comment]
same here. i am waiting for 5+ days

**Comment by anon-user-com** [comment]
> same here. i am waiting for 5+ days
> 
> already paid for registration

I'm thinking it's a problem on myst system

**Comment by adinetech** [comment]
> > same here. i am waiting for 5+ days
> > already paid for registration
> 
> I'm thinking it's a problem on myst system

No, reboot your node.

**Comment by maade69** [comment]
> > > same here. i am waiting for 5+ days
> > > already paid for registration
> > 
> > 
> > I'm thinking it's a problem on myst system
> 
> No, reboot your node.

gonna try now

**Comment by maade69** [comment]
well, that worked

**Comment by anon-user-com** [comment]
> well, that worked
> 
> 

What OS and are you using docker

**Comment by anon-user-com** [comment]
> > > same here. i am waiting for 5+ days
> 
> > > already paid for registration
> 
> > 
> 
> > I'm thinking it's a problem on myst system
> 
> 
> 
> No, reboot your node.

I installed it from my friend house (different ip) I install it on lubuntu latest version and still I can't register for free I restart mysterium-node on linux and still nothing

**Comment by adinetech** [comment]
Free registration will be available again at ~10 AM UTC, provide me your registration address.

**Comment by maade69** [comment]
> > well, that worked
> 
> What OS and are you using docker

ubuntu server, without docker

**Comment by anon-user-com** [comment]
> Free registration will be available again at ~10 AM UTC, provide me your registration address.

I will send you later because I'm having some problems also it's a metamask wallet address

**Comment by anon-user-com** [comment]
> > > well, that worked
> 
> > 
> 
> > What OS and are you using docker
> 
> 
> 
> ubuntu server, without docker
> 
> 

Yes also at first I try it with windows (docker) after that I'm using lubuntu and everything it correctly except node registration but I'm seeing that there are so many users that are seeing this problem.

**Comment by adinetech** [comment]
I asked your node's deposit address, not metamask wallet address.

**Comment by anon-user-com** [comment]
> I asked your node's deposit address, not metamask wallet address.

This part here?  Also I have a question do I need to catch early on morning around 11am utc
![image](https://user-images.githubusercontent.com/64283589/152984718-3ee2de1d-8f85-42f4-abc5-4d34bc7bcb82.jpeg)

**Comment by adinetech** [comment]
> > I asked your node's deposit address, not metamask wallet address.
> 
> This part here? Also I have a question do I need to catch early on morning around 11am utc ![image](https://user-images.githubusercontent.com/64283589/152984718-3ee2de1d-8f85-42f4-abc5-4d34bc7bcb82.jpeg)

That is node/provider ID, not channel ID

**Comment by anon-user-com** [comment]
> > > I asked your node's deposit address, not metamask wallet address.
> 
> > 
> 
> > This part here? Also I have a question do I need to catch early on morning around 11am utc ![image](https://user-images.githubusercontent.com/64283589/152984718-3ee2de1d-8f85-42f4-abc5-4d34bc7bcb82.jpeg)
> 
> 
> 
> That is node/provider ID, not channel ID

![image](https://user-images.githubusercontent.com/64283589/153052370-b82df876-3b6d-4cda-a2c8-bd14445ef603.jpeg)

Oo yeah I think its this part here.

**Comment by adinetech** [comment]
Possible to copy-paste the address here? 🤔

**Comment by anon-user-com** [comment]
> Possible to copy-paste the address here? 🤔 

Yes yes of course 

0x99B5A5166Fe2545FC89e3a6F069465e300DE919A

**Comment by adinetech** [comment]
I sent you 0.2MYST for registration, get started with your setup!

**Comment by anon-user-com** [comment]
> I sent you 0.2MYST for registration, get started with your setup!

Thank you very much I'm going to do it now

**Comment by F1uk369** [comment]
@adinetech I'm having the same issue, is there a solution? I press the free registration button, and for a bit it just worked, but then said there was a problem with the node identity. now the registration is an infinite spinning circle!

**Comment by F1uk369** [comment]
![image](https://user-images.githubusercontent.com/96375953/156751112-ec28582c-c9db-4092-a124-937296080c73.png)

**Comment by adinetech** [comment]
Click Deposit MYST token and share the address.

**Comment by F1uk369** [comment]
> Click Deposit MYST token and share the address.

0x011Ce87A72C54dB98447f1086AC1f6E2C644d708

**Comment by adinetech** [comment]
Alright, I sent it.
