### ISSUE TITLE
[Android] Cannot parse proposals response: net/http: request canceled

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4742]
**Describe the bug**
Can't fetch proposals.
We can see errors like "cannot parse proposals response: net/http: request canceled"

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8008275/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.0
 - OS: Android

**Comment by tomasmik** [comment]
Seems to be a simple connection issue which was either localized or fixed as no one else reported this.
