### ISSUE TITLE
Coin can't collected after crash of raspberry

### ISSUE THREAD

**Issue by Captmicka** [mysteriumnetwork/node#4752]
*Describe the bug*
I am contacting you because I had a problem with the SD card in my raspberry and I lost access to my OS, after changing the SD (and reinstalling the OS) I was unable to recover my Node.

I earned 29.53 Myst but I didn't collect them and now I don't have the possibility to do it.

Could you help me to get these coins? 

The address of my node was 0x83a02d5e038e93a8984136715c9.

*To Reproduce*
1. Reinstall raspbian after a crash
2. New install seen as new node no way to claim the earned coin

*Expected behavior*
Found a way to recover my earned coin 29 Myst

*Screenshots*

*Environment (please complete the following information):*
 - Node version: 1.2.4
 - OS: Raspbian 10
 - Your identity (if applicable): B0z1tzM4MhPHW2ttIftWBFM71fnuJ6c6dEFzZq3R
 - Payment (top-op) reference (if applicable): 0xFCfdc6101969642dA43FD96D792DD497A320f65F

*Additional context*

**Comment by veldspar** [comment]
Do you still have your old SD card? If so, you might just be in luck.
Attach your old sd card to a linux pc or a raspberry pi using a microSD card reader.
Before doing anything at all, we will make a backup of the entire card(make sure you have space for that, you need free disk space of at least the size of the card)

- Find out device of sd card reader: after plugging it in, check in the terminal by entering dmesg. it should have the last lines that will tell you the device name, likely being sda or sdb (with 2 corresponding partitions sda1 and sda2, or sdb1 and sdb2)
- now backup your sd card: `dd if=/dev/sda of=/path/to/where/to/save.img bs=1M oflag=sync status=progress` replace sda with the device name your card reader has, and path/to/where/to/save.img with the path to a place where to store your image.
- now that we have backed it up, mount the second partition of the card: `mount /dev/sda2 /mnt` again replace sda with the device name of yours
- finally, navigate to /mnt/var/lib/mysterium-node and copy all the files out to your computer. ideally do: cd /mnt/var/lib; tar cfz mysterium.tgz mysterium-node; cp mysterium.tgz ~
- you should now have your node identity(with your myst token) in your home folder as a tgz archive.
- to install this identity, stop mysterium first: `systemctl stop mysterium-node`

- then move the current identity out of the way - we will rename it here for sake of easiness: `mv /var/lib/mysterium-node /var/lib/mysterium-node.old` (depending on your system you might need to sudo this)
- now cd to /var/lib and do `tar xfz ~mysterium.tgz` `sudo chown -R mysterium-node:mysterium-node mysterium-node`
- where the first one extracts the old nodes identity and the latter one makes sure all permissions are right
- now start mysterium: `systemctl start mysterium-node`
if all goes well you should be able to loginto the nodeUI with your **old password from the old node identity**
you can now continue using your old identity or transfer all funds out and revert the above steps to go on with the new identity

I hope this helps, and please people, keep a backup of your keys!

**Comment by Captmicka** [comment]
Hello,
I already tried to mount it but the SD is dead and no way to recover the data.
I didn't know if you had a way to recover the scales so I asked.

**Comment by etherunit** [comment]
@Captmicka Unfortunately, there is no way to restore your previous identity without it being backed up. data-dir content includes files like keystore, nodeui-passw, mainnet and other data which is required to migrate/restore node properly.

**Comment by veldspar** [comment]
generally not everything is lost yet. In my experience with raspberry pis(over 7 years now) its usually not the sd card that actually fails. Its more along the lines of the partition table or the actual partition headers becoming corrupt. there might be other software around that can fix that. I cannot recommend anything to you(because I wouldnt know any from heart) but it might be worth a try
