### ISSUE TITLE
pilvytis requests take 30-60 seconds, or return error "address unavailable", or error code 500

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4756]
As described

E.g.
Address unavailable: https://pilvytis.mysterium.network/api/v2/settlements/summary?filter.from=2022-02-01T05:00:00Z&filter.to=2022-02-08T14:39:33Z&filter.external_id=xxx

**Comment by tomasmik** [comment]
should be resolved.

**Comment by portalsdevs** [comment]
Thanks, it has.
