### ISSUE TITLE
[windows] Registration status incorrect (Unregistered) for offchain identity

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4757]
**Describe the bug**

Getting registration status "Unregistered" for registered offchain identity.

failed to contact hermes to get new registration status error="could not request consumer data from hermes: internal error" status=Unregistered

Also error
Error parsing discovery response error="error querying device by location: error requesting root device details from \"http://192.168.2.1:9080\": EOF"

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8026597/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.6
 - OS: Windows

**Comment by tomasmik** [comment]
Try again. Should work fine.
