### ISSUE TITLE
MYST didn't reach the wallet on bittrex

### ISSUE THREAD

**Issue by apaulmann** [mysteriumnetwork/node#4763]
I wanted to transfer some MYST from my nodes to my wallet on Bittrex. I put my walletadress "0xf304f01a239ce287cf451c4a5ac23f1a1e20555a" into the withdraw but the MYST never reached my wallet on Bittex.

When I checked the transactions I found my MYSTs here:
https://polygonscan.com/address/0xf304f01a239ce287cf451c4a5ac23f1a1e20555a#tokentxns

But this is not my wallet. What I did wrong? Are my MYST lost now?

**Comment by Sermooh** [comment]
Bittrex does not support the Polygon network. Most likely, you will not be able to return the tokens.

**Comment by apaulmann** [comment]
But have a look in the mysterium documentation.
https://docs.mysterium.network/node-runners/mysterium-cli/#gatsby-focus-wrapper
(in the middle. Search for bittrex)

Is that not right?

[...]
There are two types of wallets that you can use:

Exchange wallets (HitBTC and Bittrex deposit addresses are supported only);

Direct Blockchain wallets (Metamask, Trust wallet, Atomic, MEW, MyCrypto, Trezor, Ledger ...).
[...]

**Comment by adinetech** [comment]
Yeah, its not updated since it can accept MYST in Ethereum network, not in Polygon.

**Comment by etherunit** [comment]
thanks for pointing out. we have updated it to be more clear. 
-> `Exchange wallets (HitBTC and Bittrex deposit addresses are supported on Ethereum network only!!);`

**Comment by adinetech** [comment]
> thanks for pointing out. we have updated it to be more clear. -> `Exchange wallets (HitBTC and Bittrex deposit addresses are supported on Ethereum network only!!);`

I made a PR, feel free to review and merge it https://github.com/mysteriumnetwork/documentation/pull/105/files

**Comment by etherunit** [comment]
![Screenshot 2022-02-10 at 09 02 58](https://user-images.githubusercontent.com/60128746/153354934-b883d376-6ee0-42d7-b03f-330a851aa0a3.png)
btw, we have this information in UI, so it should make people "more" aware.

**Comment by adinetech** [comment]
> ![Screenshot 2022-02-10 at 09 02 58](https://user-images.githubusercontent.com/60128746/153354934-b883d376-6ee0-42d7-b03f-330a851aa0a3.png) btw, we have this information in UI, so it should make people "more" aware.

I agree.
