### ISSUE TITLE
Appl get stuck on loading screen 

### ISSUE THREAD

**Issue by esexyou** [mysteriumnetwork/node#4772]
**Describe the bug**
MysteriumVPN app for Windows stuck on loading screen and cannot start normally.

**Expected behavior**
Launch and use.

**Screenshots**
![image](https://user-images.githubusercontent.com/76847127/153690829-c0d8c85a-8897-46ca-afb5-14433617d640.png)

**Additional context**
[main.log](https://github.com/mysteriumnetwork/node/files/8052467/main.log)
[renderer.log](https://github.com/mysteriumnetwork/node/files/8052468/renderer.log)

**Comment by etherunit** [comment]
@esexyou Please delete `%USERPROFILE%\.mysterium\logs\mysterium-node.log` file and launch your application again.

**Comment by esexyou** [comment]
Hey! Thanks that indeed did work but i have another issue i have been using it for like 3 days and then i got another issue i try connecting to any country and it just says updating and then randomly kicks me and wont let me connect fully help?

![image](https://user-images.githubusercontent.com/76847127/155227318-f8e1e09e-68dd-4ac6-ba11-203fb4c5f4a6.png)

**Comment by etherunit** [comment]
What's your current app version? 10.5.3.?

**Comment by esexyou** [comment]
yes it is 10.5.3

**Comment by esexyou** [comment]
Hello any update?

**Comment by esexyou** [comment]
Hello? why am i getting no reply i need this fixed

**Comment by etherunit** [comment]
Is it possible to add mysterium-node log file? It includes most relevant information.
Find it here:` %USERPROFILE%\.mysterium\logs\mysterium-node.log (node)`
or Submit via app window.

**Comment by esexyou** [comment]
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8153016/mysterium-node.log)

this is my log right there. that what i found and then i put it right here help

**Comment by esexyou** [comment]
Issue listed:
![image](https://user-images.githubusercontent.com/76847127/156353903-bfe857f2-12d8-49af-9246-6168376190b0.png)

Either dosen't connect me at all or sometimes does and says updating and the vpn dosent work at all. Like a timeout or something please help i gave u mysterium node log file and no response.

App version: 
![image](https://user-images.githubusercontent.com/76847127/156354024-151b29e3-d18e-4eaa-84fa-512aa972f5f3.png)

also this has nothing to do with my router or anything i tried switching connections and still same issue. please help i need to use the vpn and im getting no response at all.

**Comment by etherunit** [comment]
Seeing such messages in the output:

`2022-02-28T11:42:09.298 ERR /source/core/discovery/repository.go:94   > Returning 0 unique proposals error="ErrorCollection: cannot fetch proposals: Get \"https://discovery.mysterium.network/api/v3/proposals?nat_compatibility=prcone&quality_min=1.00&service_type=wireguard\": failed to dial discovery.mysterium.network:443: all dials failed\n  * [discovery.mysterium.network:443] dial tcp: lookup discovery.mysterium.network: no such host\n  * [51.15.116.186:443] dial tcp 0.0.0.0:0->51.15.116.186:443: connectex: An established connection was aborted by the software in your host machine.\n  * [51.15.72.87:443] dial tcp 0.0.0.0:0->51.15.72.87:443: connectex: An established connection was aborted by the software in your host machine."`

Apparently, it's failing to work as expected, you might try switching to another DNS setting, choose Provider or Auto instead. 

Also, simply restarting the app or completely rebooting your PC might help too.

Please let me know how it goes.

**Comment by esexyou** [comment]
hello, the DNS setting was already chosen as provider, i did switch it to automatic and that did not change nothing at all. and what do you mean exactly by rebooting my pc? you mean restarting it i have done it many times nothing has worked please help me.

**Comment by esexyou** [comment]
hello any help?

**Comment by esexyou** [comment]
why is my request being ignored. i have been waiting a week now
