### ISSUE TITLE
unable to confirm installation is correct

### ISSUE THREAD

**Issue by WojtekonGithub** [mysteriumnetwork/node#4775]
after following all directions, I turn on Raspberry Pi, i use Putty to connect and I am okay via SSH - but I get this output even when running updates.

then when I go to browser and try to connect to claim UI, i get this response (please check pictures).

What else could it be preventing me from accessing via browser ?

What is not working is: once Raspberry Pi has been set up according to instructions you have provided, when I click on CLAIM NODE on the browser - it times out and it does not find the device on my home network. I even took the firewall down of my router - same thing.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
any pictures available? it could be helpful to see the output of developer tools console/network tab at the time this happens.

**Comment by WojtekonGithub** [comment]
i have tried to follow up exactly what was written here:

https://docs.mysterium.network/node-runners/setup/raspberry-pi/#install-a-mysterium-node

I am not command specialist or anything like that - i thought this would be a simple process, but i have noticed I am failing somwhere here.....

Please help.




login as: myst
***@***.***'s password:
Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Jan 11 14:21:51 2021 from 192.168.0.200

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

***@***.***:~ $ passwd
Changing password for myst.
Current password:
New password:
Retype new password:
passwd: password updated successfully
***@***.***:~ $ ping raspberrypi.local

PING raspberrypi.local (192.168.0.16) 56(84) bytes of data.
64 bytes from 192.168.0.16: icmp_seq=1 ttl=64 time=0.137 ms
64 bytes from 192.168.0.16: icmp_seq=2 ttl=64 time=0.111 ms
64 bytes from 192.168.0.16: icmp_seq=3 ttl=64 time=0.108 ms
64 bytes from 192.168.0.16: icmp_seq=4 ttl=64 time=0.096 ms
64 bytes from 192.168.0.16: icmp_seq=5 ttl=64 time=0.091 ms
64 bytes from 192.168.0.16: icmp_seq=6 ttl=64 time=0.109 ms
64 bytes from 192.168.0.16: icmp_seq=7 ttl=64 time=0.118 ms
64 bytes from 192.168.0.16: icmp_seq=8 ttl=64 time=0.125 ms
64 bytes from 192.168.0.16: icmp_seq=9 ttl=64 time=0.101 ms
64 bytes from 192.168.0.16: icmp_seq=10 ttl=64 time=0.086 ms
64 bytes from 192.168.0.16: icmp_seq=11 ttl=64 time=0.093 ms
64 bytes from 192.168.0.16: icmp_seq=12 ttl=64 time=0.098 ms
64 bytes from 192.168.0.16: icmp_seq=13 ttl=64 time=0.115 ms
64 bytes from 192.168.0.16: icmp_seq=14 ttl=64 time=0.132 ms
64 bytes from 192.168.0.16: icmp_seq=15 ttl=64 time=0.203 ms
64 bytes from 192.168.0.16: icmp_seq=16 ttl=64 time=0.127 ms
64 bytes from 192.168.0.16: icmp_seq=17 ttl=64 time=0.098 ms
64 bytes from 192.168.0.16: icmp_seq=18 ttl=64 time=0.090 ms
64 bytes from 192.168.0.16: icmp_seq=19 ttl=64 time=0.095 ms
64 bytes from 192.168.0.16: icmp_seq=20 ttl=64 time=0.100 ms

64 bytes from 192.168.0.16: icmp_seq=21 ttl=64 time=0.073 ms
64 bytes from 192.168.0.16: icmp_seq=22 ttl=64 time=0.126 ms
64 bytes from 192.168.0.16: icmp_seq=23 ttl=64 time=0.126 ms
64 bytes from 192.168.0.16: icmp_seq=24 ttl=64 time=0.096 ms
64 bytes from 192.168.0.16: icmp_seq=25 ttl=64 time=0.098 ms

64 bytes from 192.168.0.16: icmp_seq=26 ttl=64 time=0.097 ms
        64 bytes from 192.168.0.16: icmp_seq=27 ttl=64 time=0.115 ms

64 bytes from 192.168.0.16: icmp_seq=28 ttl=64 time=0.106 ms
64 bytes from 192.168.0.16: icmp_seq=29 ttl=64 time=0.080 ms

64 bytes from 192.168.0.16: icmp_seq=30 ttl=64 time=0.114 ms
64 bytes from 192.168.0.16: icmp_seq=31 ttl=64 time=0.146 ms
64 bytes from 192.168.0.16: icmp_seq=32 ttl=64 time=0.109 ms
64 bytes from 192.168.0.16: icmp_seq=33 ttl=64 time=0.104 ms
64 bytes from 192.168.0.16: icmp_seq=34 ttl=64 time=0.117 ms
^[[4~
64 bytes from 192.168.0.16: icmp_seq=35 ttl=64 time=0.115 ms
64 bytes from 192.168.0.16: icmp_seq=36 ttl=64 time=0.109 ms
64 bytes from 192.168.0.16: icmp_seq=37 ttl=64 time=0.137 ms
64 bytes from 192.168.0.16: icmp_seq=38 ttl=64 time=0.126 ms
^Z
[1]+  Stopped                 ping raspberrypi.local
***@***.***:~ $ sudo apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libcurl4
The following packages will be upgraded:
  curl libcurl4
2 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.
Need to get 549 kB of archives.
After this operation, 6,144 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Abort.
***@***.***:~ $ sudo apt-get update
Err:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
  Temporary failure resolving 'raspbian.raspberrypi.org'
Err:2 http://archive.raspberrypi.org/debian buster InRelease
  Temporary failure resolving 'archive.raspberrypi.org'
Err:3 http://deb.debian.org/debian unstable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:4 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease
  Temporary failure resolving 'ppa.launchpad.net'
Reading package lists... Done
W: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease  Temporary failure resolving 'raspbian.raspberrypi.org'
W: Failed to fetch http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu/dists/focal/InRelease  Temporary failure resolving 'ppa.launchpad.net'
W: Failed to fetch http://archive.raspberrypi.org/debian/dists/buster/InRelease  Temporary failure resolving 'archive.raspberrypi.org'
W: Failed to fetch http://deb.debian.org/debian/dists/unstable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
***@***.***:~ $ sudo apt-cache policy myst
myst:
  Installed: 1.2.4
  Candidate: 1.2.4
  Version table:
 *** 1.2.4 100
        100 /var/lib/dpkg/status
     1.2.2+build455036075+focal 500
        500 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal/main armhf Packages
***@***.***:~ $
***@***.***:~ $ myst:
     0.47.0~rc0+build301789769+focal 500
        500 http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu focal/main armhf Packages
 *** 0.46.2~rc0+build295039394+focal 500
        500 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal/main armhf Packages
        100 /var/lib/dpkg/status

-bash: myst:: command not found
***@***.***:~ $   Installed: 0.46.2~rc0+build295039394+focal
-bash: Installed:: command not found
***@***.***:~ $   Candidate: 0.47.0~rc0+build301789769+focal
-bash: Candidate:: command not found
***@***.***:~ $   Version table:
-bash: Version: command not found
***@***.***:~ $      0.47.0~rc0+build301789769+focal 500
-bash: 0.47.0~rc0+build301789769+focal: command not found
***@***.***:~ $         500 http://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu focal/main armhf Packages
-bash: 500: command not found
***@***.***:~ $  *** 0.46.2~rc0+build295039394+focal 500
-bash: ***: command not found
***@***.***:~ $         500 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal/main armhf Packages
-bash: 500: command not found
***@***.***:~ $         100 /var/lib/dpkg/status
-bash: 100: command not found
***@***.***:~ $
***@***.***:~ $ 0.46.2~rc0+build295039394+focal 5000.47.0~rc0+build301789769+focal 500^C
***@***.***:~ $ sudo apt install myst=0.47.0~rc0+build301789769+focal 500
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '0.47.0~rc0+build301789769+focal' for 'myst' was not found
E: Unable to locate package 500
***@***.***:~ $[cid:388855a7-aaa0-4862-81cd-d8e0bf3cc8c2]
________________________________

**Comment by WojtekonGithub** [comment]
![git](https://user-images.githubusercontent.com/99623530/154841631-c0120b34-4ba6-44d5-9100-ee804d2fa8c0.JPG)
![r2](https://user-images.githubusercontent.com/99623530/154841635-d679ed4c-d545-4307-a644-85ed03f1de08.JPG)
![r1](https://user-images.githubusercontent.com/99623530/154841639-6a8644a2-694e-41ec-8f54-01f299630043.JPG)

i have attached 3 pictures, i hope that will explain the issue, please let me know.

**Comment by etherunit** [comment]
index files failed to download. try: `sudo apt-get update && sudo apt-get upgrade` prior to myst installation.
