### ISSUE TITLE
Balance update

### ISSUE THREAD

**Issue by anon-user-com** [mysteriumnetwork/node#4778]
**Describe the bug**
My balance isn't updating on mystnodes.com but if I check on localhost:4449 dashboard everything is okay 

**Expected behavior**
Myst balance update on mynodes.com

**Environment (please complete the following information):**
 - Node version: [1.2.4]
 - OS: [Ubuntu 18.04 LTS]
 - Your identity: [0xe5aabd416409008119aa61435]

**Comment by tomasmik** [comment]
Balance on mystnodes lags behind and it not up to date because it does not pull it from blockchain directly.

**Comment by anon-user-com** [comment]
Yes I know it but it has some days with this problem maybe 2-3 days

**Comment by tomasmik** [comment]
> Yes I know it but it has some days with this problem maybe 2-3 days

Please provide more info next time :) re-opened the issue.

**Comment by anon-user-com** [comment]
Yeah very good but I don't know what to right for example what.

**Comment by Donatas-MN** [comment]
@anon-user-com can you add screenshots from MystNodes.com and NodeUI?
