### ISSUE TITLE
[android] can't connect to any provider node. "could not dial p2p channel: could not ping peer: too few connections were built"

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4783]
**Describe the bug**
Can't connect to nodes: could not dial p2p channel: could not ping peer: too few connections were built
Trying to connect from home in Brasil.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8078449/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.0
 - OS: Android

**Comment by adinetech** [comment]
Could be an problem with the node, try different node.

**Comment by portalsdevs** [comment]
renamed to make it more explicit

**Comment by tomasmik** [comment]
It appears that either DNS is broken or ISP blocking interaction with our services, so could not dial error is not the only issue for that person.
