### ISSUE TITLE
Android & PC version doesn't show my original available balance

### ISSUE THREAD

**Issue by Ecrudragon** [mysteriumnetwork/node#4789]
Hi,
I top-up around 20$ to my mysterium account now my Mysterium account doesn't show full available balance even though i have 947306475071206246 balance in my account it only gives me 0.947 MYST to use, it goes for both Android and PC apps.

P.S an old version of Android app was showing my full balance but it doesn't anymore because i can't log in to that old android version anymore.

**Environment (please complete the following information):**
 - Node version: [2.07]
 - OS: [Android]
 - Desktop app version (if applicable): [10.5.2]
 - Your identity (if applicable): [0x7E7faD55d64141d933CBfb673B1fca4253fAC1f1]
 
**Additional context**
{"137":{"Identity":"0x7E7faD55d64141d933CBfb673B1fca4253fAC1f1","Beneficiary":"0xE9779146E428d4F52B868b591056C9e378672940","ChannelID":"0xE9779146E428d4F52B868b591056C9e378672940","Balance":947306475071206246,"Settled":0,"Stake":0,"StakeGoal":null,"RevealedPromise":{"ChannelID":"0xe9779146e428d4f52b868b591056c9e378672940","Amount":51347969373393754,"Fee":0,"Hashlock":"0xc73bd30f72f650b3675dd8e8d0928a35b677e16b9cbfaebab742d9930fdfad5d","Signature":"0x4e5d706bc43559a22381ada5417a83d8f7cf5f5b8b4b8d4da52d9b50fc3176e33070cc66f9e440b60d98f4959726441c28bc3edebb650b7c92985305a7e3573b1c","ChainID":137},"LatestPromise":{"ChannelID":"0xe9779146e428d4f52b868b591056c9e378672940","Amount":51347969373393754,"Fee":0,"Hashlock":"0xc73bd30f72f650b3675dd8e8d0928a35b677e16b9cbfaebab742d9930fdfad5d","Signature":"0x4e5d706bc43559a22381ada5417a83d8f7cf5f5b8b4b8d4da52d9b50fc3176e33070cc66f9e440b60d98f4959726441c28bc3edebb650b7c92985305a7e3573b1c","ChainID":137},"LatestSettlement":"0001-01-01T00:00:00Z","IsOffchain":false,"BeneficiaryCachedAt":"0001-01-01T00:00:00Z"}}

**Comment by Ecrudragon** [comment]
> Balance":947306475071206246" is 0.947MYST equivalent Can you specify where top up is done? consumer channel address? identity channel address?

Hi, top-up is done via coinbase and i can provide reference link/code or something for the transaction, will it be enough? thanks

**Comment by Ecrudragon** [comment]
0.000225 BTC sent to : 32tR3aD4pGQMiyj3qFwvFsrq9SD9XWdfYs

**Comment by Sermooh** [comment]
Most likely, Ecrudragon top up the account during the Testnet period. When upgrading to Mainnet, his balance was lost.

**Comment by Ecrudragon** [comment]
> Most likely, Ecrudragon top up the account during the Testnet period. When upgrading to Mainnet, his balance was lost.

@Sermooh this could be the reason, now the thing is how will i get my balance back?

**Comment by tomasmik** [comment]
> Most likely, Ecrudragon top up the account during the Testnet period. When upgrading to Mainnet, his balance was lost.

We've stopped migrating balance from testnet3 -> mainnet last week as testnet3 no longer exists.

**Comment by Ecrudragon** [comment]
> > Most likely, Ecrudragon top up the account during the Testnet period. When upgrading to Mainnet, his balance was lost.
> 
> If this is the case then it's worth to mention that we've stopped migrating balances from testnet3 -> mainnet last week as testnet3 no longer exists.

Please elaborate how is this my fault that you moved from testnet3 to mainnet and i lost my money, so is there any chance to get it back or is it gone for good? Getting this money back should be mysterium network responsibility, thanks

**Comment by tomasmik** [comment]
> > > Most likely, Ecrudragon top up the account during the Testnet period. When upgrading to Mainnet, his balance was lost.
> > 
> > 
> > If this is the case then it's worth to mention that we've stopped migrating balances from testnet3 -> mainnet last week as testnet3 no longer exists.
> 
> Please elaborate how is this my fault that you moved from testnet3 to mainnet and i lost my money, so is there any chance to get it back or is it gone for good? Getting this money back should be mysterium network responsibility, thanks

You can work this out with the support team. They should be able to help you out.

**Comment by Sermooh** [comment]
> 

This is a fair statement. The client does not have to worry about carrying the balance. Moreover, there was no manual about vpn balance migration. That's not how a solid company treats their customers. If the balances couldn't be migrated automatically, the employees of the company should have done it manually by topping up the balances of the accounts in mainnet.

**Comment by Sermooh** [comment]
> Please elaborate how is this my fault that you moved from testnet3 to mainnet and i lost my money, so is there any chance to get it back or is it gone for good? Getting this money back should be mysterium network responsibility, thanks

This is a fair statement. The client does not have to worry about carrying the balance. Moreover, there was no manual about vpn balance migration. That's not how a solid company treats their customers. If the balances couldn't be migrated automatically, the employees of the company should have done it manually by topping up the balances of the accounts in mainnet.

**Comment by Ecrudragon** [comment]
Is my issue dead? Or mysterium doesn't care at all?

**Comment by adinetech** [comment]
@etherunit will get back to you soon.

**Comment by etherunit** [comment]
@Ecrudragon I completely understand your situation. Please give me some time to clear this out with the team and get back to you with a solution.

**Comment by Ecrudragon** [comment]
> @Ecrudragon I completely understand your situation. Please give me some time to clear this out with the team and get back to you with a solution.

I'd really appreciate a solution thanks

**Comment by etherunit** [comment]
@Ecrudragon Please provide us with your beneficiary wallet (identity channel address or Polygon compatible wallet address) where you would like to receive 20$ worth of MYST.

**Comment by etherunit** [comment]
As it's not clear, which amount: 0.000225BTC or 20$ was sent

**Comment by Ecrudragon** [comment]
> @Ecrudragon Please provide us with your beneficiary wallet (identity channel address or Polygon compatible wallet address) where you would like to receive 20$ worth of MYST. Also, I'd like to request you to provide a payment reference link/code of it.

Trust Wallet
My Public Address to Receive MYST 0x953BC2313521AFD99529EE742DB70D2b7e762CDF

**Comment by etherunit** [comment]
Please specify amount to sent (a payment reference link should have it indicated)?

**Comment by Ecrudragon** [comment]
> Please specify amount to send (a payment reference link should have it indicated)?

0.00022531 BTC sent to 32tR3aD4pGQMiyj3qFwvFsrq9SD9XWdfYs (that's all i remember i don't understand cyrpto system and how it works)

**Comment by Ecrudragon** [comment]
@etherunit any news?

**Comment by Ecrudragon** [comment]
@etherunit i hope you're fine.
It's been many days since i opened this issue but to be fair you're not solving it as early as i hoped for, i request you to kindly resolve this issue, thanks

**Comment by adinetech** [comment]
@etherunit will be back on Monday, I'll remind him regarding the same.

**Comment by etherunit** [comment]
Hi, got informed it should be done until Tuesday. Closing this case for now. Feel free to reopen it if no MYST will arrive in your wallet.

**Comment by Ecrudragon** [comment]
> Hi, got informed it should be done until Tuesday. Closing this case for now. Feel free to reopen it if no MYST will arrive in your wallet.

Dear @etherunit unfortunately no MYST received yet, please check thanks

**Comment by adinetech** [comment]
Processed your refund: https://polygonscan.com/tx/0x3e97f75e7f4382d1c988e9649ded862b2009d8c250c3ac3bbfbfaa4be619e98c

**Comment by Ecrudragon** [comment]
> Processed your refund: https://polygonscan.com/tx/0x3e97f75e7f4382d1c988e9649ded862b2009d8c250c3ac3bbfbfaa4be619e98c

Thank you so much bro, really appreciate it 👍 🥇
