### ISSUE TITLE
Node dashboard do not update after node move

### ISSUE THREAD

**Issue by Jhobean** [mysteriumnetwork/node#4791]
**Describe the bug**
I moved my node from Ubuntu to Docker Windows 1 month ago. I used the Key replacement with COPY Paste. My node work well and I have updated it to last version many time. But on Node dashboard, I continu to see the old version and old OS.

If I press "test node" it do not update.

![image](https://user-images.githubusercontent.com/51728381/154586149-4ed6bf3e-ecae-40d5-be1c-8d9e59a55011.png)

**Expected behavior**
See the good version and good OS

**Comment by etherunit** [comment]
Have you tried to clear cache or open incognito window for testing purposes?

**Comment by Jhobean** [comment]
Yes, DO not work

**Comment by Jhobean** [comment]
![image](https://user-images.githubusercontent.com/51728381/154813789-b49c1a5b-145c-419d-bc05-42695f40a96b.png)

**Comment by Jhobean** [comment]
OK I found the bug!

There was missing MY API # on the node UI. It's strange because Online statut add MYST total was updated but not the version..

**Comment by Guillembonet** [comment]
Oh yeah its very possible, the earned amount doesn't come from the node but from the smart contract of your identity so that explains it!
