### ISSUE TITLE
keep connecting without any benefit

### ISSUE THREAD

**Issue by iiMx369** [mysteriumnetwork/node#4799]
hi I notice someone keep connecting without any benefit
I use windows docker 
![unknown (1)](https://user-images.githubusercontent.com/29420624/154846003-01cee32a-fc7f-4304-a8af-7672434e2661.png)
![2](https://user-images.githubusercontent.com/29420624/154846002-64d0998f-ee73-41e9-b33b-503c4bf78e6e.png)

**Comment by etherunit** [comment]
There may be a time when you encounter an issue with your node and we may ask you to submit your logs for further investigation. For us to understand what is happening we'd like you to submit your node logs. Login to your Node UI](https://docs.mysterium.network/node-runners/node-ui/) and click the "Bug" button on the left side panel and team will investigate it further.
