### ISSUE TITLE
Fix mobile package build in the node

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#4804]
It's broken now, even if CI says that it's good.

**Comment by tadaskay** [comment]
Ci doesn't say it's good. It looks like it's been broken in this pipeline https://gitlab.com/mysteriumnetwork/node/-/commit/4f1382bf2915fe4c0b92f4b4b0757a37baa6f86f

**Comment by soffokl** [comment]
https://gitlab.com/mysteriumnetwork/node/-/jobs/2076085187

**Comment by soffokl** [comment]
it says `Job succeeded`
