### ISSUE TITLE
SDK for mobile (iOS, Android)

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#481]
*As a* mobile applications developer
*In order* to bootstrap mobile application
*I want* to be able to use all endpoints of Tequilapi

**Comment by zolia** [comment]
This goes in line with our plans to implement all tequilapi functionality through function calls. This would reduce issues on mobile platforms and would simplify access to node through native APIs.

**Comment by chompomonim** [comment]
Our mobile platform don't use requilapi anymore.
