### ISSUE TITLE
Only receiving test connections despite node stating: "accepting connections: All"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4811]
**Describe the bug**
(0xdb9c8020d26526d226b27fa33fcce84c7998feb2) only receives sessions all from the Netherlands no real data transferred.

opened all the firewall, manual port forwarding done but still not receiving any real sessions. 

logs:
[2022-02-23-logs-mysterium-node.zip](https://github.com/mysteriumnetwork/node/files/8125421/2022-02-23-logs-mysterium-node.zip)

**Comment by isaackielma** [comment]
Similar issue:

📅 2022-02-22 08:58:03.662164672 +0000 UTC m=+510453.349538221

Description:

Hi there,
I have already made a request regarding my Myst Node, it said I should set up manual port forwarding. I have therefore redirected the port range 10000-60000 to port 10000 (tcp/udp) with the help of iptables. However, I still get "empty" requests, i.e. requests that have 0 bytes, and for which I receive no payout. can you please help me with that.

Logs:

https://mystnodes.com/support/logs/2022-02-22-cd034ae6-03c5-429e-8836-4d44a9026b4e-mysterium-node.zip3550039004

**Comment by etherunit** [comment]
```
[CONNECTING] from: 0xe3ba8dc9cde3f53aef8601e97f3d03a707cf33cb to: 0xdb9c8020d26526d226b27fa33fcce84c7998feb2
[ERROR] Server response invalid: 500 Internal Server Error (http://127.0.0.1:4050/connection). Possible error: could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session d8a4666b-82c8-4684-a9f7-fc631f67866c: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: no such file or directory
```
It's doesn't work, there is no tun device built. what does `modprobe wireguard` as root returns

**Comment by MrMadlew** [comment]
> It's doesn't work, there is no tun device built. what does `modprobe wireguard` as root returns

When I run that command I get this result:

`bash-5.1# sudo modprobe wireguard
modprobe: can't change directory to '/lib/modules': No such file or directory`

**Comment by etherunit** [comment]
Thanks! there is a docker instance on Mac, Windows, Linux ?

**Comment by MrMadlew** [comment]
> Thanks! there is a docker instance on Mac, Windows, Linux ?

https://docs.mysterium.network/node-runners/setup/docker/
https://registry.hub.docker.com/r/mysteriumnetwork/myst/
Is this why? "Currently node supports OpenVPN as its underlying VPN transport."

**Comment by etherunit** [comment]
This has no relations with your current issue. Please note that OpenVPN is no longer used in our network. Depending on what is host operating system, there will be a different troubleshooting option.
Could you verify the host OS? docker container is running on Mac / Windows / Linux machine? which one?

**Comment by MrMadlew** [comment]
Thanks, etherunit. The host OS is Linux based. It is Docker on a Synology NAS device (Intel CPU)
