### ISSUE TITLE
Sessions with very little MYST paid 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4812]
**Describe the bug**

Provider has gotten 3 sessions where data was used but unusual amount of MYST was paid.

Node ID: 0xc2143254804280538296408bf8d4be3a91863684

Few sessions out there using data without paying.

Netherlands
834bee29-4193-4e91-a718-edaf6ad3e3af (15/02/2022, 11:36:02)
00:00:34 20.64 MB < 0.0000001 MYST

Iran
00:00:31 26/01/2022,
21:42:01 < 0.0000001 MYST 1.28 MB
33244479

Azerbaijan
00:00:45 26/01/2022,
00:21:31 < 0.0000001 MYST 11.31 MB
52443ba6

**Comment by etherunit** [comment]
Is it possible to get other session ids?

**Comment by etherunit** [comment]
@isaackielma ?
