### ISSUE TITLE
Node not registering on fresh install on Raspberry PI 4

### ISSUE THREAD

**Issue by ganzocrypt** [mysteriumnetwork/node#4813]
I just tried to install the node on RPI 4 8gb, I got to the node in the mynode (Offline) account but it does not register, here is the log.
Version: 1.3.3

Feb 23 22:38:57 raspberrypi myst[1007]: 2022-02-23T22:38:57.404 DBG config/config.go:220                     > Returning user config value terms.version:0.0.35
Feb 23 22:38:57 raspberrypi myst[1007]: 2022-02-23T22:38:57.423 DBG identity/selector/handler.go:98          > Attempting to use last identity
Feb 23 22:38:57 raspberrypi myst[1007]: 2022-02-23T22:38:57.424 DBG identity/selector/handler.go:103         > Found identity in cache: 0x677076958e9775fa23a13c1b67f19b56443702c2
Feb 23 22:38:57 raspberrypi myst[1007]: 2022-02-23T22:38:57.424 DBG identity/manager.go:153                  > Unlocked identity found in cache, skipping keystore: 0x677076958e9775fa23a13c1b67f19b56443702c2
Feb 23 22:38:57 raspberrypi myst[1007]: 2022-02-23T22:38:57.425 DBG identity/selector/handler.go:108         > Unlocked identity: 0x677076958e9775fa23a13c1b67f19b56443702c2
Feb 23 22:38:57 raspberrypi myst[1007]: 2022-02-23T22:38:57.769 WRN session/pingpong/consumer_balance_tracker.go:475 > Could not get consumer channel error="no contract code at given address"
Feb 23 22:38:59 raspberrypi myst[1007]: 2022-02-23T22:38:59.261 DBG core/location/oracle_resolver.go:64      > Detecting with oracle resolver
Feb 23 22:38:59 raspberrypi myst[1007]: 2022-02-23T22:38:59.673 DBG eventbus/event_bus.go:81                 > 
Feb 23 22:39:01 raspberrypi myst[1007]: 2022-02-23T22:39:01.526 DBG eventbus/event_bus.go:81                 > Published topic="NAT-type-detected" event=prcone
Feb 23 22:39:36 raspberrypi myst[1007]: 2022-02-23T22:39:36.542 ERR tequilapi/endpoints/transactor.go:325    > Failed identity registration request for ID: 0x677076958e9775fa23a13c1b67f19b56443702c2, &{ReferralToken:<nil>} error="server response invalid: 400 Bad Request (https://transactor.mysterium.network/api/v1/identity/register){\"error\":\"registration in progress\"}"

I follow all the steps but cannot get it to register. Do I need to do anything else like NAT/router ports forwarding or something?
thx

**Comment by ganzocrypt** [comment]
I got online now!

**Comment by stratoshift** [comment]
> I got online now!

How did you fix it
