### ISSUE TITLE
Error message Warning: apt-key is deprecated.

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4816]
**Describe the bug**
When trying to add the repository to my server it says "Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found." and after trying to update my server I get:
E: The repository 'http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu jammy Release' does not have a Release file.

**Screenshots**
<img width="943" alt="Screenshot 2022-02-24 at 10 37 11" src="https://user-images.githubusercontent.com/84313603/155508369-553b89ed-d2a4-4693-a2d3-8283369d72ca.png">

**Environment (please complete the following information):**
 - OS: Debian 10

**Comment by veldspar** [comment]
see https://github.com/mysteriumnetwork/node/issues/4677 for workaround
