### ISSUE TITLE
considerable amount of myst lost upon withdraw (not solved)

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4817]
**Describe the bug**
https://github.com/mysteriumnetwork/node/issues/4634

"nodeid 0x397818e19ab5a2ea26daa00f66bef6881e195065

had a balance of ~1200, withdraw attempted all at once and got an error message. successfully withdrew 90, then 100

tried one for 800 and it does not appear in provider's withdraw logs, but has been deducted from balance.

Expected behavior
Withdrawal amount should either remain on balance or go to wallet included in the transaction. Transaction details should appear in withdraw logs if amount is deducted from balance"

Apparently the solution would be to withdraw again and the next withdrawal will force the hung withdrawal to complete. Because withdrawal has been limited due to smart contract to no more than 99 MYST a time.

However, we tried again and appears to be the same problem: https://polygonscan.com/token/0x1379e8886a944d2d9d440b3d88df536aea08d9f3?a=0xabf1b2946d8b00ad9a3c91da9daf89fe94c4141d

**Comment by tomasmik** [comment]
Update node version. Withdrawal above 100 MYST is not allowed. His money should be send to him upon next withdrawal

**Comment by overland-liquor** [comment]
@tomasmik  please take another look at this, it is not resolved.  the suggested resolution has been tried and did not result in the release of funds
