### ISSUE TITLE
I cannot connect to any vpn from any country

### ISSUE THREAD

**Issue by pabsanort2** [mysteriumnetwork/node#4819]
**Describe the bug**
When i try to connect to any vpn from any country i get this error: 
![image](https://user-images.githubusercontent.com/72545577/155701419-2a1ed39b-f59c-40db-be52-deb828a0b9ea.png)

**To Reproduce**
1. Just click any contry and try to connect

**Expected behavior**
Just to connect correctly to the vpn.
**Screenshots**
![image](https://user-images.githubusercontent.com/72545577/155701529-22ee4c45-977a-486c-a5fc-e30fb353cc63.png)
**Environment (please complete the following information):**
 - Node version: 16.14.0
 - OS: Windows 10
 - Desktop app version (if applicable): 10.5.3

**Comment by adinetech** [comment]
Download https://www.wintun.net/ then extract the dll file and move to C:\Windows\System32.
Restart the app.

**Comment by etherunit** [comment]
@pabsanort2 I'm closing this issue for now. Feel free to re-open it in case this issue will appear in any of its form.
