### ISSUE TITLE
No MYST is being issued for this node.

### ISSUE THREAD

**Issue by FLYERFIGHTER66** [mysteriumnetwork/node#4820]
**Describe the bug**
The system is not paying MYST for usage.  At this writing, I have had 111 sessions for 9.12 hours and 1.24 GB of transfer all unpaid.  I 

**To Reproduce**
1. This behavior is repeating itself.  Go to the node UI and look at the last 111 sessions.  No MYST has been issued 
2. or Look at (https://mystnodes.com/nodes) and note that the Earnings have not changed since 20 Feb 2022.

**Expected behavior**
I expect that the system should add MYST to my earnings total on the mystnodes.com/nodes page and to the earnings column on each entry on the sessions screen (http://localhost:4449/#/sessions)

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.2.4
 - OS: Alpine Linux v3.14(docker) running on Windows 10 Home Version 10.0.19044 Build 19044
 - Docker (if applicable): Docker Desktop 4.5.1 (74721)
 - Node ID: 0xfc2c4b2ba9717aada8eda0037041dd071c81251e

**Additional context**
 - I am happy to provide any further details needed for troubleshooting.  Contact me at bill@behrs.us
 
![Screenshot 2022-02-25 111800](https://user-images.githubusercontent.com/22639467/155750220-f379a89c-6a8e-4f07-a3a8-d4836b617185.png)

**Comment by etherunit** [comment]
Looks to be similar to https://github.com/mysteriumnetwork/node/issues/4815

**Comment by FLYERFIGHTER66** [comment]
I submitted the bug via the bug button on the Node UI as requested.  The last time I submitted information there, Isaac replied by telling me to open an issue here on github.  If need be, I can paste some logs here if that helps.  Let me know.  My node is still not being issues any MYST.

**Comment by isaackielma** [comment]
@FLYERFIGHTER66 No need to submit again! 

Logs:

https://mystnodes.com/support/logs/2022-02-28-bd7d8243-6b62-46fc-8ba5-f55be3500cd6-mysterium-node.zip2578032804

Thanks!

**Comment by etherunit** [comment]
Can you please 1st try to update your node? https://docs.mysterium.network/node-runners/setup/updating/

**Comment by etherunit** [comment]
from 1.2.4 to 1.4.1

**Comment by etherunit** [comment]
@FLYERFIGHTER66

**Comment by Guillembonet** [comment]
@FLYERFIGHTER66 your node logs were helpful, we identified the issue and will post updates here!

**Comment by Guillembonet** [comment]
I fixed all the nodes for which I have issues manually, if you have this error still paste me your identity here and I can fix it. We will be automatically fixing the rest in the coming days.

**Comment by msvanvertloo** [comment]
0x308f1be6ac3ea1b7cbc8ae8d3c3c8503b849b9fd

**Comment by hishamaw** [comment]
0xde05ffcd14cc3eb2abdca595ea91558a84fe141c

**Comment by hishamaw** [comment]
@Guillembonet, Could you fix my node, please?

**Comment by Guillembonet** [comment]
a fix was just released, your node should be able to recover automatically now @hishamaw

**Comment by kiraitachi** [comment]
Hi @Guillembonet, sorry to open when closed, I was reviewing my connections and I'm on version 1.4.1. My node id is:

0x5c60a3aeb9573ef7aac1e08ed4917c15c3ee042c

![image](https://user-images.githubusercontent.com/40744673/158021986-9354ed2f-fe13-4fb2-9a5b-b6766c80f047.png)

I have many connections that did consume, but did not pay. Is this a UI bug? Or an actual issue on the payment?

Cheers!

**Comment by hishamaw** [comment]
@Guillembonet  sir still not resolved
![MYST](https://user-images.githubusercontent.com/101164451/158024672-39518b6d-2087-4f2c-b4e7-a6bc30aa8d2a.jpg)

**Comment by hishamaw** [comment]
Today resolved for new sessions only, thank you.
is there a way to prevent this to happen again as all old sessions I will not get paid for it forever as I see

**Comment by Guillembonet** [comment]
I don't think you can recover payments for old sessions, node should not allow connections if you are not getting paid, but since the error was returned by hermes we probably were not dropping the connection for it. Anyway it should not happen again and we will be adding more improvements soon to prevent it further @hishamaw 
@kiraitachi let me know if you are still seeing this 0 myst sessions, I'll also take a look now

**Comment by hishamaw** [comment]
@Guillembonet, thank you for your reply. have a nice day.
