### ISSUE TITLE
NodeUI - API key update results in validation error

### ISSUE THREAD

**Issue by HashZero81** [mysteriumnetwork/node#4821]
**Describe the bug**
Validation error is returned on the node dashboard when updating/changing the API key

**To Reproduce**
1. Log into "My Nodes" of newly created account to get the new API key.
2. Head over to the Node dashboard and log in (node needs to have already been claimed in some mystnodes account)
3. Go to "Settings," enter the new API key and click "Save"
4. Error returned:  "Error - Validation Error."  In addition the node is not showing on the "My Nodes" page.

**Expected behavior**
The API key should be updated and the node displayed on the "My Nodes" page.

**Screenshots**
![Error](https://user-images.githubusercontent.com/100466154/155837511-5fa60a82-e72d-414e-9f6a-b6c5d2ee4311.PNG)

**Environment (please complete the following information):**
 - Node version: mainnet (1.3.3-bf5cd483)
 - OS: Ubuntu 20.04.4 LTS

**Additional context**
Error log show the message below

MMN registration:  server response invalid:  500 Internal Server Error (https://mystnodes.com/api/v1/node){"errorCode":"databaseError","message":"Database error"}

**Comment by etherunit** [comment]
Solution: restart node, refresh mystnodes.com page, re-enter the API key and click Save.
Please let us know if that helps.

**Comment by HashZero81** [comment]
Sadly it did not worked.  Still getting the same error.

I tested with a second node, which resulted in the same error.  On the second node, I went one step further to completely uninstall the node with apt purge, removed any additional folders I could found for myst nodes and do a re-installation.  This also resulted in the same error.

**Comment by etherunit** [comment]
@HashZero81 @ozzono 
Before our QA will step in and make a round of testing, could this be tried in Incognito mode? Before doing that, make sure that node is running the latest available public version: https://github.com/mysteriumnetwork/node/releases/tag/1.4.1

**Comment by HashZero81** [comment]
Hi

I am able to replicate the issue in Incognito mode as well.  I am still getting the validation error.

**Comment by etherunit** [comment]
@HashZero81 With the latest node version? 
@lusine-h Could you try to replicate this on your machine?

**Comment by etherunit** [comment]
Getting the same problem.
![Screenshot 2022-03-09 at 09 30 20](https://user-images.githubusercontent.com/60128746/157393586-929329b5-83e1-4cae-b4b0-2269f68d63ba.png)

**Comment by Robin-Sch** [comment]
https://github.com/mysteriumnetwork/node/issues/4693#issuecomment-1026250310 This fixed it, make sure to settle and withdraw everything because else you lose it
