### ISSUE TITLE
not receiving MYST from connections

### ISSUE THREAD

**Issue by Bullameister** [mysteriumnetwork/node#4823]
**Describe the bug**
i haven't received MYST for about a week

**Expected behavior**
to receive MYST

**Screenshots**
![1](https://user-images.githubusercontent.com/95347004/155950859-9c6f171c-2f76-4ba4-9d0e-c2d016904b1a.PNG)
![2](https://user-images.githubusercontent.com/95347004/155950864-1bd3acdd-accd-4791-acc4-200d67c060c5.PNG)
![3](https://user-images.githubusercontent.com/95347004/155950867-a7e8d845-0386-4802-aee4-dfe74a1fbd32.PNG)
![4](https://user-images.githubusercontent.com/95347004/155950868-442cf772-8696-4eaf-86d7-1a35ce45b553.PNG)
![5](https://user-images.githubusercontent.com/95347004/155950870-79e11716-f90a-4296-877a-064c4fd89995.PNG)
![6](https://user-images.githubusercontent.com/95347004/155950873-60830c8b-2b73-41f1-bac5-9419b50c324e.PNG)
![7](https://user-images.githubusercontent.com/95347004/155950874-348f14d6-b3c2-4b31-a1e0-2820f0d41570.PNG)
![8](https://user-images.githubusercontent.com/95347004/155950875-e30c1a27-0127-45c8-b398-fb8d7f67c49e.PNG)
![9](https://user-images.githubusercontent.com/95347004/155950878-6c7bba5d-3a82-45f8-830c-dd57f674c52b.PNG)
![10](https://user-images.githubusercontent.com/95347004/155950879-78777257-6bb0-409c-84f2-7bf657b97840.PNG)
![11](https://user-images.githubusercontent.com/95347004/155950880-598428bf-0ea6-4c60-a175-b3da5b54479d.PNG)
![12](https://user-images.githubusercontent.com/95347004/155950882-13c20bc1-efd0-4d20-8886-81e0508ff2e3.PNG)
![13](https://user-images.githubusercontent.com/95347004/155950884-6e89573b-6c1e-44cb-877f-535ef4517e0b.PNG)
![14](https://user-images.githubusercontent.com/95347004/155950888-0eb3d55f-ad5e-48df-abb0-df4e07a2b5ad.PNG)
![15](https://user-images.githubusercontent.com/95347004/155950890-4f69eb37-a254-4794-bc7f-a3a4bc50f524.PNG)
![16](https://user-images.githubusercontent.com/95347004/155950895-bbe0df6e-4955-447b-a10e-4e7ef02f2fa8.PNG)
![17](https://user-images.githubusercontent.com/95347004/155950896-bf17cbae-a763-4b45-aaa7-13d49d56b301.PNG)

**Environment (please complete the following information):**
 - Node version: mainnet (1.2.4-c0cbfaab)
 - NodeUI version: 1.7.1
 - OS: debian 10
 - Docker latest
 - Your identity (if applicable): [e.g. 0x57d4b3dd67a1436868fcd5bed7052daae9878fd2
 

**Additional context**

**Comment by etherunit** [comment]
@Bullameister Please try to [update your node](https://docs.mysterium.network/node-runners/setup/updating/) and see if problem remains.

**Comment by Bullameister** [comment]
That worked thanks heaps
