### ISSUE TITLE
Node says it's online, portal says it's never seen the node.

### ISSUE THREAD

**Issue by mauroferra** [mysteriumnetwork/node#4828]
**Describe the bug**
The node UI reports an online status:
<img width="539" alt="Screenshot 2022-03-01 at 2 46 01 PM" src="https://user-images.githubusercontent.com/40890242/156180409-5996cd2f-c2b7-4ff5-ba96-da1c16f91404.png">

However the portal reports that the node has never been seen online:
<img width="1409" alt="Screenshot 2022-03-01 at 2 47 22 PM" src="https://user-images.githubusercontent.com/40890242/156180999-dd4a4220-e0d4-4345-940b-d7dc629a9f2a.png">

**To Reproduce**
Reproducible by logging into my node and my account, not sure if this section applies in this case.

Anyhow:
1. Log into the node's UI and access the path /#/dashboard
2. Verify that the status of the node is Online and the field "Accepting connections" shows "All"
3. Access https://mystnodes.com/nodes and verify, on the other hand, that the node shows offline / never seen.

**Expected behavior**
The node status should properly update to Online

**Screenshots**
Added inline above

**Environment (please complete the following information):**
 - Node version: n/a
 - OS: n/a
 - Desktop app version (if applicable): n/a
 - Docker (if applicable): Docker version 20.10.3, build b455053
 - Your identity (if applicable): 0x4202610f06f7997067ee886775668dfd09a398f7
 - Payment (top-op) reference (if applicable): 0xe61f48Fe5DA2a47b44be5aE2f6d671975d615321

**Additional context**
Node registration was broken last week and up until yesterday, as confirmed to me by one of your Support representatives. I performed a total of 4 payments via card, each of about 1.2 EUR, which should give me about 12 MYST. Today the registration succeeded, but my node currently shows a balance of 6.6 MYST instead.

**Comment by adinetech** [comment]
It can take some time to show online because the test agent has to test your node.

**Comment by mauroferra** [comment]
It had been a few hours actually with no sign of change. Of course in the moment i decide to bother the developers, it fixes itself :)

Issue resolved.

Thanks,
Mauro
