### ISSUE TITLE
Node Shows ON Hold after Connecting

### ISSUE THREAD

**Issue by comdanluk** [mysteriumnetwork/node#4832]
When I connect to a Node after showing connected, It will automatically go ON Hold after some seconds.

**Expected behavior**
I expect my Mysterium account to connect without changing back to On Hold after connectWhen I connect to a Node after showing connected, It will automatically go ON Hold after some seconds.

**Expected behavior**
I expect my Mysterium account to connect without changing back to On Hold after connecting

![Screenshot_20220303-054737](https://user-images.githubusercontent.com/100838043/156550294-5112410f-be75-4164-8b64-00c6117916fb.jpg)

![Screenshot_20220303-054930](https://user-images.githubusercontent.com/100838043/156550313-a793967c-ed28-451e-86b7-5919a058e152.jpg)

 - Node version: [e.g. 0.68.1]
 - OS: [Infinix Hot 11 play,  11]

 - Your identity 
0x4bcff5cc673ed24a9f732ad4b47b03d4da0c6c42

**Additional context**
After connecting to a Node it will Just stop working I won't be able to browse, Then after some seconds it will just show 'ON HOLD'. 
I have tried different and several nodes same problem. 
And it's also takes alot of time to connect.

As you can see in the image attached above It shows where a Node was connected and after some seconds it started showing :ON HOLD:ing

![Screenshot_20220303-054737](https://user-images.githubusercontent.com/100838043/156550294-5112410f-be75-4164-8b64-00c6117916fb.jpg)

![Screenshot_20220303-054930](https://user-images.githubusercontent.com/100838043/156550313-a793967c-ed28-451e-86b7-5919a058e152.jpg)

 - Node version: [e.g. 0.68.1]
 - OS: [Infinix Hot 11 play,  11]

 - Your identity 
0x4bcff5cc673ed24a9f732ad4b47b03d4da0c6c42

**Additional context**
After connecting to a Node it will Just stop working I won't be able to browse, Then after some seconds it will just show 'ON HOLD'. 
I have tried different and several nodes same problem. 
And it's also takes alot of time to connect.

As you can see in the image attached above It shows where a Node was connected and after some seconds it started showing :ON HOLD:

**Comment by etherunit** [comment]
There may be a time when you encounter an issue with your node and we may ask you to submit your logs for further investigation. Click the "report issue" button to submit this information.

**Comment by comdanluk** [comment]
Thank you for your response I already filled the Logs details in the bug
message report. but if you can tell me the particular information you need
I will provide them

When I connect to a Node after showing connected, It will automatically go
ON Hold after some seconds.

**Expected behavior**
I expect my Mysterium account to connect without changing back to On Hold
after connectWhen I connect to a Node after showing connected, It will
automatically go ON Hold after some seconds.

**Expected behavior**
I expect my Mysterium account to connect without changing back to On Hold
after connecting




 - Node version: [e.g. 0.68.1]
 - OS: [Infinix Hot 11 play,  11]

 - Your identity
0x4bcff5cc673ed24a9f732ad4b47b03d4da0c6c42


**Additional context**
After connecting to a Node it will Just stop working I won't be able to
browse, Then after some seconds it will just show 'ON HOLD'.
I have tried different and several nodes same problem.
And it's also takes alot of time to connect.

As you can see in the image attached above It shows where a Node was
connected and after some seconds it started showing :ON HOLD

 - Node version: [e.g. 0.68.1]
 - OS: [Infinix Hot 11 play,  11]

 - Your identity
0x4bcff5cc673ed24a9f732ad4b47b03d4da0c6c42


**Additional context**
After connecting to a Node it will Just stop working I won't be able to
browse, Then after some seconds it will just show 'ON HOLD'.
I have tried different and several nodes same problem.
And it's also takes alot of time to connect.

As you can see in the image attached above It shows where a Node was
connected and after some seconds it started showing :ON HOLD:

**Comment by comdanluk** [comment]
> There may be a time when you encounter an issue with your node and we may ask you to submit your logs for further investigation. Click the "report issue" button to submit this information.

Here's my identity address
0x4bcff5cc673ed24a9f732ad4b47b03d4da0c6c42


Can you please tell me how I can get my Mysterium logs so I can provide them

**Comment by etherunit** [comment]
You can submit logs directly within Android app. Click on the "three bars" button on the left right, then Help and submit a report from there. Team will investigate it ASAP.

**Comment by comdanluk** [comment]
Have done that several times, I did not have the issue resolved

**Comment by comdanluk** [comment]
Hello I have reported the bug as instructed and till now am still
experiencing this same issue.

My node connect but it's doesn't work

**Comment by isaackielma** [comment]
0x6d3a0c468551a845ba67cdd808255adede76c53e

Platform: Android, Message: My Node goes on Hold automatically after connecting

have tried different nodes but it keeps getting on hold after connecting

Logs
https://mystnodes.com/support/logs/2022-03-08-95e52275-7d36-4f41-89dc-3f425c3fb0f3-mysterium-node.zip2752128386

**Comment by comdanluk** [comment]
I can't find the node that's is sent..
