### ISSUE TITLE
Claiming Nodes.

### ISSUE THREAD

**Issue by 99Vic** [mysteriumnetwork/node#4835]
I download and install the Mysterium Node download, then install on a raspberry Pi Micro SD card.  I Plug it in the raspberry Pi and wait a few minutes.  Check the web, Nothing - unable to connect.!    Twenty minutes later, I check again, Nothing - unable to connect.  I tried again later and the next few days; Nothing - unable to connect.

Micro-SD card is plugged into the SD card slot.  My Raspberry Pi is plugged in with the appropriate power source and equipment.   Turned on the Pi.  ssh into the pi and update pi software system.   Nothin, I can't connect and claim my node.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
Check if you are able to ping your rpi device; `ping raspberrypi.local`
copy output IP,  open browser and enter raspberrypi:4449
alternatvely, try another login methods: https://docs.mysterium.network/node-runners/node-ui/#how-to-login

**Comment by etherunit** [comment]
Closed due to inactivity.
