### ISSUE TITLE
Articles provided by the bot are not working 'not found'

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4837]
**Describe the bug**

Links not working:

[A clear and concise description of what the bug is.](https://docs.mysterium.network/en/articles/4517647-how-to-get-submit-your-node-logs-if-there-is-no-access-to-the-application-interface-ui?utm_content=article_4517647

https://docs.mysterium.network/en/articles/3777471-manual-port-forwarding?utm_content=article_3777471

https://docs.mysterium.network/en/articles/3440034-supported-node-runner-platforms?utm_content=article_3440034)

**Screenshots**
<img width="718" alt="Screenshot 2022-03-03 at 23 46 56" src="https://user-images.githubusercontent.com/84313603/156689789-80f3ab4c-cbfd-4fcb-8a2f-d62cf9524fae.png">
<img width="1431" alt="Screenshot 2022-03-03 at 23 47 17" src="https://user-images.githubusercontent.com/84313603/156689830-6dab34b6-f050-4d85-a0df-bc3e8e929684.png">

**Comment by etherunit** [comment]
@isaackielma This gonna be fixed with our new documentation and newly embed links.
