### ISSUE TITLE
ON Hold after some seconds during session

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4838]
When I connect to a Node after showing connected, It will automatically go ON Hold after some seconds.

**Expected behavior**

I expect my Mysterium account to connect without changing back to On Hold after connectWhen I connect to a Node after showing connected, It will automatically go ON Hold after some seconds.

**Expected behavior**

I expect my Mysterium account to connect without changing back to On Hold after connecting

- Node version: [e.g. 0.68.1]

- OS: [Infinix Hot 11 play, 11]

- Your identity

0x4bcff5cc673ed24a9f732ad4b47b03d4da0c6c42

**Additional context**

After connecting to a Node it will Just stop working I won't be able to browse, Then after some seconds it will just show 'ON HOLD'.

I have tried different and several nodes same problem.

And it's also takes alot of time to connect.

As you can see in the image attached above It shows where a Node was connected and after some seconds it started showing :ON HOLD

- Node version: [e.g. 0.68.1]

- OS: [Infinix Hot 11 play, 11]

- Your identity

0x4bcff5cc673ed24a9f732ad4b47b03d4da0c6c42

**Additional context**

After connecting to a Node it will Just stop working I won't be able to browse, Then after some seconds it will just show 'ON HOLD'.

I have tried different and several nodes same problem.

And it's also takes alot of time to connect.

As you can see in the image attached above It shows where a Node was connected and after some seconds it started showing :ON HOLD:

[Screenshot_20220303-054737.jpg](https://my-mysterium-network.intercom-attachments-5.com/i/o/474482062/a80e21e25212b61883f90534/Screenshot_20220303-054737.jpg?expires=1646366377&signature=980fd807d8825182cabe78d092088d5658188d943d4b10b76e32e8b92a315bcf)
[Screenshot_20220303-054930.jpg](https://my-mysterium-network.intercom-attachments-5.com/i/o/474482068/a851a056ec647fc322bef5c1/Screenshot_20220303-054930.jpg?expires=1646366377&signature=3e8f104bebcbc754faba7e39f29e4e11f6c6c3baaf3153ccfe1b280a8784d171)

**Comment by etherunit** [comment]
Need logs to start looking.

**Comment by comdanluk** [comment]
Hello I have reported the bug as instructed and till now am still
experiencing this same issue.

My node connect but it's doesn't work
