### ISSUE TITLE
UI shows all value 0 but nodes are working 

### ISSUE THREAD

**Issue by BillyTi** [mysteriumnetwork/node#4839]
Hey Team, 

After update my nodes to 1.4 all node UI's show 0 
0 Balance 
0 Sessions 
no settings 
and "All Services Offline" 

but the nodes are still working i can see it in in mynodes overview 

All nodes running ubuntu 

![myst_error2](https://user-images.githubusercontent.com/8103413/156718394-5d33b7cc-2db5-4c0f-aadb-d55bb48796d7.png)

**Comment by tomasmik** [comment]
Did you try incognito mode on your browser?

**Comment by etherunit** [comment]
All services are offline, node has failed to start. Please share us with your node id @BillyTi and team will look into it.

**Comment by BillyTi** [comment]
> Did you try incognito mode in your browser?

yes diffrent browser and also incognito ...

**Comment by etherunit** [comment]
@BillyTi Is it possible to provide us with your node id? Thanks
