### ISSUE TITLE
Withdrawal created a transaction but the Mysterium is "stuck"

### ISSUE THREAD

**Issue by paulodell** [mysteriumnetwork/node#4841]
I have now created two withdrawals and both have completed (txn urls below), BUT they are not visible in my wallet (MEW) - previously the payments were visible.

I notice that when it worked the Coin is called "Mysterium" and now it is labelled "Mysterium (PoS)".

How can I get the two transactions below visible in my wallet or into the correct wallet?

**Environment (please complete the following information):**
 - Node version: 1.4.1
 - OS: Raspbian GNU/Linux 10 (buster)
 - Withdrawal reference(s): 
 -     https://polygonscan.com/tx/0x9989adfc8522dea589670e3fce8dc1b366f11cb5ad452976203293a3583e0411
 -     https://polygonscan.com/tx/0xd9f2902c822b67022f6e811d99335aef862af5e6dfd3c88553b9b1afb2984c39

**Comment by tomasmik** [comment]
MYST address on polygon is: 0x1379E8886A944d2D9d440b3d88DF536Aea08d9F3

Make sure youre using Polygon mainnet and your tokens are configured correcly. Money is clearly in your wallet as evident here: https://polygonscan.com/address/0x087574feb2f950bd04ed7658693e2979ac4613e3
