### ISSUE TITLE
myst UI does not update balance, traffic and bandwidth

### ISSUE THREAD

**Issue by morelo-coin** [mysteriumnetwork/node#4844]
**Describe the bug**
After updating to 1.4.0 and up with the newer look interface (30 days values) the values stay all at 0.
Meanwhile al my 8 connected nodes ui show increasing balance and traffic.

**To Reproduce**
1. Go to '(https://mystnodes.com/nodes)'
2. all values show  0

**Expected behavior**
Expected behavior: showing increasing balance, traffic and bandwidth on the mysterium ui

**Screenshots**
![image](https://user-images.githubusercontent.com/85998043/156893751-856cc950-713d-4a4d-8cab-205b94e175c9.png)

**Environment (please complete the following information):**
 - Node version: [1.4.2
 - OS: [e.g. raspbian buster, windows 10]
 - Your identity (node ID): [0x12a7bf687fa1b26b733d1892f15e29c67c213a40], 0x8954c984efc3a7c159c6a68bf37d8ed4779ce334, 0x999c1b0a5910e323e97fcc79357ff869ba5a6d7f, 0x51a833abb424e19bd1ba4715108113386eb2e6b6, 0x6143913140622e33ff7bcbdc0e0c9f5aa63ac194, 0xf12024bca92e50a5f28b5875652a8bfded1f46d9, 0xd17e5a6e44cd28979d18f706304780f0ad37d8d4, 0x48a13ec9ce283b1577a8f7295b06ca47d21973da
 - Payment (top-op) reference (if applicable): [0xaBD4c76BB11CBBF4B5F746A13be21fBB2eC1da55]

**Comment by etherunit** [comment]
Do you still experience this issue?

**Comment by morelo-coin** [comment]
Yes I do. all values still show 0 as shown in the screenshot, node ui show increased of balance and traffic

**Comment by etherunit** [comment]
Have you tried an incognito window? Is there any effects while using it?

**Comment by morelo-coin** [comment]
ok? when using incognito mode with chrome the balance, traffic etc does show correctly. is this a must to have the site run like this?

**Comment by kiraitachi** [comment]
This probably an issue on your side @morelo-coin. Delete cookies and everything on your browser, that's why he suggested incognito mode. It happens to many sites when some stuff gets cached, etc.

**Comment by morelo-coin** [comment]
I've removed all cookies, even from a fresh computer the result is the same. no values shown  just  all  zero. incognito mode shows correct values.

**Comment by kiraitachi** [comment]
Unless in other computer also has the issue, I see no reason why it works on incognito and not after cleaning cookies, cache, etc....

Could you try another browser just for a quick test?

What browser are you using?

**Comment by morelo-coin** [comment]
I tried firefox, google chrome and they all showed 0 on all computers. I just tried edge and that one showed the balances in a correct way just like incognito mode of google chrome. so not sure why only edge and google chrome incognito mode shows the correct values.

**Comment by etherunit** [comment]
@morelo-coin We have done a significant amount of improvements. Do you still experience this issue on your end?

**Comment by morelo-coin** [comment]
Yes I do, but I can live with simply right clicking the url and open incognito.

Get BlueMail<https://bluemail.me> for Desktop

etherunit wrote:



@morelo-coin<https://github.com/morelo-coin> We have done a significant amount of improvements. Do you still experience this issue on your end?

**Comment by kiraitachi** [comment]
I'm building a Firefox ESR sandboxed version with Vmware Thinapp. I'm setting the Windows 2021 LTSC VM as soon as that setup I will lunch Vmware Thinapp and fully sandbox a fresh Firefox in a Fresh OS to send the .exe to you. That way we can distinguish if it's a browser issue or not.

If it works, it means it's some data stored or cached on your computer so issue is on your side. If it doesn't work, means some issue on website backend with your account?

The idea is to fully isolate a browser from your environment that you can test and see for yourself. I will have this done by today.

Keep in mind I don't work for Mysterium. I'm just a regular Joe, that recently has been accepted as ambassador for Mysterium....

Will keep you on the loop @etherunit

**Comment by kiraitachi** [comment]
Hi @morelo-coin.

I know issue is closed, but somehow, it's because you decided to live with it. Can you download this portable browser "Firefox" since it was the one giving issues even in incognito. Since its sandboxed and portable, it should work. If it doesnt...probably an error on backend on your account.

I uploaded the file to IPFS so that is available across the world.
https://cloudflare-ipfs.com/ipfs/QmQr8hPUGEW3udSUAujhnyz6W3w3Yc7upcTqoqiojce2xE
or here
https://ipfs.io/ipfs/QmQr8hPUGEW3udSUAujhnyz6W3w3Yc7upcTqoqiojce2xE

If links goes slow or bad let me know I will upload to other services.

Let us know the feedback.

Cheers!
