### ISSUE TITLE
[windows] many OnHold, wsasend: An established connection was aborted by the software in your host machine."

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4847]
**Describe the bug**
Getting into many connection freezes (OnHold state), errors like wsasend: An established connection was aborted by the software in your host machine."

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8192291/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.6
 - OS: Windows

**Comment by isaackielma** [comment]
Issue on the app side: 
https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/269
