### ISSUE TITLE
MYST Balance Reduced

### ISSUE THREAD

**Issue by yariadhi** [mysteriumnetwork/node#4849]
Hi All,

Is there anyone here experienced the MYST balance reduced without trace?

As per today I just noticed that my MYST balance was reduced. The initial balance received for opening node is USD $1, and received around 3.0 something MYST, a day after the balance suddenly become 2.6477861 MYST. I have been checking on the Ethereum Blockchain Explorer and there's no any transaction recorded. This node was marked by Mysterium Network as "residential"

![image](https://user-images.githubusercontent.com/101096305/157002102-9fb4ea95-7b12-4266-9e42-cc84a6553a5b.png)
 
While I have added another nodes after few minutes later after creating first node and depositing another USD $1; received around 3.0 something MYST balance; and my second node was marked as "hosting" however, I didn't facing same issue as above, as per today my MYST balance still same.

![image](https://user-images.githubusercontent.com/101096305/157002988-521f49ea-3d6a-45ba-97c8-53a54641ce4e.png)

**Comment by adinetech** [comment]
Hey, check https://polygonscan.com/ with your Payment Channel, which can be found from the settings of the node UI.
