### ISSUE TITLE
No Contract code at given address #4667

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4850]
**Describe the bug**
[A clear and concise description of what the bug is.
](https://github.com/mysteriumnetwork/node/issues/4667)

Same issue as provided on last post, Version 1.4.1 tested beta as well, 1.4.2, but onboarding didn't work as well. I made backup, downloaded image again, pushed backup, that didn't work neither. Run new install, tried editing node, got stuck on same level. Etc...

Followed comments on github, your documentation etc.. but when I saw that nothing is working I decided to contact you directly.

Tried again, just now, because I got page for free onboarding, and this is error output: https://paste.lugons.org/?66b4749549410166#6Ej6QhjduaQ1jfJj1To7UcD59wCVKpzxhmhnh2SQFiqJ

**Comment by etherunit** [comment]
`2022-03-07T13:29:47.462 ERR identity/registry/registry_contract.go:261 > registration reported as failed by transactor, will check in bc just in case`
All attempts to complete the registration failed > https://transactor.mysterium.network/api/v1/identity/0x6c48ac00fdde39b22f5f279ba3565111bc9a15b7/status

**Comment by etherunit** [comment]
what does he see exactly? does he press some button to do free registration?

**Comment by etherunit** [comment]
@isaackielma

**Comment by etherunit** [comment]
Yep, seeing it fails all the time -- > https://transactor.mysterium.network/api/v1/identity/0x0d08e616799d49ff1f67e90c7df767bc8ac09a3d/status

**Comment by etherunit** [comment]
Again it could be related to the problem with free regs described here: https://github.com/mysteriumnetwork/node/issues/4862

**Comment by etherunit** [comment]
@Guillembonet might confirm?

**Comment by Guillembonet** [comment]
would be nice to retry and send some logs, I can't see any so its hard to see whats going on @etherunit @isaackielma
