### ISSUE TITLE
wg error: could not configure kernel space device: operation not permitted

### ISSUE THREAD

**Issue by mrtipgo8** [mysteriumnetwork/node#4851]
**Describe the bug**
When initiating a node test, logs show an error:

ERR core/service/session_manager.go:187      > Session failed, disconnecting error="cannot get provider config for session xxxxxxxxxxxxxxxx: could not start new connection: could not start provider wg connection endpoint: could not configure device: could not configure kernel space device: operation not permitted"

Due to the error, the node is not accepting sessions, but it shows Online in the mystnodes UI.

**To Reproduce**
1. Install CentOS 7 64 bit on KVM VPS
2. Install wireguard and setup latest node release binary package myst_linux_amd64.tar.gz
3. Start a node test
4. Observe this error in the Mysterium logs

**Expected behavior**
Expected test to be successful with no error in logs

**Environment (please complete the following information):**
 - Myst node 1.4.1
 - OS: CentOS 7 64 bit

**Additional context**
The node was running without issues (accepting sessions) before 25 January 2022, and the issue started after updating the node to a more recent release around that time.

**Comment by etherunit** [comment]
what's the output for `sudo modprobe wireguard` ?

**Comment by mrtipgo8** [comment]
There is no output, which I guess is correct

**Comment by etherunit** [comment]
Could you specify what was the way you've installed a node server?

**Comment by mrtipgo8** [comment]
Install wireguard:
sudo yum install epel-release elrepo-release
sudo yum install yum-plugin-elrepo
sudo yum install kmod-wireguard wireguard-tools

Then run ansible playbook (some parts like registering with API key omitted):

#create user fot the mysterium node
    - name: create user mysteriem-node
      user:
        name: mysterium-node
        state: present

# sudoers file for the mysterium-node user
    - name: copy sudoers file for the mysterium-node user
      copy:
        src: templates/sudoers.d/mysterium-node
        dest: /etc/sudoers.d/

#create user fot the mysterium node
    - name: create user mysteriem-node
      user:
        name: mysterium-node
        state: present

# download myst binary
    - name: download myst binary
      get_url:
        url: https://github.com/mysteriumnetwork/node/releases/download/{{ MYST_VERSION }}/myst_linux_amd64.tar.gz
        dest: /opt/
        force: no

# unarchive myst
    - name: unarch myst
      unarchive:
        src: /opt/myst_linux_amd64.tar.gz
        dest: /opt/myst/
        remote_src: yes
        owner: mysterium-node

# copy myst variables file
    - name: copy myst service unit file
      copy:
        src: templates/mysterium-node
        dest: /etc/sysconfig

# copy myst service unit file
    - name: copy myst service unit file
      copy:
        src: templates/myst.service
        dest: /etc/systemd/system/

# start mysterium node service
    - name: service start
      systemd:
        name: myst
        daemon-reload: yes
        state: restarted
