### ISSUE TITLE
node working for free for two weeks

### ISSUE THREAD

**Issue by hishamaw** [mysteriumnetwork/node#4852]
**Describe the bug**
my node is not receiving any myst; please explain to me what is happening, why my server working for free for two weeks??!!.

**To Reproduce**

**Expected behavior**

**Screens
![01](https://user-images.githubusercontent.com/101164451/157189454-2df6859e-7e2c-4d65-b6b9-79d28cd3af7c.jpg)
hots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]	1.4.1
 - OS: [e.g. raspbian buster, debian 10]  Ubuntu 20.04.4 LTS
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A] 0xde05ffcd14cc3eb2abdca595ea91558a84fe141c

 - Payment (top-
[log01.zip](https://github.com/mysteriumnetwork/node/files/8203777/log01.zip)
op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by Guillembonet** [comment]
deplicate of #4820
