### ISSUE TITLE
Settlement done incorrectly

### ISSUE THREAD

**Issue by ksteink** [mysteriumnetwork/node#4857]
**Describe the bug**
I have a Myst Node that has never unsettled (it's running over a month).   The local node reports (now 3.00 Myst) and the mystnodes.com reports 0.46 Mist earnings.  Discussing with Tech Support suggested to report in GitHub a potential issue / bug.

**To Reproduce**
1. Check my local Node status shows as today March 08th 3.00 Myst with 0 Settlement.
2. Click on your Mystnodes.com portal and you will see that I have 0.46 Myst.
3. This happened after I passed the 30 days mark

**Expected behavior**
The mystnodes.com and local node web page should match the total amount of Myst mined.  I understand that withdraw and settlement happens after or each 5 Myst to avoid high transaction fees.  

**Screenshots**

Local Myst Node:

<img width="1142" alt="Myst Node earnings report" src="https://user-images.githubusercontent.com/54821265/157309150-3f6ec958-6974-464e-b6a1-0abeba6b4e86.png">

mystnodes Portal Report:

![Mystnodes Portal earnings report](https://user-images.githubusercontent.com/54821265/157309247-2fa1ef81-c107-4f05-aece-248005f768d5.png)

**Environment (please complete the following information):**
 - Node version: 1.1.9
 - OS: x86 Ubuntu Server 21.04
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A
 - Your identity (if applicable): 0x9be7b2134827deaffa3ed6d5c8882
 - Payment (top-op) reference (if applicable): 

**Additional context**
None

**Comment by mdomasevicius** [comment]
@ksteink please check with new NodeUI
