### ISSUE TITLE
Total Earnings number decreasing

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4858]
**Describe the bug**
0x50eef7a36104bce4baae4e962f1b1bef4cc29610

This node had been seeing increasing Total Earnings.

However, on mystnodes.com, the Total Earnings number was initially increasing, but recently starting to decrease

Logs
https://mystnodes.com/support/logs/2022-03-07-c28cdd8f-3783-489a-a80b-bbca0e2b7127-mysterium-node.zip787445191

**Comment by etherunit** [comment]
Try incognito mode, I still think mystnodes.com has some sort of caching issue (especially if zeores are displayed). In this case it sounds different, but worth trying.

**Comment by isaackielma** [comment]
We have tried incognito mode and the issue is still happening

**Comment by Donatas-MN** [comment]
On Mystnodes.com we're now showing earnings for the last 30 days (not from the beginning of time as before), so it better reflects current earnings. If user was earning more in the previous period, he will see lower current earnings. Ping me on Slack if more clarification is needed!
