### ISSUE TITLE
Node fails to register for free from node ui 

### ISSUE THREAD

**Issue by Guillembonet** [mysteriumnetwork/node#4862]
**To Reproduce**
1. Start node when free registrations are finished
2. Wait until they are enabled
3. Try to register for free
4. Registration fails because of timeout

**Expected behavior**
You can register

Node is not calling to the correct endpoint to register for free

**Comment by SorbanElod** [comment]
I have the same problem

**Comment by Guillembonet** [comment]
@SorbanElod for now just restart the node if free registrations are available and you'll be registered, do not trigger any manual registration
