### ISSUE TITLE
0 Bytes connections only from Netherlans

### ISSUE THREAD

**Issue by ojozef** [mysteriumnetwork/node#4863]
**Describe the bug**
I have setup node on vps (hostlinger) and so far I have only 0 Bytes connections only from Netherlans. Also I can't see this node on MysteriumVPN to connect to. Node is available to public, ports 10000-60000 are open.

**To Reproduce**
1. Install ubuntu 18.04 on Hostlinger
2. Setup node using linux guide

**Expected behavior**
Normal vpn sessions 

**Screenshots**
<img width="1198" alt="Screen Shot 2022-03-10 at 9 42 30 AM" src="https://user-images.githubusercontent.com/48872447/157622405-023c7fb4-7ff0-48d6-a340-b93c71458be9.png">

**Environment (please complete the following information):**
 - Node version: 1.4.1-5331dabd
 - OS: [Ubuntu 18.04]
 - Your identity 0x15de345eed389f2f28f045098e2d858982b78fac
 
**Additional context**
Logs:
[logs.txt](https://github.com/mysteriumnetwork/node/files/8221712/logs.txt)

**Comment by adinetech** [comment]
Hostinger uses OpenVZ-based virtualization for their VPS instead of XEN/KVM, it is not possible for you to run a node because wireguard won't work with OpenVZ.

**Comment by ojozef** [comment]
Thank you for explanation!
