### ISSUE TITLE
Issue with Nodes Earnings

### ISSUE THREAD

**Issue by nferocious76** [mysteriumnetwork/node#4871]
**Describe the bug**
So, I've been monitoring my nodes in a close watch so I can accumulate more observation data from my nodes.

And this is what happened. In my nodes earnings instead of it increasing it is getting lower and lower while my `Total Earnings` in the `Node UI Dashboard` is not updating. Also, sessions are active so I am not really sure what is happening here. Am I paying instead of the one utilizing my bandwidth? lol These missing myst where did it go? I am kind of lost. Please help.

**To Reproduce**
1. Go to [Mysterium Nodes](https://mystnodes.com/nodes), and `Local Node: node_IP:4449`
2. See Nodes Dashboard and My Nodes
4. See earnings not matching up

**Expected behavior**
The earnings should be reflected in my Local Nodes or atleast the earnings in my `My Nodes` should not be getting less and less while there's an active sessions utilizing my bandwidth.

Expected earnings: 1.9 MYST

**Screenshots**
Stuck at: 
<img width="254" alt="Screen Shot 2022-03-12 at 6 21 13 PM" src="https://user-images.githubusercontent.com/8805997/158014181-5faf5388-572b-43f6-9c01-e71677166a34.png">

**Environment (please complete the following information):**
 - Node version: mainnet (1.2.4-c0cbfaab)
 - NodeUI version: 1.7.1
 - OS: Zorin OS 16

**Additional context**

**Comment by Guillembonet** [comment]
the earnings in my nodes are for the last 30 days, so they can be decreasing. Not sure what you mean about the other thing about not increasing earnings, can you elaborate?
