### ISSUE TITLE
node throws an error

### ISSUE THREAD

**Issue by Minecon724** [mysteriumnetwork/node#4872]
https://pastebin.com/raw/RFhGhHHG

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1] 1.4.1+build482701541+bionic
 - OS: [e.g. raspbian buster, debian 10] ubuntu 18.04

**Additional context**
ipv6 is disabled in the os

**Comment by Minecon724** [comment]
constantly, the node doesnt even start

**Comment by etherunit** [comment]
running it on Ubuntu 18.04?

**Comment by Minecon724** [comment]
yes

**Comment by etherunit** [comment]
I have tried to reproduce it with no luck. could you try to reinstall your node and check again at which step it fails?

**Comment by Minecon724** [comment]
i have reinstalled it without issues.
the error occurs on the systemd service start, then it enters in a bootloop

**Comment by Minecon724** [comment]
btw it is [minerstat os](https://minerstat.com/)

**Comment by Minecon724** [comment]
hello, i am still affected by this issue
