### ISSUE TITLE
No earnings from for almost 180 sessions

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4873]
**Describe the bug**

I have not received any earnings from one of my nodes for almost 180 sessions (18 pages in the UI). It shows data being transferred and no matter how much data was used, all earnings show 0.0000000 Earnings. I would like my earnings credited to my wallet

Logs:

https://mystnodes.com/support/logs/2022-03-04-f8c53166-73d4-431d-9d0d-85df112a31fe-mysterium-node.zip2205877044

**Comment by Guillembonet** [comment]
I tried connecting and checked historical data and it seems fine now, you might have been affected by a bug, but it was fixed some days ago, it should be fine and not happen again now
