### ISSUE TITLE
don't earn anything

### ISSUE THREAD

**Issue by 12jking** [mysteriumnetwork/node#4879]
**Describe the bug**
My node shows that I don't earn anything from my sessions

**To Reproduce**
idk

**Expected behavior**
I expect that my sessions pay me as normal

**Screenshots**
![Screenshot 2022-03-14 144311](https://user-images.githubusercontent.com/52884171/158461045-dce3099f-d61c-4ed8-9a8f-65471c57c412.png)

**Environment (please complete the following information):**
 - Node version: 1.4.2
 - OS: Win 10 Docker
 - Docker (if applicable): v4.4.4 and image tag: b70af2e596e5
 - Your identity (if applicable): 0x72f76d8b4f2e5465197cd46f91ee7b11f63e1325
 - Payment (top-op) reference (if applicable): 0x3Ee6A49daB35e34596Cb35289FF591DCDfb10133

**Comment by etherunit** [comment]
Could you please re-attach the screenshot?

**Comment by Guillembonet** [comment]
looks like the update solved it mysteriumnetwork/node-user-reports#6004
