### ISSUE TITLE
MYST not received after 6day connection ended

### ISSUE THREAD

**Issue by mrgupe** [mysteriumnetwork/node#4880]
I have had multiple times issues when a connection is more than a day and the issue is when something happening with a connection at my end or server all rewards are gone never reach my wallet, they are recorded in history but that not been taken action to solve the problem and to pay out to me, works best for the consumer as they got free service or wouldn't be surprised they are paying for service and all goes into contract address just not been paid out to node runner.

An easy solution would be: Payout every 5MYST as you have capped it like that already in that scenario node provider would lose less than 5MYST if an error occurs.

![progreess](https://user-images.githubusercontent.com/53581740/158250413-f04a06f7-bea0-4cc8-91c4-89099b42ae08.PNG)
![mr](https://user-images.githubusercontent.com/53581740/158250414-d15c38e6-b501-4f19-86ea-64e8be3cd3f8.PNG)
![myst](https://user-images.githubusercontent.com/53581740/158250415-55fdd6ce-76de-480e-b299-a35e0ab92e12.PNG)

Your identity
0x971d211581dd4bb2c59b68113dd4ecd0cf90ac13
Your Payment Channel
0x96e1CA548c34C729847fD8446f5d2634B4e35a80
Node version: mainnet (1.3.2-c9a0fa84)
NodeUI version: 1.7.1

**Comment by mrgupe** [comment]
it reported everywhere already

**Comment by mrgupe** [comment]
> can you use the report bug button on node ui so we can take a look at the logs?

have reported already everywhere, MYST IU/discord/telegram/github

**Comment by Guillembonet** [comment]
why do you think you have not been paid? I see you have been paid correctly, we already make node settle promises every 5 MYST. https://polygonscan.com/tokentxns?a=0x96e1CA548c34C729847fD8446f5d2634B4e35a80

**Comment by mrgupe** [comment]
I don’t think I know, there is no income if connections is ongoing if it would last months there wouldn’t be ang income from ongoing connection, payments are settled only after connection is ended in this scenario it ended when polygon crashed, it is registred in history bug I haven’t got paid for it, I’m withholding every time ehen I reach 100myst which is 3-5day frame in this time there was 6days no withdrawal because there was no income because I haven’t got paid for that connection, though you have some knowledge but seems im wrong, you could check by payments it’s clearly there is no transactions for it, and after all you just close case like it’s solved.

G. Petersons
