### ISSUE TITLE
Provider session underpaid

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4885]
**Describe the bug**

MYST earned is inadequate comparing the data and time component. Data transferred 19.9GB, MYST earned: 0.046053
**Session**: https://mainnet-grafana.mysterium.network/d/eC1DulgGz/session?orgId=1&var-session=6bcec7f7-9e1d-44ae-aad3-54d66f164cf8&var-service_type=All
Doing simple calculation based on service price that particular session should have earned him at least 2.2686MYST excluding time component.

Both provider and consumer seems to be reporting the same amount via metrics.
![Screenshot 2022-03-16 at 08 30 44](https://user-images.githubusercontent.com/60128746/158530149-17166d61-060c-4161-afd3-a0e688f79a44.png)

From the first glance at logs, node failed to update the amount of data transferred and thus failed to handle calculation properly.

Logs: https://mystnodes.com/support/logs/2022-03-15-016e9c08-b7a9-4539-965c-6fab85383bca-mysterium-node.zip1947352158

**Comment by Guillembonet** [comment]
so far I have only seen this once, so its VERY rare

**Comment by adinetech** [comment]
> > so far I have only seen this once, so its VERY rare. Contact me for some more in depth details
> 
> contact you on discord?

Yes, contact him on discord.

**Comment by adinetech** [comment]
https://github.com/mysteriumnetwork/node/issues/4900

**Comment by Guillembonet** [comment]
This issue had been fixed. If your node version is >= 1.4.9 and has a session with this (that has occurred while using that version, old sessions will still be underpaid) please report it
