### ISSUE TITLE
Which ppa to use for production?

### ISSUE THREAD

**Issue by jlsam** [mysteriumnetwork/node#4887]
**Is your feature request related to a problem? Please describe.**
Upgrading through the ppa https://launchpad.net/~mysteriumnetwork/ is much more convenient than using GitHub releases because it requires less code to automate (no need to code for version checks). I monitor new releases from the Discord #releases channel, which notifies on GitHub releases.

I've been using the [Mysterium Node](https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node) archive, but I noticed it is falling behind the GitHub releases. The latest version there is 1.4.1 from March 3rd. 

In the meantime I noticed that [Mysterium Node dev](https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node-dev) tracks much more closely the releases on GitHub, so should everyone use this instead to keep the nodes updated, or using the former archive is more stable and recommended?

**Describe the solution you'd like**
Clarification on which archive to use for production.

**Comment by tomasmik** [comment]
Stable releases are here: https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node
Latest probably fine and stable releases are here: https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node-pre
No promises for stability releases are here: https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node-dev

If there are urgent features, big fixes or anything, packages are moved to the stable release in a bout 1-2days.
