### ISSUE TITLE
Total earnings for the month keep going down

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4891]
**Describe the bug**

Total earnings for the month keep going down. The earnings have been dropping. I was on 0.36 MYST for the month, last night it had dropped to 0.30 and now its at 0.28.

Logs:

https://mystnodes.com/support/logs/2022-03-16-79aef23a-adb9-45fb-961d-9daf786b658c-mysterium-node.zip2985311938

**Comment by adinetech** [comment]
It's not a bug, now it just shows 30 days earnings instead of the earnings from the 1st day. if earnings reduce over time then total earnings shown on mystnodes.com will also reduce but true total earnings can be fetched from the node UI.
