### ISSUE TITLE
No connection for over a minute

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4892]
**Describe the bug**

There are some connectivity issue with node as except myself all connection last for less than 1 minute.

Logs:

https://mystnodes.com/support/logs/2022-03-16-e579e292-b22f-43ec-bbf4-7e6c6dbedbb3-mysterium-node.zip2721348618

**Comment by etherunit** [comment]
From the first glance at logs, I suspect iptables issue for 0xa811efb69b3c19dc221f1dfef8991afe82fffb16 based on data.

<img width="790" alt="Screenshot 2022-03-18 at 07 21 00" src="https://user-images.githubusercontent.com/60128746/158942432-65f97ea6-3f7a-4172-b09b-13d13f374839.png">

It would be helpful to request sudo iptables-save output from this provider. This way we check the chain info.
