### ISSUE TITLE
Mystberry OS segmentation fault

### ISSUE THREAD

**Issue by astronyu** [mysteriumnetwork/node#4893]
**Describe the bug**
Fresh installation on Raspberry pi using Mystberry OS. Logs shows the server is being started and stopped due to segmentation fault.

**To Reproduce**

sudo systemctl status mysterium-node.service
`myst@raspberrypi:~ $ sudo systemctl status mysterium-node.service
● mysterium-node.service - Server for Mysterium - decentralised VPN Network
   Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Thu 2022-03-17 13:10:10 CET; 3s ago
     Docs: https://mysterium.network/
  Process: 2609 ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS service --agreed-terms-and-conditions $SERVICE_OPTS (code=killed, signal=SEGV)
 Main PID: 2609 (code=killed, signal=SEGV)`

sudo journalctl -u mysterium-node.service showing 
`Mar 17 12:58:51 raspberrypi systemd[1]: Started Server for Mysterium - decentralised VPN Network.
Mar 17 12:58:51 raspberrypi systemd[1]: mysterium-node.service: Main process exited, code=killed, status=11/SEGV
Mar 17 12:58:51 raspberrypi systemd[1]: mysterium-node.service: Failed with result 'signal'.
Mar 17 12:58:56 raspberrypi systemd[1]: mysterium-node.service: Service RestartSec=5s expired, scheduling restart.
Mar 17 12:58:57 raspberrypi systemd[1]: mysterium-node.service: Scheduled restart job, restart counter is at 8.
Mar 17 12:58:57 raspberrypi systemd[1]: Stopped Server for Mysterium - decentralised VPN Network.
Mar 17 12:58:57 raspberrypi systemd[1]: Started Server for Mysterium - decentralised VPN Network.
Mar 17 12:58:57 raspberrypi systemd[1]: mysterium-node.service: Main process exited, code=killed, status=11/SEGV
Mar 17 12:58:57 raspberrypi systemd[1]: mysterium-node.service: Failed with result 'signal'.
Mar 17 12:59:02 raspberrypi systemd[1]: mysterium-node.service: Service RestartSec=5s expired, scheduling restart.
Mar 17 12:59:02 raspberrypi systemd[1]: mysterium-node.service: Scheduled restart job, restart counter is at 9.
Mar 17 12:59:02 raspberrypi systemd[1]: Stopped Server for Mysterium - decentralised VPN Network.
Mar 17 12:59:02 raspberrypi systemd[1]: Started Server for Mysterium - decentralised VPN Network.
Mar 17 12:59:02 raspberrypi systemd[1]: mysterium-node.service: Main process exited, code=killed, status=11/SEGV
Mar 17 12:59:02 raspberrypi systemd[1]: mysterium-node.service: Failed with result 'signal'.
Mar 17 12:59:07 raspberrypi systemd[1]: mysterium-node.service: Service RestartSec=5s expired, scheduling restart.
Mar 17 12:59:08 raspberrypi systemd[1]: mysterium-node.service: Scheduled restart job, restart counter is at 10.
Mar 17 12:59:08 raspberrypi systemd[1]: Stopped Server for Mysterium - decentralised VPN Network.`

myst config show is showing
`Segmentation fault`

**Expected behavior**
Server is running and node UI available on localhost:4449

**Environment (please complete the following information):**
 - Node version: [e.g. current latest]
 - OS: [e.g. mystberry]

**Comment by adinetech** [comment]
Restart the Raspberry Pi, it might work.

**Comment by astronyu** [comment]
> Restart the Raspberry Pi, it might work.

That was one of the first thing I did, unfortunately it doesn't fix anything.

**Comment by etherunit** [comment]
There is possibly a corruption of the files or hardware. I’d recommend to start from reinstalling on a new SD card.

**Comment by astronyu** [comment]
> There is possibly a corruption of the files or hardware. I’d recommend to start from reinstalling on a new SD card.

Tried reinstalling many time. It's probably hardware issue. Will move on to vps setup instead.

**Comment by otkd** [comment]
> > There is possibly a corruption of the files or hardware. I’d recommend to start from reinstalling on a new SD card.
> 
> Tried reinstalling many time. It's probably hardware issue. Will move on to vps setup instead.

Try `sudo rpi-eeprom-update -a` then reboot
