### ISSUE TITLE
Failed to send handshake initiation: no known endpoint for peer

### ISSUE THREAD

**Issue by astronyu** [mysteriumnetwork/node#4896]
**Describe the bug**
`Mar 18 14:32:45 racknerd-4f0301 myst[3423]: DEBUG: [userspace-wg]2022/03/18 14:32:45 peer(nab5…YOwY) - Sending handshake initiation
Mar 18 14:32:45 racknerd-4f0301 myst[3423]: ERROR: [userspace-wg]2022/03/18 14:32:45 peer(nab5…YOwY) - Failed to send handshake initiation: no known endpoint for `

Myst node installed on a vps and was running fine. A test from monitoring agent shows data is running. Then, I test the setup triggering monitoring again after few minutes and it shows there was no data. In the log I can see that it failed to establish handshakes.

I tried restarting the node with command 

**To Reproduce**
1. Go to 'mystnodes.com'
2. Click on 'test'
3. SSH to server with command 'sudo journalctl -fu mysterium-node.service'

**Expected behavior**
Proper handshake and vpn connected

**Screenshots**

**Environment (please complete the following information):**
 - Node version: mainnet (1.4.1-5331dabd)
 - NodeUI version: 1.7.3
 - OS: Ubuntu 18.04.6 LTS
 - Your identity (if applicable): 0xb140b50add05c1e9fc034bdf2e302e3a8a64ca0c

**Additional context**
![Screenshot 2022-03-18 223049](https://user-images.githubusercontent.com/3217740/159022084-62291e02-227a-4262-9bc4-237699344da9.png)
![Screenshot 2022-03-18 223446](https://user-images.githubusercontent.com/3217740/159022713-65b5e501-82d2-4ffd-a6d0-d6247ae578f6.png)

**Comment by etherunit** [comment]
Apologies for the delayed reply. We can see that your node is running fine and getting healthy sessions on a daily basis.

![Screenshot 2022-04-06 at 11 19 43](https://user-images.githubusercontent.com/60128746/161929326-a6d6f983-80d3-4fb7-9e11-a2b45b4e5a8e.png)

Speedtest results of our latest test:

 Server: Cox - Wichita - Wichita, KS (id = 16623)
        ISP: ColoCrossing
    Latency:   146.29 ms   (0.35 ms jitter)
   Download:   109.48 Mbps (data used: 163.3 MB)
     Upload:    94.38 Mbps (data used: 112.5 MB)
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/c1a0976d-9446-42b7-b10d-727dc36e610e
