### ISSUE TITLE
Cannot withdraw money

### ISSUE THREAD

**Issue by Bharath1910** [mysteriumnetwork/node#4901]
I get this error whenever I try to withdraw money from my Mysterium. I have a metamask wallet, and I'm using Polygon Mainnet network
my withdrawl amount is 3.63 MYST

![image](https://user-images.githubusercontent.com/72338995/159173211-b6064c11-43b1-42f8-9553-cc4d59363794.png)

how can I withdraw my money?
**My Node ID:** 0x39d8752374072e2af8713ab4f6f027cc6f553daa

**Comment by Guillembonet** [comment]
try again, should be fixed now

**Comment by Bharath1910** [comment]
It still gives me the same problem, but when I try to withdraw a fraction of my earned MYST, it successfully withdraws..
