### ISSUE TITLE
Problems installing myst onto a clean DietPi dist

### ISSUE THREAD

**Issue by speedf1** [mysteriumnetwork/node#4903]
I've previously been able to install nodes onto a RPI running dietpi.  Tried a new node a few days.  Completely fresh dietpi installation, on network that has previously had a myst node running on a Pi.  However, this time round, I get the following error message:

root@DietPi:~# grep -qxF 'deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal main' /etc/apt/sources.list || echo 'deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal main' | sudo tee -a /etc/apt/sources.list > /dev/null

root@DietPi:~# sudo apt-get update
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Get:2 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease [18.1 kB]
Hit:3 https://archive.raspberrypi.org/debian bullseye InRelease
Err:2 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ECCB6A56B22C536D
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ECCB6A56B22C536D
E: The repository 'http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by syahpian** [comment]
run this comman first then run apt-get update
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ECCB6A56B22C536D

**Comment by speedf1** [comment]
That seemed to work, thanks.
