### ISSUE TITLE
Invalid order 

### ISSUE THREAD

**Issue by Bxclass74** [mysteriumnetwork/node#4911]
hello dear
I paid btc with my own wallet
But the transaction was unsuccessful
The amount has been deducted from my wallet
Please check

I attach the payment documents
![Untitled 1](https://user-images.githubusercontent.com/102139880/159428428-d2e3d2e7-ba6d-4539-8398-e7334810989e.png)
![Untitled3](https://user-images.githubusercontent.com/102139880/159428459-42535144-d042-4fe8-8eb1-6b4762e53b32.png)
![Untitled2](https://user-images.githubusercontent.com/102139880/159428481-6d63b923-2417-40fa-82bd-9e4cebb71a51.png)
@ #

**Comment by etherunit** [comment]
@Bxclass74 Have you tried to reach out to Coingate?

**Comment by isaackielma** [comment]
Just opened an issue on coingate should get a reply soon
