### ISSUE TITLE
earning issue

### ISSUE THREAD

**Issue by pongpong83** [mysteriumnetwork/node#4912]
**Describe the bug**
![image](https://user-images.githubusercontent.com/99677999/159483829-c70f9bcc-3219-4918-803e-f62054c32fd1.png)
![image](https://user-images.githubusercontent.com/99677999/159484775-1be7c105-0fc6-4d1a-9385-97a85327e83b.png)

why the Singapore session pay so few to me?

**Environment (please complete the following information):**
 - Node version: 1.4.10-alpine
 - OS: Win10
 - Kubernetes v1.21.5
 - My identity :0x88d87415977bcb37273545fca74fd3834856d5d4

**Comment by supercjlee** [comment]
![image](https://user-images.githubusercontent.com/60121744/159597754-5a20e0e4-bf49-4e6f-932f-ee5b1930abd7.png)
Same issue.....

**Comment by supercjlee** [comment]
I am already shutdown the Mysterium Node.....wait for next version coming....not waste my bandwidth to someone free to used.

**Comment by etherunit** [comment]
Guys, please update your node. Node releases starting from 1.4.9 should include a fix for this problem.

**Comment by astronyu** [comment]
> Guys, please update your node. Node releases starting from 1.4.9 should include a fix for this problem.

Is 1.4.11 the latest for linux node and 1.4.13 for windows?

**Comment by pongpong83** [comment]
Updated, it seems ok now.

Where had the MYST gone? I didn't receive the shown amount of MYST.

**Comment by etherunit** [comment]
The amount of MYST lost is impossible to retrieve, the only way to fix it is to process with manual reimbursements. For that, please provide your node identity and affected session ids. Thanks!

**Comment by astronyu** [comment]
@etherunit will us be notified of the reimbursement?

**Comment by etherunit** [comment]
Yes, you will be notified directly in this ticket.

**Comment by supercjlee** [comment]
I already totaly shoudown my Mysterium Node....the profit too low....don't want to waste my network bandwidth.....
