### ISSUE TITLE
Everything looks correct, but node is not working

### ISSUE THREAD

**Issue by creapet** [mysteriumnetwork/node#4913]
**Describe the bug**
Hi, my node does not work. Everything looks correct, the mysterium-node.service is loaded and active. It reports as being online and available. But it also reports Test Failed.

The log of the mysterium-node.service unit looks okay to me, when a client connects it is creating myst0 interface and adding firewall and nat rules, but it does complain when deleting the qdisc settings:

Mar 19 16:29:37 orcl myst[837]: 2022-03-19T16:29:37.238 INF nat/service_iptables.go:74 > Setting up NAT/Firewall rules... done
Mar 19 16:29:37 orcl sudo[1536]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev myst0 root
Mar 19 16:29:37 orcl sudo[1536]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 16:29:37 orcl myst[837]: 2022-03-19T16:29:37.243 ??? usr/lib/go-1.17/src/io/io.go:425 > Error: Cannot delete qdisc with handle of zero.
Mar 19 16:29:37 orcl sudo[1536]: pam_unix(sudo:session): session closed for user root
Mar 19 16:29:37 orcl sudo[1538]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev myst0 ingress
Mar 19 16:29:37 orcl sudo[1538]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 16:29:37 orcl myst[837]: 2022-03-19T16:29:37.250 ??? usr/lib/go-1.17/src/io/io.go:425 > Error: Cannot find specified qdisc on specified device.
Mar 19 16:29:37 orcl sudo[1538]: pam_unix(sudo:session): session closed for user root
Mar 19 16:29:37 orcl sudo[1540]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev ifb0 root
Mar 19 16:29:37 orcl sudo[1540]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 16:29:37 orcl myst[837]: 2022-03-19T16:29:37.259 ??? usr/lib/go-1.17/src/io/io.go:425 > Cannot find device "ifb0"
Mar 19 16:29:37 orcl sudo[1540]: pam_unix(sudo:session): session closed for user root
Mar 19 16:29:37 orcl sudo[1544]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev ifb0 ingress
Mar 19 16:29:37 orcl sudo[1544]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 16:29:37 orcl myst[837]: 2022-03-19T16:29:37.268 ??? usr/lib/go-1.17/src/io/io.go:425 > Cannot find device "ifb0"

I checked with ip addr show in the 10 secs it is running that myst0 is created, but there is no ifb0:

ubuntu@orcl:~$ ip a
1: lo: <loopback,up,lower_up> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 <br> link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 <br> inet 127.0.0.1/8 scope host lo <br> valid_lft forever preferred_lft forever <br> inet6 ::1/128 scope host <br> valid_lft forever preferred_lft forever <br>2: enp0s3: <broadcast,multicast,up,lower_up> mtu 9000 qdisc pfifo_fast state UP group default qlen 1000 <br> link/ether 02:00:17:00:82:5e brd ff:ff:ff:ff:ff:ff <br> inet 10.0.100.92/24 brd 10.0.100.255 scope global enp0s3 <br> valid_lft forever preferred_lft forever <br> inet6 fe80::17ff:fe00:825e/64 scope link <br> valid_lft forever preferred_lft forever <br>6: myst0: <pointopoint,noarp,up,lower_up> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000 <br> link/none <br> inet 10.182.0.1/24 scope global myst0 <br> valid_lft forever preferred_lft forever</pointopoint,noarp,up,lower_up></broadcast,multicast,up,lower_up></loopback,up,lower_up>

The node is running in the oracle cloud, is a ubuntu 20.04 LTS.

I opened all ports from Internet to the node, except tcp/22,111,4449 and the node is connected with a public IP in public subnet using an Internet gateway. (Oracle cloud stuff = directly connected to Internet)

**To Reproduce**
1. Go to 'cloud.oracle.com and create a new account and a new VM in the free tier'
2. Set up the VM with Ubuntu 20.04 (Oracle cloud maintained)
4. Deploy Mysterium via the ppa - onboard using hosting
5. Now, mysterium.service systemd service is running, the node is available to the public and online according to mystnodes.com, but on the node itself it says test failed.

**Expected behavior**
Test is success and clients can connect for longer than 10 secs.

**Screenshots**
No screenshots

**Environment (please complete the following information):**
 - Node version: mainnet (1.4.8-ce5662f3)
 - OS: 20.04.4 LTS (Focal Fossa)
 - Client: N/A
 - Docker: N/A
 - 0xf797bb9dcbf96d11b97236e465a6981d28fe9d7d
 - Payment (top-op) reference (if applicable): N/A

**Additional context**
Normally when I use Wireguard, I have a wireguard config which I can output using the tool, 'wg'. Also I would have a wireguard network interface, usually called 'wg0'

The wg tool does not show anything at all and I guess the wg0 has been changed with myst0.

But it does seem like the Wireguard part of it is just not working, but I don't know exactly how to go about troubleshooting this, as I can gather from the log file that a lot of what is needed for the client to connect is created only when a client tries to connect, and is not just available all the time.

Anyway, let me know what you need to help me out!

**Comment by etherunit** [comment]
There may be a time when you encounter an issue with your node and we may ask you to submit your logs for further investigation. [Login to your Node UI](https://docs.mysterium.network/node-runners/node-ui/) and click the "Bug" button on the left side panel.
We will investigate it further.

**Comment by creapet** [comment]
Hello, thanks for a reply

When I click the Bug button and type a message and click Send, all that
happens is the live chat thing opens, telling me that I have no
conversations

I tried a few times - actually this is how I initially went about reporting
an issue with you. At that time, I then continued to start a new
conversation when the chat thing opened. Here I was told to submit via
GitHub -  and now you tell me to use this Bug feature :)

Anyway...


Mvh

Peter Gammelgaard


Den ons. 23. mar. 2022 kl. 09.40 skrev etherunit ***@***.***>:

**Comment by isaackielma** [comment]
https://mystnodes.com/support/logs/2022-03-23-72ad77f0-8a86-4890-a85e-041f01154f81-mysterium-node.zip2481042512

**Comment by etherunit** [comment]
Thanks for adding logs.
See the picture below. All connection attemps fails with `internet_failed` meaning that provider has certain rules in his firewall blocking packets that tries to move outside his network. 
![Screenshot 2022-03-28 at 08 52 17](https://user-images.githubusercontent.com/60128746/160334900-5021b54f-f7f8-4f99-9f5c-a801bb419323.png)

More details:

```
2022-03-28T08:54:50.623 WRN ../../../../source/requests/dialer_swarm.go:293      > Failed to lookup host: "location.mysterium.network" error="lookup location.mysterium.network on 10.182.0.1:53: dial udp 10.182.0.1:53: operation was canceled"
2022-03-28T08:54:50.623 WRN ../../../../source/requests/dialer_swarm.go:293      > Failed to lookup host: "location.mysterium.network" error="lookup location.mysterium.network on 10.182.0.1:53: dial udp 10.182.0.1:53: operation was canceled"
2022-03-28T08:54:52.236 WRN ../../../../source/requests/dialer_swarm.go:293      > Failed to lookup host: "location.mysterium.network" error="lookup location.mysterium.network on 10.182.0.1:53: dial udp 10.182.0.1:53: operation was canceled"
2022-03-28T08:54:52.236 WRN ../../../../source/requests/dialer_swarm.go:293      > Failed to lookup host: "location.mysterium.network" error="lookup location.mysterium.network on 10.182.0.1:53: dial udp 10.182.0.1:53: operation was canceled"
```

**Comment by etherunit** [comment]
I found it becomes a quite frequent problem for providers sitting behind `(hosting - Oracle Cloud)` cloud infrastructure. 
One of the ways to check it is to add a public nameserver like 1.1.1.1 or 8.8.8.8 to resolvconf. See below:
![Screenshot 2022-03-28 at 08 59 48](https://user-images.githubusercontent.com/60128746/160335591-a9409a75-fab6-4228-9080-0f55ecabd737.png)
