### ISSUE TITLE
Low earnings for large transfers 

### ISSUE THREAD

**Issue by kwadratt** [mysteriumnetwork/node#4914]
Recently got those two large transfers that generated inadequate earnings comparing to the data and time.

![Screenshot 2022-03-22 214441](https://user-images.githubusercontent.com/26044129/159585473-39c9e740-ebb5-465e-9c36-a7f007f8f55f.png)
![Screenshot 2022-03-22 214245](https://user-images.githubusercontent.com/26044129/159585509-67011fc2-18bc-4c50-b203-2da4156c4004.png)

Environment:
 - Node version: 1.4.11
 - OS: Raspbian GNU/Linux 10 (buster) on Raspberry Pi
 - Identity: 0x7cfa66a8f1cc925c5b33d47ca2afa3f65c532140

Let me know if you need any more information.

**Comment by supercjlee** [comment]
Same sympton from my side too....

![image](https://user-images.githubusercontent.com/60121744/159597585-043b8c97-08ad-458c-9c0e-5c9145fc2d39.png)

**Comment by supercjlee** [comment]
![image](https://user-images.githubusercontent.com/60121744/159597684-c48ff6a4-f400-458e-bf2d-594075b3e0a2.png)

But ? 77.43GB only got 0.0412018 MYST ?

**Comment by supercjlee** [comment]
I am already shutdown the Mysterium Node.....wait for next version coming....not waste my bandwidth to someone free to used.

**Comment by adinetech** [comment]
Please provide us the full output of session ID (you can check Latest Sessions) which underpaid you and node ID.

We will make sure to send the missing MYST amounts which happened during this incident, the issue is already resolved so kindly update your node.

**Comment by supercjlee** [comment]
Singapore
2d 01:41:08
21/03/2022, 06:29:13
0.0412018 MYST
77.43 GB
6dbe56d8

**Comment by kwadratt** [comment]
@adinetech Could you tell me how to get full output of the session ID?

My Identity: 0x7cfa66a8f1cc925c5b33d47ca2afa3f65c532140
Sessions underpaid: 
993a6f3b
3a148051

**Comment by adinetech** [comment]
@etherunit

**Comment by etherunit** [comment]
Thanks guys! We are still in the process of collecting details from affected providers. We will start to reimburse them shortly.

**Comment by kwadratt** [comment]
> Thanks guys! We are still in the process of collecting details from affected providers. We will start to reimburse them shortly.

@etherunit, @adinetech Are you still in the process?
