### ISSUE TITLE
[mystnodes.com] 30 days earning display disagree with nodeUI

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [mysteriumnetwork/node#4918]
**Describe the bug**
Hi,
In column "Earnings (last 30 days)" on mystnodes.com I see this value 1.296788 MYST for node 0xa6c1a2402edfeee5866ec21b911c297696114dd8. While there is a recent connexion that made > 3.4 MYST 2 days ago. So the numbers do not add up correctly.

See the screenshots below:

![image](https://user-images.githubusercontent.com/44687951/159761729-51a2adaf-2ef5-4f74-966e-13a9739abccd.png)
![image](https://user-images.githubusercontent.com/44687951/159762267-eeed72b2-2eb0-4b8a-852c-a26f9255c752.png)
![image](https://user-images.githubusercontent.com/44687951/159762299-242e3533-fe67-4c42-ad2a-0c2ea045d643.png)

**Environment:**
 - Node version: 1.4.13
 - Docker: Yes
 - Your identity (if applicable): 0xa6c1a2402edfeee5866ec21b911c297696114dd8

**Comment by etherunit** [comment]
Do you still experience this glitch @CharlyEmpereurmot ?

**Comment by CharlyEmpereurmot** [comment]
Hi,
Yes there is still a disagreement, mystnodes.com now saying 1.32xx MYST for this node.

**Comment by etherunit** [comment]
@LukutasV Could you take a look? I imagine it should add 3.4MYST to the balance displayed on mystnodes.com? 
Specifically for 0xa6c1a2402edfeee5866ec21b911c297696114dd8 (For the last 30 days)?

**Comment by CharlyEmpereurmot** [comment]
Hi! The 30 days count still does not include this 3.4 MYST transaction.

![image](https://user-images.githubusercontent.com/44687951/161934114-32ddf00f-f263-4853-babf-501d4dc0e481.png)

**Comment by mdomasevicius** [comment]
related to 5121
