### ISSUE TITLE
Unable to complete payment

### ISSUE THREAD

**Issue by vnanikalyan** [mysteriumnetwork/node#4919]
**Describe the bug**
Unable to complete payment while setting up the node. 

**To Reproduce**
**_step1_** : open - <ip_address>:4449
**_step2_**: click on the "start node setup" button
**_step3_**: paste the ether address
**_step4_**: 
1) On Network registration popup
2) Choose Buy MYST with Credit or Debit card
			- USD
			- India
3) Click on Next
4) Will be redirected to https://checkout.cardinity.com/
5) Unable to complete payment. Getting Payment Error message

**Expected behavior**
Should be able to complete the payment transaction for setting up the node.

**Screenshots**
![payment_error_1](https://user-images.githubusercontent.com/16670359/159763933-236229ef-aaaa-4ee7-9785-d1c4c35258f1.png)
![payment_error_2](https://user-images.githubusercontent.com/16670359/159763996-60c4cbe3-2b87-4ef7-91b2-fddd471f2571.png)

**Environment (please complete the following information):**
 - Node version: V16.14.1
 - OS: Raspbian GNU/Linux 11 (bullseye)

**Additional context**
I thought the issue was with Indian Credit Cards and asked a couple of my friends from Chicago and Pittsburg to do the transaction for me and they were also unable to complete the transaction and saw the same error message.

**Comment by tomasmik** [comment]
Can you provide additional information such as your identity, payment order ID etc. Were you charged for the payment?

**Comment by vnanikalyan** [comment]
No, I am not charged for the payment. So I don't have an order ID. 

For the last couple of days, I was trying to finish the payment. But fortunately yesterday, I could set up my node with the free option. Now my node is up and running.
