### ISSUE TITLE
Wrong earning given for the transferred data

### ISSUE THREAD

**Issue by saurav010** [mysteriumnetwork/node#4924]
I recently transferred 31.07GB data and the user was connected for more than 1D 9H and my earning from this was just 0.0731629 MYST.

If it was working properly then I was expected to earn atleast 4.05MYST.

![ss](https://user-images.githubusercontent.com/69521418/159928886-625f0502-e093-4b08-94c5-fe484245826c.png)

 - Node version: 1.4.11
 - OS: Raspbian GNU/Linux 10 (buster)
 - Your identity (if applicable): 0x4e854919a18c6b78c0613894028b4803fbd5d366

**Comment by etherunit** [comment]
Please update your node as soon as possible. Since this issue is related to the one mentioned in your ticket, I will close this one and refer to the duplicated one.

**Comment by saurav010** [comment]
I have updated my node but I still haven't gotten the MYST from the session ID 28f1f841
