### ISSUE TITLE
Withdrawl to Polygon Mainnet is not working.

### ISSUE THREAD

**Issue by mrvickter** [mysteriumnetwork/node#4926]
**Describe the bug**
When I click ok to proceed with my withdrawal I get message "There was an error processing your withdrawal. Please try again later."
I try again later, and the issue is still there. I updated my node to 1.5.0 - no resolve.

**To Reproduce**
1. Clicked withdraw button
2. Select Polygon Mainnet and click withdraw
3. Click okay to proceed.

**Expected behavior**
Expect funds to transfer to my wallet.

**Environment (please complete the following information):**
 -Node version: mainnet (1.5.0-0d5e9375) NodeUI version: 1.8.0
 - OS: Alpine Linux v3.14(docker
 - Your identity: 0x2ac86dcff181d267cf8fc9b5f835d983c3b3b1c0
 - Payment Channel: 0x6EFE7BBA8F315d6E681aDe627FEdB1dCD2fd9A6E
 - Default Withdrawal Address: 0xdBa14127a1c6dCcCEE5DcE88Cc81604734096889

**Comment by mrvickter** [comment]
This is the only thing produced in the logs when I execute the above action.

2022-03-24T20:09:35.424 INF ../../session/pingpong/hermes_promise_settler.go:471 > Marked provider {0x2ac86dcff181d267cf8fc9b5f835d983c3b3b1c0} as requesting settlement

**Comment by mrvickter** [comment]
Putting Mysterium node offline until this gets resolved. I'm getting connections and providing service, but I'm not getting paid.

**Comment by mrvickter** [comment]
I settled and withdrew these transactions on my node but they are not reflecting to the node balance.

https://polygonscan.com/tx/0x097e7ddbd9258a6ca714a85c3c2f8242fb9416c0203dc3c395f6176d2c5f2315
https://polygonscan.com/tx/0xb6164480bfa85ff5b3e76921f49d419fdb7cf82c9d36eac01f419d47c2d10f98

**Comment by Guillembonet** [comment]
https://polygonscan.com/address/0xdba14127a1c6dcccee5dce88cc81604734096889#tokentxns this is your wallet, right? your settlements are going directly there so you won't need withdrawals anymore, if they go to your wallet the balance is not expected to increase. It's working as expected as I see it, just let me know if you feel something is not okay and we can check it :)

**Comment by mrvickter** [comment]
Great, I see the two settlement transactions in my wallet. If I don't need withdrawals anymore, how do I get the 3.063784 MYST balance that was originally on the node balance? That balance was the change after purchasing the $1 worth of MYST to activate the node on setup.

**Comment by etherunit** [comment]
Reopening this issue as it was not fully solved. Closing the #4945 (duplicate).

**Comment by mrvickter** [comment]
Able to withdraw, all is well. Thank you!
