### ISSUE TITLE
Lots of data being transferred, but zero MYST earned

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4928]
Description:

ID: 0x99e0c8c13d843babea95466bebc815b75df0b69f

I see lots of data being transferred, but zero MYST has come into my account for a while. Can you review my account and let me know what is going wrong?

Logs:

https://mystnodes.com/support/logs/2022-03-14-f15adb31-cdab-4725-9b06-cdbcd35f82ac-mysterium-node.zip3360287734

**Comment by etherunit** [comment]
Is it possible to get more visual details (screenshots would be perfect)? Why it's important?
It's not clear from the current description to which side of the potential issue we might refer.

**Comment by etherunit** [comment]
@isaackielma I am closing this ticket due to inactivity. Feel free to reopen it in case you will have anymore details.
