### ISSUE TITLE
Wrong calculation - 1d session and over 90Gb of data generated 0.016Myst

### ISSUE THREAD

**Issue by eduardorothschild** [mysteriumnetwork/node#4929]
![image](https://user-images.githubusercontent.com/21217703/160081091-98bd31b6-c619-4f21-ad8a-8fd2ab9b5037.png)

Node ID 0x7da9cb1f32f309925808685da4ef4c7d3c490a7d

**Comment by adinetech** [comment]
The issue is resolved before few days, update your node.

**Comment by eduardorothschild** [comment]
> The issue is resolved a few days ago, update your node.

My node is on auto-update. What about the past?

**Comment by adinetech** [comment]
> > The issue is resolved a few days ago, update your node.
> 
> My node is on auto-update. What about the past?

Please provide us the full output of session ID (you can check Latest Sessions) which underpaid you and your node ID.

**Comment by eduardorothschild** [comment]
Both information pieces are on the ticket description.

**Comment by adinetech** [comment]
> Both information pieces are on the ticket description.

I notice, Thanks!

**Comment by saurav010** [comment]
@adinetech I have same issue please check it too. My ticket id is #4924 .

**Comment by etherunit** [comment]
Please leave your node identity and session ids so that we can process with manual reimbursements.

**Comment by eduardorothschild** [comment]
As mentioned above, my info is on the description of the ticket.

**Comment by etherunit** [comment]
It would be much more helpful if you could copy > paste it (affected session id(s).

**Comment by eduardorothschild** [comment]
Netherlands
1d 04:11:06
21/03/2022, 20:31:10
0.0160010 MYST
97.38 GB
ead5e455

**Comment by saurav010** [comment]
@etherunit my affected section Id is 28f1f84.

**Comment by saurav010** [comment]
I have updated my node but I still haven't gotten the MYST from the session ID 28f1f841

**Comment by adinetech** [comment]
Updating the node won't recover the lost MYST, the team will manually process reimbursements.

**Comment by saurav010** [comment]
Ok I got that. So I don't have to do anything from this point on and rest will be done by the team, right?

**Comment by adinetech** [comment]
Correct.
