### ISSUE TITLE
Problem with node registration

### ISSUE THREAD

**Issue by Tactictoes** [mysteriumnetwork/node#4930]
Even after using multiple browsers and with anti virus uninstalled. After chosing "Buy MYST with Credit or Debit card"
I go through the process on the payment provider which goes through without issue except that the tokens are never registered by the node UI. The money is withdrawn from my account but the UI never proceeds with registration.

Also any attempt to try again issues this error "server response invalid: 409 Conflict (https://pilvytis.mysterium.network/api/v2/payment/cardinity/orders){"error":"you can only topup if you have less than 5 MYST","field":"balance"} (path="/v2/identities/0xca7434f714193cb07cdd811fb78a1b48fc288849/cardinity/payment-order")"

Node Version: 1.4.11
Raspberry Pi OS Lite 32
System: 32-bit
Kernel version: 5.10
Debian version: 11 (bullseye)

0xca7434f714193cb07cdd811fb78a1b48fc288849

Also trying to use the chat interface from the Node UI fails as when you click in the chat box, the cursor disappears as though you never clicked in it and you cannot type anything (muiltiple browsers). The interface works fine if you go to mystnodes.com/me and use it from there.

**Comment by etherunit** [comment]
`server response invalid: 409 Conflict ([https://pilvytis.mysterium.network/api/v2/payment/cardinity/orders){"error":"you](https://pilvytis.mysterium.network/api/v2/payment/cardinity/orders)%7B%22error%22:%22you) can only topup if you have less than 5 MYST","field":"balance"} (path="/v2/identities/0xca7434f714193cb07cdd811fb78a1b48fc288849/cardinity/payment-order")"`

Based on this error in code, it seems that you are trying to top up the balance which already hold more than 5 MYST? is that correct?

**Comment by tomasmik** [comment]
It is true, there already is money in the payment channel

**Comment by Tactictoes** [comment]
Yeah, payment was successful but it refused to continue with registration, it gave this message for a day, then let me try to register for a second time which also failed, resulting in this message again.

**Comment by Tactictoes** [comment]
Free registration also failed if that is useful?

**Comment by tomasmik** [comment]
Well for me it says that you're actually registered: https://transactor.mysterium.network/api/v1/identity/0xca7434f714193cb07cdd811fb78a1b48fc288849/status

For 3 days in fact.

**Comment by Tactictoes** [comment]
Yes the registration issue was fixed for me manually.
