### ISSUE TITLE
No Payout

### ISSUE THREAD

**Issue by BLukas275** [mysteriumnetwork/node#4931]
**Describe the bug**
I get sessions, but with 0 bytes and no payout (empty sessions)

**Screenshots**
![image](https://user-images.githubusercontent.com/83073610/160125062-81a0bab0-eb37-44c1-ba3a-b831412f4080.png)

**Environment (please complete the following information):**
 - Node version: [1.8.0]
 - OS: [ubuntu server 20.04.4]
 - Your identity (if applicable): [0xf4b4c85ac4239387d91a77c352ab57caa72d15fd]
 - Payment (top-op) reference (if applicable): [0x27112df103200462Bc4C26D84B721A9F71a42948]

**Comment by etherunit** [comment]
Your node service is failing to handle an incoming connections and thus build wireguard tunnel successfully. The result is constant "test failed" and multiple sessions with 0B.
![Screenshot 2022-03-28 at 09 11 24](https://user-images.githubusercontent.com/60128746/160337128-93f0717c-98cb-4c82-9839-b8ee4c5cfa68.png)
Reason is mentioned below:

`2022-03-28T09:14:27.208 ERR ../../../../source/tequilapi/endpoints/connection.go:218 > Failed to connect error="could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session ab7f29a3-6b04-4c05-9d02-9b9dda96a010: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: permission denied"
`

**Comment by etherunit** [comment]
Firstly, please run `modprobe wireguard` and share the output.

**Comment by etherunit** [comment]
That's right. It's OpenVZ virtualization type. Please check this: https://www.interserver.net/tips/kb/tuntap-enable-openvz/
