### ISSUE TITLE
[windows] Connection gets into OnHold state frequently

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4933]
**Describe the bug**
Connection gets into OnHold state frequently. Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8352041/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.4.2
 - OS: Windows

**Comment by portalsdevs** [comment]
More logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8355067/mysterium-node.log)

**Comment by Donatas-MN** [comment]
That's old node version, please update to the newest one.
