### ISSUE TITLE
[windows] Max p2p keepalive err count reached, disconnecting

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4937]
**Describe the bug**
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8361550/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.4.2
 - OS: Windows

**Comment by Donatas-MN** [comment]
That's old node version, please update to the newest one.
