### ISSUE TITLE
Follow Up - Withdrawl to Polygon Mainnet is not working. #4926

### ISSUE THREAD

**Issue by mrvickter** [mysteriumnetwork/node#4940]
Great, I see the two settlement transactions in my wallet. If I don't need withdrawals anymore, how do I get the 3.063784 MYST balance that was originally on the node balance? That balance was the change after purchasing the $1 worth of MYST to activate the node on setup.

https://github.com/mysteriumnetwork/node/issues/4926

**Comment by Guillembonet** [comment]
you can use the withdraw button for that, should work fine
