### ISSUE TITLE
Auto settlement Not working

### ISSUE THREAD

**Issue by Nimbu00** [mysteriumnetwork/node#4946]
**Describe the bug**
Unsettled earning exceeding 5 MYST. If I am not wrong after 5 MYST a auto settlement is executed.
 Restarting node doesn't help
 Using cli to settle earning is also not working. 
 Pressing settle button in UI give a statement " settlement was executed successfully! " but nothing happen .

NODE LOG: https://drive.google.com/file/d/1RSDFGR4M9218xONo2QnsfnPZroTYNVC1/view?usp=sharing

**Screenshots**
![Screenshot_20220328-181759_RaspController](https://user-images.githubusercontent.com/87263735/160602947-a41f7070-b2d9-464c-bb62-f978d1872820.jpg)
![Screenshot_20220329-152255_Brave](https://user-images.githubusercontent.com/87263735/160602956-f3094377-a5fc-4f56-af17-47986fd78ff7.jpg)

**Environment (please complete the following information):**
 - Node version: 1.6.0
 - OS:  Mysterium Node RPI image(RPI 3B+)
 - Your identity : 0x53df0d917f502c7883bc1da75e9ee210f704edd7

**Comment by etherunit** [comment]
Do you still experience this issue? After clicking a button in UI it sometimes might take a while to process your request and settle funds into balance. if some amount of time passes without any outcome, there might be an issue.

**Comment by Nimbu00** [comment]
I waited Full day after pressing settle button . same result

**Comment by etherunit** [comment]
From the first glance at logs, seeing quite a few repeating lines of 

`Mar 29 14:32:35 raspberrypi myst[553]: 2022-03-29T14:32:35.442 ERR session/pingpong/hermes_promise_settler.go:860 > Could not calculate hermes fee error="Post \"https://polygon-rpc.com/\": context deadline exceeded"`

Need your comments @Guillembonet

**Comment by Guillembonet** [comment]
hey @Nimbu00 I advise you to ssh into that raspberry and try running `curl -I https://polygon1.mysterium.network` to check you are able to access the polygon rpc, if that is fine then the error is probably related to you network performance. I saw we have a small timeout for the call that is failing in your logs. We will increase it in the next version and it should improve your situation :)
