### ISSUE TITLE
Myst token upgrade failed because of missing payload

### ISSUE THREAD

**Issue by Razer0123** [mysteriumnetwork/node#4947]
**Describe the bug**
I was trying to update my tokens, but the tutorial is split in parts, and i thought the point 5 was the last one, so i did not insert a payload

**To Reproduce**
Follow migration steps until 5 and send tokens to the contract address

**Expected behavior**
Receiving new MYST back

Here is the transaction id
https://etherscan.io/tx/0xf98d0d8c47797f93b9b20fde935053dfd35e8589c8014a0f73ed94e56cae90cd

**Comment by isaackielma** [comment]
Currently talking with our team for a resolution of this issue. Should get an update soon.

**Comment by Razer0123** [comment]
News?

**Comment by etherunit** [comment]
@isaackielma?

**Comment by Razer0123** [comment]
Here it is

0x28cA99bC97bF09e1e2fC5CD8ff088414B49F7237

**Comment by Razer0123** [comment]
> Thanks! Tokens were sent. Please let me know otherwise!
> 
> https://polygonscan.com/tx/0xee1cb79384be822d475bfb64b0d6b69ba82273d94dd67121d4631bbbea0c7417

From the transaction ID seems you sent tokens in your wallet, not in mine

Wallet of the sender 0xee3bcec51960290bf0e69d59d0dcb2cdebfdec9b

Wallet of the receiver  0xee3bcec51960290bf0e69d59d0dcb2cdebfdec9b

So I did not receive any token

**Comment by etherunit** [comment]
Please check it now: https://polygonscan.com/tx/0xc6c6631f9400b81f2aea1139957f46950f56742e3b0463e1439b2cec16632adb

**Comment by etherunit** [comment]
Also, please be more attentive next time since this refund is out of our refund policy (act of good will). Thanks

**Comment by Razer0123** [comment]
Thank you very much
