### ISSUE TITLE
Version 1.6.1 not available via Docker Hub

### ISSUE THREAD

**Issue by mrvickter** [mysteriumnetwork/node#4951]
I am unable to pull 1.6.1 only up to 1.6.0 available.

https://hub.docker.com/r/mysteriumnetwork/myst/tags

![Capture](https://user-images.githubusercontent.com/60835163/160945873-31210170-8ab5-4e9e-bf84-a83c4f0d58af.PNG)

**Comment by etherunit** [comment]
1.6.0 is the latest tag available in docker hub (released 3 days ago).
