### ISSUE TITLE
Error validation failed

### ISSUE THREAD

**Issue by Pukorog** [mysteriumnetwork/node#4954]
After Installing the mysterium app, I tried to Top up my account using the credit card option but what I got validation failed. Which I've Never experienced before and it occurred severally.

Android version 10.
From Nigeria

![Screenshot_20220330-180523](https://user-images.githubusercontent.com/102716798/160985530-0fee6ef2-3b6f-4691-a775-47bf1d169059.png)

![Screenshot_20220330-180523](https://user-images.githubusercontent.com/102716798/160985681-c5f8045e-097c-46d8-8302-5b442a42d38c.png)

**Comment by etherunit** [comment]
Please note that due to the changes in merchant, top ups using credit card are currently unavailable (we are in the process of selecting a different one). Alternatively, use PayPal service until cc top-ups will be reimplemented.
Apologies for any inconvenience.
