### ISSUE TITLE
Error Withdraw to Metamask 

### ISSUE THREAD

**Issue by sasawwwsd** [mysteriumnetwork/node#4956]
When i click to withdraw to my metamask it give me this message

"Could not withdraw: could not call hermes pay and settle:hermes request promise error: could not request promise: could not unmarshal error body: received unknown error: expected provider channel, got consumer"

Thanks

**Comment by tomasmik** [comment]
Only providers can withdraw. You must provide traffic, you cannot have more MYST bought than it's required for registration etc.

There are measures in place which make it not possible to withdraw if you are only a consumer.
