### ISSUE TITLE
problem not connecting to servers

### ISSUE THREAD

**Issue by Saymonsandy** [mysteriumnetwork/node#4959]
Since I downloaded the VPN and using the VPN, it was not connected from the ground up via Wi-Fi. It does not work and does not connect, not even to one of the existing servers. After that, I was running the Internet with a data chip and it was working at an amazing speed, but after the new update two months ago, it does not work with the chip. Enter the program. A message appears that there is no Internet. What is the solution? Summarizing the talk via Wi-Fi, it shows all servers, but does not connect As for through a data chip, when entering the program, a message appears that there is no internet, and I have fast internet?

https://drive.google.com/file/d/1-2syzsic-XvS6BUFHj6IBRgH1Fi76iEm/view?usp=drivesdk

**Comment by etherunit** [comment]
Thanks for the detailed description. Apparently, there might be different issues, but without logs, its hard to say more.
Please submit your app/node logs for further analysis. https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs
