### ISSUE TITLE
Missing Transaction

### ISSUE THREAD

**Issue by raj174** [mysteriumnetwork/node#4961]
**Describe the bug**
One of the withdrawal transactions that I did is missing.
I made 6 withdrawals of 99MYST each and one of them are missing and I have not received the tokens.
In the wallet, I had 617 MYST now I have 22MYST. In the external wallet, I have 497MYST.
Something to note is that I did this as quickly as I could. So before I could even see the transaction shown on the UI.

**To Reproduce**
1. Go to withdraw in the node UI
2. Click on withdraw
3. Repeat the steps immediately not waiting for the transaction to show on the UI

**Expected behavior**
After doing this I should have received my tokens in the external wallet.

**Environment (please complete the following information):**
 - Node version: [1.6.2-cd08bc47]
 - UI version: [1.10.0]
 - Your identity (if applicable): [0x0a8ee5536829ce60a85b85183a3ab0e7670ec841]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Comment by adinetech** [comment]
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/68943180/161412273-abb3d94d-0d03-4c0e-a878-92119df62a93.png">
