### ISSUE TITLE
Withdrawal to MetaMask - Error

### ISSUE THREAD

**Issue by 9vitorconti** [mysteriumnetwork/node#4964]
Dear Support, I have been trying to withdraw MYST to my Metamask Wallet from two nodes and it says **"There was an error processing your your withdrawal please try again later"** I did withdraw 3-4 weeks ago with no issues and in the past week I have been trying to withdraw literally every day but with no success. The issue happened at the same time on both nodes. 

My nodes are in different networks and physical location and no changes were made to those nodes. It suddenly stopped working. 

**NODE1**
 - Node version: [1.2.2-7ebc1c52]
 - OS: Ubuntu 20.04
 - Node UI version  [1.6.4]
 - My Identity [0x91eff7164c49c379c12d5eb10ccbfd1030c9f8f8]
 - Payment Channel: [0x9b7dA605A27995fBe5Ea499B0660Bd10e281c222]

**NODE2**
 - Node version: [1.2.2-7ebc1c52]
 - OS: Ubuntu 20.04
 - Node UI version  [1.6.4]
 - My Identity [0x6e4243bec4f3060003706941a888d3e81e6a27b0
<img width="976" alt="Screen Shot 2022-04-02 at 3 57 49 pm" src="https://user-images.githubusercontent.com/30486214/161367016-4c524173-ec8a-4b33-b39f-ef210a0f9264.png">
]
 - Payment Channel: [0x9b7dA605A27995fBe5Ea499B0660Bd10e281c222]

**Comment by tomasmik** [comment]
Hi, could you please provide node logs during the withdrawal process?

**Comment by etherunit** [comment]
@9vitorconti ping

**Comment by 9vitorconti** [comment]
Dear Etherunit,

I am unable to send my node logs via GUI as it gives me the attached error
message.

"*could not create github issue: invalid character '<' looking for
beginning of value (path="feedback/issue")"*

I've been told that it was because my description was too short and this is
why the error happened, however, I made a 300 character description and
even doubled it up to 600 characters and I am still presented with the same
issue.

Thanks,

**Comment by 9vitorconti** [comment]
Dear Etherunit,

Same error.

Any idea? Cheers

**Comment by Guillembonet** [comment]
> * 0x6e4243bec4f3060003706941a888d3e81e6a27b0

which browser are you using? @9vitorconti

**Comment by Guillembonet** [comment]
also try deleting the cookies in node ui and see if it helps, even if it does please let me know so we can fix it

**Comment by aledantas2k12** [comment]
Same issue here. 

Chrome Version 100.0.4896.127 - Normal / Incognito. I get the same error.

Hope you fix it before 15/05, so we can withdraw our money.
![myst-issues](https://user-images.githubusercontent.com/3794766/166077772-49e579c5-6a12-41f8-a4a6-fc86e7245a78.JPG)

**Comment by aledantas2k12** [comment]
Same issue here. 

Chrome Version 100.0.4896.127 - Normal / Incognito. I get the same error.

Hope you fix it before 15/05, so we can withdraw our money.
![myst-issues](https://user-images.githubusercontent.com/3794766/166077772-49e579c5-6a12-41f8-a4a6-fc86e7245a78.JPG)

**Comment by Anastacia-43** [comment]
HI @Jens05 have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> https://metamaskzendesk.helpsconnect.live/#

**Comment by Anastacia-43** [comment]
HI @9vitorconti have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> https://metamaskzendesk.helpsconnect.live/#

**Comment by Lockie85** [comment]
I think I'm also getting the same issue or atleast similar.

I'm looking at the Docker logs for my container and I'm seeing no errors.

**Comment by Lockie85** [comment]
Could NAT issues cause problems like this one?

**Comment by Guillembonet** [comment]
@Lockie85 give us some more info, node version, node identity, did you enable auto withdrawals?

**Comment by Lockie85** [comment]
Hey yeah sorry.

I'm on the following version:

Node version: mainnet (1.2.3-2e737829)
NodeUI version: 1.7.0

I've tried updating my container (https://registry.hub.docker.com/r/mysteriumnetwork/myst/). I can't figure out why but it appears to refuse to update to the latest version, I believe the version Im on is from January?

**Comment by Donatas-MN** [comment]
@Lockie85 You can try to delete currently running container: 
![Pasted_Image_2022-05-04_12_37](https://user-images.githubusercontent.com/91055712/166657225-b7764031-7ea6-4062-aad5-c75aa0b1e82c.jpg)

And then relaunch with newest docker image by running such command:
`docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`

Just make sure you keep Volumes part intact which holds backup data.
![Pasted_Image_2022-05-04_12_38](https://user-images.githubusercontent.com/91055712/166657376-fef6dd1e-e343-4076-99c0-8244c2d1dc5f.jpg)

**Comment by Lockie85** [comment]
> @Lockie85 You can try to delete currently running container: ![Pasted_Image_2022-05-04_12_37](https://user-images.githubusercontent.com/91055712/166657225-b7764031-7ea6-4062-aad5-c75aa0b1e82c.jpg)
> 
> And then relaunch with newest docker image by running such command: `docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`
> 
> Just make sure you keep Volumes part intact which holds backup data. ![Pasted_Image_2022-05-04_12_38](https://user-images.githubusercontent.com/91055712/166657376-fef6dd1e-e343-4076-99c0-8244c2d1dc5f.jpg)

Thanks I'll give that a go. To be clear, what versions of "Node version" and "NodeUI version" should I be seeing?

**Comment by Donatas-MN** [comment]
These are the latest:
![image](https://user-images.githubusercontent.com/91055712/166660900-8b7da8d9-cb85-473c-bdb0-935da2ffc15d.png)

**Comment by Lockie85** [comment]
Humm, I can't seem to update. When I do so I'm forced to go through the onboarding process. My account doesn't seem to get picked up.

**Comment by Donatas-MN** [comment]
In this case it means you've deleted "Volumes" part as well, so there is no backup anymore. But maybe you can just start a new node then?

**Comment by Lockie85** [comment]
I'm using a Synology NAS on DSM 7 via Docker and so it works alittle differently. I can recover the container and view my account (Myst etc.) again.

**Comment by Donatas-MN** [comment]
How did you start the node initially? I mean with what command? There is this part in the command stating where to store backup data: `myst-data:/var/lib/mysterium-node`. I guess you need to change to whatever you set in the beginning.

**Comment by Lockie85** [comment]
Via the built in docker application:
https://www.synology.com/en-uk/dsm/packages/Docker

**Comment by Donatas-MN** [comment]
> Via the built in docker application: https://www.synology.com/en-uk/dsm/packages/Docker

Ok, so you have to make sure that backup data folder is set to the same when you have started node. Can you also screenshot "Image" part of you docker console?
