### ISSUE TITLE
[android] VPN not working. NATS: disconnected error=EOF

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4965]
**Describe the bug**
Lots of errors.
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8402081/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.0
 - OS: Android

**Comment by Donatas-MN** [comment]
That's very old node version, please update to the newest one.
