### ISSUE TITLE
[windows] After connected to bad node, getting NATS: connection closed, VPN doesn't work anymore.

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4966]
**Describe the bug**
Worked fine for many days. Then after connecting to bad node, it can't get to work.
Lots of errors.
Logs:
[mysterium-node.log.zip](https://github.com/mysteriumnetwork/node/files/8402101/mysterium-node.log.zip)

**Environment (please complete the following information):**
 - Node version: 1.4.2
 - OS: Windows

**Comment by Donatas-MN** [comment]
That's old node version, please update to the newest one.
