### ISSUE TITLE
"proxy error content cancelled."

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4971]
**Describe the bug**
node constantly goes offline with this error "proxy error content cancelled."

Logs:

https://mystnodes.com/support/logs/2022-04-04-3b527a38-8eed-4a4a-ae4c-55461218d4bb-mysterium-node.zip4099997631

**Comment by etherunit** [comment]
Please try the following node version (update manually): https://github.com/mysteriumnetwork/node/releases/tag/1.6.4

fix eventbus deadlocks by @Snawoot in https://github.com/mysteriumnetwork/node/pull/5018

p.s. let us know if that helps, thanks!
