### ISSUE TITLE
With 1Gbps network monitoring system marks node as not suitable for torrents

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4973]
If possible, I would like my node to be visible in torrent Download list. Is there anything that can be done for that to happen?

node ID: 0xe81aa5dfb615ca0b8a08c6f645000f50051d2416

logs: https://mystnodes.com/support/logs/2022-04-05-7cfb9290-24ad-47fa-b637-05deb3355b45-mysterium-node.zip4095345227

**Comment by adinetech** [comment]
All datacenter nodes will be visible in the Download list, you may suggest the user to reduce the quality filter to low and check again.

**Comment by etherunit** [comment]
@isaackielma I'm closing this for now as it's the part of the functionality. Feel free to reopen it in case any additional questions appears.
