### ISSUE TITLE
I have charged in Mysterium vpn but the balance is not showing

### ISSUE THREAD

**Issue by ibrahimis** [mysteriumnetwork/node#4974]
I have charged in Mysterium vpn but the balance is not showing
This is my first time using Mysterium vpn
Charge your account with bitcoin

  I attached all the purchase photos, wallet number, account file Jason and password

The wallet number it was Charge to:
 37ngChd5hewsteg5mRXnpRuWZUWW6F8ewS

Pictures:
![Capture](https://user-images.githubusercontent.com/37902999/161758972-1f57604f-f2a6-4ae5-a168-32dda6fd4fda.PNG)
![Screenshot_2022-04-04-17-20-04-143_com bitpapa](https://user-images.githubusercontent.com/37902999/161759220-2c872055-969f-43c2-a2ef-20a690df4ea5.jpg)

files:

**Comment by adinetech** [comment]
Please delete the Desktop.zip file, anyone can able to access the funds if your topup get completes.

**Comment by etherunit** [comment]
By the way, restarting the app (or device running it) might enforce balance to appear. But yeah, as @adinetech said, invoice and identity address would help a lot.

**Comment by etherunit** [comment]
Any updates @ibrahimis ?

**Comment by ibrahimis** [comment]
> Any updates @ibrahimis ?

Unfortunately, nothing new
