### ISSUE TITLE
Cannot Withdraw internal balance

### ISSUE THREAD

**Issue by vcerenu** [mysteriumnetwork/node#4978]
**Describe the bug**
After active automatic withdrawal in 1 node I try to withdraw the internal balance but I receive this message and not found

![image](https://user-images.githubusercontent.com/56500015/161973574-0f386e5d-c89a-415f-8ffc-c9bb198f5380.png)

**To Reproduce**
1. Click in "Withdraw" button in a main page, 
2. In the next windows click Withdraw
3. Receive message error

**Expected behavior**
Withdraw complete in my wallet

**Screenshots**

**Environment (please complete the following information):**
 - Node version: mainnet (1.6.2-cd08bc47)
 - OS: ubuntu server 20.04
 - Your identity (if applicable): 0x8af948c9b5a4ea0577cc656b40e2f71a404f172d

**Comment by pixxelspotter** [comment]
Same Problem here:

- Node version: mainnet (1.6.2-cd08bc47)
- OS: Ubuntu Server 20.04
- Your identity (if applicable): 0x5df2217e308c4380972075fcd3d783c7b93ead0b

**Comment by Guillembonet** [comment]
can you provide logs using the report a bug button please?

**Comment by Guillembonet** [comment]
@vcerenu I checked your logs (I saw you already sent them) and sadly there is nothing useful there, I'll add some logging so after the next update I can understand what is going on, in the meantime, we can try to solve it anyway if you ping me on discord. My username is bunetz#7324 . Thanks and sorry about this issue!

**Comment by pixxelspotter** [comment]
> Same Problem here:
> 
> * Node version: mainnet (1.6.2-cd08bc47)
> * OS: Ubuntu Server 20.04
> * Your identity (if applicable): 0x5df2217e308c4380972075fcd3d783c7b93ead0b

I was able withdraw, i mixed up the setup time with the 72h to be able to withdraw.

**Comment by Guillembonet** [comment]
@vcerenu did some changes externally and now your withdrawal should work, open again if it doesn't. I'll add more logging anyway so logs are useful next time :)
