### ISSUE TITLE
Withdraw Error

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4981]
Description:

When I try to withdraw my internal balance receive the message "There was an error processing your withdrawal. If this is a new node, you have to wait at least 72 hours after network registration before making the first withdrawal. Otherwise, please try again later or contact our support.
"

Logs:

https://mystnodes.com/support/logs/2022-04-06-a9b710fe-8611-49e8-a830-74f72d81829d-mysterium-node.zip979050343

**Comment by adinetech** [comment]
Is it a new node created within 3days (72hours)?

**Comment by etherunit** [comment]
No, it's not new. But it might be fixed already. 
@isaackielma Please check and feel free to reopen it in case the issue remains.
0x8af948c9b5a4ea0577cc656b40e2f71a404f172d
<img width="758" alt="Screenshot 2022-04-19 at 09 12 48" src="https://user-images.githubusercontent.com/60128746/163937872-34b25de3-2375-4884-8e8f-51b032d190a0.png">
