### ISSUE TITLE
Having a Issue with my node,  Not receving any traffic after days of being online.

### ISSUE THREAD

**Issue by Ghastly-Hollows** [mysteriumnetwork/node#4984]
So My Node has been running for over a week now and the only traffic I receive is from the Netherlands for .01 or .02 seconds.
I believe this is just the system checking to see if my node is active, I however have not received any traffic from Users and do not know if my Node was set up incorrectly.  My Node is running off of my Raspberry pi 4 using the install steps from the website.  I have not changed any settings since installation.  I was asked to submit a copy of the log;

-- Logs begin at Thu 2022-04-07 02:54:25 CDT, end at Thu 2022-04-07 08:32:18 CDT. --
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(E7Su…SI30) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(E7Su…SI30) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(E7Su…SI30) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(PU9l…1qiI) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(PU9l…1qiI) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(PU9l…1qiI) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(Tubr…bQiM) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(Tubr…bQiM) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(Tubr…bQiM) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(igQP…5W2w) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(igQP…5W2w) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(igQP…5W2w) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(kJrt…DEUU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(kJrt…DEUU) - Sending handshake initiation
Apr 07 02:54:26 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:26 peer(kJrt…DEUU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(/KpW…hGTs) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(/KpW…hGTs) - Sending handshake initiation
Apr 07 02:54:26 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:26 peer(/KpW…hGTs) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(GRzL…Kul4) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(GRzL…Kul4) - Sending handshake initiation
Apr 07 02:54:26 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:26 peer(GRzL…Kul4) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(FD6e…U+00) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(FD6e…U+00) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(FD6e…U+00) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(MBYI…gUjc) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(MBYI…gUjc) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(MBYI…gUjc) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(c05j…PE2s) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(c05j…PE2s) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(c05j…PE2s) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(tdTA…VtwA) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(tdTA…VtwA) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(tdTA…VtwA) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(/j9S…naRU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(/j9S…naRU) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(/j9S…naRU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(oVxW…6vlM) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(oVxW…6vlM) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(lbeR…zXXU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(lbeR…zXXU) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(oVxW…6vlM) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(lbeR…zXXU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(Hf4P…BQQM) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(Hf4P…BQQM) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(Hf4P…BQQM) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(c++A…UMxk) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(c++A…UMxk) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(c++A…UMxk) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(7MP+…zQGY) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(7MP+…zQGY) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(7MP+…zQGY) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(s8ww…/fVU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(s8ww…/fVU) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(s8ww…/fVU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(x0lq…3Rzc) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(x0lq…3Rzc) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(x0lq…3Rzc) - Failed to send handshake initiation: no known endpoint for peer
lines 1-58...skipping...
-- Logs begin at Thu 2022-04-07 02:54:25 CDT, end at Thu 2022-04-07 08:32:18 CDT. --
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(E7Su…SI30) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(E7Su…SI30) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(E7Su…SI30) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(PU9l…1qiI) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(PU9l…1qiI) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(PU9l…1qiI) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(Tubr…bQiM) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(Tubr…bQiM) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(Tubr…bQiM) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(igQP…5W2w) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:25 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:25 peer(igQP…5W2w) - Sending handshake initiation
Apr 07 02:54:25 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:25 peer(igQP…5W2w) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(kJrt…DEUU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(kJrt…DEUU) - Sending handshake initiation
Apr 07 02:54:26 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:26 peer(kJrt…DEUU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(/KpW…hGTs) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(/KpW…hGTs) - Sending handshake initiation
Apr 07 02:54:26 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:26 peer(/KpW…hGTs) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(GRzL…Kul4) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:26 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:26 peer(GRzL…Kul4) - Sending handshake initiation
Apr 07 02:54:26 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:26 peer(GRzL…Kul4) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(FD6e…U+00) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(FD6e…U+00) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(FD6e…U+00) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(MBYI…gUjc) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(MBYI…gUjc) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(MBYI…gUjc) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(c05j…PE2s) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(c05j…PE2s) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(c05j…PE2s) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(tdTA…VtwA) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:27 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:27 peer(tdTA…VtwA) - Sending handshake initiation
Apr 07 02:54:27 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:27 peer(tdTA…VtwA) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(/j9S…naRU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(/j9S…naRU) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(/j9S…naRU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(oVxW…6vlM) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(oVxW…6vlM) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(lbeR…zXXU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(lbeR…zXXU) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(oVxW…6vlM) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(lbeR…zXXU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(Hf4P…BQQM) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(Hf4P…BQQM) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(Hf4P…BQQM) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(c++A…UMxk) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(c++A…UMxk) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(c++A…UMxk) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(7MP+…zQGY) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(7MP+…zQGY) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(7MP+…zQGY) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(s8ww…/fVU) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(s8ww…/fVU) - Sending handshake initiation
Apr 07 02:54:28 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:28 peer(s8ww…/fVU) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(x0lq…3Rzc) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:28 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:28 peer(x0lq…3Rzc) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(x0lq…3Rzc) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(ccJu…JbHQ) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(ccJu…JbHQ) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(ccJu…JbHQ) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(9eIq…SJVc) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(9eIq…SJVc) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(9eIq…SJVc) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(oKw/…XQUg) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(oKw/…XQUg) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(oKw/…XQUg) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(3Vv9…hxmw) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(3Vv9…hxmw) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(3Vv9…hxmw) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(MX2m…gsz4) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(MX2m…gsz4) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(MX2m…gsz4) - Failed to send handshake initiation: no known endpoint for peer
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(cY/U…xhQE) - Handshake did not complete after 5 seconds, retrying (try 2)
Apr 07 02:54:29 raspberrypi myst[17453]: DEBUG: [userspace-wg]2022/04/07 03:54:29 peer(cY/U…xhQE) - Sending handshake initiation
Apr 07 02:54:29 raspberrypi myst[17453]: ERROR: [userspace-wg]2022/04/07 03:54:29 peer(cY/U…xhQE) - Failed to send handshake initiation: no known endpoint for peer
Determining length of file... (interrupt to abort)

**Comment by etherunit** [comment]
The most important thing is missing - > ProviderID.

**Comment by Ghastly-Hollows** [comment]
How do I fix that?

**Comment by adinetech** [comment]
Provide us your Provider ID.

**Comment by Ghastly-Hollows** [comment]
As in my Internet provider?

**Comment by etherunit** [comment]
Go to NodeUI > Settings > copy/paste value under **_Your identity_**

**Comment by Ghastly-Hollows** [comment]
I believe my identity is 0xa340899538bac1600fd6271a8945443506468445

**Comment by etherunit** [comment]
`2022-04-19T09:09:22.969 ERR ../../../../source/tequilapi/endpoints/connection.go:203 > Failed to connect error="could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session e31a1f27-dff8-4da6-9d8c-fc09e482d93e: failed to setup NAT/firewall rules: error calling IPTables: \"/usr/sbin/iptables -I MYST 1 --destination 10.182.59.1 --protocol udp --dport 53 --jump REDIRECT --to-ports 11253 --table nat\": exit status 2 output: iptables v1.8.2 (nf_tables): unknown option \"--dport\"\nTry `iptables -h' or 'iptables --help' for more information.\n: exit status 2"`

It's the output from my connection attempt. Firstly, please try to completely reboot the host machine/server, then I'll try again.

**Comment by Ghastly-Hollows** [comment]
node should be reset now.

**Comment by Ghastly-Hollows** [comment]
Seems that I'm getting traffic on my node now,  Not sure how it was fixed or what I did to break it originally but it is working I suppose.
