### ISSUE TITLE
Bug with infinity loading

### ISSUE THREAD

**Issue by DiogoMarques2003** [mysteriumnetwork/node#4985]
Recently my node started to stop working and to be in an infinite load when I enter the main page.
I already tried to restart node and computer but it still didn't work.

![image](https://user-images.githubusercontent.com/52538977/162218703-a44a7d70-7883-4a5d-a7f1-42eafbfdf11b.png)
![image](https://user-images.githubusercontent.com/52538977/162218895-94e98c1d-06cc-478e-b7f4-4022fbe2240e.png)
![image](https://user-images.githubusercontent.com/52538977/162218930-07d336d4-c8d7-4839-8a3e-7721cd4c61cb.png)

**Environment:**
 - Node version: mainnet (1.6.2-cd08bc47)
 - OS: ubuntu 20.04.4 LTS
 - Your identity (if applicable): 0x2cdcacc6ffdb4db74b9fb898e14d0e24e3373494

**Comment by adinetech** [comment]
https://github.com/mysteriumnetwork/node/issues/4971

**Comment by etherunit** [comment]
Related to #4999

**Comment by etherunit** [comment]
Please try the following node version (update manually): https://github.com/mysteriumnetwork/node/releases/tag/1.6.4

fix eventbus deadlocks by @Snawoot in https://github.com/mysteriumnetwork/node/pull/5018

p.s. let us know if that helps, thanks!

**Comment by DiogoMarques2003** [comment]
I'm already using that version and so far I haven't had the problem again.
