### ISSUE TITLE
[windows 7] can't reconnect without rebooting windows. Multiple network connections.

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4990]
**Describe the bug**
After connecting, the connection drops after 20-30 minutes.

When it goes down, it will not re-connect without re-booting Windows.
Every time it connects, it sets up a new network connection. It's up to myst20 or so by now.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8456496/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.4.2
 - OS: Windows 7

**Comment by Donatas-MN** [comment]
That's old node version, please update to the newest one.
