### ISSUE TITLE
[android] "No address associated with hostname" after connecting

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#4991]
**Describe the bug**
Something is broken with dns.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8456537/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.0
 - OS: Android

**Comment by Donatas-MN** [comment]
That's very old node version, please update to the newest one.
