### ISSUE TITLE
Earnings do not match with price of data transferred 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4994]
Description:

Hello
Please see details of Session ID be184da7 below :

Netherlands
18:47:12
01/04/2022, 05:08:14
0.3863219 MYST
159.61 GB

As you can see, 159.61GB were transferred over almost 19h of time.

How come this session only granted me 0.3863219 MYST, when the rates are :

Price per hour
0.0006240 MYST
Price per GB
0.1046027 MYST

This obviously doesn't match.
Multiplying the GB rate with the 160GB brings me up to 16+ Myst (and this is not counting Hourly rate)

Could you please check?
Thank you very much :)

Here's my Node ID :
0xddd3794cd861524490955e9c7d27102f8631385f

Logs:

https://mystnodes.com/support/logs/2022-04-08-b7aed6ca-3f86-4cd4-a85e-8f9862f4b547-mysterium-node.zip3630844321

**Comment by prshaka** [comment]
Same as this? https://github.com/mysteriumnetwork/node/issues/4929
