### ISSUE TITLE
Notification to outdated nodes

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#4997]
We still have a significant amount of providers sitting at below 1.4.x node. With on-time update of our network nodes (sending notify's to an outdated nodes) we expect them to face less problem related to previously fixed bugs (e.g. no rewards issue). 

Node version distribution: https://mainnet-grafana.mysterium.network/d/HaqMZOpMz/support-dashboard?orgId=1&viewPanel=19

**Comment by etherunit** [comment]
related #5016 #5027 #5028

**Comment by Donatas-MN** [comment]
Email sent.
