### ISSUE TITLE
Node offline in node dashboard

### ISSUE THREAD

**Issue by virusbear** [mysteriumnetwork/node#4998]
**Describe the bug**
I am experiencing similar issues on my node as described by @soffokl in issue #4049.
My node shows up as offline in the node dashboard but was online in the NodeUI for the first 12-18h of operation.
After that 12 - 18 h the NodeUI now shows "Test Failed" status.
The only traffic received by the Node seems to be the connection tests scheduled every 6h, causing sessions of 0 seconds and 0 bytes of data.

**Expected behavior**
Node shows online in both the Node dashboard as well as the NodeUI and gets traffic routed.

**Screenshots**
![image](https://user-images.githubusercontent.com/23473248/162799577-2800dba1-20cb-423a-a5c0-6ce2ad9fa0f5.png)

![image](https://user-images.githubusercontent.com/23473248/162799655-c6718663-921d-425e-8504-3c30a12a88bc.png)

**Environment (please complete the following information):**
 - Node version:  mainnet (1.6.3-3432c686)
 - OS: Ubuntu 20.04.4 LTS
 - Docker (if applicable): version: 20.10.14; tag: latest
 - Your identity (if applicable): 0x65e31d79ca1efc641d0bf11405da619f2c030390

**Additional context**
The server is hosted in Germany with public IP and gigabit networking.
The server was restarted multiple times as well as the service/docker container running mysterium-node.
The first installation was bare metal, switched to docker to avoid any mismatching configurations
Checking the [proposals endpoint](https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&provider_id=0x65e31d79ca1efc641d0bf11405da619f2c030390) completes successfully and shows my node (only if I don't use whitelisted traffic though)

Docker run command:
`docker run --cap-add NET_ADMIN -d --restart always --net host --name myst -v /var/lib/mysterium-node:/var/lib/mysterium-node mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`

journalctl output:
[node.log](https://github.com/mysteriumnetwork/node/files/8466639/node.log)
docker logs:
[logs.txt](https://github.com/mysteriumnetwork/node/files/8466643/logs.txt)

## Update
I logged in from another network which is not my home network.
Being able to open the NodeUI it now shows "All services offline":
![image](https://user-images.githubusercontent.com/23473248/162920115-2be4c98e-b383-464c-b441-c710cdda994a.png)

While loading the NodeUI it seems like the tequilapi does not authorize any connections
![image](https://user-images.githubusercontent.com/23473248/162920373-fac751da-9d39-4efe-8f53-aa614a87493b.png)

**Comment by etherunit** [comment]
Note that your shared proposals endpoint has `include_monitoring_failed=true` meaning that it will show anyway. If you remove this part, node will disappear with null --> https://discovery.mysterium.network/api/v3/proposals?provider_id=0x65e31d79ca1efc641d0bf11405da619f2c030390

Connections from MA with xx.xx KB of data may indicate that node establish a tunnel but fails to transmit further packets with peer. It's a common issue with firewall (iptables) blocking it. 

```
2022-04-13T09:25:24.057 WRN ../../../../source/requests/dialer_swarm.go:293      > Failed to lookup host: "quality.mysterium.network" error="lookup quality.mysterium.network: no such host"
2022-04-13T09:25:34.058 ERR ../../../../source/core/quality/mysterium_morqa.go:190 > Failed to sent batch metrics request, 21 error="Post \"https://quality.mysterium.network/api/v3/batch\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
2022-04-13T09:25:57.049 WRN ../../../../source/requests/dialer_swarm.go:293      > Failed to lookup host: "broker.mysterium.network" error="lookup broker.mysterium.network: no such host"
```

**Comment by virusbear** [comment]
I just recreated my docker container with the `---dns 8.8.8.8` option to hopefully prevent any lookup errors. my docker logs
([logs2.txt](https://github.com/mysteriumnetwork/node/files/8479285/logs2.txt)) don't show any Failed to lookup host errors anymore.

Unfortunately I am not familiar with iptables. 
Running `sudo iptables -t nat -nvL` shows this output:
```
Chain PREROUTING (policy ACCEPT 165 packets, 7999 bytes)
 pkts bytes target     prot opt in     out     source               destination         
57947 2906K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 165 packets, 7999 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 385 packets, 25885 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 385 packets, 25885 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           

Chain MYST (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       all  --  *      *       0.0.0.0/0            10.0.0.0/8           to:240.0.0.1
    0     0 DNAT       all  --  *      *       0.0.0.0/0            172.16.0.0/12        to:240.0.0.1
    0     0 DNAT       all  --  *      *       0.0.0.0/0            192.168.0.0/16       to:240.0.0.1
    0     0 DNAT       all  --  *      *       0.0.0.0/0            127.0.0.0/8          to:240.0.0.1
```
 
Am I correct that this is the standard created by docker (before the docker installation no entries were shown)?
I already disabled ufw on the node so no traffic is blocked by it.

Is there a possibility I can somehow get this node to work?

**Comment by etherunit** [comment]
Please try to update your node to 1.6.4. It could potentially hold a solution: _fix eventbus deadlocks by @Snawoot in_ https://github.com/mysteriumnetwork/node/pull/5018

**Comment by virusbear** [comment]
I upgraded everything about 2 days ago and it did not seem to fix anything. 
After fiddling around a little bit I got the node back up online again but the Nodes dashboard is still showing offline:
![image](https://user-images.githubusercontent.com/23473248/164448053-5508604b-5c4c-409e-acf6-e27d48743c18.png)
