### ISSUE TITLE
Create PR template to automatically add work-in-progress label on new PRs

### ISSUE THREAD

**Issue by tadovas** [mysteriumnetwork/node#500]
As PR reviewer I would like all new PR's to have work-in-progress label automatically added. Pr creator can remove this flag when PR is finished and ready to review, to reduce PR list for reviewers which are not ready yet.

**Comment by soffokl** [comment]
Sounds like a simple service, that listens webhook, and do an API call to set label. 
Like this one: https://github.com/sfbrigade/github-auto-label

**Comment by soffokl** [comment]
But, there is a problem, that outside collaborator will not be able to change the label.

**Comment by tcharding** [comment]
Can you fellas please explain your process here.  What is the use of a raising a PR that is _not_ ready for review?  (We have `bin/check`, `bin/test`, `bin/test_e2e` right so it can't be to use the CI.)
