### ISSUE TITLE
node

### ISSUE THREAD

**Issue by joelvergis** [mysteriumnetwork/node#5003]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by joelvergis** [comment]
Unable to claim myst tokens collected after hardware crash. I can view it on myst, but unable towithdraw the tokens.

**Comment by etherunit** [comment]
I suspect you are unable to login to your NodeUI? Have you made an identity backup before it crashed?

**Comment by joelvergis** [comment]
unfortunately, no. I did not know how to make a backup before. Its hidden
deep in your documentation.

I have the Node ID, Node API and Withdrawal Address tho.

**Comment by etherunit** [comment]
Unfortunately, there is not much really we can do without the backup. We have a task to allow to backup and restore keystore while setting up a node - > https://github.com/mysteriumnetwork/node/issues/4782

**Comment by joelvergis** [comment]
How do I initiate this online backup?
