### ISSUE TITLE
transfer to Ethereum network not credited

### ISSUE THREAD

**Issue by avmorales25** [mysteriumnetwork/node#5005]
Withdrawal of MYST not credited to ethereum account

When doing auto settlement of MYST to ethereum wallet, there is a transaction history but MYST was not posted. 
I was expecting to see the transaction of MYST to ETH posted in my ETH account after 3 days. It's been more than 5 days and it is not showing. There is a record of the transaction in the MYST wallet, the ETH was verified and correct. 

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.11.0
 - OS: raspbian debian bullseye
 - Your identity (if applicable): 0x380ed9f6b9ddc1b6841897431920c1136d6ca8e0
 - Payment (top-op) reference (if applicable): 0xCa114CF03F1BcC569272a3D1343b6490119556C4

**Additional context**
<img width="1587" alt="Screen Shot 2022-04-12 at 13 19 31" src="https://user-images.githubusercontent.com/98541121/163028519-e9d08211-e121-4a55-ab0d-d127280c7553.png">

**Comment by etherunit** [comment]
I suspect this was a settlement to an external wallet at Polygon network (Ethereum has much higher fees). 
If yes, then the question have you properly configured Polygon at your wallet and added MYST as a custom token using the correct contract address?

**Comment by etherunit** [comment]
More details: https://docs.mysterium.network/for-node-runners/how-to-setup-polygon-myst-on-metamask
