### ISSUE TITLE
Failed to connect: Failed to lookup proposal: no providers available for the filter

### ISSUE THREAD

**Issue by kiraitachi** [mysteriumnetwork/node#5006]
**Describe the bug**
When trying to connect with Mysterium VPN Desktop on Kali Linux to my own cloud hosted node in Oracle I get the following message:

`Failed to connect: Failed to lookup proposal: no providers available for the filter`

This does not happen with other nodes I host or with other people's nodes. So, I believe it might be an issue on my node.

**To Reproduce**

1. Search for my identity from within "Manual connect" 0x3cadd2e36a30fcf11ff49b61f4dd4af1aef62f3c
2. Try to connect
3. `Failed to connect: Failed to lookup proposal: no providers available for the filter`

**Expected behavior**
Connection successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/40744673/163039732-7a576c3f-cdb7-4fca-bc84-9dc689f64214.png)

**Environment (please complete the following information):**
 - Node version: mainnet (1.6.3-3432c686)
 -NodeUI version: 1.11.0
 - OS: Kali Linux
 - Desktop app version: 10.8.3
 - Your identity Node: 0x3cadd2e36a30fcf11ff49b61f4dd4af1aef62f3c

**Comment by etherunit** [comment]
That is correct, there is an issue with your node. Please add your node logs so we can start looking into it.

**Comment by kiraitachi** [comment]
I uploaded the logs to my IPFS server, let me know If I can help somehow. Probable related to something in Oracle security or ports I presume since its cloud hosted.

https://ipfs.io/ipfs/QmeqjzU7M17MPbNX3eGccWTUNnAQjLUgRUhn2m2wd1F7a1?filename=Mysterium.log

**Comment by etherunit** [comment]
```
WARNING] Server responded with an error: 503 (http://127.0.0.1:4050/connection/ip) [unavailable] Service Unavailable
[WARNING] Server responded with an error: 503 (http://127.0.0.1:4050/connection/location) [unavailable] Service Unavailable
[INFO] Proposal:Provider: 0x3cadd2e36a30fcf11ff49b61f4dd4af1aef62f3c, ServiceType: wireguard, Country: NL
```

I've tested connectivity to your node.  It's connectable but unable to reach services once it's established. I suspect problem rely on firewall setting. It could be that DNS is improperly configured and is set to systemd's 127.0.0.53.
Check this: https://askubuntu.com/questions/1012641/dns-set-to-systemds-127-0-0-53-how-to-change-permanently
