### ISSUE TITLE
Failing CI should mark PR with specific label

### ISSUE THREAD

**Issue by tadovas** [mysteriumnetwork/node#501]
As a PR reviewer I don't want to review PRs on which CI jobs failed. CI could add specific labels indicating that PR is ok or failed  (i.e. CI failed, CI ok). These labels can be later uses for pull remainders to filter out only good ones

**Comment by soffokl** [comment]
PR already will be marked by CI as failing or not with following icons: 
![image](https://user-images.githubusercontent.com/8612618/47482991-e9bd8200-d859-11e8-9a95-6b9c5906b3a5.png)
![image](https://user-images.githubusercontent.com/8612618/47483024-fcd05200-d859-11e8-928f-712eb87fc01a.png)

Isn't it enough?

**Comment by tadovas** [comment]
Not sure if pull remainder tool can filter by this
