### ISSUE TITLE
50$ of Mysterium worth disappeared

### ISSUE THREAD

**Issue by Beppe1509** [mysteriumnetwork/node#5010]
**Describe the bug**
I was using mysterium and suddently 165 something mysterium disappeared, I checked the mysterium channel address and with a bit of tracing back, the address "0x74D42650a7aaD0416378F69982b768834f84067F" got my mysterium.

**To Reproduce**
1. Use mysterium

**Expected behavior**
My 50$ doesn't randomly disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/61753332/163169616-a358026e-eebe-433f-9e5d-83fa10e38af0.png)
![image](https://user-images.githubusercontent.com/61753332/163169635-91cd8c0c-8fe5-47da-aa4b-ceb3fa592872.png)

**Environment (please complete the following information):**
 - Node version: 1.6.0
 - OS: Windows 10
 - Desktop app version: 10.9.0
 - Your identity: 0xec53dabcec5188506801a328fc441b5887dc9d03
 - Channel ID: 0x63A9b50724494c7298abC8bea64Df9876f53b5C5

**Comment by Guillembonet** [comment]
There is a provider with this identity but the user says it's not him so not sure about what is going on here. The user also says he has never had any node.

**Comment by tomasmik** [comment]
It's not possible for MYST to "disappear". Node has no such functionality to automatically send MYST somewhere.

**Comment by sarthakgangwar** [comment]
Provide some more info like where did it disappear from ? Node or App ... Nodes can not send money out themselves so it must have been sent to your entered wallet ... As for app wallet I think you got hacked

**Comment by etherunit** [comment]
Closed due to inactivity. Feel free to reopen it in case you have any additional information to us.
