### ISSUE TITLE
Excessive number of DNS requests?

### ISSUE THREAD

**Issue by MarkWieczorek** [mysteriumnetwork/node#5015]
**Describe the bug**
My node currently has a single connection from the netherlands that is transferring about 10 MB/s. This is great. However, I use a Pi-hole with unbound on my network (for a recursive DNS resolver with filtering), and I noticed that the number of DNS requests coming from the mysterium node is very high: more than about 100 requests per minute. Almost all of these requests are going to hermes.mysterium.network (about a quarter are going to location.mysterium.network and quality.mysterium.network).

The reason that this is a problem is that the default maximum number of DNS requests for Pi-hole is 1,000 per minute. Conceivably, if I were to have 10 ongoing connections, I would exceed this value. When that happens, Pi-hole stops resolving DNS requests, and the mysterium connections would fail. So, I ask this question: should the mysterium node attempt to economize the number of dns lookups? Such as by internally caching hermes.mysterium.network?

**Environment (please complete the following information):**
 - Node version: 1.6.3
 - OS: Raspbian GNU/Linux 10 (buster)

**Comment by adinetech** [comment]
Mention https://github.com/mysteriumnetwork/node/issues/4780

**Comment by etherunit** [comment]
Note that hermes DNS record has TTL 30 seconds for failover reasons which is quite common for frontends of high availability clusters.

**Comment by MarkWieczorek** [comment]
@etherunit I have a single connection on my node and it is making 100+ DNS requests per minute. Could you confirm that this is a feature, and not a bug?

Node version: mainnet (1.8.1-b39ec047)
