### ISSUE TITLE
Last seen inaccuracy

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5017]
"last seen" status is being inaccurate/misleading on [mystnodes.com](http://mystnodes.com/) for a node that is listed on discovery and got plenty of sessions during last 24hrs.
id: [0x31d0e9ff7d0fb39a8679e3a474e8caf78a7253dd](https://mainnet-grafana.mysterium.network/d/n3xeQlgMz/provider?orgId=1&var-provider=0x31d0e9ff7d0fb39a8679e3a474e8caf78a7253dd&var-service_type=All&from=now-24h&to=now)
![Screenshot 2022-04-14 at 08 20 16](https://user-images.githubusercontent.com/60128746/163320320-a1742327-12a0-4d33-8a1c-529ea689ebb1.png)
![Screenshot 2022-04-14 at 08 34 29](https://user-images.githubusercontent.com/60128746/163320328-395a76e4-324e-4698-a714-5c3215a2012c.png)

**Comment by syahpian** [comment]
i have 3 node getting this issue 

0x53244a679231a899dfdf55901514ae63ddbcf5a6 - last seen not updated
0x399aad6b5c3f0e9c4147fc80fb222e63a55a7411 - last seen not updated
0x3058744bc80f227bcb466dc27109264052caee04 - last seen and node version not updated

![image](https://user-images.githubusercontent.com/12189144/163344534-d3bf1743-0864-462a-9a28-05c7de617602.png)

**Comment by cyanide-aoe2** [comment]
3/5 nodes of mine have the same issue.

ids:
1) 0x8780ae79f8eb69249c1554a9c658107ec9f32d55 (AT)
2) 0xd44ad33595560c1584a6e17eec063f23aaedc207 (IN)
3) 0x503e08b28c3da44a6f6a1a08a457571df651e4df (US)

All running 1.6.3.

**Comment by etherunit** [comment]
Yet another example:. sample identity: 0x8780ae79f8eb69249c1554a9c658107ec9f32d55
Almost same creation dates, all online, but last seen differs. 
![Uploading Screenshot 2022-04-14 at 20.07.54.png…]()
