### ISSUE TITLE
Installation guide is not available on dockerhub

### ISSUE THREAD

**Issue by alexIslander** [mysteriumnetwork/node#5020]
**Describe the bug**
I attempted to install the docker container and wanted to follow the [guide](http://docs.mysterium.network/en/latest/user-guide/installation/), but it is not available on [dockerhub](https://hub.docker.com/r/mysteriumnetwork/myst/).

**To Reproduce**
1. Go to dockerhub
2. Click on installation guide

**Expected behavior**
The guide is available

**Comment by etherunit** [comment]
We will make sure to update it. For now, please use: https://docs.mysterium.network/for-node-runners/docker-guide
