### ISSUE TITLE
[android] VPN disconnect frequently

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#5022]
**Describe the bug**
VPN disconnect frequently
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8501226/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.1.0
 - OS: Android

**Comment by Donatas-MN** [comment]
That's very old node version, please update to the newest one.
