### ISSUE TITLE
Several long lasting sessions with 0 Bytes transferred

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5024]
0xe9d4aef05a79e093fc818764cc6f24848ebbe78f .
There are several connections, all coming from Germany, which consuming server time for hours or even days, with 0 Bytes transferred and 0 MYST earnings. Below I cite some examples:
Date: 29-Mar-2022 Duration: 18d 23:44 Session ID: 6301c788
Date: 13-Apr-2022 Duration: 3d 14:01 Session ID: ed654a28
Date: 16-Apr-2022 Duration: 21:12:27 Session ID: 25e75219 .
There are also many more connections from the same country lasting for many hours with so many few Bytes been transferred that makes me wonder how connection remains active

Logs:

https://mystnodes.com/support/logs/2022-04-17-f97e2960-1a23-4991-a2ed-49195dc0505d-mysterium-node.zip1799895722

**Comment by etherunit** [comment]
From the first glance at logs, peers maintains the connection clearly by periodically sending keepalive packets. Session management and price calculation looks fine too. We know that provided is coded one the way it interrupts session if not getting tokens, therefore I think there is "a visual glitch" on UI side (UI  probably getting this data from the node, which failed to collect that tokens info).

**Comment by etherunit** [comment]
@Ayse-AK I think it's something worth looking at since we have it for a long time already.

**Comment by etherunit** [comment]
Closed due to inactivity. Feel free to reopen it in case you'll get any additional information.
