### ISSUE TITLE
0 bytes transferred. Cannot connect 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5025]
Description:

I've been running this dockerized mysterium node from within a CentOS VPN for a few months now, but even though there've been 262 sessions with 57 unique clients all from the Netherlands, there has been 0 bytes actually transferred and thus 0 Myst earned. Can you guys see what's wrong?

Logs:

https://mystnodes.com/support/logs/2022-04-08-6344e101-185b-46e2-add6-9ad07f8f342b-mysterium-node.zip1275703225

**Comment by mauroferra** [comment]
I have the same issue, my logs are here: https://mystnodes.com/support/logs/2022-05-11-d82bd9f5-0894-40d2-97db-c6c51b5870e6-mysterium-node.zip103379952

I was in touch with a support agent via email about this problem, but commenting here for the record.
