### ISSUE TITLE
Node freezes when a session is running for a long time

### ISSUE THREAD

**Issue by alamdar9** [mysteriumnetwork/node#5029]
Node freezes when a session is running for a long time then i receive this error "Identity not found" I've to stop and start mysterium again to get it fixed

Node version: mainnet (1.6.4-12146bf0)
NodeUI version: 1.11.0

0x60c676023a08d616b62fd3dbb6847101362aa041

![5435435353sdgsdfg](https://user-images.githubusercontent.com/9874411/163923533-c8fefe4e-a689-49c6-bace-8f34e94b45fd.jpg)

**Comment by etherunit** [comment]
@alamdar9 I almost know where is the problem, node logs could confirm my presumption

**Comment by alamdar9** [comment]
Okay, I sent in a bug report from those instructions from my Node UI. Do you also want me to post my node logs here?

**Comment by etherunit** [comment]
No need, thanks for submitting your node logs. We will review it and come back with a reply here.

**Comment by etherunit** [comment]
When did you send the report? Is it possible to get a report id? I'm not able to find it by your node id.

**Comment by alamdar9** [comment]
How do i get the report id? When I reported the issue, it just closed the screen, pop up and opened a live chat. I've just made another bug report right now. 12:06 is the time or under 12:10

**Comment by etherunit** [comment]
Please confirm its your node id > 0x60c676023a08d616b62fd3dbb6847101362aa041?

**Comment by alamdar9** [comment]
Any updates? I'm still getting this error on the latest update 1.6.5

**Comment by etherunit** [comment]
Thanks for confirming. I'll keep looking into it_

**Comment by etherunit** [comment]
@alamdar9 Please try to update your node as we did some major improvements.
