### ISSUE TITLE
One of my Nodes is online, but reporting as "last seen" 11 days ago on mystnodes.com

### ISSUE THREAD

**Issue by speedf1** [mysteriumnetwork/node#5033]
As per the title.  This is node 0x2163fd60996553c867f6434d6aab37383aff6c54 which seems to be online, and receiving traffic.  However Mystnodes.com dashboard doesn't seem to "see it".  I've tried rebooting the node with no affect.

**Comment by etherunit** [comment]
I can see that your node is online and visible on discovery: https://discovery.mysterium.network/api/v3/proposals?provider_id=0x2163fd60996553c867f6434d6aab37383aff6c54
The status "last seen" is not 100% accurate, therefore please rely on mystnodes.com status (online or offline) and on status in NodeUI. Eventually, "last seen" will be either improved or removed completely.
