### ISSUE TITLE
"myst cli" is showing NotConnected

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5037]
Hello team --

Recently I've upgraded my docker node to the latest version 1.6.4.
Node version: mainnet (1.6.4-12146bf0) NodeUI version 1.11.0
For some reason when I check the status of my node from "myst cli" is showing NotConnected

» identities list
[+] 0xe1833ef5640ee6cf3b50d5292f75e97f66e714e5
» status
[INFO] Status:NotConnected
[INFO] SID:
[INFO] IP:188.25.252.69
[INFO] Location: Bucuresti, RO (residential - Digi Romania)

But when I access the UI : https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&provider_id=0xe1833ef5640ee6cf3b50d5292f75e97f66e714e5

is showing ok

{
"id": 0,
"format": "service-proposal/v3",
"compatibility": 2,
"provider_id": "0xe1833ef5640ee6cf3b50d5292f75e97f66e714e5",
"service_type": "wireguard",
"location": {
"continent": "EU",
"country": "RO",
"city": "Bucuresti",
"asn": 8708,
"isp": "Digi Romania",
"ip_type": "residential"
}

Logs:

https://mystnodes.com/support/logs/2022-04-19-1da5476a-b73b-42b1-9f40-6a751f1b590e-mysterium-node.zip3294014012

**Comment by etherunit** [comment]
@isaackielma mystcli shows status of consumer (not provider) at that point.
