### ISSUE TITLE
fail to connect

### ISSUE THREAD

**Issue by vsrn666** [mysteriumnetwork/node#5039]
**Describe the bug**
When i click

**To Reproduce**
1. Go to 'quick connect'
2. Click on 'quick connect'
3. Scroll down to 'spain'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/94306344/164108513-d8976986-7d77-4b5a-962f-4540325e50bb.png)
![image](https://user-images.githubusercontent.com/94306344/164108945-1d1f3b67-79ea-48c3-9aff-87f61bf98864.png)

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: Windows 10
 - Desktop app version (if applicable): [10.9.0 
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
@vsrn666 It's happening for all providers you are trying to connect to or just 1? Is it possible to provide app/supervisos/node logs as mentioned in this page: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Comment by vsrn666** [comment]
> @vsrn666 It's happening for all providers you are trying to connect to or just 1? Is it possible to provide app/supervisos/node logs as mentioned in this page: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

in every node 
NODE
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8519454/mysterium-node.log)
.
APP-
[main.log](https://github.com/mysteriumnetwork/node/files/8519457/main.log)
[renderer.log](https://github.com/mysteriumnetwork/node/files/8519458/renderer.log)

SUPERVISOR-
[myst_supervisor.log](https://github.com/mysteriumnetwork/node/files/8519467/myst_supervisor.log)
