### ISSUE TITLE
Node offline since 1.6.4 update

### ISSUE THREAD

**Issue by Friguletz** [mysteriumnetwork/node#5042]
Tuesday morning I've updated the Node from 1.6.3 to 1.6.4.
From what i ''see'' its in an endless loop of trying to connect to Myst network.
Since then it doesn't stay online

Environment:
 - Node version: 1.6.4
 - OS: Windows 10
 - Desktop app version (if applicable): 1.0.27
 - Docker Desktop 4.6.1 (76265)
 - Identity: 0x4011c66a07c6526ca3839b1aaf4e2ef4325f6b22

I've attached a log from the node
[New Text Document.txt](https://github.com/mysteriumnetwork/node/files/8519477/New.Text.Document.txt)

**Comment by etherunit** [comment]
It stopped publishing proposal ±2-3 days ago. 
![Screenshot 2022-04-20 at 20 57 14](https://user-images.githubusercontent.com/60128746/164293369-02c41d10-3e5e-49cb-b2b7-c136284e4766.png)
its hard to say why it failed that particular day from the 1st glance at logs because it start only at
`2022-04-19T19:39:01.281 INF`

**Comment by etherunit** [comment]
from current logs its clear that your node is failing to reach the blockchain, broker and other services. 

e.g. `failed to lookup host: "broker.mysterium.network" error="lookup broker.mysterium.network on 192.168.65.5:53: dial udp 192.168.65.5:53: operation was canceled"`

**Comment by Friguletz** [comment]
updated to 1.6.5 rebooted laptop + network + changed networks (have 2 different ISPs here) same issues doesn't connect... :(

Is there any possibility to migrate the node from this laptop to another ?

**Comment by etherunit** [comment]
How did you update it? It still shows offline on mystnodes.com
I need to understand whether its something badly executed on your side or its an issue on our side.

**Comment by Friguletz** [comment]
its stays on like 10-15sec - while trying to connect to the MYST network
in that time, the Myst Node Launcher manages to install the update
![image](https://user-images.githubusercontent.com/97876704/164650152-afff15ad-122c-4493-88df-d146c5f1e1e7.png)
![image](https://user-images.githubusercontent.com/97876704/164650298-89776600-5afb-4aed-b066-25af697a7405.png)

**Comment by adinetech** [comment]
It seems like the node automatically crashes within 10-15 seconds because unable to reach the Mysterium services, Sadly I don't have any idea to resolve this error.

**Comment by Donatas-MN** [comment]
@Friguletz can you try the newest version?

**Comment by Zensey** [comment]
it looks like a name resolution issue 

@Friguletz 
if the problem still persists could you try query a server address in a terminal:  
`nslookup polygon1.mysterium.network`

**Comment by Ayse-AK** [comment]
Hi @Friguletz Can you try the latest version?
