### ISSUE TITLE
node status is offline 

### ISSUE THREAD

**Issue by abubacker123** [mysteriumnetwork/node#5044]
My node status is always offline in the dashboard even after restarting the node several times but in the node UI it shows online and there there is no traffic. I have attached the screen shot have a look at it.
![Screenshot (23)](https://user-images.githubusercontent.com/53364822/164205024-b3a889f7-4f63-43b9-a880-817c2e5cec24.png)

![Screenshot (24)](https://user-images.githubusercontent.com/53364822/164204725-4ed46569-b5b1-4f72-b09f-51e4fea726b2.png)

**Comment by etherunit** [comment]
Please copy paste your node identities here. Thanks!

**Comment by abubacker123** [comment]
I have mentioned my node id below
0x6f8c097ce7d071d0c400a20803ea14de7fa62191

**Comment by etherunit** [comment]
Your node is offline now, can you please switch it on and check it mystnodes.com still report it as offline?

**Comment by abubacker123** [comment]
I also restarted the node it's still offline ...

**Comment by adinetech** [comment]
> 

It shows as online now, https://discovery.mysterium.network/api/v3/proposals?provider_id=0x6f8c097ce7d071d0c400a20803ea14de7fa62191

**Comment by adinetech** [comment]
@etherunit you may close this issue.

**Comment by abubacker123** [comment]
Thank you soo much
