### ISSUE TITLE
Node UI - UI Popup text box updates

### ISSUE THREAD

**Issue by Ayse-AK** [mysteriumnetwork/node#5045]
**1)** 
Update the popup text as below
This fee includes a 20% network fee plus blockchain transaction fees for settlement transactions.

![Screenshot (2)](https://user-images.githubusercontent.com/102946394/164207271-5441fafa-061c-4375-89d6-0a312cc20006.png)

**3)**
Replace **Beneficiary** with **External Wallet Address**

**4)** 
Remove the items related to **type** 

![cancel](https://user-images.githubusercontent.com/102946394/164231320-5645effc-850a-4751-a1bf-906c95d370c7.png)

**5)**
Replace **Total Withdrawn** with **Total Settled** 

![test](https://user-images.githubusercontent.com/102946394/164440792-9338091f-56f9-45d1-b3e7-987cbe2da3c2.png)

Not: Keep CSV

**Comment by lusine-h** [comment]
checked, looks good
