### ISSUE TITLE
Node is online, Node UI shows offline

### ISSUE THREAD

**Issue by gigatexel** [mysteriumnetwork/node#5049]
**Describe the bug**
I installed a new node based on this Docker Image: https://hub.docker.com/r/mysteriumnetwork/myst/
All works fine, with connections happening as expected.

However, after a few hours the local NodeUI starts reporting as being Offline. Also, all history is gone.
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/65073191/164419107-e1296aec-b940-4b6d-aa5c-cc3c8079018d.png">

Nothing strage in the logs, the node still seems to be running.
Also, mystnodes.com still reports it as being online.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/65073191/164419405-69e745bb-a587-461b-91e6-7f21e27f8f12.png">

Restarting the Docker container fixes it for a few hours.

Comparable to https://github.com/mysteriumnetwork/node/issues/4698 but no errors in the logs.

**To Reproduce**
1. Installed the Docker container on Debian 12 on a RPI4
2. Command used:
`docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`

**Environment (please complete the following information):**
 - Node version: mainnet (1.6.5-4c6440ea)
 - OS: Debian 12
 - Docker: https://hub.docker.com/r/mysteriumnetwork/myst/

**Comment by etherunit** [comment]
Thanks for the details! I'll try to reproduce this issue and get back to you.

**Comment by etherunit** [comment]
by the way, whats your node identity?

**Comment by gigatexel** [comment]
0x697c675823ccc3330f71286fea0f5022a9572673

**Comment by gigatexel** [comment]
Just tested my hypothesis abote but seems to be wrong :-)

**Comment by adinetech** [comment]
The node is actually online.
`[{"id":0,"format":"service-proposal/v3","compatibility":2,"provider_id":"0x697c675823ccc3330f71286fea0f5022a9572673","service_type":"wireguard","location":{"continent":"EU","country":"BE","city":"Flanders","asn":5432,"isp":"Proximus","ip_type":"residential"},"contacts":[{"type":"nats/p2p/v1","definition":{"broker_addresses":["nats://broker.mysterium.network:4222","nats://broker.mysterium.network:4222","nats://51.15.116.186:4222","nats://51.15.72.87:4222"]}}],"quality":{"quality":1.4,"latency":0,"bandwidth":5.351171}}]`

**Comment by adinetech** [comment]
It can be a user interface glitch, restart the node & update your node (if not done already)

**Comment by gigatexel** [comment]
Yes it is. But IU reports it as offline.

**Comment by adinetech** [comment]
Exactly, UI issue. Another user reported the same.

![image](https://user-images.githubusercontent.com/68943180/165094946-340f6e01-f58e-4870-a21e-eec5088d9904.png)
![image](https://user-images.githubusercontent.com/68943180/165094955-f256008c-c2bd-4cb3-acdb-d224d69df5d4.png)

**Comment by prshaka** [comment]
@etherunit I had the same issue with 1.6.4 and noticed it happened when I let the UI open in a browser then sent my computer to sleep or switched apps on my phone and then get back to the UI. Doing that and checking several times a day, the node would show offline at least once a day.
So I tried to systematically close the UI after use and now it has been several days it works perfectly fine.
@gigatexel do you use the UI as I describe? Then maybe you can try my quick fix!

**Comment by etherunit** [comment]
@prshaka Could you also add your node logs here? That would be helpful.

**Comment by Snawoot** [comment]
Please try release 1.6.7 - it should contain relevant fixes.
