### ISSUE TITLE
Unable to install the node

### ISSUE THREAD

**Issue by chiragnahata** [mysteriumnetwork/node#5051]
I am unable to install Mysterium Node. Whenever I am installing it with .exe file it is showing a alter version of wsl is already installed. Setup is exiting.

**Comment by RWolfyo** [comment]
Same issue here 
![image](https://user-images.githubusercontent.com/46199699/164616015-ec00d5f6-78a5-4201-98bd-e1e59cf60d26.png)

**Comment by chiragnahata** [comment]
![image](https://user-images.githubusercontent.com/63905783/164718548-c699ab13-97b6-41e8-9cb9-640b20b22d98.png)
This is the error showing now

**Comment by RWolfyo** [comment]
Everything seems to work on my side, installed without any issues and node seems to function.

**Comment by Zensey** [comment]
@RWolfyo @chiragnahata 
also another issue has been fixed:
https://github.com/mysteriumnetwork/myst-launcher/releases/download/1.0.28-dbg2/myst-launcher-amd64.exe

@chiragnahata 
could you try to reinstall Docker manually from its site
https://www.docker.com/products/docker-desktop/
