### ISSUE TITLE
Node ID Zero'd Out

### ISSUE THREAD

**Issue by johnhighway** [mysteriumnetwork/node#5052]
**Describe the bug**
My node lost its ID information and all previous data is now gone.

**To Reproduce**
1. Go to 'Settings'
2. See Identity '0x'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33267537/164732418-8dac3acd-52ae-4f82-b9af-599a784635b1.png)

![image](https://user-images.githubusercontent.com/33267537/164732654-5d9ee9f6-cb8c-425c-a007-52873a046442.png)

**Environment (please complete the following information):**
 - Node version: 1.6.5
 - OS: Ubuntu 20.04.4 LTS
 - Your identity: 0x06e695d811bd08e37a216c43826ab8e512053845

**Comment by etherunit** [comment]
Please submit a bug report. It could help us to understand what happened.

**Comment by johnhighway** [comment]
Tried submitting a bug report and got this error instead.
![C453381F-C534-49C8-988D-B4FAE27F36EE](https://user-images.githubusercontent.com/33267537/164912101-5c446701-f874-48eb-89b0-a3b37f572340.png)

**Comment by johnhighway** [comment]
I tried submitting a bug report
![5FF6E481-4272-4686-BFB5-C305C7CE5784](https://user-images.githubusercontent.com/33267537/164912310-2e2deeda-565b-4da2-9bab-963c54683a1b.jpeg)

**Comment by adinetech** [comment]
Check service status.

Linux/Raspberry Pi: `sudo systemctl status mysterium-node.service`
Save the log and upload it here: `sudo journalctl -u mysterium-node.service > [your_file_name].log`

**Comment by johnhighway** [comment]
Here's the log file... I can't upload it 
https://www.dropbox.com/s/rqjjzgjyh66vuyi/myst-jp-01-mystservice.log?dl=0

**Comment by gigatexel** [comment]
Seems identical to https://github.com/mysteriumnetwork/node/issues/5049

**Comment by adinetech** [comment]
Yeah, it is the same issue.

**Comment by mdomasevicius** [comment]
This happens when for some reason `/event` endpoint get's stuck.

**Comment by Snawoot** [comment]
Please try release 1.6.7 - it should contain relevant fixes.
