### ISSUE TITLE
provide configuration options for automatic settlement

### ISSUE THREAD

**Issue by overland-liquor** [mysteriumnetwork/node#5054]
**Is your feature request related to a problem? Please describe.**

the new automatic settlement feature does not allow node operators any control over their payout.  this is a regression from the previous manual setup from a network fee optimization perspective.  mining pools, for example, offer the options below to pool contributors

**Describe the solution you'd like**

it would be very nice to have configuration options for automatic settlement to include:
- balance threshold - id like to set mine to 99 to minimize fee expenditure
- gas price limit - again, for fee minimization
- an on/off switch (could effectively be worked around with the gas price limit above)

**Comment by tomasmik** [comment]
> balance threshold - id like to set mine to 99 to minimize fee expenditure

This is rather difficult to implement without staking being required in the network. The fees are also super small on polygon network. Currently it costs you `0.01957254520144 MYST` to settle any amount of earned tokens, which at let's say 3 MYST earned is pretty much nothing. We have plans to make changes here, but not yet.

> gas price limit - again, for fee minimization
> an on/off switch (could effectively be worked around with the gas price limit above)

https://github.com/mysteriumnetwork/node/issues/5067

Thanks for the request.

**Comment by overland-liquor** [comment]
@tomasmik 

> This is rather difficult to implement without staking being required in the network

i dont understand how or why this would be true - why does it matter if the threshold is configurable between 5 and 99?  before this regression was implemented there was no limit at all.

>Currently it costs you 0.01957254520144 MYST

and the cumulative amount after the number of transactions to reach 99 would make it 0.38 - thats 7% of earnings
