### ISSUE TITLE
Old myst can't settle!

### ISSUE THREAD

**Issue by Jconfig** [mysteriumnetwork/node#5055]
**Describe the bug**

**To Reproduce**
1. Go to 'Node IP:4449'
2. Click on 'Settled Now'
3. Scroll down to '0.15MYST is available for Settle'

**Screenshots**
![Screenshot_2022_0426_080627](https://user-images.githubusercontent.com/67420848/165209879-5f4fc2c5-ab5c-4534-bff4-ad8c77650c46.png)

![Screenshot_2022_0426_080647](https://user-images.githubusercontent.com/67420848/165209900-d3403dee-7223-417f-a3a7-ba237c17c982.png)

**Environment (please complete the following information):**
 - Node version: [Node version: mainnet (1.6.5-4c6440ea)]
 - OS: [Ubuntu 20.04]
 - Your identity (if applicable): [e.g. 0x81854d9d63b381912a3042067006424112aaccc7]

**Additional context**
I updated my Ubuntu distro. When I had 0.75MYST after that I can't settle my all Myst I earned, only 0.15MYST are available for settle :(

**Comment by adinetech** [comment]
It's no longer possible for the node runners to manually settle the MYST earnings, update your node to enable automatic withdrawals to the external wallet once you reach 5 MYST.

**Comment by Jconfig** [comment]
> It's no longer possible for the node runners to manually settle the MYST earnings with the new version but not sure about the current situation you may try to use the incognito tab or clear the node UI cookies, you will only have automatic withdrawals to the external wallet with the new version and it will happen once every 5 MYST.
