### ISSUE TITLE
System not validating my .2 MYST sent

### ISSUE THREAD

**Issue by 2020movievault** [mysteriumnetwork/node#5059]
**Describe the bug**

I sent .2 MYST to claim my node. While the transaction has been confirmed on the block chain & has left my wallet it has not been confirmed by MYST.

**To Reproduce**

Steps to reproduce the behavior: Claim Node 

**Expected behavior**

Expected the system to validate the transaction. 

**Screenshots**

![Screenshot from 2022-04-20 18-39-55](https://user-images.githubusercontent.com/85257908/165317065-86d63506-b0ba-4eb5-a820-635661d39829.png)

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: Ubuntu
 - Desktop app version (if applicable): None 
 - Docker (if applicable): None
 - Your identity (if applicable): 
 - Payment (top-op) reference (if applicable): 0xa390aef61bd56010f8161fcc0135d1634e6889e6

**Additional context**
https://etherscan.io/tx/0xc8c4874dea966969dbf680e93ac2e3aa76c08f329fbe0804ba5fac6bc3418901

**Comment by adinetech** [comment]
Hey, you need to use the polygon network but you used Ethereum mainnet for this small transaction and wasted gas (eth) too!

**Comment by 2020movievault** [comment]
> Hey, you need to use the polygon network but you used Ethereum mainnet for this small transaction and wasted gas (eth) too!

Thanks for responding. I have MYST from the time I ran test net that's sitting in my ERC wallet. How can I or where can I convert them to MYST that's compatible to the polygon network?

**Comment by adinetech** [comment]
This issue can be closed, no response from the user.
