### ISSUE TITLE
Mysterium node gui not loading

### ISSUE THREAD

**Issue by speedf1** [mysteriumnetwork/node#5060]
Node 0xb5c256daaddae37fea5281b1a740f0b1d841db3b on a Raspberry Pi is running according to mystnodes.com.  I can log into the node through SSH.  However webgui on port 4449 has stopped responding.  Rebooting the Pi doesn't resolve the situation.  The gui has previously worked.

The Pi is running the mysterium image, and version 1.6.5

**Comment by Donatas-MN** [comment]
@speedf1 can you try to update to the newest version 1.6.9? Also, can you attach screenshot of Network tab in Chrome browser (mouse right click and select Inspect, then navigate to Network tab and reload page).

**Comment by speedf1** [comment]
Unfortunately I don't have access to the node for a while.  I'll update this ticket when I can get access.

**Comment by etherunit** [comment]
Any updates on this one?

**Comment by speedf1** [comment]
Unfortunately not.  The whole node is unresponsive.  I need to get physical access to it which is unlikely to be for a good few weeks.
