### ISSUE TITLE
Inaccessible Dashboard

### ISSUE THREAD

**Issue by arnav7633** [mysteriumnetwork/node#5066]
**Describe the bug**
Local dashboard becomes inacessible after a few hours and keeps giving timeout of 20000ms reached on path nat/type, price/current etc. 

**To Reproduce**
1. Go to local dashboard

**Expected behavior**
Dashboard loads in normally

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.6.2
 - OS: raspi os lite

![image](https://user-images.githubusercontent.com/68459855/165666808-138ff3d9-9781-44d3-adf2-0d478044d378.png)

**Comment by arnav7633** [comment]
No evident error in logs

**Comment by arnav7633** [comment]
On inspection I found this error `http proxy error: context cancelled`

**Comment by arnav7633** [comment]
Restarting led to loss of stats

**Comment by Snawoot** [comment]
Hello! This problem is solved in node version 1.6.4. Please upgrade.
