### ISSUE TITLE
Windows launcher - Node has stopped working

### ISSUE THREAD

**Issue by speedf1** [mysteriumnetwork/node#5072]
Node 0xbf58b2b1cdc4281dae809be06c7d7224817a10e3 has gone offline.  This is a node running on a Windows docker container.

The Mysterium Node Launcher keeps cycling status from "Offline" to "Installing".

Trying to start the container manually in docker gives the following message "Error invoking remote method 'docker-start'container'.  Error: (HTTTP code 500) server error - Ports are not available:  listen upd 0.0.0.0:58545: bind: An attempt was made to access a socket in a way forbidden by its access permissions."

This node has been working fine.  I don't think any changes have been made to the PC or network.

**Comment by Zensey** [comment]
Hi @speedf1 

If you are using `Manual port forwarding` mode and UDP port 58545 is used in the range of ports, then try to use some other range

**Comment by speedf1** [comment]
HI, I don't think this is the issue.  The node has been working fine.  Only recently it's started displaying this behaviour.  The "networking mode" option in the launcher is also greyed-out.

**Comment by Zensey** [comment]
@speedf1 
can you try execute a following command in a terminal / powershell:
`docker container port myst`

I'd like to get a list of ports bound by container

**Comment by speedf1** [comment]
Hi,

I'm not too familiar with docker, but that command doesn't seem to do anything.  See screenshot
![Screenshot 2022-05-07 052120](https://user-images.githubusercontent.com/87641705/167238013-42386b3a-0b81-4c1a-9ea7-ee1bee7c54cc.png)

**Comment by Zensey** [comment]
@speedf1 
Could you try start container manually from the Dicker desktop UI ?
If it fails, then try to detect which program uses the UDP port with the program called "Process Hacker 2". 
Or just close all programs, especially P2P programs, VoIP, browsers - they can use UDP ports for WebRTC protocol
and launch Docker Desktop first -- before other programs.

**Comment by speedf1** [comment]
So trying to start the node from the Docker UI now gives the following message:

Error invoking remote method 'docker-start-container':  Error: (HTTP code 500) server error.  Ports are not available. exposing port UDP 0.0.0.0.52559 ->0.0.0.0.0. listen udp 0.0.0.0:52559. bind: An attemp was made to access a socket in a way forbidden by its access permissions.

I've tried closing all other programs that are running on this PC.  Still the same message.  Again, this node was working.  I'm not aware of any changes that should've caused it to stop (nothing new has been installed).  I've checked for virus and nothing.

**Comment by Zensey** [comment]
Please remove myst container (from Docker desktop UI), container will be recreated automatically.

Also please provide:
- launcher version
- file %USERPROFILE%/.myst_node_launcher
- output of command: `docker container port myst`

**Comment by Zensey** [comment]
@speedf1 
the port range is wrong: 10000-60000

In general (42000-42100) 100 port is more than enough, it means 100 possible concurrent VPN consumers served simultaneously !
The use of a larger range is not advisable.

Ports from higher range like >=51000 and >=60000 are used by OS and VoIP applications, like WebRTC / browser, so don't use ports from higher ranges.

**Comment by Zensey** [comment]
@speedf1 
So you need to change port range, preferably to 42000-42100 and remove container, so a new instance will be created with correct port range
