### ISSUE TITLE
consumer-mode not starting

### ISSUE THREAD

**Issue by jkimmel** [mysteriumnetwork/node#5073]
Starting mysterium-consumer exits with error, but account info shows it is registered

```
pi@raspberrypi:~ $ sudo systemctl start mysterium-consumer.service
pi@raspberrypi:~ $ sudo systemctl status mysterium-consumer.service
● mysterium-consumer.service - Consumer client for Mysterium - decentralised VPN Network
     Loaded: loaded (/lib/systemd/system/mysterium-consumer.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2022-04-29 12:19:20 CEST; 718ms ago
       Docs: https://mysterium.network/
    Process: 7788 ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS daemon (code=exited, status=1/FAILURE)
   Main PID: 7788 (code=exited, status=1/FAILURE)
        CPU: 362ms

```
```
pi@raspberrypi:~ $ myst account info
[SECTION] General account information:

[INFO] Using identity:0x79854176f07087676d060e4bfeaf951b6729822b
[INFO] Registration Status:Registered
[INFO] Channel address:0x6Cf5faa5AF1F0498e304dC4Cf1438ceE35459fB8
[INFO] Balance: 0.000000

```

**Environment (please complete the following information):**
 - Node version: [1.6.5]
 - OS: [raspbian buster]
 - 
 - Your identity: [0x79854176f07087676d060e4bfeaf951b6729822b]

**Comment by adinetech** [comment]
Do you followed this docs? https://docs.mysterium.network/for-users/linux
<img width="865" alt="image" src="https://user-images.githubusercontent.com/68943180/165972259-b328c12f-1f2f-4490-8fb6-06942c9d8465.png">

**Comment by jkimmel** [comment]
Yes, that's exactly what I did.

AdineVikash ***@***.***> schrieb am Fr., 29. Apr. 2022, 17:09:

**Comment by jkimmel** [comment]
Now I see
` mysterium-consumer.service - Consumer client for Mysterium - decentralised VPN Network
     Loaded: loaded (/lib/systemd/system/mysterium-consumer.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-04-29 13:11:16 CEST; 1 day 23h ago
       Docs: https://mysterium.network/
   Main PID: 12485 (myst)
      Tasks: 11 (limit: 1597)
        CPU: 4min 33.446s
     CGroup: /system.slice/mysterium-consumer.service
             └─12485 /usr/bin/myst --config-dir=/etc/mysterium-node --script-dir=/etc/mysterium-node --data-dir=/var/lib/mysterium-node --runtime-dir=/var/run/mysterium-node --keysto>

Apr 29 15:46:30 raspberrypi myst[12485]: 2022-04-29T15:46:30.833 WRN communication/nats/connection_wrap.go:106 > NATS: reconnected
Apr 29 15:46:31 raspberrypi myst[12485]: 2022-04-29T15:46:31.172 WRN requests/dialer_swarm.go:293             > Failed to lookup host: "broker.mysterium.network" error="lookup broker>
Apr 29 16:15:10 raspberrypi myst[12485]: 2022-04-29T16:15:10.990 WRN communication/nats/connection_wrap.go:105 > NATS: disconnected error="nats: stale connection"
Apr 29 16:15:34 raspberrypi myst[12485]: 2022-04-29T16:15:34.996 WRN requests/dialer_swarm.go:293             > Failed to lookup host: "broker.mysterium.network" error="lookup broker>
Apr 29 16:16:06 raspberrypi myst[12485]: 2022-04-29T16:16:06.018 WRN requests/dialer_swarm.go:293             > Failed to lookup host: "broker.mysterium.network" error="lookup broker>
Apr 29 16:16:30 raspberrypi myst[12485]: 2022-04-29T16:16:30.023 WRN requests/dialer_swarm.go:293             > Failed to lookup host: "broker.mysterium.network" error="lookup broker>
Apr 29 16:16:59 raspberrypi myst[12485]: 2022-04-29T16:16:59.685 WRN communication/nats/connection_wrap.go:106 > NATS: reconnected
Apr 30 05:24:14 raspberrypi myst[12485]: 2022-04-30T05:24:14.791 WRN communication/nats/connection_wrap.go:105 > NATS: disconnected error="read tcp 192.168.1.146:32859->51.15.116.186>
Apr 30 05:24:16 raspberrypi myst[12485]: 2022-04-30T05:24:16.475 WRN communication/nats/connection_wrap.go:106 > NATS: reconnected
Apr 30 06:12:59 raspberrypi myst[12485]: 2022-04-30T06:12:59.300 WRN requests/dialer_swarm.go:293             > Failed to lookup host: "hermes.mysterium.network" error="lookup hermes>
~
`

**Comment by jkimmel** [comment]
Without any intervention on my part, the log now looks like this:

`● mysterium-consumer.service - Consumer client for Mysterium - decentralised VPN Network
     Loaded: loaded (/lib/systemd/system/mysterium-consumer.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-04-29 13:11:16 CEST; 2 days ago
       Docs: https://mysterium.network/
   Main PID: 12485 (myst)
      Tasks: 11 (limit: 1597)
        CPU: 6min 51.830s
     CGroup: /system.slice/mysterium-consumer.service
             └─12485 /usr/bin/myst --config-dir=/etc/mysterium-node --script-dir=/etc/mysterium-node --data-dir=/var/lib/mysterium-node --runtime-dir=/var/run/mysterium-node --keystore.lightweight dae>

Mai 01 13:35:50 raspberrypi myst[12485]: 2022-05-01T13:35:50.752 DBG identity/selector/handler.go:103         > Found identity in cache: 0x79854176f07087676d060e4bfeaf951b6729822b
Mai 01 13:35:50 raspberrypi myst[12485]: 2022-05-01T13:35:50.752 DBG identity/manager.go:153                  > Unlocked identity found in cache, skipping keystore: 0x79854176f07087676d060e4bfeaf951b6>
Mai 01 13:35:50 raspberrypi myst[12485]: 2022-05-01T13:35:50.753 DBG identity/selector/handler.go:108         > Unlocked identity: 0x79854176f07087676d060e4bfeaf951b6729822b
Mai 01 13:57:13 raspberrypi myst[12485]: 2022-05-01T13:57:13.049 DBG eventbus/event_bus.go:101                > Published topic="order_updated" event=ID: 5482a124-d1ab-43f5-9109-b611226596df, Identity>
Mai 01 15:13:47 raspberrypi myst[12485]: 2022-05-01T15:13:47.096 WRN requests/dialer_swarm.go:293             > Failed to lookup host: "hermes.mysterium.network" error="lookup hermes.mysterium.network>
Mai 01 20:13:55 raspberrypi myst[12485]: 2022-05-01T20:13:55.279 WRN requests/dialer_swarm.go:293             > Failed to lookup host: "hermes.mysterium.network" error="lookup hermes.mysterium.network>
Mai 01 20:56:28 raspberrypi myst[12485]: 2022-05-01T20:56:28.445 WRN communication/nats/connection_wrap.go:105 > NATS: disconnected error="nats: stale connection"
Mai 01 20:56:30 raspberrypi myst[12485]: 2022-05-01T20:56:30.519 WRN communication/nats/connection_wrap.go:106 > NATS: reconnected
Mai 02 05:22:15 raspberrypi myst[12485]: 2022-05-02T05:22:15.423 WRN communication/nats/connection_wrap.go:105 > NATS: disconnected error="read tcp 192.168.1.146:49855->51.15.116.186:4222: read: conne>
Mai 02 05:22:21 raspberrypi myst[12485]: 2022-05-02T05:22:21.097 WRN communication/nats/connection_wrap.go:106 > NATS: reconnected
`

Why are these connection problems?
Is my client now logged in? I would like to know this before I do a topup.

**Comment by tomasmik** [comment]
Can you reach those addresses using your browser or curl? For example `hermes.mysterium.network`
Where is this node located, what country? Are you able to reached the internet and is your DNS resolution OK?

**Comment by jkimmel** [comment]
Yes, I can reach 'hermes.mysterium.network`
Node is located in Spain

**Comment by tomasmik** [comment]
If you are able to reach that address, then your node should be too. Maybe there were some temporary connection issues, could you check again?

**Comment by isaackielma** [comment]
@jkimmel Are you still experiencing the issue?

**Comment by jkimmel** [comment]
The issue has gone.
But I still see in the log "quality":{"quality":0,"latency":0,"bandwidth". Is this the reason I have almost no traffic?
Almost no traffic means 1.5 Myst within two weeks
