### ISSUE TITLE
0 Bytes sessions from Germany.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5080]
**Describe the bug**
Most of the node runners receive 0 bytes test sessions from Germany, but at least it should show a few Kilobytes/Megabytes (Exchange of invoice maybe didn't take place)

**Expected behavior**
A session should use a few Kilobytes while at idle.

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/165971582-85b049ee-1e8a-42a8-81d5-32b298dd89c1.png)
![image](https://user-images.githubusercontent.com/68943180/165971611-34474bc5-73da-42a0-a76f-4e18e9a2b4a4.png)

**Comment by arnav7633** [comment]
or near to 0, i.e 500ish kb

**Comment by arnav7633** [comment]
With background services unavoidable few kilo bytes also dont make sens, i have had connections about 30 hours with just 500 kbs which is literally impossible as on whatever device you use there is always background services connected to servers
