### ISSUE TITLE
Account deleted 

### ISSUE THREAD

**Issue by Rufaiadetayo01** [mysteriumnetwork/node#5081]
Good day I deleted my mysterium app and I try to Login back but it says wrong password and that's the password I use to download my key #

**Comment by adinetech** [comment]
You might used different password.

**Comment by Rufaiadetayo01** [comment]
And what can I do about it because all I have is the key and I registered the account about 2 month now and haven't used it much it remain like 9.5

**Comment by Rufaiadetayo01** [comment]
And is it possible to use different password for the key and login

**Comment by adinetech** [comment]
No, the restore/import password should be the same as the exporting/backup password.

**Comment by Rufaiadetayo01** [comment]
But am sure about the password I use to download the key because I downloaded it yesterday before uninstalling the app

**Comment by Rufaiadetayo01** [comment]
![Screenshot_20220430-061441](https://user-images.githubusercontent.com/104661069/166103353-905c1123-1ef8-4a87-afb2-53dccf5699be.png)
Downloaded on 29th of this month

**Comment by Rufaiadetayo01** [comment]
What can I do about the account I only have the address and the file
