### ISSUE TITLE
Cannot Reset Password

### ISSUE THREAD

**Issue by marconyew** [mysteriumnetwork/node#5082]
Seems that on Ubuntu 20.04 on Digital Ocean. I cannot reset my node password. Everytime I run the myst reset command the MYST UI keeps redirecting me to type in my old password. 

Personally, I love contributing to this project but I need to see my node stats!

**Comment by tomasmik** [comment]
`myst reset --tequilapi` seems to work fine for me. Make sure to try incognito or deleting your cache/cookies.

**Comment by Donatas-MN** [comment]
Try to reproduce in NodeUI.

**Comment by tomasmik** [comment]
Works in all cases

**Comment by Donatas-MN** [comment]
Yes, worked for me as well in the NodeUI. Make sure you update to the newest version in case it still does not work.
