### ISSUE TITLE
Connection is "limited". No other time where it is shown as "Most"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5083]
**Describe the bug**
Not able to change "Accepting Connections: Limited" to "Accepting Connections: Most". I have node in raspberry pi, please help me to improve the connection

Node ID: 0x84caba7b288429cc1083c5765e0ee560ca339b0f

Tried port forwarding and disabling any Firewalls but no success

**Screenshots**
<img width="1418" alt="Screenshot 2022-05-01 at 20 29 08" src="https://user-images.githubusercontent.com/84313603/166168996-50a2f51d-fb0f-4a49-a992-cc9d37b3134a.png">

**Comment by Donatas-MN** [comment]
This is not a bug. It means that connection is limited by something on user end. Try to follow this guide: https://docs.mysterium.network/troubleshooting/troubleshooting-nat-type-related-issues
