### ISSUE TITLE
NodeUI - NodeUI improvements and bug fixes

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#5084]
- [x] Currently "external wallet" is shown here while it should be Beneficiary:
![Pasted_Image_2022-05-02_10_20](https://user-images.githubusercontent.com/91055712/166198622-2bace551-a8ec-40bf-85ad-9b65ae08ce6b.jpg)

This might lead to such situations as above when user might think beneficiary change was successfully done, but in reality it's not.

- [x] Some time ago we used to show Auto withdrawal: ERROR in case there was error changing beneficiary. It's not shown anymore, but should be:
![Pasted_Image_2022-05-02_10_22](https://user-images.githubusercontent.com/91055712/166198853-b8af49f8-d9b4-4c65-a859-4d80f00b4218.jpg)

- [x] Font size should be the same for text and address here (in SETTLE NOW modal):
![Pasted_Image_2022-05-02_10_23](https://user-images.githubusercontent.com/91055712/166198955-7f520dd9-6f31-4c56-966a-946ee013d378.jpg)

- [x] Spinner on Withdraw button is working fine, so we should also implement on SETTLE NOW:
![Pasted_Image_2022-05-02_10_26](https://user-images.githubusercontent.com/91055712/166199272-8c0a2951-e238-473a-8732-206ba9b213e1.jpg)

**Comment by lusine-h** [comment]
Settlement is not working correctly, I had X amount to settle and after clicking on the "Settle" button, it shows a spinner on the "Settle now" button, then the spinners is disappeared and I see the same amount as I had before settlement. 
Other improvements are fine.

**Comment by Donatas-MN** [comment]
Worked fine for me. Can you try again @lusine-h? This spinner does not reflect error, I mean it will spin for a minute as most of settlements will be done within such period.
