### ISSUE TITLE
Node Showing Less Earning Balance

### ISSUE THREAD

**Issue by kabirzohaib22** [mysteriumnetwork/node#5086]
My node is not showing the total earnings in my Internal Balance.
The Balance i'm getting is less.

Node Identity - 0xc35e91a92d88cfe6692d250268b478e81c3d9f8c
![Screenshot from 2022-05-02 18-37-16](https://user-images.githubusercontent.com/87380999/166238939-300802cd-0d95-477b-bb76-2fb1c4c234b8.png)

**Comment by adinetech** [comment]
Remember that you have to pay a 20% network fee + Polygon fees for every settlement and automatic withdrawals, so total earnings will be less than what you actually have in your wallet.

**Comment by Donatas-MN** [comment]
Yes, internal balance is earnings after all fees, in other words the amount you can withdraw. 

Also make sure you click "Enable automatic withdrawals" and set your wallet for Automatic withdrawals!
