### ISSUE TITLE
Migrating topup from one device to another

### ISSUE THREAD

**Issue by jkimmel** [mysteriumnetwork/node#5087]
The title tells it all.
In my case migrating from desktop to consumer mode on a Raspi.
Anyway my search didn't find anything related in the docs so I'm asking here.

**Comment by tomasmik** [comment]
Can't you just export the identity and use it on both devices? The only problem is that you can't create a connection from both devices at the same time, but you will have your identity and balance on both of them.

**Comment by jkimmel** [comment]
How to do it?
Especially how to import identity in a Raspi node which already has a identity.
