### ISSUE TITLE
Remind node runners to update their nodes to latest versions with a notification

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5089]
**Is your feature request related to a problem? Please describe.**
Currently some node runners are forgetting to update their nodes and their sessions will stop accumulating MYST due to that. This will also help us avoid other version incompatibility issues.

example of possible outcome: https://github.com/mysteriumnetwork/node/issues/4912

**Describe the solution you'd like**
If users are warned of such issue before it happens, it will help avoiding nodes sharing bandwidth without earning rewards.

**Describe alternatives you've considered**
There are possible alternative such as autoupdate or something along those lines. A simple solution perhaps for now could be a pop up notification that is very conspicuous. That way users will be more aware of the importance of keeping their nodes up to date.

**Comment by Donatas-MN** [comment]
This is planned with https://github.com/mysteriumnetwork/node/issues/5011.
