### ISSUE TITLE
Nodes show online but have no last seen time on them 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5090]
<img width="1240" alt="Screenshot 2022-05-03 at 17 50 58" src="https://user-images.githubusercontent.com/84313603/166564082-a73c7ade-557d-4d50-aafa-abcadd5a3082.png">

**Comment by Donatas-MN** [comment]
It's expected behaviour, not a bug. Last seen is shown only for "Offline" status to indicate how much time passed when node was last seen online.

if node status is Online here, it means it's currently available for connection.
