### ISSUE TITLE
Node version is stuck in 1.4.8

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5091]
**Describe the bug**
Node version is stuck in 1.4.8 how can it be upgraded?
Already tried sudo apt update and sudo apt install myst as suggested in the guides, but it says i have the latest version.

Logs:

https://mystnodes.com/support/logs/2022-04-29-8d5d7987-1aab-4400-8940-ab4afe661c7b-mysterium-node.zip4227380361

**Comment by Donatas-MN** [comment]
Can you ask user to do following:
1. Restart node by executing `reboot` command in terminal.

2. Try to switch to pre-release version by executing these 2 commands:
`sudo add-apt-repository ppa:mysteriumnetwork/node-pre`
`sudo apt update; sudo apt install myst`

3. If it does not work, ask to send us screenshot of terminal when trying to do update.
