### ISSUE TITLE
Withdraw error

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5098]
Description:

31 Myst disappear after trying to withdraw them. No transaction appears on my wallet withdraw transaction history. My withdraw address is good and compatible with polygon network, works fine on my second node. 

Logs:

https://mystnodes.com/support/logs/2022-05-04-4661ab19-a6f0-40b9-a027-f2ac244b7bb6-mysterium-node.zip2219234103

**Comment by Guillembonet** [comment]
I issued a fix for this and sent you 0.2 MYST. Try to withdraw that and you should receive the "lost" amount + that as a bonus
