### ISSUE TITLE
Registration payment failed

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5099]
I paid with paypal, for network registration, but I never received myst
and the registration failed.
I tried to repeat the payment but it gives me an error message:
"Cannot create a registration topup while you have previous orders in progress
or completed".
What can I do?
Thanks
<img width="1275" alt="Screenshot 2022-05-04 at 17 57 21" src="https://user-images.githubusercontent.com/84313603/166824784-5162421b-9dee-40ac-9c2f-c9b7d71537bb.png">

PayPal transaction ID: 4A383469MY161610H

root@36ee1788bed6:/home/claudio# myst cli identities new
[SUCCESS] New identity created:0x7f9ec185c33b4e00056ef3b7d090f9585cf8cbeb
root@36ee1788bed6:/home/claudio# myst account set-identity 0x7f9ec185c33b4e00056ef3b7d090f9585cf8cbeb
[SUCCESS] Identity 0x7f9ec185c33b4e00056ef3b7d090f9585cf8cbeb set as default

[INFO] Using identity:0x7f9ec185c33b4e00056ef3b7d090f9585cf8cbeb
[INFO] Registration Status:Unregistered
[INFO] Channel address:0x6CA8068180642057B0Dc56E371D65302a4c54C54
[INFO] Balance: 0.000000

**Comment by Guillembonet** [comment]
hello, please update node version to latest and reopen if it still happens. Make sure version is >= [1.6.8](https://github.com/mysteriumnetwork/node/releases/tag/1.6.8)
