### ISSUE TITLE
Mobile: android and ios entrypoints should use different subpackages

### ISSUE THREAD

**Issue by tadovas** [mysteriumnetwork/node#510]
In order to adapt mobile entrypoint for each OS (android, ios) mobile package should be split into OS specific subpackages, this way full pontential of gomobile can be used (java interop on android package, swift/objc on ios)

**Comment by zolia** [comment]
Not sure if its still relevant. We already have WireguardTunnelSetup and Openvpn3TunnelSetup those probably should be left in the same, mysterium package due to how packages are being included in mobile frameworks..

**Comment by Waldz** [comment]
Is there a point to artificially improve iOS package.
We will work on that then doing iOS connection.
