### ISSUE TITLE
Update to 1.6.9 not visible on mystnodes

### ISSUE THREAD

**Issue by KonradBorowiecki** [mysteriumnetwork/node#5102]
I have updated a few hours ago and the update is not shown on NodeUI or mystnodes website.
My raspberry pi says: 
myst is already the newest version (1.6.9+build529119828+focal).

Where versions reported in NodeUI are:
Node version: mainnet (1.4.1-5331dabd)
NodeUI version: 1.7.3

I did a sudo reboot and the NodeUI shows correctly.

Is there anything one needs to do for the update of the pi to be observed by mystnodes?

My node id is: 0x47b2cda366aae6f1965ecf286c1f74b2d36f1952

**Comment by etherunit** [comment]
I can see that your node service proposal appeared again. Please wait a bit while it switches to online.

**Comment by KonradBorowiecki** [comment]
@etherunit what do you mean service proposal? How did I do that? The Status is online now. I used these two commands I am not sure if they sorted me last time. Whatever I did something has helped. Could you clarify what might have actually been the command that helped here?
sudo systemctl enable mysterium-consumer.service
sudo systemctl status mysterium-consumer.service

**Comment by etherunit** [comment]
Mysterium node service could be enabled directly in UI via toggle or in terminal: 
`sudo systemctl enable mysterium-node.service`
Anyway, I can confirm that your node is online and working fine.
