### ISSUE TITLE
Bug - Participation in the network without reward

### ISSUE THREAD

**Issue by S4endSTORM** [mysteriumnetwork/node#5103]
**Describe the bug**
I have a session (4fa5fd50) from Belarus that lasts for more than 3 days on my node but without reward.

**Screenshots**
https://zupimages.net/viewer.php?id=22/18/lccl.png

**Environment (please complete the following information):**
 - Node version: 1.6.9-5a512e40
 - OS: Windows 11
 - Desktop app version (if applicable): 1.0.30
 - Docker (if applicable): 4.7.1 (77678)
 - Your identity (if applicable): 0x0200f6f22cb88e36cb01ca511d499f30e6a7a5c6

**Comment by etherunit** [comment]
Could you please copy > paste truncated session id? The one from UI.

**Comment by S4endSTORM** [comment]
4fa5fd50

**Comment by etherunit** [comment]
Thanks for providing it. 
From the first glance, it looks like consumer reported only the part of the metrics, but even that part for some reason is not reflected locally in UI. 
I suspect that proper price calculation based on data transferred failed and thus failing a session to cleanup properly.
Could you provide us with the output from /`var/lib/mysterium-node/db/myst.db` file so we can take a better look at local stats

**Comment by S4endSTORM** [comment]
I find  `/var/lib` in Docker folders but i can't find/haven't `mysterium-node/db/myst.db`.
Therefore I cannot provide you with the requested file.

**Comment by etherunit** [comment]
Please check the article: Finding data-dir in dockerized node (Windows host) - https://docs.mysterium.network/for-node-runners/migrating-your-node

**Comment by S4endSTORM** [comment]
Thanks for your help.
Here is the requested file: [myst.zip](https://github.com/mysteriumnetwork/node/files/8684412/myst.zip)

**Comment by etherunit** [comment]
Please provide with the key used to encrypt the database.

**Comment by etherunit** [comment]
1st entry:`{"SessionID":"4fa5fd50-7b16-4085-8c9d-faff8498d602","Direction":"Provided","ConsumerID":{"address":"0x2602c42bb405a7b6cacefe1617b4a430d33f57ba"},"HermesID":"0xa62a2A75949d25e17C6F08a7818e7bE97c18a8d2","ProviderID":{"address":"0x0200f6f22cb88e36cb01ca511d499f30e6a7a5c6"},"ServiceType":"wireguard","ConsumerCountry":"BY","ProviderCountry":"FR","DataSent":0,"DataReceived":0,"Tokens":0,"IPType":"","Status":"New","Started":"2022-05-02T11:35:22.739073986Z","Updated":"0001-01-01T00:00:00Z"}"`

From the first glance, provider part of reporting has failed and therefore I'm not seeing any stats being stored locally. Btw, it would great if you could also add your node logs.
https://docs.mysterium.network/troubleshooting/reporting-an-issue

**Comment by S4endSTORM** [comment]
Logs:
https://mystnodes.com/support/logs/2022-05-16-c71aa3d6-5204-44ec-a8c7-9eab484dda5e-mysterium-node.zip3137937140

**Comment by etherunit** [comment]
Thanks for the log output, however, it useless as it doesn't cover the required dates for analysis.

**Comment by S4endSTORM** [comment]
I understand, thank you for your help.
If there is a way to provide you with the logs over the desired period I would do it as soon as possible, not being used to this kind of approach I do not have the knowledge for that.

Otherwise if there is nothing else to do, I will close this "issue".
Looking forward to your return.
