### ISSUE TITLE
autosettlement is a regression

### ISSUE THREAD

**Issue by overland-liquor** [mysteriumnetwork/node#5108]
**Describe the bug**

autosettlement is taking ~20% of profits per transaction currently.

**To Reproduce**

look at transactions in node dashboard

**Expected behavior**

settlement options should be controllable by node operators to include all of the following:
1) an option to disable autopayment, as before this regression was introduced
2) a fee threshold
3) an option to increase the payout amount to payment contract max

**Screenshots**

![image](https://user-images.githubusercontent.com/97700468/167451139-e2c20922-863d-4b98-a41d-de8dcde39f47.png)

**Environment (please complete the following information):**
 - Node version: 1.13.0
 - OS: debian 10
 - Docker (if applicable): Docker version 20.10.14, build a224086

**Comment by Donatas-MN** [comment]
This is not a bug. As explained in nodeUI (click ? next to Unsettled earnings) these are the settlement fees:
- Network settlement fee: 20% (fixed fee).
- Blockchain transaction fees: dynamic depending on blockchain conditions and congestion.

Auto settlement is done every 5 MYST. If node runner wants to settle before that then he can click "Settle now" button and settle before reaching 5 MYST. 

Currently 5 MYST auto-settlement threshold cannot be increased.
