### ISSUE TITLE
"Identity not found" error message

### ISSUE THREAD

**Issue by speedf1** [mysteriumnetwork/node#5110]
I've migrated two nodes from running on an RPI to docker (Windows) using the instructions on the dysmetrium documentation.  Migration seems to have worked, but whenever I log into the webgui on either of those nodes, I get the error message in the bottom right of the screen that says "Identity not found" (see attached screenshot.
![identity not found](https://user-images.githubusercontent.com/87641705/167639013-03d55996-a263-4f7c-aebd-372733aff051.png)

**Comment by etherunit** [comment]
Try to restart node and it should be fine.

**Comment by speedf1** [comment]
Nope.  That didn't fix it.

**Comment by etherunit** [comment]
This could also indicate that some file content of the previous node is missing. Have you migrated all data content or just specific sets of data?
