### ISSUE TITLE
unreachable node

### ISSUE THREAD

**Issue by HasseM** [mysteriumnetwork/node#5112]
I'm running a RPi node for some time now and I got an email that I needed to update because else I would lose my balance. So I followed instructions.....

Update went okay (from 1.0.5 to latest). But after the update my node is unreachable via webgui or mynodes.
- I can reach my node over SSH and login without problems.
- I cannot reach my node via browser on ip:4449
- My node stays offline in the MyNodes tab.
- I tried downloading and installing it again on a new SD card but I get exactly the same problem. It does not even show up as a new node.
- On SSH I tried entering 'myst show config' but I get: Segmentation fault.

So previously working install does not work anymore after following update instructions. Also new installation does not work. I will try different RPi tomorrow (not at hand right now). But I guess it will be a huge problem to get it solved before the deadline!

**Comment by HasseM** [comment]
I was just wondering if the update has higher system requirements? I just noticed that the Pi I am using has just 2 USB ports and a big SD card adapter, so it may be a PI Model B. The 1.0.5 version worked okay on it.  And the Segmentation fault message implies something with memory. So 1+1=2......? I'll have a new Pi3 by tomorrow. What would be the instructions to migrate to it? I have a major issue with the migration [instructions ](https://docs.mysterium.network/for-node-runners/migrating-your-node) on your website: I cannot do 'myst config show' to get the data-dir as this command also gives a Segmentation fault. I also cannot just put the existing SD card (the big model) into the microsd card slot of a Pi3. So I need a way to copy the config file from one pi to the other or something like that. I am not a Linux Guru so some advice on how to find and copy the (whole?) data-dir would be nice.

**Comment by etherunit** [comment]
It could be the result of filesystem corruption on the SD card (re-image the SD Card (or preferably a new SD Card) from the backup would work. 
It could also indicate the lack of space on the SD card or memory shortage. If you are using raspberry pi 1 model b it might have only 256 MB of memory. It might be not enough for both myst and OS. We haven't done any big changes regarding memory usage, but with that small memory size every MB might be critical.
