### ISSUE TITLE
Issue #5110 inadvertently close

### ISSUE THREAD

**Issue by speedf1** [mysteriumnetwork/node#5115]
Issue #5110 was closed but is still open.

Latest updated:

All data was migrated from one node to the other, as per instructions on https://docs.mysterium.network/for-node-runners/migrating-your-node

**Comment by etherunit** [comment]
I suspect "Identity not found" error is not related to the migration process then. I have experienced the exact same issue a couple of days ago. If you still experience it each time while newly logged in or just by refreshing your UI page, then please submit the latest node logs (make sure to update it to the latest version before final check).

**Comment by speedf1** [comment]
How do I capture the node logs?

**Comment by isaackielma** [comment]
Here are the new node logs submitted a little less than an hour ago:

https://mystnodes.com/support/logs/2022-05-19-39308da8-8b6c-45c6-ba14-6472396b7fb4-mysterium-node.zip661450233

**Comment by etherunit** [comment]
Thanks @isaackielma 
related #4846

**Comment by etherunit** [comment]
#4846

**Comment by etherunit** [comment]
@speedf1 Do you still experience the "Identity not found" issue after the latest fixes have been deployed into prod?

**Comment by speedf1** [comment]
@etherunit Hi, just checked and yes, I'm still seeing it on version 1.8.1.
