### ISSUE TITLE
session without payment

### ISSUE THREAD

**Issue by DiogoMarques2003** [mysteriumnetwork/node#5117]
**Describe the bug**
Today I had a connection that didn't give me any payment.

**Screenshots**
![image](https://user-images.githubusercontent.com/52538977/168245541-befee64c-02da-4e1f-a180-df4dfffd8293.png)

**Environment (please complete the following information):**
 - Node version: 1.6.9-5a512e40
 - OS: ubuntu
 - Your identity (if applicable): 0x2cdcacc6ffdb4db74b9fb898e14d0e24e3373494
 - session id: 6992feae-73f9-4cf0-a493-289a2ed0e62e

**Comment by etherunit** [comment]
The session was too short to issue an invoice for payment. 
![Screenshot 2022-05-16 at 08 26 36](https://user-images.githubusercontent.com/60128746/168525211-3dc9723c-cf9c-45c6-9f4e-175d6aa965cf.png)

**Comment by DiogoMarques2003** [comment]
Okay I thought since he used 535mb of data he was going to pay
