### ISSUE TITLE
Payment for using myst dint go through 

### ISSUE THREAD

**Issue by Hopeisalive312** [mysteriumnetwork/node#5118]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
 I did pay twice for the service using Android device and myst application 120 plus 120 tokens twice on the network to use dvpn but my payment dint go through although on block chain it says confirmed but my application isn't active yet what shall be done i have asked the mod in the telegram group he asked me to register a complaint here with the transaction hash(adine). I will be posting both the transaction hash here now 
Please check to it and refer to me asap. As i am worried about the money.
https://bscscan.com/tx/0x679117fb544eb214dc70aaa5e3a0eff8d8d5291789d627681094320654753648
0x7893fc7afa4ce41a36ad66c245d973f2b27d9b9bb6f176e0e56b0d01839954c2
Both the transaction hash are here i have submitted the token on bsc chain.
Swapped it from pancake swap and paid to coingate via bsc chain thank you.

**Comment by etherunit** [comment]
Please note that at least on mobile app, USDT top ups via Coingate are supported via Ethereum network only. Doing it via BSC will fail without possibility to recover.

**Comment by etherunit** [comment]
Please note that there is a warning directly on our app informing users that Ethereum network is supported only (for MYST top ups via Coingate).

**Comment by etherunit** [comment]
After discussed it internally, we agreed to make a partial refund for you (as an act of good will). Please provide us with your Polygon compatible wallet address (or identity channel).

**Comment by Hopeisalive312** [comment]
I am sorry but i don't still see that thing written in your application. I have send you screenshot please see to it. If it was written at all i wouldn't have made the payment in the first go. Although this is my matic address 0xe3Ff2779c078398E181a44B9d0D4530A5B9b9caA 
![Screenshot_20220518-190758_1](https://user-images.githubusercontent.com/105502361/169053595-cabca3ec-b840-4377-bdba-498229326cfa.jpg)
It's not showing the way you have described rather it is other way

**Comment by etherunit** [comment]
What's the mobile app version you are using?

**Comment by Hopeisalive312** [comment]
![Screenshot_20220522-162415_1](https://user-images.githubusercontent.com/105502361/169691750-7c342327-a753-4cd2-8b4b-b363480539f8.jpg)
This is the version i am using

**Comment by etherunit** [comment]
Could you please update it to v2.0.15
Go to Google Play store and Update from there.
Once updated, navigate to the payment section and look for the notice.

**Comment by Hopeisalive312** [comment]
In the play Store it says it is already updated to the latest version any way what could be done to resolve the issue? As it's already been 15 days since i have recharged it

**Comment by etherunit** [comment]
@Hopeisalive312 Apologies for the delayed reply. We have checked it once again internally with team members. 
I can confirm that v2.0.9 acknowledge users on the supported chains when doing MYST top up via Coingate gateway.
Please see below:
![Screenshot 2022-05-31 at 09 52 37](https://user-images.githubusercontent.com/60128746/171110856-b9714c15-161b-4ce1-a5a7-d6982ef32549.png)
![Screenshot 2022-05-31 at 09 52 44](https://user-images.githubusercontent.com/60128746/171110868-23c895f9-e4a1-4ef1-8396-1c6b87a12a05.png)
This screen is available once you click on top up MYST token and go next to confirm.

**Comment by etherunit** [comment]
Could you please make a screenshot of what you're seeing on your end when selecting MYST for top up? Each step of clicking Next. Thanks!

**Comment by Hopeisalive312** [comment]
I have done all the processes already kindly please refund as you have mentioned earlier it's already a month since i have purchased it twice

**Comment by etherunit** [comment]
https://polygonscan.com/tx/0xf539214f9fa25a4c65a170c4b43e84bb548ad7d02775e9be9b1202b28dc8e8cd

**Comment by Hopeisalive312** [comment]
First of all thank you so much.
I did send 2 times 120 tokens of myst one from polygon matic and other from bsc network total 240 myst tokens and i just back 50 tokens which is not even half of it.
Transaction details are mentioned above for both in starting of the thread

**Comment by Hopeisalive312** [comment]
Am i getting any reply for this ?

**Comment by etherunit** [comment]
@Hopeisalive312 Could you please clarify once again your ID? You can find it under `Profile > Mysterium Identity Address.`

**Comment by Hopeisalive312** [comment]
What does that mean ?

**Comment by Hopeisalive312** [comment]
I have sent both the transaction details above as i have send myst from 2 accounts

**Comment by Hopeisalive312** [comment]
Cause first i send it dint work then second again i send.
And one more question ltc does work right? With this myst i can send ltc and it will still work right?

**Comment by etherunit** [comment]
The identity is the parameter which "identify" you on the network and track all previous transactions.
The identity could be viewed directly in the dVPN app under Profile (Main menu) > Mysterium Identity Address.
 Could you please copy > paste it here?

**Comment by etherunit** [comment]
Do you have access to your mobile application?

**Comment by Hopeisalive312** [comment]
No i deleted it i am sorry but although it was working so i deleted it

**Comment by Hopeisalive312** [comment]
Hello 👋 is anyone listening?
