### ISSUE TITLE
The node stopped transmitting 2 days ago

### ISSUE THREAD

**Issue by juanjogonzalez** [mysteriumnetwork/node#5120]
**Describe the bug**
It's been 48 hours since my node stopped transmitting (displayed as offline on the dashboard) but I don't get any errors. 
I restarted, stop & start the node and the problem persists

**To Reproduce**
1. Go to Url: localhost:4449
2. Click on Button: View All Sessions
3. Show the sessions List
4. The last session is May 11

**Expected behavior**
There is Live Sessions, but no new sessions

**LOG**
may 12 11:04:38 juanjo-ubuntu myst[4216]: 2022-05-12T11:04:38.869 DBG communication/nats/sender.go:59 > Message "signed.-ydYR3BbHU7xJmrRzeRJlFRteLwbmhl7m7-B6Kv0ZJF4fJjlNZP_zijy5mkNZhplL8AocnAzras_5SjZ3YNk-gA.1652367878.*.proposal-ping.v3" sending: {"proposal":{"id":0,"format":"service-proposal/v3","compatibility":2,"provider_id":"0x841c19c5f6e5a3d4fd7042a0b23525ad219cae9f","service_type":"wireguard","location":{"continent":"SA","country":"CL","city":"Santiago Metropolitan","asn":27901,"isp":"Mundo Chile","ip_type":"residential"},"contacts":[{"type":"nats/p2p/v1","definition":{"broker_addresses":["nats://broker.mysterium.network:4222","nats://broker.mysterium.network:4222","nats://[51.15.116.186:4222](http://51.15.116.186:4222/)","nats://[51.15.72.87:4222](http://51.15.72.87:4222/)"]}}],"quality":{"quality":0,"latency":0,"bandwidth":0}}}
may 12 11:07:38 juanjo-ubuntu myst[4216]: 2022-05-12T11:07:38.870 DBG communication/nats/sender.go:59 > Message "signed.gWUz6tl_lGXmRANhnEEi0WSnA62hz2BPtX8Qbefsnr9kSvyCuKKk_9muXYScqETM2vwDg9fdrAwTXH0B5soB9wE.1652368058.*.proposal-ping.v3" sending: {"proposal":{"id":0,"format":"service-proposal/v3","compatibility":2,"provider_id":"0x841c19c5f6e5a3d4fd7042a0b23525ad219cae9f","service_type":"wireguard","location":{"continent":"SA","country":"CL","city":"Santiago Metropolitan","asn":27901,"isp":"Mundo Chile","ip_type":"residential"},"contacts":[{"type":"nats/p2p/v1","definition":{"broker_addresses":["nats://broker.mysterium.network:4222","nats://broker.mysterium.network:4222","nats://[51.15.116.186:4222](http://51.15.116.186:4222/)","nats://[51.15.72.87:4222](http://51.15.72.87:4222/)"]}}],"quality":{"quality":0,"latency":0,"bandwidth":0}}}

**Environment (please complete the following information):**
 - Node version: mainnet 16.9-5a512e40
 - OS: Ubuntu 22.04 LTS
 - Your identity (if applicable): 0x841c19c5f6e5a3d4fd7042a0b23525ad219cae9f
 - Payment (top-op) reference (if applicable): 
 - Node Status: Test Failed

**Additional context**
N/A

**Comment by juanjogonzalez** [comment]
It seems to me that the problem occurs when there is a change in the public IP. I have another node running on the same network, but with Alpine Linux v3.14(docker) on a macbook, and that node in the mystnodes.com node list shows up with a different IP than the public one, however it is up and broadcasting.

**Comment by etherunit** [comment]
It's clear that your node was working fine, but starting 05/12 it stopped operating normally. Please submit full node logs to us for further investigation.
In the meantime, check if Wireguard service is enabled in UI or terminal:`sudo systemctl restart mysterium-node.service`

**Comment by etherunit** [comment]
After initiating several manual node checks, the status switched to online.
https://discovery.mysterium.network/api/v3/proposals?provider_id=0x841c19c5f6e5a3d4fd7042a0b23525ad219cae9f
Node speedtest below:
```
Server: Transtelco - Santiago de Chile (id = 44270)
        ISP: Mundo Chile
    Latency:   245.75 ms   (41.05 ms jitter)
   Download:    86.38 Mbps (data used: 142.8 MB)
     Upload:    55.36 Mbps (data used: 77.1 MB)
Packet Loss:     0.0%
 Result URL: https://www.speedtest.net/result/c/c085d33d-8f30-42c3-ad0f-5321d02c62bf
```
