### ISSUE TITLE
Node UI balance different than mystnodes.com balance

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5121]
Description:

Node UI balance is less than https://mystnodes.com/nodes balance for this node.

Logs:

https://mystnodes.com/support/logs/2022-05-12-2e129d48-1061-4b30-aea3-085f7a483446-mysterium-node.zip2611648095

<img width="1071" alt="Screenshot 2022-05-14 at 21 01 28" src="https://user-images.githubusercontent.com/84313603/168451866-e1603626-7b1d-43d2-a4b2-74244e794f48.png">
<img width="1239" alt="Screenshot 2022-05-14 at 21 02 03" src="https://user-images.githubusercontent.com/84313603/168451889-c0585c8e-a6c7-44f9-be9f-b7909fec165c.png">

**Comment by tomasmik** [comment]
When you get balance from different sources in two different places, this is sort of only natural.

**Comment by isaackielma** [comment]
@tomasmik Not sure. At least on my nodes it has always shown same balance on both node UI and Mystnodes.com.

**Comment by tomasmik** [comment]
I would suspect something like that or some cache issue where balanced on web-ui is not updated.

**Comment by kishfox** [comment]
The balance on the web UI updates in real time according to the incoming connections, and that leads me to not believe the idea of it being a cache issue there. 

In addition, the issue is not reflecting the total balance, but the specific balance for the node per the node's UI and the [mysteriumnodes.com](https://mystnodes.com/nodes) page, @tomasmik

**Comment by kishfox** [comment]
@tomasmik  not to mention the payout did not occur until the NodeUI balance reached 5.0 MYST, thus revealing the NodeUI as the true and accurate balance.

**Comment by tomasmik** [comment]
I have assigned the issue to @Ayse-AK . Seems like mystnodes lies about balance sometimes.

**Comment by mdomasevicius** [comment]
This will be covered with NodeUI 2.0
