### ISSUE TITLE
lost 24 MYST unsettled tokens upon node update

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5122]
While upgrading my node to the new version, I lost 24 MYST unsettled tokens. While upgrading I took a backup, of the ".mysterium-node" folder and upgraded using the following command.

docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v D:\miner-apps-installed\mysterium:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions.

But unfortunately, it was asking for new node registration. So I paid another .21 MYST to register. But surprisingly it was not activated for the existing node: 0xbc18f0abdd8fe6f535990e909e7623fbc41d468a
Instead, it was registered with new identity: 0x51fabcdd38816c0faac68906d72e43eb695048d7
Actually, before upgrading, I tried to settle the 24 unsettled tokens. But after waiting for more than 30 minutes. It never got settled. So I have only withdrawn the existing settled amount of 24 MYST tokens and started the upgrade process.

Now I lost 24 MYST tokens. Please help recover those other 24 MYST tokens.
attaching screenshots for the same.

My details:
Withdrawal address: 0x7eE68f4ae94CED8FC7e69f795fD5782484Ff656F

<img width="1403" alt="Screenshot 2022-05-15 at 14 50 58" src="https://user-images.githubusercontent.com/84313603/168486847-52075d1f-201e-490b-b6d5-5a9b0f83bdaa.png">

**Comment by isaackielma** [comment]
Waiting on logs for further investigation

**Comment by Guillembonet** [comment]
you cannot settle because you need to enable auto-withdrawals. For that, you need to upgrade the node. The myst have been withdrawn here https://polygonscan.com/tx/0x2c81e35ad3546fef0acb9174ef4ba4d6c46b03d9ebef98f9207b0b9e42439a8e
I'm not entirely sure about if the command for docker run's volumes is correct and maybe that's why it wasn't mounted properly.

**Comment by isaackielma** [comment]
these subtle differences are following:

- that myst-data is a named volume which is autocreated when container runs. we can say it is isolated from HOST system

- if you use bind-mount to real path as in your case instead of that ephemeral named volume, directory in the container will be backed by filesystem on host OS. on Linux it will work just fine. on Windows it will work through some sort of translation layer which replicates behavior of normal filesystem only partially.

so our node may have hard times working on such filesystem mounted to directory on Windows, in general we don't support such configuration. 

Could you please let us know what specific error which arises upon running such command?
