### ISSUE TITLE
Not able to conclude initial set up on Raspberry PI

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5123]
I plugged in the sd card and then powered up and connected it direct to my router. there is a steady red light (which I think indicates power?) and a green light intermittently flashes (or at least it was when first powered up).

I've logged in to my home router and it should appear at port 3, but nothing showing after 15 minutes...please help!

I think I should be ok with the rest of the onboarding once I can get it visible on my network and see the device IP, but I can't figure out how to get
<img width="985" alt="Screenshot 2022-05-15 at 15 06 10" src="https://user-images.githubusercontent.com/84313603/168487452-bb3f56b0-6580-4276-b5a0-3040f8bc7f03.png">

**Comment by etherunit** [comment]
Please follow (last comment): https://discourse.mozilla.org/t/start4-elf-is-not-compatible-this-board-requires-newer-software/94783

This is a known issue that's been affecting lots of users recently. I think the most recent Pi4 boards require a newer firmware that's no longer compatible with the official Pi4 image which is over a year old at this point.

Use the automatic weekly build from https://files.retropie.org.uk/images/weekly/, that one should work for you.
