### ISSUE TITLE
my coin send auto settlement to empty wallet

### ISSUE THREAD

**Issue by hishamaw** [mysteriumnetwork/node#5124]
my coin gets sent by node using the auto settlement to an empty wallet

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1] Node version: mainnet (1.6.9-5a512e40)
NodeUI version: 1.13.0
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A] 0xeb223555cb7808f8f97b7c4d3c14144aaadc14b0
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
Add any other context about the 
![MYST auto settlement error](https://user-images.githubusercontent.com/101164451/168494050-a4f940a9-b6dc-4419-ba05-2be4f44ba759.jpg)
problem here.

**Comment by Guillembonet** [comment]
https://polygonscan.com/tx/0xef48e8b0742ee1d27929ffb8109c895ae102abaee2523b212987e8c19f40c912 looks like a bug in UI, the MYST is sent to the same address as the others

**Comment by hishamaw** [comment]
I didn't find transaction history in the wallet so I thought the coin disappear.

after I check transaction details I find out it goes to the wallet.

thank God it UI problem only thank you for your time and support

**Comment by tomasmik** [comment]
I reopened the issue for further investigation as even if its a UI problem it needs to be solved

**Comment by hishamaw** [comment]
if you need anything from my side i will support you

**Comment by hishamaw** [comment]
Node version: mainnet (1.6.9-5a512e40)
NodeUI version: 1.13.0

windows version
Node version installed: 1.6.9-alpine

docker desktop version 4.5.1 (74721)

**Comment by tomasmik** [comment]
After further investigation this indeed seems like a UI issue as all data is written on node side.
