### ISSUE TITLE
deb package not found

### ISSUE THREAD

**Issue by hrm6592** [mysteriumnetwork/node#5125]
**Describe the bug**
Installation procedure describe in portal site seems some problems.

**Problems**
- Portal site is outdated.
  https://mystnodes.com/onboarding/datacenter/0
  says 
  ```sudo add-apt-repository ppa:mysteriumnetwork/node```
  This command add following line to /etc/sources.list.d/mysteriumnetwork-ubuntu-node-kinetic.list
  ```
  deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu kinetic main
  # deb-src http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu kinetic main
  ```
  "kinetic" is not found in http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu/dists/
  So,
  ```sudo apt-get update```
  failed on error.

Anyway, I was able to install myst-node described in github method.

**Comment by etherunit** [comment]
![Screenshot 2022-05-16 at 09 40 03](https://user-images.githubusercontent.com/60128746/168533712-90c01640-0442-4dd4-9cb0-4a486e4aa6a1.png)
