### ISSUE TITLE
Unable to claim node "Failed to register to MMN"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5126]
Error when I trying to register node to the Mysterium Nodes API via the API key in the NodeUI: "Failed to register to MMN".

Although the node can be found in the consumer app and it is connectable, it cannot be claimed due to error.

<img width="635" alt="Screenshot 2022-05-16 at 17 56 34" src="https://user-images.githubusercontent.com/84313603/168681498-5e9e1f9f-e16e-4460-9942-f379412ca50a.png">
<img width="634" alt="Screenshot 2022-05-16 at 17 59 11" src="https://user-images.githubusercontent.com/84313603/168681807-3d050dc7-9170-47ec-8a3c-2d81aea0ba79.png">
<img width="565" alt="Screenshot 2022-05-16 at 23 29 07" src="https://user-images.githubusercontent.com/84313603/168716187-f30129ab-8382-4d90-b142-2f81d53dee10.png">

Logs:

https://mystnodes.com/support/logs/2022-05-16-13830e0e-b9ba-45bb-8090-899fd7a0a469-mysterium-node.zip1326219315

**Comment by tomasmik** [comment]
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/8707860/mysterium-node.log)

Snipped a section of logs which are important in this case. Seems like we are asking for an api call to complete a capcha??
