### ISSUE TITLE
Auto withdrawal enabled sent to wrong beneficiary address

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5129]
Auto withdrawal enabled and according to the user, address was properly updated to user's metamask wallet. For some reason on 5/5 and 4/19 it was sent to identity address which is a trust wallet and those coins were lost forever. Not certain why auto withdrawal would send it to identity address even though it was set up to send to meta mask address.

<img width="1299" alt="Screenshot 2022-05-17 at 11 46 35" src="https://user-images.githubusercontent.com/84313603/168840830-525bea1b-c184-4cb2-b64e-4b3bf5efb0d1.png">
<img width="1296" alt="Screenshot 2022-05-17 at 11 47 05" src="https://user-images.githubusercontent.com/84313603/168840853-8451697e-dff7-4440-88ff-0703f89391fd.png">
<img width="1288" alt="Screenshot 2022-05-17 at 11 48 19" src="https://user-images.githubusercontent.com/84313603/168840856-ac074b9c-42f1-47a4-b872-0a30741ce9cf.png">

Logs:

https://mystnodes.com/support/logs/2022-05-17-d8c3fd8f-12af-4e42-b4ca-6b664feb1d7d-mysterium-node.zip177130039

**Comment by etherunit** [comment]
Yes, it looks like the same UI display glitch. Money is being sent to an "empty" wallet.

**Comment by isaackielma** [comment]
These are the three in question:

0xdae4c8aa1e410884b49ae36197c44efcde17f7a9fea9aa22afedcea41cc17eb8

0x07d2aa57aa36cb70c0051f7f428f41ef8747a71d561f4d854ce95f802a9e766e

0xcb247239ea809c4a17aca1c3c427cec4cf9d1ba78c5272ff96d481c6d2a2b0f8

**Comment by isaackielma** [comment]
Here are the meta mask wallet tx urls. https://polygonscan.com/tx/0xbd71a61e82d7c2f763e8542f36ab558b890b23407a4565a69ceea435810ac2ae



Here is one from the wrong trust wallet address. https://polygonscan.com/tx/0xe76a19a5d11966430b1bdc927304a5806d27cf6a8b656164a2176a8fa80c95b7

**Comment by tomasmik** [comment]
This has been fixed: https://github.com/mysteriumnetwork/node/pull/5134
