### ISSUE TITLE
Node Status: Test Failed

### ISSUE THREAD

**Issue by juanjogonzalez** [mysteriumnetwork/node#5141]
**Describe the bug**
I haven't been able to run the node for 2 days and it seems that it was due to the update made by the docker

**To Reproduce**

**Expected behavior**
N/A

**Screenshots**
<img width="943" alt="image" src="https://user-images.githubusercontent.com/24239700/169623459-67d8d7ed-5674-4572-a50c-d375eaaf56e9.png">

**Environment (please complete the following information):**
 - Node version: mainnet (1.6.9-5a512e40)
 - OS: macOS Monterrey
 - Desktop app version (if applicable): 1.6.11-alpine
 - Docker (if applicable): Docker Engine v20.10.1.  Image ID: 624a8bc516fb, TAG: latest
 - Your identity (if applicable): 0xb7c436d088d39131dbb5e28c0d8970682d8ff158
 - Payment (top-op) reference (if applicable):

**Additional context**
LOGS
[logMystERR.log](https://github.com/mysteriumnetwork/node/files/8745857/logMystERR.log)

**Comment by etherunit** [comment]
It seems that your docker container is not available anymore. Could you please switch it on so we'll continue looking into it?
