### ISSUE TITLE
Fail to get current location

### ISSUE THREAD

**Issue by juanjogonzalez** [mysteriumnetwork/node#5152]
**Describe the bug**
In the list of nodes the option "Last seen" appears in "never" and it is not sending sessions or data

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24239700/170735660-cb532dfe-363b-4188-8955-4b59ac74c8b6.png)
<img width="891" alt="image" src="https://user-images.githubusercontent.com/24239700/170735827-4aee377d-feb7-465c-aa8a-0ba7e2c7cfed.png">

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: Alpine Linux v3.14(docker) in MacOS Monterrey version 12.1
 - Desktop app version (if applicable): 1..6.11-alpine
 - Docker (if applicable): Docker version 20.10.14, build a224086, Tag ImageID: 9c3c1c724352 
 - Your identity (if applicable): 0x43decb4372fa19e23306f2cd92d2a9c002a669ed
 - Payment (top-op) reference (if applicable): 

**Additional context**

2022-05-27T12:59:59.033 WRN ../../core/service/pool.go:182                 > Failed to get current location for proposal, using last known location error="failed to execute request: Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

Similar bug but other operating system:
https://github.com/mysteriumnetwork/node/issues/3735

**Comment by etherunit** [comment]
Mysterium Network do not support multiple devices under a single IP address. Having multiple nodes will likely to affect your internet connection quality as well as reduce service stability thus making a negative impact on the network itself.

Each node must be linked to a different residential IP address, so unless you have multiple routers, each with their own IP and node linked to it, it's not possible.

Node operators running multiple nodes under the same IP address won't be able to propogate their service proposals (1st proposal claimed some IP will be promoted to discovery only, others tied to the same IP address will be offline).
