### ISSUE TITLE
debian repository

### ISSUE THREAD

**Issue by stutteringp0et** [mysteriumnetwork/node#5156]
**Describe the bug**
1.7.0 has been out for 2 days, but it does not exist in either of the deb repos

**To Reproduce**

**Expected behavior**

**Screenshots**
myst/focal,focal,now 1.6.11+build541187968+focal amd64 [installed]
  Mysterium Node - VPN server and client for Mysterium Network

**Environment (please complete the following information):**

**Additional context**

**Comment by stutteringp0et** [comment]
3 days, no apt repo updates

**Comment by etherunit** [comment]
The build of the 1.7.0 has failed, that is why it’s missing. Team will fix it as soon as possible.
