### ISSUE TITLE
Payments should work even if local database is deleted

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#5157]
Right now we rely on the local database during settlements. We need to check what happens if that database is deleted after we've earned some amount of money.
* [x] Is the node able to settle the money earned even if the database is deleted
* [x] Are the earnings shown correctly in the node ui
* [x] Can we recover the missing data
  * [x] Does consumer connecting from the same hermes, recovery everything that we need?
  * [x] Can we somehow detect database corruption and recovery using hermes/blockchain?

**Comment by n10ty** [comment]
Done
