### ISSUE TITLE
missing myst/transactions

### ISSUE THREAD

**Issue by stutteringp0et** [mysteriumnetwork/node#5167]
**Describe the bug**
My Node UI shows total earnings of 6.45 Myst, Unsettled earnings of 0.12 Myst, but the node wallet shows 0 transactions.  I seem to be missing 6.33 Myst.

**To Reproduce**
Node ID: 0x0465422ac98f41d5a4db676ca2106cfebd96af9b
Metamask wallet: 0x5a0e68bF95ed0575f8480195fFf91161CF0C9F2b

**Expected behavior**
a transaction detailing where the myst was transferred to

**Screenshots**
![image](https://user-images.githubusercontent.com/310899/172017524-fe1ee2a8-b3aa-4f41-82e6-aa0b5e789135.png)
![image](https://user-images.githubusercontent.com/310899/172017527-db836923-20c3-4436-aa4f-def4334e4efe.png)

**Environment (please complete the following information):**
 - Node version: 1.7.1
 - OS: Ubuntu 20.04
 - Your identity (if applicable): 0x0465422ac98f41d5a4db676ca2106cfebd96af9b

**Additional context**
At present there are 209 pages of session logs.

**Comment by stutteringp0et** [comment]
no change in 1.8.0, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.8.1, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.9.1, myst is still missing

**Comment by stutteringp0et** [comment]
It also appears that auto settlement doesn't work
<img width="228" alt="image" src="https://user-images.githubusercontent.com/310899/174425881-104cabce-0a2c-43be-a3b5-8a974438eba6.png">

**Comment by etherunit** [comment]
@Guillembonet Could you please take a look into this one? Thanks

**Comment by stutteringp0et** [comment]
Auto-settlement finally happened sometime last night.  So I guess it happens sometime after you hit 5 myst...whatever.

The primary issue remains.  

Total myst earned for this node is 17.95, minus 3 settlements and 3 network fees of 
1.0209990 MYST
3.9790397 MYST
1.0130902 MYST
3.9829377 MYST
0.3002954 MYST
1.1328021 MYST

That leaves 7.9539344 myst unaccounted for.  I understand these numbers are truncated for display purposes, but hundred-millionths of a myst in 3 transactions don't add up to 7.953...

**Comment by stutteringp0et** [comment]
no change in 1.9.2, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.9.3, myst is still missing

**Comment by stutteringp0et** [comment]
I guess auto-settlement stopped working.  It's been over 5 for a couple of days now.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/310899/177013372-342cad34-ff18-4463-853b-aae3a9b2ddf9.png">

**Comment by stutteringp0et** [comment]
no change in 1.9.4, myst is still missing

**Comment by etherunit** [comment]
@stutteringp0et Apologies for a delayed reply. I have informed our payments team to look into this.

**Comment by stutteringp0et** [comment]
I'll keep updating

**Comment by stutteringp0et** [comment]
no change in 1.9.5, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.9.6, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.10.0, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.11.1,  myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.12.0, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.12.1, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.12.2, myst is still missing

**Comment by stutteringp0et** [comment]
no change in 1.14.0, myst is still missing

Additionally, I have 3 nodes with balances above 5 myst for several days which have not auto-settled.  This seems to happen quite often.

**Comment by etherunit** [comment]
@stutteringp0et It looks like the missing MYST won't re-appear in your balance. The easiest way to fix it is to reimburse your losses manually. Please provide us with your wallet address (Polygon compatible) or identity channel to proceed.

**Comment by stutteringp0et** [comment]
I was hoping more for an identification of the issue that caused the myst to go missing in the first place.  The idea that a crypto transaction can occur without a record within the blockchain is concerning - because, isn't that the point of blockchain transactions in the first place?  

Closing this issue without resolution is sweeping a pretty major deficiency of this crypto under-the-rug.

The losses are negligible, I mean - what 7 myst is like $2 now...if that.  I don't care about $2 - I'm more worried about the stability and utility of a coin that loses transactions and if it's wise to use my hardware to support such a system.

**Comment by stutteringp0et** [comment]
Yeah, nevermind - I'm removing your application from my infrastructure (21 nodes in 11 countries) and cashing out.  Good luck with your blockchain that loses transactions.
