### ISSUE TITLE
installation on Debian 10

### ISSUE THREAD

**Issue by m1000rr** [mysteriumnetwork/node#5168]
Installation is failing on debian 10 with the following errors:
`Err:10 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu kinetic Release
  404  Not Found [IP: 185.125.190.52 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`
Any fix?

**Comment by etherunit** [comment]
Ubuntu 22.10 “Kinetic Kudu” Is Slated for Release on October 20th, 2022. Following the release of Ubuntu 22.04 LTS “Jammy Jellyfish”, the Ubuntu team is now focusing their efforts on the next major release of their Debian-based GNU/Linux distribution, Ubuntu 22.10 “Kinetic Kudu”.
