### ISSUE TITLE
Node failing test and not able to maintain connections

### ISSUE THREAD

**Issue by mightybuddha** [mysteriumnetwork/node#5171]
Hello, 

I am a complete noob at this, so any advice or help will be greatly appreciated.

I am running a mysterium node on a raspberry pi at home. It initially worked without problems for a couple of days, and then it suddenly stopped. Although connections to it are still established (as per dashboard) the are never longer than a minute with a very few kbs of data transferred. 

Attached you can find the log file of the mysterium node. 

**Screenshots**
![image](https://user-images.githubusercontent.com/106952598/172114214-25a8d869-b882-4e2e-8659-fd78e9a91f10.png)

![image](https://user-images.githubusercontent.com/106952598/172114258-2c51d607-9a57-4c04-83af-7e22751c7636.png)

**Environment (please complete the following information):**
 - Node version: 1.7.1
 - OS: Debian GNU 11 (bullseye)
 - Your identity: 0x24e471a0fe17d0153eaa69681868fa39e462d504

Log file:
[mysterium_001.log](https://github.com/mysteriumnetwork/node/files/8842529/mysterium_001.log)

**Comment by etherunit** [comment]
First thin to try, SSH into your raspberry pi and execute `sudo reboot`

**Comment by mightybuddha** [comment]
Did that, but to no avail.

**Comment by mightybuddha** [comment]
> First thin to try, SSH into your raspberry pi and execute `sudo reboot`

Any other possible resolutions stemming from the log file?

**Comment by etherunit** [comment]
Please note that test failed status has been successfully cleared.
<img width="773" alt="Screenshot 2022-06-08 at 09 08 16" src="https://user-images.githubusercontent.com/60128746/172543876-e1571ff8-de41-49d0-b62c-ed7c99e123fa.png">
Node is online and connectable: https://discovery.mysterium.network/api/v3/proposals?provider_id=0x24e471a0fe17d0153eaa69681868fa39e462d504
```
» status
[INFO] Status:Connected
[INFO] SID:76c195a7-9e22-4256-9b39-3941f4d7ea5d
[INFO] Location: Limburg, NL (residential - T-Mobile Netherlands B.V.)
[INFO] Proposal:Provider: 0x24e471a0fe17d0153eaa69681868fa39e462d504, ServiceType: wireguard, Country: NL
[INFO] Connection duration: 23s
[INFO] Data: 158.5KiB/122.6KiB
[INFO] Throughput: 1.9KiBs/3.6KiBs
[INFO] Spent: 0.000000
» disconnect
[SUCCESS] Disconnected.
```
