### ISSUE TITLE
0 bytes sessions

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5177]
Many connections but all the time with 0 bytes or 00:00:00 and 00:00:01 seconds, is something is wrong in the configuration of the node:

» service list
[Running] ID: 84239a94-be1c-439c-ba98-1dd66ac54845 ProviderID: 0xcbe0634360370fa18e9e3c2cc2342476a5efd6db Type: wireguard

» healthcheck
[INFO] Uptime: 86h30m53.680553846s
[INFO] Process: 2699
[INFO] Version: 1.7.1
[INFO] Branch: 1.7.1. Build id: 550906843. Commit: 343fc50d
» nat
[INFO] Node Monitoring Status: "pending"
[INFO] NAT type:Port Restricted Cone

Here is the information provided by chat also, where was requested to create this issue and attach the logs.

Logs:

https://mystnodes.com/support/logs/2022-06-08-76658288-2599-4998-937f-67a558af7770-mysterium-node.zip354144426

**Comment by etherunit** [comment]
After initiating manual checks - "connection_failed" status has been cleared out. 
It's available in discovery now: https://discovery.mysterium.network/api/v3/proposals?provider_id=0xcbe0634360370fa18e9e3c2cc2342476a5efd6db
Tested, it's connectable and working fine.
Speedtest results:
 Server: TELECABLE FIBRA S.L.U. - Santa Pola (id = 25386)
        ISP: Vodafone Spain
    Latency:    87.85 ms   (1.22 ms jitter)
   Download:    39.15 Mbps (data used: 39.1 MB)
     Upload:    21.57 Mbps (data used: 37.6 MB)
Packet Loss: Not available.
 Result URL: https://www.speedtest.net/result/c/9ec05038-5eda-4cae-ba3f-dbb8a4e1ee4c

**Comment by etherunit** [comment]
![Screenshot 2022-06-10 at 09 08 16](https://user-images.githubusercontent.com/60128746/173002083-9d955d84-3810-46c0-9970-097c36c2379d.png)

**Comment by ideaalab** [comment]
Hey, how did you solve this? Im having the same problem :(

**Comment by etherunit** [comment]
Provide us with your node identity @ideaalab.
The only thing we did is manually requested checking your node service.

**Comment by ideaalab** [comment]
0x02811264d298cb89b527af19b2eec1fea1501346

**Comment by ecorrech** [comment]
same problem, can you check my node?

0xef56a096cc1efab26a69e18fac2c1fcdacfc30d5

thanks

**Comment by Ragazzo50** [comment]
Please,
0x04421b6175f4e68ec9e594ba30a9b11998277e45
Thanks

**Comment by ideaalab** [comment]
I wouldnt say that 0 byte sessions are solved...
