### ISSUE TITLE
Node not online on Mystnodes

### ISSUE THREAD

**Issue by yashraj-n** [mysteriumnetwork/node#5180]
I have a Ubuntu server running Mysterium Node version 1.7.1-343fc50d). Its been more than 3 days since I started the service, yet Mystnodes is showing my node offline

1. Start the Mysterium node

**Expected behavior**
Expected the node to be online on mystnodes.com

**Screenshots**
![myst nodes screenshot](https://cosii.reeee.ee/5yztIeWQP.png)

**Environment (please complete the following information):**
 - Node version: mainnet (1.7.1-343fc50d)
 - NodeUI version: 1.15.0
 -  OS: Ubuntu 18.04.6 LTS x86_64
 - Identity: 0xcbf6115cb3014248fd97677c5b4cbd6114585db0

**Comment by adinetech** [comment]
0xcbf6115cb3014248fd97677c5b4cbd6114585db0 is not available in the Discovery API.
Please confirm whether you're running more than a node using the same IP address.

**Comment by etherunit** [comment]
In this case it's not related to a single IP limitation. 
Registration succeeded: https://transactor.mysterium.network/api/v1/identity/0xcbf6115cb3014248fd97677c5b4cbd6114585db0/status
But any further operations have failed. 

Can you check if node service is active? Run in terminal:`sudo systemctl status mysterium-node.service`
Is there any chance to extract node logs for further analysis?
