### ISSUE TITLE
DNS Issue with Mysterium in Docker Container.

### ISSUE THREAD

**Issue by CookieCr2nk** [mysteriumnetwork/node#5182]
**Describe the bug**

When i start the Mysterium Docker Container with my docker-compose everything is working fine, but DNS resultion to location.mysterium.networks and another Domain fails. As Troubleshooting step i also set a custom DNS in my docker-compose file. Also as a Troubleshooting i can say, that DNS in the Container is working, because i can use "ping location.mysterium.network"  in the container without problems. Is it a Application Bug?

![image](https://user-images.githubusercontent.com/38990807/173114978-68d2a871-2e0c-46f8-8b1f-d23031ff8fef.png)

```
//broker.mysterium.network:4222","nats://broker.mysterium.network:4222","nats://51.15.116.186:4222","nats://51.15.72.87:4222"]}}],"quality":{"quality":0,"latency":0,"bandwidth":0}}}
mysterium-node    | 2022-06-10T16:52:05.509 WRN ../../requests/dialer_swarm.go:293             > Failed to lookup host: "location.mysterium.network" error="lookup location.mysterium.network on 1.1.1.1:53: dial udp 1.1.1.1:53: operation was canceled"
mysterium-node    | 2022-06-10T16:52:05.509 WRN ../../requests/dialer_swarm.go:293             > Failed to lookup host: "pilvytis.mysterium.network" error="lookup pilvytis.mysterium.network on 1.1.1.1:53: dial udp 1.1.1.1:53: operation was canceled"
```

**To Reproduce**
1. Start the Container with docker-compose up -d

**Expected behavior**
I expect that DNS Resolution is working proberly.

**Environment (please complete the following information):**
 - Node version: 1.16.2
 - OS: Debian 11.3 with LXC on a Proxmox Host
 - Docker (if applicable): 20.10.17
 - Your identity (if applicable): 0x6e4590d09081d15c73359a5a366e645e28e5d330
 - Payment (top-op) reference (if applicable):

```
version: "3.0"
services:
  mysterium-node:
    image: mysteriumnetwork/myst:latest
    restart: always
    container_name: mysterium-node
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./myst-data:/var/lib/mysterium-node
    command:
      - service --agreed-terms-and-conditions
    network_mode: "host"
    dns:
      - 1.1.1.1
      - ```

**Comment by etherunit** [comment]
@CookieCr2nk Can you specify the exact problem here? 
`WRN` in the log output has no real impact on the node, it doesn't break anything.

**Comment by etherunit** [comment]
DNS resolution works via provider:

```
raspberrypi-2:~ andzejuskorkuzas$ dig delfi.lt @10.182.0.1

; <<>> DiG 9.10.6 <<>> delfi.lt @10.182.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23643
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;delfi.lt.			IN	A

;; ANSWER SECTION:
delfi.lt.		600	IN	A	91.234.200.114
delfi.lt.		600	IN	A	91.234.200.110
delfi.lt.		600	IN	A	91.234.200.111
delfi.lt.		600	IN	A	91.234.200.112
delfi.lt.		600	IN	A	91.234.200.113

;; Query time: 81 msec
;; SERVER: 10.182.0.1#53(10.182.0.1)
;; WHEN: Mon Jun 13 10:49:16 EEST 2022
;; MSG SIZE  rcvd: 157
```

But internet fails:

```
raspberrypi-2:~ andzejuskorkuzas$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
^C
--- 8.8.8.8 ping statistics ---
26 packets transmitted, 0 packets received, 100.0% packet loss
```

`OS: Debian 11.3 with LXC on a Proxmox Host`

I suspect there is a permission issue setting ip tables forwarding rules since you are using container in container.

**Comment by CookieCr2nk** [comment]
Hello @etherunit ,

I tested it on a KVM Virtual Machine with Debian 11 as distro, but there's the same effect.

What i did:

1. create a the same docker-compose.yml file on the new KVM Host.
2. Start Node and stopped it immidiatly
3.  Replace Keystore
4. Start docker-compose.yml again.

```
mysterium-node    | 2022-06-13T19:58:53.971 DBG ../../eventbus/event_bus.go:101                > Published topic="NAT-type-detected" event=prcone
mysterium-node    | 2022-06-13T19:58:56.730 WRN ../../requests/dialer_swarm.go:293             > Failed to lookup host: "location.mysterium.network" error="lookup location.mysterium.network on 1.1.1.1:53: dial udp 1.1.1.1:53: operation was canceled"
```

**Comment by CookieCr2nk** [comment]
My Node identity is: 0x6e4590d09081d15c73359a5a366e645e28e5d330 But does the Node identity does a difference?

**Comment by etherunit** [comment]
Have you done any specific changes to your node? All subsequent connection tests resulted in failure:
`2022-06-16T11:32:50.419 ERR ../../../../source/tequilapi/endpoints/connection.go:203 > Failed to connect error="could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built"`

**Comment by CookieCr2nk** [comment]
Sry my bad, i shut it down, because i want to test something. I noticed also, that when someone is connected i see"
mysterium-node    | 2022-06-16T16:11:13.267 ERR ../../core/service/session_manager.go:388      > Failed to send p2p keepalive ping. SessionID=7ee41ef0-2199-470b-9e7c-ee687c2f8034 error="timeout waiting for reply to \"p2p-keepalive\": p2p send timeout" in the log. Can you try to connect to my node again?


![image](https://user-images.githubusercontent.com/38990807/174116603-858c8b07-57d6-48fe-9d9c-9f1a19690778.png)


![image](https://user-images.githubusercontent.com/38990807/174116656-152ad4dd-b997-4004-bbba-1ba9293a1575.png)

**Comment by CookieCr2nk** [comment]
Also interesting what i saw at debugging is following error message. Is that releveant?

![image](https://user-images.githubusercontent.com/38990807/174503248-924ccd45-d4b0-4c09-8dc2-992a64d1dc8b.png)
