### ISSUE TITLE
dVPN app "Oops, could not connect - too few connections were built"

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5183]
**Describe the bug**
1. Our dVPN app by default uses automatic NAT type detection to filter out an incompatible providers. It should increase user' chances of successfully connecting to provider nodes. The thing is that it's always an assumption what nodes will be connectable and therefore we cannot guarantee 100% accuracy.
However, it converts into the problem for some consumers sitting behind more restricted networks. Note that I'm excluding cases when consumer is not be able to use our network at all because his ISP is blocking UDP traffic and we have nothing to do about it.
So, after successfully topping up their channels and trying to establish a connection it leads to the following output:
<img width="588" alt="Screenshot 2022-06-10 at 13 42 21" src="https://user-images.githubusercontent.com/60128746/173327100-29b49530-489f-4b53-927c-d5cbe4a99677.png">

Mulitiple attempts to connect to the random max quality rated providers fails at this point and app become unusable.
Long time ago we were planning to add some UI with automated checks what is working for user and what is not, but we never started it.

2. Add extra info to the output; "I" icon with link to docs explaining the origin of the issue, why it happened and how to avoid that; Current error messages with no extra details are too complicated to the user.

**Expected behavior**
VPN connection could be established after balance is filled with tokens.

**Environment (please complete the following information):**
 - Node version: latest
 - OS: Windows/Mac/Android

**Comment by Donatas-MN** [comment]
Both mobile and desktop apps have NAT detection type checkbox:
![image](https://user-images.githubusercontent.com/91055712/176186206-aeacfe3c-fa81-4630-9577-11b31ebf272b.png)

By default it's off, so users see unfiltered list. It should probably turned ON by default.

**Comment by Donatas-MN** [comment]
Task to fix this: https://github.com/mysteriumnetwork/node/issues/5251
