### ISSUE TITLE
Mystnodes.com returns Connection failed as Status.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5184]
**Describe the bug**
Mystnodes.com returns Connection failed as Node Status and Earnings (last 30 days) shows as 0 MYST.

**To Reproduce**
Check mystnodes.com

**Expected behavior**
It should show as online, as the node shows up in the discovery API and shows online in the Node UI.

**Screenshots**
<img width="933" alt="image" src="https://user-images.githubusercontent.com/68943180/173359021-8d59fc20-636d-4178-99e0-5223ece28ae6.png">

**Environment:**
 - Node version: 1.7.1

**Comment by etherunit** [comment]
@adinetech I think it's fixed.

**Comment by adinetech** [comment]
Yes, it is fixed, and closing this issue.
