### ISSUE TITLE
Connection Failed using Controllino Hotspot

### ISSUE THREAD

**Issue by Jbt8** [mysteriumnetwork/node#5195]
Hello, I am using a Controllino hotspot to run Mysterium node and It seemed to wok ok for a few days. Now it is showing "Connection failed". I have enabled PnP and disabled it. I have restarted my hotspot and no luck. I've also tried various settings, UPNP, Man, Punch through, etc....Please help. Thanks.

**Comment by etherunit** [comment]
Currently, Mysterium Network has no official support to cover Controllino IoT gateway's Helium mining capabilities with node service. Research towards technical compatibility, configuration and more testing is required.

**Comment by Jbt8** [comment]
Hello, I contacted Controllino regarding the "Connection Failed issue. They
asked me if I had a static ip address for my device, which I do. I also
port fwd to 44158. I also have NAT Traversal enabled and UPnP enabled as
well. My current configuration is UPnP, holepuching, then Manual.

I was advised to contact you guys again and state that I need support for
myst on a raspberry as indicated on the below cut/paste email from
Controllino.

Okay, when you call myst support, ask for myst on a raspberry, not on a
controllino.

Viele Grüße / Best regards
Tobias

**Comment by etherunit** [comment]
@Jbt8 Currently, our team is testing their solution and preparing a set of guides/troubleshooting KB for the users. Please follow our documentation page to find out more. 
https://docs.mysterium.network/
