### ISSUE TITLE
0 byte connections on Synology

### ISSUE THREAD

**Issue by ideaalab** [mysteriumnetwork/node#5203]
**Bug**
Node is online and accepting most connections. No apparent errors, but hundreds of connections, all are less than 1 second and 0 bytes.

**Screenshots**
![image](https://user-images.githubusercontent.com/25922675/173779308-84168b50-1a41-4b36-a6ce-8bb2d631d11a.png)

**Environment**
 - Node version: mainnet (1.7.1-343fc50d)
 - NodeUI version: 1.15.0
 - System: Synology DS720+
 - OS: DSM 7.1-42661 Update 2
 - Docker: 20.10.3-1306
 - Your identity: 0x02811264d298cb89b527af19b2eec1fea1501346
 - Router opened ports: 59850:60000 UDP forwarded to the Synology IP

**Additional context**
Ports 4449/TCP and 59850:60000/UDP are opened on the Docker container.
Ive tried to find support on discord channels, but I was pointed to report a bug here as its a known issue that nodes on Synology may not work.
There are thousands of Synology NAS out there. Being able to use them to host a Mysterium node would allow the network to expand easily.
Im new here, but if I can help doing some test please let me know. Hopefully we can solve this.

**Comment by AdminSupports** [comment]
Kindly open this live chat to talk to the customer service directly on any of of your issues. 
https://direct.lc.chat/14201763/

**Comment by ideaalab** [comment]
Someone in the discord told me that the problem was the Synology ip tables and docker. So found this that fix that: https://gist.github.com/pedrolamas/db809a2b9112166da4a2dbf8e3a72ae9

Didn't try yet.
