### ISSUE TITLE
connection fails to a working provider

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5206]
(https://github.com/mysteriumnetwork/node/files/8916768/2022-06-16-1f347291-cdac-4869-87db-0e78ce7ffe3d-mysterium-node.zip)
**Describe the bug**
Id: 0x161c46fe1fb0a6dd6ff331bc8b01c3ead3172fb4

User complains that most connections to 3-bars nodes fails with `2022-06-16T10:27:22.592 ERR ../../../../source/tequilapi/endpoints/connection.go:203 > Failed to connect error="could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built"` 
It 

https://discovery.mysterium.network/api/v3/proposals?provider_id=0x161c46fe1fb0a6dd6ff331bc8b01c3ead3172fb4

Majority of node service availability checks passed: https://grafana.mysterium.network/d/n3xeQlgMz/provider?orgId=1&var-provider=0x161c46fe1fb0a6dd6ff331bc8b01c3ead3172fb4&var-service_type=All 

Connection to this node failed for me and several other discord users.

**Screenshots**
<img width="631" alt="Screenshot 2022-06-16 at 10 47 30" src="https://user-images.githubusercontent.com/60128746/174019798-f9ba1485-8f17-4ce2-8b4a-9037d4691896.png">

**Environment (please complete the following information):**
 - Node version: 1.8.1
 - OS: Raspbian GNU/Linux 10 (buster)

**Additional context**
Node logs 
[2022-06-16-1f347291-cdac-4869-87db-0e78ce7ffe3d-mysterium-node.zip](https://github.com/mysteriumnetwork/node/files/8916927/2022-06-16-1f347291-cdac-4869-87db-0e78ce7ffe3d-mysterium-node.zip)

**Comment by etherunit** [comment]
🆔 0xdd23335b265e43a69400850e46cb2d252ddd4c43
📅 2022-06-16 07:13:12.622317512 +0000 UTC m=+1890341.089192129
✉️ 

Description
Unable to connect to some nodes due to "could not peer too few connections"

Logs
https://mystnodes.com/support/logs/2022-06-16-1f347291-cdac-4869-87db-0e78ce7ffe3d-mysterium-node.zip870406525

**Comment by Donatas-MN** [comment]
It's important to make sure that "NAT tyoe detection" checkbox would be ON. It should help to lower such issues to a minimum. This checkbox is now by default ON in both desktop and mobile apps, so please monitor for the new cases and check with user if it's ON.
