### ISSUE TITLE
'Unable to locate package myst'

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5223]
**Describe the bug**
Getting the following error when trying to go through the PI setup process: 'Unable to locate package myst'

<img width="1275" alt="Screenshot 2022-06-18 at 22 00 37" src="https://user-images.githubusercontent.com/84313603/174461704-952887ea-b6ce-4464-a246-f0feef075b30.png">

**Comment by isaackielma** [comment]
Please try following this guide https://www.youtube.com/watch?v=El19X-zHt-c  starting at 13:40

Let me know in case the issue still persists

**Comment by etherunit** [comment]
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys `paste-pubkey-here`
sudo apt-get update
sudo apt install myst
```

**Comment by isaackielma** [comment]
Just updated user with the info. Will comment here once we get a response!
