### ISSUE TITLE
Node is online and accepting connections, but in all connections only 0 bytes transferred

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5228]
The node is online and accepting connections, but in all connections only 0 bytes transferred.

Example of three sessions where this is happening:

34ed3812-7f0a-4709-9d14-470114fac132

2f53027b-6538-4de6-ad2b-63dd06afa9e4

e2488ed0-3509-4ca2-81bb-198738ed7176

Logs:

https://mystnodes.com/support/logs/2022-06-17-d2da04b3-f892-4183-ba27-149173966bc5-mysterium-node.zip2081087900

**Comment by ecorrech** [comment]
any update?

**Comment by mZoleee** [comment]
same issue here.. any idea to fix?
