### ISSUE TITLE
Unable to fully register node

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5230]
3 Servers deployed on the Cloud with Linode and mysterium installed on them. 

When trying to initialize them in the NodeUI the only things I was asked are a password and the API Key. After that I got a pending loading screen. With the CLI I found out that they are unregistered and I am unable to register them. 

I didn't pay for registering those nodes yet. I was instantly redirected to the dashboard in the NodeUI. 

They are all running on Ubuntu 22.04 LTS

Node IDs:

0x658d125ae19236a4d568b0818b273638b0928c52
0xabebc0abec38691bbe7e527a042ebc88d7431709

<img width="1394" alt="Screenshot 2022-06-20 at 11 03 36" src="https://user-images.githubusercontent.com/84313603/174619197-ef3eba3d-53a9-46ab-b16b-712c73f08b5c.png">

**Comment by ToddEnneking** [comment]
It is a new installation.

 

Here is the script I ran to install it (on two different VPSes):

 

sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"  #

api_key="wtKu0Dc1J0GT6XeHVWcQV8cbKy0VStSD3uDV6HoW" # mainet API key for DCM

payout_address="0x22868254aAB6a171b0fa92e7F433B7c455a914E4" #

myst_id=$(myst cli --agreed-terms-and-conditions identities list | head -1 | cut -c 14-55) #

myst cli --agreed-terms-and-conditions identities unlock $myst_id #

myst cli --agreed-terms-and-conditions identities register $myst_id #

myst cli --agreed-terms-and-conditions mmn $api_key #

myst cli --agreed-terms-and-conditions identities set-payout-address $myst_id $payout_address #

myst cli --agreed-terms-and-conditions identities get-payout-address $myst_id #

 

I then run the following to check status:

 

myst cli --agreed-terms-and-conditions service list #

myst cli --agreed-terms-and-conditions service sessions #

myst account info #

myst connection info #

myst cli --agreed-terms-and-conditions identities list #

myst cli --agreed-terms-and-conditions identities get $myst_id #

myst cli --agreed-terms-and-conditions healthcheck #

myst cli --agreed-terms-and-conditions status #

sudo systemctl status mysterium-node.service #

 

See the attached log of the installation process.

 

All looks good. The node first shows that registration is in progress, then later shows unregistered.

 

I check https://mystnodes.com/nodes and it shows up in pink and offline.

 

I go to http://NODE IP ADDRESS:4449

 

I enter the password and then the withdrawal address if it asks (sometimes it asks and sometimes it already knows it). I then get “Your identity is being registered, please be patient...”

 

After a while I receive the error message: “Unfortunately, node identity registration failed. Please click RETRY button to try again.”

 

Please let me know if you need anything further.

 

Best of health,

 

Todd

**Comment by lusine-h** [comment]
Also happens for me with the same steps
![image](https://user-images.githubusercontent.com/60058956/179979415-e3b6266c-eec3-4b30-9654-51186cf955dd.png)

**Comment by etherunit** [comment]
@ToddEnneking This issue has been reproduced successfully (2nd option), what we've found:

If user is registering his node via NodeUI stepflow, top up/registration screen is shown;
If user is registering his node via mysterium-cli with `[INFO] Usage: register <identity> [beneficiary] [referralcode]` command , then NodeUI will skip top up screen and therefore registration will never complete and eventually fails;
If user is registering his node via mysterium-cli with `[INFO] Usage: register <identity> [beneficiary] [referralcode]` command, make manual top up transaction (using Metamask etc) to your channel during attempt event, then the registration will be completed.
