### ISSUE TITLE
Mysterium Node issue with connection

### ISSUE THREAD

**Issue by sanox1** [mysteriumnetwork/node#5240]
**Describe the bug**
On my nodes I see connection failed,  

In log of docker:

022-06-22T12:48:02.380 WRN ../../nat/traversal/pinger.go:138  > One of the pings has error error="ping receiver error: context deadline exceeded"
2022-06-22T12:48:02.380 DBG ../../eventbus/event_bus.go:101   > Published topic="Traversal" event={ID:remove this id Stage:hole_punching Successful:false Error:too few connections were built}
2022-06-22T12:48:02.380 ERR ../../p2p/listener.go:168  > Could not ping peer error="too few connections were built"

I opened port 4449 on router but no luck. Please assist.

**To Reproduce**
1. I deleted docker image
2. I deleted docker container
3. I put new string into docker "docker pull mysteriumnetwork/myst && docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v C:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions" and claimed node, paid 0.03 MYST and it was green for about 10 minutes
4. After 10 minutes I see error Connection failed in mystnodes.com

**Expected behavior**
I expect green connection. My other node on raspbian is working normally but its currently offline as I have turned raspberry off.

**Screenshots**
not applicable

**Environment (please complete the following information):**
 - Node version:  1.9.1
 - OS: Windows 10
 - Desktop app version (if applicable):  not available
 - Docker (if applicable): Alpine Linux v3.14(docker)
 - Your identity (if applicable): 0x50cd291c8a49ad44f0c15e82932a6b8bbba8fe61
 - Payment (top-op) reference (if applicable): n/a

**Additional context**
not applicable

**Comment by adinetech** [comment]
Forward default 10000:60000 UDP ports, it might work.

**Comment by sanox1** [comment]
Hi, you mean open these ports in router? Or adjust the docker image?

**Comment by etherunit** [comment]
You need to do both.
Go to https://docs.mysterium.network/troubleshooting/troubleshooting-nat-type-related-issues and navigate to view this subsection: `Enable Port Forwarding for the Docker container running a node`

**Comment by sanox1** [comment]
docker run --cap-add NET_ADMIN -d -p 4449:4449 -p 59850-60000:59850-60000/udp --name myst -v myst-data:/var/lib/mysterium-node mysteriumnetwork/myst:latest --udp.ports=59850:60000 service --agreed-terms-and-conditions
614e8fab17c41c76fa8eb272fd7e9cda974c27ac43da0965e5640ae423e8ddb0
docker: Error response from daemon: Ports are not available: exposing port UDP 0.0.0.0:59948 -> 0.0.0.0:0: listen udp 0.0.0.0:59948: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

this error appears

**Comment by etherunit** [comment]
It looks like ports were not available. Do you still experience this issue till now?

**Comment by sanox1** [comment]
For now it works on launcher 1.10.0/docker 4.10.1 by using port forwarding 34500: 50000 and opening those ports in the router.Lets keep the issue open this week to monitor further

**Comment by sanox1** [comment]
For now it works again. Opened port range 34500:50000 on router and used manual port forwarding in launcher 1.10.0/docker4.10.1

**Comment by sanox1** [comment]
Hello,
stopped working again. Getting this error in docker:
![image](https://user-images.githubusercontent.com/20610296/182436662-82f13db2-7b69-4c69-96e4-feef650cc708.png)

**Comment by adinetech** [comment]
Use another port range.

**Comment by sanox1** [comment]
> Use another port range.

the button in launcher is no longer clickable so I cannot change the port range. This happens EVERY TIME I switch from NAT to Port forwarding, and is not fixed unless I delete and recreate the container and image in docker and pay another 0.03 MYST. I am wasting my time and money with this project!
