### ISSUE TITLE
Node UI : Password Reset Not Woring

### ISSUE THREAD

**Issue by jaejaebruno23** [mysteriumnetwork/node#5243]
**Describe the bug**
When I tried to reset my password with the myst reset, I didn't get any confirmation that it was successful. And when I tried to Shift + F5 my browser, still it requires me to input my password.

**To Reproduce**
1. Go to Terminal and type docker exec myst reset
2. Go to Browser (localhost:4449)
3. Tried signing In but there is Bad credentials prompt

**Expected behavior**
It should have landed to a setup page for me to enter the new password but it did not.

**Screenshots**
![image](https://user-images.githubusercontent.com/96913178/175813205-1af31487-c8d4-4845-b13d-d198a2eaa9f0.png)

**Environment (please complete the following information):**
 - Node version: 1.9.2
 - OS: linux(docker)
 - Desktop app version (if applicable): 1.9.2
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
First, it requires to execute an interactive bash shell on the container.
`docker exec -it myst /bin/sh`

Then run pwd reset command:
`myst reset`

**Comment by etherunit** [comment]
![Screenshot 2022-06-29 at 09 23 43](https://user-images.githubusercontent.com/60128746/176366057-5964e1fa-ef49-40a1-9a83-91133c7ec6a4.png)
