### ISSUE TITLE
node is online but node UI displays only white browser page

### ISSUE THREAD

**Issue by hammerhead8599** [mysteriumnetwork/node#5244]
I have been running a node for two weeks now and this morning the web UI stopped functioning. The my node page shows node online but when I click the button for node UI it opens another tab as normal. The tab will flash the UI briefly along with the "loading" circle animation and then the page goes white. Shortly after the only item that loads is the chat balloon icon.
Now for the twist. I have tried Windows 10 Edge browser, Fedora, Debian, Linux mint. I have tried Firefox browser and chromium browser in Linux all with identical results. The only way I can see the node UI is on my Android phone.
I would guess that the mobile format is different than the desktop and this format may be where the issue lies. 
I am in no way a dev or coder but can follow instructions well and my preferred flavor is Linux. 
Almost forgot to detail my node set up. It is the latest stable version on a ubuntu 21 vm hosted on a proxmox server.
Please advise on any other logs etc. you might need me to upload.
Thank you

**Comment by sfxworks** [comment]
This just started to occur for me too.

**Comment by etherunit** [comment]
@hammerhead8599 @sfxworks 
Can you please provide a screenshot of your network tab (from developer tools) and submit a bug report (with node logs)? That could help us to identify and solve this issue.

**Comment by Wichtelchen1973** [comment]
Me too... reported the problem before at https://github.com/mysteriumnetwork/node/issues/5214

**Comment by etherunit** [comment]
I see, do you still experience that @Wichtelchen1973? Or it was fixed after a reboot or restart of the container?

**Comment by etherunit** [comment]
![Screenshot 2022-06-29 at 10 27 04](https://user-images.githubusercontent.com/60128746/176377519-7347d1b9-5824-4a37-90a8-d9a1a6b73bbf.png)
![Screenshot 2022-06-29 at 10 27 10](https://user-images.githubusercontent.com/60128746/176377526-be7448c9-00de-4ca7-a261-67e8bb550cb8.png)

**Comment by Wichtelchen1973** [comment]
A restart brings no change. Other browsers don't solve the problem either. If I change the resolution in debug mode I get the dashboard. 760x480 works and from 780x480 doesn't work.
![Bild1](https://user-images.githubusercontent.com/108090047/176386899-dedf60d3-4ea9-4408-a919-c7bb529cd95e.png)
![Bild2](https://user-images.githubusercontent.com/108090047/176386931-60a1117f-fa4a-4e20-a1db-fe180592c44a.png)

**Comment by Wichtelchen1973** [comment]
The problem only seems to occur intermittently. The dashboard is now working again for me.

**Comment by adinetech** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68943180/176422943-f97e3709-e8b1-40ab-b784-5feb70dbb32a.png">

**Comment by hammerhead8599** [comment]
@etherunit Hello and thanks for the reply. I just got back to my server and chacked the web UI and it is working now. No idea why or how it is working because nothing has changed in my setup. Have a different issue but will a different post on it when I have time to sort through it

**Comment by nabh2930** [comment]
I m running myst node in docker, shouldn't it be easy to upgrade myst without impacting active connections? I was told by moderators that updating to 1.9.5  will fix the issue. Please help.

**Comment by johanschaap** [comment]
I have been having the same problem for a week or so now. 

I can log in to the web ui but after that the wheel keeps spinning... Tried 4 different browsers, some of them never accessed the web ui so that should rule out cache. My RPI is running and up-to-date. I am running windows 11 on a Dell laptop and tried Brave, Chrome and Edge and Chrome and Safari on my iPhone 12. 

![image](https://user-images.githubusercontent.com/108923743/177943662-f6c86723-afd3-43ae-bbd3-9a98a3fb01ca.png)

**Comment by johanschaap** [comment]
I am not sure what you mean by that (and I am not a technical person). I do not think I have ever used the developers console. I just enter the ip-address:4449 in my browser. In the past, I got the web UI. Now I do not anymore. At least, I do get the login page but after that the wheel keeps spinning.  But if you want me to do something, please do give me instructions.

**Comment by adinetech** [comment]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/68943180/178095400-85d0fafc-c356-4881-8673-634ea5140265.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/68943180/178095407-385256f5-19cd-4e65-9b62-cc45fdcef2bf.png">

**Comment by ssmth2875** [comment]
@johanschaap your issue appears related to an issue I just opened here under an older alias. https://github.com/mysteriumnetwork/node/issues/5284
Have you actually restarted the raspberry pi? My node stops at the service level while the VM is still up and running. I restart the VM and my node restarts

**Comment by johanschaap** [comment]
I did restart my RPI yesterday and I could access the Web UI afterwards.
But today the wheel was spinning again. Just restarted and now I can see
the web ui again. Could there be something with how sessions are managed?

**Comment by ssmth2875** [comment]
@etherunit As a somewhat strange sidenote my node has not whitescreened again but I have had identical display results for different unrelated webpages. One is my account access page for a mobile provider and the other is a popular auto parts vendor. All I get is a white screen with the help chat bubble on any computer on my home network. I can access both pages correctly on my smartphone hotspot. Any ideas what to check? I do use pihole network wide with Unbound recursive DNS server active at router level. Thanks for any help.

**Comment by johanschaap** [comment]
So, I opened up my laptop again. Earlier today, I rebooted my RPI. In one tab, I refreshed my web ui. Spinning wheel. In another tab with the Web UI open, I could click on menu items. The most recent session started 2 minutes ago, so the data seems to be accurate. Strange bug this is....

**Comment by mauroferra** [comment]
I believe @etherunit is asking for is this:

<img width="2063" alt="Screen Shot 2022-07-19 at 12 38 12 PM" src="https://user-images.githubusercontent.com/40890242/179731455-83734757-56f5-4ba8-ac0f-e666d7cbbc99.png">

Happening to me too:
- running 1.9.5 on Docker
- restarting the container fixes the problem
- the node is actually working fine and serves connections, as shown from logs and mystnodes.com

Possible pattern: both times it happened to me there was a 30+ hours session running on my node (duration: 153002.455374069)

**Comment by ssmth2875** [comment]
@etherunit My UI is acting up again. Attached is photos of the results
![IMG_20220723_090659](https://user-images.githubusercontent.com/105179060/180609320-09e6e739-cc36-4dfb-8d02-2917efb321e2.jpg)
![IMG_20220723_090709](https://user-images.githubusercontent.com/105179060/180609332-29c814cb-a7f9-47fe-8ee5-3a63cc7e7961.jpg)
![IMG_20220723_090925](https://user-images.githubusercontent.com/105179060/180609345-d33b770f-82c0-4b27-aa5c-19cd75411fef.jpg)

**Comment by nabh2930** [comment]
I have active connection for more than one day and its still active. Unable to load node -ui. I'm running myst version 1.9.5. for my total data used it still somewhere around below 2 GB.

![image](https://user-images.githubusercontent.com/108820333/180631157-1a01a5c0-3ddc-483a-85b4-7d13d7edef36.png)

**Comment by adinetech** [comment]
I don't have a problem now but I found a 404 error, I'm not sure whether it is normal.
![image](https://user-images.githubusercontent.com/68943180/180635280-971e5bba-8d85-4e40-b040-94c25511fc98.png)

**Comment by mauroferra** [comment]
It did it again yesterday, still running 3 connections:

![image](https://user-images.githubusercontent.com/40890242/180637437-f549043b-e29e-4b8c-b497-6790c34152f6.jpeg)

I'd like to use the node UI to manage the node but don't want to terminate these connections, and have to check docker logs via ssh client through a vpn from the phone before restarting it. Given that it seems to be a relatively important bug, it's starting to be annoying to do all of the above when there is no outlook for a resolution nor it's in any way evident that the problem is understood or acknowledged by developers, even after the issue has been open for so long.

Please, do update this issue with your plan for debugging and fixing it, as it clearly is a regression introduced recently.

**Comment by ms74ro** [comment]
When I want to enter the dashboard, I enter the password and then nothing is visible, the whole window is white in the browser. Until yesterday, he didn't do that.

![image](https://user-images.githubusercontent.com/107406419/180647110-ed0b998f-dc16-4dc6-b2fd-76b3ee3d4098.png)

**Comment by Snawoot** [comment]
Try version 1.9.7

**Comment by hammerhead8599** [comment]
Thanks a million folks. Been running 1.9.7 since @Snawoot  suggested it and haven't had a single issue.
