### ISSUE TITLE
Automatic deposits

### ISSUE THREAD

**Issue by rkireland** [mysteriumnetwork/node#5254]
**Describe the bug**

**To Reproduce**

**Expected behavior**
My automatic deposits are not showing up in my MetaMask wallet. I have added the polygon Mainnet network and still nothing
**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
This might help you -- > https://docs.mysterium.network/for-node-runners/how-to-setup-polygon-myst-on-metamask

**Comment by etherunit** [comment]
Adding MYST token to MetaMask on the Polygon Mainnet
To add MYST token to your MetaMask, go to the main MetaMask account page. Click on the assets tab, where you’ll see Add Token at the bottom.

After you click Add Token, navigate to the Custom Token tab and manually enter the MYST token details. Copy the Token Contract Address (please find below) and paste that onto the Custom Token tab on MetaMask.

MYST token details:

Token Contract Address on PolygonScan : 0x1379e8886a944d2d9d440b3d88df536aea08d9f3

Symbol: MYST

Decimals: 18
