### ISSUE TITLE
Node showing "Connection Failed"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5255]
**Describe the bug**
This is the address -

0x9955e325eac953364de50b869319b39b3dc7f62f

not made any changes to the PC or router. It was working okay 

<img width="1075" alt="Screenshot 2022-06-29 at 05 37 53" src="https://user-images.githubusercontent.com/84313603/176392646-e9ec2f32-b475-4121-ab58-1d7a277e12a1.png">

Waiting on logs

**Comment by etherunit** [comment]
Please try `docker myst restart`

**Comment by arijitray81** [comment]
I have not changed any settings in the router or in the computer. However, the node stopped working post-June-26-2022. I believe the ISP is blocking this.

I have tried using the same node on a different ISP and it works perfectly. In fact, the other node is on a different ISP, 2500 miles apart.

**Comment by arijitray81** [comment]
In fact, I created another node on another computer connected to the same router. Here too earlier a node was working. But it is no longer working.

Node ID - 0x12c04f2bebb95c00f88ed90a9047efe07379cd05
