### ISSUE TITLE
Node says connection failed

### ISSUE THREAD

**Issue by Leem1969** [mysteriumnetwork/node#5259]
My node says connection failed when I goto mynodes also the signal says blank. The part on the web page that looks like mobile signal icon. If I click test the test runs and I see the connection on my node. However the data transferred is minimal.
![Capture](https://user-images.githubusercontent.com/108409583/176443362-bcde9b66-c0e8-4b81-a8e8-056ea1ebb288.JPG)

**Comment by etherunit** [comment]
@Leem1969 What's your Mysterium ID?
