### ISSUE TITLE
Introduce new services for node pricing

### ISSUE THREAD

**Issue by Donatas-MN** [mysteriumnetwork/node#5262]
To better support B2B clients we need to introduce additional pricing services. Currently there is only one service called Wireguard available.

Tasks:
- [x] Keep existing Wireguard service as public service (accessed by all consumers). Name can be kept as well to retain compatibility.
- [x] Add "B2B VPN and Data transfer" service which could be accessed only by whitelisted consumers
- [x] Add "B2B Data scraping" service which could be accessed only by whitelisted consumers

**Comment by mdomasevicius** [comment]
It would be good to have an endpoint in tequilapi that would list all of these servises plus any additional information related to them

**Comment by Donatas-MN** [comment]
> It would be good to have an endpoint in tequilapi that would list all of these servises plus any additional information related to them

@yeszhanov95 can you add tequila api endpoint for this?
