### ISSUE TITLE
Most sessions always end at the exact same time and data usage is almost identical

### ISSUE THREAD

**Issue by TonsakZone** [mysteriumnetwork/node#5268]
Most of my sessions in my node always end at the same time, which is 1:36 minutes.
And data usage is around 19kB. Is there something wrong with my node or it's a bug?

**Comment by etherunit** [comment]
What's your node identity? @TonsakZone

**Comment by TonsakZone** [comment]
0x59a92acf6a18343055b3bb5b048a8385cc0ef272

Here you go

**Comment by etherunit** [comment]
@isaackielma Can you check it now? I see an increased usage and data amounts.
<img width="762" alt="Screen Shot 2022-07-18 at 07 46 42" src="https://user-images.githubusercontent.com/60128746/179446825-5dcd5441-e18b-4ddc-8b9d-0da023aab1ec.png">
