### ISSUE TITLE
Internal Server Error during Network Registration (onboarding)

### ISSUE THREAD

**Issue by mattany** [mysteriumnetwork/node#5269]
**Describe the bug**
when trying to pay with paypal or Credit or Debit card on the initial screen of the node ui (http://localhost:4449/#/onboarding) I get a red "Internal Server Error" toast popup.

**To Reproduce**
1. Open http://localhost:4449/#/onboarding
2. Click Start Node Setup
3. Choose "Pay with Paypal" or "Pay with Credit or Debit card"
4. Click Pay Now
5. See error

**Expected behavior**
A popup should open enabling payment

Request that fails:
```POST http://localhost:4449/tequilapi/v2/identities/<wallet address>/paypal/payment-order```
request payload:
{"pay_currency":"USD","country":"<My country code>","project_id":"mystnodes","amount_usd":"1","gateway_caller_data":{}}

response:
```{"error":{"code":"gateway_order_channel_balance","message":"Internal Server Error"},"status":500,"path":"/v2/identities/<wallet address>/paypal/payment-order"}```
**Screenshots**
![image](https://user-images.githubusercontent.com/26661713/176938844-b9a8e2ca-9ab3-45c6-8d81-91116f9652dd.png)
**Environment (please complete the following information):**
 - Node version: 1.9.4-alpine
 - OS: Windows 11
 - Mysterium Launcher version:  1.0.30
 - Docker (if applicable): 4.10.0 (82025)
 - Your identity (if applicable): I'd rather not

**Comment by etherunit** [comment]
Can you please add node logs by any chance?

**Comment by mattany** [comment]
here you go https://gist.github.com/mattany/aea22c2a34fd65b19af65a1f0e1b662b
