### ISSUE TITLE
GUI or working Node on win docker

### ISSUE THREAD

**Issue by incarvr6** [mysteriumnetwork/node#5272]
Finally managed to connect to my problematic node. But still with problems...
If node works, GUI is not available,if GUI works node is not reachable.
Basically with simple node restarting I can get one or other but not both at the same time.

Running in Windows 10 with docker 4.9.1 
Node version 1.9.4

Node ID  0x06e014c830af8ae63c0c1de34e6d720fcd0f4655

**Comment by etherunit** [comment]
@incarvr6 Apologies for the delayed reply. We can see that your node is online and pretty much stabl now. Do you still experience such issues (with node or NodeUI)?

<img width="784" alt="Screen Shot 2022-07-18 at 07 45 54" src="https://user-images.githubusercontent.com/60128746/179446702-58a9f22e-e9c8-4c60-b8db-014a735303ec.png">

**Comment by incarvr6** [comment]
Yes it works now with updated to 1.9.5.
It seams that port forward feature in launcher is making issues with node.
