### ISSUE TITLE
Long session not rewarded 

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5273]
Description:

Hi ! I have had a session going on for 2 and a half days, 2Gb + transferred, but it doesn't show up on my sessions list and don't know if I have been paid for it. Thank you

Logs:

https://mystnodes.com/support/logs/2022-07-01-ef09693d-07e0-4fa4-8b1e-680f4f190725-mysterium-node.zip2770760620

**Comment by isaackielma** [comment]
Description:

Hi,

The issue I have is on the home screen session time keeps on counting but nothing is showing in the live sessions.

If I go back to the list of sessions, I found two that the time keeps on increasing but they don't show up on the live sessions and it seems like I'm not receiving any rewards for those sessions.

Logs:

https://mystnodes.com/support/logs/2022-06-21-424929f7-97cc-47fa-a15b-1f3f9f0bc25c-mysterium-node.zip1464703229

**Comment by etherunit** [comment]
@isaackielma I'd useful to check whether session data has appeared after a while (node restarts etc). I mean it could be a matter of a delay (time period to display live sessions) or a glitch with long sessions.
