### ISSUE TITLE
Node stopped working

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5275]
**Describe the bug**
my device went offline. it was a raspberry pi 400 keyboard with 5G ethernet attachment, no ports, was working great and now its stopped after turning it back on.

**Environment (please complete the following information):**
 - Node version: 1.9.2
 - OS: Ubuntu 22.04 LTS
 - Your identity (if applicable): 0x43778c81c99c1e85e0139074dc7e2a523c98afde

**Additional context**
Logs:

https://mystnodes.com/support/logs/2022-07-03-c2dd1f12-cefe-465d-95ad-05d6214db494-mysterium-node.zip3881107549

**Comment by etherunit** [comment]
@isaackielma Can you please check the apprx. timestamp when it's crashed? His logs is huge and we have no identifiers to follow.

**Comment by isaackielma** [comment]
Waiting on provider's response if the issue is still occurring on latest version

**Comment by etherunit** [comment]
Closed due to inactivity.
