### ISSUE TITLE
Mysterium raspberry image not working on newest boards

### ISSUE THREAD

**Issue by incarvr6** [mysteriumnetwork/node#5277]
Image from https://mystnodes.com/onboarding/rpi/install/0
Dose not work on latest boards
![Uploading IMG20220703172023.jpg…]()

**Comment by incarvr6** [comment]
![IMG_20220704_105055](https://user-images.githubusercontent.com/49254419/177130188-7bd66b65-0b31-4e57-8772-6e778a298e22.jpg)

**Comment by mishmearreal** [comment]
Having the same issue any work around?

**Comment by incarvr6** [comment]
You might run in to key problem , this is what helped me:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138

**Comment by incarvr6** [comment]
Have you changed image on your download link?
