### ISSUE TITLE
Transaction Sent to MetaMask Wallet but not received

### ISSUE THREAD

**Issue by sircam15** [mysteriumnetwork/node#5279]
I sent payments from two nodes to my MetaMask Wallet and they were not received.

I have sent payments to the nodes for registration and to and from wallets and understand the process.

I expected the payment to be received within my metamask.

Node version: 1.8.1
Ubuntu 20.04

If possible is there a way to share the transactions with yourselves without sharing my wallet address publicly?

**Comment by tomasmik** [comment]
Additional information is needed to answer on what happened wrong here. Identity, transactions, wallets sent to, anything. I could only suggest one thing now, and that would be to make sure you're using polygon mainnet netowork on metamask.

**Comment by sircam15** [comment]
Hi Tomas,

Thanks for getting back to me. How do I find my identity?

Yes I was using the polygon mainnet.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adinetech** [comment]
You can find your identity from the Settings of the Node UI and add the MYST token contract (if you haven't added it already)

**Comment by Devmenai** [comment]
> You can find your identity from the Settings of the Node UI and add the MYST token contract (if you haven't added it already)

Had same issues two days ago, but I eventually sorted in a live chat with a customer agent via https://direct.lc.chat/14390013/

**Comment by sircam15** [comment]
Okay thanks.

Node 1: 0xad221ad95b7d89a7358203d54fd2cca95ecce38c

Node 2: 0x8404c20d1c9f2342184a78ecfa3e913bb090d329

**Comment by sircam15** [comment]
Is there any update on this it has been a long time since I responded and have yet to receive a response
