### ISSUE TITLE
node is unable to register

### ISSUE THREAD

**Issue by muusli** [mysteriumnetwork/node#5281]
The node is unable to register. After installation and adding the API Key/Password a never ending loading Screen in the NodeUI occurs. 
Registration over cli fails after some time. 

1. Start a Server in the Cloud with e.g. Ubuntu 21.10 in my Case on Linode (Or on a RaspberryPI with PiOS)
2. ssh connect and install latest stable version
`sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"`
3. Enter IP Adress + :4449 in a browser for the Node UI
4. Fill out the form with password and API Key
5. Get never ending loading screen

I expected next steps to set up the node in the ui e.g. a withdrawal adress/Management over mystnodes.com/nodes and that I can somehow pay the registration fee
or
in the cli I expected a successful registration 

<img width="800" alt="step1" src="https://user-images.githubusercontent.com/58421542/177299489-539705db-7c53-4c67-96b0-c3a66a6ddc39.PNG">
<img width="790" alt="Step2" src="https://user-images.githubusercontent.com/58421542/177299496-54aa1654-d70a-4505-bf20-885d78a806d6.PNG">
<img width="945" alt="step 3" src="https://user-images.githubusercontent.com/58421542/177299500-653b6b3a-4e81-467b-b787-759c26b05c9f.PNG">
<img width="965" alt="service status" src="https://user-images.githubusercontent.com/58421542/177299503-3d3b5236-b2ce-4c78-901b-37aa0104a89e.PNG">

Environment 
 - Node version: [e.g. 0.19.1]
 - OS: Ubuntu 21.1 (But it also don't work on Debian/PiOs or other versions of ubuntu)
 - identity : 0x5e2fb7b9280435b2143703be4b43f4bb8957c8d0

I didn't pay any fees yet and was unable to find a way for that, I manually added a withdrawal address over the the cli. And the Server Node can't get a contract address.

Thanks for your help in advance!

**Comment by tomasmik** [comment]
Seems related to: https://github.com/mysteriumnetwork/node/issues/5230

**Comment by etherunit** [comment]
Please see comment https://github.com/mysteriumnetwork/node/issues/5230#issuecomment-1191235233
