### ISSUE TITLE
Node UI shows all services offline before restart

### ISSUE THREAD

**Issue by ssmth2875** [mysteriumnetwork/node#5284]
I am running a node on a proxmox server through a Ubuntu 21.10 VM. 2 GB ram 2 core vCPU. Installed fine and generally works well. It has developed a pattern lately though. I work during the day and do not get to my network until evening. When I try to open the GUI it will not open and the node status indicator shows all services offline. I enter my proxmox GUI for the VM and the RAM graph shows usage maxxed out and the CPU usage shows a serious spiking pattern. I reboot the VM and both graphs smooth out and the node GUI restarts all services and everything appears normal. 
This weekend, being a US holiday I was online sporadically from Friday thru Monday and the spiking issue never appeared. The node showed working at all times. 
I would appreciate any suggestions as to VM changes or tweaks
Thanks in advance

**Comment by ssmth2875** [comment]
![Screenshot from 2022-07-10 11-47-05](https://user-images.githubusercontent.com/105179060/178152137-79c61b99-0ec0-497c-a551-9ff1fbec1eac.png)
![Screenshot from 2022-07-10 11-48-21](https://user-images.githubusercontent.com/105179060/178152145-cec960de-7395-4c89-8dd3-e34ab5acfccd.png)

**Comment by johanschaap** [comment]
I have the same. Running a node on RPI. Fully updated. Worked fine until recently. It seems to have gotten worse now. I do not get the spinning wheel anymore, the web ui flashes and turns into a blanc page. Really frustrating. I am running windows 11 on my laptop and I tried several different browsers. Also on my iPhone 12 I have no result. In the past, I could reboot my RPI and it worked again. At least for a day. But now even rebooting the RPI does not help.

**Comment by etherunit** [comment]
@ssmth2875 Apologies for a delayed reply. Do you still experience this issue?

**Comment by hammerhead8599** [comment]
Hello @etherunit 
I only experience this sporadically. It has not failed since the past weekend so not sure if I can try to cause it to fail to help with diagnosis.
Thanks for the help.

**Comment by hammerhead8599** [comment]
@etherunit 
Just FYI this is an older identity for the same individual as @ssmth2875

**Comment by etherunit** [comment]
@johanschaap @hammerhead8599 guys, we have done some important fixes that should tackle this. Please upgrade your nodes and check if it helps.

**Comment by hammerhead8599** [comment]
Have been running 1.9.7 for 6 days now (at the suggestion of @Snawoot) to resolve another issue and no problems at all.
Great work and I really appreciate the help.

**Comment by johanschaap** [comment]
Thx, works like a charm!
