### ISSUE TITLE
Limited Status for Accepting Connections in my Myst

### ISSUE THREAD

**Issue by julianesco** [mysteriumnetwork/node#5293]
**Describe the bug**
The Accepting Connections status in my Myst Node is set as Limited.

**To Reproduce**
1. Log in to the Myst Node
2. Go to the Node Myst Dashboard
3. Scroll Down and check the Accepting Connections option
4. See Status is Limited

**Expected behavior**
I should expect not see this message and be sure that my node is available to all consumers.

**Screenshots**
I have added screenshots of the Accepting Connections status message and also de systemctl node status
![Myst Limited Status](https://user-images.githubusercontent.com/22917511/178218699-e118b538-d462-4e6e-85b8-c4fc5e3320ed.png)
![Myst node systemctl Status](https://user-images.githubusercontent.com/22917511/178218701-b9dcfa95-1c9d-4ce5-a477-0757a0a60211.png)

**Environment (please complete the following information):**
 - Node version: 1.12.0
 - OS: Ubuntu 20.04
 - Desktop app version (if applicable): v1.6.5
 - Docker (if applicable): No docker installed
 - Your identity (if applicable): 0xfde3a922517a678584b4cffe3096656f3c709a25
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by Peter-SovietSquirrel** [comment]
It says limited because you have Symmetric NAT. You are going to have to forward pots and not use UPnP or hole punching and do 1:1 NAT Mapping for the device that runs the Mysterium Node.
