### ISSUE TITLE
Custom price

### ISSUE THREAD

**Issue by Trusteduninstaller** [mysteriumnetwork/node#5296]
I think we (node runners) should be able to change the price per hour or per GB. 
Because now for example if the price is too high and you are not getting that many clients means that you will have less earnings and you can't affect that. But if we could change it to lower price it would be better for you and clients because if the price would be lower more (dVPN) users would connect to your node.

**Comment by tomasmik** [comment]
We're working on things related to your node price. Not exactly a custom price completely but there will be changes on how you can price and sell your traffic. Stay tuned.
