### ISSUE TITLE
5 MYST Coins not credited 

### ISSUE THREAD

**Issue by Kilopee** [mysteriumnetwork/node#5300]
When left alone without a wallet address the node auto cashed out 5 MYST, I assume to a mysterium wallet, but not my own as I had not set one up yet. 

I’ve added a address and coins now go to it, but the original 5 MYST still hasn’t been credited.

**Comment by etherunit** [comment]
Can you please provide your identity? 
Can you elaborate more on this part "When left alone without a wallet"? Thanks!

**Comment by Kilopee** [comment]
Hi, thanks for getting back to me, there was no wallet address connected to
the account, when the first payment was made automatically. Node -
0x9f4a3e9d245b733ac68c470582781e15c0d373c7.

**Comment by etherunit** [comment]
Hi @Kilopee, have you registered your identity (complete the onboarding steps) without entering your wallet address? It's mandatory to do that.

**Comment by etherunit** [comment]
Close due to inactivity.
