### ISSUE TITLE
Can not update node on Ubuntu 22

### ISSUE THREAD

**Issue by sag333ar** [mysteriumnetwork/node#5308]
**Describe the bug**
Can not update my node on Ubuntu 22

**To Reproduce**
1. [Clicked here](https://docs.mysterium.network/for-node-runners/updating-your-node)
2. Ran command - `sudo apt update`
3. Then ran command - `sudo apt install myst`

```
~ sudo apt install myst
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
myst is already the newest version (1.9.2+build570175622+jammy).
```

**Expected behavior**
It should update to latest 1.9.5 but it isn't

**Comment by Zensey** [comment]
@sag333ar @isaackielma 
There's no surprise, 1.9.2 is the latest myst build available on launchpad.

https://ppa.launchpad.net/mysteriumnetwork/node/ubuntu/pool/main/m/myst/

**Comment by sag333ar** [comment]
@isaackielma - then why does my node says "Connection failed"

**Comment by Zensey** [comment]
@sag333ar 
You can switch to the node-dev repo https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node-dev
Then 1.9.5 will become be available for update.

**Comment by Zensey** [comment]
@sag333ar 
But I would recommend using node-pre than dev
https://ppa.launchpad.net/mysteriumnetwork/node-pre/ubuntu/pool/main/m/myst/

**Comment by sag333ar** [comment]
@Zensey - please provide exact command which I can run on my Ubuntu.

**Comment by sag333ar** [comment]
> sudo apt install myst

worked like charm. thank you.

**Comment by sag333ar** [comment]
No. Now it says 
`Node status: Test Failed`

@etherunit , @isaackielma , @Zensey

**Comment by isaackielma** [comment]
Looks like these 2 nodes are sharing the same IP. Please choose to have only 1 of them and the issue will likely go away. Mysterium Network only allows 1 node per IP address

<img width="1038" alt="Screenshot 2022-07-24 at 16 32 59" src="https://user-images.githubusercontent.com/84313603/180663008-5d6bb858-d779-43ad-a6ca-73a4700d53cb.png">

**Comment by sag333ar** [comment]
but @isaackielma , you can clearly see that the Desktop node says `connection failed` and `M1 13` says offline. 
It means The other node (M1 13) is offline. I turned it off. If other node (M1 13) is turned off, `Desktop` node should work fine, shouldn't it?

**Comment by etherunit** [comment]
We should check it. please provide your node identity, the one that fails. thanks!

**Comment by sag333ar** [comment]
@etherunit it's `0x16940f45ee5f0d52ecbe968bc131e5c93c738267`

**Comment by etherunit** [comment]
I can connect to your node, but unable to resolve any pages.
```
ping google.com
ping: cannot resolve google.com: Unknown host
```
might be an issue with DNS settings

**Comment by sag333ar** [comment]
What DNS settings do you recommend?

**Comment by etherunit** [comment]
You can try Google DNS
8.8.8.8
1.1.1.1

**Comment by sag333ar** [comment]
@etherunit 
Worked fine for me

```
➜  ~ ping google.com
PING google.com(bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e)) 56 data bytes
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=1 ttl=118 time=5.25 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=2 ttl=118 time=5.27 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=3 ttl=118 time=6.76 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=4 ttl=118 time=5.91 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=5 ttl=118 time=6.25 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=6 ttl=118 time=5.55 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=7 ttl=118 time=5.17 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=8 ttl=118 time=5.61 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=9 ttl=118 time=6.06 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=10 ttl=118 time=7.70 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=11 ttl=118 time=5.15 ms
64 bytes from bom07s18-in-x0e.1e100.net (2404:6800:4009:80c::200e): icmp_seq=12 ttl=118 time=7.49 ms

```

**Comment by sag333ar** [comment]
> You can try Google DNS 8.8.8.8 or Cloudfare 1.1.1.1

@etherunit - I updated DNS settings. Try now.

**Comment by etherunit** [comment]
Hello @sag333ar I'm experiencing the same issue. Can you please submit the latest node log for review?

**Comment by sag333ar** [comment]
I stopped every node of `mysteriumnetwork `
