### ISSUE TITLE
Connection failed on dashboard, shows online on node UI

### ISSUE THREAD

**Issue by ygboucherk** [mysteriumnetwork/node#5310]
I'm running a node on a VPS/data center (enabled forwarding in ufw config). It shows accepting all connections on node UI (online), but shows failed connection on https://mystnodes.com/nodes !
![image](https://user-images.githubusercontent.com/60298855/179527486-48f5d183-d01b-4f0a-bad2-fb7501c0d8f7.png)

**Comment by Peter-SovietSquirrel** [comment]
Your node on mystnodes shows as online.

**Comment by ygboucherk** [comment]
It's fixed now.
Wait... how do you know ?

**Comment by etherunit** [comment]
Team members have access to the node statuses internally.
We hope it works expected now.
