### ISSUE TITLE
Unpaid sessions

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5314]
NodeUI was stuck on loading. After reboot reboot it is working. However, one big connection had approx. 50GB and didn't get any MYST because of rebooting node.

<img width="1278" alt="Screenshot 2022-07-19 at 12 51 46" src="https://user-images.githubusercontent.com/84313603/179794391-866bbe7e-d658-4683-a817-6e74181386df.png">

Regardless of that, bandwidth was shared and MYST not credited. Session ID shows 0bytes for a +2 day session:

<img width="1285" alt="Screenshot 2022-07-19 at 12 36 57" src="https://user-images.githubusercontent.com/84313603/179791156-c0e05c80-3af6-41c3-a82d-44906faa0f48.png">

These are the two other long lasting sessions that were not paid:

<img width="1287" alt="Screenshot 2022-07-19 at 12 42 57" src="https://user-images.githubusercontent.com/84313603/179792642-e4770da2-3744-477a-bc35-0ee7c3f69139.png">

<img width="1285" alt="Screenshot 2022-07-19 at 12 42 30" src="https://user-images.githubusercontent.com/84313603/179792553-916bc1d1-d22d-4945-82d9-003722853dd1.png">

**Comment by etherunit** [comment]
Thanks for submitting the issue. Team will investigate it further.
Is it possible to attach logs to it @isaackielma ?

**Comment by etherunit** [comment]
related to https://github.com/mysteriumnetwork/node/issues/5311

**Comment by etherunit** [comment]
Once it will be fixed, such issues should not appear anymore.
