### ISSUE TITLE
 i notice that there is a rhythm in the time.

### ISSUE THREAD

**Issue by cornejongeneel** [mysteriumnetwork/node#5317]
hello there i notice that there is a rhythm in the timeline of usage, a lot is around 00:01:35.
is there an explanation for that?

And is there a way in which more use can be made of my network sometimes it is not used for 2 days and sometimes 5 times in a day,
it would be nice if it was more consistent.
thank you for your time. 
Regards

**![node runner](https://user-images.githubusercontent.com/43524809/180060329-a6add87e-db1f-4b35-b5e7-2a62b53a77f6.jpg)**

 - NodeUI version: 1.17.1
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker Desktop 4.10.1 (82475) 
 - 0x9e85fc3af464da3793491c5fce57c19d450366b6

**Comment by tomasmik** [comment]
This is not something we can really control. People connect to your node whenever they want/need to.
