### ISSUE TITLE
0 data transferred but credited. 

### ISSUE THREAD

**Issue by rossiscool123** [mysteriumnetwork/node#5318]
**Describe the bug**
Sessions aren't showing data used but showing credited amount.

**Expected behavior**
Data usage shown next to session.
**Screenshots**
https://i.imgur.com/tBmDikH.png

**Environment (please complete the following information):**
 - Node version: 1.16.2
 - OS: Ubuntu 20.04.4 LTS 
 - Your identity: "0xe940dd0f14bdbb970c496d098bd3752217f823d0"
![tBmDikH](https://user-images.githubusercontent.com/62076535/180125669-e7375dc9-4b95-4afb-8285-4010f8156f07.png)

**Comment by rossiscool123** [comment]
I could see that the node was definitely transmitting data using nload and looking at the network interfaces named "myst1" as an example.

**Comment by etherunit** [comment]
It could be that node failed to update data transfer component. 
Do you still see it as 0 after restarting it?
