### ISSUE TITLE
Could not filter list of proposals with country query string

### ISSUE THREAD

**Issue by poyaz** [mysteriumnetwork/node#5325]
**Describe the bug**
I read the open API document on [listProposals](https://tequilapi.mysterium.network/#operation/listProposals) and according to the document for filter country, we can use the `country` query string. But I tested on docker image with image tag `mysteriumnetwork/myst:latest` (Use with tequilapi) and also tried with discovery node and the result was same. The country not filtred and return all country.

**To Reproduce**
1. Send request on `https://discovery.mysterium.network/api/v3/proposals?country=GB`

**Expected behavior**
The result of proposals not filtered 

**Screenshots**
-

**Environment (please complete the following information):**
 - Node version: 1.9.5
 - OS: Debian
 - Desktop app version -
 - Docker (if applicable): mysteriumnetwork/myst:latest
 - Your identity (if applicable): -
 - Payment (top-op) reference (if applicable): -

**Additional context**
-

**Comment by soffokl** [comment]
It's should be `location_country` for unknown reasons:
https://discovery.mysterium.network/api/v3/proposals?location_country=GB
