### ISSUE TITLE
IP type shown as DATA CENTER but at ip2location.com it is residential

### ISSUE THREAD

**Issue by xpugur** [mysteriumnetwork/node#5326]
I got 2 nodes running.
At dashboard 1 of them show up as DATA CENTER IP,
![cc](https://user-images.githubusercontent.com/18118067/180647317-1ff2c6f3-f111-4cf1-866b-e8357c863b35.JPG)

I checked the IP on ip2location.com  and it shows as   (RES) Residential proxies [PX10+ only]  
(i checked cause i run some other apps that do NOT work on DCH IP but they were working so i checked just to be sure and it is residential)

Node version is the latest, i did restart the node and pc, still same,
Windows 11
0xf107004debf0754319f1e14c6d6cfe7634b498ee

How can i fix it without changing my IP ?

**Comment by n10ty** [comment]
I can assume what happening. Mysterium node list takes IP type from [proposal list](https://discovery.mysterium.network/api/v3/proposals?access_policy=all). If it is residential id display it as "Residential". In other cases or if it is not found in proposals - "Data Center". The node can appear in proposals later (it takes some time to add in the list) than in the node list and until then the node will be marked as hosted. No need to worry - it's just a label. Your bandwidth price still rely on internal IP location service.

**Comment by xpugur** [comment]
"Can you find your proposal in the list?" ?  what is "proposal" ? what list? 
i only know that for a few days it did not earn a thing than i cancel my static IP so changed IP :/

**Comment by adinetech** [comment]
Whether the IP change helped you?

**Comment by xpugur** [comment]
> Whether the IP change helped you?

now i got Datacenter IP so i stopped running node, but it would work if it was residential IP :)

**Comment by adinetech** [comment]
Got it, I would tell it's strange for a consumer to have a data center IP as not all streaming services will work with it.
