### ISSUE TITLE
Auto withdraws not working

### ISSUE THREAD

**Issue by fraucs** [mysteriumnetwork/node#5327]
**Describe the bug**
Hi, my node try yo send automatically  withdraws, but no external address is displayed  and on [polygonscan.com](http://polygonscan.com/)   the payments is all in **Settle Promise**.

If I settle manually the external payments is done and I receive the payments.

**To Reproduce**
1. Click on wallet on left sidebar of node UI
2. You see in the list many automatic withdraws without external wallet.
3. if you withdraw manually, the "external wallet" field is full and actually paid.
4. check transactions on [polyscan](https://polygonscan.com/token/0x1379e8886a944d2d9d440b3d88df536aea08d9f3?a=0x2a668de5d0ed2ee3d30ea2419fe595f97ecbc397)  to  see detailed transactions.

**Expected behavior**
I expect the automatic collection to work as expected and not to "lose" everything if I don't do the manual withdraws before 5 myst.
**Screenshots**
<img width="1440" alt="node ui" src="https://user-images.githubusercontent.com/46866745/180719244-010a955a-1065-4040-ab7b-343f1873df10.png">

**Environment (please complete the following information):**
 - Node version: Version: 1.9.2 
 - OS: Raspbian bullseye 
 - Your **0x76fbcaaa52ce11ffeaf6cf0c919b737ee8ada683**

**Comment by tomasmik** [comment]
Settle Promise is the automatic withdraw action. The issue is not very clear tho, so when you set automatic withdrawals and go over the configured MYST limit, does it no settle for you? Did you try to lower the limit? If the limit being lowered doesn't affect when settlements happen, you should try and restart your node.

**Comment by fraucs** [comment]
Hi @tomasmik , I'll try to explain, when withdrawing automatically i don't get tokens on my wallet.
While when I manually settle the withdrawal all works fine.
