### ISSUE TITLE
Updated server and docker no longer working 

### ISSUE THREAD

**Issue by jaimecalvo81** [mysteriumnetwork/node#5330]
**Describe the bug**
I updated my server from Ubuntu 16.04 to Ubuntu 22.04.
Then I did a pull of latest docker image. 
This is the command I ran:
sudo docker run --cap-add NET_ADMIN -d -p 4449:4449 --name mys -v config:/var/lib/mysterium-node mysteriumnetwork/myst:latest service --agreed-terms-and-conditions

When I started up the docker again I needed to register the node again. 

**To Reproduce**
1. Go to 'http://mys.digitalconcept.se:4449'
2. On https://mystnodes.com/nodes its id is:
0x65ae9739152c9d7f62c1d84b256a0cd15712cbad

**Expected behavior**
Expected to reconnect as it was. 

**Environment (please complete the following information):**
 - Node version:? 
 - OS: Ubuntu 16.04 - > 22.04
 - Docker (if applicable): mysteriumnetwork/myst:latest@sha256:983d463f549daff259a878444ab6035d08da522e706bdc49b13c16cd663ead3e
 - Your identity (if applicable): 0x65ae9739152c9d7f62c1d84b256a0cd15712cbad

**Additional context**

**Comment by etherunit** [comment]
What's the output of `docker ps -a`

**Comment by jaimecalvo81** [comment]
a5e7d5c75171   mysteriumnetwork/myst:latest  "/usr/local/bin/dock…"   5 days ago   Up 5 days 0.0.0.0:4449->4449/tcp, :::4449->4449/tcp  mys

**Comment by etherunit** [comment]
It looks like you have started a new container which required new registration.

**Comment by jaimecalvo81** [comment]
I thought the mount was done to be able to change to the latest image without losing contact.
Can I pay with collected MYS ? How do I see my total amount of MYS ? Or do they disappear after 30 days ?

**Comment by etherunit** [comment]
No they don't disappear. The only thing that happens automatically is auto-settlement which will settle your earnings to the wallet. 
You can't pay with collected MYST directly from your NodeUi, unless you have transferred them your external wallet.
You can check the amount of MYST on polygonscan.com (copy the identity channel and paste it in the search bar)
