### ISSUE TITLE
[android] node disconnects frequently after connecting

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#5332]
**Describe the bug**
Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/9187932/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.7.1
 - OS: Android

**Comment by portalsdevs** [comment]
More logs from the same user:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/9187959/mysterium-node.log)

**Comment by tomasmik** [comment]
solved
