### ISSUE TITLE
[linux] node gets into On Hold state frequently

### ISSUE THREAD

**Issue by portalsdevs** [mysteriumnetwork/node#5334]
**Describe the bug**
Node gets into On Hold state usually in 3-6 minutes after connecting. User notices that usually this happens if there's network activity like streaming.
This same issue happens at home and at work for the same user, so it's not a network problem.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/9188062/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 1.6.0
 - OS: Linux

**Comment by portalsdevs** [comment]
More logs from the same user:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/9188099/mysterium-node.log)

**Comment by tomasmik** [comment]
solved
