### ISSUE TITLE
Node identity export to file error on Windows 

### ISSUE THREAD

**Issue by andrey-mysterium** [mysteriumnetwork/node#5335]
**Describe the bug**
We have an empty file after export identities on Windows system

**To Reproduce**
1. identities export <pass> <pass> path
2. we have a Success response but file is empty

**Expected behavior**
A destination file need to contain a valid JSON identities data

**Environment (please complete the following information):**
 - Windows

**Comment by tomasmik** [comment]
This feels more like a desktop issue, not the node itself.

**Comment by andrey-mysterium** [comment]
> This feels more like a desktop issue, not the node itself.

Yes, it seems true. But need to check it.

**Comment by andrey-mysterium** [comment]
So I prepare Windows setup and get such results:

1 Execute Myst node application
2 Run Myst CLI and get only one identities in list
3 From my other computer export identity as a JSON text

`identities export IDENTITY PASS`

4 Import this identity to Windows based test node

`identity import PASS {..json..}`

5 Export identity to file


![Image](https://user-images.githubusercontent.com/107684964/196030488-a6b9701a-ab3e-4876-9f6d-fad1e2a64fa1.png)


6 Check is file exist (yes)



![Image](https://user-images.githubusercontent.com/107684964/196030700-cb36f526-8010-45d2-a377-fc5fcd5fc7d7.png)



7 Open the file and check content (yes)



![Image](https://user-images.githubusercontent.com/107684964/196030551-28681fe6-ecf0-4568-aba3-3364d6ae6f8e.png)

8 Remove all .mysterium keystore files on Windows setup
9 Import identity from saved file (done)


![Image](https://user-images.githubusercontent.com/107684964/196030669-a35b1d37-c324-4792-adc8-9b4e51aa10b9.png)

So identities export to file work properly from first look.
