### ISSUE TITLE
Ip2location info not correct

### ISSUE THREAD

**Issue by Sendros** [mysteriumnetwork/node#5337]
Hi, Using you discord I was told my static ip was marked as datacenter instead of residential.
![image](https://user-images.githubusercontent.com/105081591/180981538-bcb54733-7c27-46b5-881d-63559d18ccb4.png)

#Adine told me to contact ip2location and if they did not answer to create ticket here because you might have some options.

https://www.ip2location.com/86.107.187.166

Kind regards, 
Sander

**Comment by n10ty** [comment]
Hi, Sander. As you know we are using Ip2location to get IP type and usually it is accurate enough. But of course, sometimes mistakes could happen. Not sure changing IP will help - they can mark all your subnet as hosted. I checked, yes your ISP does not seem like hosted. What you can do now: write to support ([support@ip2location.co](mailto:support@ip2location.com)) and ask to mark your IP as residential. Please post here the result.

**Comment by Sendros** [comment]
Thank you! What is the difference between the 2 that one qualifies as DCH and the other does not?

**Comment by n10ty** [comment]
Just an example that this is looks like a mistake

**Comment by n10ty** [comment]
@Sendros I got response, they promised to include this changes into next release. If I'm not wrong they release new db once a month.

**Comment by Sendros** [comment]
@n10ty HI, I got the same response:) They say end of the month, so any day now. 

Thanks so far!

**Comment by Sendros** [comment]
Hi @n10ty , Its updated now. How long wil it take for my node to show as residential and scale earnings according?

https://www.ip2location.com/demo/86.107.187.166
0x55cdaabf560c46b1cada8d9372f5ddd2ed6e3271

**Comment by isaackielma** [comment]
@n10ty @Sendros Are you guys still having this issue?

**Comment by Sendros** [comment]
@isaackielma Hi, Ip2location has updated his info. However Myst did not not yet adopt this information.

**Comment by n10ty** [comment]
We update once a week. I triggered manual update. Please check now ([here](https://location.mysterium.network/api/v1/location/))

**Comment by Sendros** [comment]
That show residential now! So, When does it who in the app or at Myndes? And when goed the price/Gb go up scaling as resedential?

**Comment by n10ty** [comment]
@Sendros Check now, it should have updated

**Comment by Sendros** [comment]
[cid:storage_emulated_0_Android_data_com_samsung_android_email_provider_files__EmailTempImageHEV_1659340012426_jpg_1659340012458]
Not yet


Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Andrey ***@***.***>
Datum: 01-08-2022 09:31 (GMT+01:00)
Aan: mysteriumnetwork/node ***@***.***>
Cc: Sendros ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [mysteriumnetwork/node] Ip2location info not correct (Issue #5337)


@Sendros<https://github.com/Sendros> Check now, it should have updated

**Comment by n10ty** [comment]
[Proposal](https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&access_policy=all&provider_id=0x55cdaabf560c46b1cada8d9372f5ddd2ed6e3271) shows your IP is a residential. It cached in Node. There are few layers of cache. Try restart node or wait for a while.

**Comment by Sendros** [comment]
Oke ill wait! Thank you so far!

**Comment by Sendros** [comment]
So this is how it goes now:
-Mynodes shows residential
-App shows Datacenter(even after refresh and reinstall)
-When connected its switching. 1 Minute it show residential the other minute it shows datacenter. It keeps doing this?

**Comment by Snawoot** [comment]
@Sendros can you please check which IP address is returned to you on this URL https://location.mysterium.network/api/v1/location/ ? please do few checks with few minutes interval. also please make sure you're not running node with the same provider ID elsewhere.

**Comment by Sendros** [comment]
Hi @Snawoot 

I only have 1 node.  Ip returning is 
86.107.187.166

When using myst vpn trough my gsm i still see this:
![SmartSelect_20220801-143411_MysteriumVPN](https://user-images.githubusercontent.com/105081591/182148871-633405a8-e75e-4918-bf21-e1a503f3291b.jpg)
![SmartSelect_20220801-143315_MysteriumVPN](https://user-images.githubusercontent.com/105081591/182148876-3f14cd01-63e5-4399-b10f-5f8a6e84e40e.jpg)


Mynodes shows:
![Screenshot 2022-08-01 143822](https://user-images.githubusercontent.com/105081591/182149608-83ab301b-23e5-4541-8101-2addda7e2a36.png)

**Comment by Snawoot** [comment]
@Sendros ok, thanks! looking into that

**Comment by Sendros** [comment]
Btw, Just found out that when connected to VPN my speeds maxes out at 40Mbps. Could it be that the node is having a hard time with the encryption? My Phone has 200/200 and my node has 1000/1000

**Comment by n10ty** [comment]
@soffokl could you please help?

**Comment by Sendros** [comment]
> > Btw, Just found out that when connected to VPN my speeds maxes out at 40Mbps. Could it be that the node is having a hard time with the encryption? My Phone has 200/200 and my node has 1000/1000
> 
> Unlikely. Usually speed is measured with TCP session (using HTTP or HTTPS protocol). In that case, bandwidth is not the only limiting factor: actual transfer speed will depend on packet loss rate and latency.

Makes sense. I don't have another fixed 1gb line to test my node performance.

**Comment by n10ty** [comment]
@Sendros Is it still actual?

**Comment by Sendros** [comment]
Hi, This is solved! Thank you
