### ISSUE TITLE
bug when claiming a node

### ISSUE THREAD

**Issue by kendouch** [mysteriumnetwork/node#5344]
**Describe the bug**
I bought a raspeberry pi programmed with SD card to create a node (amysterium raspberry pi ready to plug and play) . And i put the sd card as well as the box connected to the power supply and my internet router.
And i can not go on the UI and put the APY and before I can not claim the node.  When i try to reset another an SD card with mystOS same issues my py just reboot in a loop. But with an debian OS its all good, except when i try to get a mysteriumnod manually i got issues in the cmd of ubuntu. 

**Expected behavior**
I am unable to say where the problem comes from

**Screenshots**

![Sans titre](https://user-images.githubusercontent.com/110155699/181441751-1c508573-4d38-43f5-9f4c-79b63dbb33c4.png)

 - OS: [debian 10]
**Additional context**
This is the first time I have a raspberry py and I do this kind of manipulation, its quit funny but hard !

**Comment by Peter-SovietSquirrel** [comment]
You could use the script or follow they guide from the docs 
`sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"

https://docs.mysterium.network/for-node-runners/raspberry-pi-guide`

**Comment by kendouch** [comment]
i tried in vain it doens't work, and when i just lauch the command ligne :  grep -qxF 'deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal main' /etc/apt/sources.list || echo 'deb http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal main' | sudo tee -a /etc/apt/sources.list > /dev/null


As the website of mysterium said. I got on the line 4, an error message telling me that the list of source could be read
I hope i will find a solution cause i love the concept of a dvpn, and i am unlucky cause i bought the py plug and play for that ( quit expensive
![IMG_20220728_193202](https://user-images.githubusercontent.com/110155699/181673415-af9bf9b3-fde5-4846-9e2f-7ccc888e4e6e.jpg)
)
here an image of the issue
Have a nice day

**Comment by isaackielma** [comment]
Could you please try rebooting the node and then try to claim once again? Looks like a synching issue happening with API key.

**Comment by kendouch** [comment]
Ok then how i do to reboot the node ?

**Comment by adinetech** [comment]
`sudo systemctl restart mysterium-node.service`

**Comment by kendouch** [comment]
I got this message, Which translates into " impossible to find the myst
package" and before that there is the error2 "the following signers could
not be verified because the public key is not available

**Comment by etherunit** [comment]
as per error, links in your source file are malformed so it couldnt read and process it.

**Comment by kendouch** [comment]
However I use the script of the official site mysterium node .How i Can fix
it ?

**Comment by kendouch** [comment]
OK, guys when i try to boot mystberry with raspberryPi imager or balena itcher i got bunch of errors, i will post an image of the script as he is booting
![IMG_20220801_114408](https://user-images.githubusercontent.com/110155699/182121626-a04f31e1-da33-4587-affb-f00b800fe239.jpg)
.

And when i drop the scrip for the basic RPI device i got others errors like " I got this message, Which translates into " impossible to find the myst
package" and before that there is the error2 "the following signers could
not be verified because the public key is not available"
I don't know what to do
its still fucked...

**Comment by kendouch** [comment]
ok guys, i can close the issue i just swap the start4.elf for a brandnew and it work im so happy !! THANKS ALL
