### ISSUE TITLE
connection failed

### ISSUE THREAD

**Issue by CEDRICHK** [mysteriumnetwork/node#5347]
**Describe the bug**
i can no longer connect via ssh (putty). I have a connection error. However on the interface I manage to connect to it!! 

**Expected behavior**
A successful connection with ssh.

**Environment (please complete the following information):**
 - Your identity (if applicable): 0x059d44de1b869da7d7adfda464dc81a4e4438d64

**Comment by adinetech** [comment]
Do you use the Mystberry OS (Raspberry Pi OS with Mysterium node pre-installed)?

**Comment by adinetech** [comment]
You can change the password using `sudo passwd`

**Comment by etherunit** [comment]
What type of connection error? Screenshot would help a lot.
