### ISSUE TITLE
Could not start my Raspberry Pi 4B 8GB after flashing RPI image from mystberry.zip

### ISSUE THREAD

**Issue by laozifury** [mysteriumnetwork/node#5352]
I am planning to run a Msyterium node on my network with a Raspberry Pi 4B 8GB.

Reference is made with the below guideline on https://docs.mysterium.network/

- Download the Mysterium Node RPI image: [mystberry.zip](https://github.com/mysteriumnetwork/node/releases/latest/download/mystberry.zip)
- Download Balena Etcher if you haven’t already got it: https://www.balena.io/etcher/
- Insert the microSD into the provided SD card reader and connect it to your computer.
- Open BalenaEtcher and select mystberry.zip as the image. Select the SD card file as the target.
- Make yourself a tea. Wait until your Flash! is complete.
- Insert the microSD card into your Raspberry Pi.
- Plug in the network cable into your router and then the power cord. It may take a few minutes before the Pi is fully up.

ISSUE:
After plugging in a flashed microSD into my RPI, it shows "the board requires newer software".  It seems that the Pi is not compatible with the image.

What should I do?

**Comment by etherunit** [comment]
There is a workaround:
Download the raspbian or debian 64-bit image and flash it to the SD-card. Then use the following command to install Myst:
```
sudo apt-get install curl
sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"
```

**Comment by etherunit** [comment]
I consider closing this issue, feel free to reopen it in case you'll still face an issue.
