### ISSUE TITLE
It is not possible to Connect to my node

### ISSUE THREAD

**Issue by discord-bot-coom** [mysteriumnetwork/node#5356]
**Describe the bug**

**To Reproduce**
1. Go to 'start it'
2. Click on 'and then goes to the logs'
4. See error https://rentry.co/tctke

**Environment (please complete the following information):**
 - Node version: [1.11.1]
 - OS: [Windows 11]
 - Docker 4.11.0 
 - Your identity 0x22a150e7983abdd0605bb4279076dce947c12ee1

**Additional context**
the problem came after the last update

**Comment by adinetech** [comment]
Please make sure that your node and app version is up to date.

**Comment by discord-bot-coom** [comment]
@adinetech nothing helps
:(

**Comment by adinetech** [comment]
I maybe misunderstood your issue, you're unable to connect to your own node or you never got any sessions to your node?

**Comment by discord-bot-coom** [comment]
@adinetech Now I'll explain a little better when you do a test on the website for node, I don't get that anyone connects there and if someone connected nothing happens so this is after the latest update on docks and on node

**Comment by adinetech** [comment]
I understand, it seems like a firewall issue that doesn't allow any connections to your node.

**Comment by discord-bot-coom** [comment]
@adinetech I'm not very good at firewalls and How to fix
:)
