### ISSUE TITLE
2 extras in the My Nodes portal and put your developers planning/schedule up so all can see progress and status

### ISSUE THREAD

**Issue by Durfduivel** [mysteriumnetwork/node#5359]
I asked for a green light when my node is in use by a client. And I asked to put back the actual MYST that is collected by the node.
I personally am not interested in monthly earnings because the earnings go to my wallet every time they reach 5 MYST. I just want to see how much MYST is in every node because some times I collect it manually and now I have to go into every Node UI to see this.

Other people have asked for some extras to put in the My Nodes portal and they asked this in the Discord Server.
Do you developers have a schedule so we all can see upcoming changes and changes that have been rejected?

**Comment by Durfduivel** [comment]
This related issue I entered was closed but no status update: https://github.com/mysteriumnetwork/node/issues/4550

**Comment by mdomasevicius** [comment]
@Durfduivel thanks for the issue. I will investigate and estimate what we can do about MYST earning breakdown and the node usage indicator. I will link development items here for you to track.

**Comment by veldspar** [comment]
As someone running 23 nodes myself, here's a few tricks you can use: for node connection indicator, run a script on every node that checks whether the interface myst0 exists. There are some corner cases where a connection is up but myst0 isn't but for my purpose that's accurate enough. The balance can be queued using the API. Put it into a script, cronjob the script and have all nodes push the info into a central db. If you run multiple nodes that should be easy enough
