### ISSUE TITLE
Connection failed on dashboard, shows online on node UI

### ISSUE THREAD

**Issue by critinvest** [mysteriumnetwork/node#5371]
I'm running 2node on from home and one from vps. It shows accepting all connections on node UI (online), but shows failed connection on https://mystnodes.com/nodes 
![myst](https://user-images.githubusercontent.com/111102342/184276791-9881f822-f012-471d-b8df-2cfba283b806.jpg)
!

**Comment by Jutawanmalay** [comment]
Same issue with me online in ui node but in dashboard connection failure dont know why still checking who have experience please advice

**Comment by Stoony1** [comment]
I have the Same Problem with 1.12.2 fresh installation
