### ISSUE TITLE
Auto update on Nodes

### ISSUE THREAD

**Issue by anweshan1** [mysteriumnetwork/node#5374]
Why don't we have an auto-update feature that automatically updates the nodes?
I don't think it's that much harder cause I see every other program having an auto-updater shipped with it...
I would really love to see an auto-updater with myst too.

**Comment by adinetech** [comment]
https://docs.mysterium.network/for-node-runners/updating-your-node
Search for `How to setup automatic node updates on Ubuntu/Debian/RaspberryPi`

**Comment by anweshan1** [comment]
I see what you gave here to me, but I am asking devs to add a autoupdater
itself on the package such that it updates automatically without doing
anything else.
Many of the packages come with a auto updater so its also not that big of
a deal i guess.
Thanks for your help tho
