### ISSUE TITLE
Client don't pay the session

### ISSUE THREAD

**Issue by DiogoMarques2003** [mysteriumnetwork/node#5375]
**Describe the bug**
For some reason the client isn't paying the session use.

**Screenshots**
![image](https://user-images.githubusercontent.com/52538977/184500116-abaf2254-e747-4984-a26e-67fed4422eb8.png)

**Environment (please complete the following information):**
 - Node version:  mainnet (1.11.1-8c8ace18)
 - OS: ubuntu 22.04.1
 - Your identity (if applicable): 0x2cdcacc6ffdb4db74b9fb898e14d0e24e3373494

**Comment by etherunit** [comment]
@DiogoMarques2003 Please submit node logs for review.
