### ISSUE TITLE
Withdrawn ammount didn't come to wallet 

### ISSUE THREAD

**Issue by AdnanSayyed** [mysteriumnetwork/node#5376]
**Describe the bug**
Withdrawn of the amount is not come in wallet since 48 hours passed, the wallet address is same as before were I withdrawn myst successfully

**To Reproduce**
1. Withdraw MYST to the wallet

**Expected behavior**
The amount must reflect in the wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/30722682/184524334-c4f374fe-b630-4d06-adc2-33877a28fe47.png)
![image](https://user-images.githubusercontent.com/30722682/184524343-004c01eb-017e-4933-9e75-9bface3b4d82.png)

**Environment (please complete the following information):**
 - Node version: mainnet (1.11.1-8c8ace18)
 - OS: Windows 10
 - Desktop app version (if applicable): 1.11.1
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0xc6bbb96ec18b390bf48924635001a00a4f57d113

**Additional context**
This is the second time its happening

**Comment by adinetech** [comment]
Make sure you're using the Polygon network and added the MYST token.

**Comment by AdnanSayyed** [comment]
Off course, I am using metamask

**Comment by AdnanSayyed** [comment]
withdrawn came successfully , hence closing issue
