### ISSUE TITLE
Auto settlements not being sent to saved wallet address

### ISSUE THREAD

**Issue by dansinclair25** [mysteriumnetwork/node#5385]
**Describe the bug**
1. Auto settlements are not being sent to wallet address even though it's added to the settings
2. Payouts are not appearing in my Metamask wallet, even though it's set up correctly.

**To Reproduce**
No idea how to reproduce

**Expected behavior**
My Metamask wallet address should appear in the transactions list, and the payout amount should be shown in my Metamask wallet.

**Screenshots**
Transactions list:
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/2573447/185496593-3772e332-9095-43c4-811a-60563bc7633b.png">

External wallet address:
<img width="969" alt="image" src="https://user-images.githubusercontent.com/2573447/185497110-74e5709c-4b6b-4c2d-acad-256d3e49c567.png">

**Environment (please complete the following information):**
 - Node version: mainnet (1.11.1-8c8ace18)
 - OS: RaspberryOS
 - Your identity (if applicable): 0xa8caaee0ce959323294eda12ff778faff40fc117

**Additional context**
None

**Comment by yoshikidneo** [comment]
I've encountered this same issue, the external wallet on the new UI shows as all 0's which had me concerned. I have my MYST on the polygon network, so when I go to polyscan and look up my wallet, the transaction ID's match up on the network, so I am getting my payouts even though the UI leads me to believe differently.
