### ISSUE TITLE
Memory Leak in Docker for Windows

### ISSUE THREAD

**Issue by Sendros** [mysteriumnetwork/node#5395]
Hi, I am using the windows client and the memory is endlessly growing until I restart docker for windows. you cant see the memory allocated. 

My system has 16gb ram and it will use all 16 in about 4 days of running. Then after I restart docker it goes back to 3gb in use.

I updated docker but it did not help.

Thanks in advance.

Kind regards,
Sander

**Comment by etherunit** [comment]
It's about Consumer or Provider mode on Windows? @Sendros

**Comment by Sendros** [comment]
Hi @etherunit 

If you mean if I am running a node or using vpn. I am running a node.

**Comment by xpugur** [comment]
i have the same issue (since the last update i think) ...  after this i try to limit the usage accourding to this info https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig , i made a txt file named it .wslconfig and put it at user folder, it takes longer to reach the ram limit but it does ( it was working for weeks before without problem, but now in a few days it uses all the ram:/ ) ... not sure if i did the file right tho 😅 can you send me an example file for this? (windows 10)

 i limit it to 2 gb ram but when i exit docker 4 gb ram become free( at windows start there is 2.7 gb ram available and i run 1 more app that uses around 1gb)

**Comment by etherunit** [comment]
@Sendros Apologies for the delayed reply. Do you still experience the same issue with the latest node version? If yes, could you send us with your memory profile + node logs once it grows up again? Thanks

**Comment by xpugur** [comment]
> 
for me after docker update(i thought it is related to docker update)  memeory leak kinda over (i did try to limit ram usage with .wsl file at docker but it was stil lusing a lot ram but after update problems gone but now i got other problems :/ 

  before every problem i got lots of connections with voer a day ongoing connections etc. but after latest updates (node) i only got like 3-4 sec connections :/ i go back check 5 pages of connection all of them like this 3-5 sec connections :/ .... deleted myst node, deleted container/image files at docker,  deleted .mystnode folder at user/ , restarted pc....  put myst folder to user/ from backup file, downloaded latest myst node, but at first it ask for node needs to add an exception to firewall or something like that so i say yes than black cmd screen appeared and i waited but nothing else happen stuck there :/ ...  no containers created at docker and   at user/ i saw mysterium.bin and mysterium folder other than mystnode folder... i assume it is related to version 1.16 problem?  so i wait for another update🙄

**Comment by xpugur** [comment]
nevermind it is fixed now and working,  deleted everything installed everything and used backup node folder 
WEIRD thing was myst node came with  default  "native" selected and i did not know abut it cause never needed to do something about it, but just realzie i have to select docker from menu, i have no idea if it is a new option or what is it used for ... and black cmd screen did not appear this time (with 1.17.1 version)  
and now i got longer connection sessions from clients finally :)

**Comment by Sendros** [comment]
Hi @etherunit,

I stopped using the windows client. So, if you want to troubleshoot, I can start it up. Or if not, you can close the ticket.

Sander
