### ISSUE TITLE
Error install in public KEY

### ISSUE THREAD

**Issue by ea1htb** [mysteriumnetwork/node#5401]
GPG error: http://deb.debian.org/debian unstable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 648ACFD622F3D138 NO_PUBKEY 0E98404D386FA1D9

Hi I have many errors when install mysterium node

**Comment by etherunit** [comment]
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys paste-pubkey-here
sudo apt-get update
sudo apt install myst
```

**Comment by ea1htb** [comment]
ok thanks
