### ISSUE TITLE
Cannot create a payment order

### ISSUE THREAD

**Issue by i-am-alex-smith** [mysteriumnetwork/node#5403]
**Describe the bug**
When using the TequilAPI with the `mysteriumnetwork/myst` Docker image, cannot use https://tequilapi.mysterium.network/#operation/createOrder or https://tequilapi.mysterium.network/#operation/createPaymentGatewayOrder to create an order. The API just returns `404 page not found` as text and the older versions return a 500 status code with following text: ```{"error":{"code":"err_payment_create","message":"Failed to create payment order: 404 page not found"},"status":500,"path":"/identities/:id/payment-order"}```

**Expected behavior**
The API was creating a Coingate order and returning the order information containing link, ETH amount, etc.

**Environment:**
 - Docker: [1.10.0-alpine](https://hub.docker.com/layers/myst/mysteriumnetwork/myst/1.10.0-alpine/images/sha256-91c5e54c15f57de7c031a7cf2bb11be3233b061d6d853646a021dc3f5e3c46da?context=explore)

**Comment by Guillembonet** [comment]
the endpoint is `/identities/{id}/{gw}/payment-order` (`{gw}` is coingate in your case), I see the documentation was missing that v2, [thanks](https://github.com/mysteriumnetwork/node/pull/5404) ;)

**Comment by i-am-alex-smith** [comment]
Hey, thanks for your quick response, but I'm still seeing this after adding `/v2`:
```{"error":{"code":"gateway_min_amount","message":"Failed to get minimum order amount"},"status":500,"path":"/v2/identities/:id/coingate/payment-order"}```

**Comment by Guillembonet** [comment]
> Hey, thanks for your quick response, but I'm still seeing this after adding `/v2`: `{"error":{"code":"gateway_min_amount","message":"Failed to get minimum order amount"},"status":500,"path":"/v2/identities/:id/coingate/payment-order"}`

This looks like a normal error, likely you are missing some request data or using wrong one. Check the payload sample in [the docs](https://tequilapi.mysterium.network/#operation/createPaymentGatewayOrder).

**Comment by i-am-alex-smith** [comment]
I checked it correctly, doesn't work. Is there something changed in the pilvytis service as well?
Can you please provide me with a cURL command which I can run and see the response? Thanks.

**Comment by Guillembonet** [comment]
> I checked it correctly, doesn't work. Is there something changed in the pilvytis service as well? Can you please provide me with a cURL command which I can run and see the response? Thanks.

If you provide some code of how you are calling maybe I can help you figure out what's wrong

**Comment by i-am-alex-smith** [comment]
I start the myst like this:

```nohup myst --consumer=true --ui.enable=false --tequilapi.port=7001 --script-dir="/etc/mysterium-node" daemon &```

And then unlock the identity using the password (that's working all fine).

But when I try to top up, with something like this:

```curl -X POST http://127.0.0.1:7001/v2/identities/$IDENTITY/coingate/payment-order -H 'Content-Type: application/json' -d '{"country": "US","gateway_caller_data": {},"myst_amount": "2","pay_currency": "LTC","project_id": "mysteriumvpn, mystnodes"}'``` 

it returns: ```{"error":{"code":"gateway_min_amount","message":"Failed to get minimum order amount"},"status":500,"path":"/v2/identities/$IDENTITY/coingate/payment-order"}``` 

I tested bunch of things with the parameters I'm passing like `myst_amount` = "25", or `pay_currency` = "EUR", it always returns the same thing.

**Comment by Guillembonet** [comment]
@i-am-alex-smith you must choose one of the 2 project ids, try `mysteriumvpm`, the other won't work as it is used for registration only

**Comment by i-am-alex-smith** [comment]
@Guillembonet Nope, it's still the same error:

```{"error":{"code":"gateway_min_amount","message":"Failed to get minimum order amount"},"status":500,"path":"/v2/identities/$IDENTITY/coingate/payment-order"}```

**Comment by Guillembonet** [comment]
@i-am-alex-smith tested and this works: `'{"country": "US","gateway_caller_data": {},"myst_amount": "8","pay_currency": "LTC"}'`

**Comment by i-am-alex-smith** [comment]
Yes! This works! Seems like `project_id` was the culprit. 
Just to confirm, is there a way to topup with like 2 MYST for example? Honestly, I don't have any requirement for 8 MYST on same identity, so it'll be good if I can topup with a custom MYST amount. Thanks!
