### ISSUE TITLE
Node not working even if it's completely exposed to the internet

### ISSUE THREAD

**Issue by migs35323** [mysteriumnetwork/node#5407]
**Describe the bug**
Node reports test failed 
mystnodes.com reports connection failled
the connections i receive all consume 1kb~
node setted up in a raspberry pi trough docker, using the website instructions
1gb connection, router configured as DMZ into the node, no restrictions at all

**To Reproduce**

1. have a new OS install
2. docker run --cap-add NET_ADMIN --net host --name myst -d mysteriumnetwork/myst service --agreed-terms-and-conditions
3. open the node ui PAY THE FEE THE WEBSITE DOESN'T TELL ABOUT < just saying :+1: 
4. setup the node as instructed in the node ui since the onboarding doesn't work at all
5. when node doesn't happear as offline it happears as connection failled

**Expected behavior**
receiving connections and having a healthy node

**Screenshots**

**Environment (please complete the following information):**
 - Node version: myst:latest > 1.12.2-3f735a9c
 - OS: raspi OS 64 bits, 
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): docker 20.10.17 myst:latest
 - Your identity (if applicable): [e.g. 0x724f16de83222aed258965934919e0501c881bad]
 - Payment (top-op) reference (if applicable): 6dcbec2e-413b-4ccd-8de1-a46bbd18b618

**Additional context**
I tried to contact support trough the built in chat, however i didn't get any help or possible solutions...
in the documentation has a typo about iptables but i managed to apply the correct one
while troubleshooting i even placed the node in a dmz, the node has been completly open to the internet for an entire day, 
the node ui reports that it accepts "all connection types"

**Comment by etherunit** [comment]
I can see that "Connection failed" status has been cleared out and it's working as expected now.
![Screen Shot 2022-09-05 at 08 14 08](https://user-images.githubusercontent.com/60128746/188365308-dec62ab7-3283-4b36-b955-8556bb286c40.png)
