### ISSUE TITLE
Node stopped working

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#5409]
**Describe the bug**
Yesterday the node was completely offline, both from [mystnodes.com](http://mystnodes.com/) and from node UI.
Today I see node online from mystnodes, but the GUI does not work correctly.

**Screenshots**
![NodeUI_1](https://user-images.githubusercontent.com/34000198/188140820-75cb7779-7f75-429c-aa6f-b0f04a09799c.JPG)
![NodeUI_2](https://user-images.githubusercontent.com/34000198/188140831-5af7159c-8e9f-4c78-81b6-60c133ef7c69.JPG)
![NodeUI_3](https://user-images.githubusercontent.com/34000198/188140834-aefff879-ef18-4f13-9508-ee7fe7626f00.JPG)
![NodeUI_4](https://user-images.githubusercontent.com/34000198/188140841-20021edb-f248-4e49-9e60-c85894690616.JPG)

**Environment (please complete the following information):**
 - Node version: 1.12.2
 - OS: Raspberry
 - Your identity (if applicable): 0x4e29980147340362e66c58474ec2b2d79648d0c4

**Additional context**
[myst.log](https://github.com/mysteriumnetwork/node/files/9477754/myst.log)

**Comment by lollapalooza1973** [comment]
A new set of logs.

[myst.log](https://github.com/mysteriumnetwork/node/files/9488311/myst.log)

**Comment by lollapalooza1973** [comment]
I have now removed that setting and put the node IP address in the DMZ section.

In the node UI now I see "Accepting connections: all" and "Node status: Test Failed".
Also, I'm still getting timeouts on the Node UI, and "connection failed" on [mystnodes.com](http://mystnodes.com/)
See attached screenshots.
I'm also attaching a new set of logs.
[myst.log](https://github.com/mysteriumnetwork/node/files/9489833/myst.log)

![Mystnodes](https://user-images.githubusercontent.com/34000198/188450991-43f610a1-7466-465f-954f-207db3b4f9ac.png)
![NodeUI](https://user-images.githubusercontent.com/34000198/188450998-61030c8e-7ce1-4ae4-9c60-b6efa766f292.png)

**Comment by lollapalooza1973** [comment]
I've updated the node about 20 minutes ago.
Unfortunately I still have the same issue: node UI shows "test failed", and there are timeouts.
Also, there's no session list and no chart for the last 30 days.

I'm attaching a screenshot and a new set of logs.
[myst.log](https://github.com/mysteriumnetwork/node/files/9504102/myst.log)
![screenshot](https://user-images.githubusercontent.com/34000198/188827157-5567edd6-8f65-407d-8f09-bae8279b54ea.png)

**Comment by lollapalooza1973** [comment]
@etherunit It's almost 10 days for me... nobody is taking care of my issue.

**Comment by etherunit** [comment]
@lollapalooza1973 We are looking into it. I will update you as soon as possible.

**Comment by etherunit** [comment]
From the first glance at our end, your node started to connect fail on 09/06. 
![Screen Shot 2022-09-12 at 08 44 25](https://user-images.githubusercontent.com/60128746/189581729-1b58338f-1695-4db9-8e75-ccda4d5584a8.png)
And the reason is being switch from manual to holepunching. Can you please try to switch back to manual port forwarding? Our system shows that it still using nat hole punching to establish channels.
![Screen Shot 2022-09-12 at 08 46 07](https://user-images.githubusercontent.com/60128746/189582023-48f14ea3-a13e-46fc-8bec-c9cabd6be44c.png)

**Comment by hbkwant** [comment]
Thanks, meanwhile during weekend i did a fresh install of the node with Node ID now 0x6eca3ef45b3ad900a5d8266a8a4876cf54a70a88.

Node status is now online but haven't seen any connections from last 24 Hrs, and on the portal https://mystnodes.com/nodes it says connection failed.
![image](https://user-images.githubusercontent.com/17057476/189583094-41882e8c-79e3-485c-a569-4ce809cd0571.png)



![image](https://user-images.githubusercontent.com/17057476/189582893-e0866525-5557-43a5-bca1-be9a5964c36a.png)

**Comment by hbkwant** [comment]
Manual method has priority 
![image](https://user-images.githubusercontent.com/17057476/189583365-bfdadd84-4f9c-48b6-9cc3-02514a07745b.png)

**Comment by lollapalooza1973** [comment]
> From the first glance at our end, your node started to connect fail on 09/06. ![Screen Shot 2022-09-12 at 08 44 25](https://user-images.githubusercontent.com/60128746/189581729-1b58338f-1695-4db9-8e75-ccda4d5584a8.png) And the reason is being switch from manual to holepunching. Can you please try to switch back to manual port forwarding? Our system shows that it still using nat hole punching to establish channels. ![Screen Shot 2022-09-12 at 08 46 07](https://user-images.githubusercontent.com/60128746/189582023-48f14ea3-a13e-46fc-8bec-c9cabd6be44c.png)

My node started with "connect fail" on 9th Sep without any change from my side.
Then I tried to change settings, modify the ports, etc, but this did not fix the issue.
After 2-3 days of attempts without success, I set it back to "manual", and now it's still "manual".

**Comment by lollapalooza1973** [comment]
> Thanks, meanwhile during weekend i did a fresh install of the node with Node ID now 
@hbkwant this is my thread ;-)

**Comment by hbkwant** [comment]
@lollapalooza1973 ohhh sorry man i was so involved in the issue i forgot to see its your thread.

**Comment by lollapalooza1973** [comment]
@hbkwant ;-)

**Comment by lollapalooza1973** [comment]
@etherunit here's a couple of screenshots from the configuration the node has been running with for the last 6-7 days.
![image](https://user-images.githubusercontent.com/34000198/189692575-7e7af41b-6bf1-44f5-9a2a-d666a69f99fe.png)
![image](https://user-images.githubusercontent.com/34000198/189692680-b8f290d5-4975-4916-97df-745d67372ed6.png)

**Comment by lollapalooza1973** [comment]
@etherunit I have updated the node.
Now it's on 1.15.0

But it still does not work.

**Comment by lollapalooza1973** [comment]
@etherunit do you have any news?

**Comment by etherunit** [comment]
There are several panics in go routines in the latest log output

```
 Sep 13 04:08:26 raspberry-myst myst[5742]: runtime: out of memory: cannot allocate 507510784-byte block (1106345984 in use)
Sep 13 04:08:26 raspberry-myst myst[5742]: fatal error: out of memory
Sep 13 04:08:26 raspberry-myst myst[5742]: goroutine 5815 [running]:
Sep 13 04:08:26 raspberry-myst myst[5742]: runtime.throw({0x101f0af, 0xd})
Sep 13 04:08:26 raspberry-myst myst[5742]:         /usr/lib/go-1.18/src/runtime/panic.go:992 +0x5c fp=0x41e90e0 sp=0x41e90cc pc=0x4d928
Sep 13 04:08:26 raspberry-myst myst[5742]: runtime.(*mcache).allocLarge(0x76dbc2e0, 0x1e1f8000, 0x0)

```

Memory is being consumed by some processes and therefore it evokes node crash.

**Comment by etherunit** [comment]
Check your memory usage with `htop` or `free -h` commands.

**Comment by lollapalooza1973** [comment]
@etherunit  Node runs on Raspberry 3B+ 
Installation has been done with "mistberry.zip" image, and Myst node it's the only thing running on that device.

![image](https://user-images.githubusercontent.com/34000198/190089902-dcad33b7-2b0e-4f25-8af8-a49c8adf5551.png)

**Comment by lollapalooza1973** [comment]
@etherunit 
sorted by memory:
![image](https://user-images.githubusercontent.com/34000198/190090842-6ced7288-1798-43d8-9c73-166994458bc5.png)

**Comment by etherunit** [comment]
Let's do the following
SSH to your rpi and run `sudo reboot`
Once done, I'll try connecting your node. I will ask you to submit logs once after my tests will be done.

**Comment by lollapalooza1973** [comment]
@etherunit 
I believe that myst process gets stuck for some reason, and it fills up the memory. It also goes to 100%, see below screenshot.
![image](https://user-images.githubusercontent.com/34000198/190122482-2b23f704-4356-4204-a63c-78ebeb518e9c.png)

**Comment by lollapalooza1973** [comment]
@etherunit here's the log.
[myst.log](https://github.com/mysteriumnetwork/node/files/9565173/myst.log)

And here's the htop screenshot taken right after I took the logs
![image](https://user-images.githubusercontent.com/34000198/190124777-5c8d8da3-2c32-46a3-ad3d-e8f4be8362b3.png)

**Comment by etherunit** [comment]
I checked your latest log and it contains plenty of panics there

```
Sep 14 04:08:31 raspberry-myst myst[1434]: runtime: out of memory: cannot allocate 507510784-byte block (1303445504 in use)
Sep 14 04:08:31 raspberry-myst myst[1434]: fatal error: out of memory
Sep 14 04:08:31 raspberry-myst myst[1434]: goroutine 6162 [running]:
Sep 14 04:08:31 raspberry-myst myst[1434]: runtime.throw({0x1021b2f, 0xd})
Sep 14 04:08:31 raspberry-myst myst[1434]:         /usr/lib/go-1.18/src/runtime/panic.go:992 +0x5c fp=0x38f30e0 sp=0x38f30cc pc=0x4d928
Sep 14 04:08:31 raspberry-myst myst[1434]: runtime.(*mcache).allocLarge(0x76df1790, 0x1e1f8000, 0x0)
Sep 14 04:08:31 raspberry-myst myst[1434]:         /usr/lib/go-1.18/src/runtime/mcache.go:215 +0x1e8 fp=0x38f3108 sp=0x38f30e0 pc=0x2931c
Sep 14 04:08:31 raspberry-myst myst[1434]: runtime.mallocgc(0x1e1f8000, 0xf3cb88, 0x1)
Sep 14 04:08:31 raspberry-myst myst[1434]:         /usr/lib/go-1.18/src/runtime/malloc.go:1096 +0x6b0 fp=0x38f3148 sp=0x38f3108 pc=0x1ef3c
Sep 14 04:08:31 raspberry-myst myst[1434]: runtime.growslice(0xf3cb88, {0x36874000, 0x2021800, 0x2021800}, 0x2021801)
Sep 14 04:08:31 raspberry-myst myst[1434]:         /usr/lib/go-1.18/src/runtime/slice.go:278 +0x498 fp=0x38f3170 sp=0x38f3148 pc=0x68a7c
Sep 14 04:08:31 raspberry-myst myst[1434]: github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*Cursor).first(0x38f3238)
Sep 14 04:08:31 raspberry-myst myst[1434]:         /build/myst-9Qug5C/myst-1.15.0+build638337528+focal/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/cursor.go:182 +0x120 fp=0x38f31a0 sp=0x38f3170 pc=0x8453f4
Sep 14 04:08:31 raspberry-myst myst[1434]: github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*Cursor).next(0x38f3238)
Sep 14 04:08:31 raspberry-myst myst[1434]:         /build/myst-9Qug5C/myst-1.15.0+build638337528+focal/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/cursor.go:234 +0x54 fp=0x38f31c4 sp=0x38f31a0 pc=0x845744
Sep 14 04:08:31 raspberry-myst myst[1434]: github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt.(*Cursor).Next(0x38f3238)
Sep 14 04:08:31 raspberry-myst myst[1434]:         /build/myst-9Qug5C/myst-1.15.0+build638337528+focal/go/src/github.com/mysteriumnetwork/node/vendor/go.etcd.io/bbolt/cursor.go:75 +0x30 fp=0x38f3208 sp=0x38f31c4 pc=0x844c54
Sep 14 04:08:31 raspberry-myst myst[1434]: github.com/mysteriumnetwork/node/vendor/github.com/asdine/storm/v3/index.(*UniqueIndex).RemoveID(0x31f5d50, {0x32a8600, 0x26, 0x30})
Sep 14 04:08:31 raspberry-myst myst[1434]:         /build/myst-9Qug5C/myst-1.15.0+build638337528+focal/go/src/github.com/mysteriumnetwork/node/vendor/github.com/asdine/storm/v3/index/unique.go:65 +0xa8 fp=0x38f3248 sp=0x38f3208 
```

I have also conducted more than 10 tests and all failed with:

`2022-09-14T12:56:15.596 ERR ../../../../source/tequilapi/endpoints/connection.go:203 > Failed to connect error="could not send p2p session create request: timeout waiting for reply to \"p2p-session-create\": p2p send timeout"`

The issue was added to Protocol board for further analysis on the potential memory leaks.

**Comment by lollapalooza1973** [comment]
Great @etherunit 
At least we have something.
What shall I do now?

**Comment by etherunit** [comment]
Just wait for further updates.
Apologies for any inconvenience @lollapalooza1973

**Comment by etherunit** [comment]
@lollapalooza1973 One more option to try. There might be an issue with corrupted db because of out of memory, we can try to remove it and restart a node.

1. Go to `cd /var/lib/mysterium-node/mainnet/db/ `and delete `myst.db` file
2. Restart node service

**Comment by lollapalooza1973** [comment]
Hi @etherunit  
I have deleted the file and restarted the service about 1 hour ago.
As of now, I still see the node offline on mystnodes.com
I also tried to connect from a client: node is listed, but I can't connect to it.

**Comment by etherunit** [comment]
I can confirm that your node started working again. Clearing database seemed to help.
![Screen Shot 2022-09-16 at 07 40 22](https://user-images.githubusercontent.com/60128746/190558028-25f74e3d-ed26-4507-b6ef-2c4453b2e48f.png)
![Screen Shot 2022-09-16 at 07 41 10](https://user-images.githubusercontent.com/60128746/190558081-72fdaa69-f2c7-4eed-84ca-9596f299b511.png)

**Comment by etherunit** [comment]
In the meantime, let's wait for protocol team to investigate this memory leak problem. The root cause it all happened - memory filled and caused node failure.

**Comment by lollapalooza1973** [comment]
Hi @etherunit 
Yes, I see connections again... and also node seems to be ok on mystnodes.com
Thank you
