### ISSUE TITLE
datacenter ip addresses are now marked as "connection failed" after update

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5415]
**Describe the bug**
All "datacenter" ip addresses are now marked as "connection failed". After login into the dashboard there are no apparent errors.
Nodes stopped working after myst version 1.12.2 .updated to 1.13.1 to check if that would help but without success.

0x508bb94a58b696208c99986db807360eef488a89

0xc2208126ff444c31dc53f54ccfa8a6870f3a8980

0x702592fac5234c48fdc148caca979e10a0723dcb

0xb3181b55b427f71f2b56abaf679fa3aa92a13708

0xd5075c9803fb1d187c2d954acc85b86c32643e36

**Expected behavior**
If no real changes were made, nodes shouldn't stop working

**Additional context**
Logs:

https://mystnodes.com/support/logs/2022-09-06-25e592d4-8f1f-4561-acc9-9f902a192716-mysterium-node.zip3008678114

https://mystnodes.com/support/logs/2022-09-06-8dd702a8-a152-4588-afb6-c1ff9c3418a3-mysterium-node.zip1612791439

https://mystnodes.com/support/logs/2022-09-06-f650443e-a6d9-4f34-857d-3f9251860120-mysterium-node.zip3637414529

https://mystnodes.com/support/logs/2022-09-06-322c6e9c-a026-48d1-8357-a677ae92eebc-mysterium-node.zip2049104767

https://mystnodes.com/support/logs/2022-09-06-e04fd155-befe-43d7-a0c2-ec12ae4bac59-mysterium-node.zip2014248545

**Comment by etherunit** [comment]
@isaackielma I've checked few log outputs for the reports. I found the following detail:

`2022-09-06T14:15:03.534 ERR ../../core/service/session_manager.go:187      > Session failed, disconnecting error="cannot get provider config for session a39d2f83-f08f-41cb-b594-274b3c870561: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: CreateTUN(\"myst0\") failed; /dev/net/tun does not exist"`

First thing we can do here: suggest provider to contact his cloud server provider and ask to enable TUN/TAP feature.
