### ISSUE TITLE
Node Status : Test Failed

### ISSUE THREAD

**Issue by kabirzohaib22** [mysteriumnetwork/node#5416]
**Describe the bug**
I'm Experiencing this issue from past 5 days. i have tried all the methods by restarting the node and changing internet methods. 

**Screenshots**
![image](https://user-images.githubusercontent.com/87380999/188709710-96d0814c-10db-411f-8ac0-c0f520081b9b.png)

**Environment (please complete the following information):**
 - Node version: 1.12.2
 - OS: Debian GNU/Linux 11 (bullseye)

 - Your identity (if applicable): 0xc35e91a92d88cfe6692d250268b478e81c3d9f8c
 - Payment (top-op) reference (if applicable): NIL

**Comment by lollapalooza1973** [comment]
Same issue for me.
I've raised this: https://github.com/mysteriumnetwork/node/issues/5409

**Comment by hbkwant** [comment]
Getting the issue : Node status : Test Failed from last 3 days

Node version: mainnet (1.13.1-0245c7bb)
NodeUI version: 1.17.2
ID 0x7e52414c858e9ce530f85b7bf1e177faf5692a36

![image](https://user-images.githubusercontent.com/17057476/189180546-c80a2d47-9e29-4061-9946-7a758b7c445d.png)

**Comment by isaackielma** [comment]
@kabirzohaib22 Hello there!

Do you happen to have logs so we can check them?

**Comment by kabirzohaib22** [comment]
> 

[NODE LOGS.txt](https://github.com/mysteriumnetwork/node/files/9557843/NODE.LOGS.txt)

**Comment by kabirzohaib22** [comment]
> 
[NODE LOGS.txt](https://github.com/mysteriumnetwork/node/files/9557914/NODE.LOGS.txt)

**Comment by etherunit** [comment]
<img width="750" alt="Screen Shot 2022-09-14 at 09 26 32" src="https://user-images.githubusercontent.com/60128746/190077595-a95e14c7-5cd4-41a5-b8f3-264930c64bbc.png">
It looks like UDP hole punching is used to establish a connection instead of manual port forwarding. The problem is that it doesnt work with your network,
<img width="1344" alt="Screen Shot 2022-09-14 at 09 34 15" src="https://user-images.githubusercontent.com/60128746/190077910-1db88bf9-95db-4c80-90ed-56498371a65a.png">

Please try to switch back to `manual` and see if it helps.

**Comment by kabirzohaib22** [comment]
> <img alt="Screen Shot 2022-09-14 at 09 26 32" width="750" src="https://user-images.githubusercontent.com/60128746/190077595-a95e14c7-5cd4-41a5-b8f3-264930c64bbc.png">
> It looks like UDP hole punching is used to establish a connection instead of manual port forwarding. The problem is that it doesnt work with your network,
> 
> <img alt="Screen Shot 2022-09-14 at 09 34 15" width="1344" src="https://user-images.githubusercontent.com/60128746/190077910-1db88bf9-95db-4c80-90ed-56498371a65a.png">
> 
> Please try to switch back to `manual` and see if it helps.

How do i do that, can you please guide me.

**Comment by etherunit** [comment]
Could you specify how it's currently configured in NodeUI? Go to Advanced Settings

**Comment by kabirzohaib22** [comment]
> Could you specify how it's currently configured in NodeUI? Go to Advanced Settings

![image](https://user-images.githubusercontent.com/87380999/190110727-2068d4b9-8ce4-4499-b854-ff845d9deef6.png)

**Comment by etherunit** [comment]
Thanks, could you also check it under args for myst service -- >  `cat /etc/default/mysterium-node`
Specifically DAEMON_OPTS and SERVICE_OPTS lines

**Comment by kabirzohaib22** [comment]
> Thanks, could you also check it under args for myst service -- >  `cat /etc/default/mysterium-node`
> Specifically DAEMON_OPTS and SERVICE_OPTS lines

Any updates yet ?

**Comment by Donatas-MN** [comment]
There are upcoming monitoring service changes which should help to reduce such issues. We expect them to be released next week.

@kabirzohaib22 can you also try to start completely new node on the same network? It might be related to somehow corrupted DB/config of existing node.

**Comment by kabirzohaib22** [comment]
> Thanks, could you also check it under args for myst service -- > `cat /etc/default/mysterium-node` Specifically DAEMON_OPTS and SERVICE_OPTS lines

my node is not yet fixed, it's been a month now :(

**Comment by Donatas-MN** [comment]
Have you tried to setup completely new node?

**Comment by kabirzohaib22** [comment]
> Have you tried to setup completely new node?

No i haven't yet

**Comment by Donatas-MN** [comment]
Please try. If possible on multiple devices.

**Comment by kabirzohaib22** [comment]
> Please try. If possible on multiple devices.

Tried it, still not working.

**Comment by etherunit** [comment]
guys, team did quite a few important bug fixes included in the latest node releases. Please update and check if that helps.

**Comment by lollapalooza1973** [comment]
1.19.0 is not availalbe yet via apt

**Comment by Donatas-MN** [comment]
@lollapalooza1973 @kabirzohaib22 @hbkwant Are you still experiencing "Test failed" issue?

**Comment by kabirzohaib22** [comment]
> @lollapalooza1973 @kabirzohaib22 @hbkwant Are you still experiencing "Test failed" issue?

Yes, it's been a long time now.
My node is still running,but not generating anything because of this.
It's not showing up ON

**Comment by Donatas-MN** [comment]
@kabirzohaib22 can you reinstall node from scratch with newest version and then submit logs here?

**Comment by kabirzohaib22** [comment]
[Uploading logs.txt…]()


> @kabirzohaib22 can you reinstall node from scratch with newest version and then submit logs here?

**Comment by kabirzohaib22** [comment]
> @kabirzohaib22 can you reinstall node from scratch with newest version and then submit logs here?
[nodelogs.zip](https://github.com/mysteriumnetwork/node/files/10865165/nodelogs.zip)
i have re-installed the node. couple of months earlier it was running on docker.

**Comment by etherunit** [comment]
Thanks @kabirzohaib22 . I will check your node logs and reply back.

**Comment by kabirzohaib22** [comment]
> @kabirzohaib22 can you reinstall node from scratch with newest version and then submit logs here?

i got no reply yet

**Comment by ZygintasBudrys** [comment]
@etherunit could you please update the status of this? Thank you

**Comment by etherunit** [comment]
@kabirzohaib22 Apologies for a delayed response on this ticket. Based on the previous log output and current metadata, your node is still struggling to establish p2p connections while using hole_punching (current active traversal method). Please see below:

```
ar 02 01:01:12 raspberrypi myst[826]: 2023-03-02T01:01:12.655 DBG eventbus/event_bus.go:101                > Published topic="Traversal" event={ID:remove this id Stage:hole_punching Successful:false Error:too few connections were built}
Mar 02 01:01:12 raspberrypi myst[826]: 2023-03-02T01:01:12.656 ERR p2p/listener.go:168                      > Could not ping peer error="too few connections were built"
```

I suggest to improve it by configuring on of the following traversals: UPnP, port forwarding or DMZ (in a very rare cases as in general it's not recommended due to security reasons). See the explaining article by following this [link.](https://help.mystnodes.com/en/articles/8005209-troubleshoot-connection-monitoring-fail-issues)
