### ISSUE TITLE
Funds are off 

### ISSUE THREAD

**Issue by EvilEng9** [mysteriumnetwork/node#5417]
Node:  0xdc2e3bb3b50da7ae8bff579f59fd043eea423011

On Mysterium, my node shows over 70 MYST in earnings.  But on MetaMask, it only shows 54 MYST.  I don't quite understand the transaction trials when looking into the issue.  Is there anything you can check on your end?

**Comment by n10ty** [comment]
Hi. Mysterium is not related to your personal Metamask wallet. These are 2 completely different balances. You can withdraw MYST to your Metamask wallet and they funds will be added up.
