### ISSUE TITLE
"Connection Failed" status on Node's Dashboard

### ISSUE THREAD

**Issue by shinichi85** [mysteriumnetwork/node#5419]
**Describe the bug**
On the web Mysterium Web UI (port 4449) I can see 81 sessions and 65 unique clients but none of them earn me anything. The traffic was zero.

**To Reproduce**
1. Go to https://mystnodes.com/nodes
2. The status showing "Connection failed"

**Expected behavior**
To be normal again like the others nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/8230922/189082866-af2549d2-0312-4d4c-8307-fc891f5c3520.png)

**Environment (please complete the following information):**
 - Node version: mainnet (1.13.1-0245c7bb)
 - NodeUI version: 1.17.2
 - OS: Ubuntu 18.04.6 LTS
 - Your identity (if applicable): 
   * 0xe186f9d336107cc09e0a974e27daa9478c6e9751
   * 0xc66e6e52ae71f11eb8b4e2956566ec8ac139dbd7

**Additional context**
[logfile.txt](https://github.com/mysteriumnetwork/node/files/9525427/logfile.txt)

**Comment by etherunit** [comment]
@shinichi85 This is the error I get once I'm trying to establish a connection tunnel:
 
`2022-09-12T08:56:59.245 ERR ../../../../source/tequilapi/endpoints/connection.go:203 > Failed to connect error="could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session 3b544c59-a40a-4486-b5ed-9498a877a800: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: permission denied"`

Please run the following command to quickly identify Virt type on your server machine: `virt-what`

**Comment by shinichi85** [comment]
root@localme:~# virt-what
openvz
lxc
root@localme:~# ls -l /dev/net
total 0
crwxrwxrwx 1 root root 10, 200 Sep  3 02:59 tun
root@localme:~# dmesg | grep TUN
root@localme:~# sudo modprobe tun
modprobe: FATAL: Module tun not found in directory /lib/modules/4.15.0

So the TUN device is the problem? Is there any way to install it manually because the provider said it should be okay since it's a VPS structure not shared one.

**Comment by etherunit** [comment]
OpenVZ containers (VPS) do not have access to TUN virtual device by default
most often you need to ask hosting support to enable TUN for you.

Also, [make sure that your running kernel and your kernel headers are the same version.](https://wesley.sh/solved-attempting-to-install-and-configure-wireguard-fails-with-unknown-device-type-and-fatal-module-wireguard-not-found-in-directory/)

**Comment by shinichi85** [comment]
My kernel and kernel-headers are on the same version

root@localme:~# uname --kernel-release
4.15.0
root@localme:~# apt search linux-headers-$(uname -r)
Sorting... Done
Full Text Search... Done
linux-headers-4.15.0-1004-oem/bionic 4.15.0-1004.5 amd64
  Linux kernel headers for version 4.15.0 on 64 bit x86 SMP

![image](https://user-images.githubusercontent.com/8230922/189941126-ec1fd089-c89e-451b-ba7d-81ec9b98615c.png)
Already activated the TUN adapter

Now trying to update node to 1.15.0 version but still no luck

Still finding this error and still "Connection Failed" status on dashboard
2022-09-13T15:31:53.365 DBG core/service/subscription.go:70          > Received P2P session status message for "p2p-session-connectivity-status": ConsumerID:"0xcb333a8c609bf6fb8c2ce9370aefe4dc397b1991" Code:2000 Message:"could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session d59fe870-fb9c-4ea8-9c31-077a3f30bd0b: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: permission denied"
2022-09-13T15:29:25.052 ERR core/quality/mysterium_morqa.go:209      > Failed to sign metrics event error="failed to sing metrics event: authentication needed: password or unlock"

**Comment by etherunit** [comment]
try `chmod 777 /dev/net/tun`

**Comment by shinichi85** [comment]
> try `chmod 777 /dev/net/tun`

Already did it too but still no effect

Restart service and reboot 2 times also not helping at all

![image](https://user-images.githubusercontent.com/8230922/190077499-b59b9835-a7eb-4cf3-84ff-efb72e113c29.png)

**Comment by etherunit** [comment]
Could you show the current permissions:
`ls -l /dev/net`

If your `/dev/net/tun `does not look like `# crw-rw-rw- 1 root root 10`,  run the following to recreate that special file:


`sudo rm /dev/net/tun`
`sudo mknod /dev/net/tun c 10 200
``sudo chmod 666 /dev/net/tun
`
# check again now
`ls -l /dev/net
`

**Comment by shinichi85** [comment]
root@localme:~# ls -l /dev/net
total 0
crw-rw-rw- 1 root root 10, 200 Sep 14 06:28 tun
root@localme:~# sudo rm /dev/net/tun
root@localme:~# sudo mknod /dev/net/tun c 10 200
root@localme:~# sudo chmod 666 /dev/net/tun
root@localme:~# ls -l /dev/net
total 0
crw-rw-rw- 1 root root 10, 200 Sep 14 07:30 tun

Restart the service and also reboot but still "Connection Failed"

![image](https://user-images.githubusercontent.com/8230922/190090509-e15037cb-f3d3-4508-9125-991a0457b114.png)
Wonder why still sessions and unique clients keep connecting even when "Connection Failed"

**Comment by etherunit** [comment]
@shinichi85 Please restart your node to take all changes in effect

**Comment by shinichi85** [comment]
As I mentioned before, already did restart the service and even reboot the server Sir

**Comment by etherunit** [comment]
Another option to try - for running a provider service in userspace that should not require `tun` device at all
This might help to run a provider on a limited environments.

Go to 

`nano /etc/default/mysterium-node`

Add `--userspace` to `DAEMON_OPTS=`

It should be like:

```
# Define additional args for `myst` service (see `myst --help` for full list)
CONF_DIR="--config-dir=/etc/mysterium-node"
SCRIPT_DIR="--script-dir=/etc/mysterium-node"
RUN_DIR="--runtime-dir=/var/run/mysterium-node"
DATA_DIR="--data-dir=/var/lib/mysterium-node"
DAEMON_OPTS="--keystore.lightweight --userspace"
SERVICE_OPTS="wireguard"
```

Restart node service:
`sudo systemctl restart mysterium-node.service`

**Comment by etherunit** [comment]
I'm closing this issue for now. Please feel free to reopen it once it's completed.
