### ISSUE TITLE
MYST Rewards calculations wrong

### ISSUE THREAD

**Issue by gtex007** [mysteriumnetwork/node#5420]
**Describe the bug**

The calculation of the rewards in MYST seems to be wrong in more then 17%!
Expected: 0.20 MYST - viewed: 0.17 MYST in less than 1 day.

**To Reproduce**
1) make the calculation of price per hour x hours + price per GB x GB (screenshot 2 and 4 with present prices)

Calculation
![Screenshot_2](https://user-images.githubusercontent.com/113118368/189142837-7f228265-9f8b-47a8-9cd7-2f43c3a2eb6d.jpg)

Prices:
![Screenshot_4](https://user-images.githubusercontent.com/113118368/189142845-660f4f75-c088-4be6-a40f-2504e468a3bf.jpg)

2) compare the result with the dashboard (screenshot 3)
![Screenshot_3](https://user-images.githubusercontent.com/113118368/189142839-ab81dfa1-c095-45f9-aa4c-d0b1b3306e2d.jpg)

**Expected behavior**
As far as i understand the value in the dashboard does not have the deducted feeds neither the blockchain transaction cost.
So the value shoud be 0,20 and not 0,17 at that moment

**Screenshots**
- Screenshot 2 - calculation
- Screenshot 3 - dashboard values
- Screenshot 4 - prices values

**Environment (please complete the following information):**
 - Node version: [1.13.1]
 - OS: [raspberry pi - linux raspberrypi 5.10.103-v7+ SMP armv71]
 - Your identity (if applicable): 0x6f36a698159e783a4853172801dcd5206f4f6c3b

**Additional context**
n/a

**Comment by n10ty** [comment]
Prices per Gb and per hour update every 5 minutes to tie to tie to MYST rate.
Pirce for residential Gb of traffic around 0.03-0.04$.  (depends on you location and IP type: residential or hosting)
It means that when MYST rate is **0.3$** than price will be 0.1 MYST/Gb
And when MYST rate is **0.45$** price will be 0.066MYST/Gb
