### ISSUE TITLE
myst host problem

### ISSUE THREAD

**Issue by Turangoago** [mysteriumnetwork/node#5422]
**Describe the bug**
The board has been connected and working for days, but it does not have any clients

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1280" alt="Captura de Pantalla 2022-09-09 a las 14 40 05" src="
<img width="1280" alt="Captura de Pantalla 2022-09-09 a las 14 40 05" src="https://user-images.githubusercontent.com/113173948/189353017-e7033cd5-547e-4e60-8a04-e687e12b9af9.png">
<img width="1280" alt="Captura de Pantalla 2022-09-09 a las 14 39 58" src="https://user-images.githubusercontent.com/113173948/189353025-03e24d2f-6d60-45cf-92c2-dacb19236865.png">
<img width="1280" alt="Captura de Pantalla 2022-09-09 a las 14 40 21" src="https://user-images.githubusercontent.com/113173948/189353006-caf17c71-ea68-4e6b-8dbd-cc073978c93e.png">

**Environment (please complete the following information):**
 - Node version: mainnet (1.13.1-0245c7bb)
 - OS: aspbian buster
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x03b1e0d78c9f707c064039b6b587bbde8c491f77
 - Payment (top-op) reference (if applicable): 0xe1c05CA9F517a40aF758643ED4067473331A9A4D

**Additional context**

**Comment by etherunit** [comment]
@Turangoago Unfortunately, your node is offline thus making impossible to troubleshoot it. Please turn your node on so we can continue looking into it.
I'm closing this for now, feel free to reopen it anytime.
