### ISSUE TITLE
Node installer stuck at

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5428]
**Describe the bug**
Downloaded the update from https://mystnodes.com/onboarding/desktop/windows/0 exactly one say ago for the node launcher and after installing it and running it, a Dos window keeps popping up but doesn't do anything . how can it be fixed?

**To Reproduce**
1. Go to 'https://mystnodes.com/onboarding/desktop/windows/0'
2. Click on '[Download Windows installer](https://github.com/mysteriumnetwork/myst-launcher/releases/latest/download/myst-launcher-amd64.exe) (recommended)'

**Screenshots**
<img width="1455" alt="Screenshot 2022-09-14 at 07 37 58" src="https://user-images.githubusercontent.com/84313603/190138846-52a822dd-ba50-42d3-9700-24c5b5fc7241.png">

**Environment (please complete the following information):**
 - Node version: 1.15.0
 - OS: Win 10

**Comment by Zensey** [comment]
It seems you've chosen a `Native` backend from `Node` menu.
If so then you have to remove or disable `myst` container in Docker, because two providers cannot run simultaneously.

**Comment by Zensey** [comment]
@isaackielma
Yes, you were right about terminal window showing up. 
As of 1.0.34 this is fixed.

**Comment by etherunit** [comment]
@isaackielma Any updates on it?
