### ISSUE TITLE
Incorrect values of data report shows on the Node UI.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5433]
**Describe the bug**
Data Report of the new Node UI has a bug, it shows as bytes or something else, Eg `234259372 GB` 

**To Reproduce**
1. Open the Node UI
2. Scroll down and click earnings and change it to data to see Data Report 
4. You can find the bug

**Expected behavior**
It should show the exact bandwidth/data usage of the node, Eg `2 GB` instead of `234259372 GB` etc.

**Screenshots**
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/68943180/190435234-f553235b-e6d7-4ef7-a978-fb50fcb6f672.png">

**Environment:**
 - Node version: 1.15.0
 - Node UI version: 2.0.2

**Comment by adinetech** [comment]
Updating the node to the latest version `1.17.1` didn't help.

**Comment by Ayse-AK** [comment]
@adinetech Is the issue resolved?
