### ISSUE TITLE
Incorrect data usage (transferred data)

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5434]
**Describe the bug**
The data transferred shows on the Node UI changes, it should increase but even reduce.

**Expected behavior**

**Screenshots**
Last 24 hours shows 3.01 GB transferred <img width="1311" alt="image" src="https://user-images.githubusercontent.com/68943180/190441329-0055b817-5d2b-4bfb-ab75-79c7339188f8.png">
Last 30 days shows 660.77 MB transferred <img width="1304" alt="image" src="https://user-images.githubusercontent.com/68943180/190441420-649d5695-009e-443f-b49a-a236280db677.png">

Reloaded the page twice, now Last 30 days shows 108.6 GB transferred (it seems correct, genuine) <img width="1309" alt="image" src="https://user-images.githubusercontent.com/68943180/190441810-29f74391-9e12-437a-8d91-c70325b2569a.png">

**Environment:**
 - Node version: 1.17.1
 - Node UI version: 2.0.2

**Comment by Ayse-AK** [comment]
@adinetech Are you still facing the same issue?

**Comment by adinetech** [comment]
It is resolved after updating the node, closing this issue as completed.
