### ISSUE TITLE
B2B VPN and data transfer and B2B Data Scraping turns off after restarting the node.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5435]
**Describe the bug**
B2B VPN and data transfer and B2B Data Scraping turn off after restarting the node services.

**Expected behavior**
The started pricing services should be still on even after restarting the node.

**Identity**
0x00253b64a8809513e921a6c7159643423ec88efd

**Raspberry Pi**

**Screenshots**
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/68943180/190442718-12d1a03d-d97a-4b3d-a347-4dab399789d8.png">

**Comment by Ayse-AK** [comment]
B2B services are disabled by default, this will be changed in upcoming releases and they will be enabled as well.
