### ISSUE TITLE
Public switch automatically turned on

### ISSUE THREAD

**Issue by Nitrooo** [mysteriumnetwork/node#5441]
**Describe the bug**
The Public switch is automatically turned on when updating from 1.14.0 to 1.17.2, even though it was previously disabled.
At least another user reported the same issue on Discord, updating from 1.17.0 to 1.17.1.

**To Reproduce**
- install a node <= 1.17.0.
- disable the Public switch in the UI
- update the node to >= 1.17.1

**Expected behavior**
The Public switch stays off.

**Comment by MarkWieczorek** [comment]
Its worse: clicking the "restart" node option in the node UI automatically resets "Public" to on.

**Comment by Donatas-MN** [comment]
We've reproduced the issue with service selection resets and it will be fixed soon. Meanwhile, if you used to have "whitelisting" flag ON then it means it's still ON and Public service can be left turned ON. 

With the upcoming fix and migration such changes will be done:
1. All nodes which had whitelisting ON will be migrated to new whitelisted services: B2B Data transfer and B2B Data scraping. Public service will be OFF for such users.
2. All new nodes and all existing nodes without whitelisting ON will be migrated to ALL 3 services ON.
3. Whitelisting option will be completely replaced with new B2B Data transfer and B2B Data scraping services.

**Comment by MarkWieczorek** [comment]
I can confirm that this bug has NOT been fixed in 1.17.4. After upgrading from 1.17.3->1.17.14, the "public" option was automatically turned on, even though it was off in the previous version.

**Comment by Donatas-MN** [comment]
The new node version for this fix is coming beginning of next week.

**Comment by Donatas-MN** [comment]
@MarkWieczorek can you check this with the newest 1.17.5?
