### ISSUE TITLE
Node loses identity when port forwarding

### ISSUE THREAD

**Issue by BayselGitHub** [mysteriumnetwork/node#5443]
Hey, I'm a node runner and I use docker. Whenever I try to use normal port forwarding, my node loses its identity and asks me to pay an extra dollar or deposit 0.04 myst when I go on its dashboard. None of these issues appear when I use automatic port forwarding though.

**Comment by etherunit** [comment]
Just to verify:
By "normal port forwarding" you are referring to Manual port forwarding and by "automatic port forwarding" - to uPnP, correct?
Can you please submit your node log output to check why it behaves in this way?
See here: https://docs.mysterium.network/troubleshooting/reporting-an-issue

**Comment by etherunit** [comment]
Closed due to inactivity. Feel free to reopen it in case you have an update.
