### ISSUE TITLE
New Node UI tells me to update, even though I am using the latest version

### ISSUE THREAD

**Issue by MarkWieczorek** [mysteriumnetwork/node#5445]
**Describe the bug**
A few days ago I updated my mysterium node in order to use the new UI and B2B options. After doing so (using apt-get on a raspberry pi), the node UI tells me that an update is available, even though I am using the latest release.

Node version: 1.17.1
Node UI version: 2.0.3

<img width="366" alt="Untitled" src="https://user-images.githubusercontent.com/8697285/190875026-4365f853-1528-46df-a382-5f177625f458.png">

**Comment by adinetech** [comment]
Latest node version is 1.17.2

**Comment by liamgibbins** [comment]
I have the same issue, updated and says there's a new update

**Comment by Donatas-MN** [comment]
@Ayse-AK could we update message to something like this?

Title: New version released (1.17.5)

Message: 
Your current version: 1.17.0
Click [here](https://docs.mysterium.network/for-node-runners/updating-your-node) to update to the newest version!

**Comment by Ayse-AK** [comment]
Hi guys, 
We are working on[ it.](https://github.com/mysteriumnetwork/node/issues/5455) 
Thank you

**Comment by MarkWieczorek** [comment]
This is still broken in 1.17.4
