### ISSUE TITLE
Session amounts are incorrect/flatlined session amounts not reflecting in balance

### ISSUE THREAD

**Issue by shnoah641** [mysteriumnetwork/node#5446]
**Describe the bug**
My session amounts received are completely off and flatlined and same with data being transferred some sessions showing up as kb rather than whole mb of data. And my balance is not reflecting either.
 

**To Reproduce**
1. Go to 'Node UI'
2. Click on 'History'
3. Scroll down to 'Go to page 2 and 3'

**Expected behavior**
It should be giving me the correct values.

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.17.2
 - OS: Microsoft Windows 10 Home
- Docker (if applicable): docker version : 4.12.0 (85629) and image tag : f09f417aa449aa6107eebb6ef25bbe651e9e72019c97d509aeff870a1f41f9cc
 - Your identity (if applicable): 0xf1d615dcbc059b4c6c4853c7e37254df8ae13b8f

**Additional context**
![IMG_20220917_233106528_HDR](https://user-images.githubusercontent.com/72530034/190889105-ca977b94-8226-46f5-a17b-1b11274fccba.jpg)
![IMG_20220917_232751234_HDR](https://user-images.githubusercontent.com/72530034/190889150-c3967e3c-a541-400c-ab64-613a50b4e733.jpg)
d

**Comment by rmtucker** [comment]
Totally agree with this comment,and also if you refresh the node ui,it displays a completely different set of data and sessions,And which are not mine.The only thing showing correctly is the current sessions at the bottom and the next auto settlement slider at the top.Everything else is just nonsense that is being displayed.
