### ISSUE TITLE
Identity from docker container not porting over to native backend

### ISSUE THREAD

**Issue by richmailYT** [mysteriumnetwork/node#5447]
**Describe the bug**
Balacne from docker node dosnt appear in new node running with native back end
Bug appears to be the native backend giving me a different identity

**To Reproduce**
1. Update to latest
2. Use native backend
3. Go to localhost:4449
4. Check balance

**Expected behavior**
New UI, nothing else changed

**Screenshots**
![image](https://user-images.githubusercontent.com/73596193/190902322-20988a89-06d4-4470-9baa-09da6080b86d.png)

![image](https://user-images.githubusercontent.com/73596193/190902347-76b48a0a-d411-4ab9-890d-76796f0e63c0.png)

**Environment (please complete the following information):**
 - Node version: 1.17.2
 - OS: Windows 10
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): mystnode says my identity is 0xe47e75d725b94572acaaec9381c8b27a3d76edbf but the node says my identity is 0x450808276cdbd8632d149d5602f0511d464f29f6
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
Old data from old node dosnt port over well, see #5446

**Comment by etherunit** [comment]
@richmailYT 
0x450808276cdbd8632d149d5602f0511d464f29f6 - is newly installed node service with its own id and data directory files.
0xe47e75d725b94572acaaec9381c8b27a3d76edbf - node container is turned off (not operational). You can verify that by running `docker ps` (list active containers) on your host machine.

**Comment by richmailYT** [comment]
@etherunit Can I not port over my identity from the docker container? This is a inconvience for me and for new-comers (those without technolodgy knowledge). They wouldn't know that you'd have to start the docker container manually and withdraw the myst.

**Comment by etherunit** [comment]
It's possible, please follow steps from https://docs.mysterium.network/for-node-runners/migrating-your-node

**Comment by richmailYT** [comment]
this is what I used, but its the same result. The identity gets reset after I restart the node, and I dont think the node fully thinks its using "0x45" as its identity. The MYST balance dosnt update. It shows the balance of "0x47"
