### ISSUE TITLE
Split up core/service

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#545]
We should improve the naming in core/service. Everything is a service, when what we're really providing is transports, so:

Break core/service to provider.Service, provider.TransportCreator,  provider.Transport

**Comment by zolia** [comment]
Not sure about this. Everything we look to provide is services. Our two main supported services just happed to be transports. Maybe we can abstract further and say that we have something in-common between service/transports to make new service/transports implementations more simple.

**Comment by zolia** [comment]
we already did it imho
