### ISSUE TITLE
1

### ISSUE THREAD

**Issue by PavelKeyIrk** [mysteriumnetwork/node#5457]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by PavelKeyIrk** [comment]
Can't install node on ubuntu.
after all commands I get an error.
Errors were encountered while processing:
resolvconf
myst
E: Sub-process /usr/bin/dpkg returned an error code (1)
What can be done about it?

**Comment by etherunit** [comment]
Hi @PavelKeyIrk,
There is a problem with package installer on your system. If your package database has become corrupted, reconfiguring it can quickly fix it: `sudo dpkg --configure -a`

**Comment by PavelKeyIrk** [comment]
#> Could you please let us know which exact commands were used for the installation ? If possible to paste the whole terminal output from beginning of installation until final error message that would be great!
> 
> Looking forward to your response!

Ubuntu 20.04.4 LTS 

root@node1:~# sudo add-apt-repository ppa:mysteriumnetwork/node

 More info: https://launchpad.net/~mysteriumnetwork/+archive/ubuntu/node
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease
Hit:2 http://ru.archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://ru.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://ru.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:5 http://ru.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:6 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2,113 kB]
Get:7 http://ru.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [375 kB]
Get:8 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [954 kB]
Get:9 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [218 kB]
Get:10 http://ru.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [1,740 kB]
Get:11 http://ru.archive.ubuntu.com/ubuntu focal-security/main Translation-en [292 kB]
Get:12 http://ru.archive.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [11.1 kB]
Get:13 http://ru.archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [726 kB]
Get:14 http://ru.archive.ubuntu.com/ubuntu focal-security/universe Translation-en [134 kB]
Get:15 http://ru.archive.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [15.1 kB]
Fetched 6,913 kB in 2s (4,127 kB/s)
Reading package lists... Done
root@node1:~# sudo apt-get update
Hit:1 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease
Hit:2 http://ru.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://ru.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://ru.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 http://ru.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
root@node1:~# sudo apt install myst
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libpkcs11-helper1 openvpn resolvconf wireguard wireguard-tools
Suggested packages:
  openvpn-systemd-resolved easy-rsa
The following NEW packages will be installed:
  libpkcs11-helper1 myst openvpn resolvconf wireguard wireguard-tools
0 upgraded, 6 newly installed, 0 to remove and 9 not upgraded.
Need to get 14.5 MB of archives.
After this operation, 40.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal/main amd64 myst amd64 1.17.3+build644152066+focal [13.9 MB]
Get:2 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 libpkcs11-helper1 amd64 1.26-1 [44.3 kB]
Get:3 http://ru.archive.ubuntu.com/ubuntu focal/universe amd64 resolvconf all 1.82 [54.7 kB]
Get:4 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 openvpn amd64 2.4.7-1ubuntu2.20.04.4 [476 kB]
Get:5 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe amd64 wireguard-tools amd64 1.0.20200513-1~20.04.2 [83.3 kB]
Get:6 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe amd64 wireguard all 1.0.20200513-1~20.04.2 [3,264 B]
Fetched 14.5 MB in 1s (23.0 MB/s)
Preconfiguring packages ...
Selecting previously unselected package libpkcs11-helper1:amd64.
(Reading database ... 107591 files and directories currently installed.)
Preparing to unpack .../0-libpkcs11-helper1_1.26-1_amd64.deb ...
Unpacking libpkcs11-helper1:amd64 (1.26-1) ...
Selecting previously unselected package resolvconf.
Preparing to unpack .../1-resolvconf_1.82_all.deb ...
Unpacking resolvconf (1.82) ...
Selecting previously unselected package openvpn.
Preparing to unpack .../2-openvpn_2.4.7-1ubuntu2.20.04.4_amd64.deb ...
Unpacking openvpn (2.4.7-1ubuntu2.20.04.4) ...
Selecting previously unselected package wireguard-tools.
Preparing to unpack .../3-wireguard-tools_1.0.20200513-1~20.04.2_amd64.deb ...
Unpacking wireguard-tools (1.0.20200513-1~20.04.2) ...
Selecting previously unselected package wireguard.
Preparing to unpack .../4-wireguard_1.0.20200513-1~20.04.2_all.deb ...
Unpacking wireguard (1.0.20200513-1~20.04.2) ...
Selecting previously unselected package myst.
Preparing to unpack .../5-myst_1.17.3+build644152066+focal_amd64.deb ...
Unpacking myst (1.17.3+build644152066+focal) ...
Setting up resolvconf (1.82) ...
Created symlink /etc/systemd/system/sysinit.target.wants/resolvconf.service → /lib/systemd/system/resolvconf.service.
Created symlink /etc/systemd/system/systemd-resolved.service.wants/resolvconf-pull-resolved.path → /lib/systemd/system/resolvconf-pull-resolved.path.
resolvconf-pull-resolved.service is a disabled or a static unit, not starting it.
resolvconf.postinst: Error: Cannot replace the current /etc/resolv.conf with a symbolic link because it is immutable; to correct this problem, gain root privileges in a terminal and run 'chattr -i /etc/resolv.conf' and then 'dpkg --configure resolvconf'; aborting
dpkg: error processing package resolvconf (--configure):
 installed resolvconf package post-installation script subprocess returned error exit status 1
Setting up libpkcs11-helper1:amd64 (1.26-1) ...
Setting up wireguard-tools (1.0.20200513-1~20.04.2) ...
wg-quick.target is a disabled or a static unit, not starting it.
dpkg: dependency problems prevent configuration of myst:
 myst depends on resolvconf; however:
  Package resolvconf is not configured yet.

dpkg: error processing package myst (--configure):
 dependency problems - leaving unconfigured
Setting up wireguard (1.0.20200513-1~20.04.2) ...
No apport report written because the error message indicates its a followup error from a previous failure.
         Setting up openvpn (2.4.7-1ubuntu2.20.04.4) ...
 * Restarting virtual private network daemon.                                             [ OK ]
Created symlink /etc/systemd/system/multi-user.target.wants/openvpn.service → /lib/systemd/system/openvpn.service.
Processing triggers for systemd (245.4-4ubuntu3.17) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Errors were encountered while processing:
 resolvconf
 myst
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@node1:~#

If i use  # sudo dpkg --configure -a

Setting up resolvconf (1.82) ...
resolvconf-pull-resolved.service is a disabled or a static unit, not starting it.
resolvconf.postinst: Error: Cannot replace the current /etc/resolv.conf with a symbolic link because it is immutable; to correct this problem, gain root privileges in a terminal and run 'chattr -i /etc/resolv.conf' and then 'dpkg --configure resolvconf'; aborting
dpkg: error processing package resolvconf (--configure):
 installed resolvconf package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of myst:
 myst depends on resolvconf; however:
  Package resolvconf is not configured yet.

dpkg: error processing package myst (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 resolvconf
 myst
root@node1:~#

**Comment by etherunit** [comment]
please do as the error message suggests. Gain root privileges in a terminal and run 'chattr -i /etc/resolv.conf' and then 'dpkg --configure resolvconf
