### ISSUE TITLE
B2B hardly any traffic compared to the old GUI

### ISSUE THREAD

**Issue by rossiscool123** [mysteriumnetwork/node#5461]
**Describe the bug**
Hardly any traffic in the new GUI, running my node only as B2B and not public to avoid bad actors using my internet for illegal activity (UK resident)

**To Reproduce**
1. Disable public node
2. Enable VPN and data scraping B2B

**Expected behavior**
More sessions, before the GUI update I had connections from the Netherlands constantly connected, sometimes seasons went into the weeks.

https://i.imgur.com/YDbrRqJ.png

 - Node version: 1.17.3
 - OS: Ubuntu 22.04.1 LTS
 - Your identity (if applicable): 0x40d7b054420e2ee97b899f7eb5e58ffa88a93c93

**Comment by surfercool** [comment]
Same issue with 
Node version: 1.17.3
Node UI version: 2.0.5
Microsoft Windows 10 Pro
No more connection and Monitoring failed. Setup does not change only Myst Version

**Comment by etherunit** [comment]
@rossiscool123 Well, it's clear that your node is receiving traffic via whitelisted data transfer service. 
![Screen Shot 2022-09-23 at 08 29 12](https://user-images.githubusercontent.com/60128746/191897161-10b2a47e-d756-494c-a52e-930bd60d6463.png)


@surfercool Please provide us with your node identity for further analysis.

**Comment by liamgibbins** [comment]
I have noticed a slowdown in traffic since the update aswell

**Comment by Casermandl** [comment]
i dont get any b2b traffic anymore since the update i had to enable public now i only get public traffic

**Comment by MarkWieczorek** [comment]
I can confirm this bug. Before switching to the new new node UI, I was consistently getting 30 Myst per month with the "verified partner" option on. Now, I am getting less than 1 Myst with the two B2B options selected.
