### ISSUE TITLE
Ui notification saying new version available but can't update

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#5465]
Node version:
1.17.3
Node UI version:
2.0.5
Raspberry Pi
After running the update procedure,it informs me i am already running the latest version.
![Screenshot from 2022-09-23 22-07-52](https://user-images.githubusercontent.com/6954079/192056980-f127c475-5418-4f63-8f80-82f3ddc24bbb.png)

**Comment by MarkWieczorek** [comment]
I can confirm this bug. I am running 1.17.4, which according to github is the latest version.

**Comment by mdomasevicius** [comment]
Releases to APT are delayed

**Comment by rmtucker** [comment]
Yes and No
The notification at the top of the screen seems to follow the pre-release update,But the stable version is not usually released for 4-5 days after as stated above.
At the moment it is saying that there is an update but only a pre-release version not APT.

**Comment by Ayse-AK** [comment]
@rmtucker Please make sure that you are using the latest version
