### ISSUE TITLE
External wallet address showing as null even though the transaction was Successful 

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#5466]
Node version:
1.17.3
Node UI version:
2.0.5
Raspberry pi
![Screenshot from 2022-09-23 10-18-20](https://user-images.githubusercontent.com/6954079/191930310-9c56cef1-14cc-4b09-b4e0-78162efa1704.png)
External wallet address showing as null even though the transaction was Successful and the Myst has been paid into my wallet.
If i go to settle manually my wallet address is shown correctly.

**Comment by Casermandl** [comment]
same here with new gui

**Comment by johnkennyuk** [comment]
same here
