### ISSUE TITLE
duration timer freeze and data transferred reset back to 0MB

### ISSUE THREAD

**Issue by syahpian** [mysteriumnetwork/node#5467]
**Describe the bug**
after long time user connect to the node, the duration timer freeze and data transferred reset back to 0MB, running "sudo service mysterium-node status" reveal several error "WRN services/wireguard/service/stats_publisher.go:56 > Could not get peer statistics error="file does not exist""

**To Reproduce**
1. let the node online
2. see duration timer freeze and data transferred reset to 0MB
3. run "sudo service mysterium-node status" on ssh

**Expected behavior**
there should be no duration timer freeze and data transferred reset back to 0MB when user using to the node for long time

**Screenshots**
![image](https://user-images.githubusercontent.com/12189144/192004187-5487e8fa-9685-4407-92ef-919d5c154407.png)

![image](https://user-images.githubusercontent.com/12189144/192004220-0312824c-c282-49f4-bc06-f34c91bf9f9c.png)

**Environment (please complete the following information):**
 - Node version: 1.17.3 (stable) and 1.17.4 (pre-release)
 - OS: Ubuntu Server 22.04.1 LTS on raspberry pi 4
 - OS: Ubuntu Server 20.04.5 LTS on vps

log file
node id: 0x399aad6b5c3f0e9c4147fc80fb222e63a55a7411
[log.log](https://github.com/mysteriumnetwork/node/files/9635282/log.log)
node id: 0x3058744bc80f227bcb466dc27109264052caee04
https://pixeldrain.com/u/KBmyzyWB

**Comment by SriRamTejaTelukuntla** [comment]
The same happened with my node,so I tried re-flashing os on raspberry pi and it still happens.

**Comment by mdomasevicius** [comment]
Event but - event order issues
