### ISSUE TITLE
Android SDK instructions does not help to start library

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#547]
How to reproduce:
1. Go to http://docs.mysterium.network/en/latest/user-guide/mobile-sdk/  ->  Android
2. Try to run described instructions
3. Dont find clear instructions

Expected result:
- Example for Gradle syntax + example application
- Example for ReactNative syntax

**Comment by tadovas** [comment]
ReactNative has nothing to do this this library, as this library depends only on Android standart API. Example application in docs sounds too much overhead - what exact outcome is expected? It seems this issue is more related to android app being developed, not the node repo.
