### ISSUE TITLE
Cant withdraw MYST

### ISSUE THREAD

**Issue by richmailYT** [mysteriumnetwork/node#5471]
**Describe the bug**
Wont let you withdraw your MYST, i've also tried manual withdraw but that alos didnt work.
IT just gave me the spinning circle for a little bit then dissappeared with no noticable change
I've even checked my Metamask wallet on Polygon

**To Reproduce**
1. update to 2.0
2. wait to earn myst
3. attempt to withdraw

**Expected behavior**
Withdraws without a problem

**Screenshots**

![image](https://user-images.githubusercontent.com/73596193/192162016-d75507de-6da4-4b7d-a315-42ff2c1a526d.png)

**Environment (please complete the following information):**
    Node version: 1.17.2
    OS: Windows 10
    Desktop app version (if applicable): None
    Docker (if applicable): None (native backend)
    Your identity (if applicable): None
    Payment (top-op) reference (if applicable): None

**Additional context**
None

**Comment by etherunit** [comment]
Please update your node to the latest version and if that's still happening, then submit screenshot of Developers console > Network tab at withdrawal + [node log](https://docs.mysterium.network/troubleshooting/reporting-an-issue) for review.

**Comment by richmailYT** [comment]
@etherunit 
im on lastest version

![image](https://user-images.githubusercontent.com/73596193/192891177-e910013d-ecbf-4619-9bae-dad8719a57fc.png)

**Comment by etherunit** [comment]
@richmailYT Please update your node and try again. We did quite a few changes to tackle some minor issues.
