### ISSUE TITLE
Connection instability/high drop rate

### ISSUE THREAD

**Issue by Nitrooo** [mysteriumnetwork/node#5473]
In the last few weeks the connection to the nodes, from a user standpoint, has become significantly more unstable than it used to be. Disconnections are obviously physiological, but the drop rate has increased so evidently and so consistently that there must be something wrong going on. This consideration is not based on my subjective impression, but rather it has been statistically proven for a large number of nodes over the course of the last few weeks from several different unrelated high-performance business-grade fiber connections.

I can't say for sure, but I can speculate this is related to the code changes for the UI revamp, as the issue seems to have arisen approximately around that update.

Adine is aware of the problem and asked me to open this ticket, since he gathered more evidence of the same phenomenon from other users/node runners.

Needless to say this is a huge issue. Are you devs already aware of it?

**Comment by etherunit** [comment]
@Nitrooo Thanks for reporting. Could you please provide us with node identities. It would allow us to check it directly and locate the problem easier.

**Comment by Nitrooo** [comment]
@etherunit I'm currently collecting the data you asked. I texted you on Discord, I will send you an archive with the logs tomorrow, or even earlier if you want.

**Comment by Nitrooo** [comment]
@etherunit whenever you want, I have the logs.

**Comment by etherunit** [comment]
Yes, please submit log output here. Thank you.

**Comment by Nitrooo** [comment]
I produced tons of logs, I can't paste gigabytes of data here. However, after a quick inspection (by using `grep`, mostly), every single connection seems to have failed in the way you described in your issue #5492. So, I'd say we can close this issue and if necessary re-open it after #5492 is fixed.
