### ISSUE TITLE
Cannot change beneficiary address

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5475]
**Describe the bug**
On nodeui if provider clicks on "settle now" the window will close after the next click anywhere on the screen.

Node Version: 1.17.1
Nodeui Version:  2.0.6
OS: Mac
Browser: Multiple different brwosers

**To Reproduce**
1. Go to 'nodeui'
2. Click on '.settle now'
3. Click again to see window disappearing

**Additional context**
Same issue as: https://github.com/mysteriumnetwork/node/issues/5469

**Comment by rmtucker** [comment]
Node version:
1.17.5
Node UI version:
2.0.6
I am also seeing this in the latest version as above.
And can not understand that there is no method to alter the external wallet address from the settings page?

**Comment by Loggsie** [comment]
As a temporary work around try myst cli from within MacOS terminal to set your beneficiary address

https://docs.mysterium.network/for-node-runners/mysterium-cli
