### ISSUE TITLE
Node not Working after fresh reinstall

### ISSUE THREAD

**Issue by djcrawleravp** [mysteriumnetwork/node#5477]
**Describe the bug**
0 Connections since inception

**To Reproduce**
1. Creating a fresh new node (deleting the old config files)

**Expected behavior**
Same Raspberry pi 4 using docker Ubuntu 20, same Ip address, I used to have a minimum of 4 connections all the time

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [1.17.4]
 - OS: [Ubuntu 22.04.1 LTS]
 - Docker (if applicable): 20.10.8 mysteriumnetwork/myst:latest
 - Your identity (if applicable): 0xa0f9455b6c6b053d93bd05e67fdcef3428f2ff30

**Additional context**

**Comment by etherunit** [comment]
Connection attempts failed with `2022-09-29T08:51:30.746 ERR ../../../../source/core/connection/manager.go:251    > Connect failed, disconnecting error="could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session 10e1a3ba-1e99-4096-a46c-1386375d68bd: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: CreateTUN(\"myst0\") failed; /dev/net/tun does not exist"`

Can you please specify which command was used to start container inside Ubuntu? It looks like it's missing `--device /dev/net/tun:/dev/net/tun` flag

**Comment by djcrawleravp** [comment]
I'll try that flag for a wkke and reach you back to confirm you if that was the issue.

Thanks @etherunit !

**Comment by djcrawleravp** [comment]
Update after 10 hours no single connection, my other node at the office has connections 24/7

**Comment by etherunit** [comment]
The output changed to 
`022-10-10T15:24:49.833 ERR ../../../../source/tequilapi/endpoints/connection.go:203 > Failed to connect error="could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session dab515f1-a8c6-457d-a1c7-8248ba74f2ec: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: operation not permitted"`

Try to adjust permissions: `sudo chmod 666 /dev/net/tun`

**Comment by etherunit** [comment]
`operation not permitted` error usually means you’re most like not super-user (sudo). However, you should never see this message unless you were trying to run:

`sudo chmod 666 /dev/net/tun`

You can try to re-create /dev/net/tun file. 

```
sudo rm /dev/net/tun
sudo mknod /dev/net/tun c 10 200
sudo chmod 666 /dev/net/tun
```

Once you’ve correctly re-created /dev/net/tun, you can modprobe it:

`sudo modprobe tun`

If you received an error here, there are other issues, possibly there is a network profile, service or card that is incompatible with your current kernel.
