### ISSUE TITLE
Refactor service interface

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#548]
At the moment, the service interface looks like the following:

```go
type Service interface {
	Start(providerID identity.Identity) (dto_discovery.ServiceProposal, session.ConfigProvider, error)
	Wait() error
	Stop() error
}
```

The wait seems a bit redundant, the suggestion is to remove the wait, and instead rely on a "serve"
 or run method, that blocks. We can then start it in routines if needed on the consumer side

**Comment by zolia** [comment]
I think its high priority enough, because it might change how we think about starting and using services. Lets see how we can refactor it.
