### ISSUE TITLE
No/or Bad Traffic

### ISSUE THREAD

**Issue by Delope302** [mysteriumnetwork/node#5486]
No/or Bad Traffic                              Node 1.17.5      Nude UI version 2.0.6

Germany 00:51:00 27/09/2022, 20:12:51 Public 0.00082 MYST 2.58 MB a2cf7cad
Algeria 00:04:57 27/09/2022, 19:16:56 Public 0.00225 MYST 22.91 MB 0f2ada25 
Netherlands 00:00:36 27/09/2022, 17:37:46 B2B VPN and data transfer 0.00035 MYST 42.73 MB ad4ad037
United States 00:00:22 27/09/2022, 17:25:04 Public 0.00119 MYST 24.82 MB 2a1b6554
Germany 00:31:06 27/09/2022, 17:06:12 Public 0.00060 MYST 1.49 MB c9d167d8
Singapore 00:00:00 27/09/2022, 17:00:52 B2B VPN and data transfer < 0.00001 MYST 0 Bytes d92c54b
Australia 00:00:00 27/09/2022, 16:34:08 B2B VPN and data transfer 0.00124 MYST 0 Bytes e34017cf
United States 27/09/2022, 15:55:33 B2B VPN and data transfer 0.00004 MYST 0 Bytes 82a65fa1
Netherlands 00:00:35 27/09/2022, 15:24:17 Public 0.00317 MYST 33.89 MB 66b9e362
Australia 00:00:00 27/09/2022, 15:13:43 Public 0.00230 MYST 0 Bytes 66192c79
Germany 04:19:48 27/09/2022, 05:32:20 Public 0.00438 MYST 13.24 MB 181cac2b

**Comment by cybermodz** [comment]
Same as I am on the latest version and have all the switches enabled but people connect then disconnect with no data transfer. This is the same for my b2b VPN traffic most of the connections do 0bytes of data and 0 seconds to 10 seconds of connected time. I get about 150 -200 of these no-data connections and lose money. I already have a bug report open with my exact issue. Here are some of the connections I seem to get.

![image](https://user-images.githubusercontent.com/39441384/192754058-b55b99db-be02-4f5b-8918-6f804e59538f.png)

**Comment by etherunit** [comment]
Please update your nodes to the latest version. We have released quite a few bug fixes to tackle this.
