### ISSUE TITLE
Auto settlement not working

### ISSUE THREAD

**Issue by catsado89** [mysteriumnetwork/node#5487]
Hello my Nodes don't auto settle. I have entered withdraw address and also enabled the option. Today I manually selected the option to auto settle and for some reason the withdraw was split in to few transactions? My nodes were with over 5 MYST of balance in them.

**Environment (please complete the following information):**
 - Node version: 1.17.4 also 1.17.1
 - OS: Ubuntu 20, Ubuntu 22, Windows 10
 - Desktop app version (if applicable): 1.0.34 under windows 10
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x2e4172ee8611c597f625fa9eea05e7687f81be81 , 0x922c9f91cb575f37b5982811d8a609c7d8ee18e3 , 0xec5cae1c1300ec004ab4862adf1c9ad32f3ed3da

![myst](https://user-images.githubusercontent.com/102851309/192615454-0116a172-1a11-4137-83dc-835b0d4d9a07.png)
![myst2](https://user-images.githubusercontent.com/102851309/192615459-59c2a0c6-0722-4768-bca4-95e9fae8917b.png)

**Comment by catsado89** [comment]
Well it's going on. Ty for such a great answering support.
![mystnode](https://user-images.githubusercontent.com/102851309/194812932-21014281-7951-4582-9e0f-5b17c86b8127.png)

**Comment by etherunit** [comment]
@catsado89 Apologies for a delayed reply. This issue has been fixed. Please update your node software.
