### ISSUE TITLE
Node UI 2.0: wont allow bug report

### ISSUE THREAD

**Issue by liamgibbins** [mysteriumnetwork/node#5489]
**Describe the bug**
It won't let me send a bug report from the node menu -> report bug.

Using mobile phone Samsung S21+, Samsung browser.
When selecting report a bug and you click in the email or description fields it closes the window and goes back to dash board.

**To Reproduce**
As per above

**Expected behavior**
To be able to fill in the email and description fields of the report a bug and submit a bug report via node.

**Environment (please complete the following information):**
 - Node version: 1.17.3
 - OS: ubuntu 20.04 lts
 - linux install no docker
 - Node UI: 2.0.5

**Comment by etherunit** [comment]
Update: This also true on desktop
