### ISSUE TITLE
Nose UI 2: graph does represent data transfered

### ISSUE THREAD

**Issue by liamgibbins** [mysteriumnetwork/node#5490]
**Describe the bug**
Current sessions says a different value for data than the graph

**Screenshots**
![Screenshot_20220928-115840_Samsung Internet](https://user-images.githubusercontent.com/16313132/192764629-346e77dd-618d-479f-b9a0-031aaadb4d3a.jpg)
![Screenshot_20220928-115833_Samsung Internet](https://user-images.githubusercontent.com/16313132/192764632-094de60f-ec06-4c4b-8f6f-3a2d5d9641c5.jpg)

**Environment (please complete the following information):**
 - Node version: 1.17.3
 - OS: ubuntu 20.04 lts
 - Node UI: 2.0.5

**Additional context**

**Comment by etherunit** [comment]
@liamgibbins please try to update your node to 1.17.5 and check if thats still reproducable
