### ISSUE TITLE
interface bug

### ISSUE THREAD

**Issue by dddavid51** [mysteriumnetwork/node#5491]
Hello,
I wanted to report a bug when I want to change the pickup address and I click on the little pen the window closes.
I have the same problem on bug report when I click on the email address the window closes too.
Sincerely,
David

0x522a4e1c061ebfbb8b1859e110f413d41817f4e8
1.17.3

**Comment by etherunit** [comment]
Duplicate of https://github.com/mysteriumnetwork/node/issues/5469

**Comment by etherunit** [comment]
@Ayse-AK Any updates on this one?

**Comment by Ayse-AK** [comment]
@etherunit it's on our to-do list.

**Comment by sayembara** [comment]
I'm still having the above issue today, unable to change the withdraw address. I will test again after a day or two, assuming the update requires some days to take effect.

**Comment by Ayse-AK** [comment]
@sayembara Please make sure that you are using the latest version

**Comment by sayembara** [comment]
> @sayembara Please make sure that you are using the latest version

Yes, using latest Mysterium Node launcher 1.18.3. But the issue is at http://localhost:4449/#/transactions ("Settle Now"), unable to change the withdraw wallet address. Please share the link to update this web interphase. Thanks a lot.

**Comment by sayembara** [comment]
Ok, today I tried and confirmed the address could be changed. Thanks for the quick update. Issue closed.
