### ISSUE TITLE
Monitoring failed

### ISSUE THREAD

**Issue by Ectalite** [mysteriumnetwork/node#5495]
**Describe the bug**
The monitoring failed for my node and the direct message support said I have to open a bug report because I can't send the problem through the report issue button (the report issue menu closes itself when I want to write something).

**To Reproduce**
See screenshot

**Expected behavior**
Monitoring should work.

**Screenshots**
<img width="306" alt="image" src="https://user-images.githubusercontent.com/31344054/192995527-df203022-8045-4f31-981f-8bac88742448.png">

**Environment (please complete the following information):**
 - Node version: 1.17.4
 - OS: raspbian buster
 - Desktop app version (if applicable): /
 - Docker (if applicable): /
 - Your identity (if applicable): 0x75d7dd508fd9835db48eb90d389ed43776bd7af6
 - Payment (top-op) reference (if applicable): /

**Additional context**
I already set NAT Traversal order manual on top.

**Comment by avmorales25** [comment]
i have the same issue. hope someone reply your post with an answer.

**Comment by etherunit** [comment]
Can you please open terminal and run `sudo systemctl status mysterium-node.service`

**Comment by Ectalite** [comment]
Here is the log:
[log.txt](https://github.com/mysteriumnetwork/node/files/9697530/log.txt)

**Comment by Ectalite** [comment]
I just updated the package from 1.17.4 to 1.18.3

**Comment by Ectalite** [comment]
I think everything is alright then 
![image](https://user-images.githubusercontent.com/31344054/195031165-3146c447-f661-44a7-ac44-f466cf8cb39a.png)
