### ISSUE TITLE
Balance is not updated in app state upon successful payment

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#5496]
`/events/state` does not update identity balance after successful payment.

Affected versions: 1.16.0+

> What is the payment flow/gateway: coingate, paypal? Direct channel topup?
Paypal, but others should be affected too. Except direct channel topup.

> Is this a new identity? Problem with registration? User waiting for node to be registered? Or regular topup? Both?
Both, not related to registration.

> What is the expectation? Immediately balance change?
Balance should change within a reasonable amount of time (30-60s)

> Does UI calls force balance update?
No, and it should not. Force update is only needed in direct deposit, because there is no payment order whose status can change.

**Comment by Flowrin1** [comment]
https://github.com/mysteriumnetwork/node/issues/5561 same issue no resolve after 1 year....
