### ISSUE TITLE
Different MYST earnings data shown in NodeUI

### ISSUE THREAD

**Issue by NeoOne117** [mysteriumnetwork/node#5499]
**Describe the bug**
I am on node version 1.17.5, NodeUI version 2.0.6

On the top of the NodeUI dashboard page, next to 'Next auto settlement' it shows 1.96 MYST. But on the earnings report down below, it shows 1.711 MYST as 'Total Earnings'.

This is shown when the 7 day period is selected, because the node has only been online for about 5 days 10 hours, and only the 7 day report shows the total earnings.

Why is there a different in MYST earned shown on these two different parts of the NodeUI dashboard ?

**To Reproduce**
1. Go to 'NodeUI Dashboard'
2. Check MYST earnings next to'Next auto settlement'
3. Scroll down to 'Earnings Report'
4. Total MYST earned differs in these two parts

**Expected behavior**
MYST earnings next to'Next auto settlement' and MYST earnings down below in Earnings Report must be the same.

**Screenshots**
<img width="308" alt="Screenshot 2022-09-30 at 4 07 42 AM" src="https://user-images.githubusercontent.com/41228015/193155202-b2480a4f-bf6d-4f48-b1f0-bed63a8c0d0b.png">

<img width="265" alt="Screenshot 2022-09-30 at 4 07 58 AM" src="https://user-images.githubusercontent.com/41228015/193155206-bec4a5f4-f4c6-4b42-9c99-c31818896e8d.png">

**Environment:**
 - Node version: 1.17.5
 - OS: raspios-bullseye-arm64
 - Desktop app version (if applicable): NodeUI 2.0.6
 - Docker (if applicable): Docker 20.10.18 and mysteriumnetwork/myst:latest
 - Your identity (if applicable): 0x277d0fccbcf0edf9d39da01d90fbf1f6b2e28810
 - Payment (top-op) reference (if applicable): N/A

**Additional context**
N/A

**Comment by Ayse-AK** [comment]
Hi @NeoOne117 Can you send the screenshot of the transaction page?

**Comment by NeoOne117** [comment]
> Hi @NeoOne117 Can you send the screenshot of the transaction page?

Which part exactly do you need the data/screenshot of in the transaction page ?

**Comment by cirial** [comment]
I too also have this issue.

**Comment by Ayse-AK** [comment]
@NeoOne117 does the issue still persist?

**Comment by cirial** [comment]
Yes - I've only made about 15 MYST according to the LocalUI.  However when
I check Mystnodes.com, it shows I've made over 183 MYST.  It has gotten
worse.
