### ISSUE TITLE
All stats 0 in MystNodes account after node update to 1.17.5

### ISSUE THREAD

**Issue by NeoOne117** [mysteriumnetwork/node#5500]
**Describe the bug**
After updating node version from 1.17.4 to 1.17.5, when logged into https://mystnodes.com these stats are all shown as 0 : 

Total Earnings (30 days)
Total Bandwidth (30 days)
Total Transferred (30 days)
Nodes section - Earnings (last 30 days)

**To Reproduce**
1. Go to 'https://mystnodes.com', login to account.
2. Click on 'My Nodes'
3. Check all stats

**Expected behavior**
All stats should update, showing :

Total Earnings for 30 days
Total Bandwidth for 30 days
Total Transferred for 30 days
Total Earnings per node in the node list for last 30 days (per node)

**Screenshots**
<img width="1463" alt="Screenshot_2022-09-28_at_11 41 32_PM" src="https://user-images.githubusercontent.com/41228015/193157210-a6597b70-d4f1-4aec-a3b3-5c2c632153bd.png">

**Environment:**
 - Node version: 1.17.5
 - OS: raspi-bullseye-arm64
 - Desktop app version (if applicable): NodeUI 2.0.6
 - Docker (if applicable): Docker 20.10.18, mysteriumnetwork/myst:latest
 - Your identity (if applicable): 0x277d0fccbcf0edf9d39da01d90fbf1f6b2e28810
 - Payment (top-op) reference (if applicable): N/A

**Additional context**
While on node version 1.17.4, the 'My Nodes' page showed data for all of the above. After updating node to 1.17.5, all of them went to 0.

But in the local NodeUI dashboard data is still there.

**Comment by rmtucker** [comment]
I had this problem last version and it turned out to be my ad blocker in firefox.

**Comment by NeoOne117** [comment]
> I had this problem last version and it turned out to be my ad blocker in firefox.

This was the problem. Once I whitelisted mystnode site, its showing all data now. Thanks mate :)
