### ISSUE TITLE
Hundreds of sessions but nearly all are 0 Bytes in last 24 Hours

### ISSUE THREAD

**Issue by rmtucker** [mysteriumnetwork/node#5505]
Node version:
1.17.5
Node UI version:
2.0.6
Raspberry Pi
Node has been working extremely well till the last 24 hours (averaging 5 myst every 48hrs,Now next to nothing),When suddenly getting a couple of hundred 0 byte connection especially from the netherlands?
Node id = 0xc3b9f2ca4c87009b0e273634f28db888147f7fb9
![Screenshot from 2022-10-03 18-31-47](https://user-images.githubusercontent.com/6954079/193641731-9f11c942-bb32-4592-97f8-5be45270a1cf.png)
![Screenshot from 2022-10-03 18-32-28](https://user-images.githubusercontent.com/6954079/193641733-c315e177-1f42-409c-bf8a-2ee97dbce7f7.png)

**Comment by rmtucker** [comment]
It is getting worse,it is every few minutes now.
![Screenshot from 2022-10-03 20-26-31](https://user-images.githubusercontent.com/6954079/193661937-22d9929d-e949-49e4-970c-ee3654751f1a.png)

**Comment by cybermodz** [comment]
this is the same for me I have also made a bug report with this issue and not been resolved. Here is a few of the pages with 0 bytes on them some public and b2b.

![image](https://user-images.githubusercontent.com/39441384/193664183-ed2ca51e-9f10-4509-9ea9-f1c84347aa5a.png)
![image](https://user-images.githubusercontent.com/39441384/193664216-aa8a7979-7710-40f4-9775-42bb29d0c39e.png)
![image](https://user-images.githubusercontent.com/39441384/193664244-cc79bbcc-eee7-4f30-8da8-24ab0f0fc2b2.png)

**Comment by lollapalooza1973** [comment]
Same for me. I have reported under this [issue](https://github.com/mysteriumnetwork/node/issues/5459) but I had no answer.

![image](https://user-images.githubusercontent.com/34000198/193784024-ecc73459-ee45-41c0-bd4b-c9faf0cc8844.png)

**Comment by rmtucker** [comment]
Updated to 1.18.0 this morning and the problem is still there,398 sessions but only .066 Myst?

**Comment by lollapalooza1973** [comment]
See if you are impacted by this [issue](https://github.com/mysteriumnetwork/node/issues/5508)

If the node assign the same IP address to more than one client, maybe that's the reason why they disconnect and do 0 seconds/0 bytes.

**Comment by cybermodz** [comment]
Ok, I have updated to the latest node version 1.18.1 and still receiving these connections.
![image](https://user-images.githubusercontent.com/39441384/194034921-8b2d2236-2ad0-4bac-b4a3-fe2578f25bfc.png)

**Comment by lollapalooza1973** [comment]
I have updated too, but I still get the same.
![image](https://user-images.githubusercontent.com/34000198/194035484-2d7bb64f-c090-4f51-a13f-7fbc3ad2a388.png)

**Comment by rmtucker** [comment]
version 1.18.2 still has the same problem

**Comment by liamgibbins** [comment]
Same here, getting worse as far as I can see.

<img width="1854" alt="historyerr" src="https://user-images.githubusercontent.com/16313132/194065071-a57dc02e-602b-4257-a06e-1ad1bad9b8ee.png">
