### ISSUE TITLE
error history 7 and 30days

### ISSUE THREAD

**Issue by liamgibbins** [mysteriumnetwork/node#5519]
**Describe the bug**
I just upgraded to 1.18.0 and now getting this error, when I look in history tab it started giving this error.

`Could not get provider sessions list: failed to request provider monitoring sessions list: Get "https://quality.mysterium.network/api/v3/provider/sessions?range=30d": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**To Reproduce**
1. Go to 'history,
2. Click on 7 or 30 days
3. See error

**Expected behavior**
to bring up the history without errors

**Screenshots**
![mystdash](https://user-images.githubusercontent.com/16313132/194040847-06f059d0-88c2-497e-9aa2-318052bbaff0.jpg)

<img width="1776" alt="mystlogsoct05" src="https://user-images.githubusercontent.com/16313132/194042835-9a3a4ea5-90d5-4058-924e-7f13e368dc11.png">

**Environment (please complete the following information):**
 - Node version: 1.18.0 
 - OS: ubuntu server 20.04 lts

**Comment by etherunit** [comment]
Please try to upgrade your node to 1.18.3 and see if problem remains.

**Comment by liamgibbins** [comment]
Sorry forgot to update the post.

It seems to be working 1000% better now thank you.

Not getting many issues from the node now
