### ISSUE TITLE
Raspberry Pi 4 Virgin Media hub 3

### ISSUE THREAD

**Issue by Zeke-san** [mysteriumnetwork/node#5524]
**Describe the bug**
The bug I'm experiencing is that the Raspberry Pi 4 is not being detected on my home computer network. When I sign into my router to check the connected devices I cannot see the Raspberry Pi 4 connected to the router.

The device is 100% corrected plugged in and I also cannot see the device on the Network settings in the control panel of my computer.

**To Reproduce**
Steps to reproduce the behaviour:

^^^^ not applicable because there's no error message.

**Expected behaviour**
I purchased the Raspberry Pi 4 from the partnered shop therefore it is already setup and ready to use so I expected it to work straight away out of the box because that's what the instructions say and what it is expected to do, hence why I purchased from them in the first place.

**Screenshots**

here in the screenshot you will see that the device is not viewable in the router.
[Screen Shot](https://i.imgur.com/E6fyqbM.png)

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. Raspbian buster, Debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

^^^^ I don't have this information yet as I'm new to the whole thing.

**Additional context**

**Comment by isaackielma** [comment]
Seems like an issue on your end where something might be corrupted or not working properly. Either something not properly set up on device or something in your network configuration blocking it. 

Could you please provide more info about how are you trying to connect? Are you using wifi, land cable? Are there any lights blinking on your device?

**Comment by Zeke-san** [comment]
Hi basically my raspberry pi doesn't have an IP address allocated to it and
it's saying that I need to update the software in order for start4.elf to
be compatible.

 20221009_185600.jpg
<https://drive.google.com/file/d/1gs5-fW1MwQ-W74RRsnd2QPNny0ZV9CMH/view?usp=drive_web>

here's a screenshot of the pi when I boot it up

**Comment by etherunit** [comment]
P.S. We have no access to view GD content.
I suspect it prints: `Error on boot: start4.elf is not compatible - This board requires newer software.` This in particularly means that your device is failing to boot up properly.
The problem is that the hardware has changed, the firmware in the eeprom already supports that change, but start4.elf doesn't and must be updated.
The way (suggestions) you can do it is described here: https://forums.raspberrypi.com/viewtopic.php?t=340104

**Comment by Zeke-san** [comment]
Sure sorry about that I wasn't aware you wouldn't be able to see it and yes
you're completely right that is exactly what the boot menu of the raspberry
pi is saying.
So what you're saying is that if I were to update the software I should be
able to boot up the Pi and obtain an IP address?

**Comment by etherunit** [comment]
Well, you should be able to boot up the Pi and if it's correctly booting, then it should get an IP address that you can identify locally by pinging it.
```
ping raspberrypi.local
ping raspberrypi
```

**Comment by Zeke-san** [comment]
its definitely not correctly booting. When i boot it up the pi keeps telling me to update the software "This board requires newer software" but I'm not sure how to update the software because when I plug in the pi from my computer it is not recognised from my computer.

**Comment by Zeke-san** [comment]
Will I have to buy a card reader just to update the MicroSD before I can use the raspberry pi 4?

**Comment by etherunit** [comment]
Essentially, it requires to get the new start4.elf and fixup4.dat from [https://github.com/raspberrypi/firmware ... aster/boot](https://github.com/raspberrypi/firmware/tree/master/boot) and update your disk image.
