### ISSUE TITLE
Graph not showing valid numbers since the new UI

### ISSUE THREAD

**Issue by NeoTrace82** [mysteriumnetwork/node#5526]
**Describe the bug**
checking the Graph doesn't show any valid information
while you can see I transferred 20GB the last 5h the graph isn't showing any of these values

![Bildschirmfoto 2022-10-08 um 08 18 34](https://user-images.githubusercontent.com/7862507/194692422-c83efe86-c361-4f98-b1fd-afc525d9fe27.png)
![Bildschirmfoto 2022-10-08 um 08 20 01](https://user-images.githubusercontent.com/7862507/194692438-994f496a-2fec-4cc2-b7df-763ab4da9d23.png)

**Environment (please complete the following information):**
 - Node version: 1.18.3
 - OS: Raspbian Bullseye
 - Docker: 20.10.18
 - Your identity: 0xcf645fc37d995bfeabee8fa3ccfc9b4efdd7b673

**Comment by lollapalooza1973** [comment]
Same issue here

**Comment by etherunit** [comment]
@NeoTrace82 @lollapalooza1973 Team has included this task to review in their board. Please track for further updates directly in this ticket.

**Comment by NeoTrace82** [comment]
still the same with newest release and how is it possible that over 6GB are transferred and I only earned 0.406 MYST out of it

![Bildschirmfoto 2022-10-22 um 23 49 53](https://user-images.githubusercontent.com/7862507/197363664-b7fda582-a314-4f46-8464-54863e75b2b2.png)

**Comment by etherunit** [comment]
@NeoTrace82 @lollapalooza1973

**Comment by NeoTrace82** [comment]
graphs are showing some values but nothing that would relate to the actual data
is there a chance to clear the cache by hand?

**Comment by lollapalooza1973** [comment]
Chart is still wrong
Chart shows 0.75 Myst earned in the last hour, but there's no connection with such amount.

![image](https://user-images.githubusercontent.com/34000198/201710206-784a6927-0635-46e6-9208-0a07ef4d3454.png)
![image](https://user-images.githubusercontent.com/34000198/201710440-2581fe6a-52a6-46f4-a755-dca0a8bc15b7.png)

**Comment by mdomasevicius** [comment]
@NeoTrace82 there is no way to clear this cache manually; it's purpose is to elevate request pressures. We are looking into this.

**Comment by etherunit** [comment]
I'm following up on this one. Team did some major improvements in reflecting data. Can you please check on your end @lollapalooza1973

**Comment by lollapalooza1973** [comment]
I believe that the graph still does not reflect the real data.
I had two transactions on 12th February, and I don't see that amount of Myst in the chart.
![image](https://user-images.githubusercontent.com/34000198/218711058-52d4508e-c9a1-4b49-aed5-0a9158c7c433.png)
![image](https://user-images.githubusercontent.com/34000198/218711132-0727e454-3108-4f0d-96fa-2f1d054d5c9f.png)

**Comment by etherunit** [comment]
@lollapalooza1973 We are going to improve it too. I'll give you more updates next week.

**Comment by etherunit** [comment]
@ZygintasBudrys Any updates on this one?

**Comment by ZygintasBudrys** [comment]
The way that info is being gathered will be improved which should solve issues
