### ISSUE TITLE
Getting underpaid sometimes

### ISSUE THREAD

**Issue by lollapalooza1973** [mysteriumnetwork/node#5527]
**Describe the bug**
Sometimes the earnings do not match with the price per GB and the transferred data

**Screenshots**
![2](https://user-images.githubusercontent.com/34000198/194758423-ab2bf238-28e7-44e7-b1de-fc15bf876b94.png)
![3](https://user-images.githubusercontent.com/34000198/194758426-367a96b5-800f-4336-90ce-1d5e596d87ba.png)
![1](https://user-images.githubusercontent.com/34000198/194758427-62c50b65-c325-4a62-92fc-e5f19d3350fb.png)

**Environment (please complete the following information):**
 - Node version: 1.18.3
 - Your identity (if applicable): 0x4e29980147340362e66c58474ec2b2d79648d0c4

Logs:
[myst.log](https://github.com/mysteriumnetwork/node/files/9741617/myst.log)

**Comment by lollapalooza1973** [comment]
![immagine](https://user-images.githubusercontent.com/34000198/194758771-753b4297-1eb6-44dd-bb0f-f16a57bf5b75.png)
![immagine](https://user-images.githubusercontent.com/34000198/194758801-63e916fe-2a40-4016-bde5-807a24150a66.png)

**Comment by cybermodz** [comment]
I am too getting underpaid for my earnings, for example, I have got a b2b VPN connection and they have used 34GB and paid 2.924myst but when I multiply their use and the rate it says they paid for 26GB of data, not 34GB so I am missing pay for 0.8GB. I am losing money as it is not calculating the correct values. Here is what it is showing me.

![image](https://user-images.githubusercontent.com/39441384/194764145-f5580240-1ad4-49dd-9b47-da9703a00329.png)

**Comment by lollapalooza1973** [comment]
This one also:
![immagine](https://user-images.githubusercontent.com/34000198/194767158-7767312e-970b-4364-8b1b-476983c5f9d2.png)

Price per GB is 0.1208
1.84 GB * 0.1208 = 0.222 Myst.
Earnings are 0.19.

**Comment by lollapalooza1973** [comment]
![immagine](https://user-images.githubusercontent.com/34000198/194768192-ea933e5b-65c7-4893-90aa-fea38b64a75d.png)
Another example.
Price per GB is 0.0914
Transferred data is 141 MB
Earnings is supposed to be around 0.012 Myst, bu I earned 0.00627 Myst (about half of what the client was supposed to pay).

**Comment by lollapalooza1973** [comment]
Again...
![immagine](https://user-images.githubusercontent.com/34000198/194780819-74d9ad7e-1f07-4138-ae8d-3cd5e9356a91.png)

And again...
![immagine](https://user-images.githubusercontent.com/34000198/194780860-0f11cb61-769b-4470-bb35-5e819ccbb442.png)

**Comment by lollapalooza1973** [comment]
Look at this... price was 0.1209 Myst per GB; transferred data was 10.78 GB.
Payment should be 1,303302 Myst, plus the" price per hour" that I did not take into account.
Instead, I've been paid 1,20 Myst.
>0,10 Myst less than expected...

![image](https://user-images.githubusercontent.com/34000198/194844629-0c18ae1a-2ec4-4511-aefb-6f9b46281287.png)

**Comment by n10ty** [comment]
@lollapalooza1973 do you run several nodes with one identity at the same time (Like on laptop and raspberry, for example) ?

**Comment by lollapalooza1973** [comment]
@n10ty just one node, on Raspberry. That's all.

**Comment by cybermodz** [comment]
@n10ty same issue just one node on raspberry pi 4

**Comment by n10ty** [comment]
@cybermodz  I see your ongoing session, you've posted before:
41.9Gb * 0.09MYST/Gb = 3.7 MYST. What do you see in UI now?

**Comment by cybermodz** [comment]
@n10ty this is what I got going now one that I checked. The b2b connection has done 13.8GB at 1.190myst. However, when I do that maths it shows that 1.190 is paid for 10.8GB. So they have not paid for 3GB and this has stayed like this for some time now. Here are some others I did not check and am sure that they are underpaying me.
![image](https://user-images.githubusercontent.com/39441384/194890980-1353c435-56b2-4b02-8a94-f7727bd83aaf.png)
![image](https://user-images.githubusercontent.com/39441384/194890985-1361b60c-2f3a-4f1e-8c9c-ba9650462ed6.png)

**Comment by n10ty** [comment]
@cybermodz Please consider only finished session, because you don't get paid instantly - there is a delay after bandwdith consumption

**Comment by lollapalooza1973** [comment]
@n10ty In my screenshots I have considered only sessions that were concluded since some time.

**Comment by n10ty** [comment]
There is some delay between the invoice sent and the invoice getting paid (because it's impossible to do settlement instantly for each byte of data). This delay grows over the session. It means that if the consumer will decline to pay latest invoice you will not get paid for latest invoice period. 
For long session node also guarantee provider will get paid. But there is some leeway, because data could be send but not be received, therefore not paid, for example.
We have some improvements to introduce in this area.
For now let me know if you have finished sessions underpaid more than half for example.

**Comment by lollapalooza1973** [comment]
@n10ty look here: https://github.com/mysteriumnetwork/node/issues/5527#issuecomment-1272573351
Session from Algeria lasted 24 minutes.

It paid 0.198 instead of 0.222.
It's about 10% less.
