### ISSUE TITLE
Dashboard is not showing the correct info

### ISSUE THREAD

**Issue by ramzius** [mysteriumnetwork/node#553]
At the moment dashboard is showing a lot on ongoing sessions from the same Identity and those sessions have the same download/upload stats count.
 for example those sessions 3dec5163-cd67-4d7e-9e4e-c93006e1e66a  4b87d3fe-0d08-413a-8213-44820844bdfe has the same consumer id 0xed9841459a6446044e64ba1a14498ac59b62cd7e started couple minutes apart, but has the same download/upload stats, there are more sessions like this from the same consumer ID
![image (1).png](https://images.zenhubusercontent.com/5b98365e6eb3db5743275f61/e725b505-4702-4ba5-ba06-a319f1a52655)

Something is reseting data during the session or reporting the same stats from another session during new session stats reporting, check the history of those sessions

**Comment by zolia** [comment]
This is a result of incomplete statistics verification in discovery.
Created #581 to address this issue.
