### ISSUE TITLE
Node UI - Onboarding - Set withdrawal address

### ISSUE THREAD

**Issue by Ayse-AK** [mysteriumnetwork/node#5542]
Please follow the original
Current.
![image](https://user-images.githubusercontent.com/102946394/189834755-e61254bc-5862-49f7-9ed2-9d2f2dfd1ac4.png)
Original design
![image](https://user-images.githubusercontent.com/102946394/189834835-4434c393-8f10-49dd-93b8-b3c1104e63de.png)

**Comment by mdomasevicius** [comment]
Decided to go with Primary Colored Links
