### ISSUE TITLE
Connection failed status

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5544]
**Describe the bug**
0x2d6c21725a9a69457dd40abf6331d6172d608777

Node has connection failed status even after disabling firewall and antivirus. 

https://grafana.mysterium.network/d/n3xeQlgMz/provider?orgId=1&var-provider=0x2d6c21725a9a69457dd40abf6331d6172d608777

**Environment (please complete the following information):**
 - Node version: 1.19.0
 - OS: Microsoft Windows 10 Home
 - Your identity (if applicable): 0x2d6c21725a9a69457dd40abf6331d6172d608777

**Additional context**
Logs:
https://mystnodes.com/support/logs/2022-10-13-6928936f-4295-4537-b487-3fd3cdc3b9ff-mysterium-node.zip1486081606

**Comment by etherunit** [comment]
Just made a test and its connectable.
» status
[INFO] Status:Connected
[INFO] SID:2f0fa3f1-0a0b-4464-930a-8ae8f0c8ce70
[INFO] IP:90.241.117.xxx
[INFO] Location: Cambridge, GB (residential - Vodafone Ltd)
[INFO] Proposal:Provider: 0x2d6c21725a9a69457dd40abf6331d6172d608777, ServiceType: wireguard, Country: GB

Can you please check once again?

**Comment by etherunit** [comment]
I can see that status for this node has switched to online. Please inform provider about that. Closing this case for now.
