### ISSUE TITLE
Node Connection Failed Status

### ISSUE THREAD

**Issue by jspree32** [mysteriumnetwork/node#5547]
Node running on Windows 10 in Native mode version 1.19.0.
Since the update to 1.19.0, the node status has been Connection Failed.
This node id: 0x5713a47260ff16615dca58b49919dc3f9f20c7fd

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
@jspree32 Service is not announced to discovery. Can you please provide us with your node log if possible?

**Comment by jspree32** [comment]
[mysterium-node.zip](https://github.com/mysteriumnetwork/node/files/9809708/mysterium-node.zip)


> @jspree32 Service is not announced to discovery. Can you please provide us with your node log if possible?

**Comment by jspree32** [comment]
Any update on this?
