### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Wensen1** [mysteriumnetwork/node#5548]
**Describe the bug**
After the Update to Node 1.19 5 Nodes have Connection failed Problems.

**To Reproduce**
1. Updtae Node To 1.19

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [1.19]
 - OS: [Linux Docker]
 - Desktop app version (if applicable): [Synology Docker]
 - Docker (if applicable): mysteriumnetwork/myst:Latest
 - Your identity (if applicable): [0x13d578f05c59f754eb99303dfdbdf3b7cb3adfa6]

**Additional context**
Have on 3 Synology´s the same Problem with 1.18 but they will not work. I Have an 4 Other Synology´s the Same Problem.

**Comment by etherunit** [comment]
This is the connection output: `2022-10-18T12:48:02.006 ERR ../../../../source/tequilapi/endpoints/connection.go:216 > Failed to connect error="could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session 5d70fb9a-ba67-41b8-84a5-4332e174062e: could not create provider mode wg config: could not allocate provider IP NET: no more unused subnets"`

**Comment by Wensen1** [comment]
THX but I don't understand the Problem. Is ist a Port Problem ore a Container Problem. Sorry for my stupidity.

**Comment by etherunit** [comment]
We are keep looking into this issue. Will provide an update shortly.

**Comment by catsado89** [comment]
I have the same problem. This happened if I remembered correctly with the latest update of the launcher. When first started it it asked to add some missing firewall rules and from there on my Windows nodes are with connection failed error.

**Comment by etherunit** [comment]
@catsado89 Please provide your node identity. I will check for the output,

**Comment by Wensen1** [comment]
After the Update 1.19.1 one Start working Again. The Other 7 don't Make it.

**Comment by catsado89** [comment]
> @catsado89 Please provide your node identity. I will check for the output,

0x922c9f91cb575f37b5982811d8a609c7d8ee18e3

0x2e4172ee8611c597f625fa9eea05e7687f81be81

**Comment by Wensen1** [comment]
Can it be the Router? I Use on all Locations a Fritz!Box. The Desktop Version Works Fine With the Router. The Unifi System Works fine.

**Comment by catsado89** [comment]
Issue reapearing again. Mysterium support is non existent. What a shame no response no nothing.

**Comment by etherunit** [comment]
Apologies for a delayed reply. Please note that we your nodes are online and working as expected:
<img width="766" alt="Screen Shot 2022-11-26 at 14 55 34" src="https://user-images.githubusercontent.com/60128746/204090092-ffddc047-8fa4-4235-b22a-1553c9bd9fef.png">
If you will need any extra help, feel free to reopen it anytime.
