### ISSUE TITLE
malfunctioning node

### ISSUE THREAD

**Issue by Blzs89** [mysteriumnetwork/node#5550]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
@Blzs89 Can you please describe what's the issue is?

**Comment by Blzs89** [comment]
Yes! 

Sorry for the lack of information.

So I use the latest Node vesion and after the update, my node seems like malfunctioning. 

I have significantly less connection and data transfer. Before the update i had 100 connection daily , now it is 10.

I tried to connect manually to my node via mobile app , but I cannot find in the list.

Can you please look after my node?

**Comment by Blzs89** [comment]
Environment (please complete the following information):

    Node version: 1.19.0
    OS: Win 10
    Desktop app version 
    Your identity  0xacda72065c1fbab38a1df4802186a444e665bb84
