### ISSUE TITLE
Node dropping connection and not updating stats, then freezing

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#5551]
**Describe the bug**
When using node 1.19.0, consumer keeps disconnecting/connecting to provider. At the same time, session stats are not updating properly (every second) via /events/state endpoint. After a few connects and disconnects, without any user interaction, the node stops responding, cannot even disconnect.

**To Reproduce**
1. Run app with node 1.19.0
2. Connect to any provider

Expected: connects after a few seconds (<10)
Actual: connected state is updated only after 20s

Expected: connection stats (see duration timer) are updated every second
Actual: connection stats are not updated

Expected: connection is active
Actual: connection drops soon after connecting and the node keeps reconnecting (multiple times), then freezes and does not respond to disconnect call

**Screenshots**

![Oct-19-2022 10-02-46](https://user-images.githubusercontent.com/4745368/196619867-42fc9655-9214-4784-96ee-690b9f48e1a6.gif)

**Environment (please complete the following information):**
 - Node version: 1.19.0
 - OS: macOS
 - Desktop app version (if applicable): master
 - Your identity (if applicable): 0x1a16f8bff99c3d3cf743c803c10a51e75892d64c

**Additional context**

[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/9817710/mysterium-node.log)

**Comment by tadaskay** [comment]
With node version 1.19.4, state does not change at all, not even `Connecting` when the connection is initiated. After a few moments, an error is thrown: 
```
2022-10-31T14:34:01.857 INF ../../../../source/core/connection/manager.go:397    > Cancelling connection initiation:  error="could not start new connection: failed to start connection endpoint: could not configure device: failed to create wg interface: could not setup network: could not set DNS: exit status 4"
```

**Comment by tadaskay** [comment]
Also, please link PRs when fixing issues. It helps much.

**Comment by tadaskay** [comment]
On windows, connection appears to work. But state endpoints skips 'Connecting' status. When connection is initiated, it stays in 'NotConnected' status and then after 10s changes into 'Connected'. 'Disconnecting' works fine.

**Comment by tadaskay** [comment]
```
 .\node_modules\@mysteriumnetwork\node\bin\win\x64\myst.exe --usermode daemon
 .\node_modules\@mysteriumnetwork\node\bin\win\x64\myst.exe cli
```

**Comment by andrey-mysterium** [comment]
Fix "Connecting" state update

https://github.com/mysteriumnetwork/node/pull/5605

**Comment by tadaskay** [comment]
Tested on master @ [e110960](https://github.com/mysteriumnetwork/node/commit/e11096056847cdbb5c41feee8d6a238267f52d1d).
Using daemon and CLI, connection keeps dropping and connecting. And after 'disconnect' action, it hangs and stays in connecting state forever.
```
build/myst/myst cli --tequilapi.port=44050
build/myst/myst --usermode --tequilapi.port=44050 daemon
http :44050/events/state
```

After digging further, it looks like the actual connection is working, but events/state is interchangeably returning 'connecting'/'connected' connection state. I'll send logs privately.

**Comment by andrey-mysterium** [comment]
@tadaskay Yes you are right, now I see similar flow. But week ago it work normally (without reconnections. Only skipping Connecting state). So continue problem investigation

**Comment by tadaskay** [comment]
In the latest release (1.19.6), it still does not work properly. After `Disconnecting`, it changes to `Connecting`. Should be `NotConnected`.

[state1.log](https://github.com/mysteriumnetwork/node/files/10113074/state1.log)

**Comment by andrey-mysterium** [comment]
Yes, it is like new sub task. Will fix it too.
