### ISSUE TITLE
Auto Settlement not sending to wallet address unless manually settled

### ISSUE THREAD

**Issue by tot1986** [mysteriumnetwork/node#5552]
![image](https://user-images.githubusercontent.com/116152882/196634021-a2f627f1-d6ae-4cc2-860b-dff7daf0f32b.png)

**Describe the bug**
when autosettlement runs itself it sends the myst to a 0'd wallet address and not mine, if the i manually settle then it goes to my wallet as per the attached image

**To Reproduce**
see attached picture

**Expected behavior**
myst to go to my wallet address

**Screenshots**
![image](https://user-images.githubusercontent.com/116152882/196634021-a2f627f1-d6ae-4cc2-860b-dff7daf0f32b.png)

**Environment (please complete the following information):**
 - Node version: 1.19
 - OS: Raspi
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x968f98dbadd4f278d64ec079539937cd186ea2be
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by etherunit** [comment]
Related to https://github.com/mysteriumnetwork/node/issues/5503
@tot1986 When the auto-settlement occurs, do you get the actual amount in your wallet? Can you please check that?
This 0x0000 address is just the visual outcome but actual tx is executed properly.

**Comment by 8BitStick** [comment]
@etherunit Thanks, I can confirm that is was only a visual for me.
<img width="137" alt="Screenshot 2022-10-29 at 12 00 19 pm" src="https://user-images.githubusercontent.com/75169016/198754795-12f62155-a5f8-4729-87f2-f1c35000de60.png">
<img width="138" alt="Screenshot 2022-10-29 at 12 00 26 pm" src="https://user-images.githubusercontent.com/75169016/198754804-d7cb7d3d-6ec6-4a5e-b80f-a768e91b7577.png">

**Comment by tot1986** [comment]
It would appear that it is also visual, can this be resolved as fairly disconcerting when glancing at the transactions page?
also is autowithdraw limits going to be able to be altered in the future
thanks

**Comment by etherunit** [comment]
Guys, this issue is fixed now. Please update your nodes to 1.19.4
