### ISSUE TITLE
Client connection problem.

### ISSUE THREAD

**Issue by lcbpublic** [mysteriumnetwork/node#5555]
I'm submitting this per instructions from Isaac following several e-mail exchanges.

**Describe the bug**
I'm running Node version 1.18.5 on a System76 Thelio Major (AMD CPU, Nvidia GPU, 64GiBytes RAM, 2 Gigabit Ethernet NICs, etc.) running Pop!_OS 22.04 LTS (derived from Ubuntu 22.04 LTS, derived from Debian).  This server serves as my firewall and router (as well as DNS, DHCP, etc., etc.) protecting/serving a private network behind it.  It connects to the Internet through a cable modem that is in "passthrough mode".

I downloaded your "stable" .deb package and followed the instructions on:

https://docs.mysterium.network/for-node-runners/linux-guide

to install it.  I also followed the instructions to "onboard" it.  When I started the Node I got a few very short connections which each transferred 1.01kBytes (according to the UI), then nothing.  The UI said the Node was "online" but

https://mystnodes.com/nodes

said "Connection failed".  To eliminate possible firewall issues I shut my Node down, removed all filter rules (but not NAT rules) from my Internet facing network interface, and restarted the Node.  Same result.  Over time, the Node _does_ create an 'ifb0' interface and a slew of 'mystX' interfaces.

**To Reproduce**
Well.  I doubt you'll get the same result but, to reproduce the problem:
1. Start the Node with

# systemctl start mysterium-node

2. Go to:

http://localhost:4449/#/dashboard

and note that it says "Node status  Online".

3. Go to

https://mystnodes.com/nodes

an note that it says "Connection failed" after my Node Name, and Last Seen is "-".  Version is "1.18.5", Operating System is "Pop!_OS 22.04 LTS", and IP is "98.43.37.70" which are correct.

**Expected behavior**
It should say something other than "Connection Failed" after the Node Name, and Last Seen should be some recent date and time (not just "-").

**Screenshots**
![2022 10 19_MysteriumNoldeUI_Screenshot](https://user-images.githubusercontent.com/18057328/196818447-aeb6399b-e2cc-49e6-9c04-c9227da7e4ec.png)

![2022 10 19_MysteriumMyNodes_Screenshot](https://user-images.githubusercontent.com/18057328/196818536-e26849d7-63cb-4486-abd8-fb798a9ef380.png)

**Environment (please complete the following information):**
 - Node version: 1.18.5
 - OS: Pop!_OS 22.04 LTS
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A
 - Your identity (if applicable): 0x9d11d2002ff3dc6ad0dc62485523cd03ad5e8b3e
 - Payment (top-op) reference (if applicable): N/A

**Additional context**
I'd do additional troubleshooting but documentation is inadequate (I can't even find out what port the Node listens on) and logs are minimal.  At least, as far as I can tell at this point.  Consequently, I'm going to stop my Node until I get some info about what to try next.

**Comment by etherunit** [comment]
@lcbpublic Your node is switched off. Please make sure to turn it on, so we can continue looking into it.

**Comment by lcbpublic** [comment]
Hello,

My Node is back up/online.  Surprise!  It initially showed as "online", but a
little later went to "Connection failed"!?!?  Don't know what changed.

Note: Shortly after startup I get the attached output from 'systemctl
/usr/bin/myst'.  There is one entry marked "ERR".  Don't know whether this is
significant or not.

Cheers
Leland
-- 
-------------------------------------------------------------------------------
Leland C. Best      | Creationists make it sound as though a 'theory' is
***@***.*** | something you dreamt up after being drunk all night.
                    | -- Isaac Asimov
-------------------------------------------------------------------------------

**Comment by lcbpublic** [comment]
I see many recent bugs that sound related so I'm going to shut my Node down.  I can't justify leaving all the ports on my firewall open with a malfunctioning piece of software running indefinitely on it.
