### ISSUE TITLE
Sessions with 0 Bytes of data transferred.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5562]
**Describe the bug**
Sessions with 0 Bytes of data transferred.

**Expected behavior**
The Node UI should show the exact information of the session.

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/197549889-54cb48e6-e8f1-4eea-ae8f-7f14f0969486.png)
<img width="940" alt="Screen Shot 2022-10-28 at 16 42 15" src="https://user-images.githubusercontent.com/60128746/198619379-22705b4b-737d-4d71-9578-7d4a49a41d36.png">

**Environment:**
 - Node version: 1.19.1
 - Node identity: 0xb554005f6edbc72f870dad43ea3b6829e068d5fa

**Comment by NeoOne117** [comment]
Same issue here, after updating to 1.19.2 (from 1.18.5 - didn't have this issue). Been about 12 hours after the update, I have about 30 pages (in NodeUI History section) of the same thing.

Screenshot :

<img width="1286" alt="Screenshot 2022-10-26 at 8 34 57 PM" src="https://user-images.githubusercontent.com/41228015/198158925-95f5cb61-f13a-4190-a5c9-da22bda10757.png">

**Comment by etherunit** [comment]
@adinetech @NeoOne117 We have done some fixes on superproxy side which could potentially cause this. Any improvements on your side?
