### ISSUE TITLE
Getting less quality bars and b2b connections when public is turned off.

### ISSUE THREAD

**Issue by cybermodz** [mysteriumnetwork/node#5566]
When I turn off the public option it drops the quality bars. This affects the b2b connections as I get less when my quality drops. This results in me gaining fewer b2b connections and less money.

1: Disable the public option
2: Give it a few hours and see the quality of the node drop
3: See fewer b2b connections on the node

When you disable the public option this should not result in the quality of the node dropping. This should not result in fewer b2b connections as this should not be related to the public quality.

![image](https://user-images.githubusercontent.com/39441384/197824202-6ed84911-de5e-48af-8e67-c4bb246c2836.png)
![image](https://user-images.githubusercontent.com/39441384/197824259-6849f440-7703-49db-9d86-5d640b45ea2f.png)

 - Node version: 1.19.1
 - OS: Raspbian
 - Your identity: 0x77c0ae9c4dfd5a93673ee8efb2e598e3ba74ff78

**Comment by cybermodz** [comment]
It is now getting down to 1 bar and no one is connected
![image](https://user-images.githubusercontent.com/39441384/197839267-a043f468-bcc7-4dd6-bccf-f198d4f7ccdb.png)

**Comment by etherunit** [comment]
https://discovery.mysterium.network/api/v3/proposals?&access_policy=all&provider_id=0x77c0ae9c4dfd5a93673ee8efb2e598e3ba74ff78

I see the quality has recovered. Closing this for now.
