### ISSUE TITLE
Monitoring failed

### ISSUE THREAD

**Issue by olorus** [mysteriumnetwork/node#5568]
**Describe the bug**
In Node UI Dashboard, I have in red "Monitoring failed"

**Environment (please complete the following information):**
 - Node version: 1.19.1	
 - OS: Microsoft Windows 10 Pro
 - Desktop app version (if applicable): 1.19.1

 - Your identity (if applicable): 0x7ae228a471a357dcbec3c519c18f54004c5515ea

**Comment by olorus** [comment]
It seems to be fixed with node version 1.19.4
But I still having 0 bytes connections for all B2B VPN

**Comment by olorus** [comment]
Monitoring failed again + 0 bytes B2B VPN

**Comment by iamflorencejay** [comment]
Probably same as #5588

**Comment by etherunit** [comment]
@olorus Apologies for a delayed reply.
I can confirm that your node is online and works as expected now.
<img width="768" alt="Screen Shot 2022-11-26 at 14 58 13" src="https://user-images.githubusercontent.com/60128746/204090162-be31b168-e874-4fc1-85f0-9c9404e4ee6a.png">
