### ISSUE TITLE
People cannot properly connect to my node/transfer data

### ISSUE THREAD

**Issue by Mistercoolertyper** [mysteriumnetwork/node#5575]
**Describe the bug**
Basically, i have an issue where whenever someone connects to my node, the sessions are either really short with 0 bytes transferred or the status changes to "Monitoring failed!"

**To Reproduce**
I don't really know, how to reproduce it cause i dont know, what causes it but it just happens whenever someone connects to my node

**Expected behavior**
I Expected people to be able to actually connect to my node properly and transfer data properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/84140706/198274732-715e7605-f639-4054-a41f-bbf3335e84a1.png)
![image](https://user-images.githubusercontent.com/84140706/198274803-d31826c7-1036-4664-a25f-ab07156e1a57.png)
![image](https://user-images.githubusercontent.com/84140706/198274813-ac305255-c2ef-419b-b3ff-2db93eb6b180.png)

**Environment (please complete the following information):**
 - Node version: 1.19.2(native backend selected)
 - OS: Windows 10 Pro version 22h2 (OS Buid 19045.2193)
 - Desktop app version (if applicable): 1.19.2
 - Docker (if applicable): "backend" option is selected, so i don't use docker
 - Your identity (if applicable):0x78ec44ca3e8975f3c12be5a3a33406bd39b8a464

**Additional context**
i currently have 156 sessions with a total session time of 09:59:12 and a total data transferred of 278.77 MB(for the last 24 hours i think)

EDIT:
Switched the backend to docker and it seems to work fine now, one thing i have noticed, is that there has been a lot of sessions(probably more than half my total sessions in the last 24 hours), that have been from the us and have just been really long sessions with not a lot of data transferred with the longest one being 6 hours with 238mb transferred.
I'm not sure, if this is the case, but it looks like someone is maybe automating it or something like that, since it's always connections from the us and there's basically constantly a connection from the us.

Every time, a session disconnects, there's another one from the us so i don't know, if someone is automating it, or if it's something else, because if my node was really that slow(wich i don't think, it is), then people wouldn't stay connected for multiple hours, they would just go on a different node, but they just stay connected and barely transfer any data.

**Comment by cybermodz** [comment]
same as me having 0 bytes of data with failed connections

**Comment by Peter-SovietSquirrel** [comment]
This is also happening to the node below, attached log. Version 1.19.1 & 1.19.3, only notable change has been for past 7 days data_trasfer quality was 0.399 today it has retuned to 2.025.

0x57daba353514f004c86edf2e3892740ec4d98c4d
[node_log.zip](https://github.com/mysteriumnetwork/node/files/9879503/node_log.zip)

**Comment by Mistercoolertyper** [comment]
> This is also happening to the node below, attached log. Version 1.19.1 & 1.19.3, only notable change has been for past 7 days data_trasfer quality was 0.399 today it has retuned to 2.025.
> 
> 0x57daba353514f004c86edf2e3892740ec4d98c4d [node_log.zip](https://github.com/mysteriumnetwork/node/files/9879503/node_log.zip)

how do you view the data_transfer quality? would be interesting to see, what mine is

**Comment by catsado89** [comment]
Same with me.

**Comment by Mistercoolertyper** [comment]
just a little update to the issue, it seems to work a little better with the docker backend selected, i've selected docker as a backend instead of native and now im getting some sessions with like a few mb transferred each and people seem to be able to connect to my node properly now, there is still some 0 second sessions sometimes, but it seems to work way better now

**Comment by catsado89** [comment]
> just a little update to the issue, it seems to work a little better with the docker backend selected, i've selected docker as a backend instead of native and now im getting some sessions with like a few mb transferred each and people seem to be able to connect to my node properly now, there is still some 0 second sessions sometimes, but it seems to work way better now

Yeah today I tried this option too and can confirm this way I also get some sessions and traffic.

**Comment by Mistercoolertyper** [comment]
one thing, i'm still wondering tho, is if the online and offline percentage is even correct or at least, what it counts, because i have 2 things running on my laptop rn, the first one is the mysterium node and the 2nd one is a minecraft server using the feathermc launcher. i went on my laptop via rdp like 20 mins ago or so to check on the server and the node. i noticed the server had timed out a few times(to their proxy or whatever), wich indicates that my internet probably went out for like a minute or so on my laptop, but the mysterium node statistics said 100% online 0% offline so are they not accurate or do they measure smthn else?

**Comment by Mistercoolertyper** [comment]
just a little update on the post, look at the bottom of it if you wanna read it

**Comment by etherunit** [comment]
Hey guys, we have released some minor nodes fixes which should decrease the amount of 0 bytes sessions.
Do you still experience this issue?

**Comment by Mistercoolertyper** [comment]
> Hey guys, we have released some minor nodes fixes which should decrease the amount of 0 bytes sessions. Do you still experience this issue?

i haven't been experiencing the issues since i switched the backend option to docker mode, i could try using native again to see, if it's fixed tho

**Comment by etherunit** [comment]
Yes, it's fixed.

**Comment by catsado89** [comment]
Sadly the damage is done. Our nodes are with low quality rating now and I don't get connections like before the problem...
