### ISSUE TITLE
Node UI shows last 24 hour earnings for 7 days and 30 days

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5576]
**Describe the bug**
Node UI shows the last 24-hour earnings for 7 days and 30 days

**Expected behavior**
Total earnings shouldn't show the same for the last 24 hours, 7 days, and 30 days however, the graph seems fine.

**Screenshots**

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/68943180/198300198-01ca6552-f2bd-48b3-bc8b-a60bb91fae17.png">
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/68943180/198300328-f9aedafe-3dfc-4dea-b761-659c1dd8a333.png">
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/68943180/198301832-8e88bba9-5d04-4603-8583-e283b1b3cbfd.png">

**Error found in the Developer Console:**
`main.36fe3128.js:2          GET http://192.168.0.5:4449/tequilapi/node/provider/sessions?range=30d 500 (Internal Server Error)`

**Environment:**
 - Node version: 1.19.1
 - Node UI version: 2.2.0
 - OS: Raspbian bullseye
 - Your identity: 0x0133f1ab7be3ee6b9b9286a3e894dc345014edd2

**Output of Developer Console:**

![image](https://user-images.githubusercontent.com/68943180/198593240-12257739-8189-4bcf-b4ae-3bdbaa7d1f0e.png)

**Additional context**
It should show the data of the last 7 days and 30 days, whenever we (node runners) click it.

**Comment by mdomasevicius** [comment]
@adinetech can you reproduce this?

It is likely due to this failure:


![Image](https://user-images.githubusercontent.com/20511486/200844471-061cff8f-86e1-4d3a-9682-7c6f8c7a16ba.png)

There were some issues when requests used to fail to our infra but I think they have been resolved
https://user-images.githubusercontent.com/20511486/200844358-308baa39-9307-4360-9078-10e5e3086798.webm

**Comment by andrey-mysterium** [comment]
It look like id : 0x0133f1ab7be3ee6b9b9286a3e894dc345014edd2  is not valid yet

I can't get any info for this provider id:

https://grafana.mysterium.network/d/n3xeQlgMz/provider?orgId=1&var-provider=0x0133f1ab7be3ee6b9b9286a3e894dc345014edd2&var-service_type=All

So 500 error is just show that we have  data request timeout
