### ISSUE TITLE
mystnodes.com shows as offline and earnings as 0 MYST

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5577]
**Describe the bug**
mystnodes.com should as offline (sometimes) and earnings as 0 MYST.

**Expected behavior**
mystnodes.com shouldn't show as offline as there is an ongoing session, so the node is up and running and after some time it shows 0 MYST.

**Troubleshooting**
I asked the provider to check/try on the incognito/private and checked it myself but it still shows 0 MYST.

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/198303815-8a70e649-07e8-4a8c-99e2-72a93297a79c.png)

**Environment:**
 - Node version: 1.19.1
 - Provider's Identity: 0x34f9bbe5b8a2c6274b868056b95a2a6c95d1d8ee

**Comment by MinerGuy62** [comment]
I am also experiencing this issue

**Comment by speedf1** [comment]
Same error for me as well.

**Comment by isaackielma** [comment]
"Even after erasing the cookie and the cache date but the problem was the same"

**Comment by alexgenson** [comment]
I’m having the same issue on a desktop browser, however a mobile browser works as expected.

**Comment by dmitrijrub** [comment]
same problem

**Comment by Ayse-AK** [comment]
Hi guys, we made a release on Friday, Is it fixed on your end now?

**Comment by speedf1** [comment]
Yes, now showing MYST value
