### ISSUE TITLE
The provider is getting identity not loaded error while reloading the Node UI

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5578]
**Describe the bug**
The provider is getting an identity not loaded error while reloading the Node UI and the main problem is the sessions are being disconnected/interrupted once this error appears for several Milliseconds.

**To Reproduce**
1. Open Node UI on any browser.
2. The error will be shown, please check the screenshot.

**Expected behavior**
The process of reloading the node UI should be smooth, optimize it. 

**Troubleshooting**
1) Ask the provider to update the node version - done
2) Check the live logs to find out issues during reloading the node UI process.

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/198307308-924c4cef-263f-4e59-815e-90a9b26ea92c.png)

**Environment:**
 - Node version: 1.19.1
 - OS: Native Linux
 - Provider's identity: 0xb554005f6edbc72f870dad43ea3b6829e068d5fa

**Comment by mdomasevicius** [comment]
@adinetech these reproduction steps work for you?

**Comment by mdomasevicius** [comment]
@adinetech need Node logs when this is happening

**Comment by adinetech** [comment]
Sure, I'll send the node logs if I find someone reporting about the same, the provider who reported is stopped running the node for some reason.

**Comment by isaackielma** [comment]
Not entirely sure if the same issue because I could not confirm with the user, but here is what I could find.

Error message: Identity not loaded

Logs:

https://mystnodes.com/support/logs/2022-11-02-6af11007-ef37-4d56-a6ba-fa1647dab8ef-mysterium-node.zip204322054
