### ISSUE TITLE
Switch to make public not working

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5579]
**Describe the bug**

Switch to make public doesn't work , even after updating to last version and after restarting , if someone tries to connect to node they get this error : cannot start session , consumer identity is not allowed. even when the "public" option turned on.

This node was always set to "only verified traffic" from months , yesterday it was to set to allow public service, after activating the public button on the UI dashboard, when someone tries to connect to it via linux it says "failed to connect : could not send p2p session create request: peer error : cannot start session : consumer identity not allowed" and on windows or phone app instead, the node doesn't even appear on the list! After 12 hours , rebooted 4-5 times and still nothing. After trying to make a new node same problem , it doesn't come out on the list and not even test connections happens after waiting hours , which is strange because connection tests happens after a while you create a new node and everything works good.

**To Reproduce**
1. Go to 'nodeUI'
2. Click on 'enable "public" service'
3. Go to app 'attempt connection'

**Expected behavior**
Node should be visible when allowed public service.

**Screenshots**
<img width="1373" alt="Screenshot 2022-10-28 at 08 26 20" src="https://user-images.githubusercontent.com/84313603/198576834-8b0a0382-766e-41cc-be83-d8c7647cffc4.png">

**Environment (please complete the following information):**
 - Node version: 1.9.2
 - OS: Ubuntu
 - Your identity (if applicable): 0xed719888ef7309cb46af6a9a98fc05d9a47dc4b8

**Additional context**
Logs:

https://mystnodes.com/support/logs/2022-10-27-3f2fcf5d-42c4-42af-99f3-1de7fa83bce5-mysterium-node.zip1560175911

**Comment by etherunit** [comment]
@isaackielma Suggest to restart node after applying changes. Discovery shows that scrapping and data_transfer services are activated only: https://discovery.mysterium.network/api/v3/proposals?&access_policy=all&provider_id=0xed719888ef7309cb46af6a9a98fc05d9a47dc4b8

**Comment by ec2samu** [comment]
hello it's me , the person who had this issue , no... rebooting didn't helped , i even tried to make anew node and the problem is still there. i'm also noticing a continuous decrease of public nodes day by day , i think the bug is slowly spreding to everyone.

**Comment by isaackielma** [comment]
Rebooting app did not help
