### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by skapytek** [mysteriumnetwork/node#5580]
Ive uninstalled via "apt remove myst"
I can still access the node. Just seeing this error:
"Looks like your node is unreachable... 😭"

How to completely uninstall myst and all nodes?

**Comment by etherunit** [comment]
How to uninstall (reinstall) a Mysterium node?

For Linux node:

1. Firstly, check out for the name of the package you want to remove: dpkg --list 
2. Then remove the given package: sudo apt-get remove package_name
3. Purge any related code: sudo apt-get purge package_name
4. Finally, do a clean so you check everything is correctly removed: sudo apt-get clean

Or just use this all-in-one command: sudo apt-get --purge remove <package> where <package> is the name of the package you want to uninstall. Once done, install a fresh copy of Mysterium's software.

**Comment by isaackielma** [comment]
If user has installed node with windows installer. Which commands from CMD would be able to delete node like the commands for linux above?

**Comment by etherunit** [comment]
@isaackielma 

For native backend:
- uninstall Mysterium Launcher
- del %USERPROFILE%\.mysterium-bin\*.exe

For docker backend:
- open docker desktopm -> containers, delete myst container
