### ISSUE TITLE
Cannot delete node in https://mystnodes.com/nodes

### ISSUE THREAD

**Issue by sradas** [mysteriumnetwork/node#5581]
**Describe the bug**
When try to delete unused node in https://mystnodes.com/nodes list, nothing happens. A menu is displayed, but seems nothing is executed.

**To Reproduce**
1. Go to https://mystnodes.com/nodes
2. Click on "..." menu 
3. Scroll down to "Delete node"
4. Nothing happens, node is still listed, even after a few days

**Expected behavior**
Node should be deleted immediately or message should be about expected timeline for deletion

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.0.11, 1.0.14
 - OS: buster
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [API: xI6Tq9uoq2VIjqAMrYc0zsqIqUPS3MWkFphxs2U1]
 - Payment (top-op) reference (if applicable):

**Additional context**
Tried in Firefox and Edge browsers, last versions

**Comment by isaackielma** [comment]
Moving this issue to mystnodes.com repo instead for better organisation. For any updates or news please go to: https://github.com/mysteriumnetwork/mmn/issues/517 

Furthermore, our beloved Product Owner @Ayse-AK has informed us that the issue should be resolved in a few days 😉

**Comment by Ayse-AK** [comment]
Hi @sradas we are on leave now. This issue will be fixed in a couple of days. I'll let you know when it is fixed.
