### ISSUE TITLE
"Underpaid" sessions error

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5583]
**Describe the bug**
Providers believe they are being underpaid according to session history stats on mystnodes.com. Team has probably heard of issues like this before. We in support believe this issue may be happening because we are not including session start price in the history stats.

If we check node UI data does not match. However, when checking it from logs, or consumer data the price matches data transferred. which is less than what is displayed on node UI. Hopefully the screenshots below can illustrate the issue better than my explanation

**To Reproduce**
1. Go to 'node ui during session'
2. Click on 'history'
3. Scroll down to 'ongoing session'
4. See discrepancy

**Expected behavior**

We need the session start price in the history.

**Screenshots**
<img width="701" alt="Screenshot 2022-11-02 at 13 58 50" src="https://user-images.githubusercontent.com/84313603/199555006-94767489-e9c5-4fc2-83e7-b0536df33d33.png">
<img width="766" alt="Screenshot 2022-11-02 at 13 59 48" src="https://user-images.githubusercontent.com/84313603/199555010-a0bc0ba0-6706-408c-acf1-85621587e1b6.png">
<img width="738" alt="Screenshot 2022-11-02 at 14 00 52" src="https://user-images.githubusercontent.com/84313603/199555012-73b65c4c-e5d2-4c96-844a-322a09470037.png">

**Environment (please complete the following information):**
 - Node version: latest
 - OS: any
 - Desktop app version (if applicable): latest

**Comment by etherunit** [comment]
@andrey-mysterium Any insights on this one?

**Comment by etherunit** [comment]
@isaackielma It's not bug, but the way its handling GB calculation. It should be fixed by https://github.com/mysteriumnetwork/node/issues/5585
