### ISSUE TITLE
External Wallet address change failed settlement fees exceed earning amount. Please provide more service and try again. Current earnings: 3104037216585545, current fees: 48355021435317109: fee not covered, cannot continue

### ISSUE THREAD

**Issue by strongbow1** [mysteriumnetwork/node#5586]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by isaackielma** [comment]
How much do you have in your balance in total? It looks like the error is because of insufficiency of funds.

**Comment by strongbow1** [comment]
I have made 4 transactions since this message appeared. This message is from a Transaction that never finished. When I tried to manually transfer, I had 4.79 Myst. Now that Balance is GONE, never made it to my external wallet, and now I have the Error since then. And no support is helping me. I sent out numerous emails explaining exactly, and no one has a clue.

**Comment by isaackielma** [comment]
User logs for investigation:


https://mystnodes.com/support/logs/2022-11-10-660f565b-b6e7-4cab-a206-4baea0774fe4-mysterium-node.zip1957827353


<img width="484" alt="Screenshot 2022-11-14 at 12 45 56" src="https://user-images.githubusercontent.com/84313603/201703510-7c33a0a3-d684-4c5c-8115-690896ce9af2.png">

**Comment by strongbow1** [comment]
So, No one is helping with this anymore? I still have missing Myst and a failed transaction, and it's not going away. When will you resolve my issue and reimburse me the missing Myst I lost?

> User logs for investigation:
> 
> https://mystnodes.com/support/logs/2022-11-10-660f565b-b6e7-4cab-a206-4baea0774fe4-mysterium-node.zip1957827353
> 
> <img alt="Screenshot 2022-11-14 at 12 45 56" width="484" src="https://user-images.githubusercontent.com/84313603/201703510-7c33a0a3-d684-4c5c-8115-690896ce9af2.png">

**Comment by Guillembonet** [comment]
https://polygonscan.com/address/0x7B10088Cc373a10BC3b72bB69D94302a8508A742#tokentxns looks like it works now

**Comment by strongbow1** [comment]
> https://polygonscan.com/address/0x7B10088Cc373a10BC3b72bB69D94302a8508A742#tokentxns looks like it works now

The issue still remains.. I Still have the Error and I still have missing transaction of 5 myst. so the issue is NOT resolved

**Comment by Guillembonet** [comment]
> > https://polygonscan.com/address/0x7B10088Cc373a10BC3b72bB69D94302a8508A742#tokentxns looks like it works now
> 
> The issue still remains.. I Still have the Error and I still have missing transaction of 5 myst. so the issue is NOT resolved

can you paste the transaction ID of the missing settlement?

**Comment by strongbow1** [comment]
> > > https://polygonscan.com/address/0x7B10088Cc373a10BC3b72bB69D94302a8508A742#tokentxns looks like it works now
> 
> > 
> 
> > The issue still remains.. I Still have the Error and I still have missing transaction of 5 myst. so the issue is NOT resolved
> 
> 
> 
> can you paste the transaction ID of the missing settlement?

There is no transaction ID that is what I made PRETTY CLEAR but no one cares!! Since the failed transaction i have the error message and missing Mysterium in my external wallet! And if you actually read up on the problem and not just closed it you would have know but you just assumed without getting in contact with me!!

**Comment by strongbow1** [comment]
> > > https://polygonscan.com/address/0x7B10088Cc373a10BC3b72bB69D94302a8508A742#tokentxns looks like it works now
> 
> > 
> 
> > The issue still remains.. I Still have the Error and I still have missing transaction of 5 myst. so the issue is NOT resolved
> 
> 
> 
> can you paste the transaction ID of the missing settlement?

And I was Guaranteed a solution and a payment if the lost Mysterium from Isaac which has not happened either

**Comment by Guillembonet** [comment]
> > > > https://polygonscan.com/address/0x7B10088Cc373a10BC3b72bB69D94302a8508A742#tokentxns looks like it works now
> > 
> > 
> > > 
> > 
> > 
> > > The issue still remains.. I Still have the Error and I still have missing transaction of 5 myst. so the issue is NOT resolved
> > 
> > 
> > can you paste the transaction ID of the missing settlement?
> 
> And I was Guaranteed a solution and a payment if the lost Mysterium from Isaac which has not happened either

Are you complainig abou the transaction which shows 0x000 address or some other which you believe shoul b there but is not?

**Comment by strongbow1** [comment]
> > > > > https://polygonscan.com/address/0x7B10088Cc373a10BC3b72bB69D94302a8508A742#tokentxns looks like it works now
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > The issue still remains.. I Still have the Error and I still have missing transaction of 5 myst. so the issue is NOT resolved
> 
> > > 
> 
> > > 
> 
> > > can you paste the transaction ID of the missing settlement?
> 
> > 
> 
> > And I was Guaranteed a solution and a payment if the lost Mysterium from Isaac which has not happened either
> 
> 
> 
> Are you complainig abou the transaction which shows 0x000 address or some other which you believe shoul b there but is not?

Read up on the problem! Isaac is very well informed of what is going on but I have this feeling he refuses to understand and help fix the issue!!
So once again. I made a MANUAL settlement to my external wallet! Which failed hence the warning! It never showed up on my myst node was about 4.96 myst that now is lost and the error has been there since 20 days and no one from you or support want to find a solution to fix it! But yet you close the bug report without confirming the issue or without any prior knowledge of what is going on! I am sitting with a failed payment and missing Mysterium which never reached my wallet and due to the error is not showing up under my transactions! Now I need Isaac to hold on his promise to reimburse me the missing Mysterium he promised
Me and for support to fix this annoying error which is now on my node since 20 days

**Comment by Guillembonet** [comment]
You did [this transaction](https://polygonscan.com/tx/0x0646312847f6d86e9bc2301efd018b3fee53733d167ecdf7fe33470247066779) which shows with 0x000 (due to UI issue)
Then you did [this one](https://polygonscan.com/tx/0x2abfcdc7bd8b65c21dc09bc19d77b5f0d7ad08d3e9803505241dd10df0fda462) which also shows in your screenshot and with correct wallet address.

**Comment by Guillembonet** [comment]
There is no missing transactions in between those two

**Comment by strongbow1** [comment]
> There is no missing transactions in between those two

There is!! Why else would I get the error message? For fun?

**Comment by strongbow1** [comment]
> You did [this transaction](https://polygonscan.com/tx/0x0646312847f6d86e9bc2301efd018b3fee53733d167ecdf7fe33470247066779) which shows with 0x000 (due to UI issue)
> 
> Then you did [this one](https://polygonscan.com/tx/0x2abfcdc7bd8b65c21dc09bc19d77b5f0d7ad08d3e9803505241dd10df0fda462) which also shows in your screenshot and with correct wallet address.
> 
> 

Between 26/10/22 and 02/11/22 the two transactions you mentioned I made a manual transaction and that is GONE!! MISSING!! Nowhere to be found, and then I received the error message if you follow this thread and the new one I opened! And that problem I described to Isaac MANY TIMES, and he refuses to understand and like you refuse to resolve the issue but just close the bug without understanding the core issue.

There was a transaction I made between 26/10/22 and 02/11/22 that triggered the error message and removed about 4.96 Myst from my node, but never registered the transaction and that is MISSING now. Neither you want to fix it and neither Isaac who guaranteed me a fix to my issue and a pay out of the missing Myst has taken place.

And it has been now more than 20 days that this issue is ongoing with empty promises from your side to fulfill your promises and find a fix and find my missing Myst I lost.

**Comment by Guillembonet** [comment]
An error does not automatically mean that you money is sent to nowhere, it can also mean that nothing was done, which looks like it's what happened.

In the [first transaction](https://polygonscan.com/tx/0x0646312847f6d86e9bc2301efd018b3fee53733d167ecdf7fe33470247066779) you settled 60.078 MYST (this is the total amount you earned and you can see this value in the input data section of polygonscan).
In the [second transaction](https://polygonscan.com/tx/0x2abfcdc7bd8b65c21dc09bc19d77b5f0d7ad08d3e9803505241dd10df0fda462) you settled 64.77 MYST.

The amount you are expected to receive if there is no other transaction in between is 64.77-60.078=4.692 MYST minus 20% fees, which is 3.75 MYST and is the amount you received in the second transaction to your wallet, therefore there is no transaction missing.

**Comment by strongbow1** [comment]
There is a missing transaction. Between 26/10/22 and 02/11/22 I made a manual settlement and that is missing! And you refuse to resolve my issue. Plus the issue still remains as the error will not disappear from my node! This issue you also have not resolved. Why is nobody looking into the transaction that is missing? But just assume?

**Comment by strongbow1** [comment]
Ok then explain to me why a transaction is missing between 26/10/22 and 02/11/22? Besides I can not settle 64+ myst when auto settlement is on! So it shows you have no idea what the issue is and just assume the problem is fixed but no investigation is being made to solve my problem

**Comment by Guillembonet** [comment]
Settlements work as follows:
1. You earn some MYST (let's say 5).
2. You settle them (paying 20% fees).
3. You earn 3 more MYST, in total 8.
4. You settle them by calling the settlePromise function in hermes smart contract with amount = 8 MYST
5. The smart contract function pays you the amount minus what you have already settled before, in this case: 8-5=3 MYST  (paying 20% fees, so 2.4 MYST).

You always call this function with the total amount you earned with that node, therefore it is easy to check whether 2 transactions are consecutive or not by getting subtracting the amounts you called the smart contract function with and seeing if what you got paid matches the subtraction of those values minus the fees. In your case they do and therefore they are consecutive, and although you believe otherwise, there is no transaction missing between those 2, and if there was any it did not take away any of your funds since you got the expected amount in the next transaction.

As you can see I do have an idea and complete knowledge of how settlements work, I did check your issue and you can refer to my previous comment for clarification after reading about this.

**Comment by strongbow1** [comment]
You are not understanding my problem are you!! The error message is still there and my transaction I made between 26/10/22 and 02/11/22 is missing!! Not shown GONE!! And that transaction cost me 4.96 myst that went from my node and disappeared! But you are not looking into the problem you are ASSUMING and issue that is not there and you are refusing to solve it and also give a solution on how to make this message disappear. So yes I stand by my comment you have no clue what you doing!!

**Comment by Guillembonet** [comment]
> You are not understanding my problem are you!! The error message is still there and my transaction I made between 26/10/22 and 02/11/22 is missing!! Not shown GONE!! And that transaction cost me 4.96 myst that went from my node and disappeared! But you are not looking into the problem you are ASSUMING and issue that is not there and you are refusing to solve it and also give a solution on how to make this message disappear. So yes I stand by my comment you have no clue what you doing!!

I totally understand it, if there is this error notification don't worry, just ignore it or press it so it goes away. Your autowithdrawal address is set to 0x7B10088Cc373a10BC3b72bB69D94302a8508A742. If this is the one you want then all is working as expected. And for the missing transaction, I can assure there is no missing transaction, all the money you earned between those dates was settled on the second transaction I linked you.

**Comment by strongbow1** [comment]
Don't you think I tried pressing on the error? It wont go away!! But you would know that if you actually asked what the problem was and not assume stuff!!

**Comment by Guillembonet** [comment]
> Don't you think I tried pressing on the error? It wont go away!! But you would know that if you actually asked what the problem was and not assume stuff!!

Okay so then the issue is in UI, it seems to be showing an error which is no longer there. I will create an issue for this then

**Comment by strongbow1** [comment]
Wow cant believe it took you 20days just to open aa different issue and yet there is still no resolution.
