### ISSUE TITLE
Node shows as monitoring failed after updating to 1.19.4

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5588]
**Describe the bug**
Node is marked as monitoring failed after updating to 1.19.4

**Expected behavior**
Node shows as monitoring failed for a majority of the node runners, those are running 1.19.4, however, it is not the case for everyone.

**Environment (please complete the following information):**
 - Node version: 1.19.4
 - OS: Windows native, Linux/Raspberry Pi (Debian 10)

**Comment by iamflorencejay** [comment]
Same here.

**Comment by TheophileDiot** [comment]
Same

**Comment by etherunit** [comment]
Hey guys, please provide us with your node identities, otherwise, we won't be able to check and fix it.

**Comment by iamflorencejay** [comment]
@etherunit 0x7159d375be4a1965021dd299d8d1a205dee47e1d

**Comment by TheophileDiot** [comment]
> Hey guys, please provide us with your node identities, otherwise, we won't be able to check and fix it.

@etherunit 
0x456783d63a51832d2431fe21b58d6147a29e19b7
0xd6a4c51dba04c471665376d6dbb8f05ad193093e
0x2b6c74e0322181e2d4cde0a2e7a1c53bd698a503
0xdd897fb6e356107908fe20a79c8b71bc2b3c6717

> That's every node I have (they all have the issue)

**Comment by MAXIGAMESSUPPER** [comment]
I only have one node and my node id is 0x63e3c9a7dd26cf4d8171c2eeea2b3bdb851c0418

**Comment by SriRamTejaTelukuntla** [comment]
Node ID - 
0x0910d29035c04f0b11b72514305ceedb62401d50

**Comment by iamflorencejay** [comment]
so we have a lot of people, not me. 🤔

**Comment by TheophileDiot** [comment]
> so we have a lot of people, not just me. thinking

@iamflorencejay I think that's everyone using the Linux integration

**Comment by nhujgtr** [comment]
@etherunit id: 0x1e5ff8ae54889a8b0959184606b181b6c6d58112 version: 1.19.4
"monitoring failed" problem hope you can fix it thank you

**Comment by MurphyFiveNode** [comment]
Same here.
Monitoring failed. How can I fix the problem?
My Id´s

0x64f15ffa12118a816962d80a3a0c0b5e001fc008

0xbad319870dd75da4cc85fca36dc903d7d049e482

0x318b63f662bfe7a7c44d76d5dbcd8b7c15f061eb

**Comment by etherunit** [comment]
@MurphyFiveNode 

0x64f15ffa12118a816962d80a3a0c0b5e001fc008 - online
0xbad319870dd75da4cc85fca36dc903d7d049e482 - offline
0x318b63f662bfe7a7c44d76d5dbcd8b7c15f061eb - connection failed (this node fails to resolve ip address). `2022-11-10T09:06:24.022 ERR ../../../../source/core/ip/resolver.go:102           > could not reach location service, will use fallbacks error="Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"`

There might be an issue with firewall or DNS configuration on your host machine.

**Comment by iamflorencejay** [comment]
Even I downgraded my stuff, and forces to use docker, it is still the same.

**Comment by iamflorencejay** [comment]
> @etherunit 0x7159d375be4a1965021dd299d8d1a205dee47e1d

@etherunit can you check mine?

**Comment by iamflorencejay** [comment]
I've seen something on the docker logs, idk how to fix this?
```
2022-11-10T07:21:54.981 ERR ../../p2p/listener.go:137                      > Could not handle exchange ack error="pending config not found for key xxx"
2022-11-10T07:21:54.926 ERR ../../p2p/listener.go:137                      > Could not handle exchange ack error="could not decrypt peer conn config: could not decrypt config to proto bytes: could not decrypt message"
```

**Comment by S4endSTORM** [comment]
Same here - Monitoring failed
0x0200f6f22cb88e36cb01ca511d499f30e6a7a5c6

**Comment by MurphyFiveNode** [comment]
> @MurphyFiveNode
> 
> 0x64f15ffa12118a816962d80a3a0c0b5e001fc008 - online 0xbad319870dd75da4cc85fca36dc903d7d049e482 - offline 0x318b63f662bfe7a7c44d76d5dbcd8b7c15f061eb - connection failed (this node fails to resolve ip address). `2022-11-10T09:06:24.022 ERR ../../../../source/core/ip/resolver.go:102 > could not reach location service, will use fallbacks error="Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"`
> 
> There might be an issue with firewall or DNS configuration on your host machine.

It's really strange. I have set the router to "Expose Host". All ports are open. Firewall disabled. Is it maybe because I am from Europe/Germany? Maybe my provider blocked the connection to the Myterium Node. i gave no idea what else i could try.

**Comment by drownwagon** [comment]
Adding my node 0x26bc8199bbf80a95d92aef03aaff5795f3f4619c to the list monitoring failed issue

**Comment by uthej23** [comment]
Same problem since 5 days- Monitoring Failed
Node ID-
0x0910d29035c04f0b11b72514305ceedb62401d50

**Comment by iamflorencejay** [comment]
now it is fixed on my end

**Comment by vamsip000** [comment]
My node id
0x6b91a85fa447cf898bd4717545422bacf3ca73c8

**Comment by GLaDOSSSSS** [comment]
0x82c98de78ee80c759b77be1b02a6f3c51f6e5052

**Comment by jaska087** [comment]
0x50a1aba02d736b082e97f2c69bd9682d39997e9a
Worked for a few hours, then "Monitoring failed"

**Comment by johnfadley** [comment]
0x1c5864601e6dcfce9c702d2d21f83c57fe0bc7b8

**Comment by MRColorR** [comment]
0x9b634b413392e69e053077e79dcdc9d459e0098d , "Connection failed" on my nodes dashboard but it seems online and working on mystnode windows app. The node is running on a freshly installed Windows 11 laptop.

**Comment by S4endSTORM** [comment]
> 0x9b634b413392e69e053077e79dcdc9d459e0098d , "Connection failed" on my nodes dashboard but it seems online and working on mystnode windows app. The node is running on a freshly installed Windows 11 laptop.

I had the same problem with Myst **"Native Windows"** and **"Raspberry Pi"** nodes.
By **_transforming your "Native Windows" node into a "Windows Docker" node_**, everything will work correctly again.
_The problem seems to be in the firewall, I couldn't fix the firewall issue but Docker doesn't seem to be affected by it._

**Comment by MRColorR** [comment]
> > 0x9b634b413392e69e053077e79dcdc9d459e0098d , "Connection failed" on my nodes dashboard but it seems online and working on mystnode windows app. The node is running on a freshly installed Windows 11 laptop.
> 
> I had the same problem with Myst **"Native Windows"** and **"Raspberry Pi"** nodes. By **_transforming your "Native Windows" node into a "Windows Docker" node_**, everything will work correctly again. _The problem seems to be in the firewall, I couldn't fix the firewall issue but Docker doesn't seem to be affected by it._

yes you're right, this is my 4th node and i just wanted to try windows native env, but i'll  bring my docker-compose file back up for now. thank you

**Comment by liamgibbins** [comment]
Same here running native linux (not docker)
0x7d989a2b430e71c8d926d575a8d4efea773c1b27

**Comment by omerkamis** [comment]
0x0ba34f4ec9d75530a61b29e5fa2b1f6a48b522a4
0x6ede2df7b54151445f730e0ae61c856fbaef65ff
Hello there
These nodes seem to be closed all the time.
can you check?

**Comment by iamflorencejay** [comment]
same problem, probably on their server, not ours

**Comment by liamgibbins** [comment]
> > @MurphyFiveNode
> > 0x64f15ffa12118a816962d80a3a0c0b5e001fc008 - online 0xbad319870dd75da4cc85fca36dc903d7d049e482 - offline 0x318b63f662bfe7a7c44d76d5dbcd8b7c15f061eb - connection failed (this node fails to resolve ip address). `2022-11-10T09:06:24.022 ERR ../../../../source/core/ip/resolver.go:102 > could not reach location service, will use fallbacks error="Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"`
> > There might be an issue with firewall or DNS configuration on your host machine.
> 
> It's really strange. I have set the router to "Expose Host". All ports are open. Firewall disabled. Is it maybe because I am from Europe/Germany? Maybe my provider blocked the connection to the Myterium Node. i gave no idea what else i could try.

More info please, self hosted? Etc..
Sounds like a dns issue to me, so you have tried DMZ so no ports are blocked by the firewall.
Did you get it sorted out?

**Comment by etherunit** [comment]
Hey guys, team has finally fixed a few minor bugs with launcher update mechanism and a way it handles DNS services. Please update your launchers. 

Note! Users of Mysterium Launcher v.1.0.31 - 1.0.35: in order to upgrade to a new version v.1.0.37, it's required to download the MSI package from the following link: [https://github.com/mysteriumnetwork/myst-launcher/releases/latest/download/myst-launcher-x64.msi](https://github.com/mysteriumnetwork/myst-launcher/releases/download/1.0.37/myst-launcher-x64.msi)

‍
