### ISSUE TITLE
Connection failed - my node

### ISSUE THREAD

**Issue by PavelKeyIrk** [mysteriumnetwork/node#5590]
My node id is 0xb2bec5e36caf049d317c3532a46b01c1b59dd6f7
There was a problem in https://mystnodes.com/nodes I see the status
connection failed
Ubuntu
I do as it says in the manual.
root@myst1:~# iptables -P FORWARD ACCEPT
root@myst1:~# iptables -P FORWARD INPUT
iptables: Bad policy name. Run `dmesg' for more information.
The node fails the test. Sometimes the status changes to online, but the test still fails.
file etc/default/mysterium-node changed according to instructions.
DAEMON_OPTS="--keystore.lightweight --udp.ports=30000:60000" SERVICE_OPTS="wireguard"
ports on the router are forwarded.

**Comment by etherunit** [comment]
I can confirm that your node status is online. Test failed status has been cleared out.
See below:
![Screen Shot 2022-11-08 at 09 34 20](https://user-images.githubusercontent.com/60128746/200502215-a2aaa616-7181-4119-ac19-1391cc19c86e.png)
