### ISSUE TITLE
Unable to connect to any node

### ISSUE THREAD

**Issue by ghost** [mysteriumnetwork/node#5591]
**Describe the bug**
Whenever I try to connect to any node, no matter which country or if its hosting/residential I get the following error:
"Oops! Could not connect"
"Failed to connect: could not start new connection: failed to start connection endpoint: could not configure device: failed to create wg interface: could not setup network: could not set DNS: could not configure DNS"

**To Reproduce**
1. Launch Mysterium on Windows 10
2. Log in
3. Attempt to connect to any node.

**Expected behavior**
Whats expected to happen in terms of the bug is the connection trying to connect for a while, before taking you to the homescreen with an error that appears for only a few seconds.

**Screenshots**
(https://i.imgur.com/TtJLA37.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Desktop app version: 10.13.3
 - Identity: 0xa96f8b4397d7414a6612fd256ff1ec8a9d0daf8f

**Additional context**
Settings;
 - Default Filters: Medium
 - Connection;
   - DNS server: Automatic
   - NAT type detection: Yes
   - Kill switch: No
   
   Example of failing nodes;
    - 0x041594f43e4f (Norway : Hosting)
     - 0x2e8a14020d64 (Norway : Residential)
     - 0x96d0b72e400d (Georgia : Residential)
     
    Misc;
     - MYST: 4.48
     - Categories attempted: "All Nodes" & "Media Streaming"
     - Can use other VPNs like PIA fine. I assume this error is due to some DNS thing I have to configure differently / install?

**Comment by etherunit** [comment]
Have you tried to switch to other DNS setting within app? I'd suggest trying System

**Comment by NemesisDevTeam** [comment]
> Have you tried to switch to other DNS setting within app? I'd suggest trying `System`

Hey!
Yes I did try with all of the DNS settings, still none of them worked.

**Comment by etherunit** [comment]
I see. Could you submit your node logs please? https://github.com/mysteriumnetwork/mysterium-vpn-desktop#windows-1

**Comment by NemesisDevTeam** [comment]
[main.log](https://github.com/mysteriumnetwork/node/files/10127093/main.log)
[renderer.log](https://github.com/mysteriumnetwork/node/files/10127094/renderer.log)
[myst_supervisor.log](https://github.com/mysteriumnetwork/node/files/10127097/myst_supervisor.log)
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/10127102/mysterium-node.log)


> I see. Could you submit your node logs please?
> 
> Logs help to debug issues when something goes wrong. Make sure to attach all of them when submitting a bug report.
> 
> **Windows**
> 
> ```
> %USERPROFILE%\AppData\Roaming\MysteriumVPN\logs (app)
> %USERPROFILE%\.mysterium\logs\mysterium-node.log (node)
> %PROGRAMDATA%\MystSupervisor\myst_supervisor.log (supervisor)
> ```

**Comment by NemesisDevTeam** [comment]
> I see. Could you submit your node logs please?
> 
> Logs help to debug issues when something goes wrong. Make sure to attach all of them when submitting a bug report.
> 
> **Windows**
> 
> ```
> %USERPROFILE%\AppData\Roaming\MysteriumVPN\logs (app)
> %USERPROFILE%\.mysterium\logs\mysterium-node.log (node)
> %PROGRAMDATA%\MystSupervisor\myst_supervisor.log (supervisor)
> ```

Any idea on how to fix it?
Logs provided.

**Comment by NemesisDevTeam** [comment]
@etherunit

**Comment by etherunit** [comment]
Thanks for submitting your node and app logs! 

From the first glance, it looks like DNS / UDP traffic related.

```
2022-11-12 14:29:22.706] [info]  Spawning a child process:  C:\Program Files\MysteriumVPN\resources\app.asar.unpacked\node_modules\@mysteriumnetwork\node\bin\win\x64\myst.exe --ui.enable=false --usermode --consumer --tequilapi.port=44050 --discovery.type=api daemon
[2022-11-12 14:29:26.094] [error] Error: Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)
    at SimpleURLLoaderWrapper.emit (node:domain:475:12)
[2022-11-12 14:29:31.159] [error] Pushy registration error The API request failed: request to https://api.pushy.me/register failed, reason: getaddrinfo ENOTFOUND api.pushy.me
```

Have you tried other providers? If connecting to other providers returns the same output, then most likely the problem is in your network.
