### ISSUE TITLE
Unable to update node

### ISSUE THREAD

**Issue by apple047** [mysteriumnetwork/node#5595]
I'm unable to update the node, command returns as node is already up to date and displays the current version despite newer versions being available.
OS Ubuntu 20.04 
Can be replicated infinitely, tested another node with an older version same output 
![image](https://user-images.githubusercontent.com/68748976/200348149-945bf22d-f2b3-409b-81f7-6774cf1adc9b.jpeg)
![image](https://user-images.githubusercontent.com/68748976/200348618-25f3f1c3-415b-43f2-bb81-8ecbb1932315.jpeg)

Id: 0xa9ccd769f8429c730c8338cc2be7f2d356001039
Another node with same bug: 

0xc803439189c2c14ccb64725c305b6d7db2837fdb

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by apple047** [comment]
Also tried to install the node on a new server but appears the server with the installation file is missing 

$:sudo add-apt-repository ppa:mysteriumnetwork/node
›assword for user:
fo: https://launchpad.net/~mysteriumnetwork/+archive/ubur
NTER] to continue or ctrl-c to cancel adding it
'box ' /tmp/tmpydezxvlr/pubring.gpg' created server receive failed: No keyserver available

**Comment by etherunit** [comment]
@apple047 Could you provide the full output of your terminal (A screenshot) from the installation process?

**Comment by apple047** [comment]
Sorted, I had to add the repository again and the newer version was found and installed, where as before it was indicated as being up to date![image](https://user-images.githubusercontent.com/68748976/203171251-94bb4d0b-b65f-465f-ba2b-338c0c11db93.png)![image](https://user-images.githubusercontent.com/68748976/203171268-ad5497ac-0b7c-40dc-96b6-c3f1e05d4dd6.png)

**Comment by apple047** [comment]
I've tried to set up another node and it appears the same fault as before can be observed ![image](https://user-images.githubusercontent.com/68748976/205365643-25aceaf9-44b1-43af-ae94-40f6d24a150f.png)
