### ISSUE TITLE
Failed to register to mystnodes.com

### ISSUE THREAD

**Issue by PJSzymanski** [mysteriumnetwork/node#5596]
**Describe the bug**
I can't register new node @ mystnodes.com

**To Reproduce**
1. Go to Mysterium Node Launcher (Node are running (PORT RESTRICTED cone NAT), v.1.19.4))
2. Click on 'Node UI'
3. LOG IN -> Click on -> Settings -> API KEY - IlJ39AnfgN1P0TSUkG2RNmook4cWHaI54zZUdHCh
4. See error - > Failed to register to mystnodes.com

**Expected behavior**
new node in my nodes list

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [1.19.4]
 - OS: [Windows]
 - Your identity: 0xf390330c454549ad53dd26e532c4b337a4560a61
 - Payment (top-op) reference: 0x6888d8C0b4396268833DB3d93F7b603C7088D989

**Additional context**

**Comment by etherunit** [comment]
@PJSzymanski Is it possible to get the output of `dev console > network tab` at the time this happening?

**Comment by etherunit** [comment]
Closed due to inactivity. Feel free to reopen it once you have an update.
