### ISSUE TITLE
Node's balance gradually going down (disappears)

### ISSUE THREAD

**Issue by pfoxqa** [mysteriumnetwork/node#5597]
**Describe the bug**
Node was installed and run on Ubuntu 22.04.1 LTS. Got a balance of over 4 MYST. Then the hard drive failure happened and the system needed to be reinstalled. So, no more access to the node. However, the node balance is gradually getting lower. From over 4 MYST the balance decreased to 2.701478 MYST. 

**To Reproduce**
Due to the long-term effect, it is not possible to reproduce the problem on another system. Additionally, you would need access to the account.

**Expected behavior**
Node balance stays the same when a node is not running.

**Screenshots**
attached.

**Environment (please complete the following information):**
 - Node version: 1.17.1
 - OS: Ubuntu 22.04.1 LTS.
 - Your identity: 0x626f6920f80542f37f7d25252a85bc88685abe1a
![Screenshot_1](https://user-images.githubusercontent.com/93166375/200374184-a30e31da-01ee-499c-99e6-b61e18352ab6.png)
![Screenshot_2](https://user-images.githubusercontent.com/93166375/200374191-f6afe102-7b1f-4611-bf20-3d81d0a6bb23.png)

**Comment by etherunit** [comment]
There are several indicators for such outcome:

- Node is no longer online and is not accessible
- **We show earnings for last 30 days, therefore, earnings are getting lower, because node is not earning any more MYST**
