### ISSUE TITLE
Failed to stop myst service when --experiment-identity-check enabled

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#560]
![image](https://user-images.githubusercontent.com/8612618/48880913-b3652980-ee3c-11e8-9cd0-bb8f78211c37.png)

**Comment by zolia** [comment]
If this is true, then we need address it. Since it might hinge  our service starts. 
We need to investigate.

**Comment by soffokl** [comment]
Cannot reproduce it anymore, looks like it was fixed by some indirect changed.
