### ISSUE TITLE
myst node external wallet address is showing as 0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by JayceEdie** [mysteriumnetwork/node#5608]
All 4 of my Myst node external wallet address were showing as 0x0000000000000000000000000000000000000000. I have since updated my address with this https://docs.mysterium.network/for-node-runners/payout-guide in the section about how to change beneficiary (wallet) address. My Myst tokens are now going back into my wallet again. I do not know when or how it got set to this in the first place, as initially, my coins were going into my wallet from all my nodes. Then at some point, they stopped and I am not sure when. The transaction history on my nodes only shows one page of history and nothing further. Also, if my tokens have been going to the burn address, is there a way to recover them?

There haven't been any recent transactions showing in my wallet until I changed my wallet address. The Myst tokens used to go into my wallet but haven't in a while.

My node version is 1.19.3, and my node UI version is 2.3.1 on all four nodes. 
one node is on a Raspberry Pi 4 B running Raspberry Pi OS lite 64bit
the other three are in a Linode Datacenter running Debian 11

**Comment by etherunit** [comment]
Please update your node software to 1.19.4
https://github.com/mysteriumnetwork/node/releases/tag/1.19.4
It has been fixed already.
[How to update](https://docs.mysterium.network/for-node-runners/updating-your-node)

**Comment by JayceEdie** [comment]
I will update my nodes, but that doesn't answer my second question.  If my tokens have been going to the burn address because of this issue, is there a way to recover them?

**Comment by etherunit** [comment]
Can you please specify to which address it has been sent? You can simply copy > paste the transaction data (with links to PolygonScan) from your NodeUI  to your next comment. Thanks!

**Comment by JayceEdie** [comment]
In all three of my nodes, my transaction data was showing 0x0000000000000000000000000000000000000000 as the External Wallet Address. As you suggested, I looked up the transaction IDs in PolygonScan that did show that the tokens were going to my wallet address. Looking further, the transaction dates in my wallet history matched the transaction dates in my node UI. So all the tokens did go to my wallet.
Thank you so much for all your help.
