### ISSUE TITLE
Not getting paid for sessions.  3 Nodes 3 Different Sessions 

### ISSUE THREAD

**Issue by 2020movievault** [mysteriumnetwork/node#5609]
**Describe the bug**
I noticed that 3 different sessions with earnings that exceeded the auto payment threshold of  5 MYST completed yet it did not trigger a payment on my node. This happened 3 different nodes on 3 separate sessions. I am unsure how many other sessions I have not been paid for but these 3 were easy as they were high amounts and went on for 5 days which caught my eye. 

Node 1) 0x910a6276bdaa9f76d27cb2fdc552ee4f6b837d24
Node 2) 0x53dfb72e4e9ade1bffa856e3ee5778df62707554
Node 3) 0xe7ed8ad4e5b7957850b8087634f634ecf3ae67c4 

**To Reproduce**
Unsure how to reproduce a non payment error which should be happening automatically after the completion of a session. 

**Expected behavior**
Payments should be made for all sessions provided by the node which did not occur here.

**Screenshots**

Node 1 payment Transactions. Look at second slide that shows  session ID 1A29572D for 17.13324 MYST where session started on 11/4/2022 at 21:05 and went on for 5 days and 18 hours. This session completion happened on  11/10/2022 should have triggered multiple payments but if you look there are only 1 payment triggered on 11/10/2022

![Detail](https://user-images.githubusercontent.com/85257908/201305111-bebd358f-8a4b-4847-98bb-fd082c76810b.png)

![Session Detail](https://user-images.githubusercontent.com/85257908/201305169-7d26a8a2-0b24-4440-9a23-45e88e22d986.png)

Node 2 payment Transactions. Look at second slide that shows  session ID BC642490 for 8.43364 MYST where session started on 11/4/2022 at 22:46 and went on for 5 days and 16 hours. This session completion happened on  11/10/2022 should have triggered a payment but if you look there are no payments after 11/8/2022

![Session Detail 2](https://user-images.githubusercontent.com/85257908/201306905-8fe9c85b-9b69-40ea-beea-34fa20dc9ccf.png)

![Detail 2](https://user-images.githubusercontent.com/85257908/201306926-0ab6939c-ddfc-459e-9a87-b3bb8d897358.png)

Node 3 payment Transactions. Look at second slide that shows  session ID 6E5D458C for 7.6996 MYST where session started on 11/4/2022 at 21:06 and went on for 5 days and 17 hours. This session completion happened on  11/10/2022 should have triggered a payment but if you look there are no payments after 11/8/2022

![Session Detail 3](https://user-images.githubusercontent.com/85257908/201307461-48bf20ba-e79e-4011-9809-ac5aea2616fa.png)

![Detail 3](https://user-images.githubusercontent.com/85257908/201307475-992e1ac0-f8ce-4092-990c-df574a5dbd9e.png)

**Environment (please complete the following information):**
 - Node version: [1.19.0] 0x910a6276bdaa9f76d27cb2fdc552ee4f6b837d24  Node 1 
 - Node version: [1.19.1] 0x53dfb72e4e9ade1bffa856e3ee5778df62707554 Node 2 
 - Node version: [1.19.0] 0xe7ed8ad4e5b7957850b8087634f634ecf3ae67c4
 - OS: [Ubuntu ]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x910a6276bdaa9f76d27cb2fdc552ee4f6b837d2
 - 0x53dfb72e4e9ade1bffa856e3ee5778df62707554 
 - 0xe7ed8ad4e5b7957850b8087634f634ecf3ae67c4
 - Payment (top-op) reference (if applicable): NA

**Additional context**

I am unsure how many other sessions I have not gotten paid for. I just caught these because they went on for 5 days and the amount of Myst earned was significantly higher.

**Comment by etherunit** [comment]
@2020movievault Do you still experience this issue? There might be a delay in updating those stats.

**Comment by 2020movievault** [comment]
Ys the problem was never fixed and for all I know its been happening consistently since but since the transaction amounts are so small and so many it's hard to tell how many sessions are not being paid for? 

Node 1 0x910a6276bdaa9f76d27cb2fdc552ee4f6b837d24 still doesn't show the 17.334 MYST 13.86 after 20% cut. Only 2 individual payments made on  11/12/2022 & 11/13/2022 when the session terminated on the 10th and the 13.86 MYST transaction since it was from one session should have created 2 separate payments. 

![0x910a6276bdaa9f76d27cb2fdc552ee4f6b837d24 11-14-2022](https://user-images.githubusercontent.com/85257908/201723380-56e21fe0-9271-42c0-86aa-e9e5bae840e1.png)

Not being able to download the session transaction's I can't tell how many other sessions have not translated = Non payment.

Node 2 Same Problem  0x53dfb72e4e9ade1bffa856e3ee5778df62707554 look at my first screen shot of this node when i claimed the session closing didn't trigger payment. The total myst earned at that time was 3.64 when I hadn't seen the payment .  The next settlement which triggered on 11/12/2022 should have been for the missing 8.43364 from the session + the pending 3.64 and should have triggered 2 Payments but it did not. 


![0x910a6276bdaa9f76d27cb2fdc552ee4f6b837d24 11-14-2022](https://user-images.githubusercontent.com/85257908/201725431-09a753b1-9acb-4d51-8af7-a3eb3da0680a.png)

Node 3 0xe7ed8ad4e5b7957850b8087634f634ecf3ae67c4 Same problem. At the time of me making the incident I had a pending payment of 3.49 MYST  add to that the missing 7.69976 MYST from the session the the total indeed a delay should have been for 11.18 MYST but as you see in the screenshot below that did not happen.  


![0x910a6276bdaa9f76d27cb2fdc552ee4f6b837d24 11-14-2022](https://user-images.githubusercontent.com/85257908/201726394-8cef05e6-92f4-4364-8246-85d965b6b809.png)

I would like to know how can I download my entire session list and cross check it with the payment transactions to see how many sessions have been unpaid for?
