### ISSUE TITLE
Node works but B2B connections zero data transfer.

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5612]
**Describe the bug**

All B2B connections (scraping and VPN/data transfer) result in 0 data being transferred. Public connections seem to work fine.

**To Reproduce**

1. Go to History

2. See that all B2B connections have 0 bytes transferred

**Expected behavior**

I expect B2B connections to work.

**Screenshots**

Not required.

**Environment:**

- Node version: 1.19.4

- OS: Windows 10 Home, version 21H1

- My identity: 0xd284ba4a357e69a43564a486819878f1ce9744ba

**Additional context**

I'd like to allow all connection types (public, B2B).

**Comment by Spiffical** [comment]
Isaac posted this issue on my behalf, and I wanted to update with the solution:

Luckily, it was a simple fix. I just switched to the Docker backend instead of the Native backend, and all my connections are coming through just fine now.
