### ISSUE TITLE
Monitoring Failed

### ISSUE THREAD

**Issue by hardlycodingbears** [mysteriumnetwork/node#5621]
**Describe the bug**
My node displays monitoring failed ... please contact support

**To Reproduce**
N/A

**Expected behavior**
N/a

**Screenshots**
<img width="320" alt="Screenshot 2022-11-15 at 09 35 55" src="https://user-images.githubusercontent.com/40523241/201884362-8cc42b2a-7827-4c36-b4b4-aba261f7f78f.png">

**Environment (please complete the following information):**
 - Node version: 1.19.4
 - OS: Ubuntu 20.04
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A
 - Your identity (if applicable): 0xda42d7d1d72f8f9becc45f3edb34d821bd3aaacf
 - Payment (top-op) reference (if applicable): N/A

**Additional context**

**Comment by etherunit** [comment]
I've made several connection attempts with the following outcome: 

_Connection to Wireguard service:_
```
2022-11-16T09:41:07.726 ERR ../../../../source/core/ip/resolver.go:102           > could not reach location service, will use fallbacks error="Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
2022-11-16T09:41:07.726 ERR ../../../../source/core/location/cache.go:108        > Location update failed error="failed to execute request: Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

Connection to DT service:
`[ERROR] Failed to connect: could not create p2p channel during connect: p2p dialer failed: could not ack config: could not send signed msg: could not send broker request to subject 0xda42d7d1d72f8f9becc45f3edb34d821bd3aaacf.data_transfer.p2p-config-exchange-ack: context deadline exceeded`

**Comment by hardlycodingbears** [comment]
> I've made several connection attempts with the following outcome:
> 
> _Connection to Wireguard service:_
> 
> ```
> 2022-11-16T09:41:07.726 ERR ../../../../source/core/ip/resolver.go:102           > could not reach location service, will use fallbacks error="Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
> 2022-11-16T09:41:07.726 ERR ../../../../source/core/location/cache.go:108        > Location update failed error="failed to execute request: Get \"https://location.mysterium.network/api/v1/location\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
> ```
> 
> _Connection to DT service:_ `[ERROR] Failed to connect: could not create p2p channel during connect: p2p dialer failed: could not ack config: could not send signed msg: could not send broker request to subject 0xda42d7d1d72f8f9becc45f3edb34d821bd3aaacf.data_transfer.p2p-config-exchange-ack: context deadline exceeded`
> 
> @hardlycodingbears Please provide us with your node logs, it could give us some extra helpful insights.
> 
> How to submit node logs? >> https://docs.mysterium.network/troubleshooting/reporting-an-issue

just sent a bug report, thanks (:

**Comment by etherunit** [comment]
Thanks, team will review it and get back to you shortly.

**Comment by hardlycodingbears** [comment]
> 

hello, was just wondering what came of the review (:
