### ISSUE TITLE
NEED ATENTION 

### ISSUE THREAD

**Issue by Ivaylo1977** [mysteriumnetwork/node#5622]
0x6ab32187275583f76355975210ca32c15052d4b2

0x1942c01cb56b7322b8b8d986ead07a2a3f426595
 they didnt work. always say need atention in UI

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by isaackielma** [comment]
Could you please explain exactly what is happening? what leads you to the issue?
