### ISSUE TITLE
Monitoring Failed (twice...)

### ISSUE THREAD

**Issue by louisdchrf** [mysteriumnetwork/node#5623]
**Describe the bug**
Monitoring is failed and tell to contact the support, the support tell to report a issue on Github

**Expected behavior**
The nodes was running during 2 days then failed (report on the mystnode.com interface and on the interface of the nodes)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/44228226/201988216-fcb2da4b-b353-476f-b470-58fee759134e.png">

**Environment (please complete the following information):**
 - Node version: 1.19.4
 - OS: Ubuntu 20.04 LTS x64
 - Identities : 0xb413f2dacd8eebd8b0c18d9faedf66f6812b1749 AND 0xa39c096f7432c117b1df52f8696aac2891d81ec8
 
Please add support or option to have more information on the monitoring of the nodes,

**Comment by etherunit** [comment]
@louisdchrf Your nodes are connectable, but internet browsing is not working once connected. There might be several reasons behind: Firewall (iptables) settings, DNS misconfiguration etc.

dig tesla.com

; <<>> DiG 9.10.6 <<>> tesla.com
;; global options: +cmd
;; connection timed out; no servers could be reached

First things first, I'd suggest checking iptables rules: `sudo iptables-save`

Please copy > paste the ouput here.

**Comment by louisdchrf** [comment]
I can't a documentation telling what ports to open, I usually don't stay with all port open on a machine.

dig tesla.com is working : 
![image](https://user-images.githubusercontent.com/44228226/202136185-a5bb38dc-e725-433d-a2a4-bb03360044b2.png)

The iptables rules (open for all on 4449, and 10 000 to 60 000) :

![image](https://user-images.githubusercontent.com/44228226/202137162-42819410-e2a4-4381-8c4d-6f678ae726bd.png)

**Comment by etherunit** [comment]
Could you provide an output of `sudo iptables-save` command?

**Comment by louisdchrf** [comment]
IP in the report is the cloudflare ip, to managed the access from a entry in my domain

`# Generated by iptables-save v1.8.4 on Thu Nov 17 18:35:49 2022
*nat
:PREROUTING ACCEPT [2617:144288]
:INPUT ACCEPT [550:21952]
:OUTPUT ACCEPT [2182:206088]
:POSTROUTING ACCEPT [2182:206088]
:MYST - [0:0]
-A MYST -d 10.0.0.0/8 -j DNAT --to-destination 240.0.0.1
-A MYST -d 172.16.0.0/12 -j DNAT --to-destination 240.0.0.1
-A MYST -d 192.168.0.0/16 -j DNAT --to-destination 240.0.0.1
-A MYST -d 127.0.0.0/8 -j DNAT --to-destination 240.0.0.1
COMMIT
# Completed on Thu Nov 17 18:35:49 2022
# Generated by iptables-save v1.8.4 on Thu Nov 17 18:35:49 2022
*filter
:INPUT DROP [2042:121140]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2:80]
:ufw-after-forward - [0:0]
:ufw-after-input - [0:0]
:ufw-after-logging-forward - [0:0]
:ufw-after-logging-input - [0:0]
:ufw-after-logging-output - [0:0]
:ufw-after-output - [0:0]
:ufw-before-forward - [0:0]
:ufw-before-input - [0:0]
:ufw-before-logging-forward - [0:0]
:ufw-before-logging-input - [0:0]
:ufw-before-logging-output - [0:0]
:ufw-before-output - [0:0]
:ufw-logging-allow - [0:0]
:ufw-logging-deny - [0:0]
:ufw-not-local - [0:0]
:ufw-reject-forward - [0:0]
:ufw-reject-input - [0:0]
:ufw-reject-output - [0:0]
:ufw-skip-to-policy-forward - [0:0]
:ufw-skip-to-policy-input - [0:0]
:ufw-skip-to-policy-output - [0:0]
:ufw-track-forward - [0:0]
:ufw-track-input - [0:0]
:ufw-track-output - [0:0]
:ufw-user-forward - [0:0]
:ufw-user-input - [0:0]
:ufw-user-limit - [0:0]
:ufw-user-limit-accept - [0:0]
:ufw-user-logging-forward - [0:0]
:ufw-user-logging-input - [0:0]
:ufw-user-logging-output - [0:0]
:ufw-user-output - [0:0]
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -j ufw-after-input
-A INPUT -j ufw-after-logging-input
-A INPUT -j ufw-reject-input
-A INPUT -j ufw-track-input
-A FORWARD -j ufw-before-logging-forward
-A FORWARD -j ufw-before-forward
-A FORWARD -j ufw-after-forward
-A FORWARD -j ufw-after-logging-forward
-A FORWARD -j ufw-reject-forward
-A FORWARD -j ufw-track-forward
-A OUTPUT -j ufw-before-logging-output
-A OUTPUT -j ufw-before-output
-A OUTPUT -j ufw-after-output
-A OUTPUT -j ufw-after-logging-output
-A OUTPUT -j ufw-reject-output
-A OUTPUT -j ufw-track-output
-A ufw-after-input -p udp -m udp --dport 137 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 138 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 139 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 445 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 67 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 68 -j ufw-skip-to-policy-input
-A ufw-after-input -m addrtype --dst-type BROADCAST -j ufw-skip-to-policy-input
-A ufw-after-logging-forward -m limit --limit 3/min --limit-burst 10 -j LOG --lo                                                                                                                                                                                                          g-prefix "[UFW BLOCK] "
-A ufw-after-logging-input -m limit --limit 3/min --limit-burst 10 -j LOG --log-                                                                                                                                                                                                          prefix "[UFW BLOCK] "
-A ufw-before-forward -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-forward -j ufw-user-forward
-A ufw-before-input -i lo -j ACCEPT
-A ufw-before-input -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-input -m conntrack --ctstate INVALID -j ufw-logging-deny
-A ufw-before-input -m conntrack --ctstate INVALID -j DROP
-A ufw-before-input -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-input -p udp -m udp --sport 67 --dport 68 -j ACCEPT
-A ufw-before-input -j ufw-not-local
-A ufw-before-input -d 224.0.0.251/32 -p udp -m udp --dport 5353 -j ACCEPT
-A ufw-before-input -d 239.255.255.250/32 -p udp -m udp --dport 1900 -j ACCEPT
-A ufw-before-input -j ufw-user-input
-A ufw-before-output -o lo -j ACCEPT
-A ufw-before-output -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-output -j ufw-user-output
-A ufw-logging-allow -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix                                                                                                                                                                                                           "[UFW ALLOW] "
-A ufw-logging-deny -m conntrack --ctstate INVALID -m limit --limit 3/min --limi                                                                                                                                                                                                          t-burst 10 -j RETURN
-A ufw-logging-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix                                                                                                                                                                                                           "[UFW BLOCK] "
-A ufw-not-local -m addrtype --dst-type LOCAL -j RETURN
-A ufw-not-local -m addrtype --dst-type MULTICAST -j RETURN
-A ufw-not-local -m addrtype --dst-type BROADCAST -j RETURN
-A ufw-not-local -m limit --limit 3/min --limit-burst 10 -j ufw-logging-deny
-A ufw-not-local -j DROP
-A ufw-skip-to-policy-forward -j DROP
-A ufw-skip-to-policy-input -j DROP
-A ufw-skip-to-policy-output -j ACCEPT
-A ufw-track-output -p tcp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-track-output -p udp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-user-input -s 82.65.13.4/32 -p tcp -m tcp --dport 22 -j ACCEPT
-A ufw-user-input -s 82.65.13.4/32 -p udp -m udp --dport 22 -j ACCEPT
-A ufw-user-input -s 82.65.13.4/32 -p tcp -m tcp --dport 9090 -j ACCEPT
-A ufw-user-input -s 82.65.13.4/32 -p udp -m udp --dport 9090 -j ACCEPT
-A ufw-user-input -p tcp -m multiport --dports 10000:60000 -j ACCEPT
-A ufw-user-input -s 82.65.13.4/32 -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 4449 -j ACCEPT
-A ufw-user-input -p udp -m udp --dport 4449 -j ACCEPT
-A ufw-user-input -s 82.65.13.4/32 -p tcp -m tcp --dport 19999 -j ACCEPT
-A ufw-user-input -s 82.65.13.4/32 -p udp -m udp --dport 19999 -j ACCEPT
-A ufw-user-input -s 173.245.48.0/20 -j ACCEPT
-A ufw-user-input -s 103.21.244.0/22 -j ACCEPT
-A ufw-user-input -s 103.22.200.0/22 -j ACCEPT
-A ufw-user-input -s 103.31.4.0/22 -j ACCEPT
-A ufw-user-input -s 141.101.64.0/18 -j ACCEPT
-A ufw-user-input -s 108.162.192.0/18 -j ACCEPT
-A ufw-user-input -s 190.93.240.0/20 -j ACCEPT
-A ufw-user-input -s 188.114.96.0/20 -j ACCEPT
-A ufw-user-input -s 197.234.240.0/22 -j ACCEPT
-A ufw-user-input -s 198.41.128.0/17 -j ACCEPT
-A ufw-user-input -s 162.158.0.0/15 -j ACCEPT
-A ufw-user-input -s 104.16.0.0/13 -j ACCEPT
-A ufw-user-input -s 104.24.0.0/14 -j ACCEPT
-A ufw-user-input -s 172.64.0.0/13 -j ACCEPT
-A ufw-user-input -s 131.0.72.0/22 -j ACCEPT
-A ufw-user-limit -m limit --limit 3/min -j LOG --log-prefix "[UFW LIMIT BLOCK]                                                                                                                                                                                                           "
-A ufw-user-limit -j REJECT --reject-with icmp-port-unreachable
-A ufw-user-limit-accept -j ACCEPT
COMMIT
`

**Comment by etherunit** [comment]
Current INPUT policy is set to drop the packets. Quick fix for this problem: `sudo iptables -P INPUT ACCEPT`

**Comment by louisdchrf** [comment]
I change the settings, now waiting for the monitoring to come back

I don't totally agree on leaving the input policy to allow all packets, it will be better to open just the needed ports on the nodes I think

**Comment by louisdchrf** [comment]
The two nodes are back, but whithout filtrering anything on it
