### ISSUE TITLE
Can not use identities withdraw command to withdraw balance

### ISSUE THREAD

**Issue by lhllhx** [mysteriumnetwork/node#5624]
**Describe the bug**  
Can not use identities withdraw command to withdraw balance  

![image](https://user-images.githubusercontent.com/52107206/202154368-58791804-d5e4-4a96-b18d-3bec151615cc.png)  

api https://tequilapi.mysterium.network/#operation/Withdraw is alse 404

**Environment (please complete the following information):**
Mysterium Node
  Version: 1.19.4
  Build info: Branch: 1.19.4. Build id: 681194760. Commit: a1df69f5
Mysterium Node
  Version: 1.19.4
  Build info: Branch: 1.19.4. Build id: 681194760. Commit: a1df69f5

 - OS: debian 10

**Comment by etherunit** [comment]
@lhllhx Please provide us with your Mysterium ID thanks!

**Comment by lhllhx** [comment]
> @lhllhx Please provide us with your Mysterium ID. thanks!

0x4f2ba46f0d1099f85ca8f858fca9426a6a866f7f

**Comment by n10ty** [comment]
@lhllhx your [balance](https://hermes3.mysterium.network/api/v1/data/provider/0x4f2ba46f0d1099f85ca8f858fca9426a6a866f7f) is 0.0128 MYST, why do you want to withdraw? It's not enough to cover fee. Maybe you provided wrong identity?

**Comment by lhllhx** [comment]
> @lhllhx your [earnings](https://hermes3.mysterium.network/api/v1/data/provider/0x4f2ba46f0d1099f85ca8f858fca9426a6a866f7f) is 0,0162 MYST, why do you want to withdraw? It's not enough to cover fee. Maybe you provided wrong identity?

Which Balance is 0.48 myst. I want to withdraw it.

**Comment by n10ty** [comment]
Could you please show a screenshot where do you see this balance?

**Comment by lhllhx** [comment]
> Could you please show a screenshot where do you see this balance?

![image](https://user-images.githubusercontent.com/52107206/202206768-cb671a87-794c-44cc-b67c-7bffbd44e967.png)

**Comment by lhllhx** [comment]
the command and api is also error in my other node. May be it is a common bug.

**Comment by n10ty** [comment]
You can't withdraw not an earnings

**Comment by lhllhx** [comment]
So the api and the command is discarded？

**Comment by n10ty** [comment]
No, API and command are working. Withdraw of non earnings disabled on Hermes side

**Comment by lhllhx** [comment]
> No, API and command are working. Withdraw of non earnings disabled on Hermes side

If I have some earning and settle it to the Chanel address .Can I withdraw all to my address？
