### ISSUE TITLE
No B2B Traffic

### ISSUE THREAD

**Issue by DrakonIsterwall** [mysteriumnetwork/node#5627]
The Bug is that it i get a lot of connections from B2B but its always like 0-3 seconds and no traffic, Public works totaly fine.

No Reproduction because it always was like that even when i restart everything.

![b2b](https://user-images.githubusercontent.com/117237001/202521512-616aa2ea-ad3c-4ff6-a21c-f77b9cec59f5.PNG)
![settings](https://user-images.githubusercontent.com/117237001/202521544-97635aff-a1f8-40aa-abdd-f675d3c8721a.JPG)

The Screenshots are a bit older but nothing changed till now

   Environment 
 - Node version: 1.19.4
 - OS: Windows
 - Desktop app version 1.19.4
 - Your identity : 0x12dd78dd56ecd9e6c270e95d44e88dbf0c3d4d70

**Comment by etherunit** [comment]
I can confirm that both public and B2B data_transfer services worked fine for me.
On the other hand, I can see that it has quite a few failed B2B connections over the last 24h (see below):
![Screen Shot 2022-11-18 at 08 06 01](https://user-images.githubusercontent.com/60128746/202632578-134d4eea-ac8d-45d6-8051-2b1bc2c1035f.png)
I will investigate this further with team and will try to find the cause.

**Comment by DrakonIsterwall** [comment]
okay thanks ;)

**Comment by DrakonIsterwall** [comment]
I found your B2B connection and seemed to work but another B2B connections still have the same problem , i guess it was your from lithuania right ? one time public and one time B2B
![b2b](https://user-images.githubusercontent.com/117237001/202714173-7c27840f-2d01-4f38-891e-cc5988abf9a3.JPG)

Public is still stable working 

![more pictures](https://user-images.githubusercontent.com/117237001/202714393-20b6f0e9-ae17-4f18-8dac-4160e7d277c3.JPG)

**Comment by etherunit** [comment]
Yes, my sessions are from Lithuania. I've done another test and connection worked fine for me. Internet browsing works too, but other B2B sessions are still continue to fail on your side. 
I will continue looking into this.

**Comment by DrakonIsterwall** [comment]
Thanks for your effort, yea it really is weird why it seems to work for you but other cant connect . I hope there gonna be a solution , then i would probably have way more traffic haha .

Have a nice day ;)

**Comment by DrakonIsterwall** [comment]
okay the topic get closed and whats the solution ? :D

**Comment by soffokl** [comment]
We have released a new node version, which should resolve the problem. Please update to the latest version.

**Comment by DrakonIsterwall** [comment]
Yeah can verfiy that B2B is working now sure some fail but some fail for public too over time, thanks for the fix keep up your good work
