### ISSUE TITLE
Hello , problem monitoring failed

### ISSUE THREAD

**Issue by gascanair** [mysteriumnetwork/node#5629]
Hello,
in the central panel for a month I have problems with Node on a raspberry os bullseye. I get this "monitoring failed" error and I don't understand why.
I have 2 nodes in different locations with different ip, on 2 raspberry bullseye 11. the internet provider is the same.

What should be the problem? one works very well without interruption, and the second node has problems.

![image](https://user-images.githubusercontent.com/6025604/202801202-1c5f8f6e-2c98-4a67-8161-16f3f3a79e6b.png)

 - Node version: 1.19.4
 - OS: bullseye 11  raspbian 
 - Your identity (id node ): 0x65871e682a708751a4725130d574f8baafb8fbed

thanks

**Comment by etherunit** [comment]
Hello,  there was a temporary glitch in our monitoring agent. Currently, I can see that both of your nodes are online and working fine now.

**Comment by gascanair** [comment]
Nice , Thanks
