### ISSUE TITLE
kein mining

### ISSUE THREAD

**Issue by babyflo94** [mysteriumnetwork/node#5630]
Good evening my problem is that I can not mine mystnodes ...
 I always have monitoring failed in the attachment you will find the pictures 
I do not know how to proceed, I have already written to support and they referred me here. 
I am slowly in despair I do not know what to do and a computer genius I am unfortunately not ...
all data can be found in the appendix with pictures

my address is : 0xc05d8de2ff342626bdd422221935d56a43935aa3
node version is :
Node version:
1.19.4
Node UI version:
![myst 5](https://user-images.githubusercontent.com/34323183/202821104-f6ac557d-34e5-49dd-b4c4-dfea00e5f9a9.PNG)
![myst 2](https://user-images.githubusercontent.com/34323183/202821106-654cf031-7db1-4e62-80c0-fc3724bced2e.PNG)
![mysr 3](https://user-images.githubusercontent.com/34323183/202821107-36593d01-909e-4642-a517-a695a8120a68.PNG)

2.3.1

**Comment by chemagallego** [comment]
Hi, I have the same problem.

**Comment by chemagallego** [comment]
Same problem here since last week.

**Comment by chemagallego** [comment]
I resolved the problem checking fw rules, I needed to add a new rule: adding udp access.
