### ISSUE TITLE
Monitoring failed

### ISSUE THREAD

**Issue by chemagallego** [mysteriumnetwork/node#5631]
**Describe the bug**
Monitoring failed and connection failed since last week, it was working fine before.

**To Reproduce**
go to https://mystnodes.com/nodes Status: connection failed
go to Dashboard Node status: Monitoring failed

**Expected behavior**
To be online

**Environment (please complete the following information):**
 - Node version: 1.19.4
 - OS: ubuntu 20.04
 - Desktop app version (if applicable): no
 - Docker (if applicable): no
 - Your identity (if applicable): 0x68d6ad328493c5a395a1ca0e6ac1bd5e71f03a48

**Comment by chemagallego** [comment]
Must to say that now it's working fine (one line) after disable ufw (firewall rules), but we need to know which ports are needed to work fine without disable our main fw. We cannot disable our firewalls in order to work fine with mysterium network.  Does It make sense to you ?

**Comment by etherunit** [comment]
try 10000-60000/udp

**Comment by etherunit** [comment]
I can confirm that your node status has changed to online and it works as expected.
![Screen Shot 2022-11-23 at 08 46 18](https://user-images.githubusercontent.com/60128746/203486693-f79e6623-1587-41ef-a3c7-e2dfca8ebe7c.png)

**Comment by chemagallego** [comment]
Hi, 

Yes, you are right. Adding a new fw rule with 10000-60000/udp solved the problem. Thanks.
