### ISSUE TITLE
homepage earnings report and node earnings report mismatch

### ISSUE THREAD

**Issue by omerkamis** [mysteriumnetwork/node#5633]
Hello;
on the myst home page;
The earnings in my myst account and the earnings in the node are different from each other, what could be the reason for this?
I'm running more than one node, my account needs to be collected 1031 myst, but there has never been such a balance for the nodes. Can you help me with this issue?
Can you explain to me why the balance on the website and the balances accumulated in the nodes are different?
![image](https://user-images.githubusercontent.com/31625263/203145426-7bcdfd3a-8f67-4fe9-bc26-57c56ce0b36a.png)
![image](https://user-images.githubusercontent.com/31625263/203145584-b087ba56-4932-400a-822d-e24ad685f000.png)

myst account: kriptoronin@gmail.com
node id:0x9674a6207514f7ba99f00774ae000c1140082c49

**Comment by etherunit** [comment]
What's the amount of MYST displayed in UI for 0x9674a6207514f7ba99f00774ae000c1140082c49?

**Comment by etherunit** [comment]
Please update your node. We did a few improvements to tackle this. Feel free to reopen in case it won't work.
