### ISSUE TITLE
Monitoring failed

### ISSUE THREAD

**Issue by speedf1** [mysteriumnetwork/node#5634]
Node status is shown as "monitoring failed". [mystnodes.com](http://mystnodes.com/) also shows this node as "Connection failed". This node had been working until a few days ago.

Node is 0x04277ccf66243e96b11161096d2952f8e93e6eaa, running Node version:1.19.5, Node UI version:2.3.2

**Comment by etherunit** [comment]
@speedf1 I can see that your node is online and works as expected.

[CONNECTING] From: 0xe3ba8dc9cde3f53aef8601e97f3d03a707cf33cb to: 0x04277ccf66243e96b11161096d2952f8e93e6eaa

```
[SUCCESS] Connected.
» status
[INFO] Status:Connected
[INFO] SID:d3b82d45-303e-4ee8-bc68-cab97d0d305b
[INFO] Location: Brighton, GB (residential - TalkTalk Communications Limited)
[INFO] Proposal:Provider: 0x04277ccf66243e96b11161096d2952f8e93e6eaa, ServiceType: data_transfer, Country: GB
```
