### ISSUE TITLE
Multiple B2B VPN and data transfer connections but no data transferred 

### ISSUE THREAD

**Issue by craigellis1986** [mysteriumnetwork/node#5639]
**Describe the bug**
The node sees multiple connections for B2B VPN and data transfer but there is never any traffic transferred.  It always shows 0 bytes.

**To Reproduce**
Viewin the history of the node shows B2B VPN and data transfer and 0 bytes.

**Expected behavior**
Data should be transferred meaning the number of bytes increases from 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/118891755/203517760-0424c061-0b3b-410f-b6ff-faa3f70e54bf.png)

**Environment (please complete the following information):**
 - Node version: 1.19.5
 - OS: Windows 11
 - Desktop app version (if applicable): 2.3.2
 - Your identity 0xdfb18087adaa4ac43a7260c9bb96067db657d395

**Comment by etherunit** [comment]
related to https://github.com/mysteriumnetwork/node/issues/5627
