### ISSUE TITLE
#5586 Was closed without any resolution

### ISSUE THREAD

**Issue by strongbow1** [mysteriumnetwork/node#5641]
Following up on my bug report #5586 the Issue remains. I have lost 5 Myst and the error is still shown on my node.

Closing, a bug without any resolution is pure lack of customer support and lack of know how. No attempt has been made to actually solve my issue. 

So thus I am opening a ticket for the SAME issue, please find attached the issue that is still a problem and yet, my bug report was closed without any resolution.
![mysterium](https://user-images.githubusercontent.com/21293934/203759281-57e3e739-5a0d-42b5-b385-337cd11a0f7c.png)
![MYST Error](https://user-images.githubusercontent.com/21293934/203759375-956d27d8-6977-4c1d-9c9b-2e343da06271.png)

**Comment by Guillembonet** [comment]
checked and there is no missing transaction, explained in the other issue

**Comment by strongbow1** [comment]
You have not checked anything!! The issue is still remaining
