### ISSUE TITLE
My node is running but no session time

### ISSUE THREAD

**Issue by mrcryptodollars** [mysteriumnetwork/node#5644]
**Describe the bug**
so simply, installed software from mysterium the native launcher and i ran it, but when i opened my nodes, it was stating that connection failed. while its online on my dashboard .i left it on for a day. But nothing 0:0:0 session time it never started .so i complained about this to the support. I haven't used docker coz i already paid to the native launcher so i already have an account there but if i tried to use docker it was asking me to create new node. so, i stopped and came here in search of help.

I restarted my device several time but same issue .

**Expected behavior**
i expected maybe restarting system will make it work .

**Screenshots**
![Web capture_24-11-2022_5423_mystnodes com](https://user-images.githubusercontent.com/118986116/203798863-48da3b9f-e8b3-446e-90d0-5a53cf60241a.jpeg)

**Environment (please complete the following information):**
 - Node version: 1.19.5

 - OS: Windows
![Web capture_24-11-2022_53136_localhost](https://user-images.githubusercontent.com/118986116/203796550-6321f452-e535-4fc2-84f1-9f5c8f4250a0.jpeg)

 - Desktop app version (if applicable): [
![Screenshot 2022-11-24 053432](https://user-images.githubusercontent.com/118986116/203797103-8f1f2c35-2bf9-4860-aa5a-08e980d757cf.png)

 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x372a2457b8d9d47a17dd8709cffd21e4cc844cdc
 - Payment (top-op) reference : paid myst token 0.45 via 0x4DAceD6B1715b325634529636f610AbDcD128E3d
 - 
 - 
 - ![Screenshot 2022-11-23 020533](https://user-images.githubusercontent.com/118986116/203799884-9eca02ed-11d8-4fe8-a974-7b6684092748.png)

**Additional context**
Help me out please , it's been a day and i'm stuck in this

**Comment by isaackielma** [comment]
Logs:

https://mystnodes.com/support/logs/2022-11-24-812193d7-b6c3-4a92-a3d6-5bc5c617c300-mysterium-node.zip558398165

**Comment by 825i** [comment]
Read the readme dude. You have port restricted NAT. Nothing can see you.

**Comment by mrcryptodollars** [comment]
can you guide me how to do it ?

**Comment by mrcryptodollars** [comment]
> Read the readme dude and official docs. You have port restricted NAT. Nothing can see you.

Can you help me with that ?
Guide me ?

**Comment by Loggsie** [comment]
> > Read the readme dude and official docs. You have port restricted NAT. Nothing can see you.
> 
> Can you help me with that ?
> Guide me ?

Set on Node GUI settings -> advanced -> port range 10000-60000 -> save

Access router administration settings and port forward to Node LAN IP range 10000-60000 (UDP only) -> save

Reboot Node

On Node GUI settings -> advanced -> NAT transversal should now either say 'Most' or 'All' the node is now visible to the Mysterium Network.

**Comment by mrcryptodollars** [comment]
![Web capture_25-11-2022_04747_localhost](https://user-images.githubusercontent.com/118986116/203939098-c7d82d33-88d5-4d6c-a9eb-1a40d86b2e95.jpeg)


Watch this

**Comment by Loggsie** [comment]
You've the exact same issue I'm trying to overcome, my node went offline recently and it struggles to become visible to the network again.

Null output with your node

https://discovery.mysterium.network/api/v3/proposals?provider_id=0x372a2457b8d9d47a17dd8709cffd21e4cc844cdc
