### ISSUE TITLE
Reopen #5586 (CLOSED WITHOUT FIXING THE PROBLEM)

### ISSUE THREAD

**Issue by strongbow1** [mysteriumnetwork/node#5645]
Bug report #5586 (https://github.com/mysteriumnetwork/node/issues/5586) was YET AGAIN closed without resolution! Support have done NOTHING to help find my missing transaction that took place and failed neither are they looking into helping getting rid of the error message on my node! They just keep closing bugs without any proper investigation or resolution!

**Comment by Guillembonet** [comment]
please stick to the original issue instead of creating new ones. Refer to my replies in that issue and reply if the issue is still unclear.

**Comment by strongbow1** [comment]
Please read what the issue is about before you assume your assessment without any knowledge which you are doing
