### ISSUE TITLE
'Data Transferred' metric inconsisteny on NodeUI Homepage & History page

### ISSUE THREAD

**Issue by NeoOne117** [mysteriumnetwork/node#5649]
**Descrption :**
The 'Data Transferred' metric on the NodeUI homepage is different from the one shown on the history page.

**To Reproduce :**
1. Go to 'NodeUI Homepage'
2. Check the sessionID and see data transferred
3. Go to 'History' page
4. Check for the same sessionID, shows different data

**Expected behavior :**
'Data Transferred' should be same/close to similar on both pages witout a drastic difference.

**Screenshots :**
1. 'Data Transferred' on homepage.

<img width="1509" alt="Screenshot 2022-11-25 at 7 59 02 AM" src="https://user-images.githubusercontent.com/41228015/203889150-8f301951-6f71-4b94-ab3e-054ef7caf93a.png">

2. 'Data Transferred' on history page.

<img width="1469" alt="Screenshot 2022-11-25 at 7 58 47 AM" src="https://user-images.githubusercontent.com/41228015/203889232-4359c669-5465-46ca-a35e-702ca8e267ba.png">

**Environment :**
 - Node version: 1.19.5
 - OS: Debian 11 (bullseye) aarch64
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): Docker version 20.10.21, build baeda1f | image tag : 1.19.5-alpine
 - Your identity (if applicable): 0x277d0fccbcf0edf9d39da01d90fbf1f6b2e28810
 - Payment (top-op) reference (if applicable): N/A

**Comment by NeoOne117** [comment]
> @NeoOne117 Could you check it now?

The data is still inconsistent.

Homepage : 
<img width="1514" alt="Screenshot 2022-12-02 at 8 11 56 PM" src="https://user-images.githubusercontent.com/41228015/205318252-3a18e04c-7068-46d2-8954-81cdc7433cce.png">

History Page :
<img width="1420" alt="Screenshot 2022-12-02 at 8 12 06 PM" src="https://user-images.githubusercontent.com/41228015/205318302-5a71c84d-716d-4155-8f58-c5b81903108b.png">

**Comment by NeoOne117** [comment]
> @NeoOne117 Could you check it now?

Keeps changing in the history page, but static on now for the homepage.

Homepage :
<img width="1534" alt="Screenshot 2022-12-02 at 9 29 16 PM" src="https://user-images.githubusercontent.com/41228015/205334055-5d2c0423-0f60-4f28-82d6-35912578d41e.png">

History Page :
<img width="1528" alt="Screenshot 2022-12-02 at 9 29 30 PM" src="https://user-images.githubusercontent.com/41228015/205334102-2b54dc81-aac1-4c6c-9a4e-5095d71756c2.png">

**Comment by etherunit** [comment]
@NeoOne117 We did some important improvements that should help to avoid discrepancies in metrics such as earnings, data transfer, session counts etc. Please check and confirm it's resolved on your end.
