### ISSUE TITLE
Node offline

### ISSUE THREAD

**Issue by Ondevento** [mysteriumnetwork/node#5653]
**Describe the bug**
**To Reproduce**
**Expected behavior**
**Screenshots**
**Environment (please complete the following information):**
- Node version: [e.g. 0.19.1]
- OS: [e.g. raspbian buster, debian 10]
- Desktop app version (if applicable): [e.g. 2.0.4]
- Docker (if applicable): specify docker version and image tag
- Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
- Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]
**Additional context**
Node version 1.19.6 OS: Alpine linux v3.14 (docker) Desktop app versionNode UI version:
2.3.2 identity 0xe43ea1dc186578597dee58dd6203283b744566f2 type error: node status Monitoring failed , node offline

**Comment by etherunit** [comment]
@Ondevento Most connections are reported as `data_transfer-internet_fail`.
I suspect there are certain issues with firewall or DNS configuration on your end.
<img width="774" alt="Screen Shot 2022-12-01 at 11 45 23" src="https://user-images.githubusercontent.com/60128746/205020517-6615d30a-e315-425f-b079-ee1feec91a09.png">
Can you please check that?
