### ISSUE TITLE
"Monitoring failed" status after latest update

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5656]
**Describe the bug**

Node is no more working after lat update 1.19.4

**To Reproduce**

1. Update node to latest version
2. go on the node UI and on top there is the status “monitoring failed, contact support"

**Expected behavior**

Update should not affect node status.

**Screenshots**
<img width="1085" alt="Screenshot 2022-11-28 at 21 47 19" src="https://user-images.githubusercontent.com/84313603/204410958-25ea5559-8187-44cc-96df-eb724546a65e.png">

**Environment (please complete the following information):**

- Node version: 1.19.4

- OS: Linux ( COTX hardware )

- Your identity (if applicable): 0x2ba9a75d6d43fd92e18368bb06e46c4f0da56088

**Additional context**

Logs:

https://mystnodes.com/support/logs/2022-11-02-20d82c84-7a5a-49f9-ab62-07a09fbfc153-mysterium-node.zip1238047244

**Comment by etherunit** [comment]
@isaackielma Suggest them to update & restart.
