### ISSUE TITLE
Connection Failed (Controllino node)

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5657]
**Describe the bug**
The node is not working and showing connection failed.

**Expected behavior**
Node should work after update

**Environment (please complete the following information):**
- Node version:
1.19.6
- Node UI version:
2.3.2
- OS: Alpine linux v3.14 (docker)

- Your identity 0xe43ea1dc186578597dee58dd6203283b744566f2

**Additional context**
Add any other context about the problem here.type error: node status Monitoring failed and status Connection failed

**Comment by etherunit** [comment]
@isaackielma Currently, we are blocked from any further troubleshooting process because Controllino is delaying with device verification. Once we will have it verified, team will continue to investigate it.

**Comment by etherunit** [comment]
For now, please inform them that team is working on it and will provide an update soon.
