### ISSUE TITLE
My nodes have the status monitoring failed

### ISSUE THREAD

**Issue by TheophileDiot** [mysteriumnetwork/node#5659]
It's been weeks since I updated my nodes to 1.9.4 and I kept upgrading them to the newer version but it changes nothing.
Any idea ?
![image](https://user-images.githubusercontent.com/57175294/205249259-aa914d95-67cc-4bec-b0e8-3e0e90fc9ff9.png)
![image](https://user-images.githubusercontent.com/57175294/205249335-be2152c6-7540-4fc4-b537-e6dd72a90d9e.png)

**Comment by etherunit** [comment]
Could you copy > paste your identities into the issue? Thanks!

**Comment by TheophileDiot** [comment]
Sure
0x456783d63a51832d2431fe21b58d6147a29e19b7
0xd6a4c51dba04c471665376d6dbb8f05ad193093e
0x2b6c74e0322181e2d4cde0a2e7a1c53bd698a503
0xdd897fb6e356107908fe20a79c8b71bc2b3c6717

**Comment by TheophileDiot** [comment]
@etherunit any good news ?

**Comment by etherunit** [comment]
Thanks for providing it and apologies for a delayed reply. Seemingly, all your nodes are hosted in Oracle's cloud. From my previous experience, Oracle implies some restrictions in routing packets. For this reason, all your nodes are marked with internet_fail tag (could not open webpages). 

Please provide us with the output of `sudo iptables-save` from one of the servers. Thank you.

**Comment by etherunit** [comment]
I

**Comment by etherunit** [comment]
Closed due to inactivity. The issue will be re-opened once we hear you back.

**Comment by TheophileDiot** [comment]
Hi, sorry. I didn't see your message
Here's some of my iptables infos :
```# Generated by iptables-save v1.8.7 on Mon Jan 16 10:57:32 2023
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
-A INPUT -p udp -m multiport --ports 10000:60000 -j ACCEPT
-A INPUT -p udp -m udp --dport 4449 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 4449 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
# Completed on Mon Jan 16 10:57:32 2023
# Generated by iptables-save v1.8.7 on Mon Jan 16 10:57:32 2023
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:MYST - [0:0]
-A MYST -d 10.0.0.0/8 -j DNAT --to-destination 240.0.0.1
-A MYST -d 172.16.0.0/12 -j DNAT --to-destination 240.0.0.1
-A MYST -d 192.168.0.0/16 -j DNAT --to-destination 240.0.0.1
-A MYST -d 127.0.0.0/8 -j DNAT --to-destination 240.0.0.1
COMMIT
# Completed on Mon Jan 16 10:57:32 2023```
I hope this helps

**Comment by TheophileDiot** [comment]
@etherunit
