### ISSUE TITLE
Monitoring Failed/Connection Failed

### ISSUE THREAD

**Issue by davoede** [mysteriumnetwork/node#5662]
Hi,

Node gives 'Monitoring Failed' in Node UI and 'Connection Failed'  in My Nodes.
Also Incoming Connections to the node are never more than a few 100 Bytes.

 - Node version: 1.19.6
 - OS: Linux Mint 20.3 Cinnamon
 - Your identity : 0x9108c2e3319603dd0cc3e08aa1e3a400551cb647

![Schermafdruk van 2022-12-05 02-12-46](https://user-images.githubusercontent.com/12674397/205529171-4e5969f9-25eb-418f-8651-71784100be8a.png)
![Schermafdruk van 2022-12-05 02-14-32](https://user-images.githubusercontent.com/12674397/205529178-bc26c7e2-b83c-4b77-94a7-796f5caeb18b.png)

**Comment by davoede** [comment]
Apparently the node is back online, haven't changed anything...

**Comment by etherunit** [comment]
![Screen Shot 2022-12-07 at 14 30 35](https://user-images.githubusercontent.com/60128746/206179892-183eb885-0f0b-4c41-b722-7230743401f4.png)
It looks like most test connections are being marked as `data_transfer - internet_fail.` Can you please check and verify that firewall is not blocking any connections?

**Comment by davoede** [comment]
Hi etherunit,

Apparently my ISP had problems with the network. My node is working perfectly now. Thank you for the help.
