### ISSUE TITLE
Connection Failed on WebUI but NodeUI shows connected ...

### ISSUE THREAD

**Issue by chainworksindustries** [mysteriumnetwork/node#5664]
**Describe the bug**

Hi!
It seems that on occasion the link between the Docker Container here (in Fedora 36) and the 'MyNodes' are connected - then drops with 'Connection Failed' on the MyNodes DashBoard for the rest of the Time.
this is after I have messed around with a few setups (includign opening Ports/PortForwarding/FireWallSeetings in Fedora) and paying the Credit Card Fee for MYST to run these things, with still no success. When Testing the Node from the MysNodes DashBoard - it seems to work, but somewhere there is an issue.
I am no newbie here - not in IT (30+ Years) or Crypto (12Years) - but there is something here that is not right.
As mentioned - currently it is a Docker Image that is running, but I have tried a Native install also into Fedora and the same thing happens. If I try again, the fpurth Fee will have to be paid - and as small as 1USD is - it gets frustrating when I have MANY systems (and IP's) I can get running here.
Please help
Ray - CWI

**To Reproduce**

Just run the Node from the Docker Container - even after Firewall and Router Ports are open, there is still an error of 'Connection Failed' in the Web Interface, but shows 'Open' and connected win the NodeUI.

**Expected behavior**

'Connection Failed' error on WebSite Account. No data transferred even though 'testing the node' works flawlessly fro what I can see.

**Screenshots**

1 - ScreenShots Sent the first Chat in WebSite Chat.
2 - No ScreenShots sent in the referred to 'bug report' in the NodeUI.
3 - now referred to here for this SAME issue - so reporting 3Times now.

**Environment (please complete the following information):**
 - Node version: 1.19.7
 - OS: Fedora 37
 - Desktop app version (if applicable): NA
 - Docker (if applicable): "docker version" accepts no arguments.
See 'docker version --help'.

Usage:  docker version [OPTIONS]

Show the Docker version information
[root@cwi-node system]# docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:34 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

 - Your identity (if applicable): 0x8595b82b5a47cc7e784e11a430337f47de32799b
 - Payment (top-op) reference (if applicable): No Idea what that is - had to pay three times to get ONE version working and now have these issues.

**Additional context**

It seems I am not the only one here with a very similar (if not the same) issue. I will get this installed into a VPS this week - to see if there is any differences in workings.

Just wondering ... Could SELinux be an issue here? If so, How? It seems SELinux interferes with almost everything in CentOS and Fedora, so this could be something to look into. Just a thought!

Update - Same thing is happening with CentOS 9 Stream on Digital Ocean VPS using Docker Container.

#crysx #cwi

**Comment by chainworksindustries** [comment]
![Screenshot from 2022-12-06 22-39-25](https://user-images.githubusercontent.com/24930403/205909100-46fd4bbf-f186-41aa-b25e-bcbcdeeaf79e.png)
![Screenshot from 2022-12-06 22-41-31](https://user-images.githubusercontent.com/24930403/205909209-a02de478-b672-4a94-b61c-47237e24793c.png)

**Comment by etherunit** [comment]
@chainworksindustries Hi, unfortunately, we are not able to diagnose your node due to offline status. Please turn it on so we can continue looking into it. Thank you

**Comment by chainworksindustries** [comment]
The Node is Current ...

Try diagnosing this one Please - 0x33172141d5cbd54bad114bead3ead633e94794ab

That one is on all the Time. I see there are more with Similar issues as these.

Thanks for Your Efforts!

#crysx #cwi

**Comment by etherunit** [comment]
Concerning your last identity. Below is the output I got while testing it:

```
[ERROR] Failed to connect: could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session c300fdb4-0e37-4e15-ab1f-d19b7c959af5: failed to setup NAT/firewall rules: error calling IPTables: "/usr/sbin/iptables -I PREROUTING 1 --source 10.182.121.2/24 --jump MYST --table nat": exit status 3 output: iptables v1.8.7 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

Firstly, you can simply try to reboot your system. If that doesn't help, check below:

iptalbes tool relies on a kernel module interacting with netfilter to control network traffic. This error happens while iptables cannot found that module in kernel, so iptables suggest you to upgrade it. 

`Perhaps iptables or your kernel needs to be upgraded.`

However in most cases it's just the module not added to kernel or being banned, try this command to check whether be banned:

`cd /etc/modprobe.d/ && grep -nr iptable_nat`

if the command shows any rule matched, such as `blacklist iptable_nat` or `install iptable_nat /bin/true`, delete it. Since iptables will cost some performance, it's not strange to ban it while not necessary.

If nothing found in blacklist, try add `iptable-nat` to the kernel manually:

`modprobe iptable-nat`

If all of above not works, you can consider upgrading your kernel.

**Comment by etherunit** [comment]
any updates @chainworksindustries ?

**Comment by etherunit** [comment]
We are closing this issue due to no updates. This issue will be re-opened once we hear you back.
