### ISSUE TITLE
Monitoring Failed after update 1.19.7 on WebUI but NodeUI online and sessions active

### ISSUE THREAD

**Issue by rhulsebos** [mysteriumnetwork/node#5665]
I have 3 out of 4 nodes showing up with  "Monitoring Failed " under My Nodes in WebUI after updating to Node version 1.19.7
the nodes run Ubuntu 22.04.1 LTS and one on Raspbian 5.10.103.
Nodes run in 4 different counrtys in data centers and with ample bandwith, and most have been functional a longer periode of time, and producing just fine.
And furthermore one of the nodes is showing up as a Linux machine after the update to version 1.19.7 in the My Nodes WebUI and this is infact a Raspbian 5.10.103. (schreenshots added

**To Reproduce**

**Expected behavior**

**Screenshots**
![myst-error-01](https://user-images.githubusercontent.com/43217745/206118779-8480b6ba-2231-4145-b39b-bd9e1d7554cf.jpg)
![myst-error-02](https://user-images.githubusercontent.com/43217745/206118803-4ce4cd8c-c44c-4aff-8131-950e3e241027.jpg)

**Environment (please complete the following information):**
 - Node version: 1.19.7
 - OS: Ubuntu 22.04.1 LTS, Linux raspberrypi 5.10.103-v7l+
 - Desktop app version: Brave v1.46.134, Firefox 107.01
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x12c3020441573a511a24045186e00974e6cb8307, 0x211c21f45b9aebfd0de3ea36a3cc082ba9e72271, 0xf6b818ab98af9410eb108fc7999ab9ed18e67bcd
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
Sinds this morning i'm also getting an editional error refreshing the NodeUI itself (0x12c3020441573a511a24045186e00974e6cb8307) page "Could not get provider sessions list: json: cannot unmarshal object into Go value of type []node.SessionItem"

**Comment by rhulsebos** [comment]
Anyone know how to downgrade a node? 1.19.7 is not working and now it starts decreasing the reward to!

**Comment by etherunit** [comment]
@rhulsebos 
I have tested both of your nodes.

1. uk01.kynex.ch (DATA CENTER)
0x211c21f45b9aebfd0de3ea36a3cc082ba9e72271
Connection to this node works but access to the internet is restricted (while VPN'ed). Please submit the output of iptables (Linux firewall): `sudo iptables-save`
Verify that iptables rules are not blocking any traffic.

2. bunker.kynex.ch
0x12c3020441573a511a24045186e00974e6cb8307
Node is connectable and internet pages resolves normally, however, most of B2B connections are marked as `data_transfer - internet_fail`. I will investigate it further and get back to you shortly.
![Screen Shot 2022-12-13 at 09 36 21](https://user-images.githubusercontent.com/60128746/207255049-c3502376-5743-468c-85b9-4070499c0263.png)

@yeszhanov95 Can you please check why we are marking it in this way?

**Comment by rhulsebos** [comment]
> 1. sudo iptables-save

# Generated by iptables-save v1.8.7 on Wed Dec 14 17:18:54 2022
*filter
:INPUT DROP [118295:8066611]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [528:30796]
:ufw-after-forward - [0:0]
:ufw-after-input - [0:0]
:ufw-after-logging-forward - [0:0]
:ufw-after-logging-input - [0:0]
:ufw-after-logging-output - [0:0]
:ufw-after-output - [0:0]
:ufw-before-forward - [0:0]
:ufw-before-input - [0:0]
:ufw-before-logging-forward - [0:0]
:ufw-before-logging-input - [0:0]
:ufw-before-logging-output - [0:0]
:ufw-before-output - [0:0]
:ufw-logging-allow - [0:0]
:ufw-logging-deny - [0:0]
:ufw-not-local - [0:0]
:ufw-reject-forward - [0:0]
:ufw-reject-input - [0:0]
:ufw-reject-output - [0:0]
:ufw-skip-to-policy-forward - [0:0]
:ufw-skip-to-policy-input - [0:0]
:ufw-skip-to-policy-output - [0:0]
:ufw-track-forward - [0:0]
:ufw-track-input - [0:0]
:ufw-track-output - [0:0]
:ufw-user-forward - [0:0]
:ufw-user-input - [0:0]
:ufw-user-limit - [0:0]
:ufw-user-limit-accept - [0:0]
:ufw-user-logging-forward - [0:0]
:ufw-user-logging-input - [0:0]
:ufw-user-logging-output - [0:0]
:ufw-user-output - [0:0]
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -j ufw-after-input
-A INPUT -j ufw-after-logging-input
-A INPUT -j ufw-reject-input
-A INPUT -j ufw-track-input
-A FORWARD -j ufw-before-logging-forward
-A FORWARD -j ufw-before-forward
-A FORWARD -j ufw-after-forward
-A FORWARD -j ufw-after-logging-forward
-A FORWARD -j ufw-reject-forward
-A FORWARD -j ufw-track-forward
-A OUTPUT -j ufw-before-logging-output
-A OUTPUT -j ufw-before-output
-A OUTPUT -j ufw-after-output
-A OUTPUT -j ufw-after-logging-output
-A OUTPUT -j ufw-reject-output
-A OUTPUT -j ufw-track-output
-A ufw-after-input -p udp -m udp --dport 137 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 138 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 139 -j ufw-skip-to-policy-input
-A ufw-after-input -p tcp -m tcp --dport 445 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 67 -j ufw-skip-to-policy-input
-A ufw-after-input -p udp -m udp --dport 68 -j ufw-skip-to-policy-input
-A ufw-after-input -m addrtype --dst-type BROADCAST -j ufw-skip-to-policy-input
-A ufw-after-logging-forward -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW BLOCK] "
-A ufw-after-logging-input -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW BLOCK] "
-A ufw-before-forward -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-forward -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-forward -j ufw-user-forward
-A ufw-before-input -i lo -j ACCEPT
-A ufw-before-input -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-input -m conntrack --ctstate INVALID -j ufw-logging-deny
-A ufw-before-input -m conntrack --ctstate INVALID -j DROP
-A ufw-before-input -p icmp -m icmp --icmp-type 3 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 11 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 12 -j ACCEPT
-A ufw-before-input -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A ufw-before-input -p udp -m udp --sport 67 --dport 68 -j ACCEPT
-A ufw-before-input -j ufw-not-local
-A ufw-before-input -d 224.0.0.251/32 -p udp -m udp --dport 5353 -j ACCEPT
-A ufw-before-input -d 239.255.255.250/32 -p udp -m udp --dport 1900 -j ACCEPT
-A ufw-before-input -j ufw-user-input
-A ufw-before-output -o lo -j ACCEPT
-A ufw-before-output -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A ufw-before-output -j ufw-user-output
-A ufw-logging-allow -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW ALLOW] "
-A ufw-logging-deny -m conntrack --ctstate INVALID -m limit --limit 3/min --limit-burst 10 -j RETURN
-A ufw-logging-deny -m limit --limit 3/min --limit-burst 10 -j LOG --log-prefix "[UFW BLOCK] "
-A ufw-not-local -m addrtype --dst-type LOCAL -j RETURN
-A ufw-not-local -m addrtype --dst-type MULTICAST -j RETURN
-A ufw-not-local -m addrtype --dst-type BROADCAST -j RETURN
-A ufw-not-local -m limit --limit 3/min --limit-burst 10 -j ufw-logging-deny
-A ufw-not-local -j DROP
-A ufw-skip-to-policy-forward -j DROP
-A ufw-skip-to-policy-input -j DROP
-A ufw-skip-to-policy-output -j ACCEPT
-A ufw-track-output -p tcp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-track-output -p udp -m conntrack --ctstate NEW -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 22 -j ACCEPT
-A ufw-user-input -p udp -m udp --dport 1194 -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 1194 -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 19302 -j ACCEPT
-A ufw-user-input -p udp -m udp --dport 19302 -j ACCEPT
-A ufw-user-input -p udp -m udp --dport 4449 -j ACCEPT
-A ufw-user-input -p tcp -m tcp --dport 4449 -j ACCEPT
-A ufw-user-limit -m limit --limit 3/min -j LOG --log-prefix "[UFW LIMIT BLOCK] "
-A ufw-user-limit -j REJECT --reject-with icmp-port-unreachable
-A ufw-user-limit-accept -j ACCEPT
COMMIT
# Completed on Wed Dec 14 17:18:54 2022
# Generated by iptables-save v1.8.7 on Wed Dec 14 17:18:54 2022
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:MYST - [0:0]
-A MYST -d 10.0.0.0/8 -j DNAT --to-destination 240.0.0.1
-A MYST -d 172.16.0.0/12 -j DNAT --to-destination 240.0.0.1
-A MYST -d 192.168.0.0/16 -j DNAT --to-destination 240.0.0.1
-A MYST -d 127.0.0.0/8 -j DNAT --to-destination 240.0.0.1
COMMIT
# Completed on Wed Dec 14 17:18:54 2022

**Comment by etherunit** [comment]
Thanks for the output. Any reason `:INPUT` & `:FORWARD` policies are set to`DROP`?
The quick fix would be to set it to accept and then check again.
