### ISSUE TITLE
NodeUI says status online - Mystnodes returns Connection failed.

### ISSUE THREAD

**Issue by Geestig** [mysteriumnetwork/node#5668]
**Describe the bug**
After enabling MYST on my COTX firmware device it worked during half a day. I then moved it so it could work through WIFI (stable) but ever since that change MYST no longer is farmed. In the meanwhile I've reactived another node, tried it back on ethernet, both with and without an access point in between with no results. I can access my dashboard, both locally and through public IP. 

When I press the test connection button I see the test connection in my dashboard. It stays there for over a minute. When rebooting my device Mystnodes returns 'online' as status. But when I test the connection and the 'test session' ends it gets returned back to 'Connection failed'. 

According to: https://discovery.mysterium.network/api/v3/proposals?include_monitoring_failed=true&provider_id=0x6b6a471e28ff1bf6e5feda0b47c9d15d243b25a9 
I seems like i have very high latency which shouldnt be the case since my internet is very stable and runs at 150+ mbps consistently. This doesnt change when I use the device on Wifi, Ethernet through router, Ethernet directly into main router, ...

**To Reproduce**
1. Reboot device.
2. Wait for MYST node to boot.
3. Check NodeUI to see Status online.
4. Check Mystnodes to see Status online.
5. Run test connection on Mystnodes.
6. See session start in NodeUI.
7. Wait for session to end.
8. Check NodeUI to see Status online.
9. Check Mystnodes to see Status connection failed.

**Expected behavior**
It should just work - NodeUI says it's fine, test sessions enter.

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Your identity (if applicable): 0x6b6a471e28ff1bf6e5feda0b47c9d15d243b25a9

**Additional context**
Already contacted COTX support and on their end everything works fine. They think my IP might need to be refreshed or something along those lines so maybe my public IP is stored somewhere disabling any incoming connections. I have disabled firewall, enabled upnp, forwarded all the required ports, etc.

**Comment by etherunit** [comment]
For some reason, it reports as still using hole_punching mechanism. Could you please check that and switch to upnp?

**Comment by Geestig** [comment]
uPNP should already be enabled.

**Comment by etherunit** [comment]
For some reason, it still reports as holepunching is in use. 
Please make sure that uPnP is activated on your router and also prioritised under Advanced Settings > NAT traversal (drag&drop it to the 1st position).

**Comment by etherunit** [comment]
Any updates @Geestig ?
