### ISSUE TITLE
MystNode "Monitoring failed" warning, replacing green "online" Status, on UI

### ISSUE THREAD

**Issue by PipBowl** [mysteriumnetwork/node#5669]
**Describe the bug**
The app has been great. Yesterday i noticed a red "Monitoring failed" had replaced my green "online status". Tried rebooting a bit. Nothing. Tried waiting lol nothing. Contacted support on Mystnodes app, presented "node ID address". Nothing. Now suggested I come here.

This is my mystnode ID address
0x12aa8da5bb5eb961cbf9e63f7d780c342f9301ea

**To Reproduce**
The node isnt running, however the pop up bar at the bottom of my laptop screen, says that it is... im also no longer earning or contributing to the network due to this.

**Expected behavior**
N\A

**Screenshots**
I dont know how, i would love too though. im more a cellphone guy after 10 years lol

**Environment (please complete the following information):**
 - Node version: 1.19.7
 - OS: Windows 8.1 (lol)
 - Desktop app version (if applicable): 1.19.7
 - Docker (if applicable): N\A (So far)
 - Your identity (if applicable): 0x12aa8da5bb5eb961cbf9e63f7d780c342f9301ea
 - Payment (top-op) reference (if applicable): N\A (so far, around a week old at this)

TIA LADIES & GENTS!
Adam
Beaverton, Ont, CA

**Comment by etherunit** [comment]
@PipBowl Please note that your node is online and works as expected. 
![Screen Shot 2022-12-13 at 09 52 26](https://user-images.githubusercontent.com/60128746/207257673-9ed45985-791c-41c7-b089-c4d779518170.png)
