### ISSUE TITLE
mystnodes.com earnings randomly decreasing

### ISSUE THREAD

**Issue by hkup859** [mysteriumnetwork/node#5673]
I'm submitting this based on a request from chat support:

**Describe the bug**
I've noticed my earnings on mystnodes.com seem to go down randomly. I check it pretty frequently and only have 1 node. There are no transactions or any other earnings related data from my node that would indicate why it is going down. When it does this it decreases by a few myst all at once, then continues growing naturally. As an example, I check it one day and my total earnings said 25.5751. I rechecked the following day and it showed 21.1294. I know that myst takes fees of 20%, but on any given settlement the fees are only around 1 myst, so that doesn't really explain what is happening.

**Theory**
I'm not certain, but I have a theory as to what is happening. Normally mystnodes.com appears to show my total gross earnings (before fees). That number naturally grows each day until I hit a settlement, when the calculation seems to change to show my total NET earnings (after fees). This would explain the dramatic decrease all at once as I've had a few settlements at this point. Further pointing to this theory is that my current mystnodes.com earnings do show the NET earnings of 19.6457, but again, yesterday it showed what I believe was my GROSS earnings. I don't believe there is anything wrong with the node itself as all of it's numbers seem to make sense and there has been no issue with transactions or anything. Either gross earnings or net earnings on mystnodes.com makes sense to me, I just don't know why it is going back and forth.

**To Reproduce**
1. Go to https://mystnodes.com/nodes and track your "Total earnings 30 days" field. 
2. Verify if this shows NET or GROSS earnings.
3. Check this field every day and record the amount.
4. After some amount of time (or likely your next settlement), see if the formula has changed from NET to GROSS or GROSS to NET.

NOTES:
* I only have 1 node, so I'm not sure if that plays a role in this.
* This is a new node, so given that this field is a 30 day total I'm not sure how it will react to a longer running node.
* Again, this only impacts the mystnodes.com website and not my node dashboard. The node dashboard seems to be performing properly.

**Expected behavior**
I expect when tracking this field on mystnodes.com the "Total earnings 30 days" field will fluctuate not just in amount, but in the formula it is using. Switching from GROSS to NET or vice versa. If that is not the case (aka if my theory above is wrong), I would expect there to be an unexpected drop in this metric when tracking it daily. 

**Environment (please complete the following information):**
 - Node OS: Raspbian

**Comment by rhulsebos** [comment]
I have the same problem, this started in Node version 1.19.7 with to me seems extreem unstable

**Comment by Ayse-AK** [comment]
@hkup859 Can you please share your node name/ID and your launcher version?

**Comment by mdomasevicius** [comment]
@hkup859 , thanks for the issue.

> As an example, I check it one day and my total earnings said 25.5751. I rechecked the following day and it showed 21.1294.

From what you describe to me it seems to be working as intended.
> Total earnings 30 days
The total earnings are for the 30 days window, meaning that this window will move next day and your earnings for 30 days period most likely will be different.

**Comment by hkup859** [comment]
My node version is 1.19.5.

**Comment by hkup859** [comment]
> I have the same problem, this started in Node version 1.19.7 with to me seems extreem unstable

@rhulsebos Is your node also new (under 30 days old) or older than 30 days? I'm curious how this bug might effect longer running nodes and if my gross vs net earnings theory holds.

**Comment by hkup859** [comment]
Okay, now the Total 30 days earnings on mystnodes.com is just entirely inaccurate. It's showing 248.5852 all of a sudden. It showed 190 or so yesterday. My single node is only reporting 46.5316 in total earnings. However this field is calculated, it's clearly extremely broken.

**Comment by cirial** [comment]
I filled a similar bug as what your seeing @hkup859.  I started my first node 7 days ago.  Mystnodes.com shows my 30 day earnings as 101 MYST, but the localui on the computer running the node has only paid out 10 MYST.  I havent heard anything about a bug fix.

**Comment by hkup859** [comment]
@cirial I'm guessing (more so hoping) that they are silently making updates to it. I have been running a node long, but this is definitely new. My guess would be they updated it to try and fix my original problem, only to cause this new one. Idk though. I guess all we can do is record what's happening and wait.

**Comment by etherunit** [comment]
@hkup859 @cirial
Apologies for a delayed reply as it took some time for our team to investigate this further and find possible solution. Please note that we have patched our internal component operating this data, therefore it should fix current and historical issues.
Could you please check and confirm it's fixed on your end?

**Comment by hkup859** [comment]
@etherunit I looked at myst nodes and confirmed it looks correct. I will keep an eye on it for a couple days to make sure it stays accurate, but this looks promising.

Thank you all for your hard work!

**Comment by cirial** [comment]
Mine looks to be correct too. Thanks!Sent from my iPhoneOn Feb 14, 2023, at 7:37 AM, hkup859 ***@***.***> wrote:﻿
@etherunit I looked at myst nodes and confirmed it looks correct. I will keep an eye on it for a couple days to make sure it stays accurate, but this looks promising.
Thank you all for your hard work!

**Comment by hkup859** [comment]
Since cirial has also confirmed it is working correctly I will go ahead and close this issue. If by chance it starts messing up after a few days I will re-open with specifics.

Thanks again!
