### ISSUE TITLE
Unable to turn on B2B services

### ISSUE THREAD

**Issue by anweshan1** [mysteriumnetwork/node#5674]
**Describe the bug**
I have been running a node, I turn on B2B VPN and data transfer and B2B Data Scraping,
but it automatically disables them, and I also get a error when turning it on on many of my nodes.
P.S. I am getting this error on all of my nodes ( i have 35 of them)
as in the 2nd attached image, I turned them by trying many times(refreshing the webui page) and clicking it again and again.
it turned on, but then it turned off automatically within a minute or so.. :(

**Expected behavior**
I expect the nodes to turn on B2B Data Scraping and B2B VPN and data transfer and do not disable them automatically.
**Screenshots**
![image](https://user-images.githubusercontent.com/88617234/206848988-080876ab-1367-41a8-a656-0d88d7feb1ce.png)
![image](https://user-images.githubusercontent.com/88617234/206850512-5146d4af-cdfc-4109-b1f3-99adc60a6072.png)
![image](https://user-images.githubusercontent.com/88617234/206850517-57e46a11-9faf-4d1d-a962-9712e64f4228.png)

**Environment :**
 - Node version: [1.19.6]
 - OS: [Ubuntu 20.04]
 - Your identity (if applicable): [0x0b3ec0d244ed499dc4866977d60c986f6ff31153]

**Comment by etherunit** [comment]
Have you manually set any flags in the node configuration file?
In the following locations:
```
/etc/default/mysterium-node
/etc/mysterium-node/config.toml
```

**Comment by anweshan1** [comment]
> Have you manually set any flags in the node configuration file? In the following locations:
> 
> ```
> /etc/default/mysterium-node
> /etc/mysterium-node/config.toml
> ```

nope, I haven't done anything(haven't messed up with anything) just installed myst using the curl link as provided and registered my node.

**Comment by etherunit** [comment]
@anweshan1 Can you please submit a node logs? It can help us to investigate it further.

**Comment by anweshan1** [comment]
[log.txt](https://github.com/mysteriumnetwork/node/files/10231468/log.txt)
here is the log file as requested @etherunit

**Comment by etherunit** [comment]
@anweshan1 One more thing - have you noticed anything under Developer consoler > Network tab once you're trying to switch it on and then until it disables? Any errors?

**Comment by anweshan1** [comment]
@etherunit 
![image](https://user-images.githubusercontent.com/88617234/208763119-5b69ab6c-bf2d-40d9-9bd6-1f7288c66630.png)
This is console tab, it errored out this time also when I tried to start, it couldn't start

**Comment by MykolasMaciekus** [comment]
@anweshan1 Can you please provide info from network tab for failed post request for services? Examples of info I need: 
![Screenshot 2023-01-03 at 14 52 23](https://user-images.githubus
![Screenshot 2023-01-03 at 14 52 48](https://user-images.githubusercontent.com/85465685/210361553-e2098211-2ddb-4351-8592-cc05e5421fe1.png)
ercontent.com/85465685/210361545-739625ea-64ae-4c2d-a0a6-c9601bc48b35.png)
![Screenshot 2023-01-03 at 14 52 32](https://user-images.githubusercontent.com/85465685/210361549-dcdd2f73-899d-4928-98cb-dcdfe3600363.png)

**Comment by anweshan1** [comment]
@MykolasMaciekus 
![image](https://user-images.githubusercontent.com/88617234/210864487-172a7f5e-3694-4717-8eab-82bdce1253ab.png)
![image](https://user-images.githubusercontent.com/88617234/210864552-9612ad17-a540-4cfb-8c18-27e262f9b64a.png)
![image](https://user-images.githubusercontent.com/88617234/210864637-e2950564-9466-4ad3-9db2-49ef80fa4380.png)

**Comment by mdomasevicius** [comment]
@anweshan1 
- Are you using adblock extensions on your browser by any chance? Can you try using incognito mode on chrome or different browser with no extensions?
- Can you also show a print out of network tab as you log into node and go to dashboard (see example image)? It seems strange that only half the requests fail.
![image](https://user-images.githubusercontent.com/20511486/210950400-aebcd148-a900-45a7-84b8-5fe4ed994f37.png)

**Comment by etherunit** [comment]
any updates @anweshan1 ?

**Comment by anweshan1** [comment]
The thing is, I killed the node where I was running it due to some problems
with hosting, so i think we have to close this :(
