### ISSUE TITLE
Connection failed but all services are GREEN.

### ISSUE THREAD

**Issue by BaGRoS** [mysteriumnetwork/node#5675]
Hi I saw similar bug many times:

![image](https://user-images.githubusercontent.com/14954591/207103106-3701fea7-8800-4fec-aaec-445741a79995.png)

All services ONLINE, but node connection failed, when I changed node version to 1.19.7, I saw change in 5 second...

![image](https://user-images.githubusercontent.com/14954591/207103359-43d86b80-0f28-4c03-84a0-2eed0c5575e8.png)

**Comment by BaGRoS** [comment]
Public?

**Comment by BaGRoS** [comment]
> @BaGRoS Hi, please send us with your node identity address. Thanks!

Public?

**Comment by etherunit** [comment]
Yes, Mysterium Identity (You can find it under Settings in UI).

**Comment by BaGRoS** [comment]
> Yes, Mysterium Identity. The one which is visible in your original description. Simply copy > paste it here.

onJfKoEj07beSr6rot8VV3c8K3M7oYyhhIDJTbfK

**Comment by BaGRoS** [comment]
> Yes, Mysterium Identity. The one which is visible in your original description. Simply copy > paste it here.

0x163557513c8e30eaa6a4fc5ffacd17164ff21f48

**Comment by BaGRoS** [comment]
> Yes, Mysterium Identity. The one which is visible in your original description. Simply copy > paste it here.

????? Any news ????

**Comment by BaGRoS** [comment]
> Yes, Mysterium Identity. The one which is visible in your original description. Simply copy > paste it here.

Any ideas?

**Comment by etherunit** [comment]
@BaGRoS Apologies for a delayed reply. I did some testing towards your node with following results:

I was able to establish connection to your node but failed to open any website ```
"Server IP address could not be found. Try: Checking the proxy, firewall, and DNS configuration."
```

I suspect there is an issue with server address translation. You can try updating the DNS address for your device running the node.

Some like to use a solution such as [Google’s public DNS](https://developers.google.com/speed/public-dns/docs/using) or [Cloudflare’s offering](https://kinsta.com/docs/cloudflare-settings-with-kinstas-cloudflare-integration/)

**Comment by BaGRoS** [comment]
On webpage 
https://mystnodes.com/nodes
my node is offline, but on node webpage is online and I see connected IPs, and tokens growing.

**Comment by etherunit** [comment]
We previously had some issues on our backend which is fixed now.
Your node is displayed as online as well as generating multiple successful connections.
![Screen Shot 2023-01-25 at 11 16 58](https://user-images.githubusercontent.com/60128746/214524691-f97e02c5-4cc5-4954-815a-9a0dee2e3242.png)
