### ISSUE TITLE
monitoring failed

### ISSUE THREAD

**Issue by CroMoTho** [mysteriumnetwork/node#5676]
Hey there, the support has directed me here. so here i am. 

in the Dashboard i can see the Text Monitoring failed please contact support. 

in the cli i can see that my node is not connected.

 But i see many data transfers on my Account

upnp is activated. can u help me with this ?

0x70c63e68413ed3c467893ffa90a87b182f5ff216

**Comment by etherunit** [comment]
@CroMoTho Unfortunately, we are not able to diagnose your node due to offline status. 
Please enable it so we can continue troubleshooting process. Thanks!

`[ERROR] Failed to connect: failed to lookup proposal: no providers available for the filter`

**Comment by CroMoTho** [comment]
ok the node is currently online yet

**Comment by etherunit** [comment]
We did several connection tests. What we found:

1. uPnP is not active, therefore it's "failover" to other NAT traversal method, in this case - hole punching. I suggest you to switch and try uPnP.
2. Previously, any connection attempt was failing, currently - it's connecting but failing to resolve internet pages, it is just not opening/loading while connected to your node.

Do you have a DNS server assigned by your ISP or some custom DNS server entry configured? 
Do you have a firewall which might potentially block any traffic?

**Comment by etherunit** [comment]
Can you please change DNS to some public one (Google, Cloudflare) and do service checks again?

**Comment by CroMoTho** [comment]
on my pc i have change the DNS to google and a other one. i will take a look for a ipv6 DNS. 
with the change of the ipv4 DNS it dosnt work.

i will get a new router in the next few days,and i will try the port forwarding again.

**Comment by CroMoTho** [comment]
ok here i am with a new node and router but with the same issue. i have set up the node to holepunch, upnp and IPv$ Exposure. but all these dont work for me 

  > Failed to lookup host: "broker.mysterium.network" error="lookup broker.mysterium.network on 192.168.178.1:53: dial udp 192.168.178.1:53: i/o timeout"

my new ID: 0xc33b9f06432dcbc98562560ca872cd5ab5a8bc7c


thank you for your help

**Comment by etherunit** [comment]
@CroMoTho I dont see such node online. Can you please double-check it on your end? Thanks

**Comment by CroMoTho** [comment]
i currently lost my Node. The OS of my PI are crashed. i write you soon with my new Node ID.

**Comment by CroMoTho** [comment]
Here i am: 0x6159efcc162d584ca6f41e72d179d4cc9a99f781

**Comment by etherunit** [comment]
@CroMoTho Apologies for a delayed reply. Please note that your node is offline making it impossible to diagnose. Please enable your service so we can continue troubleshooting it.
Thanks.

**Comment by CroMoTho** [comment]
ok no problem. i had given up hope, but well lets go. 

please use this Node: 0x5fe7e8786d029880f5002f02341d11e0b56cd187

but iam not 24/7 online with this device. so when are u Online?

**Comment by CroMoTho** [comment]
hey there. i got the Problem. i have a DS-Lite connection. The Lite Version is the Problem. i have now a IPv4 Address, and it works almost fine.
