### ISSUE TITLE
All nodes on VPS are "connection failed"

### ISSUE THREAD

**Issue by kogoromori** [mysteriumnetwork/node#5678]
Hello,

I'm running 6 Myst-Nodes myself, 1 is residential at my Laptop, works fine.
The other 5 are running on VPS hosted in datacenters. Every vps is hosted at a different provider, but they have all the same problem.
"Connection failed", shown at /nodes.
They're running on Debian-machines via Docker.
3 of them are "Connection failed" at /nodes, but online in their dashboards, and they have all earned 0 Myst.
The 2 other ones are also "Connection failed" but they show "Monitoring failed" in their dashboards and they have earned something, but a very very low amount. Like 0.00001 Myst per day.

**To Reproduce**
1. Installed those nodes freshly, latest versions.
2. Go to https://mystnodes.com/nodes and see at first Online
3. Later it will change to "Connection failed" and stay like that

**Expected behavior**
I was in touch with the support for some days, but no solution was found.

**Screenshots**
>Nodes at /nodes
![Nodes at /nodes](https://abload.de/img/screenshot2022-12-14agdelv.png)

>Node: 0x7c8d1efc454323dc949659b1762ae7d080a87e01 (Racknerd, US) (Connection failed but dashboard says online)
![Node:0x7c8d1efc454323dc949659b1762ae7d080a87e01 hosted at Racknerd (US)](https://abload.de/img/screenshot2022-12-14a9gftn.png)

>Node: 0x0492ccf56d31bcbdb3de42f0d5bc52a2586dd107 (Lansol, Germany) (Connection failed, dashboard says Monitoring failed)
![Node: 0x0492ccf56d31bcbdb3de42f0d5bc52a2586dd107](https://abload.de/img/mysterium_node_ui_-_2jti7i.png)

>And it's settings (every node has the same settings)
![Settings](https://abload.de/img/screenshot2022-12-14ax8f72.png)

Since they're all look the same, i only uploaded 2.
One with monitoring failed and one without.

**Environment (please complete the following information):**
 - Node version: 1.19.7
 - OS: Debian 10, Debian 11
 - Docker (if applicable): Docker version 20.10.21, build baeda1f (latest)
 - Your identity (if applicable): [0x7c8d1efc454323dc949659b1762ae7d080a87e01] , [0x84e24a831d4e6f2acebb8712dcdd55d172fcbda6] , [0x0492ccf56d31bcbdb3de42f0d5bc52a2586dd107] , [0x28fd5e161f7fd3763d33a45b9093a28905e2b607] , [0x1b9ba462f12c2c68c201d0139840361d1281f612]

**Additional context**
If you need any more informations (logs, etc), let me know. (also where and how to get those infos ;))

**Comment by etherunit** [comment]
@kogoromori Thanks for reporting. I will continue updating in #5679 and close this duplicated one.

**Comment by kogoromori** [comment]
Since #5679 was closed, maybe we could open this issue again?
