### ISSUE TITLE
Connection failed - locally all services are green

### ISSUE THREAD

**Issue by apedance** [mysteriumnetwork/node#5679]
3 Machines

2x Linux: Debian 11 with Docker environment.

1x Windows 10 latest with Native/docker windows version of myst running in docker mode.

Hi! Another issue with connection failed despite being online.

Manual Port Forward active on router and working.
UPnP enabled on router and working. Game consoles are able to set UPnP ports.

ID: 0xcb9eb0ac98bcb503c44e5f20f64877c8818bd51e

![image](https://user-images.githubusercontent.com/4264240/207574152-4064e2fb-4730-40e8-822f-3caf9f3d24f8.png)

![Untitled](https://user-images.githubusercontent.com/4264240/207574482-dfa9bd8c-8f06-41ef-b893-dce24a960152.png)

![image](https://user-images.githubusercontent.com/4264240/207575374-0b8b4767-e0a3-4073-ac2b-a86018b3394e.png)

![image](https://user-images.githubusercontent.com/4264240/207575665-c65f9334-a336-4c86-a30a-6e3e28a6dce8.png)

**Comment by apedance** [comment]
Problem on 3 different nodes.
![image](https://user-images.githubusercontent.com/4264240/208155829-b047fcb7-8de1-4fcd-8404-e60cc284410a.png)

1x Windows as seen above.

2x
OS: Debian 11
1.19.7

0x9564eeaa48a104778c33f50735db2580045416b3
0x84d885ba47150d88bc194fac22ff5d9b3763ca9d



Getting connections without exceeding 1,5kb
![image](https://user-images.githubusercontent.com/4264240/208156057-71f6268e-19f9-4d63-9b98-3beb675da95a.png)

Monitoring failed.
![image](https://user-images.githubusercontent.com/4264240/208156155-7e5a9131-ae53-41c1-a260-076c610b7278.png)

**Comment by kogoromori** [comment]
#5678 
Same as me. And there are many more with the same issues.

**Comment by etherunit** [comment]
Related https://github.com/mysteriumnetwork/node/issues/5685

**Comment by apedance** [comment]
More info:

The both linux machines are running these params.

![image](https://user-images.githubusercontent.com/4264240/208439807-ca2961ac-73bc-4322-a414-8d0efac4e181.png)
![image](https://user-images.githubusercontent.com/4264240/208439919-7c2dd186-a1d0-43ef-accb-7fa10802e6d7.png)

DNS of linux /etc/resolf.conf
nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by DIKSA799** [comment]
Me too. I'm facing exactly thesame issue. Any solution?

**Comment by etherunit** [comment]
@apedance I can confirm that all of your nodes are online and works as expected. 
![Screen Shot 2023-01-09 at 09 36 38](https://user-images.githubusercontent.com/60128746/211259709-6526f210-3f37-4bcb-be0d-c6e3b5f86202.png)

@DIKSA799 What's your node identity?

**Comment by apedance** [comment]
Nodes are working now.
Shutting down nodes due to poor earnings and high fees.

Thanks for the support.
