### ISSUE TITLE
Linux VPS node connection failed, no earnings, Failed to send handshake initiation

### ISSUE THREAD

**Issue by simonc129** [mysteriumnetwork/node#5685]
**Describe the bug**
I am testing the myst node docker on two seperate VPS from two different vendors, one is Oracle Cloud. Both CentOS 7.  The two nodes i installed were seen online https://mystnodes.com/nodes for around 30 mins then ,shows "connection failed". There seem to be some interactions from the peers from the log but no earnings. 

**To Reproduce**
1. i install the docker on VPS (static public IP. CentOS7) using:
sudo docker run --cap-add NET_ADMIN --device /dev/net/tun:/dev/net/tun -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions  

2. registered and topped up. "Registration status: Registered"

3. run the following command
sysctl -w net.ipv4.ip_forward=1, 
iptables -P FORWARD ACCEPT
iptables -P INPUT ACCEPT

4. node seems running fine for the first 30 mins but later on mystnodes.com/nodes shows "connection failed"

5. run command: docker logs -f myst. Looks like there are some sessions with peers, but with many errors such as "Failed to send handshake initiation: no known endpoint for peer" (see attached picture). i am not familiar with how to submit full log details, apreciate it if anyone could kindly teach me how to do that if needed.

6. no earnings at all using: identities get <identity> command

**Expected behavior**
node showing in https://mystnodes.com/nodes with green online status and produce regular earnings

**Screenshots**
see attached. 

**Environment (please complete the following information):**
 - Node version: Version: 1.19.7
 - OS: CentOS Linux release 7.9.2009 (Core). Linux version 5.4.225
 - Docker (if applicable): 1.31.1
 - Your identity (if applicable): 0x0818c7f4fa292ae94fd844be3ba6bfbf54732e1d

![error1](https://user-images.githubusercontent.com/109418196/208331903-a88fb4d2-edfc-415d-9273-51eb4bcf36f0.png)

**Comment by etherunit** [comment]
Here is the problem:
`2022-12-19T09:33:31.485 ERR ../../../../source/core/connection/manager.go:260    > Connect failed, disconnecting error="could not send p2p session create request: peer error: cannot start session: : cannot get provider config for session 85ec810c-7ddd-4348-804f-859b7f697103: failed to setup NAT/firewall rules: error calling IPTables: \"/usr/sbin/iptables -I MYST 1 --destination 10.182.8.1 --protocol udp --dport 53 --jump REDIRECT --to-ports 11253 --table nat\": exit status 2 output: iptables v1.8.7 (legacy): unknown option \"--to-ports\"\nTry `iptables -h' or 'iptables --help' for more information.\n: exit status 2`

Firstly, can you please try to completely remove this container and install a fresh one with below command:

`docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`

**Comment by simonc129** [comment]
Thanks. i actually tried what you said multiples times but seems does not resovle the issue, node still shows "connectioned failed" and no earnings. i checked log, seems there is a TUN issue now
![error2](https://user-images.githubusercontent.com/109418196/208438922-f6a8b400-13de-48df-a675-3ee635c5cc32.png)

**Comment by simonc129** [comment]
@etherunit hi, may i follow up on the issue? the node seems to be running , but produces no earnings.  Thank you

**Comment by taheri79** [comment]
i have the same problem but the difference is im using ubuntu v18 and without docker

**Comment by etherunit** [comment]
@simonc129 

To fix f`ailed to create TUN device: CreateTUN(\"myst0\") failed; /dev/net/tun does not exist"`
In your Docker run command or docker-compose.yml file, use:

`--device /dev/net/tun:/dev/net/tun`

or

```
devices:
  - /dev/net/tun:/dev/net/tun
```

**Comment by christ0s** [comment]
i have the same problem but the difference is im using ubuntu 20.04 and without docker
any solutions ?

**Comment by simonc129** [comment]
> `--device /dev/net/tun:/dev/net/tun`

Thanks, but i already included "--device /dev/net/tun:/dev/net/tun" in my very first try as i mentioned in Step 1 to reproduce the issue in my initial post

**Comment by etherunit** [comment]
@christ0s Have you tried to install with apt commands?

**Native install**
On Debian/Ubuntu systems you can use Aptitude and execute:

```
sudo add-apt-repository ppa:mysteriumnetwork/node
sudo apt-get update
sudo apt install myst
```

**Comment by etherunit** [comment]
@simonc129 Please run it again with `--device /dev/net/tun:/dev/net/tun` and share the result. Thanks!

**Comment by simonc129** [comment]
> @simonc129 Please run it again with `--device /dev/net/tun:/dev/net/tun` and share the result. Thanks!

still the same issue, see the error snapshot attached.
![myst_err3](https://user-images.githubusercontent.com/109418196/209423182-cffe773e-4afc-421a-aaf4-3ae4c310b1f2.png)

**Comment by YuriyGavrilov** [comment]
go the same handshake issue on fresh linux installation ( node id:0xcc3ec458b58745155c9b5b23f64eb2c87c52b869)
ned -1, SSL error code 1, net_error -101
Dec 27 19:30:44 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193044.463783:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
Dec 27 19:30:44 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193044.465538:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
Dec 27 19:30:44 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193044.475730:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
Dec 27 19:32:00 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193200.968908:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
Dec 27 19:32:01 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193201.050502:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
Dec 27 19:32:01 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193201.225516:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
Dec 27 19:32:01 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193201.226323:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
Dec 27 19:32:01 odroid org.mate.panel.applet.BriskMenuFactory[2079]: [2079:2127:1227/193201.229811:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; retu

**Comment by etherunit** [comment]
@YuriyGavrilov @simonc129 Thanks for the info guys! I will test it on Linux VPS and get back to you shortly.

**Comment by etherunit** [comment]
Did a fresh node installation on Ubuntu 22.04 Linux VPS. Works as expected. Node identity: Please test 0x8d73494ba298d12e1850e4509fd270eb67dc01e6

```
DEBUG: [userspace-wg]2022/12/28 10:06:20 peer(VexS…EJUk) - Received handshake response
2022-12-28T10:07:10.442 DBG ../../../../source/eventbus/event_bus.go:101         > Published topic="consumer_ping_p2p" event={SessionID:bc292a96-f99a-4c99-ba83-624418549e67 Duration:33.618624ms}
2022-12-28T10:07:15.478 DBG ../../../../source/eventbus/event_bus.go:101         > Published topic="consumer_ping_p2p" event={SessionID:bc292a96-f99a-4c99-ba83-624418549e67 Duration:35.110775ms}
2022-12-28T10:07:16.011 DBG ../../../../source/core/connection/manager.go:941    > Received p2p keepalive ping with SessionID=bc292a96-f99a-4c99-ba83-624418549e67 from 0x8D73494Ba298d12e1850e4509Fd270eb67dc01E6
```

@YuriyGavrilov I can see that you are running several Linux-based nodes (same node releases) behind the residential networks, and that's the only node failing -> 0xcc3ec458b58745155c9b5b23f64eb2c87c52b869 (other nodes works fine).

The connection to this node completes with: `2022-12-28T10:13:58.203 ERR ../../../../source/tequilapi/endpoints/connection.go:216 > Failed to connect error="could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built"
`
Meaning: NAT traversal failed. Sometimes that happen if you're dialing peer with NAT incompatible with yours or if UDP traffic blocked. Try connecting from a machine which has ports exposed publicly or which has public IP.

Alternatively, if you want to alter the network configuration and experiment a bit, switch from hole_punching to uPnP in your router settings. Once router settings adjusted, navigate to your NodeUI panel and move upnp to top under Advanced Settings. 

<img width="1476" alt="Screen Shot 2022-12-28 at 10 19 24" src="https://user-images.githubusercontent.com/60128746/209781262-9e1481ac-46f5-49f3-a4d1-05d4b5efe76c.png">

**Comment by YuriyGavrilov** [comment]
many thanks @etherunit 
funny that those two my nodes are equal by hardware and software ... i use 4g lte modem directly connected to the devices

**Comment by YuriyGavrilov** [comment]
got first reward. but handshake appears sometime

**Comment by YuriyGavrilov** [comment]
tried self connection test and it is good. thanks @etherunit

**Comment by simonc129** [comment]
> @YuriyGavrilov @simonc129 Thanks for the info guys! I will test it on Linux VPS and get back to you shortly.

Thanks. i just relaunched the docker on my VPS with the command below and see how it goes.
sudo docker run --cap-add NET_ADMIN --device /dev/net/tun:/dev/net/tun -d -p 4449:4449 --network=host --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions

**Comment by simonc129** [comment]
> > @YuriyGavrilov @simonc129 Thanks for the info guys! I will test it on Linux VPS and get back to you shortly.
> 
> Thanks. i just relaunched the docker on my VPS with the command below and see how it goes. sudo docker run --cap-add NET_ADMIN --device /dev/net/tun:/dev/net/tun -d -p 4449:4449 --network=host --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions

still the same issue：“failed to send handshake initiation”

**Comment by etherunit** [comment]
@simonc129 Could you share with your latest node identity?

**Comment by simonc129** [comment]
> @simonc129 Could you share with your latest node identity?

sure. it's
0x0818c7f4fa292ae94fd844be3ba6bfbf54732e1d

**Comment by etherunit** [comment]
@simonc129 Thanks. By the way, any reasons you are running it inside container? Have you tried to install it natively using aptitu de commands?

**Comment by simonc129** [comment]
> @simonc129 Thanks. By the way, any reasons you are running it inside container? Have you tried to install it natively using aptitude commands?
> 
> ```
> sudo add-apt-repository ppa:mysteriumnetwork/node
> sudo apt-get update
> sudo apt install myst
> ```
> 
> If you still want to run it inside docker container, then please follow steps below:
> 
> 1. Run `docker run --cap-add NET_ADMIN -d -p 4448:4449 --name myst2 -v myst-data2:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`
> 2. Complete the onboarding process
> 3. Copy > paste output of `sudo iptables-save`
have not tried using aptitude commands. will try now

**Comment by etherunit** [comment]
Any updates @simonc129 ?

**Comment by simonc129** [comment]
> Any updates @simonc129 ?

sorry to get back to you late. i deleted the old docker container and run the command below exactly as you instructed. container has been running for two days. i checked the log, seems only a TUN related error :

2023-01-24T11:32:57.522 ERR ../../core/service/session_manager.go:187      > Session failed, disconnecting error="cannot get provider config for session 895d444d-7804-4f99-b7aa-2963f3bbf005: could not start new connection: could not start provider wg connection endpoint: could not configure device: failed to create TUN device: failed to create TUN device: CreateTUN(\"myst0\") failed; /dev/net/tun does not exist"

below is the output of sudo iptables-save.
<img width="552" alt="output" src="https://user-images.githubusercontent.com/109418196/214293496-ba1ceeee-64b6-4e51-8182-e44e6a20eb26.png">

**Comment by YuriyGavrilov** [comment]
@simonc129 may be it helps? https://docs.mysterium.network/troubleshooting/tun-device-errors

**Comment by simonc129** [comment]
> @simonc129 may be it helps? https://docs.mysterium.network/troubleshooting/tun-device-errors

thanks i noticed this post and incorporated it in my first attempt to run the docker (see "Reproduce"), but seems it is not the main cause of my problem

**Comment by etherunit** [comment]
@simonc129 I should say thank you for your patience. But in order for us to locate this problem better, I want to ask you to try it again.
Delete the docker container and launch a completely new one as instructed with `--device /dev/net/tun:/dev/net/tun` flag.

**Comment by simonc129** [comment]
> @simonc129 I should say thank you for your patience. But in order for us to locate this problem better, I want to ask you to try it again. Delete the docker container and launch a completely new one as instructed with `--device /dev/net/tun:/dev/net/tun` flag.
> 
> `docker run --cap-add NET_ADMIN -d -p 4447:4449 --name myst3 -v myst-data3:/var/lib/mysterium-node --device /dev/net/tun:/dev/net/tun --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`

have some MYST balance with my current identity when registered the identity, channel. could you guide me through how to transfer those balance to my wallet before deleting the docker? not quite sure what to fill in each of the parameters below

  withdraw <providerIdentity> <beneficiary> <toChain> [amount]

**Comment by etherunit** [comment]
It's not needed to transfer it anywhere in case you will use the same volumes. You can delete and remove the container but it will preserve keystore file on starting a new one.
