### ISSUE TITLE
auto reconnect to linuv vpn desktop app

### ISSUE THREAD

**Issue by soulistyces** [mysteriumnetwork/node#5688]
my problem is that myst auto-log off after some hours and i want to use it more tiime without been worried that the connection went off and now im stuck with unprotected network

**Describe the solution you'd like**
Please make it happen auto-reconnect to node and favorits enable on desktop app linux or win

**Describe alternatives you've considered**
i tried android x86 but keeps lagging its not an alternative

**Comment by max2322** [comment]
`   --auto-reconnect   ` 

Try using the key with myst command

**Comment by soulistyces** [comment]
> ` --auto-reconnect `
> 
> Try using the key with myst command

how do i import identitie in myst cli and connect to node cant find info about it
