### ISSUE TITLE
could not set DNS: exit status 1

### ISSUE THREAD

**Issue by 0ut0flin3** [mysteriumnetwork/node#5689]
whether I try to connect from the desktop application or try to connect via Tequila, I get this error every time (always):
 `Failed to connect: could not start new connection: failed to start connection endpoint: could not configure device: could not set DNS: exit status 1`
I'm using Linux Ubuntu 22.10

**Comment by etherunit** [comment]
Could not set DNS means that consumer failed to configure system DNS to use provider DNS.
From the message it’s hard to say why this happened, most likely some incorrect configuration on the host network / machine.
Please try to skip this DNS configuration step and keep using system DNS. Just add `dns=system` to the CLI connect command or select it in the app settings.

**Comment by 0ut0flin3** [comment]
> Could not set DNS means that consumer failed to configure system DNS to use provider DNS. From the message it’s hard to say why this happened, most likely some incorrect configuration on the host network / machine. Please try to skip this DNS configuration step and keep using system DNS. Just add `dns=system` to the CLI connect command or select it in the app settings.

Thank you for the reply. Yes, it works that way (by setting dns=system), but I can do this if I connect from the CLI. But I would be using Tequila Api to connect. It always worked, but not anymore (it works via cli instead). Is there any way to set the dns to "system" also using tequila api? Thanks a lot and happy new year

**Comment by etherunit** [comment]
CLI is using tequila API too, so it should work. Can we get a request you are sending? It could help us to find what is wrong there.

**Comment by 0ut0flin3** [comment]
> CLI is using tequila API too, so it should work. Can we get a request you are sending? It could help us to find what is wrong there.

I'm back, sure.
I send below the body and headers of the PUT request which I do, which has always worked, the error changes every now and then. Sometimes it gives the DNS error I was saying, sometimes it says that my identity is not allowed, (but it is registered, attached screens). Instead, everything works fine directly using everything from the client (myst cli) and setting dns=system

THIS IS THE PUT REQUEST i made to http://localhost:4050/connection:
`{'provider_id': '0x00someproposal', 'consumer_id': '0x4e42e93ce71beb489aca1e624940e7ab9a142cc6'}`
`{"Content-Type": "application/json"}`

THESE ARE THE ERRORS I RECEIVE (sometimes one sometimes another):
`Failed to connect: could not start new connection: failed to start connection endpoint: could not configure device: could not set DNS: exit status 1
`
`Failed to connect: could not send p2p session create request: peer error: cannot start session: : consumer identity is not allowed: 0x4e42e93ce71beb489aca1e624940e7ab9a142cc6`

![image](https://user-images.githubusercontent.com/114559605/211138988-1bc94488-3a1f-4f5a-9984-491ca38f04ca.png)

**Comment by 0ut0flin3** [comment]
Could the issue be that I'm on Ubuntu 22.10? Should I use 21.04 instead?

**Comment by 0ut0flin3** [comment]
> > CLI is using tequila API too, so it should work. Can we get a request you are sending? It could help us to find what is wrong there.
> 
> I'm back, sure. I send below the body and headers of the PUT request which I do, which has always worked, the error changes every now and then. Sometimes it gives the DNS error I was saying, sometimes it says that my identity is not allowed, (but it is registered, attached screens). Instead, everything works fine directly using everything from the client (myst cli) and setting dns=system
> 
> THIS IS THE PUT REQUEST i made to http://localhost:4050/connection: `{'provider_id': '0x00someproposal', 'consumer_id': '0x4e42e93ce71beb489aca1e624940e7ab9a142cc6'}` `{"Content-Type": "application/json"}`
> 
> THESE ARE THE ERRORS I RECEIVE (sometimes one sometimes another): `Failed to connect: could not start new connection: failed to start connection endpoint: could not configure device: could not set DNS: exit status 1 `
> 
> `Failed to connect: could not send p2p session create request: peer error: cannot start session: : consumer identity is not allowed: 0x4e42e93ce71beb489aca1e624940e7ab9a142cc6`
> 
> ![image](https://user-images.githubusercontent.com/114559605/211138988-1bc94488-3a1f-4f5a-9984-491ca38f04ca.png)

SOLVED, I simply added this to the request: `{"dns": "system", "kill_switch": True,"proxy_port": 0}`
I didn't know there were these options. now everything works fine.

**Comment by chompomonim** [comment]
@0ut0flin3 this way your DNS under VPN sessions will be set to your system default. Not very good for privacy. Much better would be to set provider's DNS.
