### ISSUE TITLE
using docker container in RouterOS 7.6

### ISSUE THREAD

**Issue by max2322** [mysteriumnetwork/node#5694]
using docker container in RouterOS 7.6
**Describe the bug**
Below is the error
[90m2022-12-30T15:17:08.406 [0m [1m [31mERR] [0m [0m [1m../../cmd/mysterium_node/mysterium_node.go:62] [0m [36m > [0m Failed to create command : [36merror= [0m [31m"$HOME is not defined" [0m

I think you didn't describe the $HOME variable correctly. Inside the container, it returns an empty value

**Comment by etherunit** [comment]
@max2322 Can you please specify your `docker run` command which you have used to start container?

**Comment by max2322** [comment]
> @max2322 Can you please specify your `docker run` command which you have used to start container?

`/container/add remote-image=mysteriumnetwork/myst interface=veth1 root-dir=disk1/mysterium envlist=mysterium logging=yes`

the container cannot be started with any parameters used.
At the same time, other docker containers are running.

**Comment by etherunit** [comment]
Can you try the following command: `docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`

**Comment by max2322** [comment]
> Can you try the following command: `docker run --cap-add NET_ADMIN -d -p 4449:4449 --name myst -v myst-data:/var/lib/mysterium-node --restart unless-stopped mysteriumnetwork/myst:latest service --agreed-terms-and-conditions`


Same error:
"$HOME is not defined

The situation is changing, I'm waiting for the key HOME="/"
Container to use but not transferable
