### ISSUE TITLE
Monitoring Failed

### ISSUE THREAD

**Issue by louisdchrf** [mysteriumnetwork/node#5695]
**Describe the bug**
Monitoring Failed

**Environment (please complete the following information):**
 - Node version: 1.19.7
 - OS: Raspbian
 - Desktop app version (if applicable): 2.3.2
 - Your identity (if applicable): 0xd40506ae6ecf160cacd8726862abec3448b5977b

Myst was running fine until a clean reboot of Raspbian (not power outage)

**Comment by etherunit** [comment]
@louisdchrf It's clear that after a clean reboot of Raspbian, it started to misreport your exact location, in other words,  you are reporting one `location/country/node_type`, but our internal monitoring agent detects another details during checks. Can you please check which location is being reported here: [ ip2location.com](https://www.ip2location.com/demo/78.56.89.253) ?

**Comment by louisdchrf** [comment]
Hi,
my IP is located in Paris, Ile de France, France
![image](https://user-images.githubusercontent.com/44228226/210525965-738d5784-ae70-4a07-8bb8-6990b6a03a6e.png)

**Comment by etherunit** [comment]
Thanks for confirming. I tried again to connect to your exit node to check the location, but DNS server is not working.
Because of it monitoring agent fails to check location via https://location.mysterium.network/api/v1/location and returns location failed.
Can you reconfigure it? My advice is to set up with Google or Cloudflare DNS for testing purposes.

**Comment by louisdchrf** [comment]
What do you mean be reconfigure it ? Reset my node configuration once again ?
The node is already using Google AND Cloudflare DNS and was working fine

**Comment by louisdchrf** [comment]
it show now "monitoring failed"

**Comment by etherunit** [comment]
What is under `cat /etc/resolv.conf`?

**Comment by louisdchrf** [comment]
`
administrateur@mining:~ $ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4
`

**Comment by louisdchrf** [comment]
and on the webui : 
![image](https://user-images.githubusercontent.com/44228226/211285580-f761809f-7b70-4eda-947c-ffbdcdf9efe4.png)

**Comment by louisdchrf** [comment]
Hi, do we have any update on the subject ? my Node still not working :/

**Comment by etherunit** [comment]
@louisdchrf The identity not loaded issue indicates that there is an issue with your network / internal local DNS cache. Anyway, it seems that you have set up a new identity from scratch using your RPi device.
The node is reported to be online and generating sessions successfully.
![Screen Shot 2023-01-16 at 12 41 49](https://user-images.githubusercontent.com/60128746/212659470-44f74289-5280-4c9f-9740-02b6cef420b9.png)
