### ISSUE TITLE
Monitoring Failed

### ISSUE THREAD

**Issue by PipBowl** [mysteriumnetwork/node#5696]
**Describe the bug**
When running node for days its fine, 100%/100% then every now and then it will go down where i have to contact support. They suggested me come here to tell you guys about it. Monitoring Failed, need a reboot,

node ID is.. 0x12aa8da5bb5eb961cbf9e63f7d780c342f9301ea

**To Reproduce**
1. run node

**Expected behavior**
Monitoring Failed

**Screenshots**

**Environment (please complete the following information):**
 - Node version: 1.19.7
 - OS: windows 8.1
 - Desktop app version (if applicable): 1.19.7?
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): 0x12aa8da5bb5eb961cbf9e63f7d780c342f9301ea
 - Payment (top-op) reference (if applicable): 0x3Ea6226943c55EC56d22672e1426c7960d2f5889

**Additional context**

**Comment by isaackielma** [comment]
Logs:

https://mystnodes.com/support/logs/2022-12-22-929e101a-c3c4-40a2-a5de-db5b493e0c94-mysterium-node.zip845115052

**Comment by etherunit** [comment]
@PipBowl I can confirm that your node is online and works as expected, therefore I'm closing this ticket.
![Screen Shot 2023-01-09 at 09 23 12](https://user-images.githubusercontent.com/60128746/211258055-b6a0988e-cdaf-479f-8a74-710564afaf53.png)
