### ISSUE TITLE
Error adding myst repositories

### ISSUE THREAD

**Issue by Adrigamer2950** [mysteriumnetwork/node#5705]
**Describe the bug**
When I was installing Myst on my raspberry pi, I got an error beacuse "the public key of the myst repositories is not available" (screenshot bellow)

**To Reproduce**
1. Add Myst repositories
2. Execute 'sudo apt update'

**Expected behavior**
Update of packages

**Screenshots**
![image](https://user-images.githubusercontent.com/58531641/211388869-f97c66e7-8e0d-43ae-b5a3-ead71995965a.png)

**Environment (please complete the following information):**
 - OS: rapsbian bullseye

**Comment by etherunit** [comment]
@Adrigamer2950 

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys `paste-pubkey-here`
sudo apt-get update
sudo apt install myst
```
