### ISSUE TITLE
I have a connection problem. He does not connect to the network. I have fast internet. Please help

### ISSUE THREAD

**Issue by sadekwardah** [mysteriumnetwork/node#5706]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1]
 - OS: [e.g. raspbian buster, debian 10]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**

**Comment by isaackielma** [comment]
Description
Platform: Android, Message: welcome The app is not working The network cannot be connected Please Help Thanks

Logs
https://mystnodes.com/support/logs/2023-01-11-be3caed6-f57d-4eb2-ad5b-2fd693b76e38-mysterium-node.zip691480210

**Comment by isaackielma** [comment]
Have you tried several different nodes? Is your internet speed good? Could you please perform a test here: http://speedtest.net/
