### ISSUE TITLE
As a node runner / Missing reward distribution, settlement for a session of a cost >= 5Myst

### ISSUE THREAD

**Issue by Nementon** [mysteriumnetwork/node#5708]
**Describe the bug**
As a node runner, an user have consumed a session for a duration of 4days at 07/01/2023 for a cost > 5Myst.
The session is available on the session history, but by looking on the transactions settlement:
- No settlement has been done at 07/01/2023 (it expected to be, since settlement is done every 5Myst)
- Looking on the dashboard, it is also not reported on the earning stats of the last 30days.

**To Reproduce**
Can not manually be reproduce, depends of the network behaviour

**Expected behavior**
When a user consume a session for 4days at a cost >= 5Myst, the reward to be distributed to the node runner and then trigger automatically a settle transaction to the registered node owner Polygon address's

**Screenshots**
- Session history and settlement transactions:
  ![Myst-History-Transactions-mismatch](https://user-images.githubusercontent.com/2373370/212002511-fa62716b-c3e0-4096-9d4c-d651d6e9a4de.png)

- Dashboard earning history in the last 30days: 
  ![image](https://user-images.githubusercontent.com/2373370/212001839-5fed6347-6b7f-4905-bb95-564d39cba5a3.png)

**Environment (please complete the following information):**
 - Node version: 1.19.7
 - OS: Raspbian GNU/Linux 10 (buster)
  - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A
 - Your identity (if applicable): 0x0f78fbc4dc68734b1fc13fdc444574420cb00326
 - Payment (top-op) reference (if applicable): N/A

**Additional context**
- The session id: 213db400
- The node id: 0x0f78fbc4dc68734b1fc13fdc444574420cb00326

**Comment by cirial** [comment]
I think the MYST team is robbing node runners blind with their inaccurate reporting.  The reporting is either flat out wrong, or just inaccurate and there has been been no real comment from the team.

**Comment by liamgibbins** [comment]
I think they pay when the session ends (not clear on that), the issue is if they have enough MYST on the app by the time the session ends.

I dont think there robbing us blind, I just think the system needs some time spending on it to get the correct stats in, this is also reflected with the website leaderboards and Mynodes displaying different vaues or values that dont add up to the node dashboard.

Maybe if they dedicated a couple of days to it, it might stop people whining or question it.

Personally I would like a quality of life feature that displays average data, sessions, Myst per month but that is something you could do yourself with the API.

**Comment by liamgibbins** [comment]
Same here, myst earned does not tally up

![Screenshot_20230119_120530_Samsung Internet](https://user-images.githubusercontent.com/16313132/213439133-27556937-844d-4396-abd2-52c1c2fca9fe.jpg)

**Comment by etherunit** [comment]
@Nementon Apologies for a delayed reply. Please note that we have seen your issue and currently investigating it.

**Comment by n10ty** [comment]
@Nementon There was a settlement at Jan 7th ([link](https://polygonscan.com/tx/0x8ae2ce08d22890a0a42125f8d35d0580e6b601121a729eb4f0195b7029a8eed6).
But in some way your node didn't receive an update about this settlement (might be some network issue or node restart, for example) so it doesn't display in your transaction list.

**Comment by Nementon** [comment]
@etherunit @n10ty  allright, thanks for your times and investigation, I'm closing the issue since it wasn't bug after all
