### ISSUE TITLE
bubble errors from ./bin/check

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#571]
at the moment when running the ./bin/check the following can happen:

![image](https://user-images.githubusercontent.com/18392269/49001807-6d72d300-f166-11e8-8d5e-d49454acf548.png)

We'd probably need to fail here as I might have had changes that break the .json in the first place.

**Comment by tadovas** [comment]
A simple -e at the beginning of of swagger_generate and check_swagger will do the trick.
