### ISSUE TITLE
Wrong earning my dashboard an my node 

### ISSUE THREAD

**Issue by lanamaulanaaaa** [mysteriumnetwork/node#5717]
## My dashboard Node
![image](https://user-images.githubusercontent.com/121058807/213019990-93a59e7d-8cd4-437e-b392-60ad18984901.png)

## My dashboard account
![image](https://user-images.githubusercontent.com/121058807/213020221-1ce57441-f968-4a4e-9079-d45e7b3f7fc5.png)

- lots of mistakes in earnings , anyone can resolved this ?

**Comment by etherunit** [comment]
@lanamaulanaaaa Thanks for reporting! Our team is aware of this problem and working on it.

**Comment by etherunit** [comment]
I'm following up on this one. Team did some important improvements that should improve in reflecting data and earnings. Can you please check and verify that @lanamaulanaaaa
