### ISSUE TITLE
Error when linking node to API

### ISSUE THREAD

**Issue by Liten90** [mysteriumnetwork/node#5718]
**Describe the bug**

_When trying to register a node in the API. I get an error in the node interface._

**Screenshots**
![image](https://user-images.githubusercontent.com/32055609/213815610-83806dac-87aa-4c57-97ed-f4dc3b0c930b.png)

 - Node version: 1.19.8
 - OS: Win 10x64 Opera 94.0.4606.65
 - Desktop app version (if applicable): desktop node
 - Your identity (if applicable): 0xea2d206c1f8acee7a61b79f2873f41ce56f19f6a
 

**Additional context**
Isaac asked to leave a request here, because the problem is several months old.
old log https://mystnodes.com/support/logs/2022-12-01-7cb48e5f-755d-49ca-945b-d2526a75d53f-mysterium-node.zip1562504942
![Снимок](https://user-images.githubusercontent.com/32055609/213816402-c249d1b9-6100-44cb-b2cd-80982ad1040a.PNG)

**Comment by etherunit** [comment]
@Liten90 Thanks for reporting! Could you add some screenshots from DevConsole's Tab? In particular, we need more details on what's being displayed on request under Network/Console tabs.

**Comment by etherunit** [comment]
Important line from logs on registering node to MMN: `2022-12-02T00:34:07.980 ERR /source/tequilapi/endpoints/mmn.go:113    > MMN registration error: {"errorCode":"invalidSignature","message":"Invalid request signature"}`

**Comment by Liten90** [comment]
> @Liten90 Thanks for reporting! Could you add some screenshots from DevConsole's Tab? In particular, we need more details on what's being displayed on request under Network/Console tabs.

Where should you watch it?
![image](https://user-images.githubusercontent.com/32055609/214118354-9f5857a6-c1ef-4a48-b6a4-1e2e48bbff45.png)

**Comment by etherunit** [comment]
To open Developer tools, go to your Opera browser and click the Developer on top menu bar and then Developer tools. 
Record Console and Network tab during this error message "Failer to register to mystnodes" and share the screenshot here if possible.
Thanks!

**Comment by Liten90** [comment]
![image](https://user-images.githubusercontent.com/32055609/216159780-9526d335-ab36-4aec-9c68-8fa13a9476de.png)

**Comment by MykolasMaciekus** [comment]
@Liten90 
Could you please provide us with screenshots with payload and response for this request? You can find them in marked tabs:
![216159780-9526d335-ab36-4aec-9c68-8fa13a9476de](https://user-images.githubusercontent.com/85465685/216268690-7b6eb59d-4089-4125-9b9d-796923ef64c2.png)

**Comment by Liten90** [comment]
![image](https://user-images.githubusercontent.com/32055609/216416917-806fffb4-7091-4507-96e4-841d96b2e5a4.png)
![image](https://user-images.githubusercontent.com/32055609/216417062-474f63fd-10b5-4bbf-a5e1-7e6d608ffa4e.png)

**Comment by etherunit** [comment]
Hi @Liten90, apologies for a delayed reply. After some review, we suspect that there is an issue with decrypting and verifying user identity signature. In order for us to try reproduce and potentially resolve this, we would need your identity backup files. 
Could you please create a backup of your node and send .mysterium folder including a keystore file? That would be a super helpful component to further investigate this issue.

**Comment by Liten90** [comment]
I sent it to you via node support.

**Comment by etherunit** [comment]
What was the email associated with your report?

**Comment by Liten90** [comment]
tatarenko90@hotmail.com

**Comment by etherunit** [comment]
@MykolasMaciekus https://wetransfer.com/downloads/1388411e69867f267de01548c3ff493e20230209182019/2185bc7b6d0493fe159bbdc24a18051220230209182034/707e1b?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

**Comment by etherunit** [comment]
@Liten90 First of all, thank you for your patience in submitting your .mysterium folder with its keystore. Team has reviewed and did some tests on your identity, however, in all cases (running the node from source and from docker) we could successfully claim the node, so we could not reproduce the issue. Right now the node identity is claimed to your account on [mystnodes.com](http://mystnodes.com/). 
We are keeping this ticket open for some period of time as a matter for future references.

**Comment by Liten90** [comment]
thx )
________________________________
От: etherunit ***@***.***>
Отправлено: 14 февраля 2023 г. 10:24
Кому: mysteriumnetwork/node ***@***.***>
Копия: Liten90 ***@***.***>; Mention ***@***.***>
Тема: Re: [mysteriumnetwork/node] Error when linking node to API (Issue #5718)


@Liten90<https://github.com/Liten90> First of all, thank you for your patience in submitting your .mysterium folder with its keystore. Team has reviewed and did some tests on your identity, however, in all cases (running the node from source and from docker) we could successfully claim the node, so we could not reproduce the issue. Right now the node identity is claimed to your account on mystnodes.com<http://mystnodes.com/>.
We are keeping this ticket open for some period of time as a matter for future references.
