### ISSUE TITLE
Dashboard Earnings Error

### ISSUE THREAD

**Issue by merchable** [mysteriumnetwork/node#5719]
**Describe the bug**
The dashboard now reports network total earnings, instead of node total earnings

**To Reproduce**
Open Mysterium Node UI

**Expected behavior**
The dashboard show report on node total earnings
**Screenshots**

![dashboard](https://user-images.githubusercontent.com/22080998/213864476-195c8e5d-d42c-48d8-8128-2e8875367898.jpg)

**Environment (please complete the following information):**
 - Node version: 1.19.8-alpine
 - OS: Windows
 - Docker (if applicable): 4.16

**Comment by etherunit** [comment]
@merchable I have checked locally and with several node runners and it looks like it displays the right figures. Is that still a case on your end?

**Comment by merchable** [comment]
That's not the case on my side, it is still shows total network earnings. My current node has been up just over a week, there is no way it has earned 59026 myst in public alone.

**Comment by etherunit** [comment]
@merchable Sorry for some misleading info. 
Total network earnings is intended feature showing which service is generating most income. While service earnings is showing the amount if MYST earned by you.
