### ISSUE TITLE
[linux] Under "My Nodes" the OS types and icons for Debian-based nodes are not displayed consistently

### ISSUE THREAD

**Issue by guus461** [mysteriumnetwork/node#5720]
**Describe the bug**
After running an update my Raspberry Pi OS node is displayed in the My Nodes dashboard as "Raspberry Pi" with a nice icon, as it should. 
However, after a while (within an hour or so) the OS type and logo fall back to generic Linux and a Tux icon.

**To Reproduce**
1. Check the OS type of your Raspberry Pi node before running an update
2. Run the update
4. Go back to My Nodes online, and you'll see the OS type and icon for your Raspberry Pi are perfect for a while 
5. But after a while (maybe an hour or so), the OS type falls back to generic Linux and Tux icon

**Expected behavior**
I expect the Raspberry PI OS type to stick

**Screenshots**
Correct (right after update)
![image](https://user-images.githubusercontent.com/14141936/213927781-1c59384b-5676-4fd3-accf-db5a1a9a4218.png)

Incorrect (moments after update)
![image](https://user-images.githubusercontent.com/14141936/213927746-cc4fbe6c-ba2a-413c-9533-64215ea220f9.png)

**Environment**
 - Node version: 1.19.8
 - OS: Raspberry Pi OS Bullseye on a Raspberry Pi 3 B+
 - Kernel release 5.15.84-v7+
 - Kernel date Jan 5th 2023

**Comment by etherunit** [comment]
@guus461 Could you try to restart service and see if that makes any changes?
SSH into your RaspberryPi and run: `sudo systemctl restart mysterium-node.service`

**Comment by guus461** [comment]
@etherunit, thanks for the quick reply.
Restarting the node as per your instruction puts the OS type and icon indeed back to Raspberry Pi.
I will leave it for a while and check later if it persists.

**Comment by guus461** [comment]
45 minutes later, still going strong...

**Comment by etherunit** [comment]
Interesting, I believe that was some sort of glitch. Hopefully, that will display the right detail moving on.

**Comment by guus461** [comment]
I did the same for my Debian nodes, who were in the same way marked as generic "Linux" but after the restart now are "Debian/GNU Linux  11 (bullseye)", meaning the problem was/is not only related to Raspberry Pi OS.
I will keep an eye on the OS types in the coming 24 hours. Thanks for your help so far.

**Comment by guus461** [comment]
Checking My Nodes atwo hours after the restart the OS types and icons have fallen back to generic Linux and Tux.

![image](https://user-images.githubusercontent.com/14141936/214043125-109bbb33-6428-4c28-9b1b-b52c23a5121c.png)

All my types (Raspberry Pi, Ubuntu, and 2x Debian, are now back to generic linux as OS, 

How shall we further investigate?

**Comment by etherunit** [comment]
Could you provide us with your node identity?

**Comment by guus461** [comment]
Providing two of four:
0xeb688fa4f0c24fad41308ef242336b0f6341021e - Raspberri Pi
0x3c4fd61d7d2acd0022e612a0320fbd8e57dfd589 - Debian 11

**Comment by etherunit** [comment]
Thanks for providing it @guus461!
Team will check why it's falling back to LinuxOS after a while and get back to you with an update.

**Comment by mdomasevicius** [comment]
It seems that the node itself reports OS as "linux" so it's not the issue with msytnodes.com

**Comment by ZygintasBudrys** [comment]
Ask Dmitri if this has any relevance

**Comment by guus461** [comment]
The issue still persists
