### ISSUE TITLE
Quality indicators in NodeUI, My Nodes, and android app do not match

### ISSUE THREAD

**Issue by guus461** [mysteriumnetwork/node#5723]
**Describe the bug**
For two out of three of my nodes:

in Node UI:
![image](https://user-images.githubusercontent.com/14141936/215108331-74f1615a-3bb6-494a-bf75-1f0c35929b23.png)

in My Nodes:
![image](https://user-images.githubusercontent.com/14141936/215108886-b9f68520-ac27-4322-ad7d-464db1b9a840.png)

**Expected behavior**
These two nodes are are pretty much running 24/7 on a 100Mbit fiber, so I'd expect the highest quality indicator under My Nodes and -more importantly- toward the users/clients.

To add to this, in the Android app these two nodes are listed with only one bar:

![image](https://user-images.githubusercontent.com/14141936/215113705-4ab4fd71-fd81-49db-93ab-f007cd2099d0.png)

And to leave my completely puzzled, the only 'three bar' node I have (according to My Nodes) is actually given only two bars in the Android App.

There seem to be three versions of the truth..

**Environment (please complete the following information):**
 - Node version: 1.19.8
 - Node UI version: 2.4.0
 - Android app version: 2.1.4
 - OS: Raspberry Pi OS 11  and  Debian 11 (x2)
 - Node ids: 0xeb688fa4f0c24fad41308ef242336b0f6341021e (Rasp Pi)  and  0x71f1e1f300e8a72e4ec2535e3a48e18dedc3d57d  and 0x3c4fd61d7d2acd0022e612a0320fbd8e57dfd589

**Comment by guus461** [comment]
P.S. Love your product though!

**Comment by etherunit** [comment]
@guus461 Please note that all of them have it's own source of quality at this stage. Mystnodes.com and NodeUI are showing the aggregated quality, while dVPN app shows only for the public service and for consumer location only. That's how it's implemented right now.
