### ISSUE TITLE
Taking out funds from old hermes

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5729]
Service provider holds funds in his old beneficiary and Hermes which was switched off. 
Balance: 85.694361960981880122 MYST
To take funds out of there we should call the `requestExit` and `finalizeExit` functions on the channel contract using some JS code or directly on PolygonScan: https://polygonscan.com/address/0x290a6b44e8FD003691496E26790c7DFdB1341795#writeContract
Bur for that, we need to write a script to run in provider's data folder which creates a signature using his keystore.

**Comment by adinetech** [comment]
Provider `0xac542929ab6e0be26b70d4de1c775c60bd2b8c19` faces the same problem, right now the MYST is in his Channel Identity of Hermes v1.

**Comment by etherunit** [comment]
Provider 0x36530ab55fd9c4c87308e37daa754fdcad31d679

**Comment by etherunit** [comment]
0x21b172e3b8769c2f1ee995238caa7b28e0f8254c

**Comment by etherunit** [comment]
Users confirmed they have successfully retrieved tokens from their contacts. Closing this case.
