### ISSUE TITLE
Next auto settlement displays as NaN MYST - Mobile/Android Provider

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5730]
**Describe the bug**
The Next auto settlement displays as NaN MYST in the Node UI of the Android Provider.

**To Reproduce**
1. Open Node UI
2. Look at the Next auto settlement and the balance shown as NaN.

**Expected behavior**
The Node UI should show/display the Next auto settlement as it does on Linux/macOS/Windows provider builds.

**Screenshots**
<img width="250" alt="image" src="https://user-images.githubusercontent.com/68943180/216348295-4cd0a0d9-5708-414d-bcf3-31a1ea742f1d.png">

**Environment (please complete the following information):**
 - Node version: source.dev-build
 - Node UI version: 2.4.0
 - OS: Android 12
 - Your identity: 0x21a40c7d29a85dd7ecf590dde6653e8a2bb7c371

**Comment by etherunit** [comment]
Same NaN is displayed under Settings > Traffic > Limit bandwidth to "NaN"

**Comment by ZygintasBudrys** [comment]
Needs to be handled in FE

**Comment by etherunit** [comment]
Seems to be fixed @ZygintasBudrys ?
