### ISSUE TITLE
Failed to lookup proposal:no providers avaliable for the filter

### ISSUE THREAD

**Issue by Schwarzeisc00l** [mysteriumnetwork/node#5744]
I bought a vps that has Ubuntu 20.04 inside. I set up the node as a Datacenter. The provider told me that they didn't have any limitations by default. SO im confused. I can post any logs you want me to post but im kinda new so you would have to tell me how.

Thanks for help

**Comment by etherunit** [comment]
@Schwarzeisc00l Usually, once after your node is successfully onboarded, it takes up to a few hours for your service proposals to be listed in discovery. Please post your node identity so we can check it.

**Comment by etherunit** [comment]
@Schwarzeisc00l In case you will have any further questions, feel free to reopen this issue. For now, I will close it.
