### ISSUE TITLE
Nodeui & Mystnodes displaying divergent quality score metrics

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5751]
**Describe the bug**
Connection quality in the node dashboard shows 3 out of 3 while it shows 1 out of 3 on the Myst Nodes page.

**Expected behavior**
Quality scores should match. Both node ui and mystnodes should show same result.

**Screenshots**
<img width="1029" alt="Screenshot 2023-03-08 at 04 57 35" src="https://user-images.githubusercontent.com/84313603/223655996-a180fdbf-021b-465b-a6ac-dfc1c8ff1391.png">
<img width="1269" alt="Screenshot 2023-03-08 at 04 57 44" src="https://user-images.githubusercontent.com/84313603/223656007-5db26536-845e-4e27-a9ef-d9b526c0f0e1.png">

**Additional context**
Logs:

https://mystnodes.com/support/logs/2023-02-24-5fd4b485-9a33-4578-90b0-ca9e32295158-mysterium-node.zip1156321957

**Comment by ZygintasBudrys** [comment]
Requires discussion with @soffokl on the source of metrics

**Comment by DeVisdude** [comment]
I am the original reporter/user of this issue.
Are there any updates on this?
Can I help by supplying more info?

**Comment by etherunit** [comment]
@DeVisdude 
We have done some improvements there. Can you please check it on your end?

**Comment by DeVisdude** [comment]
@etherunit
Thanks for the update.
Yes it looks like both show 1 out of 3 now so that one is solved.

Tbh I dont know why it is 1 out of 3 instead of 3 out of 3, as my node is always online directly connected to the router of my 1gbit fiber connection. But ofcourse thats another matter.
Is it possible this is made more clear WHAT exactly makes my connection quality poor? So I can act on it. 
Should I open another "issue" for this?

**Comment by DeVisdude** [comment]
@etherunit any feedback please?

**Comment by DeVisdude** [comment]
@etherunit any response would be appreciated....

**Comment by shawaj** [comment]
Not providing the exact error, but it has a little tooltip that tells you something about it:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/3359418/234075172-e7792edd-bcb9-4a3a-9faf-e1c635ed99c9.png">

**Comment by DeVisdude** [comment]
Yes I noticed that. 
However my suggestion is to inform the node owner why exactly the quality is (not) OK, so the node owner can act on it. 

Like: red flag on latency, or uptime is lower than 24 hours, or bandwidth score = XX

makes sense, right?

**Comment by mdomasevicius** [comment]
needs alignment (mmn vs nodeui data fetching strategies)
