### ISSUE TITLE
"Failed to register node to mystnodes.com"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5753]
**Describe the bug**

API key, is not accepted, error showing up:

<img width="632" alt="Screenshot 2023-03-15 at 12 43 15" src="https://user-images.githubusercontent.com/84313603/225363724-978e2932-90ba-4bec-acf3-205863a378fd.png">

Logs:

https://mystnodes.com/support/logs/2023-03-15-9242bf95-1d85-4e4b-b5ce-3ce7e5981111-mysterium-node.zip1107893761

**To Reproduce**
1. Go to 'claim your node'
2. Click on 'nodeui'
3. Scroll down to 'mystnodes.com integration'
4. Insert API key and confirm
5. See error

**Expected behavior**
Node should be claimed successfully following the previous steps.

**Comment by GustavoPAlmeida** [comment]
Same Here.
Docker/Unraid

**Comment by mdomasevicius** [comment]
@GustavoPAlmeida please try again

**Comment by GustavoPAlmeida** [comment]
Working! Thanks!

**Comment by moonpawn** [comment]
I have this bug too
