### ISSUE TITLE
'My Nodes' page not showing the Last Seen and Quality for nodes

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5754]
**Describe the bug**
"'My Nodes' page doesn't show the Last Seen and Quality for any of my nodes. The values appear in the discovery URL anyway."

Logs:

https://mystnodes.com/support/logs/2023-03-10-01026641-b13f-4848-afe0-097a631b5701-mysterium-node.zip2501442045

**Screenshots**
<img width="1050" alt="Screenshot 2023-03-15 at 13 53 03" src="https://user-images.githubusercontent.com/84313603/225383408-cb5d34cf-9a5d-4ba7-a0e8-d21eefae21a1.png">

**Comment by etherunit** [comment]
As discussed with team, we do not show Last seen number for online nodes. It start showing the difference of last seen online and offline time after some short period of time. Regarding quality metric - the fix should be released this week as per Mantas comment.
