### ISSUE TITLE
My node is connected but there is no traffic in it

### ISSUE THREAD

**Issue by Cannonbow** [mysteriumnetwork/node#5756]
**Describe the bug**
So I want to report a problem, the issue is that I had a problem with monitoring failed, i created a new node and registered it, I still had the same problem and with help of adine i could change the DNS from 127.0.0.53 to 1.1.1.1 and changed from parameters of network the DNS to 1.1.1.1 8.8.8.8. My node is online, and it appears in mysterium VPN and you can connect to the node, but there is no traffic in it. i don't know what it is blocking my node to send traffic to the client.

**Environment (please complete the following information):**
 - Node version: 1.19.21
 - OS: Ubuntu 22.04 LTS
 - Your identity (if applicable): 0xb67a351a25427a98e1c8b71cb40c068b62fb90e1

**Additional context**
i did a test from mystnodes and i got traffic 132 MB from it, i was happy like i said it was working finally but after that people who started to log on my node, they connected successfully but there is no traffic. i would send logs if needed but there is expiration date so i send the log if needed.

**Comment by etherunit** [comment]
@Cannonbow Thanks for a detailed description. Could you please attached your node log so we can investigate it further?

**Comment by adinetech** [comment]
Logs -> https://files.adinetech.com/logs/Nasr_node20_03.log

I attempted to use every DNS setting on Mysterium VPN (Automatic, Cloudflare, System, and Provider). I've been able to connect to his node but nothing seems to work.

**Comment by etherunit** [comment]
@adinetech @Cannonbow 
I can see there were several successful connections a few days ago, have you changed something in node settings? 

![Screen Shot 2023-03-23 at 09 07 59](https://user-images.githubusercontent.com/60128746/227128971-2e647734-9e7b-4b7e-bea0-d0a5ee07d06a.png)

**Comment by etherunit** [comment]
By the way, it's doesn't look as DNS issue anymore. Once connected, you cannot even ping 8.8.8.8, looks like in general connection is broken, maybe `forwarding` is disabled or other issues with `iptables` configuration on the host machine.

**Comment by Cannonbow** [comment]
> @adinetech @Cannonbow I can see there were several successful connections a few days ago, have you changed something in node settings?
> 
> ![Screen Shot 2023-03-23 at 09 07 59](https://user-images.githubusercontent.com/60128746/227128971-2e647734-9e7b-4b7e-bea0-d0a5ee07d06a.png)

yes i changed dns it was 8.8.8.8 to 1.1.1.1 and the node worked for me for connections only but when people connect, they receive no traffic

**Comment by Cannonbow** [comment]
> T PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 65494
> ;; QUESTION SECTION:
> ;google.com.			IN	A
> 
> ;; ANSWER SECTION:

for this part i wrote cat /proc/sys/net/ipv4/ip_forward and it gives me 1 so here till now it is good, i already wrote:
iptables -P FORWARD ACCEPT
iptables -P INPUT ACCEPT
but it didnt fix my issues, as i said people can connect to the node successfully but they receive no traffic, for port forwarding it is already enabled with 10000:60000 in WAN and 10000:60000 in LAN so i don't know if it is port forwarding issue or no. The connection issue was with DNS issue and it was fixed, but the problem now is the traffic and i dont know how to fix it.

**Comment by etherunit** [comment]
Would be nice to get output of the `sudo iptables-save`, there might be other rules that blocks the traffic.

**Comment by Cannonbow** [comment]
> Would be nice to get output of the `sudo iptables-save`, there might be other rules that blocks the traffic.

yes for sure here is the pdf format of the output of sudo iptables-save 
[IPTABLES OUTPUT.pdf](https://github.com/mysteriumnetwork/node/files/11062434/IPTABLES.OUTPUT.pdf)

**Comment by etherunit** [comment]
Last line of warning indicates that there are some additional rules listed.
`sudo iptables-legacy-save` might show them.

**Comment by Cannonbow** [comment]
[CamScanner 03-27-2023 14.20.pdf](https://github.com/mysteriumnetwork/node/files/11079718/CamScanner.03-27-2023.14.20.pdf)

here it is

**Comment by Cannonbow** [comment]
@etherunit hi again ether i just wanna tell you that my node is started to work again i dont know what is happening? but when adine tried my node the download speed is great but not the upload speed i have internet speed of 100 mbps of download and 50 mbps with upload.  and before upload speed used to work for me here is my node to check again 0xb67a351a25427a98e1c8b71cb40c068b62fb90e1

**Comment by adinetech** [comment]
It's important to keep in mind that bandwidth can be affected by a range of factors, including distance. Additionally, some ISPs may limit international bandwidth to reduce costs (although peering is typically free, the availability of the bandwidth could be lower). To confirm this, It's recommended to have someone else test your node.

**Comment by adinetech** [comment]
Thank you for reaching out to me on Discord and letting me know that you fixed the Ethernet cable. I ran another test and the results were positive. 
Here's the Speedtest result: https://www.speedtest.net/result/14541653593
