### ISSUE TITLE
Node Monitoring Issue

### ISSUE THREAD

**Issue by lee-aaron** [mysteriumnetwork/node#5757]
**Describe the bug**
I'm seeing some I/O bugs after updating from 1.19.5 to 1.19.21 and I'm also having monitoring issues after sending MYST to the address.

**To Reproduce**
1. Upgrade from 1.19.5 to 1.19.21

**Expected behavior**
I don't expect to not have an error after upgrading.

**Screenshots**
```
Mar 19 19:45:55 raspberrypi myst[7713]: 2023-03-19T19:45:55.014 INF services/wireguard/service/stats_publisher.go:65 > Stopped publishing statistics for session 0b415bb3-7907-4724-a49b-a61c03820375
Mar 19 19:45:55 raspberrypi sudo[19389]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev myst0 root
Mar 19 19:45:55 raspberrypi sudo[19389]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 19:45:55 raspberrypi myst[7713]: 2023-03-19T19:45:55.048 ??? usr/lib/go-1.18/src/io/io.go:428 > Error: Cannot delete qdisc with handle of zero.
Mar 19 19:45:55 raspberrypi sudo[19389]: pam_unix(sudo:session): session closed for user root
Mar 19 19:45:55 raspberrypi sudo[19391]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev myst0 ingress
Mar 19 19:45:55 raspberrypi sudo[19391]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 19:45:55 raspberrypi myst[7713]: 2023-03-19T19:45:55.089 ??? usr/lib/go-1.18/src/io/io.go:428 > Error: Cannot find specified qdisc on specified device.
Mar 19 19:45:55 raspberrypi sudo[19391]: pam_unix(sudo:session): session closed for user root
Mar 19 19:45:55 raspberrypi sudo[19393]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev ifb0 root
Mar 19 19:45:55 raspberrypi sudo[19393]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 19:45:55 raspberrypi myst[7713]: 2023-03-19T19:45:55.128 ??? usr/lib/go-1.18/src/io/io.go:428 > Cannot find device "ifb0"
Mar 19 19:45:55 raspberrypi sudo[19393]: pam_unix(sudo:session): session closed for user root
Mar 19 19:45:55 raspberrypi sudo[19397]: mysterium-node : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/sbin/tc qdisc del dev ifb0 ingress
Mar 19 19:45:55 raspberrypi sudo[19397]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 19 19:45:55 raspberrypi myst[7713]: 2023-03-19T19:45:55.165 ??? usr/lib/go-1.18/src/io/io.go:428 > Cannot find device "ifb0"
Mar 19 19:45:55 raspberrypi sudo[19397]: pam_unix(sudo:session): session closed for user root
```

**Environment (please complete the following information):**
 - Node version: [e.g. 0.19.1] 1.19.21
 - OS: [e.g. raspbian buster, debian 10] raspbian buster
 - Desktop app version (if applicable): [e.g. 2.0.4] 2.4.0
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. 0xDb34233cf11Ac64a449144Ec8D8251268a4b168A] 0x69b2678ecb352b0cbf608c8fcf7989b6d0580465
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
I sent 0.2 MYST to the channel address listed in `myst account info` and it shows registered as well as the balance. I didn't see an amount to send to register the node when upgrading. I don't know what a payment reference is but I might have one if you know what that's supposed to look like (I don't think it's the tx hash for sending the MYST).

**Comment by etherunit** [comment]
From the first glance, it looks like there is some issue with DNS configuration on your end. It was able to create p2p channel but actual browsing was not working. 

When digging hostnames, it returns  

```
->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 52202
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
**_;; WARNING: recursion requested but not available_**
```

Can you please try to adjust your DNS setting to 8.8.8.8 or 1.1.1.1?

**Comment by lee-aaron** [comment]
I was running pihole but I uninstalled it, set the DNS, and rebooted the pi. I think it works now. Feel free to close if things look ok on your end.
