### ISSUE TITLE
Quality metrics issue

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5759]
**Describe the bug**

node id: 0xa945c61ca06718a485c51cf27d363c0887a08bd0

Issue with the "Quality" metrics bar between the displayed quality in the respective node UI and in the overall "My Nodes" view on the MYST website. This bug report is from a node that shows 3 bars / full quality in the Node UI but only gets a 2 out of 3 in the main Dashbaord on the website. 

I run dozes of nodes, and this one is one of a new batch set up around Feb23. It seems like all my nodes that have been set up this year have the same issue. They all started and were initially set up with version 1.19.20 or 1.19.21 (maybe this is a relevant hint). currently there are 54 nodes in my list with the same issue. All of them have been set up this year and almost all of them show three bars in the respective node UI but show zero / all bars geyed out in the main dashboard.

Logs:

https://mystnodes.com/support/logs/2023-03-17-52b02721-5ed9-42f0-bf02-446ca73f081c-mysterium-node.zip3370352907

**Screenshots**
<img width="1242" alt="Screenshot 2023-03-24 at 07 32 26" src="https://user-images.githubusercontent.com/84313603/227498545-d60eebb2-6269-4a0f-a5cb-7ef273a8852c.png">
<img width="1265" alt="Screenshot 2023-03-24 at 07 32 38" src="https://user-images.githubusercontent.com/84313603/227498554-f8056fe0-a340-4068-9260-663dd2639a59.png">

**Environment (please complete the following information):**
this particular vps node currently only runs MYST. I usually pair them with Presearch and/or STREAMR/DATA once a client wants to spin up one of these nodes (or I myself).

The vps envirpnment for these smallest units is always Ubuntu 20.4 (updates running once a week via ansible), 768MB Memory, 1 CPU, 10GB SSD. Memory gets a double with another 768MB Cache from the drive. VM swappiness is 10, cache pressure is set to 50. UFW is usually set to default MYST port settings, except if I need also other ports for projects like FIRO, ETHO Protocol, RTM etc. I never shrink the port space for MYST, though. All installs are always native installs using the MYST Repo, no docker installs! Myst also gets its own user and home directory - any project is separated on each machine, so I can quickly move things around in case a server gets too full.

But the issue appears on MYST nodes like the above, where MYST is the only running app, and also paired on other machines that already rune a PRE or DATA node. Also the bigger vps machines with 4, or 6++ RAM and multiple cpu have the same issues, so it doesn´t appear to be a HW problem in terms of capacity. Providers are usually always Netcup or Racknerd. Some are onecloud, so there´s not one particular provider that could block anything that might cause the issues.

**Comment by etherunit** [comment]
@ZygintasBudrys Any updates on this one?

**Comment by mdomasevicius** [comment]
I need identity

**Comment by etherunit** [comment]
@isaackielma Could you add node identity into the issue? Thanks

**Comment by isaackielma** [comment]
@mdomasevicius node id: 0xa945c61ca06718a485c51cf27d363c0887a08bd0
