### ISSUE TITLE
Docker node migration to Windows resulting status "monitoring failed"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5761]
**Describe the bug**

Node has been working correctly on Linux. After importing it to Windows it has started recently getting the "Monitoring Failed" message even though it had no  running previously on Ubuntu. Same network setup. 

User note:

"Currently trying to change my PC from Linux to Mac OS but running into an issue. I have two nodes, 0x59699dbe5e7be157cbd1770370e5f249a8aa6c5a and 0xfb4d88f6f30513357d2a73addc5348dcaeba842d. I was able to stop the other one, but when I started Linux, I got a monitoring failed message. What can I do to solve this issue and successfully transition to Mac OS?"

**To Reproduce**
1. Go to 'Find data-dir in docker node'
2. Click on 'Migrate to a Windows docker node'
3. See error

**Logs**
[**Click Here For Logs**](https://mystnodes.com/support/logs/2023-03-28-86f657b5-55f0-42ec-8a40-729649be25be-mysterium-node.zip1596647854)

**Comment by etherunit** [comment]
I suspect the migration was done incorrectly. As suggested, please use the following steps to conduct the migration and then check again:

To migrate from native to docker :
- open `%USERPROFILE%`
- make a copy the folder .mysterium and rename the copy to .mysterium-node

To migrate from docker to native :
- open %USERPROFILE%
- make a copy the folder .mysterium-node and rename the copy to .mysterium

**Comment by jganchozo** [comment]
Hello, I think that is not the problem I tried creating a new node on Mac, and I am getting the same problem. Monitoring failed.
