### ISSUE TITLE
Node UI displays incorrect data and earnings graph

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5767]
**Describe the bug**
The Data and Earnings graph of the node is inaccurate.

**To Reproduce**
1. Open Node UI
2. Check the "Earnings Report"
3. Change to "data" from "earnings"
 
**Expected behavior**
The graph should be updated instead of showing old information.

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/231169973-c43c09d9-0534-4fdf-aedf-1bd62472f00c.png)
![image](https://user-images.githubusercontent.com/68943180/231170018-c75bcd4b-f766-47c3-b827-123d0e3b2288.png)

**Environment:**
 - Node version: unconfirmed
 - Provider's identity: 0x604b19073863e1c0972bf86af55a47ad7477dcab]

**Comment by adinetech** [comment]
Any updates on this issue?

**Comment by mdomasevicius** [comment]
need retesting

**Comment by ZygintasBudrys** [comment]
Severity: Major 
Priority: Medium

**Comment by lusine-h** [comment]
Was not able to reproduce.

**Comment by ZygintasBudrys** [comment]
Will not be relevant after rework
