### ISSUE TITLE
Incorrect Statistics data is being displayed

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5772]
**Describe the bug**
The statistics data shown in the Node UI is not correct.

**Expected behavior**
Statistics data of Offline, Online, Idle, Connected should show the correct information.

**Screenshots**
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/68943180/232205308-20148b43-4f4c-4da4-ab1a-b9840b012a9a.png">
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/68943180/232206627-2a344469-f00c-47b5-aa10-92e7525c1fb3.png">
(No Network downtime)

**Comment by starfoxdot64** [comment]
Hey there! This is unrelated, and I apologize, but I needed to find a _safe_ way to reach out to you - the Discord server is compromised and advertising an airdrop, created with your account before being not only banned from the server, but impersonated by a dummy account sharing your user info. I don't know if you have the contacts for the higher ups, but they need to be roped in and fast - they're trying to steal MYST tokens.

**Comment by adinetech** [comment]
Hey @starfoxdot64, I wanted to let you know that our team has banned the scammer and deleted the messages. Thank you for reaching out to me via Github.

**Comment by starfoxdot64** [comment]
> Hey @starfoxdot64, I wanted to let you know that our team has banned the scammer and deleted the messages. Thank you for reaching out to me via Github.

Sounds good. Sorry about the, uh... _unusual_ method of contact.

**Comment by etherunit** [comment]
@adinetech Can you please check stats now? Did you see any improvements since our latest fixes?

**Comment by adinetech** [comment]
It is fixed already, you can close the issue.
