### ISSUE TITLE
Big gap between NodeUI and Mystnodes.com balance

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5776]
**Describe the bug**
0x2726bb879b213ec15046b62f1a462d6b7d29c916

The number node UI displays vs the mystnodes website versus wallet are all different. Node UI balance is lower than mystnodes.com balance.

https://hermes3.mysterium.network/api/v1/data/provider/0x2726bb879b213ec15046b62f1a462d6b7d29c916

**To Reproduce**
1. Go to 'NodeUI'
2. Go to 'Mystnodes.com'
3. Go to wallet
4. See discrepancies 

**Screenshots**
<img width="198" alt="Screenshot 2023-04-17 at 16 07 51" src="https://user-images.githubusercontent.com/84313603/232597604-883b7c19-1098-4e15-903e-28d7e2708892.png">
<img width="1456" alt="Screenshot 2023-04-17 at 17 01 29" src="https://user-images.githubusercontent.com/84313603/232597650-22360142-9c83-4832-a99f-50faf23d378c.png">

**Environment (please complete the following information):**
 - Node version: 1.19.21
 - OS: Linux
 - Your identity (if applicable): 0x2726bb879b213ec15046b62f1a462d6b7d29c916

**Comment by etherunit** [comment]
Thanks for reporting. It might be related to the issue with metrics infrastructure we have experienced a while ago.

**Comment by Peter-SovietSquirrel** [comment]
Environment (please complete the following information):

Node version: 1.20.0
OS: Linux
Your identity (if applicable): 0x604b19073863e1c0972bf86af55a47ad7477dcab
Grafana reports 6 MYST earned.
![image](https://user-images.githubusercontent.com/60095913/234526165-deb4cbae-d9f0-482c-8d07-df90072f9997.png)
![image](https://user-images.githubusercontent.com/60095913/234526447-145e07f2-bb9f-4a6b-8342-a3d3446b35ac.png)
