### ISSUE TITLE
I could not add my node into mystnodes.com

### ISSUE THREAD

**Issue by leon78113** [mysteriumnetwork/node#5780]
**Describe the bug**
I could not add my node into mystnodes.com, had checked the node of the API key is same as my account on mystnodes.com.

I am running 3 Myst nodes, 2 on Windows 10 (located U.S. & Taiwan ), 1 on Mac (located U.S.)

Tried serval times, the node on Windows ( located in Taiwan, node version 1.19.21) could not be added into my mystnodes.com.

After I claimed my node from localhost, it did not be added to my my mystnodes.com.

Tried to update the API key for the node, but it shows "Failed to register to mystnodes.com."

Please see the screenshots below: 

**Screenshots**
![00](https://user-images.githubusercontent.com/7873215/234070733-70641cef-83b3-4ba1-a18b-6147a94370a0.PNG)
![01](https://user-images.githubusercontent.com/7873215/234070738-26abe45d-b134-4717-ba82-d9683ff7d9bf.PNG)
![02](https://user-images.githubusercontent.com/7873215/234070741-9412333b-c7bb-43e1-82e5-785996b6704a.PNG)

P.S. 
Identity: 0x77bcf460b6c67394be9798ef8b672a88144f44a2
API Key: 3IJKjpx0VRgXktRd2mHZLzMYgofDStiZ5L7gQQcZ

**Comment by etherunit** [comment]
@leon78113 Is it possible to make a screenshot of whats being displayed under `dev tools > network tab` during this moment? Essentially, it's important to understand which calls are failing.

**Comment by leon78113** [comment]
@etherunit 

Do you mean this one? 

DevTools failed to load source map: Could not load content for chrome-extension://cmndjbecilbocjfkibfbifhngkdmjgog/lib/browser-polyfill.js.map: 
System error: net::ERR_BLOCKED_BY_CLIENT

![03](https://user-images.githubusercontent.com/7873215/234680271-bc86d38b-de6a-4f41-b028-9feefc1e086b.PNG)

**Comment by etherunit** [comment]
Thanks for the screenshot, but what we need is loading content from the dev tools on the page where "failed to register to mystnodes.com" is shown. Is that possible to get by any chance?

**Comment by leon78113** [comment]
Got it, please see the attachment. Thanks.

![01](https://user-images.githubusercontent.com/7873215/235251911-57563530-8212-4eca-926f-619c26568bb0.PNG)

**Comment by leon78113** [comment]
Hi, any update for the issue?

**Comment by etherunit** [comment]
@leon78113 I'm following up on this issue. Can you please confirm that issue is not longer exists on your end? Thank you in advance!

**Comment by etherunit** [comment]
Closing this one. Feel free to reopen if needed.
