### ISSUE TITLE
Earnings discrepancy - only settlement occured after earning 30+ MYST

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5783]
**Describe the bug**
The provider earned almost ~35 MYST (as shown in the mystnodes.com and node UI) but he received only 1 settlement (5 MYST).

**Expected behavior**
Usually, the settlement should happen at 5 MYST. If not, the balance should show on the Node UI but almost ~30 MYST is lost as it is never settled.

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/234311535-e69cfe01-b838-48bb-a98c-7f177043dbb4.png)
![image](https://user-images.githubusercontent.com/68943180/234311565-a2113e87-d0d4-499f-86c5-caa8a8b99370.png)
![image](https://user-images.githubusercontent.com/68943180/234311597-34df9c84-2e3d-4632-8724-b3d023805a7a.png)
![image](https://user-images.githubusercontent.com/68943180/234311672-b82bdecb-1a1b-4bc5-b3ff-9c00a553be8a.png)
<img width="534" alt="image" src="https://user-images.githubusercontent.com/68943180/234311851-8ff61272-7872-492c-8169-47ebfd02c895.png">

**Environment:**
 - Node version: 1.20.0
 - Provider's identity: 0x604b19073863e1c0972bf86af55a47ad7477dcab

**Comment by etherunit** [comment]
Thanks for reporting. It might be related to the issue with metrics infrastructure we have experienced a while ago, team will check it and inform back asap.

**Comment by JohnSmithyy** [comment]
I'm facing the same exact issue. Has a fix been made?

**Comment by etherunit** [comment]
We have fixed previous issues, however, we have experienced another issue with metrics. @soffokl will look into it

**Comment by coreydrysdale** [comment]
I am having the same issue. Here are my 3 node identities: 0xcad4a6e7fdee9bb50ffcf6f017129618087ec575,  0x8b43c9a398fe32329f523693b1dde49e38908ad0 & 0xf9724b5ff1538509ed72ac4c8b70c52d79e895de

**Comment by JohnSmithyy** [comment]
Any luck fixing it? Doesnt this mean that all mystnodes.com earnings are wrong and the leaderboards are also wrong?

**Comment by Peter-SovietSquirrel** [comment]
NodeID: 0xadc9563a22e2bcc9e39ab02febda0a09ee470baa
Mystnodes 30 day earning: 11.64
Grafana 30 day earnings: 2.17

**Comment by mat1990dj** [comment]
Any update regarding the issue?

**Comment by Peter-SovietSquirrel** [comment]
NodeID: 0xadc9563a22e2bcc9e39ab02febda0a09ee470baa
Mystnodes 30 day earning: 8.996153 MYST
Grafana 30 day earning: 2.35

**Comment by etherunit** [comment]
@mat1990dj @Peter-SovietSquirrel @JohnSmithyy @coreydrysdale 
Guys, we have done some fixes towards aggregating data for the earnings. Can you please check and confirm whether this issue is still present on your end. Thank you

**Comment by etherunit** [comment]
Closing this issue for now. Feel free to reopen if needed.
