### ISSUE TITLE
Lost earnings after 2 weeks of session

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5788]
**Describe the bug**
The session that had been running for over 10 days and owed the node runner at least 25 MYST has not paid out. Provider is wondering if a lost connection or server reboot can be blamed for the lack of payment. He believes that there is a significant issue with the way rewards are distributed, as sessions cannot run for so long without any payment. Provider would appreciate it if someone could investigate the lost revenue. Their node provided 300GB of data and almost two weeks of session service for one client alone.

The session that began in 93a31 generated earnings of more than 25 MYST, but it is not appearing in the history. There are a few other missing sessions, but they are less significant than this one. The node runner was previously assured that this would be paid out and that such incidents do not occur, as per a support thread.

**Expected behavior**
someone ran up over 20 MYST in 1 connection but i needed to reboot, that 20 MYST should have made its way to node balance.

Get paid out the earnings you had earned.
What would be better is if it went 24 hours then pay the current earnings out and reset the connection to 0. This would be like getting interim payments.

**Screenshots**
<img width="374" alt="Screenshot 2023-04-28 at 06 51 14" src="https://user-images.githubusercontent.com/84313603/235118300-f6646bc9-0159-40b6-beb0-92cbfff91c37.png">

**Environment (please complete the following information):**
 OS = ubuntu 20.04
Node Version = 1.20.0
Node UI Version = 2.6.3

**Additional context**
The provider doesn't see any logs in the mapped folder to the docker container. As the provider had previously mentioned on intercom chat, they have deleted and recreated the docker container since reporting the issue, so there will be no logs. However, this doesn't stop us from attempting to reproduce the issue themselves, as the steps are straightforward.

**Comment by etherunit** [comment]
@isaackielma Provider identity is missing. Could you please add it to the issue?

**Comment by isaackielma** [comment]
Node id: 0xd92f65ea87be884244e94111fb954c649292f974

**Comment by isaackielma** [comment]
Provider has confirmed issue was resolved.
