### ISSUE TITLE
(mystnodes.com) The version writes over other columns

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5797]
**Describe the bug**
In the mystnodes.com UI, the version writes over the OS and other columns - Look at the screenshot below.

**Expected behavior**
There must be some space or sorting to make it look better, right now it didn't look good.

**Screenshots**
![image](https://user-images.githubusercontent.com/68943180/236636384-aad8cd4b-dcaa-41e5-96ef-9d7b825b185d.png)

**Comment by Pro100Atom** [comment]
I have the same problem. Let's wait for a response from the developers

**Comment by MykolasMaciekus** [comment]
Improved, please test again

**Comment by lusine-h** [comment]
The issue is solved.
