### ISSUE TITLE
I'm sending MYST to my Node but it's not received

### ISSUE THREAD

**Issue by NinoSkopac** [mysteriumnetwork/node#5802]
<img width="640" alt="Screenshot 2023-05-15 at 02 01 34" src="https://github.com/mysteriumnetwork/node/assets/1783732/075e2827-60fb-4a53-a00f-5f74e2bbebdd">

Transactions: https://polygonscan.com/address/0x60a73e07e3f849b02ef37a20dd1c00ed13d6389b#tokentxns

<img width="1202" alt="Screenshot 2023-05-15 at 02 01 52" src="https://github.com/mysteriumnetwork/node/assets/1783732/123b7d97-b8a4-42f4-aa33-fbe44a257847">

```bash
% yarn fleet-info
yarn run v1.22.19
$ ts-node src/fleet/info.ts
US - balance:	0
✨  Done in 4.09s.
```

Please explain

**Comment by Loggsie** [comment]
You shouldn't send MYST here once your node identity has been verified with the initial deposit of typically MYST 0.2

You would instead send MYST from the transaction page under settle now to your ERC-20 wallet address.

As you do not have access nor control of your nodes identity private key you have (to my knowledge), no way to recover what you have already sent.

**Comment by Loggsie** [comment]
To be clear, you do not send MYST to your node.

What are you trying to achieve? 

When you're hosting a node people pay MYST directly to your ERC-20 compatible Polygon wallet address, it doesn't go to the node at any point. Your wallet address is specified as shown in the images.

![Screenshot_20230515-174519.png](https://github.com/mysteriumnetwork/node/assets/89365430/3882da79-b177-4988-881e-3908024d6819)

![Screenshot_20230515-174620.png](https://github.com/mysteriumnetwork/node/assets/89365430/3f1595d7-2e77-4a2d-acbf-71fca796e6fe)

If you're using Mysterium VPN as a user to connect to a node and need account credit, MYST is sent to your top up address. This is entirely different to your node's identify address.

**Comment by NinoSkopac** [comment]
Okay.

Where's the top up address?

**Comment by Loggsie** [comment]
You don't have one as you're hosting a node.

**Comment by NinoSkopac** [comment]
But I need the node to connect

**Comment by Loggsie** [comment]
Then close this case as solved and request assistance with your node not receiving traffic. 

Your node already has an established identity, now you need help as to why traffic isn't being received.

**Comment by NinoSkopac** [comment]
It's not solved. 

How do i top up?

**Comment by Loggsie** [comment]
Then you're using the incorrect software. 

Your screen shot is for a node. 

Download the Mysterium VPN software and you'll see your top up address listed.

**Comment by NinoSkopac** [comment]
I don't think I'm using incorrect software.

I'm not trying to use the desktop app, I'm running this on a server. I had this working before, but once the money from initial top up had dried up, it stopped working. Afterwards, randomly, sometimes it shows a tiny amount of myst, and then it works again. Then 0 again. Wth

**Comment by NinoSkopac** [comment]
Like this: https://github.com/mysteriumnetwork/workshop

**Comment by NinoSkopac** [comment]
I thought I might have storage issues, but I tried increasing the disk size and it didn't matter. 

After, I read that the node requires only 500 MB of space, and I had more than that from the get-go.

**Comment by Loggsie** [comment]
The github you linked to is a node docker container for connecting multiple nodes (fleet) to specific countries, it is not for standard VPN use. What exactly are you trying to deploy and/or achieve?

The standard VPN software for Linux (RPM & Deb) can be found here

 https://www.mysteriumvpn.com/downloads

**Comment by NinoSkopac** [comment]
Yep, I'm deploying it containerized, and I had it working before. 

My issue is myst not arriving.

**Comment by NinoSkopac** [comment]
Gotta use the channel address!
