### ISSUE TITLE
Myst Tokens went to old hermes -- default wallet address?

### ISSUE THREAD

**Issue by Andrew2k3** [mysteriumnetwork/node#5806]
Node was setup and working for a few months.
I did not setup a send address for the MYST wallet for a very long time... because i was still trying to choose between metamask/HitBTC...
My Myst tokens started to consolidate automatically by default to an address... i believe support was helping me before and they called it "old hermes" im not sure what that means...

How do i get my Myst tokens back... (i do not want to get charged service fees again)...
My new wallet address is 0x0d8f1845d25b564568C628224FdC606635641233

![Capture](https://github.com/mysteriumnetwork/node/assets/134179110/6fb18689-77d1-4f97-bb54-3600f8334153)

**Comment by etherunit** [comment]
@Andrew2k3 

Please follow the steps below to retrieve your tokens from the old Hermes:

1. Login to `myst cli`
2. run: `identities export <identity> "<password>"`  with a new non-empty password
3. copy the result in the form of `{"address":"59 ... version":3}`  make sure there are no \" , if there are replace them with just " . Create a new file with `.json` extension and copy the previous keystore
4. Import the new file in metamask using the import json option in metamask. Use your previously defined password. The address should be the one written in the json file in the "address" field.
5. Get some matic in your wallet by using a faucet (or request to support)
6. Go to your channel address in polygonscan in the contract>write contract section and connect metamask. Make sure it shows the address you just imported as connected.
7 Paste the address were you want to send the funds to in the beneficiary field
9 Pick a timestamp between current time and 3 days from now here: https://www.unixtimestamp.com/ (you will have to do this transaction before said date, so pick at least a day in the future just to be safe). Paste it int he validUntil field
write 0x0  in the signature field
10. Press write.
11. A metamask popup should appear that looks like this:
12. Press confirm and wait until the transaction is mined
13. After 3 days call the finalizeExit using polygonscan

**Comment by etherunit** [comment]
@Andrew2k3 Any updates?

**Comment by etherunit** [comment]
@Andrew2k3 I'm closing this issue for now. If you will have any questions, feel free to reopen this issue. Thanks
