### ISSUE TITLE
node failed to start

### ISSUE THREAD

**Issue by nickali2** [mysteriumnetwork/node#5808]
I just installed node with this code on my Linux server (Ubuntu 20.4):
`sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"`

after installation completed i checked the status using this code:
`sudo systemctl status mysterium-node.service`
 i received this message:
 `● mysterium-node.service - Server for Mysterium - decentralised VPN Network
     Loaded: loaded (/lib/systemd/system/mysterium-node.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-05-22 18:31:59 CEST; 502ms ago
       Docs: https://mysterium.network/
    Process: 54782 ExecStart=/usr/bin/myst $CONF_DIR $SCRIPT_DIR $DATA_DIR $RUN_DIR $DAEMON_OPTS --ui.features=restart service --agreed-terms-and-conditions $SER>
   Main PID: 54782 (code=exited, status=1/FAILURE)`
![image](https://github.com/mysteriumnetwork/node/assets/23019220/79be9e13-88f3-4052-a895-2924ab2cfbf1)

service never started and I cannot connect to server via ip:4449. server refuses the connection. this is my log
`-- Logs begin at Mon 2023-05-22 17:57:18 CEST. --
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.872 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://broker.mysterium.network:4222 removed
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.873 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.22.197:4222 removed
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.873 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.23.12:4222 removed
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.873 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.23.14:4222 removed
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.873 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.23.16:4222 removed
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.873 INF firewall/incoming_firewall_noop.go:38    > Rules reset was requested
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.873 INF firewall/outgoing_firewall_noop.go:35    > Rules reset was requested
May 22 18:34:26 firstfrontserver myst[55261]: 2023-05-22T18:34:26.873 ERR cmd/mysterium_node/mysterium_node.go:68  > Failed to execute command:  error="could not get hermes URL: Get \"https://observer.mysterium.network/api/v1/observed/hermes\": dial tcp: lookup observer.mysterium.network on [::1]:53: read udp [::1]:47499->[::1]:53: read: connection refused"
May 22 18:34:26 firstfrontserver systemd[1]: mysterium-node.service: Main process exited, code=exited, status=1/FAILURE
May 22 18:34:26 firstfrontserver systemd[1]: mysterium-node.service: Failed with result 'exit-code'.
May 22 18:34:31 firstfrontserver systemd[1]: mysterium-node.service: Scheduled restart job, restart counter is at 349.
May 22 18:34:31 firstfrontserver systemd[1]: Stopped Server for Mysterium - decentralised VPN Network.
May 22 18:34:31 firstfrontserver systemd[1]: Started Server for Mysterium - decentralised VPN Network.
May 22 18:34:31 firstfrontserver myst[55287]: 2023-05-22T18:34:31.999 DBG config/config.go:81                      > Loading user configuration: /etc/mysterium-node/config-mainnet.toml
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.000 INF config/config.go:93                      > User configuration loaded:
May 22 18:34:32 firstfrontserver myst[55287]: {}
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.014 DBG config/config.go:216                     > Returning CLI value data-dir:/var/lib/mysterium-node
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.014 DBG config/config.go:216                     > Returning CLI value data-dir:/var/lib/mysterium-node
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.014 DBG config/config.go:216                     > Returning CLI value script-dir:/etc/mysterium-node
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.015 DBG config/config.go:216                     > Returning CLI value runtime-dir:/var/run/mysterium-node
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.015 DBG config/config.go:216                     > Returning CLI value keystore.lightweight:true
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.015 INF logconfig/config.go:74                   > Log level: debug
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.015 INF logconfig/config.go:76                   > Log file path: /var/lib/mysterium-node/.mysterium/logs/mysterium-node
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.016 DBG logconfig/rollingwriter/rollingwriter.go:76 > Found 0 old log files in log directory, skipping cleanup
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.016 INF cmd/di.go:221                            > Starting Mysterium Node 1.20.4
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.018 INF firewall/incoming_firewall_noop.go:32    > Rules bootstrap was requested
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.019 INF cmd/di.go:704                            > Using local DNS: feedback.mysterium.network -> [116.203.17.150]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.019 INF cmd/di.go:704                            > Using local DNS: api.ipify.org -> [54.204.14.42 54.225.153.147 54.235.83.248 54.243.161.145 23.21.109.69 23.21.126.66 50.19.252.36 174.129.214.20]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.019 INF cmd/di.go:704                            > Using local DNS: badupnp.benjojo.co.uk -> [104.22.70.70 104.22.71.70 172.67.25.154]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.020 INF cmd/di.go:704                            > Using local DNS: broker.mysterium.network -> [51.15.22.197 51.15.23.12 51.15.23.14 51.15.23.16]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.020 INF cmd/di.go:704                            > Using local DNS: transactor.mysterium.network -> [51.15.22.197 51.15.23.12 51.15.23.14 51.15.23.16]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.020 INF cmd/di.go:704                            > Using local DNS: affiliator.mysterium.network -> [51.15.22.197 51.15.23.12 51.15.23.14 51.15.23.16]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.021 INF cmd/di.go:704                            > Using local DNS: observer.mysterium.network -> [51.15.22.197 51.15.23.12 51.15.23.14 51.15.23.16]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.021 INF cmd/di.go:704                            > Using local DNS: quality.mysterium.network -> [51.158.129.204]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.021 INF cmd/di.go:704                            > Using local DNS: trust.mysterium.network -> [51.15.22.197 51.15.23.12 51.15.23.14 51.15.23.16]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.022 INF cmd/di.go:704                            > Using local DNS: pilvytis.mysterium.network -> [51.15.22.197 51.15.23.12 51.15.23.14 51.15.23.16]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.023 INF cmd/di.go:704                            > Using local DNS: discovery.mysterium.network -> [51.15.22.197 51.15.23.12 51.15.23.14 51.15.23.16]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.023 INF cmd/di.go:704                            > Using local DNS: location.mysterium.network -> [51.158.129.204]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.024 DBG communication/nats/connector.go:79       > Connecting to NATS servers: [nats://broker.mysterium.network:4222]
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.024 INF firewall/outgoing_firewall_noop.go:57    > Allow URL nats://broker.mysterium.network:4222 access
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.024 INF firewall/outgoing_firewall_noop.go:57    > Allow URL nats://broker.mysterium.network:4222 access
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.025 INF firewall/outgoing_firewall_noop.go:57    > Allow URL nats://51.15.22.197:4222 access
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.025 INF firewall/outgoing_firewall_noop.go:57    > Allow URL nats://51.15.23.12:4222 access
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.025 INF firewall/outgoing_firewall_noop.go:57    > Allow URL nats://51.15.23.14:4222 access
May 22 18:34:32 firstfrontserver myst[55287]: 2023-05-22T18:34:32.025 INF firewall/outgoing_firewall_noop.go:57    > Allow URL nats://51.15.23.16:4222 access
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.849 INF cmd/di.go:733                            > Using L1 Eth endpoints: [https://ethereum1.mysterium.network/ https://cloudflare-eth.com/]
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.850 INF cmd/di.go:734                            > Using L2 Eth endpoints: [https://polygon1.mysterium.network/ https://polygon-rpc.com/]
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.853 WRN cmd/di.go:319                            > observer hermeses call failed, using fallback known hermeses err="Get \"https://observer.mysterium.network/api/v1/observed/hermes?approved=true\": dial tcp: lookup observer.mysterium.network on [::1]:53: read udp [::1]:53289->[::1]:53: read: connection refused"
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.853 INF cmd/di.go:516                            > Node chain id 137
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.857 ERR session/pingpong/hermes_url_getter.go:102 > failed to get hermes url from blockchain, using fallback error="Post \"https://polygon1.mysterium.network/\": dial tcp: lookup polygon1.mysterium.network on [::1]:53: read udp [::1]:37150->[::1]:53: read: connection refused" chain_id=137 hermes_id=0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.859 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://broker.mysterium.network:4222 removed
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.859 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://broker.mysterium.network:4222 removed
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.859 WRN communication/nats/connection_wrap.go:105 > NATS: disconnected
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.860 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.22.197:4222 removed
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.860 WRN communication/nats/connection_wrap.go:104 > NATS: connection closed
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.860 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.23.12:4222 removed
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.860 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.23.14:4222 removed
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.860 DBG firewall/outgoing_firewall_noop.go:61    > Rule for URL: nats://51.15.23.16:4222 removed
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.860 INF firewall/incoming_firewall_noop.go:38    > Rules reset was requested
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.861 INF firewall/outgoing_firewall_noop.go:35    > Rules reset was requested
May 22 18:34:33 firstfrontserver myst[55287]: 2023-05-22T18:34:33.861 ERR cmd/mysterium_node/mysterium_node.go:68  > Failed to execute command:  error="could not get hermes URL: Get \"https://observer.mysterium.network/api/v1/observed/hermes\": dial tcp: lookup observer.mysterium.network on [::1]:53: read udp [::1]:51979->[::1]:53: read: connection refused"
`

**Comment by etherunit** [comment]
@nickali2 Just for testing purposes, could you please try to install a node using apt commands on your Linux machine:

```
sudo add-apt-repository ppa:mysteriumnetwork/node
sudo apt-get update
sudo apt install myst
```

**Comment by nickali2** [comment]
> @nickali2 Just for testing purposes, could you please try to install a node using apt commands on your Linux machine:
> 
> ```
> sudo add-apt-repository ppa:mysteriumnetwork/node
> sudo apt-get update
> sudo apt install myst
> ```

I get the same error.

**Comment by etherunit** [comment]
Looks like something is blocking it on your host machine from being properly installed.

**Comment by etherunit** [comment]
I'm closing this issue for now. Feel free to reopen it anytime in case you have an update.
