### ISSUE TITLE
Sessions and earnings not being properly recorded

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5816]
**Describe the bug**

There is an issue with sessions and earnings not being properly recorded in the dashboard and history.

**To Reproduce**

1. Go to the dashboard 
2. Check for an ongoing session from with more than 20GB of data transfer and more than 6 MYST in earnings.
3. session is no longer listed in the ongoing sessions.
5. Check the History section and observe that the session is not recorded there either.
6. Notice that the auto settlement value remains almost the same.

**Expected behavior**

The session should be properly recorded in the ongoing sessions and history sections of the dashboard. The auto settlement value should reflect the correct earnings.

**Screenshots**

<img width="1329" alt="Screenshot 2023-06-01 at 11 56 10" src="https://github.com/mysteriumnetwork/node/assets/84313603/ec800a2f-cdb7-40ea-9af1-b985abee3f01">

Please note that a similar issue occurred a few days ago with another big transaction from a Portuguese session, which was logged correctly.

Additional Notes:

Note from provider:

"I just saw another movement in the history with 6.50087 MYST, which was also not added to the earnings.

1. Yesterday in the morning between 9:00-12:00 (Lisbon timezone) I checked the dashboard. There was a couple of ongoing sessions. One in particular from Portugal was up for more than 1 day with more than 20Gb of data transfer (it had more than 6 Myst on the earning column),
2. This session was having traffic since I saw the value rising slowly during the morning.
3. The auto settlement value was around 4.5 Myst at that time
4. at the end of the morning (I think after 12:00 Lisbon timezone) The session was not on the ongoing sessions anymore. Looking into History, it was not recorded there also.
5. The auto settlement maintain almost the same value (it might have been updated on another ongoing small transactions)

Note that a couple of days ago (during the weekend) I saw another big transaction with a Portuguese session. That one was logged correctly.

Hope this helps"

**Comment by jenovauh** [comment]
I have the same issue. To me it is kind of like cheating our bandwidth and not earning anything from such big transaction.

**Comment by davidpcruz** [comment]
This happened again now with Node version: 1.23.0.
The original bug was created on my behalf by support :) 
Another big session from Portugal. The auto settlement was almost reaching its threshold 4.94 MYST.
There was a session from Portugal (screen attached) that ended with 0.41098 MYST, and the value was not updated.
Seams that long connections are not being counted properly
![image](https://github.com/mysteriumnetwork/node/assets/2327456/659efd68-a76a-43a8-99e0-249a83d0621b)
