### ISSUE TITLE
Myst tokens not accumulating properly 

### ISSUE THREAD

**Issue by gotmygat** [mysteriumnetwork/node#5820]
**Describe the bug**

I suspected that mystnodes rewards are not accruing properly. Testing it by connecting to my own node and streaming 4k YouTube. From outside my house. 

I can see that I paid more in myst than my node is reporting back to me. This is a problem because the rewards UI is not displaying transparency/accuracy and there's no wa
![Screenshot_20230617_235602_RVNC Viewer](https://github.com/mysteriumnetwork/node/assets/49083413/92ffbdc7-76f0-46a0-8677-f8e3eecebe55)
![Screenshot_20230617_235557_RVNC Viewer](https://github.com/mysteriumnetwork/node/assets/49083413/64d1025e-60cc-49de-814f-ab66517049bc)
![Screenshot_20230617_235639_Keep Notes](https://github.com/mysteriumnetwork/node/assets/49083413/f214cde3-4588-4c45-8f6e-ee446c63c935)
y what I put in the screenshot is not a lie.

**To Reproduce**

Go check my node for my connection from Canada which is me:

0x2726bb879b213ec15046b62f1a462d6b7d29c916

**Expected behavior**

The traffic displayed for how much traffic my node managed should reflect what I literally streamed off my own node. 

![Screenshot_20230617_235551_RVNC Viewer](https://github.com/mysteriumnetwork/node/assets/49083413/0dccaef1-88
![Screenshot_20230617_235639_Keep Notes](https://github.com/mysteriumnetwork/node/assets/49083413/e22d962b-7a38-4930-a6f7-251d91b67cfe)
10-4bca-a10d-7006c33fdb5c)

**Comment by etherunit** [comment]
@gotmygat 
Based on our internal sources, session=40d0fcef-1266-44f4-82ae-45464ed1077b earned you 0.673370MYST

```
Provider duration1.96 hour
Consumer duration1.85 hour
Provider report3.22 GB
Consumer report3.12 GB
MYST earned0.673370
```
Can you please check it on your end?
