### ISSUE TITLE
(Mystnodes - Android) Incorrect UI Theme Adjustment in Mysterium Node on Android

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5827]
**Describe the bug**
By default, the UI theme is set to the OS default in the Mysterium Node on Android. However, it was initially set to light while my system default was dark. I then changed it to dark and subsequently clicked back on the OS default. It is now correctly set to dark.

**To Reproduce**
1. Open Mysterium VPN
2. Open Settings
3. Open Node UI
4. Node UI -> Settings -> User Settings -> Theme, It shows OS default and the interface was light, but the system (OS) was dark.

**Expected behavior**
Mysterium Node (Mystnodes) on Android should check the system theme/mode and adjust the UI theme accordingly.

**Screen recorded video**
https://github.com/mysteriumnetwork/node/assets/68943180/bd6e8d3c-0280-470c-b9b8-b2cfdbda8c58

**Environment:**
 - Android Node version: 1.0
 - OS: Android 12

**Comment by psdhaps** [comment]
How to download mystnode for android
