### ISSUE TITLE
Beneficiary eventual change

### ISSUE THREAD

**Issue by mdomasevicius** [mysteriumnetwork/node#5865]
As user it would be nice to be able to change beneficiary wallet in NodeUI without performing withdrawal.

Currently NodeUI needs to call withdraw with beneficiary change endpoint. 
Idea: have an endpoint that just accepts beneficiary address without performing withdrawal. Then when next withdrawal is performed (automatic or manual) use the last set beneficiary wallet to perform withdraw with beneficiary change if needed.

**Comment by n10ty** [comment]
We already have some endpoints in Tequilla API to store and get payout address:
[GetPayoutAddress](https://github.com/mysteriumnetwork/node/blob/master/tequilapi/endpoints/identities.go#L605)
[SavePayoutAddress](https://github.com/mysteriumnetwork/node/blob/master/tequilapi/endpoints/identities.go#L645C26-L645C43)

**Comment by Guillembonet** [comment]
This will fail in this scenario:
1. User sets a new beneficiary using the endpoints
2. User triggers a settle event using the `/transactor/settle/sync` or `/transactor/settle/sync`

In that case the locally saved beneficiary will not be used and user will receive an error or settle the funds in an undesired wallet
