### ISSUE TITLE
(Mystnodes.com) VPN Service Misidentified as "Data Scraping for B2B Clients"

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/node#5866]
**Describe the bug**
VPN service on mystnodes.com says "Data scraping traffic from B2B clients" instead of "Mysterium VPN app user traffic" etc.

**To Reproduce**
1. Check mystnodes.com 
2. Click on Services to check all service types. 
3. See the error

**Expected behavior**
Edit the content of the VPN service on mystnodes.com to "Mysterium VPN app user traffic" or something relevant to it.

**Screenshots**
![image](https://github.com/mysteriumnetwork/node/assets/68943180/eb63898f-e0af-46c9-88f1-911cca7a51d1)

**Comment by ZygintasBudrys** [comment]
Severity: Low
Priority: Medium

**Comment by adinetech** [comment]
Closing as it's fixed.
