### ISSUE TITLE
Different earning reported

### ISSUE THREAD

**Issue by Peter-SovietSquirrel** [mysteriumnetwork/node#5869]
In each of the 3 services below are all displaying different earning for the last 30 days. 

Node ID
0x57daba353514f004c86edf2e3892740ec4d98c4d

Mystenodes	253.253263 MYST 
NodeUI		234.922 MYST
Grafana		324 MYST

**Comment by Carbon2029** [comment]
similar case here

**Comment by etherunit** [comment]
@Carbon2029 Can you please elaborate more? Where the difference comes from?

**Comment by Carbon2029** [comment]
@etherunit  well the last 30 day earnung in node ui and Mystnodes dosent match 
its sometimes high sometimes low sooo its confusing

**Comment by etherunit** [comment]
@Carbon2029 Team is working on it. Will keep you updated.
