### ISSUE TITLE
error "Failed to create a new connection: server responded with an error: 500 (http://127.0.0.1:4050/connection) [err_connect]

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5872]
**Describe the bug**
When user tries to connect to a node via Docker user often gets the following error in Docker logs: "> Unexpected message:
!?B??;?HԷyG??L??e - attempting to continue
2023-08-28 16:08:34 2023-08-28T14:08:34.648 DBG ../../nat/traversal/pinger.go:394 > Remote peer data received, len: 32"

It seems there is a problem with encoding during initial connection state

**To Reproduce**
1. Create a Docker Container (Docker for Windows on Windows 10, with WSL2 Ubuntu 22.04) from the image https://hub.docker.com/r/mysteriumnetwork/myst

2. 50% of the nodes gets the error above and connection is not possible. But when he tries to conect to the same nodes (that are not working on Docker) via Mysterium Dark Windows client software (on the same machine where Docker is running; same network and router) the nodes are connecting and working okay.

**Expected behavior**
That the non-working nodes on Docker start to work the same way as in the Mysterium Dark Windows client software

**Screenshots**

**Environment (please complete the following information):**
 Windows 10 Enterprise with Docker for Desktop 4.21.1 (114176). Also the same problem exists on native Ubuntu 22.04 with Docker using the same image.

Attached are some screenshots that describe the issue in more detail.

![connection_issue_docker](https://github.com/mysteriumnetwork/node/assets/84313603/5d2e9cbe-088b-4f2c-acdd-d8893326e36e)

![connection_issue_docker2](https://github.com/mysteriumnetwork/node/assets/84313603/da7642e2-73e6-47d4-87a6-74b8e85a6aec)

![myst_error_docker](https://github.com/mysteriumnetwork/node/assets/84313603/c4f7d3be-a4fa-4937-980c-82a6fa0fb5a0)

![myst_error_docker2](https://github.com/mysteriumnetwork/node/assets/84313603/d98d9143-5bb1-4f12-96fc-65caaf955e95)

**Comment by morpheus9393** [comment]
Is there any news regarding the bug? 

We have been waiting since September for this to be fixed and a quick Google search shows that many users are affected. 

When can we expect the bug(s) to be fixed?
