### ISSUE TITLE
Monitoring failed for one of two same nodes

### ISSUE THREAD

**Issue by YuriyGavrilov** [mysteriumnetwork/node#5883]
**Describe the bug**

0x16687310f8dd4f1e3149e18447c5029ecb70b143 - Monitoring failed 
0x4878af9ab6cb85675ec9b549565c3ef69702fc23 - works fine

**To Reproduce**

**Expected behavior**
Two nodes receive traffic well. 

**Screenshots**
<img width="720" alt="Снимок экрана 2023-10-15 в 10 29 34" src="https://github.com/mysteriumnetwork/node/assets/44679014/24281eca-54bd-49c0-b039-059cfd136ae0">

**Environment (please complete the following information):**
 - Node version: [e.g. 1.27.0]
 - OS: [e.g. ubuntu ]
 - Desktop app version (if applicable): [e.g. 2.0.4]
 - Docker (if applicable): specify docker version and image tag
 - Your identity (if applicable): [e.g. ]
 - Payment (top-op) reference (if applicable): [e.g. 1118e94e-27fc-4fd2-b604-fd26008fb709]

**Additional context**
Two week ago failed node goes offline and nothing can turn it back to online. rm docker run it again, reboot. 
 of course I've done this manual https://help.mystnodes.com/en/articles/8005254-firewall-iptables-configuration

This two nodes completly the same, same OS, Hardware, lte modem. etc..

**Comment by szferi91** [comment]
same here, they don't seem to care, the support told me to use the one that works xD

**Comment by YuriyGavrilov** [comment]
@szferi91 I think there is some ip geo checks… there in no other explanation

**Comment by etherunit** [comment]
@kreaninw @szferi91 Guys, can you please provide your providers ids? thanks
