### ISSUE TITLE
Monitoring failed ISP RCS & RDS SA / Digi ROMANIA

### ISSUE THREAD

**Issue by neostyle14** [mysteriumnetwork/node#5900]
![fff](https://github.com/mysteriumnetwork/node/assets/123271266/53201f56-7492-41ec-8ff0-1d9011c9494b)
![3nodes](https://github.com/mysteriumnetwork/node/assets/123271266/ac466cac-a713-4cc3-b3f8-53b51b515d9d)
Hi, I'm from Romania, I use RCS & RDS SA / Digi as an internet provider.
I have 3 mysterium nodes and since 21.10.2023 none of them work.
I discussed on the official mysterium network discord channel with several administrators, especially with "Adine" about this problem, but I still haven't managed to solve the problem, the 3 nodes are still non-functional.
I mention that until this date of 21.10.2023 the nodes worked perfectly and I did not make any kind of modification to the network or the ports in my network.

I talked to the user "Yung" on discord and he checked if there is any node in Romania that uses the same internet provider as me and he told me that all the nodes that have this internet provider are down.

When I enter the graphical interface on the browser, my nodes appear online, but the quality shows a red dot and I have absolutely no session with anyone, and monitoring failed appears on all 3 nodes.

I tried on one of my nodes that is installed on a raspberry pi to replace the "resolvconf" module with "systemd-resolved" but it still doesn't work.

My 3 nodes: 

Nebra Titulescu
0x4f06de4a834a5d5005367f2fda6e9e58fa9d9898

Nebra Petite Stone Viper
0x7168ac040cd8b4e89bf5283b825136e6d1908973

Raspberry
0x569d2459dd5803a3cda83e843b6f3529ffe1f7c6

I would like to mention in particular that I am not the only one with this problem, all the users who have the mysterium network node and have RCS RDS SA / Digi as their internet provider have the same problem as me, it doesn't work for them either.

**Comment by neostyle14** [comment]
I send logs to discord user "Adine"

**Comment by etherunit** [comment]
@neostyle14 Team is checking it. We can see that node itself is working fine, however, it's not checked properly by our monitoring agent.
I will keep you posted.

**Comment by mirsadu76** [comment]
I'm in the same situation.
Having the same ISP - RCS & RDS SA, my node shows "Monitoring failed" on my mystnodes account.
When trying to test the node, I get an "Internal Server Error" message.

In the NodeUI Dasboard:
Status: online
Quality: red
NAT: open
Last 24 hours statistics: 100% online, 100% idle

The last connection / session was on 25/10/2023 and it lasted for about 4 hours. Since then, none. Until this date, everything worked just fine and no changes were made to the settings or the configuration files after the node installation.

I updated the node to the latest version, but nothing changed.

OS: Debian (Linux Mint Debian 5 - Elsie)
Node version: 1.28.0
Node UI version: 2.13.1
Node ID: 0xf1f55335ab07985f1824bff4cf206bea2beb54c0

[myst-log.txt](https://github.com/mysteriumnetwork/node/files/13276819/myst-log.txt)

**Comment by ms74ro** [comment]
This problem has only 2 causes RCS-RDS or Mysterium. Honestly, I suspected the people from RCS-RDS of having done something, but now I even suspect the people from Mysterium. Romanian nodes were in the Top 100, now there are none. Conspiracy or what? Maybe I'm wrong, but I don't think so.

**Comment by szferi91** [comment]
actually, someone hacked them from an IP linked to an RDS Romania account, now everyone is blocked from the RDS Romania

**Comment by etherunit** [comment]
@ms74ro @szferi91 Actually, it's far away from conspiracy theory. The specific issue is connected to abusive activities from multiple user accounts who used IPs (mapped to a certain ASN) supplied by RDS Romania. As our system was frequently targeted for abuse, it automatically blocked the IPs and removed it from the network. Our team is actively investigating it and our goal is to remove normal users (who didn't participate in traffic abuse) from the block list as quickly as we can.
We apologies for any inconvenience.

**Comment by ms74ro** [comment]
So in the end, RCS-RDS is not to blame. I was really determined to give up their services. In this case I will wait.

**Comment by neostyle14** [comment]
> @ms74ro @szferi91 Actually, it's far away from conspiracy theory. The specific issue is connected to abusive activities from multiple user accounts who used IPs (mapped to a certain ASN) supplied by RDS Romania. As our system was frequently targeted for abuse, it automatically blocked the IPs and restricted from the network. Our team is actively investigating it and our goal is to find a workaround and remove normal users (who didn't participate in traffic abuse) from the block list as quickly as we can. We apologies for any inconvenience.


any update?

**Comment by neostyle14** [comment]
Hi, now the nodes are back online. Thank you!!
