### ISSUE TITLE
Disproportion between bandwith speed limiter and the actual internet speed of the client

### ISSUE THREAD

**Issue by m1hc1u** [mysteriumnetwork/node#5902]
**Describe the bug**
My ISP provides me with 450 Mb/s download speed and 50 Mb/s upload speed. We've conducted few tests via Mysterium Dark with my contact who is ~ 100km away within same country. He has 600 Mb/s download & 300 Mb/s upload speed.

We made 4 tests and I used "Limit bandwith to..." under Node UI\Settings\Traffic menu. ⁠#node-runners-general 

Test # 1 - Limit bandwith to 50 Mb/s
Test # 2 - Limit bandwith to 100 Mb/s
Test # 3 - Limit bandwith to 250 Mb/s
Test # 4 - Limit bandwith to 400 Mb/s

There were none other connections with my node during tests - only my contact.
As you can see, the difference between chosen limit and client's speeds are at least 9x lower than expected.

**To Reproduce**
1. Connect with my node
2. Use speedtest to check the bandwith

**Expected behavior**
Almost none disproportion between limited bandwith setup and contact's speed.

**Screenshots**
Test # 1 [https://cdn.discordapp.com/attachments/1096784581732093962/1167583754580148224/50mbps.png?ex=654ea81b&is=653c331b&hm=d2de60b1790d1a55b724e3f73d6cb06c35a7ceb5bc98812265f41cf899d12a4c&](https://cdn.discordapp.com/attachments/1096784581732093962/1167583754580148224/50mbps.png?ex=654ea81b&is=653c331b&hm=d2de60b1790d1a55b724e3f73d6cb06c35a7ceb5bc98812265f41cf899d12a4c&)
Test # 2 [https://cdn.discordapp.com/attachments/1096784581732093962/1167583754831790100/100mbps.png?ex=654ea81b&is=653c331b&hm=e628bb502d902d270b4309b153def0eb11ba368cc6a691cc2a97e370bef0529d&](https://cdn.discordapp.com/attachments/1096784581732093962/1167583754831790100/100mbps.png?ex=654ea81b&is=653c331b&hm=e628bb502d902d270b4309b153def0eb11ba368cc6a691cc2a97e370bef0529d&)
Test # 3 [https://cdn.discordapp.com/attachments/1096784581732093962/1167583755146383381/250mbps.png?ex=654ea81b&is=653c331b&hm=e49002f2619b10775a40a5cc0e422f203e799305c9204eb1cce398bc73ddf121&](https://cdn.discordapp.com/attachments/1096784581732093962/1167583755146383381/250mbps.png?ex=654ea81b&is=653c331b&hm=e49002f2619b10775a40a5cc0e422f203e799305c9204eb1cce398bc73ddf121&)
Test # 4 [https://cdn.discordapp.com/attachments/1096784581732093962/1167583755452563517/400mbps.png?ex=654ea81b&is=653c331b&hm=1109c5bf731010ab1c3faebd52e1c084e7a8b6eb350b3afc1d2a06ffa72126b9&](https://cdn.discordapp.com/attachments/1096784581732093962/1167583755452563517/400mbps.png?ex=654ea81b&is=653c331b&hm=1109c5bf731010ab1c3faebd52e1c084e7a8b6eb350b3afc1d2a06ffa72126b9&)

**Environment (please complete the following information):**
 - Node version: 1.27.0
 - OS: Mystberry
 - Your identity (if applicable): 0xcdbd3c67742921337abddcadb484f1f17faa6bd2

**Comment by etherunit** [comment]
@m1hc1u For some reasons, I am unable to see content in the screenshots (not opening). Can you please check?

**Comment by lusine-h** [comment]
I tried reproducing the issue but I couldn't see the exact results as my connection is slower than the user had. For the provider it is 54 download and 40 upload and for the consumer 15 download and 6 upload. I was able to test only with slower values, limited provider with 15 mb and while connection for the consumer the speed was 12 download and 5 upload. If the issue which user reported happens also for me I should see about 2 mb speed but I see normal speed for the limit I set.

**Comment by adinetech** [comment]
I conducted tests with varying bandwidth limits, and the results are as follows:

**No Bandwidth Limit:**
Test Latency: 47ms
Download and Upload Performance: 52.32 Mbps download, 135.31 Mbps upload.

**Bandwidth Limited to 15 Mb/s:**
Latency during test: Higher than baseline
Download and Upload Performance: 0.9 Mbps download, 1.69 Mbps upload.

**Bandwidth Limited to 101 Mb/s:**
Latency during test: Slightly higher than baseline
Download and Upload Performance: 11.04 Mbps download, 11.98 Mbps upload.

![image](https://github.com/mysteriumnetwork/node/assets/68943180/13ab2695-f4a9-4e22-b05e-38af51d183a7)
![image](https://github.com/mysteriumnetwork/node/assets/68943180/027a0c6f-ae83-4c6a-9b1f-f4c4e961f3d4)
![image](https://github.com/mysteriumnetwork/node/assets/68943180/2fddcb69-7e59-4979-bd1e-5ef849a24cbf)

**Comment by ZygintasBudrys** [comment]
Severity: Major
Priority: High

**Comment by tzununbekov** [comment]
@m1hc1u we've merged the fix and released the patched version of the node. Please update to the latest version ([1.29.7](https://github.com/mysteriumnetwork/node/releases/tag/1.29.7)) and let us know if it solves the issue or if the problem persists

**Comment by ZygintasBudrys** [comment]
@lusine-h please try to reproduce it

**Comment by adinetech** [comment]
Could this be tested by running a node on a datacenter?
