### ISSUE TITLE
Today's stats is not reflected in UI

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5914]
**Describe the bug**
If a data transfer session began on the previous day, the traffic from that session isn't accounted for in today's statistics. 

For instance, let's say a session started yesterday, and 58 GB of traffic was transferred. By this morning, 66 GB of traffic had already been processed, and by the evening, it was 70 GB. However, Mysterium doesn't recognize this traffic passing through the node today. Instead, it's only visible in the 7-day and 30-day statistics, counted toward the previous days' data. Consequently, users can't see today's statistics. 

**Expected behavior**
The traffic from the previous day is counted in today's stats.

**Additional context**
![Screen Shot 2023-11-08 at 07 44 25](https://github.com/mysteriumnetwork/node/assets/60128746/7ef0dee3-2b84-4966-a0ab-ae9e08dc5835)

**Comment by ZygintasBudrys** [comment]
@lusine-h will retest it
