### ISSUE TITLE
The history tab does not include some sessions

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5930]
**Describe the bug**
 I can see the sessions in active list while in progress. Post completion of session I am unable to find the session in history page.

**Expected behavior**
All sessions are displayed under History page.

**Screenshots**
![Screenshot 2023-11-26 at 8 37 23 PM](https://github.com/mysteriumnetwork/node/assets/60128746/13e6af64-b54a-4b9a-8810-441d87736697)
![Screenshot 2023-11-27 at 6 17 42 PM](https://github.com/mysteriumnetwork/node/assets/60128746/dc1bf049-bee8-420c-bccc-cbbc4473f156)
![Screenshot 2023-11-27 at 6 18 26 PM](https://github.com/mysteriumnetwork/node/assets/60128746/c081e714-8507-49ab-aafb-6a12ad3c0c3c)

Will add logs shortly.

**Comment by ZygintasBudrys** [comment]
Waiting for logs form @etherunit

**Comment by etherunit** [comment]
![Screen Shot 2023-11-28 at 10 16 49](https://github.com/mysteriumnetwork/node/assets/60128746/e8b53147-f71b-48b0-b3fb-b85f44f0d5c5)
![Screen Shot 2023-11-28 at 10 16 57](https://github.com/mysteriumnetwork/node/assets/60128746/067691bb-67eb-447c-8565-f2986768f008)
![Screen Shot 2023-11-28 at 10 17 03](https://github.com/mysteriumnetwork/node/assets/60128746/3c0f1f38-e4ed-4f92-830f-a40636c29503)

**Comment by etherunit** [comment]
Another one:
0x4a54f73cb3ab23a01600124c9d74c5058559cda1
"There are sessions that end but are not counted. I had a multi day session with 12 Myst which disappeared and was not counted"
"more recently a session from Germany of 9gb, was not counted. I have the impression that all sessions exceeding 1 GB are not counted".
As requested in our email exchange, I am sending you the log node

Logs: https://mystnodes.com/support/logs/2023-11-30-b85d0324-14f0-40c4-a59a-bfb9240a4501-mysterium-node.zip1974639615

**Comment by mdomasevicius** [comment]
@etherunit this is not node or nodeUI, in the end we get this data from prometheus. @soffokl explained that due to how it works we should expect some kind of error delta ~10%
