### ISSUE TITLE
Add ip2location.io/ip as primary or fallback IP address API

### ISSUE THREAD

**Issue by ip2location** [mysteriumnetwork/node#5943]
I would like to introduce https://ip2location.io/ip API to retrieve user's IP address.

**Comment by n10ty** [comment]
Make your PR :)

**Comment by ip2location** [comment]
@n10ty PR added. Thank you.

**Comment by soffokl** [comment]
@ip2location thank you, it's merged now.

**Comment by n10ty** [comment]
<img width="330" alt="Screenshot 2024-01-18 at 09 30 25" src="https://github.com/mysteriumnetwork/node/assets/2970001/cc7cc6b2-39f3-4036-8047-2293d5d7f3e7">
@soffokl FYI it returns IPv6 for me

**Comment by soffokl** [comment]
@n10ty  yeah, the same as many other we have in the list.
