### ISSUE TITLE
Earnings discrepancy 

### ISSUE THREAD

**Issue by Peter-SovietSquirrel** [mysteriumnetwork/node#5950]
Node ID: 0x57daba353514f004c86edf2e3892740ec4d98c4d

Mystnodes reports earnings of 582 MYST
![image](https://github.com/mysteriumnetwork/node/assets/60095913/cc0706a6-715e-464d-aad9-73144502190d)

Grafana reports earnings of 250MYST
![image](https://github.com/mysteriumnetwork/node/assets/60095913/fce575bd-9016-4e2e-a445-e4732975960e)

**Comment by PaJaSoft** [comment]
Hi all,
although original report doesn't contain much useful data, I see this as a very visible and important bug from UX perspective...

My own investigation was reported on Discord (support-forum -> "Missing MYST?"), so trying to track it as a serious issue in this place:

Original report with detailed information:
I see an issue with my Myst node after one week running permanently (and without any service or network outage) on the 500Mbps network.

Node identity: 0xdc99374f969a8acd0c9bb3c5c1137a0fce72967c
Configured settlement wallet: 0x1D805CDa6E21B62D3A51d045B6275A3CD8ad016f (the same like on https://mystnodes.com/me)

Based on information provided by Node UI of that node I can see right now:
Transactions -> Total settled: 0.00 MYST
Amount for next settlement: 1.579965 MYST

Sum from my History (only items with really significant MYST earned (0.1 MYST and more)) is roughly ~12 MYST earned already. However https://mystnodes.com/nodes is showing just 1.512922 MYST (well, a bit delayed, understand) but I can see in my [wallet](https://polygonscan.com/address/0x1D805CDa6E21B62D3A51d045B6275A3CD8ad016f#tokentxns) nothing related, just one old transaction (0xab4e9942a97c2dedc91ffc82b841c1e0654272004ec1d7f526dd2966031d4274) from the other Myst node where I tried manual transfer previously to check if everything is working as expected... 

Related history for above report and conclusion:

|1|Germany|1d 08:39:09|01/03/2024, 05:50:00|Mysterium VPN|0.67891 MYST|186.59 MiB|9a4718e6-9613-4f51-b390-4276b7fce99f|
|2|Germany|2d 13:54:32|27/02/2024, 18:40:00|B2B VPN and data transfer|0.13875 MYST|23.45 MiB|a03d4357-f3c2-41c4-8961-0858725e7909|
|3|Germany|2d 09:00:00|27/02/2024, 18:40:00|Mysterium VPN|1.11183 MYST|1.53 GiB|a47df2e7-788e-4d05-bb0b-345e1491d08f|
|4|Germany|2d 12:39:57|27/02/2024, 18:40:00|B2B Data Scraping|0.38849 MYST|23.44 MiB|0ab1a6a3-f5a7-4d00-87f8-7052717399c4|
|5|Germany|2d 12:39:57|27/02/2024, 18:40:00|B2B Data Scraping|0.38849 MYST|23.44 MiB|0ab1a6a3-f5a7-4d00-87f8-7052717399c4|
|6|Germany|1d 04:46:48|26/02/2024, 10:50:00|Mysterium VPN|8.11705 MYST|1.07 GiB|20c49b94-803d-4796-87e4-0158f1f5a9ca|
|7|Germany|12:02:32|25/02/2024, 22:10:00|Mysterium VPN|1.17857 MYST|684.53 MiB|dd070a89-cfb3-4240-9fe5-18ae7b370d8c|

Update::
Just discovered another discrepancy and starting to feel UI is really broken with reporting history and current sessions...
Ongoing session:
|Germany|19:26:19|B2B VPN and data transfer|0.251 MYST|2.75 GiB|39fe5397-9fcd-4c97-aacc-01ea7bc8f66d|

In History:
|Germany|19:14:09|03/03/2024, 00:50:00|B2B VPN and data transfer|2.00606 MYST|2.75 GiB|39fe5397-9fcd-4c97-aacc-01ea7bc8f66d|

As you can see the SessionID is the same and I bet I would never get 2+ MYST from this session into my account... (similarly like 8 MYST above - SessionID "20c49b94-803d-4796-87e4-0158f1f5a9ca"), even this is in history 'last 24 hours', my unsettled balance is only 1,86 MYST now and from that Node settlement had never occurred so far...

**Comment by ZygintasBudrys** [comment]
Severity: medium
Priority: medium

**Comment by progamer562** [comment]
agree myst is going down hill so fassssst

**Comment by informativeaimedia** [comment]
hi, i have the same problem... i've only got 8 myst when my earning is already 16 myst.. only had it open less than a week through..

**Comment by ZygintasBudrys** [comment]
Not relevant after rework
