### ISSUE TITLE
Common iptables service manager

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#597]
We will need to move all iptables code into separate service common to any service using iptables. This will be needed to resolve possible rule clash'es. 

AC:
 - we have common iptables service for any service using iptables
 - two and more services are able to work without disrupting each other

**Comment by soffokl** [comment]
Looks like this issue resolved in the https://github.com/mysteriumnetwork/node/issues/674 and https://github.com/mysteriumnetwork/node/issues/673. 
Closing it.
