### ISSUE TITLE
100% time Offline, 100% time Idle reported in UI

### ISSUE THREAD

**Issue by PaJaSoft** [mysteriumnetwork/node#6000]
Using Node version: 1.29.8 and Node UI version: 2.15.0 (Windows Native installation), but probably it isn't only in this release.

UI reports in Statistics (Last 24 hours) 100% Ofline and 100% Idle although connections have been flowing without any issue and there was no service or network outage on that node and 500Mbps network for over one week.

In contrary Dashboard reports 'Online -> green point', ' Quality -> green point' but Myst cli:
- healthcheck -> fine
- nat -> Monitoring Status: "success"
- status -> "Status:NotConnected"

all of the time...:-(

**Comment by ZygintasBudrys** [comment]
Severity: low
Priority: low

**Comment by nightcrawlerbr** [comment]
I have the same issue. Node works fine, connections flow, but UI reports 100% offline and 100% iddle. Last 3 versions. Node 1.29.9.   UI 2.15.1. The same happens for last 3 versions of Node (didn't check UI, watchtower upgraded automatically). Running on Docker (Alpine host). No outages and still every report is 100% offline and iddle.

**Comment by ZygintasBudrys** [comment]
Will be solved with another ticket:
https://github.com/mysteriumnetwork/mystnodes/issues/176/
