### ISSUE TITLE
Node UI should report expired session properly

### ISSUE THREAD

**Issue by PaJaSoft** [mysteriumnetwork/node#6001]
When a session expired, Node UI reported weird issue (a box at right bottom) or just using/visualize stale data. In such a situation there should be a proper handling which should lead to report about situation and ask user for a session refreshing action (-> a new login). Current behavior is really confusing...

**Comment by ZygintasBudrys** [comment]
Severity: low
Priority: low

@lusine-h try to reproduce

**Comment by lusine-h** [comment]
When the token is expired and I do refresh it shows Node UI Welcome screen for login and there isn't reported issue at right corner.

**Comment by PaJaSoft** [comment]
That's another case - if you have an open tab with Node UI in web browser and do F5/Ctrl-F5 (aka Refresh) than it is taken properly. However if you have an open tab with Node UI, session somehow expires, you can still navigate through pages (e.g. Dashboard -> History, Transaction - Settle now etc.) and there is no any sign that displayed data are staled. Sometimes something gets broken and you can see red box in right bottom corner, but not always, so you can't easy discover your session is over and you need to re-login.

**Comment by ZygintasBudrys** [comment]
Hello, we will be changing the NodeUI in the upcoming quarters that would solve the issue.

**Comment by lusine-h** [comment]
- Adjusted token expiry date using the DevTools application section
- Navigated within the webpage after modifying the token expiry
- Token expired during navigation
- Clicked around the page, resulting in an error message `Request failed with status code 401 (path="node/monitoring-status")`
- Continued clicking led to a white empty screen display
