### ISSUE TITLE
Often "Failed to sign metrics event error"

### ISSUE THREAD

**Issue by PaJaSoft** [mysteriumnetwork/node#6002]
I can see a quite often in the LOG reported:
> 2024-02-23T13:28:59.326` ERR ../../core/quality/mysterium_morqa.go:212      > Failed to sign metrics event error="failed to sign metrics event: authentication needed: password or unlock"

In support-forum I was advised this is actually not an issue, so it would be swallowed in the code or not reported in this form, it's confusing from UX...

**Comment by ZygintasBudrys** [comment]
Severity: low
Priority: low

**Comment by PaJaSoft** [comment]
The issue isn't fixed yet, I guess it would have a value to track it ...
