### ISSUE TITLE
Release 1.29.11 not uploaded to docker hub

### ISSUE THREAD

**Issue by shawaj** [mysteriumnetwork/node#6012]
Release 1.29.11 not uploaded to docker hub

**Comment by PaJaSoft** [comment]
I'm pretty sure I was seeing it on GH last night as(viewed on my cell phone, so impractical) a ~2 days old stuff (common assets set) but it disappeared for now:-0.

So now 1.29.9 is the latest... weird game around:-(

**Comment by shawaj** [comment]
> I'm pretty sure I was seeing it on GH last night (viewed on my cell phone, so impractical) as a ~2 days old stuff (common assets set) but it disappeared for now:-0.
> 
> So now 1.29.9 is the latest... weird game around:-(

Oh yeah very weird. It was definitely there as I got a notification about it!

**Comment by tzununbekov** [comment]
Hi folks, you are right - we had an issue with the CI release workflow that caused tags to have missing artifacts. The CI is fixed now, and the proper release is [ready](https://github.com/mysteriumnetwork/node/releases/tag/1.29.10). We'll take better care of tag consistency in the future. Thanks for reporting the issue. Feel free to re-open if there is more to the topic.

**Comment by shawaj** [comment]
Thanks @tzununbekov
