### ISSUE TITLE
Monitoring failed node cant connect anymore

### ISSUE THREAD

**Issue by Lacc1986** [mysteriumnetwork/node#6024]
Just set up a new node on my VPS yesterday had 3 connections with 3 hosts since it can't connect back since and monitoring fails. I had this issue last November with my node on my local Linux machine tried everything the node did not sync e and monitoring failed. Anybody can explain what has been happening since November? Now my old nodes that were not updated working flawlessly on the VPS but those that were upgraded to 1.29.8 or newer just stopped working. Noting works and cannot setup a new node that is working anymore.

**Comment by etherunit** [comment]
@Lacc1986 Could you write your node identity address?
