### ISSUE TITLE
MTU

### ISSUE THREAD

**Issue by Scotty714** [mysteriumnetwork/node#6037]
The MTU of my network is 1472. Wireguard sets the default MTU of 1420. As far as i am aware the overhead for Wireguard is 60 bits for IPv4, so i need to change the default to 1412.  I can do this manually - but every new connection defaults to 1420.
Is there a variable i could add into the docker config to change this? 

many thanks

Environment:
 - Node version: 1.29.18
 - OS: Unraid - Docker

**Comment by Zensey** [comment]
@Scotty714 
Do you mean setting MTU for all myst* interfaces, including myst0 ?
 
> `ip link set dev myst0 mtu 1420`

**Comment by Scotty714** [comment]
yeah - i can do that but then any new connections created default to 1420

**Comment by Zensey** [comment]
@Scotty714 

I've added a command line argument for setting Wireguard MTU:
--wireguard.mtu=1400

Example of use:
myst  --wireguard.mtu=1400 service

Its available in the latest build
docker pull mysteriumnetwork/myst-snapshots:1.29.19-1snapshot-20240426T1308-ee113ab7-alpine

**Comment by Scotty714** [comment]
Perfect - great work mate!
