### ISSUE TITLE
Monitoring failed for several days now

### ISSUE THREAD

**Issue by techroy23** [mysteriumnetwork/node#6052]
**Screenshots**
![image](https://github.com/mysteriumnetwork/node/assets/53241974/2b8c606b-85ed-4059-a8a8-c0566ae8ac2a)
![image](https://github.com/mysteriumnetwork/node/assets/53241974/a515e78b-01e7-436f-b37a-daf937b04c45)

**Environment (please complete the following information):**
 - Node version: 1.29.21
 - OS: Debian GNU/Linux 12 (bookworm) x86_64
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): mysteriumnetwork/myst:latest    121422a1f0ba
 - Your identity (if applicable): 0xb30a0a524b0af74be3712f6fdbf58af05b2bf020
 - Payment (top-op) reference (if applicable): https://polygonscan.com/tx/0xe3b446f8094701ff834babb60a55d011d3c55335adfd860a8c08dee78dd3db37

**Additional context**
I have restarted my server multiple times now. made sure the DNS is not blocking anything.

**Comment by techroy23** [comment]
Your identity (if applicable): 0xa2411e2547a4cc61953b2d19b0adc63f2d6b9ad0

same monitoring failed still.

**Comment by DonVitja** [comment]
Same for me. Is there no solution for this?

**Comment by DonVitja** [comment]
I fixed the Problem.....

1. Have your internet provider unlock the ports (in Germany they are closed by default ((Vodafone)))
2. For the modem, make sure that the EXTERNAL port forwarding is at UDP 66000-66100, the INTERNAL (LOCAL) must remain at UDP 56000-56100.
3. Restart all nodes, restart modem

**Comment by techroy23** [comment]
> I fixed the Problem.....
> 
> 1. Have your internet provider unlock the ports (in Germany they are closed by default ((Vodafone)))
> 2. For the modem, make sure that the EXTERNAL port forwarding is at UDP 66000-66100, the INTERNAL (LOCAL) must remain at UDP 56000-56100.
> 3. Restart all nodes, restart modem

err all ports are open already and its running on my vps not local machine
