### ISSUE TITLE
Observer Hermeses Call Fail (Failed to get Hermes URL from Blockchain) error in log

### ISSUE THREAD

**Issue by theVasilis** [mysteriumnetwork/node#6057]
**Describe the bug**
The node won't start because in every restart attempt the process fails with the below error message:

`observer Hermeses call failed, using fallback known hermeses...`

and then on the next line of the log:

`failed to get Hermes URL from blockchain, using fallback...`

further down:

`Failed to execute command:  error="could not get Hermes URL:....` 
`Main process exited, code=exited, status=1/FAILURE`
`Failed with result exit-code`

and then `mysterium-node-service` restarts and attempts the connection again. 

The service is running fine `systemctl status = ACTIVE, ENABLED`

One thing I've noticed by checking the files is that the file `config-mainet.toml` is empty (or I can't read it with `cat` or `nano`). I believe there should be some configuration data there and that might be the reason of this error.

**To Reproduce**

**Expected behavior**
I expected Myst Node to complete the online connection and bring me to the NODE UI or at least show me a success message with a NODE ID. (I'm running SSH in terminal mode.)

**Screenshots**
![Screenshot 2024-06-21 22 56 17](https://github.com/mysteriumnetwork/node/assets/15715431/5378efb5-fea1-4ed2-b0d4-8cbfed98edf4)

**Environment (please complete the following information):**
 - Node version: Latest one (just installed it 12 hours ago)
 - OS: Debian 12 Bookworm on a VPS
 - CPU: Low MHZ entry-level VPS (but running ATOR node perfectly)
 - RAM: 1GB
 - Desktop app version (if applicable): Terminal
 - Docker (if applicable): N/A
 - Your identity (if applicable): N/A (didn't manage to reach at this point) [from the back office zeXB4nlubbFkq8954Th1uc5pG5wY4qJuYw5Ocqs6]
 - Payment (top-op) reference (if applicable): N/A

**Additional context**
After using the script to install the node, the service was stale because the firewall was blocking all connections. I reviewed the logs and identified the ports Mysterium Node is using, so I proceeded and whitelisted them. Then restarted the service and since then it is ACTIVE and ENABLED and it automatically restarts for 5 times.

**Comment by theVasilis** [comment]
Just to add some updates.

I managed to claim my node on the dashboard and I can visit my node's public URL.

However it appears to be Offline with Failing Monitoring, Quality Low and NAT Open indications.

Here's the node's ID: `0x0b873d7c7f673a704e8a858707e1ca33a758a4bc`

**Comment by Teense** [comment]
I think I have same issue with my RPi. How did you completely solved that problem?

**Comment by theVasilis** [comment]
> I think I have same issue with my RPi. How did you completely solved that problem?

@Teense my Debian installation didn't have any hostname added under `/hosts.conf` file. It was completely empty, so I added the default Google and CloudFlare hostnames (8.8.8.8, 8.8.4.4, 1.1.1.1) and then the node appeared to be connected and operating online.

Now i'm not sure that is the solution, because I have the Debian installation set to auto updates, so it might be some library receiving updates overnight.

I hope that helps.
