### ISSUE TITLE
tun removal fails on node shutdown

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#637]
On provider side, when node is stopped, we get: 

`Dec 19 10:39:51 lxc1-rackray myst[6703]: 2018-12-19T08:39:51.822468743 [Warn] Failed to remove tun device: [sudo ip tuntap delete dev tun0 mode tun] Returned exit error: exit status 1 Cmd output: ioctl(TUNSETIFF): Device or resource busy`

Looks like openvpn is not yet killed and tun device is not released yet. Attempt to remove such device gives above error.

**Comment by soffokl** [comment]
It's backported to `0.5-rc`.
