### ISSUE TITLE
SPIKE: measure provider access speed.

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#638]
In order to gather information for consumer to evaluate provider's access we could choose from these options to proceed: 
  - pluggable service to measure access speed from consumer to provider
  - pluggable service to measure access speed between MORQA agent and provider
  - simple ICMP ping option

Client could get some statistics either from MORQA or gather and cache such statistics right after it connects to node.

**Comment by chompomonim** [comment]
This is already solved by monitoring agent and quality oracle.
