### ISSUE TITLE
e2e compatibility matrix tests

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#641]
In order to make migration between versions more smooth we need to make sure that no combination of (provider / consumer / mobile endpoint contract) breaks.

Currently, more and more time is being spent thinking about and fixing compatibility issues. We need to be sure that each fix / feature we merge does not brake anything. 

For startup lets make sure that at least one version before  ( 0.5 should be compatible with 0.6 ) is cross-compatible with each other element.

We should start having { provider | consumer | mobile contract }  e2e test matrix. Let make it step by step. 

This might end up being epic, but we need to do it.

**Comment by vkuznecovas** [comment]
We already have this.
