### ISSUE TITLE
The new docker server background log reports an error

### ISSUE THREAD

**Issue by ymai6** [mysteriumnetwork/node#668]
The new docker server background log reports an error. The client is not connected. as follows:

2019-01-16T03:24:20.387590746 [Trace] [openvpn-process] Stdout: Wed Jan 16 03:24:20 2019 tls-crypt unwrap error: packet authentication failed
2019-01-16T03:24:20.388514538 [Trace] [openvpn-process] Stdout: Wed Jan 16 03:24:20 2019 TLS Error: tls-crypt unwrapping failed from [AF_INET]5.113.218.75:6784

**Comment by zolia** [comment]
Hello, 

could you please provide more detailed log output from provider and consumer? These messages most likely are not the root cause of the problem.

**Comment by ymai6** [comment]
How can I export more detailed logs to you?

取得 iOS 版 Outlook<https://aka.ms/o0ukef>

________________________________
寄件者: zolia <notifications@github.com>
寄件日期: 星期三, 1月 16, 2019 15:45
收件者: mysteriumnetwork/node
副本: ymai6; Author
主旨: Re: [mysteriumnetwork/node] The new docker server background log reports an error (#668)


Hello,

could you please provide more detailed log output from provider and consumer? These messages most likely are not the root cause of the problem.

**Comment by ymai6** [comment]
> Hello,
> 
> could you please provide more detailed log output from provider and consumer? These messages most likely are not the root cause of the problem.

Maybe it's just that my client is not connected, I see other connections in the panel.Thanks

**Comment by zolia** [comment]
Hello, 

From log, it looks like client IS connected. TLS encryption failing, but it still might be not the root issue. 
What client are you using? Your mobile, desktop or cli application? We would like to inspect logs three too. 
It still might be the issue of iptables rules on a docker.

Thats output of 'iptables -L -n  -t nat'  on that docker host?

Have you tried launching wireguard service? Does it work?

**Comment by zolia** [comment]
no update from user.
