### ISSUE TITLE
Where is your website's repo?

### ISSUE THREAD

**Issue by dandv** [mysteriumnetwork/node#7]
There are some run-on sentences I wanted to fix.

**Comment by Waldz** [comment]
@dandv currently we not ready for this, will do shared content just after ICO.
Could you just paste wanted update here to ticket?

**Comment by dandv** [comment]
In the meantime I've read the entire page and there are many mistakes. I'd be happy to submit a PR against some HTML, but copy/pasting each English wording problem along with the suggested is unfortunately too much work.

**Comment by Dracozny** [comment]
Node Registration is broken? https://mvp.mysterium.network/bounty_register is not found.
