### ISSUE TITLE
Metrics service

### ISSUE THREAD

**Issue by donce** [mysteriumnetwork/node#701]
We shouldn't send events to `ElasticSearch` directly:

* If we have open ElasticSearch to everyone, it can be easily overloaded, no matter how many nodes we have;
* If we will need to replace ElasticSearch with some other solution one day, we will need to update every client for that;
* Any one can fake/compromise these stats.

- Create new service at `metrics.mysterium.network` with a single endpoint to create metrics.
- Use this service in `mysterium-vpn`, `mysterium-vpn-mobile` and `node` instead of accessing ElasticSearch directly.
- Hide ElasticSearch
- It should have some protection from overloading - i.e. IP throttling, but this might be implemented later on.

**Comment by zolia** [comment]
metrics.mysterium.network service superseded by quality.mysterium.network
