### ISSUE TITLE
Remove old promise package

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#708]
With the current implementation, the old promise package seems to be redudant. Remove it.

https://github.com/mysteriumnetwork/node/tree/master/core/promise

Could also consider moving the current implementation to the core package.

**Comment by zolia** [comment]
outdated by new payment model

**Comment by vkuznecovas** [comment]
not outdated at all - we're still using it, so do keep this open.

**Comment by zolia** [comment]
We can look at this task as a subtask to remove old payment model which is still supported.
