### ISSUE TITLE
Payment alignment mechanism

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#709]
The consumer and provider always need to be aligned in their view of the current session and its balance. Due to time differences and possible shifts, we'll need to keep track of separate balances and try see if they outgrow a given threshold. If that occurs, the consumer or the provider will end the session. The alignment should occur both on provider and consumer, since neither of the parties can trust each other. 

This is probably going to be the meat of the payments.

**Comment by zolia** [comment]
outdated by new payment model
