### ISSUE TITLE
Re-evaluate session creation dialog

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#720]
With the current changes, the session creation dialog becomes a bit cumbersome and heavy. Might want to consider splitting the payment related details to an extra communication step, maybe called `payment-agreement` where the consumer and provider would first agree on payment related details and then initiate the real session creation.

**Comment by zolia** [comment]
@vkuznecovas can you comment on this, is it still actual?

**Comment by chompomonim** [comment]
@vkuznecovas I'm closing this issue as it is most probably not relevant anymore.
