### ISSUE TITLE
set-up port 443 instead 1194

### ISSUE THREAD

**Issue by malikshi** [mysteriumnetwork/node#721]
server spec
OpenVZ 7
Ubuntu 16.04
2GB RAM

there my docker config
docker run --cap-add NET_ADMIN --net host --publish "443:443" --name mysterium-node -d mysteriumnetwork/mysterium-node --agreed-terms-and-conditions
![screenshot_707](https://user-images.githubusercontent.com/9080737/52434456-ee285500-2b41-11e9-8178-a8a715786929.png)
![screenshot_709](https://user-images.githubusercontent.com/9080737/52434490-04ceac00-2b42-11e9-8061-fd504f007556.png)
and still using port 1194 not 443 ?

**Comment by soffokl** [comment]
@malikshi `--publish "443:443"` is a docker argument, and it does nothing when `--net host` is used. 

And first of all, your command to start service looks a bit outdated. Please consider to take a look on our documentation page: http://docs.mysterium.network/en/latest/

If you want to change port for listening, you will need to use `--openvpn.port` argument for service subcommand. 

Something like this:

`docker run --cap-add NET_ADMIN --net host --name myst -d mysteriumnetwork/myst service --openvpn.port=443 --agreed-terms-and-conditions`

**Comment by malikshi** [comment]
![screenshot_710](https://user-images.githubusercontent.com/9080737/52462998-d388c700-2ba7-11e9-8119-e842771b4dd3.png)
now like that, showing error in iptables

**Comment by soffokl** [comment]
It looks like a warning, it should not prevent normal work. 
Do you have any problem causing by these messages?

**Comment by malikshi** [comment]
> It looks like a warning, it should not prevent normal work.
> Do you have any problem causing by these messages?

yeah, im try to connect but no luck, its shown log session only in log, and like that pic in my windows.
![screenshot_711](https://user-images.githubusercontent.com/9080737/52463851-2021d180-2bab-11e9-8f4a-8f652e52f250.png)

**Comment by soffokl** [comment]
Please take a look on http://docs.mysterium.network/en/latest/user-guide/troubleshooting/#in-logs-i-see-clients-attempts-but-it-does-not-fully-connect
> It also might be that default firewall forward policy is set to `DROP`.

**Comment by malikshi** [comment]
@soffokl https://hub.docker.com/r/mysteriumnetwork/mysterium-node its working using old one, but not working on this https://hub.docker.com/r/mysteriumnetwork/myst ??

**Comment by soffokl** [comment]
hm, found a check where we are preventing using port less than 1024
https://github.com/mysteriumnetwork/node/blob/master/services/openvpn/config_validator.go#L74
@Waldz @zolia do we really need this check?

**Comment by malikshi** [comment]
I have OpenVPN services, mostly using port 80/443/53.

**Comment by zolia** [comment]
Idea of using port above 1023 is that you could run service in unprivileged environment. Anything run with < 1024 has to have root permissions. 
Of cause we can relax from this requirement if there is a real use-case. 
We may leave just a warning not an actual startup termination.

**Comment by malikshi** [comment]
> Idea of using a port above 1023 is that you could run service in unprivileged environment. Anything run with < 1024 has to have root permissions.
> Of cause we can relax from this requirement if there is a real use-case.
> We may leave just a warning not an actual startup termination.

I know what you mean about that idea. now I'm using a port above >1024 because of it. and using low digit port for other services, but it will great if allowing port <1024. I have tried under 1024 won't run well and stuck in log session.

**Comment by zolia** [comment]
Services now can be specified the exact port to bind to. Consider it solves this issue now.
