### ISSUE TITLE
Replace wireguard logging with unified one

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#725]
At that moment wireguard use some internal logging to STDOUT, that is formatted differently then unified, which we are using in the node.
![image](https://user-images.githubusercontent.com/8612618/52559432-739c5580-2e1f-11e9-90cc-f85407f9d306.png)

We need to find a way to make it look as a single logging.

**Comment by chompomonim** [comment]
Is this issue still relevant?

**Comment by soffokl** [comment]
This was resolved.
