### ISSUE TITLE
Move dtos from github.com/mysteriumnetwork/node/services/openvpn/discovery/dtopackage 

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/node#761]
We're currently using github.com/mysteriumnetwork/node/services/openvpn/discovery/dto in quite a few places. Need to look into why, and move the required pieces accordingly.

**Comment by Waldz** [comment]
https://github.com/mysteriumnetwork/node/pull/748/files#r261474153

**Comment by chompomonim** [comment]
@vkuznecovas is this still relevant?

**Comment by zolia** [comment]
Looked at code, does not look like relevant anymore. Closing.
