### ISSUE TITLE
Service endpoints should return service parameters in `serviceInfo` DTOs

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#764]
- We are going to need to know at least `serviceType` (wireguard/openvpn/etc) -  https://github.com/mysteriumnetwork/node/pull/759#discussion_r261571136
- If we are removing `Options` from the service info, what should be the way to figure out what options were used for starting a service? - https://github.com/mysteriumnetwork/node/pull/759#discussion_r261476263
- Endpoint `GET /services` should be extended
- Endpoint `GET /services/{id}` should be extended

**Comment by soffokl** [comment]
> * We are going to need to know at least `serviceType` (wireguard/openvpn/etc) -  [#759 (comment)](https://github.com/mysteriumnetwork/node/pull/759#discussion_r261571136)

`serviceType` exists in the `Proposal`. I don't that we need to duplicate it on the top level.
