### ISSUE TITLE
Node crashes when I stop it with cmd+c

### ISSUE THREAD

**Issue by Germuxas** [mysteriumnetwork/node#777]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x459cf26]

goroutine 1 [running]:
github.com/mysteriumnetwork/node/services/openvpn/service.(*Manager).Stop(0xc0003590e0, 0xc0000df868, 0x1)
	/ext-go/1/src/github.com/mysteriumnetwork/node/services/openvpn/service/manager.go:98 +0x26
github.com/mysteriumnetwork/node/core/service.(*Pool).Stop(0xc0000a4080, 0xc00002a270, 0x24, 0x4a9ea00, 0xc000055010)
	/ext-go/1/src/github.com/mysteriumnetwork/node/core/service/pool.go:75 +0x16d
github.com/mysteriumnetwork/node/core/service.(*Pool).StopAll(0xc0000a4080, 0x10, 0xc0000df9a0)
	/ext-go/1/src/github.com/mysteriumnetwork/node/core/service/pool.go:86 +0xbb
github.com/mysteriumnetwork/node/core/service.(*Manager).Kill(0xc000097800, 0x4a096c0, 0xc0000dfa18)
	/ext-go/1/src/github.com/mysteriumnetwork/node/core/service/manager.go:143 +0x2f
github.com/mysteriumnetwork/node/cmd.(*Dependencies).Shutdown(0xc000001800, 0x0, 0x0)
	/ext-go/1/src/github.com/mysteriumnetwork/node/cmd/di.go:192 +0x375
github.com/mysteriumnetwork/node/cmd/commands/daemon.NewCommand.func2(0xc0001c2420, 0x47cb514, 0x19)
	/ext-go/1/src/github.com/mysteriumnetwork/node/cmd/commands/daemon/command.go:45 +0x2a
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli.Command.Run.func1(0xc0000dfd48, 0xc0001c2420, 0xc0000dfe78)
	/ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/command.go:185 +0x3b
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli.Command.Run(0x47bb8d7, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x47d27fb, 0x22, 0x0, ...)
	/ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/command.go:215 +0x9b0
github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli.(*App).Run(0xc000212000, 0xc0000a8000, 0x2, 0x2, 0x0, 0x0)
	/ext-go/1/src/github.com/mysteriumnetwork/node/vendor/github.com/urfave/cli/app.go:255 +0x687
main.main()
	/ext-go/1/src/github.com/mysteriumnetwork/node/cmd/mysterium_node/mysterium_node.go:54 +0xcd

**Comment by soffokl** [comment]
@Germuxas it will be good to know which version of the node was running to get this error. 

If it's was just a `master` branch, it's probably easy to fix. 
https://github.com/mysteriumnetwork/node/blob/master/services/openvpn/service/manager.go#L98
