### ISSUE TITLE
After starting service, service and myst cannot be stopped

### ISSUE THREAD

**Issue by donce** [mysteriumnetwork/node#779]
`/services` returns
```
[
    {
        "id": "aac24872-58d9-48d6-b25b-97ce2ceb90a6",
        ....
        "status": "NotRunning",
    }
]
```

Invoking `DELETE http://localhost:4050/services/aac24872-58d9-48d6-b25b-97ce2ceb90a6` does not respond, connection just hangs.

Invoking `POST http://localhost:4050/stop` executes, but node does not stop.

**Comment by zolia** [comment]
fixed

**Comment by tadaskay** [comment]
For the future reference, it would be useful to link the actual fix.
