### ISSUE TITLE
When consumer disconnects and tries to connect back, handshake doesn't go through

### ISSUE THREAD

**Issue by Germuxas** [mysteriumnetwork/node#783]
INFO: [userspace-wg]2019/03/07 14:30:40 Interface set up
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: handshake worker - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: decryption worker - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: encryption worker - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: TUN reader - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: receive incoming IPv6 - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: receive incoming IPv4 - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 UDP bind has been updated
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: receive incoming IPv4 - stopped
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: receive incoming IPv6 - stopped
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: receive incoming IPv6 - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 Routine: receive incoming IPv4 - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 UDP bind has been updated
DEBUG: [userspace-wg]2019/03/07 14:30:40 peer(Qaqb…7E2Y) - Starting...
DEBUG: [userspace-wg]2019/03/07 14:30:40 peer(Qaqb…7E2Y) - Routine: sequential receiver - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 peer(Qaqb…7E2Y) - Routine: nonce worker - started
DEBUG: [userspace-wg]2019/03/07 14:30:40 peer(Qaqb…7E2Y) - Routine: sequential sender - started
2019-03-07T12:30:40.432515 [Info] [nat] NAT rule from '10.8.0.0/24' to IP: 10.0.88.201 added
2019-03-07T12:30:40.445411 [Info] [nat] NAT rule from '10.182.0.2/24' to IP: 10.0.88.201 added
2019-03-07T12:30:40.445511 [Trace] [promise-storage] could not load promise info, defaulting to zero payment infonot found
2019-03-07T12:30:40.445752 [Debug] [NATS.Receiver] Request '0x643d41b3933d17c73f24f6aea20262cb47f7cc59.wireguard.0xea18939813aae55b02e28fefea92f011ec04cc0e.session-create' response: {"payload":{"success":true,"message":"","session":{"id":"ff2797d7-12c7-4732-9cd3-9714ec1bc174","config":{"provider":{"public_key":"8eT6fgTaZTRoh7s24ER/Zn1SwzrZrsr4Mc/+esZ+Fx8=","endpoint":"88.119.191.24:52820"},"consumer":{"private_key":"","ip_address":"10.182.0.2/24","connect_delay":2000}}},"paymentInfo":{"lastPromise":{"sequenceID":0,"amount":0},"freeCredit":0}},"signature":"/JRy1RKTOecOqGHVgxU6EvFDczPhLt2HuJK7YtWXiRAC8hBN6m9Kc780uVC+NWbQWe2nNPp6wVVzJIpcpwXd9gA="}
2019-03-07T12:30:42.498864 [Debug] [port mapping] , Couldn't add port mapping for port 52820: goupnp: SOAP request got HTTP 500 Internal Server Error, retrying with permanent lease
2019-03-07T12:30:42.511621 [Info] [port mapping] Mapped network port:52820
DEBUG: [userspace-wg]2019/03/07 14:31:10 peer(Qaqb…7E2Y) - Sending handshake initiation
ERROR: [userspace-wg]2019/03/07 14:31:10 peer(Qaqb…7E2Y) - Failed to send handshake initiation no known endpoint for peer
DEBUG: [userspace-wg]2019/03/07 14:31:10 peer(Qaqb…7E2Y) - Awaiting keypair
DEBUG: [userspace-wg]2019/03/07 14:31:15 peer(Qaqb…7E2Y): Handshake did not complete after 5 seconds, retrying (try 2)
DEBUG: [userspace-wg]2019/03/07 14:31:15 peer(Qaqb…7E2Y) - Sending handshake initiation
ERROR: [userspace-wg]2019/03/07 14:31:15 peer(Qaqb…7E2Y) - Failed to send handshake initiation no known endpoint for peer
DEBUG: [userspace-wg]2019/03/07 14:31:20 peer(Qaqb…7E2Y): Handshake did not complete after 5 seconds, retrying (try 3)
DEBUG: [userspace-wg]2019/03/07 14:31:20 peer(Qaqb…7E2Y) - Sending handshake initiation
ERROR: [userspace-wg]2019/03/07 14:31:20 peer(Qaqb…7E2Y) - Failed to send handshake initiation no known endpoint for peer
DEBUG: [userspace-wg]2019/03/07 14:31:26 peer(Qaqb…7E2Y): Handshake did not complete after 5 seconds, retrying (try 4)
DEBUG: [userspace-wg]2019/03/07 14:31:26 peer(Qaqb…7E2Y) - Sending handshake initiation

When I start a node, first connection is perfect to openvpn or wireguard. Then I disconnect the node from my phone, and try to connect back to the same node. Disconnected first 5 times in a period of 1 second time, then it tries to load, but shows this handshake log.

**Comment by Waldz** [comment]
@soffokl:
About the existing problem, I’m lacking details. So I can just guess that the problem related to NAT port mapping.
If you are running several providers in the same office, it will not be possible to map them at the same time to the same port. So there could be conflicts.
@Germantas @Mindaugas if you can update me on details how it was tested, it will really help to investigate the problem.
What version of node are you running?
What OS you are using to run a node as provider?
What is the network that you are using?

The same for consumer is it android app, is it wifi network or LTE or something?

Do you have several nodes running in the same network at the same time?

And it will be good to see full logs from both consumer and provider.

**Comment by Waldz** [comment]
> If you are running several providers in the same office, it will not be possible to map them at the same time to the same port. So there could be conflicts.
Yes, we run several nodes on the same office network

> What version of node are you running?
I thought them to always retest latest `0.0.0-dev` from master 

What OS you are using to run a node as provider?
> OSX and later they will experiment on Windows laptop

The same for consumer is it android app, is it wifi network or LTE or something?
> Sometimes they try to consuming from same office network, but I thought them to consume from mobile network, so than it would be different networks ATM

Do you have several nodes running in the same network at the same time?
> Yes again

**Comment by soffokl** [comment]
First of all, at that moment it's impossible to support several providers with a NAT port mapping. 
If the first node asked to do a port map for wireguard for 52820 port, another instance cannot use the same port. 
It was planned to use a random public port for every port map, but it's not implemented yet.
https://github.com/mysteriumnetwork/node/issues/770

**Comment by soffokl** [comment]
I'd recommend doing manual port mapping, to make sure that the problem really related to the described case.
