### ISSUE TITLE
As a user I want to be able to see number of ongoing sessions

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#790]
*As a* Provider
*In order to* understand is my machine is being utilised
*I want* to be able to see number of ongoing sessions

AC:
- See text "Connected sessions: 0"
- When Consumer connects, text should change to "Connected sessions: 1"
- When Consumer disconnects, text should change to "Connected sessions: 0"

Tasks:
- [x] Implement Tequilapi endpoint - #789
- [x] Implement Tequilapi client - https://github.com/mysteriumnetwork/js-tequilapi/pull/45
- [ ] Show session number in GUI - ?

**Comment by mjankauskas** [comment]
[ ] - Show active user count
[ ] - Add external link to session dashboard

**Comment by mjankauskas** [comment]
This task is in progress for 4 days already and blocker is merged 4 days ago. Any updates?
@Waldz

**Comment by Waldz** [comment]
Wrong repo for ticket, moving data to ticket https://github.com/mysteriumnetwork/mysterium-vpn/issues/451
