### ISSUE TITLE
Payments hi-lvl solution architecture

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#796]
Find and describe how payment contracts will be used from MN applications. 

Decided weather:
   - node should expose endpoinds needed to interact with payment contracts
   - or application directly should interact with blockchain

Depict high level diagram how various payment functions will interact between MN components.
Describe geen path, edge-cases and possible abuse scenarios.

Pros for everything in a node: 
   - fixed contract for API users
   - simplified and clear use for 3rd party developers
   
Pros for direct communication with blockchain: 
   - decoupled from a node, all required interaction can be direct - better sense of distributed nature
   - we could have separate JS library to simplify interaction with MN payment contracts

P2P Payments Solution State Flow:
![zenuml (1).png](https://images.zenhubusercontent.com/5af1cafb4b5806bc2bd24f36/510abf22-37ed-47c4-b12b-db46d7d73178)

**Comment by zolia** [comment]
Basic flow for identity registration:
 - User generates private key
 - User generates identity (internally public key) from private key
 - Generate Top-up address from generated identity (need to know Registry contract address) (keccak("0xff++msg.registry_contract_address++identityHash++keccak(byteCode)"))
Top-up address will be Users smart-contract after transaction is performed.
 - Send MYST (Stake + transaction fee + Top-up amount) to Top-up address

 - Transactor performs registration transaction for the user 
 - To transactor: register(identity, Users_signature) -> deploys user SC
 - Transactor: userContract.settlePromise(Users_signature)
 - Users_signature is a promise to pay a fee to transactor.

promise: 
to, amount, fee, extradatahash
to = transactorAddress
amount = amount of tokens
fee = 0
extraData = 0

 - Provider  and consumer will be the same address 
 - Registry Owner adjusts min. staking / registration parameters according to market


Possible node endpoints to support new SC:

// Communicate with Transactioner to register identity
POST /identities/{id}/registration
subsequent POST calls should return an error "identity already created".

**Comment by AndriusMyst** [comment]
Payments research objects:
https://connext.network/
https://github.com/ConnextProject/docs/wiki/Connext-Overview-and-FAQ

**Comment by mjankauskas** [comment]
@zolia can you add this to Payments project?

**Comment by chompomonim** [comment]
I do believe that this task is already resolved.
