### ISSUE TITLE
Resource exhaustion on WG nodes

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#809]
Need to investigate major resource exhaustion issues on WG node. 
Describe possible solutions.

**Comment by soffokl** [comment]
I have discovered a problem when we are overallocating IP subnets for wireguard after latest changes. 
Going to fix it in the scope of this issue.

**Comment by soffokl** [comment]
Overallocating IP subnets problem will be resolved by the https://github.com/mysteriumnetwork/node/pull/846
