### ISSUE TITLE
Cannot start deamon on ubuntu

### ISSUE THREAD

**Issue by jQrgen** [mysteriumnetwork/node#816]
Hey

I get the following error message when trying to start a deamon from cli on ubuntu after installing with .deb package.

```
$ myst daemon
2019-03-24T19:19:31.606483249 [Info] Starting Mysterium Node (source.dev-build)
stat /usr/bin/config: no such file or directory
```

**Comment by zolia** [comment]
please try ubuntu installation with our recent release 0.15.1
install using this command: 

> sudo -E bash -c "$(curl -s https://raw.githubusercontent.com/mysteriumnetwork/node/master/install.sh)"
