### ISSUE TITLE
"Identity unlocking failed" after computer wake ups from sleep

### ISSUE THREAD

**Issue by mjankauskas** [mysteriumnetwork/node#825]
Leave app running,
put computer to sleep
When woken up shows an error

![Screen Shot 2019-03-27 at 09.34.02.png](https://images.zenhubusercontent.com/5c3b439554281239e265e8e9/686410a5-588a-4ef1-b1ab-cdb5db4d87b0)

**Comment by ignasbernotas** [comment]
Cannot replicate, tried closing the lid and putting to sleep for some time. Seems to work fine. Need to get the logs next time this happens:) Closing for now.
