### ISSUE TITLE
Clean sessions from storage when service is stopped

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#829]
*Problem:*
Now when Provider stops service, `GET /service-sessions` endpoint still returns previous sessions

Need:
- either implement `session.Instance.Status` to distinguish sessions from closed ones 
- either clear "current sessions" from `SessionStorage`
- also consider destroying session on Consumer side

**Comment by zolia** [comment]
On app we can see that after first connect it instantly sets counter to 4 and after disconnect it leaves at 3.
