### ISSUE TITLE
Node integration with LocationOracle

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#863]
- [x] Mock Tequilapi endpoint `/location` and `/connection/location`
- [x] Refactor CLI arg to have typed location providers in "--location.type"
- [x] Autodetect IP attributes from LocationOracle
- [x] Return IP attribytes in Tequilapi endpoints `/location` and `/connection/location`
- [x] Manual IP attributes configuration (can be done later)
- [x] Refactor CLI arg to have typed IP adapters in "--ip.type" (can be done later)
- [x] Stop using Ipify and migrate to LocationOracle (can be done later)

Node has several location detection providers:
```
--location.type         Location autodetect provider (builtin, mmdb, oracle) default: 'builtin'
--location.address   Address of specific location provider given in '--location.type' e.g. https://testnet-location.mysterium.network/location for --location.type=oracle provider

# Possibility from local binary database of GeoLite2 format e.g. http://dev.maxmind.com/geoip/geoip2/geolite2/
# would suggest localdb, we could eventually modify maxmind db with our own data.
--location.type=localdb

# Possibility to identity IP from Oracle
--location.type=oracle
--location.address="https://testnet-location.mysterium.network/location"

# Possible to have manual provider also:
--location.type=manual
--location.address=""
--location.country="LT"
--location.city="Vilnius"
--location.user_type="datacenter"
```

Node has several IP detection providers:
```
--ip.type         IP autodetect provider (ipify, oracle) default: 'ipify'
--ip.address   Address of specific IP provider given in --ip.type e.g. https://testnet-location.mysterium.network/ip for --ip.type=oracle provider e.g. https://api.ipify.org/ will be used for --ip.type=ipify

# Possibility to identity IP from Oracle
--ip.type=ipify
--ip.address="https://api.ipify.org/"


# Possibility to identity IP from Oracle
--ip.type=oracle
--ip.address="https://testnet-location.mysterium.network/ip"
```

**Comment by zolia** [comment]
@soffokl can you check checkbox'es if they are done with your PR?

**Comment by soffokl** [comment]
@zolia done, checked all of them since it covered.

**Comment by Waldz** [comment]
Moving here from LocationOracle ticket https://github.com/mysteriumnetwork/location-oracle/issues/2

Left overs:
- [ ] Node autodetects IP attributes same ways as "country" and adds to Proposal
- [ ] Implement "node_type" proposals filter in Discovery service (datacenter/residential/..)
- [ ] Implement "node_type" field in Dashboard service (datacenter/residential/...)

**Comment by vkuznecovas** [comment]
Reopening since we've got checkboxes to tick still...
