### ISSUE TITLE
 Provider sends metrics about NAT traversal local status

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#890]
As a Mysterium
We want to know of how many Providers fails to configure NAT traversal (node is not accessible)

Tasks:
- [x] Send metrics to ELK stack
- [x] Kibana dashboard

**Comment by donce** [comment]
![Screenshot 2019-04-26 at 12.04.22.png](https://images.zenhubusercontent.com/5ba247ee8c7b5425fc895855/92f730f1-3936-4949-84d7-fab1d992cfce)
