### ISSUE TITLE
Version dev builds

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#897]
It's hard to determine node version used from logs when all of them are `0.0.0-dev`. We should version dev builds with timestamp and git hash.

**Comment by tadovas** [comment]
It's already there. /healthcheck endpoint contains all data about version

**Comment by soffokl** [comment]
`myst -v` should work too.

**Comment by tadaskay** [comment]
Yeah, it does print 0.0.0-dev, not exact version

**Comment by soffokl** [comment]
`0.0.0-dev` is a binary from the master branch, there is no release. https://github.com/mysteriumnetwork/node/releases/tag/0.0.0-dev
```
Mysterium Node
  Version: 0.0.0-dev
  Build info: Branch: 0.0.0-dev. Build id: 4539. Commit: 418588165d0e6b3b20cda1e45e9c8864db14abda

```

Released versions include the correct version of the release. 
And both of them includes also commit ID and build number.

**Comment by tadaskay** [comment]
Correct, this ticket is about versioning dev builds so that it's possible to trace exact version from the logs. Not:

```
2019-04-20T14:00:45.466098 [Info] Starting Mysterium Node (0.0.0-dev)
```

But for instance:

```
2019-04-20T14:00:45.466098 [Info] Starting Mysterium Node (0.9.0-dev-20190402-418588165)
```

Where `0.9.0` is the last release version, `dev` is an indicator this is a master branch build, followed by some kind of a timestamp and a git commit sha.

**Comment by soffokl** [comment]
If was fixed in the https://github.com/mysteriumnetwork/node/pull/1022

**Comment by tadaskay** [comment]
It partially fixes the issue, I think we should still version the builds properly and move releases to another repo (e.g. `node-dev-builds`)
