### ISSUE TITLE
Fix syntax error in Dockerfile

### ISSUE THREAD

**Issue by zyfdegh** [MysteriumNetwork/node#9]
When I clone this repo and execute

```sh
docker-compose build
```

Output

```sh
Building mysterium-node
ERROR: Dockerfile parse error line 11: Unknown instruction: &&
```

So in file `Dockerfile-mysterium-node` and `Dockerfile-mysterium-client`， there are syntax mistakes.

I'll put a PR to fix this.

**Comment by Waldz** [comment]
Currently Docker files was just a draft.
I did not managed to launch because it lacks `/dev/tun` devices.

We are testing/bugfixing on real Debian machines. If community finds how to launch `mysterium-server` on Docker it helps to start supporting more different OSes

**Comment by Waldz** [comment]
A fix from community member: https://github.com/MysteriumNetwork/node/pull/12

**Comment by Waldz** [comment]
https://hub.docker.com/r/mysteriumnetwork/mysterium-node/

```
$ docker run --cap-add MKNOD --cap-add NET_ADMIN -p "1194:1194" -e "NODE=123456" --name mysterium-node -d mysteriumnetwork/mysterium-node:latest
$ docker logs -f mysterium-node
```
