### ISSUE TITLE
Possible error: failed to send request '157f9cf0-edea-4ba2-a0b4-51ed3717738b.session-create'. nats: timeout

### ISSUE THREAD

**Issue by Waldz** [mysteriumnetwork/node#912]
*Way to reproduce:*
- Start Provider with NAT hole punching experiment enabled
- Find different desktop|mobile machine, and try to connect to Provider
- Check Provider logs during connection - connection fails (probably broker messages are racing???)

Expected behaviour:
- After connecting connection should be successful, if NAT hole punching is done

Search for line `[Error] [Tequilapi.Client] server response invalid: 500 Internal Server Error (http://myst-consumer:4050/connection). Possible error: failed to send request '157f9cf0-edea-4ba2-a0b4-51ed3717738b.session-create'. nats: timeout` in 
debug logs https://travis-ci.com/mysteriumnetwork/node/jobs/195591618

**Comment by vkuznecovas** [comment]
This problem is already solved. Not sure which commit fixed it, but there was an issue where nat pinger would block forever on `waitForPreviousStageResult` which caused the consumer to timeout on waiting for response via nats as the provider was not responding.
