### ISSUE TITLE
Promo banner for bounty program

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#929]

**Comment by mjankauskas** [comment]
<img width="552" alt="Screen Shot 2019-05-08 at 11 08 57" src="https://user-images.githubusercontent.com/46646357/57359993-c917a280-7181-11e9-9975-9036c033844a.png">
@AndriusMyst please add the link of the form here

**Comment by AndriusMyst** [comment]
@mjankauskas link to the form:
https://mysteriumnetwork.typeform.com/to/Y0D7a5

**Comment by mjankauskas** [comment]
done
