### ISSUE TITLE
Sign dVPN application with GPG keys (Apple, Microsoft)

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#930]

**Comment by mjankauskas** [comment]
@Germuxas made firs analysis, but it need an engineer to implement the changes. @Germuxas please comment

**Comment by Germuxas** [comment]
So what I have done, using the tools provided for Windows, and now investigating MacOS, there was a possibility to build certificates with tools, but after @ignasbernotas had a look, those applications made a certificate only for a work computer, not for a package to add to the system. 

With further investigation, this is out of my hands, as there is a need to add features to the code, that our app would be read, by Microsoft and Apple, so I have no ability to investigate and add any of the code implementations. This tasks will be passed to one of the developers.

**Comment by Germuxas** [comment]
Whoever will help with this issue, please update me - what is happening with it, and if you will need any of signing or any other help, just ping me.

**Comment by chompomonim** [comment]
Duplicate with #2129
