### ISSUE TITLE
Download mobile node dependency:  ./util_scripts/download-node. No such file

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#932]
Readme says:
Download mobile node dependency:
./util_scripts/download-node

Unfortunately, there's no such file in the repo.

**Comment by soffokl** [comment]
@cvl What readme you are referencing here? We need to fix it, but I cannot find it.

**Comment by Waldz** [comment]
Documentation was stale in repo https://github.com/mysteriumnetwork/mysterium-vpn-mobile
Was fixed in https://github.com/mysteriumnetwork/mysterium-vpn-mobile/pull/163/files#diff-04c6e90faac2675aa89e2176d2eec7d8
