### ISSUE TITLE
Uncouple dashboard from database

### ISSUE THREAD

**Issue by donce** [mysteriumnetwork/node#944]
API and dashboard are strongly coupled, both depends on DB. By decoupling Dashboard from DB (and using API for statistics instead), we can then finally split 2 services and allow API to handle DB.

- [x] Add a python module for dashboard-related queries in `api` (don't use db models directly from dashboard)
- [ ] Convert python module to REST API
- [ ] Split `dashboard` from `api`

**Comment by chompomonim** [comment]
Will be fixed after advanced discovery implemented. Closing as it is kind of duplicate.
