### ISSUE TITLE
Application freezes in starting mode when starting provider while connecting to WIFI

### ISSUE THREAD

**Issue by donce** [mysteriumnetwork/node#960]
Steps to reproduce:
- Connect to wifi
- Open application
- Open "Run service" tab
- Select another wifi network and start connecting to it
- Immediately press "Start service" in application while wifi is still connecting. Might need to press multiple times, until application gets stuck in "Connecting" stage

It can become stuck in 2 different ways:

<img width="646" alt="Screenshot 2019-04-29 at 13 23 10" src="https://user-images.githubusercontent.com/1409983/56890382-f6799780-6a81-11e9-9043-357e4b8859c5.png">
<img width="655" alt="Screen Shot 2019-04-29 at 11 47 46" src="https://user-images.githubusercontent.com/1409983/56890415-07c2a400-6a82-11e9-8b9a-d1b99eaabc22.png">

**Comment by ignasbernotas** [comment]
Fixed with #1019
