### ISSUE TITLE
yarn install throws error on windows 10 on mysterium-vpn module

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#961]
yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-plugin-vue@4.7.1" has incorrect peer dependency "eslint@^3.18.0 || ^4.0.0".
[4/4] Building fresh packages...
[1/4] ⠂ mysterium-client-bin
[2/4] ⠂ electron
[3/4] ⠂ node-sass
error C:\Users\zz\Desktop\dev\mysterium-vpn\node_modules\mysterium-client-bin: Command failed.
Exit code: 1
Command: .\download-mysterium-client
Arguments:
Directory: C:\Users\zz\Desktop\dev\mysterium-vpn\node_modules\mysterium-client-bin
Output:

**Comment by chompomonim** [comment]
Is this issue still valid after https://github.com/mysteriumnetwork/mysterium-client-npm-package/pull/10 done?

@cvl could you check with newest yarn and newest changes in our repo?

**Comment by cvl** [comment]
Yes, the issue persists.
I believe this is a https://github.com/mysteriumnetwork/mysterium-vpn problem (not node).
https://github.com/mysteriumnetwork/mysterium-vpn doesn't have issues bar though.

**Comment by cvl** [comment]
Similarly for Mac:
yarn download:bins:osx

yarn run v1.22.0
$ util_scripts/download-osx-binaries.sh && yarn download-mysterium-client darwin ./bin
curl is /usr/bin/curl
grep is /usr/bin/grep
sed is /usr/bin/sed
tr is /usr/bin/tr
Downloading asset...
######################################################################################################### 100.0%curl: Saved to filename 'openvpn_osx64'

util_scripts/git-asset-dl.sh done.
error Command "download-mysterium-client" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by chompomonim** [comment]
Won't be fixed. We're working on new desktop app.
