### ISSUE TITLE
Add testers node ids to whitelist

### ISSUE THREAD

**Issue by mjankauskas** [mysteriumnetwork/node#962]
Add these node IDs to mysterium whitelist:

Mindaugas - 0x7617cab56d49facd4300a36ba2ca5382dacd5a8f
Germantas - 0x7a7c7f403e6ee98fd3d8ec96bcf40ba303eed02a
Andrius - 0xdd57187372b9d56477f7f6b77fc1df5088ae3aed

**Comment by mjankauskas** [comment]
@Waldz is this still relevant?

**Comment by Waldz** [comment]
Yes, now proposals have local filters, so it's possible to filter by identities in ACL rules

**Comment by eugenegoncharuk** [comment]
A newer version of the Desktop App has been released on May 2020. No relevant anymore.
