### ISSUE TITLE
Show IP attributes (country and type) before starting service

### ISSUE THREAD

**Issue by mjankauskas** [mysteriumnetwork/node#969]
As a Provider
I would like to have confirmation that my IP is residential IP (or datacenter IP)
As this tells me if I'm eligible to receive income (bounty) from Mysterium

App has to have this data before starting the service ![0457aab7-ad13-4d4a-84eb-54152299f43b (1).png](https://images.zenhubusercontent.com/5c3b439554281239e265e8e9/95390504-ad88-4465-ba79-0a0c2dff7843)

**Comment by eugene-aheads** [comment]
The newer Desktop App has been released on May 2020. So closing it as not relevant anymore.
