### ISSUE TITLE
DNS Leak Question

### ISSUE THREAD

**Issue by idunno101** [mysteriumnetwork/node#988]
I performed a packet capture using Wireshark to test the connection of the vpn (Windows 10, VPN 0.6.0). I noticed that the DNS queries seemed to be leaking since I was able to see and follow the addresses of the websites that I was visiting during the capture. 
I did the same test using Nordvpn and was not able to see the addresses of the websites as the whole connection was unreadable. 
I'm not sure if what I saw was actually an issue but just bringing it up in case it is a problem that isn't being worked on.

![screenshot 84](https://user-images.githubusercontent.com/29008730/52166217-658c5d80-26d8-11e9-81b2-338e8b7a0a18.png)
![screenshot 85](https://user-images.githubusercontent.com/29008730/52166219-6b823e80-26d8-11e9-950a-1f6bbc8f5472.png)

**Comment by chompomonim** [comment]
We have new desktop app so this problem most probably is already solved long time ago. Also there is new DNS leak related issue we're solving right now (#3135).
