### ISSUE TITLE
Windows 10 with mysterium-vpn 0.4.0 cannot access Google/Youtube site, however can access Microsoft website.

### ISSUE THREAD

**Issue by tonyxia2016** [mysteriumnetwork/node#993]
Windows 10 with mysterium-vpn 0.4.0 cannot access Google/Youtube site, however can access Microsoft website.

On the Mac with  mysterium-vpn 0.4.0, all the web sites are accessible.

This issue was there with older mysterium-vpn version on Windows 10.

**Comment by chompomonim** [comment]
@tadaskay is this issue still relevant with our newest Windows app?
